### ISSUE TITLE
WiX Toolset website has "old" link to "how to build WiX"

### ISSUE THREAD

**Issue by steveOgilvie** [wixtoolset/issues#5130]

**Comment by steveOgilvie** [comment]
If you go to the WiX Toolset website: 

 http://wixtoolset.org/development/building-wix/
by clicking on the Development Hyperlink on top of website, then in Coding area, click on hyperlink "build WiX"

it should go to the Updated link: http://wixtoolset.org/documentation/manual/v3/wixdev/building_wix.html

**Comment by barnson** [comment]
http://wixtoolset.org/development/building-wix/ is the new page; we removed the older page from the .chm and point there instead.

**Comment by steveOgilvie** [comment]
Classification: Public

Awesome, thank you

Sent by my BlackBerry DTEK60...

This message has been marked as Public by TITUS Mail on Feb 12, 2017 20:15:21 PM.

The above classification labels were added to the message by TITUS Mobile.
Visit www.titus.com for more information.

________________________________
