### ISSUE TITLE
Installer for WiX Toolset doesn't work.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [wixtoolset/issues#5131]
The installer found [here](https://wix.codeplex.com/downloads/get/1504734) fails on Windows 7 with no error message except "Failed. Try again?" Absolutely no diagnostic information is displayed anywhere. It makes me wonder why the installer for WiX isn't an MSI, given that WiX is a tool to generate MSIs.

I hope your compiler tells me more than "Compilation failed" when I have a syntax error.

I'll just be over there, installing from the ZIP archive. ----->

**Comment by jchoover** [comment]
It's nearing Christmas, so I will leave you with a parting gift.  Look in
%TEMP% for your log files.  WiX is installed as a bundle of several MSI's,
and there is a verbose log file for each in %TEMP%.  (I know WixStdBA shows
an error page with a link to the logs, not sure on the WixBA.)
