### ISSUE TITLE
32/64 bit flag is ignored in some case in regutil.cpp

### ISSUE THREAD

**Issue by nbelyh** [wixtoolset/issues#5132]
I'm writing WIX extension using WIX sdk, and using regutil.cpp (note it's also used internally in wix, so maybe this can cause some issues).

If you specify that key should be deleted from 64-bit hive here, it will not be the case because first check will be false (see the link below):

https://github.com/wixtoolset/wix3/blob/develop/src/libs/dutil/regutil.cpp#L205

The check for the 32/64 bit, which follws later, should probably be at the very begining of the function, and the 'sam' parameter for the RegOpen() should include 32/64 options... Otherwise it gets completely ignored, and the function does not work if you specify non-default bitness (does not delete the key, because it's in the other hive).

**Comment by BMurri** [comment]
Pull requests:

[wix4](https://github.com/wixtoolset/wix4/pull/181)
[wix3](https://github.com/wixtoolset/wix3/pull/326)

I verified in both wix3 and wix4 codebases that every single invocation of RegDelete() used REG_KEY_DEFAULT, so there should be no impact to the toolset's own usage.
