### ISSUE TITLE
WiX 4.0 Visual Studio 2015 build missing WiX variables in candle.exe command line

### ISSUE THREAD

**Issue by JurekM** [wixtoolset/issues#5170]
When building WiX 4.0 inside Visual Studio 2015 candle.exe is started with all variables missing from the command line if the project has no dependencies. Adding any dependency works around this issue - all variables are back. This worked in VS2012/WiX 3.8. 100% repro.

No references in WiX project:

C:\Program Files (x86)\WiX Toolset v4.0\bin\candle.exe -out obj\Release\ -arch x64 ExampleLibUpdaterSetup.wxs

After adding a reference to an unrelated project ExampleWeb:

C:\Program Files (x86)\WiX Toolset v4.0\bin\candle.exe -out obj\Release\ -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\" -dSolutionDir=C:\Projects\MyStuff\ -dSolutionExt=.sln -dSolutionFileName=Example.sln -dSolutionName=Example -dSolutionPath=C:\Projects\MyStuff\Example.sln -dConfiguration=Release -dOutDir=...._Release\ -dPlatform=x64 -dProjectDir=C:\Projects\MyStuff\Server\WIX_LibUpdaterSetup\ -dProjectExt=.wixproj -dProjectFileName=WIX_LibUpdaterSetup.wixproj -dProjectName=WIX_LibUpdaterSetup -dProjectPath=C:\Projects\MyStuff\Server\WIX_LibUpdaterSetup\WIX_LibUpdaterSetup.wixproj -dTargetDir=C:\Projects\MyStuff_Release\ -dTargetExt=.msi -dTargetFileName=ExampleLibUpdaterSetup.msi -dTargetName=ExampleLibUpdaterSetup -dTargetPath=C:\Projects\MyStuff_Release\ExampleLibUpdaterSetup.msi -dExampleWeb.Configuration=Release -d"ExampleWeb.FullConfiguration=Release|x64" -dExampleWeb.Platform=x64 -dExampleWeb.ProjectDir=C:\Projects\MyStuff\Server\ExampleWeb\ -dExampleWeb.ProjectExt=.csproj -dExampleWeb.ProjectFileName=ExampleWeb.csproj -dExampleWeb.ProjectName=ExampleWeb -dExampleWeb.ProjectPath=C:\Projects\MyStuff\Server\ExampleWeb\ExampleWeb.csproj -dExampleWeb.TargetDir=C:\Projects\MyStuff\Server\ExampleWeb\bin\ -dExampleWeb.TargetExt=.dll -dExampleWeb.TargetFileName=ExampleWeb.dll -dExampleWeb.TargetName=ExampleWeb -dExampleWeb.TargetPath=C:\Projects\MyStuff\Server\ExampleWeb\bin\ExampleWeb.dll -arch x64 ExampleLibUpdaterSetup.wxs

**Comment by robmen** [comment]
Fixed by wixtoolset/wix4#60
