### ISSUE TITLE
WiX Toolset v3.10.1 : light.exe compilation error

### ISSUE THREAD

**Issue by switmac** [wixtoolset/issues#5172]
So I installed WiX Toolset v3.10.1 in my unit.
When I run the command, `light.exe SampleFirst.wixobj`
I get this error message,
**light.exe : error LGHT0350 : The package being validated requires a higher version of Windows Installer than is installed on this machine. Validation cannot continue.**

Is this a Wix Toolset Error or my environment setup error or something else?
Please let me know.

Best Regards!
Thank you. :)

**Comment by switmac** [comment]
I found out the cause for this error is in the tag Package attribute InstallerVersion whose value must be 100. My bad.

**Comment by Teomazivila** [comment]
Hi Switmac,
Thanks a lot for your feedback. I had the same issue just now nad your observation helped me as well. Thanks
