### ISSUE TITLE
New website not as clear

### ISSUE THREAD

**Issue by peterhull90** [wixtoolset/issues#5173]
(apologies if this is not the right place to report this)
I notice on the new website the detailed element descriptions contain tables with the attributes and descriptions. There is no gap or line between rows and, because the attribute name is centred, I find it's not easy to read across to the corresponding description. 

See example from http://wixtoolset.org/documentation/manual/v3/xsd/wix/msupackage.html

![doc](https://cloud.githubusercontent.com/assets/376711/12111732/803444b4-b38f-11e5-8967-52778d204ced.jpg)

**Comment by robmen** [comment]
@peterhull90 this is exactly the correct place to report issues, thank you. And you're very right that the existing style is very difficult to read. If/when my pull request is approved, the site should be drastically improved after 5-10 minutes.
