### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by adamskrodzkicgi** [wixtoolset/issues#5180]
During installation as an administrator I get following error 

Product: WiX Toolset v3.10 Core -- Error 1310. Error writing to file: C:\Program Files (x86)\WiX Toolset v3.10\bin\torch.exe.  System error 0.  Verify that you have access to that directory.

Windows 7 Enterprise Service Pack 1

  - Provider 

   [ Name]  MsiInstaller 
 
  - EventID 11310 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 0 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2016-01-12T12:04:06.000000000Z 
 
   EventRecordID 12570 
 
   Channel Application 
 
 

- EventData 

   Product: WiX Toolset v3.10 Core -- Error 1310. Error writing to file: C:\Program Files (x86)\WiX Toolset v3.10\bin\torch.exe. System error 0. Verify that you have access to that directory. 
   (NULL) 
   (NULL) 
   (NULL) 
   (NULL) 
   (NULL) 
    
   7B39343837464137352D314146452D344135442D394643362D3234434346434332413431337D 

--------------------------------------------------------------------------------

Binary data:

In Words

0000: 3834397B 37414637 41312D35 342D4546 
0008: 2D443541 36434639 4334322D 43434643 
0010: 31344132 7D33   

In Bytes

0000: 7B 39 34 38 37 46 41 37   {9487FA7
0008: 35 2D 31 41 46 45 2D 34   5-1AFE-4
0010: 41 35 44 2D 39 46 43 36   A5D-9FC6
0018: 2D 32 34 43 43 46 43 43   -24CCFCC
0020: 32 41 34 31 33 7D         2A413}

**Comment by barnson** [comment]
Can you attach a verbose log showing the problem? It should have more detail that will help.

**Comment by barnson** [comment]
Please reopen if you can supply more details.

**Comment by adamskrodzkicgi** [comment]
whit what parameters should I run installer to create verbose log?

**Comment by jchoover** [comment]
No parameters needed, look in %temp% for a wix*.log
