### ISSUE TITLE
Cannot successfully escape InstallCommand variables with space in them

### ISSUE THREAD

**Issue by Molnigt** [wixtoolset/issues#5181]
I found this issue describing the same thing but the solution doesn't work with my version.
https://github.com/wixtoolset/issues/issues/4257
`ExeCommand='"[INSTALLDIR]&quot; "[INSTALLDIR]&quot;' Return='asyncWait'`

I run Burn v3.10.1.2213, on Windows v6.1 (Build 7601: Service Pack 1)

I need to pass the installation directory to a cmd but when [WixBundleOriginalSourceFolder] contains a space I get `0x80070001 Incorrect Function` when running. 
Running directory is `"c:\@Work\Wix bug\"`

I've tried several ways but they all fail.
`InstallCommand="[TOKEN] [FQDN] &quot;[InstallFolder]&quot; [MAIL] [Installer] > [TempFolder]Test.[WixBundleFileVersion].log"`
`InstallCommand='[TOKEN] [FQDN] &quot;[InstallFolder]&quot; [MAIL] [Installer] > [TempFolder]Test.[WixBundleFileVersion].log'`
`InstallCommand='[TOKEN] [FQDN] "[InstallFolder]&quot; [MAIL] "[Installer]&quot; > [TempFolder]Test.[WixBundleFileVersion].log'`

It looks ok in the logfile,
`\ProgramData\Package Cache\30DA83AAED7100029B08D21E94CB9D28AE73B68E\runme.cmd" ***** no.domain.com "c:\@Work\Wix bug\" no@mail.com c:\@Work\Wix bug\test.exe > C:\Users\J~1.M\AppData\Local\Temp`
But all variants gives the same error,
```
[57E0:67D0][2016-01-12T14:26:37]e000: Error 0x80070001: Process returned error: 0x1
[57E0:67D0][2016-01-12T14:26:37]e000: Error 0x80070001: Failed to execute EXE package.
[7500:5994][2016-01-12T14:26:37]e000: Error 0x80070001: Failed to configure per-machine EXE package.
[7500:5994][2016-01-12T14:26:37]i319: Applied execute package: RunBatch, result: 0x80070001, restart: None
```

This is my version with the https://github.com/wixtoolset/issues/issues/4257 syntax.
```
<?xml version="1.0" encoding="utf-8"?>
<?ifndef Version?> 
	<?define VERSION = "2.1.0" ?> 
	<?define UPGRADECODE = "A5586EE0-0713-7220-A193-8E4E6ADE27C7" ?> 
<?endif ?> 

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
	xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"
	xmlns:util="http://schemas.microsoft.com/wix/UtilExtension" >

  <Bundle Name="Test" Version="$(var.VERSION)" Manufacturer="Foo Bar AB" UpgradeCode="$(var.UPGRADECODE)">

	<Variable Name="TOKEN" Hidden="yes" bal:Overridable="yes"/>
	<Variable Name="FQDN" bal:Overridable="yes"/>
	<Variable Name="MAIL" bal:Overridable="yes"/>
	
  <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkLicense">

		<bal:WixStandardBootstrapperApplication
			SuppressOptionsUI="yes"
			xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"
			LicenseUrl=""
			ThemeFile=".\res/ClassicTheme.xml"
			LocalizationFile=".\res/ClassicTheme.wxl"
		/>

	</BootstrapperApplicationRef>
	
	<Variable Name="InstallFolder" Type="string" Value="[WixBundleOriginalSourceFolder]" />	
	<Variable Name="Installer" Type="string" Value="[WixBundleOriginalSource]" />	
	
	<Chain>
			<ExePackage Id="RunBatch" DisplayName="Creating new node through RestInTSM API..."
				SourceFile="./runme.cmd"
				InstallCommand='[TOKEN] [FQDN] "[InstallFolder]&quot; [MAIL] "[Installer]&quot; > [TempFolder]Test.[WixBundleFileVersion].log'
				InstallCondition="TOKEN"
			/>
			
	</Chain> 
  </Bundle>
</Wix>
```
Is there any other way to do this?

**Comment by Molnigt** [comment]
What do you mean? Ofcourse cmd.exe interpretes the cmd. I don't have any issue with the cmd itself, only variables passed to it. And this do actually work just fine when no space in path. Please reopen.

**Comment by rseanhall** [comment]
FYI, `"c:\@Work\Wix bug\"` has a backslash before the double quote which means that double quote is not taking care of the space.  You need to make it `"c:\@Work\Wix bug\\"`.  It's not a WiX bug, especially since Burn doesn't support batch files.

**Comment by Molnigt** [comment]
ok, to take the batch file out of the discussion I use an exe instead. It is still the same problem.
`[7610:6DE4][2016-01-12T15:58:06]i301: Applying execute package: RunBatch, action: Install, path: C:\ProgramData\Package Cache\1BD367DC7D1483671877188682C35FD5C7E53A34\messagebox.exe, arguments: '"C:\ProgramData\Package Cache\1BD367DC7D1483671877188682C35FD5C7E53A34\messagebox.exe" "c:\@Work\Wix bug\" TOKEN'` sends `c:\@Work\Wix bug\" TOKEN` to the exe. Without the first qoute.

**Comment by robmen** [comment]
Correct. The open quote starts eating whitespaces and the backslash after the word `bug` escapes its quote giving you the string `c:\@Work\Wix bug\" TOKEN`. The command line processor doesn't complain that it can't find a closing quote.

To fix, you can pick one of two options:

1. Escape the troublesome backslash as @rseanhall proposed, like: `"c:\@Work\Wix bug\\" TOKEN`
2. Avoid the escape sequence by providing the folder name via its dot notation, like: `"c:\@Work\Wix bug\." TOKEN`

    Note: Some programs don't like referencing a folder via its dot notation, so this option may not work with your executable.

**Comment by tanworks-dev** [comment]
The following code works fine on my system: 
InstallCommand='/q InstallFolder="[InstallFolder]"'
