### ISSUE TITLE
Loose file support in Burn?

### ISSUE THREAD

**Issue by jason109** [wixtoolset/issues#5182]
We have MSI's that contain loose files.  The loose files need to be modified after the MSI's are created.  Burn fails to successfully install loose files if they have been modified.  The install will fail and the log indicates that there was a hash mismatch error.
We also have one MSI itself that is uncompressed.  It too needs to be modified after burn has created the setup exe.
The primary use case for this need is that certain files like help files, release notes, etc., are not complete until after the install has been built and tested.

I found the following from sourceforge.  It is dated from 2012 and specifies the same problem.  I could not find this reported anywhere else.
http://sourceforge.net/p/wix/mailman/wix-users/thread/CAHdHTVf8ozC8QzQm0G8hTB=BPXkWGS6qAN_PQhwjrToVn=b=_g@mail.gmail.com/

Error when replacing an entire 'loose' MSI:
2016-01-12T09:50:22]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\myInstaller.msi
[0F04:11A8][2016-01-12T09:50:22]e000: Error 0x80091007: Failed to verify hash of payload: myInstaller.msi

Error when an MSI contains a loose file:
[16D0:04C0][2016-01-12T10:47:54]e000: Error 0x80091007: Hash mismatch for path: C:\ProgramData\Package Cache\.unverified\MsiHelpFilePayloadId
[16D0:04C0][2016-01-12T10:47:54]e000: Error 0x80091007: Failed to verify hash of payload: MsiHelpFilePayloadId
[16D0:04C0][2016-01-12T10:47:54]e310: Failed to verify payload: MsiHelpFilePayloadId at path: C:\ProgramData\Package Cache\.unverified\MsiHelpFilePayloadId, error: 0x80091007. Deleting file.
[16D0:04C0][2016-01-12T10:47:54]e000: Error 0x80091007: Failed to cache payload: MsiHelpFilePayloadId

Is this a feature that can be added to burn?  Our previous install app created via InstallShield supported this use case.

**Comment by robmen** [comment]
I believe I misread the original email in the linked thread. I was noting that loose files are absolutely supported by Burn. What is not supported is modifying those files outside of the bundle. This is a security feature to ensure installation files are not tampered with in transit.

It isn't possible to tell the difference between valid modifications made during a build process and malicious changes made by an attacker.

**Comment by jason109** [comment]
I realize this could be a security issue.  However, would you be willing to add a feature such that the hash/security check could be turned off?  Obviously the default would be to apply the security check.  Our primary reason for needing this is to update help files (.chm), release notes (.pdf), etc. that are finalized after a build has been validated.

Thoughts?

**Comment by varun7447** [comment]
Wix 3.10.2 support Loose file install? The loose file install is working fine with setup project msi. When the same setup project when bundled with other exe the loose files are not copied to the install folder. Is there anything that we need specify in burn msi package element?

**Comment by robmen** [comment]
@jason109 no. It'd be better to update the bundle post build. That feature doesn't exist either but would be more acceptable than opening a security vulnerability mechanism.

@varun7447  You can always add `Payload` elements for those files that are not automatically detected by light.exe as needed.

**Comment by varun7447** [comment]
Thanks for the response. I am actually trying to see if i need to compile these loose files as part of Burn? Can i use wildcard file name like *.txt in payload?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by varun7447** [comment]
Thanks Rob. I have asked my question and support for loose file install with Burn.
