### ISSUE TITLE
Problem with VS2013 and WiX 3.8

### ISSUE THREAD

**Issue by martingraef** [wixtoolset/issues#5190]
I see a problem with the environment based on VS2013 and WiX 3.8
I've started with VS2010 and WiX 3.5 and I was able to install the product on every Windows platform without any problems. The next step was to build the same project using VS2013 however WiX 3.5 cannot be used and the recommendation is to use WiX 3.8.
When running the installer I see the following error:
Action start 16:35:10: CostFinalize.
Error 1606. Could not access network location  .

The only change I made in the WXS file was to replace the construction:
           Action="create" />
with
           ForceCreateOnInstall="yes" ForceDeleteOnUninstall="yes" />
in the sections where registry entries were made, based on the error messages during the build process.
Other than that the WXS file is identical.
Would you please be able to provide some explanation or suggestions how to fix this problem?
I do appreciate your help and time.
Best regards,
Martin Graef

**Comment by barnson** [comment]
Please send more details about your authoring and log to wix-users for support.
