### ISSUE TITLE
3.10.2 will not install on latest Windows 10 

### ISSUE THREAD

**Issue by rykr** [wixtoolset/issues#5191]
Is there a log I can look at to see why it's failing?

**Comment by robmen** [comment]
Yes, look in your Temp folder. The WiX log should be obvious. Please attach the log file here as well so we can help evaluate the issue.

**Comment by rykr** [comment]
Here are the two log files.  I see the errors but not what is causing them.

[Logs.zip](https://github.com/wixtoolset/issues/files/107272/Logs.zip)

**Comment by JohnLudlow** [comment]
`MSI (c) (94:F8) [14:35:16:163]: Failed to grab execution mutex. System error 258.`

Looks like another MSI transaction is running. Are you running another install in the background? Perhaps Windows Update is still running some updates?

**Comment by rykr** [comment]
Yes, sorry for the false alarm.  I didn't know it but there was an open install transaction.  Once I rebooted it successfully ran but gave a couple of dialogs about unable to find some source and restore wouldn't be possible.  But it successfully installed and seems to work.  *shrug*

Thanks!
