### ISSUE TITLE
The file element contains an unexpected attribute 'source'

### ISSUE THREAD

**Issue by AntBPTS** [wixtoolset/issues#5192]
I'm using WiX Edit to package an application with runtime embedded from Flash CC. My project has 2 files included when packaging and it seems WiX Edit has taken a misliking to these being included. the error message I get is as follows:

error CNDL0004 : The file element contains an unexpected attribute 'source'

This error appears twice (lines 10 and 13) which are the lines I set the source for the files.

Any ideas?

**Comment by barnson** [comment]
The attribute is `Source` with an uppercase `S`.
