### ISSUE TITLE
Files that are marked permanent fail to get updated if they have been touched while installed.

### ISSUE THREAD

**Issue by TannerMoore** [wixtoolset/issues#5194]
I have found recently that a file on my system isn't updating if I touch it while it is installed. I am going to run through two scenarios since I think this is a hard problem to explain.

Scenario 1 - good

1. Install text file named "version.txt" which contains the string "version 1."
2. Run upgrade with new installer containing a modified "version.txt."
3. New text file named "version.txt replaces old text file and now contains the text "version 2."

Scenario 2 - bad

1. Install text file named "version.txt" which contains the string "version 1."
2. User edits "version.txt" and replaces text with "version 0."
3. Run upgrade with new installer containing a modified "version.txt."
4. Old, edited text file remains installed with the text "version 0" inside.

If this is not a bug, help me understand why this is intended behavior!

-Tanner

**Comment by robmen** [comment]
https://msdn.microsoft.com/en-us/library/aa368599%28v=vs.85%29.aspx
