### ISSUE TITLE
Uninstall using "Apps & Features" setting panel on Windows 10 required administrator privilege

### ISSUE THREAD

**Issue by fbruneteau** [wixtoolset/issues#5196]
Environment
- WiX 3.10.2
- Visual Studio 12.0

I create a MSI and include it in a Bootstrapper
to create an exe file with multi languages (package per user using "HKCU" property).

2 users on Windows 10:
- user1 (not administrator)
- admin (administrator privileges)

For each user, the package is installed in "C:\Users\${username}\AppData\local\${installed_directory}".

Failed scenario:
- 1. Log user1 and install : success
- 2. Log admin and install : success
- 3. Switch/log to user1.
- 4. Try to uninstall user1 package in "Apps & Features":
     - Popup asking administrator privileges (why ?)
     - Uninstall the admin package in "C:\Users\admin\AppData\local\${installed_directory}"
       instead of user1 package "C:\Users\user1\AppData\local\${installed_directory}"

Success scenarii:

Scenario 1:
* Step 1, 2 and 3
* Try to uninstall user1 package in "Programs and Features" from Control Panel: success

Scenario 2:
* Step 1, 2 and 3
* Try to uninstall user1 package using exe installer: success

Scenario 3:
* Log user1 and install using MSI installer without bootstrapper: success
* Try to uninstall MSI
     * In "Apps & Features": success
     * In "Programs and Features": success
     * Using MSI installer: success

What could in bootstrapper require to have administrator privileges  ?

Here is the file "Bundle.wxs":

```
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"  xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">

  <Bundle Name="$(ProductName)" Version="$(ProductVersion)" Manufacturer="$(Manufacturer)" UpgradeCode="$(UpgradeCode)">

    <WixVariable Id="WixStdbaThemeXml" Value="layout\layout.xml"/>

    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense">
        <bal:WixStandardBootstrapperApplication LogoFile="layout\Welcome.png" LicenseFile="resources\1033\licence.rtf" SuppressOptionsUI="yes" />

        <Payload Compressed="yes" Id="thm-de-DE" Name="1031\thm.wxl" SourceFile="resources\1031\thm.wxl" />
        <Payload Compressed="yes" Id="thm-en-US" Name="1033\thm.wxl" SourceFile="resources\1033\thm.wxl" />
        <Payload Compressed="yes" Id="thm-fr-FR" Name="1036\thm.wxl" SourceFile="resources\1036\thm.wxl" />
        <Payload Compressed="yes" Id="thm-nl-NL" Name="1043\thm.wxl" SourceFile="resources\1043\thm.wxl" />

        <Payload Compressed="yes" Id="lic-de-DE" Name="1031\license.rtf" SourceFile="resources\1031\licence.rtf" />
        <Payload Compressed="yes" Id="lic-en-US" Name="1033\license.rtf" SourceFile="resources\1033\licence.rtf" />
        <Payload Compressed="yes" Id="lic-fr-FR" Name="1036\license.rtf" SourceFile="resources\1036\licence.rtf" />
        <Payload Compressed="yes" Id="lic-nl-NL" Name="1043\license.rtf" SourceFile="resources\1043\licence.rtf" />
    </BootstrapperApplicationRef>

    <Chain>
      <MsiPackage DisplayInternalUI="no" Id="Setup" Compressed="yes" SourceFile="resources\release\$(MsiName)" Permanent="no" Vital="yes">
      </MsiPackage>

    </Chain>
  </Bundle>

</Wix>
```

**Comment by BMurri** [comment]
Two questions:
1) What value do you have set in your MSI's sources for Package/@InstallScope?
2) Did you ask about this on the wix-users list?

**Comment by fbruneteau** [comment]
1) I use 

```
<Package InstallerVersion="200" Compressed="yes" InstallScope="perUser" InstallPrivileges="limited" ReadOnly="yes" />

<Fragment>
    <Directory Id="TARGETDIR" Name="SourceDir">
        <Directory Id="LocalAppDataFolder">
            <Directory Id="INSTALLFOLDER" Name="Manufacturer">
                <Directory Id="APPFOLDER" Name="ProductName"/>
            </Directory>
        </Directory>
    </Directory>
</Fragment>
```

2) No.

**Comment by barnson** [comment]
Burn bundles are manifested to run `asInvoker` so they don't request early elevation even for per-machine bundles. As it works correctly everywhere else, it's pretty clearly an issue with the Windows 10 settings app.

**Comment by barnson** [comment]
You might see if you can file a bug on Windows as this is a behavior change there. You could also follow up on the wix-users list with logs to see if anyone has suggestions.
