### ISSUE TITLE
CAQuietExec in defered mode does not runs a 64 bit proccess

### ISSUE THREAD

**Issue by efraimN** [wixtoolset/issues#5197]
The defered mode opens a 32 bit server, (as can be seen in the logs). No 64 bit server.
Hello, I'm your 32bit Elevated custom action server

**Comment by barnson** [comment]
[64-bit versions are available.](http://wixtoolset.org/documentation/manual/v3/customactions/qtexec.html)

**Comment by efraimN** [comment]
But in DEFERED mode doesnt works. The priblem is the server procces user
for UAC elevation. Is 32 bits app. :-(

**Comment by barnson** [comment]
Please post the authoring you're using.

**Comment by barnson** [comment]
Please let us know if this is still a problem.
