### ISSUE TITLE
Pass Property value to msi from the Bootstrapper during uninstallation based on checkbox.

### ISSUE THREAD

**Issue by dllentry** [wixtoolset/issues#5203]
Pass value from Burn bootstrapper to msi during uninstallation process. The said value is that of a checkbox that is present in the Modify page of the bootstrapper that needs to be passed to a Custom Action in the msi which acts upon the value of the checkbox. Thanks.

**Comment by dllentry** [comment]
@robmen @barnson

**Comment by barnson** [comment]
Please send support requests to the wix-users mailing list.
