### ISSUE TITLE
Issue with running WiX UI (InstallDir/Minimal) in minimized mode.

### ISSUE THREAD

**Issue by TimMayert** [wixtoolset/issues#5204]
My Wix installer is using WiXUI_InstallDir for UI mode and runs fine in full UI mode, but I noticed that if the install is ran and you minimize it that it will finish with the Finish Dialog box appearing off the screen to the left side and only a tiny bit of the Finish dialog box is visible for you to drag back to the center of the screen.

I have tried this on Win 8.1 VM and Windows 10 physical box and it always occurs. I even tried WiXUI_Minimal and the same thing happens.

Has anyone seen this and if so is there a fix for this or something that I can do to work around this issue?

**Comment by barnson** [comment]
This is an MSI problem, not a WixUI problem. You can see it with non-WixUI MSIs. The MSI team would have to fix this.
