### ISSUE TITLE
The language of this installation package is not supported by your system	light.exe

### ISSUE THREAD

**Issue by ramaduraiu** [wixtoolset/issues#5206]
HI Team, I am using WIX toolset  for MSI package in Visual studio . While the application I am getting below error.
 "An unexpected Win32 exception with error code 0x657 occurred: The language of this installation package is not supported by your system	light.exe"

Please let me know how to resolve it. 

Thanks in advance

**Comment by barnson** [comment]
Please send support requests to the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/). Include pertinent details like the exact error message (with error code) and the language and codepage authoring.
