### ISSUE TITLE
Installing Wix 3.10 failed on Windows 7

### ISSUE THREAD

**Issue by ChriChri69** [wixtoolset/issues#5207]
After downloading Wix 3.10, the installation failed.
(in middle of the red bar)
see attached log file
It looks like it is trying to execute msi from : C:\ProgramData\Package Cache\{777FF883-221F-42B6-8A44-7FF1D0C7A06B}v3.10.2516\data\core.msi
but this folder is not existing ... and neither the core.msi
in "similar" folders, i only got msdk.msi and msdk1.cab

How can i install wix ?
[WiX Toolset_v3.10.2.2516_20160210183658.txt](https://github.com/wixtoolset/issues/files/125238/WiX.Toolset_v3.10.2.2516_20160210183658.txt)

**Comment by jchoover** [comment]
winerror.h 0x80070652
#defineERROR_INSTALL_ALREADY_RUNNING
Another installation is already in progress. Complete that installation
before proceeding with this install.

**Comment by ChriChri69** [comment]
Restarted computer.
Next try worked.
Thanks.
