### ISSUE TITLE
Burn ShowFilesInUse and Windows XP

### ISSUE THREAD

**Issue by ghost** [wixtoolset/issues#5208]
I have a simple bundle with one MSI package. The bundle uses the standard bootstrapper application. The attribute bal:WixStandardBootstrapperApplication/@ShowFilesInUse is set to "yes".

When the setup is run with my application running, the files-in-use dialog shows my app correctly, however, choosing "Close the applications and attempt to restart them." does nothing under XP. It does work on Windows 8.

Probably this is due to the fact that Restart Manager is not available under XP?

I would expect that either burn waits until the app is closed (e.g. retry), or the files-in-use dialog is not shown under XP.

WiX v3.10.2.2516
Visual Studio 2015

**Comment by creativbox** [comment]
Burn does currently not supply the enough information about files in use. The distinction between INSTALLMESSAGE_FILESINUSE and INSTALLMESSAGE_RMFILESINUSE (without/with restart manager) is lost when OnExecuteFilesInUse() is called. WixStdBa is therefore only implementing the restart manager functionality. 
This was discussed on the mailing list some time ago (2014?) and should be changed in Wix 4.
