### ISSUE TITLE
Variables/Constants seem to be sticky between executions of Light.exe

### ISSUE THREAD

**Issue by rabbers** [wixtoolset/issues#5209]
There appears to be an inconsistency in my project whereby Light.exe uses values for it's search folder that were calculated during a previous run.

In my project I have a Nant build script that invokes 32bit MSBuild to build a Wix Bootstrap project - Wix Bootstrap immediately builds WixMSI project, and that immediately builds and prepares my customactions.CA.dll.

My customactions.CA.dll can be seen in a Debug_x64 directory, which the WixMSI project correctly uses as the output folder.

When the build log gets down as far as a call to Light.exe, an error reports that it can't find Debug_**x86**/customactions.CA.dll.

I've spend ages looking at this, and decided to remove x86 build from my build script - the x64 version built, so I commented back in my x86 build.

Then during the x86 build, Light.exe reported that it can't find Debug_**x64**/customactions.CA.dll.

So essentially, when Light.exe successfully links something, it remembers the search path, and won't let it go.

I'm not sure if this is in the scope of the Nant process, the MSBuild Process, or Light.exe, but it's very wierd.

Mark

**Comment by barnson** [comment]
Please send support requests to the wix-users mailing list. You'll want to provide logs to show how everything's hooked together. Also, whether the behavior's the same if you take Nant out of the loop.
