### ISSUE TITLE
Web Documentation for WixNetFxExtension is mangled

### ISSUE THREAD

**Issue by NameOfTheDragon** [wixtoolset/issues#5210]
This page: http://wixtoolset.org/documentation/manual/v3/customactions/wixnetfxextension.html
is very broken and so are some pages that link to it, e,g, http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html

**Comment by barnson** [comment]
What's broken about http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html?

**Comment by NameOfTheDragon** [comment]
Under step 2 item 2, the link to the WixNetFxExtension page is mangled.

Best regards,
Tim Long

**Comment by moenasser** [comment]
Came here to say the same thing.

The .NET Versions page is a mess.

http://wixtoolset.org/documentation/manual/v3/customactions/wixnetfxextension.html

**Comment by robmen** [comment]
The root issue is that the tables in documentation are following afoul of the CommonMark spec section 4.6 namely:

> There are problems, however, if the inner tags are indented and separated by spaces, as then they will be interpreted as an indented code block:

There are many blank lines between the <tr> and <td> elements in the HTML doc pages. Those need to be removed to render properly under CommonMark.

Probably same issue for any doc pages with broken tables.

**Comment by cremor** [comment]
@barnson The link in step 2 point 2 on the page http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html is still broken.
