### ISSUE TITLE
heat not able to pick up  new files

### ISSUE THREAD

**Issue by wixuser123** [wixtoolset/issues#5211]
Using vs2015, .net 4.6.1, wix 3.10. 
Directory(Xmldir) which has 103 xml files. Run an executable file (yyy.exe)  which produces 200 xml files in Xmldir. Total of 303 xml files

heat cmd in prebuild event on  directory(Xmldir). I only see 103 files not 303 files.
Prebuild Commands as below:

$(SolutionDir)/yyy.exe 
(wait 6 seconds so that new 200 xml files are generated and run heat cmd)
C:\Program Files (x86)\WiX Toolset v3.10\bin\heat.exe" dir "C:\SourceCode\Xmldir" -template fragment  -dr  -cg XmlFiles -gg -scom -sreg gl -sfrag -srd -var  var.Xlmlfolder  -o "../Installer/Xmlfiles.wxs"

**Comment by barnson** [comment]
Please send support requests to the wix-users mailing list.
