### ISSUE TITLE
WiX 3.11.0.129 doesn't work with Visual Studio 2015

### ISSUE THREAD

**Issue by HB-2012** [wixtoolset/issues#5214]
During startup, Visual Studio reports that the package 'WiX Project Package' could not be loaded. This results in not being able to load any ".wixproj" projects. The ActivityLog.xml of Visual Studio reports the following:

`<entry>
<record>443</record>
<time>2016/02/17 12:58:15.809</time>
<type>Error</type>
<source>VisualStudio</source>
<description>CreateInstance failed for package [WiX Project Package][Could not load file or assembly &apos;file:///C:\Program Files (x86)\WiX Toolset v3.10\bin\votive2010.dll&apos; or one of its dependencies. The system cannot find the file specified.]:{   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)}</description>
    <guid>{E0EE8E7D-F498-459E-9E90-2B3D73124AD5}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.10\bin\votive2010.dll' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>`

Of which only the following is relevant, really:
`Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.10\bin\votive2010.dll' or one of its dependencies. The system cannot find the file specified.`

This is correct, because WiX installed to the following folder:
`C:\Program Files (x86)\WiX Toolset v3.11`

When you attempt to open any .wixproj in this state, the following error will occur in the Migration Report:
`ProjectFile.wixproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=628321&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD`

I'm running Windows 10 with the .NET 4.6.1 runtime libraries. I used Visual Studio 2015 Update 1 (v14.0.24720.00). The issue can not be reproduced using the latest stable release of WiX 3.10.

**Comment by rseanhall** [comment]
This was fixed by https://github.com/wixtoolset/wix3/pull/330, it will be in the next build.

**Comment by HB-2012** [comment]
Great. I didn't check the pull requests for a possible fix, only the list of issues. Sorry for that.

I guess the issue can be closed.

**Comment by richlander** [comment]
FYI: I updated the target of that link, above. Tell me if you want it pointing elsewhere.

http://go.microsoft.com/fwlink/?LinkId=628321&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD

**Comment by robmen** [comment]
Thanks, @richlander. Awesome.
