### ISSUE TITLE
4.0 Duplicate Symbol error when referencing WixUI_Minimal

### ISSUE THREAD

**Issue by seannerd** [wixtoolset/issues#5216]
In WiX 4.0 (4.0.3729.0), Adding `<UIRef Id="WixUI_Minimal" />` generates the error:

> Duplicate symbol 'WixAction:InstallUISequence/WelcomeEulaDlg' referenced by C:\build\work\1\s\src\ext\UIExtension\wixlib\WixUI_Minimal.wxs(60). This typically means that an Id is duplicated. Ensure all your identifiers of a given type (File, Component, Feature) are unique or use an access modifier to scope the identfier.    SetupPacketTest C:\build\work\1\s\src\ext\UIExtension\wixlib\WelcomeEulaDlg.wxs 54

Adding a UIRef to WiXUI_Advanced, WiXUI_FeatureTree, WiXUI_InstallDir or WiXUI_Mondo generates the error:

> '.', hexadecimal value 0x00, is an invalid character. SetupPacketTest light.exe   0

I'm using VS 2015 in Win 10 64 bit. 

Any suggestions would be great :)
- Sean

**Comment by barnson** [comment]
Which version of WiX?

**Comment by seannerd** [comment]
@barnson Sorry, it was in the title - and incomplete. I updated the post.

**Comment by swalexw** [comment]
Noticed this as well with 4.0.3826.0

**Comment by elioYakidoo** [comment]
I also have this issue whenever I add the WIXUI_Minimal I get the "Id is duplicated error"

and whenever I add the WIXUI_Mondo I also get the

'.', hexadecimal value 0x00, is an invalid character. SetupPacketTest light.exe 0

I wonder if there is an update on this fix.

**Comment by rkrgithub** [comment]
Use a stable version. It solved the issue for me.

**Comment by JuergenGutsch** [comment]
Is there a stable 4.0? can't find any ;)

**Comment by rkrgithub** [comment]
if 4.0 is not stable, then go with lover versions :-) ;-)

**Comment by JuergenGutsch** [comment]
thanks a lot, that helps ;) 4.0 has some nice new feature in it, that's why I asked ;)

**Comment by hulucc** [comment]
+1， exactly the same environment and same problem

**Comment by wyzerd** [comment]
Is 4.0 dead? I found this hoping for a solution in VS2017 project. The last release was over a year ago and the src hasn't been updated in 3 months?

**Comment by robmen** [comment]
WiX v4.0 is not dead. Last release was last month (http://wixtoolset.org/releases/weekly/). The source has not been updated in 3 months because WiX v3.11 took up all our cycles accommodating the VS2017 breaking changes.

We should be making more progress soon but, personally, after the big push to support VS2017, I've been taking a bit of a break.

**Comment by wyzerd** [comment]
Awesome, thanks for the quick response. I am struggling to learn this and didn't want to put forth a bunch of effort if it wasn't going to happen.

**Comment by JuergenGutsch** [comment]
One year later, the bug is still there.
Is there a possible workaround? Would it help to copy the WixUI_Minimal.wxs locally and change or remove the DialogRef?

**Comment by robmen** [comment]
WiX v4 is undergoing massive amounts of development. You can catch up with progress in the WiX Toolset weekly meetings.

**Comment by JuergenGutsch** [comment]
I will definitely, but I also have to get a product shipped with a MSI package as soon as possible :)

BTW: It works, if I copy the fragment and its contents of the WixUI_Minimal.wxs to the projects wxs file, call the id "WixUI_Custom_Minimal", use this id to reference to the UI and if I remove the WelcomeEulaDlg. Hope this helps :)

**Comment by robmen** [comment]
Uhh, we would not recommend shipping a product with WiX v4 at this time. There are significant breaking changes still underway through the end of the year.

**Comment by JuergenGutsch** [comment]
It's shipped inside the company only. So we control the whole path and we are shipping on every build. The setup isn't really complex. a minimal UI, just file copy, some registry entries and a few shortcuts. 
Let's see how it works :) I'm going to be your beta tester in an enterprise environment :-D

**Comment by robmen** [comment]
Sounds good. You'll want to start picking up builds regularly at the end of this year and into 2018.

**Comment by maniglia** [comment]
# Small update:
WiX Toolset Compiler version 4.0.0.5918
Windows 10
VS 2019

WixUI Dialogs:
`WixUI_Mondo` --> OK
`WixUI_Common` --> OK
`WixUI_FeatureTree` --> OK
`WixUI_InstallDir` --> OK
`WixUI_ProgressOnly` --> OK

`WixUI_Advanced` AND `WixUI_Minimal` both generate exceptions:


`WixUI_Minimal`
> C:\agent\_work\9\s\src\ext\UIExtension\wixlib\WelcomeEulaDlg.wxs(49) : error LGHT0091 : Duplicate symbol 'WixAction:InstallUISequence/WelcomeEulaDlg' referenced by C:\agent\_work\9\s\src\ext\UIExtension\wixlib\WixUI_Minimal.wxs(55). This typically means that an Id is duplicated. Ensure all your identifiers of a given type (File, Component, Feature) are unique or use an access modifier to scope the identfier.
C:\agent\_work\9\s\src\ext\UIExtension\wixlib\WixUI_Minimal.wxs(56) : error LGHT0092 : Location of symbol related to previous error.


`WixUI_Advanced`
> C:\agent\_work\9\s\src\ext\UIExtension\wixlib\WixUI_Advanced.wxs(30) : error LGHT0094 : The identifier 'Property:ApplicationFolderName' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.
C:\agent\_work\9\s\src\ext\UIExtension\wixlib\InstallScopeDlg.wxs(15) : error LGHT0094 : The identifier 'Property:WixAppFolder' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.

**Comment by robmen** [comment]
There is a test now covering this in UI.wixext. The test is passing so the root issue was fixed somewhere along the way.

**Comment by eggoor** [comment]
WixUI_Advanced:

`1>D:\a\wix\wix\src\ext\UI\wixlib\WixUI_Advanced.wxs(39): error WIX0094: The identifier 'Property:ApplicationFolderName' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.
1>D:\a\wix\wix\src\ext\UI\wixlib\InstallScopeDlg.wxs(14): error WIX0094: The identifier 'Property:WixAppFolder' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.`

is still there, wix --version 4.0.2+644ed011

**Comment by computerquip-work** [comment]
Can we re-open this? I'm getting issues that are the exact same as https://github.com/wixtoolset/issues/issues/5216#issuecomment-590830306

**Comment by rowbot38** [comment]
I'm also seeing WIX0091/92 using 4.0.3 but nothing to do with UI's. I have two HarvestDirectory's and different versions of the same DLL in different folders (bin1\acme.dll and bin2\acme.dll) - please advise. This is a regression coming from 3.14.
