### ISSUE TITLE
ConfigureUsers fails when it can't check the existence of the domain and no action is required

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#5217]
ConfigureUsers calls ScaUserExecute.
When ScaUserExecute can't check the existence of the domain it sets ueUserExists = to USER_EXISTS_INDETERMINATE and continues the flow.
However, the failure to check the existence is still reflected in hr.
When there's no need to create or delete the user, hr keeps its failure status and returned from the function, which fails the entire (un)install.

**Comment by barnson** [comment]
https://github.com/wixtoolset/wix3/pull/333
