### ISSUE TITLE
Cannot Find References

### ISSUE THREAD

**Issue by MP012016** [wixtoolset/issues#5223]
Hello,

I updated to the latest beta release of Wix Toolset (3.11.0.129).  As soon as I upgraded, none of my custom action projects (new or existing) could find their references any longer:
![image](https://cloud.githubusercontent.com/assets/17458141/13294698/d839763e-daea-11e5-95fd-4da8ecd9bca6.png)

As soon as I uinstalled 3.11.0.129 and reinstalled 3.10.2.2516, the problem went away.

I am using Visual Studio Premium 2013 and typically work with VB Custom Action projects.

Thank you.

**Comment by barnson** [comment]
There's a bug in the current build of WiX v3.11 that likely affects this issue. Please try v3.11.0.130 or later when the next build comes out.
