### ISSUE TITLE
Firewall exception not bound to a file or program is not removed on uninstall

### ISSUE THREAD

**Issue by kkorotkov** [wixtoolset/issues#5224]
In some cases it is needed to make a firewall exception that is not bound to a specific program or file:
![image](https://cloud.githubusercontent.com/assets/1833750/13325417/0ca5d5be-dbe2-11e5-8024-20a7641f7af4.png)

For this I put `<FirewallException>` element directly under `<Component>` and specify neither "File" nor "Program" attribute. The rule is created as expected for "Any" program, but is not later removed on uninstall.

WiX 3.10, Windows 7 x64,

**Comment by barnson** [comment]
Please attach a verbose log showing the failure to uninstall.

**Comment by kkorotkov** [comment]
Traced it down to the same fixed component GUID used in two different installers. In case `<FirewallException>` bound to a file, it worked because file is using generated GUID ('*').
The issue can be rejected.
