### ISSUE TITLE
Need option to allow duplicate directory IDs

### ISSUE THREAD

**Issue by heaths** [wixtoolset/issues#5227]
We had a version of wix internally that allows duplicate directory IDs as sources started diverging. This was reflected in wixtoolset/issues#4244, which was closed in lieu of a [proposed feature](/wixtoolset/issues/issues/4259) for wix4. Since I can't reopen the original issue, I would like to discuss making an optional feature in wix3 to allow for the migration while we clean up sources and move to wix4.

**Comment by robmen** [comment]
:-1: This isn't a real feature. The real feature is "inline path syntax" and that exists in WiX v4.0 for real. I don't think we should carry along this functionality in WiX v3.x.
