### ISSUE TITLE
Add Support for ImportBefore and ImportAfter targets in Wix Tool Installation Directory

### ISSUE THREAD

**Issue by BobSilent** [wixtoolset/issues#5228]
Currently only import of a dedicated targets file is supported:

`<Import Project="$(CustomBeforeWixTargets)" Condition=" '$(CustomBeforeWixTargets)' != '' and Exists('$(CustomBeforeWixTargets)')" />
<Import Project="$(CustomAfterWixTargets)" Condition=" '$(CustomAfterWixTargets)' != '' and Exists('$(CustomAfterWixTargets)')" />`

which is quite fine if you always customize this on commandline and if you have a customization per source code repository.

I you want to add some default customizations for a dedictad Wix Version (v3 or v4) or on a per machine basis, this is quite problematic.

Therefore I would like to have (in addition) a per Installation import directory in Wix Toolset Folder like Msbuild has it today (which works for C#, C++, VB.Net ...)

e.g. in C:\Program Files (x86)\MSBuild\12.0\Bin\Microsoft.Common.CurrentVersion.targets 
The following is available:
`
  <Import Project="$(MSBuildUserExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportBefore\*" Condition="'$(ImportUserLocationsByWildcardBeforeMicrosoftCommonTargets)' == 'true' and exists('$(MSBuildUserExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportBefore')"/>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportBefore\*" Condition="'$(ImportByWildcardBeforeMicrosoftCommonTargets)' == 'true' and exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.targets\ImportBefore')"/>
`
e.g. for Wix V3
C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\ImportAfter
C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\ImportBefore

and the same for Wix v4

this would enable me to centrally deploy some customization (on a machine basis) for a dedicated Wix Toolset Version, which should be valid for all our Products, without the need to add a CustomTargets into every Repository, and if there is a need to adapt, change each and every repository Custom Action.

In Addition the CustomBeforeWixTargets and CustomAfterWixTargets can be used for special things per Project Repository.

Currently I can do this, by deploying my CustomBeforeWixTargets and CustomAfterWixTargets and set a machine envionment variable to the file.
BUT: as Wix3 and Wix4 use same names they would both use the same files.

I am going to prepare a Pull Request if this i accepted.

**Comment by robmen** [comment]
Does this already work in v4? WiX v4 standardized on Common.targets so possibly this functionality came along for free.

I don't think we'd take this in WiX v3.x. New feature work goes in WiX v4.0.

**Comment by rseanhall** [comment]
It looks like in v4 we would get the ImportBefore/ImportAfter from the Common.targets file, but C#, VB, C++ etc. all have their own ImportBefore/ImportAfter folders, too.  It looks like we would have to copy what the other products are doing in our target file(s) to allow people to have ImportBefore/ImportAfter targets only for WiX projects (c.f. C:\Program Files (x86)\MSBuild\14.0\Bin\Microsoft.CSharp.targets).
