### ISSUE TITLE
Evaluate use of element text

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5235]
- Describe the scenario and benefits that the feature supports.

> The use of element text can be confusing and can complicate code. For example, ThmUtil lets you specify a control's text using element text. But it also supports child `Text` elements (with and without a `Condition` attribute for conditional text). The ThmUtil code has to do extra work to handle both. It's also a bit confusing: As [Zen](https://www.python.org/dev/peps/pep-0020/) says, "There should be one--and preferably only one--obvious way to do it."
- Describe how you're accomplishing the feature today (if possible).

> Brute force.
- Describe what you'd like the new feature to do.

> Deprecate/eliminate the use of element text where it isn't "vital." Today, that's probably only for expressions, though Burn authoring would disagree even with that. Even if we don't make major changes like this in the core language, we should take it for ThmUtil.

**Comment by rseanhall** [comment]
FWIW, I tried to leave the element text feature in ThmUtil to make migration easier from v3.

**Comment by barnson** [comment]
So much other stuff has changed, I'd vote for this particular porting pain point. And it's probably worth some eye time on the ThmUtil schema to see what can be trimmed or refactored. I'm motivated in part by the idea that at some point we could replace XML parsing in ThmUtil with a serialization format of some sort and element text is pretty XML-specific.
