### ISSUE TITLE
WiX Finish Dialog appears partially off screen, if install Progress Dialog is minimized.

### ISSUE THREAD

**Issue by tushardevsharma** [wixtoolset/issues#5243]
I am using WIX toolset to create the installation procedure for my product. 

I have noticed that if I minimize the installation Progress dialog box, then when the installation completes, the install Finish dialog would appear partially off screen (to the top left corner of the screen). I have to drag the Finish dialog box back to the center of the screen for it to be completely visible. 

Is there a way to prevent this from happening? Or is this simply a bug in Windows Installer itself?

**Comment by barnson** [comment]
WiX isn't in control of MSI UI.

**Comment by VivekDJadhav** [comment]
Is there any solution for this. I am also getting this issue.
