### ISSUE TITLE
Build error while creating setup project

### ISSUE THREAD

**Issue by vishkhatal** [wixtoolset/issues#5245]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

I am using 
Wix version -v3.8.1128.0
VSTS version-2013
.NET version -4.5
Windows version -windows 7

Problem -

I am creating wix installers for AsP.MVC web application.But I am getting an error saying that
 "The Command {..} exited with code 9009."

Probably the error is because of this line :

  <PropertyGroup>
    <PreBuildEvent>$(SolutionDir)Setup.eMee.Aboard.API\PreBuild.$(Configuration).bat $(SolutionDir)</PreBuildEvent>
  </PropertyGroup>

**Comment by robmen** [comment]
From the issue template.

> ## Discussions and support
> 
> Note that discussions are best held on the mailing lists, not in issues. Please do not open issues  requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.
