### ISSUE TITLE
Installing v3.11 from the bootstrapper doesn't update MSBuild target paths

### ISSUE THREAD

**Issue by acohenX1** [wixtoolset/issues#5246]
Version of WiX: 3.11.0.321
Version of Visual Studio: Premium 2013 v4.5.51209
Version of .NET: 4.5.2
Windows Version: 2008 R2, 7

Repro steps:
* Install WiX 3.10
* Optionally remove WiX 3.10
* Install WiX 3.11
* Build your solution
Result:  

> Error	The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets  Line 52 Column 5

Note the path mentioned above is `C:\Program Files (x86)\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll` which is again, the old path.

When consulting Wix.CA.targets I see the following:

`  <PropertyGroup>`
`    <WixInstallRegKey>SOFTWARE\Microsoft\Windows Installer XML\3.10</WixInstallRegKey>`
`    <WixInstallRegKeyWow64>SOFTWARE\Wow6432Node\Microsoft\Windows Installer XML\3.10</WixInstallRegKeyWow64>`
`  </PropertyGroup>`

Paths in other areas of the targets files include the installation directory for 3.10 too, such as this one from wix200x.targets:

`        <WixTasksPath Condition=" '$(WixTasksPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\..\WiX Toolset v3.10\bin\WixTasks.dll</WixTasksPath>`

**Comment by orochies** [comment]
My solution was to replace all the targets which appears 3.10 by 3.11

**Comment by barnson** [comment]
Fixed by a83b2130299ef95c9b0ec5c6d80bf34cc4722dfb.
