### ISSUE TITLE
Burn 3.9.1208.0: Payload is not picked up from package cache - prompts for source instead

### ISSUE THREAD

**Issue by dsed** [wixtoolset/issues#5247]
WiX version 3.9.1208.0, 3.10.2.2516
Visual Studio 2013 Update 5
.Net 4.5.2
Windows 8.1 64bit

When uninstalling my bundle from Add and Remove Programs I get a prompt for source instead of having the bundle picking up the payload from the package cache.

This happens in the following scenario
Having the following package definition

```
<PackageGroup Id="packageGroup.A">
      <ExePackage Id="$(var.EXEPACKAGE.A.INSTALL)"
                  Cache="always"
                  CacheId="$(var.PRODUCTCODE.A)-Client-v$(var.PRODUCTVERSION.A)"
                  Compressed="no"
                  Description="!(loc.Description.A)"
                  DetectCondition="$(var.A.PRESENT)"
                  DisplayName="!(loc.DisplayName.A)"
                  InstallCommand="&quot;$(var.COMMAND.INSTALL.A)&quot;"
                  InstallCondition="NOT $(var.THERMO.A.BLOCKER.PRESENT)"
                  Name="$(var.FOLDER.WORKSPACE.DISTRIBUTION.PACKAGES.DESTINATION)A\Product.Installer.exe"
                  PerMachine="yes"
                  Permanent="no"
                  RepairCommand="&quot;$(var.COMMAND.REPAIR.A.INSTALL)&quot;"                  
                  SourceFile="$(var.FOLDER.WORKSPACE.DISTRIBUTION.BINARIES.HELPER)Product.Installer.exe"
                  SuppressSignatureVerification="no"
                  UninstallCommand ="&quot;$(var.COMMAND.UNINSTALL.A.INSTALL)&quot;"
                  Vital="yes">
        <ExitCode Behavior="error" />
        <!-- ERROR_SUCCESS -->
        <ExitCode Value="0"
                  Behavior="success" />
        <!-- ERROR_SUCCESS_REBOOT_REQUIRED -->
        <ExitCode Value="3010"
                  Behavior="scheduleReboot" />
        <PayloadGroupRef Id="payloadGroup.A" />
        <PayloadGroupRef Id="payloadGroup.A.Helper" />
        <dependency:Provides DisplayName="A Driver"
                             Key="$(var.PRODUCTCODE.A)-Client"
                             Version="$(var.PRODUCTVERSION.A)" />
      </ExePackage>
```

Note that Product.Installer.exe is built and digitally signed with each release. This is why I set SuppressSignatureVerification to "no".

After installing version 1 I do an upgrade to version 2. During upgrade there is no indication that Product.Installer.exe of version 1 is replaced with version 2.

After removing the original package source I start an uninstall from Add and Remove Programs and was expecting it to succeed. Instead I get a prompt for source. 

In the log I can see that burn did not even try to acquire the package from the package cache (at least there is no such log entry). The only entry found is:

```
[0C3C:0F78][2016-03-24T10:22:46]w343: Prompt for source of package: exePackage.A.Install, payload: exePackage.A.Install, path: D:\Packages\A\Driver\Product.Installer.exe
```

After pointing to the package cache location uninstallation continues without any errors though:

```
[0C3C:0F78][2016-03-24T10:27:36]i338: Acquiring package: exePackage.A.Install, payload: exePackage.A.Install, copy from: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\A\Driver\Product.Installer.exe
[0C3C:0F78][2016-03-24T10:27:36]i000: Setting string variable 'WixBundleLastUsedSource' to value 'C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\'
[11D4:1074][2016-03-24T10:27:36]i304: Verified existing payload: exePackage.A.Install at path: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\A\Driver\Product.Installer.exe.
```

```
[11D4:11D0][2016-03-24T10:31:29]i301: Applying execute package: exePackage.A.Client.Install, action: Uninstall, path: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\A\Driver\Product.Installer.exe, arguments: ''
```

I am expecting that burn is picking up the payload from the package cache immediately not having to point it to the correct location. I am also wondering why burn does not even try to attempt to verify the payload before prompting. As far as I remember this used to work in Wix 3.6.

**Comment by robmen** [comment]
Please edit your issue and provide all the information from the Issue template. You can get the template by clicking "New Issue" then canceling that issue.

**Comment by barnson** [comment]
Please attach a complete log showing the problem.

**Comment by dsed** [comment]
[Problem.zip](https://github.com/wixtoolset/issues/files/193360/Problem.zip)

**Comment by dsed** [comment]
I have just uploaded the requested log files, for upgrade, repair and uninstall.
The payloads of interest are 
`Prompt for source of package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, path: D:\Packages\Thermo TSQ Endura Quantiva\Client\Thermo.Product.Installer.exe`
and
`Prompt for source of package: exePackage.Thermo.Exactive.Client.Install, payload: exePackage.Thermo.Exactive.Client.Install, path: C:\ProgramData\Package Cache\{CE48A6F4-A18B-4781-B561-491DF6F6F0FC}-v1.1.1016.0\Packages\Thermo Exactive\Driver\Thermo.Product.Installer.exe`

Another observation I made: when I apply the uninstall after the repair I get only one resolve source prompt, else I get the same result as applying a repair - two prompts.

**Comment by rseanhall** [comment]
Burn looks for existing payloads during Detect, not Apply.  In the log, you can see that it has a problem with a payload:

    Detected partially cached package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, invalid payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, reason: 0x80070570

`0x80070570` means `The file or directory is corrupted and unreadable`. The `-burn.unelevated` switch in the repair and uninstall logs imply that the normal engine is running elevated so there shouldn't be any differences in accessing the file between detect and apply. I don't see why the detect code would get `0x80070570` when verifying the payload but the apply code wouldn't, there could be a bug if they're not using the same code.

**Comment by barnson** [comment]
Why are you specifying `CacheId`? It looks like it's not unique, which why Burn is saying the existing payload is corrupt.

**Comment by rseanhall** [comment]
Here's my theory on what happened here:

1. Version1 of the bundle is built with VersionA of `exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install`.
1. Version1 of the bundle is deployed with VersionB of `exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install`.  The V1 bundle is only OK with this because Burn checks only the signature and not the hash when `SuppressSignatureVerification` is `no` during `Apply`.
1. When Version1 of the bundle gets repaired, Burn returns `ERROR_FILE_CORRUPT` when checking if the payload is cached because the detection logic for cached payloads merely checks the file size.
1.  During `Apply` of the repair, Burn sees that the payload was detected as missing and tries to acquire it.  It doesn't bother looking at the package cache because `Detect` already said it wasn't there.

**Comment by dsed** [comment]
Regarding the `CacheId`: It is unique for this package. I have also tried to leave it to the engine to create it, but this results in the weird behavior that orphaned packages are left in the package cache when upgrading the bundle. I assume this is in conjunction with the package dependency.

Regarding the deployment scenario:

1. Version 1 of the bundle is built with version A of `exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install`
2. Version 2 of the bundle is built with version B of
`exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install`
3. During upgrade the engine detects that version B is 'corrupt'
```
Detected partially cached package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, invalid payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, reason: 0x80070570
```
4. In the Apply phase the engine acquires the payload
```
Acquiring package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, copy from: D:\Packages\Thermo TSQ Endura Quantiva\Client\Thermo.Product.Installer.exe
Verified existing payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install at path: C:\ProgramData\Package Cache\{CE48A6F4-A18B-4781-B561-491DF6F6F0FC}-v1.1.1016.0\Packages\Thermo TSQ Endura Quantiva\Client\Thermo.Product.Installer.exe.
``` 
Here I assume that the engine is overwriting the existing file
5. But when repairing the bundle (version B, source not available) the engine reports again
```
Detected partially cached package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, invalid payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, reason: 0x80070570
```
Seems to me the engine did **not** update the payload in 4
6. As a result I get the prompt for source
7. Above also applies to `exePackage.Thermo.Exactive.Client.Install`

Furthermore the behavior becomes really strange when doing an uninstall:

For `exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install` the engine reports
```
Detected partially cached package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, invalid payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, reason: 0x80070570
Acquiring package: exePackage.Thermo.Exactive.Client.Install, payload: exePackage.Thermo.Exactive.Client.Install, copy from: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\Thermo Exactive\Driver\Thermo.Product.Installer.exe
Verified existing payload: exePackage.Thermo.Exactive.Client.Install at path: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\Thermo Exactive\Driver\Thermo.Product.Installer.exe.
Prompt for source of package: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, payload: exePackage.Thermo.TSQ.Endura.Quantiva.Client.Install, path: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\Thermo TSQ Endura Quantiva\Client\Thermo.Product.Installer.exe
```
whereas for ` exePackage.Thermo.Exactive.Client.Install` the engine reports
```
Detected partially cached package: exePackage.Thermo.Exactive.Client.Install, invalid payload: exePackage.Thermo.Exactive.Client.Install, reason: 0x80070570
Acquiring package: exePackage.Thermo.Exactive.Client.Install, payload: exePackage.Thermo.Exactive.Client.Install, copy from: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\Thermo Exactive\Driver\Thermo.Product.Installer.exe
Verified existing payload: exePackage.Thermo.Exactive.Client.Install at path: C:\ProgramData\Package Cache\{E375A980-147A-4287-9172-FE4A3BCF8FA2}-Client-v2.6.0.2640\Packages\Thermo Exactive\Driver\Thermo.Product.Installer.exe.

```
and does not prompt for the source.

How can it be that the engine acquires and verifies the payload and later could not find it anymore?
Why is this not happening for all payloads using the same approach?
Another thing worth mentioning: **this used to work in WiX 3.6**

**Comment by rseanhall** [comment]
`Cache="yes"` was added in v3.9, so the behavior in v3.6 is a compiler error.

Reusing `CacheId` is not supported.

If `SuppressSignatureVerification` was set to `yes`, then Burn would always reject the payload.

I think it is a bug that detect and apply don't verify the payloads the same way.

**Comment by rseanhall** [comment]
We're not going to make any changes to this in 3.x. We are removing support for Authenticode verification in v4.0 (https://github.com/wixtoolset/issues/issues/6301).
