### ISSUE TITLE
Silent installation is not started if access to log file is denied or it doesn't exist

### ISSUE THREAD

**Issue by flydyk** [wixtoolset/issues#5248]
WiX version: 3.10.2.2516
.NET Framework 4.5
Windows 8.1 64-bit

Suppose we've built installer ApplicationInstaller.exe.

Steps to reproduce:
1. Execute command ApplicationInstaller.exe -quiet -log "T:\Installation.log"

Result: Installation is not started
Expected: Successful installation with missing log file

It seems that WiX Burn Engine stops installing if log file is not accessible.

**Comment by rseanhall** [comment]
Related to #4362.

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/issues/issues/4929

Burn now writes an error to the Application event log if it can't run.
