### ISSUE TITLE
Bundle doesn't uninstall a permanent package on failed Bundle Install, but deletes the cache during rollback.

### ISSUE THREAD

**Issue by rw1017** [wixtoolset/issues#5249]
- Which version of WiX are you building with?
  3.7.1224.0
- Which version of Visual Studio are you building with (if any)?
  Visual Studio 2013, Update 4
- Which version of .NET are you building with?
  .Net 4.5
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
  Windows 7, 32-bit
- Describe the problem and the steps to reproduce it.

Installing a Bundle with (a.msi, b.msi, c.msi), where a is set to "Permanent"...
Suppose c.msi fails because of user error(not msi), the rollback process is started, and uninstall b.msi, but a.msi remains because it's set to Permanent.  Burn uncaches a.msi.

Assume the user corrects the issue, and re-runs bundle install.
The Bundle will detect that a.msi already exists, and will not cache.

This causes a problem if we try to Repair the Bundle through ARP/calling the exe from cache(we removed the original media source/CD)
- Describe the behavior you expected and how it differed from the actual behavior.

I'd expect that if the rollback process leaves A.msi, it would keep the package cache on the system.
However, the rollback process removes the cached A.msi, and leaves the system error-prone in repairing the bundle(after it's been installed successfully after the error.)
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.
## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

**Comment by barnson** [comment]
Burn's doing the right thing -- without a bundle around, nothing would ever clean up the cache. 

Cache="always" prevents this scenario. See also https://github.com/wixtoolset/issues/issues/5125.
