### ISSUE TITLE
Using a image file for a progressbar element in a burn theme file draws wrong border

### ISSUE THREAD

**Issue by andershol** [wixtoolset/issues#5250]
When using an image file for a progressbar element in a burn theme file, the [documentation states](http://wixtoolset.org/documentation/manual/v3/xsd/thmutil/progressbar.html) that 

> The image must be 4 pixels wide: left pixel is the left side of progress bar, left middle pixel is progress used, right middle pixel is progress unused, right pixel is right side of progress bar

But it seems that the right side of the progress bar is not draw with the right-most (i.e. fourth) column of the image, but with the left-most (i.e. first) column of the image.
Looking at DrawProgressBar in [src/libs/dutil/thmutil.cpp](https://github.com/wixtoolset/wix3/blob/45ab91e7b2b08b1752bf5d958c49f66ff9ac3c23/src/libs/dutil/thmutil.cpp#L3263) it seems that the line

> `::StretchBlt(pdis->hDC, pdis->rcItem.right - 1, 0, 1, dwHeight, hdcMem, nSourceX, nSourceY, 1, dwHeight, SRCCOPY);`

should read

> `::StretchBlt(pdis->hDC, pdis->rcItem.right - 1, 0, 1, dwHeight, hdcMem, nSourceX + 3, nSourceY, 1, dwHeight, SRCCOPY);`

(i.e. `nSourceX` should be replaced by `nSourceX + 3`)

**Comment by barnson** [comment]
Behavior change so taking in v4.

**Comment by andershol** [comment]
:( Then every bugfix is a behavior change? In the common case (I assume) where the border is the same color on all four sides, there is no change of behavior (I guess that is why the bug have gone unnoticed). Also the feature is probable not used much as it has gotchas, the docs are sparse, and not examples use it.
Another way to fix the problem would be if no left/right border was drawn if the image is only two pixel wide. The you could place image-elements next to the progressbar element to give the illusion of a border (this is what I need to do anyway, as I need a non-rectangular border wider than 1px). Or you could redraw all elements after (i.e. on top of) the progress-bar when redrawing the progress-bar, so it doesn't "jump" to the foregrond when redrawn.

**Comment by barnson** [comment]
There's a difference between fixing something that's broken and fixing something that's not performing "as documented."

We don't currently track the size of the bitmap so I don't know if we want to go there. But I'm marking this to go through triage again, so if you have any other ideas, please add them and we'll discuss at triage on 19-April.

**Comment by barnson** [comment]
Triage says this doesn't meet the v3.x bar.

**Comment by andershol** [comment]
Too bad. But if you want to take it for v4, perhaps the issue shouldn't be closed.

**Comment by robmen** [comment]
You are absolutely correct. This should stay open in WiX v4.

Note: You're going to see more issues moving to WiX v4. We are shifting our attention to the next release and very soon feature work and non-vital bug fixes will only be fixed there.
