### ISSUE TITLE
Blue Arrows indicating compressed on Windows 10 shortcut icons

### ISSUE THREAD

**Issue by elliotl** [wixtoolset/issues#5251]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.2.2516
Also saw this with version 3.9.x

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Pro 2013 version 12.0.40629.00 Update 5

* Which version of .NET are you building with?

> none

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Home, version 1511, OS build 10586.164

* Describe the problem and the steps to reproduce it.

Installer creates desktop icon for app.
![sg_icon_img_win10](https://cloud.githubusercontent.com/assets/1779152/14320547/5894d86e-fbca-11e5-9e5d-8432ef4a4271.png)

![sg_icon_img_win7](https://cloud.githubusercontent.com/assets/1779152/14320561/68eb1cc8-fbca-11e5-8c47-6c04b12a0278.png)

On windows 10, the icon has blue arrows indicating compression!! I do not want the user to see the blue arrows. No blue arrows show up in windows 7 or 8.1 .

See Product.wxs below:
[Product_wxs.txt](https://github.com/wixtoolset/issues/files/206633/Product_wxs.txt)

**Comment by barnson** [comment]
This is Windows 10 behavior: The icons are cached and stored in a folder that's now compressed so it gets the compression overlay. WiX isn't involved in those decisions.

**Comment by elliotl** [comment]
Other shortcut icons on my Windows 10 desktop do not contain the compression arrows. If I create a shortcut for an .exe by using the Windows Explorer to send a shortcut to the desktop, the icon for that desktop shortcut does not contain compression arrows. 

So it is clearly possible to create desktop shortcuts in Windows 10 with icons that are not fouled up by compression arrows.

So the question is: How do I get my Wix based installer to create a desktop shortcut icon without compression arrows. 

I am not the only person seeing this as a Wix problem. 
See http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Blue-Arrows-on-Per-Machine-Shortcut-Icons-td7601086.html#a7601089 .

I suspect that this is a bug introduced by Microsoft and it is triggered by the compressed option in the following tag:
<Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />

When the installer makes the system call to create the desktop short, the system notes that the icon image file is in some compressed archive, so it pollutes the image with compression arrows???

Even though the bug is probably Microsoft's fault, it creates a rather widespread problem for developers creating installers with Wix and possibly other tools. Is there a workaround?

**Comment by elliotl** [comment]
The tag in previous comment did not show up, so I will try again:
[Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" /]

**Comment by robmen** [comment]
For discussion, please contact the wix-users@lists.wixtoolset.org mailing list. If through discussion we find that there is some way the WiX Toolset should change, we can open an issue here.
