### ISSUE TITLE
Blue compression arrows on Windows 10 shortcut icons

### ISSUE THREAD

**Issue by elliotl** [wixtoolset/issues#5252]
I made some comments on bug #5251 that was just closed. I do not mean to abuse this forum, but
I was not sure if my comments and questions would be addressed unless there was an open bug.

**Comment by robmen** [comment]
For discussion, please contact the wix-users@lists.wixtoolset.org mailing list. If through discussion we find that there is some way the WiX Toolset should change, we can open an issue here.
