### ISSUE TITLE
MSI: Control with @Type="HyperLink" doesn't support @Transparent and @NoPrefix

### ISSUE THREAD

**Issue by fourpastmidnight** [wixtoolset/issues#5256]
Which version of WiX are you building with?
: 4.0.3729.0

Which version of Visual Studio are you building with (if any)?
: 2015 Enterprise Update 2
: MSYS2 bash shell command line

Which version of .NET are you building with?
: N/A

If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
: N/A

**Describe the problem and the steps to reproduce it:**
I authored the `WelcomeDlgLink` dialog from the "reference" MSI UI database from the Windows 7 SDK. This dialog contains a Hyperlink control, which according to the MSI database, has control attributes whose integer value is 196611 (`0x30003`), which is `Transparent="yes"`, `Disabled="no"`, `Hidden="no"` and `NoPrefix="yes"` (which, oddly enough, is not listed as one of the supported attributes via the MSI Installer Reference, but nonetheless is a bit present in the reference MSI). So, in WiX, the control is authored as:

`<Control Id="WebLink" Type="HyperLink" Width="220" Height="30" X="135" Y="120" 
          Transparent="yes" NoPrefix="yes" Text="!(loc.MyLocalizedHyperlinkText)" />`

When building the MSI, I receive two errors, one for each of the `@Transparent` and `@NoPrefix` attributes.

**Describe the behavior you expected and how it differed from the actual behavior:**
I expected that these attributes would be supported since the reference MSI allows these attributes to be set (though I could understand if `@NoPrefix` were not supported because it's actually not documented as part of the MSI Reference Documentation).

I understand that the MSI technology, as a whole, is being more or less "deprecated" in favor of the newer AppX installation technology, so this may not be high on your priority list of things to "implement"; but I just wanted to point out some missing functionality.

**Comment by barnson** [comment]
What are the error messages? `Transparent` should work but `NoPrefix` isn't supported. (It's really a thing for static controls.)

**Comment by fourpastmidnight** [comment]
@barnson:

The following error is displayed for the `Transparent` attribute in the Visual Studio error pane:

```
The Control element contains an unexpected attribute 'Transparent`.
```

Looking in the Build Output window, I see the following:

```
error CNDL0004: The Control element contains an unexpected attribute 'Transparent'.
```

**Comment by robmen** [comment]
Turns out the root issue is that the `Control/@Type` is `Hyperlink` not `HyperLink`. The fix is to error when an invalid control type is provided.
