### ISSUE TITLE
[Feature Request] Light.exe: It would be nice to keep the generated MSI database even if validations fail

### ISSUE THREAD

**Issue by fourpastmidnight** [wixtoolset/issues#5257]
# Problem Description

I love running all the validations when building a WiX-based MSI installer. As per best practices: don't disregard an ICE warning or error until you know and understand why the warning/error is being presented and can make a determination as to whether or not the warning/error can be safely disregarded. I have found that most times, a warning/error should not be disregarded, and that there is a way to resolve the warning/error through careful authoring of the WiX XML; though I understand that this may not be the case 100% of the time.

However, when it comes to running these ICE validations, sometimes the error messages that are presented are not really enough to understand what's really happening, why the generated MSI database is invalid. This is especially true when you are using localization and WiX variables, as they aren't resolved at compile time, but link time. And often times, the only clue you have as to what's happening is by looking at the generated MSI database.
# Feature Request

_As a WiX installer author
I want to be able to pass a command line argument to `light.exe` that will result in the generated MSI database not being deleted even if there are ICE validation failures
So that I can view the generated database in tools such as `ORCA` to gain deeper insight into why the generated database is invalid_

I would even suggest that perhaps this should be the default behavior, but in lieu of that, for the present moment, let's just consider it as an option.
## An Example of How this Feature Could Have Reduced My Debug/Development Time

During authoring an installer, I had the following XML (abbreviated to get to the main point faster):

``` xml
<Dialog Id="SomeDialog">
    <Control Id="BannerBitmap" Type="Bitmap" Text="[BannerBitmap]" Height="44" Width="370" />
</Dialog>

<Dialog Id="AnotherDialog">
    <Control Id="DialogBitmap" Type="Bitmap" Text="[DialogBitmap]" Height="234" Width="370" />
</Dialog>

<Property Id="BannerBitmap" Value="!(loc.BannerBitmap" />
<Property Id="DialogBitmap" Value="!(loc.DialogBitmap)" />

<WixLocalization Culture="en-us" xmlns="http://wixtoolset.org/schemas/v4/wxl">
    <String Id="BannerBitmap" Overridable="yes">bannrbmp</String>
    <String Id="DialogBitmap" Overridable="yes">dlgbmp</String>
</WixLocalization>
```

For about 6 hours over the course of wiring up my UI, I'm wondering why my `[BannerBitmap]` property is resulting in ICE17 errors (which I ignored until the very end, seeing nothing wrong with the WiX XML I had written). The error message is obvious--the property value could not be found in the `Binary` table--but everything looked right. What the heck is wrong? Well, after about 1.5 hours of careful scrutiny, I realized my `BannerBitmap` property value was missing the ending `)` on the WiX localization variable! This isn't caught at compile time because localization variables aren't resolved until link time. See my additional feature request #5258 that could more quickly help with this specific problem.

In lieu of any syntax analysis that could've helped me resolve this issue even before building the entire MSI (as per #5258), if I only had access to the generated MSI database even though it failed ICE validations, I might have been able to look in the Binary table and discovered a `BannerBitmap` property whose value was `!(loc.BannerBitmap` instead of the expected value `bannrbmp` all due to the fact that I was missing the ending `)` on my localization variable.
# Potential Feature Request Implementations

I propose one of two ways to implement this feature request:
1. Extend the functionality of the existing `-notidy` switch so that in addition to not deleting temporary files, the generated MSI database is not deleted either, even in the face of ICE validation failures.
   - While this may be the "easy route", it's probably not the best, since the "temporary files" generated by `light.exe` are really not in the same class as the generated MSI database--it's probably best not to "overload" this switch with this behavior
2. Create a new command line switch for `light.exe`. Perhaps `-keep[:<SUFFIX=INVALID>]`.
   - Here, if `-keep` is specified, then by default, the MSI would be copied to the output directory as `MyInstaller-INVALID.msi`. If a suffix is specified, such as `-keep:Failed`, then the output would be `MyInstaller-Failed.msi`.

**Comment by barnson** [comment]
Solve in v4 by leaving .msi in intermediate directory if it fails validation.

**Comment by fourpastmidnight** [comment]
That's even easier ☺
