### ISSUE TITLE
preprocessor conditionals  executed before command line variables created

### ISSUE THREAD

**Issue by garymazz** [wixtoolset/issues#5259]
Version 3.10.2.2516
Windows 10 (doesn't make a difference)
Build System: Maven (no VS)
.NET: None
- Describe the problem and the steps to reproduce it.

Issue is occurring using include file referenced in wxs file

include file content:

```
  <?ifndef $(var.ResourceDir) ?>
    <?define ResourceDir           ="$(sys.CURRENTDIR)target\resources" ?>
  <?endif?>

```

Execute candle with -d parameter
`candle  -dResourceDir=SomeOtherDirectory
`
I expect the preprocessor's ifndef condition located in the include file to recognize the variable defined on the command line.

**Comment by barnson** [comment]
<?ifndef ResourceDir ?>

works.

**Comment by garymazz** [comment]
thanks,  Bob
