### ISSUE TITLE
Feature Request: Add service "start  parameter" attribute ServiceInstall tag.

### ISSUE THREAD

**Issue by garymazz** [wixtoolset/issues#5261]
Please add service "start  parameter" attribute ServiceInstall tag. Currently the argument attribute rolls up the executable image and arguments into the service executable path which helps with 'admin tampering" of execution arguments. User accessible "startup parameters" are also important to support for server based services.

Version: 3.10

**Comment by barnson** [comment]
Windows Installer doesn't support that functionality. At the moment, we don't have a custom action to handle service installation so we're limited to what MSI offers.
