### ISSUE TITLE
MSBUILD fails in VS 2015, but works in VS 2013

### ISSUE THREAD

**Issue by tomhornyak** [wixtoolset/issues#5263]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.1.2213.0

* Which version of Visual Studio are you building with (if any)?

> vs 2015 Update 1 and update 2 - both fail

* Which version of .NET are you building with?

> 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> Running candle & light in an MS build script fails. Using Running the exact command that fails in a developer command prompt works. This is msbuild version 14.0.35123.0.
The MS build command
        <Exec
            Command='"$(WIX)\bin\candle" –ext WixIISExtension -ext WixUtilExtension -dpublishDir=$(PublishDir) -dMyWebResourceDir=. @(WixCode, &apos; &apos;)'
            ContinueOnError="false"
            WorkingDirectory="." />
 
D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup>msbuild Setup.msbuild /t:makeinstaller
Microsoft (R) Build Engine version 14.0.25123.0
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/14/2016 12:40:59 PM.
Project "D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup\Setup.msbuild" on node 1 (makeinstall
er target(s)).
MakeInstaller:
  "C:\Program Files (x86)\WiX Toolset v3.10\\bin\candle" -ext WixIISExtension -ext WixUtilExtension -dpublishDir=..\..\
  NextGenPortal\Setup\publish\ -dMyWebResourceDir=. Product.wxs WebSiteContent.wxs IISConfiguration.wxs
candle.exe : error CNDL0103: The system cannot find the file '-ext' with type 'Source'. [D:\ViewStore\SyngoDynamics\Mai
n\WebStation\NextGenPortal.Setup\MVC.Setup\Setup.msbuild]
D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup\Setup.msbuild(37,9): error MSB3073: The comman
d ""C:\Program Files (x86)\WiX Toolset v3.10\\bin\candle" -ext WixIISExtension -ext WixUtilExtension -dpublishDir=..\..
\NextGenPortal\Setup\publish\ -dMyWebResourceDir=. Product.wxs WebSiteContent.wxs IISConfiguration.wxs" exited with cod
e 103.
Done Building Project "D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup\Setup.msbuild" (makeins
taller target(s)) -- FAILED.

Running the same command in the same vs 2015 command prompt where ms build failed.

D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup>"C:\Program Files (x86)\WiX Toolset v3.10\\bin\
candle" -ext WixIISExtension -ext WixUtilExtension -dpublishDir=..\..\NextGenPortal\Setup\publish\ -dMyWebResourceDir=.
Product.wxs WebSiteContent.wxs IISConfiguration.wxs
Windows Installer XML Toolset Compiler version 3.10.1.2213
Copyright (c) Outercurve Foundation. All rights reserved.

Product.wxs
WebSiteContent.wxs
IISConfiguration.wxs

Using VS 2013 / msbuild 12.0.31101.0 works

D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup>msbuild Setup.msbuild /t:makeinstaller
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/14/2016 12:44:00 PM.
Project "D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup\Setup.msbuild" on node 1 (makeinstall
er target(s)).
MakeInstaller:
  "C:\Program Files (x86)\WiX Toolset v3.10\\bin\candle" -ext WixIISExtension -ext WixUtilExtension -dpublishDir=..\..\
  NextGenPortal\Setup\publish\ -dMyWebResourceDir=. Product.wxs WebSiteContent.wxs IISConfiguration.wxs
  Windows Installer XML Toolset Compiler version 3.10.1.2213
  Copyright (c) Outercurve Foundation. All rights reserved.

  Product.wxs
  WebSiteContent.wxs
  IISConfiguration.wxs
  Install package has been created.
Done Building Project "D:\ViewStore\SyngoDynamics\Main\WebStation\NextGenPortal.Setup\MVC.Setup\Setup.msbuild" (makeins
taller target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

* Describe the behavior you expected and how it differed from the actual behavior.

> I would expect the same behavior in VS 2015 MSBUILD as I see in VS2013 MSBUILD

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

**Comment by rseanhall** [comment]
The hyphen in your Command looks like it's not a normal hyphen - `–ext WixIISExtension`.  This is really a support issue so please contact the wix-users@lists.wixtoolset.org mailing list for any further questions.
