### ISSUE TITLE
WixVSExtension documentation formating

### ISSUE THREAD

**Issue by KindDragon** [wixtoolset/issues#5264]
Please fix this page formatting:
http://wixtoolset.org/documentation/manual/v3/customactions/wixvsextension.html

**Comment by jonstelly** [comment]
It's also a problem for [WixNetfxExtension](http://wixtoolset.org/documentation/manual/v3/customactions/wixnetfxextension.html)

**Comment by KindDragon** [comment]
Related to #5210
