### ISSUE TITLE
Burn payloads can have Names that allow escaping cache folder

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5265]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.
## Bugs

If this issue is a bug:
- Which version of WiX are you building with?

3.10.2.2516
- Describe the problem and the steps to reproduce it.

Authoring like

```
<MsiPackage SourceFile="$(var.Msi.TargetPath)" Name="..\myveryspecialmsi.msi">
```

is legal. But it "moves" the payload out of the intended cache directory.
- Describe the behavior you expected and how it differed from the actual behavior.

Backslashes should be allowed to support subdirectories of the cache directory but `..` should be a compile-time error.

**Comment by barnson** [comment]
Warning in v3. Already an error in v4(?).

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/wix4/pull/200
