### ISSUE TITLE
Calling "rundll32 syssetup,SetupInfObjectInstallAction" triggers addionial wix burn dialog end of installation on 32 bit windows

### ISSUE THREAD

**Issue by metsma** [wixtoolset/issues#5266]
If this issue is a bug:
- Which version of WiX are you building with?

> 3.10.2.2516
- Which version of Visual Studio are you building with (if any)?

> Visual Studio 2013 Community Update 5
- Which version of .NET are you building with?

> 4.5
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7, 8, 8.1, 10 32 bit
- Describe the problem and the steps to reproduce it.

> After install additional Install/Uninstall appears
- Describe the behavior you expected and how it differed from the actual behavior.

> No need additional install window, on 64 bit this window does not appear.
### Minimal example

bootstrapper.wxs
`
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
    xmlns:bal="http://schemas.microsoft.com/wix/BalExtension">
  <Bundle Name="eID software" Version="$(var.MSI_VERSION)"
      UpgradeCode="f1c4d351-269d-4bee-8cdb-6ea70c968875">
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkSidebarLicense">
      <bal:WixStandardBootstrapperApplication LicenseUrl=""/>
    </BootstrapperApplicationRef>
    <Variable Name="InstallFolder" Type="string" Value="[ProgramFiles6432Folder]\Open-EID"/>
    <Chain>
      <MsiPackage Id="Minidriver.X64" InstallCondition="VersionNT64" ForcePerMachine="yes"
          SourceFile="minidriver_3.11.0.1175.2.x64.msi" Compressed="yes">
        <MsiProperty Name="APPLICATIONFOLDER" Value="[InstallFolder]"/>
      </MsiPackage>
      <MsiPackage Id="Minidriver.X86" InstallCondition="NOT VersionNT64" ForcePerMachine="yes"
          SourceFile="minidriver_3.11.0.1175.2.x86.msi" Compressed="yes">
        <MsiProperty Name="APPLICATIONFOLDER" Value="[InstallFolder]"/>
      </MsiPackage>
      <ExePackage SourceFile="$(var.path)\CustomAction.cmd" PerMachine="yes" Compressed="yes"
        InstallCommand="rundll32 syssetup,SetupInfObjectInstallAction DefaultInstall 128 [InstallFolder]\esteidcm.inf" />
    </Chain>
  </Bundle>
</Wix>
`

CustomAction.cmd
`%*`

Minidriver msi-s are available at https://installer.id.ee/media/windows/installer/. 
### Additional info

Same happens I call "rundll32 syssetup,SetupInfObjectInstallAction" in MSI, bootstrapper triggers additional window end of installation on 32 bit windows.  
64 bit windows works as expected.

**Comment by barnson** [comment]
Windows runs RunOnce values while installing drivers and that's where Burn registers a bundle for restart handling. You can detect this scenario in a custom BA and exit the second instance when the first is running. We'll take this in v4.0 to see if we can detect this state and prevent the second instance.

**Comment by glaure** [comment]
Using WIX 3.11 I got hit by this issue too.

**Comment by barnson** [comment]
Seems like an XP-era problem. If it's something that still happens on in-service OSes, let us know.

**Comment by metsma** [comment]
Yes it happens, windos 7/8.1/10

**Comment by rseanhall** [comment]
From the discussion in https://www.firegiant.com/blog/2020/12/22/wix-online-meeting-202-highlights/:

We use the [`RunOnce`](https://docs.microsoft.com/en-us/windows/win32/setupapi/run-and-runonce-registry-keys) key in the way that it was intended to be used - to complete installation after a reboot (or the machine loses power, etc). While it may be possible to use some other Windows functionality to schedule ourselves to run after a reboot, doing so would risk even more false positives from antivirus software since `RunOnce` is the way you're supposed to do that. We have no plans to change how we're using `RunOnce`, but if someone comes up with a proposal that meets all of the functionality we need while still being secure then we'll be happy to review it.
