### ISSUE TITLE
License agreement not rendered

### ISSUE THREAD

**Issue by EMostafaAli** [wixtoolset/issues#5272]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2015 V 14.0.25123.00 Update 2

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> I built an installer with WIX and I noticed whenever I run the installer on windows 10 (not sure about other versions), the license agreement was not rendered correctly as in the attached figure, It appears if I minimize / restore the installer window.
<img width="386" alt="2016-04-21 16_23_14-curve load for sap2000 setup" src="https://cloud.githubusercontent.com/assets/11354102/14726258/255ca1e6-07de-11e6-8e0e-c2efd9be6e8c.png">

**Comment by jozefizso** [comment]
Does your license agreement file use RTF format? Please, open it in Wordpad and resave it. This will remove RTF features that are not supported by the Windows GDI+ rich text box that renders the RTF.

**Comment by EMostafaAli** [comment]
Thanks, this solves the problem.

But I am not sure why in the first case, it renders correctly after I minimize / restore the  window.

**Comment by robmen** [comment]
@EMostafaAli this is Windows Installer and the RichText control behavior. It basically has issues with complex RTF that Wordpad will strip out.
