### ISSUE TITLE
IISWiXExtension IISMAJORVERSION stores #10 for IIS 10 which makes comparisons impossible without a custom action

### ISSUE THREAD

**Issue by BenOSIsoft** [wixtoolset/issues#5276]
## System Information

WiX Version 3.10.2.2516
Visual Studio 2015 Enterprise 2015 with Update 2 Version 14.0.25123.0
.Net Version 4.5
Operating System: Windows 10
IIS Version: 10+

## Steps for Reproduction

**Add the following to a .wxs file as a conditional message:**

```
    <!-- IIS version check -->
    <PropertyRef Id="IISMAJORVERSION" />     
    <Condition Message="This application requires IIS version 7.5. or IIS version 8 or higher">
      (IISMAJORVERSION = "#7" AND IISMINORVERSION = "#5") OR (IISMAJORVERSION >= #8)
    </Condition>
```

Expected behavior is for the check to realize that '# 10' > '# 8'. Currently these are being evaluated as string comparisons. If the quotes and pound signs are removed, it is an integer comparison, but the property IISMAJORVERSION is still a string ('# 10'), and thusly does not pass the check.

The simplest solution is change IISMAJORVERSION to store an integer version of the value, but this will make IISWiXExtensions to be not backwards compatible with other users currently using this type of check.

I realize this check can be changed to add the IISMAJORVERSION # 10, but that makes our installs require a change every time the IIS version is added. Additionally our customers that choose not to upgrade will be unable to take advantage of the latest IIS versions unless we provide a work around adjusting the registry keys of IIS.

Ideally WiX should recognize that #Value is an integer comparison, but I'm not sure what solution is easiest/best for you all.

**Comment by robmen** [comment]
This is Windows Installer behavior. It adds the "#" before numeric registry values. To do otherwise requires a custom action to be written... and no one has written replacements for the built-in AppSearch functionality of MSI.

**Comment by BenOSIsoft** [comment]
That's interesting.

Is there not a way for the comparison operator to know that is an integer as well? Currently trying something like IISMAJORVERSION >= 8 - is not true because I think the property value '# 10' is being evaluated as a string and not an integer even though there is a pound sign in front of it.

From your statement, does this mean that functionality will only be possibly using a custom action for the foreseeable future?

**Comment by robmen** [comment]
Unfortunately, yes. Someone is going to need to get the search functionality available in Burn available as CustomActions. It's just work.

**Comment by BenOSIsoft** [comment]
Alright, thanks for your time. I've been a long time user of WiX (around 5 years now), and I really appreciate all the work you all have done and currently are working on.

**Comment by Zarium** [comment]
as an (ugly) workaround in this particular case one could simply exclude early versions of IIS:

<Condition Message="!(loc.IISVersion)"><![CDATA[(IISMAJORVERSION <> "#5") AND (IISMAJORVERSION <> "#6") ]]></Condition>

**Comment by mgroetan** [comment]
Seeing that there's still an open WiX issue for this (https://github.com/wixtoolset/issues/issues/4851/), I've successfully implemented my own custom action to fix this.

WiX markup:
`
    
    <PropertyRef Id="IISMAJORVERSION" />
    <CustomAction Id='Iis.CheckInstalledVersion.SetProperty' Property='Iis.CheckInstalledVersion' Execute='immediate' Value='' />
    
    
    <CustomAction Id='Iis.CheckInstalledVersion' BinaryKey='ServerSetupCA' DllEntry='CheckInstalledIisVersion' Execute='immediate' Return='check' Impersonate='yes' />
    <InstallExecuteSequence>
      <Custom Action="Iis.CheckInstalledVersion.SetProperty"                        Before="LaunchConditions" />
      <Custom Action="Iis.CheckInstalledVersion"                                    After="Iis.CheckInstalledVersion.SetProperty" />
    </InstallExecuteSequence>
    
    <Condition Message="This application requires IIS [Iis.RequiredVersion] or higher. Please run this installer again on a server with the correct IIS version.">
      <![CDATA[Iis.IsRequiredVersion > 0]]>
    </Condition>
`

Custom action implementation:
`
        /// <summary>
        /// The custom action to check the installed IIS version.
        /// </summary>
        /// <param name="session">
        /// The installer session.
        /// </param>
        /// <remarks>
        /// Sets custom properties "Iis.RequiredVersion" and "Iis.IsRequiredVersion".
        /// </remarks>
        /// <returns>
        /// Returns ActionResult.Success when check is successful.
        /// ActionResult.Failure otherwise.
        /// </returns>
        [CustomAction]
        // ReSharper disable once UnusedMember.Global (referenced in custom action fragment)
        public static ActionResult CheckInstalledIisVersion(Session session)
        {
            try
            {
                session.Log("* Starting to check installed IIS version");
                const int IisRequiredVersion = 10;

                string iisMajorVersionFromRegistry = session["IISMAJORVERSION"];
                session.Log(string.Format("*!*! DEBUG; CheckInstalledIisVersion; IIS major version: {0}", iisMajorVersionFromRegistry));
                string iisMajorVersionNumeric = iisMajorVersionFromRegistry.Replace("#", string.Empty);
                int iisMajorVersion = int.Parse(iisMajorVersionNumeric, CultureInfo.InvariantCulture);

                bool isRequiredVersion = iisMajorVersion >= IisRequiredVersion;

                // Setting the required version as a custom property, so that it can be used in the condition message
                session["Iis.RequiredVersion"] = IisRequiredVersion.ToString(CultureInfo.InvariantCulture);
                // Setting the results of the check as "bool"
                session["Iis.IsRequiredVersion"] = isRequiredVersion ? "1" : "0";

                return ActionResult.Success;
            }
            catch (Exception ex)
            {
                session.Log(string.Format("CheckInstalledIisVersion; Error occured: {0}", ex.Message));
                return ActionResult.Failure;
            }
        }
`

I won't bother you with details about configuring a custom action class, as I guess that's common knowledge if you're even considering this approach.

Question: I'm wondering why I had to code the condition like this (that is, the comparison part):
Iis.IsRequiredVersion > 0
I thought that merely referencing the property would evaluate it to "true" only if it was set and contains anything other than "0"?

Note: In my actual code, the condition is located in the "Product.wxs" file, whereas all the custom action stuff is placed in a separate WiX fragment, for readability.

**Comment by BenOSIsoft** [comment]
Since I started this thread, I'll answer your question.

Conditions in WiX are evaluated as TRUE or FALSE based on the condition not 0 and 1 like other languages. That's why simply returning '0' does not work. This can be confusing conditions can be evaluated based on feature states which are simply integers.

Below is more information showing different types of conditions as well as the feature states.

https://msdn.microsoft.com/en-us/library/aa368012(v=vs.100).aspx

**Comment by schalla27** [comment]
https://stackoverflow.com/questions/47838332/launch-condition-custom-action-and-property
Hi I used this example but am getting this error when I add a condition. CDATA[Iis.IsRequiredVersion > 0]]>
Looks like the condition is never true.

**Comment by laurynas-b** [comment]
For those who don't want to do custom actions, another option how to match, version 10+:
`IISMAJORVERSION >= "#10" AND IISMAJORVERSION < "#2"`
