### ISSUE TITLE
Layout to custom directory doesn't copy bundle payload

### ISSUE THREAD

**Issue by res2k** [wixtoolset/issues#5277]
When letting Burn layout to a directory other than the default (i.e. using `SetVariableString (L"WixBundleLayoutDirectory", ...)`) the bundle is copied from the clean room, i.e. any payload is missing.
- Which version of WiX are you building with?

> 3.10.3 (built from wix3103 branch)
- Which version of Visual Studio are you building with (if any)?

> VS 2013 Update 1
- Which version of .NET are you building with?

> n/a
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7
- Describe the problem and the steps to reproduce it.

> The bootstrapper application needs to set the `WixBundleLayoutDirectory` variable to some value other than the default. When performing the layout the engine will then copy the bundle executable from the clean room (the copied file is smaller than it should be; it's also clear from the logs).
- Describe the behavior you expected and how it differed from the actual behavior.

> The engine should copy the bundle executable from the original source path so it includes all payloads.

**Comment by BMurri** [comment]
Does this issue need to be ported to wix4?

**Comment by rseanhall** [comment]
I cherry picked it into wix4 - https://github.com/wixtoolset/wix4/pull/216

**Comment by BMurri** [comment]
Then it appears this bug needs to be closed as fixed

**Comment by rseanhall** [comment]
yep, thanks
