### ISSUE TITLE
Shortcuts x64 version

### ISSUE THREAD

**Issue by WojciechKarbowski** [wixtoolset/issues#5278]
When we are creating shortcuts in x64 version  for one file last one is not created in start Page (Windows 8.1 Pro) .
## Bugs

If this issue is a bug:

BUG

* Which version of WiX are you building with?

Version 3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

I am compiling from command line .

* Which version of .NET are you building with?

not aplicable

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windiows 8 Pro 64 bit

InstallerVersion="200"

I am creating 3 shortcuts for one file, one on desktop, and two on startpage. On startpage always appear first one secend one is random (or last on list with Wizzard argument). There are no bugs in log file. On x86 version this is not appear -shortcuts is always created.

But if i will right click on first shortcut (on Start Page) then ill select open containg foler, there will be both. So maybe it has not been refreshed. Moreover if i will reboot system shortcut will appear,on the beggining it is not shown but we see that start page it is refreshing then it is appear.

Also important is that on test maschines we are rebuilding over and over again the same build version.

Example code

```
<Directory Id="" Name="$(var.Product_Name)" >
<Component Id="MainExecutable" Guid".." Win64="yes">
<File Id="file.exe" Source="..\..\Release\build\file.exe" Name="file.exe" KeyPath="yes" Win64="yes">
<Shortcut Id="AppProgramMenu" Directory="ProgramMenuDir" Name="$(var.Product_Name)" WorkingDirectory="INSTALLFOLDER" Icon="ICON_APP_C.ICO" IconIndex="0" Advertise="yes"/>
<Shortcut Id="DesktopShortcut" Directory="DesktopFolder" Name="$(var.Product_Name)" WorkingDirectory="INSTALLFOLDER" Icon="ICON_APP_C.ICO" Advertise="yes" IconIndex="0" />
<Shortcut Id="AppProgramMenuWizard" Directory="ProgramMenuDir" Name="$(var.Product_Name) Wizard" WorkingDirectory="INSTALLFOLDER" Icon="ICON_APP_C.ICO" Arguments="-wizard " Advertise="yes"/>
</File>
```
for  x86 verson i am removing win64...

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

 In my opinion it should work in the same way for x86 and x64 version. For x86 shortcuts always appear on start page on 64 bits it is 10 %.

Update :

if i will uninstall previous then reeboot computer, build new version install it then it is always apopears.

My conclusion
For shure it is matter of some kind of update of Windows x64 start page.  

Update 1:
I found info that this may be Windows Explorer problem and this situation sometimes appear so please  cosnider also this subject. 
http://answers.microsoft.com/en-us/windows/forum/windows8_1-performance/force-refresh-of-start-menu-start-screen-in/ee4e36d2-91d0-4f34-9eb8-b17ab096e83c?auth=1

Generaly if i will manualy restart windows explorer task icon will appear on start page. Maybe it is problem that start menu is refreshed when there are created first shortcut, but it supose after second one (or even last one).

**Comment by robmen** [comment]
Why do you consider this a WiX Toolset issue? The WiX Toolset creates the MSI but the Windows Installer is responsible for actually executing the install and the WiX Toolset doesn't contribute any code to Windows Explorer.

**Comment by WojciechKarbowski** [comment]
It is very possible. On the beggining i was almost shure tat it is matter of variable or any value of shotcut. Now i see that the problem is in order of refrehing after adding shortcut. It was eveolwing during my research  of the problem.
