### ISSUE TITLE
Heat fails without MSBuild tools 12.0 (2013)

### ISSUE THREAD

**Issue by ulabs-sgiroux** [wixtoolset/issues#5283]
Heat requires ms build tools 12, and will fail if VS2015 is installed

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

> Visual studio community 2015 Update 2 14.0.25123.00

* Which version of .NET are you building with?

> 4.6.01055
Also Framework 4.5 SDK, 4.5.1 SDK, 4.6.1 & 4.6.1 SDK are installed

* Describe the problem and the steps to reproduce it.

1. Start with the latest Visual Studio 2015 Community Edition. 
2. Install WiX 3.10.2.2516
3. Attempt to run Heat to harvest a csproj file (e.g. PS C:\> heat project .\funproject.csproj -pog Binaries -ag template:fragment -o temp.wxs)
4. Note "heat.exe : error HEAT5316 : Failed to load MSBuild wrapper object: Could not load file or assembly 'Microsoft.Build, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find thefile specified."
5. Note MS Build tools 14 install with the latest visual studio / .NET development tools
6. Install MS Build tools 12
7. Repeat step 3 and observe it succeed

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected WiX to load any Microsoft.Build version and not rely on an older version. If this was stated in getting started or a software requirements page, I would have installed the right build tools immediately. It seems as if other utilities such as candle and light work fine when run from visual studio.

**My issues are solved, however this remains a potential issue**

**Comment by rseanhall** [comment]
I explained why heat behaves this way in #4853.  I'll leave it for triage to decide whether heat should try to use a different version of MSBuild than what is specified in the `ToolsVersion` attribute in the harvested project.

**Comment by ulabs-sgiroux** [comment]
Thank you, for my reference the csproj ToolsVersion is 12.0 and the target framework is 4.5. Visual studio seemed to be able to build the project without msbuild 12.

I think that resolves this issue so long as this is intended operation. Thank you very much for your quick response. I tried searching the issue database but did not come across that case.

**Comment by jnm2** [comment]
What's the timescale for this fix?

**Comment by rseanhall** [comment]
If you listen to the [triage meeting](https://youtu.be/WL_SUwbBCzI?t=16m12s), we decided that heat is already doing the right thing by using the tools version specified in the project file.  There are no plans to change this behavior - either install the right version of the MSBuild tools or edit the project file to specify the version of the MSBuild tools that you already have installed.
