### ISSUE TITLE
bug with custom actions and XP 

### ISSUE THREAD

**Issue by oren-cybereason** [wixtoolset/issues#5284]
Hi,

We are using visual studio 2015 with wix 3.10.2015.

when installing on a win7 32 bit we have no issues 

when installing on XP we get the following error when calling the custom action in the dll.

	Action start 16:03:50: MyCustomAction.
	Action ended 16:03:51: MyCustomAction. Return value 3.
	Action ended 16:03:51: INSTALL. Return value 3.

	
here is the declaration from the customAction.cpp file :

    extern "C" _declspec(dllexport) UINT __stdcall MyCustomAction(MSIHANDLE hInstall);
    
    extern "C" UINT __stdcall MyCustomAction(MSIHANDLE hInstall)
    {
        HRESULT hr = S_OK;
        UINT er = ERROR_SUCCESS;
    	// commented out code 
        return WcaFinalize(er);
    }

```

 <CustomAction Id='myCustomAction'
                   BinaryKey='CustomActions'
                   DllEntry='MyCustomAction'
                   Execute='immediate'
                   Return='check'/>
```

				  
```

<InstallExecuteSequence>
            <Custom Action="myCustomAction" After='AppSearch' ></Custom>
</InstallExecuteSequence>
```

Any ideas ? clues ? directions would be extremely appreciated 
declaration in wxs file:

Any ideas ? clues ? direcions would be extremly appreciated

**Comment by barnson** [comment]
For support, please send mail to the wix-users mailing list.
