### ISSUE TITLE
Wix Namespace Link Broken

### ISSUE THREAD

**Issue by StilgarISCA** [wixtoolset/issues#5288]
The [documentation](http://wixtoolset.org/documentation/manual/v3/xsd/wix/) says that the XML namespace link (xmlns) should be http://schemas.microsoft.com/wix/2006/wi However this link 404's.

Steps to reproduce:
- Paste the schema link into your web browser ;)

Expected result:
- A document detailing the namespace loads.

Actual result:
- 404

**Comment by robmen** [comment]
XML namespaces need to be unique. They do not need to actually resolve to an actual document (although it is cool when they do).
