### ISSUE TITLE
WIX_DIR_COMMON_DOCUMENTS evaluated to 'D:\'

### ISSUE THREAD

**Issue by hosebr** [wixtoolset/issues#5290]
Bug:
When using WIX_DIR_COMMON_DOCUMENTS in a WiX project, it is evaluated to be 'D:\' - see this excerpt from the installation log file:

MSI (c) (0C:1C) [11:28:18:092]: PROPERTY CHANGE: Adding TARGETDIR property. Its value is 'D:\'.
MSI (c) (0C:1C) [11:28:18:092]: PROPERTY CHANGE: Adding WIX_DIR_COMMON_DOCUMENTS property. Its value is 'D:\'.
MSI (c) (0C:1C) [11:28:18:092]: PROPERTY CHANGE: Adding INSTALLFOLDER property. Its value is 'D:\SetupProject1\'.
MSI (c) (0C:1C) [11:28:18:092]: Target path resolution complete. Dumping Directory table...
MSI (c) (0C:1C) [11:28:18:092]: Note: target paths subject to change (via custom actions or browsing)
MSI (c) (0C:1C) [11:28:18:092]: Dir (target): Key: TARGETDIR	, Object: D:\
MSI (c) (0C:1C) [11:28:18:092]: Dir (target): Key: WIX_DIR_COMMON_DOCUMENTS	, Object: D:\
MSI (c) (0C:1C) [11:28:18:092]: Dir (target): Key: INSTALLFOLDER	, Object: D:\SetupProject1\

WiX 3.10.2.2516 on Windows 7 with VS 2015 U2 (using 2010 toolset version). Minimal VS project and the resulting installer is attached in ZIP-compressed archive.

Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

.NET version unknown (versions up to 4.6.1 installed).

Thanks for looking into this!

[SetupProject1.zip](https://github.com/wixtoolset/issues/files/254652/SetupProject1.zip)

**Comment by barnson** [comment]
You're missing a `PropertyRef`. The doc says:

> To use these custom actions you simply need to add a <PropertyRef> to the property you want to use and then include WixUtilExtensions when linking.

**Comment by hosebr** [comment]
Where do I need to put the PropertyRef? Including the line
    <PropertyRef Id="WIX_DIR_COMMON_DOCUMENTS" />
in the Product tag (as in the original example) or also in each fragment has no effect.

**Comment by robmen** [comment]
For support please contact wix-users@lists.wixtoolset.org

**Comment by hosebr** [comment]
Hi,
the problem is that the msi setup cannot put its custom action DLL into the user's temporary folder on my PC for some obscure reason. It there any way that WiX can check for this problem? Otherwise, there is no hint for the user that the installation failed.
Thanks!

**Comment by hosebr** [comment]
My final comment on the matter:
The "obscure reason" things stopped working may be a side-effect of MS updates KB3136000, KB3139923, KB3139852, KB3139398, KB3140410, KB3114887, KB3138910, and KB3139914. The problem vanished when installing a further set of updates.
However, I still think that WiX doesn't handle the case of missing custom action DLLs well. Please correct me if this is out of the hands of the WiX developers because the problem occurs at the msiexec stage.

**Comment by robmen** [comment]
The WiX Toolset provides custom action DLLs to be used in your MSI but the Windows Installer is responsible for extracting and loading them from the MSI. Unfortunately, there is no code from WiX that can execute before the Windows Installer accomplishes the extraction and loading of our DLLs.

This is fully a Windows problem... so we're at their mercy.
