### ISSUE TITLE
"ResolveWixReferences" task could not be loaded

### ISSUE THREAD

**Issue by sameera** [wixtoolset/issues#5291]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3.2094

* Which version of Visual Studio are you building with (if any)?

> 2015 Pro

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/a

* Describe the problem and the steps to reproduce it.

I'm having the same issue as described in 
[#5289](https://github.com/wixtoolset/issues/issues/5289)
I saw that the issue was closed with the comment that the problem was not setting the WixToolPath; which I assume is a reference to the steps in:
[Setting up daily builds](http://wixtoolset.org/documentation/manual/v3/msbuild/daily_builds.html)

But, IIUC, these steps are for build machines where user doesn't want to setup Wix Toolset on this machine. However, I'm only trying to build my project locally where the toolset is already installed.

In fact, I only have this issue with the latest version of Wix 3.10.3.2094. On another dev machine we have 3.10.2516 (by wix.dll version number) which builds the same project just fine. In VS, when I double click the build error, I'm taken to wix2010.targets which has:

```
<WixInstallPath Condition=" '$(WixInstallPath)' == ''">$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Installer XML\3.11@InstallRoot)</WixInstallPath>
    <WixInstallPath Condition=" '$(WixInstallPath)' == ''">$(Registry:HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows Installer XML\3.11@InstallRoot)</WixInstallPath>
```

I checked the registry and there is no 3.11 key. There is a 3.10 key which has the absolute path to wix bin folder. I experimented by fixing the reference in wix2010.targets; which got me past the missing wixtasks.dll error. But, now gives the following error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveWixReferences" task was not found. Check the following: 
1.) The name of the task in the project file is the same as the name of the task class. 
2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 
3.) The task is correctly declared with <UsingTask> in the project file,
 or in the *.tasks files located in the "C:\Program Files (x86)\MSBuild\14.0\bin" directory.	
....	C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets	735	
```

**Comment by barnson** [comment]
A couple of 3.11 references came in during the .NET Foundation relicensing.

**Comment by meettoamar** [comment]
Just try to 3 steps
1) Remove Tools folder of Wix and close the VS2017
2) Open again VS2017 and reload the project.
3) Try to build again . It should work.
