### ISSUE TITLE
Create separate feed for minor releases of WiX

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#5292]
Currrently, v3.10.2 is the latest stable release but we are working on v3.10.3.  When users download v3.10.2, they are prompted to upgrade to the development release of v3.10.3.  Until the minor release is declared stable, it should not be provided as an upgrade to the previous stable release.

Proposed solution:
Create a 3.10.3 feed and publish development releases to it.  Remove previous 3.10.3 versions from the 3.10 feed.  Add 3.10.3 to the 3.10 feed when it's officially released.

**Comment by jchoover** [comment]
Another option would be to extend the feed with an attribute to indicate it's a daily/pre-release build, and allow the BA to decide if it wants to consider it for an update.
