### ISSUE TITLE
bootstrapper is deleted prematurely on upgrade, causing the install to fail

### ISSUE THREAD

**Issue by squirmy** [wixtoolset/issues#5298]
Hi,

We're experiencing another issue with the bootstrapper being deleted prematurely which looks semi related to #5238, but it is happening at a later point. I see there are some changes that have been done to address this, but just wanted to submit my logs to make sure this is covered.

Building with:
Wix 3.10.1.2213 (for the currently installed bootstrapper)
Wix 3.10.2.2516 (for the upgrade bootstrapper)
Visual Studio 2015 Update 2
.NET 4.0

Installing on:
Windows XP

The problem is that the installer fails to perform an upgrade as the source seems to be deleted before it can use it. Here are the logs:

[RWWA_Terminal_20160518130918.txt](https://github.com/wixtoolset/issues/files/271663/RWWA_Terminal_20160518130918.txt)
[RWWA_Terminal_20160518131005.txt](https://github.com/wixtoolset/issues/files/271662/RWWA_Terminal_20160518131005.txt)

**Comment by barnson** [comment]
Please try [WiX v3.10.3 RC](http://wixtoolset.org/releases/v3-10-3-2917/) to make sure the issue is fixed.

**Comment by squirmy** [comment]
We'll definitely upgrade and check it out - just can't do it at the moment as we're needing to get a release out. So for now we'll stay on version 3.10.1. We should be in a position to test this in a week or two.

I reported it in case it was helpful in identifying another scenario which may not have been addressed in the changes already made.

**Comment by barnson** [comment]
We have a new RC release: http://wixtoolset.org/releases/v3-10-3-3007/. Please take a look so we know your issue is fixed.
