### ISSUE TITLE
Mapping ExitCode 3010 for NetFx installer does not work

### ISSUE THREAD

**Issue by Laniusexcubitor** [wixtoolset/issues#5299]
Building with WiX 3.8.1128.0, Visual Studio 2015 Update 2, .Net 4.0
Installing on Windows 7 Build 7601

I am using ExitCode mappings to define a forceReboot after installation of NetFx 4.5.1:
&lt;ExitCode Value="1641" Behavior="forceReboot"/&gt;
&lt;ExitCode Value="3010" Behavior="forceReboot"/&gt;
&lt;ExitCode Value="0" Behavior="success"/&gt;
&lt;ExitCode Behavior="error"/&gt;

When installing on Windows 7 with installed NetFx 4.0 the NetFx 4.5.1 installer will require a reboot which according to the above ExitCode mapping should occur immediately. But the mapping is not used and I will get a "restart: Required" instead of a "restart: Initiated"
Log:
 [0C14:0370][2016-05-19T15:11:32]e000: Error 0x80070bc2: Process returned error: 0x80070bc2
[0C14:0370][2016-05-19T15:11:33]e000: Error 0x80070bc2: Failed to execute EXE package.
[0C28:068C][2016-05-19T15:11:33]i319: Applied execute package: NetFx451Redist, result: 0x0, restart: Required

I think when checking for the mappings there is some difference from the fallback check that checks for the default codes (1641, 3010 etc.) as the default code mapping seems to work (the 3010 result is recognized as RestartRequired).

**Comment by barnson** [comment]
Please try with the latest stable release (WiX v3.10.2).

**Comment by Laniusexcubitor** [comment]
Tried with WiX v3.10.2. No change.

I just posted a pull request for this small fix :)

**Comment by Laniusexcubitor** [comment]
Exitcode can be set to HResult since 3.9 (see #4319) Did not try that with 3.10… only with 3.8.
So using
&lt;ExitCode Value="3010" Behavior="forceReboot"/&gt;
&lt;ExitCode Value="-2147021885" Behavior="forceReboot" /&gt;
&lt;ExitCode Value="0" Behavior="success"/>
&lt;ExitCode Behavior="error"/&gt;
is the right thing to do.

**Comment by daveobike** [comment]
> Exitcode can be set to HResult since 3.9 (see #4319) Did not try that with 3.10… only with 3.8.
> So using
> <ExitCode Value="3010" Behavior="forceReboot"/>
> <ExitCode Value="-2147021885" Behavior="forceReboot" />
> <ExitCode Value="0" Behavior="success"/>
> <ExitCode Behavior="error"/>
> is the right thing to do.

For anyone that ends up here researching the same mapping error code issue. For a .net 4.7.2 install with Windows 10 >= 1607 the error code returned is 0x80070bc2 (same as described in this issue). However I believe @Laniusexcubitor had a typo on the HResult value. The signed decimal conversion is -2147021886 not 2147021885 as described above. So the additional ExitCode line would be

ExitCode Value="-2147021886" Behavior="forceReboot" /> in place of the -2147021885

Or at least, when I changed the exit code to -2147021886, from -2147021885, it properly forced a reboot. Where it was not rebooting with -2147021885
