### ISSUE TITLE
Unable to build WiX project after upgrade to 3.10.3.2917

### ISSUE THREAD

**Issue by MarkStega** [wixtoolset/issues#5303]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* WiX Version 3.10.3.2917

*  VS2015 Community Update 2 with .Net Core Tools 

[WiX.zip](https://github.com/wixtoolset/issues/files/275904/WiX.zip)

Preview 1

* .Net V4.5

* Describe the problem and the steps to reproduce it.

I had a working WiX setup project hosted in a VS2015 solution. I upgraded from WiX 3.10.2.2516 to WiX 3.10.3.2917. Now the WiX project fails to build. I am reasonably certain that it is not an issue with the WiX tools as I can run heat, candle, and light from the command line without an issue. On my production build system with the same versions of .Net and Visual Studio (including the .Net Core Tools Preview 1) but with WiX 3.10.2.2516 the project builds without issue.

The error is:

Severity -- Error
	
Code

Description -- The "WixAssignCulture" task could not be loaded from the assembly \WixTasks.dll. Could not load file or assembly 'file:///D:\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask

Project -- WiX

File	-- C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets

Line -- 2303

Suppression State

I've attached the project file and the wxs and xslt source files.

[Edit] Uninstalling WiX 3.10.3 and installing Wix 3.10.2 resolves the issue

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

**Comment by barnson** [comment]
I can't reproduce this. Can you try another upgrade and if it repros, repair v3.10.3 and report back?

**Comment by MarkStega** [comment]
After upgrading again to 3.10.3.2917 the issue does not reproduce for me.

**Comment by ezequielsvelez** [comment]
Hello,
I was able to reproduce this issue on Wix Toolset v3.10.4.4718

Error message:
 C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets(2303,5): error MSB4062: The "WixAssignCulture" task could not be loaded from the assembly C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=**********' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

Could you provide any additional information, to troubleshoot this issue?

Thanks in advance!

**Comment by MarkStega** [comment]
You might try what I did which was to revert to an earlier version of Wix and then reapplying the upgrade.

**Comment by ezequielsvelez** [comment]
Hello Mark,

Thanks for your answer, I tried to revert to a previous version ante then upgrade without success. Finally, I decided to move to wix 3.11.
Not proud about that, but I needed to generate an installer quickly.

Regards.
