### ISSUE TITLE
None of the projects in wix310-debug.zip load in visual studio because of missing "C:\tools\WixBuild.props"

### ISSUE THREAD

**Issue by slynch8** [wixtoolset/issues#5304]
Bug:

WiX Toolset v3.10.2
Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2

Downloaded Source Code wix310-debug.zip from here:
https://wix.codeplex.com/releases/view/619491

All projects fail to load in Visual Studio because they can't find this props file: "C:\tools\WixBuild.props"

Here is the error message:

---------------------------
Microsoft Visual Studio
---------------------------
Unable to read the project file "balutil.vcxproj".

C:\Users\Stewart\Downloads\wix310-debug\src\libs\balutil\balutil.vcxproj(40,3): The imported project "C:\tools\WixBuild.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
---------------------------
OK   
---------------------------

Stewart Lynch
slynch@puredevsoftwre.com
PureDev Software

**Comment by barnson** [comment]
The -debug.zip is intended for reference only. If you want buildable code, clone the GitHub repo and build wix.proj in the root.
