### ISSUE TITLE
"Program file" is replaced by "Program file (x86)"

### ISSUE THREAD

**Issue by maliutin** [wixtoolset/issues#5305]
WiX version: 3.10.3.2917
Visual Studio version: 2015 Update 2
.NET version: 3.5

Our program is installed in Windows 10 x64 with MS Word 2013 x86.
But the base configuration is Windows 8.1 x64 and MS Word 2013 x86. The windows was updated to version 10.
This fact is important because after that Word x86 has location “C:\Program Files\Microsoft Office\root\Office15\”. We can see it in the registry:
![msi-001](https://cloud.githubusercontent.com/assets/10669340/15472644/e21e9552-2104-11e6-9e97-9e47dbec06fb.png)

Thus, our installer should detect that the user computer has the installed Word 2013 x86.
For this we used the standard scenario:
```XML
<Property Id="HOSTPATH">
  <RegistrySearch Id="RegSearch_HOSTEXE" Root="HKLM" Key="SOFTWARE\Microsoft\Office\15.0\Word\InstallRoot" Name="Path" Type="directory">
    <FileSearch Name="WINWORD.EXE" />
  </RegistrySearch>
</Property>
<Condition Message="!(loc.HostConditionMessage)"><![CDATA[Installed OR HOSTPATH]]></Condition>
```
And in result this condition does not pass.
To found the problem I used procmon.exe and found that the installer looks for WINWORD.EXE in another folder:
![msi-002](https://cloud.githubusercontent.com/assets/10669340/15472874/e4f7aac4-2105-11e6-8aaf-ef295da2101c.png)
The installer tries to find “C:\Program Files (x86)\Microsoft Office\root\Office15\” but the registry contains “C:\Program Files\Microsoft Office\root\Office15\” value.

In result the installer can not find WINWORD.EXE file and the condition can not pass.

**Comment by robmen** [comment]
For support, please contact wix-users@lists.wixtoolset.org
