### ISSUE TITLE
Warn against using ServiceConfig and ServiceConfigFailureActions

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5306]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> n/a

* Which version of Visual Studio are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> n/a

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7 and later

* Describe the problem and the steps to reproduce it.

> The [`MsiConfigureServices` doc](https://msdn.microsoft.com/en-us/library/windows/desktop/dd407945%28v=vs.85%29.aspx) warns against using the feature because "this functionality is not working as expected."(!)

* Describe the behavior you expected and how it differed from the actual behavior.

> Well, I'd expect engine features to, you know, work as expected, but failing that, the WiX doc should warn against using them. Maybe make it a compiler warning?

**Comment by BMurri** [comment]
The pull requests in wix3 and wix4 purported to resolve this appear to both be closed after having been applied to their respective develop branches. Shouldn't the bug be closed, too?

**Comment by barnson** [comment]
Yep.
