### ISSUE TITLE
Burn built-in SystemFolder and System64Folder properties reversed

### ISSUE THREAD

**Issue by RGBradford** [wixtoolset/issues#5307]
In WIX 3.10.2, the values of the Burn `SystemFolder` and `System64Folder` built-in properties are reversed when compared to similar properties in Windows Installer.

In Windows Installer, the built-in property <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/aa372055(v=vs.85).aspx">SystemFolder</a> typically resolves to `C:\Windows\System32` on 32 bit operating systems and `C:\Windows\SysWow64` on 64 bit operating systems.  In Burn the `SystemFolder` property always resolves to `C:\Windows\System32`.

In Windows Installer, the built-in property <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/aa372054(v=vs.85).aspx">System64Folder</a> typically resolves to `C:\Windows\System32` on 64 bit operating systems and is not used on 32 bit operating systems.  In Burn the `System64Folder` property resolves to `C:\Windows\SysWow64` on 64 bit operating systems.

This makes detecting the presence of 32 bit files in Burn more complicated than necessary,  For example to detect the presence of the 32 bit file in a system folder requires two `util:FileSearch` elements:

```
<util:FileSearch Id="FileExistsOnX64" Condition="VersionNT64" Variable="myFileExists" Path="[System64Folder]MyFile.dll" Result="exists"/>
<util:FileSearch Id="FileExistsOnX86" Condition="NOT VersionNT64" Variable="myFileExists" Path="[SystemFolder]MyFile.dll" Result="exists"/>
```

**Comment by phillHgl** [comment]
I did not see where System64Folder is documented as a Burn Variable in the chm.  I did see it in the source.
