### ISSUE TITLE
Wixlib built by LIT from multiple wixlibs is invalid

### ISSUE THREAD

**Issue by gshirreffs** [wixtoolset/issues#5311]
Working with Wix 3.10

When I combine multiple wixlibs into one wixlib, the resulting wixlib is not correctly processed by light.

The source code for lit.cs indicates that this is meant to be a supported action (line 189).

But there is no attempt to combine the sections loaded from the constituent libraries; sections are simply appended to the SectionCollection, and then when the new library is written, it effectively becomes no more than a concatenation of the constituent libraries.  e.g.

```
<wixLibrary>
  <section type="fragment">
    <table name="Component>
      .
      .
      .
    </table>
  </section>
  <section type="fragment">
    <table name="Component>
      .
      .
      .
    </table>
  </section>
</wixLibrary>

```

The linker then only finds the Component table in the first section.  If I manually adjust the resulting wixlib so that all of the rows from the second Component table are move to the first, then the resulting wixlib works fine.

```
<wixLibrary>
  <section type="fragment">
    <table name="Component>
      .
      .
      .
      <!-- stuff from second library here -->
      .
      .
      .
    </table>
  </section>
</wixLibrary>

```

It would seem to me that the Librarian.Combine(SectionCollection) function needs to actually merge the source sections and tables into the target, rather than just appending them.

**Comment by barnson** [comment]
A .wixlib is a collection of sections so there's no need to merge. And I have no problem getting a symbol from other sections in a .wixlib. Please provide an [MVCE](http://stackoverflow.com/help/mcve) that shows the problem you're experiencing.

**Comment by barnson** [comment]
If you can provide an example that shows a problem with the current structure, we can reopen the bug at triage.
