### ISSUE TITLE
Allow custom ProjectDefineConstants defined as properties

### ISSUE THREAD

**Issue by kzu** [wixtoolset/issues#5313]
If someone wants to define custom define constants for the WiX compilation as properties, like:

```
<PropertyGroup>
  <ProjectDefineConstants>
    MyConstant=SomeValue;
    $(ProjectDefineConstants)
  </ProjectDefineConstants>
</PropertyGroup>
```

They are out of luck because the WiX targets redefine the property without appending to whatever value was already defined (unlike the code above). See https://github.com/wixtoolset/wix3/blob/develop/src/tools/WixTasks/wix2010.targets#L436

* Which version of WiX are you building with?

> v3.10.2 (but this happens in all previous versions AFAIK

* Which version of Visual Studio are you building with (if any)?

> VS2015 Update 2

* Which version of .NET are you building with?

> .NET v4.0, 4.5.2 and 4.6

**Comment by rseanhall** [comment]
The `DefineConstants` property is already available for the developer to specify constants like this.

**Comment by kzu** [comment]
Good point :)
