### ISSUE TITLE
error LGHT0103 : The system cannot find the file

### ISSUE THREAD

**Issue by prees1** [wixtoolset/issues#5314]
Windows Installer XML Toolset Linker version 3.10.2.2516
 .NET Framework 4.0

```
wine ../../wix/heat.exe dir lib -gg -sfrag -cg Library -o lib.wsx -dr INSTALLDIR
wine ../../wix/candle.exe ddd-tools.wsx lib.wsx
wine ../../wix/light.exe -ext WixUIExtension -ext WixUtilExtension ddd-tools.wixobj lib.wixobj -b lib -o tools.msi
```

error LGHT0103 : The system cannot find the file 'Z:\home\wix\dddtools\ddd-tools-0.7.0-win32\lib\ruby\lib\ruby\gems\2.2.0\gems\bundler-1.9.9\lib\bundler\Class3PublicPrimaryCertificationAuthority.pem'.

If I change the file:
`\home\wix\dddtools\ddd-tools-0.7.0-win32\lib\ruby\lib\ruby\gems\2.2.0\gems\bundler-1.9.9\lib\bundler\Class3PublicPrimaryCertificationAuthority.pem`
to
`\home\wix\dddtools\ddd-tools-0.7.0-win32\lib\ruby\lib\ruby\gems\2.2.0\gems\bundler-1.9.9\lib\bundler\short.pem`
it works.
If I change it to
`\home\wix\dddtools\ddd-tools-0.7.0-win32\lib\ruby\lib\ruby\2.2.0\rubygems\ssl_certs\looooooooooooooooooooooooooooooooooooooog.pem`
it fails again.

It appears the issue is the filepath length.
Any solutions or ways around this?

Thanks

**Comment by barnson** [comment]
Works for me on Windows 7 SP1.

**Comment by prees1** [comment]
I should mention I am running this via wine. Do you think that could be the issue?

**Comment by barnson** [comment]
I'm not aware of anyone working on WiX who uses Wine, so it's definitely not something we explicitly support. I'm not aware of any path restrictions Wine imposes, though WiX inherits the typical Windows 260-character limit.

**Comment by prees1** [comment]
Ok thanks @barnson. I will look into whether or not this issue is Wine dependent.

**Comment by kacf** [comment]
I was able to get around these issues by:

* Using Wine 32-bit (wine:i386 on Debian). 64-bit does not work because of the "dotnet" below.
* Running `winetricks dotnet45` and click through all the boxes and instructions.

After this I was able to run both `candle.exe` and `light.exe` successfully.

**Comment by prees1** [comment]
Very interesting. I will give this a shot and see how it goes. Thanks for sharing!

**Comment by kacf** [comment]
Also note that the maximum file path length appears to be only 128 characters, and you'll get messages about files not found if you exceed it (not uncommon if you use Jenkins). But maybe this is a problem on native Windows too, I'm not sure. Using a shorter path appears to work.

**Comment by qlik-pwe** [comment]
@barnson With newer windows10 buildswe are supposed to be able to use path names longer than 260 characters.  Should we expect the the WiX binaries to just work, or will they require a re-build?

**Comment by robmen** [comment]
@qlik-pwe Sounds like a great thing you could investigate and if changes are necessary provide a PR for WiX v4

**Comment by qlik-pwe** [comment]
@robmen Sounds fun, but for now i am not succeeding in getting Win10 to play nicely.  I have Win10 1607 installed and have set Tthe registry and group policy settings I have read about (below) but still cannot list long filenames via cmd not delete them via explorer. #StillFiguringOutEnvironmentIssues
 Policy set:
Configuration\Administrative Templates\System\Filesystem Enable Win32 long path :ennabled
Registry:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem  "LongPathsEnabled"=dword:00000001

**Comment by qlik-pwe** [comment]
Taking a quick peek.  Tried compiling wix for the first time works.  Setting the config overrides gets a different error.  Looks like some Calls to ShortPathName() functions...
heat.exe : error HEAT0001 : Capacity exceeds maximum capacity.
Parameter name: capacity

Exception Type: System.ArgumentOutOfRangeException

Stack Trace:
   at System.Text.StringBuilder.ReplaceBufferInternal(Char* newBuffer, Int32 newLength)
   at WixToolset.Extensions.UtilFinalizeHarvesterMutator.NativeMethods.GetShortPathName(String longPath, StringBuilder shortPath, Int32 buffer)
   at WixToolset.Extensions.UtilFinalizeHarvesterMutator.NativeMethods.GetShortPathName(String fullPath) in D:\github\wix4\src\ext\UtilExtension\wixext\UtilFinalizeHarvesterMutator.cs:line 1088
   at WixToolset.Extensions.UtilFinalizeHarvesterMutator.MutateFiles() in D:\github\wix4\src\ext\UtilExtension\wixext\UtilFinalizeHarvesterMutator.cs:line 997
   at WixToolset.Extensions.UtilFinalizeHarvesterMutator.Mutate(Wix wix) in D:\github\wix4\src\ext\UtilExtension\wixext\UtilFinalizeHarvesterMutator.cs:line 101
   at WixToolset.Mutator.Mutate(Wix wix) in D:\github\wix4\src\tools\wix\Mutator.cs:line 69
   at WixToolset.Tools.Heat.Run(String[] args) in D:\github\wix4\src\tools\heat\heat.cs:line 136

**Comment by barnson** [comment]
`private const int MaxPath = 255;` in wix4\src\ext\UtilExtension\wixext\UtilFinalizeHarvesterMutator.cs.

Probably not the only instance of that.

**Comment by qlik-pwe** [comment]
Hmm.  Need to go deeper, I guess.  Light.exe will work with these changes but When it is called from Wix.Tasks.dll the 'file not found' error returns.  Copying the command line that WixTasks says it is calling, the error goes away.

**Comment by barnson** [comment]
Try setting `RunWixToolsOutOfProc` to `true` in the .wixproj. It's false by default and runs the tool as a thread for perf gains. But it probably needs work for LFNs.

**Comment by qlik-pwe** [comment]
Awesome.  Thanks @barnson !  That allows me to use these changes in v3 and v4.  I still need to get test.bat to run in either but will try to get this in.

**Comment by qlik-pwe** [comment]
Trying to get teset.bat to run, I searched a bit and found a thread indicating that test.bat doesn't build outside of MS?  Also, the strong-name signed build instructions point to code under Votive which I don't see under the dev tree..  If I have a build that fixes this issue and builds in both build and release configurations, is that enough to start a PR? 
http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/2016-December/000560.html

**Comment by barnson** [comment]
Yeah, that should be fine. You might try building from a checkout that has >MAXPATH paths, as building WiX builds the WiX MSIs and bundle, so you'll get some code exercise that way. BTW, can you point to "strong-name signed build instructions"? There are some Votive-specific InternalsVisibleTo as I recall, but that shouldn't affect the rest.

**Comment by qlik-pwe** [comment]
@barnson  The instructions I was looking at are here http://wixtoolset.org/development/building-wix/ 
I see reference to src\Votive which I don't get from the repo.  Am I reading that incorrectly?  Thx.

**Comment by syedhassaanahmed** [comment]
@prees1 I got the same error as you while trying to run wix with Wine. Did you find a workaround for long filenames?

**Comment by qlik-pwe** [comment]
I can get the executable to handle the long filenames with the code change above but then Wix.targets fails in cleanCore when it tries to find files using FindUnderPath, an msbuild task.  I'm not sure if this task can be updated or if msbuild needs to be updated.

**Comment by prees1** [comment]
I never found a solution. I have since been using Appveyor and the wix
installation included there instead of wine.

On Sep 13, 2017 9:31 AM, "Syed Hassaan Ahmed" <notifications@github.com>
wrote:

@prees1 <https://github.com/prees1> I got the same error as you while
trying to run wix with Wine. Did you find a workaround for long filenames?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/wixtoolset/issues/issues/5314#issuecomment-329168420>,
or mute the thread

**Comment by yamlfd** [comment]
I‘m on Windows 7 SP1 Enterprise and WiX 3.11 and the paths are really longer. How soon can we get this issue resolved? It is a blocker and I cannot change the underlying software. The software itself has no issues with this long path, it is just HEAT.

**Comment by yamlfd** [comment]
@barnson : Can you help here, please?

**Comment by barnson** [comment]
I'd be happy to review a pull request, @yamlfd.

**Comment by yamlfd** [comment]
I cannot develop WiX Toolkit itself.

**Comment by mwiesiolek** [comment]
I have encountered the same issue

**Comment by yiyimi** [comment]
I have encountered the same issue......

**Comment by wstaelens** [comment]
I have encountered the same issue...………...

**Comment by wstaelens** [comment]
https://github.com/wixtoolset/issues/issues/4365/

**Comment by keeganwitt** [comment]
I had this happen on Windows 10 (using the Visual Studio 2017 plugin), with a path that wasn't particularly long (100 characters)
`The system cannot find the file ' C:\Users\Keegan\Documents\GitHub\groovy-wix\apache-groovy-docs\html\documentation\json-builder.html' with type ''.`
I tried adding the below XML to the wixproj file, but it didn't help
```xml
<PropertyGroup>
  <RunWixToolsOutOfProc>true</RunWixToolsOutOfProc>
</PropertyGroup>
```
The file definitely exists though
```
C:\Users\Keegan>dir C:\Users\Keegan\Documents\GitHub\groovy-wix\apache-groovy-docs\html\documentation\json-builder.html
 Volume in drive C is OS
 Volume Serial Number is 5E9B-0C59

 Directory of C:\Users\Keegan\Documents\GitHub\groovy-wix\apache-groovy-docs\html\documentation

02/01/2019  08:49 PM             3,860 json-builder.html
               1 File(s)          3,860 bytes
               0 Dir(s)  201,562,976,256 bytes free
```

**Comment by madduci** [comment]
Hi, is there any update for the issue?

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by barnson** [comment]
WiX v4 supports x-plat via .NET Core. More work is required.

**Comment by rseanhall** [comment]
In v4, I took the changes from @qlik-pwe and fixed a few other things so that WiX uses the new long path functionality of newer builds of Windows 10 to support paths longer than MAX_PATH. If you are running on a version of Win10 with that support and have enabled it (https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation), then the only remaining limitation would be if WiX is using a Windows API that didn't get updated with support. It's not clear if the MSI APIs fall into this category.

**Comment by Cldndan** [comment]
I don't understand the above error message.

reason:
1. The file exists in the specified path.

If you look at the excerpt below, it is a list of dll files in the case of the corresponding province, and the file near the error section exists in the corresponding path, but the file is not found.

Please tell us why.

[
An excerpt from the XML content.

<File Id="msvcp140DLL" Source="$(env.SystemRoot)\System32\msvcp140.dll"/>
<File Id="vcruntime140_1DLL" Source="$(env.SystemRoot)\System32\vcruntime140_1.dll"/>
<File Id="vcruntime140DLL" Source="$(env.SystemRoot)\System32\vcruntime140.dll"/>

]

**Comment by Cldndan** [comment]
D:\KPWorkSpace\AllFireWall\SetupFireWall\Product.wxs(70,0): error LGHT0103: The system cannot find the file 'C:\WINDOWS\System32\vcruntime140_1.dll'.

I don't understand the above error message.

reason:
1. The file exists in the specified path.

If you look at the excerpt below, it is a list of dll files in the case of the corresponding province, and the file near the error section exists in the corresponding path, but the file is not found.

Please tell us why.

[
An excerpt from the XML content.

<File Id="msvcp140DLL" Source="$(env.SystemRoot)\System32\msvcp140.dll"/>
<File Id="vcruntime140_1DLL" Source="$(env.SystemRoot)\System32\vcruntime140_1.dll"/>
<File Id="vcruntime140DLL" Source="$(env.SystemRoot)\System32\vcruntime140.dll"/>

]

**Comment by BMurri** [comment]
> D:\KPWorkSpace\AllFireWall\SetupFireWall\Product.wxs(70,0): error LGHT0103: The system cannot find the file 'C:\WINDOWS\System32\vcruntime140_1.dll'.
> 

Even though this is the same error message, this is not the same error. Please start a new [discussion ](https://github.com/wixtoolset/issues/discussions)about your issue.

**Comment by Cldndan** [comment]
I'm pretty sure it's something different.

However, I would like to know why the Not Found error occurs even though the file exists in the specified path.

Here's what I checked.
1. The file exists in that path.
2. It was confirmed that the permissions of the dll files starting with vcruntime140 are set identically to those of the vcruntime140_1.dll file.
- This means that the error does not occur for vcruntime140.dll.
3. The current OS is 64-bit wondows 11.
4. What can be selected in the Wix Builder Properties window is that you cannot select anything other than Configuration (C): Active (Debug)/Debug/Release/All Configurations and Platform: Active (x86).
- Is Wix Builder built for 32-bit 32-bit processors?
- Even if it is the same as above, there is no reason to mark the unmountable file as File Not Found in the installation file (MSI) of a specific 64-bit dll.
(Simply mark the file as unsupported and that's it.)
-It would be correct to induce redistribution with redistribution package and display a warning message saying that the dll file can be used by redistribution package, but I would like to know the exact reason on the premise that not displaying it as such is really an error.

**Comment by BMurri** [comment]
> I'm pretty sure it's something different.

I agree with this comment. This is exactly why I asked you to start a new discussion for your issue. Commenting on an issue that's been closed for over 2 years is unlikely to get anyone who can actually help involved.

**Comment by JCcanizares** [comment]
> > I'm pretty sure it's something different.
> 
> I agree with this comment. This is exactly why I asked you to start a new discussion for your issue. Commenting on an issue that's been closed for over 2 years is unlikely to get anyone who can actually help involved.

After encountering this same error and being unable to find a proper fix, I can verify that the error occurs when the file path exceeds `255` characters. Specifically, I encountered an error because it was unable to locate a file within a path that was `264` characters long. However, I managed to resolve the issue by renaming the application's folder and shortening the path to `250` characters.

After that change, the `MSI` build succeeded without any problems.

**Comment by NeerajAtCellsens** [comment]
I am getting this error while building an MSI with WIX 3.11 (32-bit)
light.exe(0,0): error LGHT0103: The system cannot find the file 'C:\Users\NeerajSaxena\AppData\Local\Temp\n4gmbstq\MergeId.85306\MapInfo.miAwareSDK.dll.D4F7308E_27E5_480B_B103_EDCDBDCFE96E' with type ''.
