### ISSUE TITLE
[mba] Error event not called anymore (upgrading from 3.7 to 3.10)

### ISSUE THREAD

**Issue by softlion** [wixtoolset/issues#5315]
This seems a bug in Wix 3.10

I just upgraded wix from 3.7 to 3.10 and now the Error handler is not called when an ExePackage returns an exitcode which behavior is set to error.

    <ExitCode Value="1" Behavior="error" />

When receiving an error in wix 3.7, the Error event of mba is called. In wix 3.10 only the ExecutePackageComplete event is called with a non zero Status (0x800703ef).

This prevent the installer UI from displaying useful message to the user, as the UI don't know the real installer exit code anymore.

Any clue ?

**Comment by barnson** [comment]
There've been no changes that should cause different behavior. You might want to send more details to the wix-users mailing list.

**Comment by softlion** [comment]
I can't find any change that may cause this behavior, and no log would help
finding what's wrong.
So I've removed the event and found a workaround.
