### ISSUE TITLE
VS crashes when I create a new Setup Project

### ISSUE THREAD

**Issue by sagunji** [wixtoolset/issues#5316]
Hello, I am having a massive problem while using WiX 3.8(stable). I am beginner in c# and I want to create flexible setup environment for user. Though, everytime I start a new project with Setup Project, my Visual Studio crashes.
I am using Visual Studio 2012 Version 11.0.50727.1 RTMREL.I am building with .Net Framework 4.5.
My VS works perfectly except when I start Setup Project using WiX. VS stops responding and restarts. I also tried other version WiX v3.10.2 (stable) but same problem everytime.

**Comment by barnson** [comment]
Please attach ActivityLog.xml: https://msdn.microsoft.com/en-us/library/bb166359%28v=vs.110%29.aspx

**Comment by sagunji** [comment]
Hello, I have successfully countered the problem. As it turns out it was not due to WiX but my other extensions were blocking it. I checked the ActivityLog.xml and found the problem. I was experimenting with different installation tools and one of them was not loaded correctly. Thank you for your response.
