### ISSUE TITLE
Leverage YAML instead of inventing the new RType format?

### ISSUE THREAD

**Issue by kzu** [wixtoolset/issues#5324]
Not that I think it's feasible in the (likely?) short time-frame before wix4 ships, 
but I wonder what were the team's reasoning behind creating an entire new 
format instead of leveraging a (popular?) existing one. 

I'm glad you didn't pick JSON like everyone else seems to be doing to leave 
XML behind, but I do find YAML expressiveness, conciseness and flexibility 
quite remarkable and suitable to almost any XML-like configuration/data 
that I can possibly think of. Granted, there's a learning curve like anything 
else, but one you can reuse on other domains, like CI configurations (AppVeyor) 
or static blog generators (Jekyll), and surely many others.

**Comment by robmen** [comment]
RType is all very experimental at this time. We originally investigated YAML (among many others) a lot. We found it added a lot of ceremony that was easy to get wrong (on top of the white space issues). The fact that the spec is ~80 pages isn't a ringing endorsement of simplicity. :)

When more important things are working I'm going to document RType independent of the WiX Toolset and see if it gets any traction. Based on what we learn there we'll revisit what should be done in the WIX v5 time frame when we get back to the alternative source code formats.

Thanks much for your input and peeking into the future a bit. Excited to work on this stuff but there are a lot of nuts and bolts that need to get done before fun stuff like RType. :)

**Comment by kzu** [comment]
Heya Rob, thanks for taking the time to share your thoughts.

Yes, I figured you probably read that long detailed spec. Much shorter than XML+XMLNS+Infoset though, and arguably almost as comprehensive ;)

Maybe a similar approach where the underlying YAML model is exposed as a XAML stream could apply relatively easily?

Anyway, congrats on bringing WiX forward in a substantial way. We're starting to dogfood swix so I'll probably have more questions down the road. What's the best way to channel those? 

Thanks again

**Comment by robmen** [comment]
`swix` is still in prototype mode. It isn't in the WiX v4.0 timeline so it'll be something we'll light up in probably WiX v5.0. What we've started doing in v4.0 is pulling features from swix to make the interop work better in future releases.

There is still much to do to `swix` to get it to a good place. So, any bugs opened against `swix` would all be postponed for future release. Like I said, thanks for peeking into the future. It'll be fun when we get to work on that part.
