### ISSUE TITLE
Exit code from burn bundle is not available to a calling process

### ISSUE THREAD

**Issue by astx30** [wixtoolset/issues#5326]
If this issue is a bug:

* Which version of WiX are you building with?  
v3.10.2

* Which version of Visual Studio are you building with (if any)?
Visual studio 2015 Upgrade 2

* Which version of .NET are you building with?
.NET 3.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 7 64 bit

* Describe the problem and the steps to reproduce it.
I am developing a Burn bundle to chain together a 3rd party setup package, along with some post installation cleanup/modifications. The bundle represents an optional feature and is invoked from a higher-level "framework" application.

When an error occurs in the installation, I want to handle it in the calling application. However I don't get an exit code from the bundle, even though in the Burn log I see an error code.

Excerpt from the Burn log:

```
e000: Error 0x80070643: Failed to install MSI package.
e000: Error 0x80070643: Failed to execute MSI package.
e000: Error 0x80070643: Failed to configure per-machine MSI package.
... 
i399: Apply complete, result: 0x80070643, restart: None, ba requested restart:  No
i500: Shutting down, exit code: 0x80070643
...
i007: Exit code: 0x80070643, restarting: No
```
Calling the bundle from powershell:

```
PS C:\Projects\MySetup\bin\Debug> $p=Start-Process MySetup.exe -PassThru
PS C:\Projects\MySetup\bin\Debug> $p.WaitForExit()
PS C:\Projects\MySetup\bin\Debug> $p.ExitCode
PS C:\Projects\MySetup\bin\Debug>
```

* Describe the behavior you expected and how it differed from the actual behavior.

I would like the error code from the burn exe to be available to the calling application

**Comment by barnson** [comment]
Burn does return an exit code. Take a look at http://stackoverflow.com/questions/10262231/obtaining-exitcode-using-start-process-and-waitforexit-instead-of-wait for ways to capture it in PowerShell.
