### ISSUE TITLE
Light: There should be a better error message than "error LGHT0001: Failed to save resource. Error: 87"

### ISSUE THREAD

**Issue by Farrukhw** [wixtoolset/issues#5330]
## Bug

WixToolset Version: 3.10.2.2516
Visual Studio Enterprise 2015.2
.Net FW: 4.6.01055

While using an .exe file as an icon resource in Burn attribute IconSourceFile, Light ended with error:
**light.exe(0,0): error LGHT0001: Failed to save resource. Error: 87"**

This is very much generic message and doesn't provide direction for resolution. There should be a better error message, guiding/directing about which resource causes the failure while saving/inserting into final Bundle.exe.

Problem would be resolved, when a .ico file is used instead of .exe file in IconSourceFile attribute of Burn element.

**Comment by barnson** [comment]
Burn should provide a better error message or support loading icons from an .exe.
