### ISSUE TITLE
wix-database-deployment-installation

### ISSUE THREAD

**Issue by waqar2012** [wixtoolset/issues#5333]
http://stackoverflow.com/questions/14480837/wix-database-deployment-installation

I am trying to build that Customize able GUI that shows in above link. But  i am ubable to build can you help me.
It gives the error on control element. Unable to resolve this.
Please help;

**Comment by barnson** [comment]
For support, send mail to the wix-users mailing list.

**Comment by waqar2012** [comment]
From where i get the mailing list and how i send the email, Kindly guide me how can i implement and build that gui.
