### ISSUE TITLE
BundleEnumRelatedBundle returns provider key which can't be used with BundleGetBundleInfo

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5334]
- Which version of WiX are you building with?

> 3.10.2
- Which version of Visual Studio are you building with (if any)?

> 2013.5
- Which version of .NET are you building with?

> 4.6.1
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a
- Describe the problem and the steps to reproduce it.

> `BundleEnumRelatedBundle` returns the bundle's provider key but the bundle id is required by `BundleGetBundleInfo`.
- Describe the behavior you expected and how it differed from the actual behavior.

> Common scenario of iterating on bundles via `BundleEnumRelatedBundle` and calling `BundleGetBundleInfo` to get info on the bundle is borked. `BundleEnumRelatedBundle` should allow return of provider key or bundle id.

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/wix3/pull/369
 https://github.com/wixtoolset/wix4/pull/216
