### ISSUE TITLE
error CNDL0150: Undefined preprocessor variable '$(var.TaskManager.PackageDir)'

### ISSUE THREAD

**Issue by pverma00** [wixtoolset/issues#5336]
We are trying to migrate WIX project developed in VS 2010 and WIX v3.5 to VS 2015. On build of the project we are getting **Undefined preprocessor variable '$(var.TaskManager.PackageDir)'** error.
Is there anyone who can help us? 

Below are the details:
 
**Software’s used:**
**Visual studio:**    vs2015
**Wix Toolset:**      v3.10.2
 
 
**Implementation:**
We have created a new WIX project to deploy windows service. 
Within the product.wxs file of setup project we have used below line of code to read web.config file.
 
<File Id="ConfigFile" Source="$(var.ProjectName.PackageDir)\Web.config" KeyPath="yes" />
 
 
**Error on project build:**
On build of setup project we are getting below error.
 
**error CNDL0150: Undefined preprocessor variable '$(var.TaskManager.PackageDir)'**

**Comment by barnson** [comment]
For support, please send mail to the wix-users mailing list.
