### ISSUE TITLE
wix-database-deployment-installation

### ISSUE THREAD

**Issue by waqar2012** [wixtoolset/issues#5337]
Hi Support Team,
I want to implement this type of interface that is shown in the below link.
http://stackoverflow.com/questions/14480837/wix-database-deployment-installation

Is there any sample please share with me.
When i create a project and create the files according to the above example. it gives the error at control element is not resolved.
Kindly help me how can i build the project.

**Comment by barnson** [comment]
For support, send mail to the wix-users mailing list.

**Comment by waqar2012** [comment]
From where i get the wix mailing list

**Comment by robmen** [comment]
http://wixtoolset.org/documentation/
