### ISSUE TITLE
Using Wix Toolset on both VS2008 and VS 2015 at the same time

### ISSUE THREAD

**Issue by oznetmaster** [wixtoolset/issues#5338]
## Feature requests

Wix 3.8 was the last version to support VS2008.  It does not support VS2015.

Wix 3.10 supports VS2015, but not vS2008.

Those who are developing for compact framework 3.5 have to still use VS2008.  That includes any tools or VS2008 add-ins.

It would be extremely useful if two versions of Wix Toolset could coexist.  I know it is possible, since R# does it - old version for VS2008, and new for VS 2015.

**Comment by barnson** [comment]
https://www.joyofsetup.com/2013/09/27/visual-studio-2008-deprecated-in-wix-v3-8/ 

It's possible but there's an ongoing infrastructure cost and nobody's expressed interest in doing the development work to make it possible to have multiple versions of Votive installed in separate versions of Visual Studio. Until that changes...

**Comment by oznetmaster** [comment]
Isn't it just an installer issue?

R# has check boxes for the VS versions you want to install for.  It only installs on those versions.

**Comment by robmen** [comment]
No. First, all of the Votive registration needs to be side-by-side. Then any bugs in the code that expect Votive to be a singleton need to be addressed. Then there is the installer work.

Note: I may have missed some steps. I'm not a Votive expert.

**Comment by barnson** [comment]
And the MSBuild files are explicitly non-side-by-side.

**Comment by barnson** [comment]
Triage concludes it's a lot of work and doesn't move Votive forward for the investment. It's possible you could get the right behavior by registering 3.8 Votive everywhere. You could also just use v3.8 for Visual Studio support and v3.10.3 binaries for the build.
