### ISSUE TITLE
Website content is duplicated in IIS Manager

### ISSUE THREAD

**Issue by morphal** [wixtoolset/issues#5340]
## Bugs
* Which version of WiX are you building with?
>  v3.10.3.3007 

* Which version of Visual Studio are you building with (if any)?
>  VS2015 update3

* Which version of .NET are you building with?
>  .NET 4.5.1

* Describe the problem and the steps to reproduce it.

1. Create installer, using sample project (https://github.com/morphal/WixIISAppIssue)
2. Install the application

* Describe the behavior you expected and how it differed from the actual behavior

> I expect site content, including folders, to be only inside the Web Application node
> Website folders are duplicated both inside Website node and Web Application node:
![image](https://cloud.githubusercontent.com/assets/3996120/16558907/b9ad145a-41f1-11e6-910c-a734bdee81e0.png)

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
