### ISSUE TITLE
WIX Heat not harvesting a reg file properly - outputting the wrong attribute - 'Directory' instead of 'DirectoryRef'

### ISSUE THREAD

**Issue by sharmade** [wixtoolset/issues#5341]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? v3.10.3.3007 

> v3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> Using command line

* Which version of .NET are you building with?

> v4.0.30319

* Describe the problem and the steps to reproduce it.
WIX heat.exe producing incorrect output .wxs file while harvesting a .reg file. 

Command line option used: 
heat.exe reg abc.reg -ag -out  .\reg.wxs -cg NTFilesGroup

* Describe the behavior you expected and how it differed from the actual behavior.

> In the output .wxs file, it is expected to have:
 
- A DirectoryRef attribute in the Component node: ' DirectoryRef="TARGETDIR" ' This is to instruct the output MSI to install the registry stuff at the Target machine.
However, output was different. Instead of DirectoryRef attribute, output was 'Directory="TARGETDIR" ' This doesn't compile with Candle.
Following is a snippet of the output:
 <Fragment>
        <ComponentGroup Id="NTFilesGroup">
            <Component Id="cmp15D68A58E14463942E0ED28DCA5D0637" **Directory**="TARGETDIR" Guid="*" KeyPath="yes">

Attached are the files. They have been appended with .txt as it seems that uploading the .reg and .wxs files is not supported.

[abc.reg.txt](https://github.com/wixtoolset/issues/files/346940/abc.reg.txt)

[reg.wxs.txt](https://github.com/wixtoolset/issues/files/346941/reg.wxs.txt)

**Comment by barnson** [comment]
`Directory` is the right attribute name. What's the error?

**Comment by sharmade** [comment]
My use case: Build a MSI on a CI server (TFS Server TFbuild)
I have a main .wxs file. The .wxs file produced by harvesting the .reg file will be referenced in the main .wxs by including its component group in the main .wxs features tag.

After harvesting a registry file, 'DirectoryRef' is the required output attribute and not 'Directory'. This instructs the MSI to install the registry entries in the target computer and not in a directory. In fact, the produced .wxs will not even compile because &lt;Directory Id="TARGETDIR"&gt; must  be followed by a 'Name' attribute.

So, the desired attribute is something like this:
 &lt;DirectoryRef Id="TARGETDIR"&gt; 

If I had used a syntax with lesser parameters such as:
heat.exe reg abc.reg -ag -out .\reg.wxs 
I would have got the desired output.

However, because I am running MSI creation as a part of CI, I have to add -cg NTFilesGroup to the command:
heat.exe reg abc.reg -ag -out .\reg.wxs **-cg NTFilesGroup**.

This will allow me to group all the components in a Component group in the .wxs output of .reg file, which can then easily be included in  a Fragment in the main .wxs file.

Unfortunately heat is not producing the correct output when I add the parameter cg NTFilesGroup

**Comment by robmen** [comment]
There is no `DirectoryRef` attribute on a `Component. There is a `Directory` attribute on `Component`. What exactly is the problem?

**Comment by sharmade** [comment]
Expected output after harvesting the .reg file (Notice the **DirectoryRef** Tag enclosing the component):
&lt;Fragment&gt;
        &lt;**DirectoryRef** Id="TARGETDIR"&gt;
            &lt;Component Id="cmp03DAA7F9E8DEC3D0CA1BBCD767EBE23F" Guid="*" KeyPath="yes"&gt;
.................


Actual output after harvesting the .reg file (Notice the presence of **Directory** instead of DirectoryRef) 

&lt;Fragment>
        &lt;**Directory** Id="TARGETDIR"&gt;
            &lt;Component Id="cmp15D68A58E14463942E0ED28DCA5D0637" Guid="*" KeyPath="yes"&gt;
........................

**Command used: heat.exe reg abc.reg -ag -out .\reg.wxs -cg NTFilesGroup**

Now, if I try to build the reg.wxs file (using candle.exe - candle.exe -v *.wxs), I get the following error:
error CNDL0025 : The Directory element requires the Name attribute because there is no parent Directory element.
error CNDL0206 : The 'TARGETDIR' directory has an illegal DefaultDir value of '.'.  The DefaultDir value is created from the *Name attributes of the Directory element.  The TARGETDIR directory is a special directory which must have its Name attribute set to 'SourceDir'.

**Comment by barnson** [comment]
No repro. 

    >>>heat.exe reg abc.reg -ag -out .\reg.wxs -cg NTFilesGroup
    Windows Installer XML Toolset Toolset Harvester version 3.10.3.3007
    Copyright (c) .NET Foundation and contributors. All rights reserved.

    Processing complete

I get the following authoring, which has neither `Directory` nor `DirectoryRef`:

    <?xml version="1.0" encoding="utf-8"?>
    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
        <Fragment>
            <ComponentGroup Id="NTFilesGroup">
                <Component Id="cmp9615A2E808DEDA9B695F947C4B56EC9D" Directory="TARGETDIR" Guid="*" KeyPath="yes">
                    <RegistryKey ForceCreateOnInstall="yes" Key="SOFTWARE\Test\HBARS" Root="HKLM" />
                </Component>
                <Component Id="cmp882ED12692F15E9B04BE5DBF1EFB76F3" Directory="TARGETDIR" Guid="*" KeyPath="yes">
                    <RegistryKey Key="SOFTWARE\Test\HBARS\CONFIG" Root="HKLM">
                        <RegistryValue Name="WrapDataSource" Value="TULOX3SQLServer,1437" Type="string" />
                        <RegistryValue Name="DatabaseName_NSW" Value="HBARS_NSW" Type="string" />
                        <RegistryValue Name="DatabaseName_VIC" Value="HBARS_VIC" Type="string" />
                        <RegistryValue Name="DatabaseName_QLD" Value="HBARS_QLD" Type="string" />
                        <RegistryValue Name="DatabaseName_WA" Value="HBARS_WA" Type="string" />
                    </RegistryKey>
                </Component>
            </ComponentGroup>
        </Fragment>
    </Wix>

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
