### ISSUE TITLE
MSI Registry prepend value not updated

### ISSUE THREAD

**Issue by Pradeep-RG** [wixtoolset/issues#5342]
We are using wix 3.9.1208.0 to generate MSI. Below code prepend the value to Upperfilters registry key.

    <RegistryKey Id="UpperFilters" Root="HKLM" Key="xxxxxxxxx" Action="create">
          <RegistryValue Name="UpperFilters" Type="multiString" Action="prepend" Value="xxxxx"/>
    </RegistryKey>

After install observed, value not prepend to 'UpperFilters' registry key and not found any errors in MSI log. This issue happened only once.

MSI Log:

    MSI (s) (0C:28) [10:38:08:835]: Executing op: ComponentRegister(ComponentId=xxxx,KeyPath=02:xxxxx,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=0) MSI (s) (0C:28) [10:38:24:455]: Executing op: RegOpenKey(Root=-2147483646,Key=xxxxx,,BinaryType=0,,) 
    MSI (s) (0C:28) [10:38:24:456]: Executing op: RegAddValue(Name=UpperFilters,Value=xxxxx[~],)

Is MSI returns any failures when unable to update registry?

Will all registry failures are recorded in MSI log?

What's the issue in my scenario?

Thanks in Advance.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/)
