### ISSUE TITLE
Managed Bootstrapper Application Host - Upgrade from WiX 3.8 to 3.10 error

### ISSUE THREAD

**Issue by khacminh** [wixtoolset/issues#5343]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> WiX 3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

> VS 2015 update 3

* Which version of .NET are you building with?

> .NET 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7 and Windows 10

* Describe the problem and the steps to reproduce it.

> I started using WiX with version 3.8 and everything works fine, including create *.msi file and Bootstrapper *.exe installation file. I can also create installation UI for my own. Now my company upgrade VS 2013 to VS 2015 and WiX 3.8 is now incompatible. Therefore, I have to upgrade WiX 3.8 to 3.10.2. Now, if I use **WixStandardBootstrapperApplication.RtfLicense**, everything will works fine. However, if I use **ManagedBootstrapperApplicationHost** for custom UI installer, the application cannot be installed.

I put my bundle.wxs and log files' content here: 
https://gist.github.com/khacminh/17e18175ff752768ba16afc9c0071777

Thank you

**Comment by robmen** [comment]
Upgrade to WiX v3.10.3. Very possible you hit a bug in .2.

**Comment by khacminh** [comment]
Hi robmen,

I upgraded to WiX 3.10.3.3007 but the issue is still there.

**Comment by rseanhall** [comment]
Did you recompile your custom BA against 3.10.3?  That's required.

I'm not understanding why there is a normal log that stops on the line `Creating BA thread to run asynchronously.`, and a failed log.  Is that two separate runs of the bundle?  Is it a typo that the path in the Failed log is missing slashes around the guid? (`C:\Users\Administrator\AppData\Local\Temp{5B7E6773-DC64-4BAD-8E5A-F2EA0EEAEC98}.cr\MyInstaller.exe`)

**Comment by khacminh** [comment]
Hi Sean Hall,

That typo mistake is my bad. There is a slashes around the guid. The correct path is:
`C:\Users\Administrator\AppData\Local\Temp\{5B7E6773-DC64-4BAD-8E5A-F2EA0EEAEC98}\.cr\MyInstaller.exe`

This morning, I clean and build my project again. Then, I reboot all my PCs and run MyInstaller.exe on them. On 1 of my PCs (running windows 10 Pro), the old issue is still there. On others (wins 7 and wins 10), My UI installer can be launched but nothing is installed. Sometimes, after a couple times of retrying, the old issue occurs and it could be solved by rebooting the pc. Here is my new issue log:

https://gist.github.com/khacminh/49c70d337a2d94829390b52f79cbc665

**Comment by rseanhall** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered, but since the WixStandardBootstrapperApplication.RtfLicense BA is working then the issue is likely somewhere in your custom BA.

**Comment by khacminh** [comment]
Hi, 
After busy days, I come back with this issue and I still believe this is a bug. 

On WiX 3.8, after the command:  _Bootstrapper.Engine.Plan(LaunchAction.Install)_, the following events fired: ApplyBegin >> ExecuteBegin >> ApplyComplete

However, on WiX 3.10.3, the event ExecuteBegin not fired and my msi cannot be installed.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
