### ISSUE TITLE
Wixtoolset and Multiple versions of Visual Studio

### ISSUE THREAD

**Issue by seanqmc** [wixtoolset/issues#5345]
* Which version of WiX are you building with?

> 3.8.1128.0

* Which version of Visual Studio are you building with (if any)?

> VS2012 UPD 4, VS2013 UPD5, VS2015 UPD2

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7

* Describe the problem and the steps to reproduce it.

> I have to support multiple projects build with different versions of Visual Studio. As such, I have VS 2012, VS 2013, and VS 2015 installed on my machine. I installed Wix Toolset from http://wixtoolset.org/releases/v3.8/stable. It says it installed fine, and status showed it 'registering' with the 3 different versions of VS. However, when I attempt to open a solution with multiple .wixproj projects, VS shows an error stating that Visual Studio does not have the project type installed. Furthermore, I do not see any Wix project templates when I go to create a new project. This is the same behavior on all 3 versions of Visual Studio. However, when I open VS Extensions and Updates, Wix Toolset does appear in the list.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected that when I opened a VS2012 project that contained .wixproj projects in it, that VS would not give me an error saying that these projects could not be opened. I also expected the WIX project templates to be available for use when creating a new project.

**Comment by barnson** [comment]
WiX v3.8 doesn't support VS2015. Try WiX v3.10.3.

**Comment by seanqmc** [comment]
So does that mean it wont install on VS2012 and VS2013 if it detects VS2015 on the machine? When installing, status shows it is updating VS2012 and VS2013 registration. Plus the solution in question is a VS2012 solution which I am attempting to open with VS2012.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually its a conflict on a specific machine.

**Comment by seanqmc** [comment]
Looking at a comment in the version 3.8 install location (https://wix.codeplex.com/releases/view/115492), which resembled my issue, I was referred to http://wixtoolset.org/issues, which redirects to this site, to file the issue. I have posted this issue to the mailing list.

**Comment by seanqmc** [comment]
I have to agree with the original commentator regarding 3.8 version of Wix Toolset. If you have Multiple versions of VS installed, and one of them is unsupported, then don't even try to install version 3.8 if you have VS2015 installed on your machine. Attempt the latest version. Hope this saves you some time.
