### ISSUE TITLE
Wix boostrapper not calling msi file during uninstall when DisplayInternalUI is set to yes in bundle

### ISSUE THREAD

**Issue by Vakul18** [wixtoolset/issues#5347]
I am using wix 3.10.3.3007 with  Visual Studio 2012 update 5, .net version 4.5 . 

I created a wix bundle and referenced the msi project in this bootstrapper project. It installs the msi perfectly but during uninstall it only removes the entry from the Add or remove Programs, but doesn't call the msi when DisplayInternalUI is set to "yes" for the msi package.When the DisplayInternalUI is set to "no" for msi package, then  it uninstalls correctly by calling the msi package.I have set a GUID for Product Id in my msi project.
Also, in logs when the uninstall is correct it shows msi state as present, but when it doesn't call the msi during uninstall, it shows the state of msi as absent .

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
