### ISSUE TITLE
has no project template and item template

### ISSUE THREAD

**Issue by Tearies** [wixtoolset/issues#5350]
I was intalled the new version Wix Toolset(**3.11**) with the new version visual studio (**15 preview 3**), it seems **has no project template and item template**

**Comment by robmen** [comment]
Visual Studio 15 is not supported, yet.

**Comment by Tearies** [comment]
thanks for your reply. I hope it can be supported in a short time

**Comment by robmen** [comment]
You could always add the support.

**Comment by Tearies** [comment]
What should I do?

**Comment by robmen** [comment]
Add the support. Clone the wix3 repository, look at how the setup supports VS2010+, enhance that, and update any other code that is necessary.

I haven't done this work myself in a long time but it's just code. :)

**Comment by Tearies** [comment]
thanks again
