### ISSUE TITLE
Wix 3.8 VS 2015 ToolsVersion 14.0 issue

### ISSUE THREAD

**Issue by zhuraulevich** [wixtoolset/issues#5351]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.8.1128.0

* Which version of Visual Studio are you building with (if any)?

> MS VS Community 2015 14.0.25123.00 Update 2

* Which version of .NET are you building with?

> .NET Framework 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 8.1 x64

* Describe the problem and the steps to reproduce it.

> Wix build successfully only projects with ToolsVersion=4.0 or ToolsVersion=12.0. If I add a new project (with ToolsVersion=14.0) into solution and installer - I get such error:

"Failed to load project ...\NewClassLibraryProject\NewClassLibraryProject.csproj: Unable to cast object of type 'System.Xml.XmlComment' to type 'System.Xml.XmlElement'. heat.exe	"

* Describe the behavior you expected and how it differed from the actual behavior.

> I need to always manually change ToolsVersion from 14.0 to 12.0 for new projects to avoid these errors. Can Wix work with ToolsVersion=14.0 correctly?

**Comment by rseanhall** [comment]
Full support for 12.0 and 14.0 were added in v3.10 (see #4597, #4853, #5283).  Please open a new issue if v3.10.3 also doesn't work.
