### ISSUE TITLE
Allow a Default value on util:RegistrySearch

### ISSUE THREAD

**Issue by dbengle** [wixtoolset/issues#5355]
It would be very useful if you could specify a default value to be used on a WixUtil RegistrySearch in the case where  the registry key or value is not found.

There are workarounds to accomplish this, but they are somewhat clumsy.  This would simplify coding for the user and make it easier to use.  

This could be accomplished by adding a Default= attribute to the RegistrySearch element.

**Comment by ibb-zimmers** [comment]
you can already set a default value (at least for the property)

`<Property Id="INSTALLDIR"  Value="c:\Default\Location" >
      <RegistrySearch Id="InstallDirSearch" Key="SOFTWARE\foo\bar" Name="InstallDir" Root="HKLM" Type="raw" />
    </Property>`

**Comment by dbengle** [comment]
I was actually interested in the RegistrySearch in the Util schema, which sets a variable, rather than a property.  That one clears the any value set in variable when it isn't found.  

There are some indirect workarounds, but it would be easier if we could just specify a default value to use when it isn't found.

**Comment by robmen** [comment]
Updating the title of the issue to be very specific.

**Comment by barnson** [comment]
Rather than add a `Default` attribute, maybe the search should work like MSI, where a missing value doesn't overwrite the default.

**Comment by dbengle** [comment]
Yes, that would work, and I would be very happy with that approach.
