### ISSUE TITLE
Burn should expose bundle's upgrade code (and id?) as variable

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5356]
- Describe the scenario and benefits that the feature supports.

> Today a BA has to track related bundles via callbacks. As with `WixBundleProviderKey`, it would simplify certain searches if Burn provided the authored upgrade code as a variable (`WixBundleUpgradeCode`).
- Describe how you're accomplishing the feature today (if possible).

> Today a BA can track all possible related bundles via callback and, after the detect phase, can make decisions based on specific related bundles. 
- Describe what you'd like the new feature to do.

> This is a case of "simple things being simple" -- it wouldn't account for `RelatedBundle/@Action='upgrade'` upgrade codes, just the authored upgrade code. But the existing BA interface would continue to allow all that.

**Comment by nirbar** [comment]
I find it useful to set the bundle tag to the upgrade code. Maybe the tag should default to the upgrade code, which will also come in handy in OnDetectRelatedBundle.

**Comment by barnson** [comment]
Turns out there's no guarantee that the authored `Bundle/@UpgradeCode` guid is the first one in the bundle manifest.

**Comment by rseanhall** [comment]
The authored `Bundle/@UpgradeCode` will need to be separated from the rest of them for https://github.com/wixtoolset/issues/issues/4153 (which is needed for https://github.com/wixtoolset/issues/issues/3693).
