### ISSUE TITLE
Using RegistrySearch with empty attribute "Key"

### ISSUE THREAD

**Issue by cybrex86** [wixtoolset/issues#5358]
Sometimes registry value may be in root:
`<RegistrySearch Id='SomeValue' Root='HKLM' Name='Value1' Type='raw' />`

It's valid value with some specific properties. It value auto remove after reboot. WinAPI function RegOpenKeyEx can open this key for get values, why wix can't do it?

**Comment by barnson** [comment]
Windows Installer requires a key.
