### ISSUE TITLE
WiX VS Project ignores GenerateProjectSpecificOutputFolder MsBuild property

### ISSUE THREAD

**Issue by karan-kang** [wixtoolset/issues#5359]
WiX Project (.wixproj) currently do not work with GenerateProjectSpecificOutputFolder MSBuild property. This causes issues because it pollutes the TFS drop folder.

_Reproduction Steps:_
1) Create two projects "Project" and "Project.Installer" with Release\x86 configuration
2) Setup an MSBuild with /p:GenerateProjectSpecificOutputFolder=true flag
3) Notice the Project assemblies will be outputted to **x86\Release\Project\** and Installer Project MSIs will be outputted to **x86\Release\**

_Version Information:_
WiX: 3.10
.NET: 4.5.2
VS: 2015 Update 3
Platform: x86
OS: Windows 8.1

**Comment by aloker** [comment]
I've stumbled across this issue today. This causes all kinds of trouble for us.

**Comment by robmen** [comment]
It isn't clear how supported this is in SDK-style projects now (see https://github.com/dotnet/msbuild/issues/4435 and what it is duped to) but it seems to work now after wixtoolset/wix4#60 if provided the following properties: `-p:GenerateProjectSpecificOutputFolder=true -bl /p:OutDirWasSpecified=true -p:OutputPath=some\custom\path`
