### ISSUE TITLE
Incorrect link in WiX document

### ISSUE THREAD

**Issue by jeremyma** [wixtoolset/issues#5360]
page:
http://wixtoolset.org/documentation/manual/v3/overview/light.html

Sections:
"Specifies a semicolon or comma delimited list of localized string cultures to load from .wxl files and libraries. Precedence of cultures is from left to right. For more information see [Specifying cultures to build](../howtos/ui_and_localization/specifying_cultures_to_build.html)."

**Comment by barnson** [comment]
MarkdownSharp doesn't format text in HTML markup. Nor does it support MD tables. Time to switch to CommonMark.NET?

**Comment by robmen** [comment]
AFICT, we already upgraded to `CommonMark.dll`.

**Comment by barnson** [comment]
@robmen in wix4? Don't see it in nuget or checked-in in wix3.

**Comment by robmen** [comment]
Oh, my bad. I've been too focused on `website`.

**Comment by barnson** [comment]
https://github.com/wixtoolset/wix3/pull/373
