### ISSUE TITLE
Unresolved reference to symbol 'ChainPackageGroup:NetFx461Redist' in section 'Bundle'.

### ISSUE THREAD

**Issue by regal60740** [wixtoolset/issues#5361]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)
3.10.3.3007
* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)
2015 Professional Update 3
* Which version of .NET are you building with?

> (.NET version)
4.6.01055
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
Windows 7 Professional
* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

I am trying to install .NET 4.6.1 as a prerequisite.

Added a reference to WixNetFxExtension to my bundle project.

<Bundle>
<PayloadGroup Id="NetFx461RedistPayload">
      <Payload Name="redist\NDP461-KB3102436-x86-x64-AllOS-ENU.exe"
               SourceFile=".\Media\NDP461-KB3102436-x86-x64-AllOS-ENU.exe"/>
    </PayloadGroup>
<BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkLicense">
      <bal:WixStandardBootstrapperApplication LicenseUrl="" SuppressOptionsUI="yes" />
    </BootstrapperApplicationRef>
<Chain>
      <PackageGroupRef Id="NetFx461Redist"/>
      <PackageGroupRef Id="..."/>
      <PackageGroupRef Id="..."/>      
      <PackageGroupRef Id="..."/>      
    </Chain>
</Bundle>

When I right click the project and "build", I get the error: "Unresolved reference to symbol'ChainPackageGroup:NetFx461Redist' in section 'Bundle:...;

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)
I expect the project to build when using the package "NetFx461Redist". The older packages (NetFx46Redist and older) build just fine. The latest version "NetFx461Redist" does not work.

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)
I need the extension "WixNetFxExtension" to work for package "NetFx461Redist". I need to install .NET 4.6.1 in order to install SQL Server 2016.

**Comment by barnson** [comment]
NetFx461Redist is not in WiX v3.10.3. It's in WiX v3.11 prereleases.

**Comment by kmillerdevx3** [comment]
@barnson Any hope of these version dependencies being documented somewhere? The WixNetFxExtension page lists all of them, with no mention of what WiX version is required. (I came here with the same issue, for 4.6.2.)

**Comment by barnson** [comment]
Feel free to file a doc bug and submit a PR. :)
