### ISSUE TITLE
Executable package built with 3.10.3 executes "successfully" without installing bundled MSI.

### ISSUE THREAD

**Issue by bakerhillpins** [wixtoolset/issues#5362]
# Problem Description:
I have a WIX installer project that I was building with 3.9.1208.0. The 3.9 produced bundle works fine. I upgraded to 3.10.3.3007 yesterday and the bundle compiled from the same code image executes successfully but never installs the bundled MSI. There are several prerequisites that all seem to be satisfied.

This is built on a Windows 7 Enterprise laptop with Service Pack 1 (6.1.7601 with SP1 7601).
Install reports completed but the bundled MSI is never installed on the Laptop above or a Windows 10 (10.0.10240) Enterprise 2015 LTSB. Have not tried other systems. I attached a log from the Win10 system.

I was unable to find a similar issue listed here.

I can provide code or the actual bundles if that would help but can't post them publicly. I realize there isn't much in here for you to work on but I don't know what else to start the conversation with since I don't have any real error data to send. It just completes with no errors reported. Please ask for what you need. I should be notified on a response to this issue.

If you use TeamViewer or other such online collaborative tools I am open to that route as well.

# Here is the entire VS version dump:

Microsoft Visual Studio Professional 2012
Version 11.0.61030.00 Update 4
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Professional

Team Explorer for Visual Studio 2012   04938-004-0034007-02845
Microsoft Team Explorer for Visual Studio 2012

Visual Basic 2012   04938-004-0034007-02845
Microsoft Visual Basic 2012

Visual C# 2012   04938-004-0034007-02845
Microsoft Visual C# 2012

Visual C++ 2012   04938-004-0034007-02845
Microsoft Visual C++ 2012

Visual F# 2012   04938-004-0034007-02845
Microsoft Visual F# 2012

Visual Studio 2012 Code Analysis Spell Checker   04938-004-0034007-02845
Microsoft® Visual Studio® 2012 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

AlignAssignments   1.0
Command for aligning assignments.

AutoBraceComplete   1.0
auto brace complete

CustomDocWell   1.0
Provides configurable behavior for the document well in Visual Studio 2012.

NuGet Package Manager   2.8.50126.400
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

OptionsPageImpl   1.0
Information about my package

PowerCommands for Visual Studio 2010   1.0
A set of power commands for Visual Studio 2010

PreEmptive Analytics Visualizer   1.0
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

Quick Launch Tasks   1.0
Microsoft Quick LaunchTasks package adds accessibility and settings tasks to the Quick Launch tool.

TenAsys INtime SDK    
TenAsys INtime SDK www.tenasys.com
Provides support for development and debug of INtime projects.
Version 6.1.16195.1 / Build 123

Visual Assist   
For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2013 Whole Tomato Software, Inc.

Windows Installer XML Toolset   3.10.3.3007
Windows Installer XML Toolset version 3.10.3.3007
Copyright (c) .NET Foundation and contributors. All rights reserved.

Git Extensions
Git Extensions is a graphical interface for Git
For more information about Git Extensions, see the Git Extensions website at
http://sourceforge.net/projects/gitextensions/
Copyright © 2008-2014 Henk Westhuis

INtime Addin
Allows editing of C++ objects after a project has been created by the INtime Application wizard, plus some conversions. For more details see http://www.tenasys.com.

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
 

[Install on Win 10.txt](https://github.com/wixtoolset/issues/files/389093/Install.on.Win.10.txt)

**Comment by rseanhall** [comment]
Recompile your BA against v3.10.3, there is no binary compatibility guarantee in 3.x.  Your BA is requesting Cache not Install:

    [1090:1590][2016-07-28T13:15:48]i200: Plan begin, 9 packages, action: Cache

While you're at it, probably want to customize this:

    [1090:0B94][2016-07-28T13:15:46]i000: Running the WiX BA.

**Comment by bakerhillpins** [comment]
Ok. Simple fix. Thanks for being prompt.

Did I miss that "no compatibility" guarantee somewhere? The BA seems to execute just fine.  Sorry for the inconvenience.
