### ISSUE TITLE
Referencing the NetFx461Web package group in a bundle does not work

### ISSUE THREAD

**Issue by nathan-alden** [wixtoolset/issues#5363]
* Which version of WiX are you building with?

> WiX Toolset v3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Community 2015 with Update 3 (14.0.25424.00)

* Which version of .NET are you building with?

> .NET Framework 4.6.1

* Describe the problem and the steps to reproduce it.

> Error generated on build when using `<PackageGroupRef Id="NetFx461Web"/>` in bundle

```
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:bal="http://schemas.microsoft.com/wix/BalExtension">
  <Bundle Name="My Bootstrapper" Version="!(bind.packageVersion.MySetup)" Manufacturer="redacted" UpgradeCode="redacted" IconSourceFile="redacted.ico">
    <bal:Condition Message="redacted requires a 64-bit version of Windows 7 or newer.">
      <![CDATA[VersionNT >= v6.1 AND VersionNT64]]>
    </bal:Condition>
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense">
      <bal:WixStandardBootstrapperApplication LicenseFile="License.rtf"/>
    </BootstrapperApplicationRef>
    <Chain>
      <PackageGroupRef Id="NetFx461Web"/>
      <MsiPackage Id="MySetup" SourceFile="$(var.MySetup.TargetPath)"/>
    </Chain>
  </Bundle>
</Wix>
```

`Unresolved reference to symbol 'ChainPackageGroup:NetFx461Web'`

* Describe the behavior you expected and how it differed from the actual behavior.

> I created a standard bootstrapper project and it works perfectly, but not if I use the `NetFx461Web` package group. If I change it to `NetFx46Web`, it builds and works perfectly.

**Comment by robmen** [comment]
You need WiX v3.11.

**Comment by nathan-alden** [comment]
Thanks for the prompt response! I feel like I was still clicking Submit when you answered.

**Comment by nathan-alden** [comment]
Thanks again; 3.11 did, indeed, fix the issue.
