### ISSUE TITLE
PreBuild Events are Run before all References are build when using TFS Buildserver

### ISSUE THREAD

**Issue by miracle152004** [wixtoolset/issues#5364]
Hi I run into the following bug:

* 3.10.3

* Which version of Visual Studio are you building with (if any)?

> TFS 2015

* Which version of .NET are you building with?

> 4.5.1

* Describe the problem and the steps to reproduce it.

> When using Windows Installer XML on a build server we are using pre-build events to do some additional work. This work requires that all Projects set as Reference are Build before the Pre-Build Event of the setup is executed. But while doing this we identified that some of the projects aren't available before the setup build is started. This results in an overall build failure. While observing the folders on the server we saw that one project is not build before the setup build is started.

* Describe the behavior you expected and how it differed from the actual behavior.

> The Prebuild-Event should only be triggered after all references to the setup project are already build and ready to use.

Could you please take a look.

Thanks.

**Comment by barnson** [comment]
Please attach a verbose MSBuild log from TFS.

**Comment by barnson** [comment]
Please attach a verbose MSBuild log from TFS.

**Comment by rossbrower** [comment]
Adding the /m:1 argument to msbuild may help. This should prevent msbuild from building other projects in parallel and allow your pre-build task to run at the expected time.
