### ISSUE TITLE
Older bundle not detecting that newer bundle is installed

### ISSUE THREAD

**Issue by robe070** [wixtoolset/issues#5365]
* Which version of WiX are you building with?
3.10.3007

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10 build and Windows 10 installed

* Describe the problem and the steps to reproduce it.
There are 4 bundles, code is listed below. 1.0.0, 1.0.0.1, 1.0.0.2 and 2.0.0
If 2.0.0 is installed and then 1.0.0 is run it 'installs' quickly creating an entry in Programs & Features.
If 1.0.0 is then uninstalled, it truly uninstalls the whole application, leaving 2.0.0 still listed.

```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Burn Installer" Version="1.0.0" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MsiPackage Id="MainPackage" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v1.0.0_en-us.msi" Vital="yes" DisplayInternalUI="yes" />
    </Chain>
  </Bundle>
</Wix>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Patch 1.0.0.1" Version="1.0.0.1" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Action="Patch"/>     
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MspPackage Id="Patch" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v1.0.0.1_en-us.msp" Vital="yes" DisplayInternalUI="no" PerMachine="yes" Permanent="no"/>
    </Chain>
  </Bundle>
</Wix>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Patch 1.0.0.2" Version="1.0.0.2" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Action="Patch"/>     
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MspPackage Id="Patch" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v1.0.0.2_en-us.msp" Vital="yes" DisplayInternalUI="no" PerMachine="yes" Permanent="no"/>
    </Chain>
  </Bundle>
</Wix>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Burn Installer" Version="2.0.0" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MsiPackage Id="MainPackage" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v2.0.0_en-us.msi" Vital="yes" DisplayInternalUI="yes" />
    </Chain>
  </Bundle>
</Wix>

```

* Describe the behavior you expected and how it differed from the actual behavior.

3.9.1208 properly reports an error when 1.0.0 is attempted to be installed:
`Error 0x80070666: Cannot install a product when a newer version is installed`

**Comment by barnson** [comment]
Please attach logs demonstrating the problem.

**Comment by robe070** [comment]
I've downgraded to WiX 3.9 now and getting back to 3.10 will be time consuming due to the lengthy build process. And I have thousands of log files from trying to work out what I was doing wrong.

Are the log files essential to move this forward?
If this is something you'll address ASAP, then I'll go through this lengthy process. Otherwise I have to get on with other work. Too much time spent already working out how to use Burn with patches.

**Comment by barnson** [comment]
Without logs or the bundles to reproduce the problem, you're waiting on a volunteer to spend the time putting together his or her own repro. Downgrading to WiX v3.9 means you're creating bundles that are vulnerable to the security issue fixed in WiX v3.10.2.

**Comment by robe070** [comment]
Thanks Bob, I know. What I don't know is this:
"If this is something you'll address ASAP, then I'll go through this lengthy process. Otherwise I have to get on with other work. Too much time spent already working out how to use Burn with patches."
It seems pretty important to me. Is it to you?

**Comment by robmen** [comment]
@robe070 there have been 16,000+ installs of WiX v3.10.3 and this is the first upgrade issue anyone has mentioned. You'll have to pardon us for being skeptical that there is a failure in the WiX Toolset and isn't just an issue in your BA. Of course, that isn't to say that there isn't an error in the WiX Toolset, it always possible we missed something. The log files should tell us pretty quickly.

However, you are dealing with volunteers on GitHub. Making demands like "I won't help you unless you guarantee me a fix quickly" is a fantastic way to those of us who put so much effort into the WiX Toolset for free.

If you want preferential support, contribute to the community and build up a reputation as someone who helps improve the WiX Toolset. Otherwise, if you want commercial support with guarantees of response times and bug fixes, there are options for that. If you don't want to do either of those, then please respect that the people that do volunteer on the WiX Toolset see a great many things to do to improve the WiX Toolset and work hard for your benefit for free.

**Comment by robe070** [comment]
I'm just asking if the issue is actually an issue that it would be addressed quickly because you would deem it as important. Nothing more than that. It seems fundamental to me. I'm asking if thats the case for you too. I would expect this would effect many users.

If you were to respond "yes its important if it truly is a defect" than I'd spend that time now.

**Comment by rseanhall** [comment]
Based on the logs in https://github.com/wixtoolset/issues/issues/5366, I believe these bugs are related.

**Comment by barnson** [comment]
At the moment, we lack the detail needed to determine (a) if there's a bug and (b) if so, how important it is.

**Comment by rseanhall** [comment]
I can't reproduce this in 3.9.1208, 3.10.3.3007, or latest from the develop branch.

**Comment by robe070** [comment]
I've installed 3.10.3007 again and I cannot reproduce it either, unless I change the Upgrade Code, which is correct behavior. I apologize for wasting your time on this one. I clearly wasn't running what I thought I was running at the time.
