### ISSUE TITLE
Patches for 1.0.0 are not removed from Programs & Features when bundle 2.0.0 is installed

### ISSUE THREAD

**Issue by robe070** [wixtoolset/issues#5366]
* Which version of WiX are you building with?
3.9.1208

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10 build and Windows 10 installed

* Describe the problem and the steps to reproduce it.
There are 4 bundles, code is listed below. 1.0.0, 1.0.0.1, 1.0.0.2 and 2.0.0
If 1.0.0, 1.0.0.1, 1.0.0.2 and 2.0.0 are installed Programs and Features will still have 1.0.0.1 and 1.0.0.2 listed as installed in Programs and Features. They will remain there until the last Version is uninstalled.

```
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Burn Installer" Version="1.0.0" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MsiPackage Id="MainPackage" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v1.0.0_en-us.msi" Vital="yes" DisplayInternalUI="yes" />
    </Chain>
  </Bundle>
</Wix>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Patch 1.0.0.1" ParentName="Burn Installer" Version="1.0.0.1" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Action="Patch"/>     
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MspPackage Id="Patch" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v1.0.0.1_en-us.msp" Vital="yes" DisplayInternalUI="no" PerMachine="yes" Permanent="no"/>
    </Chain>
  </Bundle>
</Wix>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Patch 1.0.0.2" ParentName="Burn Installer" Version="1.0.0.2" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Action="Patch"/>     
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MspPackage Id="Patch" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v1.0.0.2_en-us.msp" Vital="yes" DisplayInternalUI="no" PerMachine="yes" Permanent="no"/>
    </Chain>
  </Bundle>
</Wix>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Bundle Name="Burn Installer" Version="2.0.0" Manufacturer="LANSA" UpgradeCode="A184CF47-6B44-40FB-B5A2-900CFE0B90CB" Copyright="..." AboutUrl="...">
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" />
    <Chain>
      <MsiPackage Id="MainPackage" SourceFile="C:\dev\Trunk\work\x_win95\x_lansa\X_Apps\TESTLIST\TESTLIST_v2.0.0_en-us.msi" Vital="yes" DisplayInternalUI="yes" />
    </Chain>
  </Bundle>
</Wix>

```

* Describe the behavior you expected and how it differed from the actual behavior.

When an Upgrade is applied, all prior Versions and Patches should be delisted from Programs and Features and/or View Installed Updates. Exactly the same as does occur when the MSI/MSP are directly installed rather than through the Bundler.

Note: this is just a test. The actual scenario is to bundle a number of installs together. Its been simplified to highlight the issue.

**Comment by barnson** [comment]
Please attach logs demonstrating the problem.

**Comment by robe070** [comment]
I notice this in the 2.0.0 patch file:
Unable to remove cached bundle: {fb4c3225-5e64-4304-81bd-2b87287250c9}, from path: C:\ProgramData\Package Cache\{fb4c3225-5e64-4304-81bd-2b87287250c9}\, reason: 0x80070091
Does that give any clues?
[logs_2.0.0.zip](https://github.com/wixtoolset/issues/files/395137/logs_2.0.0.zip)
[logs_1.0.0.zip](https://github.com/wixtoolset/issues/files/395139/logs_1.0.0.zip)
[logs_patch.zip](https://github.com/wixtoolset/issues/files/395140/logs_patch.zip)

**Comment by robmen** [comment]
Note: the log files show Burn v3.9  R2 is being used, not WiX v3.10.3.

**Comment by robe070** [comment]
yes. Copy and paste problem. Apologies

**Comment by robe070** [comment]
Uninstall logs. Same error reported in the log yet the entry is removed from Programs & Features:
[logs_uninstall.zip](https://github.com/wixtoolset/issues/files/395180/logs_uninstall.zip)

**Comment by rseanhall** [comment]
I haven't used related bundles so I'm not clear on whether there is a bug here.  Are patch bundles supposed to have the same UpgradeCode as the original bundle?  That doesn't seem right to me, especially since you have to put the original bundle's upgrade code in the RelatedBundle element.

**Comment by robe070** [comment]
It makes no difference whether the UpgradeCode in the patch is the same or different. And as we are trying to relate a patch from a previous Version say 1.0.0.1 with the new version 2.0.0, the more possible connections between them the better.

But actually its not the relationship with 2.0.0 thats key here; its that the removal of the previous version - 1.0.0 - at the end of the 2.0.0 install does not remove the related bundles, yet uninstalling 2.0.0 DOES remove those related bundles. Go figure!

Is there anyone who has used related bundles? Is there another way to patch an app and have the relatedness we desire?

But truly I really think its a bug.

**Comment by rseanhall** [comment]
This is obviously unintended behavior.  But there are some very weird relationships with 2.0.0 here.  You can see from the Burn_Installer_20160802121528.log from the 2.0.0.zip (this is 2.0.0 telling 1.0.0 to uninstall) that 1.0.0 tried to uninstall the patch (note that it is the 1.0.0 bundle's responsibility to uninstall the patch, not 2.0.0).

    [37E0:37E4][2016-08-02T12:15:28]i100: Detect begin, 1 packages
    [37E0:37E4][2016-08-02T12:15:28]i102: Detected related bundle: {d4353935-8c6c-4a0b-b8f7-d19f2f53a17e}, type: Upgrade, scope: PerMachine, version: 2.0.0.0, operation: None
    [37E0:37E4][2016-08-02T12:15:28]i102: Detected related bundle: {fb4c3225-5e64-4304-81bd-2b87287250c9}, type: Patch, scope: PerMachine, version: 1.0.0.1, operation: Remove
    [37E0:37E4][2016-08-02T12:15:28]i103: Detected related package: {48EA35C8-9431-403F-B3AA-B3F3C5AB7477}, scope: PerMachine, version: 2.0.0.0, language: 0 operation: Downgrade
    [37E0:37E4][2016-08-02T12:15:28]i101: Detected package: MainPackage, state: Obsolete, cached: Complete
    [37E0:37E4][2016-08-02T12:15:28]i199: Detect complete, result: 0x0
    [37E0:37E4][2016-08-02T12:15:28]i200: Plan begin, 1 packages, action: Uninstall
    [37E0:37E4][2016-08-02T12:15:28]i214: Plan skipped related bundle: {d4353935-8c6c-4a0b-b8f7-d19f2f53a17e}, type: Upgrade, because it was previously scheduled.
    [37E0:37E4][2016-08-02T12:15:28]i207: Planned related bundle: {fb4c3225-5e64-4304-81bd-2b87287250c9}, type: Patch, default requested: Absent, ba requested: Absent, execute: Uninstall, rollback: Install, dependency: Unregister
    [37E0:37E4][2016-08-02T12:15:28]i207: Planned related bundle: {d4353935-8c6c-4a0b-b8f7-d19f2f53a17e}, type: Upgrade, default requested: None, ba requested: None, execute: None, rollback: None, dependency: None
    [37E0:37E4][2016-08-02T12:15:28]i201: Planned package: MainPackage, state: Obsolete, default requested: None, ba requested: None, execute: None, rollback: None, cache: No, uncache: Yes, dependency: Unregister
    [37E0:37E4][2016-08-02T12:15:28]i299: Plan complete, result: 0x0

The fact that the 2.0.0 bundle ({d4353935-8c6c-4a0b-b8f7-d19f2f53a17e}) is detected twice (I'm assuming {48EA35C8-9431-403F-B3AA-B3F3C5AB7477} is the bundle Id for 2.0.0) and planned twice is very suspicious.  It is interesting that it fails to remove the patch bundle from the package cache, but that shouldn't cause the behavior here.  (0x80070091 means the directory is not empty, I wonder what was deleted and what is remaining)

    [37D4:37D8][2016-08-02T12:15:32]i352: Removing cached bundle: {c854b62a-7729-4842-8f42-d059309af09d}, from path: C:\ProgramData\Package Cache\{c854b62a-7729-4842-8f42-d059309af09d}\
    [37D4:37D8][2016-08-02T12:15:36]w354: Unable to remove cached bundle: {c854b62a-7729-4842-8f42-d059309af09d}, from path: C:\ProgramData\Package Cache\{c854b62a-7729-4842-8f42-d059309af09d}\, reason: 0x80070091. Continuing...

I also find it very odd that 2.0.0 decided it needed to install the patch itself.

    [127C:0D98][2016-08-02T12:13:49]i100: Detect begin, 1 packages
    [127C:0D98][2016-08-02T12:13:49]i102: Detected related bundle: {c854b62a-7729-4842-8f42-d059309af09d}, type: Upgrade, scope: PerMachine, version: 1.0.0.0, operation: MajorUpgrade
    [127C:0D98][2016-08-02T12:13:49]i102: Detected related bundle: {fb4c3225-5e64-4304-81bd-2b87287250c9}, type: Patch, scope: PerMachine, version: 1.0.0.1, operation: Install
    [127C:0D98][2016-08-02T12:13:49]i103: Detected related package: {512E3151-A220-4AF5-AF4D-376EFF5E7337}, scope: PerMachine, version: 1.0.0.0, language: 0 operation: MajorUpgrade
    [127C:0D98][2016-08-02T12:13:49]i101: Detected package: MainPackage, state: Absent, cached: None
    [127C:0D98][2016-08-02T12:13:49]i199: Detect complete, result: 0x0
    [127C:3148][2016-08-02T12:13:50]i000: Setting numeric variable 'EulaAcceptCheckbox' to value 1
    [127C:0D98][2016-08-02T12:13:50]i200: Plan begin, 1 packages, action: Install
    [127C:0D98][2016-08-02T12:13:50]i000: Setting string variable 'WixBundleRollbackLog_MainPackage' to value 'd:\temp\Burn_Installer_20160802121348_0_MainPackage_rollback.log'
    [127C:0D98][2016-08-02T12:13:50]i000: Setting string variable 'WixBundleLog_MainPackage' to value 'd:\temp\Burn_Installer_20160802121348_0_MainPackage.log'
    [127C:0D98][2016-08-02T12:13:50]i201: Planned package: MainPackage, state: Absent, default requested: Present, ba requested: Present, execute: Install, rollback: Uninstall, cache: Yes, uncache: No, dependency: Register
    [127C:0D98][2016-08-02T12:13:50]i207: Planned related bundle: {c854b62a-7729-4842-8f42-d059309af09d}, type: Upgrade, default requested: Absent, ba requested: Absent, execute: Uninstall, rollback: Install, dependency: None
    [127C:0D98][2016-08-02T12:13:50]i207: Planned related bundle: {fb4c3225-5e64-4304-81bd-2b87287250c9}, type: Patch, default requested: Present, ba requested: Present, execute: Install, rollback: None, dependency: Register
    [127C:0D98][2016-08-02T12:13:50]i299: Plan complete, result: 0x0

Based on what I see here, I would try giving every bundle it's own upgrade code and use the `RelatedBundle` element to establish relationships.  That might at least provide a workaround.  I'll try to reproduce this myself over the weekend, but it would save me a lot of time if you could provide a self-contained example that builds all of the MSI's, MSP's, and bundles.

**Comment by robe070** [comment]
If you change the UpgradeCode, then the relationship between 1.0.0 and 2.0.0 is broken. Thus when 2.0.0 installs, 1.0.0 is not uninstalled. And I tested it out to prove myself right, at least in 3.9.1208.

Providing all the objects built into these msi and msp to you is a large job. I believe this is not an issue with constructing the msi and msp as they work perfectly by themselves. Its the actions of the Bundler thats in question. So I'll provide a standalone set of bundle wxs, the msi, the msp and a bat file to build it all.

**Comment by robe070** [comment]
I've cut out as much as I can from our WiX generator. Still creates a sizeable msi - 50 MB. So I've uploaded it to DropBox.
[Repo code](https://www.dropbox.com/sh/vw180s0rs0enl72/AAAQCwlbaf4PkkOI-Gp51Q1pa?dl=0)
Run BurnAll.bat to build the 3 bundle exe:
Burn.exe
BurnPatch2.exe
Burn2.exe

**Comment by rseanhall** [comment]
Thanks, this looks like what I need.

For the 2.0.0 bundle, I expected you to add `<RelatedBundle Id="{1.0.0_GUID}" Action="Upgrade" />` to keep the upgrade relationship.

**Comment by robe070** [comment]
When I added that to 2.0.0, if I installed it when 1.0.0 was not already installed, no entry was put in programs and features. The entry was in View Installed Updates. Thus I surmised it's not meant for major upgrades. Maybe it's what's needed to tidy up the patches, but then this defect needs to be addressed. 

My pc is not accessible until Monday. Maybe you could try it out with my test case to see what I mean. 

Warm regards

Rob Goodridge

On 5 Aug 2016, at 10:46 PM, Sean Hall <notifications@github.com> wrote:

Thanks, this looks like what I need.

For the 2.0.0 bundle, I expected you to add <RelatedBundle Id="{1.0.0_GUID}" Action="Upgrade" /> to keep the upgrade relationship.

**Comment by rseanhall** [comment]
When I specify a separate upgrade code for 2.0.0, I can install it without any of the other bundles installed and it shows up in Programs and Features and not in View Installed Updates.  However, it doesn't change the patch behavior.

**Comment by rseanhall** [comment]
So the only documentation I can find for how these Patch bundles are supposed to work are the integration tests at https://github.com/wixtoolset/wix3/blob/develop/test/src/WixTests/Burn/Burn.RelatedBundleTests.cs.  Patch bundles are supposed to have a separate upgrade code from their target bundles.

According to the `Burn_InstallUninstallStickyPatchRelatedBundle` test, this is working as designed.  Apparently, the Burn engine expects the full bundle's BA to decide which versions that the Patch bundle is supposed to apply to.  This would require designing and implementing a way to specify this at compile time.

**Comment by robe070** [comment]
> When I specify a separate upgrade code for 2.0.0, I can install it without any of the other bundles installed and it shows up in Programs and Features and not in View Installed Updates. However, it doesn't change the patch behavior.

Yes, thats correct, but if you change the Upgrade Code in 2.0.0 it will NOT replace 1.0.0.

My comment was about the behavior of `RelatedBundle `as in your request...

> I expected you to add `<RelatedBundle Id="{1.0.0_GUID}" Action="Upgrade" />` to keep the upgrade relationship.

That is, when `RelatedBundle` is specified it will not put an entry in Programs & Features. It ends up in View Installed Updates.

So to re-iterate. If UpgradeCode is changed in 2.0.0 then to allow 2.0.0 to upgrade 1.0.0 you need to specify RelatedBundle using the 1.0.0 UpgradeCode,  but that combination puts the installation entry in View Installed Updates. This is not desirable. Therefore you must not change the UpgradeCode in 2.0.0. The whole point of UpgradeCode is to link the installations so that a later installation replaces the earlier one. UpgradeCode must be the same in every Major Upgrade.

As to the Patch requiring the UpgradeCode to be changed, I'll see what that does and respond to your later post.

**Comment by robe070** [comment]
Thanks for having a go at this Sean.

So this is a test with 1.0.0 and 2.0.0 UpgradeCode set to the same value. Patch UpgradeCode set to a different value.

**Test 1**
Install 1.0.0 and 1.0.0.2 and Uninstall 1.0.0. All entries in Programs & Features (PF) and View Installed Updates (VIU) are removed. Test passed.

**Test 2**
Install 1.0.0 and 1.0.0.2, and 2.0.0. PF has 2.0.0 entry - good. VIU still has 1.0.0.2 listed - bad. Test failed. 

So, no change from the originally reported issue. Changing the UpgradeCode in the patch does not fix the issue. 

I still think the issue is with the implied uninstall of 1.0.0 when 2.0.0 is installed. That is, its not about 2.0.0. Patches to 1.0.0 are not its responsibility. Why 1.0.0 implied uninstall behaves differently to when 1.0.0 is specifically uninstalled is key. 

Surely there are more experienced people around who know how this is meant to behave. Because looking at code is just understanding what its coded to do, not what its meant to do. The lack of documentation makes using and diagnosing troublesome.

**Comment by rseanhall** [comment]
Sorry for the confusion about the upgrade codes.  I was not trying to say that changing them resulted in fixing the behavior that this bug was originally about.  Let's just drop that part.

The 2.0.0 bundle is installing the 1.0.0.2 patch bundle again (applying it to itself), which increases the ref count on it to 2.  This is why the 1.0.0 uninstall is not uninstalling the 1.0.0.2 patch.

The code and integration tests very clearly show how this is supposed to behave.  When a bundle (let's say "B") is installing itself, and a patch bundle is installed and targets one of B's upgrade codes, then that patch bundle should be installed for B as well. It's up to the BA during planning to tell the engine not to install it.  The engine has no concept of a patch bundle only applying to versions X-Y of the target upgrade code.

The sticky patching feature isn't part of this bug, but it does make it extremely difficult to add behavior in the engine to guess that a patch bundle with version 1.0.0.2 should only apply to the bundle with version 1.0.0.0.  This feature says that if a bundle has `<RelatedBundle Id="{BASE_BUNDLE_UPGRADE_CODE}" Action="Detect" />`, then the patch bundle should apply to it as well.  And the version of this other bundle will probably not be 1.0.0.

Maybe @heaths can comment on this bug?

**Comment by robe070** [comment]
OK. I can see the log is informing us that the patch is re-installed by 2.0.0. And the Patch's UpgradeCode in this test is different to 2.0.0. So presumably its using the RelatedBundle value to detect they are related (as it matches 2.0.0 UpgradeCode). And thus it needs to be re-installed.

So I can see no combination which allows me to 
(1) Have patches for 1.0.0 be linked to 1.0.0 so that uninstalling 1.0.0 removes them too; (The Patch UpgradeCode or/and RelatedBundle values must equal the 1.0.0 UpgradeCode
AND
(2) NOT have 1.0.0 patches NOT re-installed by 2.0.0 (The Patch UpgradeCode  AND RelatedBundle values must **not** equal the 2.0.0 UpgradeCode)
AND
(3) Allow install of 2.0.0 to uninstall 1.0.0 automatically. (UpgradeCode in 1.0.0 and 2.0.0 must match.)
AND
(4) Have patches listed in VIU and the major upgrades listed in PF (Patches need to specify RelatedBundle = 1.0.0 UpgradeCode)

And the behavior I'm attempting to achieve is what a simple MSI/MSP by themselves do.

ps Having an old patch overwrite a newer version in the Major Upgrade is catastrophic.

**Comment by robe070** [comment]
I have tested all the RelatedBundle Action values, Upgrade, Patch and Addon.

Upgrade causes the patch bundle install to remove 1.0.0 and remove the entry from PF so we are just left with the VIU entry for the patch, and nothing is physically installed.

Addon has the same effect as Patch.

So the setting should be left as it is - Patch.

Its only effect is to re-add the VIU entry as the msp itself is not actually executed.

Full test results shown [here](http://www.evernote.com/l/AA2s4TfEiE5Jor7Nrk_geAYJIr89qbVvIkw/)

**Comment by robmen** [comment]
This is one behavior that came to us in bulk from Visual Studio in the v3.9 timeframe where we did not have as much input into the design as we would have liked. Some of the functionality has been very useful to have but there have been some very broken scenarios as well. None of it was documented (not that documentation was good before).

In this case, I believe to it is required is to create a detect RelatedBundle in the v1.0.0 Bundle upfront with a unique GUID. This GUID will be the target for all v1.0.0 patch bundles. Then in v2.0.0 you change that detect RelatedBundle to a new GUID. When the patches target the detect RelatedBundle and not the upgrade codes they should not get repaired during upgrade of v1.0.0.

This is unfortunate because the goal was to be able to update bundles without needing to do lots of a priori work. If this works (I believe it will), you have to insert a detect RelatedBundle for the purposes of "patching in the future". Something we could investigate in the future, but if the above works as I understand it to, this is probably the behavior for v3.x.

**Comment by robe070** [comment]
Thanks Rob, but no dice.
I changed this in my test case:
```
Burn Bundle has
<RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CC" Action="Detect"/>
Patch Bundle has
<RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CC" Action="Patch"/>
Burn 2 Bundle has
<RelatedBundle Id="A184CF47-6B44-40FB-B5A2-900CFE0B90CD" Action="Detect"/>
```
The behavior I see when applying the patch is, in summary, that the application is uninstalled!:
1. 1.0.0 installed
2. 1.0.0.1 installed

a) Patch Bundle Executes 1.0.0.1.msp
    The patch bundle adds the patch entry into VIU

b) Patch Bundle executes 1.0.0 bundle to UNINSTALL it
    Result is that 1.0.0 and 1.0.0.1 are both uninstalled by uninstalling 1.0.0
     PF entry for 1.0.0 is removed

The log files for applying the patch:
[Patch_1.0.0.1.zip](https://github.com/wixtoolset/issues/files/407974/Patch_1.0.0.1.zip)

**Comment by robe070** [comment]
I've done another test using a unique Patch UpgradeCode, and that seems to have fixed everything! I'll write about it in more detail in the next hour or so.

**Comment by rseanhall** [comment]
I thought that `A184CF47-6B44-40FB-B5A2-900CFE0B90CD` was your upgrade code everywhere, you need some unique upgrade codes.  Rob is suggesting that you do this:

    <Bundle Version="1.0.0" UpgradeCode="AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA">
        <RelatedBundle Id="BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB" Action="Detect" />
    </Bundle>
    <Bundle Version="1.0.1" UpgradeCode="CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC">
        <RelatedBundle Id="BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB" Action="Patch" />
    </Bundle>
    <Bundle Version="2.0.0" UpgradeCode="AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA">
        <RelatedBundle Id="DDDDDDDD-DDDD-DDDD-DDDD-DDDDDDDDDDDD" Action="Detect" />
    </Bundle>

**Comment by robe070** [comment]
And thats indeed exactly what I have done!
This is how I interpret what I've found and you have documented above...
In Major Upgrade bundles the UpgradeCode must match. "AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA" in the example.
In Patch Bundles the Upgrade Code must be unique, unrelated to any other GUID used in any bundle. "CCCCCCCC-CCCC-CCCC-CCCC-CCCCCCCCCCCC" in the example.
In the Major Upgrade bundles the RelatedBundle must be unique. This GUID is used in all the patches for that Major Upgrade. "BBBBBBBB-BBBB-BBBB-BBBB-BBBBBBBBBBBB" in the example.

**Comment by robmen** [comment]
Next time take both of the issues you opened to be discussed on wix-users.

**Comment by robe070** [comment]
OK I will. And I still have an issue with the solution provided here, so do I continue it here or go to wix-users? All the context is here so it seems sensible to continue here.

**Comment by robe070** [comment]
But this introduces another more minor issue. The patch bundle will now install successfully even when 1.0.0 is not present. And if the patch is marked as permanent=yes, 1.0.0 is needed to be installed in order to uninstall it! Of course the underlying MSP has not been installed, it just looks like it has. 

This is caused by the UpgradeCode differing between 1.0.0 and 1.0.0.1, which it has to be otherwise installing 1.0.0.1 uninstalls the whole app! See previous issue above.

[Patch_1.0.0.1_20160809185122.zip](https://github.com/wixtoolset/issues/files/410130/Patch_1.0.0.1_20160809185122.zip)

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
