### ISSUE TITLE
Clarify default behavior of /layout switch in Help page

### ISSUE THREAD

**Issue by joeloff** [wixtoolset/issues#5368]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> 2015

* Which version of .NET are you building with?

> 4.5

* Describe the problem and the steps to reproduce it.

> The default help shown when executing a bundle with /? doesn't indicate that /layout without a folder will copy the packages to the temporary folder. This makes it difficult for customers to discover

* Describe the behavior you expected and how it differed from the actual behavior.

> Help should clarify the default behavior. It's possible to override the default help screen by providing an override of the string in a .wxl file, but this needs to be added to every project. Having it in the default theme would simplify building new bundles

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Help customers understand what the intensions and behavior of /layout option is.

* Describe how you're accomplishing the feature today (if possible).

> A custom theme file and .wxl can be used to override the default help text.

* Describe what you'd like the new feature to do.

> Update the default help strings

**Comment by robmen** [comment]
This is related to #5369 which is not an issue in WiX v3.10.3.
