### ISSUE TITLE
/layout [Dir] - AttachedContainer content is lost

### ISSUE THREAD

**Issue by joeloff** [wixtoolset/issues#5369]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> 2015

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Win 7, Win 8, Win 10, Windows Server

* Describe the problem and the steps to reproduce it.

> Create a bundle that contains both downloadable packages and some smaller packages that are embedded in the attached container. When you execute the bundle with /layout switch, e.g. Foo.exe /layout C:\Bar, all the online packages are downloaded into C:\Bar. The bundle engine seems to be copied into C:\Bar as well, but when you execute the bundle from Bar, it fails, because its only the bundle engine (none  of the attached container items are present in the copied executable).

* Describe the behavior you expected and how it differed from the actual behavior.

> When the bundle is copied to C:\Bar I would expect it to be the bundle and not just the bundle engine. Since only the bundle engine is present, running it from the layout folder fails when the original installer had packages embedded in the attached container.

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Customers, especially corporate customers often have machines that have restricted internet access. By creating a layout, they can place the full install on an internal share allowing products to be installed on servers that cannot go online to download packages on demand. However, if the packages contain embedded content in the attached container, the layout that is created isn't functional unless you replace the bundle engine with the actual bundle itself in the layout folder.

* Describe how you're accomplishing the feature today (if possible).

> We communicate this information to customers through blog posts, readmes, emails, etc.

* Describe what you'd like the new feature to do.

> Instead of copying the bundle engine, copy the bundle to the layout folder

**Comment by rseanhall** [comment]
Can you attach the log?  This should have only been an issue in v3.10.2.

**Comment by barnson** [comment]
Doesn't repro with the WiX v3.10.3 bundle itself.

**Comment by joeloff** [comment]
Yeah, our bundle was built with 3.10.2.2516

**Comment by robmen** [comment]
@joeloff Why did you file the bug against `v3.10.3.3007`? This wasted a good bit of our time. :cry:

**Comment by joeloff** [comment]
Sorry about that @robmen, wasn't on purpose.
