### ISSUE TITLE
Support the newly-released .NET Framework 4.6.2

### ISSUE THREAD

**Issue by nathan-alden** [wixtoolset/issues#5370]
Microsoft just released .NET Framework 4.6.2. It would be awesome if WiX were updated to support the latest redistributable downloads.

**Comment by robmen** [comment]
Totally. Would you please contribute it? The patterns for .NET Framework are very well established and should be straight forward for someone new to the WiX Toolset to learn and replicate.

**Comment by nathan-alden** [comment]
Sure. I was already looking at the commits for the same change with .NET 4.6.1. I'll see if I can do a pull request.

**Comment by nathan-alden** [comment]
Hi, Rob. I'm working on the changes now, and one thing I noticed is that the public key for Microsoft's sha1 signing certificate seems to have changed, even for the .NET 4.6.1 web installer. The thumbprint is the same (`52868DFCA6E3AF2632389E6C1EE7D0468D3797D0`) but the old public key is `52868DFCA6E3AF2632389E6C1EE7D0468D3797D0` and the new one is `3082010A028201010092FC6F36BBE103B928D646D1A261BAA546FB63163E2EF947D2C7ECEDC799B1265175BDDACC0F061411A46C199EC05F4D5489E44D50D88DCDA161A577139A1CA7ED0D74F7A75679E828F753D2B17A63E0F59497B7ECD947F86C3DF32588B3BC0AC504A78E7C8548761C6146AA19C47A628BC1C235AAFB586FC5630B934930811B7BDF7F7C4FB4476D5F781CAFB6F7961352EFB9D14D39E573DE484E3C14AA970D39CC8B51E15CD13BF08E67EA3060A94D5A9D43BDDB23BAC00FD74B109D9C4DF051A284AAE49CA73DD6A3EF0A1848A8FAB14EA5980E4BBFF014F300C8B048D65BFE38D789112D05BA43024F22009625AD7D356E8468AB20183828FE1CA210B1A50203010001`:

![image](https://cloud.githubusercontent.com/assets/1189759/17454007/02ba5930-5b4e-11e6-83f7-8bad2136f01e.png)

The .NET 4.6.2 web installer's public key is the same. It looks the key itself was issued in 2015 so perhaps they resigned the installers to prevent verification failures?

Please let me know if I should use this new key, or if I'm getting something wrong. The keys for the old installers probably need to be updated, as well.

**Comment by nathan-alden** [comment]
Another issue I'm having is with `NetFx462WebLink` and `NetFx462RedistLink`. In `NetFx461.wxs`, the links appear to be direct download links. However, I cannot find an `fwlink` direct download link for the .NET 4.6.2 installers. I did find two `fwlinks` (http://go.microsoft.com/fwlink/?LinkId=671728 and http://go.microsoft.com/fwlink/?LinkId=671743) but they take me to a download landing page. There are direct download links on those pages but I am worried they might change from time to time. I think WiX intends on these two links being direct download links. Ideas?

**Comment by nathan-alden** [comment]
#372

**Comment by nathan-alden** [comment]
nathan-alden#372

**Comment by nathan-alden** [comment]
https://github.com/wixtoolset/wix3/pull/372

**Comment by robmen** [comment]
PS: I should have mentioned, use `heat payload` to generate all that data instead of trying to calculate it by hand.

**Comment by 9Rune5** [comment]
FYI: SHA-1 is shunned these days. (https://blogs.windows.com/msedgedev/2016/04/29/sha1-deprecation-roadmap/#TtkXz63iFTV4TPOQ.97)

That could explain why the signing certificate changed.
