### ISSUE TITLE
Enhance WiX Utility Extension User element to include Comment property

### ISSUE THREAD

**Issue by DarrelF** [wixtoolset/issues#5371]
The WiX Utility Extension User element does not support a comment property for adding a comment/description to the created user account. It would be nice to have a comment property so one doesn't have to schedule a separate custom action to set the comment using 'net.exe user MyUser /comment:"My comment for my user."'

Please consider adding a Comment property to WiX Utility Extension User element.

**Comment by cpuwzd** [comment]
This doesn't look too hard. I'll check it out.

**Comment by cpuwzd** [comment]
Creating pull request.
