### ISSUE TITLE
Operator ~<> does not work

### ISSUE THREAD

**Issue by alexsandrovp** [wixtoolset/issues#5372]
## Bugs
- Which version of WiX are you building with?

> 3.9.1208.0
- Which version of Visual Studio are you building with (if any)?

> none (command line)
- Which version of .NET are you building with?

> .NET 4.0
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows v6.1 (Build 7601: Service Pack 1)
- Describe the problem and the steps to reproduce it.

According to https://www.firegiant.com/wix/tutorial/com-expression-syntax-miscellanea/expression-syntax/ the operator ~<> should have the following behavior:

> ~<> not equal, case insensitive

I have a wix-burn package where I have defined the following registry search:

`<util:RegistrySearch Format="raw"
            Id="SearchPlantronicsHubBundle" Variable="PlantronicsHubType"
            Root="HKLM" Key="Software\Plantronics" Value="SpokesInstallerType" />`

and I bootstrap a package based on a condition defined as follows:

`<MsiPackage Id="SpokesNativeRuntime" Cache="yes" Permanent="no" Compressed="yes"
                       InstallCondition='PlantronicsHubType~&lt;&gt;"bundle"'
                       SourceFile="SpokesSDKNativeRuntime.msi" />`

When I make an upgrade where the previous bundle have installed SpokesSDKNativeRuntime.msi, this msi is being uninstalled, due to InstallCondition being evaluated to false, even though the variable 'PlantronicsHubType' is not set to anything, as can be seen in the log:

> [04BC:0288][2016-08-03T16:11:11]i001: Burn v3.9.1208.0, Windows v6.1 (Build 7601: Service Pack 1) ...
> ...
> [04BC:0288][2016-08-03T16:11:11]i000: Registry value not found. Key = 'Software\Plantronics', Value = 'SpokesInstallerType'

The log later says that my condition evaluates to false, although 'PlantronicsHubType' is not even set and is obviously different than "bundle" or any other variant like "BUNDLE" or "Bundle"

> [04BC:0288][2016-08-03T16:11:18]i052: Condition 'PlantronicsHubType~<>"bundle"' evaluates to false.
> [04BC:0288][2016-08-03T16:11:18]w327: Will not uninstall package: SpokesNativeRuntime, found dependents: 1

Although the log also says that SpokesNativeRuntime.msi will not be uninstalled due to a quite mysterious reason ("found dependents: 1" - what does that mean?), that package is actually uninstalled, because I cannot find its binaries and registries in my system anymore. This can be considered another bug.

The main problem is that the condition

> InstallCondition='PlantronicsHubType~&lt;&gt;"bundle"'

should've never been considered false
- Describe the behavior you expected and how it differed from the actual behavior.

> InstallCondition='PlantronicsHubType~&lt;&gt;"bundle"

should evaluate to true when the variable 'PlantronicsHubType' is not even defined.

**Comment by alexsandrovp** [comment]
An extra piece of information.

I tried to preset my variable with a dummy value:

> <Variable Name="PlantronicsHubType" Type="string" Value="0" />

but the condition with ~<> still incorrectly evaluates to false. 

If then I change the condition to use <> instead of ~<>, the evaluation works correctly and my prerequisite is not uninstalled.

So, the operator ~<> seems not to be working in any case...

**Comment by rseanhall** [comment]
I'm a little rusty on how this is supposed to work, but have you tried removing the quotes and/or putting space between the values and the conditions?

    InstallCondition='PlantronicsHubType~&lt;&gt;bundle'
    InstallCondition='PlantronicsHubType ~&lt;&gt; "bundle"'
    InstallCondition='PlantronicsHubType ~&lt;&gt; bundle'

**Comment by alexsandrovp** [comment]
I tried what you suggested, but the outcome was the same.
The only workaround i was able to find was to use operator <> instead of ~<>

**Comment by barnson** [comment]
`~<>` generally works:

    [2260:01A0][2016-08-06T17:30:27]i000: Initializing string variable 'Foo' to value 'BAR'
    [2260:01A0][2016-08-06T17:30:32]i052: Condition 'Foo ~<> "Bar"' evaluates to false.

    [0FFC:055C][2016-08-06T17:19:51]i000: Initializing string variable 'Foo' to value 'BAZ'
    [0FFC:055C][2016-08-06T17:20:16]i052: Condition 'Foo ~<> "Bar"' evaluates to true.

But not so much with empty strings. 

    [2B54:1420][2016-08-06T17:24:00]i052: Condition 'Foo ~<> "Bar"' evaluates to false.

The reason is that Burn treats it as a NULL and type-none variant and so never actually compares it. Line 902 in the CompareValues function defaults to comparing BURN_SYMBOL_TYPE_NE and should also probably do so with BURN_SYMBOL_TYPE_NE_I as well.
