### ISSUE TITLE
Wix 4 Schema is 404

### ISSUE THREAD

**Issue by togakangaroo** [wixtoolset/issues#5373]
I am using the xml namespace that I've seen recommended:

```
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
```

This namespace URL does not exist. Where then is the xsd?

**Comment by rseanhall** [comment]
The schema is not hosted there, partly because it could be different between releases.  It gets installed at %WIX%\doc\wix.xsd when you install the toolset.

**Comment by barnson** [comment]
Schema URIs are just unique identifiers.
