### ISSUE TITLE
WIX - uninstall is not working when triggered from Apps & Features in Windows 10

### ISSUE THREAD

**Issue by ishaat** [wixtoolset/issues#5376]
* Which version of WiX are you building with?

> WiX v3.11.0.705

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2013 Version 12.0.40629.00 update 5

* Which version of .NET are you building with?

> .Net 4.5.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> It happens while uninstalling from Apps & features in Windows 10.

* Describe the problem and the steps to reproduce it.

> I am using WiX v3.11.0.705 in my application. When I try to uninstall my application using Apps & Features in Windows 10 system, then it displays the following error: Error Message

The error message is "C:\Windows\system32\rundll32.exe" Element not found.
![gcetq](https://cloud.githubusercontent.com/assets/19407687/17775354/7f07bfc4-6575-11e6-8b6c-a066f37824dd.png)

On clicking OK, the uninstall cancels but the explorer remains closed. However, when I uninstall the same application using Control Panel, it works fine.
* Describe the behavior you expected and how it differed from the actual behavior.

> On uninstalling from Apps and Features option in Windows 10, the application should successfully be uninstalled.

## Feature requests

No its not a feature request.

**Comment by rseanhall** [comment]
What is the OS Build of the Windows 10 machine?  You can see this by clicking Start, typing "About your PC", and opening that.

We need a way to reproduce the problem.  A verbose MSI log would help, and also the authoring for the part of the MSI that's triggering this error.

v3.11.0.705 should have the workaround that we did for #4857, so it's unlikely that this is something that WiX can fix.

**Comment by barnson** [comment]
Is your "application" a bundle or a package?

**Comment by ishaat** [comment]
@rseanhall 
I am using Windows 10 Enterprise Version 10.0 (Build 10240).

@barnson 
We are having both the bundle and the package and I am seeing the issue in both of them

**Comment by barnson** [comment]
Please attach any logs created from both packages and bundle attempts.

**Comment by ishaat** [comment]
[Fail_log.txt](https://github.com/wixtoolset/issues/files/431860/Fail_log.txt)
@barnson I have attached the log when uninstalling from Apps & Features

**Comment by robmen** [comment]
The failure:

    SFXCA: Failed to shellex new CA process via RUNDLL32. Error code: 1223

http://errorco.de/win32/winerror-h/error_cancelled/1223/
    
    winerror.h 1223
    #define ERROR_CANCELLED
    The operation was canceled by the user.

**Comment by ishaat** [comment]
Yeah. From the logs, its appearing that the user has canceled but on uninstalling a dialog box appears "C:\Windows\system32\rundll32.exe" Element not found. And on clicking Ok, Uninstallation is revoked and the explorer remains closed.

**Comment by barnson** [comment]
This is a bug in Windows' modern ARP.
