### ISSUE TITLE
Deprecate and remove Package element

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5377]
The split between the Product and Package elements is confusing and mostly historical. At the same time, the Package element contains a number of obsolete and/or questionably-useful attributes that mostly exist to allow WiX to generate an arbitrary package. WiX v4.0 should remove the Package element, moving its useful attributes to Product and eliminating the rest.

See WIP: https://github.com/barnson/web/blob/9f22290b84198ed527d5083832a93a11a98790fd/root/documents/development/wips/5377-deprecate-and-remove-package-element.html.md

**Comment by barnson** [comment]
wix-devs discussion: http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/2016-August/000469.html

**Comment by barnson** [comment]
https://github.com/wixtoolset/Core/pull/188
https://github.com/wixtoolset/Converters/pull/36

**Comment by barnson** [comment]
A bit of work still to do:

- [x] Core
- [x] Converters
- [ ] ComPlus
- [ ] Dependency.wixext
- [ ] DirectX.wixext
- [ ] Firewall.wixext
- [ ] Http.wixext
- [ ] Iis.wixext
- [ ] Msmq.wixext
- [ ] Netfx.wixext
- [ ] Sql.wixext
- [ ] Tag.wixext(eventually)
- [ ] UI.wixext
- [ ] Util.wixext

**Comment by barnson** [comment]
https://github.com/wixtoolset/Util.wixext/pull/30
https://github.com/wixtoolset/Netfx.wixext/pull/23
https://github.com/wixtoolset/Firewall.wixext/pull/10
https://github.com/wixtoolset/Http.wixext/pull/7
https://github.com/wixtoolset/Iis.wixext/pull/14

**Comment by barnson** [comment]
https://github.com/wixtoolset/ComPlus.wixext/pull/4
https://github.com/wixtoolset/Dependency.wixext/pull/6
https://github.com/wixtoolset/DirectX.wixext/pull/5
https://github.com/wixtoolset/Msmq.wixext/pull/4
https://github.com/wixtoolset/Sql.wixext/pull/9
https://github.com/wixtoolset/Tag.wixext/pull/4
https://github.com/wixtoolset/UI.wixext/pull/8

**Comment by barnson** [comment]
https://github.com/wixtoolset/VisualStudio.wixext/pull/7
https://github.com/wixtoolset/DifxApp.wixext/pull/4
https://github.com/wixtoolset/PowerShell.wixext/pull/3

**Comment by rseanhall** [comment]
Need to update the [.xsd](https://github.com/wixtoolset/doc/blob/main/src/xsd4/wix.xsd).
