### ISSUE TITLE
Documentation website contains multiple errors

### ISSUE THREAD

**Issue by apacha** [wixtoolset/issues#5378]
The website:
http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html

the corresponding file can be found in wixtoolset/web/root/documents/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html.md

contains multiple errors, such as
- In section 2 the markup is broken and the link appears as `[WixNetfxExtension](../../customactions/wixnetfxextension.html)`
- In section 3 the example code is incorrect (the closing PayloadGroup is not valid XML). It should be
  `</PayloadGroup>` instead of `<PayloadGroup/>`

**Comment by andrekoehler** [comment]
Section 3 is currently correct, section 2 is still broken.

**Comment by barnson** [comment]
Someone/something fixed these.
