### ISSUE TITLE
Calling Run method of WiX BootstrapperApplication class using C# code?

### ISSUE THREAD

**Issue by Diwakar243** [wixtoolset/issues#5381]
Currently Run method of BootstrapperApplication class is called as soon as we launch the Setup built using WiX after adding an attribute called BootstrapperApplicationAttribute to the Properties\AssemblyInfo.cs like below

[assembly: BootstrapperApplication(typeof(CustomBootstrapperApplication))]

here CustomBootstrapperApplication class extends BootstrapperApplication.

I am using WiX CustomBA to build my setup.

Is there any other way to call the Run method directly without the need of WiX Burn engine using C# code (button click event) ?

Even if we call, all the initialization (Burn Engine and Command properties) should happen as if we launch the setup

Any help would be appreciated.

Thanks

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
