### ISSUE TITLE
Web - Weekly Releases - None since 7/5/2016

### ISSUE THREAD

**Issue by Kaelum** [wixtoolset/issues#5383]
We recently retargeted an application of ours to 4.6.2, mainly for the long filepath support, and I see that code was checked in 9 days ago to support **WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED**, but I also noticed that the [**Weekly Releases**](http://wixtoolset.org/releases/) have stopped.  Does anyone know when they will again be available?

**Comment by robmen** [comment]
This is on me. I've been slacking on my tracking of `wix3`.

**Comment by Kaelum** [comment]
Cool.  I'm looking forward to testing the latest code.

**Comment by rseanhall** [comment]
http://wixtoolset.org/releases/v3-11-0-906/
