### ISSUE TITLE
In-proc task execution results with light.exe hangs

### ISSUE THREAD

**Issue by wgebczyk** [wixtoolset/issues#5384]
- WiX 3.10.2 and 3.10.3
- executed on VSTS env
- creating ~300MB of binaries in its content

First observation is that even if I redirect WiX to run it from NuGet, task classes are taken from program files. I've tried everything including /v:diag that stated Task is loaded from WiX NuGet folder, but assemblies used dump pointed to program files. The issue was because Light element in MSBuild was trying to set property that not existed in one of the WiX version. I've worked around that by redefining whole "Link" task and removing offending property setter.

Second issue is related to Light.exe which simply stopped to work in VSTS env. When it works it takes 2-4 minutes in VSTS to process. Recently lg file reports calling "light.exe" process and nothing regardless of additional 20 min or 4 hours time. Outputted light.exe command line executed manually worked fine. Further investigation revealed that log file was simply lying!!! It was loading light.exe into msbuild process and for some reason stopped responding (debugging build agent in VSTS is beyond my capabilities).

Looking through disassembled DLLs (browsing on github really sucks as navigation between definition and calls does not exists) showed "smart" optimization - if task is run in x86 process it will load into memory, otherwise create new process.

As of now wix2010.tagets has this property definition:
```
  <!-- WiX tools are 32bit EXEs, so run them out-of-proc when MSBuild is not 32bit. -->
  <PropertyGroup>
    <RunWixToolsOutOfProc Condition=" '$(PROCESSOR_ARCHITECTURE)'!='x86' ">true</RunWixToolsOutOfProc>
  </PropertyGroup>
```
i had to put property definition inside of copied Link task to bypass this.

* Please make more official way to disable InProc tool running.
* Please do not lie in diagnostics information as it takes your user's time to investigate not fully tested features.
* Yes, you can ignore that as I've provided workarounds in above text for other users that would encounter such issues.

Thanks!

**Comment by barnson** [comment]
1. WiX doesn't have an official NuGet package so if you're having problems with one, you need to take it up with whoever provided it.
2. `RunWixToolsOutOfProc` is the official way to run out of proc.
3. How is the log "lying"?

**Comment by wgebczyk** [comment]
OK, Are you stating that if I take files from github and compile and run it it the issue will not appear?

Well - that's my last comment as you simply not referring to issue, but to somthing rather unrelated - how does it matter to use NGet or not???

Good luck with such community :)
Have a nice day!

**Comment by barnson** [comment]
Your entire first paragraph was about a problem with the NuGet package. If you're not interested in providing more details about the other problem, well, that's too bad.
