### ISSUE TITLE
Restart require install button to click on WIX installer to continue

### ISSUE THREAD

**Issue by adharjain** [wixtoolset/issues#5385]
I am using Wix 3.10. I install KB X.1, then KB X.2, computer restarts and I use 3010 exit code.
When it restarts, it gives me same button to Install and I need to click on this button to continue further.
Is there a way that I do not need to click install again and again? because I would be running another update and it will reinstall and then it again asks to click on Install.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
