### ISSUE TITLE
Support for WIX_IS_NETFRAMEWORK_461_OR_LATER_INSTALLED and NetFx461Web

### ISSUE THREAD

**Issue by mecsco** [wixtoolset/issues#5391]
I see that the property WIX_IS_NETFRAMEWORK_461_OR_LATER_INSTALLED and package NetFx461Web exist in the 'develop' branch under wix3/src/ext/NetFxExtension/wixlib/NetFx461.wxs - however it has not been merged to a 3.10.x release yet. Is there any plan to do this?

Likewise WIX_IS_NETFRAMEWORK_462_OR_LATER_INSTALLED / NetFx462Web for .NET 4.6.2, given that this version has recently been released by Microsoft too.

Thanks in advance,
Daniel

**Comment by barnson** [comment]
There are no plans for another v3.10 release.
