### ISSUE TITLE
Buttons don't show the text the first time I open the page

### ISSUE THREAD

**Issue by VapiSoft** [wixtoolset/issues#5392]
A Bug: on WIX version: I can't find the version number, but I am using WIX on line.

Please enter:  http://www.mobile-gap.net/ (from an iPhone)
The "Download" page has 2 buttons.
They don't show the text in them the first time you open the page.
The second time it is OK (but my user won't know that).
Please note: 
Do not try it on a desktop browser, it works OK.

**Comment by barnson** [comment]
This tracker is for the WiX Toolset not wix.com.
