### ISSUE TITLE
Using variable in util:RegistrySearch for Win64 attribute

### ISSUE THREAD

**Issue by cybrex86** [wixtoolset/issues#5393]
Example:

`<util:RegistrySearch Id='VC2015' Variable='VC2015' Result='exists' Root='HKLM' Value='Version' Key='$(var.InstalledSoft)$(var.Vc2015uuid)' Win64='$(var.Win64)' />`

This code compile with warning: "Instructs the search to look in the 64-bit registry when the value is 'yes'. When the value is 'no', the search looks in the 32-bit registry. The default value is 'no'."

Because attribute Win64 has type **YesNoType**.  

But this code, ok:
`<RegistrySearch Id='vc2015' Root='HKLM' Name='Version' Type='raw' Key='$(var.InstalledSoft)$(var.Vc2015uuid)' Win64='$(var.Win64)' />`

Because attribute Win64 has type YesNoTypeUnion.

**Comment by barnson** [comment]
Our issue template asks for important information. Please provide it.

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

**Comment by cybrex86** [comment]
* Which version of WiX are you building with?

> 3.10.2103.0

* (Visual Studio version, including year and update)

> Visual Studio 2015, 14.0.25425.01 Update 3

**Comment by barnson** [comment]
Thanks. The problem is with IntelliSense. Compilation isn't affected.
