### ISSUE TITLE
Running a bundle with "/layout /quiet" when a reboot is pending causes unprompted reboot

### ISSUE THREAD

**Issue by zanderz** [wixtoolset/issues#5394]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.
## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.
## Bugs

If this issue is a bug:
- Which version of WiX are you building with?
  Burn v3.10.2.2516
  Windows Installer XML Toolset Compiler version 3.10.2.2516
  > (WiX version in major.minor.release.build format)
  3.10.2.2516
- Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)
> Microsoft Visual Studio Community 2015
> Version 14.0.24720.00 Update 1
- Which version of .NET are you building with?

> (.NET version)
> Microsoft .NET Framework
> Version 4.6.01586
- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
> 10
- Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
1. Run a burn bundle that requires reboot before completion, and exit without rebooting
2. Run an upgrade (or the same bundle) with the arguments `/layout /quiet`
3. Machine will suddenly reboot with no prompt or warning

Note that in step 2, invoking with just '/layout' will yield a warning that an install is pending.
- Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

`/layout' should not cause a reboot, even if one is pending. 
## Feature requests

If this issue is a feature request:
- Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

`/layout` documentation is sparse but we are trying to use it to generate a log to parse to see what versions of packages it contains during an upgrade. Usually works pretty well.
- Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

It is a bit if a chicken and egg problem, but we have a requirement to have one bundle which conditionally can update silently or invoke UAC with a dialog when it contains a driver update. We have a separate updater process which needs to know which kind of update the bundle contains before presenting UI to the user. It took a long time, and many angry users, before we realized invoking the layout in this case can force a reboot, which really seems like a bug.

Perhaps we are misusing the /layout feature? All we need is a manifest of what the bundle contains - perhaps that's a separate feature request.

Here is where the pending reboot is first set (installer is in a public repo):
https://github.com/keybase/client/blob/master/packaging/windows/WIXInstallers/KeybaseBundle/Bundle.wxs#L95
- Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

Not reboot when /layout /quiet are given.

[Keybase_20160902135410.log.txt](https://github.com/wixtoolset/issues/files/452928/Keybase_20160902135410.log.txt)

**Comment by rseanhall** [comment]
You could use dark.exe to extract the `BootstrapperApplicationData.xml` file which probably has the information you need.
