### ISSUE TITLE
Feature request: customize pre-req ba reboot prompt dialog text

### ISSUE THREAD

**Issue by glun24** [wixtoolset/issues#5395]
## Feature requests
- Describe the scenario and benefits that the feature supports.

Using burn v3.10.2.2516 
After installing mba pre-req package, the pre-req bootstrapper will show a reboot prompt dialog if reboot is required. The text on the dialog is:
“The requested operation is successful. Changes will not be effective until the system is rebooted.”
Two buttons will show on the dialog: “OK” and “Cancel”.
If the user presses the “OK” button, the computer will be rebooted immediately.
The text on the dialog is misleading to the user. The user don’t necessarily understand that the computer will reboot immediately when the “OK” button is pressed.
- Describe what you'd like the new feature to do.

I’ve like an option to:
Add the following text to the reboot prompt dialog text: “Press OK to reboot now.”.
Or:
Change the “OK” button text to: “Reboot now”

![pre-req reboot dialog](https://cloud.githubusercontent.com/assets/22026990/18273987/7581a0a8-7440-11e6-92fa-c836878b23d4.PNG)

**Comment by rseanhall** [comment]
Related to https://github.com/wixtoolset/issues/issues/3957
