### ISSUE TITLE
WiX Project Fails to Load in Visual Studio 2015

### ISSUE THREAD

**Issue by mikedsensus** [wixtoolset/issues#5397]
On Windows 7, I installed Visual Studio Professional 2015. No prior Visual Studio installs ever existed on this machine. Next, I downloaded and installed Wix Toolset v3.10.3.3007.  When opening solution file (.sln) in Visual Studio which contains a WiX Project installer, the WiX Project will NOT load.  Text in Solution Explorer says "The application is not installed." and the WiX Project is (incompatible). However, under Programs and Features, the WiX Toolset v3.10.3.3007 is currently an installed program. Also notice when creating a New Project, the XML Templates for WiX are missing.

Here's Visual Studio from About Box:
- Microsoft Blend for Visual Studio Professional 2015
- Version 14.0.25425.01 Update 3
- Microsoft .NET Framework
- Version 4.6.01055
- Installed Version: Blend
- Visual Basic 2015   00322-40000-00000-AA957
- Microsoft Visual Basic 2015
- Visual C# 2015   00322-40000-00000-AA957
- Microsoft Visual C# 2015
- Visual C++ 2015   00322-40000-00000-AA957
- Microsoft Visual C++ 2015
- ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
- ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
- GitHub.VisualStudio   1.0
- NuGet Package Manager   3.5.0
- Visual Studio Tools for Universal Windows Apps   14.0.25527.01

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX Toolset 3.10.3.3007 ) 

* Which version of Visual Studio are you building with (if any)?
> (Visual Studio Profession 2015 Update 3) 

* Which version of .NET are you building with? 

> (.NET 4.0)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?  

> (Windows 7) 

* Describe the problem and the steps to reproduce it.

On Windows 7, I installed Visual Studio Professional 2015. No prior Visual Studio installs ever existed on this machine. Next, I downloaded and installed Wix Toolset v3.10.3.3007.  When opening solution file (.sln) in Visual Studio which contains a WiX Project installer, the WiX Project will NOT load.  **Text in Solution Explorer says "The application is not installed." and the WiX Project is (incompatible).** However, under Programs and Features, the WiX Toolset v3.10.3.3007 is currently an installed program. Also notice when creating a New Project, the XML Templates for WiX are missing.

UpgradeLog.htm says:
Installer\Installer.wixproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkId=659044&projecttype=930C7802-8A8C-48F9-8165-68863BCCD9DD

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

**Solutions containing a WiX Project should load and be editable in the Visual Studio IDE**

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by roborchistonattabotics** [comment]
Im getting this same error message with VS2019. The solution works fine on  VS2019, but when I open it in 2019, all the Wix installers have the message above.
