### ISSUE TITLE
Which is the correct license?

### ISSUE THREAD

**Issue by tngraf** [wixtoolset/issues#5398]
It seems that most files in Wix 3.11, folder src/Votive/votive2013/vssdk/ contain two license references: one on top stating that its MS-RL licensed and directly below is the complete license text of MS-PL.
As LICENSE.TXT states that the whole WiX toolkit (which is really great and I'm using it for years!) is MS-RL license I'd recommend to remove the MS-PL license text if appropriate.

Details
- Which version of WiX are you building with?
  WixBuild: Version 3.11.0.906, Latest commit 7c8457f

Thanks,

Thomas

**Comment by barnson** [comment]
https://github.com/wixtoolset/wix3/pull/380
