### ISSUE TITLE
Keyboard mnemonics in the Installer are not (always) visible

### ISSUE THREAD

**Issue by WilcoBT** [wixtoolset/issues#5400]
We build at this moment with Wix toolset v3.10.3.3007 but have seen it already with earlier versions for exmple 3.8.1128.0 The installer we create has no underscores under the N (for next) and B (for back). If you use the mouse to click these buttons it stays that way, but the moment you have once used a N or a B they do seem to be there (But I just noticed them on the finish button being missing again sometimes).
Interestingly enough, there seems to also be some kind of memory between runs of the installer as sometimes it seems to remember last time was with mnemonics and start with underscores, but then they vanish if you use the mouse.

A second related issue, the Cancel button never has anything underscored, probably because it is bound to the escape key, but maybe that one could use something underscorable as well.

What we would have expected was that these clues would be there always from the start

the .net and windows versions differ depending on the machine building, this does not seem to play a role as it happens with things build on an ancient xp machine to a modern fully updated win10

Attached is a installer stripped of its files etc illustrating the issue
[FlowXpress_Setup.zip](https://github.com/wixtoolset/issues/files/471791/FlowXpress_Setup.zip)

**Comment by barnson** [comment]
That's how Windows works generally. Users can control that in `Control Panel\Ease of Access Center\Make the keyboard easier to use\Underline keyboard shortcuts and access keys` (on Windows 10). Per UI guidelines, Cancel should never have a shortcut key.
