### ISSUE TITLE
bindpath issue

### ISSUE THREAD

**Issue by Rengia** [wixtoolset/issues#5401]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.10.3

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2015

* Which version of .NET are you building with?
No .NET

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Every Windows version

* Describe the problem and the steps to reproduce it.
If you work with bindpath variables, we have a straing behaviour, if there is no backslash between binderpath and filename:

<File Id="Test" Source="!(bindpath.Test)Test.txt" KeyPath="yes"></File>

If bindpath "Test" is for example "d:\TestFolder\" the build works without errors. But in file table (within the MSI) the FileName column has a value like leyyrbbi.txt|!(bindpath.Test)Test.txt. Expected was only test.txt.

This issue only occurs, if between binderpath and filename there is no backslash in wxs script.

**Comment by robmen** [comment]
Correct. The `\` is the separator the compiler uses to find the implicit filename in the `Source` attribute. You can either add the `\` or explicitly call out the filename with the `Name` attribute.
