### ISSUE TITLE
Webroot secure anywhere finds Pua.Add.Lyrics virus in Wix310.exe 

### ISSUE THREAD

**Issue by santoorman** [wixtoolset/issues#5404]
I downloaded latest WIX310.exe installer from following web page.  Is there really an issue with installer or is my anti-virus being overzealous?  Anyone else get this issue?

https://wix.codeplex.com/releases/view/624906

![2016-09-17_11-12-17](https://cloud.githubusercontent.com/assets/629163/18610100/b54e7398-7cc7-11e6-85d7-6f43e637ac9a.png)

**Comment by barnson** [comment]
https://www.metadefender.com/#!/results/file/25d0a1870b2b412cb16759bbe2cac18d/regular/analysis says no.

**Comment by JVimes** [comment]
Two of the scanners on VirusTotal.com [flag it as malicious](https://www.virustotal.com/en/file/9a4d1ffd02548a876c54707197437899bf2344cf2a9e5586f62c12d4ad3e2f1f/analysis/). I doubt it really is malicious, but it got blocked by my corporate firewall.

**Comment by robmen** [comment]
Submitted. Hopefully that will resolve the issues in next week or so.
