### ISSUE TITLE
WiX 3.11: CustomActions and WinForms problem

### ISSUE THREAD

**Issue by win32nipuh** [wixtoolset/issues#5405]
I have a VS2015 solution including WiX installer project.
The installer uses c# Custom Actions assembly with some WinForms.

When I build the solution using WiX 3.10 - all works fine.
But when I use WiX 3.11 on the same machine - no any WinForms appear.

I uninstalled WiX 3.11 and install Wix 3.10 again, built - all works fine.

**Comment by barnson** [comment]
Please provide more details: Which version of WiX v3.10? Which version of WiX v3.11? How does your custom action call WinForms? How is your custom action scheduled?

**Comment by win32nipuh** [comment]
Hi, I have created the test project and reproduced the problem.
Run MSI and click on "Help" button - the simple Form appears.

Install Wix 3.10 (the latest stable) -  it appears.
Install Wix 3.11 (the latest build) -  the installer hangs and can be aborted only via taskmanager.

The solution is here
http://ge.tt/9ucAE7f2

Regards

**Comment by rseanhall** [comment]
@win32nipuh please upload to a different place, all browsers are blocking downloads from that site.

**Comment by win32nipuh** [comment]
ok, on what server?

**Comment by rseanhall** [comment]
I would think the easiest thing to do would be to create a new repo here on github with your code.  Or Google Drive, OneDrive, Dropbox etc.

**Comment by win32nipuh** [comment]
I have attached zip:

[WixExample2.zip](https://github.com/wixtoolset/issues/files/496574/WixExample2.zip)

**Comment by rseanhall** [comment]
Thanks, I'll take a look in the next few days.

**Comment by win32nipuh** [comment]
Ok, thank you.

**Comment by win32nipuh** [comment]
Hi, did you have a time to check it? any progress?

**Comment by rseanhall** [comment]
Looks like we have to revert the workaround from https://github.com/wixtoolset/issues/issues/4857.  Which is fine since it didn't work for later versions of Windows anyway.

**Comment by barnson** [comment]
Fixed: https://github.com/wixtoolset/wix3/pull/382
