### ISSUE TITLE
FirewallException and quiet installation hangs?

### ISSUE THREAD

**Issue by rodwiddowson** [wixtoolset/issues#5406]
Probably PEBKAC.  Also, am willing to work on producing a repeatable 

If this issue is a bug:

* Which version of WiX are you building with?
**3.10.3.3007**

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 Redstone (anniversary update) x64.  But seen on other platforms (according to my customer).  Running inside VMWARE in case that matters

* Describe the problem and the steps to reproduce it.

My customer reports that my installer hangs when specified run /qn.  I reproduced and in fact it's a hard loop - probably between the the installer and its slave process (this because I note that one CPU is pegged between two MSIEXEC processes).  Below is a (kernel) stack of one of the threads (I happened to have WindBg attached)

The last lines of my lv* log are 

`MSI (s) (C8:3C) [13:30:32:873]: Running as a service.`
`MSI (s) (C8:E0) [13:30:32:873]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
ExecFirewallExceptions:  Installing firewall exception2 Win32Shibd_idp (C:\Program Files (x86)\Shibboleth\ProcRun\shibd_idp.exe)`
`MSI (s) (C8:70) [13:30:33:076]: Executing op: ActionStart(Name=WriteConfigFiles,,)
ExecFirewallExceptions:  Installing firewall exception2 Win64Shibd_idp (C:\Program Files (x86)\Shibboleth\ProcRun\amd64\shibd_idp.exe)`

Corresponding to

           <Component Id="procrun_32_Firewall" Directory="PROCRUNROOT" Guid="{F93B8D9F-7BBA-4D79-995D-4AC20FF158E4}" KeyPath="yes">
                 <Condition>Not NO_FIREWALL</Condition>
                 <fw:FirewallException Id="Win32Shibd_idp" Program="[#file_procrun_32_service]" Name="Win32Shibd_idp" Description="The Shibboleth IdP" Protocol="tcp" Scope="any" />
            </Component>

           <Component Id="procrun_AMD64_Firewall" Directory="dir64" Guid="{BC605FF4-0233-4332-BC90-0C2E5FEC37D2}" KeyPath="yes">
                 <Condition>NOT NO_FIREWALL And VersionNT64 And Not Intel64</Condition>
                 <fw:FirewallException Id="Win64Shibd_idp" Program="[#file_procrun_AMD64_service]" Name="Win64Shibd_idp" Description="The Shibboleth IdP" Protocol="tcp" Scope="any" />
            </Component>

            <Component Id="procrun_IA64_Firewall" Directory="diria64" Guid="{FD33F998-E151-48BB-815F-25D96D8E48DA}" KeyPath="yes">
                <Condition>Not NO_FIREWALL And Intel64</Condition>
                <fw:FirewallException Id="WinIA64Shibd_idp" Program="[#file_procrun_IA64_service]" Name="WinIA64Shibd_idp" Description="The Shibboleth IdP" Protocol="tcp" Scope="any" />
            </Component>

- If I run `/qb` then  the installation completes.
- If I specify NO_FIREWALL then the `/qn` installation completes.

Kernel stack

`0: kd> `
` # Call Site`
`00 nt!DbgBreakPointWithStatus`
`01 nt! ?? ::FNODOBFM::'string' `
`02 nt!KeClockInterruptNotify`
`03 hal!HalpTimerClockInterrupt`
`04 nt!KiCallInterruptServiceRoutine`
`05 nt!KiInterruptSubDispatchNoLockNoEtw`
`06 nt!KiInterruptDispatchNoLockNoEtw`
`07 nt!AlpcpGetDataFromUserVaSafe`
`08 nt!AlpcpCompleteDispatchMessage`
`09 nt!AlpcpDispatchNewMessage`
`0a nt!AlpcpSendMessage`
`0b nt!AlpcpProcessSynchronousRequest`
`0c nt!NtAlpcSendWaitReceivePort`
`0d nt!KiSystemServiceCopyEnd`
`0e ntdll!NtAlpcSendWaitReceivePort`
`0f RPCRT4!LRPC_BASE_CCALL::DoSendReceive`
`10 RPCRT4!I_RpcSendReceive`
`11 combase!CMessageCall::CallI_RpcSendReceive`
`12 combase!ThreadSendReceive`
`13 combase!CSyncClientCall::SwitchAptAndDispatchCall`
`14 combase!CSyncClientCall::SendReceive2`
`15 combase!SyncClientCallRetryContext::SendReceiveWithRetry`
`16 combase!CSyncClientCall::SendReceiveInRetryContext`
`17 combase!DefaultSendReceive`
`18 combase!CSyncClientCall::SendReceive`
`19 combase!CClientChannel::SendReceive`
`1a combase!NdrExtpProxySendReceive`
`1b RPCRT4!NdrpClientCall2`
`1c combase!ObjectStublessClient`
`1d combase!ObjectStubless`
`1e vbscript!IDispatchGetIDsOfNames`
`1f vbscript!GetDispatchDispID`
`20 vbscript!ModuleBinder::DDSP::GetDispmember`
`21 vbscript!VBScriptClass_NestedRelease_Fatal_Error`
`22 vbscript!CScriptRuntime::Run`
`23 vbscript!CScriptEntryPoint::Call`
`24 vbscript!CSession::Execute`
`25 vbscript!COleScript::ExecutePendingScripts`
`26 vbscript!VBScriptClass_NestedRelease_Fatal_Error`
`27 msi!CScriptSite::ParseScript`
`28 msi!RunScriptAction`
`29 msi!CMsiCustomAction::RunScriptAction`
`2a RPCRT4!Invoke`
`2b RPCRT4!Ndr64StubWorker`
`2c RPCRT4!NdrStubCall3`
`2d combase!CStdStubBuffer_Invoke`
`2e RPCRT4!CStdStubBuffer_Invoke`
`2f combase!InvokeStubWithExceptionPolicyAndTracing::__l6::<lambda_76d9e92c799d246a4afbe64a2bf5673d>::operator(`
`30 combase!ObjectMethodExceptionHandlingAction<<lambda_76d9e92c799d246a4afbe64a2bf5673d> >`
`31 combase!InvokeStubWithExceptionPolicyAndTracing`
`32 combase!DefaultStubInvoke`
`33 combase!SyncStubCall::Invoke`
`34 combase!SyncServerCall::StubInvoke`
`35 combase!StubInvoke`
`36 combase!ServerCall::ContextInvoke`
`37 combase!CServerChannel::ContextInvoke`
`38 combase!DefaultInvokeInApartment`
`39 combase!AppInvoke`
`3a combase!ComInvokeWithLockAndIPID`
`3b combase!ThreadInvoke`
`3c RPCRT4!DispatchToStubInCNoAvrf`
`3d RPCRT4!RPC_INTERFACE::DispatchToStubWorker`
`3e RPCRT4!RPC_INTERFACE::DispatchToStubWithObject`
`3f RPCRT4!LRPC_SCALL::DispatchRequest`
`40 RPCRT4!LRPC_SCALL::HandleRequest`
`41 RPCRT4!LRPC_ADDRESS::HandleRequest`
`42 RPCRT4!LRPC_ADDRESS::ProcessIO`
`43 RPCRT4!LrpcIoComplete`
`44 ntdll!TppAlpcpExecuteCallback`
`45 ntdll!TppWorkerThread`
`46 KERNEL32!BaseThreadInitThunk`
`47 ntdll!RtlUserThreadStart` `

-

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
