### ISSUE TITLE
CustomExitDialog conflicts with ExitDialog on sequence when OnExit=success is used

### ISSUE THREAD

**Issue by Hochman85** [wixtoolset/issues#5408]
Hi,
I have created MyExitDialog in a separate wxs file with:
      **InstallUISequence
        Show Dialog="MyExitDialog" OnExit="success" /
      /InstallUISequence**
[had to remove < and > from the snippet above as they were cancelling the text]
The project fails to build and complains about:
Error	30	ICE82: This action MyExitDialog has duplicate sequence number -1 in the table InstallUISequence

The moment I change OnExit to something else (sequence or After/Before), it works fine. What I really want is OnExit to override the ExitDialog's behaviour.

I am using WiX 3.9 by the way.

Any help would be appreciated

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
