### ISSUE TITLE
VsixPackage cannot fix VS2015 VSIXInstaller.exe

### ISSUE THREAD

**Issue by KindDragon** [wixtoolset/issues#5409]
Hi,

I am trying install vsix extension for VS2015 using VsixPackage tag, but WiX trying to install an extension via VSIXInstaller.exe from VS2013 (I have VS2015 installed). It works If I specify the path to VS2015 VSIXInstaller.exe using `VsixInstallerPathProperty`.

**Comment by barnson** [comment]
Please provide more details: Which version of WiX? Attach logs showing the issue.

**Comment by KindDragon** [comment]
WiX v3.10.3 (Stable)

**Comment by barnson** [comment]
Please attach the whole log -- there are interesting bits around AppSearch too.

**Comment by KindDragon** [comment]
I've attached whole log already: https://github.com/wixtoolset/issues/files/490844/_log.txt

**Comment by barnson** [comment]
Sorry, I missed the link. It looks like you're building with WiX v3.8, which didn't support VS2015. Setup.wixproj is pointing to an unofficial WiX v3.8 NuGet package, so that's consistent. Please let me know if you run into any problems upgrading; I'm looking forward to v2.49. :)

**Comment by KindDragon** [comment]
Ahh, thank you. Forget that we use NuGet package. Sorry

> I'm looking forward to v2.49. :)

I hope  that it will soon  😃
