### ISSUE TITLE
HarvestFile / HeatFile documentation

### ISSUE THREAD

**Issue by cshorler** [wixtoolset/issues#5415]
Using WiX 3.10.2, VS2013

The description of using a PropertyGroup to influence heat behaviour has an invalid / incomplete example.
(I'm particularly interested in OutputFile mentioned on the HeatFile task)

No documentation or examples seem to exist on this topic.

Documentation bug?

**Comment by barnson** [comment]
OutputFile is listed in the HeatFile task parameter table. It can't be set with a property. It defaults to the HarvestFile item group file names.

**Comment by cshorler** [comment]
OK, so OutputFile is driven by Item metadata but can't be customised without writing or redefining the entire Target for HarvestFile? (it's not obvious how to override just OutputFile)

e.g. Given the following ItemGroup
  <ItemGroup>
    <HarvestFile Include="..\siplib\sip.lib">
      <ComponentGroupName>SipDev</ComponentGroupName>
      <DirectoryRefId>PYSTATICLIBDIR</DirectoryRefId>
    </HarvestFile>
    <HarvestFile Include="..\siplib\sip.h">
      <ComponentGroupName>SipDev</ComponentGroupName>
      <DirectoryRefId>PYINCLUDEDIR</DirectoryRefId>
    </HarvestFile>
  </ItemGroup>

ultimately ends with two _sip_file.wxs passed to Candle and an error:
candle.exe(0,0): error CNDL0351: Multiple source files ('obj\x64\Debug\_sip_file.wxs', 'obj\x64\Debug\_sip_file.wxs') have resulted in the same output file '....\libs\sip\msi\obj\x64\Debug\_sip_file.wixobj'.  This is likely because the source files only differ in extension or path.  Rename the source files to avoid this problem.

I do not want to rename either sip.lib or sip.h, I guess rename the source files is referring to the .wxs files passed to candle.exe?

I also tried redefining the Filename metadata
  <ItemGroup>
    <HarvestFile Include="..\siplib\sip.lib">
      <Filename>sip_lib</Filename>
      <ComponentGroupName>SipDev</ComponentGroupName>
      <DirectoryRefId>PYSTATICLIBDIR</DirectoryRefId>
    </HarvestFile>
    <HarvestFile Include="..\siplib\sip.h">
      <Filename>sip_h</Filename>
      <ComponentGroupName>SipDev</ComponentGroupName>
      <DirectoryRefId>PYINCLUDEDIR</DirectoryRefId>
    </HarvestFile>
  </ItemGroup>

This is not allowed:
....\libs\sip\msi\SIP.wixproj : error  : "Filename" is a reserved item metadata, and cannot be redefined as a custom metadata on the item.  

What is the recommended approach for file conflicts like this?

**Comment by barnson** [comment]
Sorry, no idea. For support, please contact the [wix-users mailing list][ml]. If you can come up with documentation for this scenario, that'd be great.

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by cshorler** [comment]
In fact I think I have a better solution, I'll improve the documentation.

It's probably better to create a staging directory using the MSBuild Copy task for each Feature and then use HarvestDirectory on this staging directory.

**Comment by barnson** [comment]
Yeah, staging directories solve a lot of harvesting problems.
