### ISSUE TITLE
MSI doesn't show custom banner and dialog image on Windows 7 Pro SP1.

### ISSUE THREAD

**Issue by yfnfif** [wixtoolset/issues#5419]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
v 3.10
> (WiX version in major.minor.release.build format)
3.10.2.2516
* Which version of Visual Studio are you building with (if any)?
Visual Studio Professional 2013
> (Visual Studio version, including year and update)
Visual Studio Professional 2013 Version 12.0.40629.00 Update 5
* Which version of .NET are you building with?
Microsoft .NET Framework Version 4.5.51641
> (.NET version)
4.5.51641
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 7 Professional Service Pack 1

* Describe the problem and the steps to reproduce it.
I'm setting a custom banner and dialog image for my WiX generated MSI.
    <WixVariable Id="WixUIBannerBmp" Value="images\dialog_bmp_ww.jpg" />
    <WixVariable Id="WixUIDialogBmp" Value="images\dialog_bmp.png" />
MSI doesn't show banner and dialog image on Windows 7 Pro SP1. When MSI is started on Windows 8.1 Pro banner and dialog image are shown.

**Comment by barnson** [comment]
WiX isn't involved in showing the UI; that's the Windows Installer engine. Recommend contacting the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
