### ISSUE TITLE
Burn should support dual purpose packages

### ISSUE THREAD

**Issue by rolix7** [wixtoolset/issues#5420]
* Describe the scenario and benefits that the feature supports.

> Since Windows Installer 5 it's possible to create dual purpose packages (msi) to deal with UAC. If you don't want the user to need admin rights for installation, but still have to support terminal server installations (where you install to `C:\Program Files\`), you are forced to use dual purpose packages. Here you can decide at runtime, if you rather wanna do a `perUser` or `perMachine` installation. It would be great, if Burn would support those packages. This would make a lot of things easier.

* Describe how you're accomplishing the feature today (if possible).

> I added a "dummy" `perUser` `MsiPackage` to the bundle, which forces the bundle to be `perUser` too. The problem here is, that the bundle is always "perUser". So if I select "perMachine"-installation in my custom burn UI, my `MsiPackage` gets installed `perMachine`, but the bundle still `perUser`. Another issue is that it seems, that my `perUser` bundle is always elevating! If I select installation type `perUser` it doesn't have to elevate, 'cause my `MsiPackage` gets installed `perUser` too! Maybe the property `ALLUSERS` set to 2 confuses burn. In my opinion, this isn't really a solution. I'm still at testing and worried, there are a lot more issues.

* Describe what you'd like the new feature to do.

> Burn should determine **at runtime**, which `InstallationScope` is needed for the bundle, rather than fixing that at compile time.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/4914
