### ISSUE TITLE
Strings are no longer formatted

### ISSUE THREAD

**Issue by 9Rune5** [wixtoolset/issues#5423]
* Which version of WiX are you building with?
> 3.11.0.906

* Which version of Visual Studio are you building with (if any)?
> VS 2015 (#3)

* Which version of .NET are you building with?
> 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> Windows 10

* Describe the problem and the steps to reproduce it.

Recently I've noticed that strings are not formatted.
From one of my installer logs:

> Action 17.00.54: InstallFiles. Copying new files File: [1],  Directory: [9],  Size: [6]

This is identical to what I observe in the installer GUI during installation.
<img width="252" alt="nonverboseprogress" src="https://cloud.githubusercontent.com/assets/9988080/19447778/525cdb18-949f-11e6-9444-dae2be3a5326.png">

I noticed similar strings when executing the latest wix311.exe installer itself. While installing it too prints progress messages, and AFAICT none of them replaced the [1] formatting tags with anything meaningful.
<img width="261" alt="wixinstaller" src="https://cloud.githubusercontent.com/assets/9988080/19447902/c3505408-949f-11e6-8c0a-45df4f2cfa85.png">

**Comment by barnson** [comment]
Works as expected for me on Windows 10 v1607/14393.321.

**Comment by 9Rune5** [comment]
I'm on Win10 Build 14931.1000. I just tried my secondary PC (running the same build) and I see the same behavior there (as in the wix installer screen shot I posted).

Something funky happening with the newer Win10 builds..?

**Comment by barnson** [comment]
That's my guess.
