### ISSUE TITLE
Incorrect message in disk usage dialog

### ISSUE THREAD

**Issue by algv** [wixtoolset/issues#5424]
OutOfDiskDlgText and DiskCostDlgText duplicate message "highlighted volumes do not have enough disk space available for the currently selected features. You can remove some files from the highlighted volumes, install fewer features, or select a different destination drive."

version 3.10.3.3007

**Comment by barnson** [comment]
That's by design. Both dialogs are essentially identical, showing disk consumption for different UI flows.
