### ISSUE TITLE
WIX cannot write value to registry if key contains space

### ISSUE THREAD

**Issue by Zaknafeyn** [wixtoolset/issues#5425]
* Which version of WiX are you building with - **3.10.3.3007**
* Which version of Visual Studio are you building with (if any)? **Visual Studio 2015 Community Edition Update 3 (14.0.25420.01)**
* Which version of .NET are you building with? - **4.5**
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on? - **Windows 10**
* Describe the problem and the steps to reproduce it.

I need to write a value to registry key which contains space. 
`HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION`
However it doesn't create a value in registry key if it contains a space. Once I change key to any other (without a space) it works fine - creates both key and value in registry.

Here is my code in WIX script:

```
<?define var.IEFeatureEmulationKey = "Software\Microsoft\Internet Explorer\FeatureControl\FEATURE_BROWSER_EMULATION" ?>
....
<Fragment>            
  <DirectoryRef Id="TARGETDIR">            
    <Component Id="registryValues" Guid="{some-guid}" >
      <RegistryKey Root="HKCU" Key="$(var.IEFeatureEmulationKey)" Action="create">
        <RegistryValue Name="MyApp.EXE" Value="11000" Type="integer" Action="write"/>
      </RegistryKey>
    </Component>
</Fragment>
```

This code work only if $(var.IEFeatureEmulationKey) contains no spaces. But I need to write a value to this specific key.

* Describe the behavior you expected and how it differed from the actual behavior.

Installer should create value in registry regardless of key path or should be provided mechanism to escape spaces in order to access such keys. If I need to write/read to predefined keys, it becomes impossible with current implementation.

**Comment by robmen** [comment]
We provide a template for filing bugs for a reason. Closing this issue since the useful information in the template was not provided.

**Comment by Zaknafeyn** [comment]
@robmen, please reopen. Issue updated according to guidelines

**Comment by robmen** [comment]
Thank you. Please provide a log file showing the registry key issue as well.

**Comment by Zaknafeyn** [comment]
Added log without sensitive info
[SomeProduct_For_Outlook_20161018140221_000_SomeProductSetup.log.txt](https://github.com/wixtoolset/issues/files/536879/SomeProduct_For_Outlook_20161018140221_000_SomeProductSetup.log.txt)

**Comment by robmen** [comment]
Log file shows the key is being created:

    MSI (s) (FC:48) [14:02:25:246]: Executing op: RegOpenKey(Root=-2147483647,Key=Software\Microsoft\Internet Explorer\FeatureControl\FEATURE_BROWSER_EMULATION,,BinaryType=0,,)
    MSI (s) (FC:48) [14:02:25:246]: Executing op: RegAddValue(Name=OUTLOOK.EXE,Value=#11000,)
    MSI (s) (FC:48) [14:02:25:247]: Executing op: RegAddValue(Name=SomeProduct For Outlook.dll,Value=#11000,)

For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
