### ISSUE TITLE
Path not correct in spawned processes/com objects

### ISSUE THREAD

**Issue by WendyLGNotTheFirst** [wixtoolset/issues#5426]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
make_msi_file:
  "C:\Program Files (x86)\WiX Toolset v3.9\bin\light.exe" -sice:ICE30 -ext WixUIExtension -ext WixUtilExtension "Coda XL.wixobj" -out "..\kits\XL\Coda XL"
  Windows Installer XML Toolset Linker version 3.9.1208.0
  Copyright (c) Outercurve Foundation. All rights reserved.

* Which version of Visual Studio are you building with (if any)?

S:\coda-xl\Office\Installers>msbuild -version
Microsoft (R) Build Engine version 4.6.1055.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

4.6.1055.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
 windows 8.1

* Describe the problem and the steps to reproduce it.
Inside the installer I install several .dll files and add their location onto the path environment variable.
inside my installer I run a vb .exe that uses the excel com object to register xla's inside excel.
Whenever this step gets run excel creates error dialogs complaining that it can't find the installed dll's.

> EXCEL.EXE - System Error The program can't start because my.dll is missing from your computer. Try reinstalling the program to fix this problem.

I have printed out the path environment variable inside the visual basic program and it does not include my addition.
After having this .exe as a deferred custom action i have moved it to run in the exit dialog in the "launch your application" step. Expecting everything to be setup and the transaction complete.

```
<UI>
      <UIRef Id="WixUI_Mondo" />
      <Publish Dialog="ExitDialog"
        Control="Finish"
        Event="DoAction"
        Value="LaunchXLAReg">WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed</Publish>
    </UI>
```
it still exhibits the same behaviour, of my new path extension not being inside the "path" environment variable .

If however i do not launch the .exe from within the installer, but launch it from my desktop (as the very next action) it works perfectly silently and without hitch.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code or help you understand the behavior of the Windows Installer better.

**Comment by WendyLGNotTheFirst** [comment]
I do not want support, my installer worked under windows 7, There is nothing I can do to make it work under windows 8.1. 
I want the paths to be fully comited or for the environment to be a full new one before launching the final application.
