### ISSUE TITLE
WiX burn uninstall before upgrade

### ISSUE THREAD

**Issue by Benikz** [wixtoolset/issues#5427]
Hello dear community,
I have found this while searching for a solution to one of my problems and it seems that the answer is 3 years old.
http://stackoverflow.com/questions/16598014/wix-burn-upgrade-needs-to-uninstall-both-msis-before-upgrading
Considering Mr. Mensching's answer, I wanted to know if this has been implemented. If not, I would submit this issue.

Greetings

**Comment by robmen** [comment]
We ask that you fill out a template to help us process the bugs that come in.
