### ISSUE TITLE
Wix 3.10.3 & Windows 10: Burn does not elevate on uninstall when run from Programs and Features

### ISSUE THREAD

**Issue by tsollas** [wixtoolset/issues#5429]
* Which version of WiX are you building with?
3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2015 Enterprise Update 3

* Which version of .NET are you building with?

.NET 4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 Pro Anniversary Edition (Version 1607, build 14393.351)

* Describe the problem and the steps to reproduce it.

I've created a burn bundle installer that installs a couple of MSI's, both perMachine. The bundle does elevate properly on install. If I run the bundle exe with the /uninstall command line, it elevates on uninstall (specifically, the Uninstall shows the UAC shield, and you are prompted to elevate when clicking Uninstall). If I uninstall from Windows 10's Apps & Features window, you are prompted to elevate immediately, however this is because Apps & Features seems to blindly elevate here regardless of your bundle settings (this is documented in another issue).

However, if I uninstall from Control Panel's "Programs and Features" dialog, the uninstall will not elevate (even though the logs seem to indicate that it does). The installer in question does need elevation to do some things (like stop a service cleanly for instance). Therefore, the MSI that does actually stop the service during uninstall does not stop the service before removing it.

* Describe the behavior you expected and how it differed from the actual behavior.

The burn bundle installer should elevate (e.g. you should see the shield on the uninstall button), and you should be prompted to elevate when clicking uninstall when the uninstaller is launched from Control Panel's Programs and Features dialog.

[uninstall_000_rGuestPayHandler.Msi.log.txt](https://github.com/wixtoolset/issues/files/562509/uninstall_000_rGuestPayHandler.Msi.log.txt)
[uninstall_001_rGuestPayAgent.Msi.log.txt](https://github.com/wixtoolset/issues/files/562510/uninstall_001_rGuestPayAgent.Msi.log.txt)
[uninstall.log.txt](https://github.com/wixtoolset/issues/files/562511/uninstall.log.txt)

**Comment by barnson** [comment]
ARP automatically elevates .exes; no UAC prompt is necessary.

    MSI (s) (78:B4) [14:27:37:888]: MSI_LUA: Credential prompt not required, user is an admin

**Comment by tsollas** [comment]
Thanks Bob, completely missed that. Ok, makes sense. I presumed that you'd get a UAC prompt like you do for MSI's.
