### ISSUE TITLE
WIXUI_EXITDIALOGOPTIONALCHECKBOX background color does not match

### ISSUE THREAD

**Issue by jnm2** [wixtoolset/issues#5430]
Version 3.10.3.3007, building from command line, .NET 4.6.2 (394802), Windows 10 x64 AU

If you use `WixUI_InstallDir` and specify a value for `WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT` the background of the checkbox area is a large COLOR_3DFACE rectangle instead of white like the page it's on.

It looks like a glitch. You would expect that the background of the checkbox would be seamless with the rest of the page.

![](http://i.imgur.com/q87pF2J.png)

**Comment by barnson** [comment]
Duplicate: #1687
