### ISSUE TITLE
Control requestedExecutionLevel 'in manifest of executable output

### ISSUE THREAD

**Issue by NN---** [wixtoolset/issues#5431]
Currently using WiX it is possible to make executable with the manifest requiring default execution level:

```xml
<processorArchitecture="x86" type="win32"/>
...		<security>
			<requestedPrivileges>
				<requestedExecutionLevel level="asInvoker" uiAccess="false"/>
			</requestedPrivileges>
		</security>
	...
```

In order to run your executable as administrator it is needed to make an additional runner which will ask for elevation and run the installation file.
We have a workaround by changing the manifest after WiX build to <requestedExecutionLevel level="requireAdministrator"> .

It would be nice if it was a configurable feature in WiX.

Thanks.

**Comment by robmen** [comment]
That goes against the design of Burn and the security boundaries put in place. We purposefully do not allow this and do not recommend hacking Burn's manifest.

**Comment by rseanhall** [comment]
Rob beat me to it, but this is also a duplicate of https://github.com/wixtoolset/issues/issues/4972.

**Comment by NN---** [comment]
@robmen I fully understand the security considerations but it is much nicer to have one executable you download and not zip with multiple files.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by NN---** [comment]
@robmen I know exactly why I need it.
I need to access some OS parts which require administrator prior running the installation process.
It is essential part of my installer by product requirements.

Currently I hack it with changing a manifest. but I prefer to do it in a standard way while staying with one executable.

Thanks.

**Comment by mzayarnyuk** [comment]
you must add it, for complex changes that need admin is must be added; is stupid to add own manifest for that or custom bootstraper app if default UI is fine ....

**Comment by mzayarnyuk** [comment]
good found elegant solution with wix3 (without res-hacks) - hope with v4 will work similar
