### ISSUE TITLE
visual studio 2017 RC support

### ISSUE THREAD

**Issue by rebeldevil** [wixtoolset/issues#5437]
I have just a question, How I can install Wix on Visual Studio 2017 RC?

**Comment by robmen** [comment]
Not yet.

For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

**Comment by heaths** [comment]
See issue #5433 tracking this. After discussions with the Visual Studio SDK team, I'm putting the final touches on the WiX Improvement Proposal and will be making the necessary changes thereafter (I own the VS15 query API, among other things).
