### ISSUE TITLE
Wix Documentation - Creating a Simple Setup

### ISSUE THREAD

**Issue by gojanpaolo** [wixtoolset/issues#5439]
I just started using WiX today and it seems the documentation needs to be updated.

[http://wixtoolset.org/documentation/manual/v3/votive/authoring_first_votive_project.html](http://wixtoolset.org/documentation/manual/v3/votive/authoring_first_votive_project.html)
Step 2 line 6 states the following:

> Find the comment that says:
> 
>  `<!-- TODO: Insert your files, registry keys, and other resources here. -->`
> Delete that line and replace it with the following lines of code:
> 
>  `<File Source="$(var.MyApplication.TargetPath)" />`

but this is incomplete since we also need to uncomment the following line:

```
<!-- <Component Id="ProductComponent"> -->
      
<!-- </Component> -->
```

so yeah, please update the documentation for other newbies like me :)

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/4612
