### ISSUE TITLE
Bug: Problem with multi language msi

### ISSUE THREAD

**Issue by xunios** [wixtoolset/issues#5440]
When making a multi language msi, the msi works correctly when trying to push it with a GPO. The GPO wizard detects that it's a multi language package and show the neutral language as language to install.

But, when I adjust the 'binary' table from that same msi with Microsoft.Deployment.WindowsInstaller.Database, the languages of the msi are not recognised correctly anymore in GPO wizard. The GPO wizard now shows only german, instead of neutral. But our entire environment is in en_UK, so I have no idea where the german detection comes from.
When I check the adjusted msi with orca, I see that all languages are gone from the summary information. And I suspect that the embedded language transformations are also altered compared to when it was build originaly from my wix setup project. 
So Microsoft.Deployment.WindowsInstaller.Database adjusts much more then what I want. In my code I just have this:

    public void UpdateProgramFile(string filePath)
    {
      using (var db = new Database(this.MsiFile, DatabaseOpenMode.Direct))
      {
        UpdateSetupFile(db, "Foo FileName", filePath);
      }
    }
	
     void UpdateSetupFile(Database db, string fileName, string filePath)
    {
      using (var view = db.OpenView("UPDATE `Binary` SET `Data` = ? WHERE `Name` = '{0}'", fileName))
      {
        using (var rec = new Record(1))
        {
          rec.SetStream(1, filePath);
          view.Execute(rec);
          db.Commit();
        }
      }
    }

But this also adjust summary info, and probably also the embedded streams in the msi, because GPO wizard shows then German as a language and not neutral when using the msi in GPO wizard.

Can I somehow tell Microsoft.Deployment.WindowsInstaller.Database not to adjust anything else except what I want?

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
