### ISSUE TITLE
Bootstrapper must reboot PC after installining MSU packages if at least one of them require rebooting.

### ISSUE THREAD

**Issue by sergey-yukhno** [wixtoolset/issues#5442]
WIX 3.10.3
VS 2015 Update 3

Bootstrapper must ask reboot PC just after installining MSU packages if at least one of them require rebooting. Some products in bootstrapper can't be installed without it.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
