### ISSUE TITLE
Unmodified WIX project files are automatically checked out on Save All

### ISSUE THREAD

**Issue by mediawolf** [wixtoolset/issues#5444]
VS 2015 Update 3
WIX Toolset 3.10.3.3007
Windows Driver Kit - Windows 10.0.26639

1) Open solution containing WIX projects under TFS source control
2) File -> Save All
WIX project files are checked out but contain no changes.

I've temporary removed "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Windows Driver Kit" folder, restarted VS and problem disappeared.

One of WDK VS extensions is looking for "PlatformToolset" in each project.
Votive extension doesn't known such property but for whatever reason it calls SetConfiguration() that somehow leads to a check-out of target project.

 	mscorlib.dll!System.IO.Path.CheckInvalidPathChars(string path, bool checkAdditional)	Unknown
 	mscorlib.dll!System.IO.Path.Combine(string path1 = "E:\\SomeProject", string path2 = "..\\..\\Intermediate\\SomeProject\\\\Release|x86\\Output\\")	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.Function<Microsoft.Build.Evaluation.ProjectProperty>.Execute(object objectInstance = null, Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties = {Microsoft.Build.Evaluation.Project.Data}, Microsoft.Build.Evaluation.ExpanderOptions options = ExpandProperties, Microsoft.Build.Shared.IElementLocation elementLocation = {Microsoft.Build.Construction.ElementLocation.SmallElementLocation})	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.PropertyExpander<Microsoft.Build.Evaluation.ProjectProperty>.ExpandPropertyBody(string propertyBody, object propertyValue, Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties, Microsoft.Build.Evaluation.ExpanderOptions options, Microsoft.Build.Shared.IElementLocation elementLocation, Microsoft.Build.Evaluation.UsedUninitializedProperties usedUninitializedProperties)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.PropertyExpander<Microsoft.Build.Evaluation.ProjectProperty>.ExpandPropertiesLeaveTypedAndEscaped(string expression = "$([System.IO.Path]::Combine(`$(MSBuildProjectDirectory)`, `$(OutDir)`))", Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties = {Microsoft.Build.Evaluation.Project.Data}, Microsoft.Build.Evaluation.ExpanderOptions options = ExpandProperties, Microsoft.Build.Shared.IElementLocation elementLocation = {Microsoft.Build.Construction.ElementLocation.SmallElementLocation}, Microsoft.Build.Evaluation.UsedUninitializedProperties usedUninitializedProperties = {Microsoft.Build.Evaluation.UsedUninitializedProperties})	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.Function<Microsoft.Build.Evaluation.ProjectProperty>.Execute(object objectInstance = null, Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties = {Microsoft.Build.Evaluation.Project.Data}, Microsoft.Build.Evaluation.ExpanderOptions options = ExpandProperties, Microsoft.Build.Shared.IElementLocation elementLocation = {Microsoft.Build.Construction.ElementLocation.SmallElementLocation})	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.PropertyExpander<Microsoft.Build.Evaluation.ProjectProperty>.ExpandPropertyBody(string propertyBody, object propertyValue, Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties, Microsoft.Build.Evaluation.ExpanderOptions options, Microsoft.Build.Shared.IElementLocation elementLocation, Microsoft.Build.Evaluation.UsedUninitializedProperties usedUninitializedProperties)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.PropertyExpander<Microsoft.Build.Evaluation.ProjectProperty>.ExpandPropertiesLeaveTypedAndEscaped(string expression = "$([System.IO.Path]::GetFullPath(`$([System.IO.Path]::Combine(`$(MSBuildProjectDirectory)`, `$(OutDir)`))`))", Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties = {Microsoft.Build.Evaluation.Project.Data}, Microsoft.Build.Evaluation.ExpanderOptions options = ExpandProperties, Microsoft.Build.Shared.IElementLocation elementLocation = {Microsoft.Build.Construction.ElementLocation.SmallElementLocation}, Microsoft.Build.Evaluation.UsedUninitializedProperties usedUninitializedProperties = {Microsoft.Build.Evaluation.UsedUninitializedProperties})	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.PropertyExpander<Microsoft.Build.Evaluation.ProjectProperty>.ExpandPropertiesLeaveEscaped(string expression, Microsoft.Build.Evaluation.IPropertyProvider<Microsoft.Build.Evaluation.ProjectProperty> properties, Microsoft.Build.Evaluation.ExpanderOptions options, Microsoft.Build.Shared.IElementLocation elementLocation, Microsoft.Build.Evaluation.UsedUninitializedProperties usedUninitializedProperties)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Expander<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem>.ExpandIntoStringLeaveEscaped(string expression, Microsoft.Build.Evaluation.ExpanderOptions options = ExpandProperties, Microsoft.Build.Shared.IElementLocation elementLocation = {Microsoft.Build.Construction.ElementLocation.SmallElementLocation})	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluatePropertyElement(Microsoft.Build.Construction.ProjectPropertyElement propertyElement = "TargetDir" Value="$([System.IO.Path]::GetFullPath(`$([System.IO.Path]::Combine(`$(MSBuildProjectDirectory)`, `$(OutDir)`))`))" Condition="'$(OutDir)' != ''")	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluatePropertyGroupElement(Microsoft.Build.Construction.ProjectPropertyGroupElement propertyGroupElement)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport = "C:\\Program Files (x86)\\MSBuild\\Microsoft\\WiX\\v3.x\\wix2010.targets" #Children=189 DefaultTargets="Build" ToolsVersion="" InitialTargets="_CheckForInvalidConfigurationAndPlatform;\r\n                  _CheckRequiredProperties" ExplicitlyLoaded=true)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateImportElement(string directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement = Project="$(WixVersionTargetsPath)" Condition="")	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport = "C:\\Program Files (x86)\\MSBuild\\Microsoft\\WiX\\v3.x\\Wix.targets" #Children=2 DefaultTargets="" ToolsVersion="" InitialTargets="" ExplicitlyLoaded=true)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.EvaluateImportElement(string directoryOfImportingFile, Microsoft.Build.Construction.ProjectImportElement importElement = Project="$(WixTargetsPath)" Condition="")	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.PerformDepthFirstPass(Microsoft.Build.Construction.ProjectRootElement currentProjectOrImport = "E:\\SomeProject\\SomeProject.wixproj" #Children=11 DefaultTargets="Build" ToolsVersion="12.0" InitialTargets="" ExplicitlyLoaded=true)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.Evaluate()	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Evaluator<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition>.Evaluate(Microsoft.Build.Evaluation.IEvaluatorData<Microsoft.Build.Evaluation.ProjectProperty, Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectMetadata, Microsoft.Build.Evaluation.ProjectItemDefinition> data, Microsoft.Build.Construction.ProjectRootElement root, Microsoft.Build.Evaluation.ProjectLoadSettings loadSettings, int maxNodeCount, Microsoft.Build.Collections.PropertyDictionary<Microsoft.Build.Execution.ProjectPropertyInstance> environmentProperties, Microsoft.Build.BackEnd.Logging.ILoggingService loggingService, Microsoft.Build.Evaluation.IItemFactory<Microsoft.Build.Evaluation.ProjectItem, Microsoft.Build.Evaluation.ProjectItem> itemFactory, Microsoft.Build.Evaluation.IToolsetProvider toolsetProvider, Microsoft.Build.Evaluation.ProjectRootElementCache projectRootElementCache, Microsoft.Build.Framework.BuildEventContext buildEventContext, Microsoft.Build.Execution.ProjectInstance projectInstanceIfAnyForDebuggerOnly)	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation = {Microsoft.Build.BackEnd.Logging.LoggingService})	Unknown
 	Microsoft.Build.dll!Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(Microsoft.Build.BackEnd.Logging.ILoggingService loggingServiceForEvaluation = {Microsoft.Build.BackEnd.Logging.LoggingService})	Unknown
	votive2010.dll!Microsoft.VisualStudio.Package.ProjectNode.SetConfiguration(Microsoft.VisualStudio.Package.ConfigCanonicalName configCanonicalName) Line 3876	C#
 	**votive2010.dll**!Microsoft.Tools.WindowsInstallerXml.VisualStudio.WixProjectNode.**SetConfiguration**(Microsoft.VisualStudio.Package.ConfigCanonicalName configCanonicalName) Line 570	C#
 	votive2010.dll!Microsoft.VisualStudio.Package.ProjectConfig.GetMsBuildProperty(string propertyName = "PlatformToolset", bool resetCache) Line 827	C#
 	votive2010.dll!Microsoft.VisualStudio.Package.ProjectConfig.GetConfigurationProperty(string propertyName, bool resetCache) Line 418	C#
 	**votive2010.dll**!Microsoft.VisualStudio.Package.ProjectNode.Microsoft.VisualStudio.Shell.Interop.IVsBuildPropertyStorage.**GetPropertyValue**(string propertyName, string configName, uint storage, out string propertyValue = null) Line 6346	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	**DriverCommonPackage.dll**!Microsoft.DriverKit.DriverCommonPackage.**GetProjectProperty**(EnvDTE.Project project, string propertyName = **"PlatformToolset"**, Microsoft.VisualStudio.Shell.Interop.IVsHierarchy projectNode)	Unknown
 	DriverCommonPackage.dll!Microsoft.DriverKit.DriverCommonPackage.IsDriverProject(EnvDTE.Project proj)	Unknown
 	DriverCommonPackage.dll!Microsoft.DriverKit.DriverCommonPackage.IsDriverProjectLoaded()	Unknown
 	DriverTestPackage.dll!Microsoft.DriverKit.WdkTestPackage.Utilities.DriverDeployer.Exec(ref System.Guid pguidCmdGroup = {System.Guid}, uint nCmdId = 224, uint nCmdexecopt = 0, System.IntPtr pvaIn = {System.IntPtr}, System.IntPtr pvaOut = {System.IntPtr})	Unknown
 	DriverTestPackage.dll!Microsoft.DriverKit.WdkTestPackage.DriverTestPackage.Exec(ref System.Guid pguidCmdGroup, uint nCmdId, uint nCmdexecopt, System.IntPtr pvaIn, System.IntPtr pvaOut)	Unknown

**Comment by rseanhall** [comment]
Might be related to #4195.

**Comment by ddv239** [comment]
I debugged this code and found the real root cause for this bug. I developed a code change ready to contribute as soon as I figure out how to get permission to contribute it.

**Comment by ddv239** [comment]
I think I figured out how to fork and create a pull request, here is the fix: https://github.com/wixtoolset/wix3/pull/392
