### ISSUE TITLE
Wix C++ custom action project template in VS2015: include and lib paths

### ISSUE THREAD

**Issue by Const-me** [wixtoolset/issues#5445]
I’m using visual studio 2015 and WiX Toolset v3.10.

A newly-created C++ custom action project doesn’t link:

`1>wcautil.lib(wcalog.obj) : error LNK2019: unresolved external symbol __vsnprintf referenced in function "long __stdcall StringVPrintfWorkerA(char *,unsigned int,unsigned int *,char const *,char *)" (?StringVPrintfWorkerA@@YGJPADIPAIPBD0@Z)`

The reason for that —  under C++/General/Additional Include Directories and Linker/General/Additional Library Directories, the project says `$(WIX)sdk\VS2012\inc;%(AdditionalIncludeDirectories)` and `$(WIX)sdk\VS2012\lib\x86;%(AdditionalLibraryDirectories)`, respectively.

Easy to fix, just change `VS2012` to `VS2015`, however the template should already include the correct values.

**Comment by rseanhall** [comment]
This was fixed in v3.11 - https://github.com/wixtoolset/wix3/pull/312.  There are no plans for another v3.10 release.
