### ISSUE TITLE
XmlConfig crash

### ISSUE THREAD

**Issue by Jertix** [wixtoolset/issues#5447]
Hi, I am trying to delete an item from the web.config, but every time I use XmlConfig compilation crashes. XmlFile works well, but XmlConfig goes always crash.

I'm Windows 7 Professional 64bit.
WiX Toolset Linker version 4.0.4305.0

This is in my .wxs file:
```
		<Feature Id="Complete" Title="$(var.RootFeatureTitle)" Description="$(var.RootFeatureTitle_Description)" Level="1" Display="expand"
             ConfigurableDirectory="INSTALLLOCATION">
			 
			<Feature Id="MainContent"
					 Title="$(var.MainFeatureTitle)"
					 Description="$(var.MainFeatureTitle_Description)"
					 Level="1">
				
				<ComponentRef Id="WebConfigDelAssemblies" />					
			</Feature>
		</Feature>
```

....
```
			<Component Id="WebConfigDelAssemblies">	 	

			    <CreateFolder/>
			
                 <!-- XmlConfig always crash  -->
                 <util:XmlConfig
                    Id="DelAssembly"
                    File="[MYWEBWEBSITE]Web.Config" 
                    Action="delete"
                    Node="element"
                    VerifyPath="add[\[]@assembly='DevExpress.XtraCharts.v11.2.Web, Version=11.2.11.0, Culture=neutral, PublicKeyToken=B88D1754D700E49A'[\]]"
                    ElementPath="//configuration/system.web/compilation/assemblies"
                    On="install"
                    Sequence="1" />				

			</Component>
```

this is the error:
**candle.exe : error CNDL0001 : object reference not set to an instance of an object.**

Exception Type: System.NullReferenceException

Stack Trace:
   in WixToolset.Extensions.UtilCompiler.ParseXmlConfigElement(XElement node, String componentId, Boolean nested)
   in WixToolset.Extensions.UtilCompiler.ParsePossibleKeyPathElement(XElement parentElement, XElement element, IDictionary`2 context)
   in WixToolset.CompilerCore.ParsePossibleKeyPathExtensionElement(XElement parentElement, XElement element, IDictionary`2 context)
   in WixToolset.Compiler.ParseComponentElement(XElement node, ComplexReferenceParentType parentType, String parentId, String parentLanguage, Int32 diskId, String directoryId, String srcPath)
   in WixToolset.Compiler.ParseDirectoryRefElement(XElement node)
   in WixToolset.Compiler.ParseProductElement(XElement node)
   in WixToolset.Compiler.ParseWixElement(XElement node)
   in WixToolset.Compiler.Compile(XDocument source)
   in WixToolset.Tools.Candle.Run()
   in WixToolset.Tools.Candle.Execute(String[] args)

**Comment by Jertix** [comment]
If I try to install the latest "stable" version (3.10.3)
do you think that version have the same bug?
(my intent is to eliminate all duplicates assembly in web.config)

**Comment by barnson** [comment]
It might just be a bug in WiX v4.

**Comment by robmen** [comment]
99.99999999% likely hood this is "just a bug in WiX v4".
