### ISSUE TITLE
Unable to add new line in Wxl string

### ISSUE THREAD

**Issue by RajeshBalakrishnan** [wixtoolset/issues#5448]
Greetings,

I am using WiX v3.7. I am not able to add new line character between strings in Wix Localization (.wxl) string tag as below.

  <String Id ="PackageName">ABC Product &#xD;&#xA;&#x9; Version</String>

Is there any other option to include the new line character in Package Name string in .wxl file.

Could you please help me to resolve the same.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
