### ISSUE TITLE
XmlFile Uninstall Behavior

### ISSUE THREAD

**Issue by mjwitte32** [wixtoolset/issues#5450]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> VS 2015, Update 3

* Which version of .NET are you building with?

> 4.6.01055

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7

* Describe the problem and the steps to reproduce it.

> I have a stand-alone product that's installed initially. Some of the behavior of this product is data-driven by XML parameters. There is a separate MSI used to change the behavior of this product to more align with a specific task. The only real content of the MSI is a collection of util:XmlFile elements that adjusts some of the XML parameters in these data files. All of the util:XmlFile elements have the Permanent attribute set to "no" so that these changes will be undone on uninstall.

* Describe the behavior you expected and how it differed from the actual behavior.

> Install behavior is flawless. util:XmlFile changes all the parameters and attributes as it is supposed to. It's on the uninstall that things go awry, though. The main issue is that resetting doesn't work as expected. With attributes, instead of resetting the value of the attribute to what it was previously, it deletes the attribute entirely. When resetting the value of an element, it removes the value instead of replacing it with the previous one. But it seems this only happens for some elements. Only half of the elements' values I adjust on install get removed. The other half remain. There's no difference in how I've defined my util:XmlFile elements, so they should be doing the same thing, right?
>
> This wouldn't be the worst thing in the world if I could define a util:XmlFile to run during uninstall and manually undo my changes to these XML files, but that doesn't seem to be possible. As such, I'm forced to create my own custom action that does essentially the same thing as util:XmlFile but can be run at other times of the install sequence. Maybe this is actually a feature request, but if util:XmlFile could actually _reset_ those values, that would be perfect.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml]. You might also check out `XmlConfig`.

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by mjwitte32** [comment]
This isn't for support. It's not operating the way it should be. I can't use XmlConfig because I need to modify, not just create or delete.

**Comment by barnson** [comment]
`XmlConfig` can do everything `XmlFile` can do. Just omit `Action`.

There isn't enough data or details to diagnose a bug. For example: the authoring in question, verbose logs, results.

**Comment by robmen** [comment]
Also, `XmlFile` cannot do everything `XmlConfig` can do. In particular, `XmlFile` was designed to poke values into a file that gets installed/uninstalled by the product. `XmlFile` does not have the intelligence to do smart things during repair or uninstall. That's why `XmlConfig` exists and why `XmlConfig` is more complex to use... it does more.

**Comment by mjwitte32** [comment]
Y'all are right. `XmlConfig` did the job. That being said, I wouldn't advertise the `Permanent` attribute of `XmlFile` as being reliable on uninstall. Like I said, I saw several different outcomes. It removed the attribute it modified wholesale and then only removed _some_ of the values for elements it modified.
