### ISSUE TITLE
Create installer to VERSION SPECIFIC installdir directory. (installing multiple versions)

### ISSUE THREAD

**Issue by frankbarbarino** [wixtoolset/issues#5454]
using 3.10.2.

I'd like to be able to create (and install) multiple versions and specify static install directory for each version.  note:   I'm only expecting each MSI to install a single version... but if the ProductVersion differs, the installation directory will be different.   I am able to specify and installdir by passing MSI a template.    But when the WXS gets created from the template, the component section doesn't use the RegistryKey from the template and the "LastInstallDir" path does not include the version number.   I'm not sure if this will be the only problem encountered or just the first.   Is there a way to specify this type of installation?

Template file:
```
<Property Id="INSTALLDIR" Secure="yes" Value="C:\Program Files\MyCompany\MyProductSuite\my-product\1.0.1\">
	<RegistrySearch Id="SearchInstallDir" Key="Software\MyCompany\my-product\1.0.1\LastInstallDir" Root="HKLM" Type="directory"/>
</Property>
<Property Id="TARGETDIR" Secure="yes" Value="C:\Program Files\MyCompany\MyProductSuite\my-product\1.0.1\"/>
``

WXS file:
<Compoennt>
        <RegistryKey ForceDeleteOnUninstall="yes" Id="install_path_reg" Key="Software\Cerner\hi-ui\LastInstallDir" Root="HKLM">
...
</Component>

**Comment by rseanhall** [comment]
Please ask your question on the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/).

The WiX Toolset has been around for a long time, so we use this issue tracker differently than most other projects. For questions like this, you are going to get much better answers faster on the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/) because that's where people have been asking questions since 2004. While discussing your question, we may discover a specific bug or feature to be tracked here but usually someone can help solve your issue.

**Comment by frankbarbarino** [comment]
But the issue is not wix - it is the plugin isn't flexible enough
(understandable because wix is a nightmare)

I've tested my hypothesis to change the registrykey under the component and
fixing that entry does what I want.    but that is not possible using the
plugin.    There is no way using the plugin to interject a doFirst or
doLast into the msi task after candle / before light.   the MSI task
appears as one large task.   Can it be broken up to allow more
customizations?

(if I can put my own task between candle and light, I could edit the wixobj
file to my liking using xml editing).

**Comment by rseanhall** [comment]
Sorry to sound like a robot, but please ask your question on the wix-users mailing list. I have no idea what plugin you're talking about, so make sure to include information about that when you ask your question there.

**Comment by barnson** [comment]
That's just what a robot would say...

**Comment by rseanhall** [comment]
There is no response configured for that comment.
