### ISSUE TITLE
Project outputs from .wixproj are not available to other projects

### ISSUE THREAD

**Issue by heaths** [wixtoolset/issues#5455]
* Which version of WiX are you building with?

> 3.10.3

* Which version of Visual Studio are you building with (if any)?

> 2015

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A (though, Windows 10)

* Describe the problem and the steps to reproduce it.

> Some projects reference output from other projects, but .wixproj targets do not implement `BuiltProjectOutputGroupDependencies` or `DebugSymbolsProjectOutputGroupDependencies` so outputs are not discoverable and project output references fail.

* Describe the behavior you expected and how it differed from the actual behavior.

> The WiX targets should implement `BuiltProjectOutputGroupDependencies` - which emits `BuiltProjectOutputGroupDependency` items - and `DebugSymbolsProjectOutputGroupDependencies` - which emits `DebugSymbolsProjectOutputGroupDependency` items. See Microsoft.Common.CurrentVersion.targets for an example.

**Comment by heaths** [comment]
Note that this is not the same as #4940, which asks that _heat.exe_ call into these targets for other projects.

**Comment by robmen** [comment]
I believe this is fixed in WiX v4.0 with the standardization on Microsoft.Common.targets.

**Comment by robmen** [comment]
This is fixed in WiX v4.0 with the standardization on Microsoft.Common.targets.
