### ISSUE TITLE
Cannot find local payload for .NET 4.6.1

### ISSUE THREAD

**Issue by vvitkovsky** [wixtoolset/issues#5458]
Hello, 

I am trying to add .NET 4.6.1 as internal payload as described here;
http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html

My installer has .NET offline installer inside (size was grown) but during installation burn cannot find .NET payload, it tries to find it using Internet or using local path "redist\NDP461-KB3102436-x86-x64-AllOS-ENU.exe". If I set Compressed="yes" nothing changed.

My bootstrapper example:

<Bundle Name="SetupBoostrapper" Version="1.2.0.1" Manufacturer="VicRaven" UpgradeCode="{494EF8E6-9725-47CC-B690-CFAF762A485F}">

    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkLicense">
      <bal:WixStandardBootstrapperApplication LicenseUrl="" SuppressOptionsUI="yes" />
    </BootstrapperApplicationRef>
   
    <Chain DisableSystemRestore="yes">

      <PackageGroupRef Id="NetFx461Redist"/>      
     
      <MsiPackage Id="SetupProject" SourceFile="$(var.SetupProject.TargetPath)" DisplayInternalUI="yes" Vital="yes" Compressed="yes" InstallCondition="Sql2014Instance64 OR Sql2014Instance">
      </MsiPackage>
        
    </Chain>

    <PayloadGroup Id="NetFx461RedistPayload">
      <Payload Name="redist\NDP461-KB3102436-x86-x64-AllOS-ENU.exe" SourceFile="E:\NDP461-KB3102436-x86-x64-AllOS-ENU.exe" />
    </PayloadGroup>
     
  </Bundle>

Used WiX version: v3.11.0.906 Release
Visual Studio: 2012 update 5
OS Windows 10 Pro x64

Burn log file attached:
[SetupBoostrapper_20161219155741.txt](https://github.com/wixtoolset/issues/files/661101/SetupBoostrapper_20161219155741.txt)

Best regards, 
Victor

**Comment by vvitkovsky** [comment]
by the way, .NET 4.5.2 with the same code works fine (local installer can be found successfully)

**Comment by barnson** [comment]
Doc bug: https://github.com/wixtoolset/issues/issues/5310

**Comment by vvitkovsky** [comment]
Hello, 

I think this is not documentation issue - I use NetFx461Redist and NetFx461RedistPayload, not NetFx461Web. It is functionality issue, not documentation, because if I change all to NetFx452Redist and NetFx452RedistPayload (and use .NET 4.5.2 installer, of course) - all works ok.

So, this issue is related to .NET 4.6.1 (and 4.6.2) installation only.

**Comment by p370** [comment]
I have the same issue when trying to bundle.NET 4.6.1 installer with my setup. From the log it looks like installation checks for the NDP461-KB3102436-x86-x64-AllOS-ENU.exe file in wrong directory - it's trying to locate it in redist directory next to the installer executable and not in the temporary folder (C:\Users\_CurrentUser\_AppData\Local\Temp\{somerandomguid})  where the installation files from bootstrapper are unpacked.
I managed to solve this by using something similar to what is proposed here [http://stackoverflow.com/a/35186969](http://stackoverflow.com/a/35186969) and it worked. Could the problem be that I'm using a custom managed bootstrapper?

**Comment by 24mu13** [comment]
same for me: does not work with .NET version 4.6.x

**Comment by Adiel-Sharabi** [comment]
1+

**Comment by jonasjuffinger** [comment]
+1

**Comment by ssombat** [comment]
1+

**Comment by ginobolliger** [comment]
Hi all
I had the similar problem. We finally resolved it with an addition inside <Bootstrapper..></..>:

`...
<BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkLicense">
      <bal:WixStandardBootstrapperApplication LicenseUrl=""
                                              ShowVersion="yes"
                                              SuppressOptionsUI="yes"/>
      **<PayloadGroupRef Id="NetFx461RedistPayload"/>**
    </BootstrapperApplicationRef>
...`

Definitely something, the documentation does not mention that it's needed.

Kind regards
Gino

**Comment by dkuzakov** [comment]
> Hi all I had the similar problem. We finally resolved it with an addition inside <Bootstrapper..> **<PayloadGroupRef Id="NetFx461RedistPayload"/>** </..>:
> 
> Like this: `... <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.HyperlinkLicense"> <bal:WixStandardBootstrapperApplication LicenseUrl="" ShowVersion="yes" SuppressOptionsUI="yes"/> <PayloadGroupRef Id="NetFx461RedistPayload"/> </BootstrapperApplicationRef> ...`
> 
> Definitely something, the documentation does not mention that it's needed (maybe applies to other versions too).
> 
> Kind regards Gino

Can you please provide full example of solution? I am currently stuck with same issue for .NET 4.8
