### ISSUE TITLE
Wix in installer is not invoking the bootstarpper

### ISSUE THREAD

**Issue by anithraj** [wixtoolset/issues#5459]
Hello Team,

**Problem Definition :**  

I have set prerequisites ( Third party software's viz, SQL Server 2008 R2 and .Net Framework 4.0) to install before the actual application installation.

I have created bootstrapper project to check for registry and install the third party applications. and along with i have created wix setup project to create the Start Menu, program file icon and install actual (my own) application.

Bootstrapper is using its own set of dialogs which are not useful to me. In Wix installer has set of predefined dialogs, in that m using **WixUI_InstallDir** .

Now the problem is i want install the prerequisites and install my application using wix setup project.
Please do let me know the how do i call the bootstrapper (.exe) file in Wix setup .Msi.

So that using single setup (.Msi) i can install the third party and my application at one shot.

Thanks in advance.

Best regards
Anith

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
