### ISSUE TITLE
Downloads are blocked by Chrome (55.0.2883.87) 

### ISSUE THREAD

**Issue by m0nzderr** [wixtoolset/issues#5460]
Since the latest Chrome update (55.0.2883.87), I'm unable to download wix310.exe from 
https://wix.codeplex.com/releases/view/624906

The download is blocked with the malicious content warning.  
The issue is similar to #5404 and possibly has the same roots as http://stackoverflow.com/questions/33571975/how-to-prevent-google-chrome-from-blocking-my-installer-package

**Comment by rseanhall** [comment]
Chrome 55 is blocking it as malicious for me, too.  We'll probably have to submit a request for review to Google.

**Comment by robmen** [comment]
Unfortunately, it appears that all of codeplex.org has been flagged (i.e. it's not just our project that is flagged this way). So the team running codeplex.org needs to follow up with Google. :frowning_face:

**Comment by m0nzderr** [comment]
Thanks for a feedback! It's a almost a good news: putting the dist somewhere else remedies the problem (as a temporary workaround, of course).  Just tested the download itself and it works well. No need to fix anything. Not a big deal (for me, at least).

**Comment by face** [comment]
Thanks, missed this issue as the default query is open issues.

Would it be possible to get a sha256 checksum or some other checksum of the original wix310.exe before it was uploaded to codeplex.org so I can verify codeplex.org has not been compromised and your release is clean?

Thanks again

**Comment by robmen** [comment]
The file is signed (.NET Foundation subject).

**Comment by face** [comment]
ok, thanks.   sorry for being a windows newb...but while it passes, how do I know the .NET certificate is yours and not some other developers?  

C:\proj>"c:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" Verify /pa /v  wix310.exe

Verifying: wix310.exe
Signature Index: 0 (Primary Signature)
Hash of file (sha1): C65081AA24307C07AC463B88D773E4179D401C25

Signing Certificate Chain:
    Issued to: DigiCert Assured ID Root CA
    Issued by: DigiCert Assured ID Root CA
    Expires:   Sun Nov 09 16:00:00 2031
    SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43

        Issued to: DigiCert SHA2 Assured ID Code Signing CA
        Issued by: DigiCert Assured ID Root CA
        Expires:   Sun Oct 22 04:00:00 2028
        SHA1 hash: 92C1588E85AF2201CE7915E8538B492F605B80C6

            Issued to: .NET Foundation
            Issued by: DigiCert SHA2 Assured ID Code Signing CA
            Expires:   Fri May 04 04:00:00 2018
            SHA1 hash: 0DBDAA96E673B9DB9FF6C8B99D0AECB6FB268409

The signature is timestamped: Tue Jun 07 09:12:49 2016
Timestamp Verified by:
    Issued to: DigiCert Assured ID Root CA
    Issued by: DigiCert Assured ID Root CA
    Expires:   Sun Nov 09 16:00:00 2031
    SHA1 hash: 0563B8630D62D75ABBC8AB1E4BDFB5A899B24D43

        Issued to: DigiCert Assured ID CA-1
        Issued by: DigiCert Assured ID Root CA
        Expires:   Tue Nov 09 16:00:00 2021
        SHA1 hash: 19A09B5A36F4DD99727DF783C17A51231A56C117

            Issued to: DigiCert Timestamp Responder
            Issued by: DigiCert Assured ID CA-1
            Expires:   Mon Oct 21 16:00:00 2024
            SHA1 hash: 614D271D9102E30169822487FDE5DE00A352B01D


Successfully verified: wix310.exe

Number of files successfully Verified: 1
Number of warnings: 0
Number of errors: 0

**Comment by face** [comment]
oh, I guess you are .Net Foundation,  never mind...i'm good.

**Comment by robmen** [comment]
The subject identifier is: `Issued to: .NET Foundation`. The WiX Toolset is a member of the [.NET Foundation](https://dotnetfoundation.org/) (you can see our logo on their front page).
