### ISSUE TITLE
Issue with Burn loose file using wild card

### ISSUE THREAD

**Issue by varun7447** [wixtoolset/issues#5462]
* Which version of WiX are you building with?
WIX 3.10.2

> (WiX version in major.minor.release.build format)
WIX v3.10.2.2516

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of .NET are you building with?

> (.NET version) .Net 4.6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
Windows 2012 R2
* Describe the problem and the steps to reproduce it.
MSI file is able to copy the files from SOURCEDIR when executed independently. When the same MSI bundled with other pre-requisites the files in the SOURCEDIR are not executed. 

```
<Component Id="LicenseFile" Guid="">
            <CopyFile Id="Copy" Delete="no" DestinationDirectory="INSTALLFOLDER" SourceName="*.lic" SourceProperty="SOURCEDIR" />
          </Component>
```
Burn is not executing the CopyElement as the files reside in the SOURCEDIR but burn is executing the entire installation from cache location. Even after changing the BURN cache location to the source directory the files are not picked up. We cannot put all the files in the payload since we are no0t sure what .*lic files will be in the location. We cannot build the installer per user.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by varun7447** [comment]
I have opened various threads regarding this and no luck. 

As i mentioned above the CopyElement is working fine while executing the MSI. Same MSI when bundled into an exe with .netframework, CopyElement is not working. The reason i guess is burn caching all the packages inside the exe to a TEMP location. There are some loose files that are in the same directory as exe and these files need to be installed to INSTALLDIR. I cannot use them as payload elements as the files that need to install might change based on the user. Is there a way i can execute the exe from the same location instead of temp location? That way my loose files(*.lic) can be copied after the installation by MSI CopyElement from the SourceDir?? The *.lic here is some users might use ABC.lic so when we give the installer with ABC.lic the user will see only ABC.lic. Second user might need DEF.lic and the same installer we going to place the DEF.lic along with exe so that it get's installed to INSTALLDIR
