### ISSUE TITLE
More support for VS2017

### ISSUE THREAD

**Issue by r4tz52** [wixtoolset/issues#5463]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> WiX.3.11.0.906-pre

* Which version of Visual Studio are you building with (if any)?

> no matter

* Which version of .NET are you building with?

> no matter

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> no matter

* Describe the problem and the steps to reproduce it.

> VS15_ITEMTEMPLATES_DIR and some similar properties not working. This properties tries to get right path from HKLM\SOFTWARE\Microsoft\VisualStudio\15.0\Setup, but Visual Studio 2017 doesn't store this information in registry due to new "side-by-side installations" feature.
More info here: http://stackoverflow.com/questions/41106407/programmatically-finding-the-vs2017-installation-directory
https://blogs.msdn.microsoft.com/heaths/2016/09/15/changes-to-visual-studio-15-setup/

* Describe the behavior you expected and how it differed from the actual behavior.

> VS15_ITEMTEMPLATES_DIR should represent VS15.0 ItemTemplates directory path.

**Comment by robmen** [comment]
I expect this to be covered by #5433.

**Comment by barnson** [comment]
See the WIP as well: http://wixtoolset.org/development/wips/5433-add-support-to-detect-and-install-vsix-packages-into-vs15/

Let's have a single tracking issue for Dev15.
