### ISSUE TITLE
Visual Studio 2015 "Additional Include Directories" has invalid partial path

### ISSUE THREAD

**Issue by Simon-IT** [wixtoolset/issues#5471]
Hi guys,
 as showed in the attached image

![git1](https://cloud.githubusercontent.com/assets/24890180/21686208/dcd9787e-d364-11e6-8430-6be019373567.png)

when you create a **C++ custom action project**, an invalid partial path is used: **it's 2012 instead 2015**.

Wix version: 3.10.3
Visual Studio 2015 Community Edition Version 14.0.25431.01 Update 3

Thank you.
Regards,

Simone

**Comment by barnson** [comment]
Fixed in WiX v3.11: https://github.com/wixtoolset/wix3/commit/9de4163b03514c87a4a588d9397f215526b1481a
