### ISSUE TITLE
ICE Fails with error 217 for unprivileged accounts

### ISSUE THREAD

**Issue by mortenn** [wixtoolset/issues#5473]
* Which version of WiX are you building with?

3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

Running build on TeamCity server

* Which version of .NET are you building with?

4.6.2

* Describe the problem and the steps to reproduce it.

When running the build as an unprivileged account, the build fails with errors like this;

    [Light] light.exe error LGHT0217: Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".

Adding the service account to the local administrators group on the server fixes the problem, but this does seem like a good idea.

**Comment by rseanhall** [comment]
ICE validation code comes from Microsoft, and [it doesn't work unless you're an interactive user or a local administrator](https://sourceforge.net/p/wix/mailman/message/24361610/).

**Comment by grochoge** [comment]
Theoretically one should be able to set the service permissions to allow Authenticated Users to start the service as well, but attempting to change those seems to give access denied even as admin :-(

sc sdset msiserver "D:(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCLCSWRPWPDTLOCRRC;;;BA)(A;;CCLCSWRPLOCRRC;;;IU)**(A;;CCLCSWRPLOCRRC;;;AU)**(A;;CCLCSWRPLOCRRC;;;SU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)"
