### ISSUE TITLE
Install Certificate in Windows 7 with UAC Enabled

### ISSUE THREAD

**Issue by roend83** [wixtoolset/issues#5478]
* Which version of WiX are you building with?

> 3.10.3

* Which version of Visual Studio are you building with (if any)?

> VS2015 Update 3

* Which version of .NET are you building with?

> .NET 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7

* Describe the problem and the steps to reproduce it.

> PFX certificates cause the install to fail in Windows 7 when UAC is enabled.  The relevant error from the log is:

InstallCertificates:  Error 0x80090010: Failed to open PFX file.
InstallCertificates:  Error 0x80090010: Failed to get SHA1 hash of certificate.
InstallCertificates:  Error 0x80090010: Failed to resolve certificate: LocalhostPersonalCertificate
CustomAction InstallCertificates returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

The relevant configuration is:

`<Binary Id="LocalhostPfx" SourceFile="localhost.pfx" />
...
<iis:Certificate Id="LocalhostPersonalCertificate" BinaryKey="LocalhostPfx" Name="localhost" StoreLocation="localMachine" StoreName="personal" Overwrite="yes" PFXPassword="*****" Request="no" />`

When UAC is disabled, the installer works as expected.  This also works in Windows 10 regardless of whether or not UAC is enabled.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect the installer to succeed and the certificate to be installed.  Instead the installer fails and all changes are rolled back.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
