### ISSUE TITLE
Burn detects per-machine packages as per-user, when run as LocalSystem

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5479]
If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3

* Which version of Visual Studio are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> n/a

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Witnessed on Windows 10

* Describe the problem and the steps to reproduce it.

> When running as LocalSystem, calling `MsiGetProductInfoEx` with `MSIINSTALLCONTEXT_USERUNMANAGED` returns `ERROR_SUCCESS` for products that are installed per-machine. Likely, this is caused by MSI assigning per-machine products to LocalSystem. Burn decides that a successful call to `MsiGetProductInfoEx` with `MSIINSTALLCONTEXT_USERUNMANAGED` means that the package is per-user. Burn doesn't use that state but does report it in the log.

* Describe the behavior you expected and how it differed from the actual behavior.

> Burn should check for per-machine state first to avoid this state.

**Comment by Texernie** [comment]
Is there any work around to this? A related issue was closed pointing to this one. This is a fairly major stumbling block for the project I am working on.
