### ISSUE TITLE
WiX Heat tool fails on harvesting selfreg data for out-of-process COM servers with CLR Support enabled

### ISSUE THREAD

**Issue by TigerGalo** [wixtoolset/issues#5480]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.10.2516

* Which version of Visual Studio are you building with (if any)?
MS Visual Studio 2010  ver. 10.0.40219.1 SP1Rel

* Which version of .NET are you building with?
MS .NET Framework ver. 4.0

* Describe the problem and the steps to reproduce it.

Initially I had few COM Servers that when I try the WiX Heat tool on to harvest self-registry data then it would not fail but harvest nothing by generating only the File element under the Component element. However, it would give me a warning like below:

heat.exe file "C:\TestCOMHeat\TestCOM\Debug\TestCOM.exe" -o abcd.wxs

heat.exe : warning HEAT5151 : Could not harvest data from a file that was expected to be an assembly: C:\TestCOMHeat\TestCOM\Debug\TestCOM.exe. If this file is not an assembly you can ignore this warning. Otherwise, this error detail may be helpful to diagnose the failure: Could not load file or assembly 'TestCOM, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Attempt to load an unverifiable executable with fixups (IAT with more than 2 sections or a TLS section.) (Exception from HRESULT: 0x
80131019)

After some research and testing, finally, I figured it out that the reason was the CLR Support. So if my COM component is using managed code (C++/CLI) and for that purpose I enable Common Language Runtime Support for my project then Heat sort of treats my component as .NET assembly, which is wrong, and cannot harvest anything. However, if the CLR Support is disabled (removed), then it's fine.

So, if you go ahead and create a new empty ATL Project with Visual Studio under Visual C++ branch, then you can easily test my statements with CLR Support ON and OFF trying to harvest with heat.

* Describe the behavior you expected and how it differed from the actual behavior.

I know that heat itself is not capable to harvest self-reg data for COM servers, however, I tried the above also with the 'atlcom' option of heat after installing the WixHeatATLHarvesterExtension out there free in the Internet (https://github.com/nirbar/WixHeatATLHarvesterExtension).  I have also tried all these steps with a HeatWave Harvesting tool by FireGiant which is more powerful than the heat, but the results, unfortunately are the same.

So what I expect, the core heat at least not to give this warning and not to state that it cannot harvest data from a file. The warning to me is because the out-of-process COM servers are still being considered as .NET assembly just because they have the CLR support enabled. I believe, if it is fixed then heat with the ATL extension should be able to harvest self-reg data. And I hope the will also be integrated into HeatWave as well.

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

Benefit would be harvesting also self-reg data.

* Describe how you're accomplishing the feature today (if possible).

Using HeatWave (which also fails on harvesting if the COM Server component has CLR Support ON) or registering/unregistering with the use of custom actions which is not encouraged, and the last way as a workaround is manually register and compare registry exports taken before registration and after, then based on difference create the WiX tags for it. The later, needs to be done every time interface changes for these components.

* Describe what you'd like the new feature to do.

To harvest with no issues and despite whether the COM Server has CLR Support ON or OFF.

**Comment by barnson** [comment]
Heat doesn't support harvesting out-of-proc servers. That's a long-standing request nobody's implemented: https://github.com/wixtoolset/issues/issues/103
