### ISSUE TITLE
WiX should support building with (and native libraries for) VS2017

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5484]
* Describe the scenario and benefits that the feature supports.

> Get the benefits of latest code-gen and the ability to build with only the latest VS installed.

* Describe how you're accomplishing the feature today (if possible).

> n/a

* Describe what you'd like the new feature to do.

> Detect when running under a VS2017 instance and use its toolsets for native and managed code. Build native libraries with VS2017; that's not strictly necessary as VS2017 is allegedly forward and backward compatible with VS2015 libraries but given how we've split the native libraries, it makes sense to ship VS2017 support the same way.

**Comment by cedral** [comment]
More specifically if you don't have VS2015. We do every other version so we have 2013 and 2017. So installing WIX 3.11 currently does not give me the libraries to build with 2017 without manually going and getting the binaries and unzipping them into the install folder myself.
