### ISSUE TITLE
Building WiX projects that generate messages may deadlock in VSTS vNext builds

### ISSUE THREAD

**Issue by dwhearn** [wixtoolset/issues#5486]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2015 Update 2 from VSTS vNext build definition.

* Which version of .NET are you building with?

> .NET 4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> NA

* Describe the problem and the steps to reproduce it.

> Using Visual Studio Team Services new vNext build definition, add a step to build a Visual Studio solution containing a WiX project. If the WiX linker generates any warning or error messages it can deadlock the build.

* Describe the behavior you expected and how it differed from the actual behavior.

> There was a report of the problem and some suggested workarounds on Microsoft's website that has been removed. One of the suggested workarounds was to specify the '‘/p:RunWixToolsOutOfProc=true’ as an MSBuild argument to the build step. This does fix the problem but is not easy to find this as a solution to the build hanging.

This was brought up as an issue with product manager VSTS build at Microsoft and their response was that they had concerns about adding this string to every single project build command and advised opening up a bug report here. The suggestion is for WiX to always run out of process so that it does not deadlock.

**Comment by barnson** [comment]
Is this discussion with VSTS folks public somewhere? It would be useful to understand what's causing the deadlock.

**Comment by barnson** [comment]
If you can provide more details, we'll take a look at our next online meeting on 28-Feb.

**Comment by dwhearn** [comment]
The Microsoft product manager who is our contact with this issue said they would have someone address your questions. But the basic problem is if the WiX linker generates a warning or error message and is running in-process with the vNext build it will normally deadlock and the build will eventually time out.

**Comment by barnson** [comment]
We haven't heard back from Microsoft and aren't experiencing it in the WiX build itself.

**Comment by ericsciple** [comment]
@barnson in VSTS we hook up a custom forwarding logger to msbuild so we can convert errors/warnings into issues that are attached to the build. The logger formats the error with special syntax, and then prints to STDOUT (for the agent to intercept and convert into an issue associated with the build).

So the logger calls `Console.WriteLine(string)`, which is hanging sometimes. `Console.WriteLine(string)` ends up calling System.IO.TextWriter.SyncTextWriter.WriteLine(string value)`, which calls `this._out.WriteLine(char)`. From a dump, I saw the local variable state `_out` is an instance of `Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.WixToolTaskLogger` and it appears `WixToolTaskLogger.Write(char)` was deadlocking. We saw this in WixTasks.dll 3.10.1.

**Comment by barnson** [comment]
https://github.com/wixtoolset/wix3/blob/develop/src/tools/WixTasks/WixToolTask.cs#L382 is how we redirect console output. Can you get more detail about the deadlock? Also, try WiX v3.10.3 (or the new v3.11 RC).

**Comment by ericsciple** [comment]
Unfortunately I don't have a repro. A customer ran into the issue and we were able to figure out a workaround.

However, [here is a thread](https://social.msdn.microsoft.com/Forums/en-US/a2d4eac5-8fbc-4202-b464-9e94a7654019/wix-installer-project-freezes?forum=msbuild) that talks about the issue. In that thread someone describes a potential theoretical repro... although the custom logger we use in TFS simply calls Console.WriteLine, so I'm not sure.

**Comment by barnson** [comment]
Thanks, @ericsciple; that thread should be useful (though I wish someone had reported it back then).

**Comment by laedit** [comment]
My two cents on this issue: I had a Wix build hanging on VSTS and it appear that building the wixproj on x86 platform with warnings like 
> warning CNDL1044: The File/@ShortName attribute's value 'SYSTEM\~1.DLL' is an ambiguous short name because it ends with a '\~' character followed by a number.  Under some circumstances, this name could resolve to more than one file or directory name and lead to unpredictable results (for example 'MICROS\~1' may correspond to 'Microsoft Shared' or 'Microsoft Foo' or literally 'Micros\~1').

 was the cause.

The [`RunWixToolsOutOfProc` property](https://github.com/wixtoolset/wix3/blob/wix3103rtm/src/tools/WixTasks/wix2010.targets#L89), setted manually to `true` in my project, had allow me to unblock the build on VSTS. Once the bad code gone I was able to remove the property without blocking the build again.

I tried to reproduce it on a new wixproj, but the warning doesn't block the build.
That said it appears twice on the log, I don't know if it is relevant:

> d:\a\1\s\SetupProject1\Product.wxs(17): error CNDL0026: The Directory/@ShortSourceName attribute's value, 'INSTALL\~1', is not a valid 8.3-compliant name.  Legal names contain no more than 8 non-period characters followed by an optional period and extension of no more than 3 non-period characters.  Any character except for the follow may be used: \ ? | > < : / * " + , ; = [ ] (space). [d:\a\1\s\SetupProject1\SetupProject1.wixproj]
SetupProject1\Product.wxs(17,0): Error CNDL0026: The Directory/@ShortSourceName attribute's value, 'INSTALL~1', is not a valid 8.3-compliant name. Legal names contain no more than 8 non-period characters followed by an optional period and extension of no more than 3 non-period characters. Any character except for the follow may be used: \ ? | > < : / * " + , ; = [ ] (space).

**Comment by dan-olsen** [comment]
Is there any word if this fix would/could be backported to 3.11.x? Since 3.14.x does not have a release timeline (that I’m aware of).

**Comment by dan-olsen** [comment]
@barnson @rseanhall Any update on the possibility of backporting this to 3.11.x? We are still getting bit by this issue almost 5 years after its been fixed and 3.14 and 4.0 are not ready for production yet.

**Comment by rseanhall** [comment]
It was never going to be backported to 3.11.x. .NET Core has been using 3.14 for several years to ship .NET 5+ (maybe even 3.1, I don't remember). 4.0 is about to ship so you should really be testing your product with v4 now.

**Comment by dan-olsen** [comment]
@rseanhall Ok. I was not aware that 3.14 was ready since the website lists 3.11.2 as the recommended build with 3.14 listed as a development build and stating it is not considered production-ready. We are not able to move to a version that is labeled as development or not production-ready which is where my original backporting question came from. If 3.14 is production ready is there plans to update the recommended version or list 3.14 as non-development?

I did know that v4 was getting ready to release soon and we plan on starting to use it soon.

**Comment by robmen** [comment]
There is no "production ready" v3.14. We've done nothing to verify any of the v3.14 builds. It's just a build. You can use it if you want. Some people choose to. Our focus in the community is on v4. 

If you are looking for guarantees about WiX builds (especially v3), you might be interested in [a support contract from FireGiant](https://www.firegiant.com/services/). They provide "production ready" releases for their customers regularly.

**Comment by dan-olsen** [comment]
@robmen Makes sense. I'll look forward to checking out v4 in the future. Thanks.

**Comment by robmen** [comment]
@dan-olsen you should make "the future" soon. After we finish with WiX v4, the community's focus will move to v5.
