### ISSUE TITLE
Random issue : The "SuppressPatchSequenceData" parameter is not supported by the "Light" task. 

### ISSUE THREAD

**Issue by fforjan** [wixtoolset/issues#5488]
* Which version of WiX are you building with?

Building with wixtoolset v3.10.3.3007 from chocolatey repository

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2015 Update 3

* Which version of .NET are you building with?

.Net 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows Server 2012R2

* Describe the problem and the steps to reproduce it.

On the same build machine 2015, builds are passing and suddently, we will get this error: 
:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets (2481, 7)
The "SuppressPatchSequenceData" parameter is not supported by the "Light" task. Verify the parameter exists on the task, and it is a settable public instance property.
C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets (2435, 5)
The "Light" task could not be initialized with its input parameters.
Process 'msbuild.exe' exited with code '1'.

And then following build will be green.
We don't really have a steps to replay it as it seems random

Any idea ?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by fforjan** [comment]
Hey Guys, no one is answering, what's the next step ?

**Comment by barnson** [comment]
You might try turning on Fusion logging.

**Comment by rail-ka** [comment]
Hello, I have the same problem, did you manage to solve the problem?
