### ISSUE TITLE
WIP: Repository Reorganization

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#5489]
* Describe the scenario and benefits that the feature supports.

> The WiX Toolset repositories are currently monoliths organized by major version. Given that the WiX Toolset spans the breadth of the Windows ecosystem that means developers need pretty much everything to build anything. We also build everything all the time whether it was updated or not. Finally, it is easy to introduce a breaking change to a public interface and quietly fix up the WiX Toolset code without fully considering the implications of the change.
>
> This proposal breaks down the monolithic repository into repositories defined by the interfaces between WiX Toolset layers. This will improve developer productivity when working in a layer and better demarcate interfaces between WiX Toolset layers.

* Describe how you're accomplishing the feature today (if possible).

> We build everything all the time today.

* Describe what you'd like the new feature to do.

> See the WIP design document.

**Comment by fyodorkor** [comment]
Hi,
This is great Idea that will simplify the process of development but let me share with your two issues that we faced in our environment:
1. Recursivity: Component A depend on Component B, B depends on Component C and C depend on A. In a long dependency queue it is quite difficult to catch this without special tool.
2. Versioning: Let say Component A depends on B and C, and B depend on C. If they are all built in different times it can be a situation that component B brings component C of version 1 but Component A brings C of version 2 and version 1 through component B. Which one to take?

**Comment by robmen** [comment]
You are absolutely correct.

The design here emphasizes layers to prevent cycles and a single repository (`Core`) that is the final arbiter of which version of shared (via interfaces) components are released.

It will be a bit bumpy during early development when interfaces are allowed to change that smooths out once the interface boundaries are well defined.

This proposal is very specific to the design of the WiX Toolset and may not be generally applicable to other projects. 😉

**Comment by iswix-llc** [comment]
On several occassions over many years I've pulled the wix source down and tried to build it and I've just never had good results.  I wish there was a vagrant image or docker image that would allow me to  build wix reliably without putting much thought into it.  There have been a few tims where I felt that I could handle fixing a bug and submitting a pull request but simply trying to get it to build in the first place stops me.

**Comment by NicoleTedescoCalvIO** [comment]
Is there a community forum where WiX building is discussed?  Does there exist fixes to the build process that is contained in tribal lore that is otherwise undocumented?  I would like to know what I am missing to make the build work in VS Community 2017, for instance.  I am trying to make a decision whether to go with WiX, along with the commitment that would require to get involved and help WiX continue to function and evolve, or spend the money on a commercial system.  Before I can do that, I would like to know what it would feel like to successfully contribute to a WiX build.  That, of course, cannot happen until I can successfully build the project at least once.

**Comment by robmen** [comment]
You want the [wix-devs](http://wixtoolset.org/documentation/) mailing list.

**Comment by NicoleTedescoCalvIO** [comment]
Thank you for your fast reply!
