### ISSUE TITLE
WiX 3.10.3 Upgrading from previous version of product fails to install 11 files

### ISSUE THREAD

**Issue by steveOgilvie** [wixtoolset/issues#5491]
Added the exported tables of the 4.7 MSI built with 3.10.3 and then built with 3.10.2
Steve
[Admin_CompareMSIs.zip](https://github.com/wixtoolset/issues/files/785210/Admin_CompareMSIs.zip)
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.10.3
> (WiX version in major.minor.release.build format)
3.10.3.3007
* Which version of Visual Studio are you building with (if any)?
VS 2015 
> (Visual Studio version, including year and update)
Version 14.0.25431.01 Update 3
* Which version of .NET are you building with?
4.6.01586
> (.NET version)
4.6.01586
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows Server 2012R2
> (Windows version)
6.3 (Build 9600)
* Describe the problem and the steps to reproduce it.
Upgrading our Enterprise Admin console 4.5 to 4.6 is successful
4.5 or 4.6 to 4.7 upgrade fails, 11 ASP .NET files are not installed (system.net*.dll, system.web.*.dll)
These ASP .NET files have NOT changed in over 4 versions
This Enterprise Admin Console's installer has:
1 merge module (almost no changes since 4.4 version)
12 Shared WiX libraries
3 features

This installer has barley changed over the years, the only thing that has changed was going from WiX 3.10.2 to 3.10.3 in 4.7

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
I am attaching the WiX source for 4.6 and 4.7 as well as log files, here are the logs for 4.6 fresh install and 4.7 upgrade 

* Describe the behavior you expected and how it differed from the actual behavior.
Upgrading from 4.5 to 4.6 works perfectly all files are installed
4.6 to 4.7 is missing 11 ASP .NET files...

> (Be as specific as you can and err on the side of providing too much information.)
I just can't understand this one... The install/merge module/shared libraries have not changed much from our last version to our new version...

The main difference is we went from WiX 3.10.2 to 3.10.3

The 11 files missing are from a Merge Module I have been using with this install for 5 versions of this product. The 11 files in question have NOT changed (component/file elements) in the merge module in over 4 versions.

Now I am doing an upgrade from 4.6 (16.5.11.5) to 4.7 (17.2.0.1) and the 11 files are missing (fresh install they are installed).

The merge module has changed only very slightly in the last 4 versions... since the last version it only has changed with 1 file and that is where the source of that file is (not one of the missing 11)...

From the merge module:

<?xml version="1.0" encoding="UTF-8"?>

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <?include $(var.SolutionDir)\Includes\Variables.wxi ?>
  <Module Id="AdminMergeModule" Language="1033" Version="!(bind.fileVersion.file_anotherbinary)">
    <Package Id="5559BD7F-840B-4DBA-8D43-1A50B01331DC" Manufacturer="$(var.ProductCompany)" InstallerVersion="500" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="MergeRedirectFolder">

...

then (I am calling some shared WiX libraries that are to be installed to the 'bin' folder)

<Directory Id="WixLibRedirectFolder" Name="bin">

<Component Id="cmp_System.Net.Http" Guid="{40F061F4-D7C1-49C1-8534-45D9886E6A2E}">
  <File Id="fil4009294F63EF8FAB368A73392F03EC27" KeyPath="yes" Source="$(var.tssSourcePath)\Admin\System.Net.Http.dll" /> </Component> <Component Id="cmp_System.Web.Helpers" Guid="{1BA25B0A-6D9A-4480-9E2D-C4104409B7FE}">
  <File Id="fil268028B26C4BD9C491CD78E2B02BEA52" KeyPath="yes" Source="$(var.tssSourcePath)\Admin\System.Web.Helpers.dll" /> </Component> <Component Id="cmp_System.Web.Optimization" Guid="{C4024628-473D-4D50-84BF-3FC25C660971}">
  <File Id="fil0F47A6C544A2E626CBC42D0D0CB11CAF" KeyPath="yes" Source="$(var.tssSourcePath)\Admin\System.Web.Optimization.dll" /> </Component>

The Product.wxs which calls the merge module:

The upgrade code has NOT changed since the beginning version, The ProductGUID is different every build, the version number has changed via the major.minor.release.build

<Product Id="$(var.ProductCode)" which is "*"
           Name="$(var.ProductName)"
           Language="1033"
           Version="$(var.CoreVersion)" version of a file !(bind.fileVersion.file_somebinary)
           Manufacturer="$(var.ProductCompany)"
           UpgradeCode="$(var.UpgradeCode)"> this GUID has NOT changed since beginning of this product
    <Package InstallPrivileges="elevated"
             Manufacturer="$(var.ProductCompany)"
             InstallerVersion="500"
             Compressed="yes"
             InstallScope="perMachine"/>

<MajorUpgrade DowngradeErrorMessage="$(var.DowngradeError_Message)" Schedule="afterInstallValidate" AllowDowngrades="no"/>

The 3 features are all Level="1" and are all installed, features are not visible to the user

<Feature Id="Feature_Admin"

             Title="Admin Console"
             Level="1"
             Display="expand"
             ConfigurableDirectory="DIRECTORY_PATH_SERVER">
      <MergeRef Id="AdminMergeModule"/>

...

<Directory Id="TARGETDIR" Name="SourceDir">
  <Directory Id="DIRECTORY_PATH_SERVER" DiskId="1">
    <Merge Id="AdminMergeModule" SourceFile="$(env.TLSharedServices)\Installers\wixlibx64\AdminMergeModule.msm" Language="1033"/>

The upgrade logs are not telling me much (at least I don't see what the issue is, the 4.7 upgrade log has very similar logging with the 4.6 install log except it is missing the InstallFiles section for those 11 files...

Here is the logging for 4.6:

I have included 2 files that are not upgraded, and 1 file that is (system.net.http.dll and system.web.helpers.dll, System.Web.Optimization is upgraded)...

MSI (s) (DC:B0) [12:10:32:935]: Component: cmp_System.Net.Http.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Absent;   Request: Local;   Action: Local
MSI (s) (DC:B0) [12:10:32:935]: Component: cmp_System.Web.Helpers.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Absent;   Request: Local;   Action: Local
MSI (s) (DC:B0) [12:10:32:935]: Component: cmp_System.Web.Optimization.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Absent;   Request: Local;   Action: Local

MSI (s) (DC:B0) [12:10:34:341]: Executing op: ComponentRegister(ComponentId={40F061F4-D7C1-49C1-8534-45D9886E6A2E},KeyPath=C:\inetpub\WebAdministration\bin\System.Net.Http.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
1: {3BF13C90-0568-4065-BA1D-077CC9674A2D} 2: {40F061F4-D7C1-49C1-8534-45D9886E6A2E} 3: C:\inetpub\WebAdministration\bin\System.Net.Http.dll
MSI (s) (DC:B0) [12:10:34:341]: Executing op: ComponentRegister(ComponentId={1BA25B0A-6D9A-4480-9E2D-C4104409B7FE},KeyPath=C:\inetpub\WebAdministration\bin\System.Web.Helpers.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
1: {3BF13C90-0568-4065-BA1D-077CC9674A2D} 2: {1BA25B0A-6D9A-4480-9E2D-C4104409B7FE} 3: C:\inetpub\WebAdministration\bin\System.Web.Helpers.dll
MSI (s) (DC:B0) [12:10:34:341]: Executing op: ComponentRegister(ComponentId={C4024628-473D-4D50-84BF-3FC25C660971},KeyPath=C:\inetpub\WebAdministration\bin\System.Web.Optimization.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
1: {3BF13C90-0568-4065-BA1D-077CC9674A2D} 2: {C4024628-473D-4D50-84BF-3FC25C660971} 3: C:\inetpub\WebAdministration\bin\System.Web.Optimization.dll

MSI (s) (DC:B0) [12:10:34:497]: Executing op: SetTargetFolder(Folder=C:\inetpub\WebAdministration\bin\)
MSI (s) (DC:B0) [12:10:34:497]: Executing op: SetSourceFolder(Folder=1\bin\) MSI (s) (DC:B0) [12:10:34:497]: Executing op: FileCopy(SourceName=pazmpudh.dll|System.Web.Optimization.dll,SourceCabKey=fil0F47A6C544A2E626CBC42D0D0CB11CAF.5559BD7F_840B_4DBA_8D43_1A50B01331DC,DestName=System.Web.Optimization.dll,Attributes=512,FileSize=54912,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.0.0.0,Language=0,InstallMode=58982400,,,,,,,)
MSI (s) (DC:B0) [12:10:34:497]: File: C:\inetpub\WebAdministration\bin\System.Web.Optimization.dll; To be installed; Won't patch; No existing file MSI (s) (DC:B0) [12:10:34:497]: Source for file 'fil0F47A6C544A2E626CBC42D0D0CB11CAF.5559BD7F_840B_4DBA_8D43_1A50B01331DC' is compressed
InstallFiles: File: System.Web.Optimization.dll,  Directory: C:\inetpub\WebAdministration\bin\,  Size: 54912 MSI (s) (DC:B0) [12:10:34:747]: Executing op: SetTargetFolder(Folder=C:\inetpub\WebAdministration\bin\)
MSI (s) (DC:B0) [12:10:34:747]: Executing op: SetSourceFolder(Folder=1\bin\) MSI (s) (DC:B0) [12:10:34:747]: Executing op: FileCopy(SourceName=wt4uzyey.dll|System.Net.Http.dll,SourceCabKey=fil4009294F63EF8FAB368A73392F03EC27.5559BD7F_840B_4DBA_8D43_1A50B01331DC,DestName=System.Net.Http.dll,Attributes=512,FileSize=83136,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=4.0.30319.34211,Language=1033,InstallMode=58982400,,,,,,,)
MSI (s) (DC:B0) [12:10:34:747]: File: C:\inetpub\WebAdministration\bin\System.Net.Http.dll; To be installed; Won't patch; No existing file MSI (s) (DC:B0) [12:10:34:747]: Source for file 'fil4009294F63EF8FAB368A73392F03EC27.5559BD7F_840B_4DBA_8D43_1A50B01331DC' is compressed
InstallFiles: File: System.Net.Http.dll,  Directory: C:\inetpub\WebAdministration\bin\,  Size: 83136

And the logging for 4.7 upgrade:

I have included 2 files that are not upgraded, and 1 file that is (system.net.http.dll and system.web.helpers.dll, System.Web.Optimization is upgraded)...

MSI (s) (68:FC) [13:29:31:547]: Component: cmp_System.Net.Http.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Absent;   Request: Local;   Action: Null
MSI (s) (68:FC) [13:29:31:547]: Component: cmp_System.Web.Helpers.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Absent;   Request: Local;   Action: Null
MSI (s) (68:FC) [13:29:31:547]: Component: cmp_System.Web.Optimization.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Absent;   Request: Local;   Action: Local

MSI (s) (68:70) [13:29:32:656]: Component: cmp_System.Net.Http.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Local;   Request: Absent;   Action: Absent
MSI (s) (68:70) [13:29:32:656]: Component: cmp_System.Web.Helpers.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Local;   Request: Absent;   Action: Absent
MSI (s) (68:70) [13:29:32:656]: Component: cmp_System.Web.Optimization.5559BD7F_840B_4DBA_8D43_1A50B01331DC; Installed: Local;   Request: Absent;   Action: Absent

MSI (s) (68:70) [13:29:38:029]: Executing op: FileRemove(,FileName=System.Net.Http.dll,,ComponentId={40F061F4-D7C1-49C1-8534-45D9886E6A2E})
RemoveFiles: File: System.Net.Http.dll, Directory: C:\inetpub\WebAdministration\bin\ MSI (s) (68:70) [13:29:38:029]: Verifying accessibility of file: System.Net.Http.dll MSI (s) (68:70) [13:29:38:045]: Executing op: FileRemove(,FileName=System.Web.Helpers.dll,,ComponentId={1BA25B0A-6D9A-4480-9E2D-C4104409B7FE})
RemoveFiles: File: System.Web.Helpers.dll, Directory: C:\inetpub\WebAdministration\bin\ MSI (s) (68:70) [13:29:38:045]: Verifying accessibility of file: System.Web.Helpers.dll MSI (s) (68:70) [13:29:38:045]: Executing op: FileRemove(,FileName=System.Web.Optimization.dll,,ComponentId={C4024628-473D-4D50-84BF-3FC25C660971})
RemoveFiles: File: System.Web.Optimization.dll, Directory: C:\inetpub\WebAdministration\bin\ MSI (s) (68:70) [13:29:38:061]: Verifying accessibility of file: System.Web.Optimization.dll

MSI (s) (68:FC) [13:29:43:169]: Executing op: ComponentRegister(ComponentId={40F061F4-D7C1-49C1-8534-45D9886E6A2E},KeyPath=C:\inetpub\WebAdministration\bin\System.Net.Http.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
1: {D849E411-6FA9-4655-804B-5F2FEA730212} 2: {40F061F4-D7C1-49C1-8534-45D9886E6A2E} 3: C:\inetpub\WebAdministration\bin\System.Net.Http.dll
MSI (s) (68:FC) [13:29:43:169]: Executing op: ComponentRegister(ComponentId={1BA25B0A-6D9A-4480-9E2D-C4104409B7FE},KeyPath=C:\inetpub\WebAdministration\bin\System.Web.Helpers.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
1: {D849E411-6FA9-4655-804B-5F2FEA730212} 2: {1BA25B0A-6D9A-4480-9E2D-C4104409B7FE} 3: C:\inetpub\WebAdministration\bin\System.Web.Helpers.dll
MSI (s) (68:FC) [13:29:43:169]: Executing op: ComponentRegister(ComponentId={C4024628-473D-4D50-84BF-3FC25C660971},KeyPath=C:\inetpub\WebAdministration\bin\System.Web.Optimization.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
1: {D849E411-6FA9-4655-804B-5F2FEA730212} 2: {C4024628-473D-4D50-84BF-3FC25C660971} 3: C:\inetpub\WebAdministration\bin\System.Web.Optimization.dll

MSI (s) (68:FC) [13:29:43:325]: Executing op: SetTargetFolder(Folder=C:\inetpub\WebAdministration\bin\)
MSI (s) (68:FC) [13:29:43:325]: Executing op: SetSourceFolder(Folder=1\bin\) MSI (s) (68:FC) [13:29:43:325]: Executing op: FileCopy(SourceName=pazmpudh.dll|System.Web.Optimization.dll,SourceCabKey=fil0F47A6C544A2E626CBC42D0D0CB11CAF.5559BD7F_840B_4DBA_8D43_1A50B01331DC,DestName=System.Web.Optimization.dll,Attributes=512,FileSize=54912,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=1.0.0.0,Language=0,InstallMode=58982400,,,,,,,)
MSI (s) (68:FC) [13:29:43:325]: File: C:\inetpub\WebAdministration\bin\System.Web.Optimization.dll; To be installed; Won't patch; No existing file MSI (s) (68:FC) [13:29:43:325]: Source for file 'fil0F47A6C544A2E626CBC42D0D0CB11CAF.5559BD7F_840B_4DBA_8D43_1A50B01331DC' is compressed
InstallFiles: File: System.Web.Optimization.dll,  Directory: C:\inetpub\WebAdministration\bin\,  Size: 54912

it was suggested that perhaps the version number was NULL for these files...

No they do not have NULL in the version table, they are mostly MS ASP.NET files:
																													size	Version		Lang	Attrib	Sequence
fil4009294F63EF8FAB368A73392F03EC27.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Net.Http.5559BD7F_840B_4DBA_8D43_1A50B01331DC			wt4uzyey.dll|System.Net.Http.dll		181856	1.0.0.0		0	512	65
filBE123CD38F697048D45120FCF0055F64.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Net.Http.Formatting.5559BD7F_840B_4DBA_8D43_1A50B01331DC	u3dij9qv.dll|System.Net.Http.Formatting.dll	159328	4.0.20505.0	0	512	178
filDA044F14931000656FF2E074DFAD905A.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Net.Http.WebRequest.5559BD7F_840B_4DBA_8D43_1A50B01331DC	iv9jgd3p.dll|System.Net.Http.WebRequest.dll	15456	1.0.0.0		0	512	204
fil268028B26C4BD9C491CD78E2B02BEA52.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Helpers.5559BD7F_840B_4DBA_8D43_1A50B01331DC		yqfp3ntl.dll|System.Web.Helpers.dll		138352	2.0.20505.0	0	512	34
filA44B31421CF585F507C6A5C74EFCF709.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Http.5559BD7F_840B_4DBA_8D43_1A50B01331DC			mo98fa_c.dll|System.Web.Http.dll		360032	4.0.20505.0	0	512	148
fil361B685205EA6E3FEB39D3B0F7F7E3AC.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Http.WebHost.5559BD7F_840B_4DBA_8D43_1A50B01331DC		fhm9nd3k.dll|System.Web.Http.WebHost.dll	65632	4.0.20505.0	0	512	57
fil065068CC9E5BA7AB8C7BC20A11DF9063.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Mvc.5559BD7F_840B_4DBA_8D43_1A50B01331DC			avkmkeei.dll|System.Web.Mvc.dll		497248	4.0.20505.0	0	512	10
fil0F47A6C544A2E626CBC42D0D0CB11CAF.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Optimization.5559BD7F_840B_4DBA_8D43_1A50B01331DC		pazmpudh.dll|System.Web.Optimization.dll	54912	1.0.0.0		0	512	18
fil23755169D0E4B8880A0A207D4B32F780.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Providers.5559BD7F_840B_4DBA_8D43_1A50B01331DC		twtkjtsv.dll|System.Web.Providers.dll		269120	1.0.0.0		0	512	30
filEA55CCE03AB064D7B5DD65AE816EDF26.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.Razor.5559BD7F_840B_4DBA_8D43_1A50B01331DC			boho50xy.dll|System.Web.Razor.dll		264816	2.0.20505.0	0	512	330
filBCD8D08ACF74C740EA375F4F63285AE2.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.WebPages.5559BD7F_840B_4DBA_8D43_1A50B01331DC		ywth8zjl.dll|System.Web.WebPages.dll		204400	2.0.20505.0	0	512	173
filF768CFF536DDCA65916A24225B89F904.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.WebPages.Deployment.5559BD7F_840B_4DBA_8D43_1A50B01331DC	0in838kk.dll|System.Web.WebPages.Deployment.dll	40560	2.0.20505.0	0	512	337
fil6B23B370E320F58A583A9892E587C0A0.5559BD7F_840B_4DBA_8D43_1A50B01331DC	cmp_System.Web.WebPages.Razor.5559BD7F_840B_4DBA_8D43_1A50B01331DC	hs3wbj8r.dll|System.Web.WebPages.Razor.dll	39536	2.0.20505.0	0	512	109

They are most likely the EXACT same version as the previous installer files..., i.e. they have not changed in a while...

Should I use "DefaultVersion and increase the version number by 1 i.e. the 3rd digit: i.e.
<File Id="fil4009294F63EF8FAB368A73392F03EC27" KeyPath="yes" Source="$(var.tssSourcePath)\Titus.Admin\System.Net.Http.dll" DefaultVersion="1.0.1.0" ??

[TITUS Upgrade from 45 to 46  to 47 logs.zip](https://github.com/wixtoolset/issues/files/771420/TITUS.Upgrade.from.45.to.46.to.47.logs.zip)
[fresh 46.zip](https://github.com/wixtoolset/issues/files/771455/fresh.46.zip)
[Upgrade47.zip](https://github.com/wixtoolset/issues/files/771457/Upgrade47.zip)

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by steveOgilvie** [comment]
Classification: Public
This is a bug…

4.5 to 4.6 works perfectly (3.10.0 and 3.10.2)
Upgrading to 4.7 had 11 files missing that have not changed in 4 years
The only difference is using 3.10.3

I have had to create a work around to get this working…

Install these 11 files as *.dll.bak
Copy from *.dll.bak to *.dll
Create custom action to remove the *.dll.bak

I have gone to WiX User mailing list and no one had the proper info to get this working…

The same WiX code works in 3.10.2 but not in 3.10.3

Steve

This message has been marked as Public by Steven Ogilvie on February 13, 2017 11:37:57 AM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by steveOgilvie** [comment]
Classification: Public
Please re open this is a bug…

This message has been marked as Public by Steven Ogilvie on February 13, 2017 11:38:20 AM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by robmen** [comment]
I'll reopen and triage will put it in its place but know that nothing changed in the core toolset between v3.10.2 and v3.10.3. The only changes of consequence were in Burn for handling the Windows DLL injection security vulnerability.

**Comment by steveOgilvie** [comment]
Classification: Public
Not sure what to tell you

I was able to do a 4.5 to 4.6 upgrade with no issues 3.10.2 (both of them)

4.6 to 4.7 11 files are NOT being installed that have been part of the file set since 4.2 or even 4.1

I have attached the logs from 4.5 to 4.6 then to 4.7

I have attached the wix projects for 4.6 and 4.7

Steve

This message has been marked as Public by Steven Ogilvie on February 13, 2017 1:11:43 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by steveOgilvie** [comment]
Classification: Public
Thank you

This message has been marked as Public by Steven Ogilvie on February 13, 2017 1:11:57 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
What are the differences in the .msis between the 4.7 package built with WiX v3.10.2 and WiX v3.10.3?

**Comment by steveOgilvie** [comment]
Classification: Public
4.5/4.6 were built with 3.10.2
4.7 was built with 3.10.3

The differences are minimal, changed a couple of our binaries source locations
1 change in the merge module (a source location was changed for 1 binary)
In the product.wxs file
Added a comment to a component

To fix the issue, in product.wxs
I added a new feature
Added a new directory property
Added 8 new Dlls to this new feature AND added the 11 missing DLLs (being copied over as *.dll.bak, i.e.

<Component Id="cmp_SystemNetHttp_AD" Guid="{a GUID}">
            <File Id="file_SystemNetHttp_AD" KeyPath="yes" Name="System.Net.Http.dll.bak" Source="$(var.tssSourcePath)\Admin\System.Net.Http.dll" />
            <CopyFile Id="cpy_SystemNetHttp_AD" FileId="file_SystemNetHttp_AD" DestinationName="System.Net.Http.dll" DestinationDirectory="DIRECTORY_PATH_SERVER_BIN" />
            <Condition><![CDATA[WIX_UPGRADE_DETECTED]]></Condition>
          </Component>
Then a custom action to remove the 11 *.dll.bak files just before the end of the install

Added 6 new DLLs to an existing feature

I have the source of 4.6 and 4.7 zipped up wit the bug…

This message has been marked as Public by Steven Ogilvie on February 13, 2017 5:16:57 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
I'm asking what changes are in the output .msis, before the CopyFile hack.

**Comment by steveOgilvie** [comment]
Classification: Public
Sorry I am not sure I understand your question…

Steve

This message has been marked as Public by Steven Ogilvie on February 13, 2017 5:35:31 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
Build 4.7 with WiX v3.10.2. Build 4.7 with WiX v3.10.3. Compare the two .msis. What are the differences?

**Comment by steveOgilvie** [comment]
Classification: Public
Okay I will have to get back to you on that ☺ I am leaving work for today

This message has been marked as Public by Steven Ogilvie on February 13, 2017 5:39:01 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
If you can provide more details, we'll take a look at our next online meeting on 28-Feb.

**Comment by steveOgilvie** [comment]
Classification: General Business
I am not sure what more details you need…

I have put in some log details about fresh 4.6 then upgrade to 4.7 re the missing DLLs and 1 DLL that is installed by both
I have zipped up the source of 4.6 and zipped up the source of 4.7
I have zipped up the full logs of installing 4.5 upgrade to 4.6 upgrade to 4.7

Steve

This message has been marked as General Business by Steven Ogilvie on February 14, 2017 1:21:19 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
Like I said yesterday:
> Build 4.7 with WiX v3.10.2. Build 4.7 with WiX v3.10.3. Compare the two .msis. What are the differences?

**Comment by steveOgilvie** [comment]
Classification: Public
I can’t get to that today, or most likely tomorrow, I will have to change a few project files and a build script and right now I am in the middle of releases two different products ☹

This message has been marked as Public by Steven Ogilvie on February 14, 2017 1:58:21 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by steveOgilvie** [comment]
Classification: Public

Hmm

Not much difference at all only some binary diffs and the productCode which was expected:

Binary
                IIsExecute.ibd
                IIsSchedule.ibd
                WixCA.ibd
                WixCA_x64.ibd
                WixFirewallCA.ibd
                WixUIWixca.ibd

Property.idt                       ProductCode was different (as expected)

I have exported the tables from each MSI tables to an Admin_3.10.2 and Admin_3.10.3 and zipped it up.

I have added the zip to the bug… https://github.com/wixtoolset/issues/issues/5491

Thanks,

Steve


This message has been marked as Public by Steven Ogilvie on February 18, 2017 12:53:15 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
There are no unexpected differences in the built package from v3.10.2 to v3.10.3 so this can't be a WiX bug introduced in v3.10.3.

**Comment by steveOgilvie** [comment]
Classification: Public

But didn’t answer my issue, why the upgrade fails ☹

This message has been marked as Public by Steven Ogilvie on February 21, 2017 5:05:16 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by barnson** [comment]
Issues are for bugs. The mailing lists are for support.

**Comment by steveOgilvie** [comment]
Classification: Public

Sigh I did post to wix user list and didn’t get much help…

This message has been marked as Public by Steven Ogilvie on February 21, 2017 7:13:46 PM. Classification provided by TITUS.



<http://www.titus.com/TMCPolicy_footer_link_landingpage.php>

**Comment by zoushaohong** [comment]
@steveOgilvie I met the similar case. You'd better check the those missing dll's version. I guess dlls in new installer is older then previous one. 
below information is for your reference.
-----------------
MSI (c) (28:A0) [15:23:16:922]: Disallowing installation of component: {74C2AD07-ABAF-46D3-BC9D-78E59A39DB82} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:922]: Disallowing installation of component: {045970D3-1658-4FCB-84B2-408B2936604E} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:925]: Disallowing installation of component: {51C033F2-C887-470A-A9E1-84618898782C} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:926]: Disallowing installation of component: {80C73EB5-2271-49EB-8BE3-EEF69272EED6} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:937]: Disallowing installation of component: {234F6F57-EDBF-47A4-B2AD-1971F9A4516E} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:939]: Disallowing installation of component: {E2AFE0D4-323D-4133-8228-ED478D9DED58} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:939]: Disallowing installation of component: {1BF0D7E4-8924-462E-8AC6-FB78A0A01542} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:941]: Disallowing installation of component: {62092D5F-D39F-4083-B9F8-1D853B0133D7} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:941]: Disallowing installation of component: {7F4E6120-48C2-4613-A0C9-3E15EB8FB97C} since the same component with higher versioned keyfile exists
MSI (c) (28:A0) [15:23:16:942]: Disallowing installation of component: {70F36347-A51D-4B23-B93C-AFCBB1C90B7E} since the same component with higher versioned keyfile exists
-----------------
