### ISSUE TITLE
Heat: filtering file types takes "extra" file types

### ISSUE THREAD

**Issue by HeinanCA** [wixtoolset/issues#5493]
Hey,
While working with heat to take all files needed for an ASP.NET application, I made a filtering in Heat with XSLT, with the following lines:
`  <xsl:key name="cs-search" match="wix:Component[contains(wix:File/@Source, '.cs')]" use="@Id"/>
  <xsl:template match="wix:Component[key('cs-search', @Id)]"/>
  <xsl:template match="wix:ComponentRef[key('cs-search', @Id)]"/>`

**What I expected these lines to do?** Filter all cs files (C# files), which I don't want the customer to have.

**What it actually did?** Filtered all cs files, but also all csv and css files - which I need for the application.

Solving this was easy: I did a robocopy on the source folder with the /XF *.cs flag, which did filter only the cs files and left the csv and css files intact.

**Comment by barnson** [comment]
`contains` seems to be working as designed.
