### ISSUE TITLE
Feature Request - add option to exclude files\folders from heat harvesting

### ISSUE THREAD

**Issue by TeaHunny** [wixtoolset/issues#5495]
Can you please provide a way to pass an exclude list (of files\folders) to heat harvesting process?

The scenario in is that I have a a folder with thousands of files that need to be wrapped in a MSI and the file list is vary dynamic so I need use the heat to harvest the folder. In the harvested folder there are certain files\folders that I am attaching actions to (add shortcuts to them, pass them to custom actions and so on...)  in another wxs file\fragment and I can't change the folders structure not to include these files\folders.

Currently the only normal way to exclude these files\folders is to run a XSL transform on the harvested output, but writing a XSL file is rather tedious\annoying job and it would really help if there is friendlier way to accomplish the exclude.

(Another way is to move these files, harvest the folder and then move the files back again but in my opinion that is not a good solution and it increases the chances to somehow mess up the harvested folder).

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/4023
