### ISSUE TITLE
Light option 'bcgg' is deprecated without alternative

### ISSUE THREAD

**Issue by aramhak** [wixtoolset/issues#5498]
We have a Visual Studio 2008 solution that we recently converted to 2015. The setup project for the solution was .vdproj and generated component guids the old way (using MD5 hash). We converted the .vdproj setup project to a .wixproj. Apparently, new .vdproj setup projects and .wixproj setup projects generate component guids the new way (using SHA1 hash) and that's a problem for upgrade scenario as the upgrade doesn't recognize that it's the same component we're trying to install.

There is a '-bcgg' option for light linker that'll generate backwards compatible guid. That looks like what we need. But when I'm trying to use '-bcgg' option in WiX toolset 3.10.3, I'm getting:
3>light.exe(0,0): warning LGHT1108: The command line switch 'bcgg' is deprecated.

The upgrade scenario is critical for us and uninstall/install isn't viable at this point.

Is it possible to undeprecate 'bcgg' option?

**Comment by robmen** [comment]
The switch is deprecated because MD5 is deprecated (probably same reason .vdproj deprecated theirs). Fortunately, it's a warning. You can decide to ignore it until you start to upgrade to WiX v4. Then, should you choose to upgrade to WiX v4, you can hardcode the GUIDs in your authoring for those GUIDs that cannot change.

**Comment by aramhak** [comment]
Thanks for the reply.

Even though it's a warning, the upgrade scenario still removes the files from the target directory as if 'bcgg' option is not set.

Here's my linker command line:
3>	C:\Program Files (x86)\WiX Toolset v3.10\bin\Light.exe -out [filename].msi -pdbout [filename].wixpdb -sw1076 -sw1072 -bcgg -cultures:null -ext "C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixNetFxExtension.dll" -contentsfile obj\\Release\VulcanMediaPlayerSetup_wix.wixproj.BindContentsFileListnull.txt -outputsfile obj\\Release\VulcanMediaPlayerSetup_wix.wixproj.BindOutputsFileListnull.txt -builtoutputsfile obj\\Release\VulcanMediaPlayerSetup_wix.wixproj.BindBuiltOutputsFileListnull.txt -wixprojectfile [projectname].wixproj [list_of_wixobj_files]
3>light.exe(0,0): warning LGHT1108: The command line switch 'bcgg' is deprecated.

Am I doing something wrong?

I'm trying to avoid hardcoding GUIDs for our components, there are quite a few, that'll be very error-prone.

**Comment by aramhak** [comment]
Here's some more info. Hope that helps.
The problem with recognizing/upgrading the existing components is specifically with the ones that are specified as project outputs in the .wixproj. The components that are used explicitly have no issue, they are preserved after the upgrade, while the ones specified as project outputs are removed after the upgrade.
There is no problem with the productid or upgradeid here, the product gets upgraded, so there is only one item in Add/Remove Programs.

Here's an example of a component used explicitly:
            <Component Id='com_7120120E_F8ED_894C_863B_20AE90523AF2' Guid='C9A74758-D4B8-4304-B394-6ECCEAC18132' Permanent='no' SharedDllRefCount='no' Transitive='no'>
                <File Id='_7120120E_F8ED_894C_863B_20AE90523AF2' DiskId='1' Hidden='no' ReadOnly='no' System='no' Vital='yes' Compressed='yes' Name='messages.dll' Source='..\Common\messages.dll' KeyPath='yes' />

Here's an example of a component that's specified as project output:
            <Directory Id='VmpSettings.Binaries' />
[...]
        <ComponentGroup Id='FileSystemGroup'>
            <ComponentGroupRef Id='VmpSettings.Binaries' />
        </ComponentGroup>

For such a component, vdproj to wix converter created a separate .xml file like this:
<?xml version="1.0" encoding="utf-8"?>
<ProjectOutput Name="VmpSettings" ProjectDirVar="$(var.VmpSettings.ProjectDir)" TargetDirVar="$(var.VmpSettings.TargetDir)" SharedFileId="_BAE8C867_12A2_459C_8CC5_7B77145ED4C2">
  <Binaries>
    <DiskId>1</DiskId>
    <Compressed />
    <Hidden>no</Hidden>
    <KeyPath>yes</KeyPath>
    <ReadOnly>no</ReadOnly>
    <System>no</System>
    <Vital>yes</Vital>
    <Permanent>no</Permanent>
    <SharedDllRefCount>no</SharedDllRefCount>
    <Transitive>no</Transitive>
  </Binaries>
</ProjectOutput>

This xml is used by heat to harvest .wxs file in "BeforeBuild" stage, something like:
    
    <Exec Command="&quot;$(Wix)Bin\heat.exe&quot; project &quot;%(ProjectReference.FullPath)&quot; -projectname &quot;%(ProjectReference.Name)&quot; -pog %(ProjectReference.RefProjectOutputGroups) -gg -sfrag -nologo -out &quot;$(IntermediateOutputPath)Harvested XML\_%(ProjectReference.Name).xml&quot;" IgnoreExitCode="false" WorkingDirectory="$(MSBuildProjectDirectory)" Condition="'%(ProjectReference.FullPath)'!='' And '%(ProjectReference.DoNotHarvest)'!='True' And '%(ProjectReference.ImportedFromVDProj)'=='True'" />
    <HeatProject Project="%(ProjectReference.FullPath)" ProjectName="%(ProjectReference.Name)" OutputFile="$(IntermediateOutputPath)Harvested XML\_%(ProjectReference.Name).xml" ProjectOutputGroups="%(ProjectReference.RefProjectOutputGroups)" ToolPath="$(Wix)Bin\" SuppressAllWarnings="true" AutogenerateGuids="false" GenerateGuidsNow="true" SuppressFragments="true" SuppressUniqueIds="false" Condition="'%(ProjectReference.FullPath)'!='' And '%(ProjectReference.DoNotHarvest)'!='True' And '%(ProjectReference.ImportedFromVDProj)'!='True'" />

So, can we tweak something somewhere that a component specified as a project output is recognized as the same during upgrade (which means it has the same GUID)?

Thank you.

**Comment by aramhak** [comment]
Just to give an update on this.

The problem was with the component versions, they were lower in the upgrade setup package. Once I changed them to higher versions, the components were installed fine in the upgrade.

Also had to match the component guids individually using Orca. Oh god, was that tedious.
