### ISSUE TITLE
WiX C# Custom Action - build failed

### ISSUE THREAD

**Issue by hkesharia** [wixtoolset/issues#5500]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

> 3.10.3.007

* Which version of Visual Studio are you building with (if any)?

> VS 2015 Community Edition Update 3 

* Which version of .NET are you building with?

> .Net 4.5.2
* Describe the problem and the steps to reproduce it.

> I am trying to build the sample WiX Custom action using C#. I have created the TestCustomActions project using 'C# Custom Action Project' template in VS 2015 Community edition.

>I am not able to build it. It keeps throwing the following error -

>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(3832,5): error MSB3030: Could not copy the file "C:\TestCustomActions\obj\x86\Release\TestCustomActions.CA.dll" because it was not found.

>Looks like, unmanaged CA.dll is not getting generated. Any idea, what could be the problem?

* Describe the behavior you expected and how it differed from the actual behavior.

> TestCustomActions.CA.Dll should get generated and build should be successfull.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
