### ISSUE TITLE
Wix bundle does not give appropriate error message if WixMbaPrereqPackageId does not point to package

### ISSUE THREAD

**Issue by wldevries** [wixtoolset/issues#5505]
## Feature requests

* Describe the scenario and benefits that the feature supports.

When you accidentally make a typo or reference a PackageGroup id instead of a Package id the prerequisite will not be installed. The message you get is:
    The prerequisites were already installed. The bootstrapper application will not be reloaded to prevent an infinite loop.

* Describe how you're accomplishing the feature today (if possible).

I accomplish it today by using the correct reference, but it took me a while to figure it out until I found comments in issue #4520.

* Describe what you'd like the new feature to do.

The prerequisite bootstrapper applicationt should provide an informative error message in the log to state that the reference to the prerequisite package is invalid.

**Comment by rseanhall** [comment]
I removed `WixMbaPrereqPackageId` in wix4 when implementing `PrereqSupportPackage` in v4 - https://github.com/wixtoolset/wix4/pull/78
https://github.com/wixtoolset/issues/issues/4161
