### ISSUE TITLE
Documentation Error: OnExecutePackageBegin in IBootstrapperApplication.h 

### ISSUE THREAD

**Issue by andorz** [wixtoolset/issues#5507]
* Describe the problem and the steps to reproduce it.

> Looking at the wix v4 source code I found a wrong reference in the documentation.

* Describe the behavior you expected and how it differed from the actual behavior.

> src/burn/inc/IBootstrapperApplication.h#L423 says:
> // OnExecuteBegin - called when the engine begins executing a package.
> but the method at src/burn/inc/IBootstrapperApplication.h#L429 is
> STDMETHOD_(int, OnExecutePackageBegin)

**Comment by rseanhall** [comment]
This was fixed in https://github.com/wixtoolset/balutil/pull/15.
