### ISSUE TITLE
WiX Toolset VS2017 Extension Could not load file or assembly

### ISSUE THREAD

**Issue by mojtabakaviani** [wixtoolset/issues#5508]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveWixReferences" task could not be loaded from the assembly C:\Program Files (x86)\WiX Toolset v3.10\bin\\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	
C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix2010.targets	735

**Comment by barnson** [comment]
Do you have the WiX build tools installed? Do you have .NET 3.5.1 installed?

**Comment by mojtabakaviani** [comment]
not installed Visual Studio 2015 and .NET 3.5.1, just Visual Studio 2017

**Comment by barnson** [comment]
WiX build tools must be installed and they'll prompt for .NET 3.5.1, which is required.

**Comment by mojtabakaviani** [comment]
previous version in Visual Studio 2015 not need  .NET 3.5.1

**Comment by barnson** [comment]
It did but there was a bug in the detection. That's fixed in WiX v3.11.
