### ISSUE TITLE
Wix.CA.targets was not found

### ISSUE THREAD

**Issue by tsoftware** [wixtoolset/issues#5511]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
Wix Toolset Visual Studio 2017 Extension (3.10.3.3007 also installed)

> (WiX version in major.minor.release.build format)
Wix Toolset Visual Studio 2017 Extension (3.10.3.3007 also installed)

* Which version of Visual Studio are you building with (if any)?
2015 update 3 / 2017

> (Visual Studio version, including year and update)
2015 update 3 / 2017

* Which version of .NET are you building with?
4.5.2

> (.NET version)
4.5.2

Everything still works with Visual Studio 2015, but when I open the project with Visual studio 2017, it fails to open my C# custom action project.  The error is:

 The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Checking the directory, only wix.targets exists.

**Comment by adaptabi** [comment]
This bug also exists in VS2017

**Comment by adlangx** [comment]
Still hitting this in VS 2017 Wix 3.11

**Comment by asheeshv** [comment]
Is there any update on this? 

Thanks,
Asheesh
