### ISSUE TITLE
Managed Bootstrapper Application crashes when OnDetectCompatiblePackage is invoked

### ISSUE THREAD

**Issue by gmatzen** [wixtoolset/issues#5512]
Managed Bootstrapper Application crashes when OnDetectCompatiblePackage is invoked.  

Apparently, the Visual Studio 2017 installation registers SQL Native Client 11.3.6518.0 as a forward-compatible product to SQL Native Client 11.0.2100.60.  If your bundle includes version 11.0.2100.60 of the native client, OnDetectCompatiblePackage is invoked and your bundle will crash whether or not you actually have a handler for OnDetectCompatiblePackage.

The crash occurs because "OnDetectCompatiblePackage" is missing the "[PreserveSig]" attribute in IBootstrapperApplication.cs. 

Please find additional details in the "Bugs" section below.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2015 Update 2

* Which version of .NET are you building with?

DotNet 3.5 features are enabled.
DotNet 4.6 is installed.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
Release = 394271
Version = 4.6.01055

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

I have reproduced the crash on: 
Windows Server 2012 R2  
Windows 10

* Describe the problem and the steps to reproduce it.

When building a Managed Bootstrapper Application using 3.10.3.3007, an access violation occurs during the detect phase.  The following 2 errors appear in the application event log.

----
Application: xxxxxxxxxxx.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00C2738E
Stack:
----
Faulting application name: xxxxxxxxxxx.exe, version: 2017.1.0.358, time stamp: 0x57570038
Faulting module name: xxxxxxxxxxx.exe, version: 2017.1.0.358, time stamp: 0x57570038
Exception code: 0xc0000005
Fault offset: 0x0001738e
Faulting process id: 0xed0
Faulting application start time: 0x01d297963744585e
Faulting application path: C:\Users\pi3test\AppData\Local\Temp\{D375941F-3F77-4F5A-9AC6-FF9BD2BE19E9}\.cr\xxxxxxxxxxx.exe
Faulting module path: C:\Users\pi3test\AppData\Local\Temp\{D375941F-3F77-4F5A-9AC6-FF9BD2BE19E9}\.cr\xxxxxxxxxxx.exe
Report Id: 751e30fd-0389-11e7-811f-001dd8b73700
Faulting package full name: 
Faulting package-relative application ID: 
----

To identify the problem, I built a debug version of Burn.exe using the 3.10.3 code base and rebuilt my bundle.  Running the bundle now gave a much clearer debug assertion.

----
Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.
----

This run-time check failure occurs when the OnDetectCompatiblePackage returns.  

I reproduced this problem on Windows Server 2012 R2.
1. Start with a clean Windows Server 2012 R2 with the latest windows updates.
2. Enable DotNet 3.5 framework
3. Install SQL Server 2012
    Specifically, I chose:
    en_sql_server_2012_developer_edition_with_sp1_x64_dvd_1228540
    This above SQL server installation puts version 11.1.3000.0 of SQL Native Client on the machine.
4. Install Visual Studio 2017 RC or the released Visual Studio 2017.
5. Run a Managed Bootstrapper bundle that includes the MSI for SQL Native Client version 11.0.2100.60.  The bundle will crash.

You should see the following in the bundle log:

----
Detected compatible package: sqlncli_x64, provider: {49D665A2-4C2A-476E-9AB8-FCC425F526FC}, installed: {1385D3DB-8E80-427B-91D2-B7535862B8E4}, version: 11.3.6518.0, chained: {49D665A2-4C2A-476E-9AB8-FCC425F526FC}
----

where:
{49D665A2-4C2A-476E-9AB8-FCC425F526FC} corresponds to the product code of SQL Native Client version 11.0.2100.60
{1385D3DB-8E80-427B-91D2-B7535862B8E4} corresponds to the product code of SQL Native Client 11.3.6518.0

Note that if SQL Native Client 11.3.6518.0 or greater is installed prior to the Visual Studio 2017 installation, SQL Native Client version 11.0.2100.60 will not get registered as a forward compatible package, OnDetectCompatiblePackage will not get called, and the problem will not occur.

**Comment by gmatzen** [comment]
I am going to submit a pull request for a bug fix.

**Comment by barnson** [comment]
You need to [create a fork](https://help.github.com/articles/fork-a-repo/) and then [send a pull request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by rseanhall** [comment]
@gmatzen Thanks for volunteering to fix this. I went ahead and submitted a pull request for wix3 so it could make the RC build tonight. If you still want to contribute, we need the fix in wix4 as well.

**Comment by gmatzen** [comment]
@rseanhall Thank you for submitting the pull request for the wix3 RC build.  I just checked the wix4 branch and I don't think this same bug is in that branch.  All functions with a return value had the [PreserveSig] attribute.
