### ISSUE TITLE
Failure to load WixTasks.dll

### ISSUE THREAD

**Issue by tsoftware** [wixtoolset/issues#5513]
* Which version of WiX are you building with?
Visual Studio 2017 Extension 0.9.10.21458 / 3.10.3.3007

> (WiX version in major.minor.release.build format)
Visual Studio 2017 Extension 0.9.10.21458 / 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2015 / 2017

> (Visual Studio version, including year and update)
Visual Studio 2015 / 2017

* Which version of .NET are you building with?
4.5.2

> (.NET version)
4.5.2

After the latest build, the custom action project now loads, but fails to build properly.  I saw an earlier bug with a similar error and saw that the suggestion was to have .NET 3.5.1 installed.  It was / is installed.  The issue seems to be with missing installation files: 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\WiX Toolset v3.10\bin\WixTasks.dll
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll

They do not exist.

Additionally, the custom action can apparently no longer resolve system libraries.

The following are the errors / warnings that I receive when I attempt to build the custom action / Wix project in Visual Studio 2017; it should be noted that everything still builds fine in Visual Studio 2015 and that I have tried repairing the build tools and removing and re-installing the extension:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	TCat_Setup	C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets	39	

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'Microsoft.CSharp' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'Microsoft.Deployment.WindowsInstaller' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Xml' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Security' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Xml.Linq' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.Core' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.DirectoryServices.AccountManagement' could not be found.	TCat_CustomActions			

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component 'System.DirectoryServices' could not be found.	TCat_CustomActions			
Severity	Code	Description	Project	File	Line	Suppression State
Warning	IDE0006	Error encountered while loading the project. Some project features, such as full solution analysis for the failed project and projects that depend on it, have been disabled.	TCat_CustomActions		1	Active

**Comment by robmen** [comment]
To build managed custom actions, you'll also need the fixes in [WiX v3.11 RC](http://wixtoolset.org/releases/v3.11/rc) that *just* came out.
