### ISSUE TITLE
Wix v3.11 error - The "ReadRegistry" task could not be loaded from the assembly .....WixTasks.dll

### ISSUE THREAD

**Issue by andreibarsa** [wixtoolset/issues#5516]
Hello,

i am using:
WiX v3.11 (RC)
WiX Toolset Visual Studio 2017 Extension - installed from vs2017
VS 2017 Pro
Win 8.1 64-bit OS

I have a project build in VS 2012 with Wix3.10 and runs on .net 4.5. I wanted to build the project in vs 2017, so I uninstalled  Wix v3.10, restart pc, and then installed Wix v3.11 and the WiX Toolset Visual Studio 2017 Extension from inside vs2017. When I build the solution I receive this errors:

The "ReadRegistry" task could not be loaded from the assembly **D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll**. Could not load file or assembly 'file:///D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OPGatewayService	C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets	52	

The "ReadRegistry" task could not be loaded from the assembly **D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll**. Could not load file or assembly 'file:///D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OPGatewayService	C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets	52	

The "ReadRegistry" task could not be loaded from the assembly **D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll**. Could not load file or assembly 'file:///D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OPGInstallerCA2			

The "ReadRegistry" task could not be loaded from the assembly **D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll**. Could not load file or assembly 'file:///D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\WiX Toolset v3.10\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	OPGInstalerCA			

The WixTask.dll is located here: **C:\Program Files (x86)\WiX Toolset v3.11\bin**   
The path **D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\..\WiX Toolset v3.10\bin\WixTasks.dll** doesn't exists i have this: **D:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\WiX Toolset\v4** containig only wix.ca.targets and wix.targets

The files 
**C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets** and 
**C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix200x.targets** contains the old path with WiX **Toolset v3.10**:

` <PropertyGroup>
    <WixCATargetsPath Condition=" '$(WixCATargetsPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\wix.ca.targets</WixCATargetsPath>
    <WixTasksPath Condition=" '$(WixTasksPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\..\**WiX Toolset v3.10**\bin\WixTasks.dll</WixTasksPath>
    <WixCATargetsPath Condition=" '$(WixCATargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\wix.ca.targets</WixCATargetsPath>
    <WixTasksPath Condition=" '$(WixTasksPath)' == '' ">$(MSBuildExtensionsPath)\..\**WiX Toolset v3.10**\bin\WixTasks.dll</WixTasksPath>
    <TargetCAFileName Condition=" '$(TargetCAFileName)' == '' ">$(TargetName).CA$(TargetExt)</TargetCAFileName>
  </PropertyGroup>`

**Comment by robmen** [comment]
Try removing `C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets` and `C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix200x.targets` the repair WiX v3.11 RC.

This can happen if those files were modified. If you want to root cause the issue, would need to look at the all the upgrade logs for WiX v3.11.

**Comment by andreibarsa** [comment]
Thank you for your quick response.

After repair and update to v3.11.0.129 it is working.

**Comment by FrenzelThomas** [comment]
Hi @Cheranmasi, where you able to resolve this issue? I am migrating from one azure devops server/agent to another. In the new Environment I encountered this problem.

**Comment by Cheranmasi** [comment]
I upgraded to version4 then it works
