### ISSUE TITLE
InstallValidate Hang: Files In Use Dialog Not Appearing

### ISSUE THREAD

**Issue by jasmineanderson** [wixtoolset/issues#5517]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
v3.10.3.3007

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2015

* Which version of .NET are you building with?
.NET Framework 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 8.1 and Windows 10 

* Describe the problem and the steps to reproduce it.
During an upgrade (previous version running and Word document open), install hangs at "validating install" and eventually does not respond. If I click cancel on the installer, the Files in Use dialog appears. I select to close the applications using the files and attempt to restart them, the install continues and is successfully installed. 

MSIRESTARTMANAGERCONTROL is set to disabled. 

Snippet from the logs (last entries): 
Info 1603. The file C:\Program Files\Citrix\ShareFile\Sync\libSFSyncEngine.dll is being held in use by the following process: Name: explorer, Id: 4920, Window Title: '(not determined yet)'. Close that application and retry.
Info 1603. The file C:\Program Files\Citrix\ShareFile\Sync\libSFSyncEngine.dll is being held in use by the following process: Name: WINWORD, Id: 3960, Window Title: '(not determined yet)'. Close that application and retry.
Info 1603. The file C:\Program Files\Citrix\ShareFile\Sync\libSFIPC.dll is being held in use by the following process: Name: explorer, Id: 4920, Window Title: '(not determined yet)'. Close that application and retry.
Info 1603. The file C:\Program Files\Citrix\ShareFile\Sync\libSFIPC.dll is being held in use by the following process: Name: WINWORD, Id: 3960, Window Title: '(not determined yet)'. Close that application and retry.
Info 1603. The file C:\Program Files\Citrix\ShareFile\Sync\ShareFileExplorerExt64.dll is being held in use by the following process: Name: explorer, Id: 4920, Window Title: '(not determined yet)'. Close that application and retry.
Info 1603. The file C:\Program Files\Citrix\ShareFile\Sync\ShareFileExplorerExt64.dll is being held in use by the following process: Name: WINWORD, Id: 3960, Window Title: '(not determined yet)'. Close that application and retry.
MSI (s) (3C:10) [08:55:57:676]: 1 application(s) had been reported to have files in use.

* Describe the behavior you expected and how it differed from the actual behavior.
Expecting no hang at "validating install" and I'm also expecting the Files in Use dialog to appear as soon as the install recognizes files are in use, NOT after attempting to cancel the install. 

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by rseanhall** [comment]
Sounds like a duplicate of https://github.com/wixtoolset/issues/issues/4831, try the WiX v3.11 RC.

**Comment by jasmineanderson** [comment]
That fixed it, thank you very much!

**Comment by chenggj** [comment]
@jasmineanderson  Could you share your solution about this issue?
I miss the same problem now. 
And in fact, any of the applications in the filesinuse dialog doesn't use  my installation file.
I don't know why the installation thinks they are.
