### ISSUE TITLE
VS 2017 WiX v3 New C# CustomAction Project does not compile

### ISSUE THREAD

**Issue by zsomogyibe** [wixtoolset/issues#5518]
When I start a new C# CustomAction Project by using WiX v3 the project I get does not compile (error).

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

3.11.0.1501

* Which version of Visual Studio are you building with (if any)?

VS 2017 last version + WiX Toolset Visual Studio 2017 Extension 0.9.10.21458

* Which version of .NET are you building with?

Any version

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

N/A

* Describe the problem and the steps to reproduce it.

When I start a new C# CustomAction Project in VS 2017 by using WiX v3 the project I get does not compile (error) and the References are shown with a yellow triangle and '!' (problem with the references).
When I compile the project I get the following error messages:

1. Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ReadRegistry" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\..\WiX Toolset v3.11\bin\WixTasks.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\WiX Toolset v3.11\bin\WixTasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	CustomAction1			
Severity	Code	Description	Project	File	Line	Suppression State

2. Warning		The referenced component 'Microsoft.CSharp' could not be found.	CustomAction1			
3. Warning		The referenced component 'System.Xml.Linq' could not be found.	CustomAction1			
4. Warning		The referenced component 'System.Core' could not be found.	CustomAction1			
5. Warning		The referenced component 'Microsoft.Deployment.WindowsInstaller' could not be found.	CustomAction1			
6. Warning		The referenced component 'System.Xml' could not be found.	CustomAction1			
7. Warning		The referenced component 'System' could not be found.	CustomAction1			

* Describe the behavior you expected and how it differed from the actual behavior.

I expect that the project compiles without errors and that I can build a custom action dll.

**Comment by barnson** [comment]
Fixed in v3.11.0.1507.

**Comment by zsomogyibe** [comment]
Thank you very much! Tested and it works now!
