### ISSUE TITLE
VS 2017 plugin toolset -> tool settings error under properties page

### ISSUE THREAD

**Issue by bbuerger** [wixtoolset/issues#5519]
* Which version of WiX are you building with?

> 3.11.0.1507

* Which version of Visual Studio are you building with (if any)?

> VS 2017 Enterprise

* Which version of .NET are you building with?

> 4.5.2
* Describe the problem and the steps to reproduce it.

> Open the wixproj properties page in VS 2017
Click under the Paths item (used to be Tool Settings, now invisible)

* Describe the behavior you expected and how it differed from the actual behavior.

> The tool settings page should appear, but the following error is shown:
Class not registered.
Looking for object with CLSID: {37DA98B6-C5F4-4CE6-867F-553EBE590ABE}.

**Comment by prof79** [comment]
Same here, and if you go through the registry cleaning some VS 14.0 config keys that reference aforementioned CLSID and votive2010.dll you'll end up with a new message on that invisible page in VS 2017 (even after Votive uninstall/re-install):

"An error occurred trying to load the page.
Unable to create the designer.  File is already opened in an incompatible editor."

(I had VS 2015 Community on my machine before, already uninstalled)

WiX Toolset 4.0.0.4506
Votive 2017 0.9.10.21458
Microsoft Visual Studio Community 2017
Version 15.0.26228.9 D15RTWSVC
Microsoft .NET Framework
Version 4.6.01586

**Comment by crr0004** [comment]
To get around this issue for including paths, I've put
```
<LinkerBindInputPaths>
	path1;path2
</LinkerBindInputPaths>
```

Under a <PropertyGroup> in the wixproj file.
