### ISSUE TITLE
.net 4.5.2

### ISSUE THREAD

**Issue by Pippin555** [wixtoolset/issues#5520]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by Pippin555** [comment]
I upgraded on two PCs to Wix 3.11.0.1507 and now Visual Studio shows a message that the wix projects are incompatible.
![capture_0008](https://cloud.githubusercontent.com/assets/10798392/23800322/38f63998-05ac-11e7-9f43-0a168c02726d.jpg)
One PC is Windows 7 and VS2015 Enterprise 14.0.25431.01 Update 3
The other PC is Windows 10 VS2015 Community version.
when i try to re-install wix I get the message that wix and .net 4.5.2 do not go together and that it is advised to install windows 7 SP 1 (even on the windows 10 pc)
Downgrading to 3.11.1307 or 3.10 does not help, same error

**Comment by rseanhall** [comment]
Starting with WiX 3.11.0.1501, the Visual Studio integration has been pulled out of the installer. You need to get the WiX extension from [VS Marketplace](https://marketplace.visualstudio.com/vsgallery/d4dbda5a-8bce-4a09-8a06-afd1afd006e0) or from the Extensions UI in VS itself.

For the message that wix and .net 4.5.2 do not go together on Win10, please upload the WiX installer log file from the %TEMP% directory.

**Comment by Pippin555** [comment]
thank you for the prompt answer
[WiX Toolset_v3.11.0.1507_20170310170556.log.txt](https://github.com/wixtoolset/issues/files/834467/WiX.Toolset_v3.11.0.1507_20170310170556.log.txt)

**Comment by rseanhall** [comment]
That log says that it was running on Windows 7 (no service pack). This error is expected in this case. I thought you said it was running on Windows 10? Please upload the log from the Windows 10 machine.

>[0268:0C54][2017-03-10T17:05:56]i001: Burn v3.11.0.1507, Windows v6.1 (Build 7600: Service Pack 0)

**Comment by Pippin555** [comment]
I have installed the Wix extension (0.9.10.21458) and Visual Studio still maintains that the wix project is not compatible. When reloading the project the fle Wix.targets is missing and the system tells me that that import is possibly not correct. This is the 'value' of Wix.Targets 
$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets
Do I need to upgrade the wix project in some way?

**Comment by rseanhall** [comment]
Please ask your question about WiX projects not working in Visual Studio with the latest extension on the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/). This functionality should be working, and we don't provide support here on github because that mailing list is where we have always provided support (before github existed). It will help to provide the part of your .wixproj file that imports the wix.targets.

**Comment by Pippin555** [comment]
![mypc](https://cloud.githubusercontent.com/assets/10798392/23803510/10d6d3c2-05b7-11e7-93fa-c0563c29ea72.png)

This is the configuration of my PC and I am really runing Windows 10. I also tried wix 4.0 and it correctly mentions that it is installing on windows 10
[1D5C:3570][2017-03-10T16:54:04]i001: Burn v4.0.0.4506, Windows v10.0 (Build 14393: Service Pack 0), path: C:\ProgramData\Package Cache\{b68fa123-a2ee-4373-966b-05bca25f4c42}\WiX40.exe
[1D5C:3570][2017-03-10T16:54:04]i000: Initializing string variable 'InstallFolder' to value '[ProgramFilesFolder]WiX Toolset v4.0'

**Comment by rseanhall** [comment]
You must be running the WiX v3.11 installer in compatibility mode then.

**Comment by Pippin555** [comment]
I did nothing special, but I may have started the program from Total Commander, not aware of the environment that was passed to the installer.

**Comment by Pippin555** [comment]
I will post to the wix-users mailing list, thank you for your effort
