### ISSUE TITLE
.NET 3.5 prerequisite

### ISSUE THREAD

**Issue by demidov71** [wixtoolset/issues#5523]
WiX version 3.11 installer now checks for .NET framework 3.5. Actually it needs a single DLL, which can be added manually into GAC, so the OS can be left clean from the old garbage. How can it be installed without .NET 3.5 Windows feature?

**Comment by niemyjski** [comment]
I just got this as well, I run Windows 10 in a vm and I do not want to install .NET 3.5 as it's no longer supported by MS

**Comment by demidov71** [comment]
I’ve found a fix. Set those registry entries:

 



 

Install WiX 3.11 and then delete them.

**Comment by demidov71** [comment]
I've got a fix:
1. Set registry values under HKLM\SOFTWARE\WOW6432Node\Microsoft\NET Framework Setup\NDP\v3.5
    Install DWORD 1
    SP DWORD 1
    Version STRING 3.5.30729.4926
2. Install WiX 3.11
3. Remove the above registry key.
4. Put Microsoft.Build.Utilities.dll from .NET 3.5 into GAC (GACUtil /if "path\Microsoft.Build.Utilities.dll")

**Comment by barnson** [comment]
.NET 3.5.1 is still supported and we can't redistribute a file that isn't redistributable by license.

**Comment by robmen** [comment]
Also, the .NET v3.5 dependency is planned to be removed in v3.14.

**Comment by demidov71** [comment]
The whole thing evolves so slowly, that I probably won't see this Pi version in my life time.

**Comment by niemyjski** [comment]
@robmen can this be moved into 3.11? I'm kinda blocked as I don't want to mess up my dev vm by installing .NET 3.5 (trying to mimic exactly what's in production in my dev vm). It would be nice if the builds were tested against fresh windows 10 vms (if it can't be installed out of the box then it's kind of a usability issue).

**Comment by robmen** [comment]
This isn't a new requirement. It's just we weren't blocking the install in the past and people were opening bugs because the WiX v3.x requires .NET Framework v3.5 is some cases.

@niemyjski, are you asking that we bring back the broken behavior because it works for you in your use cases?

**Comment by niemyjski** [comment]
I think it works for everyone and is a known issue :), I don't think to
many people are installing v3.5 anymore and if they are (rebuilding a box)
they should be aware of this / look at the issues / install .net 3.5 and
patches first)

Thanks
-Blake Niemyjski

**Comment by demidov71** [comment]
I would agree with Rob, except when going to upgrade to VS 2017 (as myself). Only WiX version 3.11 can be integrated into VS 2017 (unless I'm wrong). So this check for .NET 3.5 prevents the upgrade... But there is a simple fix. See above.

**Comment by barnson** [comment]
We added the check because otherwise the WiX tasks fail until we drop MSBuild 3.5 support.

**Comment by YoannNicod** [comment]
WiX, an installation toolset which has an installer unable to run properly without an old garbage .NET framework, very encouraging. I'm going to look for an other toolset because I feel like this is only the beginning of the problems I will encounter with it.

**Comment by robmen** [comment]
@YoannNicod removing the .NET Framework v3.5 dependency is a breaking change. WiX v3.14 is the first v3.x release that removes the dependency. You can try that out.

**Comment by StephenDrewLDS** [comment]
> So as long as you don't fall off the Earth in the next month or so, you'll see it. 😄

I didn't see this (v3.14) on the release page.  Is there an ETA?

**Comment by rohitlodha** [comment]
@StephenDrewLDS Where do I find weekly releases? The website weekly releases isn't updated. http://wixtoolset.org/releases/weekly/

**Comment by robmen** [comment]
@rohitlodha there was an issue in the last publishing of wixtoolset.org. The weekly releases page has been fixed.

**Comment by robertofelgin** [comment]
When is 3.14 being officially released?

**Comment by robmen** [comment]
With WiX v4. The WiX v4 date is not solid yet.

**Comment by robertofelgin** [comment]
I'm specifically asking about v3.14, not v4. I see that there is a weekly build now of v3.14 but I need a production ready build that has this fix.

**Comment by robmen** [comment]
I understood. Again, WiX v3.14 will be declared stable on the same schedule as WiX v4.0. Weekly builds are what are available at this time.

If you want commercial support to meet your business demands, there are options for that. Otherwise, you can participate in the community with us to meet our goals here faster.

**Comment by natemcmaster** [comment]
Any chance you would be willing to push 3.14 to https://www.nuget.org/packages/WiX as a pre-release? NuGet.org already has some 4.0 pre-release packages, and I would love to unblock this issue for my team.

**Comment by peterbernier** [comment]
Could we get an update on when or whether we can expect to see a production-ready release product that contains this fix?

Our installers are currently stuck with a legacy 3.5 requirement (for the installer only) as a result of this issue.

**Comment by BMurri** [comment]
It's only the building of the installers using the WiX-provided MSBuild wixproj templates/wix*.targets files that drives any 3.5 requirement.

**Comment by peterbernier** [comment]
@BMurri  That doesn't match the behaviour that I'm seeing. Trying to run an installer (built on a machine with 3.5) in a clean Windows 10 environment still gives me the 'This setup requires the .NET Framework version 3.5.' message.

Based on https://www.firegiant.com/blog/2017/3/14/wix-online-meeting-123-highlights/ it seems like this won't be resolved until WiX 3.14 comes out, so I think that asking for an update or ETA on when that will be released is reasonable.

**Comment by BMurri** [comment]
Installers created with the WiX toolset are packages that consist of some combination of Windows Installer packages (that have no managed code unless that code is supplied by you) and completely native code (supplied custom actions and the bootstrapper).

Any managed code in your installers came from you, and that managed code is the source of your installers. I build installers all the time that do not require any version of .NET and work on machines that have no 3.5, others that have no 4.x, and even (abet older) servers that have no .NET at all.

The page you reference has to do with the 3.5 requirement to build installers.

Please ask for help on wix-users if you feel your built installers should not have a dependency on 3.5. In all likelihood, it's a misconfiguration on your part.

**Comment by robmen** [comment]
@peterbernier that sort of dependency is controlled by your code. The WiX Toolset will not add anything to your installation package that requires any particular version of .NET Framework. Of course, you can write a BA or a CA that requires a particular .NET Framework.

The WiX Toolset build tools themselves do still require .NET Framework v3.5 so your build machine needs .NET Framework v3.5.

In the end, discussions should happen on wix-users mailing list.

**Comment by robe070** [comment]
We have hundreds of customers using 3.10 worldwide on all sorts of configurations and they all work.  So whatever the dependency is, its not relevant to our usage. Its a shame the dependency was not made optional. Default to require it and allow it to be unchecked so those users who don't require it may install the security fixes. (We don't use Visual Studio to run WiX. We directly run WiX)

**Comment by IanKemp** [comment]
3.14 / 4.0 when, if ever?

**Comment by robmen** [comment]
v4.0.

**Comment by zwass** [comment]
The registry entry fix is a godsend, but amazing that this issue persists years later.
