### ISSUE TITLE
-srd "Suppress harvesting the root directory as an element" does not work

### ISSUE THREAD

**Issue by Djutza** [wixtoolset/issues#5524]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
 0.9.10.21458 - Visual Studio 2017 Extension

* Which version of Visual Studio are you building with (if any)?
VS2017, 15.0.26228.

* Which version of .NET are you building with?
4.5

* Describe the problem and the steps to reproduce it.
**heat.exe** parameter **-srd** does not exclude root directory. Output .wxs file is same with and without **-srd**.

* Describe the behavior you expected and how it differed from the actual behavior.
It suppress harvesting the root directory in VS 2013 extension, but in VS 2017 does not.

**Comment by barnson** [comment]
Which version of the WiX build tools (not the VS extension)?

**Comment by Djutza** [comment]
I checked with both v3.10.3.3007 and 3.11.0.1507. In VS2013 works with both versions, in VS2017 does not.

**Comment by robmen** [comment]
Can you provide more details about how you are calling `heat.exe` in VS2013 that works and how it does not work in VS2017? The VS integration shouldn't change `heat.exe` behavior so it isn't at all clear at this time what you've done.

**Comment by Djutza** [comment]
It is not clear to me either. I open project in VS2013, build - it is ok. Close VS2013, open same project in VS2017, build fails.
For example -gg option works just fine.
Here is how it is called:
"call  &quot;%25WIX%25bin\heat.exe&quot; dir &quot;$(SolutionDir)ServiceModel\SelfHosting\SelfHosting.Implementation\bin\$(PlatformName)\$(ConfigurationName)&quot; -dr APPLICATIONFOLDER -cg ServiceModel.SelfHostingGroup -gg -scom -sreg -sfrag –srd -var &quot;var.ServiceModel.SelfHosting.Implementation.TargetDir&quot; -out &quot;$(ProjectDir)SelfHosting.wxs&quot;  -t &quot;$(SolutionDir)..\scripts\wix\Services.xslt&quot;"

**Comment by barnson** [comment]
Can you double-check the command line that `–srd` has a dash and not a hyphen?

**Comment by Djutza** [comment]
Thanks. That hyphen is there for years.
