### ISSUE TITLE
Website content is duplicated in IIS Manager

### ISSUE THREAD

**Issue by raja1985** [wixtoolset/issues#5526]
![unnamed](https://cloud.githubusercontent.com/assets/4569281/23896064/fe5f0b82-08cd-11e7-9a91-04da3cb3f6ea.png)
`Please` provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

` <DirectoryRef Id="MyAccount.UI.Web.West_1" >
      <Component Id="MyAccountVirDir" Guid="B1FE96B8-03DC-11E7-92F6-B6C263EDCBF1" KeyPath="yes">
        
        <iis:WebSite Id="DemoWebsiteWebsite" Description="[MYACCOUNT_WEB_SITE]" Directory="MyAccount.UI.Web.West_1">
          <iis:WebAddress Id="AllUnassigned" Port="80" />
          <iis:WebVirtualDir Id="MyAccount.WebVirtualDir" Alias="[MYACCOUNT_VDIR_NAME]" Directory="MyAccount.UI.Web.West_1" >
          <iis:WebApplication Id="DemoWebsiteApplication"  Name="[MYACCOUNT_VDIR_NAME]" WebAppPool="MyAccount_WebAppPool"/>
            <iis:WebDirProperties Id="MyAccountprop" Read="yes" Write="no" DefaultDocuments="Global.asax" Script="yes" Execute="yes" AnonymousAccess="yes" />
          </iis:WebVirtualDir>
        </iis:WebSite>
      </Component>
 <Component Id="MyAccountAppPool" Guid="{BFEDA6E2-03DC-11E7-A754-BDC263EDCBF1}" KeyPath="yes" >
        <iis:WebAppPool Id="MyAccount_WebAppPool" Name="[MYACCOUNT_APPPOOL_NAME]" ManagedPipelineMode="classic" ManagedRuntimeVersion="v4.0" />
      </Component>
      </DirectoryRef>`

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
