### ISSUE TITLE
Sign the vsix packages

### ISSUE THREAD

**Issue by andorz** [wixtoolset/issues#5528]
If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> the user feals more comfortable that he selected the right extension from the marketplace

* Describe how you're accomplishing the feature today (if possible).

> at the moment you see that it is not signed.
> ![vsix_sign](https://cloud.githubusercontent.com/assets/20229016/23957553/fa5c888e-099f-11e7-82de-5ab5c85a7c16.jpg)

* Describe what you'd like the new feature to do.

> show that the extension that will be installed belongs to the wix toolset (.NET Foundation)

**Comment by robmen** [comment]
Thanks for cleanly filling out the template. This is something I'd like to implement so thank you for the issue tracking it.

**Comment by robmen** [comment]
This was done at least a few releases ago.
