### ISSUE TITLE
WiX Toolset VS2017 Extension New Project Templates

### ISSUE THREAD

**Issue by eteeuw-groeneveld** [wixtoolset/issues#5531]
After installing the WiX Toolset Visual Studio 2017 Extension, there seems to be some duplicate project templates installed. The additional Wix key with 1033 sub keys seems redundant.

![image](https://cloud.githubusercontent.com/assets/17176297/23987722/352d73f2-0a2b-11e7-98fc-e5b55fa6932f.png)

* Which version of WiX are you building with?

3.11.0.1507

* Which version of Visual Studio are you building with (if any)?

Visual Studio Professional 2017

* Which version of .NET are you building with?

4.0

**Comment by robmen** [comment]
Yeah, known issue with unknown solution at this time.

**Comment by iswix-llc** [comment]
I compress my ISWIX templates as .ZIP files and deploy with my extensions.  In doing so I don't see this behavior.  I supsect if you do the same it'll work for you too.

**Comment by robmen** [comment]
Fixed by wixtoolset/VisualStudioExtension@159ed57da4a38e1422b6df48a70b63ab6eb9e804
