### ISSUE TITLE
Error updating from wix 3.0 to wix 3.6

### ISSUE THREAD

**Issue by andreibarsa** [wixtoolset/issues#5532]
Hi,

I have an old app build with vs2008 and wix 3.0 and .net 3.0.
I want to update the.net framework of the app to ver 4.5.

Because I use vs2012 to do the upgrade, I saw that wix 3.6 is the common version supported by VS2008 and VS2012.

VS2008 failed to proper convert the project to wix 3.6. In order to be able to open the project I manually replaced 3.0 with 3.x in the paths in the wixproj file.

    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' AND '$(MSBuildExtensionsPath32)' != '' ">$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>
    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.targets</WixTargetsPath>

Build the project with vs2008 and wix 3.6 on a win 10 machine I receive this error:

Error	8	System.TypeLoadException: Method 'ProcessMessage' in type 'VismaUpdate.ClientSetup.UI.VPMClientSetupUI' from assembly 'VismaUpdate.ClientSetup.UI, Version=1.0.6284.22138, Culture=neutral, PublicKeyToken=null' does not have an implementation.	C:\VismaUpdate2\branch\2.3RC2\Setup\VismaUpdate.ClientSetupUI\EXEC	VismaUpdate.ClientSetupUI

Error	9	The command ""C:\Program Files\WiX Toolset v3.6\bin\..\sdk\MakeSfxCA.exe" "C:\VismaUpdate2\branch\2.3RC2\Setup\VismaUpdate.ClientSetupUI\obj\x86\Release\VismaUpdate.ClientSetup.UI.CA.dll" "C:\Program Files\WiX Toolset v3.6\bin\..\sdk\x86\SfxCA.dll" "C:\VismaUpdate2\branch\2.3RC2\Setup\VismaUpdate.ClientSetupUI\obj\x86\Release\VismaUpdate.ClientSetup.UI.dll" "C:\Program Files\WiX Toolset v3.6\SDK\Microsoft.Deployment.WindowsInstaller.dll;..\..\References\ForEmbeddeUICustomAction\Visma.Core.Deployment.Target-YYYYMM.dll;..\..\References\ForEmbeddeUICustomAction\Visma.Core.Globalization-YYYYMM.dll;..\..\References\Visma.Core-201004.dll;..\..\References\Visma.Services.Installer.EmbeddedUI.Base.dll;..\..\References\Visma.Services.Installer.EmbeddedUI.dll;..\..\References\Visma.Services.Installer.EmbeddedUI.StandardPages.dll;C:\VismaUpdate2\branch\2.3RC2\VismaUpdate.Lib\bin\Release\Visma.Services.VismaUpdate.Lib.dll;..\..\References\Visma.Core.Globalization-201004.dll;C:\VismaUpdate2\branch\2.3RC2\VismaUpdate.Lib\bin\Release\Visma.Services.VismaUpdate.ClientLibrary.dll;..\..\References\ForEmbeddeUICustomAction\Visma.Core-YYYYMM.dll;C:\VismaUpdate2\branch\2.3RC2\Setup\VismaUpdate.ClientSetupUI\CustomAction.config"" exited with code 1.	VismaUpdate.ClientSetupUI

The same error I get also building the project with VS2012 and wix 3.6 on a win 7 machine.
I also tried and changed in the project .net ver to 4.5 on the win 7 machine and build with VS2012 and I have the same error.

Any suggestion?

Thank you

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
