### ISSUE TITLE
Project reference variable TargetPath contains multiple items for v141 C++ projects

### ISSUE THREAD

**Issue by tsoftware** [wixtoolset/issues#5535]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
Wix Toolset Visual Studio 2017 Extension / WiX 3.11.0.1507

> (WiX version in major.minor.release.build format)
Wix Toolset Visual Studio 2017 Extension / WiX 3.11.0.1507

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2017 26228.9

> (Visual Studio version, including year and update)
Visual Studio 2017 26228.9

* Which version of .NET are you building with?
4.6.01586

> (.NET version)
4.6.01586

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

> (Windows version)
Windows 10 Anniversary

* Describe the problem and the steps to reproduce it.
Visual C++ targets (dll and exe) originally created with Visual Studio 2015.  Upgraded Platform Toolset from v140 to v141.  This was done because it is causing issues with unit tests in debug mode for some reason.  After upgrade, Wix compile indicates that it cannot find DLL or EXE targets.  Checked specified directories and assemblies exist.  Revert back to v140 and everything compiles fine.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.
Expect installer to build, it does not.

> (Be as specific as you can and err on the side of providing too much information.)

**Comment by barnson** [comment]
What are "targets"? Please provide the exact error messages.

**Comment by tsoftware** [comment]
All files that are not found are C++ assemblies and they exist in the specified directory.

Severity	Code	Description	Project	File	Line	Suppression State
Error		The system cannot find the file 'C:\Users\xxx\Code\xxx\IAS\Release\xxxFilter.dll;C:\Users\xxx\Code\xxx\IAS\Release\xxxFilter.dll'.	xxxFilter-x86_Setup	C:\Users\xxx\Code\xxx\IAS\xxxFilter-x86_Setup\xxxFilter.wxs	8	
Error		The system cannot find the file 'C:\Users\xxx\Code\xxx\IAS\Release\xxxTest.exe;C:\Users\xxx\Code\xxx\IAS\Release\xxxTest.exe'.	xxxFilter-x86_Setup	C:\Users\xxx\Code\xxx\IAS\xxxFilter-x86_Setup\xxxTest.wxs	8	
Error		The system cannot find the file 'C:\Users\xxx\Code\xxx\IAS\x64\Release\xxxFilter.dll;C:\Users\xxx\Code\xxx\IAS\x64\Release\xxxFilter.dll'.	xxxFilter_Setup	C:\Users\xxx\Code\xxx\IAS\xxxFilter_Setup\xxxFilter.wxs	9	
Error		The system cannot find the file 'C:\Users\xxx\Code\xxx\IAS\x64\Release\xxxTest.exe;C:\Users\xxx\Code\xxx\IAS\x64\Release\xxxTest.exe'.	xxxFilter_Setup	C:\Users\xxx\Code\xxx\IAS\xxxFilter_Setup\xxxTest.wxs	9

**Comment by barnson** [comment]
How are you referring to the files in WiX authoring?

**Comment by tsoftware** [comment]
They all work perfectly fine, as long as the C++ platform tools are not increased to v141.  I will provide a sample of one of the files, as the rest are referenced similarly.

<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
 <Fragment>
  <DirectoryRef Id="System64Folder"
                DiskId="1">
   <Component Id="xxxFilter.Library"
              Guid="*"
              Win64="yes">
    <File Id="$(var.xxxFilter.TargetFileName)"
          Name="$(var.xxxFilter.TargetFileName)"
          Source="$(var.xxxFilter.TargetPath)"
          KeyPath="yes"/>
   </Component>
  </DirectoryRef>
 </Fragment>
</Wix>

**Comment by tsoftware** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
 <Fragment>
  <DirectoryRef Id="System64Folder"
                DiskId="1">
   <Component Id="xxxFilter.Library"
              Guid="*"
              Win64="yes">
    <File Id="$(var.xxxFilter.TargetFileName)"
          Name="$(var.xxxFilter.TargetFileName)"
          Source="$(var.xxxFilter.TargetPath)"
          KeyPath="yes"/>
   </Component>
  </DirectoryRef>
 </Fragment>
</Wix>

**Comment by tsoftware** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
 <Fragment>
  <DirectoryRef Id="System64Folder"
                DiskId="1">
   <Component Id="xxxFilter.Library"
              Guid="*"
              Win64="yes">
    <File Id="$(var.xxxFilter.TargetFileName)"
          Name="$(var.xxxFilter.TargetFileName)"
          Source="$(var.xxxFilter.TargetPath)"
          KeyPath="yes"/>
   </Component>
  </DirectoryRef>
 </Fragment>
</Wix>`

**Comment by eteeuw-groeneveld** [comment]
I have a possible related issue where $(var.Project.TargetDir) for a C++ referenced project no longer includes a trailing backslash.

I'm using the same tooling. And also upgraded from v140 to v141.

**Comment by barnson** [comment]
@eteeuw-groeneveld, please open a separate issue so we can track them.

**Comment by eteeuw-groeneveld** [comment]
OK, see #5537.

**Comment by mikecousins** [comment]
Yup, this one just bit me too.

**Comment by rar222** [comment]
Yes, also noticed this one.

<File Id="fileIdX" KeyPath="yes"  Source="$(var.Project.TargetPath)" />

Produced a

error LGHT0103: The system cannot find the file 'C:\Path\To\Src\Output\Release\Project.exe;C:\Path\To\Src\Output\Release\Project.exe;'

My workaround is to use this instead

<File Id="fileIdX" KeyPath="yes"  Source="$(var.Project.TargetDir)\$(var.Project.TargetFileName)" />
