### ISSUE TITLE
C++ Custom Action project template and SDK files missing

### ISSUE THREAD

**Issue by eteeuw-groeneveld** [wixtoolset/issues#5536]
The C++ custom action project template is missing. Further, the C++ library and header files are no longer installed.

* Which version of WiX are you building with?

3.11.0.1507

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2017 Professional

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 Enterprise Anniversary Update (64-bit)

* Describe the problem and the steps to reproduce it.

Install Wix 3.11 RC Toolset and VS 2017 Extension. Open VS and choose new Project. The C++ custom action is missing.
Open a C++ custom action project created with VS 2015. The header and library files cannot be found.

* Describe the behavior you expected and how it differed from the actual behavior.

Include the C++ custom action project template. Install header and library files to C:\Program Files (x86)\WiX Toolset v3.11\SDK\VS2017\inc and C:\Program Files (x86)\WiX Toolset v3.11\SDK\VS2017\lib resp.

**Comment by robmen** [comment]
Yes, unfinished work item.
