### ISSUE TITLE
Project reference variable TargetDir is missing trailing backslash for C++ projects

### ISSUE THREAD

**Issue by eteeuw-groeneveld** [wixtoolset/issues#5537]
When referencing a C++ project in a Setup project and using the TargetDir project reference variable, $(var.Project.TargetDir), the returned path no longer includes the trailing backslash as it used to be with WiX 3.10.3 and VS2015.

* Which version of WiX are you building with?

3.11.0.1507

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2017 Professional

* Describe the problem and the steps to reproduce it.

I've upgraded from WiX 3.10.3 and VS2015 to WiX 3.11 RC and VS2017. The referenced C++ projects platform toolset has been upgraded from v140 to v141. The $(var.Project.TargetDir) no longer has a traling backslash for a referenced C++ project.

* Describe the behavior you expected and how it differed from the actual behavior.

The returned value for $(var.Project.TargetDir) should include a trailing backslash.

**Comment by robmen** [comment]
Fixed by https://github.com/wixtoolset/wix3/commit/00057695cf60c701ca32a6b21bbdbe438a240e1c
