### ISSUE TITLE
Add Copyright (WixBundleCopyright) built-in variable for bundle

### ISSUE THREAD

**Issue by kovalikp** [wixtoolset/issues#5542]
Can you please add "WixBundleCopyright" build-it variable for bundle? I have a need to display copyright notice in custom bootstrapper UI. It would be convenient  if I wouldn't have to define custom variable, but use value from Bundle/@Copyright instead.

**Comment by barnson** [comment]
You can add a `Variable` with the same loc string used in Bundle/@Copyright. Otherwise, we want to avoid adding unnecessary "magic variables."
