### ISSUE TITLE
wix311.exe says "WiX Toolset requires the .NET Framework 3.5.1 Windows feature to be enabled."

### ISSUE THREAD

**Issue by JVimes** [wixtoolset/issues#5545]
## Bugs

* Which version of WiX are you building with?

> 3.11.0.1507

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> 4.6.2 (modern Windows 10 default)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.
> Wix 3.11 RC won't install on a system that 3.10 will install on, citing a need for a very old .NET version.
> 1. Go to http://wixtoolset.org/releases/
> 2. Click "Download WiX v3.11 RC"
> 3. Run the download (wix311.exe) on Windows 10. Apparently a Windows 10 environment without the .NET 3.5.1 feature enabled (which is the default, I believe).

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected: wix311.exe installs fine. After all, 3.10 installs fine on the same machine.
> Actual: I get a dialog saying "WiX Toolset requires the .NET Framework 3.5.1 Windows feature to be enabled."

**Comment by barnson** [comment]
WiX v3.10 would install but fail at runtime without .NET 3.5.1. So we enforce the requirement up-front now.

**Comment by JVimes** [comment]
Really? v3.10 ran fine for me without .NET 3.5.1. I'm trying to install it now (getting error codes enabling the OS feature). Maybe I didn't use whatever tool needed .NET 3x.

**Comment by JVimes** [comment]
I guess I'll close this ¯\_(ツ)_/¯

**Comment by barnson** [comment]
The WiX MSBuild tasks referenced MSBuild v3.5 assemblies.

**Comment by FabienD31** [comment]
HI, I want to use WiX to create a file .msi but i have this error "WiX Toolset requires the .NET Framework 3.5.1 Windows feature to be enabled" 
I don't use Visual studio but VSC with Electron/vueJs ans Node. 
Do you think it's possible to use WiX without .NET Framework ?
