### ISSUE TITLE
WiX Burn leaves del*.tmp in temp directory

### ISSUE THREAD

**Issue by leshy84** [wixtoolset/issues#5548]
* Which version of WiX are you building with?

3.11.0.1507

* Describe the problem and the steps to reproduce it.

Reproduction:
1. Ensure UAC is enabled.
2. Run any .NET based setup bootstrapper application, e.g. wix311.exe setup itself, without "run as administrator" .
3. Close the setup application.

Actual results:
new del*.tmp in temp folder and they are not removed after system restart.

Expected results:
no new files in temp folder.

The problem is in DirEnsureDeleteEx function (libs\dutil\dirutil.cpp), which is called from UserExperienceRemove function (burn\engine\userexperience.cpp):

```
// Try to move the file to the temp directory then schedule for delete,
// otherwise just schedule for delete.
if (::MoveFileExW(sczDelete, wzTempPath, MOVEFILE_REPLACE_EXISTING))
{
    ::MoveFileExW(wzTempPath, NULL, MOVEFILE_DELAY_UNTIL_REBOOT);
}
```

According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365240(v=vs.85).aspx) the last method should be called only in the context of a user who belongs to the administrators group or the LocalSystem account.
So it just cannot schedule the delete operation (access denied error)

**Comment by robmen** [comment]
That code is all best effort in the case the file can't be deleted (because it is in use). Curious if you have a better suggestion?

**Comment by leshy84** [comment]
Hi Rob,
only Burn itself locks the files.
So the solution should be to unlock the files before trying to remove them.
It seems app domain should be already unloaded before calling UserExperienceRemove().

**Comment by robmen** [comment]
Fantastic! If you can get that working, we'd love to see the solution in WiX v4 where our focus will be going forward.

**Comment by leshy84** [comment]
Hi Rob,
what's wrong with the unloading of the app domain?
I've just made such modifications in ext\BalExtension\mba\host\host.cpp:
1. static _AppDomain* vpAppDomain = NULL;
2. Replaced pAppDomain with the new variable and removed "ReleaseObject(vpAppDomain)" in BootstrapperApplicationCreate function.
3. Replaced "ReleaseNullObject(vpCLRHost)" with such code in BootstrapperApplicationDestroy function:
```
if (vpAppDomain != NULL)
{
    HRESULT hr = vpCLRHost->UnloadDomain(vpAppDomain);
    if (FAILED(hr))
    {
        BalLog(BOOTSTRAPPER_LOG_LEVEL_STANDARD, "Failed to unload app domain, error: 0x%08x.", hr);
    }

    vpAppDomain->Release();
}

if (vpCLRHost != NULL)
{
    vpCLRHost->Stop();
    vpCLRHost->Release();
}

```
And no new files appear in the temp folder.

**Comment by robmen** [comment]
Awesome. Seems like a great thing thing to send a PR into WiX v4 for.

**Comment by leshy84** [comment]
Sent a PR
