### ISSUE TITLE
Cannot install/update WixToolset Visual Studio 2017 Extension version 0.9.17.13693

### ISSUE THREAD

**Issue by waellus** [wixtoolset/issues#5549]
## Bugs

If this issue is a bug:

* Which version of WiX Extension are you trying to install?

> 0.9.17.13693 (currently i'm on 0.9.10.21458)

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 Enterprise

* Describe the problem and the steps to reproduce it.

> I had a prompt to update my WixTools Visual Studio 2017 extension. I tried to update it, and i got an installation failed. You'll find the log below

[VSIXInstaller_922cc441-c8f5-4b8d-ac3f-97d7e405c00b.txt](https://github.com/wixtoolset/issues/files/879748/VSIXInstaller_922cc441-c8f5-4b8d-ac3f-97d7e405c00b.txt)

PS: i just noticed that i can't uninstall WixToolset extension either... That's weird! Here's the log of the uninstall try

[VSIXInstaller_ad462533-f15a-4d79-937e-4d197fc02844.txt](https://github.com/wixtoolset/issues/files/879781/VSIXInstaller_ad462533-f15a-4d79-937e-4d197fc02844.txt)

* Describe the behavior you expected and how it differed from the actual behavior.

> Complete install, update, or uninstall of WixToolset Successfully.

**Comment by robmen** [comment]
Did you happen to previously copy files into the Visual Studio install location in an attempt to work around bugs in RC1? That's what this error seems to be suggesting: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets' already exists.

Try deleting that file (and any other files you may have copied by hand, if any) then going again.

**Comment by remcoros** [comment]
Same here. and there's no WiX folder there for me.
Running VS 2015 and 2017 enterprise.

This is the install log:

29-3-2017 19:53:34 - Microsoft VSIX Installer
29-3-2017 19:53:34 - -------------------------------------------
29-3-2017 19:53:34 - Initializing Install...
29-3-2017 19:53:34 - Extension Details...
29-3-2017 19:53:34 - 	Identifier         : WixToolset.VisualStudioExtension.Dev15
29-3-2017 19:53:34 - 	Name               : Wix Toolset Visual Studio 2017 Extension
29-3-2017 19:53:34 - 	Author             : .NET Foundation and contributors
29-3-2017 19:53:34 - 	Version            : 0.9.17.13693
29-3-2017 19:53:34 - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
29-3-2017 19:53:34 - 	Locale             : en-US
29-3-2017 19:53:34 - 	MoreInfoURL        : http://wixtoolset.org/
29-3-2017 19:53:34 - 	InstalledByMSI     : False
29-3-2017 19:53:34 - 	SupportedFrameworkVersionRange : [4.0,)
29-3-2017 19:53:34 - 
29-3-2017 19:53:34 - 	SignatureState     : Unsigned
29-3-2017 19:53:34 - 	Supported Products : 
29-3-2017 19:53:34 - 		Microsoft.VisualStudio.Community
29-3-2017 19:53:34 - 			Version : [15.0,16.0)
29-3-2017 19:53:34 - 
29-3-2017 19:53:34 - 	References         : 
29-3-2017 19:53:34 - Signature Details...
29-3-2017 19:53:34 - 	Extension is not signed.
29-3-2017 19:53:34 - 
29-3-2017 19:53:34 - Searching for applicable products...
29-3-2017 19:53:36 - Found installed product - Microsoft Visual Studio Enterprise 2015
29-3-2017 19:53:36 - Found installed product - Microsoft Visual Studio Professional 2015
29-3-2017 19:53:36 - Found installed product - Microsoft Visual Studio Community 2015
29-3-2017 19:53:36 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
29-3-2017 19:53:36 - Found installed product - Global Location
29-3-2017 19:53:36 - Found installed product - ssms
29-3-2017 19:53:36 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by waellus** [comment]
Hello Rob,
I didn't copy anything by hand. Older version 0.9.10.21458 is already installed (and i can't uninstall it).

I tried removing the .targets files and repeat the install, same error :(

**Comment by robmen** [comment]
:sigh: Unfortunately, you'll need to follow up with the Visual Studio team. The extension is installed via a .vsix and VS owns that installation mechanism. All I can say is that I've been installing/uninstalling many updates without issue (not that that helps you).

**Comment by waellus** [comment]
i guess i'll give them a piece of my mind! just kidding... Anyway i'll let them know...

in the meantime, maybe it would be good to "create or overwrite" the .targets files

It was if i remember well in:
'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets'
'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\WiXToolset\v4\wix.ca.targets' (not sure about the path because i'm writing it out what i recall).

**Comment by robmen** [comment]
Unfortunately, we don't control that behavior in the VSIX installation mechanism. VSIXs are very limited in what they can do and are fully controlled by Visual Studio. We aren't working with the Windows Installer here so there isn't much more we can do other than say, "Ask Visual Studio, maybe they can fix the installation mechanism."

**Comment by robmen** [comment]
This forum can be used to report Visual Studio issues: https://developercommunity.visualstudio.com/
