### ISSUE TITLE
WixInstallFolder

### ISSUE THREAD

**Issue by Habib10708** [wixtoolset/issues#5550]
## Bugs

> (WiX 3.11.0.1507)

> (Visual Studio 2017 Professional ,  Version:15.0.26228.9)

> (.NET version 4.6.01055)

> (Windows version 7 Enterprise, Service Pack 1)

I am getting this error when i try to build:
The WiX Toolset v4 build tools must be installed to build this project. Could not find wix.targets at ''. To download WiX Toolset v4, see http://wixtoolset.org/releases/

i have added the contents of my wix.target and my .wixproj file below.

it looks like it is looking in the registry for the location of the toolset.
I do not have a registry key in my system.
i can add it - but what is the value?  path to the toolset?

Thanks in advance for your assistance.
Habib
-----------------------------------

Pre-build event:
"$(WIX)bin\heat.exe" dir "$(SolutionDir)PivotViews\bin\$(PivotViews)" 
			-dr PivotViewsDir 
			-cg PivotViewsComponents 
			-gg -g1 -sf -srd 
			-var "var.PivotViews.TargetDir" 
			-out "$(SolutionDir)WiXProject\PivotViewsHeat.wxs"

------------------------------------
My wix.targets file:

<?xml version="1.0" encoding="utf-8"?>

<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" InitialTargets="EnsureActualWixToolsetInstalled" ToolsVersion="15.0">
  <PropertyGroup>
    <WixInstallFolder>$([MSBuild]::GetRegistryValueFromView('HKEY_LOCAL_MACHINE\SOFTWARE\WiX Toolset\v4', 'InstallFolder', null, RegistryView.Registry32))</WixInstallFolder>
  </PropertyGroup>

  <Import Project="$(WixInstallFolder)bin\wix.targets" Condition=" Exists('$(WixInstallFolder)bin\wix.targets') " />
  <Target Name="EnsureActualWixToolsetInstalled" Condition=" !Exists('$(WixInstallFolder)bin\wix.targets') ">
    <Error Text="The WiX Toolset v4 build tools must be installed to build this project. Could not find wix.targets at '$(WixInstallFolder)'. To download WiX Toolset v4, see http://wixtoolset.org/releases/" />
  </Target>
</Project>
-----------------------------------------------
My .wixproj file:
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" InitialTargets="EnsureWixToolsetInstalled" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <ProductVersion>3.9</ProductVersion>
    <ProjectGuid>4922bc41-9a04-41e2-8f41-d97772db2ed8</ProjectGuid>
    <SchemaVersion>2.0</SchemaVersion>
    <OutputName>PivotViewsInstaller</OutputName>
    <OutputType>Package</OutputType>
    <WixTargetsPath Condition=" '$(WixTargetsPath)' == '' ">$(MSBuildExtensionsPath)\WiX Toolset\v4\wix.targets</WixTargetsPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <OutputPath>Packages\</OutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
    <DefineConstants>Debug</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <IntermediateOutputPath>obj\$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Product.wxs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HSalimCo.BusinessObjects\HSalimCo.BusinessObjects.csproj">
      <Name>HSalimCo.BusinessObjects</Name>
      <Project>{9f4b6093-00ae-4f0a-95cb-6367da4facc3}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
    <ProjectReference Include="..\HSalimCo.Core\HSalimCo.Core.csproj">
      <Name>HSalimCo.Core</Name>
      <Project>{7b19298f-7553-4ebb-859c-ce2207336412}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
    <ProjectReference Include="..\HSalimCo.DataAccess\HSalimCo.DataAccess.csproj">
      <Name>HSalimCo.DataAccess</Name>
      <Project>{2caa18ca-b5f0-4fe4-9c4d-f63248d2e75b}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
    <ProjectReference Include="..\HSalimCo.DesktopUI.Common\HSalimCo.DesktopUI.Common.csproj">
      <Name>HSalimCo.DesktopUI.Common</Name>
      <Project>{97ad59c5-d3bf-42fe-9539-8164a80c6928}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
    <ProjectReference Include="..\HSalimCo.WpfPivotViews\HSalimCo.WpfPivotViews.csproj">
      <Name>HSalimCo.WpfPivotViews</Name>
      <Project>{f2b01440-ad21-468c-b4d2-9fc6e06c9064}</Project>
      <Private>True</Private>
      <DoNotHarvest>True</DoNotHarvest>
      <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(WixTargetsPath)" Condition=" Exists('$(WixTargetsPath)') " />
  <Target Name="EnsureWixToolsetInstalled" Condition=" !Exists('$(WixTargetsPath)') ">
    <Error Text="The WiX Toolset v4 build tools must be installed to build this project. To download the WiX Toolset v4, see http://wixtoolset.org/releases/" />
  </Target>
  <PropertyGroup>
    <PreBuildEvent>"$(WIX)bin\heat.exe" dir "$(SolutionDir)PivotViews\bin\$(PivotViews)" 
			-dr PivotViewsDir 
			-cg PivotViewsComponents 
			-gg -g1 -sf -srd 
			-var "var.PivotViews.TargetDir" 
			-out "$(SolutionDir)WiXProject\PivotViewsHeat.wxs"</PreBuildEvent>
  </PropertyGroup>
  
</Project>

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by AkashNPS** [comment]
Hello,
I am facing the same problem which Habib had mentioned. Below is the error on building project -

WiX Toolset v3.11 (or newer) build tools must be installed to build this project. **Could not find wix.targets at 'C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\'.** To download WiX Toolset v3.11 (or newer), see http://wixtoolset.org/releases/	CustomDialogs	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\WiX\v3.x\Wix.targets	10

Details -
(WiX 3.11.0.1507)
(Visual Studio 2017 Professional , Version:15.1 (26403.0) Release
(.NET version 4.6.01590)
(Windows version 7 Professional, Service Pack 1)

Can someone please suggest? Thanks in Advance.
Akash

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
