### ISSUE TITLE
ERROR_INVALID_HANDLE passed by CustomeAction in Wix 

### ISSUE THREAD

**Issue by keerthiabhilash** [wixtoolset/issues#5553]
Wix Version: 3.5+
visual studio 2013
I have a x64 bit Wix project which calls one off the external DLL (x64 bit dll, c++) function using custom action, the  function of the dll is sucessfuly called but when i try to get the property of the MSIHandle passed, I get back an error "ERROR_INVALID_HANDLE" by the MsiGetPropertyW() method.

This only happen when my WIX is built on x64 and my DLL is built on x64 platform. when i build both  in Win32 everything goes smooth and no error are produced the code is below :
======================================
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
	<Product Id="*" Name="wix1" Language="1033" Version="1.0.0.0" Manufacturer="DASSAULT SYSTEMES" UpgradeCode="f7fb84c7-dd36-470a-a96b-d73700a75661">
		<Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />

		<MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />

    <Media Id='1' Cabinet='product.cab' EmbedCab='yes' />
    <Directory Id="TARGETDIR" Name="SourceDir">

      <?if $(var.Platform)=x64 ?>
      <Directory Id="ProgramFiles64Folder">

        <Directory Id="INSTALLFOLDER" Name="wix1" >
          <Component Id='MyComponent' Guid='*'>
            <File Id='readme' Name='readme.txt' DiskId='1' Source='readme.txt' />
          </Component>

        </Directory>

      </Directory>
      <?else ?>
      <Directory Id="ProgramFilesFolder">
        <Directory Id="INSTALLFOLDER" Name="wix1" />
        <Component Id='MyComponent' Guid='PUT-GUID-HERE'>
          <File Id='readme' Name='readme.txt' DiskId='1' Source='readme.txt' />
        </Component>

      </Directory>
      <?endif ?>
    </Directory>

    <UI>
      <UIRef Id="WixUI_Minimal"></UIRef>
    </UI>
		<Feature Id="ProductFeature" Title="wix1" Level="1">
			<ComponentGroupRef Id="ProductComponents" />
		</Feature>

    <Binary Id="hello2.dll" SourceFile="hello2.dll"/>
    <CustomAction Id="hello2re"
               BinaryKey="hello2.dll"
               DllEntry="RegisterDlls"
               Execute="deferred"
               Return="check"
               HideTarget="no"
               Impersonate="no"/>
    <CustomAction Id="set.hello"
             Property="hello2re" Value="hithere;PPClientInstall.log"/>

    <Feature Id='MyFeature' Title='My 1st Feature' Level='1'>
      <ComponentRef Id='MyComponent' />

    </Feature>
    <InstallExecuteSequence>
      <Custom Action="set.hello" Before="hello2re">Not Installed</Custom>
      <Custom Action="hello2re" Before="InstallFiles"><![CDATA[(INSTALLER_MODE <> "REMOVE") OR (REMOVE <> "All" And NOT(REMOVE >< "ClientFeature")) OR (MaintenanceMode <> "Remove") ]]></Custom>
    </InstallExecuteSequence>

  </Product>

  
  
	<Fragment>
		<ComponentGroup Id="ProductComponents" >
			
			
				
			
		</ComponentGroup>
	</Fragment>
</Wix>

==========================================
// hello2.cpp : Defines the exported functions for the DLL application.
//

#include "stdafx.h"
#include "hello2.h"

// This is an example of an exported variable
HELLO2_API int nhello2=0;

// This is an example of an exported function.
HELLO2_API int fnhello2(void)
{
	return 42;
}

// This is the constructor of a class that has been exported.
// see hello2.h for the class definition
Chello2::Chello2()
{
	return;
}

UINT Chello2::RegisterDlls(MSIHANDLE hInstall)
{
	WCHAR vbuff[5000] = { 0 };
	WCHAR msg[5000] = { 0 };
	WCHAR InstallDirectory[5000] = { 0 };
	WCHAR TempLogFile[5000] = { 0 };
	wchar_t *wString = new wchar_t[5000];
	int RetValue = ERROR_SUCCESS;
	bool bOneMsg = false;
	try
	{
		int num = (int)hInstall;
		wchar_t buffer25[512];
		wsprintfW(buffer25, L"%d", num);
		MessageBox(NULL, buffer25, L"abhi 1 Error", MB_ICONERROR | MB_OK);

		DWORD vlen = 500;
		//wchar_t *Stringtoken=NULL;
		wchar_t *next_token = NULL;
		UINT gp = MsiGetPropertyW(hInstall, L"CustomActionData", vbuff, &vlen);
		//looks like strtok needs special pointer values
		wchar_t buffer26[256];
		wcscpy(wString, vbuff);
		wsprintfW(buffer26, L"%d", gp);
		MessageBox(NULL, buffer26, L"abhi 2 Error", MB_ICONERROR | MB_OK);
		//Get Log File and Installation Directory from the CusTomActionData

		next_token = wcstok(wString, L";");
		MessageBox(NULL, wString, L"Good ", MB_ICONERROR | MB_OK);
		if (next_token != NULL)
		{

			//Get Installation Directory
			wcscpy(InstallDirectory, next_token);
			next_token = wcstok(NULL, L";");
			if (next_token != NULL)
			{
				wcscpy(TempLogFile, next_token);

				DeleteFile(TempLogFile);
			
			}
			else
			{
				MessageBox(NULL, L"Unable to get log file information. Aborting the installation", L"Installation Error", MB_ICONERROR | MB_OK);
				RetValue = ERROR_INSTALL_FAILURE;
				//Dont display multiple messages
				bOneMsg = true;
			}

		}
		else
		{
			bOneMsg = true;
			MessageBox(NULL, L"Unable to Get Install Directory and LogFile information. Aborting the installation", L"Installation Error", MB_ICONERROR | MB_OK);
			RetValue = ERROR_INSTALL_FAILURE;
		}
		if (RetValue != ERROR_SUCCESS && bOneMsg == false)
		{
			wsprintfW(msg, L"Registering binaries failed.Please refer log file located at %s . Aborting the installation", TempLogFile);
			MessageBox(NULL, msg, L"Installation Error", MB_ICONERROR | MB_OK);
		}
		delete[]wString;
		return RetValue;
	}
	catch (...)
	{
		RetValue = ERROR_INSTALL_FAILURE;
	
		return RetValue;
	}
}

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
