### ISSUE TITLE
Unable to sign engine in bootstrapper project, Visual Studio 2017, v3.11 RC2

### ISSUE THREAD

**Issue by iKjetil73** [wixtoolset/issues#5554]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

WiX v3.11 RC2

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2017

* Which version of .NET are you building with?

NA

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 1703 (OS Build 15063.11)

* Describe the problem and the steps to reproduce it.

1. Create a C++ x64 application. Complie/Link and sign
2. Create a WiX Installer Setup project, add C++ x64 application, sign
3. Create a WiX Bootstrapper project, add WiX Installer Setup project output and C++ VS2017 Redist
4. After all compile and link, run on bootstrapper: insignia.exe -ib d:Example.Installer.exe -o engine.exe
5. Sign bootstrapper engine.exe: "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool" sign /sm /sha1 948710520ce1e2811540100452ac664db886fd43 /t "http://timestamp.verisign.com/scripts/timstamp.dll" engine.exe

This last step fails. And when running dependency walker on the engine.exe, there is a number of errors. Please 
![capture](https://cloud.githubusercontent.com/assets/26764930/24585762/765d0738-1792-11e7-93a6-bb618d79f1ac.PNG)

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
