### ISSUE TITLE
"Additional Include/Lib" template still wrong values (WiX 3.11)

### ISSUE THREAD

**Issue by chakani** [wixtoolset/issues#5555]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.0.1528

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3

* Which version of .NET are you building with?

> Microsoft .NET Framework
Version 4.6.01055

* Describe the problem and the steps to reproduce it.

> I'm getting the following compilation errors:
wcautil.lib(wcawrap.obj) : error LNK2001: unresolved external symbol __vsnwprintf
dutil.lib(strutil.obj) : error LNK2001: unresolved external symbol __vsnwprintf

The reason is that the default settings, when installing WiX for Visual Studio 2015, are:

C+ Additional Include: $(WIX)sdk\VS2010\inc;
Linker Additional Lib: $(WIX)sdk\VS2010\lib\x86;

The "2010" has to be changed to "2015".

This is a follow-up to issue #5445 of WiX 3.10, which says it's fixed in 3.11 (not).

**Comment by barnson** [comment]
Which "default settings"? For templates, see https://github.com/wixtoolset/issues/issues/5536.

**Comment by chakani** [comment]
I forgot to mention that I'm compiling a DLL Project within the same Solution as my WiX installers.

In the Visual Studio Project Properties of the DLL,  "C++ / General / Additional Include Directories" refers to \VS2010\, instead of 2015.

In "Linker / General / Additional Library Directories", also refers to \VS2010".

**Comment by barnson** [comment]
That's a per-project setting, not a WiX thing.

**Comment by chakani** [comment]
I truly apologize, you are absolutely right. Now that I think of it, this project was originally on VS 2010, and was converted to VS 2015. I had assumed that WiX had inserted these references, when in fact it was probably me.

I am sorry for the false alarm. Chalk it up to being 68  :o)
