### ISSUE TITLE
Missing link from homepage to version 4 installers 

### ISSUE THREAD

**Issue by daixtrose** [wixtoolset/issues#5556]
## Feature request

The [WiX release web page](http://wixtoolset.org/releases) does not contain a link to v4 releases, e.g. http://wixtoolset.org/releases/v4-0-701-0/, so normal users cannot find the v4 releases. I tried [google using keywords ```wix version 4 release```](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=wix+version+4+release&*) and failed. Searching for ```wix40.exe``` finally pointed me to the right place.

Please add the v4 releases to http://wixtoolset.org/releases

**Comment by Tiberriver256** [comment]
4.0 is not stable yet. Looks like he has them listed in the weekly builds:
http://wixtoolset.org/releases/weekly/

**Comment by robmen** [comment]
@Tiberriver256 is exactly correct. Although, as `wix40` (finally) becomes our focus and we fix a few key bugs, we will likely change the releases page to highly `wix40`.

**Comment by daixtrose** [comment]
@robmen I think you missed my point. I already had wix40 installed and lost an hour to find the msi in order to install it on another device. Therefore my proposal to *add* information where it belongs (IMHO).

I still don't get why you make such a secret out of the 40 branch. Please rethink.

**Comment by daixtrose** [comment]
Or how about a site map?

**Comment by robmen** [comment]
WiX v4 is not a secret, it is unstable. In the past, people would grab a weekly v4 builds thinking they were stable. Someone (I forget who) helped us reorganize the web pages to address that issue.

**Comment by briandrennan** [comment]
Hi Rob,

I did the work on the web page. I could do something else if you think there is some value in doing it. Perhaps we could organize v3 into one bootstrap panel, and v4 next to it?

I can probably get that done around the end of the month. I've got some major projects at work,  and coming up on finals for school, so that's about as early as I expect to be able to contribute.

Thanks!

- Brian

________________________________

**Comment by robmen** [comment]
@briandrennan Thanks for offering to help and I'm sorry I forgot your name. 😊 

Creating separate columns for v3 and v4 is probably a good idea. Something we could definitely discuss on wix-devs. No hurry. Builds are slower right now since we're focused on finishing WiX v3.11.

**Comment by briandrennan** [comment]
I believe this should be resolved in (pull request #28](https://github.com/wixtoolset/web/pull/28). @daixtrose, @robmen, perhaps you can have a look? I put a snip of the changes into the pull request.

**Comment by daixtrose** [comment]
You can close the FR. I am happy with the changes. Thank You.
