### ISSUE TITLE
Installer for multithread application

### ISSUE THREAD

**Issue by slavkash** [wixtoolset/issues#5557]
I use Wix Toolset v3.11.0.1507
Visual Studio Community 2015 v14.025431.01 Update 3
.NET version ASP.NET and Web Tools 2015.1
Windows 10 with latest updates

I use two installers for my multi-thread WPF application: a standard Visual Studio Installer and Wix Toolset. All files from my Wix project were taken from Release folder of my Application Project.

Then I create *.msi for both installer projects. After installation of both *.msi files on my computer, first the application.exe files are not of the same size (probably it is normal) and second  is that Visual Studio installers' application works as expected in multiple threads, while Wix' application do everything in one thread and block UI thread.

How is it possible such kind of different behavior? What can cause it? I can not find any information about similar issues.

My Product.wxs:
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
	<Product Id="8630a4a0-34bf-49ac-8ad4-fd463521ac76" Name="42LAW" Language="1033" Version="1.0.0.0" Manufacturer="*******" UpgradeCode="daa76e55-c42f-47a0-b4f5-903e4843e4b1">
		<Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />

		

		<Property Id="WIXUI_INSTALLDIR" Value="MYINSTALLFOLDER"></Property>

		<UI>
			<UIRef Id="WixUI_InstallDir" />
			<Publish Dialog="WelcomeDlg"
						Control="Next"
						Event="NewDialog"
						Value="InstallDirDlg"
						Order="2">1</Publish>
			<Publish Dialog="InstallDirDlg"
						Control="Back"
						Event="NewDialog"
						Value="WelcomeDlg"
						Order="2">1</Publish>
			<Publish Dialog="ExitDialog"	
							 Control="Finish"
							 Event="DoAction"
							 Value="LaunchApplication">WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 and NOT Installed</Publish>	

		</UI>
		
		<Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="Launch 42LAW" />
		<Property Id="WixShellExecTarget" Value="[MYINSTALLFOLDER]42LAW.exe"/>
		
		<CustomAction Id="LaunchApplication" BinaryKey="WixCA" DllEntry="WixShellExec" Impersonate="yes"/>

		<MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
		<Media Id="1" Cabinet="media1.cab" EmbedCab="yes" />
		<Property Id="ARPNOREPAIR" Value="yes" Secure="yes" />
		<Property Id="ARPPRODUCTICON" Value="_42LAWicon"/>
		<Property Id="ALLUERS" Value="1"/>
		<Icon Id="_42LAWicon" SourceFile="d:\MyProgProjects\VisualStudio\MyProjects\AvtivityTracker\AvtivityTracker\42LAW.ico"/>

		<Feature Id="ProductFeature" Title="42LAW" Level="1">
			<ComponentRef Id="_42LAW.exe"/>
			<ComponentRef Id="_42LAW.exe.config" />
			<ComponentRef Id="_Hardcodet.Wpf.TaskbarNotification.dll" />
			<ComponentRef Id="_Newtonsoft.Json.dll" />
			<ComponentRef Id="ApplicationShortcutDesktop" />
			<ComponentRef Id="ApplicationShortcutProgramMenuFolder" />
			<ComponentRef Id="ApplicationShortCutStartUp" />
		</Feature>
	</Product>	

	<Fragment>
		<Directory Id="TARGETDIR" Name="SourceDir">

			<Directory Id="ProgramFilesFolder">
				<Directory Id="MYINSTALLFOLDER" Name="42LAW"/>
			</Directory>

			<Directory Id="ProgramMenuFolder">
				<Directory Id="_42LAW" Name="42LAW"/>
			</Directory>

			<Directory Id="DesktopFolder" Name="42LAW"/>

			<Directory Id="StartupFolder" Name="42LAW"/>

		</Directory>
	</Fragment>

	<Fragment>
		<DirectoryRef Id="_42LAW">
			<Component Id="ApplicationShortcutProgramMenuFolder" Guid="0b65a10b-76f6-4ea6-80c4-6ff6994cd851">
				<Shortcut Id="ApplicationShortcutProgramMenuFolder"
								  Name="42LAW"
								  Description="42LAW"
									Target="[MYINSTALLFOLDER]42LAW.exe"
									WorkingDirectory="MYINSTALLFOLDER"
							  	Icon="_42LAWicon"/>
				<RemoveFolder Id="ProgramMenuFolder" Directory="_42LAW" On="uninstall"/>
				<RegistryValue Root="HKCU" Key="Software\42LAW" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
			</Component>
		</DirectoryRef>

		<DirectoryRef Id="DesktopFolder">
			<Component Id="ApplicationShortcutDesktop" Guid="8ecda271-b356-4a8a-8b84-b6e799dfa9b1">
				<Shortcut Id="ApplicationDesktopShortcut"
								  Name="42LAW"
								  Description="42LAW"
									Target="[MYINSTALLFOLDER]42LAW.exe"
									WorkingDirectory="MYINSTALLFOLDER"
							  	Icon="_42LAWicon"/>
				<RemoveFolder Id="DesktopFolder" Directory="DesktopFolder" On="uninstall"/>
				<RegistryValue Root="HKCU" Key="Software\42LAW" Name="installed" Type="integer" Value="1" KeyPath="yes"/>
			</Component>
		</DirectoryRef>

		<DirectoryRef Id="StartupFolder">
			<Component Id="ApplicationShortCutStartUp" Guid="f9aa3f5e-61e8-4816-bfeb-24e07e14aeb5">
				<Shortcut Id="ApplicationShortCutStartUp"
									Name="42LAW"
									Description="42LAW"
									Target="[MYINSTALLFOLDER]42LAW.exe"
									WorkingDirectory="MYINSTALLFOLDER"
									Icon="_42LAWicon">
				</Shortcut>
				<RegistryKey Root="HKCU" Key="42LAW">
					<RegistryValue Name="42LAW" Type="integer" Value="1" KeyPath="yes"  />
				</RegistryKey>
			</Component>

		</DirectoryRef>
	</Fragment>

	<Fragment>
		<DirectoryRef Id="MYINSTALLFOLDER">
			<Component Id="_42LAW.exe" Guid="c075a85d-f694-4c51-8c69-af21c841a303">
				<File Id="_42LAW.exe" Name ="42LAW.exe" Source="d:\MyProgProjects\VisualStudio\MyProjects\AvtivityTracker\AvtivityTracker\bin\Release\LAW.exe"/>
			</Component>
			<Component Id="_42LAW.exe.config" Guid="b35c05bd-ada4-4664-a9ca-3c2d1a2ec830">
				<File Id="_42LAW.exe.config" Name ="42LAW.exe.config" Source="d:\MyProgProjects\VisualStudio\MyProjects\AvtivityTracker\AvtivityTracker\bin\Release\LAW.exe.config"/>
			</Component>
			<Component Id="_Hardcodet.Wpf.TaskbarNotification.dll" Guid="6c33a707-a876-4c0b-a896-9aa8e4f7cfa6">
				<File Id="_Hardcodet.Wpf.TaskbarNotification.dll" Name ="Hardcodet.Wpf.TaskbarNotification.dll" Source="d:\MyProgProjects\VisualStudio\MyProjects\AvtivityTracker\AvtivityTracker\bin\Release\Hardcodet.Wpf.TaskbarNotification.dll"/>
			</Component>
			<Component Id="_Newtonsoft.Json.dll" Guid="0cd430aa-e8d1-4a49-8bbd-4c6f70e93e4b">
				<File Id="_Newtonsoft.Json.dll" Name ="Newtonsoft.Json.dll" Source="d:\MyProgProjects\VisualStudio\MyProjects\AvtivityTracker\AvtivityTracker\bin\Release\Newtonsoft.Json.dll"/>
			</Component>
		</DirectoryRef>
	</Fragment>

</Wix>

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
