### ISSUE TITLE
WiX + ARM64

### ISSUE THREAD

**Issue by jakepetroules** [wixtoolset/issues#5558]
The WiX Package Platform attribute doesn't seem to support the "ARM64" value yet. As Windows 10 is coming to ARM64 soon, will there be a new value added for this?

**Comment by robmen** [comment]
Does the Window Installer support `ARM64`?

**Comment by barnson** [comment]
The Win10CU SDK hints that it will:

    #define IPROPNAME_ARM64            TEXT("Arm64")

**Comment by barnson** [comment]
Handling the CAs is left as an exercise for the reader.

**Comment by be5invis** [comment]
Microsoft just announced a ARM based Surface Pro.
May need to prioritize this.

**Comment by be5invis** [comment]
https://docs.microsoft.com/en-us/windows/win32/msi/64-bit-windows-installer-packages
Some information may be helpful

**Comment by campt** [comment]
We are supporting ARM64 and have had to do some interesting hacking for ARM64 for our WIX based install package.  Having an ARM64 native version would really help since we end up relying on the x86 (32-bit) emulation support on the ARM64 platform (which requires some post-editing to set it to an ARM64-bit install), which means we can not directly install ARM64 drivers but instead have to shell out to another ARM64 native process to complete setup.

**Comment by barnson** [comment]
ARM64 support is available in WiX v3.14.

**Comment by ksubbaraman** [comment]
Thanks @barnson. We wanted to do the below and will wix 3.14 supports both.

1) Select platform type as Arm64.
2) Have our custom action(that use wix libraries) to compile using Arm64 platform.

**Comment by barnson** [comment]
Yes.

**Comment by ksubbaraman** [comment]
Thanks @barnson, this is going to be very useful to us. Also, wanted to check when 3.14 would become public, we would like to use it soon.

**Comment by voronoipotato** [comment]
Thank you everyone who worked on this!!!

**Comment by kilasuit** [comment]
Is this still needing to be an open issue?

**Comment by AraHaan** [comment]
What about 32 bit arm? I have installer projects for .NET to try to generate 32 bit arm installers (using dotnet/arcade) but it results in only ``win-x86``, ``win-x64``, and ``win-arm64`` installers to only be generated.

**Comment by barnson** [comment]
32-bit ARM was supported briefly back in the original days of Windows on ARM. (The remote debugger tools installers for VS were built with WiX, for example.) But as that wasn't an option outside Microsoft, 32-bit ARM support was dropped.

**Comment by jaykrell** [comment]
ARM32 works on ARM64 devices.
I don't know the official development/signing story, but it is obviously there.
5 architectures! x86, amd64, arm32, arm64, arm64ec.

**Comment by lextm** [comment]
@jaykrell ARM32 is going away on Windows 11 ARM64 as announced in [this article](https://learn.microsoft.com/en-us/windows/arm/arm32-to-arm64).
