### ISSUE TITLE
VS2017 Extension installs v4 templates, but v4 is not available.

### ISSUE THREAD

**Issue by tom-englert** [wixtoolset/issues#5559]
* Which version of WiX are you building with?

Toolset: 3.11.0.1507
VS Extension: 0.9.17.13693

* Which version of Visual Studio are you building with (if any)?

VS2017 (but probably affects all versions)

* Which version of .NET are you building with?

4.6.2

* Describe the problem and the steps to reproduce it.

After installing the VS2017 Extension there are two sets of templates, one for v3 and one for v4. 
If you don't expand the Wix Toolset template folder, you end up with a v4 installer as a default - however v4 is not released yet.

![wixprojecttemplate](https://cloud.githubusercontent.com/assets/10229954/24895188/54657d50-1e8f-11e7-8802-84d306d7810c.png)

This creates many confusions:

- The installer can't be compiled, if v4 is not installed (usually the default)
- see also e.g. https://github.com/tom-englert/Wax/issues/41

* Describe the behavior you expected and how it differed from the actual behavior.

There should not be any v4 templates offered when there is no official v4 version released. 
Another solution could be to postfix the template names with the required WiX Toolset version:
- Setup Project (v3)
- Setup Project (v4)
....

**Comment by robmen** [comment]
The plan is to do something like the latter, to add something visual to make it easier to know if you are picking v3 or v4 templates.

Note: There are unstable v4 builds available today.
