### ISSUE TITLE
heat.exe error processing project file

### ISSUE THREAD

**Issue by tlscales** [wixtoolset/issues#5560]
If this issue is a bug:

* Which version of WiX are you building with? 

> WiX Toolset v3.11

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2017 version 15.1 (26403.0) Release

* Which version of .NET are you building with?

> 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> While building an installer file, WiX fails to process one of the included projects.  

**Output from the installer project (WOC2Setup64_wix.wixproj) build:** 
35>------ Build started: Project: WOC2Setup64_wix, Configuration: Debug64 x64 ------
35>	"C:\Program Files (x86)\WiX Toolset v3.11\Bin\heat.exe" project "C:\tscales_CAS_WOC2_4.07.X\optionalSystems\CAS\VoIP Audio\Summit Audio Client\AudioClient\AudioClient\AudioClient.csproj" -projectname "AudioClient" -pog Binaries -gg -sfrag -nologo -out "obj\\Debug64\Harvested XML\_AudioClient.xml"
35>	"C:\Program Files (x86)\WiX Toolset v3.11\Bin\heat.exe" project "C:\tscales_CAS_WOC2_4.07.X\optionalSystems\CAS\GOInstancesManager\GOInstancesManager.csproj" -projectname "GOInstancesManager" -pog Binaries -gg -sfrag -nologo -out "obj\\Debug64\Harvested XML\_GOInstancesManager.xml"
35>	"C:\Program Files (x86)\WiX Toolset v3.11\Bin\heat.exe" project "C:\tscales_CAS_WOC2_4.07.X\optionalSystems\CAS\VoIP Audio\PJSIP\pjproject-2.1.0\pjsipDll\build\pjsipDll.vcxproj" -projectname "pjsipDll" -pog Binaries -gg -sfrag -nologo -out "obj\\Debug64\Harvested XML\_pjsipDll.xml"
35>heat.exe(0,0): error HEAT5305: Failed to load project C:\tscales_CAS_WOC2_4.07.X\optionalSystems\CAS\VoIP Audio\PJSIP\pjproject-2.1.0\pjsipDll\build\pjsipDll.vcxproj: Unable to cast object of type 'System.Xml.XmlComment' to type 'System.Xml.XmlElement'.
35>C:\tscales_CAS_WOC2_4.07.X\optionalSystems\CAS\WOC2Setup\WOC2Setup64_wix.wixproj(129,5): error MSB3073: The command ""C:\Program Files (x86)\WiX Toolset v3.11\Bin\heat.exe" project "C:\tscales_CAS_WOC2_4.07.X\optionalSystems\CAS\VoIP Audio\PJSIP\pjproject-2.1.0\pjsipDll\build\pjsipDll.vcxproj" -projectname "pjsipDll" -pog Binaries -gg -sfrag -nologo -out "obj\\Debug64\Harvested XML\_pjsipDll.xml"" exited with code 5305.
35>Done building project "WOC2Setup64_wix.wixproj" -- FAILED.

Zip with the problematic project file (pjsipDLL.vcxproj) and the presumably related file from the XSLT directory associated with the WiX installer project (_pjsipDll.xml) attached.

[pjsip DLL project files.zip](https://github.com/wixtoolset/issues/files/913995/pjsip.DLL.project.files.zip)

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected the installer to build correctly

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/5490
