### ISSUE TITLE
WiX installer repairs prerequisite .NET package

### ISSUE THREAD

**Issue by dvorn** [wixtoolset/issues#5561]
* Which version of WiX are you building with?

> 3.11.0.1528

* Describe the problem and the steps to reproduce it.

> Attempt to repair the installed WiX Toolset causes the .NET package being actually downloaded and repaired.

* Describe the behavior you expected and how it differed from the actual behavior.

> Repair of .NET package is skipped.

That was the original intent of the WiX Toolset authors: 
https://github.com/wixtoolset/wix3/blob/6e0bab12e155426d57a36c848fd6920e0eaad64f/src/Setup/WixBA/InstallationViewModel.cs#L468

However 

> [04A0:1858][2017-04-14T19:36:37]i001: Burn v3.11.0.1528, Windows v10.0 (Build 15063: Service Pack 0), path: C:\ProgramData\Package Cache\{cac445de-97dd-4dc4-81b7-bd43ac4716ef}\WiX311.exe

> [04A0:1858][2017-04-14T19:36:39]i101: Detected package: NetFx40Web, state: Present, cached: None

> [04A0:1858][2017-04-14T19:36:42]i201: Planned package: NetFx40Web, state: Present, default requested: Repair, ba requested: Repair, execute: Repair, rollback: None, cache: Yes, uncache: No, dependency: None

> [04A0:0AB0][2017-04-14T19:36:44]i338: Acquiring package: NetFx40Web, payload: NetFx40Web, download from: http://go.microsoft.com/fwlink/?linkid=182805

> [2B6C:297C][2017-04-14T19:36:47]i305: Verified acquired payload: NetFx40Web at path: C:\ProgramData\Package Cache\.unverified\NetFx40Web, moving to: C:\ProgramData\Package Cache\06BECADB92A5FCCA2529C0B93687C2A0C6D0D610\redist\dotNetFx40_Full_setup.exe.

Not a big deal in itself, but the source code of WiX installer is used by many as a pattern of building MBAs.

**Comment by robmen** [comment]
Fixed in WiX v4
