### ISSUE TITLE
Updating Visual Studio 2017 requires reinstall of extension

### ISSUE THREAD

**Issue by tsoftware** [wixtoolset/issues#5563]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.0.1528

> (WiX version in major.minor.release.build format)
3.11.0.1528

* Which version of Visual Studio are you building with (if any)?
Visual Studio  2017

> (Visual Studio version, including year and update)
Visual Studio 2017 15.1.26403.7

* Which version of .NET are you building with?
4.5.2

> (.NET version)
4.5.2

* Describe the problem and the steps to reproduce it.

Each time I have performed a Visual Studio 2017 update and then open a solution that has a WiX project in it, the WiX project indicates that the project is incompatible.  Checking on extensions and updates, it shows that the WiX extension is no longer installed.  When I reinstall the extension, the setup indicates that it is a modification, the extension reinstalls and everything is fine until the next Visual Studio 2017 update.

* Describe the behavior you expected and how it differed from the actual behavior.
I expect the WiX Visual Studio extension to survive an update and not have to reinstall.

**Comment by robmen** [comment]
That isn't in our control. Visual Studio decides which extensions get to stay. I believe that per-machine extensions are not carried forward but don't see documentation to confirm that. The VS2017 extension is per-machine due to design limitations in VS2017.

You can file issues with Visual Studio at: https://developercommunity.visualstudio.com

**Comment by tsoftware** [comment]
I understand.  This is the only extension that I have noted that hasn't been surviving.

**Comment by robmen** [comment]
You might look at what is different about the WiX Toolset from all the others.

**Comment by tsoftware** [comment]
The main difference that jumps out to me is that it creates a new project type....none of my others do.

**Comment by robmen** [comment]
Ahh, so that means the WiX Toolset is infinitely more complex.

**Comment by barnson** [comment]
FWIW, I've never lost the WiX Extension in VS2017 upgrades.

**Comment by heaths** [comment]
Nor should you, the way it works. The new installer merges new packages with old, builds a dependency graph, and installs the recent packages like other package managers. The only way I can think of is if an extension had an upper-bound on its dependency authoring.

**Comment by robmen** [comment]
We don't so this issue sounds like a great thing to go take to the Visual Studio forum linked above.
