### ISSUE TITLE
Burn should allow BA to provide update feed source

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5568]
* Describe the scenario and benefits that the feature supports.

> Today, a bundle update feed is authored in a bundle and no callback allows the BA to override it.

* Describe how you're accomplishing the feature today (if possible).

> Today, you'd have to handle downloading and parsing of a feed if you need a dynamic URI.

* Describe what you'd like the new feature to do.

> Add `IBootstrapperEngine.SetUpdateSource`, analogous to `IBootstrapperEngine.SetDownloadSource`, that a BA can call during update detection.

**Comment by jchoover** [comment]
There is an existing request that I planned on working on in 4.x for changing OnDetectUpdateBegin to be a modifiable string for sczUpdateSource. Is that sufficient, or do we need the ability to assign the update source dynamically without any original authoring for an update source?
