### ISSUE TITLE
I am getting problem in installing WiX Toolset v3.10.3  tool kit on windows7 

### ISSUE THREAD

**Issue by sunitatripathi12** [wixtoolset/issues#5569]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. I am getting problem in installing WiX Toolset v3.10.3 or any other version   tool kit on windows7(64 bit) .

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
