### ISSUE TITLE
Why does Wix311.exe still required .NET 3.51?

### ISSUE THREAD

**Issue by kdawg1406** [wixtoolset/issues#5570]
Please remove this requirement to have .NET3.51 installed on my machine.

Makes no sense with such a modern tool.

Thank you!!!!

Karl

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/5545

**Comment by kdawg1406** [comment]
@barnson yes, we all understand the current requirement.  But WHY not correct this?

**Comment by barnson** [comment]
It will be.

**Comment by rseanhall** [comment]
Also see #5523 which was triaged in meeting 123 ([video](https://www.youtube.com/watch?v=qoxnEOJZqRM), [highlights](https://www.firegiant.com/blog/2017/3/14/wix-online-meeting-123-highlights/))
