### ISSUE TITLE
Setup failed:- When i used Per-User MSI with Bootstrapper with .Net prerequisites

### ISSUE THREAD

**Issue by ankur4747github** [wixtoolset/issues#5571]
Wix setup:- I have a Per-User MSI and I added it into Bootstrapper(Bundle.wxs) and in the bootstraper(Bundle.wxs) I have prerequisites to install before MSI install... but

when i set InstallScope="perUser" inside MSI and then run bootstraper Setup Failed..

when i set InstallScope="perMachine" inside MSI and then run bootstraper Setup Successfull

I want to Install Setup with prerequisites and Per-User MSI..it is possible or am I missing anything?
I think when I set InstallScope="perUser" bootstrapper didn't get Admin rights i.e by its failed.

Wix Version:- 3.11.01528
VS:- 2013
Windows 10 x64

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
