### ISSUE TITLE
"Windows Installer XML" - where is it in VS2017

### ISSUE THREAD

**Issue by thedavegray** [wixtoolset/issues#5572]
## Discussions and support
Hi, 

- Visual Studio 2017 Enterprise 
- Windows 10 Pro 

Installed WIX Toolset and added the extension WAX so that I can create installer/setup projects using WIX, however the project type "Windows Installer XML" is not in the "Add New Project" dialog as it was in VS2015.  Anyone know where it is? 

Thanks

![image 019](https://cloud.githubusercontent.com/assets/4395873/25578433/8fe960b2-2e66-11e7-9c5a-4299796bccd1.png)

**Comment by barnson** [comment]
Install the WiX VS extension.
