### ISSUE TITLE
File not being updated correctly

### ISSUE THREAD

**Issue by christophedemey** [wixtoolset/issues#5574]
* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> 15.1 (26403.7)

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7 (6.1 Build 7601 Service Pack 1)

* Describe the problem and the steps to reproduce it.

> 
My installer has a file 'amazingcomponent.DLL', this file has been in the installer for many versions.
This DLL was updated recently and supplied by a nuget package but has remained it's name, so i did not have to update any of my wxs files or installer files.
My application v26 contains this updated DLL.
When i update from a version prior to the DLL update : v25 to v26 this happens :
- removing components fase : OK
The amazingcomponent.DLL is removed by the update.
- installing new components fase : NOK
The amazingcomponent.DLL is not copied back in by the update.

When i repair the installation v26 the amazingcomponent.DLL appears.

I attached the MSI Installer log from the update process.
This is my component registration side of my wxs file :
```
<Component Id="DJA.Standard.Web.Middleware.dll" Guid="{5B8725FC-8100-44F7-8B35-6A06A92DA8D0}">
              <RemoveFile Id="Remove_DJA.Standard.Web.Middleware.dll" Name="DJA.Standard.Web.Middleware.dll" On="uninstall"/>
              <File Id="DJA.Standard.Web.Middleware.dll" KeyPath="yes" Source="$(var.Releasepath)DJA.Standard.Web.Middleware.dll" />
            </Component>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected the old DLL to be removed (OK) and to be replaced with the DLL (NOK).

I have checked the installerlog myself but could not find any error messages, i do however see that the file is removed and not copied back in, but there does not seem to be a reason in the log for it.

Thanks

[installerLog.txt](https://github.com/wixtoolset/issues/files/978474/installerLog.txt)

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by christophedemey** [comment]
Hi

I would like to answer this issue even though it's closed.
In the hope it helps somebody someday.

In my log i have :
MSI (c) (F0:DC) [09:51:29:069]: Disallowing installation of component: {06C9D269-1AA5-5D17-9377-CEF147C52F16} since the keyfile exists and the component is marked to never overwrite existing installations

The dll that was being the issue was going from version 1.0.4 to 1.0.2 and this caused this behaviour.

Solution : Making sure the dll was higher than 1.0.4.

Thanks to the wix mailing lists for helping me resolve this problem. (Nir Bar)
