### ISSUE TITLE
AVG identifies burn.exe as potential thread

### ISSUE THREAD

**Issue by miracle152004** [wixtoolset/issues#5576]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.10.3.3007

* Describe the problem and the steps to reproduce it.

> Since today the burn.exe and the wix-setup (already installed and displayed on programs and features) are identified as potential threads by AVG on our build server.
Since both files are not digitally signed our working theory is currently that it is identified because the files are not digitally signed.
The installed version of AVG is AVG Antivirus Business Edition 16.151.8013
AVG Framework Version 1.143.2.51391
AVG Setup Version 1.143.2.51391
Virus Database: 4776/14454 (09.05.2017, 3:02)

* Describe the behavior you expected and how it differed from the actual behavior.

> Both files should not be identified as potential trojan/virus.

**Comment by robmen** [comment]
Please submit a false positive here: https://secure.avg.com/submit-sample

The more customers that report it the faster they will recognize the false positive.

**Comment by miracle152004** [comment]
Sorry I do not think this is the correct response.
I think this would not have happend if the tools and the setup would have been digitally signed.
And I would like a little more support on this end than "Send a false positive report".

**Comment by robmen** [comment]
We do digitally sign our builds. If it isn't digitally signed then maybe you do have a counterfeit infected file.
