### ISSUE TITLE
Wix 3.11 not available on nuget.org

### ISSUE THREAD

**Issue by zplan** [wixtoolset/issues#5579]
## Feature requests

If this issue is a feature request:

* Describe what you'd like the new feature to do.

> Download of new versions should be available on nuget.org as a nuget package. There are always 'unoffical' nuget packages from people who have the same problem. Please provide the package as soon as a release is stable.

**Comment by letmaik** [comment]
Why is this added to the v4.0 milestone? The package should have been released on nuget three weeks ago. Right?

**Comment by robmen** [comment]
There is no WiX v3.x NuGet package. The work is being done in WiX v4.

**Comment by letmaik** [comment]
https://www.nuget.org/packages/WiX I guess it's unofficial, but very useful!

**Comment by letmaik** [comment]
Nevermind, the maintainer uploaded 3.11.

**Comment by robmen** [comment]
Duplicate of #3981
