### ISSUE TITLE
Error : 0xc000027b Failed to elevate

### ISSUE THREAD

**Issue by apinarb** [wixtoolset/issues#5580]
*Version: Wix v3.11.0.1528
*Visual Studio version: Visual Studio 2015 Professional version 14.0.25431.01 Update 3
*Building with .NET 4.6.2

*Running on Windows 10 Home Build 14393.rs1_release_sec.170327-1835 in Test Mode

Encountered the following error log:

[Failed_Install.txt](https://github.com/wixtoolset/issues/files/990581/Failed_Install.txt)

This error occurred while performing an installation without any prior installation of our application.  I was not the one who produced the error, but I have the machine in the fail state and can view this log.  I tried the install again and was unsuccessful in reproducing this error.  No .msi log is being produced as I don't think the .msi itself was ever run.

I am not able to share code on here, but the Bundle is not doing very much.  It pretty much is just installing .NET 4.6.2, vc_redist 2015 x86 and vc_redist 2015 x64 (if they are not already installed) and passing a variable titled "OTA_UPGRADE" to the .msi. 

Is there any way to tell if this is being done incorrectly with my installer or does this look like an actual bug in WiX?  I looked through the relevant code that produces the elevated engine process and I don't see how my code could affect it (especially since it looks like the .msi is not even being launched).  Currently, we're using a WiX bundle/.msi and we are using the WixStandardBootstrapperApplication.

**Comment by barnson** [comment]
The error indicates a problem with the machine. For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
