### ISSUE TITLE
Error when building using Visual Studio 2017 Preview just released

### ISSUE THREAD

**Issue by bobu** [wixtoolset/issues#5581]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.0.1507

but for Wix Toolset Visual Studio 2017 Extension 
version 0.9.21.62588

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?
Visual Studio Enterprise 2017 Preview (2)
version 4.6.01586

> (Visual Studio version, including year and update)

* Which version of .NET are you building with?
.NET 3.5, .NET 4.51, based on the project. Also netstandard2.0 for some projects.

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10 Enterprise

> (Windows version)

* Describe the problem and the steps to reproduce it.
My solution contains an installer wix project. It correctly builds with Visual Studio 2017 that is generally available. But for the Visual Studio 2017 Preview (2) release, I get this error:

58>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets(10,5): error : The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. Could not find wix.targets at 'C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\'. To download WiX Toolset v3.11 (or newer), see http://wixtoolset.org/releases/

Note that the version of MSBuild being called is NOT in the \Program Files (x86)\MSBuild\... path, but is under the Preview version of Visual Studio that I am using. Also there is in fact a wix.ca.targets file in the directory referenced above!

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please attach a diagnostic-level build log.

**Comment by bobu** [comment]
[msbuild.zip](https://github.com/wixtoolset/issues/files/1002710/msbuild.zip)

**Comment by barnson** [comment]
You need to upgrade to the RTM version of WiX v3.11.
