### ISSUE TITLE
Passing MSI argument through EXE bundle in WiX not working

### ISSUE THREAD

**Issue by mayooran99** [wixtoolset/issues#5582]
One of my MSIs has a parameter called USERNAME. It is defined in the wxs file as shown below.
`<Property Id="USERNAME"  Value="someDefaultValue" />`

When I run the msi as shown below, it runs fine.
`msiexec /i <msiName>.msi USERNAME="test"`

Now I need to run this MSI through my WiX Bundle EXE. Below is how I am trying to do this.

` <Variable Name="UserName" Type="string" Value="someDefaultValue" Persisted="yes" bal:Overridable="yes"/>`

 <MsiPackage SourceFile="..\Dependencies\Installer\bin\Release\Installer.msi" Id="WatchDogInstallerId" Vital="no" Visible="yes">
    <MsiProperty Name="INSTALLLOCATION" Value="[InstallLoc]"/>
    <MsiProperty Name="USERNAME" Value="[UserName]"/>
  </MsiPackage>`

Below is how I am running this EXE.
`Bundle.exe UserName="Test"`

Now though the UserName parameter has the value "Test" according to the log, the msi is not getting this value passed by the EXE. Instead it prints the default value of the variable defined in the EXE's wxs file. What am I doing wrong here? Any help would be much appreciated.

Below are the logs that are related to the UserName variable.\
`[1310:173C][2017-05-15T20:41:40]i000: Initializing string variable 'InstallLoc' to value 'C:\Program Files\'
[1310:173C][2017-05-15T20:41:40]i000: Initializing string variable 'UserName' to value 'someDefaultValue'
[1310:173C][2017-05-15T20:41:40]i009: Command Line: '-burn.clean.room=C:\Users\VM\Desktop\TestBasePlatformSetup.exe UserName=test'
[13F8:176C][2017-05-15T20:43:13]i301: Applying execute package: WatchDogInstallerId, action: Install, path: C:\ProgramData\Package Cache\{3856467B-2AF4-47B8-908D-25BC9CA85EA5}v3.1.42\Installer.msi, arguments: ' MSIFASTINSTALL="7" INSTALLLOCATION="C:\Program Files\" USERNAME="someDefaultValue"'
[1310:173C][2017-05-15T20:45:58]i410: Variable: UserName = someDefaultValue`

The wix version I am using is 3.10. And the scenario I am trying to do here is a fresh install.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by nik-net** [comment]
Hi did you manage to find a way out for this problem? I am currently in the same boat.

**Comment by nik-net** [comment]
I figured this one out after an insane 5 hours wasted! The thing is that.........wait for it........Wix will automatically convert your property name to be all in upper case. My custom action could read "USERNAME" but not "UserName" even though in the wxs file the property was defined as UserName.

Go figure.

**Comment by crusy** [comment]
> For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

This link is redirected to https://docs.firegiant.com/wix/ , fyi. It still contains links to a mailing list and a forum, though:

> How to become a User: Use the WiX Toolset and participate on the [mailing lists](https://docs.firegiant.com/wix/gethelp.md#mailinglists) and [discussion forum](https://docs.firegiant.com/wix/gethelp.md#forum).

Both links result in a 404.

So, my point here is: Google redirected me to support requests quite some times in the last couple of days, but the response is always some form of "no support here", with links to non-existing content. Maybe you should consider deleting these issues, because this helps nobody – not even the mailing list user count.
