### ISSUE TITLE
Let PreprocessorExtensions implement IDisposable, or add a method to indicate that all files have been processed

### ISSUE THREAD

**Issue by Ganon11** [wixtoolset/issues#5584]
* Describe the scenario and benefits that the feature supports.

We use a Wix Preprocessor Extension to glean metadata about our deployed files in order to build what essentially amount to large manifest files. We'd like to only write these files once, when we're sure that we've processed all wxs files and gathered all metadata.

Implementing `IDisposable`, or providing another method to be called when all processing had completed, would provide a supported opportunity for extensions to do any final cleanup work before candle.exe ends.

* Describe how you're accomplishing the feature today (if possible).

Previously, we had been implementing a finalizer for the PreprocessorExtension, which would write our manifest files for us. However we began running into the limits of .NET Finalizers when our manifest files became too large, and suddenly were not reliably being written because the finalizer took too long.

Currently we write the manifest files in our implementation of FinalizePreprocess, which results in us writing files once per wxs file being processed by candle.

* Describe what you'd like the new feature to do.

Provide an override-able function (`Dispose()` or similarly named) on PreprocessorExtensions to be called when all files provided to candle.exe have been processed. Call this method at the end of `Candle.Run`.

**Comment by robmen** [comment]
In WiX v4.0 the extensions can now interact with many parts of the build pipeline. In this case, you'd probably want to write your report post Link to know which files actually ended up in the package.
