### ISSUE TITLE
Non-recommended version offered as update

### ISSUE THREAD

**Issue by chrullrich** [wixtoolset/issues#5585]
* Which version of WiX are you building with?

3.11.0.1528

* Describe the problem and the steps to reproduce it.

The current "recommended build" at wixtoolset.org is 3.11 RC2, aka 3.11.0.1528. The more recent weekly release .1701 is described as "[i]n general, [] not considered to be production-ready". Nonetheless, the .1528 installer offers .1701 as an available update.

Repro: Download the "recommended build", start it, wait a few seconds.

* Describe the behavior you expected and how it differed from the actual behavior.

I would expect the installer's update detection logic to follow the project's policy and not suggest weekly releases as updates without also providing the necessary context to allow the user to make an informed decision on the desirability of updating.

Alternatively, if tracking the weeklies is, in fact, considered a good idea, it is time to get rid of the dire warnings.

If, on the other hand, the current state of 3.11 is not meant to be used in production at all yet, the "recommended build" should be some version of 3.10 instead.

**Comment by rseanhall** [comment]
.1701 is the RTM version of 3.11. We need to update the website to reflect this.

There is already a separate issue for making sure that the weekly releases are not offered as an update to stable releases.

**Comment by chrullrich** [comment]
I looked for one, but couldn't find it. Sorry for the noise then.

**Comment by rseanhall** [comment]
I'm going to leave this open to track updating the website.

**Comment by robmen** [comment]
There was a build issue with the last commit that caused the website to go "back in time" before the WiX v3.11 release. Website fixed.
