### ISSUE TITLE
Problem building in Visual Studio 2017

### ISSUE THREAD

**Issue by aphilpotts** [wixtoolset/issues#5588]
I was able to build Wix projects from within VS 2015, I recently upgraded to 2015

I have installed the the Wix Toolset Visual Studio 2017 extension, WIX 3.11 was already installed

The extension is version 0.9.21.62588, the Wix version is 3.11.0.1307

I have a WIX variable set to "C:\Program Files (x86)\WiX Toolset v3.11\", that is where WIX is installed

When I try to build from visual studio 2017 I get this:

Severity	Code	Description	Project	File	Line	Suppression State
Warning		The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. Could not find wix.ca.targets at 'C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\'. To download WiX Toolset v3.11 (or newer), see http://wixtoolset.org/releases/	LPG.Installation			

That folder above, C:\Program Files (x86)\MSBuild\Microsoft\WiX,  is not where my WIX is installed, it is instead installed in C:\Program Files (x86)\WiX Toolset v3.11\

**Comment by aphilpotts** [comment]
This may be a red herring, the project in question builds a C# installer extension and refers to this:

    <WixCATargetsPath Condition=" '$(WixCATargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.CA.targets</WixCATargetsPath>

I will see if I can copy this from VS 2015

**Comment by robmen** [comment]
`wix.ca.targets` should be present in the `C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x` folder no matter where you install the WiX Toolset.

If that folder is missing files, then you may want to repari the WiX toolset.

**Comment by barnson** [comment]
Upgrade the RTM release of WiX v3.11.

**Comment by aphilpotts** [comment]
Joy, problem resolved, thanks
