### ISSUE TITLE
Wix Error 1001 on Windows 10 when using CustomAction beyond Program Files

### ISSUE THREAD

**Issue by NoGitHubPlease** [wixtoolset/issues#5590]
I use the latest Version of wix (3.11 I think) in Visual Studio 2013 latest updates. All is running with .Net 4.0 and/or .Net 2.0.
With this version I developed a set of install packages, all running on Windows 7 (or less) without any Problems.
Within that install packages, a custom action using an Assembly is called to prepare parts of the Installation Environment.
On Windows 10 those packages Crash. The reason is, that the Custom Actions result 'Assembly.installState' can not be writtin within the Directory, where the application is installed in, which is beyond Program Files. There a System.SecurityException is thrown, telling, that the installer does not have enough rights to write into the applications subdirectory beyond 'Program Files'. But in fact, all other installed files are there and the Assembly itself could be startet there. Just the 'Assembly.installState' file is written with different previleges than the application files. This causes Error 1001.
The Problem does not occure, if I do install beyond a different Directory, not beyond "Program Files".
I think, this is a bug.
But in fact, I was not able to define different Access rights (create file right) for the applications Directory beyond "Program Files".

**Comment by barnson** [comment]
That's InstallUtil, not WiX.
