### ISSUE TITLE
VS 2010 Extension: Install Error : System.IO.PathTooLongException on Windows XP and Server 2003

### ISSUE THREAD

**Issue by robi-wan** [wixtoolset/issues#5592]
Installation of Visual Studio 2010 Extension fails with System.IO.PathTooLongException.

* Which version of Visual Studio are you building with (if any)?
  * Microsoft Visual Studio 2010 Version 10.0.40219.1 SP1Rel
  * Microsoft .NET Framework Version 4.0.30319 SP1Rel

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
I tried it on two different Windows versions (these are part of our development/CI systems):
  * Windows XP Professional, Version 2002, SP3, 32bit
  * Windows Server 2003 Standard Edition R2 SP2, 32 bit

* Describe the problem and the steps to reproduce it.
I tried to install the Visual Studio Extension for Visual Studio 2010 by executing the file `Votive2010.vsix`. Installation failed - see log.

* Describe the behavior you expected and how it differed from the actual behavior.
I expect the installation to succeed without an error.

There is a workaround:
Extract the contents of the extension installer `Votive2010.vsix` into the folder `C:\Dokumente und Einstellungen\user\Lokale Einstellungen\Anwendungsdaten\Microsoft\VisualStudio\10.0\Extensions\.NET Foundation and contributors\Wix Toolset Visual Studio 2010 Extension\0.9.21.62588\`, start Visual Studion 2010 and enable the `Wix Toolset Visual Studio 2010 Extension` in Extension Manager.

```
24.05.2017 10:14:00 - Microsoft Visual Studio Extension Installer
24.05.2017 10:14:00 - -------------------------------------------
24.05.2017 10:14:01 - Initializing Install...
24.05.2017 10:14:02 - Extension Details...
24.05.2017 10:14:02 - 	Identifier      : WixToolset.VisualStudioExtension.Dev10
24.05.2017 10:14:02 - 	Name            : Wix Toolset Visual Studio 2010 Extension
24.05.2017 10:14:02 - 	Author          : .NET Foundation and contributors
24.05.2017 10:14:02 - 	Version         : 0.9.21.62588
24.05.2017 10:14:02 - 	Description     : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
24.05.2017 10:14:02 - 	Locale          : en-US
24.05.2017 10:14:02 - 	MoreInfoURL     : http://wixtoolset.org/
24.05.2017 10:14:02 - 	InstalledByMSI  : False
24.05.2017 10:14:02 - 	MinFramework    : 4.0
24.05.2017 10:14:02 - 	MaxFramework    : 
24.05.2017 10:14:02 - 
24.05.2017 10:14:02 - 	Supported Visual Studio Editions : 
24.05.2017 10:14:02 - 		Version : 10.0
24.05.2017 10:14:02 - 			Pro
24.05.2017 10:14:02 - 
24.05.2017 10:14:02 - 	Supported Isolated Shells : 
24.05.2017 10:14:02 - 
24.05.2017 10:14:02 - 	References      : 
24.05.2017 10:14:02 - 
24.05.2017 10:14:02 - Searching for applicable products...
24.05.2017 10:14:02 - Found installed product - Microsoft Visual Studio 2010 Professional
24.05.2017 10:14:04 - The extension with ID 'WixToolset.VisualStudioExtension.Dev10' is not installed to Microsoft Visual Studio 2010 Professional.
24.05.2017 10:14:09 - The following target products have been selected...
24.05.2017 10:14:09 - 	Microsoft Visual Studio 2010 Professional
24.05.2017 10:14:09 - 
24.05.2017 10:14:09 - Beginning to install extension to Microsoft Visual Studio 2010 Professional...
24.05.2017 10:14:09 - Install Error : System.IO.PathTooLongException: C:\Dokumente und Einstellungen\user\Lokale Einstellungen\Anwendungsdaten\Microsoft\VisualStudio\10.0\Extensions\.NET Foundation and contributors\Wix Toolset Visual Studio 2010 Extension\0.9.21.62588\ItemTemplates\WiX\v3\1033\BlankFile.zip: BlankFile.vstemplate
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)
```

**Comment by barnson** [comment]
Drop "and contributors" and squish "Visual Studio 2010" to "VS2010"

**Comment by barnson** [comment]
@robi-wan: You don't need to install the VS extension except to load .wixproj projects in Visual Studio. Command-line builds work fine with the VS extension.

**Comment by robi-wan** [comment]
@barnson Thanks for the hint. I'll remove the VS extension from the CI build agents.

**Comment by DevMichaelSabo** [comment]
I have the same problem!
Is this fixable in your code?
