### ISSUE TITLE
ERRORLEVEL returns 1 after successful installation

### ISSUE THREAD

**Issue by AlexL3** [wixtoolset/issues#5595]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

Burn v3.10.3.3007, Windows v6.3 (Build 9600: Service Pack 0)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

OS Name:          Microsoft Windows Server 2012 R2 Standard
                                                           
OS Version:       6.3.9600 N/A Build 9600                  
                                                           
OS Manufacturer:  Microsoft Corporation                    
                                                           
OS Configuration: Member Server                            
                                                           
OS Build Type:    Multiprocessor Free                      

* Describe the problem and the steps to reproduce it.

After a successful installation, checking for
echo Exit Code is  %ERRORLEVEL% returns
Exit Code is  1

As the environment variable ERRORLEVEL is not set and command extensions are enabled, %ERRORLEVEL% returns the exit code of the last program. The installation is successful, but returning non zero, as above. Thus, unable to run automated installations.

* Describe the behavior you expected and how it differed from the actual behavior.

%ERRORLEVEL% is supposed to return 0, .i.e. successful installation.

Running the same installation with another version of WiX installer, %ERRORLEVEL% does return 0.

The correct code returns when WiX version is

Burn v3.9.1006.0, Windows v6.1 (Build 7601: Service Pack 1)
 
It seems that something happened between those two versions, which prevents the correct setting of ERRORLEVEL

**Comment by rseanhall** [comment]
I can't repro this for v3.14 or v4.0.
