### ISSUE TITLE
Wix 3.11.0.1701 License agreement language

### ISSUE THREAD

**Issue by singsubbu** [wixtoolset/issues#5596]
Hi Team,

I am using Wix 3.11.0.1701 version with visual studio 2017 professional and created MSI. But when I am installing the MSI, it is giving some german language in the license agreement. Can you please let us know how to change this language to english. 
<img width="857" alt="wixlicenceagreementscreenshot" src="https://cloud.githubusercontent.com/assets/29062627/26583502/1ad48590-4563-11e7-8224-15d580254c5f.png">

Thanks
Subbu

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
