### ISSUE TITLE
VS2017DevEnvSearch does not find VS2017 if there are BuildTools installed.

### ISSUE THREAD

**Issue by jbialobr** [wixtoolset/issues#5597]
## Bugs

* Which version of WiX are you building with?

3.11.0.1528-rc2

* Which version of Visual Studio are you building with (if any)?

msbuild

* Which version of .NET are you building with?

v4.0.30319

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

10

* Describe the problem and the steps to reproduce it.

I add VS2017DEVENV propertyref to enable installing VSIX extension for VS 2017
`        <PropertyRef Id="VS2017DEVENV" />    `

The installer does not find VS2017 if there are BuildTools installed.

```
AppSearch: Property: VS2017DEVENV, Signature: VS2017DevEnvSearch
MSI (c) (34:70) [10:08:43:256]: Note: 1: 1322 2:  
MSI (c) (34:70) [10:08:43:256]: Note: 1: 1322 2:  
MSI (c) (34:70) [10:08:43:256]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (34:70) [10:08:43:256]: Note: 1: 1324 2: Common7\IDE 3: 1 
AppSearch: Property: VS2017_IDE_DIR, Signature: VS2017EnvironmentDirectorySearch
MSI (c) (34:70) [10:08:43:258]: PROPERTY CHANGE: Adding VS2017_IDE_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\'.
```
Full log: [BuildToolsInstalled.txt](https://github.com/wixtoolset/issues/files/1040677/BuildToolsInstalled.txt)

The installer finds VS2017 if the BuildTools are not installed.
```
AppSearch: Property: VS2017DEVENV, Signature: VS2017DevEnvSearch
MSI (c) (98:F8) [09:50:37:400]: Note: 1: 1322 2:  
MSI (c) (98:F8) [09:50:37:400]: Note: 1: 1322 2:  
MSI (c) (98:F8) [09:50:37:400]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (98:F8) [09:50:37:400]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (98:F8) [09:50:37:400]: PROPERTY CHANGE: Adding VS2017DEVENV property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\devenv.exe'.
AppSearch: Property: VS2017_IDE_DIR, Signature: VS2017EnvironmentDirectorySearch
MSI (c) (98:F8) [09:50:37:401]: PROPERTY CHANGE: Adding VS2017_IDE_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\'.
```
Full log: [NoBuildTools.txt](https://github.com/wixtoolset/issues/files/1040694/NoBuildTools.txt)

* Describe the behavior you expected and how it differed from the actual behavior.

The installer should find VS2017 regardless the BuildTools are installed.

**Comment by heaths** [comment]
Seems the recent support I added should've filtered to just the VS product IDs a la https://github.com/Microsoft/vswhere.

**Comment by heaths** [comment]
I'll take this one.

**Comment by Raphy23** [comment]
Any updated on this?

**Comment by heaths** [comment]
This was checked in back on May 31st in commit 67b0389ad257ef32995d3909a069da39b501e45f. @barnson, could you close this issue? Seems it didn't auto-close.

**Comment by Raphy23** [comment]
This still happens using Wix Toolset 3.11.0.1701:

With BuildTools:
```
AppSearch: 
MSI (c) (20:9C) [11:54:58:600]: Note: 1: 1325 2: Extensions 
MSI (c) (20:9C) [11:54:58:600]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (20:9C) [11:54:58:600]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (20:9C) [11:54:58:601]: PROPERTY CHANGE: Adding VS2017_EXTENSIONS_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\Extensions\'.
AppSearch: 
MSI (c) (20:9C) [11:54:58:601]: PROPERTY CHANGE: Adding VS2017_IDE_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\'.
```
And without BuildTools:
```
AppSearch: 
MSI (c) (98:64) [14:11:19:243]: Note: 1: 1325 2: Extensions 
MSI (c) (98:64) [14:11:19:243]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (98:64) [14:11:19:243]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (98:64) [14:11:19:243]: PROPERTY CHANGE: Adding VS2017_EXTENSIONS_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\Extensions\'.
AppSearch: 
MSI (c) (98:64) [14:11:19:243]: PROPERTY CHANGE: Adding VS2017_IDE_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\'.
```

**Comment by heaths** [comment]
Please run the following and paste the output (`| clip` will put it in the clipboard):

```
"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -format json | clip
```

If you don't have _vswhere_ there, it means you have an old Visual Studio. You can download the EXE from https://github.com/Microsoft/vswhere/releases.

**Comment by Raphy23** [comment]
```
[
  {
    "instanceId": "c7fd35d6",
    "installDate": "2017-10-17T13:53:29Z",
    "installationName": "VisualStudio/15.4.0+27004.2002",
    "installationPath": "D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional",
    "installationVersion": "15.4.27004.2002",
    "productId": "Microsoft.VisualStudio.Product.Professional",
    "productPath": "D:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\devenv.exe",
    "isPrerelease": false,
    "displayName": "Visual Studio Professional 2017",
    "description": "Professional developer tools and services for small teams",
    "channelId": "VisualStudio.15.Release",
    "channelPath": "C:\\Users\\rafael\\AppData\\Local\\Microsoft\\VisualStudio\\Packages\\_Channels\\4CB340F5\\catalog.json",
    "channelUri": "https://aka.ms/vs/15/release/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660692#15.4.0",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660708",
    "catalog": {
      "buildBranch": "d15svc",
      "buildVersion": "15.4.27004.2002",
      "id": "VisualStudio/15.4.0+27004.2002",
      "localBuild": "build-lab",
      "manifestName": "VisualStudio",
      "manifestType": "installer",
      "productDisplayVersion": "15.4.0",
      "productLine": "Dev15",
      "productLineVersion": "2017",
      "productMilestone": "RTW",
      "productMilestoneIsPreRelease": "False",
      "productName": "Visual Studio",
      "productPatchVersion": "0",
      "productPreReleaseMilestoneSuffix": "6.0",
      "productRelease": "RTW",
      "productSemanticVersion": "15.4.0+27004.2002"
    },
    "properties": {
      "campaignId": "168654337.1504175679",
      "channelManifestId": "VisualStudio.15.Release/15.4.0+27004.2002",
      "defaultProgram": "VisualStudio.c7fd35d6",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
    }
  }
]
```

This is the same output when running the command with and w/o BuildTools installed.
Update: This problem also happened with SQL installed:
```
AppSearch: Property: VS2017_EXTENSIONS_DIR, Signature: VS2017ExtensionsDirectorySearch
MSI (c) (5C:90) [15:32:41:902]: Note: 1: 1325 2: Extensions 
MSI (c) (5C:90) [15:32:41:902]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (5C:90) [15:32:41:902]: Note: 1: 1324 2: Common7\IDE 3: 1 
MSI (c) (5C:90) [15:32:41:903]: PROPERTY CHANGE: Adding VS2017_EXTENSIONS_DIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio\2017\SQL\Common7\IDE\Extensions\'.
```
It works fine when only VS is installed.

**Comment by heaths** [comment]
I don't see Build Tools registered at all, meaning it shouldn't be found. Just run _vswhere_ with no parameters and copy/paste the version header.

**Comment by Raphy23** [comment]
Visual Studio Locator version 2.2.11+gf1a9c6c78d [query version 1.14.187.27757]
Copyright (C) Microsoft Corporation. All rights reserved.

Could there be something missing in the installer that targets BuildTools/SQL when they are installed?

**Comment by heaths** [comment]
The query APIs read information created by the installer. _vswhere_ uses those query APIs and you have the latest version with the latest released version of the query APIs (installed by the installer). But with no results for Build Tools in the output, I'm not sure how it's being found.

Can you run https://aka.ms/vscollect.exe and attach %TEMP%\vslogs.zip to this thread?

**Comment by Raphy23** [comment]
[vslogs.zip](https://github.com/wixtoolset/issues/files/1578888/vslogs.zip)

**Comment by heaths** [comment]
I do see two instances without error. Unless the commit didn't get built into the binaries you have, could you confirm that you're using the same version of the _WixVSExtension.dll_ extension as the _WixTasks.dll_ you're using to build? Build Tools is the latest version, but I added code to only pick Community, Professional, or Enterprise (as shown in the commit) so Build Tools shouldn't even be considered.

**Comment by Raphy23** [comment]
Both are the same version: 3.11.0.1701. 
Is there some instruction/code that might be missing that could cause the installer to target non-VS directories?

**Comment by heaths** [comment]
The commit I referenced considers only the three VS SKUs, so unless that's not working or the code somehow didn't make it in (merge problem) it should be working.

I'll need to repro this. It would help eliminate doubts if in your same environment you could build a simple example MSI using the extension (eg. just install a file somewhere but use the extension so we can see it's effects on the log). With your instance data I can then debug through it.
