### ISSUE TITLE
Custom Action fails to build after upgrading to the stable version of WiX 3.11

### ISSUE THREAD

**Issue by pateljeel** [wixtoolset/issues#5598]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

v3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

Visual Studio 17 and or Visual studio 15

* Which version of .NET are you building with?

.NET 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

I Installed the latest version of the WiX toolset which is 3.11 from the website and installed the appropriate extensions from the Visual Studio Marketplace. This extension was installed within each version of Visual Studio. Selected my Custom Action project and clicked build and it errors our packaging the files: 

1>------ Build started: Project: Scf.Mcf.CustomAction, Configuration: Debug Any CPU ------
1>  Searching for custom action entry points in Scf.Mcf.CustomAction.dll
1>      Loaded dependent assembly: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
1>      Loaded dependent assembly: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll
1>      Loaded dependent assembly: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll
1>      Loaded dependent assembly: C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Scf.Installer.dll
1>      Loaded dependent assembly: C:\Program Files (x86)\WiX Toolset v3.11\SDK\Microsoft.Deployment.WindowsInstaller.dll
1>      Commit=Scf.Mcf.CustomAction!Scf.Mcf.CustomAction.CustomActions.Commit
1>      Install=Scf.Mcf.CustomAction!Scf.Mcf.CustomAction.CustomActions.Install
1>      Rollback=Scf.Mcf.CustomAction!Scf.Mcf.CustomAction.CustomActions.Rollback
1>      Uninstall=Scf.Mcf.CustomAction!Scf.Mcf.CustomAction.CustomActions.Uninstall
1>  Searching for an embedded UI class in Scf.Mcf.CustomAction.dll
1>  Modifying SfxCA.dll stub
1>  Copying file version info from C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\obj\Debug\Scf.Mcf.CustomAction.dll to C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\obj\Debug\Scf.Mcf.CustomAction.CA.dll
1>  Packaging files
1>EXEC : error : Could not find file 'C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\CustomAcion.config'.
1>C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets(156,5): error MSB3073: The command ""C:\Program Files (x86)\WiX Toolset v3.11\bin\..\sdk\MakeSfxCA.exe" "C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\obj\Debug\Scf.Mcf.CustomAction.CA.dll" "C:\Program Files (x86)\WiX Toolset v3.11\bin\..\sdk\x86\SfxCA.dll" "C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\obj\Debug\Scf.Mcf.CustomAction.dll" "C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Data.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Database.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Identity.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.SQLite.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Windows.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\EntityFramework.6.1.3\lib\net45\EntityFramework.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\EntityFramework.6.1.3\lib\net45\EntityFramework.SqlServer.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\Microsoft.AspNet.Identity.Core.2.2.1\lib\net45\Microsoft.AspNet.Identity.Core.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\Microsoft.AspNet.Identity.EntityFramework.2.2.1\lib\net45\Microsoft.AspNet.Identity.EntityFramework.dll;C:\Program Files (x86)\WiX Toolset v3.11\SDK\Microsoft.Deployment.WindowsInstaller.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\Newtonsoft.Json.10.0.1\lib\net45\Newtonsoft.Json.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Scf.Installer.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Api.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Common.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Data.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Data.Model.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.HostFile.Data.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.HostFile.Data.Model.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.MessageSubscriber.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Sdk\Scf.Mcf.Sdk.TestSubscribers\bin\Scf.Mcf.Sdk.TestSubscribers.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Security.Model.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\System.Data.SQLite.Core.1.0.104.0\lib\net46\System.Data.SQLite.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\System.Data.SQLite.EF6.1.0.104.0\lib\net46\System.Data.SQLite.EF6.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\NuGetPackages\System.Data.SQLite.Linq.1.0.104.0\lib\net46\System.Data.SQLite.Linq.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Bss.Wpf.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Telerik.Windows.Controls.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\GalaSoft.MvvmLight.Platform.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\GalaSoft.MvvmLight.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Scf.Common.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\AutoMapper.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\protobuf-net.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Microsoft.Practices.Unity.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.MessageTransport.Common.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Message.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.MessageTransport.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.Deployment.WindowsInstaller.Linq.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.SqlServer.ConnectionInfo.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.SqlServer.Smo.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.SqlServer.SmoExtended.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.SqlServer.SqlEnum.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Telerik.Windows.Controls.Navigation.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\System.Windows.Interactivity.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Telerik.Windows.Controls.GridView.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Telerik.Windows.Data.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Microsoft.Practices.ServiceLocation.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.SqlServer.SqlClrProvider.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Microsoft.SqlServer.Management.Sdk.Sfc.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Telerik.Windows.Controls.Input.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\de\Telerik.Windows.Controls.resources.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\es\Telerik.Windows.Controls.resources.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\fr\Telerik.Windows.Controls.resources.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\it\Telerik.Windows.Controls.resources.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\nl\Telerik.Windows.Controls.resources.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\tr\Telerik.Windows.Controls.resources.dll;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Sdk\Scf.Mcf.Sdk.TestPublisher\bin\Scf.Mcf.Sdk.TestPublisher.exe;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\obj\Debug\Scf.Mcf.CustomAction.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Scf.Installer.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Api.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Common.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Data.Model.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Data.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.HostFile.Data.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.HostFile.Data.Model.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.MessageSubscriber.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Security.Model.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Sdk\Scf.Mcf.Sdk.TestPublisher\bin\Scf.Mcf.Sdk.TestPublisher.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Sdk\Scf.Mcf.Sdk.TestSubscribers\bin\Scf.Mcf.Sdk.TestSubscribers.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Data.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Database.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Identity.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.SQLite.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Bss\bin\Bss.Windows.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Bss.Wpf.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\GalaSoft.MvvmLight.Platform.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\GalaSoft.MvvmLight.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Installer\bin\Scf.Common.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.MessageTransport.Common.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.Message.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Scf.Mcf.MessageTransport.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\bin\Microsoft.Practices.ServiceLocation.pdb;C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\CustomAction.config"" exited with code 1.
========== Build: 0 succeeded, 1 failed, 16 up-to-date, 0 skipped ==========

As you can see, it drops a random character from the path and errors out saying cannot find the file 
1>EXEC : error : Could not find file 'C:\TFS_LOCAL\SES ADID\GOMS\A\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\CustomAcion.config'. (dropped the 't' from 'CustomAction.config')

* Describe the behavior you expected and how it differed from the actual behavior.

I expected the custom action to build without any errors. 

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please attach your .csproj.

**Comment by pateljeel** [comment]
[Scf.Mcf.CustomAction.txt](https://github.com/wixtoolset/issues/files/1041979/Scf.Mcf.CustomAction.txt)

**Comment by barnson** [comment]
You might be running into command-line length limit. Try using a shorter path.

**Comment by pateljeel** [comment]
Did anything change in the wix.ca.targets file? Same project builds fine from Visual Studio when I downgrade to 3.10.3

**Comment by barnson** [comment]
Sure, lots. But nothing that should change behavior of MakeSfxCA.

**Comment by pateljeel** [comment]
What do you suggest we do besides using a shorter path? I don't know why it works flawlessly in 3.10.3 but fails in 3.11

**Comment by rseanhall** [comment]
This looks bad

> EXEC : error : Could not find file 'C:\TFS_LOCAL\SES ADID\GOMS\Army\Dev\Patel\2\Src\Scf\Mcf\Scf.Mcf.CustomAction\CustomAcion.config'

And there probably should be a slash after bin in the path

> "C:\Program Files (x86)\WiX Toolset v3.11\bin..\sdk\MakeSfxCA.exe"

**Comment by pateljeel** [comment]
Hmm did not notice that the slash was missing after bin.. good catch! What can I do to fix that?

**Comment by pateljeel** [comment]
Any updates on this issue?

**Comment by barnson** [comment]
This isn't a general problem so it's something particular with your configuration. For example, if you're specifying `WixToolPath`, you need to end it in a backslash. You might also look at a new custom action project created from VS templates to see changes to support VS2017 MSBuild.

If you can narrow down the problem, you might get help from the [wix-users mailing list][ml].

If discussion there points to a bug, please open a new one here.

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by icnocop** [comment]
This is a duplicate of https://github.com/wixtoolset/issues/issues/4688, which has work-arounds.
