### ISSUE TITLE
The WiX Toolset v3.11 (or newer) build tools must be installed to build this project

### ISSUE THREAD

**Issue by roblugt** [wixtoolset/issues#5599]
We are getting an error after installing the latest version (0.9.21) of the Visual Studio extension on a build server

> The  WiX Toolset v3.11 (or newer) build tools must be installed to build this project

Of course we do have v3.11 of the build tools installed.  We are using Visual Studio 2017 Professional.

We do not see the same error on developer workstations.  After some investigation we realised that the developer workstations were using an older version  of the VS extension (0.9.10) which has a different test condition in the wix.targets file.

The erroring line in wix.targets in 0.9.21 looks like this

    <Target Name="EnsureActualWixToolsetInstalled" Condition=" '$(WixTargetsImported)' != 'true' ">
 
Whereas 0.9.10 has a different condition

    <Target Name="EnsureActualWixToolsetInstalled" Condition=" !Exists('$(WixMSBuildFolder)wix.targets') ">

We have been able to bypass the problem by (temporarily) editing the wix.targets file to look like version 0.9.10.

**Comment by barnson** [comment]
That almost always means you're not using the RTM build of WiX v3.11. If you are, please open a new issue filling out the template, as it asks important questions.
