### ISSUE TITLE
Unable to install Wix Extensions for Visual Studio 2017

### ISSUE THREAD

**Issue by nicolijohn** [wixtoolset/issues#5600]
Installed Votive2017 on a windows 10 box for use with Visual Studio 2017 Enterprise, After a few months, a notice appeared saying there was an update for that  extension in visual studio. I ran the update and it failed. It doesn't determine that Visual Stuio 2017 is on machine and it fails. I can no longer work on any of my  projects due to the fact Visual Studio doesn't recognize the project type. Below is the text in from the failed log 

5/31/2017 2:41:07 PM - Microsoft VSIX Installer
5/31/2017 2:41:07 PM - -------------------------------------------
5/31/2017 2:41:07 PM - Initializing Install...
5/31/2017 2:41:07 PM - Extension Details...
5/31/2017 2:41:07 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev15
5/31/2017 2:41:07 PM - 	Name               : Wix Toolset Visual Studio 2017 Extension
5/31/2017 2:41:07 PM - 	Author             : .NET Foundation and contributors
5/31/2017 2:41:07 PM - 	Version            : 0.9.21.62588
5/31/2017 2:41:07 PM - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
5/31/2017 2:41:07 PM - 	Locale             : en-US
5/31/2017 2:41:07 PM - 	MoreInfoURL        : http://wixtoolset.org/
5/31/2017 2:41:07 PM - 	InstalledByMSI     : False
5/31/2017 2:41:07 PM - 	SupportedFrameworkVersionRange : [4.0,)
5/31/2017 2:41:07 PM - 
5/31/2017 2:41:07 PM - 	SignatureState     : Unsigned
5/31/2017 2:41:07 PM - 	Supported Products : 
5/31/2017 2:41:07 PM - 		Microsoft.VisualStudio.Community
5/31/2017 2:41:07 PM - 			Version : [15.0,16.0)
5/31/2017 2:41:07 PM - 
5/31/2017 2:41:07 PM - 	References         : 
5/31/2017 2:41:07 PM - Signature Details...
5/31/2017 2:41:07 PM - 	Extension is not signed.
5/31/2017 2:41:07 PM - 
5/31/2017 2:41:07 PM - Searching for applicable products...
5/31/2017 2:41:07 PM - Found installed product - Microsoft Visual Studio Ultimate 2012
5/31/2017 2:41:07 PM - Found installed product - Microsoft Visual Studio Premium 2012 
5/31/2017 2:41:07 PM - Found installed product - Microsoft Visual Studio Professional 2012
5/31/2017 2:41:07 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
5/31/2017 2:41:07 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
5/31/2017 2:41:08 PM - Found installed product - Microsoft Visual Studio Professional 2015
5/31/2017 2:41:08 PM - Found installed product - Microsoft Visual Studio Community 2015
5/31/2017 2:41:08 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/31/2017 2:41:08 PM - Found installed product - Global Location
5/31/2017 2:41:08 PM - Found installed product - ssms
5/31/2017 2:41:08 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

I am currently using Wix Toolset v3.11.0.1507 on a windows 10 machine and Visual Studio 2017 has all the current updates installed.

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

**Comment by nicolijohn** [comment]
Thanks Rob

**Comment by sharpe5** [comment]
I had exactly the same issue. Upgraded to Visual Studio 2017 v15.5 from v15.4, and then it installed successfully.
