### ISSUE TITLE
Unable  to install windows service with network permissions

### ISSUE THREAD

**Issue by orochies** [wixtoolset/issues#5603]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
> WiX version 3.11.1701

* Which version of Visual Studio are you building with (if any)?

> Visual Studio version 2015 14.0.25431 update 3

* Which version of .NET are you building with?

> .NET version 4.5.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows version 8.0

* Describe the problem and the steps to reproduce it.

> when installing msi say: Service could not be installed. Verify that you have sufficient privileges to install system services

* Describe the behavior you expected and how it differed from the actual behavior.

> service installed and running

check de code:

`xml`

      <Component Id="PrintServiceWin.exe" Guid="{EDE7187E-25E9-40B3-9CF5-9DA2FC68BE24}">
        <File Id="PrintServiceWin.exe" KeyPath="yes" Source="$(var.SourceDir)\PrintServiceWin.exe" />
        <ServiceInstall Id="ServiceInstaller"
          Account="[WIX_ACCOUNT_NETWORKSERVICE]"
          Name="PrintServer"
          DisplayName="$(var.Name)"
          Description="Print Service"
          Interactive="yes"
          Vital="yes"
          Type="ownProcess"
          Start="auto"
          ErrorControl="critical">
        </ServiceInstall>
        <ServiceControl Id="StartService" Start="install" Stop="both" Remove="uninstall" Name="AsetecPrintServer" Wait="yes" />
      </Component>

help me please, many days with this bug.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
