### ISSUE TITLE
MSBuild Tools 14 dependency

### ISSUE THREAD

**Issue by virzak** [wixtoolset/issues#5604]
Wix 3.11

I have a clean machine with only VS 2017 and the error I'm getting is:

heat.exe : error HEAT5316 : Failed to load MSBuild wrapper object: Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

After installing VS2015 everything works fine.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/5490
