### ISSUE TITLE
Installer shows [1], [2], [3] instead of file names, directories, sizes etc.

### ISSUE THREAD

**Issue by vvitkovsky** [wixtoolset/issues#5605]
After the latest Windows 10 update all installers made by WiX show [1], [2], [3] intead of correct file names, directory name or file size (please see attached screenshot).

![wix](https://cloud.githubusercontent.com/assets/24652637/26772445/1ad936b6-49ce-11e7-98a9-cf96c6302b49.png)

We use WiX 3.11.0.1701 release.

How this can be solved? 
Best regards, 
Victor

**Comment by robmen** [comment]
Follow up with Windows? They control the actual installation engine. WiX Toolset helps you build the installation packages.
