### ISSUE TITLE
Simple setup bug

### ISSUE THREAD

**Issue by ChuckSavage** [wixtoolset/issues#5610]
From the page - http://wixtoolset.org/documentation/manual/v3/votive/authoring_first_votive_project.html

Copied and pasted, changing MyApplication to ToClipboard, the name of my project `<File Source="$(var.MyApplication.TargetPath)" />` and get the following error on build

Severity	Code	Description	Project	File	Line	Suppression State
Error		The ComponentGroup element contains an unexpected child element 'File'.	WiXv3_Setup	C:\Users\chuck\Documents\csharp\JumpList_To_Clipboard\WiXv3_Setup\Product.wxs	27	

Might want to update the docs with the default Product.wxs file, so a beginner can follow it and not get errors. There's no longer a "Windows Installer XML node in the Project types tree, then select Setup Project", now there are Setup Project for WiX v3 and Setup Project for WiX v4. And other options v3 vs v4's.

I'm working from the Setup Project for WiX v3, since I couldn't find any documentation for v4. Why is it even an option in Visual Studio if there are no docs for it?

I had to fill in Manufacture="" with my company name, since it also errored on Manufacture having an empty string.

Here's the whole file as is:

```
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
	<Product Id="*" Name="WiXv3_Setup" Language="1033" Version="1.0.0.0" Manufacturer="SeaRisen LLC" UpgradeCode="71b53809-790d-483b-8ce8-d8f52c746b22">
		<Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" />

		<MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
		<MediaTemplate />

		<Feature Id="ProductFeature" Title="WiXv3_Setup" Level="1">
			<ComponentGroupRef Id="ProductComponents" />
		</Feature>
	</Product>

	<Fragment>
		<Directory Id="TARGETDIR" Name="SourceDir">
			<Directory Id="ProgramFilesFolder">
				<Directory Id="INSTALLFOLDER" Name="WiXv3_Setup" />
			</Directory>
		</Directory>
	</Fragment>

	<Fragment>
		<ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
			<!-- TODO: Remove the comments around this Component element and the ComponentRef below in order to add resources to this installer. -->
			<!-- <Component Id="ProductComponent"> -->
				
      <File Source="$(var.ToClipboard.TargetPath)" />
			<!-- </Component> -->
		</ComponentGroup>
	</Fragment>
</Wix>

```

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/4612
