### ISSUE TITLE
What can cause subdirectory accidentally change the parent from VS2013_ROOT_FOLDER to TARGETDIR?

### ISSUE THREAD

**Issue by Typemock** [wixtoolset/issues#5611]
## Bugs

* Which version of WiX are you building with? 

> 3.10.0.2103

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Sorry for the lack of information, but we don't know. It happened on the client side. And don't think it depends on the windows version.

* Describe the problem and the steps to reproduce it.

>We have a part in installer, which are integrating with visual studio (10, 12, 13, 15, 17).  In order to do that we are adding some files in the extensions folder. For all visual studio it looks like this:

Directory Id="VS2013_ROOT_FOLDER"
        Directory Id="Common7_13" Name="Common7"
          Directory Id="IDE_13" Name="IDE"
            Directory Id="Extensions_13" Name="Extensions"
              Directory Id="VS_13_TYPEMOCK_EX" Name="Typemock"
                Directory Id="VS_13_AUTORUNNER_EX" Name="Typemock Extension"
                  Directory Id="VS_13_AUTORUNNER_EX_VERSION" Name="$(var.MajorAndMinorVersion)"

And then adding the component and doesn't matter in this case.

So with all Visual Studios except 13 it was ok, but with 13 (with install logs on):

 MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: VS2013_ROOT_FOLDER	, Object: C:\Program Files (x86)\Microsoft Visual Studio 12.0\
MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: Common7_13	, Object: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\
MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: IDE_13	, Object: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\
MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: Extensions_13	, Object: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\
MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: VS_13_TYPEMOCK_EX	, Object: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Typemock\
MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: VS_13_AUTORUNNER_EX	, Object: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\Extensions\Typemock\Typemock Extension\
MSI (c) (A0:9C) [15:58:57:390]: Dir (target): Key: VS_13_AUTORUNNER_EX_VERSION	, Object: C:\Program Files (x86)\Typemock\Isolator\8.6\Common7\IDE\Extensions\Typemock\Typemock Extension\8.6\

* Describe the behavior you expected and how it differed from the actual behavior.

> I would like to know, why it happened, and what can we do to avoid it in future.

Kind regards,
Eva

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
