### ISSUE TITLE
Consider changing all .NET download URLs to HTTPS in NetFx Extension

### ISSUE THREAD

**Issue by VonOgre** [wixtoolset/issues#5615]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> When installing with a custom managed bootstrapper application and including any of the NetFx package groups in the chain on an environment with IE Enhanced Security enabled and/or has not permanently dismissed the IE warning for going from http -> https (e.g. after initial install and config of Windows Server 2012 or newer), the installation will fail due to being unable to retrieve the file. Targeting the https protocol for the go.microsoft.com URLs does work for all downloads and would remove the protocol change on redirect.

* Describe how you're accomplishing the feature today (if possible).

> We manually copied the NetFx462Redist package group definition and all supporting bits to our implementation, changed the download URLs to https and added "Secure" to the end of the package group ID to separate it from the original.

* Describe what you'd like the new feature to do.

> Either change the URLs in the NetFx extension to target the https protocol for each download URL or leave the originals alone and add "Secure" variants of each package group that do target the https variant of each URL.

**Comment by jozefizso** [comment]
I think we hit this bug on Windows Server 2012 as bootstrapper was failing on clean installations of the Server and admin did not run IE yet.
