### ISSUE TITLE
Feature request: Support modify/change action in WixStdBA for msi packages with DisplayInternalUI="yes".

### ISSUE THREAD

**Issue by aleksandr-grechko** [wixtoolset/issues#5616]
## Feature request: Support modify/change action in WixStdBA for msi packages with DisplayInternalUI="yes".

* Describe the scenario and benefits that the feature supports.

> We use WIX to create msi package with complex UI and several features. Also we use Wix standard BA to install some prerequisites and our msi package. We need to allow a user to install\uninstall features for already installed product. We can't use EnableFeatureSelection and custom bootstrapper because feature selection should be done on msi internal UI.

* Describe how you're accomplishing the feature today (if possible).

> Some time ago we forked Wix3 and added quite simple changes (https://github.com/aleksandr-grechko/wix3/commit/6974673b10f6168be2e21aeec47b4c74b05945c5) to Wix standard BA (handler for modify/change button) and Burn engine (force modify action for msi packages with DisplayInternalUI) to support this functionality.
These changes have been working in our production more than a year. 

* Describe what you'd like the new feature to do.

> I understand that our changes are specific and they most likely can not be added as is. For more flexibility we can add, for example, new attribute "ShowModify" for WixStandardBootstrapperApplication element and new attribute "ForceModify" for MsiPackage element.
I can implement this feature in case you approve it.

**Comment by barnson** [comment]
Burn doesn't show UI for maintenance mode operations because the user could do something in the UI that's contrary to the planned action (e.g., uninstall the package during a modify). `DisplayInternalUI` is a workaround and has a lot of limitations that can't be avoided.

**Comment by aleksandr-grechko** [comment]
@barnson From my point of view user can do only what developer lets him to do. In maintenance UI of our installer user can only install/remove features, user even cannot remove all features. This feature successfully works in our projects. But it would more convenient for us if it will be include to WiX. 
I suppose my proposition can decrease limitations of DisplayInternalUI.

**Comment by rseanhall** [comment]
This is possible in v4.0 through https://github.com/wixtoolset/issues/issues/6164.
