### ISSUE TITLE
Add search to v3 WiX manual

### ISSUE THREAD

**Issue by elinaru** [wixtoolset/issues#5618]
I’m a UX designer preparing mock-ups for a new installer. I’m not the developer who will be building the installer; I’m just designing it and preparing image assets. 

Using the table of contents alone, it’s difficult to find any guidance on preparing images for use in the installer in the [WiX manual](http://wixtoolset.org/documentation/manual/v3/). Being able to search the manual would be a big help. Downloading the entire manual as a PDF would work as well.

**Comment by ardley** [comment]
I too support making this a top-priority issue.  This is clearly an issue.

**Comment by kmackey1** [comment]
This should be a high priority. It's very difficult to find what you need without search. This has bothered me for a while and I should have reported it

**Comment by barnson** [comment]
The wix.chm help file is fully searchable and you could always use site search from Google or Bing.

**Comment by elinaru** [comment]
Where can I find the wix.chm file?

**Comment by barnson** [comment]
It's installed with WiX.

**Comment by elinaru** [comment]
Can I download it without installing Wix?

**Comment by barnson** [comment]
It might be in the binaries .zip file as well.
