### ISSUE TITLE
Running heat.exe -pog binaries on a project with typescript 2.3.3 fails

### ISSUE THREAD

**Issue by Serivy** [wixtoolset/issues#5620]
* Which version of WiX are you building with?
> 3.11.0.1701 Nuget

* Which version of Visual Studio are you building with (if any)?
> Visual Studio Enterprise 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> 0.9.21.62588

* Which version of .NET are you building with?
> 4.6.1

* Describe the problem and the steps to reproduce it.
> When harvesting occurs on our web project (using heat.exe -pog Binaries) using the latest typescript (2.3.3) nuget package, it will throw the error. I understand this is could be blamed on typescript but I think they are just one of the first to push for .net core tooling in packages. It may be related to https://github.com/wixtoolset/issues/issues/5490
The error is:
heat.exe : error HEAT5313 : Build error during harvesting: D:\HeatIssue\packages\Microsoft.TypeScript.MSBuild.2.3.3\tools\Microsoft.TypeScript.targets(172,5): The "TypeScript.Tasks.CheckFileSystemCaseSensitive" task could not be loaded from the assembly D:\HeatIssue\packages\Microsoft.TypeScript.MSBuild.2.3.3\build\\..\tools\net45\TypeScript.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
The old version of typescript (2.2) worked fine, in this new version they appear to bundle a version of System.IO.FileSystem.dll for the net45 framework as they should be able to. I am ultimately looking for a fix, but for now a workaround will do. Looking through heat source code, unfortunately it doesn’t look like it sets any custom properties i can use to identify it is a heat build. If it did when evaluating the .csproj i can put that condition manually on the import so heat ignores the problematic import entirely.

To replicate this scenario:
1) Create a new ASP.NET Web Application (.NET Framework) called 'WebApplication' at .Net Framework 4.6.1, select empty template and let it create.
2) Install the nuget wix package for toolkit: PM> Install-Package WiX -Version 3.11.0
3) Modify WebApplication.csproj to work on non 2017 projects (as my real world web application is) by changing '<Project ToolsVersion="12.0"' to '<Project ToolsVersion="4.0"' and if 'Microsoft.WebApplication.targets' gives you hassles (don't have an old sdk installed with heat) then add to the condition ' and false' or delete it for this example.
4) Run heat tool
PS D:\HeatIssue> .\packages\WiX.3.11.0\tools\heat.exe project WebApplication\WebApplication.csproj -out Output.wxs -pog Binaries
Windows Installer XML Toolset Toolset Harvester version 3.11.0.1701
Copyright (c) .NET Foundation and contributors. All rights reserved.
5) Output looks correct.
6) Install the second last version of typescript.
PM> Install-Package Microsoft.TypeScript.MSBuild -Version 2.2.2
7) Run heat, everything should still work.
PS D:\HeatIssue> .\packages\WiX.3.11.0\tools\heat.exe project WebApplication\WebApplication.csproj -out test.wxs -pog Binaries
8) Install latest version of typescript (2.3.3)
PM> Install-Package Microsoft.TypeScript.MSBuild -Version 2.3.3
(There may be some errors about unable to clean up old files due to in use, either restart or ignore it for this example, the csproj remains fine)
9) Run heat.exe again 
PS D:\HeatIssue>.\packages\WiX.3.11.0\tools\heat.exe project WebApplication\WebApplication.csproj -out Output.wxs -pog Binaries
Windows Installer XML Toolset Toolset Harvester version 3.11.0.1701
Copyright (c) .NET Foundation and contributors. All rights reserved.

heat.exe : error HEAT5313 : Build error during harvesting: D:\HeatIssue\packages\Microsoft.TypeScript.MSBuild.2.3.3\tools\Microsoft.TypeScript.targets(172,5): The "TypeScript.Tasks.CheckFileSystemCaseSensitive" task could not be loaded from the assembly D:\HeatIssue\packages\Microsoft.TypeScript.MSBuild.2.3.3\build\\..\tools\net45\TypeScript.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
heat.exe : error HEAT5307 : Build failed.

10) If I do not target binaries but instead content, it will pass
.\packages\WiX.3.11.0\tools\heat.exe project WebApplication\WebApplication.csproj -out Output.wxs -pog Content
Windows Installer XML Toolset Toolset Harvester version 3.11.0.1701
Copyright (c) .NET Foundation and contributors. All rights reserved.

* Describe the behavior you expected and how it differed from the actual behavior.
> I would like to be able to call heat.exe -pog Binaries (invoked via project harvesting on a wixlib) on a project with typescript 2.3.3 and get an output file.

**Comment by rseanhall** [comment]
The problem is here

> The "TypeScript.Tasks.CheckFileSystemCaseSensitive" task could not be loaded from the assembly D:\HeatIssue\packages\Microsoft.TypeScript.MSBuild.2.3.3\build\..\tools\net45\TypeScript.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

This means that you must set Project ToolsVersion to 14 so that WiX uses MSBuild 14 so that the TypeScript.Tasks.dll can be loaded.

For further questions, please contact the [wix-users mailing list](http://wixtoolset.org/documentation/mailinglist/).
