### ISSUE TITLE
 Subfolder "ConfigurationName(release or debug)" created in APPLICATIONROOTDIRECTORY, 

### ISSUE THREAD

**Issue by Jimmy2Fois** [wixtoolset/issues#5625]
Hello,

Since I upgraded from vs 2013 to vs 2015 using wix toolset 3.11, I have some issue.
I m using an environment var to define output path (APPLICATIONROOTDIRECTORY) since the upgrade : my MSI creates dll in [myEnvPath]\[ConfigurationName]
ConfigurationName (debug or release) is not needed ! 

Comparing  Product.wxs with old version => nothing change 

Below I pasted fragment concerning install dir configuration. 

thanks for your help
 

  <Fragment>
    <CustomAction Id="LaunchApp" Directory="APPLICATIONROOTDIRECTORY" ExeCommand="[APPLICATIONROOTDIRECTORY]\blabla.exe" Return="asyncNoWait"></CustomAction>

    
    <CustomAction
      Id="SetApplicationRootDirectory"
      Directory="APPLICATIONROOTDIRECTORY"
      Value="[%MyEnEnv]\bin\blabla\UI\" />

    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFilesFolder">
        
        <Directory Id="APPLICATIONROOTDIRECTORY" Name="DefaultFolderName" >

        </Directory>
        <Directory Id="DesktopFolder" Name="Desktop"/>
        <Directory Id="StartupFolder" Name="Startup" />
        </Directory>
    </Directory>

   <InstallUISequence>
      
      <Custom Action="SetApplicationRootDirectory" After="CostFinalize" />   
    </InstallUISequence>

    <InstallExecuteSequence>
      <Custom Action="LaunchApp" After="InstallFinalize">(NOT REMOVE="ALL")</Custom>
    </InstallExecuteSequence>
  
    <Property Id="WIXUI_INSTALLDIR" Value="APPLICATIONROOTDIRECTORY" />

  </Fragment>

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
