### ISSUE TITLE
Wix Hangs on saving a new project in VS2013

### ISSUE THREAD

**Issue by darbid** [wixtoolset/issues#5626]
I see that there is/was an issue with VS2015 [https://github.com/wixtoolset/issues/issues/5613](url)

Wix Version - 3.11 (current stable version)
Extension as is available [https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2013Extension](url) here. 0.9.21.62588
Visual Studio 2013 Community - 12.0.40629 Update 5
Tried building with 4.0 up to 4.5.2

I simply create a new Wix Setup project and then choose SaveAll.  Upon saving VS just hangs and must be closed.

Tho only additional thing I can add to #5613 is that my PC is under Group Policy and Project settings / templates are saved to a special place, thus I am guessing that the Wix extension is trying to save something in an unusual place.

All other projects I have saved so far Win Forms / WPF / Office Addins do not have the same problem.

**Comment by darbid** [comment]
same work around as is noted here https://github.com/wixtoolset/issues/issues/3218 works.

CHANGE the Visual Studio option for Projects and Solutions -> Save new projects when created to CHECKED

**Comment by barnson** [comment]
Dup of https://github.com/wixtoolset/issues/issues/3218.

**Comment by darbid** [comment]
well it kinda is a dup.  One however might hope that something has changed between VS2010 and my issue with VS2013.  Also the add-on for wix has a different file for each version of VS.

**Comment by barnson** [comment]
It's the same code. Having multiple issues for the same underlying bug isn't helpful.
