### ISSUE TITLE
Using DependencyExtension can lead to incomplete uninstall

### ISSUE THREAD

**Issue by jh1r15** [wixtoolset/issues#5629]
* Which version of WiX are you building with?

> 3.10.3.3007

* Which version of Visual Studio are you building with (if any)?

> 2015 Enterprise

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

I created an MSI with Wix. After some time, it exists in different versions. This means - according to the best practices found in different places - to change the Product/Id and the Product/Version, while leaving Product/UpgradeCode fixed.

I use this MSI in two different Burn bootstrappers B1 and B2 (amongst other, uninteresting packages):
<MsiPackage Id="mymsi" SourceFile="..../MyMsi.msi" Visible="yes"/>

Over the time, also here new versions may arrive. Those new versions might also bring newer versions of the included MSI! Whenever that happens, the Wix bookkeeping about dependencies seems to break, resulting in uninstalling MSI when it shouldn't:

1. Install B1 version 1.0.0.0, including MyMsi 1.0.0.0
2. Install B2 version 2.0.0.0, including MyMsi 2.0.0.0
3. Uninstall B2.

This completely removes MyMsi, although it's still required by B1. After some research about the backgrounds, I used DependencyExtension for setting a fixed provider key inside a component in MyMsi:

<Component Id="providerkey" Guid="{...}">
<dep:Provides Key="mykey"/>
</Component>

This fortunately doesn't uninstall MSIs early. But with this code added, the uninstall seems too weak instead. When I uninstall both B1 and B2, it depends on the order if MyMsi actually disappears in the end (this is the behavior I expect), or if it remains.

**Comment by barnson** [comment]
Please attach logs demonstrating the problem.

**Comment by jh1r15** [comment]
[logs5629.zip](https://github.com/wixtoolset/issues/files/1111384/logs5629.zip)
The archive contains all logs. The subdir 'install' contains logs from the installation. 'uninstall_clean' contains the log from the benign uninstallation order, 'uninstall_unclean' contains the order, which shows the issue.

**Comment by barnson** [comment]
I don't see anything odd in the logs. Please highlight what you're concerned about.

**Comment by jh1r15** [comment]
My expectation: The shared package MyMsi gets uninstalled after I uninstall B1 and B2.

What I encounter (with DependencyExtension used): Depending on the order of uninstalling B1 and B2, MyMsi remains installed.

**Comment by barnson** [comment]
The `uninstall_unclean` logs show expected behavior: The package isn't removed until both bundles are uninstalled:

    [1EF4:0E30][2017-06-29T01:42:08]i326: Removed dependency: {b5a5d24d-0f24-41c3-a226-62b0b1f7179b} on package provider: 126d3a99-6e09-4ff0-8679-49c501edcc69, package mymsi1.msi
    ...
    [204C:1124][2017-06-29T01:42:16]i326: Removed dependency: {aec20126-6601-43c3-aff7-87dc34e9ffaf} on package provider: 126d3a99-6e09-4ff0-8679-49c501edcc69, package mymsi2.msi
    [204C:1124][2017-06-29T01:42:16]i301: Applying execute package: mymsi2.msi, action: Uninstall, path: (null), arguments: ' MSIFASTINSTALL="7"'

For support using WixDependencyExtension, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by jh1r15** [comment]
Ehh... The package **isn't removed at all**!

**Comment by jh1r15** [comment]
@barnson Can you please re-open the ticket or tell me why you just closed it?

**Comment by barnson** [comment]
The default behavior, without manually authored dependency data, works as expected. For support using WixDependencyExtension, please contact the [wix-users mailing list][ml] with details like what you authored.

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by heaths** [comment]
@jh1r15 you should also check the MSI log. Burn is showing the right action plan, so if the MSI isn't removed it's probably something specific to that MSI. Either way, wix-users is the place for general install problems.

**Comment by jh1r15** [comment]
@barnson The MSI log doesn't tell anything when Burn doesn't call it. As you can see, in the non-working case, there isn't any log for uninstalling MyMsi, since it never gets called by Burn.

This is what Burn tells in the working case about it's plan:

[08DC:13E4][2017-06-29T01:42:16]i201: Planned package: mymsi2.msi, state: Present, default requested: Absent, ba requested: Absent, execute: Uninstall, rollback: Install, cache: No, uncache: Yes, dependency: Unregister

... and in the non-working case:

[172C:0F4C][2017-06-29T01:44:25]i201: Planned package: mymsi1.msi, state: Obsolete, default requested: None, ba requested: None, execute: None, rollback: None, cache: No, uncache: Yes, dependency: Unregister

I'd wonder if this is intended behavior.
