### ISSUE TITLE
Wix upgrade issue with different digital signature of assembly

### ISSUE THREAD

**Issue by StevenZhou1985** [wixtoolset/issues#5631]
Dear Guys,
We are facing an upgrade issue of the installation. Our installer for product with 1.0 version consume an assembly which has test digital signature. Our installer for product with 1.1 version consume a same assembly which has official digital signature. The GUID in the installer is same for the assembly. 

The assembly cannot be installed when we upgrade our product from 1.0 to 1.1. We have verified that the upgrade will be successful from no signature to official signature and official signature to official signature. Since our 1.0 product was already shipped to consumer. 

We can provide a patch to consumer to update that assembly. But this is not a good way. I just want to seek help from you guys to see if there is any better way. For example, update GUID of the assembly in 1.1, we will try it. Appreciate if there is any help from you guys.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
