### ISSUE TITLE
error CNDL0150 : Undefined preprocessor variable '$(var.PIPELINE_VERSION)'.

### ISSUE THREAD

**Issue by irfspy** [wixtoolset/issues#5632]
Hi Team,

We are using Jenkins version 2.46 and Wix Toolset v3.11 for generating msi's. But we are getting the below issue:
12:06:25 [wix] Enable Debug: false
12:06:25 [wix] Detecting environment variables...
12:06:25 [wix] Found sources: 1
12:06:25 [wix] Initializing tools...
12:06:25 [wix] Compiler found.
12:06:25 [wix] Linker found.
12:06:25 [wix] Starting compile process...
12:06:25 [Proj] $ "C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe" -arch x64 ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** ******** -nologo -out D:\Proj\build\Demo.wixobj D:\Proj\build\Demo.wxs
12:06:25 Demo.wxs
12:06:25 D:\Proj\build\Demo.wxs(3) : error CNDL0150 : Undefined preprocessor variable '$(var.PIPELINE_VERSION)'.
12:06:25 [wix] Compiling failed.
12:06:25 [wix] Compiling failed.
12:06:25 Build step 'WIX Toolset' changed build result to FAILURE

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
