### ISSUE TITLE
Patch uninstallation requests for base msi source

### ISSUE THREAD

**Issue by sankethpb** [wixtoolset/issues#5635]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
  3.10.3 

* Which version of .NET are you building with?
.Net 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 7, 8 and 10.

* Describe the problem and the steps to reproduce it.

We use WIX 3.10.3 to build both our Base Msi and Patch Msp.

Supports Windows Installer version 301

Patch is build using Purely Wix method as documented.

Our analysis:
Base Msi contained a file named "Sample.dll" with version as 1.0.0.0 and language as "neutral". While building patch, WIX considered there was change to the contents of Sample.dll but the version is retained as "1.0.0.0" and language as "neutral".

Sample.dll used for Patch creation, even though there was no change to the contents but some how we were able to identify there was binary change when compared with the base and the msp dlls used for creation. Refer below screenshot from Beyond Compare

Beyond Compare Snapshot of the DLL's included for MSI and MSP
https://i.stack.imgur.com/VX3RD.png

During installation of Base and then patch, as per Windows Installer File Versioning rules(https://msdn.microsoft.com/en-us/library/windows/desktop/aa368599(v=vs.85).aspx), the file "Sample.dll" was not re-installed by patch since the version and language are same. Hence while removal of patch, windows installer requested the source of the msi. This is causing uninstallation failures at our customers as the sources of the msi are not available during uninstall.

Here's a blog entry which said this issue is identified in Windows installer version 301 (https://blogs.msdn.microsoft.com/heaths/2007/06/28/unchanged-files-break-patch-uninstall).

We had already tried updating the installer version support to 405 in WIX and still the problem occurs.

**_Here the patch creation by WiX Toolset considers the Binary change between the base msi and patch msi to create the Msp whereas windows installer considers File versioning rules while installing._**

* Describe the behavior you expected and how it differed from the actual behavior.

Patch creation must work with same rules as MSI File versioning rules. 
Or is there any other option to fix this issue?

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by sankethpb** [comment]
I had contacted support list but haven't received any response. Also I feel that this is an issue with Wix toolset. Request to re open this issue.

**Comment by robmen** [comment]
Everything you've stated thus far sounds like you have issue with the Windows installer not with the WiX Toolset. If you find that the .MSP is being constructed incorrectly based on your .wxs files then that would be a bug in the WiX Toolset. However, the actual installation/uninstallation of patches is done by the Windows installer.

**Comment by sankethpb** [comment]
Here the patch creation by WiX Toolset considers the Binary change between the base msi and patch msi to create the Msp whereas windows installer considers File versioning rules while installing. So, here WiX says that there is a change in the file and adds it to MSP while creating, but Windows Installer says there is no change in the file and ignores it while installing. The rules used for creating a patch and rules used for installing patch seem to be different. So am not clear which has the issue here.
Could you please clarify?
