### ISSUE TITLE
Error building simple setup 

### ISSUE THREAD

**Issue by erikread** [wixtoolset/issues#5636]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.0.1701
> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?
2017 (15.2)
> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
2017 (0.9.21.62588)
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?
4.5.1-4.7
> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.
New install of Windows 10 Insider Preview 16232
Visual Studio 2017 ONLY
Create simple console app and installer.
Build solution.

Error		An unexpected Win32 exception with error code 0xEA occurred: Action - 'ICE01' More data is available	SetupProject1	light.exe	0		

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
This doesn't repro on Windows 10 CU. Please report this as a bug on wpdev or insider feedback so Windows knows they have a bug.

**Comment by robgoodwin** [comment]
I am seeing the same problem on 16232_rs_prerelease.170624-1334

**Comment by erikread** [comment]
Also occurs in 16241.

**Comment by soundsgood** [comment]
Yes, this has exeisted for a couple of releases now, and I don't think it should be dismissed as a Windows bug without someone actually looking into it.

**Comment by robmen** [comment]
First, the devs here do not test on pre-release builds of Windows. That simply isn't practical for the volunteers that actually fix bugs.

Second, that error message is coming from ICE01. The ICEs come from the Windows (via the SDK). We execute the code but the failure is internal to the Windows Installer's execution of static analysis.

Finally, there are thousands of installs of WiX v3.11 and the only reports of this issue (that I've seen) are on pre-release Windows. That *highly* suggests this is a Windows issue and something that they should be notified of via whatever pre-release channels you have.

**Comment by soundsgood** [comment]
Yes, I understand that. I’m only afraid that it *might* be a bug in Wix and that this will surface in the autumn when the next update for Win 10 is released.

I’m willing to test this on my system.

The only thing is that I’m running VS 2017, and I have problems building Wit on that version.


On 18 Jul 2017, at 8:43 AM, Rob Mensching <notifications@github.com<mailto:notifications@github.com>> wrote:


First, the devs here do not test on pre-release builds of Windows. That simply isn't practical for the volunteers that actually fix bugs.

Second, that error message is coming from ICE01. The ICEs come from the Windows (via the SDK). We execute the code but the failure is internal to the Windows Installer's execution of static analysis.

Finally, there are thousands of installs of WiX v3.11 and the only reports of this issue (that I've seen) are on pre-release Windows. That highly suggests this is a Windows issue and something that they should be notified of via whatever pre-release channels you have.

**Comment by JVimes** [comment]
Don't be too quick to blame Windows... ICE validation runs fine through Orca, just not light/smoke. Yes, just for fast ring.

**Comment by andrewst** [comment]
I too have this issue.
Windows 10, 16241

**Comment by rseanhall** [comment]
I believe the intent of Insider builds of Windows is so that Microsoft can be notified of when they break something as soon as possible. Has anyone reported this issue to Microsoft via the Insider channels? If you can point us to a response by Microsoft that this breakage is intentional and is not going to be fixed, we can reopen this bug. Or, if someone volunteers to investigate the root problem we can assign it to them and reopen.

**Comment by robgoodwin** [comment]
Yes, this has been reported.

**Comment by rseanhall** [comment]
Feel free to upvote this Insider issue - https://aka.ms/Sodgd1

**Comment by erikread** [comment]
It is still present in 16251.

**Comment by robmen** [comment]
@erikread Feel free to upvote this Insider issue - https://aka.ms/Sodgd1

**Comment by soundsgood** [comment]
I tested to disable the ICE validation and then the problem disapears.

**Comment by paw3lx** [comment]
@soundsgood how did you disabled the ICE validation?

**Comment by soundsgood** [comment]
I added this to the project file (.wixproj):

  <PropertyGroup>
    <SuppressValidation>true</SuppressValidation>
  </PropertyGroup>

After that, no problems building the setup! 😊

**Comment by erikread** [comment]
so, what you guys are saying is that disabling validation is the answer? That's like saying stay on the official version of Windows from above is the answer. Nothing but masking the issue.

**Comment by erikread** [comment]
@robmen I would love to upvote that Insider issue but I am the one that reported it.

**Comment by drearyworlds** [comment]
It will most likely not be an issue when Fall Creator's Update releases. In the meantime, disable ICE validation. Why is that not acceptable?

**Comment by erikread** [comment]
This appears to be fixed in the latest insider build
