### ISSUE TITLE
Wix project is set as incompatible

### ISSUE THREAD

**Issue by wstaelens** [wixtoolset/issues#5638]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

* Which version of WiX are you building with?

> (Wix Toolset v3.11.0.1701)

* Visual Studio
> (Visual Studio Professional 2015 version 14.0.25431.01 Update 3)
> (Visual Studio Professional 2017 version 15.2 (26430.15))

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio 2017 Extension version 0.9.21.62588)
> (WiX Toolset Visual Studio 2015 Extension version 0.9.21.62588)

* Which version of .NET are you building with?

> (.NET 4.7.02046 installed (building solution on .NET 4.6))

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 x64 pro v1703 b15063.413

* Description

I have VS2015 Pro running.
We needed VS2017 Pro for a project so we installed VS 2017.
Ofcourse to get wix working we needed to update the toolset and the VS extension.
We've upgraded wix toolset and installed the extension 2017 for VS2017 (we didn't touch VS2015).

now when opening another project again in VS2015 the wix project in the solution was set to incomptabile. The reason we found is that the VS2015 extension was uninstalled.

We did not uninstall it ourselves from VS2015. No idea why it has been removed or when exactly. 
But this might be something to look at when having two Visual Studio versions running side by side that both require Wix. 
It looks like when we installed the toolset and installed the extensions for VS2017 that it broke the VS2015 extension (or uninstalled it).
My colleague had the same that the project was set to incompatible after installing VS2017 and updating Wix toolset and installing the extension for VS2017.

**Comment by robmen** [comment]
Yep. Sorry, new (breaking) behavior in WiX v3.11 (you can read a [tiny bit more here](http://robmensching.com/blog/posts/2017/5/5/wix-toolset-v3.11-released/)). Visual Studio extension is now available separately. Links listed here: http://wixtoolset.org/releases/

**Comment by wstaelens** [comment]
oh ok. sorry thanks! 👍
