### ISSUE TITLE
Visual Studio 2017 Extension ignores variable in Output name setting

### ISSUE THREAD

**Issue by PRR24** [wixtoolset/issues#5642]
If Output name is set to "setup_$(Platform)", VS 2017 extension creates a output file "setup_$(Platform).msi" instead of expected "setup_x64.msi"
As the output name is not configurable per configuration basis, there seems no way to create different file names for different platforms.
Variables in output name work in VC 2010 extension.

Extension 0.9.21.62588
WIX 3.11
VS 15.2

**Comment by barnson** [comment]
You can't do this in the UI but you might be able to do it by hand-editing the .wixproj. Key will be to set the name after the $(Platform) variable was set, which isn't always explicit.

**Comment by PRR24** [comment]
Is there a specific reason not to allow it to be done in the UI, like it used to be?

**Comment by barnson** [comment]
The UI always escapes the value.

**Comment by PRR24** [comment]
My apologies in advance as I have limited knowledge on specific implementation...
but I can use the $(Platform) for output path, eg I can set
`<OutputPath>$(Platform)_$(Configuration)\</OutputPath>`
from UI and it works perfectly.

You are correct about escaping. If I edit the file by hand and set
`<OutputName>setup_$(Platform)</OutputName>`
everything works perfectly. I can even open the setting editor and do some changes without ruining tha handwork.

So I would like to rephrase the raised issue as a change request:
Please consider adjusting the wix project settings editor in a way that it does **not** escape OutputName value.

**Comment by barnson** [comment]
If you're interested in creating a [wip][wip] and making this change, we'd take a pull request. Otherwise, the triage team wasn't interested in this feature.

[wip]: http://wixtoolset.org/development/wips/0000-wix-improvement-proposal/
