### ISSUE TITLE
WIX 3.11 doesn't uninstall a previous version of embedded bundle during upgrade

### ISSUE THREAD

**Issue by mediawolf** [wixtoolset/issues#5643]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

VS 2015 Update 3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 7 SP 1

* Describe the problem and the steps to reproduce it.

I have bundle installer of product A which also installs bundle installer of product B as follows:
ExePackage Id="B"
            SourceFile="..."
            Name="B"
            Compressed="yes"
            Cache="no"
            Vital="yes"
            Permanent="yes"
            DetectCondition="EmbeddedB = InstalledB"
            InstallCondition="EmbeddedB &gt;= InstalledB"
            InstallCommand="/install /quiet /norestart"
            RepairCommand="/repair /quiet /norestart"
            UninstallCommand="/uninstall /quiet /norestart"
            Protocol="burn"
Product A | Product B | Built with WIX
v1               v1            v3.9.1208.0
v2               v2            v3.10.3.3007
v3               v3            v3.11.0.1701
Upgrade code of product A is the same for all versions. The same is true for product B which has own upgrade code.
Upgrading A v1 to v2 runs ok and B v1 is properly upgraded to v2. Upgrading A v1/2 to v3 also properly installs B v3 but doesn't uninstall B v1/2.
Till now I found these issues:
1) WIX v3.9/3.10 pass burn.ancestors argument to embedded bundle but v3.11 does not:
---------------------------------------
Main installer log (Burn v3.10.3.3007):
  ...
  Applying execute package: B, action: Install, path: ..., arguments: '... -burn.ancestors=...'
Embedded installer log (Burn v3.10.2.2516):
  Detected related bundle: ... operation: MajorUpgrade
  Planned related bundle: ... execute: Uninstall
---------------------------------------
Main installer log (Burn v3.11.0.1701):
  ...
  Applying execute package: B, action: Install, path: ..., arguments: '...'
Embedded installer log (Burn v3.10.2.2516):
  Detected related bundle: ... operation: MajorUpgrade
  Plan skipped related bundle: ... because it was embedded
---------------------------------------
2) During debugging PseudoBundleInitialize was never executed and this is the only function that should set pPackage->Exe.fSupportsAncestors to TRUE. As the result my package is protocol = BURN_EXE_PROTOCOL_TYPE_BURN but fSupportsAncestors is always FALSE.

* Describe the behavior you expected and how it differed from the actual behavior.

Old versions of bundle installers should be uninstalled during an upgrade. 

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please attach complete logs (obfuscated if necessary).

**Comment by mediawolf** [comment]
[UpgradeLogs.zip](https://github.com/wixtoolset/issues/files/1164688/UpgradeLogs.zip)
NormalUpgrade folder contains logs from a computer where Product B Beta 1.0 was installed, including Product Shared 1.7.15 which was embedded into Product B bundle. Then Product A 2.0.3 was installed which comes with embedded Product Shared 2.0.12.
AbnormalUpgrade folder contains logs of installed Product A 2.0.3 that came with embedded Product Shared 2.0. Then Product A 2.0.1000 was installed that comes with embedded Product Shared 2.0.1000 built using Wix 3.11, which doesn't uninstalls bundle of Product Shared 2.0.12.

**Comment by barnson** [comment]
One workaround is to drop `Protocol="burn"` from your `ExePackage` element. You'll lose progress, however.

**Comment by mediawolf** [comment]
Thanks Bob. This workaround seems fine for now. Is this WIX 3.11 problem?

**Comment by barnson** [comment]
Investigate whether we should bump the protocol version.

**Comment by mediawolf** [comment]
Removal of **protocol=burn** helped. Thanks again.
If information, that was originally sent using **burn.ancestors** command-line parameter, is now sent to nested bundles in a different way then, indeed, it's a breaking change...

**Comment by barnson** [comment]
Not really an issue now given that it's only a problem for pre-v3.9 bundles.

**Comment by rseanhall** [comment]
I took a second look at this and the `burn.ancestors` was a red herring. This was a bug with embedded bundles in v3.9/v3.10 that was fixed in https://github.com/wixtoolset/wix3/pull/319. Removing the `protocol=burn` was the workaround so that the embedded bundle was run independently instead of embedded.
