### ISSUE TITLE
Cannot install Wix Toolset Visual Studio 2017 Extension to VS 2017 Community: NoApplicableSKUsException

### ISSUE THREAD

**Issue by gentledepp** [wixtoolset/issues#5644]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
none yet - trying to install VSIX for VS 2017 for using WiX v3.11

* Which version of Visual Studio are you building with (if any)?
Visual Studiuo Community 2017 - Version 15.2 (26430.16) Release

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
WiX v3.11

* Which version of .NET are you building with?
not applicable

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.
Downloaded VSIX from https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2017Extension 

* Describe the behavior you expected and how it differed from the actual behavior.
Tried to install, but got an error that no applicable product was found for this extension.

It seems as if it only finds SQL Server Management Studio v17.1 (which I have installed with version 14.0.17119.0)
See the installation log here ( am sorry, but for some reason it is in german):

> 
> 18.07.2017 13:51:36 - Microsoft VSIX Installer
> 18.07.2017 13:51:36 - -------------------------------------------
> 18.07.2017 13:51:36 - Initializing Install...
> 18.07.2017 13:51:37 - Erweiterungsdetails...
> 18.07.2017 13:51:37 - 	Identifier      : WixToolset.VisualStudioExtension.Dev15
> 18.07.2017 13:51:37 - 	Name            : Wix Toolset Visual Studio 2017 Extension
> 18.07.2017 13:51:37 - 	Author          : .NET Foundation and contributors
> 18.07.2017 13:51:37 - 	Version         : 0.9.21.62588
> 18.07.2017 13:51:37 - 	Description     : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
> 18.07.2017 13:51:37 - 	Locale          : en-US
> 18.07.2017 13:51:37 - 	MoreInfoURL     : http://wixtoolset.org/
> 18.07.2017 13:51:37 - 	InstalledByMSI  : False
> 18.07.2017 13:51:37 - 	SupportedFrameworkVersionRange : [4.0,)
> 18.07.2017 13:51:37 - 
> 18.07.2017 13:51:37 - 	Unterstützte Produkte : 
> 18.07.2017 13:51:37 - 		Microsoft.VisualStudio.Community
> 18.07.2017 13:51:37 - 			Version : [15.0,16.0)
> 18.07.2017 13:51:37 - 
> 18.07.2017 13:51:37 - 	Verweise        : 
> 18.07.2017 13:51:37 - 
> 18.07.2017 13:51:37 - Er wird nach passenden Produkten gesucht...
> 18.07.2017 13:51:37 - Installiertes Produkt gefunden - Globaler Pfad
> 18.07.2017 13:51:37 - Installiertes Produkt gefunden - ssms
> 18.07.2017 13:51:37 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
>    bei VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
>    bei VSIXInstaller.App.InitializeInstall()
>    bei System.Threading.Tasks.Task.InnerInvoke()
>    bei System.Threading.Tasks.Task.Execute()
>

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
