### ISSUE TITLE
CustomAction ProcessXmlPropertyFile returned actual error code 1603 

### ISSUE THREAD

**Issue by sdatt25** [wixtoolset/issues#5645]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wixtoolset 3.8

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2013

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Wixtoolset 3.8

* Which version of .NET are you building with?

> .NET 4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows Server 2012 (where we deploy the msi of WixToolSet and it is failing)

* Describe the problem and the steps to reproduce it.

> We are using adding product.wxs for our application and its failing with error . Detail of msi is also attached.

* Describe the behavior you expected and how it differed from the actual behavior.

> MSI created through WiX should work with successfull deployment.

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

>Automation of deployments will be done with Wix

* Describe how you're accomplishing the feature today (if possible).

> Currently we are creating manually packages and deploying on server.

* Describe what you'd like the new feature to do.

> Get this issue fixed.
[MyLogFile.txt](https://github.com/wixtoolset/issues/files/1159582/MyLogFile.txt)

**Comment by barnson** [comment]
Your code has a bug.

**Comment by sdatt25** [comment]
hi Barnson. 

Thanks for letting me know that my code has an issue. But do you think you can tell me which section has the problem ?

Guidance to same will be helpful.

Thanks
Saurabh Datta
