### ISSUE TITLE
Hi Team , I am getting below error when trying to set the apppool to website.

### ISSUE THREAD

**Issue by akhileshsingh26** [wixtoolset/issues#5646]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage
Hi Team , I am getting below error when trying to set the AppPool to website.

WriteIIS7ConfigChanges:  Error 0x8007000d: Failed set AppPool name property
WriteIIS7ConfigChanges:  Error 0x8007000d: Failed to configure IIS appPool.
WriteIIS7ConfigChanges:  Error 0x8007000d: WriteIIS7ConfigChanges Failed.
CustomAction WriteIIS7ConfigChanges returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11

* Which version of Visual Studio are you building with (if any)?
  Visual Studio 2015

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
V3
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?
4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Window 7 or Window Server 2012)

* Hi Team , If I am creating setup from Window 7 then I don't have any problem in installation or uninstallation of my services.

If I am creating my setup from "Windows Server 2012"and installing it on any machine either on Window 7 of on "Windows Server 2012" then my custom action didn't perform.

I am getting below error when trying to set the AppPool to website.

WriteIIS7ConfigChanges:  Error 0x8007000d: Failed set AppPool name property
WriteIIS7ConfigChanges:  Error 0x8007000d: Failed to configure IIS appPool.
WriteIIS7ConfigChanges:  Error 0x8007000d: WriteIIS7ConfigChanges Failed.
CustomAction WriteIIS7ConfigChanges returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

also unable to uninstall services if setup created from "Windows Server 2012"

Thanks
Akhilesh

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
