### ISSUE TITLE
Clean Room prevents us from debugging our Managed Custom Bootstrapper Application

### ISSUE THREAD

**Issue by virulentt** [wixtoolset/issues#5647]
## Clean Room prevents us from debugging our Managed Custom Bootstrapper Application

I know Clean Room is something important for security, but unfortunately, it prevents Visual Studio to attach correctly in Debug. Could there be a way to disable it for Debugging purpose?

Thank you!

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
