### ISSUE TITLE
Burn should detect when elevated process isn't actually elevated

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5650]
* Describe the scenario and benefits that the feature supports.

> Today, a standard user running without UAC can launch the "elevated" process just fine but it immediately fails trying to do something that requires admin privs.

* Describe how you're accomplishing the feature today (if possible).

> Launch conditions.

* Describe what you'd like the new feature to do.

> The elevated process should detect when it doesn't have elevated privileges and fail with a meaningful message.

**Comment by rseanhall** [comment]
Is this issue just about getting a better error message into the bundle's log? Or is it also supposed update the built-in BA's to show the error message?

**Comment by barnson** [comment]
The former. It's an extreme edge case (IT software that fakes elevation).
