### ISSUE TITLE
Unable to complete set up after wix upgrade to 3.11

### ISSUE THREAD

**Issue by huzefaqubbawala** [wixtoolset/issues#5653]
Recently we have upgraded our Wix version from 3.6 to 3.11and .net from 4.5 to 4.6..2 and are facing issues with installing msi on windows 10 machine

Machine Configuration -

Wix - 3.11
.Net Framework - 4.6.2
Vs - Vs2015
Windows -> Windows 10, 7

Before upgrading to wix 3.11 -

Product.wxs

Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" InstallPrivileges="elevated"

Also i have custom action which internally creates a directory where i want my software to be installed (Default being program files)

CustomAction Id="CheckFolderCustomAction" BinaryKey="CustomAction" DllEntry="CheckFolder" 

When the above custom action run it creates a folder inside program file folder and everything works fine.

After upgradation -

Product.wxs

Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" InstallPrivileges="elevated"

Also i have custom action which creates a directory where i want my software to be installed (Default being program files)

CustomAction Id="CheckFolderCustomAction" BinaryKey="CustomAction" DllEntry="CheckFolder" 

- Now when i try to install the msi by double click I could not get past the step from where the above custom action is called. I get an exception in custom action saying unable to create a folder due to permission issue.

Some Workaround -

In windows 7, when i turned off UAC the issue is not reproducible but no luck with windows 10.

I do not want to turn off UAC, also it should work in all OS regardless.

Can anyone tell me why after upgrading it is not working.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
