### ISSUE TITLE
Cannot install Votive Vsix on VS 2017.

### ISSUE THREAD

**Issue by devtrix** [wixtoolset/issues#5654]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3

> (WiX version in major.minor.release.build format)
.11

* Which version of Visual Studio are you building with (if any)?
VS 2017 15.2 (26430.16)

> (Visual Studio version, including year and update)
VS 2017 15.2 (26430.16)
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
Votive2017 vsix
* Which version of .NET are you building with?

> (.NET version)
4.7
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
Windows 10 Pro
* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
When Vsix is double clicked it errors saying "This extension is not installable on any currently installed products"
* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please attach the VSIX log from %TMP%.

**Comment by devtrix** [comment]
It did install through VS 2017.  But when clicking the VSIX directly, Votive017.vsix, following is the log; its not finding VS2017.  The log is as follows:
7/27/2017 1:36:52 PM - Microsoft VSIX Installer
7/27/2017 1:36:52 PM - -------------------------------------------
7/27/2017 1:36:52 PM - Initializing Install...
7/27/2017 1:36:53 PM - Extension Details...
7/27/2017 1:36:53 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev15
7/27/2017 1:36:53 PM - 	Name               : Wix Toolset Visual Studio 2017 Extension
7/27/2017 1:36:53 PM - 	Author             : .NET Foundation and contributors
7/27/2017 1:36:53 PM - 	Version            : 0.9.21.62588
7/27/2017 1:36:53 PM - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
7/27/2017 1:36:53 PM - 	Locale             : en-US
7/27/2017 1:36:53 PM - 	MoreInfoURL        : http://wixtoolset.org/
7/27/2017 1:36:53 PM - 	InstalledByMSI     : False
7/27/2017 1:36:53 PM - 	SupportedFrameworkVersionRange : [4.0,)
7/27/2017 1:36:53 PM - 
7/27/2017 1:36:53 PM - 	SignatureState     : Unsigned
7/27/2017 1:36:53 PM - 	Supported Products : 
7/27/2017 1:36:53 PM - 		Microsoft.VisualStudio.Community
7/27/2017 1:36:53 PM - 			Version : [15.0,16.0)
7/27/2017 1:36:53 PM - 
7/27/2017 1:36:53 PM - 	References         : 
7/27/2017 1:36:53 PM - Signature Details...
7/27/2017 1:36:53 PM - 	Extension is not signed.
7/27/2017 1:36:53 PM - 
7/27/2017 1:36:53 PM - Searching for applicable products...
7/27/2017 1:36:55 PM - Found installed product - Microsoft Visual Studio Enterprise 2015
7/27/2017 1:36:55 PM - Found installed product - Microsoft Visual Studio Professional 2015
7/27/2017 1:36:55 PM - Found installed product - Microsoft Visual Studio Community 2015
7/27/2017 1:36:55 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
7/27/2017 1:36:55 PM - Found installed product - Global Location
7/27/2017 1:36:55 PM - Found installed product - ssms
7/27/2017 1:36:55 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

**Comment by devtrix** [comment]
Got it working thru VS2017 Extensions area.  So thanks anyways.
