### ISSUE TITLE
WIX does not remove the web applications after uninstall in wix

### ISSUE THREAD

**Issue by SanthoshYalamuri** [wixtoolset/issues#5657]
We are using WIX 3.10 to create web applications under default website, this implementation works fine but the issue is with uninstall of the product that it does not remove the web application under the default website.

The Website port and  name are entered by user as part of custom dialog which are stored in respective properties.further during uninstall these properties are restored using  wix toolset remember property http://robmensching.com/blog/posts/2010/5/2/the-wix-toolsets-remember-property-pattern/ which sets the web application property during uninstall, but still the application is not removed on uninstall.

Uninstall log that sets the website properties after Appsearch:

Action start 15:17:04: AppSearch.
MSI (s) (24:64) [15:17:04:657]: Note: 1: 2262 2: Signature 3: -2147287038 
MSI (s) (24:64) [15:17:04:657]: PROPERTY CHANGE: Modifying WEBSITEPORTPROPERTY property. Its current value is 'WEBSITEPORT'. Its new value: '80'.
MSI (s) (24:64) [15:17:04:657]: Note: 1: 2262 2: Signature 3: -2147287038 
MSI (s) (24:64) [15:17:04:657]: PROPERTY CHANGE: Modifying WEBSITEPROPERTY property. Its current value is 'WEBSITE'. Its new value: 'Default Web Site'.

Code:
`<Fragment>
    <iis:WebSite Id="SITE" Description="[WEBSITE]">
      <iis:WebAddress Id="AllUnassigned" Port="[WEBSITEPORT]"/>
      
    </iis:WebSite>
    <DirectoryRef Id="INSTALLFOLDER">
      <Component Id="TestAppPool" Guid="GUID" KeyPath="yes" Permanent="yes">
        <iis:WebAppPool Id="TestAppPool"
                        Name="Test Net 4.0"
                        Identity="applicationPoolIdentity"
                        ManagedPipelineMode="Integrated"
                        ManagedRuntimeVersion="v4.0" />
      </Component>

      <Component Id="IIS.Component" Guid="GUID" KeyPath="yes" Permanent="no" Win64="yes">
        <iis:WebVirtualDir Id="VirtualDir" Alias="[APPLICATION_NAME]" Directory="Dir" WebSite="SITE"  >
        
          <iis:WebApplication Id="Application" Name="[APPLICATION_NAME]" WebAppPool="TestAppPool"/>
        </iis:WebVirtualDir>

        <RegistryValue Root='HKLM' Key='SOFTWARE\Test\Product' Name='Website' Value='[WEBSITE]' Type='string' Action='write'  />
        <RegistryValue Root='HKLM' Key='SOFTWARE\Test\Product' Name='WebsitePort' Value='[WEBSITEPORT]' Type='string' Action='write' />
        <RegistryValue Root='HKLM' Key='SOFTWARE\Test\Product' Name='Application' Value='[APPLICATION_NAME]' Type='string' Action='write' />
        
      </Component>
    </DirectoryRef>
	</Fragment>`
 
There is another issue related, repair operation through Add Remove Programs throws a Fatal error with the following error:

WriteIIS7ConfigChanges:  Entering WriteIIS7ConfigChanges in C:\Windows\Installer\MSICDDF.tmp, version 3.10.3007.0
WriteIIS7ConfigChanges:  Custom action data hash: 41034C345A4E6B9B4DDB8490C1BC5266637BC0E8
WriteIIS7ConfigChanges:  CustomActionData WriteIIS7ConfigChanges length: 225
WriteIIS7ConfigChanges:  Error 0x80070002: Site not found for create application
WriteIIS7ConfigChanges:  Error 0x80070002: Failed to configure IIS application.
WriteIIS7ConfigChanges:  Error 0x80070002: WriteIIS7ConfigChanges Failed.

Any other alternative solution that would solve the issue?

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
