### ISSUE TITLE
WiX v4 should automatically set msidbFileAttributesChecksum for PE files

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5659]
* Describe the scenario and benefits that the feature supports.

> Today, you have to manually set `Checksum="yes"` for PE files to get the checksum-checking behavior.

* Describe how you're accomplishing the feature today (if possible).

> By hand. So rude.

* Describe what you'd like the new feature to do.

> The binder already gets file information to file out the File table, so how about it sets `msidbFileAttributesChecksum` when the file has version info (and is therefore a PE file with a versioninfo resource). Leave `@Checksum` for those weird PE files that don't have version info resources.

**Comment by robmen** [comment]
My understanding was that checksum was essentially deprecated.
