### ISSUE TITLE
WiX bundle hangs if .NET 3.5 not present and /passive or /quiet

### ISSUE THREAD

**Issue by IvanBoyko** [wixtoolset/issues#5661]
## Bugs

* Which version of WiX are you building with?
> wix311.exe as downloaded from:
https://github.com/wixtoolset/wix3/releases/download/wix311rtm/wix311.exe

* Which version of Visual Studio are you building with (if any)?
> irrelevant, but tried both VS 2015 or 2017 - same result

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> None, just Wix

* Which version of .NET are you building with?

> tried 4.5.1 and 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows containers, tried on couple of most recent versions of microsoft/windowsservercore - 10.0.14393.1480 and 10.0.14393.1593

* Describe the problem and the steps to reproduce it.

> I run: wix311.exe /q
> there are 2 processes wix311.exe, parent and child, both hang forever, at least 1 hour, without using CPU
> looked at them by Process Explorer, and can see a few threads in states: Wait:WrUserRequest, Wait: WrQueue, Wait:UserRequest

* Describe the behavior you expected and how it differed from the actual behavior.

> I'd expect Wix to be installed :)

**Comment by IvanBoyko** [comment]
Also, is there a documentation about command line arguments for Wix311.exe installer?

**Comment by IvanBoyko** [comment]
Funny enough, but version 3.10.3.300702 installs fine :)

**Comment by robmen** [comment]
My first random guess (without digging into the code) is that the .NET Framework v3.5 check added in WiX v3.11 does not respect the quiet flag (like it should). You could try installing .NET Framework v3.5 in your container and then WiX v3.11. If that works my hypothesis is probably right.

**Comment by barnson** [comment]
It is respecting the display level but isn't correctly exiting when it blocks (for quiet or passive).

**Comment by IvanBoyko** [comment]
Installation of .NET Framework 3.5 indeed fails in recent versions of microsoft/windowsservercore image.
Providing this image already has (I think) version 4.5, and can easily install 4.6.2, is it really not compatible with 3.5?
If I install Wix 3.10.3 (without .NET 3.5) it still runs candle.exe, light.exe, heat.exe...

**Comment by IvanBoyko** [comment]
I ended up using different base image - **microsoft/dotnet-framework:3.5**, which is actually based on standard **microsoft/windowsservercore** but also installs .NET Framework 3.5

See: https://github.com/Microsoft/dotnet-framework-docker/blob/master/3.5/Dockerfile

Here is my Dockerfile snippet that installs Wix 3.11 successfully inside container:

```
# escape=`

FROM microsoft/dotnet-framework:3.5-windowsservercore-10.0.14393.1480

# Install chocolatey, used to install other tools below
RUN @powershell -NoProfile -ExecutionPolicy unrestricted -Command "(iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')))"

# Install Wix
RUN choco install -y wixtoolset --version 3.11.0.20170506
RUN setx /M PATH "%PATH%;C:\Program Files (x86)\WiX Toolset v3.11\bin"
# smoke test
RUN candle.exe -?

```

**Comment by rseanhall** [comment]
Since this didn't make v3.11.x, this is obsolete since the root issue was the block for missing .NET 3.5 and v3.14 isn't supposed to require it anymore.

**Comment by felfert** [comment]
So where is v3.14?

**Comment by robmen** [comment]
Still under development, so it is available under the "[Development Builds](http://wixtoolset.org/releases/development/)".

**Comment by albertvaka** [comment]
Is there an ETA for 3.14? It's been unreleased for 3+ years now. Thanks!

**Comment by robmen** [comment]
WiX v3.14's primary purpose is to help the transition from WiX v3.x to WiX v4. As such, it is aligned with WiX v4 release timeline.
