### ISSUE TITLE
replacing folder by zip file increases the msi size

### ISSUE THREAD

**Issue by shritis** [wixtoolset/issues#5662]
I have a bundler folder in msi, which is about **11MB** big, so i zipped that folder and included in msi replacing the bundler folder. But my final msi folder is still bigger than the orginal msi that included the bundler folder without zip. 
What am i doing wrong here? 
My final msi created acts well expect that its size is bigger.
My final msi size without zipping the bundler folder: 14MB
My final msi size with zipping the bundler folder: 16MB

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
