### ISSUE TITLE
Windows Installer (XML) option not present in VS 2017 Community Edition

### ISSUE THREAD

**Issue by ghigliottyc** [wixtoolset/issues#5663]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (3.11.0.17.01)

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 Community edition

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Visual Studio 2017 Entension

* Which version of .NET are you building with?

> (.NET version 3.5.1)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Win 10 Creators Update)

* Describe the problem and the steps to reproduce it.

> When attempting to create a new Wix project in VS 2017 Community Edition I don't see an option to create a Windows Installer (XML) file. I don't see an option to select a .NET Framework greater than 3.5, and when I launch the Wix.exe with .NET 3.5 disabled, I explicitly states that I need to enable 3.5 to use Wix.

<img width="906" alt="screen shot 2017-08-16 at 5 03 32 pm" src="https://user-images.githubusercontent.com/11220255/29385357-5e8e5b06-82a5-11e7-9bbf-c89a835afefb.png">

**Comment by barnson** [comment]
Pick `Setup Project for WiX v3`.

**Comment by ghigliottyc** [comment]
Hi @barnson,

I've tried this previously and receive a "project creation failed" error in Visual Studio.
 
<img width="209" alt="screen shot 2017-08-17 at 10 10 19 am" src="https://user-images.githubusercontent.com/11220255/29416695-f02e4a8c-8334-11e7-92f9-5d0180ee5588.png">

**Comment by Bizarrus** [comment]
Same issue here. Brand new installed `Visual Studio 2017 (CE)` and `https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2017Extension`.

When i've tried to create an Project (`v3` or `v4`), the project creation failed.

**Comment by AnshulMehta187** [comment]
Is there any update or solution on the above mentioned issue as I am not  seeing any 
Windows Installer XML in VS 2017 Professional edition
