### ISSUE TITLE
VS 2017, View WiX editors not available

### ISSUE THREAD

**Issue by JFXV** [wixtoolset/issues#5664]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
> v3 and also tried v4

* Which version of Visual Studio are you building with (if any)?
> Visual Studio 2017 version 15.3.0  VisualStudio.15.Release/15.3.0+26730.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
>downloaded today 17 aug 2017, WiX Toolset Visual Studio Extension   0.9.21.62588

* Which version of .NET are you building with?
>Version 4.7.02046

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> Windows 10, creators update

* Describe the problem and the steps to reproduce it.
> No error-code. After installing and adding a new project to the code, going to the Solution Explorer and there are no icons. Also in the menu, there is no "View Wix Editors"

* Describe the behavior you expected and how it differed from the actual behavior.
> In all Youtube instructions you see the buttons and the menu. Not in mine installation
![wixbuttons](https://user-images.githubusercontent.com/31089301/29396928-541ca8dc-831b-11e7-8fd6-a0ca58d26a1e.png)

i installed V3.11 tools and the extension in VS

**Comment by robmen** [comment]
Votive does not add a "View Wix Editors" menu. You have us confused with someone else. 😄
