### ISSUE TITLE
Heat - Autogenerated file ids - would be nice if they sorted by directory for installer performance.

### ISSUE THREAD

**Issue by robdalsanto** [wixtoolset/issues#5666]
In his book "Wix 3.6 - A Developer's Guide to Windows Installer XML", Nick Ramirez states that the Windows Installer will install files from the MSI's FILE table in the order the files sort by Id. And he claims that Windows will take longer to write the files if it has to write to one directory and then to a different directory as it iterates through the files.

If the heat tool would either auto-generate file IDs that sort by directory, or have an option to sort by directory, then that could save a lot of time. This should also work with the MSBuild <HeatProject>, which is the method we use to harvest web-site content for our installer.

Refer to the book near the end of chapter 2, or the relevant section at [book](https://books.google.ca/books?id=S5VFSs_iKywC&pg=PT151&lpg=PT151&dq=windows+installer+file+order+by+directory+wix&source=bl&ots=sYcXHd-9Hc&sig=Otr6047zXPXM6SM7BZqle0un1wA&hl=en&sa=X&ved=0ahUKEwj9rK_U2OjVAhUJ92MKHQBbC3QQ6AEIXTAJ#v=onepage&q=windows%20installer%20file%20order%20by%20directory%20wix&f=false).

**Comment by robmen** [comment]
This isn't a heat specific problem. This is a change that will be made in WiX v4 for all files. We can't change the sort order in WiX v3 because that could break patching.

**Comment by robdalsanto** [comment]
OK, I'll wait for WiX 4 to provide this somehow. It seemed like an easy add for the MSBuild usage of HeatProject as an optional switch.
