### ISSUE TITLE
ServiceInstall Description is not being set

### ISSUE THREAD

**Issue by robdalsanto** [wixtoolset/issues#5667]
v3.11 of WiX added via NuGet, with Visual Studio 2015.
This is working fine with v3.8 of WiX, but now that we've moved to v3.11, the service-description is not being set.

I have a WiX fragment that looks like:
`    <ComponentGroup Id="JobScheduler.Service" Directory="ApplicationBinFolder">
      <Component Id="cmp5530ECD9DD64649B6D3C9134AB6AF330" Guid="*">
        <File Id="fil4339D4B1A6BE12AAC09748608100AB04" KeyPath="yes"
              Source="$(var.CL.JobScheduler.Service.TargetPath)" />
        <ServiceInstall Id="InstallJobScheduler" Name="CL.JobScheduler_[INSTANCE_NAME]"
                        DisplayName="CL Job Scheduler ([INSTANCE_NAME], [JOB_SCHEDULER_PORT], !(bind.FileVersion.fil_bin_CL.BusinessGateway.dll))"
                        Start="demand" Type="ownProcess" Vital="yes"
                        EraseDescription="yes" ErrorControl="normal"
                        Description="Copperleaf C55 Job Scheduler[CRLF]Instance : [INSTANCE_NAME][CRLF]Port : [JOB_SCHEDULER_PORT][CRLF]!(bind.FileVersion.fil_bin_CL.BusinessGateway.dll)">
          <util:ServiceConfig FirstFailureActionType="restart"
                              SecondFailureActionType="restart"
                              ThirdFailureActionType="none"
                              ResetPeriodInDays="1" RestartServiceDelayInSeconds="60"/>
        </ServiceInstall>
        <ServiceControl Id="sc_InstallJobScheduler" Name="CL.JobScheduler_[INSTANCE_NAME]" 
                        Stop="both" Remove="uninstall" Wait="no"/>
      </Component>
      <Component Id="cmpDC8ACDC5AB09B0EF4C86FAF01CC8BDCA" Guid="*">
        <File Id="filE891EC0445C1A9D7326A588FCC136D41" 
              Source="$(var.CL.JobScheduler.Service.TargetDir)CL.JobScheduler.Service.exe.config" />
      </Component>
      <Component Id="cmp5C3FD00AFF5B4CE2E9A6D9A2FB0EE72A" Guid="*">
        <File Id="fil58A9AE31D507283774699E34F70A5ACB" 
              Source="$(var.CL.JobScheduler.Service.TargetDir)CL.ReportTemplateHelper.dll" />
      </Component>
    </ComponentGroup>
`

**Comment by barnson** [comment]
Don't set `EraseDescription="yes"` if you want a description.

**Comment by robdalsanto** [comment]
I thought I had tried skipping the EraseDescription, but apparently not. That was the magic incantation. Apologies for the noise. And thank you Bob. I'll close this now.
