### ISSUE TITLE
Advertised shortcuts not displaying correct icon in the start menu.

### ISSUE THREAD

**Issue by DJJ1** [wixtoolset/issues#5669]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0.5512

* Which version of Visual Studio are you building with (if any)?

> (none)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (none)

* Which version of .NET are you building with?

> (not applicable)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 (version 1703, build 15063.540)

* Describe the problem and the steps to reproduce it.

> As part of the WXS files I created, I discovered that any advertised shortcuts that I create, using the usual method of placing Shortcut tags within the same File or Component tags of the same component, do not display the correct icons in the Start Menu.  The same issue applies to creating equivalent IniFile entries that use "Icon=...", "IconFile=...", and  "IconIndex=..." key/value pairs.

It appears that the icons are being stripped from files created by the resulting MSI file because creating shortcuts and INI files separately from the installer works as desired.  The shortcuts themselves work as expected and the Add/Remove Programs icons display correctly.  Also, unadvertised shortcuts produce the correct Start Menu icons.

* Describe the behavior you expected and how it differed from the actual behavior.

> I would expect advertised shortcuts to render correctly in the Start Menu, displaying the chosen icons and, when enlarged, an overlay with blue inward facing arrows.  Instead, some form of generic icon is displayed.

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
WiX isn't involved in creating shortcuts -- that's up to MSI and Windows. If you think this is a WiX bug, please open your .msi in Orca, export the Shortcut table, and attach it here.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
