### ISSUE TITLE
Error when running candle.exe

### ISSUE THREAD

**Issue by ghigliottyc** [wixtoolset/issues#5671]
If this issue is a bug:

- Which version of WiX are you building with?
(3.11.0.17.01)

- Which version of Visual Studio are you building with (if any)?

Visual Studio 2017 Community edition

- Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Visual Studio 2017 Entension

- Which version of .NET are you building with?

(.NET version 3.5.1)

- If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

(Win 10 Creators Update)

- Describe the problem and the steps to reproduce it.
When attempting to run candle.exe I received the following error:

> error CNDL0104 : Not a valid source file; detail: Name cannot begin with the '9' character, hexadecimal value 0x39. Line 21, position 53.

I reviewed line 21 and I don't have anything that starts with '9'.

![screen shot 2017-08-25 at 12 09 21 pm](https://user-images.githubusercontent.com/11220255/29722357-65aacc0e-898e-11e7-81ed-8397a61af5bb.png)

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
