### ISSUE TITLE
Wix nuget package should add reference for BootstrapperCore.dll

### ISSUE THREAD

**Issue by dan-olsen** [wixtoolset/issues#5678]
* Describe the scenario and benefits that the feature supports.

> After adding the Wix 3.10.3 nuget package to a Wix Managed Bootstrapper application project I would expect a reference to be added for the BootstrapperCore.dll. Because of this the current nuget package does not allow build servers to build managed bootstrapper applications without additional software. 

* Describe how you're accomplishing the feature today (if possible).

> I manually add a reference to the BootstrapperCore.dll in the nuget package at WiX.3.10.3\tools\sdk\BootstrapperCore.dll

* Describe what you'd like the new feature to do.

> I'd like the reference to be done automatically when adding the nuget package to a C# project.

**Comment by robmen** [comment]
We don't provide a Nuget package for WiX v3.x. Nuget packages will be coming in WiX v4.

**Comment by dan-olsen** [comment]
There's a nuget package with your name as an author at [https://www.nuget.org/packages/WiX/3.11.0](url) and linking to the wix toolset website. Is this not an official nuget package from WiX?

**Comment by robmen** [comment]
Nope. Anyone can take your official logos, put your name on a NuGet package, upload to the official repository (https://www.nuget.org) and let the rest of the world believe you support it.

Lovely don't you think?

**Comment by dan-olsen** [comment]
Yes it is.

Is it planned to support managed bootstrapper projects as well as wix projects in the official Wix nuget packages coming in v4?

**Comment by robmen** [comment]
Maybe. It depends how other things go. If you really want it to see it happen, you will want to leave open time on your schedule in a month or three after the core toolset is sorted out. Then you can [write a WIP](http://wixtoolset.org/development/wips/0000-wix-improvement-proposal/) and implement the feature.

**Comment by dan-olsen** [comment]
Well if I have the time I'll look into this. Thank you for the quick responses.
