### ISSUE TITLE
Include the paths of linked wxi files to candle

### ISSUE THREAD

**Issue by mrbass21** [wixtoolset/issues#5680]
* Describe the scenario and benefits that the feature supports.

 When adding an include file to a WiX project (whether by link or by copying it to the main working folder), it's implicit that the directory where the include file lives should be included.  I recently started using WiX because there was little knowledge of it at my company and the way our products are setup,  there's many shared variables. I created a Common.wxi in a common folder outside of all the WiX projects. I added the Common,wxi file as link, and expected it to automatically be referenced by candle, since its path is in the wixproj file. Since I added the file, my <?include Common.wxi ?> tag did not include the path.

This feature request is really more about making it a little more "drop dead simple" for users. WiX has plenty of options for how to specify an included search location, but I think this feature re-enforces what the UI is displaying. An include file is added to the project, so you can just reference it without adding extra paths.

* Describe how you're accomplishing the feature today (if possible).

I include the path to the folder containing the Common.wxi via the wixproj property sheet.

* Describe what you'd like the new feature to do.

If a wixproj has a wxi file added to the project (as link or not), the path to that wxi file should automatically be added to the candle.exe arguments so the file can be referenced by name only in the <?include ?> tags.

**Comment by barnson** [comment]
Nontrivial. Needs a WIP for Votive and MSBuild support.

**Comment by robmen** [comment]
Include files require a specific import point (`<?include?>`) in the .wxs code. This isn't something that can be intuited from the .wixproj. If you have a bunch of defines, it's better to specify them in the .wixproj not a .wxi file and avoid the include file completely.
