### ISSUE TITLE
Win10 desktop  to create a folder or a shortcut, can not be normal file manager or browse dialog to display and select

### ISSUE THREAD

**Issue by jaelys** [wixtoolset/issues#5681]
## Bugs
* Which version of WiX are you building with?
Wix 3.11
* Which version of Visual Studio are you building with (if any)?
Visual Studio 2017
* Which version of .NET are you building with?
.NET 4.6.1
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10

* Describe the problem and the steps to reproduce it.

In the Win10 desktop to create a folder or a shortcut, can not be normal file manager or browse dialog to display and select, but if you manually copy a copy of the same desktop location, copy will be normal, and will not jump out of the same name warning, the following is A simple example will happen

```
<Component Id="Component.MyApp.exe" Guid="6fe30b47-2577-43ad-9095-1861f9b9286d">
        <File Id="MyApp.exe" Source="AppFiles\MyApp.exe">
             <Shortcut Id="Shortcut.MyApp.exe.MyApp" WorkingDirectory="INSTALLDIR" Directory="INSTALLDIR" Name="MyApp.lnk" />
             <Shortcut Id="Shortcut.MyApp.exe.MyApp.1" WorkingDirectory="TempFolder" Arguments="777" Directory="DesktopFolder" Name="MyApp.lnk" Icon="IconFile1_Icon.ico" IconIndex="0" />
         </File> 

         <RegistryKey Root="HKCU" Key="Software\WixSharp\Used">
             <RegistryValue Value="0" Type="string" KeyPath="yes" />
         </RegistryKey>
</Component>
```

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by jaelys** [comment]
Sorry, later than out, I think this is Win10 problem, file Explorer, can not normally show AllUser within the folder and file or shortcut, I do not know which is Win10 which principle, but should not return Wix Bug, thank
