### ISSUE TITLE
Issue about Anti-Virus

### ISSUE THREAD

**Issue by AltmanWong** [wixtoolset/issues#5684]
Hi, I was building an installer using burn. Once I built the installer, I start run it on my computer. However, the anti-virus had blocked it and put it into a sandbox for scanning. Can I have any ways to by-pass the sandbox checking? Thank you so much!

Wix version: v3.11
Window Version: Windows 10

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
