### ISSUE TITLE
NativeImage - Option to include NGen /ExeConfig to capture binding redirects

### ISSUE THREAD

**Issue by jonreis** [wixtoolset/issues#5686]
I am getting hundreds of the following error:

MSI (s) (AC:58) [15:25:27:411]: Invoking remote custom action. DLL: C:\Windows\Installer\MSID12D.tmp, Entrypoint: ExecNetFx
ExecNetFx:  Microsoft (R) CLR Native Image Generator - Version 4.7.2053.0

ExecNetFx:  1> while resolving 0x10001ac - Microsoft.CodeAnalysis.VisualBasic.VisualBasicParseOptions.
ExecNetFx:  4>Warning: System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Reflection.Metadata, Version=1.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
ExecNetFx:     --- End of inner exception stack trace ---1>Warning: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
ExecNetFx:     --- End of inner exception stack trace ---4> while resolving 0x200006f - Microsoft.Cci.InheritedTypeParameter.

The ExecNetFx section of the installer ran for 12+ minutes and generated about 45MB of logging.

I have used the following:

            <File Id="Connexion.Gateway.exe" Source="Connexion.Gateway\bin\Release\Connexion.Gateway.exe">
              <NativeImage Platform="64bit" Priority="0" Id="NativeImage.7" xmlns="http://schemas.microsoft.com/wix/NetFxExtension" />
            </File>

which by default has Dependencies="yes".

I believe the issue is that NGen needs to know about the binding redirects of the application to correctly figure out the dependencies of the application. There is an NGen option: /ExecConfig for this purpose.

Could this option be added to the NativeImage Element?

Workaround: Do not use the option of the NativeImage Element Dependencies="yes"

**Comment by jonreis** [comment]
I looked at the source code for Wix and it does seem to already add the /ExeConfig

I think my issue was an invalid App.config file.

**Comment by jonreis** [comment]
Nope. Still confused. There seems to be code for setting the /ExeConfig options, but I cannot tell if it is getting hit. Nowhere in the msi log file do I see ngen being called with this flag.

**Comment by barnson** [comment]
It's set when `AssemblyApplication` is specified.

**Comment by jonreis** [comment]
That did the trick. Thank you for pointing that out!
