### ISSUE TITLE
HEAT: System.IO.PathTooLongException

### ISSUE THREAD

**Issue by yamlfd** [wixtoolset/issues#5690]
I'm using 3.11.0.1701 and need to harvest a folder inside an Eclipse directory structure.

The error message from HEAT is very useless and do not tell me what folder is the problem. But with a DIR /s I got the same error

```
Path D:\Eclipse\plugins\ternjs_1.2.0.201701041527\node_modules\tern-eslint\node_modules\eslint\node_modules\file-entry-cache\
node_modules\flat-cache\node_modules\del\node_modules\rimraf\node_modules\glob\node_modules\minimatch\node_modules\brace-expansion\node_modules is too long.
```

I cannot change the code of the software, but need to package it. This is an issue I have seen often. Can you fix HEAT to be able to harvest also these too long folders. With Explorer I can go into this folder without issues.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/5314
