### ISSUE TITLE
Burn: Variable of type "version" with no value causes Burn to crash without any proper indication.

### ISSUE THREAD

**Issue by Farrukhw** [wixtoolset/issues#5693]
## Bug

* Which version of WiX are you building with?
3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

14.0.25431.01 Update 3

* Which version of .NET are you building with?

4.7.02046

* Describe the problem and the steps to reproduce it.

Define a variable of type "version" in Bundle markup with an empty value:
`<Variable Name ="MyVar"                Type="version" Value="$(var.MinVer)" />`

Somehow, var.MinVer went empty.
This may build the Bundle project, but when you will execute Bundle.exe it would do nothing. I tried to get a log using command line "Bundle.exe /log Bundle.log" and nothing happened. Incidentally, I opened my Temp folder and there was generated a file "Setup_20171003101210_Failed.txt" with the following content:

> [1DF0:161C][2017-10-03T10:12:10]i001: Burn v3.11.0.1701, Windows v10.0 (Build 15063: Service Pack 0), path: D:\Installers\MyBundle\bin\Debug\Bundle.exe
> [1DF0:161C][2017-10-03T10:12:10]i000: Initializing version variable 'MyVar' to value ''
> [1DF0:161C][2017-10-03T10:12:10]e000: Error 0x80020005: Failed to copy variant value.
> [1DF0:161C][2017-10-03T10:12:10]e000: Error 0x80020005: Failed to change variant type.
> [1DF0:161C][2017-10-03T10:12:10]e000: Error 0x80020005: Failed to parse variables.
> [1DF0:161C][2017-10-03T10:12:10]e000: Error 0x80020005: Failed to load manifest.
> [1DF0:161C][2017-10-03T10:12:10]e000: Error 0x80020005: Failed to initialize core.

Please note that this crash is happening before it could parse command line and do the /log things.
And as it never reached the Run method of our Managed Bootstrapper, we were not able to call the debugger as well.

* Describe the behavior you expected and how it differed from the actual behavior.

It should at least let us log the behavior and so we can get our problem from the log. Consider it as Bug, as the application is unable to respond to the user in this kind of scenario.

**Comment by rseanhall** [comment]
This was fixed with https://github.com/wixtoolset/issues/issues/6210.
