### ISSUE TITLE
Wix Toolset Visual Studio 2017 Extension fails to install

### ISSUE THREAD

**Issue by kjeremy** [wixtoolset/issues#5695]
I can't seem to install the extension.  I already have the build tools. Win 7 SP1 x64

> 
> 
> 10/4/2017 2:09:54 PM - Microsoft VSIX Installer
> 10/4/2017 2:09:54 PM - -------------------------------------------
> 10/4/2017 2:09:54 PM - vsixinstaller.exe version:
> 10/4/2017 2:09:54 PM - 15.0.403+g26ad50685f
> 10/4/2017 2:09:54 PM - -------------------------------------------
> 10/4/2017 2:09:54 PM - Command line parameters:
> 10/4/2017 2:09:54 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:15.0.26730.16,/appidname:Microsoft Visual Studio Professional 2017,/culture:en-US,C:\Users\jkolb\AppData\Local\Temp\VSIXpf3jxv5x.vsix,/installas:1948,/callingprocessid:10232
> 10/4/2017 2:09:54 PM - -------------------------------------------
> 10/4/2017 2:09:54 PM - Microsoft VSIX Installer
> 10/4/2017 2:09:54 PM - -------------------------------------------
> 10/4/2017 2:09:54 PM - Initializing Install...
> 10/4/2017 2:09:54 PM - Extension Details...
> 10/4/2017 2:09:54 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev15
> 10/4/2017 2:09:54 PM - 	Name               : Wix Toolset Visual Studio 2017 Extension
> 10/4/2017 2:09:54 PM - 	Author             : .NET Foundation and contributors
> 10/4/2017 2:09:54 PM - 	Version            : 0.9.21.62588
> 10/4/2017 2:09:54 PM - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
> 10/4/2017 2:09:54 PM - 	Locale             : en-US
> 10/4/2017 2:09:54 PM - 	MoreInfoURL        : http://wixtoolset.org/
> 10/4/2017 2:09:54 PM - 	InstalledByMSI     : False
> 10/4/2017 2:09:54 PM - 	SupportedFrameworkVersionRange : [4.0,)
> 10/4/2017 2:09:54 PM - 
> 10/4/2017 2:09:54 PM - 	SignatureState     : Unsigned
> 10/4/2017 2:09:54 PM - 	Supported Products : 
> 10/4/2017 2:09:54 PM - 		Microsoft.VisualStudio.Community
> 10/4/2017 2:09:54 PM - 			Version : [15.0,16.0)
> 10/4/2017 2:09:54 PM - 
> 10/4/2017 2:09:54 PM - 	References         : 
> 10/4/2017 2:09:54 PM - 	Prerequisites      : 
> 10/4/2017 2:09:54 PM - 		-------------------------------------------------------
> 10/4/2017 2:09:54 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
> 10/4/2017 2:09:54 PM - 		Name         : Microsoft.VisualStudio.Component.CoreEditor
> 10/4/2017 2:09:54 PM - 		Version      : [15.0,16.0)
> 10/4/2017 2:09:54 PM - 
> 10/4/2017 2:09:54 PM - Signature Details...
> 10/4/2017 2:09:54 PM - 	Extension is not signed.
> 10/4/2017 2:09:54 PM - 
> 10/4/2017 2:09:59 PM - System.ArgumentNullException: Value cannot be null.
> Parameter name: String
>    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
>    at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
>    at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
>    at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
>    at VSIXInstaller.SupportedVSSKU.get_Host()
>    at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at VSIXInstaller.App.GetExtensionEngineForApplicableSKU(SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
>    at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
>    at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
>    at VSIXInstaller.App.Initialize()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

**Comment by kjeremy** [comment]
Bummer.  Thanks for the quick response.

**Comment by sharpe5** [comment]
I also have the same issue. When I run "Votive2017.vixs", it displays:

![2017-11-28 12_02_39-vsixinstaller exe](https://user-images.githubusercontent.com/1290916/33318844-1fb3581a-d434-11e7-9e97-791af098d56c.png)

I've never had any issue with installing any other extension in Visual Studio 2017.

Version: Visual Studio 2017 v15.4.5.

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
