### ISSUE TITLE
WixStdBALanguageId apparently not working

### ISSUE THREAD

**Issue by alexsandrovp** [wixtoolset/issues#5698]
According to documentation, WixStdBALanguageId should reflect the LCID of the Standard Bootstrapper UI language.

http://wixtoolset.org/documentation/manual/v3/bundle/wixstdba/wixstdba_variables.html

When I call my bundle using "mybundle.exe /lang 1031", the UI loads in German, as expected. But the log shows "Setting numeric variable 'WixStdBALanguageId' to value 1033."

The same is true if I call "mybundle.exe WixStdBALanguageId=1031". The GUI loads correctly in German, but the variable has the wrong value '1033'.

I want to use WixStdBALanguageId from within bafunctions.dll, to load some strings defined inside the dll, but with the wrong value of 'WixStdBALanguageId' they always show in English. I expected that variable to hold the value 1031 in those situations.

* Which version of WiX are you building with?
3.11.1701.0

* Which version of Visual Studio are you building with (if any)?
none (building from command line with candle/light)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
none

* Which version of .NET are you building with?
.Net 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 7 x64

**Comment by BMurri** [comment]
A quick look in the sources leads me to ask what the value of the Language tag in the German WXL file is.

**Comment by alexsandrovp** [comment]
It had the wrong value, 1033.

Thank you very much. That fixes the issue!
