### ISSUE TITLE
calling dll in wix

### ISSUE THREAD

**Issue by madhu605** [wixtoolset/issues#5701]
I’ve one  custom CA
CA files look like this:
"namespace WaferVisionCA
{
    public class CustomActions
    {
        [CustomAction]
        public static ActionResult BackUpFiles(Session session)
        {
            string dataFolder = session["DATA"];
            string backupFolder = @"C:\Backup\WaferVision\" + DateTime.Now.Month + "-" + DateTime.Now.Date + "-" + DateTime.Now.Year + "\\";
            string[] backupFilesList;
            try
            {
                if (Directory.Exists(dataFolder))
                {
                    backupFilesList = Directory.GetFiles(dataFolder, "*.wv");
                    Directory.CreateDirectory(backupFolder);
                    foreach (var file in backupFilesList)
                    {

                        File.Copy(file, backupFolder + new FileInfo(file).Name);
                    }
                }
                return ActionResult.Success;
            }
            catch (Exception ex)
            {
                session.Log("Could not take the back up : " + ex.Message);
                return ActionResult.Failure;
            }

        }
    }
}"

wix file look like:

<CustomAction Id="BackupFiles" Return="check" Execute="immediate" BinaryKey="WaferVisionCA.CA.dll" DllEntry="BackUpFiles"/>

<Binary Id="WaferVisionCA.CA.dll" SourceFile="$(var.WaferVisionCA.TargetDir)$(var.WaferVisionCA.TargetName).CA.dll"/>

<Property Id="DATA" Secure="yes" Value="C:\amat\WaferVision\Data\"/>
-<InstallExecuteSequence>
<Custom After="CostFinalize" Action="BackupFiles"/>
</InstallExecuteSequence>

it unable to copy files... and any one can help to create WIX file or XML file for installation.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by madhu605** [comment]
<CustomAction Id="BackupFiles" Return="check" Execute="immediate" BinaryKey="**.CA.dll" DllEntry="BackUpFiles"/>

<Binary Id="**.CA.dll" SourceFile="$(var.**.TargetDir)$(var.**.TargetName).CA.dll"/>

<Property Id="DATA" Secure="yes" Value="C:\**\**\Data\"/>


-<InstallExecuteSequence>

<Custom After="CostFinalize" Action="BackupFiles"/>

</InstallExecuteSequence

unable working on this code could any one can help
