### ISSUE TITLE
Project templates are missing

### ISSUE THREAD

**Issue by Hnarisetty** [wixtoolset/issues#5704]
I have installed
a. Visual Studio 2017
b. Wix tools 3.11
c. Votive2017 ( VS extension)

I don't see any project templates in new project windows in VS.  Any idea?

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by Hnarisetty** [comment]
Ok
