### ISSUE TITLE
Unable to build when reference multi-targeting project

### ISSUE THREAD

**Issue by iskiselev** [wixtoolset/issues#5705]
## Bug

* Which version of WiX are you building with?
v3.11.0.1528, v4.0.0.5512
* Which version of Visual Studio are you building with (if any)?
VS 2017 Update 4 (15.4.0)
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
0.9.21.62588
* Which version of .NET are you building with?
multi-targeting (net20/net40)
* Describe the problem and the steps to reproduce it.
Reference from WIX any multi-targeting SDK-based project (see example bellow). Try to build WIX. There will be an error `ConsoleApp1.csproj(0,0): error MSB4057: The target "GetTargetPath" does not exist in the project.`

Project example:
ConsoleApp1.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net20;net40</TargetFrameworks>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
</Project>
```

Program.cs:
```c#
using System;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
        }
    }
}
```

I've found a workaround: add to the end of project file something like:
```xml
  <Target Name="GetTargetPath" Returns="@(_FakeOutputPath)">
    <ItemGroup>
      <_FakeOutputPath Include="$(MSBuildProjectDirectory)\$(PackageOutputPath)\$(AssemblyName).UNK" />
    </ItemGroup>
  </Target>
```

**Comment by roozbehid-ic** [comment]
I hit the same issue. with following project file

    <PropertyGroup>
    <TargetFrameworks>net461</TargetFrameworks>
    <ApplicationIcon />
    <OutputType>Library</OutputType>
    <StartupObject />
    <Platforms>x64</Platforms>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Version>1.0.27</Version>
  </PropertyGroup>

**Comment by Danielku15** [comment]
It appears that in the new csproj format the "AfterCompile" target does not exist anymore. I saw this issue entered on msbuild side: https://github.com/Microsoft/msbuild/issues/2746 Anyhow I think it is a missing feature on https://github.com/dotnet/project-system side.

**Comment by sanderobdeijn** [comment]
What should the .UNK part do in the workaround? When I add it I get the following error.
The system cannot find the file '[filepath]\[filename].UNK' the .UNK part should be translated to .DLL or .EXE does this workaround work with other people?

**Comment by laurawalker** [comment]
I also had this issue and the fix above worked for me. The file does not need to exist.

**Comment by nielsedens** [comment]
@laurawalker were you building for multiple targets?
I did not get the workaround to work properly. When targeting multiple frameworks both $(PackageOutputPath) nor $(OutputPath) are always 'bin\Debug' (or 'bin\Release') when building the Wix project. The variables do not contain 'net20', 'net45' or 'net462'. I guess the Wix project doesn't target a specific platform. 

I ended up setting a fixed value for a variable "_InstallerTargetFramework" in the project referenced by the Wix project.

`<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net462;net45;net20</TargetFrameworks>
    <Version>2.5.0</Version>
    <Company></Company>
    <Product>MyLibraries.Common</Product>
    <Authors>My Company</Authors>
    <Copyright>© 2019 My Company. All rights reserved.</Copyright>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageId>MyLibraries.Common</PackageId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>ccontent.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
    <AssemblyName>MyLibraries.Common</AssemblyName>
    <RootNamespace>MyLibraries.Common</RootNamespace>
    <OutputType>Library</OutputType>
    <_InstallerTargetFramework>net20</_InstallerTargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Management" />
    <Reference Include="System.Web" />
  </ItemGroup>

  <Target Name="GetTargetPath" Returns="@(_FakeOutputPath)">
    <ItemGroup Condition="'$(OutputType)' == 'Library'">
      <_FakeOutputPath Include="$(MSBuildProjectDirectory)\$(OutputPath)\$(_InstallerTargetFramework)\$(AssemblyName).dll" />
    </ItemGroup>
    <ItemGroup Condition="'$(OutputType)' == 'Exe'">
      <_FakeOutputPath Include="$(MSBuildProjectDirectory)\$(OutputPath)\$(_InstallerTargetFramework)\$(AssemblyName).exe" />
    </ItemGroup>
    <ItemGroup Condition="'$(OutputType)' == 'WinExe'">
      <_FakeOutputPath Include="$(MSBuildProjectDirectory)\$(OutputPath)\$(_InstallerTargetFramework)\$(AssemblyName).exe" />
    </ItemGroup>
  </Target>

</Project>
`

**Comment by teroneko** [comment]
In my case I have project A that has `<TargetFrameworks>netstandard2.0;netcoreapp3.1</TargetFrameworks>` . Now when project B with `<TargetFramework>netcoreapp3.1</TargetFramework>` references project A, The error `error MSB4057: The target "GetTargetPath" does not exist in the project.` is appearing.

My workaround is to add `<AdditionalProperties>TargetFramework=netcoreapp3.1</AdditionalProperties>` or `<AdditionalProperties>TargetFramework=$(TargetFramework)</AdditionalProperties>` to project B.

**Comment by robmen** [comment]
Fixed by wixtoolset/wix4#60

**Comment by iskiselev** [comment]
I tried it with Wix4.0RC1 - and still have same issue, so still need to apply either workaround that I mentioned before or reference inner project builds with something like:
```xml
    <ProjectReference Include="..\ConsoleApp1\ConsoleApp1.csproj" SetTargetFramework="TargetFramework=net6.0" Name="ConsoleApp1.Net6" />
    <ProjectReference Include="..\ConsoleApp1\ConsoleApp1.csproj" SetTargetFramework="TargetFramework=net7.0" Name="ConsoleApp1.Net7" />
```

**Comment by rseanhall** [comment]
That sounds like https://github.com/wixtoolset/issues/issues/7149 or https://github.com/wixtoolset/issues/issues/7132.
