### ISSUE TITLE
No project templates after installing 4.0.3430.0

### ISSUE THREAD

**Issue by JuergenGutsch** [wixtoolset/issues#5706]
I just installed the latest version (4.0.0.5512) as mentioned here #5699
Now it seems, that I need to update the project files of the existing setup projects. I tried it by creating a new WiX project in VS2015.3, but I cannot found any WiX project template. 

Are the templates missing in the toolset setup?
If not are the templates anywhere in the installation folder? Is there a way to install them manually?

Thanks
Juergen

**Comment by robmen** [comment]
You need to install the [Wix Toolset Visual Studio 2015 Extension][d]

[d]: https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2015Extension
