### ISSUE TITLE
WiX Wishlist

### ISSUE THREAD

**Issue by ReverseEMF** [wixtoolset/issues#5707]
# WiX Wishlist
## 1
I dragged some things into a box such that those items became “attached” to that box.  Then I dragged a selection frame around the whole thing to select all of it.  At this point, I can click anywhere and the whole thing drags.  

I then copied/pasted it.  The newly pasted conglomerate appeared to be selected, but if, when dragging it, one clicks on one of the contained elements only the contained element is dragged, and not the whole conglomerate.  BUT, if I re-select the pasted conglomerate (e.g. by dragging a selection frame around it), THEN I can click anywhere and drag the pasted conglomerate without dragging contained elements off the unit.  I noticed that if I click-and-drag the containing box (i.e. miss all of the contained elements), I CAN drag it as a unit—BUT, that is inconsistent behavior (because if I click on any contained element, only that element drags), which is a GUI no-no.

I noticed that when I drag a selection frame around the newly Pasted conglomerate, all of the inner elements have selection rectangles around them.  Which suggests that, even when the inner elements are “attached”, they are being treated as individual elements when the whole conglomerate is selected.  I get why this was done like that – otherwise, how would you be able to click-and-drag an element to drag it out of the box, in order to detach it from the box.  That's a tough user-interface conundrum!  How do you make it so you can click anywhere within the containing box and have the whole thing drag as a unit, yet make it possible to drag things out of the box?

Why is this an issue?  Well, one reason is if the contained elements so overlap the containing box that there either is no place to click on the containing box, or such a place is hard to locate, it becomes pretty much impossible to drag the pasted box off the copied box.  Also, when you do a Copy/Paste, the pasted unit overlaps the copied unit.  When one drags a selection rectangle over the Pasted conglomerate, to select it in a way it can be dragged as a unit, it tends to, also, select elements in the original conglomerate.  Very frustrating!

## 2
If I select a number of conglomerates (i.e. boxes with stuff attached within), and then try to use the Align/Distribute tools, it aligns everything as separate elements, and not as one conglomerate.  i.e., if I place a box on a Page and then drag a Heart shape into the box, so it becomes attached to the box, then duplicate the whole thing (Copy-Paste), then select them all (i.e. "both"), and then use the Align To Top tool -- I DON'T get a nice row of lined up boxes with hearts still where they were, relative to the containing box...NO...I get a mess.  The container boxes are, indeed, aligned as expected.  But, NOT the Hearts!  In fact, the hearts aren't even all on the same line.  The first heart is aligned to the top of it's box (as would be expected if they were NOT attached) and the other heart is sticking more than half way out of the top of it's box!!  If things are attached to a containing box, shouldn't the Align and Distribute tools treat them as a single element and NOT alter the position of the inner elements (relative to the containing box)?  Because of the way this behaves, I can create a conglomerate, then use the conglomerate as a kind of template or reusable object, and “rubber-stamp” more of these constructs, but then, I can NOT use the alignment/distribution tools to get them all lined up nice and pretty!

## 3
So...when I paste a conglomerate (i.e. boxes with stuff attached within), only the containing box is “selected” (such that if I try to drag it by clicking on one of the contained elements, only that element drags, and not the whole thing)...BUT, if I use the “Overlapping Items” feature (in the Right-Click menu [Windows]), and then try to Delete it, or drag it, or use the Arrow Keys to move it, it behaves like a conglomerate (i.e. the element selected using the Overlapping Items feature, if it also contains attached elements, those elements move/delete along with the selected element!)  More non-consistent behavior!! 

Because it's implemented this way, it makes it hard to liberate an attached element when that attached element is the same size as the containing box.  Why would one ever do that?  To, say, add a border or drop shadow (etc.) to an image (since there appears to be no way to get an image to do that).  I like to get a box and then put an image inside it, such that the box allows me to add things like a border, a drop shadow, a background that presents a design element before an image loads (in cases where an image loads slowly), etc. 

So, the only way to do this, presently, is to dismantle the thing, by dragging some or all of the overlapping elements, out of the containing box(es).  Delete the element I no longer want, then reassemble the thing.

## 4
In the Desktop Editor I set up a matrix of “Clickable Thumbnails”. I did this by first placing a Container Box, then Attached an Image, then, overlapping the image, a Text Background box, then within the Text Background box, I placed a Text object.  Each of these elements were “nested attached” (i.e. text object was attached to the Text Background box which was attached to the Image, which was attached to the Container Box.  Then, over all of that, I placed a Transparent Rectangular Shape.  Why? Because a Shape can become a Link.  Each of these serve as portals to categories in the Catalog (something I was hoping Collections could be used for – but, low-and-behold, they display the Products they contain, rather than presenting a Thumbnail/Icon/Button/Link Point for drilling down to the products they contain – but I digress). 

I duplicated these conglomerates, and arranged them into an array (or matrix), then, I edited each Text Object with the name of the category (e.g. Crystals, Hearts, Spheres, Skulls, etc. [it's a Crystal and Mineral business]).  Then I created a subPage for each category (which will contain a “Shop” and the associated Products), then I linked the Overlapping Shapes to their corresponding subPage (e.g. the Crystals Overlapping Shape linked to the “Crystals” subPage, etc.).  Why use a transparrent overlapping shape?  So the whole matrix cell is clickable (none of this only-the-text-is-clickable business—something that annoys the hell out of me), After all that was done, I checked the Mobile version and NO TEXT!?!  Where'd the text go?!???

## 5
I looked everywhere for a way to do this, and found none, thus it's presence on this WishList: You know how when you put something in the Header (when Editing a Wix Site Page) it shows on every page (or when you click that “Show on All Pages” button)?  One thing I tend to like to do is Show the name of the page at the top of the page.  Like, for instance, say I have a bunch of Catalog (or “Shop”) subPages, one for each product category.  I would like to display, at the top of the page, the category that page is for.  Since I've already named the page after the category, it would be cool if there was some sort of “meta variable” that would give me that page name.  Then I could do something like the following in a “text box” (or something similar): “%PageName%”.

Example: in most word processors, there's a way to put the page number in the footer (or header, or anywhere, for that matter).  So, kinda like that.  Such a thing would make it possible for me to put one “Title” widget (for instance a Text object inside a Container box) into the Header area and have it auto-magically display the Category on each subPage (thus saving me the tedium of placing a custom Title on each subPage).

And then, to take this even further, how about a similar meta-variable that could be used in a Store element.  That way, I could place a store element in the Page area, mark it “Show on All subPages” (you would have to add that, too), then I could duplicate the subPage layout for each subPage.  The meta-variable would grab the subPage name and use it to find the Collection with that same name, and display it in the Store element.  It might need to be something like the Top Page name concatenated to the subPage name to avoid namespace conflicts.   Something like “Shop.Crystals” for the “Crystal” subPage, “Shop.Raw Stones” for the “Raw Stones” subPage, etc.  And, perhaps, to deal with spaces in the name, the variable name could be “Raw_Stones” (i.e. underscore in place of the space)--but then, that would probably be hidden from the User.

## 6
Boneyard – this is a term for a place to store, for instance, retired aircraft (Aircraft Boneyard) objects of technology held for cannibalization.  How about a WiX boneyard – a place to put design elements (i.e. a Sale Banner or an Announcement box – things that one might design, but then, not use right away, or maybe its seasonal or has to do with some anniversary).  I looked for a way to “hide” such an element, but didn't find anything like that.  So, the next best thing would be to be able to put it in a “Boneyard” or archive it some how.  I suppose I could create a Page called “Boneyard” where I could put stuff, then I could Hide the Page, then set the Permissions to “Members Only” and Hide it from the Menu...yeah, that might work!

**Comment by robmen** [comment]
This issue tracker is for the [WiX Toolset][wix] open source project. You probably are looking for [Wix.com support][s].

[wix]: http://wixtoolset.org/
[s]: https://support.wix.com/en/
