### ISSUE TITLE
Build Bootstrapper to install dotnet 3.5

### ISSUE THREAD

**Issue by ahmedpiosol** [wixtoolset/issues#5709]
* Which version of WiX are you building with?

> v4.0.0.5512 

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 community version 15.4.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> WiX Toolset Visual Studio 2017 Extension 0.9.21.62588

* Which version of .NET are you building with?

> .Net framwrok 3.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 AU

* Describe the problem and the steps to reproduce it.

>trying to build my Bootstrapper project to check and install dotnet 3.5 but it keep telling me that i am missing a reference or something despite the face that everything is there
https://imgur.com/XOnqqum

`<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:bal="http://schemas.microsoft.com/wix/BalExtension" xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
  <Bundle Name="DemoMegaSetup" Version="1.0.0.0" Manufacturer="Pioneers Solutions" UpgradeCode="51145e6e-e5b7-4941-98ab-2cf7667992fd" Compressed="yes">
    <BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense">
      <bal:WixStandardBootstrapperApplication LicenseFile="..\ReadMe.rtf"/>
    </BootstrapperApplicationRef>
    <util:RegistrySearchRef Id="NETFRAMEWORK35_SP_LEVEL"/>
    <Chain>
      
      
      <ExePackage Id="dotNetFX3.5" SourceFile="E:\AF\embedded install test\Prerequisites\dotnetfx35.exe" InstallCommand="/qb /norestart" RepairCommand="/qb /norestart" DetectCondition="NETFRAMEWORK35_SP_LEVEL &gt;= 1" InstallCondition="VersionNT &lt; v5.1">
      </ExePackage>
      <MsiPackage Id="DemoSetup" SourceFile="..\DemoSetup\bin\Debug\DemoSetup.msi"/>
    </Chain>
  </Bundle>
</Wix>`

* Describe the behavior you expected and how it differed from the actual behavior.

> it should build my project and give me a setup file but it doesn't

*Note: if i add new project with wix v3 with the same code it works without a problem

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by ahmedpiosol** [comment]
i not here to report a problem on how my code function -so sorry about the title- but to report the fact that my wix project can't detect the references in that project
