### ISSUE TITLE
Major upgrade in Multi Instance mode is installing in Default instance mode\ setting the InstanceType to 0.

### ISSUE THREAD

**Issue by rambabunethi** [wixtoolset/issues#5710]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.8.1128.0

* Which version of Visual Studio are you building with (if any)?

>-

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> -

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows Server 2012, Windows Server 2012 R2, Windows 7. It is seen on all the major operating systems.

* Describe the problem and the steps to reproduce it.
Fresh installation of msi works fine in multiple instance mode.
major upgrade in multi instance mode sets the MSI property InstanceType to 0. So all the files in multiple instances will be installed to the same install directory.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
- <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <?define Win64 = yes?> 
- <Product Id="*" Language="1033" Manufacturer="MyCompany" Name="MyProduct" UpgradeCode="{370E3357-A673-4045-A373-D2B7303709D0}" Version="11.100.388.0">
  <Package Compressed="yes" InstallScope="perMachine" InstallerVersion="301" Languages="1033" Manufacturer="MyCompany" Platform="x64" /> 
  <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." /> 
- <InstallExecuteSequence>
 <InstallServices>NOT Installed</InstallServices> 
  </InstallExecuteSequence>
  - <InstanceTransforms Property="INSTANCENAME">
  <Directory Id="TARGETDIR" Name="SourceDir">
  <Directory Id="D1" Name="Base" /> 
  </Directory>
  <Instance Id="Instance001" ProductCode="{9DC82C10-C8B8-40B9-8166-1002C7C11F11}" ProductName="MyProduct Instance001" UpgradeCode="{03A434CA-29FE-452D-BA59-806B78D5979B}" /> 
  <Instance Id="Instance002" ProductCode="{9AC45083-A50A-43E8-9CDF-8536657509BE}" ProductName="MyProduct Instance002" UpgradeCode="{BA903779-1469-4203-82FF-3B8A9E2270AA}" /> 
  <Instance Id="Instance003" ProductCode="{E6BAB081-CD21-4942-8689-CBB144C4DC4C}" ProductName="MyProduct Instance003" UpgradeCode="{A05E823A-5715-470E-B3FA-13390E96C07C}" /> 
  
  .
  .
  .
  </Wix>

* Describe the behavior you expected and how it differed from the actual behavior.
During major upgrade in multiple transofrm\insance mode, the InstanceType should be set to 1 during Product execution. But it is setting it to 0. 
Executing op: ProductInfo(ProductKey={9DC82C10-C8B8-40B9-8166-1002C7C11F11},ProductName=MyProduct Instance002,PackageName=MyProduct.msi,Language=1033,Version=191103365,Assignment=1,ObsoleteArg=0,,,PackageCode={C044927C-5AD4-4E2E-9975-6C441C144238},,,InstanceType=0,LUASetting=0,RemoteURTInstalls=0,ProductDeploymentFlags=3)

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
