### ISSUE TITLE
Download link is broken at https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2017Extension

### ISSUE THREAD

**Issue by 73UJ34** [wixtoolset/issues#5712]
The download link for Wix Toolset Visual Studio 2017 Extension at the following URL is broken. It just reloads the same page again. I don't know if you have control over that, but it needs to be fixed.

https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2017Extension

**Comment by robmen** [comment]
Visual Studio Team owns that website so (unfortunately) you'll have to follow up with them to address the issue. FWIW, everything works just fine for me in Chrome.

**Comment by 73UJ34** [comment]
Thanks for your help. I had tried FireFox and IE with no luck. Chrome
worked for me.

Thanks again for your quick reply,
Dave
