### ISSUE TITLE
Unable to build custom actions project that imports wix.ca.targets when using WiX 3.11 NuGet Package

### ISSUE THREAD

**Issue by mkelley1972** [wixtoolset/issues#5717]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

> v3.11

* Which version of Visual Studio are you building with (if any)?

> VS2017 Version 15.4.2 (MSBuild 15)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Version:  0.9.21.62588 - NA

* Which version of .NET are you building with?

> .Net version 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows Server 2012 R2

* Describe the problem and the steps to reproduce it.

> We are currently trying to upgrade our build process from VS2015 to VS2017.  To run our builds we use TeamCity Enterprise 2017.1.2.  We have several build agents/servers that build our product.  We are using WiX v3.7 on these build agents in order to support some of our older versions of our product. We are using the WiX 3.11 NuGet package to compile our code base. Specifically we are running into a problem when needing to import wix.ca.targets. We do not have 3.11 on our build machines and do not want to install it. When building via MSBuild 14 (VS2015) we do not require 3.11 on the build machine. However, upon swapping to PackageReference to support VS2017 it now states that we require WiX 3.11 installed on the machine with the below error.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets(10, 5): The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. Could not find wix.ca.targets at 'C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\'. To download WiX Toolset v3.11 (or newer), see http://wixtoolset.org/releases/

Unfortunately, we can not upgrade to Wix v3.11 due to the support of older builds.  We do NOT receive this error when build the solution locally in VS2017 due to having WiX toolset installed.  Is there anyway to get around this in our Wix.CA.targets file?

If there is any additional you need, please let us know.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by mkelley1972** [comment]
Hello barnson,
I've sent 4 previous emails to subscribe to the mailing list and no reply's.  And now the link provided, server is not available.  Is there another site that would support this WiX issue?  Thank you.

**Comment by barnson** [comment]
You can join at http://lists.wixtoolset.org/listinfo.cgi/wix-users-wixtoolset.org.

**Comment by robmen** [comment]
Server was down for a bit. It seems to be back now.

**Comment by mkelley1972** [comment]
Thanks for the follow up Bob and Ron.

I tried joining from the link you provided:  http://lists.wixtoolset.org/listinfo.cgi/wix-users-wixtoolset.org
I attempted to subscribe/join about 4 or 5 time now.  Sent several emails to wix-users-request@lists.wixtoolset.org but still no reply or correspondence from Wix support.  I'm at a lose here and not sure where else to turn at this point.  Do you have any other suggestions?

**Comment by jakubsuchybio** [comment]
I managed to build wix custom action project after adding these into .csproj file:
```
  <Import Project="$(WixCATargetsPath)" Condition=" '$(WixCATargetsPath)' != '' AND '$(Configuration)' == 'Release' " />
  <ItemGroup>
    <Reference Include="Microsoft.Deployment.WindowsInstaller">
      <HintPath>$(WixInstallPath)\Microsoft.Deployment.WindowsInstaller.dll</HintPath>
    </Reference>
  </ItemGroup>
```

The first one will import wix.ca.targets from .nuget package folder. This one populates WixInstallPath property and also populates BeforeClean and AfterCompile targets which are then creating .CA.dll
