### ISSUE TITLE
WiX 4 Roadmap?

### ISSUE THREAD

**Issue by bergmeister** [wixtoolset/issues#5719]
About 5 years ago, Rob blogged the following [here](http://robmensching.com/blog/posts/2012/12/12/the-wix-toolset-v4.0-begins/):
> The next major version of the WiX Toolset is now a couple weeks underway.

I see, commits are still made (or brought forward to?) in the wix4.0 repo but when are we expecting it to be RTM?

**Comment by robmen** [comment]
For general questions try wix-users mailing list. If you want to keep up on the progress of WiX Toolset, the @barnson at FireGiant does a great job posting weekly meeting notes ([latest][]) or you can watch on the YouTube channel.

[latest]: https://www.firegiant.com/blog/2017/10/26/wix-online-meeting-137-highlights/

**Comment by barnson** [comment]
The @barnson indeed.

**Comment by bergmeister** [comment]
Thanks for the links although I was still rather hoping for a rough date for a planned release...

**Comment by robmen** [comment]
9 months
