### ISSUE TITLE
Error LGHT0217 in TFS Build

### ISSUE THREAD

**Issue by MagnusTim** [wixtoolset/issues#5720]
Hi,

I am using Wix 311 and TFS 2017.2 and building a Wix project on a TFS build server.
To be able to run the build correctly the build account has to be local admin and that is not OK in our organisation.

If the build account is not local admin we get this error:
light.exe(0,0): Error LGHT0217: Error executing ICE action 'ICE03'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".

Does anyone have any workarounds except local admin?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
