### ISSUE TITLE
Powershells NewGuid() is not a valid GUID for WiX?

### ISSUE THREAD

**Issue by yamlfd** [wixtoolset/issues#5721]
I'm currently writting a build CMD script for project. To automatically generate a product GUID I used

I tried with lowercase default
`
FOR /F %a IN ('POWERSHELL -COMMAND "$([guid]::NewGuid().ToString())"') DO ( SET PRODUCT_ID=%a )
`

and uppercase GUIDs
`
FOR /F %a IN ('POWERSHELL -COMMAND "$([guid]::NewGuid().ToString().ToUpper)"') DO ( SET PRODUCT_ID=%a )
`

I think the powershell GUID is a valid one, but WiX tells me it is not. Why does WiX do not like the GUID from powershell? Is there any way to generate a GUID on command line that is valid for WiX product ID?

I'm on latest WiX 3.11.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by yamlfd** [comment]
Looks like a bug of WiX. Can you verify this, please?

**Comment by BMurri** [comment]
We use Guid's NewGuid method inside of WiX to generate the certain guids inside of WiX. This does not appear to be a bug of WiX. Please contact wix-users

**Comment by yamlfd** [comment]
Just in case someone has the same issue. The fix was `ToString('b')`. Without the specifier `b` or `d` a "32 digits only" GUID is generated and not a "32 digits separated by hyphens, enclosed in braces". Line breaks inside the brackets are also required.

`
FOR /F %G IN ('POWERSHELL -COMMAND "$([guid]::NewGuid().ToString('b').ToUpper())"') DO (
  SET PRODUCT_ID=%G
)
`
