### ISSUE TITLE
Patching/Updating non versioned files with a small/minor update

### ISSUE THREAD

**Issue by mounikapk** [wixtoolset/issues#5722]
## Feature requests

**This is a feature request**

We are using Wix 3.6, Visual Studio 2013/2017 for installing and creating patches for our product.

**Context around the feature**

We are unable to achieve the below requirement using Wix toolset-
We want a specific flat file, merely a .info file which need to be replaced every time in a patch. This info file has the patch information, which would change with every release. Since, that being a non versioned file, we are not able to achieve this currently.
1. Major release 17.0
2. Minor update patch (Patch1.msp)- 17.1 -> has a new file - env.info
    step 2. places the file in the installation folder for the first time.
3. Small update patch (Patch2.msp) - 17.1.1 -> env.info is updated
    step 3. doesn't replace the file with the new file.

Since this file is nonversioned.

**Need of the feature**

The WIX installer should allow us to add/replace unversioned files in a small/minor patch without being required to add a Companion file to achieve the same. Using a Companion file may not be a flexible way to achieve it, because, we might not have a .dll/versioned binary that changes from time to time. Nor we are very ok to wait for a Major upgrade to achieve this trivial stuff.

**From the design point of view, this is how we can do-**

From my example- We did a major release say 17.0, so, in 17.1 we would like to add a new .info file, which is not supported as of now. For the Wix installer patch to understand if a file has to be replaced every time we apply the patch, we can probably have a 'Replace Always'  attribute which is YesOrNo type, on the File element. This should also take care of the uninstall scenario. This can make a developer's job easy.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
