### ISSUE TITLE
Info: VS 2017 Extension only installs if VS 2017 is run as administrator

### ISSUE THREAD

**Issue by domehead100** [wixtoolset/issues#5723]
## Discussions and support

Just informational...

I tried several times to install the VS 2017 extension for Wix.  Was unsuccessful installing the extension externally (Votive2017.vsix, manually downloaded).  The VSIX installer ran briefly and then disappeared; I had assumed it had installed, but it had not.

I tried using the Extensions and Updates from VS 2017 Enterprise with basically the same behavior: after I closed VS 2017, the VSIX installer appeared briefly and then disappeared.

I don't usually log into my machine with an administrator account.  

Only after launching VS 2017 with "run as administrator" and then doing Extensions and Updates and installing the wix extension did I get a VSIX installer that actually prompted me and then actually took a bit of time and installed the wix extension.

Just noting this; perhaps it should be added to the documentation, or perhaps it already is and I didn't see it.

**Comment by robmen** [comment]
Elevation isn't normally necessary. Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve the installation issue. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
