### ISSUE TITLE
WIX installer no longer asks for elevation on start after WiX Toolset upgrade from 3.10 to 3.11

### ISSUE THREAD

**Issue by VladimirArustamian** [wixtoolset/issues#5725]
Upgraded WiX Toolset from 3.10.0.2103 to 3.11.0.1701 and it stopped asking administrator privileges at the installer launch. During the build process, we sign it with insignia.exe and signtool.exe 
The only difference was switching to a new WIX version.

In the installer logs, I see the difference.

Wix 3.10:

> Command Line: '-burn.unelevated BurnPipe.{D9BD04E1-E48E-45A6-BC15-F9138F44EBA7} {1DA74B3A-E228-4136-81DD-6EE065323F41} 14352'

Wix 3.11

> Command Line: '-burn.clean.room=C:\Users\Arustamyan\Downloads\ParagonBoxAppliance.Agent_5.2.0-alpha-1702-16a27a4.exe -burn.filehandle.attached=300 -burn.filehandle.self=296'

I checked release notes and didn't see anything related. Also, I really need admin privileges from the start.

**Comment by barnson** [comment]
Burn bundles have never prompted for elevation at launch. Nor is doing so supported.
