### ISSUE TITLE
IIS issue - The Windows Installer Service could not be accessed

### ISSUE THREAD

**Issue by sanjuleo** [wixtoolset/issues#5728]
Hi
My web application needs to create dynamic installers which I am doing with wix. My wixsharp installer creation project works well when used from a windows form but when used from the ASP.net MVC project, it throws -
"light.exe : error LGHT0217 : Error executing ICE action 'ICE07'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".
light.exe : error LGHT0216 : An unexpected Win32 exception with error code 0x643 occurred: Action - 'ICE09' Fatal error during installation

Looks like the process being run through IIS does not have access to "Windows Installer Service". Have you encountered such error?

Please advise.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
