### ISSUE TITLE
build of installer project with WIX 3.14.0.1118 fails on missing Microsoft.Build.Utilities 2.0.0

### ISSUE THREAD

**Issue by twest820** [wixtoolset/issues#5729]
* Which version of WiX are you building with?

3.14.0.1118

* Which version of Visual Studio are you building with (if any)?

VS 2017 Community 15.5.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

4.6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

n/a (Windows 10 Fall Creators Update)

* Describe the problem and the steps to reproduce it.

Build break on

3>C:\Program Files (x86)\MSBuild\Microsoft\WiX\v3.x\wix.targets(737,5): error MSB4062: The "ResolveWixReferences" task could not be loaded from the assembly C:\Program Files (x86)\WiX Toolset v3.14\bin\\WixTasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

This Windows 10 system does not have the .NET 3.5 windows feature installed but WIX 3.14 is not expected to require .NET 2.0 msbuild per #5523.  Microsoft has made what should be a trivial feature add unnecessarily difficult so I've not had a chance to get 3.5 on the machine as yet (the .NET 3.5 feature can't be picked up from Windows Update and Microsoft's indicated workaround involves downloading the Media Creation Tool, downloading and mounting a Win 10 .iso, changing the machine's group policy, and a few other steps).

ildasm on C:\Program Files (x86)\WiX Toolset v3.14\bin\\WixTasks.dll gives the below, so there might also be an issue with the Windows Installer reference.

.assembly extern mscorlib
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern System
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern Microsoft.Build.Framework
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:0:0:0
}
.assembly extern Microsoft.Build.Utilities
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 2:0:0:0
}
.assembly extern Microsoft.Deployment.WindowsInstaller
{
  .publickeytoken = (CE 35 F7 6F CD A8 2B AD )                         // .5.o..+.
  .ver 3:0:0:0
}
.assembly extern System.Xml
{
  .publickeytoken = (B7 7A 5C 56 19 34 E0 89 )                         // .z\V.4..
  .ver 4:0:0:0
}
.assembly extern wix
{
  .publickeytoken = (CE 35 F7 6F CD A8 2B AD )                         // .5.o..+.
  .ver 3:0:0:0
}

* Describe the behavior you expected and how it differed from the actual behavior.

Build just works.  Like it did with the same .wxs and WIX 3.11 with the previous Windows 10 install on the same machine.

**Comment by barnson** [comment]
Yep, known issue: https://github.com/wixtoolset/issues/issues/5711

**Comment by twest820** [comment]
Thanks for the quick response; missed #5711 as I searched on other parts of the error.

**Comment by dvorn** [comment]
@twest820 Just to let you know: I enabled .NET 3.5 many times on different computers through "Turn Windows features on or off" and it always downloaded files all by itself.

**Comment by twest820** [comment]
Thanks, that's nice.  For you.  :-p  Rather than get into [the resolution for 0x800F081F](https://support.microsoft.com/en-us/help/2734782/net-framework-3-5-installation-error-0x800f0906-0x800f081f-0x800f0907) I simply retried a few hours ago and had success.  On a different network today, so not sure if it was a transient issue or something about yesterday's location.

Had I known to do so, 3.5 probably would have installed without fuss on the system's first boot while the USB installation drive was still available.  Also haven't ever had issues modifying components on network installed machines in domain environments.  But, like others who've encountered this, I'm a little surprised WIX still relies on .NET 2.0 MSBuild considering .NET 4.0 is eight years old and the 4.5 build tools released five years ago.  Not that I'm quick to change build components either, but the last of my projects moved from 4.0 to 4.5 a year ago.

**Comment by robmen** [comment]
Moving away from .NET Framework v3.5 introduces a breaking change for those people that still depend on it. So, while it wouldn't break you it could break others. They just don't complain because we don't break them.

WiX v4 is where we can introduce breaking changes and WiX v3.14 has breaking changes (like this) to help migrate.

**Comment by twest820** [comment]
Sorry, I'm not sure I'm entirely following.   Sounds like the guidance to use 3.14 on systems without .NET 3.5 which is given in #5523 might be obsolete?  If so, is the preferred workaround now to use 4.0.0?

The breaking changes bit's mentioned in other issues on this issue but I've not come across a spot where it's indicated what the breaking change is.  I can say I didn't have to change anything moving from 3.11 to 3.14.  Does that mean the breaking change would just be a requirement to have .NET 4.0 or newer on the box to build a .msi or is there more to it than that?

Not trying to push back on decisions, just curious to understand the tradeoffs to check if our development environment roadmap can accommodate WIX.

**Comment by robmen** [comment]
No. There is no guidance to use WiX v3.14 right now. It is not released to production yet. You are welcome to use pre-release builds if you want to "live on the edge" (not that v3.14 has lots of churn in it).

Depending on the WiX functionality you use, you will see few to many migration issues in WiX v3.14 on the way to WiX v4.0.

**Comment by twest820** [comment]
Thanks, could you further clarify on one point?  In #5523 you state twice that 3.14 should remove the 3.5 requirement, indicating availability both in April of this year and as of November 28th.  However, this week's build of 3.14 clearly still requires 3.5.  Should those remarks be read as "once 3.14 becomes a recommended build it's not expected to depend on 3.5; check it out at that point"?

If so, is a few months from now about the right timeframe in which 3.14 is expected to replace 3.11?  I checked [your blog](robmensching.com/blog/posts/2017/6/4/lets-code-wix-v3.14/) but it doesn't mention about this, so I'm making a guess based on the 3.10 and 3.11 cadence.  That would put 3.14 out about the same time as [4.0 is expected](https://www.firegiant.com/blog/2017/5/9/wix-online-meeting-127-highlights/), which seems like it might make sense given its stepping stone role.  I'm guessing as to the development motivations, though the transparency with the meeting notes is awesome.

(As an aside, it's probably fair to view this particular issue as us actually being a little past the [WIX 4.0 baseline](https://www.firegiant.com/blog/2017/7/11/wix-online-meeting-130-highlights/), in the sense we just recently completed moving from VS 2015 to 2017.  From our side this is appropriately conservative but, with the eight year history of 3.x, is a bit ahead of WIX at the moment.)

**Comment by robmen** [comment]
It's a bug if WiX v3.14 still requires NETFX v3.5. If an issue is not tracking the specific case where NETFX v3.5 is required, opening one is a good idea so it can be removed.

WiX v3.14 will release on or a bit after v4.0. We won't hit v4.0 production end of this year, trending more toward mid-next year.

**Comment by twest820** [comment]
Appreciate the info.  Bob pointed out #5711 tracks the .NET 2.0/3.5 dependency above, so that seems covered.
