### ISSUE TITLE
DetectRelatedMsiPackage during an upgrade doesn't fire when install is done by system

### ISSUE THREAD

**Issue by Texernie** [wixtoolset/issues#5730]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
Burn v3.11.0.1701

* Which version of Visual Studio are you building with (if any)?
Visual Studio Enterprise 2017 version 15.5.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
Wix Toolset Visual Studio 2017 Extension version 0.9.21.62588

* Which version of .NET are you building with?
4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10 & Windows Server 2016

* Describe the problem and the steps to reproduce it.
When installing a package that has been built with Burn as a user, related msi packages are successfully detected through the DetectRelatedMsiPackage callback. When the package is installed from the system account, the C++ part of burn fails to fully detect the related msi package and therefore does not call the DetectRelatedMsiPackage event. As a result, the managed bootstrap cannot detect previously installed features.

When I run the install as the system account, I get the following lines in the log:
```
    i000: Bootstrapper is ran by NT AUTHORITY\SYSTEM
    i000: Bootstrapper is running is Authenticated = True
    i000: Bootstrapper is running as Anonymous = False
    i000: Bootstrapper is running as Guest = False
    i000: Bootstrapper is running as System = True
    i000: Bootstrapper is running as an Administrator = True
    i000: Bootstrapper is running Elevated = 1
    i100: Detect begin, 1 packages
    i102: Detected related bundle: {291900bb-7cdb-486a-8ddb-372aa1df1fe4}, type: Upgrade, scope: PerMachine, version: 1.0.1.3, operation: None
    e152: Detected related package: {FAB36CB5-330A-48F0-96D5-741B2544367B}, but failed to read language: , error: 0x6ff5a4
    i000: onDetectMsiFeature - [ServerUpdateMsi] [Feature1] [Local]
    i000: onDetectMsiFeature - [ServerUpdateMsi] [CompleteFeature] [Local]
    i000: onDetectMsiFeature - [ServerUpdateMsi] [Feature2] [Local]
```

When I run the install as a user, I get the following lines in the log:
```
    i000: Bootstrapper is ran by ABC\KHenderson
    i000: Bootstrapper is running is Authenticated = True
    i000: Bootstrapper is running as Anonymous = False
    i000: Bootstrapper is running as Guest = False
    i000: Bootstrapper is running as System = False
    i000: Bootstrapper is running as an Administrator = True
    i000: Bootstrapper is running Elevated = 1
    i100: Detect begin, 1 packages
    i102: Detected related bundle: {291900bb-7cdb-486a-8ddb-372aa1df1fe4}, type: Upgrade, scope: PerMachine, version: 1.0.1.3, operation: MajorUpgrade
    i103: Detected related package: {FAB36CB5-330A-48F0-96D5-741B2544367B}, scope: PerMachine, version: 1.0.1.3, language: 1033 operation: MajorUpgrade
    i000: Detected existing related package ServerUpdateMsi (product: {FAB36CB5-330A-48F0-96D5-741B2544367B}) at version 1.0.1.3, which will be MajorUpgrade
    i000: Migrating features for MajorUpgrade of Package ServerUpdateMsi
    i000: Migrating feature Feature1 of Package ServerUpdateMsi - marking as Present
    i000: Migrating feature CompleteFeature of Package ServerUpdateMsi - marking as Present
    i000: Migrating feature Feature2 of Package ServerUpdateMsi - marking as Present
    i000: onDetectMsiFeature - [ServerUpdateMsi] [Feature1] [Absent]
    i000: onDetectMsiFeature - [ServerUpdateMsi] [CompleteFeature] [Absent]
    i000: onDetectMsiFeature - [ServerUpdateMsi] [Feature2] [Absent]
```

* Describe the behavior you expected and how it differed from the actual behavior.
I would expect that detecting related msi packages would behave the same regardless of what user is running the install.

I have attached a stripped down version of my solution. I have confirmed that there can be a single msi package in the chain and the problem still exhibits itself.

[WixPlay3.zip](https://github.com/wixtoolset/issues/files/1543573/WixPlay3.zip)
[run_as_user.log](https://github.com/wixtoolset/issues/files/1543575/run_as_user.log)
[run_as_system.log](https://github.com/wixtoolset/issues/files/1543576/run_as_system.log)

**Comment by barnson** [comment]
Known issue: https://github.com/wixtoolset/issues/issues/5479
