### ISSUE TITLE
Integrate wix installer build into build process

### ISSUE THREAD

**Issue by christophedemey** [wixtoolset/issues#5733]
If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

> 2017 Community

* Which version of .NET are you building with?

> 4.6.2

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information.)

I downloaded binaries from : https://github.com/wixtoolset/wix3/releases/tag/wix311rtm
Unzipped the files in my installer project.

I followed instructions on http://wixtoolset.org/documentation/manual/v3/msbuild/daily_builds.html
I have : 
```
    <WixToolPath>wix\3.11\</WixToolPath>
    <WixTargetsPath>$(WixToolPath)Wix.targets</WixTargetsPath>
    <WixTasksPath>$(WixToolPath)wixtasks.dll</WixTasksPath>
```

Which gives me following error :

```
The "ResolveWixReferences" task could not be loaded from the assembly D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\wix\3.11\wixtasks.dll. Could not load file or assembly 'file:///D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\wix\3.11\wixtasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that ...
```

I can see that the path is all screwed up ProTight.MultiStation.Installer\Wix\3.11\wix\3.11\wixtasks.dll
It appears to duplicate the Wix\3.11 path when searching for the wixtasks.dll.

I know it is finding the Wix.targets because if i change the WixToolPath to a non-existing path, for example wix\3.11\xxx i am getting an error stating that the Wix.targets file cannot be found.

I also tried using full paths :
```
   <WixToolPath>D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\</WixToolPath>
    <WixTargetsPath>D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\Wix.targets</WixTargetsPath>
    <WixTasksPath>D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\wixtasks.dll</WixTasksPath>
```

Which gives me the following error :
```
The "ResolveWixReferences" task could not be loaded from the assembly 
D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\wixtasks.dll. 
Could not load file or assembly 
'file:///D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\wixtasks.dll'
or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> decl
```

When i copy the path from the error : D:\Projecten DJA\ProSuite\ProTight MultiStation\MultiStation\ProTight.MultiStation.Installer\Wix\3.11\wixtasks.dll
and paste it into a file explorer i am asked by windows how to open the dll, so i am 100% sure it is at that location.

I hope this is enough information, please let me know if you need anything else.

Thanks.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by barnson** [comment]
Doc should reflect the changes (as in the project templates) required for MSBuild v15 compatibility.

**Comment by christophedemey** [comment]
Hi @barnson 

Do you know what the problem is ?

**Comment by christophedemey** [comment]
@robmen  @barnson  i am confused, i subscribed to the mailing list, asked the same question as here but just get spammed by other peoples problem.
Is this a documentation problem ?
Can you please help me.

Any help is greatly appreciated.
Thanks.

**Comment by barnson** [comment]
Yes, it's a doc bug.

**Comment by robmen** [comment]
Also, @christophedemey, the mailing list is where the WiX Toolset community supports itself. That isn't spam, it's an for you opportunity to become part of the community to learn so you can get answers your questions and--eventually--help others learn as well.

If you want personalized support for your issues without participating in the WiX Toolset community, I list some [support options](http://robmensching.com/support/) on my website.

**Comment by christophedemey** [comment]
@barnson this still relevant ? i was cleaning up my issues i opened.

**Comment by barnson** [comment]
Yes: https://github.com/wixtoolset/issues/issues/5733#issuecomment-353118755
