### ISSUE TITLE
Add option to suppress hard linking

### ISSUE THREAD

**Issue by NeoAdonis** [wixtoolset/issues#5734]
* Describe the scenario and benefits that the feature supports.

> The idea of this feature is to add an option to the file binder so the user can force the WiX toolset to fully copy outputs instead of just creating hard links to the built components.
> 
> A use-case where this is useful is in our build system where there's a file cache in place, so the output (in this case, hard links) is saved on it. Because of this, when a component is rebuilt, the file projected by those hard links seem to be edited as well, poisoning the cache.

* Describe how you're accomplishing the feature today (if possible).

> Before migrating to WiX 3.11, we had a custom WiX version which included a switch to suppress hard linking, forcing files to be fully copied instead. Currently our build system in charge of building MSIs, the system takes a dependency on this, so in order to support this switch or match the toolset behavior with what's expected, we require to code this .

* Describe what you'd like the new feature to do.

> Add an option to the file binder to suppress hard linking,

**Comment by barnson** [comment]
WiX v4 should be able to be smarter about when to copy -v- hard link: e.g., created files like cabs should be hard-linkable but loose files laid out should be copied.

For v3, a BinderFileManager lets you override CopyFile to prevent hard linking.

**Comment by robmen** [comment]
The standard `CopyFilesToOutputDirectory` is used in v4 overridden in the `wix.targets` but behaves near identical to the standard from `Common.targets`. One modification is that hard linking is enabled by default but it can be disabled by defining the following property in the .wixproj:
    <CreateHardLinksForCopyFilesToOutputDirectoryIfPossible>false</CreateHardLinksForCopyFilesToOutputDirectoryIfPossible>

**Comment by barnson** [comment]
Resurrecting: Currently the MSBuild targets respect the request to not use hard links for _its_ copying of files, but WiX itself uses hard links (if available) for its own layout purposes. This request is to bake an option to avoid hard links into the toolset.
