### ISSUE TITLE
References to .wixproj projects from CS project do not get built by MSBuild from VS 15.5.2

### ISSUE THREAD

**Issue by tg73** [wixtoolset/issues#5735]
* Which version of WiX are you building with?

> 3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

> 15.5.2
> MSBuild 15.5.180.51428

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> Build machine has 4.7.1
> Building a wix extension dll which targets 2.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> I'm building a wix extension dll using msbuild from command line. As is a common pattern with wix extension dlls, there's an associated wixlib in a separate project. The built wixlib is added as an embedded resource to the extension dll. The extension dll `.csproj` has a project reference to the `.wixlib` project, with `<ReferenceOutputAssembly>false</ReferenceOutputAssembly>`. Prior to updating from VS 15.4 to VS 15.5.2, this all worked perfectly - the `.wixlib` project would be built first, then the extension dll `.csproj` would build. Since updating to VS 15.5.2, the build of `.wixlib` is no longer triggered, so the file for the embedded resource in the extension dll is not found.
>
> I don't know whether this bug would be considered a WiX issue, or a VS/MSBuild issue, or both.

* Investigation

> From examining MSBuild logs and prodding around, it seems to boil down to the `.wixproj` exposing no `GetTargetFrameworks` target, which causes target `_GetProjectReferenceTargetFrameworkProperties` (from `Microsoft.Common.CurrentVersion.targets`) to remove the corresponding `.wixproj` item from `@(_MSBuildProjectReferenceExistent)`, and so the referenced project is not built.

* Workaround

> In the project reference in the `.csproj`, add `<SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>`.

**Comment by robmen** [comment]
This is resolved in WiX v4.0.
