### ISSUE TITLE
Enable relative path with double dot in File/@Source attribute

### ISSUE THREAD

**Issue by daliboris** [wixtoolset/issues#5737]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> I want set `@Source` attribute of the `File` element to the parent folder of the Wix project. Double dot is standard way to do this (something like `"$(var.ProjectDir)..\Resources\File.txt"`).
> If I use this kind of relative path with current version of Wix (v3.11) there is an error in during package generation: `ICE03: Invalid Filename; Table: File, Column: FileName, Key(s): FILE_File.txt`.

* Describe how you're accomplishing the feature today (if possible).

> I'm using configuration file in my project to define common variable with absolute path to the parent folde.

* Describe what you'd like the new feature to do.

> When generating contents files relative path should be converted to absolute path. In C# it can be accomplished with `Path.GetFullPath((new Uri(relative_path)).LocalPath)`;

**Comment by barnson** [comment]
Please post the WiX authoring that causes that error.

**Comment by barnson** [comment]
`@Source` works with relative paths. `@Name` must be a legal file name, not a path.
