### ISSUE TITLE
lit.exe fails when -bf is set but works when it is not

### ISSUE THREAD

**Issue by psycorp** [wixtoolset/issues#5738]
Failing command line;

..\..\Compiler\Bins\lit.exe -nologo -bf -v  -b ..\..\..\..  -out "..\..\Lib\E3D\Release\ABA.wixlib" ".\Obj\Release\ABAComponentGroup.wixobj" ".\Obj\Release\data_4.wixobj" ".\Obj\Release\dflts.wixobj" ".\Obj\Release\dra.wixobj" ".\Obj\Release\addins.wixobj" ".\Obj\Release\libmaba.wixobj" ".\Obj\Release\pdmsuser_1.wixobj" ".\Obj\Release\hyperplantfiles.wixobj" ".\Obj\Release\plotfiles.wixobj" ".\Obj\Release\reportfiles.wixobj" ".\Obj\Release\tasks_1.wixobj" ".\Obj\Release\logfiles.wixobj" ".\Obj\Release\pmllib_1.wixobj" ".\Obj\Release\forms_23.wixobj" ".\Obj\Release\functions_24.wixobj" ".\Obj\Release\icons_3.wixobj" ".\Obj\Release\objects_22.wixobj" ".\Obj\Release\usertasks.wixobj" ".\Obj\Release\tasks_2.wixobj"
lit.exe : error LIT0001 : The system cannot find the path specified. (Exception from HRESULT: 0x80070003)

Exception Type: System.IO.DirectoryNotFoundException

Stack Trace:
   at Microsoft.Tools.WindowsInstallerXml.Cab.Interop.NativeMethods.CreateCabFinish(IntPtr contextHandle, IntPtr newCabNamesCallBackAddress)
   at Microsoft.Tools.WindowsInstallerXml.Cab.WixCreateCab.Complete(IntPtr newCabNamesCallBackAddress)
   at Microsoft.Tools.WindowsInstallerXml.Library.Save(String path, BinderFileManager binderFileManager, WixVariableResolver wixVariableResolver)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Lit.Run(String[] args)

omake: Shell line exit status 1. Stop.

omake: Shell line exit status 3. Stop.

Working command line:

..\..\Compiler\Bins\lit.exe -nologo -v  -b ..\..\..\..  -out "..\..\Lib\E3D\Release\ABA.wixlib" ".\Obj\Release\ABAComponentGroup.wixobj" ".\Obj\Release\data_4.wixobj" ".\Obj\Release\dflts.wixobj" ".\Obj\Release\dra.wixobj" ".\Obj\Release\addins.wixobj" ".\Obj\Release\libmaba.wixobj" ".\Obj\Release\pdmsuser_1.wixobj" ".\Obj\Release\hyperplantfiles.wixobj" ".\Obj\Release\plotfiles.wixobj" ".\Obj\Release\reportfiles.wixobj" ".\Obj\Release\tasks_1.wixobj" ".\Obj\Release\logfiles.wixobj" ".\Obj\Release\pmllib_1.wixobj" ".\Obj\Release\forms_23.wixobj" ".\Obj\Release\functions_24.wixobj" ".\Obj\Release\icons_3.wixobj" ".\Obj\Release\objects_22.wixobj" ".\Obj\Release\usertasks.wixobj" ".\Obj\Release\tasks_2.wixobj"

The -out directory does not exist in either case.

If the -out directory does exist then the -bf option does not error.

Wix Toolset version 3.11.1701.0 (also tested with 3.10.3.3319 and it fails there too)

Building using Makefiles (omake) so not within Studio

.NET version is 4.6.1

**Comment by robmen** [comment]
This was fixed quite a while ago, binary .wixlibs are working now in all the wixext projects.
