### ISSUE TITLE
datePicker onBlur event not working

### ISSUE THREAD

**Issue by kpslc** [wixtoolset/issues#5739]
This problem is easy to replicate. 
1. Add a datePicker field to any form. 
2. Add the onBlur event. Do something simple like "console.log("blur event called");"
3. Preview the form. Click in and select a date OR don't select a date
4. Click into another field or outside the date field.

The blur event is not called.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? Using the current web UI from Wix.com

* Which version of Visual Studio are you building with (if any)? not using Visual Studio

* Describe the problem and the steps to reproduce it. See above.

**Comment by barnson** [comment]
This is the tracker for WiX Toolset not Wix.com.
