### ISSUE TITLE
Build Burn with control guard feature (CFG) flag

### ISSUE THREAD

**Issue by assapir** [wixtoolset/issues#5743]
As part of out SDL process, we came up with a problem that our setups doesn't compile with the control guard feature (CFG) flag (/GUARD:CF). 
Is it possible to create it using this flag?
If so, how that possible?

**Comment by michaelcfanning** [comment]
If I can help with this in some way, let me know. A good way to verify is to download the latest BinSkim from [NuGet](https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/1.6.0) or to compile it from [source](https://github.com/microsoft/binskim). Run the tool against setup binaries to verify it is clean. I'm glad to advise on various compiler/linker settings if helpful. 

If it is feasible for me to fork and create a development environment sufficient to validate my changes, glad to attempt a contribution. Previously, this process looked a bit intimidating to me.

**Comment by barnson** [comment]
@michaelcfanning BA2008 is disabled for bundles. Would that be re-enabled if CFG is used?

**Comment by michaelcfanning** [comment]
Yes.
