### ISSUE TITLE
Wix Burn BootStrapper, upgrade individual components creating multiple entries in ControlPanel

### ISSUE THREAD

**Issue by srinivasmsis** [wixtoolset/issues#5744]
For Example : Bundle A contains three msi packages (A 1.0, B 1.0, C 1.0). Created a Bundle and installed the bundle.  We set Visible attribute of MsiPackage element to "Yes". So that the users can upgrade the individual components from ControlPanel.

So now in ControlPanel, the user can see the following 4 entries

Bundle A
A 1.0
B 1.0
C 1.0

Problem : If the user tries to upgrade only B to 2.0 without using Burn. Upgrading individual msi from version 1.0 to 2.0. Control Panel is creating two entries of B (1.0 and 2.0) which is not correct. 

It should identify that B 1.0 is already available which was installed using Burn and it should upgrade to 2.0

We have a requirement to display the entries in Control Panel, so that the users will have the flexibility to upgrade individual items or whole bundle. But it is creating multiple entries in Control Panel.

When we install individual components and upgrade it independently, it is working, but when we install using burn and upgrade individual components, it is not working.

Please share thoughts on this

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
