### ISSUE TITLE
Detailed error message when prerequisite installation fails in Failure page of bootstrapper.

### ISSUE THREAD

**Issue by sudhakarraog** [wixtoolset/issues#5745]
Hi,

I encountered a problem with WixStandardBootstrapperApplication while installing prerequisite for my application and want to show details about the error in error page of the application.

Problem:  Error code is returned/displayed in the FailureMessageText of WixStandardBootstrapperApplication. We want to show the detailed information about the error to the user. 

The error code was displayed when prerequisite .net framework installation failed.
![errorcode](https://user-images.githubusercontent.com/35481122/34990142-fad41e7a-faea-11e7-839b-4e01911a3df3.JPG)

Is there any way to show the detailed message to user if failed to deploy the prerequisites in quiet and passive mode?
 
Please help!

Thanks,
Sudhakararao Garikipati

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/5656
