### ISSUE TITLE
Overlap in bootstrapper OverallProgressPackageText while installation.

### ISSUE THREAD

**Issue by sudhakarraog** [wixtoolset/issues#5746]
Hi,

I encountered a problem in displaying the name of installing package with WixStandardBootstrapperApplication while installing multiple packages for my application.

Problem: The first package's text is not cleared when the second package's text is shown. So there is overlap in OverallProgressPackageText. 

![overallprogresspackagetextoverlap](https://user-images.githubusercontent.com/35481122/34991059-453a374e-faee-11e7-9be2-13bcc3d7ff02.JPG)

Is there any way to avoid overlap text in control and show accurately based on the current package installed or do we required to develop our custom bootstrapper to fix the problem?

Please help!

Thanks,
Sudhakararao Garikipati

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
