### ISSUE TITLE
Display animated gif in WixStandardBootstrapperApplication while installation.

### ISSUE THREAD

**Issue by sudhakarraog** [wixtoolset/issues#5747]
Hi,

We want to show some animated slides while package installation is in progress. Is there any way to get this done in WixStandardBootstrapperApplication/any template  or do we required to develop our custom bootstrapper to get the feature?

Please help!

Thanks,
Sudhakararao Garikipati

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
