### ISSUE TITLE
ComboBox are not visible until the mouse is over

### ISSUE THREAD

**Issue by MikaelFerland** [wixtoolset/issues#5751]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> v3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 version 15.5.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> 4.7.02556

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Pro Version 1709 OS Build 16299.192

* Describe the problem and the steps to reproduce it.

> I created a custom dialog and integrated it to the WixUI_Minimal template. Even If I created a ComboBox or RadioButtonGroup with ListItem or RadioButton. Both element are not shown initialy.
I have to put the mouse over to see the control.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected to see the control when I show the dialog for the first time.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
