### ISSUE TITLE
wixstdba.dll Is Not Authenticode Signed - Install Fails on Device Guard Enabled Machines

### ISSUE THREAD

**Issue by Alois-xx** [wixtoolset/issues#5752]
Wix 3.11 does unpack the dll wixstdba.dll to 
C:\Users\xxxx\AppData\Local\Temp\{AC252FDF-EF3A-4FFA-8C14-D376E50E3139}\.ba\wixstdba.dll
while the bootstrapper UI is shown. Where does this dll come from an can I sign it by myself? 

Currently it is not possible to show a WIX UI on a Device Guard enabled machine because Windows will show the xxxx.exe - Bad Image error. With Error Status 0xe90002.
Can I fix it by myself? Where does this dll come from? I have not found it anywhere in the Wix folders.

**Comment by barnson** [comment]
Tracked via https://github.com/wixtoolset/issues/issues/5329.
