### ISSUE TITLE
Files cannot be upgraded when the versions difference is too big

### ISSUE THREAD

**Issue by HuangSoftHuaShang** [wixtoolset/issues#5757]
## Bug Description
When the installation built with Wix is upgraded from version 4.6.6.3 to 8.17.11.2, some files are not upgraded. However, the files can be upgraded normally from 4.6.6.3 to 7.16.11.4 first, then to 8.17.11.2

The installer file URLs:
http://huangsoft.com/downloads/huashang/4.6.6.3/en-US/HuaShang.exe
http://huangsoft.com/downloads/huashang/7.16.11.4/en-US/HuaShang.exe
http://huangsoft.com/downloads/huashang/8.17.11.2/en-US/HuaShang.exe

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

> WIX 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> Studio 2012

* Which version of .NET are you building with?

> .Net4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Win7

* Describe the problem and the steps to reproduce it.

> First download http://huangsoft.com/downloads/huashang/4.6.6.3/en-US/HuaShang.exe, install it
> Then download http://huangsoft.com/downloads/huashang/8.17.11.2/en-US/HuaShang.exe, install it to upgrade from 4.6.6.3 to 8.17.11.2

* Describe the behavior you expected and how it differed from the actual behavior.

> Some exe or dll files in the installation folder C:\Program Files (x86)\HuaShang\ are not upgraded, they 
 are expected to become version 8.17.11.2, however, they still keep the version 4.6.6.3
>It will be OK if it is upgraded from 4.6.6.3 to 7.16.11.4, then from 7.16.11.4 to 8.17.11.2

Please help find out why. If it is the bug of the installer, please fix it and tell me the new version of fix. If it is something improper on my side, please let me know how to correct it. 

Thank you very much and look forward to your answer and solution.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
