### ISSUE TITLE
SogouInput (ime) crash burndle

### ISSUE THREAD

**Issue by zhou881117** [wixtoolset/issues#5759]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

3.10.4

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2015

* Which version of .NET are you building with?

.net4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

win10  6.2.9200.0

* Describe the problem and the steps to reproduce it.

have 2 exe which build by bundle.
create a new bundle to combine them,like this:
`<PackageGroup  Id="Box" >`
`<ExePackage Id="Box" Name="Box"   `               
             `     InstallCommand='"silent [BoxSetUpCatalog]"'`
               `   InstallCondition="BoxInstallCondition = 1"`
              `    Compressed="yes" Permanent="no"  PerMachine="yes" Vital="yes" Cache="yes"`
              `    SourceFile="..\..\..\..\bin\$(var.MsiOutput)\Setup Box 1.2.1.111 Release.exe" />`
`</PackageGroup>`

star sougou input，which is a chinese ime,**the most used ime in china.**
I don't have any more options.

![image](https://user-images.githubusercontent.com/29134741/35622013-55283000-06c1-11e8-956c-5d84cffa99ab.png)

run the combine bundle exe。the child bundle will crash！

but if i user other ime，it's ok。

the windows log

错误应用程序名称: Box，版本: 1.1.13.47204，时间戳: 0x57570038
错误模块名称: PicFace.dll，版本: 1.1.0.1816，时间戳: 0x5a4dd08b
异常代码: 0xc0000005
错误偏移量: 0x000eed22
错误进程 ID: 0x65c
错误应用程序启动时间: 0x01d3967320696998
错误应用程序路径: C:\Users\ADMINI~1\AppData\Local\Temp\{670F1B36-B980-4347-B567-2053384E8254}\.cr\Box
错误模块路径: **C:\Program Files (x86)\SogouInput\Components\PicFace\1.1.0.1816\PicFace.dll**
报告 ID: 3896d62f-0a10-48c9-b713-574cf9826a1e
错误程序包全名: 
错误程序包相对应用程序 ID: 

i copy it
https://github.com/wixtoolset/issues/issues/5753

**Comment by barnson** [comment]
You need to debug your bootstrapper application.

For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/

**Comment by zhou881117** [comment]
i change child bundle to
`  protected override void Run()`  
     `     {`  
          `    System.Threading.Thread.Sleep(System.Threading.Timeout.Infinite);`
it also crash!

i want to debug wix toolset!

i check out the source to comple,the error

`Strong name validation for the WiX toolset must be disabled on a developer machine to build. Execute 'msbuild C:\Users\Administrator\Desktop\wix4-develop\tools\OneTimeWixBuildInitialization.proj' from an elevated command prompt.	Wix			
`

@barnson

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
