### ISSUE TITLE
Allow to set "DisplayInternalUI" in CustomBA

### ISSUE THREAD

**Issue by danielh1989** [wixtoolset/issues#5760]
## Feature requests

We have multiple MSIs which should be installed with Wix Burn. For some scenarios, the internal UI of some MSIs needs to be displayed to make custom settings. So I need to decide at runtime if the Internal UI of a package should be displayed or not

* Describe what you'd like the new feature to do.

I'd like to set the "DisplayInternalUI" i.e. in the event "PlanPackageBegin" in "PlanPackageBeginEventArgs"

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/3703
