### ISSUE TITLE
WiX 3.11 stdba String Capitalization

### ISSUE THREAD

**Issue by nick2893** [wixtoolset/issues#5761]
In the file src\ext\BalExtension\wixstdba\Resources\HyperlinkTheme.wxl
The string,
Setup will install [WixBundleName] on your computer. Click install to continue, options to set the install directory or Close to exit.

Capitalization seems inconsistent with the buttons.  Why not capitalize "Install" and "Options":
Setup will install [WixBundleName] on your computer. Click Install to continue, Options to set the install directory or Close to exit.
(or un-capitalize "Close")

**Comment by barnson** [comment]
Fixed in https://github.com/wixtoolset/wix4/pull/211.
