### ISSUE TITLE
NetFx ChainingPackage

### ISSUE THREAD

**Issue by iswix-llc** [wixtoolset/issues#5762]
I was looking at how burn installs .net and I came across "/ChainingPackage".  I'm concerned that the default experience is to transmit the bundle name to MSFT without any documentation or opt in / opt out available to the setup developer.

**Comment by barnson** [comment]
.NET Framework redistributable follows machine policy for telemetry so it won't send by default. It would be worth investigating if there's any value to `/ChainingPackage`; if none, we should just drop it, telemetry or no.
