### ISSUE TITLE
Wix installer gets stuck at custom action (rundll32.exe)

### ISSUE THREAD

**Issue by Rishabh-V** [wixtoolset/issues#5765]
It has been observed that running a WiX installer with a custom action is getting stuck once in a while executing custom action. Based on the analysis, the machines in which this issue occurred had not been restarted for 8-9 days. We analyzed the wait chain and found that msiexec was waiting for rundll32.exe. On killing rundll32.exe, the setup rolled back. Any pointers to get around this issue would be great as we are about to release this to customer

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
