### ISSUE TITLE
Request for an --ignore flag to the WiX installer to ignore absence of .NET 3.5

### ISSUE THREAD

**Issue by tsirakisn** [wixtoolset/issues#5767]
Related to #5523 

I am trying to script WiX's installer and I am not able to proceed without enabling .NET 3.5 first. Being that .NET 3.5 is not needed for the installation itself nor is it needed for any of my WiX projects, I would like to request a command line option to ignore .NET 3.5 to avoid needing to reboot my machine.

**Comment by barnson** [comment]
WiX v3.14 already drops the requirement for .NET 3.5.
