### ISSUE TITLE
Error MSB4057: The target "_IsProjectRestoreSupported" does not exist

### ISSUE THREAD

**Issue by armsee** [wixtoolset/issues#5768]
We have a common solution for our application and its installation. A project of the application references NuGet packages (PackageReference). 

In order to be able to build the solution on our build machine, first a restore of the NuGet package is performed (msbuild /t: restore <SolutionName. sln>).

For the bootstrapper and setup project we get a warning NU1503: Skipping restore for project...  and an error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project. 

The error causes the entire build run to be aborted.

It is ok that a warning is issued for this, but an error should not be issued.

We use WiX Toolset 3.11.1 and Visual Studio 2017 (15.5.7)

Output of msbuild /t:restore SdkInstaller.sln

Microsoft (R) Build Engine version 15.5.180.51428 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 21.02.2018 09:42:31.
Project "C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" on node 1 (restore target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Mixed Platforms".
Project "C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" (1) is building "C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj" (2) on node 1 (_IsProjectRestoreSupported target(s)).
C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
Done Building Project "C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj" (_IsProjectRestoreSupported target(s)) -- FAILED.
Project "C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" (1) is building "C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj" (3) on node 1 (_IsProjectRestoreSupported target(s)).
C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.
Done Building Project "C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj" (_IsProjectRestoreSupported target(s)) -- FAILED.
_FilterRestoreGraphProjectInputItems:
  Build continuing because "ContinueOnError" on the task "MsBuild" is set to "WarnAndContinue".
C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj : warning NU1503: Skipping restore for project 'C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj'. The project file may be invalid or missing targets required for restore. [C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln]
C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj : warning NU1503: Skipping restore for project 'C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj'. The project file may be invalid or missing targets required for restore. [C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln]
Restore:
  Committing restore...
  Assets file has not changed. Skipping assets file writing. Path: C:\TPA\Installer\dev\main\SdkInstaller\FeatureValidator\obj\project.assets.json
  Restore completed in 30,67 ms for C:\TPA\Installer\dev\main\SdkInstaller\FeatureValidator\FeatureValidator.csproj.
  
  NuGet Config files used:
      C:\Users\seemueller\AppData\Roaming\NuGet\NuGet.Config
      C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
  
  Feeds used:
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
      https://api.nuget.org/v3/index.json
Done Building Project "C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" (restore target(s)).

Build succeeded.

"C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" (restore target) (1) ->
(_FilterRestoreGraphProjectInputItems target) -> 
  C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj : warning NU1503: Skipping restore for project 'C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj'. The project file may be invalid or missing targets required for restore. [C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln]
  C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj : warning NU1503: Skipping restore for project 'C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj'. The project file may be invalid or missing targets required for restore. [C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln]

"C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" (restore target) (1) ->
"C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj" (_IsProjectRestoreSupported target) (2) ->
  C:\TPA\Installer\dev\main\SdkInstaller\Bundle\Bundle.wixproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.

"C:\TPA\Installer\dev\main\SdkInstaller\SdkInstaller.sln" (restore target) (1) ->
"C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj" (_IsProjectRestoreSupported target) (3) ->
  C:\TPA\Installer\dev\main\SdkInstaller\Installer\Installer.wixproj : error MSB4057: The target "_IsProjectRestoreSupported" does not exist in the project.

    2 Warning(s)
    2 Error(s)

**Comment by barnson** [comment]
This is fixed in WiX v4 with its switch to the common targets.

**Comment by SwooshyCueb** [comment]
Considering that, by all indications, WiX 4 has not yet reached stable status (it's not even in the download section of the website), I wouldn't say WiX 3 (and by extension, this issue) is obsolete quite yet. Perhaps the website needs updating?

**Comment by dahmage** [comment]
With Visual Studio 2017 (15.8.1) release this seems to kill any build that uses restore, rather than just be a warning. (https://developercommunity.visualstudio.com/content/problem/316024/msbuild-restore-fails-on-1581-when-it-worked-on-15.html)

As there is still no sign of WiX v4 being released (after many years of 'next'), any chance of getting this fixed for WiX v3?

**Comment by vbaderks** [comment]
Is there a known workaround to suppress this warning in WiX v3?

**Comment by armsee** [comment]
We solved the problem by calling "restore" only for the C# projects instead of calling "restore" for the whole solution. The following lines in our build target file do this:

    <ItemGroup>
      <SDKPojectFiles Include="$(SDKISourceDirectory)\**\*.csproj"/>
    </ItemGroup>

    <MSBuild Targets="Restore" Projects="%(SDKPojectFiles.Identity)"
                             Properties="$(WixCommonProperties)"/>

**Comment by FamularoA** [comment]
Hello @armsee, unfortunately we encountered the same problem with the WIX setup. Could you describe in which "build Target" file you have included the "hack", thanks.

**Comment by Smurf-IV** [comment]
I did it this way in the `wixproj` file:

(Make the line look like the following: 
```
    <Target Name="EnsureWixToolsetInstalled" Condition=" '$(WixTargetsImported)' != 'true' AND '$(BuildingInsideVisualStudio)' == 'true' ">
```
