### ISSUE TITLE
vc++ project are referenced with a wrong path

### ISSUE THREAD

**Issue by atrebbi** [wixtoolset/issues#5770]
when i add a reference to a vc++ project , the project is marked as missing and variables / files are not accessible
i'm using vs2017 and wix 3.11 ( reproduced with 3.10 too )

steps to reproduce 

create a visual studio solution
add a new vc++ project and a new wix v3 project
reference vc++ project from wix setup
the reference will be marked with a yellow exclamation mark and full path is empty

**Comment by barnson** [comment]
References to .vcxproj work in general. What behavior do you see other than the yellow exclamation mark? Please provide a simple project that reproduces the errors you see.

**Comment by barnson** [comment]
Without more detail, there's not much we can do.

**Comment by atrebbi** [comment]
The first error is that variables are not expanded , I'm getting such errors :
Undefined preprocessor variable '$(var.3B_RULIB_08.11_ENGLISH.TargetPath)'.	Setup_Pipe_Sheet	C:\Sorgenti\MDL\DOT.NET\RILIUTIL\Setup_Pipe_Sheet\Product.wxs	1021

the following is a sample project :
https://www.dropbox.com/s/n2ps4hulhipbqah/ConsoleApplication1.zip?dl=0
I just created a console vc++ application and a wix setup project referencing the project ( nota that it compiles simply because the setup project is empty )

**Comment by atrebbi** [comment]
[ConsoleApplication1.zip](https://github.com/wixtoolset/issues/files/1967438/ConsoleApplication1.zip)

**Comment by barnson** [comment]
Works as expected for me on VS2017 15.6.7, including when I add `<File Source="$(var.ConsoleApplication1.TargetPath)" />`. You might try it with a project that doesn't start with a digit.

**Comment by atrebbi** [comment]
I'm using visual studio 2017 community edition , 15.5.6
I have tried to remove all dots in path names and project names , but the error persists ;
I have two major problems : 
1. I see a yellow icon near referenced projects, ancd in properties full path is empty
<img width="692" alt="screenshot 2018-05-26 20 14 27" src="https://user-images.githubusercontent.com/668879/40579150-84c66074-6121-11e8-990d-aeb25ef930db.png">
2. the compilation fail due to the fact projects are not found and variables are not expanded

**Comment by atrebbi** [comment]
when i open the solution, in full path i find this info , maybe Microsoft.VisualStudio.VCProjectEngine is not in my version of visual studio or wix can't load it for any reason ( language ? windows version ? ):

_Non Ë stato possibile caricare il file o l'assembly **'Microsoft.VisualStudio.VCProjectEngine, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'** o una delle relative dipendenze. La definizione di manifesto dell'assembly specificato non corrisponde al riferimento all'assembly. (Eccezione da HRESULT: 0x80131040)_
