### ISSUE TITLE
The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/

### ISSUE THREAD

**Issue by sujk** [wixtoolset/issues#5776]
I get the below error when even before I compile the code
 <Import Project="$(WixTargetsPath)" Condition=" '$(WixTargetsPath)' != '' " />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets" Condition=" '$(WixTargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets') " />
  <Target Name="EnsureWixToolsetInstalled" Condition=" '$(WixTargetsImported)' != 'true' ">
    <Error Text="The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/" />
  </Target>

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.1

> (WiX version in major.minor.release.build format)
3.11.1

* Which version of Visual Studio are you building with (if any)?
VS Community 2017
> (Visual Studio version, including year and update)
version 15.5.7 -  
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
0.9.21.62588
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
0.9.21.62588
* Which version of .NET are you building with?
.NET Framework 4 
> (.NET version)
4.5
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
microsoft windows 10 Pro
> (Windows version)
10.0.16299 build 16299
* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

It should build and .msi file should be created.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
