### ISSUE TITLE
RemoveRegistryValue documentation implies it can appear inside a RegistryKey element

### ISSUE THREAD

**Issue by jdh28** [wixtoolset/issues#5777]
The docs for the [`RemoveRegistryValue`](http://wixtoolset.org/documentation/manual/v3/xsd/wix/removeregistryvalue.html) element say for the `Key` attribute:

> The localizable key for the registry value. **If the parent element is a RegistryKey**, this value may be omitted to use the path of the parent, or if its specified it will be appended to the path of the parent.

This is incorrect - it doesn't seem like the `RemoveRegistryValue` element can appear inside a `RegistryKey` element.

**Comment by barnson** [comment]
Pull requests are gratefully accepted.
