### ISSUE TITLE
Torch.exe fails to complete on RS3+ OS due to new feature associated with temporary files creation

### ISSUE THREAD

**Issue by Manishd79** [wixtoolset/issues#5778]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

It was identified that running torch.exe is failing on the machines with RS3+ Windows OS. Discussion details:
After talking with .NET Core team about the issue, they came with a workaround for it. This is indeed a bug in torch.exe, brought into light just because of a recent added feature in how temporary files are created inside folders, which can be workarounded by adding the following registry keys to the machine:

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\AppContext]
"Switch.System.DisableTempFileCollectionDirectoryFeature"="true"

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AppContext]
"Switch.System.DisableTempFileCollectionDirectoryFeature"="true"

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 
> 3.7.3503.1 as well as 3.11

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 Enterprise

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> .Net 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> On a RS3+ Windows OS machine, try running torch.exe to create transform

* Describe the behavior you expected and how it differed from the actual behavior.

>Expected is to create transform successfully. Actual is failure with not able to find a part of path, an example 
Command to create Installer Transformfailed with detail as Microsoft (R) Windows Installer Xml Transform Builder version 3.7.3503.1 Copyright (C) Microsoft
Corporation. All rights reserved.  torch.exe : error TRCH0001 : Could not find a part of the path
'g:\hfrepo\src.out\Temp\amd64fre\dtf4zwl2\dtf4zwl2.cab'.  Exception Type: System.IO.DirectoryNotFoundException  Stack
Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)    at
System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare
share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy,
Boolean useLongPath, Boolean checkHost)    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share, Int32 bufferSize)    at Microsoft.Tools.WindowsInstallerXml.Pdb.Load(Stream stream, Uri uri,
Boolean suppressVersionCheck, Boolean suppressSchema)    at Microsoft.Tools.WindowsInstallerXml.Pdb.Load(String path,
Boolean suppressVersionCheck, Boolean suppressSchema)    at
Microsoft.Tools.WindowsInstallerXml.Tools.Torch.Run(String[] args) Binder temporary directory located at
'g:\hfrepo\src.out\Temp\amd64fre\ev04lszf\ev04lszf'. Unbinder temporary directory located at
'g:\hfrepo\src.out\Temp\amd64fre\ev04lszf\ev04lszf'. Torch temporary directory located at
'g:\hfrepo\src.out\Temp\amd64fre\3hxf2wwl\3hxf2wwl'. False

## Feature requests

If this issue is a feature request:

* Torch.exe is essential to create transform and getting broken on RS3+ OS Windows machine leads customer experience to suffer

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> Creating the workaround registry keys as mentioned in the top of this thread.

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please point to a public source for what the `DisableTempFileCollectionDirectoryFeature` switch controls.

**Comment by barnson** [comment]
This is fixed in WiX v4, which no longer uses the temp-file collections.

**Comment by pumaikar** [comment]
There is mistake in registry keys, backslash is missing, correctly it is
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\AppContext]
"Switch.System.DisableTempFileCollectionDirectoryFeature"="true" (without quotation marks)
using "String Value"
