### ISSUE TITLE
VS2013 toolset doesn't fail to build, but exe not the right size

### ISSUE THREAD

**Issue by c-engler** [wixtoolset/issues#5780]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.10.2.2516

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?
VS 2013
version 12.0.40629.00 Update 5
> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
3.10.2.2516
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?
4.7.02053
> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
windows 7
> (Windows version)

* Describe the problem and the steps to reproduce it.
it's a random error that happens, our Bootstrapper project has the chance of creating the package of size 492KB, where the package is suppose to be around 290MB.  I saw it's random because I didn't change anything in our build procedure, for the life of me couldn't get the correct size yesterday.  Today, only had it fail once, then the file was built to the correct size.

My concern is that updating Wix to a newer version may not fix the issue.
> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
We haven't seen any other reports like this. You should consider upgrading to the latest build anyway, to get the security fixes. If it recurs, logs might show something. It's possible something like real-time antivirus is interfering in a way that doesn't cause build errors.
