### ISSUE TITLE
CloseApplication RebootPrompt is ignored

### ISSUE THREAD

**Issue by sztrzask** [wixtoolset/issues#5782]
## Bugs
* Which version of WiX are you building with?

> 3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

> 2017, v15.6.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.,9.21

* Describe the problem and the steps to reproduce it.

Given
>   <util:CloseApplication Id="CloseWord" 
                           Target="WINWORD.EXE" 
                           PromptToContinue="yes" 
                           RebootPrompt="no"
                           Description="Close word to continue">
    </util:CloseApplication>

when installing if user have Word open and chooses `Ignore` on the prompt (from `PromptToContinue`), then after the installation he's still given the restart the PC message, even though the `RebootPrompt` is `no`

* Describe the behavior you expected and how it differed from the actual behavior.

I'd expect that the user is not given the reboot prompt.

**Comment by barnson** [comment]
`RebootPrompt` controls `CloseApplication`'s behavior, not the overall behavior of how MSI deals with files in use.

**Comment by sztrzask** [comment]
@barnson What is `RebootPrompt` supposed to do then?
