### ISSUE TITLE
WiX Toolset v3 build tools must be installed to build - MSBuild on a Docker Image

### ISSUE THREAD

**Issue by paniego** [wixtoolset/issues#5785]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> MSBuild, Microsoft Build Tools 15

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> --

* Which version of .NET are you building with?

> .NET Framework 4.7.1 is installed on the machine, but as I install Wix Toolset with chocolatey(https://chocolatey.org/packages/wixtoolset), it installs automatically 3.5 as well

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> I am trying to build my solution(composed of a IIS and a Wix installer for it) in a Docker Image which contains MSBuild. At first I tried to install there Wix Toolset running the .exe installer in powershell silently, without success (it hanged, perhaps waiting to some input from user). Then i saw the possibility of using Chocolatey, which seems to do the job of installing Wix: after installation and update of PATH, i can run >candle.exe -?  and I get
Windows Installer XML Toolset Compiler version 3.11.1.2318
Copyright (c) .NET Foundation and contributors. All rights reserved.
(...)

However, as the script (CI in gitlab) continues and tries to build the Installer project (IIS gets built without errors) I get:
Project "C:\gitlab-runner\builds\..\..\ProjectName\solution.sln" (1) is building "C:\gitlab-runner\builds\..\..\ProjectName\Setup\Setup.wixproj" (3) on node 1 (Rebuild target(s)).
C:\gitlab-runner\builds\..\..\ProjectName\Setup\Setup.wixproj(91,5): error : The WiX Toolset v3 build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/

* Describe the behavior you expected and how it differed from the actual behavior.

> When building the solution locally (On VS2017, and also WiX Toolset v3.11.1 installed manually) I don't get any problems, so I expect it to run without problems on the Docker Image as well

**Comment by jchoover** [comment]
`  <Import Project="$(WixTargetsPath)" Condition=" '$(WixTargetsPath)' != '' " />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets" Condition=" '$(WixTargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets') " />
  <Target Name="EnsureWixToolsetInstalled" Condition=" '$(WixTargetsImported)' != 'true' ">
    <Error Text="The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/" />
  </Target>`

Instead of running the installer, you could use the binary zip and set the appropriate env vars.

`    <WixToolPath  Condition=" '$(Configuration)' == 'Release' ">Z:\...</WixToolPath>
    <WixTargetsPath>$(WixToolPath)Wix.targets</WixTargetsPath>
    <WixTasksPath>$(WixToolPath)wixtasks.dll</WixTasksPath>
    <WixExtDir>$(WixToolPath)</WixExtDir>
  `

**Comment by jchoover** [comment]
[http://wixtoolset.org/documentation/manual/v3/msbuild/daily_builds.html](url)

**Comment by barnson** [comment]
WiX doesn't explicitly support Docker though should work fine with the right configuration.
