### ISSUE TITLE
Localisation text for ProgressTextFileCost, ProgressTextCostInitialize and ProgressTextCostFinalize does not work

### ISSUE THREAD

**Issue by Roneri75** [wixtoolset/issues#5786]
When using localisation in Wix i have found that the text for ProgressTextFileCost, ProgressTextCostInitialize and ProgressTextCostFinalize is not picked from the any of the language files.
I found this when doing a Swedish installer and it was showing up the English text instead of the Swedish translation.

I tried to insert it in to my own Swedish Localisation wxl file but still no change.
Everything else that i have in my MSI Wix project is translated to Swedish when running the Swedish installer.

I have even tried to change the text in the WixUI_en-us.wxl in the Wix installation but the text for these 3 does not seem to be picked from that file eider.

I'm not sure if this is bug in MSI or if it is a bug inside Wix.

All test has been done in the 3.11.1 version.
All test has been done compiling the MSI with VS2015

**Comment by barnson** [comment]
By default, progress text isn't localized, so the OS localization takes effect. If you want to force a particular localization, see http://wixtoolset.org/documentation/manual/v3/wixui/wixui_localization.html.
