### ISSUE TITLE
Language set to french (1036) in wxs : OK for x86 but not for x64 (english) build

### ISSUE THREAD

**Issue by plmsa** [wixtoolset/issues#5787]
Hi !

We are using the 3.11 version of Wix Toolset on Windows 10 system and we are stuck on a language issue of installer UI.

The language is set on the wxs file : Language="1036"

When we run our x86 installer (x86 plateform on Visual Studio) it's OK, all in french.
But when we run the x64 installer (x64 plateform on Visual Studio)... all in English !!

Someone can help ?

I would appreciate a solution for this !

Thanks

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
