### ISSUE TITLE
Can't installWix Toolset Visual Studio 2017 Extension using chocolately Install-VisualStudioVsixExtension

### ISSUE THREAD

**Issue by theperm** [wixtoolset/issues#5791]
Trying to install the Visual Studio 2017 extension using chocolateys Install-VisualStudioVsixExtension

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Pro

* Describe the problem and the steps to reproduce it.

> Install-VisualStudioVsixExtension -PackageName "WixToolsetExtension" -VsixUrl https://marketplace.visualstudio.com/_apis/public/gallery/publishers/RobMensching/vsextensions/WixToolsetVisualStudio2017Extension/0.9.21.62588/vspackage

* Describe the behavior you expected and how it differed from the actual behavior.

> Expect it to install but instead get the following

WARNING: Missing package checksums are not allowed (by default for HTTP/FTP,                                                                              
 HTTPS when feature 'allowEmptyChecksumsSecure' is disabled) for                                                                                          
 safety and security reasons. Although we strongly advise against it,                                                                                     
 if you need this functionality, please set the feature                                                                                                   
 'allowEmptyChecksums' ('choco feature enable -n                                                                                                          
 allowEmptyChecksums')                                                                                                                                    
 or pass in the option '--allow-empty-checksums'. You can also pass                                                                                       
 checksums at runtime (recommended). See choco install -? for details.                                                                                    
This package downloads over HTTPS but does not yet have package checksums to verify the package. We recommend asking the maintainer to add checksums to   
this package. In the meantime if you need this package to work correctly, please enable the feature allowEmptyChecksumsSecure, provide the runtime switch 
'--allow-empty-checksums-secure', or pass in checksums at runtime (recommended - see 'choco install -?' / 'choco upgrade -?' for details).                
At C:\ProgramData\chocolatey\helpers\functions\Get-CheckSumValid.ps1:167 char:7                                                                           
+       throw "This package downloads over HTTPS but does not yet have  ...                                                                               
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                   
    + CategoryInfo          : OperationStopped: (This package do...' for details).:String) [], RuntimeException                                           
    + FullyQualifiedErrorId : This package downloads over HTTPS but does not yet have package checksums to verify the package. We recommend asking the ma 
   intainer to add checksums to this package. In the meantime if you need this package to work correctly, please enable the feature allowEmptyChecksumsS  
  ecure, provide the runtime switch '--allow-empty-checksums-secure', or pass in checksums at runtime (recommended - see 'choco install -?' / 'choco up   
 grade -?' for details).                                                                                                                                  

Have tried using all the above suggestions butnothing works like --allow-empty-checksums-secure

**Comment by barnson** [comment]
Looks to be a Chocolatey problem.
