### ISSUE TITLE
Installer appears to ignore ConfigureIfExists on iisWebSite

### ISSUE THREAD

**Issue by drummergeek** [wixtoolset/issues#5795]
I am running Wix 3.11.1 and VS2017 Enterprise. 

We are trying to create an installer for a web application, and we set the ConfigureIfExists to "no" on our website. However, when we test an upgrade installation, it overwrites the custom bindings we set after the first installation completed. We need the site to retain its settings during an upgrade, and this function appears to be the one that would do this, but it doesn't work.

To reproduce the problem, do the following.
1. Create an installer that creates a website with ConfigureIfExists set to "no".
2. Run the installer
3. Edit the installed site's bindings.
4. Change the product version in the installer.
5. Run the updated installer.
6. Check the see if your custom bindings still exist on the site.

**Comment by barnson** [comment]
Please attach verbose logs that demonstrate the problem.

**Comment by drummergeek** [comment]
Where would I find these logs?

**Comment by drummergeek** [comment]
Here is a log of the upgrade installation after the site already exists and is configured.
[LogFileUpgrade.txt](https://github.com/wixtoolset/issues/files/1903965/LogFileUpgrade.txt)

**Comment by barnson** [comment]
The log shows that the site is being removed during the upgrade:

> Component: WebClientSite; Installed: Local;   Request: Absent;   Action: Absent

You can make the component permanent or use a different major upgrade scheduling.
