### ISSUE TITLE
Wix bundle removes symbolic link to "Package Cache" when uninstalling and upgrading

### ISSUE THREAD

**Issue by alexsandrovp** [wixtoolset/issues#5797]
* Which version of WiX are you building with?

wix 3.11.1701.0

* Which version of Visual Studio are you building with (if any)?

none, calling candle and light from command line

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

none

* Which version of .NET are you building with?

none

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 1709 x64

* Describe the problem and the steps to reproduce it.

I have my windows in drive C:, which is a smal SSD, and moved the folder **"C:\ProgramData\Package Cache\"** to **"D:\ProgramData\Package Cache\"** to save space. I created a symlink between the two locations as follows (use cmd.exe as administrator):

>cd c:\ProgramData
> mklink /d "Package Cache" "D:\ProgramData\Package Cache"

I can install my bundle normally, and its files are cached in **"D:\ProgramData\Package Cache"** as expected.

However, when I successfully uninstall the bundle, wix removes the symlink in **"C:\ProgramData\Package Cache"**

When subsequent installs are made, wix creates a new **"Package Cache"** folder in **c:\ProgramData**

If I try to uninstall another program that was already installed before the symbolic link was broken, windows cannot find the cached packages in **"D:\ProgramData\Package Cache\"**

The same issue happens when upgrading a bundle. I suspect that is because the old bundle is implicitly uninstalled in the process.

Use the TestBundle.exe (with src) to see the problem happening.
[WixBug - TestBundle.zip](https://github.com/wixtoolset/issues/files/1908509/WixBug.-.TestBundle.zip)

* Describe the behavior you expected and how it differed from the actual behavior.

I expect the symlink to "Package Cache" to remain intact.

**Comment by barnson** [comment]
Not sure if that's supported but there's a policy setting that is: https://blogs.msdn.microsoft.com/heaths/2015/06/09/redirect-the-package-cache-using-registry-based-policy/

**Comment by barnson** [comment]
Per triage, given that Burn has redirection policy, making a symlink work isn't a priority.
