### ISSUE TITLE
System Folder Properties should only be allowed inserted directly under TARGETDIR?

### ISSUE THREAD

**Issue by glytzhkof** [wixtoolset/issues#5799]
This "issue" does not seem to currently affect runtime operation of the compiled MSI.

* Which version of WiX are you building with?

> 3.111

* Which version of Visual Studio are you building with (if any)?

> VS2017 Community Edition 15.6.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> 4.7.02556

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> **SystemFolder** (and I assume other [**System Folder Properties**](http://msdn.microsoft.com/en-us/library/windows/desktop/aa370905%28v=vs.85%29.aspx#system_folder_properties)) can be mixed and matched with regular directory identifiers and moved deep into the regular directory structure without any compiler warnings. At runtime the reserved directory identifiers still seem to resolve properly to the real system folders, but these are protected directory identifiers, and should not be overridden or misplaced?

      <Directory Id="ProgramFilesFolder">
        <Directory Id="Level1">
          <Directory Id="Level2">
            <Directory Id="Level3">      
             <Directory Id="SystemFolder" />       
            </Directory>
          </Directory>
        </Directory>

* Describe the behavior you expected and how it differed from the actual behavior.

> When explicitly defined in the WiX source file (they should only be defined when needed?) these protected folder identifiers should be placed in their correct target locations directly under TARGETDIR -leaving them out of normal directory resolution?

**Comment by robmen** [comment]
This is incorrect. Moving the `SystemFolder` deeper controls your source layout. Totally supported by the Windows Installer.
