### ISSUE TITLE
Summary information code page not set via the WixLocalization element?

### ISSUE THREAD

**Issue by glytzhkof** [wixtoolset/issues#5801]
In essence, **the one line summary** is that the **summary information code page** does not seem to be possible to set in the WixLocalization element attribute in the WiX localization file. Unless I am missing something.

* Which version of WiX are you building with?

> 3.111

* Which version of Visual Studio are you building with (if any)?

> VS2017 Community Edition 15.6.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> 4.7.02556

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> The `[summary information stream code page](https://msdn.microsoft.com/en-us/library/windows/desktop/aa367864%28v=vs.85%29.aspx)` does not appear to be possible to define directly in a standard WiX localization file. It is not available in the WixLocalization element:

` <WixLocalization Culture="ja-JP" Codepage="932" Language="1041" xmlns="http://schemas.microsoft.com/wix/2006/localization">`

I also see no way to set the **Languages** attribute either (is it needed?). Both **SummaryCodepage** and **Languages** can be set in the Package element in the main wxs file. There could also be other settings I am missing. It might shine through that I haven't used localization enough to really write this up properly.

The issue is described in some detail on stackoverflow: https://stackoverflow.com/a/49605354. There seems to be a viable workaround by adding your own localization strings and setting the summary information code page and the languages in the **Package element** in the main wxs source file to these localized strings (described in the linked SO answer). Here is a compressed inline version (in case the SO answer should be deleted for some reason - happens):

Product.wxs
```
<Product Id="*" Name="!(loc.ApplicationName)" Language="!(loc.LanguageLcid)" Version="1.0.0" 
                Manufacturer="!(loc.ManufacturerName)" UpgradeCode="PUT-GUID-HERE">

  <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine" 
           Languages="!(loc.LanguageLcid)" SummaryCodepage="!(loc.SummaryCodepage)" />
```
Japanese.wxl
```
<?xml version="1.0" encoding="utf-8"?>
<WixLocalization Culture="ja-JP" Codepage="932" Language="1041" 
                 xmlns="http://schemas.microsoft.com/wix/2006/localization">
  <String Id="SummaryCodepage">932</String>
  <String Id="LanguageLcid">1041</String>
  <String Id="ApplicationName">各務原市農地支援・畑地管理システムインストーラー</String>
  <String Id="ManufacturerName">(株)テイコク</String>
</WixLocalization>
```
As far as I can see the above approach works. It allows you to compile MSI files with specific code pages and languages and summary code pages set. Testing again, I think you can remove the Codepage and Language attributes from the WixLocalization element above and set only Culture and the xmlns attribute - and then rely on the localized strings for language and summary code page.

I don't have a full overview of how the **WixLocalization element** really works and what settings it overrides and what settings (if any) remain hard coded from the main source file. I don't have the exact details but I seem to recall some unexpected behavior when I was testing it. The Language setting in the WixLocalization element did not seem to take.

* Describe the behavior you expected and how it differed from the actual behavior.

> In my less than educated opinion on the topic, I think all strings and settings potentially affected by localization should be eliminated from the main WiX source file and be replaced with localization variables - as show in the workaround snippet above - whenever localization is used. Or the WixLocalizationElement must override all settings from the main WiX source file?

If you really want to localize, you can have no elements with hard coded English strings anyway, it doesn't make sense to leave anything un-localized in this case? The exception is of course if you need only one language and want to hard code all strings - English or otherwise.

I have not used WiX localization enough to really have an educated opinion. I am going to miss out on something essential and I need to get this submitted - so there is a record of the summary code page issue at least. I'll leave out the rest of my comments and hope the above makes some sense. Off to bed. Localization nightmares will ensue.

Great moments from localization: "Marketing: we want one setup supporting 15 languages with exotic code pages - never mind that it becomes 15 gigabytes large and that bug fixes become difficult. Navajo must be supported. It must show plenty of colorful pictures with localized text in them and the custom installation dialog will have 52 visible features with localized names in them (and the localization "artist" will be screaming: "what is de context-e of these word-e" - in heavy Italian accent - followed by: "I'll be having lunch-e"... - P.S: best guys you'll ever work with: "I must-e capture da passion of our language"). The license agreements will be in living color with localized sound read out loud in native tongue - and pretty localized folder names with lots of Unicode characters will be featured everywhere. Except a few files that will have the same file name for all languages, but have different, localized content. Just to keep things interesting. And we want to register the user's email address and enter a localized serial number to prevent piracy. When can we be done?".

There is a point - a method to the madness: localization really is impossible to deal with. I would actually add as few features for it as possible - keeping them flexible and generic. Just my 2 cents. Applications should be localized and setups should be as simple as can be. I always try to deliver a separate setup per language and avoid multi-language setups (bloat, build time, bug fixing, etc...).

I assume Bob and Rob can delete whatever nonsense does not help above.

**Comment by barnson** [comment]
Let's see if we can default the summary codepage to the codepage of the package.

**Comment by BMurri** [comment]
The package can be set utf-8, but the summary codepage cannot (things break very much, or at least they did in MSI 3.x). Codepage 0 is 7-bit ASCII, so it can't be used by just about anyone except a very small subset of European languages.

What I had to do back in the day for Windows Live clients was to not allow any localization of anything going into the Summary (except the English name of the language) for consistency sake and use utf-8 for the package codepage for all languages that didn't have a non-Unicode codepage.

I don't know if MSI 4 or above have relaxed that restriction. Be sure to test (including using chars that aren't available in non-Unicode codepages) before you are satisfied with your results.
