### ISSUE TITLE
DependencyDetectProviderKeyPackageId regressed to no longer return success after finding first provider key

### ISSUE THREAD

**Issue by MattHyman** [wixtoolset/issues#5803]
DependencyDetectProviderKeyPackageId regressed to no longer return success after finding first provider key.

DependencyDetectProviderKeyPackageId was incorrectly refactored in a448a60ec8fe428058cc3ac01aeae1175b1d6402 to no longer return success after finding the first provider key. This results in incorrect provider behavior if there are multiple provider keys and the target one is not last.

* Which version of WiX are you building with?
3.11

**Comment by MattHyman** [comment]
Preparing a PR for this now.

**Comment by rseanhall** [comment]
Looks like the commit you're referencing is https://github.com/wixtoolset/wix3/commit/a448a60ec8fe428058cc3ac01aeae1175b1d6402. This sounds similar to wixtoolset/wix4#218.

**Comment by MattHyman** [comment]
PR is up at https://github.com/wixtoolset/wix3/pull/464.

**Comment by BMurri** [comment]
Since this PR has been closed, and the issue apparently either doesn't exist in wix4 or was also fixed in v4, shouldn't this issue now be closed?

**Comment by robmen** [comment]
Agreed.
