### ISSUE TITLE
burn /quiet option for MSP that uses DisplayInternalUI=yes still shows UI 

### ISSUE THREAD

**Issue by GregDomjan** [wixtoolset/issues#5806]
* Which version of WiX are you building with?
3.11.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows Server 2016  
(don't believe issue to be specific to OS)

* Describe the problem and the steps to reproduce it.

Having burn bundle to install MSP
using command line /quiet option
UI is seen, such as progress bar 
"Please wait while Windows configures "
"Gathering required information..."

* Describe the behavior you expected and how it differed from the actual behavior.

/quiet mode to not show the UI

**Comment by barnson** [comment]
Please attach bundle log and matching authoring that shows the problem.

**Comment by GregDomjan** [comment]
I think this covers the requested info @barnson 
Zip contains 

- Bundle.wxs  source 
- image showing command line and ui being displayed
- bundle log
- installer log

[MSPBundleIssue.zip](https://github.com/wixtoolset/issues/files/1978959/MSPBundleIssue.zip)

**Comment by barnson** [comment]
Turns out Burn uses different defaults for naked `MspPackage`s than `MsiPackage`s. Not sure why.

**Comment by rseanhall** [comment]
This was fixed in v4.0 as part of https://github.com/wixtoolset/issues/issues/6164.
