### ISSUE TITLE
[Screen Reader - LAPS-Domain Controller - Home Screen] Focus moves to hidden object and narrator reads the inappropriate information on welcome window

### ISSUE THREAD

**Issue by sonimishra** [wixtoolset/issues#5812]
## Bugs

* Which version of WiX are you building with?
3.7.4522.0

* Describe the problem and the steps to reproduce it.
People who depend on screen reader  will not be able to navigate on the screen properly  if narrator focus moves to hidden object in narrator scan mode. 

**Repro Steps:**
1-Go to windows icon and search for remote desktop.
2-Go to the name field and provide the IP address(domain controller) to connect to the domain controller VM.
3-Provide valid username and password for successful connection.
4-Go to LAPS named folder in the desktop and select the executable file:- LAPS 64 bit. Right click on this file and select Install button.
5-Navigate to the Run button appearing on the window and select it.
6. Navigate on the window in Narrator Scan mode using Ups/Down arrow keys.
7. Verify that narrator focus moves to hidden object and narrator reads inappropriate information or not.

**Actual:** Focus moves to hidden object and narrator reads the inappropriate information on welcome window.

**Expected:** Focus should not move to hidden object and narrator should not read the inappropriate information on welcome window.

**Comment by barnson** [comment]
We don't have access to this software and there isn't enough data to determine where a bug might exist. Please provide UI authoring or more evidence the bug is in WiX rather than the software.

**Comment by barnson** [comment]
We need more data, like a screen shot showing the problem.

**Comment by barnson** [comment]
Without clarifying data, we cannot act on this issue.
