### ISSUE TITLE
[Screen Reader - LAPS-Domain Controller - End User License Agreement] Narrator reads 'Blank' when focus moves to license agreement section in Scan mode

### ISSUE THREAD

**Issue by sonimishra** [wixtoolset/issues#5814]
If this issue is a bug:

* Which version of WiX are you building with?
3.7.4522.0

* Describe the problem and the steps to reproduce it.
People who depend on screen reader  will not be able to understand the details of the window , if narrator does reads incorrect information when focus moves to license agreement window.

**Repro Steps:**
1-Go to windows icon and search for remote desktop.
2-Go to the name field and provide the IP address(domain controller) to connect to the domain controller VM.
3-Provide valid username and password for successful connection.
4-Go to LAPS named folder in the desktop and select the executable file:- LAPS 64 bit. Right click on this file and select Install button.
5-Navigate to the Run button appearing on the window and select it.
6-Navigate to various controls lying on the LAPS setup window opened and select Next button.
7-Navigate to license window section on the End user License Agreement window opened.
8. Verify that narrator reads 'Blank' when focus moves license window section in scan mode.

**Actual:** 
Narrator reads 'Blank' when focus moves to license agreement section in Scan mode.

**Expected:** 
Narrator should not read 'Blank' when focus moves to license agreement section in Scan mode. narrator should read the heading mentioned above like "End user license Agreement" .

**Comment by barnson** [comment]
We don't have access to this software and there isn't enough data to determine where a bug might exist. Please provide UI authoring or more evidence the bug is in WiX rather than the software.

**Comment by barnson** [comment]
Without clarifying data, we cannot act on this issue.
