### ISSUE TITLE
[Visual Requirements - LAPS-Domain Controller - Home Screen] Text is not visible on 'Welcome screen' in high contrast Black mode. 

### ISSUE THREAD

**Issue by sonimishra** [wixtoolset/issues#5816]
## Bugs

* Which version of WiX are you building with?
3.7.4522.0 (But I see this bug in the Wix4 repo)

* Describe the problem and the steps to reproduce it.
Users with visual impairment, might not be able to identify and interact with the element properly, if some text is not visible when high contrast settings are applied.

**Pre requisite :** 
1)Set High contrast black theme from system settings.

**Repro Steps:**
1-Go to windows icon and search for remote desktop.
2-Go to the name field and provide the IP address(Domain controller) to connect to the Domain controller VM.
3-Provide valid username and password for successful connection.
4-Go to LAPS named folder in the desktop and select the executable file:- LAPS 64 bit. Right click on this file and select Install button.
5-Navigate to the Run button appearing on the window and select it.
6-Navigate to various controls lying on the LAPS setup window opened.
7. Verify that text is not visible on welcome screen in high contrast black mode.

**Actual:** Text is not visible on 'Welcome screen' in high contrast Black mode .

**Expected:** Text should be visible on 'Welcome screen' in high contrast Black mode .
 
**Note:** Text is visible on 'Welcome screen' in high contrast White mode .

**Test Environment:**
OS: Win Server 2016
Version 1607 (OS Build 14393.2068)

**Comment by v-tgovil** [comment]
HCL

**Comment by barnson** [comment]
We need more data, like a screen shot showing the problem.

**Comment by barnson** [comment]
Without clarifying data, we cannot act on this issue.
