### ISSUE TITLE
Wix Failed to Install

### ISSUE THREAD

**Issue by sherwinsdaniels** [wixtoolset/issues#5819]
Hi I have VS2013 installed and im trying to install WiX toolset however everytime im trying to install it runs then say failed to install, can someone please assist. In control panel there is no instant of Wix Prviously installed.

**Comment by barnson** [comment]
Please provide the information asked for in the issue template.

**Comment by sherwinsdaniels** [comment]
okay after a few attempts i managed to install the latest one.. the older ones dont work on my windows 8
