### ISSUE TITLE
WiX v4: System.NullReferenceException

### ISSUE THREAD

**Issue by DevMichaelSabo** [wixtoolset/issues#5823]
Hello
I have a small setup (WiX v3) added to my VS 2017 solution. (works well)
Now I build a new setup for another similar product and using today WiX v4. (works weill)
In next step, I tryed to porting my first setup from v3 to v4.

Now, every time I build my solution, a error message appears **and Visual Studio terminates!**
The error call stack:

`light.exe : error LGHT0001 : Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.

Exception Type: System.NullReferenceException

Stack Trace:
   bei WixToolset.Data.Rows.FileRow.get_FileSize()
   bei WixToolset.Bind.Databases.AssignMediaCommand.AutoAssignFiles(Table mediaTable, IEnumerable`1 fileFacades, Dictionary`2 filesByCabinetMedia, RowDictionary`1 mediaRows, List`1 uncompressedFiles)
   bei WixToolset.Bind.Databases.AssignMediaCommand.Execute()
   bei WixToolset.Bind.BindDatabaseCommand.Execute()
   bei WixToolset.Binder.BindDatabase(Output output, String databaseFile, IEnumerable`1& fileTransfers, IEnumerable`1& contentPaths)
   bei WixToolset.Binder.Bind(Output output, String file)
   bei WixToolset.Tools.Light.Run()
   bei WixToolset.Tools.Light.Execute(String[] args)

Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei WixToolset.Data.Rows.FileRow.get_FileSize()
   bei WixToolset.Bind.Databases.AssignMediaCommand.AutoAssignFiles(Table mediaTable, IEnumerable`1 fileFacades, Dictionary`2 filesByCabinetMedia, RowDictionary`1 mediaRows, List`1 uncompressedFiles)
   bei WixToolset.Bind.Databases.AssignMediaCommand.Execute()
   bei WixToolset.Bind.BindDatabaseCommand.Execute()
   bei WixToolset.Binder.BindDatabase(Output output, String databaseFile, IEnumerable`1& fileTransfers, IEnumerable`1& contentPaths)
   bei WixToolset.Binder.Bind(Output output, String file)
   bei WixToolset.Tools.Light.Run()
   bei WixToolset.Tools.Light.Execute(String[] args)
   bei WixToolset.Tools.Light.Main(String[] args)`

I find out, that the build/light don't crashed, if I comment out my included merge files. If I added one of them, the build crashes again :(

* Which version of WiX are you building with?

v4.0.0.5918

* Which version of Visual Studio are you building with (if any)?

15.7.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

10.1804

**Comment by barnson** [comment]
Please attach a [Minimal, Complete, and Verifiable example][mcve] that demonstrates the problem.

[mcve]: https://stackoverflow.com/help/mcve

**Comment by DevMichaelSabo** [comment]
Hi, thanks for your response.
Here my project without any files (for size), except one merge module.
I hope you can reproduce it on your developer machine.
Open only the solution and build.

[Setup.zip](https://github.com/wixtoolset/issues/files/2047294/Setup.zip)

**Comment by DevMichaelSabo** [comment]
Was it reproduceable?

**Comment by robmen** [comment]
Not sure the exact commit but this is fixed.
