### ISSUE TITLE
WiX FileSearch MinVersion broken for system folder on Windows 10

### ISSUE THREAD

**Issue by nanoant** [wixtoolset/issues#5824]
Dear WiX maintainers, this may be NOT WiX bug, but Windows / MSI engine bug in general, but I believe WiX should provide some workaround for this bug, because currently `MinVersion` for `FileSearch` is completely unreliable for system dlls.

* Which version of WiX are you building with? **FG-WiX v3.11.10026.27458**
* Which version of Visual Studio are you building with (if any)? **2015 Update 3 (14.0.25431.01)**
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)? **None**
* Which version of .NET are you building with? **4.6.2**
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on? **Windows 10 1703 (OS Build 15063.1088)**

## Describe the problem and the steps to reproduce it.

We use following check to check presence of "Universal C Runtime in Windows":
~~~xml
    <!-- Universal C Runtime in Windows (KB2999226) -->
    <Property Id="UCRTBASE">
      <DirectorySearch Id="UCRTBASESystemFolderSearch" Path="[SystemFolder]">
        <FileSearch Name="ucrtbase.dll" MinVersion="10.0.10240.0"/>
      </DirectorySearch>
    </Property>
~~~
This works for Windows 7, 8, 2012 Server but not on Windows 10! Even the file `C:\Windows\System32\ucrtbase.dll` is 10.0.15063.936 according to explorer:
![image](https://user-images.githubusercontent.com/103067/40608461-e25670ee-626b-11e8-8a72-03c4b769fec5.png)

Some further evidence:
* https://bugs.chromium.org/p/crashpad/issues/detail?id=78#c7
* https://stackoverflow.com/questions/38068477/why-does-getfileversioninfo-on-kernel32-dll-in-windows-10-returns-version-6-2
* https://github.com/PowerShell/PowerShell/issues/2009
* https://stackoverflow.com/questions/34815579/wix-run-vcredist-x64-exe-on-install#comment64865468_35317972
* https://github.com/dokan-dev/dokany/issues/135

It seems that `msiexec` lacks of Windows 8 manifest, and `GetFileVersionInfo` behaves similarly as `GetVersionEx` (https://msdn.microsoft.com/en-us/library/windows/desktop/ms724451%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) replacing `10.0` with `6.2`.
This is NOT documented and really unexpected behavior.

I have made a simple program to demonstrate the issue.
~~~c
#include <stdio.h>
#include <Windows.h>

static PrintVersion(const char* lpszFile) {
	DWORD dwSize = GetFileVersionInfoSize(lpszFile, NULL);
	void* lpVersion = malloc(dwSize);
	UINT uSize;
	VS_FIXEDFILEINFO* lpFileInfo;
	GetFileVersionInfo(lpszFile, 0, dwSize, lpVersion);
	VerQueryValue(lpVersion, TEXT("\\"), &lpFileInfo, &uSize);
	printf ("%s %d.%d.%d.%d (Major.Minor.Build.Rev(QFE)\n", lpszFile,
		HIWORD(lpFileInfo->dwFileVersionMS), LOWORD(lpFileInfo->dwFileVersionMS),
		HIWORD(lpFileInfo->dwFileVersionLS), LOWORD(lpFileInfo->dwFileVersionLS));
}

int main(int argc, char const* argv[]) {
	if (argc < 2) {
		printf("VersionInfo.exe file.exe|file.dll\n");
		return 0;
	}
	for (int argi = 1; argi < argc; ++argi) {
		PrintVersion(argv[1]);
	}
	return 0;
}
~~~

Now the example proving that Windows return different version depending whether the file is in system folder or not:
~~~
> .\VersionInfo.exe C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\ucrtbase.dll 6.2.15063.966 (Major.Minor.Build.Rev(QFE)
> cp C:\Windows\System32\ucrtbase.dll .
> .\VersionInfo.exe ucrtbase.dll
ucrtbase.dll 10.0.15063.936 (Major.Minor.Build.Rev(QFE)
~~~

## Describe the behavior you expected and how it differed from the actual behavior.
The original `MinVersion` check should work on Windows 10, and Windows should NOT alter the true version of file when doing check.

MSI (or WiX) should provide a workaround for broken `GetFileVersionInfo`.

**Comment by barnson** [comment]
WiX can't fix MSI. Burn bundles already get accurate version numbers because the Burn engine is correctly manifested.

**Comment by nanoant** [comment]
So no workaround to get correct versions in MSI? MSI has no tracker, and I doubt I can submit the problem anywhere else than here.

**Comment by robmen** [comment]
@nanoant Microsoft owns the Windows Installer (the engine that processes MSI files). If you want a change to it (such as properly manifesting their executable), you'll need follow up with Microsoft (Windows in particular).

If we could fix Windows Installer bugs we would but we can't so you'll have to contact Microsoft.

**Comment by BMurri** [comment]
A manifested exe would possibly work only if it calls the msi.dll APIs, and most of the "fire-and-forget" style setup exes shell out to msiexec, so they won't work. Further, if the MSI's UI sequence is not run, then it still won't work, because the execute sequence is run from the service.

What happens if you wrap your MSI in burn, and turn on the MSI UI (using the MsiPackage\@DisplayInternalUI attribute)? If that works, then a manifested wrapper exe has the potential to work part of the time.

Opening a support/bug ticket with Microsoft is the only way to get this resolved. Anything else is really a hack.

As an implementation detail, DTF uses rundll32.exe (which is manifested) to host managed custom actions, so a hack that would probably work would be to write a C# CA to query the file version. However, as use of rundll32 is discouraged by Microsoft, it would not be considered a good long-term strategy.

**Comment by barnson** [comment]
Windows is unlikely to fix this -- they could have manifested msiexec.exe, chose not to, and have continued to not do so. Burn is manifested, so its searches work as expected.

**Comment by Nagashravani15** [comment]
HI ,I am facing the simlar problem , is there any workaround , but surprisingly this issue is only in one of our MSI
