### ISSUE TITLE
lit.exe fails to process localization variables in SourceFile attributes

### ISSUE THREAD

**Issue by cschut** [wixtoolset/issues#5827]
* Which version of WiX are you building with?

3.11.2318.0

* Which version of Visual Studio are you building with (if any)?

Visual Studio Professional 2017 (v15.7.1)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

 v0.9.21.62588

* Which version of .NET are you building with?

.NET 4.6.2

* Describe the problem and the steps to reproduce it.

Trying to create a wixlib that contains all the dialogs.
This wixlib contains:

1. several dialog
2. bitmaps
3. a document containing a license agreement (.rtf) 
4. a localization file (.wxl)

One of the dialogs is supposed to present the license agreement in a Text element. In order to load it into this element, the SourceFile attribute is used: `<Text SourceFile="!(loc.LicenseAgreementFile)" />`.
The localization file contains the folowing line: `<String Id="LicenseAgreementFile" Overridable="yes">EULA_en-us.rtf</String>`

When trying to build, lit.exe return two errors:

1. LIT0102: The localization variable !(loc.LicenseAgreementFile) is unknown.  Please ensure the variable is defined.
2. LIT0103: The system cannot find the file '!(loc.LicenseAgreementFile)' with type 'WixControl'.

If I place the value of the localization file into the SourceFile attribute, the wixlib is build without any problems: `<Text SourceFile="EULA_en-us.rtf" />`

These dialogs first existed in the regular wix project. Light.exe was able to understand the localization variable in the SourceFile attribute.

This is an example dialog:
```
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
	<Fragment>
        <UI>
            <Dialog Id="LicenseAgreementDlg" Width="525" Height="413" Title="!(loc.LicenseAgreementDlg_Title)">
                <Control Id="LicenseText" Type="ScrollableText" X="155" Y="100" Width="358" Height="241" Sunken="yes" TabSkip="no">
                    <Text SourceFile="!(loc.LicenseAgreementFile)" />
                    <!--<Text SourceFile="EULA_en-us.rtf" />-->
                </Control>
            </Dialog>
        </UI>
	</Fragment>
</Wix>
```

This is an example localization file:
```
<?xml version="1.0" encoding="utf-8"?>
<WixLocalization Culture="en-us" xmlns="http://schemas.microsoft.com/wix/2006/localization">
    <String Id="LicenseAgreementFile">EULA_en-us.rtf</String>
</WixLocalization>
```

This is the output of the example:
```
C:\Program Files (x86)\WiX Toolset v3.11\bin\candle.exe -dDebug -d"DevEnvDir=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\\" -dSolutionDir=D:\TestProjects\LocalizationTest\ -dSolutionExt=.sln -dSolutionFileName=LocalizationTest.sln -dSolutionName=LocalizationTest -dSolutionPath=D:\TestProjects\LocalizationTest\LocalizationTest.sln -dConfiguration=Debug -dOutDir=bin\Debug\ -dPlatform=x86 -dProjectDir=D:\TestProjects\LocalizationTest\LocalizationTest\ -dProjectExt=.wixproj -dProjectFileName=LocalizationTest.wixproj -dProjectName=LocalizationTest -dProjectPath=D:\TestProjects\LocalizationTest\LocalizationTest\LocalizationTest.wixproj -dTargetDir=D:\TestProjects\LocalizationTest\LocalizationTest\bin\Debug\ -dTargetExt=.wixlib -dTargetFileName=LocalizationTest.wixlib -dTargetName=LocalizationTest -dTargetPath=D:\TestProjects\LocalizationTest\LocalizationTest\bin\Debug\LocalizationTest.wixlib -out obj\Debug\ -arch x86 dialog.wxs
C:\Program Files (x86)\WiX Toolset v3.11\bin\lit.exe -out D:\TestProjects\LocalizationTest\LocalizationTest\bin\Debug\LocalizationTest.wixlib -bf -loc en-us.wxl obj\Debug\dialog.wixobj
D:\TestProjects\LocalizationTest\LocalizationTest\dialog.wxs(6,0): error LIT0102: The localization variable !(loc.LicenseAgreementFile) is unknown.  Please ensure the variable is defined.
D:\TestProjects\LocalizationTest\LocalizationTest\dialog.wxs(6,0): error LIT0103: The system cannot find the file '!(loc.LicenseAgreementFile)' with type 'WixControl'.
```

* Describe the behavior you expected and how it differed from the actual behavior.

I would expect the value of the localization variable to be filled into the SourceFile attribute.

**Comment by barnson** [comment]
Lit.exe doesn't process .wxl files like Light.exe -- the scenario for .wxl files in .wixlibs is to simply store a set of them for when they're used by Light.exe to build a package with a particular culture. You can see what the WixUIExtension did to handle EULAs: https://github.com/wixtoolset/wix3/blob/develop/src/ext/UIExtension/wixlib/LicenseAgreementDlg.wxs.
