### ISSUE TITLE
Lighboxes bugged 

### ISSUE THREAD

**Issue by Dromus** [wixtoolset/issues#5829]
When i add a lightbox in the editor the lightbox looks normal and stays where i put it BUT it's displayed differently in the live version of my website. Either higher or lower than where i put it depending on the resolution.

Editor version: 
![screenshot_1](https://user-images.githubusercontent.com/39757740/40703955-8840dab0-63ef-11e8-88f5-1a9f7474d3c7.jpg)

Preview version:
![screenshot_2](https://user-images.githubusercontent.com/39757740/40703990-a105a742-63ef-11e8-9ae1-60b0fae1d122.jpg)

Live version:
![screenshot_3](https://user-images.githubusercontent.com/39757740/40704001-a86cdd7a-63ef-11e8-912e-d10484b48fb1.jpg)

**Comment by robmen** [comment]
This issue tracker is for the [WiX Toolset][wix] open source project. You probably are looking for [Wix.com support][s].

[wix]: http://wixtoolset.org/
[s]: https://support.wix.com/en/
