### ISSUE TITLE
Elevated Bundle /Layout Generates Files without User Permissions

### ISSUE THREAD

**Issue by andrewderryfarrell** [wixtoolset/issues#5830]
* Which version of WiX are you building with?

> Wix 3.10.4 and newer

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2017, Version: 15.7.3, Last Updated: 06/04/2018

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Wix Toolset Visual Studio 2017 Extension, Version: 0.9.21.65288

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Pro, Version 1803, Build 17134.81. This issue applies to other versions of Windows as well.

* Describe the problem and the steps to reproduce it.

> When a bundle is launched by a user elevated, the Layout process generates files that the user cannot access. The security permissions of the file do not include the user and when you attempt to open or run any of the files, Windows displays the following error dialog: "Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item.".
>
> I believe this issue was introduced by the changes to fix issue #5724 where the working directory was moved to C:\Windows\Temp when the bundle is elevated. By default, Windows does not allow users to access the files within the C:\Windows\Temp directory. The Layout process moves the bundle and downloaded files from the C:\Windows\Temp location to the desired layout directory and the files still have the security permissions that were inherited from the C:\Windows\Temp location. I was able to verify this assumption by giving myself access to the C:\Windows\Temp directory which then allowed me to perform a layout which generated files I could access.
>
> The code I looked at was in the "CalculateWorkingFolder" function and in the "CacheLayoutBundle" function.
>
> I have a custom bundle and this issue is a problem for anyone who installs my bundle using an elevated command line or if they mark the bundle to always "Run as Administrator".
>
> The following are Steps to Reproduce the issue with the WiX 3.11.1 Installer Executable:
>
> 1. Login to a Windows User Account with the default C:\Windows\Temp permissions.
>2. Open an elevated command prompt.
>3. Run the Wix 3.11.1 Installer executable and perform a layout. Ex. wix311.exe /Layout C:\Layout
>4. Open the Layout directory and run the Installer Executable.

* Describe the behavior you expected and how it differed from the actual behavior.

> I would expect the behavior to match the previous versions of WiX. The files that are generated by the Layout can be accessed by the user who ran the bundle even when the user is not the administrator.

**Comment by andrewderryfarrell** [comment]
For now I have rolled back my bundle to use WiX 3.10.3 which does not seem to have the issue. However, this is not the best solution since I am unable to fix the DLL Hijacking issue or get the latest changes. Is there an estimated time frame for the release of 4.0 or when this issue might get looked at?

Thanks!

**Comment by barnson** [comment]
You can see the triage discussion here: https://www.firegiant.com/blog/2018/6/7/wix-online-meeting-150-highlights/
