### ISSUE TITLE
(upgrading) Installing MSI over BUNDLE doesn't remove existing product

### ISSUE THREAD

**Issue by adnanshaheen** [wixtoolset/issues#5832]
Upgrading an existing product via MSI that was installed via BUNDLE doesn't remove the existing product. There are two entries in Programs & Features. (upgrading BUNDLE over BUNDLE and MSI over MSI works fine, and does remove the existing product).

* Which version of WiX are you building with?
> 3.11.1.2318
* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 Pro, 15.6.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Wix Toolset Visual Studio 2017 Extension, Version: 0.9.21.65288

* Which version of .NET are you building with?

> .NET version: 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows version: 10 [Version 10.0.17134.48]

* Describe the problem and the steps to reproduce it.

> Create an MSI, and then make a BUNDLE with chaining same MSI. Install the product via BUNDLE. Then update the version info. Build the MSI and then bundle it again. Install (upgrade) the product via MSI. Previous product is not removed. Programs & Features have duplicate entries for product. One from BUNDLE and one from MSI.

* Describe the behavior you expected and how it differed from the actual behavior.

> Not sure if this is expected behavior or not. But I assume it is not, since upgrading a product via BUNDLE over MSI does remove the existing product. In my case, the existing product can be removed if upgrade is done with BUNDLE over BUNDLE upgrade, BUNDLE over MSI upgrade, MSI over MSI upgrade. But not in case of MSI over BUNDLE upgrade.

* Describe how you're accomplishing the feature today (if possible).

> considering it as expected behavior

**Comment by barnson** [comment]
Bundles know how to upgrade MSIs and bundles. MSIs don't know how to upgrade bundles so they just upgrade the MSI.
