### ISSUE TITLE
Heat -generate payloadgroup

### ISSUE THREAD

**Issue by ryatpronk** [wixtoolset/issues#5833]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
> (WiX version in major.minor.release.build format)
3.11; It isn't clear to me how to find the ".release.build" parts of the toolset.

* Which version of Visual Studio are you building with (if any)?
> (Visual Studio version, including year and update)
Microsoft Visual Studio Community 2017 Version 15.7.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
WiX Toolset Visual Studio Extension 0.9.21.62588

* Which version of .NET are you building with?
> (.NET version)
"About Microsoft Visual Studio" says Version 4.7.02558.

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> (Windows version)
N/A

* Describe the problem and the steps to reproduce it.
> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
Running "heat.exe -generate payloadgroup"  creates separate components versus a named payloadgroup for burn.exe.

* Describe the behavior you expected and how it differed from the actual behavior.
> (Be as specific as you can and err on the side of providing too much information.)
See above.

**Comment by sonicbhoc** [comment]
I am experiencing the same issue. I always get directoryref/directory/component/file instead of a payloadgroup output no matter what I do.

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by MikeRosoft** [comment]
It appears that generating PayloadGroup does not work at all. (Why does the documentation list a feature which doesn't exist?) I have tried copying the command from another project which uses heat.exe for generation of components for MSI installer and added '-generate payloadgroup'; I got the Directory/Component/File directives. I tried various variants of the command (in case some of the options caused the error, or in case the error was dependent on parameter order) and eventually stripped it to just the necessary part:

`"$(WixInstallPath)\heat.exe" dir "$(SolutionDir)\BootstrapperInstaller.Msi\bin\$(ConfigurationName)" -generate payloadgroup -out "$(ProjectDir)\ApplicationFiles.wxs"`

Nothing worked. (I also tried '-generate:payloadgroup'.)

My Wix version is 3.14.0.2927.

**Comment by rseanhall** [comment]
It appears that today, the `-generate` option is only supported by project harvesting (`heat.exe project ...`).

@MikeRosoft that's not what his response means. It means that no one has volunteered to fix it in their free time, so it's unknown when this will be implemented. He then provides some more information if that timeline doesn't work for you.

**Comment by rseanhall** [comment]
I implemented `heat.exe dir -generate payloadgroup` in v4.0 - https://github.com/wixtoolset/issues/issues/3470.
