### ISSUE TITLE
Should ProgramFiles6432Folder work with Candle?

### ISSUE THREAD

**Issue by ryatpronk** [wixtoolset/issues#5835]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
> (WiX version in major.minor.release.build format)
3.11; It isn't clear to me how to find the ".release.build" parts of the toolset.

* Which version of Visual Studio are you building with (if any)?
> (Visual Studio version, including year and update)
Microsoft Visual Studio Community 2017 Version 15.7.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
WiX Toolset Visual Studio Extension 0.9.21.62588

* Which version of .NET are you building with?
> (.NET version)
"About Microsoft Visual Studio" says Version 4.7.02558.

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> (Windows version)
Windows 7 Home Premium Service Pack 1

* Describe the problem and the steps to reproduce it.
> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
Used <Directory Id="ProgramFiles6432Folder"> in a Setup project (i.e. not Burn) and it placed the files in the parent directory instead.

* Describe the behavior you expected and how it differed from the actual behavior.
> (Be as specific as you can and err on the side of providing too much information.)
I didn't realize it was burn-only, since the ProgramFiles64Folder variable works fine. If ProgramFiles64Folder is also a burn-only variable, why does it place it in the correct location, while ProgramFiles6432Folder does not? I'd expect ProgramFiles6432Folder.

Sorry, I don't know if this is a bug or not, because documentation hardly gives implementation examples and is very terse on explanations. Also, burn, candle, heat, etc. documentation isn't clearly separated and organized. A lot of things are trial-and-error until I can get it to work.

**Comment by BMurri** [comment]
Candle is used for both bundles and MSI packages.

ProgramFiles64Folder is defined by Microsoft in Windows Installer, which is why it works. A pair of SetProperty elements properly scheduled would provide the functionality your looking for.
