### ISSUE TITLE
The Exit Dialog does not show up at completion of installation using Visual Studio 2015

### ISSUE THREAD

**Issue by ChingMLai** [wixtoolset/issues#5836]
Recently I have installed Wix Toolset v3.11.1 build tools and Wix Toolset Visual Studio 2015 Extension.  I switched from using Visual Studio Setup project to Wix install project.  Everything works well in my Visual Studio 2015 Wix Install project except one problem.  The problem is that the Exit Dialog does not show up at the completion of installation.  In fact, the Error Dialog does not show up either when error occurs.  I try to implement custom dialogs but it was reject with error message of CE20: Standard Dialog: 'FilesInUse' not found in Dialog table.

Holden

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
