### ISSUE TITLE
Error installing Wix Toolset Visual Studio 2017 Extension

### ISSUE THREAD

**Issue by elenaaralla** [wixtoolset/issues#5838]
[VSIXInstaller_619dd5be-2975-4c0a-8ee7-4c76653f3e0c.log](https://github.com/wixtoolset/issues/files/2119518/VSIXInstaller_619dd5be-2975-4c0a-8ee7-4c76653f3e0c.log)
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

>v3.11.1 

* Which version of Visual Studio are you building with (if any)?

>Microsoft Visual Studio Professional 2017 
>Versione 15.7.3
>VisualStudio.15.Release/15.7.3+27703.2026
>Microsoft .NET Framework
>Versione 4.7.03056

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> I tryed to install it from Visual Studio- Tools->Update and Extension
> Identifier         : WixToolset.VisualStudioExtension.Dev15
> Name               : Wix Toolset Visual Studio 2017 Extension
> Author             : .NET Foundation and contributors
> Version            : 0.9.21.62588

* Which version of .NET are you building with?

> .NET Framework 3.5, NET Framework 4.7 Advanced Services

* Describe the problem and the steps to reproduce it.

> I downloaded wix311.exe  from https://github.com/wixtoolset/wix3/releases/tag/wix3111rtm
> and installed with no problem; 

>Then I tryied to install Extension for Visual Studio 2017 from Tools->Update and Extension
> but errors occur (see attached logs)

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect to Install WiX, install Extension for Viual Studio 2017 and complete the step in "Creating a Simple Setup" 
>  (http://wixtoolset.org/documentation/manual/v3/votive/authoring_first_votive_project.html)
> but I'm not able to install the extension and therefore I can not complete the "Creating a Simple Setup" steps

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
