### ISSUE TITLE
Adding to the WiX Documentation

### ISSUE THREAD

**Issue by tsahi** [wixtoolset/issues#5839]
Some time ago started creating an install package using WiX. Pretty quickly I realized the learning curve is quite steep, and the online documentation is not complete, and sometimes contradictory. Being a good netizen, I wanted to contribute what I've learned back to the WiX documentation, so others can learn from my experience. I found out that the wixtoolset.org is actually [here on GitHub](https://github.com/wixtoolset/web), so I forked and added content, and submitted two [pull](https://github.com/wixtoolset/web/pull/33) [requests](https://github.com/wixtoolset/web/pull/34). They were quickly declined, because I was on the wrong repo. I had no way of knowing that, because again, the documentation is incomplete.

So the issue here is that the documentation on [how to add documentation](http://wixtoolset.org/documentation/manual/v3/wixdev/help_development.html) is incomplete and confusing.

My next pull request will first expand on how to add documentation, and then I'll make the other two against the wix v3 documentation, which is still the stable release you recommend using.

**Comment by BMurri** [comment]
Thank you.
