### ISSUE TITLE
Strange RichEdit behavior in Burn with Turkish keyboard

### ISSUE THREAD

**Issue by denis-gz** [wixtoolset/issues#5843]
### Steps to reproduce:
0. Prerequisites: Have some Burn-based installer, configured to use standard WixStdBA module with RtfLargeLicense theme. For example, vcredist_x86.exe from MSVC2015 will do.
1. Install Turkish language in the system, along with Turkish keyboard layout (e.g. TRQ)
2. Open CMD console, switch to TRQ layout (or just run from Desktop with TRQ layout active)
3. Run the installer you prepared
4. Quit installer, either cancel or let it run to the end
5. Notice the active keyboard layout, on step 3 and step 4
### Expected result:
Active keyboard layout doesn't change (so it still should be TRQ on step 3 and 4).
### Actual result:
Active keyboard layout changes to the previous one before TRQ was set (e.g. ENG).
### Comments/details:
The strange thing is this is only happening with Turkish layouts. Spanish, German, Russian, etc. does not show such behavior with Burn.

As I was able to investigate, the bug concluded in RichEdit control which is used in RtfLargeLicense theme. For some reason, the code inside RICHED20.DLL calls ActivateKeyboardLayout with different layout than currently selected. Previously GetKeyState with VK_SHIFT argument reports incorrect state for Shift key(s), so may be this triggers the bug (this doesn't happen with other layouts).
### Suggested fix/workaround:
Just use newer MSFTEDIT_CLASS when you create RichEdit control, instead of older RICHEDIT_CLASS which is used currently. This change also implies changing the library to load - MSFTEDIT.DLL to replace RICHED20.DLL. This library exists on at least Windows XP SP3 (cannot check older SP) and later versions, and works perfectly as a drop-in replacement. Probably other issues could be fixed as well, as on Win10, this is of version 3.1 vs. version 8.5 of MSFTEDIT.

**Comment by rseanhall** [comment]
I updated v4 to use `MSFTEDIT_CLASS` from `MSFTEDIT.dll` when available. I'm not sure if that has fixed this issue or whether more work is required.
