### ISSUE TITLE
wix4 MSBuild task specifies `-cultures` but wix.exe uses `-culture`

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5847]
* Which version of WiX are you building with?

> Core @ 1a2d7994764060dc6f8936fab1c03e255f2671c5

* Which version of Visual Studio are you building with (if any)?

> 15.7.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> 4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a

* Describe the problem and the steps to reproduce it.

> `DoIt` specifies `"-cultures "` but `ParseStandardCommandLine` switches on `"culture"`.

* Describe the behavior you expected and how it differed from the actual behavior.

> Either `ParseStandardCommandLine` should support both or should be consistent.

**Comment by robmen** [comment]
Fixed by https://github.com/wixtoolset/Core/commit/06835732a8e6e9d18d548fbb4487bcaf5c8e1725
