### ISSUE TITLE
Burn: Patches fail to install when multiple patches present

### ISSUE THREAD

**Issue by GregDomjan** [wixtoolset/issues#5851]
Bug?  Seemed related to #3538  Burn:patches with same version breaks DetectTargetMsiPackage

* Which version of WiX are you building with?
3.11.0

* Visual Studio to build burn/BA.dll
2017 15.6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10 

* Describe the problem and the steps to reproduce it.

Burn package reports success but fails to install MSP from chain if the suitable MSP is after first 2 listed in chain (16 MSP listed 64/32 bit then by en/de/fr/es/jp ...) where ProductID should match
So we can patch EN 64  but DE 64 fails.
Running the DE 64 msp directly works.

debugging burn vpfnMsiDetermineApplicablePatchesW pPatchInfo
```
For EN 64 
  Item 0
    dwOrder = 0
    uStatus = 0
  Item 1
    dwOrder = -1
    uStatus = 1642
  Item 2-15
    dwOrder = -1
    uStatus = 87
```

```
For DE 64
  Item 0/1
    dwOrder = -1
    uStatus = 1642
  Item 2-15
    dwOrder = -1
    uStatus = 87
```

Re ordering the chain so that the 1 or both MSP for DE come before the 2 for EN, EN 64 then fails with uStatus 1642
So it seems only first MSP in chain can be installed.

Unclear on referring to doc, does 87 mean invalid parm, and how to fix
https://docs.microsoft.com/en-us/windows/desktop/api/msi/nf-msi-msidetermineapplicablepatchesa
https://docs.microsoft.com/en-us/windows/desktop/msi/error-codes

* Describe the behavior you expected and how it differed from the actual behavior.

Burn should be able to match installed package with MSP in chain and have MSP installation run.

MSP evaluated for install against packages could be reduced to just those with suitable conditions?

**Comment by barnson** [comment]
Please attach your WiX authoring and bundle log showing the results.

**Comment by GregDomjan** [comment]
[en-log.zip](https://github.com/wixtoolset/issues/files/2212683/en-log.zip)
[de-log.zip](https://github.com/wixtoolset/issues/files/2212684/de-log.zip)
Source [sample.zip](https://github.com/wixtoolset/issues/files/2212689/sample.zip)  
it0010 wixlib with guids, msi and bundle of msi,  
it0011 msi with version increment, msp patch, bundle of msp.
Compiled sample [demo.zip](https://github.com/wixtoolset/issues/files/2212685/demo.zip)

**Comment by barnson** [comment]
Your EN and DE patches have the same patch code, so they collide. They need unique patch codes.

**Comment by GregDomjan** [comment]
Making the  Product@UpgradeCode unique for each language and 32/64 didn't change anything.

**Comment by GregDomjan** [comment]
When I try to provide an id through wxl, I get the error 
```Patch.wxs
[INFO] candle.exe : error CNDL0001 : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).```

Following similar pattern to msi 
```
  <?if $(var.Platform)="x64"?>
  <?define PatchCode=!(loc.PatchCode32) ?>
  <?else?>
  <?define PatchCode=!(loc.PatchCode64) ?>
  <?endif?>
  
	<Patch Id="$(var.PatchCode)"
		AllowRemoval="no"
```

Did I miss something, known limitation?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).
