### ISSUE TITLE
Candle.exe should warn (instead of error) on duplicate preprocessor variables

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5853]
Change request: Candle.exe currently emits an error if the same variable is specified more than one in `-d` switches, regardless of value. The preprocessor handles this case with warnings, regardless of value. Instead, both should be warnings if the values are the same.

* Describe the scenario and benefits that the feature supports.

> To be kind to the user who accidentally ended up with multiple `DefineConstants` in their .wixprojs.

* Describe how you're accomplishing the feature today (if possible).

> Being extremely precise about shared .wixproj authoring to avoid duplicates.

* Describe what you'd like the new feature to do.

> (See above.)

**Comment by snowmoonsoftware** [comment]
Bump 👍 :)
