### ISSUE TITLE
Unable to launch Bundle (elevated) if access to 'WINDIR\Temp' folder is limited by SRP 

### ISSUE THREAD

**Issue by Mefor** [wixtoolset/issues#5856]
* Which version of WiX are you building with?

> WiX v3.11.1

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2017, Version: 15.7.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> WiX Toolset Visual Studio Extension version 0.9.21.62588

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 or any other version.

* Describe the problem and the steps to reproduce it.

>Unable to launch Bootstrapper Application in the following scenario:
1) Prerequisite:
     'Software Restriction Policies' is configured to block all executables from '%WINDIR%\Temp' folder.  
![local group policy editor](https://user-images.githubusercontent.com/6043968/43364825-ccfcf2c8-932a-11e8-8686-113840b5bc01.png)
      It is common security practice to block viruses and malware via 'Software Restriction Policies' configuration.
2) Steps to reproduce:
    a) Configure machine 'Software Restriction Policies' as it described in 'Prerequisite'(2) section.
    b) Run 'Bundle.exe' as 'Administrator'.
   Actual result: bundle won't be launched with the following error:
```
   Error 0x800704ec: Failed to launch clean room process: "C:\WINDOWS\Temp\{AB10C981-0D7D-4AA6-857F-CC37696DB4BE}\.cr\Bundle.exe" -burn.clean.room="C:\Test\Bundle.exe" -burn.filehandle.attached=652 -burn.filehandle.self=656 -log "C:\Test\bundle.log"
   Error 0x800704ec: Failed to run untrusted mode.
```
![event viewer](https://user-images.githubusercontent.com/6043968/43364903-6c7879ca-932c-11e8-958c-6cf91b05a30f.png)

* Describe the behavior you expected and how it differed from the actual behavior.

> I would expect that bundle allow to specify "clean room" location via command line parameter or engine has some kind of 'fallback' logic that will redirect "working folder" to users '%TEMP%' folder in case of any issues with '%WINDIR%\Temp' folder.

* Additional information during workaround searching (optional).

> I was trying to add 'Bundle.exe' to the 'whitelist' by adding additional 'Path Rule' to the 'Software Restriction Policies' with the help of the **Path rule precedence** ([doc link](https://technet.microsoft.com/pt-pt/library/cc786941(v=ws.10).aspx)):
  When there are multiple matching path rules, the most specific matching rule takes precedence.
The following is a set of paths, from highest precedence (more specific match) to lowest precedence (more general match):
```
Drive:\Folder1\Folder2\FileName.Extension 
Drive:\Folder1\Folder2\*.Extension 
*.Extension 
Drive:\Folder1\Folder2\ 
Drive:\Folder1\
```
  But, it seems like it is not possible because 'whitelist' rule for path '%WINDIR%\Temp\{guid}\.cr\Bundle.exe will look like '%WINDIR%\Temp\{????????-????-????-????-????????????}\.cr\Bundle.exe' and as it has '?' wildcards it does not override '%WINDIR%\Temp\' or '%WINDIR%\Temp\ *\ *\ *.exe' rules.

  Another option to 'whitelist' Bundle.exe is to add 'Hash Rule' for the unpacked ''%WINDIR%\Temp\{guid}\.cr\Bundle.exe', but it will require to has unpacked 'Bundle.exe' from machine that has no issues with using '%WINDIR%\Temp' folder, because file hashes of the 'real' unpacked Bundle.exe and one that is generated by 'insignia.exe' tools doesn't match.

**Comment by aristippus** [comment]
Could the folder be specified as an argument, rather than being a "hardcoded" path, or even a set of hardcoded fallback paths, which seemed to be the approach you were entertaining? Organizations with these kind of controls would generally have specified allowed locations to execute from.

This link mentions using certificate rules to avoid the problem, which is fine, but you can get complaints from users about the performance hit.

https://social.technet.microsoft.com/Forums/windows/en-US/a7a6d44c-f5fe-4fab-9365-8d8b5aeb8e1c/software-restriction-policies-and-installers-that-use-temp-folders

**Comment by robmen** [comment]
Specified as an argument is an option. The discoverability on all non-automatic options is really poor and automatic options have the issue that we have to pick perfect locations. We haven't landed on the perfect solution, yet (although, I am really starting to lean towards logging that a special command-line option must be used--as you suggested originally--and be done with it).

**Comment by AlexKub** [comment]
Have the same problem with antivirus settings. In my company not allow to launch any *.exe from temp directories. So i am not able to run any bootstraper project result because it create a copy in temp, launch it and get block from antivirus.
Details in [this question](https://stackoverflow.com/questions/52977390/wix-bootstrap-prevent-temp-directory-use).

**Comment by kmaciolek** [comment]
Same issue in my company, we got Software Restriction Policies so I'm unable to install Python..

```
Error 0x800704ec: Failed to launch clean room process: "C:\WINDOWS\Temp\{4503D88F-1BC3-44F2-93B9-481712C7D1FB}\.cr\python-3.7.1-amd64.exe" -burn.clean.room="C:\Utilisateurs\<user>\Downloads\python-3.7.1-amd64.exe" -burn.filehandle.attached=196 -burn.filehandle.self=204 
Error 0x800704ec: Failed to run untrusted mode.
```

**Comment by robmen** [comment]
@KevinMckk you can avoid this issue by not launching the bundle elevated.

**Comment by jaspar** [comment]
We are facing the same issue with one of our customers who is not able to install our software. The same customer is able to install an earlier version of our software that was built using WiX 3.10.3 though. Could anyone comment on this change of behavior?

**Comment by robmen** [comment]
The change in behavior was a security fix to v3.10.3 thus v3.10.3 is insecure. In fact, the root issue was the sole reason for v3.10.4.

This issue hasn't affected us or any of our customers so it hasn't bubbled to the top of things to fix. It probably isn't going to be a trivial fix whenever it is prioritized.

You can avoid the issue by not launching the bundle elevated.

**Comment by jaspar** [comment]
Thanks for the quick response Rob. One last question, so part of the security fix was to use the Windows temp folder for caching instead of the user's temp folder?

**Comment by robmen** [comment]
When the bundle is launched elevated, yes.

**Comment by Entey** [comment]
Hello WiX community.
@robmen could you please confirm whether it's possible to override the default execution path for the bundle.exe and wixstdba.exe processes when a bundle is launched with elevation? Was it added to WiX 5.0.2
