### ISSUE TITLE
Unable to upload the extension on TFS

### ISSUE THREAD

**Issue by Naveen2395** [wixtoolset/issues#5857]
I have downloaded the 'Wix Toolset Visual Studio 2015 Extension' but when i try to upload it on TFS I get the error as:

"Extension package contains invalid character(2, 2). Error: XML Document-Vsix xmlns='http://schemas.microsoft.com/developer/vsx-schema/2010' was not expected."

can anyone please suggest what should I try to resolve the issue.

Thanks

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
