### ISSUE TITLE
Feature Request - Support adding NuGet packages into WiXProj Projects (MSI project or WiXLib)

### ISSUE THREAD

**Issue by stunney** [wixtoolset/issues#5861]
I would like to create wixlibs based on packages that we store in our private package repository, both .NET and native projects included.

Right now when I try and do this I get an error

"Could not install package 'BLARH 1.0.0.0".  You are trying to install this package into a project that targets 'Unsupported, Version=v0.0' but the package does not contain any assembly references or content files that are compatible with that framework, contact the package author"

Adding a package of any sort should not matter to a wixproj.

Thoughts?

**Comment by robmen** [comment]
Maybe follow up with the NuGet team since they'll understand what all that means?

**Comment by barnson** [comment]
We need more detail (including the info requested in the issue template). Can you share a .wixlib Nupkg that demonstrates the problem and the exact repro steps you took?

**Comment by stunney** [comment]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

3.11, 3.14.1703, 4.X (error occurs everywhere)

* Which version of Visual Studio are you building with (if any)?

2017 Enterprise (15.8.0)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

4.5, 4.6, 4.7, C++ (Win32 Native)

* Describe the scenario and benefits that the feature supports.

Being able to source content from a nupkg would be an amazing way to ensure that installers are 1) fast to build, 2) decoupled from application 3) more easily managed.

The teams I have worked on typically have a large number of applications (EXEs or Web Apps) that go into an installer.  Instead of having crazy build/copy scripts set up it would be fantastic to simply go into the package management UI in the installer project and upgrade an application, test the installation, and check it in.  Updating the wxs file's path shouldn't be a problem as an additional manual step, although it could easily be extracted out and automated as a wix variable of some kind $(<packageid>.installpath).

I am trying to add a nuget package of ANY kind to a WiXProj project in Visual Studio.  This way installers are easily upgraded and maintained.

Steps:
1) Create new WiX 3/4 Library or Setup (.wixproj) project (error is the same, regardless of project version/type).
2) Go to "Manage NuGet Packages..."
3) Select nearly ANY NuGet package from NuGet.org
4) The following error appears:  "Could not install package 'BLARH 1.0.0.0". You are trying to install this package into a project that targets 'Unsupported, Version=v0.0' but the package does not contain any assembly references or content files that are compatible with that framework, contact the package author".

* Describe how you're accomplishing the feature today (if possible).

For now, I would (read: not currently doing it) need a manually maintained packages.config file and pre-build steps to get all nuget packages for each application.

* Describe what you'd like the new feature to do.

Allow for a wixlib to have any nupkg added, regardless of target frameworks, dependencies, etc.  Just install them in a local packages folder.  Maybe automatically add wixvars for Source location roots to eliminate the need to update wxs files on every upgrade.

At the end of the day, I want to promote packages to stable/release, not code.  This will go a long way in doing that.

**Comment by robmen** [comment]
This scenario is now supported using `PackageReference` in a .wixproj in WiX v4 with the adoption of an Sdk-style MSBuild project.

**Comment by robmen** [comment]
I should point out that distributing .wixlibs as .nupkgs is not a core scenario of the WiX toolset, so you will still need to do manual work to _create_ a .nupkg with a .wixlib in it (using `build\id.targets` to add a `WixLibrary` item). What _is_ supported is the ability to create `PackageReference` in a .wixproj and have that Restore properly.

**Comment by impoetk** [comment]
I have no problem on doing it manually, but a sample would be very much appreciated
1. how to properly create the nuget with the .wixlib inside when using dotnet pack for a wixproj that is a library
2. with 1 done then i believe then is just as you mention <PackageReference Include="awesomewixlib" Version="1.2.3"/>

**Comment by mosBrkr** [comment]
@impoetk Did you get this working? I would also be interested in such a solution. 

Or is there a better way for sharing e.g. bundle fragments between multiple projects?

**Comment by mosBrkr** [comment]
Ok I think I could finally solve this. It most probably isn't the best/cleanest approach but it works. The basic steps to accomplish building a NuGet package containing the '*.wixlib' which can be consumed by other WiX-projects are:
1. Add the 'NuGet.Build.Tasks.Pack' package to the WiX library project
2. Set the build properties required by the pack task within the 'wixproj' file
3. Create a build target file ('.targets') to make the library known in the build process of the referencing WiX project
4. Specify the library and the '.targets' file to be contained in the NuGet package (in the 'wixproj' file)

Afterwards the package can be created using 'dotnet pack'

<hr>

All together my final files looked somehow like this:

The 'example.wixproj' file:
```
<Project Sdk="WixToolset.Sdk/5.0.0">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <BindFiles>true</BindFiles>
    <DebugType>None</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <PackageVersion>{your package version}</PackageVersion>
    <Authors>{your name}</Authors>
    <Owners>{your name}</Owners>
    <Description>{your description}</Description>
    <Copyright>{your copyright text}</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.10.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="WixToolset.Netfx.wixext" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Include="$(OutDir)\example.wixlib">
      <Pack>true</Pack>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackageFlatten>true</PackageFlatten>
      <PackagePath>tools\payload\output</PackagePath>
    </None>
    <None Include="example.targets">
      <Pack>true</Pack>
      <PackageCopyToOutput>true</PackageCopyToOutput>
      <PackageFlatten>true</PackageFlatten>
      <PackagePath>build</PackagePath>
    </None>
  </ItemGroup>
</Project>
```

The 'example.targets' file:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target
    Name="IncludeExampleWixLibraryTarget"
    BeforeTargets="PrepareForBuild">
    <ItemGroup>
      <WixLibrary Include="$(MSBuildThisFileDirectory)..\tools\payload\output\example.wixlib">
        <Name>example</Name>
      </WixLibrary>
    </ItemGroup>
  </Target>
</Project>
```

As you can see it also works when referencing a WiX extension in the library project.

**Comment by maxxie85** [comment]
For anyone stumbling on this discussion and trying it in WiX5. I had an issue after loading the .nuget into the bundle that Visual Studio was giving me an NullReferenceException upon loading the project after adding the .nuget file containing the .wixlib 

I solved this by simplifying the example.targets file by removing the target property, and just add the library during development.

Resulting in the following `example.targets`
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <WixLibrary Include="$(MSBuildThisFileDirectory)..\lib\$(Platform)\example.wixlib"/>
  </ItemGroup>
</Project>
```

**Comment by mosBrkr** [comment]
> For anyone stumbling on this discussion and trying it in WiX5. I had an issue after loading the .nuget into the bundle that Visual Studio was giving me an NullReferenceException upon loading the project after adding the .nuget file containing the .wixlib
> 
> I solved this by simplifying the example.targets file by removing the target property, and just add the library during development.
> 
> Resulting in the following `example.targets`
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
>   <ItemGroup>
>     <WixLibrary Include="$(MSBuildThisFileDirectory)..\lib\$(Platform)\example.wixlib"/>
>   </ItemGroup>
> </Project>
> ```

Awesome! Thank you! I was wondering what is causing this issue but couldn't nail it down.
