### ISSUE TITLE
FileRemove is very slow

### ISSUE THREAD

**Issue by LGreenberger** [wixtoolset/issues#5862]
* Which version of WiX are you building with?
3.11.1.2318

* Which version of Visual Studio are you building with (if any)?
2015 & 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
 0.9.21.62588

* Which version of .NET are you building with?
NA

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 7

* Describe the problem and the steps to reproduce it.
When I use the following markup to remove all files in 2 directories, it causes the installer to take hours to delete all the files during the InstallFinalize stage. I believe this is also causing InstallValidate to take 30 minutes to execute. The logs are attached.

```
      <Directory Id="dir3C9A44480343B4C6469DA3B8510E21C2" Name="jpegfiles">
        <Component Id="cmpD8CA188428FA0ABE1BCEB4AFB46905EE" Guid="B7C953D6-08A5-4CBB-96B0-05165CECB7A3">
          <CreateFolder />
          <RemoveFile Id="rmvfil_jpgdir" Name="*.*" On="uninstall"/>
        </Component>
      </Directory>
      <Directory Id="dir4B364F0C3A071E6F43A9021BE0900215" Name="textsafe">
        <Component Id="cmp71A0AA8FF2FFC2F3303ECC1878FDD880" Guid="4559AF87-AB25-4844-B5BA-C273C79C2E81" KeyPath="yes">
          <CreateFolder />
          <RemoveFile Id="rmvfil_txtsafe" Name="*.*" On="uninstall"/>
        </Component>
      </Directory>
````
[installog.zip](https://github.com/wixtoolset/issues/files/2275857/installog.zip)

**Comment by barnson** [comment]
WiX is the build tool; it isn't involved at install time for that stock `RemoveFile` behavior. Windows Installer is the runtime engine.

**Comment by LGreenberger** [comment]
Is there a recommendation that I can use to improve the performance? Any settings or options I can enable/disable?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
