### ISSUE TITLE
error LGHT0103 : The system cannot find the file

### ISSUE THREAD

**Issue by GullySmirnoff** [wixtoolset/issues#5871]
Hi,

Could someone help us to investigate the next problem?

We have a intermittent linking issue during our packaging process and we don't know the origin of the problem. LIGHT complains about being unable to read one of the "work file" generated to produce the final .msi. And the issue has not occured with the same installer.

Log example:
`build	31-Aug-2018 02:55:10	3rdparty\wix\tags\3.8\bin\light.exe installer_DEBUGKIT\obj\fragment.wixobj installer_DEBUGKIT\obj\ui.wixobj installer_DEBUGKIT\obj\main.wixobj -v -sice:ICE80 -sice:ICE57 -out DebugKit_2018.17.0.480_x64_vc14.msi -pdbout installer_DEBUGKIT\pdb\DebugKit_2018.17.0.480_x64_vc14.msipdb -ext 3rdparty\wix\tags\3.8\bin\WixUtilExtension.dll -ext 3rdparty\wix\tags\3.8\bin\WixUIExtension.dll    
build	31-Aug-2018 02:55:10	Windows Installer XML Toolset Linker version 3.8.1128.0
build	31-Aug-2018 02:55:10	Copyright (c) Outercurve Foundation. All rights reserved.
build	31-Aug-2018 02:55:10	
build	31-Aug-2018 02:55:11	Updating file information.
build	31-Aug-2018 02:55:25	Creating cabinet files.
build	31-Aug-2018 02:55:25	There will be '8' threads used to produce CAB files.
build	31-Aug-2018 02:55:25	Creating cabinet 'D:\Temp_Global\h4xsgfmo\#media1.cab'.
build	31-Aug-2018 03:02:01	Generating database.
build	31-Aug-2018 03:02:06	C:\src\wix38\src\ext\UtilExtension\wixlib\UtilExtension_Platform.wxi(208) : error LGHT0103 : The system cannot find the file 'D:\Temp_Global\h4xsgfmo\cab_0_WixUtilExtension\2'.
`

Regards,
Gully S.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
