### ISSUE TITLE
Prevent certain files from deleting when unistalled.

### ISSUE THREAD

**Issue by AnishGowda321** [wixtoolset/issues#5873]
Hi,
Anish here.

I am using WixTool 3.0, and seems like i am facing a issue with the wix tool.
Is there any possible way to prevent files in a folder being removed or from over written during re installation? 
In the installed folder, i have file called "example.config" file and whenever i uninstall the application all the files will be removed , but i want the "example.config" file  to remain in install folder from being deleted or overwritten.
How can i achieve this ?

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
