### ISSUE TITLE
registry keys are not removed upon uninstall of COM component

### ISSUE THREAD

**Issue by adnanshaheen** [wixtoolset/issues#5874]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2318.0

* Which version of Visual Studio are you building with (if any)?

> 2017 Pro, Version: 15.6.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Version: 0.9.21.65288

* Which version of .NET are you building with?

> .NET version: 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows version: 10 [Version 10.0.17134.48]

* Describe the problem and the steps to reproduce it.

> Installing a product that has a COM component, installed via `TypeLib`, `AppId`, `Class` and `ProgId` creates registry keys. Some of them are not removed upon uninstall.

* Describe the behavior you expected and how it differed from the actual behavior.

> The following keys should have been deleted as well.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\COM3\SelfReg\AppID
{AppID-GUID}
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\COM3\SelfReg\AppID\Component.DLL
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\COM3\SelfReg\CLSID
{ClassID-GUID}
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\COM3\SelfReg\CLSID
{ClassID-GUID}
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\COM3\SelfReg\Component.ComComp

**Comment by barnson** [comment]
> Please do not open issues requesting support or debugging help; first start a thread on the wix-users mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.
