### ISSUE TITLE
wix4 code review comments

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#5876]
Pretty much all of the micro repo work has been done without pull requests, which makes it hard to track comments. This is to track these comments.

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/VisualStudio.wixext/commit/cba9d16b54cd4ba5b8750ee97ed5aa36cf1fc382#r30473730

**Comment by barnson** [comment]
> [wixtoolset/VisualStudio.wixext@cba9d16#r30473730](https://github.com/wixtoolset/VisualStudio.wixext/commit/cba9d16b54cd4ba5b8750ee97ed5aa36cf1fc382#r30473730)

Reply goes here.

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/VisualStudio.wixext/commit/cba9d16b54cd4ba5b8750ee97ed5aa36cf1fc382#r30473709
