### ISSUE TITLE
"The Class element's ForeignServer or Server attribute was not found; one of these is required" error occurs on installing an application with DevExpress controls to WiX

### ISSUE THREAD

**Issue by ChandraMohanFluke** [wixtoolset/issues#5888]
Hi Team,
Hi Team, i updated my project with  versionDevexpress 18.1 dlls , but after i updated with this new dlls , my wix installer is throwing error while trying to generate build .
Below Error Details :

Severity Code Description Project File Line Suppression State Error The Class element's ForeignServer or Server attribute was not found; one of these is required.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
