### ISSUE TITLE
NullReferenceException when trying to unset a version variable

### ISSUE THREAD

**Issue by pixafera** [wixtoolset/issues#5889]
* Which version of WiX are you building with?

3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

VS2015

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

4.0

* Describe the problem and the steps to reproduce it.

When trying to set a Version Variable to null in order to unset it (`Bootstrapper.Engine.VersionVariables[key] = null;`), a NullReferenceException is raised.
Relevant stack trace:
   at Microsoft.Tools.WindowsInstallerXml.Bootstrapper.Engine.VersionToLong(Version version)
   at Microsoft.Tools.WindowsInstallerXml.Bootstrapper.Engine.<.ctor>b__7_10(String name, Version value)
   at Microsoft.Tools.WindowsInstallerXml.Bootstrapper.Engine.Variables`1.set_Item(String name, T value)

A workaround in the meantime is to set the corresponding key in StringVariables to null instead (`Bootstrapper.Engine.StringVariables[key] = null;`)

* Describe the behavior you expected and how it differed from the actual behavior.

The variable gets unset.

**Comment by rseanhall** [comment]
This was fixed with #6210.
