### ISSUE TITLE
Guidance for building arm MSIs for Windows

### ISSUE THREAD

**Issue by rakeshsinghranchi** [wixtoolset/issues#5892]
Does wixtoolset support building MSIs for ARM architecture ? If yes, what does it take to build an MSI and burn bundle ? .NET Core produces binaries for Windows ARM32 and ARM64 . What does it take to build msi and burn bundle for these two architectures ? Note, wix3.11.1 is being used to produce x86 and x64 MSis .

https://github.com/dotnet/core-setup

cc @robmen , @barnson

**Comment by robmen** [comment]
No. ARM is not supported at this time. Someone could take on the work in WiX v4. There will be several places to update to add a new architecture.

**Comment by jformacek** [comment]
+1 here. We would like to have this capability for ARM64 for project that we do with Microsoft. I know that some work has been done, but seems to be far from being easily usable.

Thank you!
Jiri

**Comment by chrpai** [comment]
Microsoft just announced a ARM based Surface Pro.   We might want to prioritize this.

**Comment by barnson** [comment]
ARM64 is now supported in v3.14.

**Comment by rseanhall** [comment]
The issue for MSI support is https://github.com/wixtoolset/issues/issues/5558 (done in v3.14 and 4.0). ARM32 Burn is tracked at https://github.com/wixtoolset/issues/issues/6179. ARM64 Burn is tracked at https://github.com/wixtoolset/issues/issues/6180.
