### ISSUE TITLE
Bootstrapper upgrading

### ISSUE THREAD

**Issue by E-Tourneur** [wixtoolset/issues#5893]
Hi,

We are using wix in order to build our installers. 
We have multiple msi combine in one single installer via bootstrapper. 

Each installer is creating and starting a service; and sometimes, after a successful upgrade, an uninstall process is starting (I suppose to remove older version?) and this is problematic for us as an uninstall is stopping and removing associated services.

How bootstrapper uninstall/upgrade works exactly? Can we schedule the msi uninstall like the way wix is doing via “MajorUpgrade” ? 
would anyone have more information about this subject?

Thank you in advance.

Best regards,
E. Tourneur

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
