### ISSUE TITLE
Failed to call FindFirstFileW 

### ISSUE THREAD

**Issue by kisskumam** [wixtoolset/issues#5900]
Hi, 

I have this issue while trying to install my msi package created by wixtoolset on a windows 7 with 32bits processor (it was successfully installed on a 64bits one). I've been searched for days but there seems no clue for me. Please advise!
Here is the error message on the installation log:

> SchedNetFx:  Error 0x80070003: failed to call FindFirstFileW with string C:\Windows\Microsoft.NET\Framework64\*
SchedNetFx:  Error 0x80070003: failed to search for ngen under path C:\Windows\Microsoft.NET\Framework64\
SchedNetFx:  Failed to find 64bit ngen. No actions will be scheduled to create native images for 64bit.
Action ended 4:34:34: NetFxScheduleNativeImage. Return value 1.

This is the full log file. 
[https://drive.google.com/open?id=1Hgi3we9zl_x5jE5FyL_vxx1RievYRUvc](url)

Thanks so much!

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
