### ISSUE TITLE
Accessibility: Narrator reading graphic controls not useful to the user

### ISSUE THREAD

**Issue by SteveL-MSFT** [wixtoolset/issues#5906]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.9.1208.0

* Describe the problem and the steps to reproduce it.

> Start MSI installer built from WiX with standard Welcome Dialog.  Start Narrator.  Start Scan Mode.  Use cursor keys to move from control to control.  

* Describe the behavior you expected and how it differed from the actual behavior.

> Notice the decorative horizontal bar at the bottom separating content and buttons is read.  This control needs to be decorated so accessibility treats it as hidden so it is not read.

**Comment by SteveL-MSFT** [comment]
Another example is on the `Destination Folder` pane, NVDA reads the `WixUI_Bmp_Banner` pic rather than skipping it.

**Comment by barnson** [comment]
There's no documentation to indicate Windows Installer's UI engine supports this.
