### ISSUE TITLE
Installer transparent hyperlink control shows white background on dark dialog background

### ISSUE THREAD

**Issue by kmackey1** [wixtoolset/issues#5907]
## Bugs

* Which version of WiX are you building with?

3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

2013 Pro 12.0.40629.00 Update 5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.21.62588

* Which version of .NET are you building with?

4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 Pro 1803

* Describe the problem and the steps to reproduce it.

When using a transparent hyperlink control on a dark background the control has a white background.

![image](https://user-images.githubusercontent.com/26938552/48501326-dd419f00-e7f1-11e8-81f0-f60e61e1dfb8.png)

This is likely a Windows Installer bug, but I would like to know if there is a workaround other than using bitmap buttons (which can have display problems), or putting hyperlinks at the bottom of the dialog with the buttons.

Here's a dialog and related settings that show the problem:

```
<TextStyle Id="ExtText" FaceName="Tahoma" Size="8" Red="255" Green="255" Blue="255" />

<Dialog Id="InstallWelcome" Width="370" Height="270" Title="[ProductName]" NoMinimize="yes">
    <Control Type="Text" Id="TextLine2" X="25" Y="88" Width="169" Height="34" Transparent="yes"
             Text="{&amp;ExtText}This dialog shows a bug with transparent hyperlink controls on non-white backgrounds. A white background is shown instead." />
    <Control Id="TestLink" Type="Hyperlink" X="135" Y="140" Width="50" Height="12" Transparent="yes">
      <Text><![CDATA[<a href="http://www.wixtoolset.org">WiX Toolset</a>]]></Text>
    </Control>
    <Control Type="PushButton" Id="Cancel" X="300" Y="243" Width="56" Height="17" Text="&amp;Exit">
      <Publish Event="EndDialog" Value="Exit" />
    </Control>
    <Control Type="Bitmap" Id="Image" Width="370" Height="234" X="0" Y="0" Text="darkbackground" />
</Dialog>

```
* Describe the behavior you expected and how it differed from the actual behavior.

Expect the dark background behind the hyperlink as text controls do.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
