### ISSUE TITLE
Errors Pre-Build command line in Visual Studio 2015

### ISSUE THREAD

**Issue by MateuszSoftcream** [wixtoolset/issues#5910]
I would like to create .wxs file with file tree using heat.exe WIX. Any ideas whats wrong with it and why im getting 9009 error code all the time ?
This a Pre-build comand thar im using:
“$(WIX)bin\heat.exe” dir “$(N_Published)” -cg N_Published -gg -scom -sreg -sfrag -srd
-out “$(ProjectDir)\FilesFragment.wxs”

N_Published directory is fine.

**Comment by barnson** [comment]
For support, please contact the [wix-users mailing list][ml].

[ml]: http://wixtoolset.org/documentation/mailinglist/
