### ISSUE TITLE
Setting to enforce different REINSTALLMODE flag than "o" for bootstrappers

### ISSUE THREAD

**Issue by Danielku15** [wixtoolset/issues#5911]
## Feature requests

If this issue is a feature request:

As a installer author I want to enforce the installer to install files to the system regardless on their previously installed versions. By version I am referring to "file versions" as they are contained in DLLs and Executables. Currently the REINSTALLMODE is fixed to the flag "o - Reinstall if the file is missing or is an older version." among other flags and configuring the REINSTALLMODE is [actively prevented](5294) ([v3](https://github.com/wixtoolset/wix3/blob/bda1c281cb0349007d767d5404d6da87076d7d94/src/burn/engine/msiengine.cpp#L1188) and [v4](https://github.com/wixtoolset/wix4/blob/e98c0c414e5853d961a73caea42ce695ac853812/src/burn/engine/msiengine.cpp#L1199) have this behavior).

[MSI provides](https://docs.microsoft.com/en-us/windows/desktop/msi/reinstallmode) various different flags to control how files are placed depending on their version but there is no way in WiX to tell Burn to use different flags. 

It should be possible for installer authors to define how file versions are treated on the individual MSI actions in order to overcome issues when file versions shipped to the customer might differ from the "o" expectations. 

* Describe the scenario and benefits that the feature supports.

There is an issue on upgrade installations that causes old files to be removed but new files not to be placed on the system. This issue can happen if newer versions of your product try to ship the same version of a dll like the old product version. An example: 
Product v1.0 ships Library.dll with version 2.0.0.0
Product v1.1 ships Library.dll with version 2.0.0.0

On an upgrade from Product v1.0 to v.1.1 first the uninstall sequence removes Library.dll from the system but the installation sequence then does not put it again to the system as MSI somehow detected that the DLL is already on the system. Similar issues seem to happen if library authors decide to move to a new versioning schema and you suddenly have downgrades. 

We also suffer directly from the scenario above. We have some internally developed libraries that do not change their version number during our development process. For some selected libraries (especially some .net libs that stay on 1.0.0.0 internally for some time) they appear to be missing quite often and the application crashes with missing dll errors.  

Here are some references and discussions on this topic. 
http://windows-installer-xml-wix-toolset.687559.n2.nabble.com/Major-Upgrade-doesn-t-replace-some-DLL-td691384.html
https://stackoverflow.com/questions/47157021/downgraded-ms-dll-disappears-on-upgrade-windows-installer
https://blogs.msdn.microsoft.com/astebner/2015/11/16/why-windows-installer-removes-files-during-a-major-upgrade-if-they-go-backwards-in-version-numbers/
https://stackoverflow.com/questions/4227456/windows-installer-deletes-versioned-file-during-product-upgrade-instead-of-down?rq=1
https://stackoverflow.com/questions/1917877/install-a-file-regardless-of-version-number-with-wix

* Describe how you're accomplishing the feature today (if possible).

We do not have a workaround for this missing feature in place but https://stackoverflow.com/a/1919979/996233 sounds like a reasonable alternative. By supressing the file information to be generated, we could enforce the file versions to match the product versions achieving always a newer version of the DLL even though the file version is the same.

* Describe what you'd like the new feature to do.

A new set of properties/attributes on the bundle tag could allow configuring the REINSTALLMODE property. I would not allow users to again fully manually set the REINSTALLMODE on the MsiPackage as it is dependent on the actions we are triggering on the MSIs (repair, modify etc.). Instead I would rather go for a bundle-level configuration with user friendly properties that define how file versions should be interpreted. Then in burn the user defined settings can be respected when building the REINSTALLMODE property in burn.

**Comment by jshuquanser** [comment]
Just want to add another situation where this feature is really needed.
We bundle a third-party kernel driver (thus we cannot change the driver files) as part of our software package. Due to some performance issue in the newer driver (which we only found out after we've released our new software package), we have to roll back to a previous version of the driver. Since Windows drivers catalog files are digitally signed, and thus not allow any of the files to be altered, we cannot go the route of removing file version information. Therefore the only way for us to have the older version driver files to be installed is via the REINSTALLMODE options. But as pointed out now, it is officially not supported (but in Wix3 it is just a warning, and still seems to work).

**Comment by knoepdan** [comment]
I aggree this is an important feature. Most applications reference some third party dlls and it happens - not often but it happens - that you need to downgrade. Sometimes it's not even really under our control. For example when it is a dependancy of a third party library that is included via NuGet. 

So this is definitly an important feature. Is there any possibility that it might still be included in WIX 3?  (since WIX4 seems to take forever)

**Comment by rseanhall** [comment]
Why is this feature necessary in v3? v3 is pretty much done, and hardcoding the `REINSTALLMODE` property in the `MsiPackage` is a functional workaround there.

**Comment by knoepdan** [comment]
By hardcoding "REINSTALLMODE property in the MsiPackage", do you mean setting the property like this: 
"<Property Id="REINSTALLMODE" Value="amus"/>" ?   (Unfortunately, I cannot call myself a MSI or WIX expert yet). 

When we do that we get compiler warnings "warning LGHT1076: ICE40: REINSTALLMODE is defined in the Property table. This may cause difficulties.".  With a warning message like this, we don't think we can set the REINSTALLMODE this way, as it doesn't give any specifics. 

Remark: our installation(s) dont depend on other installations. All the necessecary dll's are shipped in one package, so from that point of view "amus" should be save. However, the warning is too unspecific. :-(

**Comment by rseanhall** [comment]
In the bundle (this will also produce a warning):

```
<MsiPackage>
  <MsiProperty Name="REINSTALLMODE" Value="" />
</MsiPackage>
```

**Comment by knoepdan** [comment]
Thanks.. you are really quick.. Then my questions would rather be what the warning is all about then?

**Comment by knoepdan** [comment]
just FYI: setting REINSTALLMODE=amus cause our self contained installers to fail in certain circonstances. They worked when triggered normally but failed when executed via power shell (triggered by C# code). So to me, REINSTALLMODE=amus is a mysteri e :-(

**Comment by knoepdan** [comment]
yes :-)  it only makes me wonder why amus even exists... ok maybe because it works in certain mysterious circonstances.

**Comment by barnson** [comment]
It's useful for patching.

**Comment by raQai** [comment]
> In the bundle (this will also produce a warning):
> 
> ```
> <MsiPackage>
>   <MsiProperty Name="REINSTALLMODE" Value="" />
> </MsiPackage>
> ```

@rseanhall Could you elaborate on this further? From everything I found it looks like this should not work.

According to the [MsiProperty documentation](https://wixtoolset.org/documentation/manual/v3/xsd/wix/msiproperty.html)
> Burn controls the follow MSI properties so they cannot be set with MsiProperty: ACTION, ALLUSERS, REBOOT, REINSTALL, REINSTALLMODE

And also this results in this log message while building the installer:
```
warning CNDL1149 : The 'REINSTALLMODE' MsiProperty is controlled by the bootstrapper and cannot be authored. (Illegal properties are: 'ACTION', 'ADDLOCAL', 'ADDSOURCE', 'ADDDEFAULT', 'ADVERTISE', 'ALLUSERS', 'REBOOT', 'REINSTALL', 'REINSTALLMODE', or 'REMOVE'.) Remove the MsiProperty element. This restriction will be enforced as an error in WiX v4.0.
```

Also see [#5294](https://github.com/wixtoolset/issues/issues/5294).
