### ISSUE TITLE
Installer exes 

### ISSUE THREAD

**Issue by michaelcfanning** [wixtoolset/issues#5914]
I'm a coordinator on the Microsoft open source binary-level Binskim security checker (https://github.com/microsoft/binskim). This tool is producing some results against wix-generated EXE installers, specifically noting that the linked EXE doesn't enable the /CFG feature. All the Binskim rules that require scanning PDBs (to look for things like compiler warning levels for linked object modules) also produce errors.

Currently, tool users need to request exceptions for security warnings of this kind. Ideally, the WIX-generated installers would analyze cleanly (either as a result of WIX code emit or because the tool understands relevant results are false positives and suppresses them). 

1) Is there a way to force the WXI toolset to produce a PDB associated with the installer .exe itself?
2) As far as a marker or reliable heuristic for identifying WIX-generated installer exes, my current thinking is to look for a section header named '.wixburn' in the PE. Any better suggestion?
3) Am I correct that the loader code associated with an bootstrap exe is itself static (and therefore fixed in terms of security risk)? Or is it possible to link arbitrary static libraries, for example, with the start-up code?

Thanks for any insights you can offer. 

Michael

Update:
I've put out a PR that suppresses all current tool results against WIX bootstrapper exes. If suppressing the analysis introduces security risk in your opinion, I'd appreciate your feedback.

https://github.com/Microsoft/binskim/pull/215

**Comment by robmen** [comment]
1. The .pdbs for burn.exe are available in the wix###-debug.zip for each build. They are not specialized per-bundle build.

2. That seems like a very reasonable marker.

3. Yes, the .exe is static. The build process appends the chained data (installation packages) to the .exe, but the code is unmodified.

If you wanted to send the pull request to add the `/CFG` feature after verifying that it doesn't break Burn, that'd be fine. We'd include it in WiX v3.14 and WiX v4.0.

**Comment by michaelcfanning** [comment]
good correction. :) thanks very much. i will work on this validation and plan to contribute the /CFG change.

**Comment by michaelcfanning** [comment]
@robmen, I'd like to contribute a change to enable /CFG. 1) should i open an issue on this work to solicit any comment/etc. on it, 2) are there any onboarding docs which assist in getting a clean enlist/build/test to help with verifying changes (which might have suggestions for VS toolset required to build, download location of any additional SDK installers, etc?).

**Comment by robmen** [comment]
We can use this issue to track the work. I think a WIP is overkill for this change. To get started see: http://wixtoolset.org/development/

**Comment by michaelcfanning** [comment]
ack. I see that http://wixtoolset.org/development/building-wix/ has some relevant information. thanks for the ongoing assistance.

**Comment by chrpai** [comment]
@michaelcfanning  I just spent the day configuring a build box with Azure DevOps build agent, VS2010, VS2012, VS2013, VS2015, VS2017, generating  my own SNK files and creating a pipeline for building the core wix v3 repos /  dev branch.   I've made the pipeline public pointed at a fork on mine on GitHub.

https://dev.azure.com/iswix/wix-build/_build?definitionId=78

I'd be happy to provide you any needed DevOps assistance in building/testing  your  change prior to you submitting your pull request.

**Comment by rseanhall** [comment]
Seems to be duplicate of #5743.

**Comment by michaelcfanning** [comment]
It would be nice to fix this, sorry I didn't jump on it earlier. @chrpai, does your offer of assistance still stand?

**Comment by chrpai** [comment]
@michaelcfanning I'm sorry I've had pipeline rot, build server rot, brain rot and I'm terribly swamped with work currently.

**Comment by barnson** [comment]
We're keeping the first issue open and just closing this as a dupe.

**Comment by michaelcfanning** [comment]
ack. will follow up there. @chrpai, my apologies for not taking advantage of the resources you previously put into this.
