### ISSUE TITLE
VS 2019 Support

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#5915]
VS2019 Preview 1 was released on yesterday on 12/4. We need a WiX VS / Votive prototype extension for it to see where we stand.

I will try to generate one but I haven't even looked at the repos yet.

**Comment by chrpai** [comment]
I can work on this.

**Comment by chrpai** [comment]
https://github.com/wixtoolset/VisualStudioExtension/pull/7

**Comment by vbaderks** [comment]
Would it be possible to also apply this enhancement to v3.14?

**Comment by chrpai** [comment]
@vbaderks  Votive is it's own repos that releases independent of WiX proper.  This fix will work for both v3.11 and v3.14 when released.

**Comment by chrpai** [comment]
Votive is still looking good on 2019 4.1 / SVC1.

**Comment by chrpai** [comment]
I was doing some testing today  on the latest Preview 4.3 and I noticed one small issue that I will capture in another issue.  It effects the VS2017 addin also.

**Comment by bergmeister** [comment]
yes please, we are already on RC4 and VS is going to release next week(!)

**Comment by chrpai** [comment]
@bergmeister It was a really minor thing and not a blocker for next week.  WiX is read for VS2019 as-is IsWiX.

**Comment by jyotirmayadkl** [comment]
Can any one help me i have wix 3.11 and i an unable to find vs2019 path. due to it is not stored in registry like vs 2017. so what to do ?

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/VisualStudioExtension/pull/7
https://github.com/wixtoolset/VisualStudioExtension/pull/10
