### ISSUE TITLE
Wix Windows Installer XML missing

### ISSUE THREAD

**Issue by rmubaldo-seismos** [wixtoolset/issues#5917]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> v3.11.1 

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 Professional 15.9.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Votive2017.vsix version 0.9.21.62588

* Which version of .NET are you building with?

> 4.7.03190

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Home 17763.168 64-bit

* Describe the problem and the steps to reproduce it.

> I downloaded and installed the Wix Toolset build tools v3.11.1 and the Wix Toolset Visual Studio 2017 Extension (Votive2017.vsix version 0.9.21.62588???) both from the website and from Visual Studio Marketplace.

When I follow “Create a simple setup”, Wix Windows Installer XML missing.
I tried numerous re-installs with no success. I downloaded v4.0 with no success.

I am using Visual Studio 2017 Professional 15.9.3, .NET version 4.7.03190
Windows 10 Home 17763.168 64-bit

One possible item was wix.targets found in “C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\WiX Toolset\v4”
was looking for the non-existing registry entry “HKEY_LOCAL_MACHINE\SOFTWARE\WiX Toolset\v4”. When I added it to point to wix.targets (C:\Program Files (x86)\WiX Toolset v4.0) that still did not resolve the issue

* Describe the behavior you expected and how it differed from the actual behavior.

> Did not work like sample because the Windows Installer XML was not found

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by robmen** [comment]
WiX v4 is under-development and has bugs. Use a stable v3.x release instead.

For future support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by rmubaldo-seismos** [comment]
The issue occurs in v3.11.1 downloaded and installed from the website. I only mentioned that I tried version 4 and you closed the case.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
