### ISSUE TITLE
WiX extension DLLs for x64?

### ISSUE THREAD

**Issue by jformacek** [wixtoolset/issues#5918]
Hello,
The question has been around for couple of years now and I wanted to ask on current status of WiX extension DLLs for other platforms, especially x64 (but also for ARM64)
We're getting requests for our software to be installable on pure 64-bit Windows that do not have WoW64. While all our custom actions are 64-bit, extensions we use are still x86 only. This leads us to implement more functionality as custom actions, duplicating the functionality.

I believe that this support would be handy wherever security is extremely important and administrators minimize attach surface by uninstalling of unnecessary components, especially nowadays when crypto security is a hot topic.

Thank you!
Jiri

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/4826

Rather than duplicate functionality, you could implement the feature in WiX and save everyone the trouble.
