### ISSUE TITLE
Feature request: Adding custom UI for the overall Install dialogs

### ISSUE THREAD

**Issue by AnishGowda321** [wixtoolset/issues#5924]
## Feature requests

* WIX is already providing us the option to customize the dialog image and banner image in WIX installer.
> It would be nice if WIX provide us a option where we can customize the UI for each dialog.
>Basically our requirement is to keep changing the background image based on the timer set, when the installation process start.
> so when the installation process begins. Below the progress bar we want the image to be changing based on the timer set.

**Comment by barnson** [comment]
Already possible with a Billboard control.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).
