### ISSUE TITLE
Hidden feature cannot be conditionally installed

### ISSUE THREAD

**Issue by TannerStevenson** [wixtoolset/issues#5925]
* Which version of WiX are you building with?

> 3.11.0.1701

* Which version of Visual Studio are you building with (if any)?

> 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> I have a sub-feature that should not be configurable by a user and should conditionally install if a property is set. Because the property should not be configurable, I set Display='Hidden'. However when I did this, the feature condition no longer got evaluated to automatically install the feature.

Relevant Code:
```
<Property Id="VERSION">
      <RegistrySearch Id='VersionRegistrySearch' Type='raw' Root='HKLM' Key='Path/To/Version/Key' Name='Release'/>
</Property>

<Property Id='ISVERSIONVALID' Value='false'/>

<CustomAction Id="SetValidVersion" Property="ISVERSIONVALID" Value="true" />

<InstallExecuteSequence>
      <Custom Action='SetValidVersion' Before="CostInitialize"><![CDATA[VERSION >= "B.08.00" OR (NOT (VERSION << "B") AND VERSION >= "10.0")]]></Custom>
</InstallExecuteSequence>

<Feature Id='Parent' Level='1' AllowAdvertise='no'>
      ...
      <Feature Id='Child' Level='0' Display='hidden'>
            ...
            <Condition Level='1'><![CDATA[ISVERSIONVALID = "true"]]></Condition>
      </Feature>
</Feature>
```

Note: I only set a separate property so that I wouldn't have multiple instances of that complex conditional statement.

When I removed the Display='hidden', the child feature installed as expected.

* Describe the behavior you expected and how it differed from the actual behavior.

> If I set a feature to be hidden, I expect that it would simply hide the feature in the UI, not completely disable the feature.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by TannerStevenson** [comment]
There was no error in my code. I feel it is a bug with WIX, which is why I created a bug.

**Comment by robmen** [comment]
> It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

More often than not it turns out to either be your error or Windows Installer behavior.

**Comment by TannerStevenson** [comment]
Keeping everything else the same, it works correctly when I don't set the property, and it does not work when I set the property. In the documentation it states:

**hidden**
Prevents the feature from displaying in the user interface. 

This does not mention that conditions will not work if you hide the feature in the UI. So to me, setting a feature to hidden in the UI has unintentional consequences.

**Comment by barnson** [comment]
That would be "Windows Installer behavior" that Rob mentioned.

**Comment by BMurri** [comment]
Agreed, that does appear to be unintended. Please discuss this on wix-users. Windows Installer often does unexpected things, until all the details are obtained. That doesn't mean that there's a specific bug in WiX, nor does it mean there isn't.

I concur with this issue being closed at this point.
