### ISSUE TITLE
Unable to find wix toolset 3.6 installer for windows

### ISSUE THREAD

**Issue by mounikapk** [wixtoolset/issues#5926]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Discussions and support
This is a support request. I am unable to find Wix Toolset 3.6 anywhere on the internet. I found the archives on http://wixtoolset.org but it doesn't have an .exe or an installer for Wix 3.6. I need this specific version for building an .msi for a legacy component.

* Which version of WiX are you building with?

> Wix Toolset 3.6

* Which version of Visual Studio are you building with (if any)?

> VS Ultimate 2013

* Which version of .NET are you building with?

> .Net 4.5

**Comment by barnson** [comment]
You can get the installer from the Codeplex archive. We haven't put them back up because older versions have security vulnerabilities.

**Comment by chrpai** [comment]
FYI the archive is 1.2GB.  Inside you'll find a releaseList.json that states that the file releases/7/ea1f0431-7aa8-437e-9236-25e8faec4dbb is the wix36.exe file.  Just extract and rename and you'll see what you need.

**Comment by mounikapk** [comment]
Thanks for your answers. But I have a follow-up question here. 
I have renamed and installed using WiX36.exe but i found some missing files like votive2010.dll, sconce2010.dll etc in the installed bin folder. Any clue?
