### ISSUE TITLE
Accelerator Keys not working as expected in WiX Bundle using wixstdba

### ISSUE THREAD

**Issue by 0ptikGhost** [wixtoolset/issues#5927]
* Which version of WiX are you building with?

> WiX Toolset v3.9.1208.0

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Premium 2012 Version 11.0.6129.00 Update 5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Windows Installer XML Toolset version 3.9.1208.0

* Which version of .NET are you building with?

> Microsoft .NET Framework, version 4.0.30319.42000

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows Server 2008 R2 Standard

* Describe the problem and the steps to reproduce it.

> Minimal repro project for this issue at https://github.com/0ptikGhost/HotKeysRepro
> 
> Steps to Reproduce:
> 1. Launch HotKeysRepro.zip\HotKeysRepro\bin\Release\HotKeysRepro.exe
> 2. Press Alt+a to agree to the license terms and conditions
> 3. Switch to any other window
> 4. Switch back to HotKeysRepro Setup window
> 5. Press Alt+a to deselect license checkbox

* Describe the behavior you expected and how it differed from the actual behavior.

> Step 5 above in Steps to Reproduce should deselect the license checkbox. Instead the license checkbox remains selected. This behavior is also seen with all other accelerators (hotkeys) on the window.
> 
> A workaround is to press tab between Step 4 and Step 5 above.
> 
> I built the HotKeysRepro project with WiX 3.11 and found the behavior to be different. Alt+a moves the focus to the "I agree to the license terms and conditions" text but the checkboxk is not selected or deselected. You have to press space to select/deselect the checkbox. You sill have to press tab after switching to any other window to get any of the other hotkeys to work.
> 
> The reported expected behavior is to be able to press Alt+a (or any other accelerator) directly without needing to press tab or space or any other character combo.

**Comment by rseanhall** [comment]
[`TranslateAccelerator`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-translateacceleratora) explains what's going on - accelerator keys don't work if parent window is the active window and no child window has the keyboard focus.

The solution is at [Dialog boxes return focus to the control that had focus when you last switched away; how do I get in on that action for my own windows?](https://devblogs.microsoft.com/oldnewthing/20140521-00/?p=943) Also need to make sure a control gets focus when switching pages.
