### ISSUE TITLE
light.exe fails even if the path does not contain unicode characters

### ISSUE THREAD

**Issue by MarekKosinski** [wixtoolset/issues#5928]
Hi.

Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Bugs

* Which version of WiX are you building with?
I'm using WiX 3.11 released this on Dec 31, 2017.

* Which version of Visual Studio are you building with (if any)?
I'm using Visual Studio 2017 Community version 15.9.4.

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
I'm using Wix Toolset Visual Studio 2017 Extension version 0.9.21.62588

* Which version of .NET are you building with?
I'm using .NET Framework 4.5.2

* Describe the problem and the steps to reproduce it.

I'm having a hard time creating my installer project. First off I had a problem that most things did not work if my project was located in C:/Users/Marek Kosiński/... because I had the Unicode in the path. The issue (https://github.com/wixtoolset/issues/issues/4923) helped me to realize that. 
I've moved my project to C:\ and the project started to build properly. More problems started to appear when I've added files to install. 

For example, when I add these lines:

      <Component Id="xxx.exe" Guid="f5140ff3-4f35-4e92-b193-24ab2c58fb3a">
        <File Id="xxx.exe" Name="G1ANT.Brain.UserRecorder.exe" Source="$(var.xxx_TargetDir)xxx.exe" />
      </Component>

I'm getting the very same exception as when my project was at C:\Users\...
The exception is 
The filename, directory name, or volume label syntax is incorrect. (Exception from HRESULT: 0x8007007B)

The visual studio is invoking:
4>		C:\Program Files (x86)\WiX Toolset v3.11\bin\Light.exe -out C:\G1ANT.Brain\G1ANT.Brain.WixInstaller\bin\Debug\en-US\G1ANT.Brain.WixInstaller.msi -pdbout C:\G1ANT.Brain\G1ANT.Brain.WixInstaller\bin\Debug\en-US\G1ANT.Brain.WixInstaller.wixpdb -cultures:en-US -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" -loc Common.wxl -contentsfile obj\Debug\G1ANT.Brain.WixInstaller.wixproj.BindContentsFileListen-US.txt -outputsfile obj\Debug\G1ANT.Brain.WixInstaller.wixproj.BindOutputsFileListen-US.txt -builtoutputsfile obj\Debug\G1ANT.Brain.WixInstaller.wixproj.BindBuiltOutputsFileListen-US.txt -wixprojectfile C:\G1ANT.Brain\G1ANT.Brain.WixInstaller\G1ANT.Brain.WixInstaller.wixproj obj\Debug\Components.wixobj obj\Debug\Directories.wixobj obj\Debug\Product.wixobj

and the next line is:
4>light.exe(0,0): error LGHT0001: The filename, directory name, or volume label syntax is incorrect. (Exception from HRESULT: 0x8007007B)

I'm using Windows 10, I don't know if that matters.

I'll be grateful for any tips on how to solve this issue or work around it.

**Comment by barnson** [comment]
What does `$(var.xxx_TargetDir)xxx.exe` evaluate to? If you can run Light.exe under the debugger, the exception should pop right up.

**Comment by MarekKosinski** [comment]
xxx is G1ANT.Brain.UserRecorder

**Comment by barnson** [comment]
What's the full path?

**Comment by MarekKosinski** [comment]
C:\G1ANT.Brain\G1ANT.Brain.UserRecorder\bin\Debug\G1ANT.Brain.UserRecorder.exe

**Comment by barnson** [comment]
It's probably not that path, then. You should try reproducing the problem while debugging Light.exe or using Process Monitor to track its i/o.

**Comment by barnson** [comment]
Any news? We're going to need you to reproduce the problem as it isn't happening elsewhere.

**Comment by pjaspinski** [comment]
I stumbled upon the same issue and fixed it by changing `TMP` and `TEMP` environment variables to a path that also does not contain unicode characters. By default, these variables are set to `C:/Users/*your username*/AppData/Local/Temp`, so if your username contains unsupported characters, it will cause light.exe process to fail.
