### ISSUE TITLE
HEAT5305 (heat.exe wix 3.11.1) cannot open .net standard projects

### ISSUE THREAD

**Issue by adaviding** [wixtoolset/issues#5929]
My WiX setup project does not interact correctly with .NET Standard 2.0 projects.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> Framework 4.7.2

* Describe the problem and the steps to reproduce it.

> Create a normal .NET Standard project in VS 2017.  In the same solution, create a Setup Project for WiX v3 (`*.wixproj`).  Add a reference to the .NET Standard project into the WiX setup project, so your `*.wixproj` should contain something like this.

```
<ProjectReference Include="$(SolutionDir)MyCompanyName\Common\MyCompanyName.Common\MyCompanyName.Common.csproj">
  <Name>MyCompanyName.Common</Name>
  <Project>{b248f13b-62d4-49b7-a7ea-181c7d7f5aaf}</Project>
  <Private>True</Private>
  <DoNotHarvest></DoNotHarvest>
  <RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
  <RefTargetDir>INSTALLLOCATION</RefTargetDir>
</ProjectReference>
```

Note that I tried adding some extra stuff into the ProjectReference element shown above (based on another example I found online) but it didn't help.
```
  <IsDotnetSDKProject>True</IsDotnetSDKProject>
  <TargetFrameworkIdentifier>netstandard2.0</TargetFrameworkIdentifier>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> I get a build error when I build the project.

```
6>		C:\dev\github\my_company_name\my_company_name-core\packages\WiX.3.10.3\build\..\tools\Heat.exe project C:\dev\github\my_company_name\my_company_name-core\MyCompanyName\Common\MyCompanyName.Common\MyCompanyName.Common.csproj -configuration Debug -directoryid INSTALLLOCATION -platform AnyCPU -pog Binaries -pog Symbols -pog Sources -pog Content -pog Satellites -pog Documents -projectname MyCompanyName.Common -ag -sfrag -out obj\Debug\_MyCompanyName.Common.wxs
6>heat.exe(0,0): error HEAT5305: Failed to load project C:\dev\github\my_company_name\my_company_name-core\MyCompanyName\Common\MyCompanyName.Common\MyCompanyName.Common.csproj: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\dev\github\my_company_name\my_company_name-core\MyCompanyName\Common\MyCompanyName.Common\MyCompanyName.Common.csproj
6>Done building project "DataServerInstaller64.wixproj" -- FAILED.
6>
6>Build FAILED.
```

**Comment by rseanhall** [comment]
This is because of https://github.com/wixtoolset/issues/issues/5490. See https://github.com/wixtoolset/issues/issues/4853 for details.

FYI, your output says you're using v3.10.3 not v3.11.1 like you specified in the bug.

**Comment by adaviding** [comment]
@rseanhall Yeah I tried it with `3.10.3` first, then I confirmed that it still happens on `3.11.1`.  After reading #5940 and #4853 I don't see an obvious workaround.  I verified that the `ToolsVersion` is correctly set to 15.0

```
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

but it doesn't seem to matter.  Is there a known workaround for this problem?
