### ISSUE TITLE
HEAT5305 (heat.exe wix 3.11.1) cannot open some .net framework 4.7.2 projects

### ISSUE THREAD

**Issue by adaviding** [wixtoolset/issues#5930]
My WiX setup project does not interact correctly with .NET Framework 4.7.2 projects with new syntax conventions in the `*.csproj` file.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> Framework 4.7.2

* Describe the problem and the steps to reproduce it.

> Create a normal .NET Framework project in VS 2017.  Within the project, use the glob pattern to include your `*.cs` source files as follows.

```
<ItemGroup>
    <Compile Include="**\*.cs" />
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="bin\**\*.cs" />
</ItemGroup>
```

In the same solution, create a Setup Project for WiX v3 (`*.wixproj`).  Add a reference to the project described above into the WiX setup project, so your `*.wixproj` should contain something like this.

```
<ProjectReference Include="$(SolutionDir)MyCompanyName\Common\MyCompanyName.Common.Windows\MyCompanyName.Common.Windows.csproj">
	<Name>MyCompanyName.Common.Windows</Name>
	<Project>{9f99e1e6-2260-4991-9479-1ad228349ab7}</Project>
	<Private>True</Private>
	<DoNotHarvest></DoNotHarvest>
	<RefProjectOutputGroups>Binaries;Content;Satellites</RefProjectOutputGroups>
	<RefTargetDir>INSTALLLOCATION</RefTargetDir>
</ProjectReference>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> I get a build error when I build the project.

```
5>		C:\dev\github\my_company_name\my_company_name-core\packages\WiX.3.10.3\build\..\tools\Heat.exe project C:\dev\github\my_company_name\my_company_name-core\MyCompanyName\Common\MyCompanyName.Common.Windows\MyCompanyName.Common.Windows.csproj -configuration Debug -directoryid INSTALLLOCATION -platform AnyCPU -pog Binaries -pog Symbols -pog Sources -pog Content -pog Satellites -pog Documents -projectname MyCompanyName.Common.Windows -ag -sfrag -out obj\Debug\_MyCompanyName.Common.Windows.wxs
5>heat.exe(0,0): error HEAT5305: Failed to load project C:\dev\github\my_company_name\my_company_name-core\MyCompanyName\Common\MyCompanyName.Common.Windows\MyCompanyName.Common.Windows.csproj: The attribute "Remove" in element <Compile> is unrecognized.  C:\dev\github\my_company_name\my_company_name-core\MyCompanyName\Common\MyCompanyName.Common.Windows\MyCompanyName.Common.Windows.csproj
5>Done building project "DataServerInstaller64.wixproj" -- FAILED.
5>
```

**Comment by rseanhall** [comment]
This is because of https://github.com/wixtoolset/issues/issues/5490. See https://github.com/wixtoolset/issues/issues/4853 for details.

FYI, your output says you're using v3.10.3 not v3.11.1 like you specified in the bug.

**Comment by adaviding** [comment]
@rseanhall Yeah I tried it with `3.10.3` first, then I confirmed that it still happens on `3.11.1`.  After reading #5940 and #4853 I don't see an obvious workaround.

I added the `ToolsVersion` specifier to my .NET Standard project (in the `*.csproj` file), but it didn't help.

```
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk">
```

Is there a known workaround for this problem?

**Comment by rseanhall** [comment]
There is no workaround. Someone has to implement #5490.
