### ISSUE TITLE
Extensions should version their ids

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#5933]
* Describe the scenario and benefits that the feature supports.

> Merge modules mean it's possible to mix WiX v3 with WiX v4 (or v5 or ...) outputs. Some ids will sometimes clash (when modularization is suppressed) and other ids like table names will always clash, meaning it's possible to get into a state where multiple custom actions will each process the same data.

> Table names and ids for custom actions and Binary rows should be versioned to isolate them.

* Describe how you're accomplishing the feature today (if possible).

> n/a

* Describe what you'd like the new feature to do.

> Most ids are already "namespaced" with `Wix` prefixes. `Wix4` would suffice as a replacement.

**Comment by BMurri** [comment]
IIRC there was discussion on this issue in the wix-devs and possibly during a recent bi-weekly meeting.

Even though it'll probably be short, a WIP might be a great way to gather everyone's feedback (who would care to contribute) and buyoff in an organized manner.

**Comment by barnson** [comment]
Per meeting: Table names and ids will get a `Wix4` prefix and architecture-specific suffix. Assemblies and NuGet packages will follow `WixToolset.Extension, v4.x.y`.

**Comment by barnson** [comment]
## ToDoQueue
- [ ] ComPlus.wixext
- [ ] Dependency.wixext
- [ ] Iis.wixext
- [ ] Msmq.wixext
- [ ] Tag.wixext

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6612
