### ISSUE TITLE
WIX 3.11, Registration of COM objects for x86 and x64

### ISSUE THREAD

**Issue by dmitry-lipetsk** [wixtoolset/issues#5937]
Hello

I have two MSI packages (for win32 and win64), which install (and reg) COM object.

For correct registration, need split registration data to two components:
1. First component has unique GUID for win32 and win64. This component creates registry keys in HKCR\CLSID and in HKCR\TypeLib

2. Second component has one (stable) GUID for win32 and win64. This component creates registry keys with ProgID and in HKCR\Interface

WIX 3.11, if I understood correctly, not support this split. All reg data (CLSID, TypeLib, ProgID, Interfaces) located within Component->File->TypeLib.

I offer added to Component element the new attribute (like HKeyClassesRootGuid).

Internally WIX will create two component (for Guid and for HKeyClassesRootGuid).

Reg data for ProgID and for Interfaces will link with Component_HKeyClassesRootGuid

Reg data for CLSID and TypeLib will link with Component_Guid

---
At current time, for avoid this mistake of WIX, need manually write RegistryKeys for registration of ProgID and Interfaces.

**Comment by dmitry-lipetsk** [comment]
For HKCR\Interfaces - it is my mistake

Win64 uses HKCR\Interfaces
Win32 uses HKCR\WOW6432Node\Interface

These are separate registry hives.

So, Component->File->TypeLib->Interface may be used without any problems.

Problem exists for ProgID only.

**Comment by barnson** [comment]
This sounds a lot like an ancient feature request for `ProgIdRef`: https://github.com/wixtoolset/issues/issues/67 Does that cover what you're discussing?

**Comment by dmitry-lipetsk** [comment]
Seems - no.

You may close this ticket, if it not interest for you :)
