### ISSUE TITLE
Overwriting the back event of CustomizeDlg in the FeatureTree template does not work

### ISSUE THREAD

**Issue by nsk7even** [wixtoolset/issues#5939]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> WiX Toolset v3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 15.9.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> installed: 4.7.03062, project target: 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7, Windows 10

* Describe the problem and the steps to reproduce it.

> When trying to remove the license dialog of the WixUI_FeatureTree template, the back navigation from CustomizeDlg fails to skip the license dialog: pressing "Back" in the customize dialog still goes to the license dialog.
> Skipping the license dialog in forward direction works: pressing "Next" in the welcome dialog directly goes to the customize dialog.

```
    <!-- UI Settings -->
    <UI Id="WixUI_Custom">

      <!--Lade Default UI-->
      <UIRef Id='WixUI_FeatureTree' />
      
      <!-- Skip license dialog -->
      <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="CustomizeDlg" Order="2">1</Publish>
      <Publish Dialog="CustomizeDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" Order="1">Installed</Publish>
      <Publish Dialog="CustomizeDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" Order="2">NOT Installed</Publish>

    </UI>
```

> The publish lines are taken from the source code of the FeatureTree dialog: https://github.com/wixtoolset/wix3/blob/develop/src/ext/UIExtension/wixlib/WixUI_FeatureTree.wxs

* Describe the behavior you expected and how it differed from the actual behavior.

> Navivating back from CustomizeDlg should skip the license dialog as well and directly go to the specified target (WelcomeDlg in the example above).

**Comment by barnson** [comment]
There's no support for overwriting events; you have to replace the entire fragment.
