### ISSUE TITLE
Light.exe failes (Value cannot be null) when including merge modules to product.wxs

### ISSUE THREAD

**Issue by joestell** [wixtoolset/issues#5951]
## Bugs
WixToolset v4.0, Visual Studio 2015, Wix Toolset VS2015 Extension v0.9.21.62588, 

* Describe the problem and the steps to reproduce it.

Wix Setup project using several fragments containing files, shortcuts, directories and merge modules.  Previously was build on the Wix Toolset v3.x.  Recently updated to v4.x (same files, modules, everything).  Upon compilation, I was receiving the error:

`light.exe(0,0): error LGHT0001: Value cannot be null.`

By selectively removing components, I discovered this error only happens when one or more merge modules are included in the Product.wxs.

**Comment by robmen** [comment]
This was fixed in https://github.com/wixtoolset/Core/commit/6b30680fd7a712b45538c3f0a89d652f0457a893
