### ISSUE TITLE
Wix built is of less size

### ISSUE THREAD

**Issue by shashianjan** [wixtoolset/issues#5952]
Hi , 

   Iam building the wix tool from latest source code. Initially I build it with VS2017 where I faced many erros hence I shifted to VS2013. The build went smooth and created wix311.exe. When I checked the size of the exe it was just 2MB. I compared it with the downloaded version which amounts to 26MB. I used the buildsteps mentioned in the following link
http://wixtoolset.org/development/building-wix/ 

I have only run the MSbuild in the source path. I dint build the solution files as I was getting lots errors. 
am I doing something wrong. Please help me . 

Thanks and Regards

**Comment by robmen** [comment]
For WiX development questions please contact the [wix-devs mailing list](http://wixtoolset.org/documentation/).
