### ISSUE TITLE
Accessibility: Need option to explicitly name property of GUI Control

### ISSUE THREAD

**Issue by deepgu** [wixtoolset/issues#5954]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.7.1224.0

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Windows Narrator application (screen reader) reading undesirable names for GUI controls in installer.
There is no option to explicitly set GUI Control's (Type="PushButton", "Line", "Edit" etc) names property in the Control element in wixtoolset. Because of this controls either get no names or undesirable names. It causes difficulty in understanding GUI read by screen reader.    

* Describe the behavior you expected and how it differed from the actual behavior.

> There should an attribute to explicitly set name property for GUI Control (Button, edit, line/image etc.).

**Comment by barnson** [comment]
MSI doesn't support specifying the accessible name of controls.

**Comment by deepgu** [comment]
My ask is to be able to set "name" property of GUI control explicitly through wix configuration, so that when a screen reader reads control, it is desired name.

**Comment by robmen** [comment]
That would be awesome! If you convince the Windows Installer team to support such a feature in the MSI engine, let us know then we could then add support for it in the WiX Toolset.

**Comment by BMurri** [comment]
This is what Microsoft provides for MSI accessibility: https://docs.microsoft.com/en-us/windows/desktop/Msi/accessibility

Everything on that page can be coded through WiX. If following everything relevant on that page isn't sufficient, you will need to open a bug with Microsoft directly.

WiX can't do more than that, unless you want to do an embedded external UI (our tool supports wiring yours in) or a bootstrapper interface (we provide a bootstrapper you can add your own UX to).

**Comment by BMurri** [comment]
From that document:

For Edit, PathEdit, ListView, ComboBox or VolumeSelectCombo controls, screen readers take accName and accKeyboardShortcut from a Text Control that must precede the control in the Control_Next sequence of the dialog box. The screen reader takes accName from the Text field of the Text control and accKeyboardShortcut from the keyboard shortcut in the Text field, if a shortcut exists.

So, right before the controls you need to tag, place a <Text/> element, which will create text controls as per the copied paragraph.

**Comment by deepgu** [comment]
@BMurri , I need ability to name separator , button etc. so that screen reader reads them properly.

**Comment by BMurri** [comment]
For Edit, PathEdit, ListView, ComboBox or VolumeSelectCombo controls, screen readers take accName and accKeyboardShortcut from a Text Control that must precede the control in the Control_Next sequence of the dialog box. The screen reader takes accName from the Text field of the Text control and accKeyboardShortcut from the keyboard shortcut in the Text field, if a shortcut exists.

**Comment by BMurri** [comment]
If you need help with that, please ask on wix-users
