### ISSUE TITLE
Accessibility: Need option to set order of control (Tab Order) on GUI.

### ISSUE THREAD

**Issue by deepgu** [wixtoolset/issues#5955]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

Screen reader (e.g. Windows Narrator) reads controls on the Custom Dialog in undesired order. This is because there is no way to describe order of Control (similar to TabOrder) in Dialog. 

* Describe how you're accomplishing the feature today (if possible).

Not possible.

* Describe what you'd like the new feature to do.

Provide an attribute in Control element to set order of control on GUI.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
