### ISSUE TITLE
heat.exe fails to load project

### ISSUE THREAD

**Issue by ksobon** [wixtoolset/issues#5956]
## Discussions and support

I am getting this error: 

Severity	Code	Description	Project	File	Line	Suppression State
Error		Failed to load project C:\Users\username\source\repos\Zombie\Zombie\Zombie.csproj: A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "10.0.10240.0" instead of a number, in condition "'$(UseOSWinMdReferences)' == '' and ('$(TargetPlatformWinMDLocation)' == '' and '$(TargetPlatformIdentifier)' == 'Windows' and '$(TargetPlatformVersion)' > '7.0')".  C:\Windows\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets	ZombieInstaller	heat.exe	0	

Any idea how to resolve this?

**Comment by barnson** [comment]
> Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.
