### ISSUE TITLE
Need support for localization of tooltip property of Control.

### ISSUE THREAD

**Issue by imdeepakg** [wixtoolset/issues#5957]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.7.1224.0

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Tooltip attribute of Control element is not of Formatted type and won't expand properties - just plain text is allowed there. 

* Describe the behavior you expected and how it differed from the actual behavior.

> Tooltip attribute of Control element should accept property so that it can be localized.

**Comment by barnson** [comment]
MSI doesn't support that. See "Control Table" in the MSI SDK.

**Comment by deepgu** [comment]
Control table says here (https://docs.microsoft.com/en-us/windows/desktop/Msi/control-table) that it is a "localizable text strings"

**Comment by barnson** [comment]
If it's not Formatted, it cannot use property references. Localization shouldn't use properties.

**Comment by BMurri** [comment]
Use "!(loc.WixLocalizationVariable)" for localizable fields.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by deepgu** [comment]
@BMurri , can you help me understand how does that help to make tooltip localizable? tooltip text is taken from help field (pipe separated first part) which is not Formatted.

**Comment by BMurri** [comment]
You localize the .wxl files, then feed those files to the linker (light) when building each localized MSI.

With WiX, there's no need to directly localize the MSIs. That way, the localizability of each database field is inmaterial.

You are making a separate MSI for each language, using only one set of source files for all of them, correct?

**Comment by BMurri** [comment]
Even if you are localizing the MSIs directly, fields marked localizable don't have to be Formatted. Like @barnson said: don't use properties to localize.

**Comment by BMurri** [comment]
Ask on wix-users if you don't understand. Localization is covered in the tutorial, in the book, in the documentation, and on at least a couple of blogs. And none of the localization techniques require more than the most minimal use of properties, if any. If you're depending on properties, your not doing it right, no matter which toolset you use to build your MSIs
