### ISSUE TITLE
Installation failed with Error 0x8004e00f and 0x80070511

### ISSUE THREAD

**Issue by SivaTamatam** [wixtoolset/issues#5958]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)
3.10.3.3007
* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)
**VS2012 Update 3**
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)
**4.5**
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)
**10.0.17134 Build 17134**
* Describe the problem and the steps to reproduce it.

Installing some Windows PC's throwing below error info and stopped to install

**Action start 14:37:55: ConfigureComPlusInstall.
ConfigureComPlusInstall:  Error 0x8004e00f: Failed to get collection
ConfigureComPlusInstall:  Error 0x8004e00f: Failed to get partitions collection
ConfigureComPlusInstall:  Error 0x8004e00f: Failed to get partitions collection
ConfigureComPlusInstall:  Error 0x8004e00f: Failed to get applications collection
ConfigureComPlusInstall:  Error 0x8004e00f: Failed to find collection object for application
ConfigureComPlusInstall:  Error 0x8004e00f: Failed to verify applications**

**Action start 21:33:58: ConfigureComPlusInstall.
ConfigureComPlusInstall:  Error 0x80070511: Failed to get collection
ConfigureComPlusInstall:  Error 0x80070511: Failed to get partitions collection
ConfigureComPlusInstall:  Error 0x80070511: Failed to get partitions collection
ConfigureComPlusInstall:  Error 0x80070511: Failed to get applications collection
ConfigureComPlusInstall:  Error 0x80070511: Failed to find collection object for application
ConfigureComPlusInstall:  Error 0x80070511: Failed to verify applications**

**Comment by barnson** [comment]
> Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

**Comment by perumalsamya** [comment]
Was there any solution found for the issue ? I am facing same issue
