### ISSUE TITLE
Naming a Wix installer as "Setup.exe" causes strange behavior

### ISSUE THREAD

**Issue by benp87** [wixtoolset/issues#5962]
* Which version of WiX are you building with?
3.11.1

* Which version of Visual Studio are you building with (if any)?
VS2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
0.9.21.62588

* Which version of .NET are you building with?
3.5 and 4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10

* Describe the problem and the steps to reproduce it.
After building a Wix installer, no matter if using a managed bootstrapper or the default one, and then renaming it to "Setup.exe", I monitored this executable with "Process monitor", I see that there are a lot of files that this executable tries to create, like "Welcome.exe", "LOTD.exe", "Monopoly.exe", etc..
This only happens when the executable is named "Setup.exe".

* Describe the behavior you expected and how it differed from the actual behavior.
Renaming the executable should not affect the behavior of the installer.

**Comment by barnson** [comment]
That's Windows, not WiX. Windows does lots of stuff with files named setup.exe; that's why WiX no longer allows it. https://www.firegiant.com/blog/2016/1/20/wix-v3.10.2-released/
