### ISSUE TITLE
Recovery Actions non-functionality should be documented

### ISSUE THREAD

**Issue by directionless** [wixtoolset/issues#5964]
## Bug

Apparently [MsiConfigureServices](https://docs.microsoft.com/en-us/windows/desktop/Msi/msiconfigureservices-action) does not reliably support **Recovery Actions**. This is noted in the MSI docs with:

> Windows Services provides the ability to automatically perform predefined actions in response to a failure in a service. To support programmatically setting up these Recovery Actions when a service fails, MsiServiceConfigFailureActions was added to MSI in version MSI 5.0. However, this functionality is not working as expected.

This additionally seems to be represented by error [CNDL1150](https://github.com/wixtoolset/wix3/commit/e8504c54e4cd186f676931e1d39a6e8400e575b8), which has a variety of bits of online discussion. The most common recommendation is to use a custom action to call `sc.exe`

This should be reflected in the [documentation](http://wixtoolset.org/documentation/manual/v3/xsd/util/serviceconfig.html) for the ServiceConfig. I read the docs, assumed it would work, build tools, and then discovered a compiler warning telling me it was broken. 

I'm happy to submit a PR, but I'm unclear which part of the source code matters. I see the util schema in a lot of places, and I don't understand the structure here.

**Comment by BMurri** [comment]
The WixUtilExtension provides a ServiceConfig element that works correctly for all versions of Windows Installer, and is probably preferable to rolling your own CA.

Microsoft doesn't document the failure of the reboot and restart actions in the MsiServiceConfigFailureActions table, although the failure does appear to be somewhat widely reported, included by at least one person inside MSFT at the time of their report.

**Comment by BMurri** [comment]
I personally feel that #5306 (which provides the recommended suggestion of using the WixUtilExtension's ServiceConfig element) is the correct resolution for this issue.

**Comment by directionless** [comment]
Ah. So the WixUtilExtension ServiceConfig work correctly? Same deal then, this should be documented in http://wixtoolset.org/documentation/manual/v3/xsd/wix/serviceconfig.html

**Comment by robmen** [comment]
@directionless that part of the documentation comes from the [wix.xsd]w]. If you'd like to contribute the additional documentation, you'll want to edit [that file][w].

[w]: https://github.com/wixtoolset/wix3/blob/develop/src/tools/wix/Xsd/wix.xsd
