### ISSUE TITLE
Question: how to cancel installation / update of msi package if applcation on target pc was not found 

### ISSUE THREAD

**Issue by Torchok19081986** [wixtoolset/issues#5965]
Hallo, i have a question, and hope, that someone can help me with. 
I create 2 msis : one for fullinstaller and one for update. how do i create update msi with condition where it can be only executed if product was found on target system and if not, cancel update.

Currently i tried rearch for installed product with Appseach by Upgradecode, but i always got TargetinovakeExpception with System.NullreferenceException.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
