### ISSUE TITLE
Bundle installation process crashes in remote execution scenarios

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [wixtoolset/issues#5966]
* Which version of WiX are you building with?
3.11.1

* Which version of .NET are you building with? 
4.7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on? 
Windows 10 build 17763 (rs5)

* Describe the problem and the steps to reproduce it.

Bundle installation process crashes in remote execution scenarios

1) Build a bundle with 3.11.1 toolset, that contains a condition that uses RebootPending property.
2) Run bundle in remote PowerShell session, i.e. 
 $proc = Start-Process -wait -PassThru -FilePath .\bundle_311.exe -ArgumentList ('/quiet', '/norestart')
3) Bundle installs but the process crashes.
4) Obtain process exit code:
$proc.ExitCode
Output:
-1073741819

RebootPending property, would be evaluated using ISystemInformation interface - this interface is not available in remote execution environment.

* Describe the behavior you expected and how it differed from the actual behavior.

Bundle process does not crash and returns success code (0).

* Related issues:

https://github.com/Microsoft/dotnet/issues/839

**Comment by barnson** [comment]
@heaths -- we'll need the signing service change to get a build with this fix out.

**Comment by heaths** [comment]
I was planning on that for WiX 3.14, and they use 3.11 so an upgrade to 3.14 would be easier for them (and the VC team). Would a dual check-in be acceptable? Or is there yet any code flow planned between 3.x and 4.x?

**Comment by barnson** [comment]
I'd say that starting with v3.14 is fine; the v4 microrepos complicate the problem. @robmen, do you agree?

**Comment by heaths** [comment]
On a separate note, is that really what's wrong with this bug? @NikolaMilosavljevic said they couldn't cocreate `SystemInformation` when executing remotely. They wouldn't have even gotten that far if wixstdba.dll (or mbahost.dll, if using managed) weren't signed. `LoadLibrary` fails when Device Guard blocks the unsigned DLL.

**Comment by barnson** [comment]
This bug isn't due to Device Guard, just COM goo. But we need signing to work before we can release a build with this fix in place.

**Comment by heaths** [comment]
COM goo 😝

Let's take the signing conversation over to #5329.

**Comment by rseanhall** [comment]
@firegiantco Need this in v4, too.
