### ISSUE TITLE
Deploy wix bootstrap build app in iis

### ISSUE THREAD

**Issue by SudhagaranD** [wixtoolset/issues#5968]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by SudhagaranD** [comment]
developed bootstrap build in mvc .net 4.7.1 when i run the app in debug mode /developement the installer file will get generated . when i host the app  in local iis the output file not get generated. 
the logic is same like the [sample] here (https://csharp.hotexamples.com/examples/WixSharp/Project/BuildMsi/php-project-buildmsi-method-examples.html#0x3b8142cdbf453922c1d761aee454fb62311231a0f980af4208a65e9dd8583e06-23,,67,)

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
