### ISSUE TITLE
Failure to uninstall a msp

### ISSUE THREAD

**Issue by wanpin** [wixtoolset/issues#5971]
* Which version of WiX are you building with?
3.11.2318.0

* Windows version
Windows 8.1 PRO, Windows 10. Our QA reported they can repro on other windows versions.

* Describe the problem and the steps to reproduce it.

1. I install my .msi file (MyProduct) and the windows app works like a charm
2. I apply my .msp file (MyProduct Roll-up from 6.1.19052.3 to 6.1.19057.1) and the windows app works like a charm
3. When trying to remove a patch from the Control Panel, I'm getting the following error:
_Fatal error during installation_
The Event viewer has some entries:
>- `Product: MyProduct - Update 'MyProduct Roll-up from 6.1.19052.3 to 6.1.19057.1' could not be removed. Error code 1603. Windows Installer can create logs to help troubleshoot issues with installing software packages. Use the following link for instructions on turning on logging support: http://go.microsoft.com/fwlink/?LinkId=23127`
>- `Product: MyProduct  -- Configuration failed.`
>- `Windows Installer reconfigured the product. Product Name: MyProduct  . Product Version: 6.1.19052.3. Product Language: 1033. Manufacturer: MYCOMPANY. Reconfiguration success or error status: 1603.`
>- `Ending a Windows Installer transaction: {E1CE4404-184B-4933-B221-09241816244E}. Client Process Id: 8868.`

I can provide the .msi and the .msp file.

Thank you in advance,
Wander

**Comment by barnson** [comment]
> Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

Rob has a list of some [support options](http://robmensching.com/support/) on his website.
