### ISSUE TITLE
Default for ServiceInstall vital attribute not documented

### ISSUE THREAD

**Issue by breyed** [wixtoolset/issues#5974]
In `WiX.chm`, for the `ServiceInstall` element, the documentation for the `Vital` attribute doesn't say whether WiX sets it true by default. I think it should. Installers with non-vital services seem like they'd be rare.

By comparison, `File` documents its `Vital` element like this:

> The default is "yes," unless the -sfdvital switch (candle.exe) or  SuppressFileDefaultVital property (.wixproj) is used.

Wix 3.11.1

**Comment by BMurri** [comment]
Boolean attributes default to false unless otherwise specified.

It would be good to explicitly mention that somewhere.

**Comment by barnson** [comment]
Should be documented either way and we should consider changing the default in v4.0.

**Comment by BMurri** [comment]
I've been thinking about the issue of "true defaults" and I think I have the correct wordsmithed solution: the prefix "Suppress" (e.g. SuppressVital)

**Comment by breyed** [comment]
As a point of reference, the .NET Framework data type defaults are all bits zero, so false/0/null, depending on the datatype. I think WiX has the similar pattern of data type defaults.

By default, the default values for properties match their data type defaults; however, an individual property can have its default override the data type default. For example, various `Id` properties have quite useful defaults. Another example is `File.Vital`, which defaults to true. This is analogous in .NET to setting a property's default value in the class's constructor.

The most useful default for `ServiceInstall.Vital` is true. For backward compatibility purposes, changing the default from false to true would generally be an unbreaking change. That is to say, it would likely fix a great number of currently broken setup projects that forgot to manually set vital to true. However, there may be some setup programs that want to charge ahead even without their services didn't install; for those it would be a breaking change.

`SuppressVital` would provide backward compatibility (for better and for worse), but it would lose consistency with the Windows Installer tables and with the WiX `File.Vital`. I don't think the benefit justifies the additional complexity.

**Comment by BMurri** [comment]
Something like `SuppressVital` would be done across the board (i.e. `File.SupressVital` would replace `File.Vital`) and in my opinion would likely only be done in v4 (because we are really trying very hard to add anymore to v3, because v4 really needs to ship sooner rather than later and there are few hands doing the work).

There's president in both .net and in the Win32 APIs for internal bits to be presented flipped in public APIs to better accommodate usage patterns, even though the label names can get a bit awkward as a result.

In our own toolset, `File.Vital` has spent over 3/4 of its life defaulting to `no` because we simply copied the underlying system without thinking about what the default should be. It took literally years to determine the defaults for the various `Id` properties and to even decide if as a toolset we wanted to even go down that road.

**Comment by breyed** [comment]
Such a `SuppressVital` would provide a default that matches the data type default would be consistent across all tables, but it would still leave the broader inconsistency that some properties (e.g. `SuppressVital`) default to the data type default, whereas others don't (e.g. `Id`).

I think WiX's close alignment to Windows Installers tables is very valuable (e.g. positive `Vital` and positive `msidbFileAttributesVital`). It simplifies moving between the WiX documentation and Windows Installers documentation. I agree there's precedent for adding API wrappers changing semantics, however, I don't think it adds enough value to be worth the alignment decrease.

Windows Installer has limited default support due to its database design. For example, for the `File` table, the primary key and `FileName` aren't nullable, so they don't support defaults. Since `Attributes` is a bit field, none of the bits can have defaults.

Since WiX is XML, every property is nullable, even where it's not in Windows Installer. This means that every property can have a default. I think WiX should continue taking advantage of it. Just indicate in the docs what those defaults are and that if no default is specified, the data type default is used.

**Comment by robmen** [comment]
@breyed Thank you very much for your feedback. We've debated how important the "null always means no/false/not present" precedent is. As I understand it, your suggestion is that defaulting to false is less important than defaulting to the most logical value (such as Vital='yes', which I do agree with) and then documenting the default value when absent.
