### ISSUE TITLE
Wix setup specific not install

### ISSUE THREAD

**Issue by Stefan2210** [wixtoolset/issues#5976]
Hello,
I have Wix Setup 3.1 Build an installer. On only ohne pc i have an issue that the Installation of my exe does not run. The progressbar is invisible and nothing complete. The Installation area is a nass Partition. Older Software Versions with wix run on this pc. Other computers with the newest Software Version does not have this problem with the exe Installation

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
