### ISSUE TITLE
ResolveSource not working in Upgrade or Uninstall scenario

### ISSUE THREAD

**Issue by armsee** [wixtoolset/issues#5980]
We have a C# WinForms based setup bootstrapper application which uses the burn engine from WiX 3.11.
This works fine most of the time. 
But some of our customers seem to run occasionally into a problem we do not know how to handle correctly:
They want to uninstall or upgrade our product but it appears, neither the Package Cache nor the C:\Windows\Installer folder have a copy of the installed MSI package. 
So when the uninstallation of the MSI package is processed by the engine, it reports a ExecuteMsiMessage event with the MessageType ResolveSource and after that, the installation appears to hang within the ResolveSource action. 
We also already have subscribed the “ResolveSource” event from the engine, but this event seems to be fired only by the engine in the case of a new installation, not when a deinstallation is processed.
Since the engine calculates the UI level to be used for the installation with “INSTALLUILEVEL_NONE | INSTALLUILEVEL_SOURCERESONLY”, we would expect the Windows Installer to prompt for an alternative source path to be given, but no message appears.

The last part of the MSI log file of the package looks like the following – also note the last line does not seem to be written fully:
MSI (c) (40:F8) [10:40:30:831]: SOURCEMGMT: Now checking product {AF91502A-827E-41A4-A1AF-13C170A3D2AB}
MSI (c) (40:F8) [10:40:30:831]: SOURCEMGMT: Media is enabled for product.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Attempting to use LastUsedSource from source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2:  3: GuiElementsInstaller.msi 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Processing net source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2: -2147483647 3: GuiElementsInstaller.msi 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Processing media source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2: -2147483647 3: GuiElementsInstaller.msi 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Processing URL source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\URL 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2: -2147483647 3: Gu

Does someone know this issue and how it should be handled correctly? Or is this an open issue in WiX?
We have a C# WinForms based setup bootstrapper application which uses the burn engine from WiX 3.11.
This works fine most of the time. 
But some of our customers seem to run occasionally into a problem we do not know how to handle correctly:
They want to uninstall or upgrade our product but it appears, neither the Package Cache nor the C:\Windows\Installer folder have a copy of the installed MSI package. 
So when the uninstallation of the MSI package is processed by the engine, it reports a ExecuteMsiMessage event with the MessageType ResolveSource and after that, the installation appears to hang within the ResolveSource action. 
We also already have subscribed the “ResolveSource” event from the engine, but this event seems to be fired only by the engine in the case of a new installation, not when a deinstallation is processed.
Since the engine calculates the UI level to be used for the installation with “INSTALLUILEVEL_NONE | INSTALLUILEVEL_SOURCERESONLY”, we would expect the Windows Installer to prompt for an alternative source path to be given, but no message appears.

The last part of the MSI log file of the package looks like the following – also note the last line does not seem to be written fully:
MSI (c) (40:F8) [10:40:30:831]: SOURCEMGMT: Now checking product {AF91502A-827E-41A4-A1AF-13C170A3D2AB}
MSI (c) (40:F8) [10:40:30:831]: SOURCEMGMT: Media is enabled for product.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Attempting to use LastUsedSource from source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2:  3: GuiElementsInstaller.msi 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Processing net source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2: -2147483647 3: GuiElementsInstaller.msi 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Processing media source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\Media 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2: -2147483647 3: GuiElementsInstaller.msi 
MSI (c) (40:F8) [10:40:30:832]: SOURCEMGMT: Processing URL source list.
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1402 2: UNKNOWN\URL 3: 2 
MSI (c) (40:F8) [10:40:30:832]: Note: 1: 1706 2: -2147483647 3: Gu

Does someone know this issue and how it should be handled correctly? Or is this an open issue in WiX?

**Comment by BMurri** [comment]
As far as I know, the bootstrapper application is THE windows installer UI for all cases except those initial installs that are flagged to produce their own UI. Thus, on maintenance transactions, your BA is responsible for responding to prompts for source, unless I misunderstand the sources (it's been a while since I have gone through them, so maybe something changed in the interim).

You need to respond to the ResolveSource event, call the appropriate SetLocalSource/SetDownloadSource API with a good location for the package(s), then return a result code in the args for the event to tell Windows Installer to try the new location.

**Comment by armsee** [comment]
The problem is, that in the case of an upgrade or unistall no ResolveSource event is fired from the Engine. The BA hangs in this state, and you can only kill the process. We have subscribed to all events of the engine as part of our troubleshooting, but in the situation described we do not get a single event. In case of a first time installation the system behaves correctly, if a source is missing the engine fires the ResolveSource event, and we have implemented the appropriate event handler for it.

**Comment by BMurri** [comment]
I've had MSIs do that without any bootstrapper/chainer involved, so it's quite possibly Windows Installer's fault. While it's been over a decade, not much has changed in that code on Windows in that time.

A mitigation would be to query the package paths of all MSI packages during detect and check for file existence, or better yet, briefly check the file for identify and corruption, and add recaching them to the plan. A good feature would be for the engine to do that automatically, in my not so humble opinion.

**Comment by barnson** [comment]
https://docs.microsoft.com/en-us/windows/desktop/msi/handling-progress-messages-using-msisetexternalui says:

> // Because an external UI handler cannot handle the
> // INSTALLMESSAGE_RESOLVESOURCE message,
> // Windows Installer allows a UI level,INSTALLUILEVEL_SOURCERESONLY
> // that will allow an external UI handler to have full control while also still 
> // permitting an install to resolve the source

**Comment by BMurri** [comment]
Yet that same page says

> When using MsiSetExternalUI with a message type of INSTALLMESSAGE_FILESINUSE, the message sent to the external UI handler function does not contain any information about files in use or window titles used by the FilesInUse dialog box. You should use MsiSetExternalUIRecord to obtain information.

https://docs.microsoft.com/en-us/windows/desktop/msi/monitoring-an-installation-using-msisetexternaluirecord doesn't say much of anything, unfortunately.

https://docs.microsoft.com/en-us/windows/desktop/msi/using-an-embedded-ui, on the other hand, appears to show support for resolving sources, and has this to say:

`    // This function is similar to the MsiSetExternalUIRecord callback.
`

**Comment by barnson** [comment]
Embedded UI != external UI, even if it works in a similar manner. So maybe.

**Comment by barnson** [comment]
Needs investigation.

**Comment by armsee** [comment]
Are there any new findings on the matter? We have an open customer defect to which we would have to react.

**Comment by robmen** [comment]
This issue is open and unassigned. That means it is waiting for someone to investigate the root problem, discuss possible solutions to that problem then implement the decided solution.

If you are interested in doing so yourself, our [developer documentation][devdoc] provides a great checklist for getting started.

If you are not interested then you are waiting for someone else to become interested. If this issue has been open for a long time then there probably isn't much interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[devdoc]: http://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by rseanhall** [comment]
Using the WiX 3.11.1 installer, it will hang if the MSI was deleted from C:\Windows\Installer and the Package Cache and it was ran with `/quiet /uninstall`.

**Comment by rseanhall** [comment]
It appears that if you send `INSTALLUILEVEL_NONE | INSTALLUILEVEL_SOURCERESONLY` with `NULL` hWnd to `MsiSetInternalUI` and then the MSI actually needs to resolve source, it hangs. In v3, the BA always needs to send a valid hWnd to `Apply` to avoid this. In v4, we need to figure out how to get Burn to prevent this combination and also should never use `INSTALLUILEVEL_SOURCERESONLY` unless we're showing UI.

As documented [here](https://docs.microsoft.com/en-us/windows/win32/msi/parsing-windows-installer-messages), Windows Installer sends `INSTALLMESSAGE_RESOLVESOURCE` messages for information only so it is impossible for Burn (and thus the BA) to resolve the source programmatically. In v3, the BA would have to do a separate `Detect`/`Plan`/`Apply` cycle to get the package back into one of the caches (probably by doing a `Repair` or `Cache` action). In v4, I think the solution is implementing https://github.com/wixtoolset/issues/issues/5504.
