### ISSUE TITLE
Heat fails to suppress VB6 registry entries when -svb6 is combined with -scom

### ISSUE THREAD

**Issue by t-johnson** [wixtoolset/issues#5982]
Using Wix build 3.11.2318.0
Related to heat.exe and using the scom and svb6 command line options together.

To reproduce, you will need a COM dll build in VB6

When running the command:
> heat file <filename> -scom -svb6 -o out.txt

the out.txt file contains RegistryValue entries for the MSVBVM60.DLL library, which should be suppressed by the -svb6 command option

**Comment by t-johnson** [comment]
The following is how i am working around it this issue:
https://github.com/t-johnson/wix3/commit/1b6454cd42e981f65228807fb8371a8fdbc09eb1

**Comment by barnson** [comment]
Please submit a pull request against https://github.com/wixtoolset/wix4.

**Comment by nsleigh** [comment]
Chipping in as the original author of -svb6. 
Not too sure it makes sense to specify both options, if you are suppressing com then there shouldn't be any need to also suppress the vb6 com entries. Having said that it looks like -scom is not working as I would expect.

**Comment by t-johnson** [comment]
Neil - i would not want to change the behavior of the -scom flag by itself,
people might be depending on the current behavior (even it if it not
intended).  Which is why i just added suppression of the VB6 registry
entries when the -scom and -svb6 are combined.

**Comment by nsleigh** [comment]
Sorry I deleted my comment as I realised I was missing the point of the -scom flag.

**Comment by t-johnson** [comment]
no problem. i wondered why i got an email and didn't see the comment on github
