### ISSUE TITLE
WiX setup project-Visual Studio Professional 2012 -WiX Editor not showing 

### ISSUE THREAD

**Issue by prakashb83** [wixtoolset/issues#5985]
WiX setup project-Visual Studio Professional 2012 -WiX Editor not showing 

I recently installed Microsoft Visual Studio Professional 2012 Version 11.0.50727.1 RTMREL onto an 64 bit windows server 2012 R2 

I am facing below issue WiX Editor not showing while creating the MSI Package using Wix Toolset . Please find the below screen FYR

I have followed below steps : 
Visual studio version : Visual Studio Professional 2012 –V.11.0.61219 
OS :  windows server 2012 R2
WIX toolset : V 3.11.1.   https://marketplace.visualstudio.com/items?itemName=RobMensching.WixToolsetVisualStudio2012Extension
Visual Studio WiX Setup Projects : https://marketplace.visualstudio.com/items?itemName=Add-inExpress.DesignerforVisualStudioWiXSetupProjects
Error :  VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products. The problem is that the WIX Editor not showing
 
  
The problem is that the WIX Editor not showing

![WIX Editor](https://user-images.githubusercontent.com/12325960/56637285-e2502780-6688-11e9-8966-92e6702ff773.png)

**Comment by robmen** [comment]
That menu item doesn't come from WiX. Votive (the WiX Toolset Visual Studio Extension) doesn't add that menu item. You're looking for something else.
