### ISSUE TITLE
VS 2019 Preview Extension Does Not Supply Properties For VS 2019

### ISSUE THREAD

**Issue by kdawg1406** [wixtoolset/issues#5991]
## Scenario

I'm trying to build an installer for VS 2019.  In the past, I would use properties such as "VS2015_ROOT_FOLDER", however, there are no properties for VS 2019.

`<PropertyRef Id='VS2015_ROOT_FOLDER'/>
<SetDirectory Id="DIR_VS2015_ROOT_FOLDER" Value="[VS2015_ROOT_FOLDER]" Sequence="both" />        
`
http://wixtoolset.org/documentation/manual/v3/customactions/wixvsextension.html

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> VS 2019 16.0.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Preview 2019

* Which version of .NET are you building with?

> 4.7.2

* Describe the problem and the steps to reproduce it.

I can't edit the .wxs file for an install that needs the VS Root Folder for VS 2019.

* Describe the behavior you expected and how it differed from the actual behavior.

I would expect a listing of properties for VS 2019

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/5923

**Comment by kdawg1406** [comment]
@barnson #5923 is closed.  What do I need to do to create the installer that targets VS 2019 and the root folder?  Sorry, I'm not an advanced user, but do love Wix.  Thank you!

**Comment by BMurri** [comment]
My understanding is that VS removed the "root folder" for vs 2017/2019/future because they now allow SxS installations of any given VS, even if the same version.

You have to query the installed instances and deal with each one, now.

**Comment by kdawg1406** [comment]
@BMurri any idea how to query for this? I have both 2017 and 2019 installed, they are in different folders.

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

Greatful for any assistance.

Karl

**Comment by kdawg1406** [comment]
This is how I had to author the wxs file in the past.
What is the recommended way for VS 2019?

Thank you!!!

`
<Fragment>

    <PropertyRef Id='VS2015_ROOT_FOLDER'/>
    <SetDirectory Id="DIR_VS2015_ROOT_FOLDER" Value="[VS2015_ROOT_FOLDER]" Sequence="both" />        
        
    <Directory Id="TARGETDIR" Name="SourceDir">
        <Directory Id="DIR_VS2015_ROOT_FOLDER">
            <Directory Id="COMMON7" Name="Common7">
                <Directory Id="PACKAGES" Name="Packages">
                    <Directory Id="DEBUGGER" Name="Debugger">
                        <Directory Id="INSTALLFOLDER" Name="Visualizers" />
                    </Directory>
                </Directory>
            </Directory>
        </Directory>
    </Directory>

    <Property Id="WIXUI_INSTALLDIR" Value="INSTALLFOLDER" />
</Fragment>
`
