### ISSUE TITLE
Accessibility: Narrator reads decorative image as text

### ISSUE THREAD

**Issue by jithinjosepkl** [wixtoolset/issues#5992]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.10.3.3010

* Which version of Visual Studio are you building with (if any)?
VS 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?
4.0
> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

Narrator reads decorative image as the text associated with it. As per accessibility experts, this should not be associated with text. Attached video should clarify more.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

[3746098_A11y_MSMPI_MSMPISDKSetupPopup_Screenreader.zip](https://github.com/wixtoolset/issues/files/3139424/3746098_A11y_MSMPI_MSMPISDKSetupPopup_Screenreader.zip)

**Comment by barnson** [comment]
Windows Installer is in charge of the UI at runtime. WiX is the build tool and cannot influence runtime behavior except as MSI allows. MSI would need to implement a change like this.
