### ISSUE TITLE
Accessibility: progress bar elements are incorrect

### ISSUE THREAD

**Issue by jithinjosepkl** [wixtoolset/issues#6002]
* Which version of WiX are you building with?

3.10.3.3010

* Which version of Visual Studio are you building with (if any)?

VS 2017

* Which version of .NET are you building with?

4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10

* Describe the problem and the steps to reproduce it.

Progress bar elements are incorrect. As per accessibility team, for a progress bar element, the RangeValue pattern must return a Minimum value of 0.0, a Maximum value of 100.0, and IsReadOnly true.

![3766416-PNG](https://user-images.githubusercontent.com/6690627/57108788-a4867b00-6ce8-11e9-8d13-172e285dc903.png)

**Comment by barnson** [comment]
Windows Installer is in charge of the UI at runtime. WiX is the build tool and cannot influence runtime behavior except as MSI allows. MSI would need to implement a change like this.
