### ISSUE TITLE
ExePackage - External payloads

### ISSUE THREAD

**Issue by benp87** [wixtoolset/issues#6003]
* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> VS2017, version 15.9.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 RS4

* Describe the problem and the steps to reproduce it.

> I have created a bundle that contain few ExePackages, one of the ExePackages contains payloads that I marked as external (compressed="no"), which means that after I build the bundle, those files (payloads) are being copied right next to the bundle.
The issue is that when I change those files (Text files), the source files are also being changed, it's like those files are somehow linked or something..

* Describe the behavior you expected and how it differed from the actual behavior.

> The files should be copied right next to the bundle but they shouldn't be linked to the source files that they were copied from.

**Comment by barnson** [comment]
WiX uses hard linking instead of copying files to improve performance. There's an existing feature request to allow it to be suppressed: https://github.com/wixtoolset/issues/issues/5734
