### ISSUE TITLE
Error 0x80004005: failed to connect to database

### ISSUE THREAD

**Issue by ComeOutToPlay** [wixtoolset/issues#6004]
I am using following Wix xml configuration:

          <Component Id="SqlUser" Guid="a6896bba-1818-43e0-824f-9c586e5e0a3e" KeyPath="yes" Win64="yes">
            <User Id="SqlUser" Name="[DATABASE_USERNAME]" CreateUser="no" Password="[DATABASE_PASSWORD]" xmlns="http://schemas.microsoft.com/wix/UtilExtension" />

            <CreateFolder />
          </Component>

          <Component Id="security" Guid="a6896bba-1818-43e0-824f-9c587c83e864" KeyPath="yes" Win64="yes">
            <SqlDatabase Id="security" CreateOnInstall="yes" Database="security" Server="[DATABASE_INSTANCE]" User="SqlUser" xmlns="http://schemas.microsoft.com/wix/SqlExtension">
              <SqlScript Id="script" BinaryKey="script" ExecuteOnInstall="yes" />
            </SqlDatabase>

            <CreateFolder />
          </Component>

I installed with this configuration successfully on several Windows 10 servers, but when I try on a Windows 2016 Standard, an error appears. 

[Popup window](https://ibb.co/XtVK1LN)

The error log describes the error this way:

    Info: ExecuteSqlStrings:  Error 0x80004005: failed to connect to database: 'security'
    Error: Failed to connect to SQL database.  (-2147467259   security      )
    Info: CustomAction ExecuteSqlStrings returned actual error code 1603 (note this may not be 
    100% accurate if translation happened inside sandbox)
    Info: Action ended 15:52:30: InstallFinalize. Return value 3.

I found some advices like enabling TLS protocols, or starting the SQL Browser service, but nothing worked.

Any comment would be appretiated!

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by ComeOutToPlay** [comment]
Thank you! I'll do it
