### ISSUE TITLE
Bundle doesn't detect earlier bundle with BundleUpgradeCode in different GUID style

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#6008]
## Bugs

* Which version of WiX are you building with?
3.11.1

* Which version of Visual Studio are you building with (if any)?
VS 2015 Professional Update 3

* Which version of .NET are you building with?
4.5.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Server 2012 R2

* Describe the problem and the steps to reproduce it.
1. Create a bundle with UpgradeCode '{1227229F-F0FA-40E5-A777-4416EC73EACA}' version 1.0
1. Install the bundle v1.0
1. Create a bundle with UpgradeCode '1227229F-F0FA-40E5-A777-4416EC73EACA' version 2.0 (same UpgradeCode, delete the curly braces.
1. Install the bundle v2.0

* Describe the behavior you expected and how it differed from the actual behavior.
- Actual: Both versions of the bundle are installed on the target machine
- Expected: Only version v2.0 to be installed

It seems that related bundles are detected using string-compare of the BundleUpgradeCode rather than GUID-compare.

**Comment by barnson** [comment]
The compiler normalizes that GUID so the manifests are the same. Can you attach log files showing the initial install and upgrade?

**Comment by barnson** [comment]
Need logs to further investigate.

**Comment by nirbar** [comment]
Well... it doesn't reproduce now.

**Comment by nirbar** [comment]
I managed to reproduce the issue-
When version 1.0.0 has the UpgradeCode available to the compiler it is normalized to upper case and with curly braces.
Then for version 2.0.0, if the UpgradeCode is provided as a linker variable then the GUID isn't normalized.

Attached a solution that reproduces the issue.
[Bootstrapper-GUID-style.zip](https://github.com/wixtoolset/issues/files/3381325/Bootstrapper-GUID-style.zip)

**Comment by barnson** [comment]
http://www.joyofsetup.com/2008/07/17/beware-localization-variables/

**Comment by barnson** [comment]
Normalize in backend.

**Comment by rseanhall** [comment]
This wasn't actually fixed. The compiler also puts the `UpgradeCode` into a `WixRelatedBundleSymbol`, which is the information that is actually written to the manifest. This also goes back to our discussion earlier about the Bundle element's `UpgradeCode` not being special, making it suspicious that there should even be an `UpgradeCode` available on the `WixBundleSymbol`.
