### ISSUE TITLE
Official 3.14 release date

### ISSUE THREAD

**Issue by nekobul** [wixtoolset/issues#6010]
Hi Guys,

I was trying to find a better place to ask the question and I'm sorry if this is not the right way. The question is general - when is version 3.14 planned for an official release? Based on my understanding 3.14 includes support for VS 2019. I hope it is coming very soon because we have customers now asking for VS 2019 support. Thank you!

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
