### ISSUE TITLE
wix4 has no documentation

### ISSUE THREAD

**Issue by wjk** [wixtoolset/issues#6012]
Quite simply, wix4 has absolutely no documentation on wixtoolset.org. It has been listed as "coming soon" for many, many years now. For this reason, I (and presumably many other projecs, including .NET Core itself) have remained on wix3 even though it is supposedly deprecated in favor of wix4. Furthermore, the two versions are different enough that attempting to translate the wix3 instructions over to wix4 as-is results in a broken build. If wix4 is indeed the future, I would appreciate being able to know how to use it. Thanks for looking into this!

**Comment by robmen** [comment]
WiX v4 is under active development. If you'd like to follow the status of the project, I highly recommend following the WiX Online Meetings ([FireGiant summarizes](https://www.firegiant.com/blog/) them so you don't have to watch if time is an issue).

If you'd like to get involved improving WiX v4 coding velocity, join the wix-devs mailing list and look to get involved. There is plenty left to accomplish before WiX v4 is ready for general use.
