### ISSUE TITLE
Accessibility Issue with Combo box

### ISSUE THREAD

**Issue by nirsingh** [wixtoolset/issues#6013]
This is a bug :-

* Which version of WiX are you building with?  -- 3.10.0.1208

* Which version of Visual Studio are you building with (if any)? -- Visual Studion 2013

* Which version of .NET are you building with? -- .net 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on? -- Windows Server 2016

* Describe the behavior you expected and how it differed from the actual behavior.

We have WIX .msi installer, and it has a combo box defined like this: 
            <Control Id="ActionDomainCombo" Type="ComboBox" X="200" Y="200" Width="140" Height="65" Property="ACTIONSDOMAIN" Sorted="no" ComboList="yes">
                <Condition Action="hide">
<![CDATA[ACTIONS_USE_COMPUTER_ACCOUNT=1]]>
</Condition>
                <Condition Action="show">
<![CDATA[ACTIONS_USE_COMPUTER_ACCOUNT=0]]>
</Condition>
            </Control>

We are trying to access/use the combo box via keyboard. 
1.            Pressing the TAB user reaches to the combo box. 
2.            User presses ALT+Down key to open the combo box. The combo box gets opened. 
3.            Now the user presses Up/Down Key to navigate the choices in the combo box. 

Expected Result: 
Using Up/down arrow, list item should be selected and should not close the dropdown. 
Pressing enter should select the list item and should close the DropDown. 

Actual Result: 
Drop down is getting closed with Up/down arrow and Item is automatically selected as value. 

This behavior of the combobox is different from the normal standard behavior of the Windows ComboBox. 
Is it by-deign in WIX? 
Is there any way to get the expected behavior from the combo box?

**Comment by barnson** [comment]
MSI is in charge of the internal UI behavior; WiX just builds the package.
