### ISSUE TITLE
Visual Studio 2019 support (v16.1.0)

### ISSUE THREAD

**Issue by davidnmbond** [wixtoolset/issues#6017]
The Visual Studio 2019 supported v16.0.0, but does not support v16.1.0 (latest stable)

**Comment by barnson** [comment]
We need way more information than this. Please provide the data requested in the issue template and include more details, like logs.

**Comment by davidnmbond** [comment]
@barnson - Opening a solution with .wixproj projects worked fine in VS 2019 16.0.  In VS 2019 16.1, those projects are shown as not supported and do not load.  I'm not sure what logs would be available when a project does not open in Visual Studio, but will provide what I can!

**Comment by tan-force** [comment]
I had that problem with 16.0, but I haven't seen it for some time now. Works fine for me in 16.1 and 16.2 preview too.

**Comment by barnson** [comment]
Working for the triage team on 16.1.2.
