### ISSUE TITLE
HeatDirectory document

### ISSUE THREAD

**Issue by atwayne** [wixtoolset/issues#6020]
The document of HeatDirectory task implies that it accepts more than one directory

|Parameter | Description|
|-- | --|
|Directory | Required item group parameter.**The list of directories to harvest.**|

The description is wrong as HeatDirectory doesn't take more than one directory

https://wixtoolset.org/documentation/manual/v3/msbuild/task_reference/heatdirectory.html

**Comment by BMurri** [comment]
Actually, because of the way msbuild works, the task does accept multiple directories. Due to msbuild task batching, msbuild will pass one Directory at a time to the HeatDirectory task and thus the task will pass one directory at a time to the harvesting tool.

You can load up as many non-identical values in the Directory item you wish and call the target just one time and it all works perfectly.

**Comment by atwayne** [comment]
Thanks... I did some test and it doesn't look like it's working as expected:
```
<ItemGroup>
      <Directory Include="$(SolutionDir)First\"/>
      <Directory Include="$(SolutionDir)Second\"/>
</ItemGroup>

<HeatDirectory OutputFile="Dependencies.wxs"
                   Directory="@(Directory)"
```
Then I have the following error message in output
```
16>C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe dir "\PATH\TO\First\;\PATH\TO\Second" 
16>heat.exe(0,0): error HEAT0001: The given path's format is not supported.
```
Maybe I did it wrong but it looks like the HeatDirectory task combines all the paths and pass it as a single parameter to the heat tool, and then a failure...

**Comment by BMurri** [comment]
Each directory usually needs a unique DirectoryRefId, and you didn't supply any.


      <ItemGroup>
        <DirectoryItem Include="$(SolutionDir)First\">
            <DirectoryRefId>First</DirectoryRefId>
        <DirectoryItem>
        <DirectoryItem Include="$(SolutionDir)Second\">
            <DirectoryRefId>Second</DirectoryRefId>
        <DirectoryItem>
      </ItemGroup>

**Comment by BMurri** [comment]
We should be discussing this on wix-users rather than here. If on wix-users it's determined that a bug exists, you would then be directed to open the issue with all the pertinent information as spelled out in the template you erased.

**Comment by BMurri** [comment]
The documentation mentions ComponentGroupName in the context of multiple directories. This use case is directly covered in the documentation. Please close this issue.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
