### ISSUE TITLE
Unable to extract engine.exe from 64 bit bootstrapper exe using Insignia v3.11 

### ISSUE THREAD

**Issue by julieallentimewatch** [wixtoolset/issues#6022]
* Which version of WiX are you building with?

> v3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2015 Version 14.0.23107.0 D14REL

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> WiX Toolset Visual Studio Extension version 0.9.21.62588

* Which version of .NET are you building with?

> Version 4.6.2

* Describe the problem and the steps to reproduce it.

I've been creating a 32 bit Wix bootstrapper exe for installs for a number of years.
I've recently had to create a 64 bit version of the installer.
I run a batch file to sign the bootstrapper exe as follows

"C:\Program Files (x86)\WiX Toolset v3.11\bin\insignia.exe" -ib OutlookTimeSetup64.exe -o engine.exe
"C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" sign /a /tr http://timestamp.globalsign.com/?signature=sha2 /td SHA256 "engine.exe"
"C:\Program Files (x86)\WiX Toolset v3.11\bin\insignia.exe" -ab engine.exe OutlookTimeSetup64.exe -o OutlookTimeSetup64.exe
"C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" sign /a /tr http://timestamp.globalsign.com/?signature=sha2 /td SHA256 "OutlookTimeSetup64.exe"

However I get the following message after running the first line with the 64 bit version
Insignia.exe : error ISNG0001 : Failed to copy engine out of bundle.
Exception Type: System.InvalidOperationException

Stack trace:
  at Microsoft.Tools.WindowsInstallerXml.Inscriber.InscribeBundleEngine(String bundleFile, String outputFile)
  at Microsoft.Tools.WindowsInstallerXml.Tools.Insignia.Run(String[] args)

I've search the Wix Issues database but couldn't find anything specific to 64 bit.
I've also googled the problem to no avail.
I'm hoping it's a simple solution to the problem.

**Comment by julieallentimewatch** [comment]
Error code should be INSG0001

**Comment by BMurri** [comment]
There are just enough differences between PE32 and PE32+ (having to do with the sizes of some of the structures in the "optional header" that it doesn't surprise me if insignia is miscalculating something somewhere.

As we aren't currently building 64-bit bundles, I suspect that the entire codepath has not been recently validated.

**Comment by BMurri** [comment]
It should be an easy fix for someone who's fiddled with the structures in those filetypes before. I suspect insignia is looking at the wrong location for the NumberOfRvaAndSizes member

**Comment by barnson** [comment]
Bundles are always 32-bit -- there's only the bin\x86\burn.exe stub today.

**Comment by rseanhall** [comment]
I assume this would be done as part of 64-bit burn - #4579
