### ISSUE TITLE
Wix boostrapper should provide Windows build number as variable

### ISSUE THREAD

**Issue by jozefizso** [wixtoolset/issues#6026]
* Describe the scenario and benefits that the feature supports.

> In some cases, we need to detect the Windows 10 build number in the installer. This is useful when installer bundles .NET 4.7 which is not supported on old Windows 10 releases like 1507. Installation of .NET would end with strange error like *0x800713ec - Asia*
>
> With a new **WindowsBuildNumber** internal property, we could provide a much better user experience as we could block installation on old Windows.

* Describe how you're accomplishing the feature today (if possible).

> It's almost impossible to detect Windows 10 build number now from the burn bootstrapper.

* Describe what you'd like the new feature to do.

> Burn will create an internal variable **WindowsBuildNumber**, similar to **VersionNT** and it will set it to `RTL_OSVERSIONINFOEXW.dwBuildNumber` value.

**Comment by barnson** [comment]
Merged. Thanks!

**Comment by forderud** [comment]
Sorry for my ignorance, but is it possible to use the new `WindowsBuildNumber` variable in `Condition` check for minimal Win10 version during MSI installation?

I've currently implemented a Win10 version check by comparing against the `SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentBuildNumber` registry key. However, it would be much simpler if I could instead compare more directly against WindowsBuildNumber or similar.

**Comment by jozefizso** [comment]
> Sorry for my ignorance, but is it possible to use the new `WindowsBuildNumber` variable in `Condition` check for minimal Win10 version during MSI installation?

This property was added to the burn bootstrapper which is the EXE application running the installation. You can pass this variable into the MSI you are installing using the bootstrapper.

If you have standalone MSI, this property is not available there.

**Comment by forderud** [comment]
Thanks for the clarification @jozefizso. Do you then know of a simpler way of implementing a Win10 1809 (or similar) check in a MSI installer, or is a registry check against `SOFTWARE\Microsoft\Windows NT\CurrentVersion\CurrentBuildNumber` the most straight-forward way?

**Comment by jozefizso** [comment]
@forderud there is no such built-in variable in MSI so you must read the value from the system manually.

**Comment by glen-nicol** [comment]
Can I get some further guidance on how to do what @forderud wanted? I have a v4 MSI installer that I want to limit to Windows 10 1803 or newer. I have the following in my package element:

```xml
<Property Id="WINDOWSBUILDVERSION">
  <RegistrySearch Id="WINDOWSBUILDVERSIONSearch"
                  Root="HKLM"
                  Key="SOFTWARE\Microsoft\Windows NT\CurrentVersion"
                  Name="CurrentBuildNumber"
                  Type="raw" />
</Property>

<Launch Condition="(WINDOWSBUILDVERSION &gt;= 17134)" Message="This application requires Windows 10 1803 or newer."/>
```

This doesn't work. I assume because the registry search is done after the launch condition is checked.

NOTE: I know that i also need to check VersionNT >= 603. I have that in a separate `Launch` tag.

**Comment by forderud** [comment]
The following approach seem to work fine for me:
```
<Property Id="WINDOWSBUILDNUMBER" Secure="yes">
    <RegistrySearch Id="BuildNumberSearch" Root="HKLM" Key="SOFTWARE\Microsoft\Windows NT\CurrentVersion" Name="CurrentBuildNumber" Type="raw" />
</Property>
<Launch Condition="Installed OR (WINDOWSBUILDNUMBER &gt;= 19044)" Message="This application require Windows 10 version 21H1 (build 19044) or newer." />
```

It would be nice with a more elegant way of performing this check though..

**Comment by glen-nicol** [comment]
Thanks for that, your version works! The only functional difference I see is your included `Secure="yes"`. I don't fully understand what that attribute does.
