### ISSUE TITLE
The 'Language' attribute is invalid

### ISSUE THREAD

**Issue by eugeniomiro** [wixtoolset/issues#6027]
I'm creating a new setup project under Visual Studio 2019, and I added a variable for the Language
The project still compiles, but there's a green squiggly with a warning with the following message

![image](https://user-images.githubusercontent.com/6075/59554319-9ed2b500-8f77-11e9-8018-ad21902f2d81.png)

Is this something that needs to be fixed?
Am I doing anything wrong?

Regards

**Comment by barnson** [comment]
That's Intellisense not liking your preprocessor variable

**Comment by eugeniomiro** [comment]
Sorry @barnson, but that's not it.
It's not talking about my variable, it's talking about the content of the attribute value, I can change the variable name and the message remains the same...
![image](https://user-images.githubusercontent.com/6075/59555676-7f925280-8f8c-11e9-96c4-2bd3245a9bd6.png)

**Comment by barnson** [comment]
That's Intellisense not liking **the presence** your preprocessor variable.

**Comment by eugeniomiro** [comment]
I can see that, but why is it only that way with the language and not with the UpgradeCode or the Name. Those are attributes too and they accept variables as content.
Anyway, my idea was trying to help, I hope somebody else cares about it, thank you.
