### ISSUE TITLE
ComponentInstallation.Path throws OverflowException 

### ISSUE THREAD

**Issue by manison** [wixtoolset/issues#6029]
* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> VS2017

* Which version of .NET are you building with?

> 4.8

* Describe the problem and the steps to reproduce it.

> When using the `ComponentInstallation` class from the `Microsoft.Deployment.Installation` assembly to obtain a component path the `Path` property getter throws `OverflowException` if the specified component is not installed.
```cs
var component = new ComponentInstallation(componentId);
string path = component.Path;
```
> This is because `MsiLocateComponent` return value is declared as `uint` and is casted to (signed) enum type `InstallState`. When the component is not installed, the return value from the native function is `INSTALLSTATE_UNKNOWN`, which is -1 (or 0xFFFFFFFF when treated as `uint`). This value cannot be casted to `int` without overflow. Since the assembly is complied with over/underflow runtime checks enabled this throws the `OverflowException`.

* Describe the behavior you expected and how it differed from the actual behavior.

> The `Path` property getter should return `null` if _the component is not available_ (as specified in the doc comment). (Or, since the comment is not clear, it may possibly throw `ArgumentException` if _an unknown product or component was specified_.)

**Comment by VolkerGa** [comment]
The overflow exception itself seems to be related to WiX3 only. I have not been able to reproduce it with current WiX4. Seems that DTF in latest WiX does not use `WixBuild.csproj.props` any longer which did set `CheckForOverflowUnderflow`.
However the return type of `WixToolset.Dtf.WindowsInstaller.MsiLocateComponent()` should be a signed int  to fit into the `InstallState` enum. I will create a small PR for WiX4 to change the return type. The same should work for WiX3 as well if desired.
Any thoughts?

**Comment by rseanhall** [comment]
Since this was a simple fix, I'll let triage decide whether this would be accepted in v3.
