### ISSUE TITLE
Fullwidth forms double quotes can't be displayed correctly on BootStrapper screen

### ISSUE THREAD

**Issue by burkdu** [wixtoolset/issues#6030]
When fullwidth forms double quotes（“”） is defined in HyperlinkLocaleTheme.wxl it can't be displayed correctly on BootStrapper screen. But change it to halfwidth forms double quotes（""） it can be displayed correctly. Is there any solution for this issue or it is just one bug of Wix?

Wix Toolset Version:3.11
Visual Studio Version: 2015

**Comment by BMurri** [comment]
Did you bring this up on wix-users?

What codepage do you set in your .wxl?

**Comment by burkdu** [comment]
Thanks for your response. Yes it is for wix-users and  code page is 2052.

**Comment by BMurri** [comment]
I still don't see your message on the wix-users mailing list, which is the correct place to discuss this. This will be my last message unless triage thinks there's an issue here.

I don't see any codepage 2052 on [Microsoft's official list of codepages](https://docs.microsoft.com/en-us/windows/desktop/Intl/code-page-identifiers). If a glyph isn't in the selected codepage, it can't be successfully used. If the codepage can't be found, my assumption is that ASCII will be used instead, which are limited to the original US typewriter character set (no fancy punctuation, no accents, no non-Latin characters, etc.).

**Comment by barnson** [comment]
We need more detail: What does your string look like? What are the results ("can't be displayed correctly" isn't descriptive)?

**Comment by burkdu** [comment]
The String is: ”XXXX” 
But it display as: ｜XXXX｜

**Comment by barnson** [comment]
That's not very useful. Please show your .wxl authoring and a screen shot of the results.
