### ISSUE TITLE
Extra space shown in error message for file not found

### ISSUE THREAD

**Issue by bhaskar-majumder** [wixtoolset/issues#6031]
* Which version of WiX are you building with?

> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Enterprise 2017 - 15.8.7

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.21.62588

* Which version of .NET are you building with?

> Microsoft .Net Framework 4.6.1 SDK
> Microsoft .Net Framework 4.6 Targeting Pack
> Microsoft .Net Framework 4.5.2 Multi-Targeting Pack (ENU)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Found this on all available systems running Win7 and Win10

* Describe the problem and the steps to reproduce it.

> Created an installer which contains a file component and this component is marked as `Vital="no" Compressed="no"`. While installing if the file is missing there is an error message shown, saying `Source file not found:`, which is correct. 
![image-2019-06-06-16-44-46-108](https://user-images.githubusercontent.com/42843976/59675560-1d7f5a80-91e3-11e9-9d99-1e70e6fcbe93.png)
The problem with this text is that it shows an extra space before the word `Verify`.

* Describe the behavior you expected and how it differed from the actual behavior.

> While trying to fix this I overrode the default strings `"Error1308" and "Error1311"` but it is not getting reflected.

**Comment by barnson** [comment]
Make sure your strings are in the `Error` table. Keeping the issue open if someone wants to update the .wxl strings in WixUIExtension.

**Comment by bhaskar-majumder** [comment]
Thanks for your reply. I already added these error strings in `Localization.wxl` file. Changing all other strings like `WelcomeDlgDescription` are getting reflected but changing `Error1308` and `Error1311` are not getting reflected. By `Error` table do you mean something else or it is the same `Localization.wxl` file.

**Comment by barnson** [comment]
Use Orca to look at the actual strings in your .msi.

**Comment by bhaskar-majumder** [comment]
Couldn't find the error string in the msi. But it contains all other strings.
```
  <String Id="FatalErrorTitle">{\WixUI_Font_Bigger}Setup failed</String>
  <String Id="MaintenanceTypeDlgTitle">{\WixUI_Font_Title}Change, repair or remove a previous installation?</String>
  <String Id="Error1308">Source file 111 not found: [2]. Verify that the file exists and that you can access it.</String>
  <String Id="Error1311">Source file 222 not found{{(cabinet)}}: [2]. Verify that the file exists and that you can access it.</String>
```
For example the first 2 strings from the above example are appearing in the msi but not the last 2.

**Comment by BMurri** [comment]
You do have `<UIRef Id="WixUI_ErrorProgressText">` in your authoring, correct?

**Comment by bhaskar-majumder** [comment]
> You do have `<UIRef Id="WixUI_ErrorProgressText">` in your authoring, correct?

Thanks @BMurri. That fixed the issue. I am using Wix for the first time and didn't knew that I needed to add that.
