### ISSUE TITLE
Relative path does not work in <WixToolPath>

### ISSUE THREAD

**Issue by liangming2003** [wixtoolset/issues#6032]
It’s strange that the following relative path does not work. 
`<WixToolPath>..\..\..\..\tools\wix311\</WixToolPath>`

c:\jenkins\workspace\tools\wix311\wix2010.targets(735,5): error MSB4062: The "ResolveWixReferences" task could not be loaded from the assembly c:\jenkins\workspace\tools\wix311\\..\\..\\..\\..\\tools\wix311\wixtasks.dll. Could not load file or assembly 'file:///c:\tools\wix311\wixtasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [c:\jenkins\workspace\HardShell-Dev\Hardshell\Hardshell 3\HardShellSetup\HardShellSetup.wixproj]

But the absolute path works.
`<WixToolPath>C:\jenkins\workspace\tools\wix311\</WixToolPath>`

Is there any limitation for relative path length? How to resolve this? Thanks.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
