### ISSUE TITLE
Rebuild solution fails because CleanReferencedProjects is not implemented

### ISSUE THREAD

**Issue by TripleEmcoder** [wixtoolset/issues#6034]
# Bug report

* Which version of WiX are you building with?

> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> 2019 16.1.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 0.9.28.58839

* Which version of .NET are you building with?

> 4.8.03752

## Context

Given the following solution structure:
- class library projects A, B
- WiX setup project S
- B references A
- S references A
- top level build order S, B as determined by MSBuild

## Actual behavior

When doing a Rebuild, the process fails both in Visual Studio and command-line MSBuild with a missing file when resolving references of project B. Running Clean then Build separately works fine.

This is possibly caused by target CleanReferencedProjects being not implemented, as visible here: https://github.com/wixtoolset/wix3/blob/bda1c281cb0349007d767d5404d6da87076d7d94/src/tools/WixTasks/wix.targets#L2680 and on a local install of WiX.

The chain of events is the following, as evidenced by MSBuild Log Viewer:
-- Rebuild S 
---- doesn't run Clean A (because CleanReferencedProjects is commented out, however simply uncommenting doesn't seem to work either)
---- runs Build A (and marks target as done)
---- then self: Clean S, Build S
-- Rebuild B 
---- runs Clean A (because not run before and not marked) 
---- skips Build A (beacuse marked as done)
---- then self: Clean B, Build B (fails with missing A.dll)

## Expected behavior

Target Clean propagates down the reference tree as in other projects allowing a solution-wide Rebuild to succeed.

**Comment by barnson** [comment]
This is fixed in WiX v4 with the move to Microsoft.Common.targets.

**Comment by TripleEmcoder** [comment]
Great to hear that! I haven't been able to find any timeline for that release though?
