### ISSUE TITLE
WiX Visual Studio Code Extension

### ISSUE THREAD

**Issue by VectorBCO** [wixtoolset/issues#6045]
## Feature requests

If this issue is a feature request:

*In a big companies could be exist some bureaucracy processes which disallow use Visual Studio (payable versions). And license agreement for Visual Studio Community restricts use it in a big companies. So small devops teams often use Visual Studio Code which did not have extension for WiX. In this case this small teams have only one option: use WiX as a commandline utility, which not so comfortable as a gui tool

* Describe how you're accomplishing the feature today (if possible).

Commandline functionality helped us, but it`s not so comfortable as it could be.

* Describe what you'd like the new feature to do.

I`d like to get extension for Visual Studio Code as they was created for Visual Studios pro\community

**Comment by barnson** [comment]
This is a huge feature that we'd welcome if someone wanted to do the work. It's not something the team is taking on.

**Comment by farukshin** [comment]
That would be a useful feature.

**Comment by tol-va** [comment]
It frustrating this doesn't exist despite how populate VS Code has become.
