### ISSUE TITLE
Wix Editors Doesnt work

### ISSUE THREAD

**Issue by abrantie1z** [wixtoolset/issues#6046]
Am using Release Candidate 2 of WiX Toolset Visual Studio 2019 Extension. When i add a wix setup project and right-click the project  and Select View Wix Editor, i get a message am using a 7 day preview and thats it. Nothing happens

**Comment by barnson** [comment]
That sounds like it's from a commercial extension. The WiX Visual Studio Extension doesn't have that menu item or preview message.
