### ISSUE TITLE
Not possible to hide element from Windows narrator

### ISSUE THREAD

**Issue by rhulam1** [wixtoolset/issues#6047]
If this issue is a bug:

Windows narrator reads unnecessary element and it's not possible to set role to this element: 
` <Control Type="Line" />`

* Which version of WiX are you building with?

3.7.1224.1

* Which version of Visual Studio are you building with (if any)?

MsBuild 12.0.21005.35
ToolsVersion 12.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows Server 2012R2. Version 6.3(Build 9600)

* Describe the problem and the steps to reproduce it.

Create setup with ` <Control Id="BottomLine" Type="Line" />` element and turn windows narrator on. It will read this control and it's not possible disable it.

* Describe the behavior you expected and how it differed from the actual behavior.

It should be possible to hide element from narrator reading

**Comment by barnson** [comment]
That's functionality is controlled by Windows Installer, not WiX.
