### ISSUE TITLE
Wix Toolset Visual Studio 2019 Extension fails to install with invalid certificate

### ISSUE THREAD

**Issue by shanepowell** [wixtoolset/issues#6053]
When trying to install Wix Toolset Visual Studio 2019 Extension from the extensions manager it fails on my developer machine with a invalid certificate error.

I assume this is a machine setup issue but I have no idea where to look for the issue.

[dd_VSIXInstaller_20190717085453_68c0.log](https://github.com/wixtoolset/issues/files/3403217/dd_VSIXInstaller_20190717085453_68c0.log)

**Comment by barnson** [comment]
You need to update certificates:

    17/07/2019 8:55:01 AM - 		(PartialChain)      : A certificate chain could not be built to a trusted root authority.
    17/07/2019 8:55:01 AM - 		(RevocationStatusUnknown): The revocation function was unable to check revocation for the certificate.
    17/07/2019 8:55:01 AM - 		(OfflineRevocation) : The revocation function was unable to check revocation because the revocation server was offline.

Maybe this? https://support.microsoft.com/en-us/help/2813430/an-update-is-available-that-enables-administrators-to-update-trusted-a

**Comment by shanepowell** [comment]
Can you tell me which CA certificate it can't find?  If I know that I can track down why it's not being updated (or install it manually).

**Comment by barnson** [comment]
The cert path is `DigiCert High Assurance EV Root CA` to `.NET Foundation Projects Code Signing CA`.

**Comment by shanepowell** [comment]
I have verified that I already have that certificate installed on my machine in my trusted root store.  I have also verified that it's the same certificate as can be downloaded from here:

https://www.digicert.com/digicert-root-certificates.htm
DigiCert High Assurance EV Root CA 
Valid until: 10/Nov/2031
Serial #: 02:AC:5C:26:6A:0B:40:9B:8F:0B:79:F2:AE:46:25:77
Thumbprint: 5FB7EE0633E259DBAD0C4C9AE6D38F1A61C7DC25

The machines current date/time are set correctly so it's within the valid date range.

So I don't think it's the root certificate that is the problem.

Is there any intermediate certificates in the certificate chain?  What does the issuer of the signing certificate say?

**Comment by barnson** [comment]
Sorry, I don't know how to get that info out of the VSIX. VSIX installation is wholly controlled by Visual Studio and doesn't give us any option to ignore the signature failure. We've been directed to send people to this forum to report problems: https://developercommunity.visualstudio.com

**Comment by toreaurstadboss** [comment]
I know this issue was closed, but I could not install Votive 2017 or Votive 2019 today for a solution of mine where I have a .wixproj project inside. It was this same type of certificate error. 

I managed to update my (root) certificates by synchronizing with Windows Update again, on a Windows 10 computer. I first run this command:
mkdir c:\certs #temporary folder where the certificates will be installed/updated
cd c:\certs 
certutil.exe -generateSSTFromWU roots.sst
$sstStore = ( Get-ChildItem -Path C:\certs\roots.sst )
$sstStore | Import-Certificate -CertStoreLocation Cert:\LocalMachine\Root

After doing this synchronization / refresh of (root) certificates, installing Votive 2017 or Votive 2019 installation worked again.

**Comment by carlreinke** [comment]
For anyone else who needs the certificates:

**DigiCert High Assurance EV Root CA.cer**
```
-----BEGIN CERTIFICATE-----
MIIDxTCCAq2gAwIBAgIQAqxcJmoLQJuPC3nyrkYldzANBgkqhkiG9w0BAQUFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTMxMTExMDAwMDAwMFowbDEL
MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3
LmRpZ2ljZXJ0LmNvbTErMCkGA1UEAxMiRGlnaUNlcnQgSGlnaCBBc3N1cmFuY2Ug
RVYgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbM5XPm
+9S75S0tMqbf5YE/yc0lSbZxKsPVlDRnogocsF9ppkCxxLeyj9CYpKlBWTrT3JTW
PNt0OKRKzE0lgvdKpVMSOO7zSW1xkX5jtqumX8OkhPhPYlG++MXs2ziS4wblCJEM
xChBVfvLWokVfnHoNb9Ncgk9vjo4UFt3MRuNs8ckRZqnrG0AFFoEt7oT61EKmEFB
Ik5lYYeBQVCmeVyJ3hlKV9Uu5l0cUyx+mM0aBhakaHPQNAQTXKFx01p8VdteZOE3
hzBWBOURtCmAEvF5OYiiAhF8J2a3iLd48soKqDirCmTCv2ZdlYTBoSUeh10aUAsg
EsxBu24LUTi4S8sCAwEAAaNjMGEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB/wQF
MAMBAf8wHQYDVR0OBBYEFLE+w2kD+L9HAdSYJhoIAu9jZCvDMB8GA1UdIwQYMBaA
FLE+w2kD+L9HAdSYJhoIAu9jZCvDMA0GCSqGSIb3DQEBBQUAA4IBAQAcGgaX3Nec
nzyIZgYIVyHbIUf4KmeqvxgydkAQV8GK83rZEWWONfqe/EW1ntlMMUu4kehDLI6z
eM7b41N5cdblIZQB2lWHmiRk9opmzN6cN82oNLFpmyPInngiK3BD41VHMWEZ71jF
hS9OMPagMRYjyOfiZRYzy78aG6A9+MpeizGLYAiJLQwGXFK3xPkKmNEVX58Svnw2
Yzi9RKR/5CYrCsSXaQ3pjOLAEFe4yHYSkVXySGnYvCoCWw9E1CAx2/S6cCZdkGCe
vEsXCS+0yx5DaMkHJ8HSXPfqIbloEpw8nL+e/IBcm2PN7EeqJSdnoDfzAIJ9VNep
+OkuE6N36B9K
-----END CERTIFICATE-----
```

**NET Foundation Projects Code Signing CA.cer**
```
-----BEGIN CERTIFICATE-----
MIIEkTCCA3mgAwIBAgIQB7BBjaUeFIwzG7zetxODIzANBgkqhkiG9w0BAQsFADBs
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j
ZSBFViBSb290IENBMB4XDTE4MDQyNzEyNDE1OVoXDTI4MDQyNzEyNDE1OVowWjEL
MAkGA1UEBhMCVVMxGDAWBgNVBAoTDy5ORVQgRm91bmRhdGlvbjExMC8GA1UEAxMo
Lk5FVCBGb3VuZGF0aW9uIFByb2plY3RzIENvZGUgU2lnbmluZyBDQTCCASIwDQYJ
KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMEKr+GiNAiNtF3mKk02ZsqMbEkIHAgR
kJ157n27gy4QAehqEzQex7hITUkvH7VfusqvBs7Qc2ACdJQC3QY1sqTHy+Odf/OA
DuWYmQd1ezAdrsYFqHFdXpA3blPW5tUOPI5keElZCyLQvqEDvxSANkgbnVWVL2Cn
giUuUYvYm1ey2uKKOwSQoRYj/Lkfr9zlN93YJuQQYVprYeKE8qttswnz9zTuoAVh
CDxUeUvinHn1E2Jp9qOyL4b8cybDAqzR9W8YcDsjJfg0HHVolT7iQSgzjv4QCiMQ
RuIuq8kGAWinYQ4GgDUgopNFIGWrM/EIJfJ9AO9/nSEj7pg/C/+JncsCAwEAAaOC
AT8wggE7MB0GA1UdDgQWBBTLXJOuiJv+Q29WUFICbXj8rOGxWjAfBgNVHSMEGDAW
gBSxPsNpA/i/RwHUmCYaCALvY2QrwzAOBgNVHQ8BAf8EBAMCAYYwEwYDVR0lBAww
CgYIKwYBBQUHAwMwEgYDVR0TAQH/BAgwBgEB/wIBADA0BggrBgEFBQcBAQQoMCYw
JAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmRpZ2ljZXJ0LmNvbTBLBgNVHR8ERDBC
MECgPqA8hjpodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRIaWdoQXNz
dXJhbmNlRVZSb290Q0EuY3JsMD0GA1UdIAQ2MDQwMgYEVR0gADAqMCgGCCsGAQUF
BwIBFhxodHRwczovL3d3dy5kaWdpY2VydC5jb20vQ1BTMA0GCSqGSIb3DQEBCwUA
A4IBAQCzRsSk8+oKunJTBdNRowt0Zif2QKCtVe68JKjpGNyQ5fvr9ReCqxVhM0vD
G2bCP6eFt9RJHrWs6Dcctt0U9Mw7Lya8BAt0fvzEXZAe2k3nLGJjHjB4LVK5d8RD
txbm50NJChFPxwQk3YUdeBrEBHHEEBOoKxVZYJa3sPhc3oVlLt0lEBKfbfolqV/y
n74g1sdB9Ws4pTF9eZcyVMSu5As5n5a5OYwjgoyqoTnRiaEKrLZsD/tO6lztfG3A
sxAvdPD/k2JIdM/YFa5Y+7clvSvcz1TyWbC0Wgaf0IzHB+uaPWNYQ9blrRUGJmxG
JE9Svbblx7UGMdUaX/3QvDW5eIrp
-----END CERTIFICATE-----
```

**WiX Toolset (.NET Foundation).cer**
```
-----BEGIN CERTIFICATE-----
MIIFlzCCBH+gAwIBAgIQDV75AwPCKAN33+BNdOIIYTANBgkqhkiG9w0BAQsFADBa
MQswCQYDVQQGEwJVUzEYMBYGA1UEChMPLk5FVCBGb3VuZGF0aW9uMTEwLwYDVQQD
EyguTkVUIEZvdW5kYXRpb24gUHJvamVjdHMgQ29kZSBTaWduaW5nIENBMB4XDTE5
MDQwMzAwMDAwMFoXDTIyMDQwNzEyMDAwMFowgZIxFDASBgNVBAUTCzYwMyAzODkg
MDY4MQswCQYDVQQGEwJVUzELMAkGA1UECBMCd2ExEDAOBgNVBAcTB1JlZG1vbmQx
JjAkBgNVBAoTHVdpWCBUb29sc2V0ICguTkVUIEZvdW5kYXRpb24pMSYwJAYDVQQD
Ex1XaVggVG9vbHNldCAoLk5FVCBGb3VuZGF0aW9uKTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAK2+TLBv+GiRDE3XUnsJr3KvcGWoBS4l+KPWvA6VuEaJ
9iCNkzZFt9ABm3JQfRY04jJk6RVKsp6YXYy89Dr8rGiBYBIfWXgBM4xil7Gll8vq
o/6t/XchfXLkNFK84unaaKENhpZNP6rmvSpcbIR4nfYKBI7jhjcrtBjio4ienCKo
eM3M6od+vR/cTEaS6gKUEM1DERn58RQHV6SFRas12mTob4vlt5qaPwTGSfjjIMGJ
+7aG7RYtGhT/F/OdlBqBanvONKykKtHKlyoFeuIml8tzK/A69h7J2i49koXUEja5
+toQ6JcUB6O05VbAlbwhSIxyigNPit0Yr0TR6T5a3u0CAwEAAaOCAh4wggIaMB8G
A1UdIwQYMBaAFMtck66Im/5Db1ZQUgJtePys4bFaMB0GA1UdDgQWBBS5fu56Ulan
hfZU//LnCFm9p+wFsjA0BgNVHREELTAroCkGCCsGAQUFBwgDoB0wGwwZVVMtV0FT
SElOR1RPTi02MDMgMzg5IDA2ODAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYI
KwYBBQUHAwMwgZkGA1UdHwSBkTCBjjBFoEOgQYY/aHR0cDovL2NybDMuZGlnaWNl
cnQuY29tL05FVEZvdW5kYXRpb25Qcm9qZWN0c0NvZGVTaWduaW5nQ0EuY3JsMEWg
Q6BBhj9odHRwOi8vY3JsNC5kaWdpY2VydC5jb20vTkVURm91bmRhdGlvblByb2pl
Y3RzQ29kZVNpZ25pbmdDQS5jcmwwTAYDVR0gBEUwQzA3BglghkgBhv1sAwEwKjAo
BggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAIBgZngQwB
BAEwgYQGCCsGAQUFBwEBBHgwdjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGln
aWNlcnQuY29tME4GCCsGAQUFBzAChkJodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5j
b20vTkVURm91bmRhdGlvblByb2plY3RzQ29kZVNpZ25pbmdDQS5jcnQwDAYDVR0T
AQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEAQgphBcKZOHq+IecqgCwMQyzEf8ki
zmKNj0deUfO36u2sgUb2AhTDItEHxg+rHsBIW3+nVQF90/nsjgjw4i+bCOzs5qE4
OBi5LP+tEbUc+goNOgvwRsVT1Lfn09vurEjG7usw7vSXsyUoq4qIzhpH4XJPeYkn
QLMynv1zZVa60redOSml1tk5C1/x2pLKhuObjFlhErdlW9PynIVhMtZSdxirjLLt
Q/8Dn+hHi4/gSrayL34+9JdmmDV/PvQbEbxTXak+BDbUqTsRpC4pub4N5sh2RukJ
CzFtetqVJBqMNODN8VqurDusiXADpIgM02BiWBEVWqs78bcSpIk8VmSXyg==
-----END CERTIFICATE-----
```

I only had to install the *.NET Foundation Projects Code Signing CA* certificate into the *Intermediate Certificate Authorities* store to get Votive to install.
