### ISSUE TITLE
Wix remains unavailable in VS 2019 after install of extension

### ISSUE THREAD

**Issue by geedsen** [wixtoolset/issues#6054]
Using VS 2019 Enterprise, latest version 16.1.6
Using latest toolkit (everything worked fine in VS 2017) btw.
Opening the project in VS2019 says the Bootstrapper application is incompatible. See attachment.
![Untitled](https://user-images.githubusercontent.com/1316595/61521480-90f9cf00-aa10-11e9-9625-b1e8f3ae7450.png)

**Comment by SylwesterZarebski** [comment]
Weird thing... after install and multiple restart of VS 2019 16.2.0, extension starts working...
Maybe there was a problem with running VS 2017 in first tries.

**Comment by geedsen** [comment]
Not for me, still nothing, it says 'application is not installed'. I do wonder if there is any support at all actually looking at the number of reactions here...

**Comment by BMurri** [comment]
The community support is on the wix-users mail list, not on the GitHub issue tracker. I haven't seen this issue discussed there.

Having stated that, with all the recent changes to VSIX, we've been directed to send people with VSIX installation issues to request support from Microsoft's Visual Studio.

**Comment by geedsen** [comment]
The wix project was originally created in VS 2017 (or might even be an earlier version). So then I figured I could try to create a Wix project in VS2019. And actually that worked just fine. So then I started comparing the project file of the 2017 version with the new project.
The new wixproj starts like this

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" InitialTargets="EnsureWixToolsetInstalled" 
         xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>

The old one:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" InitialTargets="EnsureWixToolsetInstalled" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\packages\WiX.3.11.1\build\wix.props" Condition="Exists('..\..\packages\WiX.3.11.1\build\wix.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Co

So removing the <Import Project=....> line from the old project fixed the problem.
The project then loaded just fine.

**Comment by ChadBH** [comment]
Right clicking the .wixproj and clicking "Reload Project" fixed it for me.

**Comment by jkowalski0058** [comment]
Right clicking the .wixproj and clicking "Reload Project" fixed it for me.
