### ISSUE TITLE
Can't uninstall program install with MSI created with WIX

### ISSUE THREAD

**Issue by agentsofshield** [wixtoolset/issues#6057]
* Which version of WiX are you building with?

Wix Toolset v3.11.1.2318

* Which version of .NET are you building with?

4.7.03056

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10.0.17763
Windows 7 

* Describe the problem and the steps to reproduce it.

I created an MSI file to install osquery using the script provided by them https://github.com/osquery/osquery/blob/master/tools/deployment/make_windows_package.ps1
and installed it on some of my hosts, both Win7 and Win10.
Osquery did not show as an installed program in appwiz after running the MSI, although the service is installed and process is running regularly. When trying to use the MSI to uninstall (`osquery.msi /uninstall`) I saw the following message :
`This patch package could not be opened. Verify that the patch package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer patch package`
When trying to use the uninstall string I see this message:
`This action is only valid for products that are currently installed`

* Describe the behavior you expected and how it differed from the actual behavior.

The program is running as it should and installed everything as it should, but it doesn't show on the appwiz (as the original MSI does) and it can't be uninstalled showing the errors above.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
