### ISSUE TITLE
Cart item quantity selector NOT aligned with input field

### ISSUE THREAD

**Issue by ericqianli** [wixtoolset/issues#6058]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

Go to any site with a store, add some products to cart and go to the cart page. Notice that the quantity selector (the up and down arrows next to the product quantity) is not vertically centered in the input field. It sinks to the bottom of the field.

Example templates with 100% repro:
https://www.wix.com/website-template/view/html/1616?siteId=cfc939bd-a569-44c8-a5c9-00ed33a94743&metaSiteId=422ea116-7c62-4038-a550-a027d55fe99b&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fonline-store

https://www.wix.com/website-template/view/html/2226?siteId=ceff36c1-c9d5-4a36-9058-54dc93c1b2be&metaSiteId=d1c3e4a3-ce83-4f24-ae51-bbbb7d705958&originUrl=https%3A%2F%2Fwww.wix.com%2Fwebsite%2Ftemplates%2Fhtml%2Fonline-store

**Comment by barnson** [comment]
Wrong repo. You want https://support.wix.com/en/.
