### ISSUE TITLE
Files in Use does not show running application or window name

### ISSUE THREAD

**Issue by sqeezy** [wixtoolset/issues#6059]
* Which version of WiX are you building with?

> 3.11.2318.0

* Which version of Visual Studio are you building with (if any)?

> built from commandline via cake

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> 4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10/7 different builds each

* Describe the problem and the steps to reproduce it.

When upgrading/uninstalling a package installed with wix while the main application of that package is still running, the 'Files in Use' dialog does not show the correct application name or window title.
Instead it shows 'A'.

*Steps to reproduce:*

1. Install package in version X
2. Open installed application with name 'App.exe' (the window title is an alphanumeric string with whitespaces)
3. Start bootstrapper for package in version X+1 and try to install

* Describe the behavior you expected and how it differed from the actual behavior.

*Expected:*

'Files in Use' dialog shows application name or window title of the open application.

*Actual:*

Shows 'The following applications are using files that need to be updated: A'.

![FilesInUseBug](https://user-images.githubusercontent.com/4598603/61876118-6ade9e00-aeec-11e9-9b00-262e245ce30d.png)

**Comment by barnson** [comment]
Does the window title start with `A`? Are you using WixStandardBootstrapperApplication?

**Comment by creativbox** [comment]
See issue #5201
