### ISSUE TITLE
Wix Standard Bootstrapper and RemotePayload redirects to amazonaws.com fail

### ISSUE THREAD

**Issue by ghost** [wixtoolset/issues#6060]
* Which version of WiX are you building with?

> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

> 2019 (16.1.6)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 1903 64-bit Enterprise

* Describe the problem and the steps to reproduce it.

> Create a bootstrapper project with an ExePackage with RemotePayload. Set the DownloadLink to https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs927/gs927w32.exe or any other link that redirects to amazonaws.com?

* Describe the behavior you expected and how it differed from the actual behavior.

> The file should be downloaded when the bootstrapper is run, but it fails with 0x80070005 (Access Denied).
[Elephant_20190730112514.log](https://github.com/wixtoolset/issues/files/3446206/Elephant_20190730112514.log)

**Comment by barnson** [comment]
Burn issues a `HEAD` request, which can be configured in AWS to be unsupported.
