### ISSUE TITLE
Is it possible to called custumaction with admin privilege like deferred execution after InstallationFinalize ? 

### ISSUE THREAD

**Issue by kuldip1490** [wixtoolset/issues#6068]
I have been working on wixtoolset project. I am stuck at between after InstallationFinalize and execution "deferred", both are opposite.

My simple requirement  : Customaction called with deferred execution after InstallFinalize

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
