### ISSUE TITLE
Burn: HTTP to HTTPS redirects fail to download when IE is configured to warn on zone change.

### ISSUE THREAD

**Issue by jchoover** [wixtoolset/issues#6071]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> All 3.x and 4.x are impacted

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 7 and Windows 10

* Describe the problem and the steps to reproduce it.

> When WinINet/IE is configured to "Warn if changing between secure and non secure mode", burn will fail to download packages if the origional URL is HTTP but that URL redirects to HTTPS.

Log Ex:
[3ED4:3E20][2019-08-16T10:20:54]i338: Acquiring package: X, payload: X, download from: http://...
[3ED4:3E20][2019-08-16T10:20:54]e000: Error 0x80072f07: Failed to send request to URL: http://....msi, trying to process HTTP status code anyway.
[3ED4:3E20][2019-08-16T10:20:54]e000: Error 0x80072f76: Failed attempt to download URL: 'http://...' to: 'C:\Users\Y\AppData\Local\Temp\...'

0x80072f07 = WININET_E_HTTP_TO_HTTPS_ON_REDIR
A redirect request will change a non-secure to a secure connection

* Describe the behavior you expected and how it differed from the actual behavior.

> You should only get that error if Internet Explorer is configured to warn the user when changing between non-secure and secure connections.  Within Internet Explorer, go to Tools -> Internet Options -> Advanced -> Security and look for the "Warn if changing between secure and non secure mode" setting at the bottom of the form.  If that setting is checked, uncheck it and save the change.  Then try running the Bundle installer again.

As burn is downloading a installer, I don't see any security issues with a HTTP to HTTPS redirect. I would expect burn to download the payload as normal, and verify it's hash.

Doing it up front seems to be simple, using InternetQueryOption for INTERNET_OPTION_SECURITY_FLAGS, then adding SECURITY_FLAG_IGNORE_REDIRECT_TO_HTTPS to the flags and assigning it back.

**Comment by puckrandi** [comment]
Diable http to https redirects

**Comment by barnson** [comment]
https://github.com/wixtoolset/dutil/pull/4
