### ISSUE TITLE
Splash Screen resizes on 4K monitor

### ISSUE THREAD

**Issue by MattHyman** [wixtoolset/issues#6072]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.14.1703.0

* Which version of .NET are you building with?
4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10

* Describe the problem and the steps to reproduce it.
1. Launch WiX bundle using 4K monitor
2. View Splash screen - the image starts at the right size, then jumps to smaller size after 1s. Splash screen is a BMP 750x550 with 24 bit depth.

**Comment by barnson** [comment]
Fixed in v4.
