### ISSUE TITLE
Using Lux with Wix 3.11

### ISSUE THREAD

**Issue by daveops1** [wixtoolset/issues#6073]
* Which version of WiX are you building with?

> (WiX version 3.11.1.2318)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio 2019 Community Edition version 16.2.3)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension 1.0.0.4)

* Which version of .NET are you building with?

> (.NET version 4.8.03752)

* Describe the problem and the steps to reproduce it.

> I am attempting to add a unit test to my .wxs source file which I am editing in Visual Studio 2019 Community Edition IDE.  I am creating it per the steps outlined at (https://wixtoolset.org/documentation/manual/v3/overview/lux.html):

`<Fragment>
    <lux:UnitTest CustomAction="CheckOpenDentalInstalled" Property="SIMPLE" Value="[INSTALLFOLDER]" Operator="equal" />
  </Fragment>`

However, I receive the following error when trying to build the Wix Setup Project in Visual Studio, as well as when attempting to run Candle.exe from the command prompt: `Not a valid source file; detail: 'lux' is an undeclared prefix.`

When I add the namespace declaration to the top of the .wxs source file, the error goes away and the source compiles:

Before:

`<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">`

After:
`<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:lux="http://schemas.microsoft.com/wix/2009/Lux">`

I follow steps to compile using candle with the -ext WixLuxExtension, it compiles to the .wxsobj.  However when I run lux.exe command against the compiled source, I receive the following error:

`lux.exe : error LUX8003 : No unit tests were found in given input files.`

Any insight into this would be greatly appreciated as I am attempting to add unit testing to my Custom Actions in WiX.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by daveops1** [comment]
Thank you very much for the quick feedback.  I will pose my issue there and see what comes of it.
