### ISSUE TITLE
How to Build Wix MSI File for multiple projects in same solution

### ISSUE THREAD

**Issue by Sumanthdv** [wixtoolset/issues#6078]
I have 13 projects in one solution which are integrated.
Now when i build the solution, it generates some binaries in bin/Release folder.
Now i want to generate an WIX MSI File which copies all the generated binaries into Installation Folder.

I have done this manually, by creating a seperate wix project and adding all the binaries to Installation Folder using File Tag.

Now my requirement is , i have add the Wix project in the same solution where my all 13 projects exists. When the entire  solution is build it should generate the MSI file taking the binaries generated from rest of the projects.

Is there anyway to do this ?
Thanks in Advance.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
