### ISSUE TITLE
Need separate SDK NuGet package for Wix Custom Action Development

### ISSUE THREAD

**Issue by phbarton** [wixtoolset/issues#6080]
* Describe the scenario and benefits that the feature supports.

We have Wix Custom Actions which support other parts of our installation. As such, we need the SDK assemblies in order to build them. The current Wix 3.11 NuGet package is a tools package and does not add the references to the SDK assemblies. By creating a separate SDK NuGet package, those references and build tasks/targets will automatically be added to the custom actions project. This allows for builds to occur in the CI/CD pipeline without having to install the Wix SDK on the agent prior to the build.

* Describe how you're accomplishing the feature today (if possible).

Currently, we are maintaining the needed assemblies in source control so that we can bring them onto the agent when the source code tree is built. Additionally, we've had to modify our targets files to add specific search paths for these assemblies in order to resolve the references.

* Describe what you'd like the new feature to do.

Provide a separate NuGet package for the Wix SDK which will add the necessary references and build targets so that development can occur without having to install all of the Wix onto the target system.

**Comment by robmen** [comment]
This is coming in WiX v4.

**Comment by phbarton** [comment]
Great! Thank you for the quick response. I do have a workaround wherein I add the reference to the assembly(ies) that I need, then modify the <HintPath> element of the project file to use the $(WixSdkPath) property. Though not optimal, it works-ish...
