### ISSUE TITLE
Download link broken for Visual Studio 2019 Extension

### ISSUE THREAD

**Issue by andyfisher100** [wixtoolset/issues#6082]
When clicking the link on the WiX toolset site to download the Visual Studio 2019 extension, you are redirected to the following page:
https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2019Extension

When clicking the download link on the page, the following XML error is displayed

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccountNotFound</Code>
<Message>
The specified account does not exist. RequestId:6941c0f1-f01e-005f-7344-751255000000 Time:2019-09-27T15:03:40.3522121Z
</Message>
</Error>`

the link in the browser when this error is displayed is the following:
https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2019extension/1.0.0.4/1563296438961/Votive2019.vsix

**Comment by robmen** [comment]
That page is owned by Visual Studio. Also, seemed to be a temporary issue as it is working for me now.
