### ISSUE TITLE
Allow more controls on the installation successful page

### ISSUE THREAD

**Issue by jozefizso** [wixtoolset/issues#6084]
## Feature request

* Describe the scenario and benefits that the feature supports.
> We use standard WiX bootstrapper UI for installer of our application. We would like to display more information on the final page when installation is successful.
> 
> I propose to add two new controls to the **Success** page: **SuccessInstallDescription** (text) and **SuccessInstallIllustration** (image).
> These two new controls will allow us to display more informative message about the application when installation finished.

* Describe how you're accomplishing the feature today (if possible).
> None, WiX Standard Bootstrapper Application UI can display only a single text label named **SuccessInstallHeader** on **Success** page.

* Describe what you'd like the new feature to do.

> Extended **CWixStandardBootstrapperApplication** with two new named controls which will be shown only when installation completed successfully (the same way as **SuccessInstallHeader** control).
> 
> This change will be backwards compatible with existing themes.

**Comment by rseanhall** [comment]
This is already possible in v4 because of the added functionality in #4149.

**Comment by jozefizso** [comment]
We need this in WiX v3
