### ISSUE TITLE
Documentation advises wrong calling convention for native custom bootstrapper applications

### ISSUE THREAD

**Issue by AceFuture** [wixtoolset/issues#6088]
The documentation for [Building a Custom Bootstrapper Application](https://wixtoolset.org/documentation/manual/v3/bundle/ba/) advises the following function signature as main entry point for a custom _native_ DLL implementation:

`extern "C" HRESULT WINAPI BootstrapperApplicationCreate(
    __in IBootstrapperEngine* pEngine,
    __in const BOOTSTRAPPER_COMMAND* pCommand,
    __out IBootstrapperApplication** ppApplication
    )`

I've created a very simplistic DLL project exposing this main entry point exactly as advised and showing a message box to indicate the method was called correctly. However, the compiled bootstrapper exe was never showing anything, the process died almost instantly after it started. The Iog file has the following error information:
> e000: Error 0x8007007f: Failed to get BootstrapperApplicationCreate entry-point

After some digging through the _Burn_ source code, I discovered that the _UserExperienceLoad_ method seems to be loading the custom DLL and getting the address of the exported _BootstrapperApplicationCreate_ function like this:

`PFN_BOOTSTRAPPER_APPLICATION_CREATE pfnCreate = (PFN_BOOTSTRAPPER_APPLICATION_CREATE)::GetProcAddress(pUserExperience->hUXModule, "BootstrapperApplicationCreate");`
(src\burn\engine\userexperience.cpp Line 92)

This cannot work. Note the **WINAPI** macro in the call signature of _BootstrapperApplicationCreate_ which forces the calling convention to be **stdcall**. This exports the symbol "_BootstrapperApplicationCreate@12". However, the use of _GetProcAddress_ here expects a **cdecl** calling convention instead, which is "BootstrapperApplicationCreate".

Removing the **WINAPI** macro from the _BootstrapperApplicationCreate_ function signature has solved this issue immediately, as the function is exported correctly as **cdecl** now.

The documentation should be updated and the **WINAPI** macro removed from the function signature. Alternatively, it can be replaced by **__cdecl** instead, to force the correct calling convention in any case. Another solution would be changing the _GetProcAddress_ call to look for "_BootstrapperApplicationCreate@12" instead, but this will break running systems, so it's not advisable.

I'm using Visual Studio 2017, the WIX extension for it, Windows 10 (1903) and the latest release of WIX which is [v3.11.2](https://github.com/wixtoolset/wix3/releases/tag/wix3112rtm). I'm not building with .NET, this solely concerns native projects.

I do not know if WINAPI is possibly defined in another way on different environments, but I don't believe that's the case. Neither have I found anything anywhere about this, so I guess I'm the only one actually making a native DLL here? Otherwise I don't understand how the WINAPI export could work.

**Comment by barnson** [comment]
`stdcall` is the correct calling convention but the entry point must have a "naked" name, as you note. WixStdBA does so via a [.def file](https://github.com/wixtoolset/wix3/blob/develop/src/ext/BalExtension/wixstdba/wixstdba.def).

**Comment by AceFuture** [comment]
> `stdcall` is the correct calling convention but the entry point must have a "naked" name, as you note. WixStdBA does so via a [.def file](https://github.com/wixtoolset/wix3/blob/develop/src/ext/BalExtension/wixstdba/wixstdba.def).

Can confirm this is the case. In fact, changing it to cdecl, as I proposed, is a mistake here as it corrupts the stack because calling code is always using stdcall (PFN_BOOTSTRAPPER_APPLICATION_CREATE definition).

Creating a very simplistic export definition modules file (.def) solved the issue as well and doesn't corrupt stack memory.

```
EXPORTS
    BootstrapperApplicationCreate
    BootstrapperApplicationDestroy
```

My suggestion then is to make this more clear in the documentation by adding something along the lines of "The functions **BootstrapperApplicationCreate** (and optionally **BootstrapperApplicationDestroy**) must be exported "naked" / in stdcall style. This can be done by [using a module definition (.def) file](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files)"

**Comment by barnson** [comment]
This is "fixed" because of [oopbas](https://wixtoolset.org/docs/fivefour/oopbas/) in WiX v5.
