### ISSUE TITLE
Custom action dll is not in valid format

### ISSUE THREAD

**Issue by andrey-ivanov** [wixtoolset/issues#6089]
* Which version of WiX are you building with?

3.11.2

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2019, v.16.3.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

1.0.0.4

* Which version of .NET are you building with?

4.0

* Describe the problem and the steps to reproduce it.

  * Build custom action dll
  * Try to codesign the dll, you will get the error:
     `%1 is not a valid Win32 application.`

* Describe the behavior you expected and how it differed from the actual behavior.

Codesigning of a generated CA dll should be possible

Downgrading package to WiX 3.11.1 solves the issue. It looks like regression.

**Comment by barnson** [comment]
How are you building the custom action DLL? How are you signing it?

**Comment by andrey-ivanov** [comment]
I've stripped down the existing project, please check attachment. The issue is reproducible if I just manually build this project in VS 2019.

Code signing command looks like:

    C:\signtool\signtool.exe" sign /f "C:\signtool\key.pfx" /p keyPass /t "http://timestamp.comodoca.com/" /v "C:\Release\Setup.CA.dll"

This command output looks like:

> The following certificate was selected:
> ...
> Done Adding Additional Store
> SignTool Error: SignedCode::Sign returned error: 0x800700C1
>         %1 is not a valid Win32 application.
> SignTool Error: An error occurred while attempting to sign: C:\Release\Setup.CA.dll
> 
> Number of files successfully Signed: 0
> Number of warnings: 0
> Number of errors: 1

I also tried to use  signtool.exe from the most recent Windows 10 SDK. The output, in this case, looks a bit different but it basically refers to the same error (it refers to http://aka.ms/badexeformat instead).

[Setup.zip](https://github.com/wixtoolset/issues/files/3702822/Setup.zip)

**Comment by jozefizso** [comment]
I tried to compile the project in the **Setup.zip** using Visual Studio 2019 and it does produces **Setup.CA.dll** file which cannot be signed, nor it can be viewed by tools like PE Explorer (even when recompiled as 32-bit DLL).

```
> peverify.exe /VERBOSE Setup.CA.dll

Microsoft (R) .NET Framework PE Verifier.  Version  4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

File not found or has bad headers.
1 Error(s) Verifying Setup.CA.dll
```

**Comment by jozefizso** [comment]
I tried this with WiX Toolset 3.10 which we use to compile our installer project and the custom action produced by it has the same issue. We never signed the CA dll in this project...

**Comment by barnson** [comment]
PEVerify is for managed assemblies. *.CA.dll are native DLLs.

**Comment by WesleyFudala** [comment]
I am also having this issue with exactly the same output as Andrey.  Tested signtool from winsdk 8 and 10.  I just recently upgraded to wix 3.11.2 from 3.8 so not sure when it started.  Unsure if this is helpful but I am able to open the *.CA.dll of my pre-upgraded project using 7zip to see the contents.  Trying to open a new *.CA.dll with 7zip results in an error saying it is not seen as an archive.

**Comment by BMurri** [comment]
If sfxca.dll is signed before makesfxca runs, the resulting *.ca.dll cannot be signed, nor can the previous signature be removed (I forget what the error was, but it may have been the one your reporting).

I suspect that the fact that sfxca.dll was signed in the most recent v3 publicly released build may be the cause of this.

@andrey-ivanov, @jozefizo, @WesleyFudala please try to remove the digital signature from the sfxca.dll file in your WiX toolset files, try your build again, and report back to this issue if that resolved your issue or not.

**Comment by WesleyFudala** [comment]
@BMurri I'm not sure how to properly remove the digital signature.  I did try using the signtool remove option on both the x86 and x64 sfxca.dll but still got the same issue signing the resulting custom action dll.  I suspect this was not the right way to remove the signature as I still see an entry in the digital signatures tab if I view the file properties.  Perhaps the others will have better luck.

**Comment by BMurri** [comment]
IIRC I used delcert

**Comment by andypea** [comment]
Thanks @BMurri. I followed your advice and I now have a working installer.

Is there a way to do this without modifyin sfxca.dll in place? I assume that my changes will be squashed the next time Wix is updated.

**Comment by BMurri** [comment]
@andypea please open a new issue asking for sfxca.dll to not be signed by WiX's build, since its use always breaks its signature in normal use and prevents a working signature from being added during the corresponding build.

**Comment by BMurri** [comment]
I'll post a couple of pull requests.

**Comment by goewat** [comment]
> 
> 
> If sfxca.dll is signed before makesfxca runs, the resulting *.ca.dll cannot be signed, nor can the previous signature be removed (I forget what the error was, but it may have been the one your reporting).
> 
> I suspect that the fact that sfxca.dll was signed in the most recent v3 publicly released build may be the cause of this.
> 
> @andrey-ivanov, @jozefizso, @WesleyFudala please try to remove the digital signature from the sfxca.dll file in your WiX toolset files, try your build again, and report back to this issue if that resolved your issue or not.

That solved my problem. Thank you very much.
