### ISSUE TITLE
BUG: Light parses CDATA part in conditions wrong when >< is contained

### ISSUE THREAD

**Issue by quirrel1002** [wixtoolset/issues#6094]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

>3.10.3.3007

* Which version of .NET are you building with?

> I am using the command line tools of WiX

* Describe the problem and the steps to reproduce it.

> when I add the following condition to a Component elemt
<Condition><![CDATA[(TESTDRIVE >< ":") AND (NOT ((TESTDRIVE >> ":") OR (TESTDRIVE >> ":\") OR (TESTDRIVE >> ":\\")))]]></Condition>
, it fails with ICE03 error about bad condition string!
=> 
when I change the condition to 
<Condition>(TESTDRIVE  &gt;&lt; ":") AND <![CDATA[(_NOT ((TESTDRIVE >> ":") OR (TESTDRIVE >> ":\") OR (TESTDRIVE >> ":\\")))]]></Condition>
the MSI is build correctly

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected that the first condition parses correctly

Please have a look, but I suspect some CDATA issue here

**Comment by barnson** [comment]
Please attach the authoring so it doesn't get munged by GitHub.

**Comment by quirrel1002** [comment]
Hello, 
I attached it as a file now, please tell me if you need more info.
[CDATA_ParsingIssue.txt](https://github.com/wixtoolset/issues/files/3803495/CDATA_ParsingIssue.txt)

**Comment by barnson** [comment]
Doesn't repro for me on WiX v3.11.2.

**Comment by quirrel1002** [comment]
so, you are right this is not reproducable I reanalysed and found a problem on Wxs "generation" site in my build chain.
