### ISSUE TITLE
Wix setup is detected as Trojan by Jianming Antivirus

### ISSUE THREAD

**Issue by sinewsoftware** [wixtoolset/issues#6095]
**Which version of WiX are you building with?**
3.11.2

**Describe the problem and the steps to reproduce it.**
The setups build with 3.11.2 version of Wix shows a Trojan detected by virustotal with Jianming Engine.

Wix's own 3.11.2 setup show similar behavior/ Trojan detection
https://www.virustotal.com/gui/file/32bb76c478fcb356671d4aaf006ad81ca93eea32c22a9401b168fc7471feccd2/detection 

Note: Setups created with older version of Wix does not show this behaviour.

**Describe the behavior you expected and how it differed from the actual behavior.**
It should not be detected as a Trojan.

**Comment by robmen** [comment]
Seems to be green now. If you continue to have false positives reported, send email to support@jiangmin.com.
