### ISSUE TITLE
Work with Multi-Instance installation

### ISSUE THREAD

**Issue by ericriendeau** [wixtoolset/issues#6101]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

3.11

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2015

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

3.11

* Which version of .NET are you building with?

4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 2012, Windows 19

* Describe the problem and the steps to reproduce it.

I modify my product.wxs to add the Instances list to be able to install my product with different instance and is working fine but when I try to install my product with the default instance without specify the TRANSFORMS is installing correctly but is not appearring in the add/remove programs of Windows.

* Describe the behavior you expected and how it differed from the actual behavior.

Why the default instance not appear in the add/remove programs.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
