### ISSUE TITLE
VSIX Installer fails if Visual Studio has any language packs installed

### ISSUE THREAD

**Issue by rickpapo** [wixtoolset/issues#6103]
In the normal use case (installing on a system where Visual Studio has no language packs), the VSIX Installer support works just fine.  If Visual Studio has any language packs (apart from English) installed, then the VSIX install aborts.  Digging into the various log files shows that the VSIX Installer does not want to install the VSIX because another MSI install is already in progress.  Which it is.  Why this works when no language packs are installed in Visual Studio I cannot say, though I can speculate that there is additional work called for which activates the Windows Installer subsystem recursively.

After attempting to make a custom action shelling out to the VSIXInstaller.exe program, I discovered that that was exactly what you guys had been doing, albeit with the /admin command line option set.  Either way, whether I use your WiX extension to do it, or a custom action, the error message is the same: "Pre-check verification: Your machine is busy installing a program other than Visual Studio."

Unless you guys can come up with a fix, I will have to simply move my VSIX install out to the bootstrapper program, rather than having it as part of the MSI.

**Comment by robmen** [comment]
This is a known issue in VS called out in [the WIP for this feature](https://wixtoolset.org/development/wips/5433-add-support-to-detect-and-install-vsix-packages-into-vs15/):

> Nested MSI sessions
> 
> When an MSI invokes VSIXInstaller.exe targeting VS2017, if any workloads or components are installed that also install MSIs, the session will fail. Microsoft is considering a change to VSIXInstaller.exe to accept a command line parameter when run from within an MSI when VSIXInstaller.exe was found by the CAs documented herein, and when passed will determine if any MSIs will be installed / repaired and exit immediately with an error code we would map back to to a custom message like the following example.

AFAIK, the Visual Studio team has not implemented their part of the solution. You'll want to follow up with them.
