### ISSUE TITLE
When I download & run installer in MS Edge it does not pop up on top of the browser

### ISSUE THREAD

**Issue by jozefizso** [wixtoolset/issues#6105]
# Bug

* Which version of WiX are you building with?
> 3.11.2

* Which version of Visual Studio are you building with (if any)?
> Visual Studio 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> 3.11.2

* Which version of .NET are you building with?
> .NET Framework 4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> Windows 10, Version 1803 or newer

* Describe the problem and the steps to reproduce it.

1. Use Microsoft Edge browser from Windows 10 (eg. Microsoft Edge 44.18362.449.0)
2. Go to a website which has download link to an installer built with wix3 (eg. https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-3.0.101-windows-x64-installer)
4. Click on a download link
3. Click on **Run** button in the download file popup.
4. MS Edge will download the installer and run it
5. The bootstrapper is opened, but the window is shown behind the MS Edge

* Describe the behavior you expected and how it differed from the actual behavior.
> Wix3 Bootstrapper should display on top of the browser window.
>
> I think the bootstrapper should explicitly set the window style to move the initial window on top of the all other applications.

PS: This does not happen in other browsers - the bootstrapper is shown above browser window when it is run after download.

**Comment by jozefizso** [comment]
I think the **WixStandardBootstrapperApplication** should be changed so the main window is brought to foreground when bootstrapper is run.

**Comment by barnson** [comment]
Hard to fix because Windows actively tries to prevent apps from trying to "steal" focus. Does this repro on Chromium Edge?

**Comment by barnson** [comment]
No repro in CrEdge 79.0.309.56.
