### ISSUE TITLE
Use WiX Toolset as a C# library - .NET Core support

### ISSUE THREAD

**Issue by drauch** [wixtoolset/issues#6107]
Hi!

* Describe the scenario and benefits that the feature supports.

For everybody using the WiX Toolset as a C# library to unpack/repack MSI files it would be of great help to be a .NET Core compatible library. This would allow users of the WiX Toolset to migrate from legacy .NET Framework to "the future" .NET Core / .NET 5.

Best regards,
D.R.

**Comment by barnson** [comment]
DTF works with .NET Core. WiX v4 is built with .NET Core and uses DTF: see https://github.com/wixtoolset/Dtf.

**Comment by Nandakumargithub** [comment]
Any idea when WiX v4 is expected for release?

**Comment by BMurri** [comment]
That has been answered elsewhere but it's not unreasonable to expect it to be released by the end of this year.
