### ISSUE TITLE
Support .NET Standard and/or .NET Core custom Bootstrapper

### ISSUE THREAD

**Issue by sonicbhoc** [wixtoolset/issues#6108]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Be able to write a custom managed BA in .NET Core instead of .NET Framework since the future of managed code is in .NET Core.

* Describe how you're accomplishing the feature today (if possible).

> Not possible today without privately implementing this feature request.

* Describe what you'd like the new feature to do.

> Add built-in BA that loads the .NET Core runtime, much like the current `bal:ManagedBootstrapperApplication` loads the .NET Framework runtime.

**Comment by sonicbhoc** [comment]
I created the task by mistake while gathering my thoughts. I will reopen it once I have enough info.

**Comment by BMurri** [comment]
I assume you are referring to custom BAs.

This either already is or will be supported at launch in v4. v3 will only ever support .NET Framework out-of-the-box.

**Comment by barnson** [comment]
@BMurri 

> This either already is or will be supported at launch in v4. 

It's not already supported and significant (unplanned, unfunded) effort is required to support hosting .NET Core -v- Framework.

**Comment by BMurri** [comment]
My bad. I'm interested in looking to see what the scope of work would be, but I wouldn't be able to start until year's end.

**Comment by barnson** [comment]
https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting

**Comment by rseanhall** [comment]
I'm going to reopen this and edit the OP since I already used this issue number for the WIP.

**Comment by lcrumbling** [comment]
We have a custom bootstrapper application written in .Net Framework, which we are naturally porting over to .Net Core. Sounds like we'd need to wait until this is completed before moving forward. Is there any timeline for completion on this issue?

**Comment by rseanhall** [comment]
Soon? But this would only be for v4, which has a timeline of "hopefully sometime this year?".
