### ISSUE TITLE
Wix Bundle: Change DisplayInternalUI from Code-Behind (BootstrapperApplication)

### ISSUE THREAD

**Issue by dhoerner2412** [wixtoolset/issues#6109]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

We're using a Wix Bundle to install multiple MSI packages. All those MSI's can be installed with a UI or for our standard-usecase, all msi-properties are set with variables and no UI is needed. At the moment, we need two <MsiPackage> blocks for each msi in our Bundle.wxs file, one with DisplayInternalUI = "no" and one with DisplayInternalUI = "yes". All other parameters are identical!

* Describe how you're accomplishing the feature today (if possible).

We have defined each msi twice in the bundle.wxs and in CodeBehind (BootstrapperApplication in .NET) we decide which need to be installed

```
<MsiPackage
          Id                  =   "PackageWithoutUi"
          DisplayName         =   "PackageWithoutUi"
          SourceFile          =   "..\Test.msi"
          Compressed          =   "yes"
          Name                =   "PackageWithoutUiSetup.msi"
          Visible             =   "yes"
          Permanent           =   "no"
          DisplayInternalUI   =   "no"
          Vital               =   "no">

        <MsiProperty Name="TARGETDIR" Value="[TARGETDIR]\$(var.Desc)"/>
        <MsiProperty Name="SERVICE_PORT" Value="[CIS_MCN_PORT]"/>
</MsiPackage>
	  
<MsiPackage
          Id                  =   "PackageWithUi"
          DisplayName         =   "PackageWithUi"
          SourceFile          =   "..\Test.msi"
          Compressed          =   "yes"
          Name                =   "PackageWithUiSetup.msi"
          Visible             =   "yes"
          Permanent           =   "no"
          DisplayInternalUI   =   "yes"
          Vital               =   "no">

        <MsiProperty Name="TARGETDIR" Value="[TARGETDIR]\$(var.Desc)"/>
        <MsiProperty Name="SERVICE_PORT" Value="[CIS_MCN_PORT]"/>
</MsiPackage>
```

* Describe what you'd like the new feature to do.

Add a feature to set

- DisplayInternalUI  by a variable value which can be changed in Code-Behind (BootstrapperApplication in .NET) or per Commandline
- DisplayInternalUI  in CodeBehind (BootstrapperApplication in .NET)

**Comment by barnson** [comment]
Duplicate: #3703

**Comment by barnson** [comment]
This issue is open and unassigned. That means it's waiting for someone to investigate the root problem, discuss possible solutions to the problem, and implement an agreed solution.

If you are interested in doing that work yourself, our [developer documentation][dev] provides a great checklist for getting started.

If you are not interested in doing that work, someone else needs to become interested enough to do it. If this issue has been open for a long time, there probably isn't general interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options][support].

[dev]: https://wixtoolset.org/development/
[support]: https://www.firegiant.com/support-options/

**Comment by dhoerner2412** [comment]
> 
> 
> This issue is open and unassigned. That means it's waiting for someone to investigate the root problem, discuss possible solutions to the problem, and implement an agreed solution.
> 
> If you are interested in doing that work yourself, our [developer documentation](https://wixtoolset.org/development/) provides a great checklist for getting started.
> 
> If you are not interested in doing that work, someone else needs to become interested enough to do it. If this issue has been open for a long time, there probably isn't general interest in this particular issue. In that case, you'll want to consider how to motivate others to fix it for you. This is a pretty [good list of support options](https://www.firegiant.com/support-options/).

Ok I successfully got the sourcecode for burn etc from github. Which repository do I need to build the candle.exe?
