### ISSUE TITLE
VS2019 debug build of WIX projects outputs MSI files into bin\Release not bin\Debug

### ISSUE THREAD

**Issue by Deracination** [wixtoolset/issues#6113]
## Bug

* Which version of WiX are you building with?
3.11.2

* Which version of Visual Studio are you building with (if any)?
VS2019 16.2.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
WiX 1.0.0.4

* Which version of .NET are you building with?
.NET 4

* Describe the problem and the steps to reproduce it.
When the VS configuration is set to Debug building the WIX installers via right-click/Build creates the WIX output files (.MSI, etc) in the bin/Release directories for the WIX projects. This change appeared recently (since November 2019), maybe related to a VS update?

* Steps
  * Set solution to 'Debug' build, and 'right-click/Build' a WIX project - the output is in the bin\Release directory for the project
  * Set solution to 'Release' build and 'right-click/Build' on a WIX project - the output is also in the bin\Release directory.

* Describe the behavior you expected and how it differed from the actual behavior.
I expect Debug build WIX files to be output in the bin/Debug directory as was happening previously.

**Comment by barnson** [comment]
Works as expected with VS2019 16.4.2.

**Comment by Deracination** [comment]
Confirmed this is fixed with VS2019 16.4.2. This was a Visual Studio bug.
