### ISSUE TITLE
Build wix  on tfs builds prebuild too early

### ISSUE THREAD

**Issue by slnetgit** [wixtoolset/issues#6115]
I hava a Project that builds correctly with VS2017 / VS 2019. If I build on TFS 2017 the build process gives an error because the prebuild step where heat - calls are done to generate wix - Fragment files is called too early. 

After analyzing what happens I found that in the Wix 2010.targets file the Definition of the CoreBuild dependson seems to have a small Problem 

<PropertyGroup>
    <CoreBuildDependsOn>
      BuildOnlySettings;
      PrepareForBuild;
      PreBuildEvent;        -- should happen after resolve references 
      ResolveReferences; --  should happen before prebuild 
      AddCompilerDefineConstants;
      CompileAndLink;
      Signing;
      GetTargetPath;
      IncrementalClean;
      PostBuildEvent
    </CoreBuildDependsOn>
  </PropertyGroup>

I changed the order to 

\<CoreBuildDependsOn\>
      BuildOnlySettings;
      PrepareForBuild;
      ResolveReferences;
      PreBuildEvent;
      AddCompilerDefineConstants;
      CompileAndLink;
      Signing;
      GetTargetPath;
      IncrementalClean;
      PostBuildEvent
    </CoreBuildDependsOn\>

And the build on the tfs succeeded.

**Comment by barnson** [comment]
Use `BeforeCompileAndLink` so `ResolveReferences` still runs if needed.
