### ISSUE TITLE
SSL/TLS 1.2 support

### ISSUE THREAD

**Issue by denysmorozenko** [wixtoolset/issues#6117]
Hi!

We are using WiX-v3.11.1.2318 for our installer.
At some point we are creating SQL database with C# code and then use WiX to connect DB and populate it with tables and stored procedures.

The problem is that we are performing installation on a hardened OS which have certain level of security features enabled. One of those features - TLS 1.2 is required for all the apps and WiX-v3.11.1.2318 does not have it.

I know that in your latest dev branch you've already added TLS 1.2 support (WiX-v3.14.0.3316). 
Can you please shed some light on possible release date for WiX with TLS 1.2 support?

**Comment by barnson** [comment]
TLS support is available in WiX v3.14.

**Comment by denysmorozenko** [comment]
Yes. I know that it available in 3.14. But as far as I know it is a developer release. 

Can you please shed some light on possible release date this version as a Recommended build?
