### ISSUE TITLE
How to build WiX Custom Action projects without having VS Extension installed?

### ISSUE THREAD

**Issue by kjeld-jensen** [wixtoolset/issues#6121]
I've got a C# solution containing a WiX installer project, which references a C# Custom Action project for WiX v3. Within the csproj of that CA project, there is a WixCATargetsPath entry referencing the file Wix.CA.targets:

`<WixCATargetsPath Condition=" '$(WixCATargetsPath)' == '' ">$(MSBuildExtensionsPath)\Microsoft\WiX\v3.x\Wix.CA.targets</WixCATargetsPath>`

The Wix.CA.targets is obviously part of the installation of the Wix Toolset VS 2017 Extension, and not of the Wix Toolset itself. But on our build server, neither Visual Studio nor Wix Toolset Extension is installed, which is why the build there fails:

`error MSB4019: Das importierte Projekt "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.`

So is it possible to build Custom Action projects on the build server without having the Wix Toolset Extension installed?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by jakubsuchybio** [comment]
I managed to build wix custom action project after adding these into .csproj file:
```
  <Import Project="$(WixCATargetsPath)" Condition=" '$(WixCATargetsPath)' != '' AND '$(Configuration)' == 'Release' " />
  <ItemGroup>
    <Reference Include="Microsoft.Deployment.WindowsInstaller">
      <HintPath>$(WixInstallPath)\Microsoft.Deployment.WindowsInstaller.dll</HintPath>
    </Reference>
  </ItemGroup>
```

The first one will import wix.ca.targets from .nuget package folder. This one populates WixInstallPath property and also populates BeforeClean and AfterCompile targets which are then creating .CA.dll
