### ISSUE TITLE
No dialogs in Visual Studio Enterprise 2019 v. 16.4.3

### ISSUE THREAD

**Issue by Smash011** [wixtoolset/issues#6122]
Since i updated Visual Studio Enterprise 2019 to the latest version 16.4.3 i get a blank screen when try to open File System Editor, Registry Editor ... Visual Studio Enterprise 2017 v. 15.9.19 still worked.
See attached file
![grafik](https://user-images.githubusercontent.com/5235343/72540316-f5430180-3880-11ea-998d-8f762f07786c.png)

**Comment by barnson** [comment]
That is not part of the WiX Toolset. If you're using a third-party editor, you'll need to check with them for support.
