### ISSUE TITLE
Unable to install 2019 extension due to Invalid Timestamp on Certificate

### ISSUE THREAD

**Issue by an0t8** [wixtoolset/issues#6124]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
> 3.11.1.2318

* Which version of Visual Studio are you building with (if any)?
> Visual Studio Enterprise 2019 16.4.3
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> VS 2019 version 1.0.0.4

* Which version of .NET are you building with?

> 4.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

>Windows 10 Enterprise 1703

* Describe the problem and the steps to reproduce it.

When attempting to install the Visual Studio Extension, I am getting and InvalidTimestamp error on a Certficate.  The install is failing with an Invalid Certificate.
See attached log:

[dd_VSIXInstaller_20200122142319_3218.log](https://github.com/wixtoolset/issues/files/4099819/dd_VSIXInstaller_20200122142319_3218.log)

**Comment by barnson** [comment]
Windows 10 Enterprise 1703 is EOL, which might mean you're not getting cert updates. See https://developercommunity.visualstudio.com/content/problem/656686/vsix-2019-extension-fails-to-install-in-offline-en.html. Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
