### ISSUE TITLE
MSBuild tools 2019 wixtoolset integration

### ISSUE THREAD

**Issue by bigswede74** [wixtoolset/issues#6125]
When I'm building the wix project I'm getting the below error.

error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" is correct, and that the file exists on disk.

I have installed the WixToolset 3.11 on the build server. Is the below article the recommended build integration path?

https://wixtoolset.org/documentation/manual/v3/msbuild/daily_builds.html

## Bugs

If this issue is a bug:

* Wix 3.1.1
* Visual Stuido 2019
* MSBuild 16.4.0.56107

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
