### ISSUE TITLE
How to create a Patch and install it to the already installed product witout affecting the previous version

### ISSUE THREAD

**Issue by Sumanthdv** [wixtoolset/issues#6128]
Hi , I'm New to Wix Toolset, I have created an MSI Through visual studio for my application.
The user has installed the application and has done some customizations.
Now i want to add a custom action while uninstalling the application through a patch without affecting users customizations, How can i do this.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
