### ISSUE TITLE
Bug with wix installer when remove old version and install newer

### ISSUE THREAD

**Issue by blinx83** [wixtoolset/issues#6129]
Version of wix 3.9
Version of visual studio : 2017 community version 15.8.7
Good Morning,

I encounter a bug when installing new version of a same software.
I uninstall the old version(which is 1.5.0) in configuration panel, after I install the new version which is 2.0.0.
The issue is that the old version reappear in configuration panel and new components are not installed.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
