### ISSUE TITLE
warning CNDL1149: ServiceConfig functionality is documented in the Windows Installer SDK to "not [work] as expected."

### ISSUE THREAD

**Issue by maniglia** [wixtoolset/issues#6131]
## Question Bug

* Which version of WiX are you building with?

> WiX Toolset Compiler version 4.0.0.5918

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Version 16.4.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> nil

* Which version of .NET are you building with?

> .NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> nil

* Describe the problem and the steps to reproduce it.

> When I try to use ServiceInstall and ServiceConfig:
`<ServiceConfig DelayedAutoStart="no" PreShutdownDelay="180000" ServiceSid="none" OnInstall="yes" OnReinstall="no" OnUninstall="no" />`

* Describe the behavior you expected and how it differed from the actual behavior.

> The compiler generates the following warning: 
warning CNDL1149: ServiceConfig functionality is documented in the Windows Installer SDK to "not [work] as expected." Consider replacing ServiceConfig with the WixUtilExtension ServiceConfig element.

In `WixToolset.Core` -> `Compiler_2.cs` -> `ParseServiceConfigElement` (row 2744),
I find the following line of code:
`this.Core.Write(WarningMessages.ServiceConfigFamilyNotSupported(sourceLineNumbers, node.Name.LocalName));`

How should I interpret this?
There is another way to install a service?

Thanks in advance.
Regards.

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by amandaabalos** [comment]
Hi, 

Did you figure this out? I am also getting the same error code

Regards

**Comment by maniglia** [comment]
Hello,
As you can see in the first post, the message is hardwired into the code. Probably for good reason.
But in many years of use I have never encountered problems.
I didn't investigate due to lack of time.
Let's wait for the next version (`WiX  v4-preview.0`) to see what happens.
Regards

**Comment by 6bee** [comment]
Just realized one may suppress compiler (candle) warning using msbuild property. For CNDL1149 this would be:
 ```
<PropertyGroup>
  <CompilerSuppressSpecificWarnings>1149</CompilerSuppressSpecificWarnings>
</PropertyGroup>
```

**Comment by 6bee** [comment]
After updating to v4 stable version (`WixToolset.Sdk/4.0.2`) this warning is shown as "_error WIX1149_". 
A different property has to be used to suppress the error:
```
<PropertyGroup>
  <SuppressSpecificWarnings>1149</SuppressSpecificWarnings>
</PropertyGroup>
```
