### ISSUE TITLE
Unable to use wix under vs2019

### ISSUE THREAD

**Issue by benjamin-devuyst** [wixtoolset/issues#6133]
Hi,

We are using WIX for a while now, and we are trying to migrate under VS2019.

Environment : 
Version of VS :
-  Microsoft Visual Studio Enterprise 2019 - Version 16.4.5
   VisualStudio.16.Release/16.4.5+29806.167
- Version of Dotnet : 4.8.03761
- Wixtoolset 3.11 and last version of the extension for VS2019,

Problem : VS is unable to open wixproj. It says : 

Unsupported
This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
	 -   path to project... .wixproj"

Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - ... 

If I try to add a new Wix project, I cannot see Wix project template ...

I have already reinstalled all twice... and problem continue...

Can you help ?

Thanks

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

**Comment by benjamin-devuyst** [comment]
Yes... but , if I open the Extension Manager, it says that extension is installed...

**Comment by BMurri** [comment]
It's obviously an installation failure of some sort, given that it's non-functional.

Please use the VS forum to diagnose what went wrong to cause the installation to end up non-functional and get it corrected.
