### ISSUE TITLE
ExecXmlFile fails for ARM64 MSIs

### ISSUE THREAD

**Issue by marswe** [wixtoolset/issues#6136]
* Which version of WiX are you building with?

> 3.14.0.3827, with ARM64 support (!!)

* Which version of Visual Studio are you building with (if any)?

> VS 2017, version 15.9.19

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Any version of Windows 10 running on ARM64.  I specifically am using a Samsung Galaxy Book S running Windows 10 version 2004

* Describe the problem and the steps to reproduce it.

If you build an MSI that installs an event manifest, like the EventManifestTest MSI from [EventManifestTests](https://github.com/wixtoolset/wix3/blob/master/test/data/Extensions/UtilExtension/EventManifestTests/product.wxs), as an ARM64 MSI and install it, the installation will fail with this error:

ExecXmlFile:  Error 0x80004001: Custom action was told to act on a 64-bit component, but the custom action process is not running in WOW.

This looks to be because the 32-bit custom action server is querying [IsWow64Process](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process) to determine if it is a 32-bit process.  On ARM64 Windows, that API returns FALSE for x86 processes.  ExecXmlFile would need to use the API [IsWow64Process2](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2) to accurately detect if the custom action server is running as x86 on ARM64.

**Comment by barnson** [comment]
ExecXmlFile was written to be 32-bit but support 64-bit resources. So it'll need some tweaks to not play WOW64 games when it's 64-bit code.

**Comment by barnson** [comment]
Fix available in WiX v3.14.0.3910: https://wixtoolset.org/releases/v3-14-0-3910/
