### ISSUE TITLE
Compiler doesn't step version up to 500 for ARM64 MSIs

### ISSUE THREAD

**Issue by marswe** [wixtoolset/issues#6137]
* Which version of WiX are you building with?

> 3.14.0.3827, with ARM64 support

* Which version of Visual Studio are you building with (if any)?

> VS 2017, version 15.9.19

* Describe the problem and the steps to reproduce it.

If you create an x64 MSI with a version < 200, candle will adjust the version for you and provide a warning that the version is being stepped up to 200.  ARM64 MSIs need a version of 500 (like ARM) -- but candle will only step up the version to 200.  

The MSI will build successfully, but then fail to install with an error dialog from the OS: "This installation package could not be opened.  Contact the application vendor to verify that this is a valid Windows Installer package." 

(Note that candle successfully sets the version to 500 if the version isn't set at all.  The step up is only relevant if someone tries to build an ARM64 version from an existing wxs that has a version set.)

**Comment by barnson** [comment]
Fix available in WiX v3.14.0.3910: https://wixtoolset.org/releases/v3-14-0-3910/
