### ISSUE TITLE
wix.ca.targets has unsupported constructs for SDK-style .csproj custom actions

### ISSUE THREAD

**Issue by jakubsuchybio** [wixtoolset/issues#6139]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.1

* Which version of Visual Studio are you building with (if any)?

> VS2019 16.4.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> No extension

* Which version of .NET are you building with?

> .NET 4.8 (SDK-style .csproj format)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 1909 18363.657

* **Describe the problem and the steps to reproduce it.**

Our company is using wix toolset for building wix custom actions for our installer. We didn't want to maintain wixtoolset installation on our build servers and on our dev machines, so we figured out how we could build our custom actions through your nuget package ```WiX```.
Basically I added this:
```
  <Import Project="$(WixCATargetsPath)" Condition=" '$(WixCATargetsPath)' != '' AND '$(Configuration)' == 'Release' " />
  <ItemGroup>
    <Reference Include="Microsoft.Deployment.WindowsInstaller">
      <HintPath>$(WixInstallPath)\Microsoft.Deployment.WindowsInstaller.dll</HintPath>
    </Reference>
  </ItemGroup>
```
Into our .csproj file for our custom actions and this injects ```CleanBefore``` and ```AfterCompile``` targets in msbuild to build .CA.dll file for us.
This works like a charm.
However I'm now migrating to sdk-style .csproj format and this building of .CA.dll stopped working.

* **Describe the behavior you expected and how it differed from the actual behavior.**

At first it didn't produce .CA.dll file, so I tried to use ```MSBuild Structured Log Viewer``` to see what is happening.
I found out that wix.ca.targets's ```CleanBefore``` and ```AfterCompile``` are overwritten by microsofts SDK targets.
I found a workaround for that by modifying ```wix.ca.targets``` with help from this issue: https://github.com/dotnet/sdk/issues/841
After that It finally started producing .CA file, but another problem presented itself. It was generating file ```.CA``` instead of full name with .dll ext.
After some googling I found another issue which solves this problem: https://github.com/dotnet/sdk/issues/3551

I already solved this bug for wix v3. Pull request will be posted afterwards

**Comment by barnson** [comment]
This will be covered in the WiX v4 NuGet package for DTF.

**Comment by jakubsuchybio** [comment]
Is there some ETA for WiX v4 DTF Nuget package? (what is DTF?)

**Comment by rseanhall** [comment]
DTF is at https://github.com/wixtoolset/Dtf. `wix.ca.targets` is in Tools though - https://github.com/wixtoolset/Tools/blob/master/src/WixToolset.BuildTasks/wix.ca.targets.

**Comment by barnson** [comment]
I imagine we'll need a separate managed-code CA NuGet package or maybe Tools picks it up? It's already the most-downstream package...

**Comment by robmen** [comment]
Yes, the `wix.ca.targets` will be extracted from tools when the SDK style CA projects are developed. That work is not completed yet.

**Comment by Kalle4242** [comment]
Hello,

I'm very confused.
I'm now searching around for half a day, why Wix Custom Actions are not running with new sdk style project files.
Now I know s.th. is not running. But I'm still missing a clear advice for users:
Do I have to wait for version 4? When will it be delivered  propably?
Is there /Will there be a workaround in between? I can't extract what I would have to do from the discussion above. 
jakubsuchybio fixed it already for version 3. Is that an opportunity? How can I get access to that fix? What do I have to do?
Or alternatively: Sorry, but you have to use the old project file format for your custom action project until version 4 will be delivered. This will be working in the meantime. But even this is not clearly statet.

Sorry, but I'm very angry about the time I wasted yesterday afternoon, trying out and googling for a solution.  
Yes, here, is maybe not the right place for such advices. But it should be described somewhere more prominent, at least that there are problems. Please keep in mind, that these issue logs sometimes are the only available documentation for users, who do work only from time to time on these themes.

Never mind, further help on custom action project files in sdk style is appreciated,
Kalle

P.S.: I felt reminded of my youth:
“But the plans were on display…”
“On display? I eventually had to go down to the cellar to find them.”
“That’s the display department.”
“With a flashlight.”
“Ah, well, the lights had probably gone.”
“So had the stairs.”
“But look, you found the notice, didn’t you?”
“Yes,” said Arthur, “yes I did. It was on display in the bottom of a locked filing cabinet stuck in a disused lavatory with a sign on the door saying ‘Beware of the Leopard.”
― Douglas Adams, The Hitchhiker's Guide to the Galaxy

**Comment by robmen** [comment]
WiX v3 was developed before the introduction of SDK-style projects by Microsoft. Therefore, WiX v4 will be the first version to support SDK-style CA projects. That should happen next year.

**Comment by jakubsuchybio** [comment]
Hey @Kalle4242, I figured out a workaround for this. It is in my fork. You can look at it.
Also in build steps of our main build we use this powershell to override nuget's wix.ca.targets with the one from my fork.

```
echo "Downloading wix.ca.targets"
Invoke-WebRequest -Uri https://raw.githubusercontent.com/jakubsuchybio/wix3/develop/src/tools/WixTasks/wix.ca.targets -OutFile %system.teamcity.build.tempDir%\wix.ca.targets
# Invoke-WebRequest -Uri https://raw.githubusercontent.com/wixtoolset/wix3/develop/src/tools/WixTasks/wix.ca.targets -OutFile %system.teamcity.build.tempDir%\wix.ca.targets
echo "Download complete"

echo "Copying wix.ca.targets to %env.USERPROFILE%\.nuget\packages\wix\3.11.2\tools\sdk\wix.ca.targets"
echo f | xcopy %system.teamcity.build.tempDir%\wix.ca.targets %env.NUGET_PACKAGES%\wix\3.11.2\tools\sdk\wix.ca.targets /K /D /H /Y
echo "Copy complete"
```

**Comment by Kalle4242** [comment]
Hey Robmen, hey jakubsuchy,

thanks for your quick answers. I hab to adopt jakubs fix to our non-nuget wix 3.11.1 installation and edit the location of the toolset back to v3.11. But then it was finally building the customaction.ca.dll.

Is there any difference to between the versions. First I had the idea that I at least would have to import the targets from different location. But this will probably work without changes because then "WixCATargetsPath" will be filled when working with the nuget package.

Thank you for help,
Karl

**Comment by jakubsuchybio** [comment]
Hi guys,
we just migrated our wix 3.11.2 to 3.14 and got into troubles of my "hotfix" in my fork.
But I just want to add to the discussion that it is not needed to do another hotfix, because with wix 4.0.4 there is much much simpler solution :)

And that is `WixToolset.Dtf.CustomAction` nuget, which solves this whole problem.
And instead of Microsoft.Deployment.WindowsInstaller just use `WixToolset.Dtf.WindowsInstaller`

And it just works... Nice

**Comment by manishmishra2013** [comment]
Hi jakubsuchybio,
How wixCA.CA.dll will create after using WixToolset.Dtf.CustomAction nuget
