### ISSUE TITLE
sys.BUILDARCH is broken for ARM64

### ISSUE THREAD

**Issue by bpulliam** [wixtoolset/issues#6141]
This is due to ARM64 missing from the switch on PreprecessorCore.cs:462

## Bugs

* Which version of WiX are you building with?
3.14.0.3827

* Which version of Visual Studio are you building with (if any)?
VS 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
N/A

* Which version of .NET are you building with?
N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.
Add $(sys.BUILDARCH) to a wxs file
run 'candle -arch arm64'

exception thrown:
candle.exe : error CNDL0001 : Unknown platform enumeration '{0}' encountered.
Parameter name: ARM64

* Describe the behavior you expected and how it differed from the actual behavior.
BUILDARCH should operate as it does on non-ARM64 platforms.

**Comment by barnson** [comment]
Fix available in WiX v3.14.0.3910: https://wixtoolset.org/releases/v3-14-0-3910/
