### ISSUE TITLE
Restart doesn't work on non elevated burn installers launched on Windows Server 2019

### ISSUE THREAD

**Issue by vanni-giachin** [wixtoolset/issues#6145]
**Wix version**: 3.11.2

**.NET Framework version**: 4.6.2

**OS**: Windows Server 2019

**Steps to reproduce**
1. Configure a Windows Server 2019 machine with default settings
2. Sign in with a administrator user (reproduced with domain administrator)
3. Run the installer. Do not execute _As Administrator_
4. Trigger a forced reboot (e.g. `<ExitCode Value="3010" Behavior="forceReboot"/>`)

**Outcome**
The UI correctly display the restart button (_SuccessRestartButton_), the installer exits when clicking on it and the registry is correctly updated, but the machine reboot doesn't start.
The logs don't show any error.

**Workarounds**
- Run as administrator
- Assign the "Shut down the system" permission on local security policy, sign out and sign in, launch the installer. The permission inheritance from the _Administrators_ group is not enough
- Restart the machine manually

**Additional info**
On Windows Server 2019 only, the output of the command `whoami /priv` from a non administrator cmd does not contain the following entry:
```
Privilege Name                Description                          State
============================= ==================================== ========
SeShutdownPrivilege           Shut down the system                 Disabled
```
So maybe the burn code should handle the case when the permission is missing, not just disabled as it is on other OS, in order to solve the issue.

Thanks!

**Comment by barnson** [comment]
Probably need a way for the UX process to talk to the elevated process to try the reboot.

**Comment by armsee** [comment]
Now that Windows Server 2019 has become more and more widespread, this issue is becoming an ever greater problem for our customers and therefore also for us.

**Comment by barnson** [comment]
Per-user bundles won't have an elevated process to talk to. One approach is to have a `-burn.restartnow` switch in Burn itself to get the bundle's Authenticode signature on the prompt.
