### ISSUE TITLE
Installing wix from CLI, no GUI

### ISSUE THREAD

**Issue by Thermi** [wixtoolset/issues#6146]
Probably a feature request, because I did not find any documentation on it.

I need to install wix itself in a CI environment to transform an MSM into an MSI file automatically without human intervention.
Does the wix installer itself (wix311.exe) support quiet and promptless installation? It would be run as a user with administrator privileges. As it's a CI environment, no human intervention is possible.

**Comment by robmen** [comment]
Yes. For additional support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
