### ISSUE TITLE
Add Property for disable FilesInUse and MsiRMFilesInUse

### ISSUE THREAD

**Issue by Horcrux7** [wixtoolset/issues#6157]
I have a windows service that hold multiple processes. For the the installer it is completely impossible to detect which files are in use before stopping the service.

On update or uninstall there are ever one of the _"files in use"_ dialogs. If I press `ignore` all is working like expected. 

This occur because I use the C-runtime. Many libraries like `api-ms-win-core-*.dll`. This libraries are used from many other programs today. Because Windows can't detect the path of the used files, only the pure files names are checked. That it list many programs that have nothing to do with my program.

The FileInUse mechanism is completely broken.

If you Google for disable the FilesInUse dialogs you find many entries since years.

Please add a property to the Wix Toolset to disable it.

**Comment by barnson** [comment]
Windows Installer is in charge at runtime. See [the MSI SDK doc on system reboots][reboots].

[reboots]: https://docs.microsoft.com/en-us/windows/win32/msi/system-reboots

**Comment by mikehenselersimfront** [comment]
please reopen, we have the exact same problem. FileInUse false positive
