### ISSUE TITLE
Choose which dialog is shown during install/update when files are in use

### ISSUE THREAD

**Issue by dukorama** [wixtoolset/issues#6160]
Feature request:

We have a client-side application that works in conjunction with our web application and are providing an initialization screen to users where they can install or update our client-side application in case they haven't done so yet. 
During install or update it can happen though that a process that would be affected by the installation/update is still running. In this case it depends on whether it is an installation or an update which dialog is shown to the user. 
In the first case, a dialog appears, providing a choice whether to close applications automatically or not to close applications. The dialog has to two buttons, OK and Cancel.
In the second case a "Files in Use" dialog appears, with three buttons, Exit, Ignore and Retry.

Since this can be confusing for users, it would be great if we could choose which dialog of the two is shown, for example by having the option that only the first dialog is shown in such cases.

![filesInUse1](https://user-images.githubusercontent.com/23388298/80385090-f0d9ac00-88a5-11ea-9cc6-155f74abfcb8.png)
![filesInUse2](https://user-images.githubusercontent.com/23388298/80385094-f1724280-88a5-11ea-9599-d864dfc81b83.png)

**Comment by barnson** [comment]
Windows Installer is in charge at runtime. See [the MSI SDK doc on system reboots][reboots].

[reboots]: https://docs.microsoft.com/en-us/windows/win32/msi/system-reboots
