### ISSUE TITLE
Wix binder is failing to find burn.exe for arm64 projects

### ISSUE THREAD

**Issue by NikolaMilosavljevic** [wixtoolset/issues#6161]
* Which version of WiX are you building with?

3.14.0.3910

* Which version of .NET are you building with?

4.8

* Describe the problem and the steps to reproduce it.

Wix binder is trying to use burn.exe from Wix's arm64 folder. However, burn.exe is x86 only. For x64 projects, binder correctly includes burn.exe from x86 folder. It should do the same for arm64 projects.

* Describe the behavior you expected and how it differed from the actual behavior.

Wix binder should use burn.exe from x86 folder for arm64 projects.

**Comment by NikolaMilosavljevic** [comment]
I have tested a change that I plan to propose on wix-devs mailing list.

**Comment by rseanhall** [comment]
This is v3 only. v4 will support more than just x86 so it will not use the x86 stub for multiple platforms, the user is required to specify the intended platform.
