### ISSUE TITLE
Move `DisplayInternalUI` attribute out of core and into `BalExtension`

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6164]
If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> https://github.com/wixtoolset/issues/issues/3703
> https://github.com/wixtoolset/issues/issues/3903
> https://github.com/wixtoolset/issues/issues/4921
> https://github.com/wixtoolset/issues/issues/5616
> https://github.com/wixtoolset/issues/issues/5806

* Describe how you're accomplishing the feature today (if possible).

> Not possible.

* Describe what you'd like the new feature to do.

> Add support for a BA to override the `INSTALLUILEVEL` for all MSI/MSP packages for all operations.
> Add support for a BA to disable Burn's external MSI UI handler in order to show the package's EmbeddedUI.
> Move `DisplayInternalUI` attribute out of core and into `BalExtension`.

**Comment by rseanhall** [comment]
What's supposed to be done in v3.14, deprecating `DisplayInternalUI`? Any ideas for the deprecation message?

**Comment by barnson** [comment]
Not a thing. Dunno why I did that. It's not being deprecated, so the only thing to consider is adding an automatic move to WixCop.

**Comment by barnson** [comment]
All done.

**Comment by elaboy** [comment]
I moved the `DisplayInternalUI = yes` to the bal extension. While it fixed the issue, and works perfectly, it is still marked as `DisplayInternalUI attribute is not allowed` by Visual Studio Community Edition 2022.

**Comment by robmen** [comment]
> While it fixed the issue, and works perfectly, it is still marked as DisplayInternalUI attribute is not allowed by Visual Studio Community Edition 2022.

This would be a doc issue. Please open a new issue for it.
