### ISSUE TITLE
Light Fails With MsiGetFileVersion on Windows 1809

### ISSUE THREAD

**Issue by ajorians** [wixtoolset/issues#6167]
## Quick Summary:

Requesting we add a retry mechanism (`do`-`while` loop or similar) around this code: https://github.com/wixtoolset/wix3/blob/develop/src/tools/wix/Binder.cs#L6288-L6302 that calls `MsiGetFileVersion` as it would fix my problem.

## Details:

I am getting a call stack and failure to build just like from this thread: http://lists.project-wombat.org/pipermail/wix-users-wixtoolset.org/2018-October/007510.html

<details><summary>StackTrace</summary>
<blockquote>
light.exe error LGHT0001: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Exception Type: System.AccessViolationException

Stack Trace:
   at Microsoft.Tools.WindowsInstallerXml.Msi.Interop.MsiInterop.MsiGetFileVersion(String filePath, StringBuilder versionBuf, Int32& versionBufSize, StringBuilder langBuf, Int32& langBufSize)
   at Microsoft.Tools.WindowsInstallerXml.Msi.Installer.GetFileVersion(String filePath, String& version, String& language)
   at Microsoft.Tools.WindowsInstallerXml.Binder.UpdateFileRow(Output output, IDictionary`2 infoCache, String modularizationGuid, Hashtable fileRowIndex, FileRow fileRow, Boolean overwriteHash)
   at Microsoft.Tools.WindowsInstallerXml.Binder.UpdateFileInformation(Output output, FileRowCollection fileRows, MediaRowCollection mediaRows, IDictionary`2 infoCache, String modularizationGuid)
   at Microsoft.Tools.WindowsInstallerXml.Binder.BindDatabase(Output output, String databaseFile)
   at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)
</blockquote>
</details>

This failure has been occurring in every build.

We have been able to work around this in the past by having developers do a Windows Update on their Windows 10 machines to version 1909.  This fixes the problem.  But our new server is running on Azure and is incapable at this time to update from version 1809.

- I can use the '-sh' (linker) flag to `light` and that creates successful builds.
   - It suppress hash checks and skips over the problem code.  But we don't want to do this.

I added tracing to see if it was a particular file being passed to `MsiGetFileVersion` and it does seem very related to MUI (Multilingual User Interface) files.  And I also added a small retry loop around the code here: https://github.com/wixtoolset/wix3/blob/develop/src/tools/wix/Binder.cs#L6288-L6302  And that fixes my problem!

<details><summary>Screenshots with my additional output that shows the retry</summary>

![image](https://user-images.githubusercontent.com/3475163/80817497-883d4880-8b9f-11ea-8aab-2a9c643dbc53.png)
</details>

It doesn't always appear to be with MUI files as I have hit the problem with a non-resource related DLL file:
<details><summary>Screenshot with my additional output</summary>

![image](https://user-images.githubusercontent.com/3475163/80984158-7f48b300-8dfb-11ea-935b-657323ec7f72.png)
</details>

It isn't deterministic whether `MsiGetFileVersion` fails or not as the same function call works the second time upon doing a retry.  And it is different files causing the issue on each build.  Thus I think a retry capability makes sense to add.  I think this even though Microsoft fixed the root problem with an update.

## Bugs

This happens with Wix 3.11.2 on both Windows 10 1809 and Windows Server 2019 1809.
Reproducing with VS2019 but using the VS2017 Toolset.  It happens with just VS2017 (15.7.5).  This uses .NET Framework 4.

I attached a simple Wix solution:
[Testme.zip](https://github.com/wixtoolset/issues/files/4575574/Testme.zip)

You should be able to verify the solution builds and then you can try a 1809 version of Windows and it should fail with the exception.

Let me know if there is any more information I can get for you.  Thanks! :smiley:

**Comment by BMurri** [comment]
That looks like the types of interference that anti-virus software often causes builds.

This looks like a support issue, which we deal with in the wix-users email list. Please take this issue there.

If a bug in WiX is determined to exist as part of the analysis done in that email list, we would then direct you to open a bug here to have it addressed in code.

**Comment by barnson** [comment]
Retrying file i/o on i/o errors is a good thing but triage was uncomfortable trying to retry after a `AccessViolationException`. There are no promises of stability after a GP fault.
