### ISSUE TITLE
Allow to harvest files with the same name but different extension

### ISSUE THREAD

**Issue by paulomorgado** [wixtoolset/issues#6178]
When I try to harvest the `MyProgram.exe` and `MyProgram.pdb` files, I get an error that looks something like this:

candle.exe : error CNDL0351: Multiple source files ('obj\Debug\_MyProgram_file.wxs', 'obj\Debug\_MyProgram_file.wxs') have resulted in the same output file '...\obj\Debug\_MyProgram_file.wixobj'.  This is likely because the source files only differ in extension or path.  Rename the source files to avoid this problem. [...\PracticesChecker.Setup.wixproj]

* Which version of WiX are you building with?

3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

Visual Studio Enterprise 2019 16.6.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

1.0.0.4

**Comment by barnson** [comment]
Separate instances of `HarvestFile` for files with the same base name and different extensions should work. Globbing won't work without more work on the heat.exe side.

**Comment by paulomorgado** [comment]
heat.exe should just take a list of paths. If it's a file, it's a file harvest; if it's a directory, it's directory haverst.
