### ISSUE TITLE
Add ARM64 Burn

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6180]
If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Can build bundles to run natively on ARM64 versions of Windows

* Describe how you're accomplishing the feature today (if possible).

> Using the x86 stub and relying on the emulation layer in Windows.

* Describe what you'd like the new feature to do.

> See above

**Comment by barnson** [comment]
Let's have one tracking issue: https://github.com/wixtoolset/issues/issues/4579
