### ISSUE TITLE
Command-line Extension Acquisition and Cache

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6184]
* Describe the scenario and benefits that the feature supports.

> WiX Extensions are distributed via NuGet in WiX v4. This works well for project-based builds (.wixproj). But it requires many manual steps to use from the command-line build (download, extract, reference extracted location in `build` command). Ideally, the command-line would have a better mechanism.

* Describe how you're accomplishing the feature today (if possible).

> N/A

* Describe what you'd like the new feature to do.

> Provide a mechanism for the command-line to have an analogous behavior that package restore provides for .wixproj

[WIP](https://wixtoolset.org/development/wips/6184-command-line-extension-acquisition-and-cache/)

**Comment by rseanhall** [comment]
@robmen What happened to https://github.com/wixtoolset/Core/pull/141#discussion_r438103333?

**Comment by robmen** [comment]
I should have linked from that issue to this one to remind me why this was still open.
