### ISSUE TITLE
WiX v4 templates do not appear when making a new project in VS

### ISSUE THREAD

**Issue by calebh** [wixtoolset/issues#6185]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0.5205

* Which version of Visual Studio are you building with (if any)?

> 2017 and 2019

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> WiX v4 templates do not appear when using the WiX visual studio extension. Steps to reproduce: Install WiX v3 from the website, install WiX v4 from the website, install the VS extension (I tried both the 2017 and 2019 extensions), observe that v4 templates are not available when making a new project but v3 templates are.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected to see options for v4 templates but only saw options for v3 templates. Uninstalling/reinstalling doesn't help. Repairing the WiX installation doesn't help. The v4 templates are indeed installed when looking at the VS 2017 installer so I don't know why they don't appear. I have confirmed that this issue occurs on two different computers.

**Comment by robmen** [comment]
Votive does not support WiX v4 yet and WiX v4 is not ready for Votive. The templates were removed because they were incorrectly suggesting users could be successful using WiX v4 in Votive. :smile:

**Comment by calebh** [comment]
Is there some other way to generate a new WiX v4 project then?

**Comment by rseanhall** [comment]
If you're expecting to create a project and have everything work, you're going to be disappointed because v4 is not ready for that. Is it possible to handcraft an MSBuild project and use the bleeding edge v4? Possibly, but we're not going to document that because otherwise we're going to get a flood of bug reports about things that we just haven't gotten to yet.

**Comment by calebh** [comment]
That sucks. I have an existing WiX v4 project that has broken because the Wix.targets file has been moved. I was hoping to figure out the new path to put in the .wixproj file by creating a new v4 project and looking at the output.

I initially created the project in v4 since I was under the impression that v4 would become the standard moving forward.

**Comment by rseanhall** [comment]
Sorry. This is exactly why we started disabling the v4 templates.

If you were using the old version of v4, that theoretically should still work. Are you running into the VS2017/MSBuild15 issue where you need to update your project to find wix.targets? https://github.com/wixtoolset/issues/issues/5804#issuecomment-532663590

**Comment by robmen** [comment]
Note: v4 *will* become the standard. But only after going through a preview process... that we hope to start very soon. The v4 builds previously available for download were *very* early and look more like v3 than v4.

@calebh You'll probably be best served moving back to v3 before trying to move to forward to v4.

**Comment by calebh** [comment]
I was able to move back to v3 with minimal changes. Thanks for the help!

**Comment by franziseidl** [comment]
It's now two years later are there templates now?
