### ISSUE TITLE
Directory.Build.props and Directory.Build.targets are not picked up by WIX projects

### ISSUE THREAD

**Issue by paulomorgado** [wixtoolset/issues#6186]
> # [Directory.Build.props and Directory.Build.targets](https://docs.microsoft.com/visualstudio/msbuild/customize-your-build#directorybuildprops-and-directorybuildtargets)
> 
> Prior to MSBuild version 15, if you wanted to provide a new, custom property to projects in your solution, you had to manually add a reference to that property to every project file in the solution. Or, you had to define the property in a .props file and then explicitly import the .props file in every project in the solution, among other things.
> 
> However, now you can add a new property to every project in one step by defining it in a single file called Directory.Build.props in the root folder that contains your source. When MSBuild runs, Microsoft.Common.props searches your directory structure for the Directory.Build.props file (and Microsoft.Common.targets looks for Directory.Build.targets). If it finds one, it imports the property. Directory.Build.props is a user-defined file that provides customizations to projects under a directory.

This seems to bit be honored by WIX project.

* Which version of WiX are you building with?

3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

16.6.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

1.0.0.4

* Which version of .NET are you building with?

N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

N/A

* Describe the problem and the steps to reproduce it.

Add **Directory.Build.props** and/or **Directory.Build.targets** in any directory form the project directory upwards.

* Describe the behavior you expected and how it differed from the actual behavior.

The files are expected to be imported by the project but aren't.

**Comment by rseanhall** [comment]
As mentioned in the article:

> MSBuild projects that use the standard build process (importing Microsoft.Common.props and Microsoft.Common.targets) have several extensibility hooks that you can use to customize your build process.

WiX v3.x does not use Microsoft.Common.props or Microsoft.Common.targets. Doing this is a major breaking change and so can't be done in 3.x. This has already been done in v4.

**Comment by paulomorgado** [comment]
In the meantime, anyone wanting to support this, can just add these entries to the .wixproj file:

```XML
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props'))" Condition="Exists($([MSBuild]::GetPathOfFileAbove('Directory.Build.props')))" />

  <!-- project stuff -->

  <Import Project="$(WixTargetsPath)" />
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets'))" Condition="Exists($([MSBuild]::GetPathOfFileAbove('Directory.Build.targets')))" />
</Project>
```
