### ISSUE TITLE
Add support for excluding merge component and/or installing individual merge component

### ISSUE THREAD

**Issue by vgriph** [wixtoolset/issues#6188]
### Scenario

In some cases, when redistributing third party products which come with their own merge module, those modules may contain components that match components of other features in an installer.

An installer for product `P` has the features `F1` and `F2` installed to the same directory. `F1` uses a third party library `L1` distributed as a single dll. `F2` uses a third party library `L2` which is distributed as a merge module. `L2` also depends on `L1` and has included the `L1` dll in the merge module as component `MC1`. The `P` installer defines component `C1` for `L1` used by `F1`.

When installing both `F1` and `F2` the two components `MC1` and `C1` are both installed at the same target location with the same key path. This is undesirable since it makes it hard to detect problems in case either `MC1` or `C1` is updated to a later version. (With this feature request, that would of course cause other issues, but would be deterministic.)

### Achieving the desired behavior today
Today we are able to work-around the issue by using a component condition on `C1`:
```
$MC1 <> 3
```

I have also tested to manually edit the installer using Orca and replace all references to `C1` in the Feature table with `MC1` and delete `C1` from the Component table.

### Description of requested feature
This feature request is for a possibility to either:
* Exclude `MC1` from `F2` when using the `MergeRef`, or
* Reference `MC1` from `F1`using a `MergeComponentRef` or similar 

The ability to exclude a component from a merge module would also help with another scenario: To be able to patch `L1` without waiting for a new merge module being built by `L2` in case of a critical bug in `L1`.

**Comment by robmen** [comment]
The Merge Module spec and merge tools are provided by Microsoft. To get changes to that spec, you'd want to take the feature request to Microsoft.

However, you can accomplish what you want by switching to .wixlibs. Wixlibs were designed for this scenario.
