### ISSUE TITLE
Update MajorUpgrade to default to same-version upgrades

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6202]
When `MajorUpgrade` was created in v3.x, it did not enable same-version upgrades by default. We have decided to enable same-version upgrades by default in v4.0. (http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/2020-July/001691.html)

**Comment by barnson** [comment]
Retriage, please: We talked about this in the context of bundles, not packages.
