### ISSUE TITLE
Add support for high DPI to the Burn engine, Take 2

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6204]
If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Per-monitor DPI awareness mode for the process in Burn (`PerMonitor` was added in 8.1/Win10 1607 and enhanced to `PerMonitorV2` in Win10 1703). The current High-DPI documentation is at https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows.

* Describe how you're accomplishing the feature today (if possible).

> Before Win10 1703, not possible without replacing the Burn stub's manifest. Starting with Win10 1703, the BA could call [SetThreadDpiAwarenessContext](https://docs.microsoft.com/en-us/windows/desktop/api/Winuser/nf-winuser-setthreaddpiawarenesscontext) to set the DPI awareness mode for its windows but not the process. The current documentation on setting the DPI awareness mode is at https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process. This is required to be able to use the High-DPI functionality from https://github.com/wixtoolset/issues/issues/3920.

* Describe what you'd like the new feature to do.

> There are two choices - update the Burn stub's manifest or programmatically set the DPI awareness at startup. Either way, due to the limitations of Windows the engine has to set the DPI awareness mode for the process.

1. In https://github.com/wixtoolset/issues/issues/4541, we updated the Burn stub's manifest so that it declared `System` DPI awareness. The easiest thing to do (and what Windows recommends) is to update the manifest again to declare support for `PerMonitor` and `PerMonitorV2`. However, declaring the DPI awareness in the manifest forces all bundles to support per-monitor DPI awareness which may not be possible or practical if the BA is using an older UI framework.

2. Remove the DPI awareness from the manifest, and instead call [SetProcessDpiAware](https://msdn.microsoft.com/library/windows/desktop/ms633543.aspx)/[SetProcessDpiAwareness](https://msdn.microsoft.com/library/dn302122)/[SetProcessDpiAwarenessContext](https://msdn.microsoft.com/library/mt807676) based on the bundle authoring. This is a supported way of declaring the DPI awareness mode for the process, though it must be done before any windows are created in the process. This allows the bundle to decide which DPI awareness mode to use.

**Comment by BMurri** [comment]
Win10 1607 LTSC will continue to be supported until October 13, 2026 (1507 is actually supported until October 14, 2025).

Could we use that metadata in the authoring to select which manifest to use with the stub? It should boil down to little more than a simple added API call. Or am I simply overengineering things?

**Comment by rseanhall** [comment]
We've been discussing this on wix-devs (http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/2020-July/001695.html). I considered being able to alter the manifest during generation of the bundle, but decided I didn't want to make it easier for people to hack the manifest.
