### ISSUE TITLE
wixstdba Options page is broken in v4

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6206]
If this issue is a bug:

* Which version of WiX are you building with?

> WixToolset.Sdk 4.0.0-build-144 and WixToolset.Bal.wixext 4.0.51

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Win10 Build 18363

* Describe the problem and the steps to reproduce it.

> Build a bundle using `WixStandardBootstrapperApplication.RtfLicense` or `WixStandardBootstrapperApplication.HyperlinkLicense`. Run the bundle and go to the Options page.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect the page to work. Instead thmutil fails to load the page.

> [316C:6330][2020-07-07T07:31:03]e000: Error 0x80070490: Failed to show control 'InstallFolder' at index 10.
> [316C:6330][2020-07-07T07:31:03]e000: Error 0x80070490: Failed to show page controls.

**Comment by rseanhall** [comment]
I forgot to mention that ThmViewer can load the page with no problems.

**Comment by barnson** [comment]
`WixStandardBootstrapperApplication.HyperlinkLicense` and `WixStandardBootstrapperApplication.RtfLicense` both work as expected via `WixToolsetTest.Bal.BalExtensionFixture.CanBuildUsingWixStdBa` test.

#worksonmymachine

**Comment by rseanhall** [comment]
Confirmed. Weird, I have no idea what changed.
