### ISSUE TITLE
WiX should include `dotnet new` templates

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6207]
* Describe the scenario and benefits that the feature supports.

> To support command-line users, WiX should offer project and item templates via `dotnet new` like Votive does inside Visual Studio.

* Describe how you're accomplishing the feature today (if possible).

> Notepad

* Describe what you'd like the new feature to do.

> Support all the project templates (bundle, package, library, merge module?) and all the item templates that make sense.

**Comment by ericstj** [comment]
Just found this when doing a search for such a feature and would like to add a refcount. 👍

**Comment by barnson** [comment]
Great, now we're leaking memory...

**Comment by ericstj** [comment]
Naw, different keypath.
