### ISSUE TITLE
Language cleanup

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6219]
* Describe the scenario and benefits that the feature supports.

> Clean up deprecated bits of the language.

* Describe how you're accomplishing the feature today (if possible).

> Still parsing and documenting them.

* Describe what you'd like the new feature to do.

* `@src` attribute: Remove everywhere
* Replace children of `*Sequence` elements with `Standard` to reflect their status as standard actions.
* More to come?

**Comment by barnson** [comment]
- [ ] @src attribute: Remove everywhere
- [ ] ~~Replace children of *Sequence elements with Standard to reflect their status as standard actions.~~ for v4.0. Maybe think about it for v5.
- [ ] More?

**Comment by barnson** [comment]
- [ ] UX
- [ ] Another pass for deprecated

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/ps.xsd#L108
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/util.xsd#L685
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/util.xsd#L873
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L153
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L499
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L868
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L2055
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L2836
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L2843
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L2879
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L2886
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L2893
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L3120
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L3502
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L3552
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L3559
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L5410
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L5760
https://github.com/wixtoolset/doc/blob/00fed2aa489e42d4fb76b5196e5525c30803ba0c/src/xsd4/wix.xsd#L8539
