### ISSUE TITLE
[Screen reader - WIX - Options] Error is not identified while leaving empty/entering any text inside the 'Install location' edit box and selected 'OK' button.

### ISSUE THREAD

**Issue by tgugler** [wixtoolset/issues#6226]
If this issue is a bug:

* Which version of WiX are you building with?

> 3.14.0.1119

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> Not Applicable

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Not Applicable

* Describe the problem and the steps to reproduce it.

User Experience:
Screen reader user would miss to select the install location if there is no error has been identified after leaving empty/entering any texts inside the 'Install location' edit box.

Pre Requisite:
Download exe file from https://www.microsoft.com/en-us/download/details.aspx?id=54688 ​
​
Repro Steps:​
1. Launch the "NPS Extension For Azure MFA" setup file.​
2. Navigate to "MICROSOFT SOFTWARE LICENSE TERMS" popup window and select "Option" button.
3. Navigate to 'Install location' edit box of "Setup Options" popup window and leave empty or enter any text inside the edit box then select OK button.
4. Verify the issue.

Actual Result:
Error is not identified while leaving empty/entering any text inside the 'Install location' edit box and selected 'OK' button.

Expected Result:
Focus should move on 'Install location' edit box and should be highlighted in red color while leaving empty/entering any text inside it. The error message should occur as 'Enter file location in <format>'.

[MAS3.3.1_options.wmv.zip](https://github.com/wixtoolset/issues/files/5043420/MAS3.3.1_options.wmv.zip)

**Comment by barnson** [comment]
Custom bootstrappers can provide whatever validation they want. WixStdBA can't assume a particular edit control is a path.
