### ISSUE TITLE
Specifying inner text where it was previously allowed should be an error

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6237]
If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> An partially converted v3 file that is still using inner text would ideally not compile.

* Describe how you're accomplishing the feature today (if possible).

> Not.

* Describe what you'd like the new feature to do.

> Produce a compiler error for inner text in places that were allowed in v3.

For example, this currently compiles but doesn't work correctly:

    <Fragment>
        <BundleCustomDataRef Id='WixStdbaInformation'>
            <BundleElement>
                <BundleAttribute Id='LicenseFile'>!(wix.WixStdbaLicenseRtfName=license.rtf)</BundleAttribute>
            </BundleElement>
        </BundleCustomDataRef>
    </Fragment>

**Comment by rseanhall** [comment]
I think the actual example given was missed - the `Data`/`BundleAttribute` elements. Also, inner text was removed from the Bal extension and maybe others.

**Comment by barnson** [comment]
Existing code covers the v3 -> v4 case, so I'm taking further work out of Preview Zero.

**Comment by barnson** [comment]
Almost.

**Comment by rseanhall** [comment]
Bal.wixext: https://github.com/wixtoolset/Bal.wixext/commit/6241bbf88e61f07816ea8fd028d7aaeba6bc524e
Firewall.wixext: https://github.com/wixtoolset/Firewall.wixext/commit/8181317ba1b9f718b6e54ce13cba04351e464c01
Util.wixext: https://github.com/wixtoolset/Util.wixext/commit/cc20def99bbd0b28f19d90aee50d67f674738505

Also, the schema changes for Bal.wixext and Core need to be done in the doc repo.
