### ISSUE TITLE
Win 3.11.2 did not install on Win 10 Surface Pro with Win SDK 

### ISSUE THREAD

**Issue by Mjraza2000** [wixtoolset/issues#6239]
"
08/18/2020 06:06:58 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: The current OS Version '10.0.18362.0' is not in the supported version range '[6.1,6.3]'.
08/18/2020 06:06:58 AM - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: The current OS Version '10.0.18362.0' is not in the supported version range '[6.1,6.3]'.
08/18/2020 06:06:59 AM - Skipping non-applicable package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect: The current OS Version '10.0.18362.0' is not in the supported version range '[6.1,6.2)'.
08/18/2020 06:06:59 AM - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.7: The current OS Version '10.0.18362.0' is not in the supported version range '[6.1,6.2)'.
08/18/2020 06:06:59 AM - Skipping non-applicable package Microsoft.DiagnosticsHub.KB2882822.Win7: The current OS Version '10.0.18362.0' is not in the supported version range '[6.1,6.2)'.
08/18/2020 06:07:01 AM - Skipping non-applicable package Microsoft.Ancm.IIS.Msi: Required conditions are not satisfied: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
08/18/2020 06:07:01 AM - Skipping non-applicable package Microsoft.Ancmv2.IIS.Msi: Required conditions are not satisfied: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
08/18/2020 06:07:01 AM - Skipping non-applicable package Microsoft.Net.4.8.FullRedist: The current OS Version '10.0.18362.0' is not in the supported version range '[6.1.1,10.0.17763]'.
08/18/2020 06:07:01 AM - Skipping non-applicable package Microsoft.Azure.PowerShell: Required conditions are not satisfied: Not Powershell5
08/18/2020 06:07:02 AM - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu: The current OS Version '10.0.18362.0' is not in the supported version range '(,6.2)'.
08/18/2020 06:07:26 AM - Product finalizer failed to execute. Command executed: "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\common7\ide\vsfinalizer.exe" -Operation Modify -SKU Professional -InstallationID 1b005e3d -InstallationName VisualStudio/16.7.1+30406.217 -InstallationVersion 16.7.30406.217 -InstallationWorkloads Microsoft.VisualStudio.Workload.CoreEditor,Microsoft.VisualStudio.Workload.NetWeb,Microsoft.VisualStudio.Workload.Node,Microsoft.VisualStudio.Workload.ManagedDesktop,Microsoft.VisualStudio.Workload.NativeDesktop,Microsoft.VisualStudio.Workload.NetCrossPlat,Microsoft.VisualStudio.Workload.NativeMobile,Microsoft.VisualStudio.Workload.VisualStudioExtension,Microsoft.VisualStudio.Workload.NetCoreTools -InstallationPackages 
"
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?  3.11.2 

> (WiX version in major.minor.release.build format)  
[dd_VSIXInstaller_20200818060633_1bc0.log](https://github.com/wixtoolset/issues/files/5091420/dd_VSIXInstaller_20200818060633_1bc0.log)

* Which version of Visual Studio are you building with (if any)?
VS 2019 

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
