### ISSUE TITLE
[Visual Requirement - WIX - Modify Setup] Content of the 'Setup' pop-up is not visible properly when the screen is resized up to 400%

### ISSUE THREAD

**Issue by tgugler** [wixtoolset/issues#6241]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.0.14.1119

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> Not applicable

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Not applicable

* Describe the problem and the steps to reproduce it.

User Experience: 
If the content of the pop-up is not visible properly at 400% resize, the AT user will not able to access the content. The user will face difficulty while navigating through the screen.

Note: User credentials should NOT be included in the bug.

Pre-requisite:
Resize the screen up to 400%.

Repro Steps:
1. Launch the "NPS Extension For Azure MFA" setup file.
2. Navigate to "MICROSOFT SOFTWARE LICENSE TERMS" popup window and select "Install" button.​
3. After successful installation of Setup, again install the same setup.​
4. Navigate to "Modify Setup" popup window and select "Uninstall" button.​
5. Navigate all the controls of "Setup Progress/Setup Successful" popup window.
6. Verify the issue.

Actual Result:
Content of the 'Setup' pop-up is not visible properly when the screen is resized up to 400%.

Expected Result:
Content of the 'Setup' pop-up should be visible properly when the screen is resized up to 400%.

Note:
This issue exists throughout the application.

![MAS1 4 10_contents not visible](https://user-images.githubusercontent.com/12263599/91196487-0d98bb80-e6af-11ea-89ef-6b55ed86594d.png)

**Comment by rseanhall** [comment]
How is this different from the user setting a very low resolution for the monitor?

The wixstdba UI is configurable. If you want the contents of the window to be fully visible even with very low resolutions, then you can modify it to be smaller.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/3920

**Comment by rseanhall** [comment]
I don't think high-DPI is the issue here. If the theme is authored to be wider than the available resolution than you'll get this problem even without any scaling. I could be wrong, but I thought the high-DPI support in this scenario will only make the UI clearer and not make the actual window smaller.

**Comment by barnson** [comment]
I thought the screen shot was truncated. If it's "actual size," then yes, it's asking for layout. @tgugler, please confirm.

**Comment by rseanhall** [comment]
I tried it myself, this is actual size. Most of the window is off-screen.
