### ISSUE TITLE
light.exe creates "corrupt" .cab files

### ISSUE THREAD

**Issue by MarkoKaiser** [wixtoolset/issues#6242]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) mailing list.

## Discussions and support

Note that discussions are best held on the mailing lists, not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Bugs

If this issue is a bug:

* Wix 3.11.2318.0

>Wix 3.11.2318.0

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> Full Framework v4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Enterprise 1809 English us

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

We have a directory with two empty text files (filesize: 0). We build the msi and cab file with calls to candle and light.
Then click on the generated .cab file in the window explorer. It does not show any file items. There is no view of the file contents.
If you create a directory beneath the two empty files and then create the .cab/.msi file, you can see the content in the windows explorer if you click on it.
* 

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please attach a [Minimal, Complete, and Verifiable example][mcve] that demonstrates the problem.

[mcve]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by MarkoKaiser** [comment]
[Wix.zip](https://github.com/wixtoolset/issues/files/5173580/Wix.zip)

see this example

**Comment by barnson** [comment]
This appears to be a limitation in Windows's support for .cab files in Explorer. The following command works as expected:

    expand Test.cab -f:* cabout

And if you add a file that isn't zero bytes in size, Explorer can open the resulting .cab.
