### ISSUE TITLE
Unable to harvest reg entries from 64bit .Net DLL

### ISSUE THREAD

**Issue by forderud** [wixtoolset/issues#6244]
I'm experiencing the following error when attempting to harvest registry entries from a 64bit .Net DLL (assembly):
```
heat.exe(0,0): warning HEAT5150: Could not harvest data from a file that was expected to be a SelfReg DLL: filename.dll.
If this file does not support SelfReg you can ignore this warning. Otherwise, this error detail may be helpful to diagnose
the failure: Unable to load file: filename.dll, error: 193
```

Harvesting registry entries from the same DLL works nicely in 32bit, so the **problem appear to be 64bit-related**.

## Details

Observed with Windows Installer XML Toolset Toolset Harvester version 3.11.2.4516 when building a .Net Framework 4.5.2 project from Visual Studio 2019.

Steps to reproduce:
1. Clone reproducer project on https://github.com/forderud/WixIssues
2. Open solution from Visual Studio opened with administrative privileges.
3. Build projects for 64bit "x64" platform.
4. Observe `HEAT5150: Could not harvest data from a file that was expected to be a SelfReg DLL...` error.

The same projects build fine against the 32bit "x86" platform.

**Comment by barnson** [comment]
Heat doesn't support x64: https://github.com/wixtoolset/issues/issues/1661

**Comment by forderud** [comment]
@barnson Would it then be possible to update the heat doc on https://wixtoolset.org/documentation/manual/v3/overview/heat.html to clearly state this limitation?
