### ISSUE TITLE
WiX ignores ExePackage UninstallCommand

### ISSUE THREAD

**Issue by neil-leathers-modesttree** [wixtoolset/issues#6245]
* Which version of WiX are you building with?

> 3.11.4516.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 19041.450

* Describe the problem and the steps to reproduce it.

1. In a `Bundle` create a `Chain` with an `ExePackage` and another subsequent `MsiPackage`
2. Specify an `UninstallCommand` for the `ExePackage`. For example:
```
             <ExePackage
                 Id="gitinstaller"
                 SourceFile="git-installer.exe"
                 InstallCommand="git-installer.exe /VERYSILENT"
                 UninstallCommand="C:\Program Files (x86)\Git\cmd\unins001.exe"
                 />
```
3. Execute the resulting installer.
4. Allow the `ExePackage` to proceed successfully
5. During the subsequent `MsiPackage` install, cancel the install or trigger an error condition

* Describe the behavior you expected and how it differed from the actual behavior.

Expected: The `ExePackage` should uninstall using the `UninstallCommand`
Actual: The `ExePackage` executable will be called without arguments

**Comment by barnson** [comment]
Please attach a bundle log demonstrating the issue.

**Comment by neil-leathers-modesttree** [comment]
User problem: I mistakenly thought `UninstallCommand` was an uninstall command and would call an indicated uninstall program. I did not realize that if the `ExePackage` generates an uninstall program as above there is no way to call it.

(Perhaps `UninstallCommand` should be renamed `UninstallArguments` for clarity.)
