### ISSUE TITLE
Drop ARM (32-bit) support

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6246]
* Describe the scenario and benefits that the feature supports.

> 32-bit ARM was never a common target even at its (Windows RT) height and is being dropped (e.g., https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md) in general. It's supported in WiX v4 in both the core toolset and extensions.

* Describe how you're accomplishing the feature today (if possible).

> n/a

* Describe what you'd like the new feature to do.

> Supporting it in the toolset is trivial (it's already done and doesn't cost anything to keep). Supporting it in the extensions adds build time and .nupkg bloat -- we should remove it from the extensions and let it live in the toolset (along with historical support for Itanium).

**Comment by barnson** [comment]
Nuke ARM32 from everywhere. Look at Itanium support.

**Comment by barnson** [comment]
Implemented in 1.8 million commits across 704,102 microrepos.

**Comment by rseanhall** [comment]
Ideally the PR's for those commits would be linked to this issue. And balutil still has ARM32.
