### ISSUE TITLE
wixproj does not support PackageReference 

### ISSUE THREAD

**Issue by gabiganam** [wixtoolset/issues#6248]
Trying to migrate from packages.config to PackageReference.
Visual Studio 2019, latest WiX 3.11.2.

**Comment by robmen** [comment]
Support for `PackageReference` is coming in WiX v4.

**Comment by gabiganam** [comment]
Awesome!
Just out of curiosity, when is v4 estimated to be released?
What's the planned content?
I couldn't find such documentation or road map on the site...

**Comment by robmen** [comment]
You can [track progress of WiX v4 via the remaining issues](https://github.com/wixtoolset/issues/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.0) or the [status updates captured by FireGiant on their blog](https://www.firegiant.com/blog/).

**Comment by amikulich** [comment]
hi @gabiganam 

I'm curious if you managed to find any workaround? Or just get rid of a planned upgrade to package references?
