### ISSUE TITLE
WiX v3.11.2. doesn't include VS2019 SDK

### ISSUE THREAD

**Issue by voguhl** [wixtoolset/issues#6250]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

* Which version of WiX are you building with?

Release v3.11.2

* Which version of Visual Studio are you building with (if any)?

n/a

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

n/a

* Which version of .NET are you building with?

n/a

* Describe the problem and the steps to reproduce it.

The release includes libraries for different Visual Studio Versions, but Visual Studio 2019 is missing.

* Describe the behavior you expected and how it differed from the actual behavior.

There should be a folder sdk/vs2019 and there should be libraries compiled for visual studio 2019.

**Comment by voguhl** [comment]
Can this be solved analog to 
https://github.com/wixtoolset/wix3/pull/430/commits/e302bc704682af3cf7eff14d4454c63465f3d02e
?

**Comment by barnson** [comment]
WiX v3 doesn't support VS2019 in its build system so there are no native libraries for it. However, you can use VS2017 C++ libraries with VS2019.

**Comment by voguhl** [comment]
Can you tell me if you are planning to support Visual Studio 2019 in the future?

**Comment by barnson** [comment]
WiX v4 supports VS2019.
