### ISSUE TITLE
Driver installation on ARM64 does not work

### ISSUE THREAD

**Issue by eloi-loomai** [wixtoolset/issues#6251]
* Which version of WiX are you building with?

v3.14.0.4118

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2019 - 19.27.29111

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

v3.14.0.4118

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 - arm64

* Describe the problem and the steps to reproduce it.

I am trying to create a driver msi package for ARM64, my installer compiles fine for arm64, but when I add the directive:
```
              <difx:Driver AddRemovePrograms="no" Legacy="no" PlugAndPlayPrompt="no" Sequence='1' />
```

My package refuses to install while throwing this error:
![image](https://user-images.githubusercontent.com/42191593/94467113-19810d00-0188-11eb-975e-19ec4e376c80.png)

The compilation commands are the followings:
```
candle -ext "%WIX%\bin\WixUIExtension.dll" -ext "%WIX%\bin\WixDifxAppExtension.dll" -ext "%WIX%\bin\WixUtilExtension.dll" driver.wxs -arch arm64
light -ext "%WIX%\bin\WixUIExtension.dll" -ext "%WIX%\bin\WixUtilExtension.dll" -ext "%WIX%\bin\WixDifxAppExtension.dll" driver.wixobj "%WIX%\bin\difxapp_x64.wixlib" -o driver-arm64.msi
```

I suspect the `WixDifxAppExtension.dll` not to be compiled for arm64.

Is there any workaround? Like x86 emulation?

**Comment by barnson** [comment]
Microsoft never shipped DifxApp for ARM64 that we're aware of, so we don't have any ARM64 custom actions to link against. You'd need to convince Microsoft to un-deprecate DifxApp and add support for ARM64.

We'll keep this issue open to consider adding an error message to WixDifxAppExtension when building for ARM64.

**Comment by everton1984** [comment]
@barnson Do you know who is responsible to release DifxApp exactly? I would like to raise an issue there as this is relevant for me.

**Comment by barnson** [comment]
It came in the WDK.

**Comment by robmen** [comment]
@everton1984 Maybe suggest they release the DifxApp source code. Then, we could consider moving it forward. :smile:

**Comment by everton1984** [comment]
@robmen :) 
@barnson  Where exactly on the WDK is the DIFxAPP.dll? I have it installed here but can't find that particular DLL or is the name different on the WDK? I want to mount a full case before talking to Microsoft.  Thanks a lor for helping btw.

**Comment by barnson** [comment]
It's deprecated and hasn't shipped in years: https://learn.microsoft.com/en-us/windows-hardware/drivers/install/difx-guidelines

**Comment by barnson** [comment]
WixToolset.DifxApp.wixext was deprecated in WiX v4 and removed in WiX v5.
