### ISSUE TITLE
light.exe error LGHT0001

### ISSUE THREAD

**Issue by vr333dev** [wixtoolset/issues#6256]
Hi, when a solution with wixproj is being built, and light.exe is called, we keep seeing this error:

light.exe : error LGHT0001: A required privilege is not held by the client [C:\Gitlab-Runner-...\build...app\installer\....Installer.wixproj]
  
  Exception Type: System.ComponentModel.Win32Exception
  
  Stack Trace:
     at Microsoft.Win32.NativeMethods.CreateDirectory(String path, SafeLocalMemHandle acl)
     at System.CodeDom.Compiler.TempFileCollection.CreateTempDirectoryWithAce(String directory, String identity)
     at System.CodeDom.Compiler.TempFileCollection.GetTempFileName(String tempDir)
     at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
     at Microsoft.Tools.WindowsInstallerXml.WixBinder.get_TempFilesLocation()
     at Microsoft.Tools.WindowsInstallerXml.WixBinder..ctor()
     at Microsoft.Tools.WindowsInstallerXml.Binder..ctor()
     at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)

Following documentation we've added WIX_TEMP environment variable to a simple/short path on the C: drive.  Also tried to manipulate folder permissions between GitLab runner (windows, shell executor, which calls the MSBuild component), Wix tools in Program Files (x86) and the C:\Temp\WixTemp folder (referenced by environment var).  I've also tried to install WIX extension to Visual Studio, but that didn't work, and I didn't think it would matter since light.exe is being called directly when building the app.  

Any ideas on how to diagnose this issue please? Research didn't help either - https://github.com/wixtoolset/issues/issues/5920
More information below...

Thanks

Vlad

##Bug (potentially):

* Which version of WiX are you building with?
3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
VS Enterprise 2017 15.9.27

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
We're using MSBuild to build a solution with wixproj

* Which version of .NET are you building with?
.NET framework 4.7.2 SDK

**Comment by barnson** [comment]
Looks like a duplicate: https://github.com/wixtoolset/issues/issues/5920

**Comment by vr333dev** [comment]
Thanks, so bottom line is that this issue will be resolved in WIX 4.x release?

Thanks

**Comment by vr333dev** [comment]
Because providing WIX_TEMP (even if the location is a Temp folder side by side with Light.exe) doesn't resolve the error unfortunately, and GitLab-runner service runs under an Admin account on our agent.

Thanks

Vlad

**Comment by robmen** [comment]
Yes, this is already resolved in WiX v4.

**Comment by vr333dev** [comment]
Leaving GitLab runner Log On as Local System resolved the issue for me.  GitLab runner is the agent which builds wixproj to create the MSI, FYI.
