### ISSUE TITLE
WixConverter should fix `$` prefixes to the `!` given that `$` was deprecated and is no longer supported.

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6262]
* Which version of WiX are you building with?

> 4.0.0-build-0160

* Which version of Visual Studio are you building with (if any)?

> n/a

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> n/a

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a

* Describe the problem and the steps to reproduce it.

> `$` as a prefix for loc variables was deprecated in the long-ago time and v4 drops support for it. WixConverter should detect and fix such references.

* Describe the behavior you expected and how it differed from the actual behavior.

> Being surprised when loc no longer happens.

**Comment by cpuwzd** [comment]
I've been looking into this issue and would like to try to correct it. Please assign it to me.

**Comment by cpuwzd** [comment]
Has anyone had a chance to review this pull request yet?
