### ISSUE TITLE
Proposed Change: Add custom action and launch condition that handles .NET Core 3.1 / .NET 5.0 runtime install checks

### ISSUE THREAD

**Issue by MSLukeWest** [wixtoolset/issues#6264]
* Describe the scenario and benefits that the feature supports.

Right now NetFxExtension has good support for checking if a .NET Framework is installed using an extension, but similar support does not exist for .NET Core 3.1 / .NET 5.0.  Checking if a runtime is installed is more complex now than it was for .NET Framework because:

1. There's separate runtimes for each Windows platform (x86/x64/arm64)
2. There's three different runtimes: Core (Called just ".NET Runtime" in 5.0), Desktop and ASP.NET

So I think it would be beneficial to wrap the checks in custom element that correctly handles the complexities of the runtime check.

* Describe how you're accomplishing the feature today (if possible).

There's two ways of accomplishing this today:

1. Using a combination of path and registry checks.  This isn't great because it requires knowing exactly what to check for each kind of runtime, and because it can never cover all different ways of installing the runtimes.  For example, different registry keys are written when installing the runtimes through the Visual Studio installer.
2. Using a custom action that calls public .NET APIs that can correctly check if the runtime requirement is satisfied.  This works well and is what I'd like the new elements to do internally, more details below.

* Describe what you'd like the new feature to do.

I think usage would look something like this:

<netfx:CheckNETRuntimeCustomAction Id="CheckNETRuntimeCA" RuntimeVersion="5.0.0" RuntimePlatform="x86" Framework="Desktop" />
<netfx:CheckNETRuntimeLaunchCondition />

Internally, it would use the NETCoreCheck tool, built and published in the .NET repo here: https://github.com/dotnet/deployment-tools/tree/master/src/clickonce/native/projects/NetCoreCheck.  This tool is what's currently being used by the bootstrapper packages used by Visual Studio Installer Projects.  We just refactored it into a custom actions assembly, which is what would be used here.  For details on how the tool works and why it was necessary see the following thread: https://github.com/dotnet/runtime/issues/36479.

It's debatable whether or not we actually would need a custom element for the launch condition itself since it's just a property check.  I think the main value here would be having a consistent message that also contains a link telling people where to install the necessary runtime from.

I would like this to be used in Win3, so it looks like the right place to make these changes would be here: https://github.com/wixtoolset/wix3/tree/develop/src/ext/NetFxExtension.  I would then port these changes to the NetFx repo: https://github.com/wixtoolset/Netfx.wixext

**Comment by MSLukeWest** [comment]
@SvetBonev @japarson

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6257

**Comment by rseanhall** [comment]
Some thoughts:
* This is basically the MSI version of the issue I created at https://github.com/wixtoolset/issues/issues/6257.
* As I mentioned in my comments in https://github.com/dotnet/runtime/issues/36479, the approach for `NetCoreCheck` irreversibly loads part of the .NET runtime into the process. Therefore it is not appropriate for custom actions because CA's are in-proc.
* We normally refer to `<netfx:CheckNETRuntimeCustomAction />` as a custom element, or an extension element, not a custom type.

**Comment by SvetBonev** [comment]
> * As I mentioned in my comments in [dotnet/runtime#36479](https://github.com/dotnet/runtime/issues/36479), the approach for `NetCoreCheck` irreversibly loads part of the .NET runtime into the process. Therefore it is not appropriate for custom actions because CA's are in-proc.

This is a valid concern for installers that might want to check for multiple versions of .NET Core.
Suggestions for how to tackle this?
- Prevent it at link time;
- Allow it and run the NetCoreCheck executable from the DLL CA;
- Fix the hostpolicy issue (long shot);
- Something else?

**Comment by MSLukeWest** [comment]
What if we had the schema prevent multiple uses of this action?  Or possibly make multiple uses a warning?

And what kind of failure do we expect if the runtime is loaded twice?  I tested this by creating a WiX package that runs this custom action 10 times in a row, switching the version to try each time (3.1.0 -> 5.0.0-rc.2 -> 3.1.5 -> 5.0.0-rc.2 -> 3.1.0, etc.), and it ran without issue.  Would you expect this to fail?

**Comment by rseanhall** [comment]
Restricting it to only run once doesn't avoid the problem. The `NetCoreCheck` approach assumes that it's the only one trying to use the `hostfxr` APIs. Since it's not our process, we can't make that assumption. If someone else in the process actually started the runtime through the hostfxr API's, then the behavior of `hostfxr_initialize_for_runtime_config` is different (I don't remember the details of it off the top of my head).

Fixing the issue in .NET also doesn't help because there are already versions out there with the current behavior.

Ideally, .NET Core would be writing to a central location with the version number but they're not doing that today. .NET 3 and 5 use Burn bundles so we might be able to leverage off of that.

Otherwise, we might have to resort to somehow use the `NetCoreCheck` approach in a separate process like embedding an exe in the MSI or the custom action dll.

**Comment by SvetBonev** [comment]
The process running the code will be the server CA process that will go away once the MSI install is complete. I can see future authors writing .NET Core-based CAs, though, IMO, the probability is low. 

I wouldn't count on the .NET bundles' detection keys - they are not documented to my knowledge.

Embedding the NetCoreCheck tool as a Binary is probably the most viable option at the moment.

**Comment by robmen** [comment]
Note: CustomAction servers are reused by the Windows Installer for CustomActions of the same type. That makes @rseanhall's concern very real. It is also why managed CustomActions are executed out of proc as well.

Note2: The change needs to go into WiX v4 first. New features are not generally being accepted into WiX v3 but we can discuss the value in doing so.

**Comment by rseanhall** [comment]
> I wouldn't count on the .NET bundles' detection keys - they are not documented to my knowledge.

Maybe that's a difference between this issue and https://github.com/wixtoolset/issues/issues/6257, then. In that one, we really are interested in whether the bundle (or a future bundle in the same family) has been installed or not. Here, we seem to be more interested in whether a specific app can actually run.

**Comment by MSLukeWest** [comment]
> Otherwise, we might have to resort to somehow use the `NetCoreCheck` approach in a separate process like embedding an exe in the MSI or the custom action dll.

My first idea was to embed NETCoreCheck.exe into the msi and use it, but I couldn't find any way in wix to launch an exe in a custom action and then use it's return code, it just fails the install if zero isn't returned, which isn't what we need.  Please correct me if I'm wrong here, or if there's a good way to work around this (other than launching the exe from inside the custom action dll).

> Note2: The change needs to go into WiX v4 first. New features are not generally being accepted into WiX v3 but we can discuss the value in doing so.

Understood.  Whatever I end up doing I'll do in v4 first.

**Comment by barnson** [comment]
Exe custom actions can't set properties. Only DLLs can.

**Comment by rseanhall** [comment]
No matter which way we go, this will add a new table-driven CA to the existing netfx CA dll. We're just discussing how that actually detects .NET Core.

**Comment by SvetBonev** [comment]
> Maybe that's a difference between this issue and #6257, then. In that one, we really are interested in whether the bundle (or a future bundle in the same family) has been installed or not. Here, we seem to be more interested in whether a specific app can actually run.

This is a fair observation. From customer standpoint, do you see the bundle question to be critical to answer? If so, we might want to discuss it separately and perhaps come up with a proposal for the .NET team.
My opinion is that it is ultimately a question whether the packaged application will run or not.

**Comment by rseanhall** [comment]
Because of roll-forward policies, there is a big difference between detecting whether a certain runtime is installed (#6257) and whether a suitable runtime is installed (the direction we seem to be going). I think the `NetCoreCheck` approach is the only supported way to detect whether a suitable runtime is installed, but that would either require the app's actual config or being able to specify all the roll-forward options along with the version, platform, and framework type (core/desktop/aspnet).

**Comment by barnson** [comment]
I'm less concerned with enabling an MSI to block than I am in a bundle to make it "just work." (Usually we get the former for free when we do the latter.)

**Comment by rseanhall** [comment]
For these kinds of checks, MSI's are typically interested in whether a certain piece of software is installed or not. Then it's up to the MSI to decide how to proceed (warn the user, block the install, etc). Trying to do a runtime check of whether the app will actually run or not during the install without actually trying to run the app is probably not worth the effort.

For what it's worth, I did some research and I think for https://github.com/wixtoolset/issues/issues/6257 we should parse the output of the `--list-runtimes` command to determine what's installed. More research will be needed to determine whether to try to locate the different architectures of `dotnet.exe` or create our own exes to run it through `hostfxr_main`.

**Comment by MSLukeWest** [comment]
I know that historically we just check if a certain piece of software is installed, but if we can answer the question "will my app run" I think that's even better, especially given the previously mentioned complexities of .NET Core runtime acquisition.  I'm talking specifically about launch conditions here, not https://github.com/wixtoolset/issues/issues/6257.

So I think there's a way to still take advantage of the NETCoreCheck method without loading the runtime in proc.  We'd add NETCoreCheck.exe to the Binary table, and then add a new custom action to the existing netfx CA dll which spawns one or more NETCoreCheck.exe processes, using their return values to set properties that can then be checked using a launch condition.  In this scenario the usage looks the same as in my original post, it's just a different implementation.

Any concerns with this approach?

**Comment by rseanhall** [comment]
It's verifying more than just whether the runtime is installed so the name of the element needs to properly reflect that.

The NETCoreCheck approach is going to fail in more scenarios because it's actually loading and running portions of the runtime (what if some file got corrupted? That's normally not something an installer cares about).

Bringing in outside .exes makes things more complicated. For example, in order to work under Device Guard configurations that require signed code they will need to be signed. We won't be signing .exes that we didn't compile.

I would rather time be spent on code that can be shared with https://github.com/wixtoolset/issues/issues/6257, but maybe other people would rather have this kind of check.

**Comment by MSLukeWest** [comment]
> The NETCoreCheck approach is going to fail in more scenarios because it's actually loading and running portions of the runtime (what if some file got corrupted? That's normally not something an installer cares about).

Since NETCoreCheck only loads hostpolicy.dll + hostfxr.dll this seems fairly unlikely.

> Bringing in outside .exes makes things more complicated. For example, in order to work under Device Guard configurations that require signed code they will need to be signed. We won't be signing .exes that we didn't compile.

NETCoreCheck.exe is already being signed, as it's distributed by the Visual Studio installer.

**Comment by barnson** [comment]
Is there a public NuGet package with the signed .exe?

**Comment by MSLukeWest** [comment]
> Is there a public NuGet package with the signed .exe?

We have a NuGet package with the signed .exe, and we're in the process of publishing it to the public feed.  ETA 1-2 weeks.

**Comment by MSLukeWest** [comment]
> > Is there a public NuGet package with the signed .exe?
> 
> We have a NuGet package with the signed .exe, and we're in the process of publishing it to the public feed. ETA 1-2 weeks.

We now have public NuGet packages for NETCoreCheck with signed .exes:

https://www.nuget.org/packages/Microsoft.NET.Tools.NETCoreCheck.x86/5.0.0 
https://www.nuget.org/packages/Microsoft.NET.Tools.NETCoreCheck.x64/5.0.0

I'll pick this back up after there's more clarity around how we're going to deal with #6257

**Comment by rseanhall** [comment]
Hi @MSLukeWest and @japarson, we are getting closer to releasing 4.0.0-preview.1 which is supposed to include all new features planned for v4.0. Are you guys planning on picking this and https://github.com/wixtoolset/issues/issues/6257 up anytime soon?

**Comment by MSLukeWest** [comment]
> Hi @MSLukeWest and @japarson, we are getting closer to releasing 4.0.0-preview.1 which is supposed to include all new features planned for v4.0. Are you guys planning on picking this and #6257 up anytime soon?

@rseanhall @japarson  Thanks for checking in Sean.  We don't have an ETA for this yet but we can consider resuming this work.  sometime soon.  Can you point me to more details on the proposed release schedule for Wix v4 so we can get a better idea of the timeline?

**Comment by robmen** [comment]
You can see the WiX v4 preview.1 (feature complete) issues: https://github.com/wixtoolset/issues/issues?q=is%3Aopen%20is%3Aissue%20project%3Awixtoolset%2Fissues%2F2

There are still a couple of hard work items in that list so the end of May would be the earliest timeframe I'd expect but the end of June seems more likely.

(I added this item to wix4-preview.1 so it is tracked appropriately)

**Comment by rseanhall** [comment]
We don't normally create a firm release schedule. If you need more than a couple of months of lead time, then I would recommend starting to get this work on your schedule.

**Comment by StefanStojanovic** [comment]
Hi everyone, I'm planning to continue work on this issue. Based on what I heard from Luke and James, final solution was going in [this direction](https://github.com/wixtoolset/issues/issues/6264#issuecomment-721382014). Is this still the path we want to move things forward or was something changed in the meantime?

**Comment by rseanhall** [comment]
The design was written up at https://wixtoolset.org/development/wips/6264-add-dotnet-runtime-compatibility-check/. There was some discussion at http://lists.wixtoolset.org/pipermail/wix-devs-wixtoolset.org/2021-January/001928.html. You can probably focus on the MSI implementation to start with since I'm working on https://github.com/wixtoolset/issues/issues/6257 for bundles.

**Comment by Adinihal** [comment]
hi @robmen  is target framework net6.0-windows supports in wix project (<ProductVersion>3.10</ProductVersion>) or do I need to update it to work with .net 6, because after a successful build I am unable to install the artifacts(packages) in my local machine it says failed to install the msi.
