### ISSUE TITLE
PDF User Documentation

### ISSUE THREAD

**Issue by mbarnet** [wixtoolset/issues#6267]
## Feature requests

If this issue is a feature request:

* Providing a downloadable PDF of the online user documentation provides the following features not available with the Web version:

1. Searchable text
2. Printable
3. Available off-line

* Describe how you're accomplishing the feature today (if possible).
Not possible due to web site limitations.

**Comment by barnson** [comment]
In WiX v3, wix.chm is available for offline viewing. There are no plans to do so in WiX v4: web sites have won and searching is more important. However, all the doc is available so anyone could create CHM, PDF, EPUB, or other types.
