### ISSUE TITLE
How to run an exe depending upon 32/64 bit and edit 

### ISSUE THREAD

**Issue by imranbaloch** [wixtoolset/issues#6270]
I wanna create an MSI file with the following requirement,

1) If client OS is 32 bit then run `My32BitService.exe -install` and run `My64BitService.exe -install` from the command prompt.
2) Put all the required files in the same directory as we have My32BitService/My64BitService.
3) Check if we have an entry of `127.0.0.1       mycustomdomain.ae` inside `C:\Windows\System32\drivers\etc`. If no entry then inserts it otherwise don't do it.

Is this is possible with WIX?

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.
