### ISSUE TITLE
Add exe launch utility to the Burn engine for detection purposes

### ISSUE THREAD

**Issue by japarson** [wixtoolset/issues#6272]
* Describe the scenario and benefits that the feature supports.

> Right now, the Burn engine supports .NET Core runtime installation detection using a combination of path and registry checks. As discussed in [dotnet/runtime#36479](https://github.com/dotnet/runtime/issues/36479), this strategy is not sufficient for robust runtime installation detection.
> 
> An alternate solution is to use the the NETCoreCheck tool, built and published in the .NET repo here: https://github.com/dotnet/deployment-tools/tree/master/src/clickonce/native/projects/NetCoreCheck. Using this tool in the Burn engine would allow us to easily handle runtime dependency installation for NetFx.wixext .NET Core packages, including newer version detection #6257 . This strategy would also be consistent with Luke's proposal for launch condition runtime detection #6264 .
> 
> The issue is that there does not appear to be any way to run an executable and use the return code in the Burn engine.

* Describe how you're accomplishing the feature today (if possible).

> I'm not sure this is possible today. The [Util schema](https://wixtoolset.org/documentation/manual/v3/xsd/util/) does not describe anything similar to an ExecutableRun element.

* Describe what you'd like the new feature to do.

> The new feature should allow executables to be run in the Burn Engine and the returns code to be available after execution. If this does not already exist today, we can add it to [Util.wixext](https://github.com/wixtoolset/Util.wixext).

**Comment by rseanhall** [comment]
In v4, I already added the ability for WiX extensions to include a bundle extension in the bundle to perform custom searches: https://github.com/wixtoolset/issues/issues/5539 ([WIP](https://wixtoolset.org/development/wips/5539-modularize-burn-searches/)).

**Comment by SvetBonev** [comment]
Curious if the bundle extension model will work well for Packages that want to do their detection in a modular fashion within their own fragment. The example is not clear on this.

**Comment by rseanhall** [comment]
The WIP didn't provide any examples with user code, that XML is the bundle's manifest.xml that is generated by the toolset. That's because the goal was for user code to continue working as before.

For #6257, we would create a new custom element in the NetFx namespace. I haven't really thought about it, maybe something like `<netfx:DotNetCoreRuntimeSearch Type='desktop' Platform='x86' Version='5.0.0' Variable='DOTNET_5_X86_DESKTOP_EXISTS' />`. That would replace the existing `util:DirectorySearch` we have today. That gets compiled and ordered along with all the other searches in the bundle. During runtime, the NetFx bundle extension would execute that search.

**Comment by SvetBonev** [comment]
Yes, doing it in the netfx extension will work fine - the idea for this proposal is to abstract it a little so that other packages can use it too.

**Comment by rseanhall** [comment]
I'm hearing that you want something like an `ExeSearch` element in the core toolset where Burn will run the given .exe during `Detect` and set a variable based on the result. That is different from what I have done in #5539.

**Comment by SvetBonev** [comment]
Not necessarily in the core toolset but in the util extension (not sure if you consider the util extension to be a part of the core toolset).

**Comment by barnson** [comment]
Given the limited amount of data that can be returned, we don't think this is generally useful for detection purposes.

**Comment by SvetBonev** [comment]
Hi Bob, could you elaborate on scenarios that would require richer data set to be returned?
Not disagreeing with your resolution, but I would like to understand how we can improve the proposal.

**Comment by barnson** [comment]
You're limited to exit code (and maybe stdout/stderr, though that's of questionable utility). That works for .NET detection but seemed limited for a general-purpose solution. We couldn't think of other cases where an .exe is required, for example. Most detection doesn't require executing code and if it does, the code can generally run in-proc. We're also a little concerned about appearing to support running arbitrary .exes from the BA.

**Comment by robmen** [comment]
I'd add that this feature could be implemented using a BundleExtension. Thus, the primitives are available in the Burn engine so if lots of people wanted a high-level "syntactic sugar" feature like `foo:ExeSearch` could be introduced. This way the core engine is no more complex than it needs to be.

**Comment by japarson** [comment]
Hi @robmen, could you help me understand which Burn engine primitives can be used to search for, execute, and read stdout from an exe?

**Comment by rseanhall** [comment]
As I mentioned in my [first comment](https://github.com/wixtoolset/issues/issues/6272#issuecomment-730023927), the engine primitive is the BundleExtension which allows a WiX extension to insert a search into the bundle that runs its own custom code at runtime. You can look at the [`WindowsFeatureSearch`](https://github.com/wixtoolset/Util.wixext/pull/20/commits/2813f4c7b61a3b4adfcbbc7e27f18b867fba02df) in Util.wixext as an example extension search.
