### ISSUE TITLE
Export from MSI

### ISSUE THREAD

**Issue by a8nJ** [wixtoolset/issues#6276]
If I get this file:

https://static.rust-lang.org/dist/rust-1.48.0-x86_64-pc-windows-gnu.msi

I try to extract like this:

~~~
dark -v -x . rust-1.48.0-x86_64-pc-windows-gnu.msi
~~~

but I just get a bunch of files like this:

~~~
fil0A0E0313BD2399519BAED65874B4E760
~~~

**Comment by robmen** [comment]
For support please contact the [wix-users mailing list](http://wixtoolset.org/documentation/).

It is possible through discussion a specific bug in the WiX Toolset will be uncovered but usually someone can help you find the error in your .wxs code.

**Comment by a8nJ** [comment]
http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2020-November/009462.html
