### ISSUE TITLE
Dark exception when extracting a bundle with detached containers

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#6298]
* Which version of WiX are you building with?
3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
VS 2019 v6.8.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
VS 2019

* Which version of .NET are you building with?
.NET Framework 4.8

* Describe the problem and the steps to reproduce it.
Create a bootstrapper project with detached containers.
Execute dark.exe to extract the packages
Getting an exception:
dark.exe : error DARK0001 : Could not find file 'D:\Projects\Tests\Bootstrapper-Detached-Container\Bootstrapper-Detached-Container\bin\Debug\Bootstrapper_Detached_Container\AttachedContainer\a0'.

Exception Type: System.IO.FileNotFoundException

Stack Trace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Microsoft.Tools.WindowsInstallerXml.BurnReader.ExtractAttachedContainer(String outputDirectory, String tempDirectory)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.UnbindBundle(String bundleFile, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Unbinder.Unbind(String file, OutputType outputType, String exportBasePath)
   at Microsoft.Tools.WindowsInstallerXml.Tools.Dark.Run(String[] args)
> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.
Dark successfully extracts the detached cabinets

See attached solution that demonstrates the issue
[Bootstrapper-Detached-Container.zip](https://github.com/wixtoolset/issues/files/5688996/Bootstrapper-Detached-Container.zip)

**Comment by rseanhall** [comment]
Is there any chance you can add a failing test for this in https://github.com/wixtoolset/Core?

**Comment by nirbar** [comment]
I'm not familiar with the new code structure... 
Where's dark?

**Comment by rseanhall** [comment]
`dark` is now `wix.exe decompile`. You can see some decompiling tests in [`DecompileFixture`](https://github.com/wixtoolset/Core/blob/85deb61f666f6817c1a137ace4d666c8ae2940fb/src/test/WixToolsetTest.CoreIntegration/DecompileFixture.cs#L12). For the MSI's, we've been checking them in because most of them can't be created by WiX. For bundles, I would prefer that the test build the bundle and then decompile it since we don't have to deal with bundles created by third party software.

**Comment by nirbar** [comment]
Added the test- https://github.com/wixtoolset/Core/pull/204

**Comment by rseanhall** [comment]
`dark` doesn't support extracting detached containers, this only happens in your fork of WiX.
