### ISSUE TITLE
dialog on zooming the screen content to 400% both the scrollbar appear to view the screen

### ISSUE THREAD

**Issue by lren** [wixtoolset/issues#6300]
Please provide answers to the following questions to help us narrow down, reproduce, and fix the problem. Fill out one section and delete the others.

## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.1

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> (Windows version)
windows 10

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

Environment Details:
Application Name: Azure Rights Management
Windows Version: Windows10​
Screen reader: Narrator, NVDA (2019.2.1)

Pre-requisite:
Go to system setting->Display and Set the desktop resolution value to 1280 x 1024 and set the size of text to 400%.
 
Repro Steps:
1. Select and download #Url :https://www.microsoft.com/en-us/download/details.aspx?id=38396
2. "Welcome to Active Directive Right screen will open.  
3. Observe if all the data on the screen can be viewed with one of the scrollbar.

Actual:
When the users zoom the screen content to 400% the data on the screen can be viewed with both the scrollbar i.e. Vertical and Horizontal which is incorrect as just one of the scrollbar should be available

The same issue observed throughout the application.

Expected:
The data on the screen should be viewed with only one of the scrollbar when zoomed to 400%.

User Impact:
When users zoom the screen content to 400% and if they have to view the screen content with both the scrollbar then they will find difficulty in viewing and reading the content present on the screen.

## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (Provide lots of specific detail so we understand the context around the feature.)

* Describe how you're accomplishing the feature today (if possible).

> (Be as specific as you can and err on the side of providing too much information.)

* Describe what you'd like the new feature to do.

> (There's no need to design it but suggestions are appreciated.)

**Comment by barnson** [comment]
Please attach a screen shot.

**Comment by lren** [comment]
![6364958_ A11y_Azure Rights Management_Welcome to Active Directive Right_Zoom](https://user-images.githubusercontent.com/7862400/102122869-fe26b500-3dfa-11eb-8e51-900fc25b8815.png)

**Comment by barnson** [comment]
What behavior are you expecting?

**Comment by rseanhall** [comment]
I got curious so I tried it myself. This is an MSI, not wixstdba. I'm too lazy to see if this is a duplicate to one of the many accessibility bugs that are already open.

**Comment by barnson** [comment]
Yes, so we're limited to what we can do.

**Comment by barnson** [comment]
MSI UI doesn't have any kind of layout capabilities.
