### ISSUE TITLE
Add DotNetRuntimeSearch to the NetFx extension for the detection of .NET Core/.NET 5 runtimes

### ISSUE THREAD

**Issue by japarson** [wixtoolset/issues#6311]
* Describe the scenario and benefits that the feature supports.

> Right now, the NetFx extension supports .NET Core/.NET 5 runtime detection using a combination of path and registry checks. As discussed in [dotnet/runtime#36479](https://github.com/dotnet/runtime/issues/36479), this strategy is not sufficient for robust runtime installation detection.
> 
> An alternate solution is to use the the NETCoreCheck tool, built and published in the .NET repo here: https://github.com/dotnet/deployment-tools/tree/master/src/clickonce/native/projects/NetCoreCheck. Using this tool in the NetFx extension would allow us to easily handle runtime dependency installation for .NET Core package definitions, including newer version detection #6257 . This strategy would also be consistent with Luke's proposal for launch condition runtime detection #6264 .
> 
> I'm proposing that we create a DotNetRuntimeSearch that would allow us to run the NETCoreCheck tool and use the result as a condition to install a .NET runtime package.

* Describe how you're accomplishing the feature today (if possible).

> The current solution is to use a combination of path and registry checks for .NET Core/.NET 5 runtime installation detection, which is not robust.

* Describe what you'd like the new feature to do.

> The DotNetRuntimeSearch would be implemented as an extension search as defined by this [WIP](https://wixtoolset.org/development/wips/5539-modularize-burn-searches/). I've designed a preliminary schema for this search [here](https://github.com/japarson/doc/commit/13703dd0e0caf3f825cd7127cff312d5fbd89e4b).

**Comment by rseanhall** [comment]
You seem to be proposing an implementation for https://github.com/wixtoolset/issues/issues/6257. The process for that is to create a WiX Improvement Proposal as described in https://wixtoolset.org/development/wips/0000-wix-improvement-proposal/ and then we would discuss that on the [wix-devs mailing list](https://wixtoolset.org/documentation/mailinglist/). Thanks.

P.S. In your WIP, I would be interested to know why you think the NetCoreCheck tool should be used when the .NET Core SDK team is currently proposing a different way to detect which runtimes are installed in https://github.com/dotnet/sdk/issues/15021.

**Comment by japarson** [comment]
Oh, I see. Sorry for the duplicate issue! I will create a WIP that addresses your concerns.
