### ISSUE TITLE
RollbackBoundary is always discarded when at the beginning of the chain

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6312]
* Which version of WiX are you building with?

> WixToolset.Sdk.4.0.0-build-176

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Author `RollbackBoundary` at the beginning of the chain - see failing test at https://github.com/wixtoolset/Core/blob/da9e593a5c044cf5430b071dd194b9d94877c4e1/src/test/WixToolsetTest.CoreIntegration/RollbackBoundaryFixture.cs#L13.

* Describe the behavior you expected and how it differed from the actual behavior.

> It works in v3.

```
Output: C:\src\mynewwix4\Core\build\Debug\netcoreapp2.1\TestData\RollbackBoundary\BeginningOfChain.wxs(5) : warning TEST1129: The RollbackBoundary 'nonvital' was discarded because it was not followed by a package. Without a package the rollback boundary doesn't do anything. Verify that the RollbackBoundary element is not followed by another RollbackBoundary and that the element is not at the end of the chain.
```

**Comment by barnson** [comment]
Investigate the creation of elements implying subtransactions to cover both rollback boundaries and MSI transactions -- and don't forget groups (package -v- transaction).
