### ISSUE TITLE
wix convert needs to convert Package/@Compressed to new default

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6317]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0-preview.0.build.0

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> The default of `Package/@Compressed` in v3 is `false`. In v4 the default is `true`.

* Describe the behavior you expected and how it differed from the actual behavior.

> `wix convert` needs to handle this change in the default.

**Comment by barnson** [comment]
So there was a bug...and I already had assigned it to me. Cool cool cool.

**Comment by rseanhall** [comment]
Just making some progress on preview.0 right?

**Comment by barnson** [comment]
Yeah, that was my intention, sure.
