### ISSUE TITLE
New minimum OS for v4

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6318]
* Describe the scenario and benefits that the feature supports.

> Setup developers need to know which OS's that custom actions and Burn support. We have changed the C++ toolset so v4 does not support the same OS's as v3. We need to update the rest of the toolset to reflect the new minimum OS. This will also allow us to stop having to worry about how to handle features were added between XP and our new minimum.

* Describe how you're accomplishing the feature today (if possible).

> Only running to dev machines.

* Describe what you'd like the new feature to do.

> Here's a list of things that should change, there might be more:

* Update block in Burn for pre-XP
* Update minimum Windows version for all native code
* Document new minimum OS

**Comment by rseanhall** [comment]
Server 2008 (server counterpart to Vista), Windows 7, and Server 2008 R2 (server counterpart to 7) are all currently supported through the [Extended Security Update program](https://docs.microsoft.com/en-us/lifecycle/faq/extended-security-updates).

Release | [Vista](https://docs.microsoft.com/en-us/lifecycle/products/windows-vista) |  [Server 2008](https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2008)
--- | --- | ---
RTM | 2010-04-13 |  2011-07-12
SP1 | 2011-07-12 |  unknown
SP2 | 2017-04-11 |  2020-01-14
Extended security update | N/A | 2023-01-10

Release | [Windows 7](https://docs.microsoft.com/en-us/lifecycle/products/windows-7) |  [Server 2008 R2](https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2008-r2)
--- | --- | ---
RTM | 2013-04-09 |  2013-04-09
SP1 | 2020-01-14 |  2020-01-14
Extended security update | 2023-01-10 | 2023-01-10

Release | [Windows 8](https://docs.microsoft.com/en-us/lifecycle/products/windows-8) |  [Server 2012](https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2012)
--- | --- | ---
RTM | 2016-01-12 |  2023-10-10
Extended security update | N/A | N/A


Release | [Windows 8.1](https://docs.microsoft.com/en-us/lifecycle/products/windows-81) |  [Server 2012 R2](https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2012-r2)
--- | --- | ---
RTM | 2023-01-10 |  2023-10-10
Extended security update | N/A | N/A

**Comment by barnson** [comment]
Build tools require "modern" OS (i.e., supported). Runtime (custom actions and Burn) should work with supported OSes (best-effort).

**Comment by barnson** [comment]
Fixed in https://github.com/wixtoolset/web/pull/101.
