### ISSUE TITLE
Include PlanDump in release builds of Burn

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6327]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> The `PlanDump` functionality makes it possible to diagnose certain classes of issues in Burn without requiring a debugger.

* Describe how you're accomplishing the feature today (if possible).

> You have to use a debugger, or a debug build of Burn.

* Describe what you'd like the new feature to do.

> Include `PlanDump` in release builds. It's probably too much to be logged by default, so make all of its messages logged at the `REPORT_DEBUG` level. Including the `REPORT_DEBUG` level in the log is a little tricky today, so we might want to add a command line switch for enabling that.

**Comment by barnson** [comment]
Policy is currently per-machine but there should be a per-user way to trigger it (HKCU policy -v- `/xlog` command-line switch).

**Comment by rseanhall** [comment]
Making it easier to enable the `REPORT_DEBUG` level is now covered by https://github.com/wixtoolset/issues/issues/6328
