### ISSUE TITLE
WiX burn engine fails to download over HTTP when HEAD request results in 404

### ISSUE THREAD

**Issue by guban** [wixtoolset/issues#6331]
* Which version of WiX are you building with?

3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2019

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Not using WiX VS Extension.

* Which version of .NET are you building with?

3.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 version 1909

* Describe the problem and the steps to reproduce it.

I have a WiX bundle that downloads some MSI files over HTTPS. Everything works fine with a test server that runs on a local machine. However, downloading from the actual production server fails. The problem is that for security reasons, the production server is intentionally configured to respond with 404 to any `HEAD` request. With this response, WiX fails immediately without even attempting to send the `GET` request that downloads the file.

* Describe the behavior you expected and how it differed from the actual behavior.

I compiled WiX `dutil` module and reproduced the problem under debugger. The relevant code is in function `DownloadUrl()` (file `dlutil.cpp`):

```
    hr = GetResourceMetadata(hSession, &sczUrl, pDownloadSource->sczUser, pDownloadSource->sczPassword, pAuthenticate, &dw64Size, &ftCreated);
    ExitOnFailure(hr, "Failed to get size and time for URL: %ls", sczUrl);
```

Then, I simply deleted the `ExitOnFailure()` line, thus making WiX ignore `GetResourceMetadata()` failures. With this change, WiX was able to download the file.

I think WiX should proceed with `GET` even if `HEAD` returns 404 or some other status. The point is to have the file downloaded. It should not matter if for some reason, getting metadata and knowing the download size beforehand was not possible. In other words, as long as `GET` request succeeds, WiX should not fail with an error, no matter what happens to the `HEAD` request.

The proposed fix is to remote the `ExitOnFailure()` line that follows the `GetResourceMetadata()` call (and adding a comment explaining why we don't check for failures). In fact, a similar logic is already applied to the "failure to initialize resume" call on the next line.

**Comment by rseanhall** [comment]
This appears to be the root cause of https://github.com/wixtoolset/issues/issues/6060.

**Comment by guban** [comment]
A workaround is to configure the server to return 200 for the HEAD request. The response does not need to contain any other useful information.

**Comment by BMurri** [comment]
`HEAD` is supposed to return the exact same headers and status as `GET`, just with an empty body.

A `404` response to `HEAD`, by definition, indicates that the requested resource does not exist.

There's no good reason for any client to be reprogrammed for a misbehaving server. Convince me otherwise

**Comment by guban** [comment]
> `HEAD` is supposed to return the exact same headers and status as `GET`, just with an empty body.
> 
> A `404` response to `HEAD`, by definition, indicates that the requested resource does not exist.
> 
> There's no good reason for any client to be reprogrammed for a misbehaving server. Convince me otherwise

Here we go:

- Installer A, where are the files I requested you to download?
- Sir, I haven’t downloaded them.
- What has prevented you from doing your job?
- Oh, a multitude of very good reasons, Sir.
- What are they?
- First, I noticed a filesystem corruption on drive C:.
   Then, I detected three non-compliances in handling HTTP requests by the server.
- I see. But have you at least tried to download the files, despite these corruptions and incompliances?
- No, Sir. I believe that I'm not obliged to do my job when the world around me is less than ideal.

- Now, Installer B, where are the files I requested you to download?
- Here they are, Sir!
- Good job! But have you noticed a file system corruption on drive C:?
- No Sir. But I afraid it's not my purpose to monitor for file system corruptions, although I verified that the checksums of the downloaded files match the expected values.
- And did you notice any incompliances in handling HTTP protocol by the server?
- Yes, Sir, but they were minor, and they did not prevent me from downloading the files.
  If you wish, you could use a dedicated compliance verifier tool, but I am just a humble installer after all.
- Ok. I guess, in the end you did what you were supposed to do, and that's what is most important.

Would you prefer to use Installer A or Installer B?

"Be conservative in what you do, be liberal in what you accept from others" (see <https://en.wikipedia.org/wiki/Robustness_principle>).

**Comment by robmen** [comment]
Burn does not use `HEAD` requests to probe HTTP compliance of the server. The `HEAD` request is part of the feature in Burn to resume downloads and works around 2GB limitations in wininet.dll.

One could suggest a feature to enable Burn to fallback to pure `GET` request if the server does not support `HEAD` requests. That would be a productive way to move the project forward.

**Comment by guban** [comment]
I appreciate the fact that WiX uses HEAD to overcome the 2GB wininet limitation. When the file is over 2GB, it is reasonable to fail when HEAD fails, telling the user to either fix the server or split the file into smaller files. But when the file is under 2GB, there is no limitation to overcome, and it is hard to justify the failure. At download time, it is possible to figure out which of the above two cases takes place because WiX usually knows the expected file size at compile time.
