### ISSUE TITLE
Document all public types and members

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6339]
* Describe the scenario and benefits that the feature supports.

> Member-level documentation is a minimum bar to support developers extending WiX.

* Describe how you're accomplishing the feature today (if possible).

> Using the source (Luke).

* Describe what you'd like the new feature to do.

> Tell me what these mysterious things do.

**Comment by BMurri** [comment]
Is this for the WiX language, the various libraries, the interfaces (for creating BAs, Extensions, every layer in v4, etc), or (my preference) "all of the things!"?

**Comment by barnson** [comment]
Assemblies. For now.

**Comment by barnson** [comment]
Once we know how we're going to build managed API documentation, we should determine gap coverage in public types. Then do what we're going to between preview.1 and RTM. Think too about how we handle doc updates without needed to rev nupkegs.
