### ISSUE TITLE
BA requests get dropped when UI is shown on engine thread

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6349]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> latest v3 and v4

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Burn uses PostThreadMessage to queue up the BA requests for actions like Detect, Plan, and Apply. If the BA shows UI in a callback, then those messages will be thrown away. This also applies when the engine shows the UAC prompt for the elevated engine. To reproduce:

1. Launch the bundle unelevated.
2. Have the BA call `Elevate`.
3. Have the BA call `Plan` inside `OnElevate` (`OnElevateBegin` in v4).
4. The UAC prompt should come up, click `Yes`.

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected: The engine processes the plan request after elevation completes.
> Actual: The engine doesn't plan.

Raymond Chen post - [Why do messages posted by PostThreadMessage disappear?](https://devblogs.microsoft.com/oldnewthing/20090930-00/?p=16553)

**Comment by BMurri** [comment]
I'd like to fix this

**Comment by rseanhall** [comment]
For implementing our own queue, I like how Raymond Chen built a linked list in [co_await awaitable signal part 4](https://devblogs.microsoft.com/oldnewthing/20210304-00/?p=104926).

**Comment by BMurri** [comment]
Last time I had time to wrap this up, I couldn't build v4. I'll be able to try again this weekend, so this should be in PR soon.

**Comment by barnson** [comment]
@BMurri we're targeting 4.0-preview.1 for Halloween so if you're going to implement this, it would need to be in sometime next week or so.

**Comment by rseanhall** [comment]
I wanted to make sure this got into v4 so I went ahead and did it.
