### ISSUE TITLE
Burn should support alternate hash algorithms

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6352]
* Describe the scenario and benefits that the feature supports.

> Burn uses SHA-1 hashes for payload verification. `IBootstrapperEngine::SetUpdate` takes a `BOOTSTRAPPER_UPDATE_HASH_TYPE` which has only two values: 

    BOOTSTRAPPER_UPDATE_HASH_TYPE_NONE,
    BOOTSTRAPPER_UPDATE_HASH_TYPE_SHA1,

which means that if you want to use a "better" hash algorithm, you have to pass in `BOOTSTRAPPER_UPDATE_HASH_TYPE_NONE` and get no hash checking whatsoever.

* Describe how you're accomplishing the feature today (if possible).

> Not.

* Describe what you'd like the new feature to do.

> All the underlying hash checking Burn uses support whatever Windows supports. Burn shouldn't be so restrictive. Alternatively, it should switch to SHA-256 to a get "modern" algorithm.

**Comment by rseanhall** [comment]
I was expecting to do this as part of https://github.com/wixtoolset/issues/issues/3992 - replacing SHA1 with SHA512.

**Comment by barnson** [comment]
Yeah, that's the "at least" scenario.
