### ISSUE TITLE
Should RegistrySearch and util:RegistrySearch follow the Compiler platform?

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6354]
## Feature requests

* Describe the scenario and benefits that the feature supports.

> In WiX v3, util:RegistrySearch did not follow the Compiler's platform (set via the `-arch` switch). This was recently "fixed" in v4 to be consistent with how the Compiler handles the platform.

* Describe how you're accomplishing the feature today (if possible).

> Should the RegistrySearches be different and ignore the default Compiler's platform and always default to 32-bit (or 64-bit?!?!?)?

* Describe what you'd like the new feature to do.

> With an answer to the above, I will adjust either the Compiler/UtilExtension/Converter or just the Converter (to handle the inconsistency in v3).

**Comment by rseanhall** [comment]
I don't know what to do about `RegistrySearch`. But for the Burn registry searches (`ApprovedExeForElevation` and `util:RegistrySearch`), I don't think it makes sense for the bitness of the bundle to have any effect on the bitness of the registry search. If anything, `default` needs to be a valid value that gets persisted through to the bundle where it will be evaluated at runtime as the architecture of the machine that it's running on.

**Comment by barnson** [comment]
`followBuild`?

**Comment by barnson** [comment]
`packageBitness` and `bundleBitness`

**Comment by BMurri** [comment]
I can see value in machineBitness as well as bundleBitness. packageBitness only makes sense when combined with the package id.

**Comment by barnson** [comment]
`packageBitness` means the bitness of the package being built. It's the same as `bundleBitness` but for MSI packages. And they're just naming suggestions because we couldn't come up with good ones during the meeting. :)

**Comment by BMurri** [comment]
I'm now watching the triage that was done earlier today.

My vote would be to have the default be set by `-arch` (same as creating things).

Alternatively, it always must be specified. I like the possibility of requesting a *machine bitness* (which is what I thought Bob's comments were relating to) but I don't think no default fits the rest of the language.

Always being 32 isn't expected, and always matching the machine bitness is especially not expected if not explicitly requested.

I vote for searches following arch for the defaults.

**Comment by robmen** [comment]
After thinking about this for a while, I've come to the exact same conclusion as @BMurri. I've also decided not to always add `Bitness` to `util:RegistrySearch` even though it's possible someone is compiling their Bundle project as `x64` in v3 but getting `x86`. It isn't worth always dirtying up v3 Bundle code with `Bitness`.
