### ISSUE TITLE
Burn can wrongly detect MSI package as Obsolete

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6377]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> latest v3 and v4

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Same scenario as https://github.com/wixtoolset/issues/issues/4292, except the non-DetectOnly row in the Upgrade table doesn't exist so all three rows are DetectOnly.

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected: Burn detects related operation as `NONE` and detects the MSI package as `ABSENT`.
> Actual: Burn detects related operation as `DOWNGRADE` and detects the MSI package as `OBSOLETE`.

**Comment by barnson** [comment]
Rare case, weird authoring. BA can override.
