### ISSUE TITLE
Windows Defender Smartscreen blocks installation 

### ISSUE THREAD

**Issue by mrzade** [wixtoolset/issues#6385]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2019 Pro (16.5.2)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> 4.7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Pro v1909 20H2 (Build 18363)

* Describe the problem and the steps to reproduce it.

> We experience weird behavior of our installer when running it on recent versions of Windows 10 with Windows Defender SmartScreen turned on. 
The installer is a single-file Burn bootstrapper that launches several EXE packages (VC Runtime installers of different versions that are required by the components we're using in our product) followed by several MSI packages (that is our product, support tools, and a device driver). The installation occurs per-machine, meaning it will be elevated by Burn at a certain moment. The installation package is downloaded from the internet (we have tested it with Google Drive).
The problem we are facing is that sometimes (we don't have found any pattern yet) when SmartScreen turned on (which is the default for fresh Windows installations!) it blocks the unpack, creation, and caching of the packages in PackageCache folder which makes the entire installation to fail! 
The behavior is completely random - sometimes it starts with an error during the creation of the restore point followed by the mismatch of the checksum of the cached package; sometimes it cannot move verified files from .unverified folder to PackageCache folder. There is no particular package that fails - on one system it could be VC Runtime, on the other - one of the MSIs.
All our MSI, as well as EXE modules, are signed with either our corporate code signing certificate issued by DigiCert (not EV certificate), or component vendor's certificate. All our MSIs are built with WiX. The installing user has administrative rights on the target system.
It is also worth mentioning that on some systems SmartScreen warning pops up.  In this case, the user gives permission to run. 

* Describe the behavior you expected and how it differed from the actual behavior.

> Well, it is obvious - when the user gives his/her permission to run the installer, it should run without being blocked.

**Comment by barnson** [comment]
WiX doesn't use issues for support. We moved this issue to the [experimental GitHub discussions area][gh].

[gh]: https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions
