### ISSUE TITLE
Patch can't be created when MSI got file from wixext

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6387]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> latest v4

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Create an MSI with a custom action from a wixext. Try to create a patch from that. See test at: https://github.com/wixtoolset/Core/blob/8e51e27adbcfe1892463463b4e7dc251019f427c/src/test/WixToolsetTest.CoreIntegration/PatchFixture.cs#L90

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected: The patch should be created.
> Actual: It tries to compare files using the ir path from the wixpdb which doesn't exist.

**Comment by robmen** [comment]
To fix this fully requires integrating the Melt patching functionality natively into the patch build process. This is definitely a feature for v4.0 but I'd argue not necessary in v4.0-preview.0. Thus, I'd like to suggest to `triage` that we move out of `FourOhPreviewZero`.

**Comment by robmen** [comment]
This will be fixed by implementing #6401.

**Comment by robmen** [comment]
This issue was fixed with the first part of #6401 implementation.
