### ISSUE TITLE
Wix 3.11 and HTTPS TLS 1.1/1.2 download issue - error code 500

### ISSUE THREAD

**Issue by eltra-ch** [wixtoolset/issues#6392]
We are using 3.11 with custom WPF bootstrapper (Windows 7, .NET 4.8).
Our HTTP provider changed the server configuration and since then we cannot download the packages using internal WIX download routine (we get HTTP 500 error code). 
We can workaround this problem on the custom bootrstrapper level using own download implementation (OnResolveSource & .NET WebClient impl.).

The main problem is with prerequisite, because there we have no possibility to override the download method and we have to relay on internal implementation. This of course doesn't work. Unfortunatelly our requirement is to support Windows 7 and .NET 4.8 so .NET 4.8 has to be installed first.

During our investigation we observed, that WinHTTP library has the same issue on Windows 7 without TLS 1.1/TLS 1.2 Patch.
Applying the patch solves the problem with WinHTTP, but doesn't with WIX. We assume, that the problem is related to TLS 1.1/1.2 handling.

**Comment by rseanhall** [comment]
We would need detailed steps to reproduce this issue in order to figure out what the root cause is.
* What version of Windows 7? Clean install of Windows 7 SP1?
* What is the TLS 1.1/TLS1.2 patch? I assume you're referring to a specific KB number.
* How are you determining that WinHTTP is broken as well? Are you rebooting after installing the patch?
* What is a URL that causes the problem?
* What do you mean by HTTP provider? Some kind of proxy configuration, load balancer, the web server for the URL, or something else?

**Comment by eltra-ch** [comment]
- Windows 7 x64 clean install with SP1
- we applied MicrosoftEasyFix51044 - "Update to enable TLS 1.1 and TLS 1.2 as default secure protocols in WinHTTP in Windows" AFAIK no reboot required
- We have written another application with pure C++ WinHTTP implementation. We observed there the same bahaviour (internal WinHTTP logging shown the TLS handshake error). After applying the patch, this application is working as expected.
- Yes it is a WebSever, direct link: https://www.maxongroup.com/medias/mmc_webmedia/vnext/release/redist/msxml/4.0/msxml.msi

**Comment by rseanhall** [comment]
According to https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392, MicrosoftEasyFix51044 is only part of the solution. You must also install the update - KB3140245.

**Comment by eltra-ch** [comment]
checked - KB3140245 is applied - no changes

**Comment by rseanhall** [comment]
Burn uses WinInet, not WinHTTP, so comparisons to WinHTTP applications aren't relevant to this issue. https://github.com/wixtoolset/wix3/blob/6e0bab12e155426d57a36c848fd6920e0eaad64f/src/libs/dutil/dlutil.cpp#L131

**Comment by rseanhall** [comment]
WinInet uses SChannel, and WinInet does not allow configuring which protocol to use. TLS1.2 is not enabled by default in clean Win7 SP1. It sounds like the server was updated to only support TLS1.2 or later. Enabling TLS1.2 in SChannel is done through a separate registry key from WinHTTP - https://support.microsoft.com/kb/187498.

```
[07DC:096C][2021-03-15T19:52:21]w343: Prompt for source of package: PackageB, payload: PackageB, path: C:\Users\admin\Downloads\msxml.msi
[07DC:096C][2021-03-15T19:52:21]i338: Acquiring package: PackageB, payload: PackageB, download from: https://www.maxongroup.com/medias/mmc_webmedia/vnext/release/redist/msxml/4.0/msxml.msi
[07DC:096C][2021-03-15T19:53:42]e000: Error 0x80072f7d: Failed to send request to URL: https://www.maxongroup.com/medias/mmc_webmedia/vnext/release/redist/msxml/4.0/msxml.msi, trying to process HTTP status code anyway.
[07DC:096C][2021-03-15T19:53:42]e000: Error 0x80072f7d: Unknown HTTP status code 0, returned from URL: https://www.maxongroup.com/medias/mmc_webmedia/vnext/release/redist/msxml/4.0/msxml.msi
[07DC:096C][2021-03-15T19:54:25]e000: Error 0x80072f7d: Failed attempt to download URL: 'https://www.maxongroup.com/medias/mmc_webmedia/vnext/release/redist/msxml/4.0/msxml.msi' to: 'C:\Users\admin\AppData\Local\Temp\{2C88FE1F-0B5C-45A0-8BC4-627125B003C7}\PackageB'
```

**Comment by eltra-ch** [comment]
SChannel changes applied - no luck at the moment. I just checked the Wiinet logs (Event Viewer) and there is simply 500 response, on HTTP request - Maybe they have problem with the flags? "Accept: */*, UserAgent: Burn" btw. thank you for your help!

**Comment by rseanhall** [comment]
There are basically two parts to this issue. The clean Win7 having issues with TLS1.2 is not something we can do anything about. The part where Burn is not working with the server is covered in https://github.com/wixtoolset/issues/issues/6331.

**Comment by eltra-ch** [comment]
I knew that the WinInet is used by WIX. WinHTTP example was used only as possible reason, because it was very similiar experience. In the meantime I got sime information about the server configuration. The "HTTP Strict Transport Secutity" -HSTS- was turned on - https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security. It looks like WIX WinInet implementation doesn't support it.

**Comment by rseanhall** [comment]
I used the debugger to skip over the HEAD request the other day, and it was able to download the file. That suggests HSTS is not the problem.
