### ISSUE TITLE
WIP: Use MSIs as source of files during patch build

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6401]
* Describe the scenario and benefits that the feature supports.

> Windows Installer patches (.msp) are created by diff'ing a baseline MSI with an updated MSI. This diffing process requires not only the two MSI databases but all the source files to calculate differences (especially for delta patching). It turns out the shipping MSI packages have all the files needed, so the tooling could us that.

* Describe how you're accomplishing the feature today (if possible).

> In v3, `melt.exe` could be used to extract the files from MSI packages and update the .wixpdb to point at those locations. This provides a pretty good experience for making all the files available. But it is "yet another .exe" required to be run to execute patching in v3.

* Describe what you'd like the new feature to do.

> With the integrated patch pipeline in v4, it would be easier if the functionality of `melt.exe` could be incorporated into the process to create a seamless experience for creating patches by sourcing the files from the MSI files.

**Comment by rseanhall** [comment]
There are multiple Burn integration tests to update as part of this change.
