### ISSUE TITLE
WIP: Improved patch filtering

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6402]
* Describe the scenario and benefits that the feature supports.

> Pure-WiX patching filtering can work well if the original .wxs code is split into small patch appropriate `Fragment`s. Unfortunately, such `Fragment`s rarely represent a logical grouping of installation functionality. Developers are often surprised that patch filtering happens at the section level rather than logical grouping of Features and Components, etc.

* Describe how you're accomplishing the feature today (if possible).

> The Unbinder actually provides a system for logically grouping Rows to be patched by CustomAction, Feature, Component, File, RegistryKey, ODBC, etc. This mechanism matches the typical developer expectations for filtering.

* Describe what you'd like the new feature to do.

> Adopt the Unbinder's filtering mechanism instead of the section-based patch filtering found in v3.

**Comment by rseanhall** [comment]
There is a Burn integration test that needs to be updated with this.

**Comment by robmen** [comment]
Also, evaluate if this addresses #2689.

**Comment by robmen** [comment]
The test @rseanhall is referring to is [SlipstreamTests.CanAutomaticallyPredetermineSlipstreamPatchesAtBuildTime](https://github.com/wixtoolset/wix4/blob/031991f32f059b64374e6d257cbe573304dd577f/src/test/burn/WixToolsetTest.BurnE2E/SlipstreamTests.cs#L269-L301)
