### ISSUE TITLE
Include all files of WixUI dialogs to SDK

### ISSUE THREAD

**Issue by Beautyod** [wixtoolset/issues#6403]
In the WiX documentation and other tutorials it's described how to include a GUI to a setup.
Unfortunately there are many wxs files missing in the WiX SDK, which were included in the past. (At least it seem so, following WiX articles.)

Currently there are the 5 example dialogs (e.g. `WixUI_InstallDir.wxs`), but not the dialog sequences (e.g. `WelcomeDlg.wxs`).
This is really frustrating for WiX beginners.

The WiX toolkit download page writes: "WiX Toolset build tools includes everything you need to create installations".
I recommend to add the needed `*Dlg.wxs` files to the SDK again.
They don't need much space, but would be really helpful.

This issue is similar to #4618 (Include WixUI dialogs in installer and zip), but are related to additional files like `WelcomeDlg.wxs`, `WixUI_InstallDirDlg.wxs`, etc.

**Comment by barnson** [comment]
In WiX v4, extensions like WixUIExtension are delivered in NuGet packages, which aren't generally useful for delivering random files. The source should stay in source control and GitHub offers URLs for individual files and .zips for bulk downloading.
