### ISSUE TITLE
Uncompressed bundle payloads are not copied to output folder for msbuild projects

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6407]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> latest v4

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Create a .wixproj for a Bundle with Compressed="no" and build the project.

* Describe the behavior you expected and how it differed from the actual behavior.

> The uncompressed payloads should be copied to the output folder, but are not.

See failing test at https://github.com/wixtoolset/Tools/blob/62dd878b5fd6d7d354034178584710ecb903985e/src/test/WixToolsetTest.Sdk/MsbuildFixture.cs#L51.

**Comment by robmen** [comment]
Thank you very much for the standing test case. Made it very easy to validate the fix worked. 👍🏻

**Comment by rseanhall** [comment]
There's a Burn integration .wixproj somewhere that has a hack to work around this issue, too.

**Comment by robmen** [comment]
Nope. Not fixed. I incorrectly disabled the `Theory` based test. Going to fix correctly now.
