### ISSUE TITLE
Force integrity check

### ISSUE THREAD

**Issue by benp87** [wixtoolset/issues#6437]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> From what I can see, a generated installer bundle does not have the following security flag: https://docs.microsoft.com/en-us/cpp/build/reference/integritycheck-require-signature-check?view=msvc-160
Is it possible to add this to Wix3? I tried to add the flag after the bundle compilation but Windows blocked the executable when I tried to run it, like it's signed or something, even though I don't see any signature when looking at the properties of the executable.

**Comment by rseanhall** [comment]
This would be a breaking change, since it would require everyone to always sign their bundles.

**Comment by benp87** [comment]
Maybe it can be a candle/light compilation flag?

**Comment by barnson** [comment]
This is difficult at best, given that it has to be set when linking Burn itself. We can't do that as it would require every bundle to be signed. If it's possible to set after linking, it might be something doable in WiX. But it needs to be designed by writing a [WIP][wip] and including more details about the need/justification.

[wip]: http://wixtoolset.org/development/wips/
