### ISSUE TITLE
The failing test for issue 6425 should be more specific. A plausible approach was suggest by #Barnson on 4/22/21.

### ISSUE THREAD

**Issue by cpuwzd** [wixtoolset/issues#6439]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
n/a
> (WiX version in major.minor.release.build format)
n/a
* Which version of Visual Studio are you building with (if any)?
n/a
> (Visual Studio version, including year and update)
n/a
* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
n/a
> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
n/a
* Which version of .NET are you building with?
n/a
> (.NET version)
n/a
* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
n/a
> (Windows version)
n/a
* Describe the problem and the steps to reproduce it.
Introduce a change that causes the number of errors expected in the fix for issue 6425 to change.
> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
n/a
* Describe the behavior you expected and how it differed from the actual behavior.
Test should pass.
> (Be as specific as you can and err on the side of providing too much information.)
Test will fail.

**Comment by barnson** [comment]
There are no failing tests.

**Comment by cpuwzd** [comment]
@barnson ,

I just looked (before I saw your response) and realized that you had inserted your suggested fix already.

Sorry to distract you. Let me know if there is anything else I can help with.

Ron

**Comment by barnson** [comment]
No worries! Your previous PR didn't have a failing test -- that breaks the build so we can't commit any failing tests. I just added some extra verification.
