### ISSUE TITLE
Freshen/trim NetFx redist package groups because of SHA-2 signing

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6443]
* Describe the scenario and benefits that the feature supports.

> https://github.com/wixtoolset/issues/issues/6438

* Describe how you're accomplishing the feature today (if possible).

> n/a

* Describe what you'd like the new feature to do.

> Re-harvest to get the new hashes. Trim the package groups for packages that are going/have gone away.

**Comment by rseanhall** [comment]
All packages pre-4.5.2 were already removed with the SHA512 update. 4.5.2-4.6.1 packages were unchanged and remain available and supported until April 2022. So the only thing to do was update the 4.6.2 and 4.7.2 packages.

**Comment by barnson** [comment]
Should we remove the package groups for the downloads that were removed?

**Comment by rseanhall** [comment]
Can you point me to a package group whose target is no longer available?

**Comment by barnson** [comment]
No, because you already removed them, of course.
