### ISSUE TITLE
Bring back option to verify remote payloads by Authenticode signature

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6447]
If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Microsoft has historically updated .NET Framework packages behind their "permalink" URL, making hash verification impractical.

* Describe how you're accomplishing the feature today (if possible).

> In v3, using signature verification.

* Describe what you'd like the new feature to do.

> Bring back option to verify payload by Authenticode signature.

**Comment by BMurri** [comment]
This seriously has caused so many issues in the past...

The only way I'd consider supporting it is if it only applied to "drop & forget" (aka permanent) packages that are downloaded and never preserved in the cache. Oh, also, no resuming partial downloads (anything goes wrong anywhere in the entire path and everything starts all over again from restarting the download at the beginning).

No other use case. And I'm pretty sure I would still cast my vote in triage as "NO!"

**Comment by rseanhall** [comment]
This was from a discussion in today's meeting that came about because of https://github.com/wixtoolset/issues/issues/6438.

I'm not aware of anybody complaining about partial downloads before. Is it related to this issue? Maybe it needs its own issue with more details?

**Comment by BMurri** [comment]
Bringing back Authenticode verification would not have covered this scenario where Microsoft "refreshed" its packages by completely changing the certificate it uses to sign them.

The new certificates Microsoft is using isn't trusted by non-updated older OSs (anything older than about 4-ish years ago), so not updating a Windows box isn't going to work regardless.

If it really must be brought back, I would say only allow it in payloads, and don't promote it. No need to support catalog file signature verifications in the burn engine.

I haven't seen other incidents of MSFT refreshing the same package behind the same URL.

------

The download issue I'm recalling involved a bad download who's certificate successfully verified, causing the engine to not redownload it, but it still failed the installation, even though the server had a newer/different package available. I don't recall all the details, just that if you change the file you intend to install, you update the hash, and there's never an issue. There's no good reason to change a file you intend to update later and not update the authoring to reflect it.

**Comment by rseanhall** [comment]
When working on https://github.com/wixtoolset/wix3/pull/520, both 4.7.2 and 4.8 had changed behind the same URL according to code submitted by other people.

Looking back at https://github.com/wixtoolset/issues/issues/5977, it looks like 4.8 had actually changed the certificate once before so this wouldn't have helped with that one. But that was a case of them updating the package behind the same URL.

But if you look at the previous definition of the 4.7.2 web at https://github.com/wixtoolset/issues/issues/5575#issuecomment-386223409 and compare it to mine, you'll see the URL and certificate information stayed the same but the hash and version changed.

------

By "payload" I'll have to assume you mean the `Payload` element since technically everything is a payload from the engine's view. I think that's too restrictive because Microsoft has shown repeatedly that they're willing to change the package behind a "permanent" URL. My work on #3640 should have made it possible for the BA to fix this scenario. There are some other caching bugs that are assigned to me that might have caused that package to stay in the package cache in v3 so in v4 retrying the install should work out.

I'm not saying it's a good idea for people to use this behavior, just that sometimes you rely on 3rd party packages and don't have control over things like this.

**Comment by BMurri** [comment]
I stand corrected and would respectfully like to ask Microsoft to stop doing stuff like that (I'm debating how I'm going to word my letter to Heath now).
---
As long as retries (at some point) ignore what look like valid already downloaded items if they don't share the same hash as what's at the other end of the URL, and the retries are automatic (to some degree), then I see the need. Security is more easily subverted wherever it's loosened, and anything short of a strict hash to confirm one-to-one the package is exactly the expected one is loose security.

**Comment by rseanhall** [comment]
The 4.8 web installer has been updated yet again behind the same URL to a brand new package with the same version as last time but different hash (I have not checked any of the other versions).

**Comment by BMurri** [comment]
Don't worry, @rseanhall , I'm not going to beat a dead horse on this issue any longer.

**Comment by rseanhall** [comment]
I had guessed that we would put it back in May so the Burn engine implementation is already done (https://github.com/wixtoolset/wix4/commit/2f4287fdcee83b30e0f7f3ce548bcdff2ee85e1f). The rest of the work should be in the core toolset.

**Comment by robmen** [comment]
We should consider making Authenticode verification only available to RemotePayloads. That is the minimal exposure required and removes the chance that someone 'accidentally' uses signature verification when hashing is superior.

**Comment by rseanhall** [comment]
We should also consider whether to change how Authenticode verification is specified on "RemotePayloads". v3 actually required the hash even if signature information was provided, even though Burn ignored the hash.

**Comment by barnson** [comment]
MsuPackage? Remote-only? Extra package payloads?
