### ISSUE TITLE
Firewall rule not created if a different rule exists with the same name

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#6450]
* Which version of WiX are you building with?
3.11.2

* Which version of Visual Studio are you building with (if any)?
VS 2019

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
VS 2019 

* Which version of .NET are you building with?
4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows Server 2019

* Describe the problem and the steps to reproduce it.
When authoring two or more firewall exception that all have the same name then only the first one is created

* Describe the behavior you expected and how it differed from the actual behavior.
I expect all the authored rules to be created even if they share the same name
Looking at the code I see that if an existing rule with the same name already exists then this rule is enabled. I'd expect the comparison to be made on all relevant properties of the rule rather than just the name

**Comment by barnson** [comment]
INetFwRules expects the name to be unique (e.g., Remove works only on name). Matching on other properties would increase the likelihood that rules would be orphaned. So the simple workaround is to make the names unique; it solves this issue and is better for users anyway.
