### ISSUE TITLE
Windows installer doesn't work

### ISSUE THREAD

**Issue by sergiocordero** [wixtoolset/issues#6457]
If this issue is a bug:

* Which version of WiX are you building with?
* Wix 3.11

* Which version of Visual Studio are you building with (if any)?
* 4.8

> (Visual Studio version, including year and update)
Visual Studio 17 15.9

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
* Visual studio 17

* Which version of .NET are you building with?
4.6

> (Windows version)
Windows 10 20h2 build 19042

* Describe the problem and the steps to reproduce it.
* When try to install windows 

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)
-is imposible to install, NetFramework 3.5 is longer not available in new windows version

* Describe the behavior you expected and how it differed from the actual behavior.
<img width="576" alt="error" src="https://user-images.githubusercontent.com/83288772/118720765-66415300-b800-11eb-9107-4dfde9dc7546.png">

> (Be as specific as you can and err on the side of providing too much information.)

**Comment by barnson** [comment]
It can be installed from Programs and Features, Turn Windows features on or off.

**Comment by robmen** [comment]
![image](https://user-images.githubusercontent.com/131904/118721738-15216700-b7e0-11eb-80dc-97343366db99.png)

**Comment by sergiocordero** [comment]
I did that and doesn't work
Please don't close that is a bug

<img width="576" alt="error" src="https://user-images.githubusercontent.com/83288772/118722639-c3d69f00-b802-11eb-8f19-c0e0d9c1953e.png">

**Comment by robmen** [comment]
That's a problem in Windows. We can't help you with Windows issues in this repo. I gave you a screenshot from my Windows 10 20h2 build 19042 to show that it does work.

**Comment by BMurri** [comment]
That's a Windows issue, not a WiX one.

**Comment by sergiocordero** [comment]
> 
> 
> That's a problem in Windows. We can't help you with Windows issues in this repo. I gave you a screenshot from my Windows 10 20h2 build 19042 to show that it does work.

I have the same version but i can't install NetFramework 3.5
