### ISSUE TITLE
ExePackage should be consistent about being uninstallable and repairable

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6459]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> If `RepairArguments` are not specified then an `ExePackage` can't be repaired. You must specify `RepairArguments=""` to declare that the command line should be empty to repair. However, all non-Permanent `ExePackage`s are uninstallable.

* Describe how you're accomplishing the feature today (if possible).

> N/A

* Describe what you'd like the new feature to do.

> Make `UninstallArguments` and `RepairArguments` consistent with the `ExePackage` being uninstallable and repairable, respectively.

**Comment by barnson** [comment]
If `Permanent="no"`, `UninstallArguments` must present (even if blank).

**Comment by rseanhall** [comment]
`MsuPackage` should have a similar requirement for `Permanent="no"`: `KB` should be non-empty.

**Comment by rseanhall** [comment]
The separation of the concepts of uninstallable 
and permanent packages was new to Burn, and requires a manifest change.

**Comment by robmen** [comment]
@rseanhall are you unblocked now with this Compiler change to allow empty string UninstallArguments now?

**Comment by rseanhall** [comment]
One of us needs to add an `Uninstallable` attribute to the ExePackage in the manifest like the `Repairable` attribute. I didn't look into whether that requires a Symbol change.
