### ISSUE TITLE
Bootrapper after installing default intance no further installation of instances are possible

### ISSUE THREAD

**Issue by emnuelgebel** [wixtoolset/issues#6471]
## Bugs

If this issue is a bug:

WiX 3.11.2

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)
Microsoft Visual Studio Professional 2019
Version 16.10.0

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
2019
* Which version of .NET are you building with?

> (.NET version)
4.6.2

> (Windows version)
Windows 10

* Describe the problem and the steps to reproduce it.

I have a custom Bootstrapper, where I can choose the InstanceNumber for the MSI-Package to Install.

All thinks works fine, if i don't intall the default Instance of the Package.

After installing successfully the default Instance, no further Instances are possible to install.

If I install only the MSI-Package without the Bootstrapper (Burn), then i can install in every Combination.

I mean firt the Default and then all other Instances, or the Default in between.

Default Instance: Applying execute package: MI_Setup_prod_x64, action: Install, path: C:\ProgramData\Package Cache\{0EE3FDCB-3C70-4734-AC9A-7383164B1421}v1.9.6.0\INDI.Office_Setup_1.9.6.0_x64.msi, arguments: ' ALLUSERS="1" MSIFASTINSTALL="7"  INSTANCENUMBER="0" TRANSFORMS="" MSINEWINSTANCE="" INSTANCEREGISTRYPATH="\Instances\0" INSTANCEFOLDERNAMESUFFIX="" ADDLOCAL="FeatureCore,FeatureLocalizationResource_ptBR,FeatureLocalization,FeatureLocalizationResource_zhCN,FeatureLocalizationResource_jaJP,FeatureLocalizationResource_plPL,FeatureLocalizationResource_skSK,FeatureLocalizationResource_esES,FeatureLocalizationResource_svSE,FeatureLocalizationResource_viVN,FeatureConfigurator,FeatureOffice,FeatureDesktopShortcut"'

Instance 1:  Applying execute package: MI_Setup_prod_x64, action: Install, path: C:\ProgramData\Package Cache\{0EE3FDCB-3C70-4734-AC9A-7383164B1421}v1.9.6.0\INDI.Office_Setup_1.9.6.0_x64.msi, arguments: ' ALLUSERS="1" MSIFASTINSTALL="7" INSTANCENUMBER="1" T=":ID01" TRANSFORMS=":ID01" MSINEWINSTANCE="1" INSTANCEREGISTRYPATH="\Instances\1" INSTANCEFOLDERNAMESUFFIX="_1.9.6.0" 

[0F30:173C][2021-06-09T18:27:00]i201: Planned package: MI_Setup_prod_x64, state: Present, default requested: Present, ba requested: Present, execute: None, rollback: None, cache: No, uncache: No, dependency: Register

**Comment by barnson** [comment]
Burn doesn't support multi-instance MSI packages today. See https://github.com/wixtoolset/issues/issues/6472.
