### ISSUE TITLE
v4-preview.0 build action does not generate an .msi file

### ISSUE THREAD

**Issue by canihavesomecoffee** [wixtoolset/issues#6473]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?  

> WiX Toolset Core version 4.0.0.0 (preview 0)

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> 3.1.410 (SDK)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Clean install of Windows 10 in VirtualBox, installed .NET core SDK, installed the preview using the command from https://robmensching.com/blog/posts/2021/5/17/wix-toolset-v4-preview.0/.
>
> Conversion goes fine (using convert), but building does not result in an .msi. No errors are displayed.
> The .wxs can be found here: https://github.com/canihavesomecoffee/ccextractor/blob/master/windows/installer.wxs
>
> Similarly, using GitHub Actions the .msi is not created (refer to https://github.com/canihavesomecoffee/ccextractor/runs/2823364517, where the 3rd upload action is supposed to upload the .msi, but no file is found
>
>> Warning: No files were found with the provided path: ./windows/installer.msi. No artifacts will be uploaded.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected an .msi :)

If I'm doing something wrong, or can help to debug, please let me know.

**Comment by rseanhall** [comment]
It's writing the MSI to `%TEMP%\installer.msi`. Use the `-o` or `-out` switch to specify the output path of the MSI.

This is a behavior change from v3 (not sure if intentional). In v3, running `candle` then `light` would have output the following (the MSI was built to `C:\src\ccextractor\windows\installer.msi`):

```
C:\src\ccextractor\windows>"C:\Program Files (x86)\WiX Toolset v3.14\bin\candle.exe" installer3.wxs
Windows Installer XML Toolset Compiler version 3.14.0.4118
Copyright (c) .NET Foundation and contributors. All rights reserved.

installer3.wxs

C:\src\ccextractor\windows>"C:\Program Files (x86)\WiX Toolset v3.14\bin\light.exe" installer3.wixobj
Windows Installer XML Toolset Linker version 3.14.0.4118
Copyright (c) .NET Foundation and contributors. All rights reserved.


C:\src\ccextractor\windows>
```

In v4, nothing is printed out.

**Comment by canihavesomecoffee** [comment]
@rseanhall Thank you for this clarification. I hadn't thought of checking %TEMP%, and I wasn't aware there was an `-o` switch (as the help menu for building isn't complete yet).

It's been a bit too long since I last worked with WiX...

Seems that this is a non-issue then, so I'll close it :+1:
