### ISSUE TITLE
wix.exe -help needs to print semantic version

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6474]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0-preview.0

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Run `wix --help`

* Describe the behavior you expected and how it differed from the actual behavior.

Actual:
```
WiX Toolset Core version 4.0.0.0
Copyright (c) .NET Foundation and contributors. All rights reserved.

Usage: wix [option]
Usage: wix [command]

Options:
  -h|--help         Show command line help.
  --version         Display WiX Toolset version in use.

Commands:
  build             Build a wixlib, package or bundle.
  decompile         Decompile a package or bundle into source code.
  convert           Convert v3 source code to v4 source code.
  extension         Manage extension cache.
  format            Ensures consistent formatting of source code.

Run 'wix [command] --help' for more information on a command.
```

Expected: Should contain the line with the semantic version that's printed with `--version` but as part of the header:

```
WiX Toolset Core version 4.0.0-preview.0+824e72cf
Copyright (c) .NET Foundation and contributors. All rights reserved.
.
.
.
```

The WiX header will now be consistent with the MSBuild header. It should provide all the detail we'll need to diagnose exactly which version of WiX was used for any given command.

**Comment by barnson** [comment]
Also worth noting (and in https://github.com/wixtoolset/wix4/pull/74): https://github.com/dotnet/msbuild/issues/6614

Now, I hope that's never implemented but the suggestion at https://github.com/dotnet/msbuild/issues/6614#issuecomment-916108619 is perfectly reasonable: Many people might come to care about the version but nobody in the known universe (Earth-616, anyway) cares about the copyright. I also nudge in favor of replacing `wix version` with `wix info` (or making it a synonym) for when we have more info to share (cached extensions maybe?).

**Comment by MarkStega** [comment]
@robmen Yes, I would appreciate the assignment of this issue to me.
