### ISSUE TITLE
Can't download WiX v3.14 from website in Chrome

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6475]
Steps to repro:
1. Open https://wixtoolset.org/releases/v3-14-0-4118/ in Chrome.
2. Click the `Launch` button.

Expected: File downloads.
Actual:

> Mixed Content: The site at 'https://wixtoolset.org/' was loaded over a secure connection, but the file at 'http://static.wixtoolset.org/releases/v3.14.0.4118/wix314.exe' was loaded over an insecure connection. This file should be served over HTTPS. This download has been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.

That file is not available from HTTPS since the certificate doesn't match `static.wixtoolset.org`. Attempting to load the page in step 1 from HTTP doesn't work since it gets redirected to HTTPS.

**Comment by oguzhanaksoy** [comment]
Reproducible on Google Chrome

> Version 91.0.4472.114 (Official Build) (64-bit)
