### ISSUE TITLE
How to build WiX Custom Action projects without installing the toolset 

### ISSUE THREAD

**Issue by Rakesh1234567** [wixtoolset/issues#6480]
Hi,
We want to build Custom action instead of installing toolset just refer toolset from directory. How we can achieve that?

Regards,
Rakesh

**Comment by barnson** [comment]
WiX doesn't use issues for support. We moved this issue to the [experimental GitHub discussions area][gh].

[gh]: https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions
