### ISSUE TITLE
Nuget dependencies lost when packaged in CA DLL

### ISSUE THREAD

**Issue by rrgjt** [wixtoolset/issues#6486]
* Which version of WiX are you building with?

>3.11.2

* Which version of Visual Studio are you building with (if any)?

>2019.16.10.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Couldn't get it to install

* Which version of .NET are you building with?

> 4.7.2

* Describe the problem and the steps to reproduce it.

> If I build the project with hard references to a custom DLL and it's dependent DLLs (eg: in a project resources folder), the project builds fine and the custom actions work well.  However if I replace the hard referenced DLLs with a nuget package that delivers the same DLLs, the custom actions fails as it says it cannot load the dependent DLLs.  The build output shows MakeSfxCA packaging the files, just as it does with hard referenced files (see below), but the resultant .CA DLL is smaller than the one created with the hard referenced build, which tends to indicate something is different.
1>  Packaging files
1>      OurInstallerCustomActions.dll
1>      OldEncryptDecrypt.dll
1>      NewEncryptDecrypt.dll
1>      StringHasher.dll
1>      Microsoft.AspNetCore.Cryptography.Internal.dll
1>      Microsoft.AspNetCore.Cryptography.KeyDerivation.dll
1>      Microsoft.Deployment.WindowsInstaller.dll
1>      OurInstallerCustomActions.pdb
1>      CustomAction.config
1>  MakeSfxCA finished: 

We've tried adding the GroupProperty tag <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies> to the project file, and that has not helped.  We would like to reduce the need to copy files manually by utilizing nuget.

**Comment by barnson** [comment]
How are you referencing the NuGet package? What does the .csproj look like?

**Comment by rrgjt** [comment]
Thanks for the quick reply.

The nuget package is being added to the project from our company nuget repo.  It is used without issue in a number of other applications, but we need to roll some functionality into the installers now.

I have attached the vbproj file (renamed to .txt  so it would be accepted).  I noted the packages do not make it into the <ItemGroup> -> <ImportInclude> sections.  I did try adding them manually, and that didn't make any difference.


[AdvancedInstallerCustomActions.txt](https://github.com/wixtoolset/issues/files/6705583/AdvancedInstallerCustomActions.txt)

**Comment by barnson** [comment]
Nothing looks odd there. Can you attach a verbose MSBuild log? Maybe it will have something interesting.

**Comment by barnson** [comment]
Without mroe info, we'll assume all's good now.

**Comment by rrgjt** [comment]
My apologies. I had meant to respond but got sidetracked. We could not get it to work, and with other factors, decided to go in a different direction using a powershell script to call the function.

Rob

________________________________
