### ISSUE TITLE
error WIX0094: The identifier 'CustomAction:UninstallCertificates_X86' could not be found

### ISSUE THREAD

**Issue by matbech** [wixtoolset/issues#6494]
>Which version of WiX are you building with?

4.0.0-preview.0

I'm getting the follow error when using the Iis extension WixToolset.Iis.wixext:
C:\projects\wix4\src\ext\Iis\wixlib\IIsExtension_Platform.wxi(61): error WIX0094: The identifier 'CustomAction:UninstallCertificates_X86' could not be found

.wixproj
```
...
<PackageReference Include="WixToolset.Iis.wixext" Version="4.0.0-preview.0" />
...
```

.wxs
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:iis="http://wixtoolset.org/schemas/v4/wxs/iis">
...
      <!-- Guid="" means that we do not want to uninstall the root ca -->
      <Component Id="DevRootCertificate" Guid="">
        <iis:Certificate Id="Certificate.RootCA" Name="Test Root certificate" Request="no" StoreLocation="localMachine" StoreName="root" Overwrite="yes" BinaryRef="DevRootCertificate" />
      </Component>

      <Component Id="LocalhostCertificate" Guid="{630977F7-F6D8-4865-98E0-A4A29C3445A2}">
        <iis:Certificate Id="Certificate.Localhost" Name="Test localhost certificate" Request="no" StoreLocation="localMachine" StoreName="personal" Overwrite="yes" BinaryRef="LocalhostCertificate" />
      </Component>
```

It seems that the Iis extension library is not passed to the linker.

**Comment by barnson** [comment]
IIS isn't officially part of Preview Zero -- and that's why. :) It'll be in the next preview.

> The most popular WiX extensions -- Util, UI, NetFx, and Bal -- were also published to NuGet.org.

https://www.firegiant.com/blog/2021/5/27/wix-online-meeting-213-highlights/

**Comment by barnson** [comment]
This was fixed in https://github.com/wixtoolset/wix4/pull/39.
