### ISSUE TITLE
`WixBundleExecutePackageCacheFolder` is not accessible in the BA process for per-machine packages

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6505]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Latest v3 and v4, this has been present since it was added (https://github.com/wixtoolset/issues/issues/3736).

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2016-June/002319.html
> Try to access `WixBundleExecutePackageCacheFolder` from a BA when the executing package is per-machine.

* Describe the behavior you expected and how it differed from the actual behavior.

> `WixBundleExecutePackageCacheFolder` should be set in both the elevated process and the BA process.

**Comment by rseanhall** [comment]
I'm having second thoughts about this. I'm starting to remember thinking that it was a feature and not a bug that it's difficult for the BA to access this variable's value. The original use case was for using it in an ExePackage's command line, not for the BA. I'd like to know what the use case is for the BA to need it.

**Comment by barnson** [comment]
Triage concurs.
