### ISSUE TITLE
During bundle upgrade, packages that get a Major Upgrade are planned with Rollback:Uninstall

### ISSUE THREAD

**Issue by MatthiasRInst** [wixtoolset/issues#6509]
* Which version of WiX are you building with?

> 3.11.2318.0

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Enterprise 2019
> Version 16.2.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10, update 1803

* Describe the problem and the steps to reproduce it.

> Issue: In the planning phase, both “fresh install” and MajorUpgrade packages are planned with “Rollback:Uninstall” (regardless of dependencies). MinorUpgrade packages are planned with Rollback:None. This planning is then executed regardless of any dependencies (even though Burn detected the dependencies in the Detect phase). This occurs regardless of whether a dependency provider is given in the bundle (Dep:provides for the MSI packages) or not.

>
Steps to reproduce:
Create 4 MSI packages Package1..Package4. with ProductVersion 1.0.0
Package4 is special as it contains an Error custom action that enforces a rollback.
Create version 2.0.0 of Package1 and Package2, with ProductCode changed (Major Upgrade)
Create the following bundles:
"OtherBundle", containing Package1 and Package3 (both ProductVersion 1)
"MyBundle", version 1.0.0.0, containing Package1 and Package2 (both ProductVersion 1)
"MyBundle" version 2.0.0.0, containing Package 1 and Package 2 (both ProductVersion 2), as well as Package3 and Package4.
Install OtherBundle, then install MyBundle, version 1. This creates a baseline with both bundles depending on Package1, MyBundle depending on Package2, OtherBundle depending on Package3.
Then install MyBundle, version 2. This updates packages 1 and 2, adds a dependency to Package3, and when installing Package4, it rolls back.

* Describe the behavior you expected and how it differed from the actual behavior.

>Expected:
The major-upgrade packages (here Package1 and Package2) are either set back to their previous state or kept in their updated version.
Observed:
For the major-upgrade packages, bundle log file says "Rollback:Uninstall" in the plan phase. Installation of package 4 fails, as intended, then installation rolls back. The packages are then actually removed in the rollback, regardless of dependencies ("OtherBundle").

Binaries, SourceCode, and the final (rollback) bundle log file are attached:

[Binaries.zip](https://github.com/wixtoolset/issues/files/6822704/Binaries.zip)
[SourceCode.zip](https://github.com/wixtoolset/issues/files/6822705/SourceCode.zip)
[MyBundle_20210715114627.log](https://github.com/wixtoolset/issues/files/6822710/MyBundle_20210715114627.log)

**Comment by barnson** [comment]
Triage team memory is that this is the best solution that's possible, given that the upgrading bundle might not be able to reinstall the old MSI. It's better to remove it and let the old bundle repair it. (Automating that repair would be a Good Thing(tm).)

## History

https://github.com/wixtoolset/issues/issues/3190
https://github.com/wixtoolset/issues/issues/3421

**Comment by barnson** [comment]
We're closing this as we have the old bugs already. But thanks for the repro case!
