### ISSUE TITLE
Rollback of bundle upgrade breaks dependencies

### ISSUE THREAD

**Issue by MatthiasRInst** [wixtoolset/issues#6510]
* Which version of WiX are you building with?

> 3.11.2318.0

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Enterprise 2019
> Version 16.2.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.4

* Which version of .NET are you building with?

> 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10, update 1803

* Describe the problem and the steps to reproduce it.

> Issue: When a bundle upgrade is rolled back, dependency providers of its packages are removed even though there are other dependents. This occurs regardless of whether a dependency provider is given in the bundle (Dep:provides for the MSI packages) or not.

>Steps to reproduce:
Create 4 MSI packages Package1..Package4. with ProductVersion 1.0.0
Package4 is special as it contains an Error custom action that enforces a rollback.
Create version 1.1.0 of Package1 and Package2, with ProductCode unchanged (Minor Upgrade)
Create the following bundles:
"OtherBundle", containing Package1 and Package3 (both ProductVersion 1)
"MyBundle", version 1.0.0.0, containing Package1 and Package2 (both ProductVersion 1.0)
"MyBundle" version 2.0.0.0, containing Package 1 and Package 2 (both ProductVersion 1.1), as well as Package3 and Package4.
Install OtherBundle, then install MyBundle, version 1. This creates a baseline with both bundles depending on Package1, MyBundle depending on Package2, OtherBundle depending on Package3.
Then install MyBundle, version 2. This updates packages 1 and 2, adds a dependency to Package3, and when installing Package4, it rolls back.
I have not included a Major upgrade scenario here, because the major-upgraded packages are uninstalled during rollback (see issue #6509), which masks the current error.

(Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

>Expected:
For the packages that were present before the upgrade (here Package1, Package2, and Package3), the dependency providers are still available after the rollback, with both OtherBundle and MyBundle as dependents.
Observed:
For all packages affected by the bundle upgrade, the dependency providers are removed during rollback. This can be seen both in the log file and in the registry. Thus dependency handling is broken.

Binaries, SourceCode, and the final (rollback) bundle log file are attached:

[Binaries.zip](https://github.com/wixtoolset/issues/files/6822742/Binaries.zip)
[SourceCode.zip](https://github.com/wixtoolset/issues/files/6822743/SourceCode.zip)
[MyBundle_20210715130733.log](https://github.com/wixtoolset/issues/files/6822744/MyBundle_20210715130733.log)

**Comment by rseanhall** [comment]
I'm pretty sure this is the intended behavior. When Burn uninstalls a package, it's supposed to remove all of its dependency metadata.

**Comment by MatthiasRInst** [comment]
This is not about uninstallation, but about rollback. In cases where bundle rollback does not and shall not uninstall packages, it does remove the dependency metadata.

Best regards

Matthias

Von: Sean Hall ***@***.***>
Gesendet: Donnerstag, 15. Juli 2021 17:16
An: wixtoolset/issues ***@***.***>
Cc: Matthias Reuss ***@***.***>; Author ***@***.***>
Betreff: Re: [wixtoolset/issues] Rollback of bundle upgrade breaks dependencies (#6510)


CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

________________________________



I'm pretty sure this is the intended behavior. When Burn uninstalls a package, it's supposed to remove all of its dependency metadata.

-

**Comment by rseanhall** [comment]
Sorry, I see what you mean now. I missed that the packages were minor upgrades so that the packages weren't uninstalled as part of rollback.
