### ISSUE TITLE
/xlog does not cause elevated process to log at DEBUG level

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6534]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> latest v4

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Run a per-machine bundle with the /xlog switch on a machine without any of the registry settings that would influence Burn's logging level.

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected: Logging from elevated process includes VERBOSE and DEBUG events.
> Actual: Logging from elevated process is at default level.

**Comment by barnson** [comment]
As of `5132ee4ed0220e7856dd6908753eba51e52bfada` and `42964da2a12df3b6e7d658a8037f17be003b1947`, this issue does not repro. Burn defaults to verbose logging (in release mode -- debug-level logging for debug builds) and there's only a handful of debug-level logging from the elevated side. For an experiment, I turned some logging to debug level and it correctly respected `/log` -v- `/xlog`.

**Comment by rseanhall** [comment]
How is that possible? The unelevated process needs to somehow inform the elevated process that debug logging was requested and I haven't seen that done anywhere. All of dutil logging is currently done only at the debug level so that's valuable information that could be missing.
