### ISSUE TITLE
bal:SuppressDowngradeFailure should cause wixstdba to not even try to Plan or Apply

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6537]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> http://lists.wixtoolset.org/pipermail/wix-users-wixtoolset.org/2021-July/009832.html

* Describe how you're accomplishing the feature today (if possible).

> I guess BAFunctions might be able to do this.

* Describe what you'd like the new feature to do.

> wixstdba should quit with exit code 0 when downgrade is detected and bal:SuppressDowngradeFailure="yes".

**Comment by rseanhall** [comment]
The initial fix for this caused https://github.com/wixtoolset/issues/issues/6722, so it was reverted. However, the root cause for the complaint in the mailing list was fixed by getting the engine to not plan anything during a downgrade (https://github.com/wixtoolset/wix4/pull/140). There are two things to consider here:
1. Should we try to reimplement the change to skip to the Successful page so that the user doesn't have to click the Install button (and fill out any required information)?
2. Should the SuppressDowngradeFailure feature be moved into the engine instead of a wixstdba feature?

**Comment by barnson** [comment]
I do like the idea of not needing to click Install just to immediately "succeed." However, do we want to make that call based only on the default action (i.e., before planning)? (I don't want to get away from the typical plan/apply pair after the install gesture.)

**Comment by barnson** [comment]
I don't have any strong feelings about this being an engine -v- ba feature.

**Comment by barnson** [comment]
BA-only decision based on data available after Detect.
