### ISSUE TITLE
Asp.Net MSI installer exit with error code: MSI (s) Doing action:StartIIS7ConfigTransaction -- Error 26031. Failed to schedule transaction for changes to IIS.  (-2147418113 )

### ISSUE THREAD

**Issue by venkatEngx** [wixtoolset/issues#6546]
Asp.Net MSI Wix installer failed with error:
 MSI (s) Doing action:StartIIS7ConfigTransaction -- Error 26031. Failed to schedule transaction for changes to IIS.  (-2147418113 ) during

Deployment: Deploying MSI installer from remote machine using powershell script.

If this issue is a bug:

* Which version of WiX are you building with?

> 1.0.0.0

* Which version of Visual Studio are you building with (if any)?

> 2010

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.0

* Which version of .NET are you building with?

> .Net 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 2016

* Describe the problem and the steps to reproduce it.

> Run MSI installer from remote machine using Powershell script with service account with admin privilege's.

* Describe the behavior you expected and how it differed from the actual behavior.

>MSI (s) (54!A4) [20:51:34:367]: PROPERTY CHANGE: Adding StartIIS7ConfigTransaction property. Its value is '**********'.
MSI (s) (54!A4) [20:51:34:367]: Doing action: StartIIS7ConfigTransaction
MSI (s) (54!A4) [20:51:34:367]: Product: ***Installer Name
[MSI_Installer_Issue.txt](https://github.com/wixtoolset/issues/files/6995992/MSI_Installer_Issue.txt)
[MSI_Installer_Issue.txt](https://github.com/wixtoolset/issues/files/6995993/MSI_Installer_Issue.txt)
 [2008-07-10] -- Error 26031. Failed to schedule transaction for changes to IIS.  (-2147418113         )

Attached detailed log file for referrence.

**Comment by barnson** [comment]
We need more information to proceed.
