### ISSUE TITLE
We get error when build WIX setup project. Error : The WiX Toolset v3.11 (or newer) build tools must be installed to build this project.

### ISSUE THREAD

**Issue by LallanGupta** [wixtoolset/issues#6548]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

> (WIX Toolset 3.11)

* Which version of Visual Studio are you building with (if any)?

> (Microsoft Visual Studio Professional 2019 Version 16.10.3)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset 3.11)

* Which version of .NET are you building with?

> (.NET 5.0)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (We are facing issue building WIX project using .Net5.0 )

* Describe the problem and the steps to reproduce it.

> (We are able to build the project using VS2019 but when we build the same project in the build server using dotnet.exe (SDK5.0.302 or using command line it fails with error "The WiX Toolset v3.11 (or newer) build tools must be installed to build this project". We use command line as "dotnet.exe build C:\ADSBuilds\1\142\s\Utilities\UFSS.Converter\Dev\UFSS.Converter-Test\UFSS.Converter.sln --configuration release --no-restore --verbosity n --output C:\ADSBuilds\1\142\a". Kindly note when we remove the wix project everything works fine so looks like WIX project has some issues)

* Describe the behavior you expected and how it differed from the actual behavior.

> (We expect this project should be built successfully using command line

I am attaching the output log of command line used to build the project.

[OUTPUT.txt](https://github.com/wixtoolset/issues/files/7013512/OUTPUT.txt)
)

**Comment by barnson** [comment]
Known issue: https://github.com/wixtoolset/issues/issues/5627
