### ISSUE TITLE
The custom action conditions not working 

### ISSUE THREAD

**Issue by NikhatNOV** [wixtoolset/issues#6552]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)

**Comment by NikhatNOV** [comment]
**THESE ARE NOT WORKING IN WIX 4.0.0**

How to Set Custom Action Conditions?
Conditions are set depending on your specific needs and can be easily customized to a great extent. They can include references to installer properties, environment variables, installation folders, state/action of a component/feature, etc.

Below, you can find a list of the most common conditions:

NOT Installed – evaluates to TRUE during the MSI installation only
NOT Installed OR REINSTALL – evaluates to TRUE during the MSI installation and repair
REMOVE = "ALL" – evaluates to TRUE during the MSI uninstallation and upgrade
(REMOVE = "ALL") AND NOT UPGRADINGPRODUCTCODE – evaluates to TRUE during the MSI uninstallation only

**Comment by barnson** [comment]
Please be more specific: How are you using them?

**Comment by NikhatNOV** [comment]
<Custom Action="DeleteScripts" After="RunApiServicesInstall">NOT Installed</Custom>
        <Custom Action="RunApiServicesStop" After="InstallInitialize">REMOVE="ALL"</Custom>
        <Custom Action="RunApiServicesUninstall" After="RunApiServicesStop">REMOVE="ALL"</Custom>

**Comment by NikhatNOV** [comment]
It does not build (wix build Test.wxs) gives error

**Comment by barnson** [comment]
What errors?

**Comment by NikhatNOV** [comment]
![image](https://user-images.githubusercontent.com/38424251/130485653-2cf65889-14de-4b42-a4a1-d2e388de0771.png)

**Comment by barnson** [comment]
Use the `Condition` attribute instead. `wix convert` converts WiX v3 to v4 authoring.
