### ISSUE TITLE
ProcessorArchitecture variable reports the wrong value for x64 bundle on ARM64

### ISSUE THREAD

**Issue by ericstj** [wixtoolset/issues#6556]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

3.11.4516.0

* Which version of Visual Studio are you building with (if any)?

N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

N/A

* Which version of .NET are you building with?

.NET5.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 11

* Describe the problem and the steps to reproduce it.

Install an x64 bundle on an ARM64 machine.  Try to observe the native machine architecture in order to make decisions in your bundle.  The `ProcessorArchitecture` value will be `9` indicating that machine is actually `x64`.

* Describe the behavior you expected and how it differed from the actual behavior.

I can't say I didn't expect this, Windows is lying to the process and the property is documented as returning the value from the API that's being lied to.

I propose we add a new property `NativeMachine` and have it return the value of `*pNativeMachine` from https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2. 

It might be interesting to expose the same from a custom-action so that MSI's might do the same.

Do we think this would be possible in an update to WiX?

cc @joeloff

**Comment by ericstj** [comment]
> That matches, as in WiX v3.14, Burn is x86 only.

Right, though I was getting at something a bit different.  Win10 permits execution of x86 code on ARM64 devices (EG: Surface Pro X) so this is already an issue, though for x86 you can still identify that the host is not x86 though other properties.  x86 also maintains the same redirection on ARM64 as it had on x86.   Win11 makes it more important, as the insider builds of Win11 permit x64 to run on ARM64 and there is no redirection nor any other property to identify that the machine is not a native x64 machine.

**Comment by barnson** [comment]
It's sad that Windows thinks that lying via API is appropriate. It's a horrible violation of Kantian ethics. (It makes me wonder what kind of ethical system Windows runs under...if any.) We knew about version lying, so did the work to undo Windows' ethical violations. Apparently Burn needs to do the same here.

**Comment by ericstj** [comment]
I don't speak for Windows, so I cannot say for sure, but I bet it's due to compatibility.  Ethically speaking, perhaps they broke fewer things by doing this.  I'm making sure they understand the reverse side of that, since the decisions made for back-compat are making it harder to create new software that "knows" about ARM64 to do the right thing.

The fact that Win10 already shipped this behavior is what makes me think that it's probably a good thing to add this regardless.  Even if we convince Windows to do something to make this better for x64/ARM64 on Win11 there is still value in this feature (`NativeMemory`).

**Comment by ericstj** [comment]
To close the loop on the urgency of this.  Given the recent announcement of Win11 going live on October 11, including the support for x64 to run and install on ARM64, this will become a problem for everyone that ships both x64 and ARM64 installers at that point.  It doesn't seem like there is time to get MSI to add some native support for something here, and regardless of that it wouldn't help the bootstrapper case.   I'll attend next Thursday's meeting to discuss this.  Look forward to seeing you!

**Comment by barnson** [comment]
Merged into both `wix3` and `wix4`.

**Comment by joeloff** [comment]
What is the process of getting a new official 3.x build?

**Comment by robmen** [comment]
From: https://www.firegiant.com/blog/2021/9/9/wix-online-meeting-219-highlights/

> We agreed to take this issue in both WiX v3.14 and v4 and to review the pull requests and get builds out as soon as reasonably practical.

Also from that meeting:
1. @rseanhall will say when he's done
2. After that, I said give me 5'ish days to get around to it

**Comment by rseanhall** [comment]
I said I was done here: https://github.com/wixtoolset/wix3/pull/538#issuecomment-919444778

**Comment by robmen** [comment]
Thanks, @rseanhall. I'll queue the build in my workflow immediately.
