### ISSUE TITLE
Software installation was blocked because the prompt was added to the startup entry

### ISSUE THREAD

**Issue by BluceBosen** [wixtoolset/issues#6571]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Professional 2019 version 16.9.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Wix toolset version 1.0.0.4

* Which version of .NET are you building with?

> .NET 4.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> When installing the WixBootstrapper form WiX/Burn., it will be added to the startup item and then deleted immediately. As a result, the security defense software on some computers will report "add to system item", so as to prevent its installation. Unless the user chooses trust, is there a good solution?

The Registry key:
HKEY_ LOCAL_ MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\RunOnce - [{20979c74-a3d9-49d5-82fe-08472efd2bb6}]

* Describe the behavior you expected and how it differed from the actual behavior.

> When the software is installed, it will not be added to the startup item, so that the security software will not prevent the installation

**Comment by rseanhall** [comment]
Did you see https://github.com/wixtoolset/issues/issues/5482?

**Comment by BluceBosen** [comment]
I just read it. It's the same problem as I described, but I'm sorry I didn't see how to solve it

**Comment by BluceBosen** [comment]
The problem occurs due to Burn's use of the RunOnce registry key, which is how a bundle resumes following a mid-chain reboot. Until/unless we see the frequency of this problem rise up, we're content to not try to architect a solution that doesn't trigger this problem.In order to use the RunOnce key in the way that it was intended to be used - to complete installation after a reboot (or the machine loses power, etc).
Does this mean that the current situation will not change?Can we use it as a configuration item to prevent many defensive software errors from preventing its installation？Because I use three defense software, two of them have errors, and their market share is still very high in my region,thanks.

**Comment by rseanhall** [comment]
There are basically 3 options for you.

1. Write up a proposal that meets all of the functionality we need and works perfectly with all antivirus vendors while still being secure. Then you'd have to wait until someone implements the proposal and it gets into an official build.
2. Work with the antivirus vendors to get them to stop blocking Burn, such as reporting your bundle as a false positive.
3. Change this issue into a feature request to explain what you mean by "use it as a configuration item to prevent many defensive software errors from preventing its installation". Make sure to follow our template so we get the information we need. Then you'd have to wait until someone implements the feature and it gets into an official build.

**Comment by BluceBosen** [comment]
Ok,Fine,thank you

**Comment by barnson** [comment]
Let us know what you decide.
