### ISSUE TITLE
Add to the registry of startup as the default configuration on WiX/Burn installation , it could be changed later

### ISSUE THREAD

**Issue by BluceBosen** [wixtoolset/issues#6575]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> (When installing the WixBootstrapper form WiX/Burn, it will be added to the system's startup item and then deleted immediately. As a result, the security defense software on some computers will report "add to system's startup item", so that to prevent its installation,Unless the user chooses trust.I use three security defense software, two of them have errors, and their market share is still very high in my region.The Registry key:
HKEY_ LOCAL_ MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\RunOnce - [{20979c74-a3d9-49d5-82fe-08472efd2bb6}]
 I use three defense software, two of them have errors, and their market share is still very high in my region.)

* Describe how you're accomplishing the feature today (if possible).

> (We should treat it as a changeable property or configuration.Keep the current mode by default,after changing its value, it will not be added to the startup registry entry)

* Describe what you'd like the new feature to do.

> (If we deal with it in this way, we will not receive false positives from some security defense software, resulting in many users thinking that the software contains viruses, so they do not trust and install the produced software package.)

**Comment by rseanhall** [comment]
Are you interested in opting out at build time (when you are building the bundle) or at runtime (when the user is running the bundle)?

**Comment by BluceBosen** [comment]
No,If the user finds that the security software gives a prompt, no matter what the prompt is, it is unlikely to continue the installation, especially for some users who do not understand the software.The judgment mechanism of security software is very simple,as long as the startup registry is added, it will prompt.If add to the startup registry as a configuration item,there will be no prompt to be misunderstood as malware

**Comment by rseanhall** [comment]
I'll try to ask the question another way. Let's say that one of your bundles requires a restart in the middle of execution. Are you aware that you'll have to provide support to users that don't understand that your bundle is only partially installed after the reboot and they have to run it again to complete the installation?

**Comment by BluceBosen** [comment]
Yes, in some cases, we need to reboot and complete the subsequent installation.Therefore, the current method is retained by default, but a value can also be set. In some cases, it does not need to be added to the startup registry , which avoids prompt of security software.It doesn't change much.

**Comment by barnson** [comment]
Metaissue: https://github.com/wixtoolset/issues/issues/6589
