### ISSUE TITLE
Accessibility: WixUIDialogBmp should not have alt text

### ISSUE THREAD

**Issue by SteveL-MSFT** [wixtoolset/issues#6585]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.1.1

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> .NET 6 RC1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> 10.0.19043

* Describe the problem and the steps to reproduce it.

> Install https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x64.msi
> Use a screenreader during install

* Describe the behavior you expected and how it differed from the actual behavior.

> The background image in the dialog is decorative and so should not have alt-text that would be read by a screen reader

![image](https://user-images.githubusercontent.com/11859881/134087815-25d46fd5-fcf7-42a5-82bb-f552d68423c4.png)

**Comment by barnson** [comment]
Windows Installer sets that property and doesn't expose a method of changing it.
