### ISSUE TITLE
Accessibility: Screen reader not reading the "Installation was successful" message 

### ISSUE THREAD

**Issue by SteveL-MSFT** [wixtoolset/issues#6586]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.1.1

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> .NET 6 RC1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> 10.0.19043

* Describe the problem and the steps to reproduce it.

> Install https://github.com/PowerShell/PowerShell/releases/download/v7.1.4/PowerShell-7.1.4-win-x64.msi with a screen reader, get to the end of the installation

* Describe the behavior you expected and how it differed from the actual behavior.

> Where it shows the built-in "The installation was successful" message in the dialog, this text isn't read by a screen reader.

**Comment by barnson** [comment]
That isn't a WixUI dialog, it's one your team wrote.

**Comment by SteveL-MSFT** [comment]
@barnson to be clear, when you say "your team", you mean the Windows installer team?  The PowerShell wix doesn't define that dialog or text https://github.com/PowerShell/PowerShell/blob/master/assets/wix/Product.wxs

**Comment by rseanhall** [comment]
A quick glance shows [this line](https://github.com/PowerShell/PowerShell/blob/d3d81c3e4453b0c03307fb488e1b60761edb7ce9/assets/wix/Product.wxs#L146):

> `<UIRef Id="CustomWixUI_InstallDir" />`

`CustomWixUI_InstallDir` is not something provided by WiX, that's a custom UI code that's somewhere in your source.

**Comment by barnson** [comment]
https://github.com/PowerShell/PowerShell/blob/master/assets/wix/Product.wxs#L111

**Comment by SteveL-MSFT** [comment]
Thanks!  I'll have someone on my team look into this.

**Comment by robmen** [comment]
@SteveL-MSFT I'm evaluating issues that are `external` but required core WiX maintainers' time to resolve.

Can you help me understand a) why this issue was opened against the WiX Toolset initially and b) why a follow-up was required to point out the exact location of the customization in the PowerShell codebase? Thanks.
