### ISSUE TITLE
Signing Custom Actions project is not currently possible

### ISSUE THREAD

**Issue by JasonWhall** [wixtoolset/issues#6593]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2

* Which version of Visual Studio are you building with (if any)?

> VS2019

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> Framework 4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Signing a Custom actions project after building using WiX 3.11.2 causes an error to occur and is the same issue as described in #6089 with steps to reproduce. This issue was fixed in commit [448bd5a](https://github.com/wixtoolset/wix3/commit/448bd5a55d18f4ab1ca8f1cd7a0f15cf94fab88e). However has not been released yet. 

> At the moment a [development version](https://wixtoolset.org/releases/development/) of WiX has to be used to include the correct signing behaviour or alternatively, hacking away at the existing 3.11.2 version to remove the digital signature on `sfxca.dll`

* Describe the behavior you expected and how it differed from the actual behavior.

> A 3.x version of the WiX toolset to be released that includes the signing fixes.

**Comment by barnson** [comment]
As you note, WiX v3.14 builds with the fix are available. When WiX v4.0 ships, there will be a "final" build of WiX v3.14.
