### ISSUE TITLE
Trying to install VS2019 Extension - Unexpected character while parsing value

### ISSUE THREAD

**Issue by btomblinson** [wixtoolset/issues#6594]
[dd_VSIXInstaller_20210928112345_4168.log](https://github.com/wixtoolset/issues/files/7246220/dd_VSIXInstaller_20210928112345_4168.log)

Trying to install the WIX Extension for VS2019 on a new machine and keep getting this error. It does the same thing whether I try to install from the download on the WIX website or via extensions in Visual Studio

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
