### ISSUE TITLE
Feature Request: include Wix Toolset installers in winget, pretty please!

### ISSUE THREAD

**Issue by CrapuleJack** [wixtoolset/issues#6601]
## Feature requests

* Describe the scenario and benefits that the feature supports.

When deploying a new dev station, I now use a powershell script to install all software required. Wix is sadly missing from the new winget repository, and thus must be installed manually.

I would suggest creating a few packages, one for the main wix toolset install and some other for each version of visual studio plugins supported.

* Describe how you're accomplishing the feature today (if possible).

Old boring unscriptable manual install :)

* Describe what you'd like the new feature to do.

Id like to be able to add wix toolset on my systems by using commands like:
winget install --id WixToolset.WixToolset
winget install --id WixToolset.VS2019Extention

**Comment by sitiom** [comment]
Resolved in https://github.com/microsoft/winget-pkgs/pull/895

**Comment by robmen** [comment]
`wix.exe` itself is available as dotnet tool and `WixToolset.Sdk` provides seamless integration in .wixproj. That just leaves the WiX Additional Tools and those are now published to `winget`.

**Comment by Wallby** [comment]
> `wix.exe` itself is available as dotnet tool and `WixToolset.Sdk` provides seamless integration in .wixproj. That just leaves the WiX Additional Tools and those are now published to `winget`.

Not a fan of dotnet as the installer doesn't even allow to opt out of telemetry.
Also not a fan of having to install another program first then install wix via that program. I.m.o. the whole point of winget is to make such secondary package managers obsolete.

**Comment by slonopotamus** [comment]
> the whole point of winget is to make such secondary package managers obsolete

I'm not sure about that given that winget is not available on Windows Server.

**Comment by Wallby** [comment]
> > the whole point of winget is to make such secondary package managers obsolete
> 
> I'm not sure about that given that winget is not available on Windows Server.

Has been requested apparently.. https://github.com/microsoft/winget-cli/issues/702

**Comment by brandonh-msft** [comment]
> `wix.exe` itself is available as dotnet tool and `WixToolset.Sdk` provides seamless integration in .wixproj. That just leaves the WiX Additional Tools and those are now published to `winget`.

```
> dotnet tool install -g wixtoolset.sdk
Skipping NuGet package signature verification.
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'wixtoolset.sdk' failed to install. Contact the tool author for assistance.
```
