### ISSUE TITLE
Motivational quotes on startup

### ISSUE THREAD

**Issue by Chetan11-dev** [wixtoolset/issues#6617]
you people do it all wrong.
You instead should have motivating quotes on startup such as:

"Great Designer you are", "Hero Designer", "Mater Designer", It will maake us happy. Get it done quickly.

**Comment by Chetan11-dev** [comment]
DO it quick

**Comment by barnson** [comment]
If you're looking to comment on wix.com, you're in the wrong place.

**Comment by Chetan11-dev** [comment]
It is a good feautre.
