### ISSUE TITLE
wix3 and wix4 both still needed .net 3.5 to be installed

### ISSUE THREAD

**Issue by mzayarnyuk** [wixtoolset/issues#6638]
## Old .net is still referred

wix3 and wix4 both still needed .net 3.5 to be installed;
it's complicated and annoying;
and I am sure is simple to up or replace most of old refs to 4.0 and rebuild;

**Comment by robmen** [comment]
WiX v4-preview.0 (and RTM) does not require .NET Framework v3.5 to be installed. Changing the underlying .NET Framework version in WiX v3.x could break old projects so we've chosen not to do that.

**Comment by mzayarnyuk** [comment]
just tried wix4 release wix40.exe 4.0.0.52.05 still ask about .net 3.5;
will try to check src but with build there can be issues as always;
and not sure if old VS projects with 3.11 wix will compatible or autoupdateable to wix4

**Comment by mzayarnyuk** [comment]
https://wixtoolset.org/releases/v3-14-0-5722/
that one start without 3.5 net; hope will workable

**Comment by robmen** [comment]
Where did you get a `wix40.exe`? There is no `wix40.exe` install in WiX v4 anymore (it should not be navigatable on the website). [It's a dotnet tool now. ](https://robmensching.com/blog/posts/2021/5/17/wix-toolset-v4-preview.0/).

**Comment by mzayarnyuk** [comment]
https://wixtoolset.org/releases/v4-0-0-5205/
it's on yours oficial site; rtm preview 0;
rtm preview 1 was not able to find;
looks like now link is hidden from download page

**Comment by mzayarnyuk** [comment]
what about upgrade vs projects created with v3.x to v4.x (we used iis activation and webapi installs and bundle with app install) ?
is it possible ?
or it will be complicated and better still use v3.x ?

**Comment by mzayarnyuk** [comment]
later maybe will try this one; maybe it will without 3.5 net looks like; or maybe will wait to preview.1 official;
https://www.nuget.org/packages/wix/4.0.0-preview.0

**Comment by rseanhall** [comment]
This is a duplicate of https://github.com/wixtoolset/issues/issues/5711. I fixed it in v3.14 almost 3 years ago, you can grab development versions of that from the website. Please use [Discussions](https://github.com/wixtoolset/issues/discussions) for your questions.
