### ISSUE TITLE
Heat Project Harvesting C++ projects doesn't work with Visual Studio 2022/MSBuild 17.0

### ISSUE THREAD

**Issue by jmairboeck** [wixtoolset/issues#6641]
* Which version of WiX are you building with?

> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> 2022 (17.0.1)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.12 (manually downloaded from Github releases)

* Which version of .NET are you building with?

> 4.8.04084

* Describe the problem and the steps to reproduce it.

> We use project harvesting to harvest the output from project references. We also use the workaround from https://github.com/wixtoolset/issues/issues/3496/#issuecomment-166096483 because the project is a library (if that matters).

The project reference is defined as follows (example):

```
<ProjectReference Include="..\..\external\Scintilla\Scintilla\win32\SciLexer.vcxproj">
      <Name>SciLexer</Name>
      <Project>{fbe04237-9c7b-4973-9c60-505975998b39}</Project>
      <Private>True</Private>
      <DoNotHarvest>
      </DoNotHarvest>
      <RefProjectOutputGroups>Binaries</RefProjectOutputGroups>
      <RefTargetDir>INSTALLFOLDER</RefTargetDir>
    </ProjectReference>
```

The heat command that is executed during the build:

`C:\Program Files (x86)\WiX Toolset v3.11\bin\Heat.exe project <path>\external\Scintilla\Scintilla\win32\SciLexer.vcxproj -configuration Release -directoryid INSTALLFOLDER -platform x64 -pog Binaries -pog Symbols -pog Sources -pog Content -pog Satellites -pog Documents -projectname SciLexer -ag -sfrag -out obj\x64\Release\_SciLexer.wxs`

(I have obfuscated the path)

It fails with the following error message:

`heat.exe(0,0): error HEAT5305: Failed to load project <path>\external\Scintilla\Scintilla\win32\SciLexer.vcxproj: Das importierte Projekt C:\Microsoft.Cpp.Default.props wurde nicht gefunden. Vergewissern Sie sich, dass der Pfad in der <Import>-Deklaration korrekt und die Datei auf dem Datenträger vorhanden ist.`

It seems that the `VCTargetsPath` MSBuild variable is empty during the execution of Heat and it doesn't find `Microsoft.Cpp.Default.props`. The .vcxproj project file contains the following (as any standard C++ project):

`<Import Project="$(VCTargetsPath)\Microsoft.Cpp.Default.props" />`

* Describe the behavior you expected and how it differed from the actual behavior.

> This should work the same as it does using Visual Studio 2019/MSBuild 16.0 (which it does).

**Comment by jmairboeck** [comment]
The problem seems to be `ToolsVersion="Current"` in the .vcxproj file. With that setting, the same problem also occurs in Visual Studio 2019.

Before we were using `ToolsVersion="14.0"`. But with that, the following error occurs:

`heat.exe(0,0): error HEAT5316: Failed to load MSBuild wrapper object: Die Datei oder Assembly "Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.`

It doesn't find the assemby Microsoft.Build, Version 14.0.0.0.

**Comment by rseanhall** [comment]
Heat has had this problem ever since MSBuild was deployed with side-by-side Visual Studio instead of the .NET Framework or a separate install. See https://github.com/wixtoolset/issues/issues/4853 and https://github.com/wixtoolset/issues/issues/5490.

**Comment by rseanhall** [comment]
The fix was for MSBuild to pass its `bin` path to heat.exe as an argument. I needed to verify that the bitness of the currently running MSBuild always matched the bitness of the heat.exe that is getting invoked.

Unfortunately, .NET Core MSBuild did not support running tasks from a separate host (which is required if heat.exe requires x86 and the currently running MSBuild is x64) until a few weeks ago - https://github.com/dotnet/msbuild/issues/5158. I'm going to go ahead and close this since project harvesting shouldn't care whether heat.exe is running x86 or x64 and create a separate issue. It was already fixed in v4 and the change was not backwards compatible so it won't be backported to v3.
