### ISSUE TITLE
Please update for Visual Studio 2022

### ISSUE THREAD

**Issue by JohnTasler** [wixtoolset/issues#6644]
Here's an article on what's needed to do this:
[Update a Visual Studio extension for Visual Studio 2022](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022)

From the code in the [develop](https://github.com/wixtoolset/VisualStudioExtension/tree/develop) branch, It appears that someone is working on this, but I'm filing this issue to track it, since doesn't yet appear to be released onto the VS2022 Marketplace.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues?q=is%3Aissue+2022
