### ISSUE TITLE
Cannot Load a .NET 5.0 Assembly on Build

### ISSUE THREAD

**Issue by AteCoder** [wixtoolset/issues#6645]
* Which version of WiX are you building with?

> (3.11.2.4516)

* Which version of Visual Studio are you building with (if any)?

> (Microsoft Visual Studio Community 2019 Version 16.11.7)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (not using an extension)

* Which version of .NET are you building with?

> (5.0)

* Describe the problem and the steps to reproduce it.

I am building multi-target MSI assemblies.  The build works find when targeting net472 and net48 but files when targeting net50-windows with the following error:  

`
The assembly file 'C:\My\lib\vs\io\vi\src\apps\isr.VI.Visa.IO\bin\Debug\net5.0-windows\isr.VI.Visa.IO.exe' appears to be invalid.  Please ensure this is a valid assembly file and that the user has the appropriate access rights to this file.  More information: HRESULT: 0x80131018	isr.VI.Visa.IO.WiX	C:\My\lib\vs\io\vi\src\apps\isr.VI.Visa.IO.WiX\Product.wxs	93	
`  

The assembly isr.VI.Visa.IO.exe runs fine.  

While debugging, I removed the Assembly attributes   

`
Assembly='.net' AssemblyApplication='fid.isr.VI.Visa.IO.exe' AssemblyManifest='fid.isr.VI.Visa.IO.exe'
`  

from the Component File statement:  

`
<Component Id='cid.isr.VI.Visa.IO.Program' Guid='*' >  
  <File Id='fid.isr.VI.Visa.IO.exe' Name='$(var.isr.VI.Visa.IO.TargetFileName)'  
		Source='$(var.isr.VI.Visa.IO.TargetPath)' KeyPath='yes' DiskId='1'  
		Assembly='.net' AssemblyApplication='fid.isr.VI.Visa.IO.exe' 
 AssemblyManifest='fid.isr.VI.Visa.IO.exe' >  
	<Shortcut Id='scid.isr.VI.Visa.IO.exe' Directory='ProductMenuDir'  
			  WorkingDirectory='BinDir' Name='$(var.isr.VI.Visa.IO.TargetName)'  
			  Icon='Product.ico' Advertise='yes'  />  
	  
  </File>  
</Component>  
`   

The build then broke at the following AfterBuild statement:  

`
<GetAssemblyIdentity AssemblyFiles="$(ProjectDir)..\isr.VI.Visa.IO\bin\$(Configuration)\$(_InstallerTargetFramework)\isr.VI.Visa.IO.exe">
  <Output TaskParameter="Assemblies" ItemName="AssemblyVersions" />
</GetAssemblyIdentity>
`  

with the error:  

`
Cannot get assembly name for "C:\My\lib\vs\io\vi\src\apps\isr.VI.Visa.IO.WiX\..\isr.VI.Visa.IO\bin\Debug\net5.0-windows\isr.VI.Visa.IO.exe". Could not load file or assembly 'isr.VI.Visa.IO.exe' or one of its dependencies. The module was expected to contain an assembly manifest.	isr.VI.Visa.IO.WiX	C:\My\lib\vs\io\vi\src\apps\isr.VI.Visa.IO.WiX\isr.VI.Visa.IO.WiX.wixproj	96	
`  

I presume this is a known issue that is being addressed in the upcoming release.   

Thank you  

David Hary

**Comment by Tarcontar** [comment]
I can confirm that, just updated a project to .net 5 and got the exact same error when i try to build the setup project.

**Comment by barnson** [comment]
MSI doesn't support .NET 5+ (aka .NET Core, not .NET Framework) and .NET 5+ doesn't support the GAC, so the assembly attributes don't really mean anything for .NET Core/5+ assemblies.

**Comment by Tarcontar** [comment]
Thx for the response!
So I can't create an MSI anymore? 
But a setup.exe should still work?

**Comment by robmen** [comment]
@Tarcontar The answer is to remove the `Assembly*` attributes:

> `Assembly='.net' AssemblyApplication='fid.isr.VI.Visa.IO.exe' AssemblyManifest='fid.isr.VI.Visa.IO.exe'`

The MSI should work fine.

This part of your issue

> The build then broke at the following AfterBuild statement:
>
> ```<GetAssemblyIdentity AssemblyFiles="$(ProjectDir)..\isr.VI.Visa.IO\bin\$(Configuration)\$(_InstallerTargetFramework)\isr.VI.Visa.IO.exe"> <Output TaskParameter="Assemblies" ItemName="AssemblyVersions" /> </GetAssemblyIdentity>```

Isn't from the WiX Toolset. Probably the `GetAssemblyIdentity` task of yours doesn't support .NET Core but I don't know what that task does so you'll need to investigate there.

**Comment by AteCoder** [comment]
Thanks for the reply!  

[GetAssemblyIdentity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.getassemblyidentity?view=msbuild-16-netcore) is an MSBuild Task, which is supported by MSBuild and MSBuild 16 (Core).   

I presume it would take figuring out which flavor of MSBuild is invoked from the IDE when compiling wixproj.

**Comment by AteCoder** [comment]
(1)  Removing the `Assembly*` attributes: confirmed.

(2) [GetAssemblyIdentity ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.getassemblyidentity?view=msbuild-16-netcore)  
specifying
`
  <PropertyGroup>
    <TargetFramework>net5.0-windows</TargetFramework>
  <PropertyGroup>
`
did not work. 

My work around for now is to point to a .NET framework assembly (e.g., `net472`) for getting the assembly version information:

`
  <PropertyGroup>  
    <_InstallerVersionFramework>net472</_InstallerVersionFramework>  
 <PropertyGroup>
`

`
<Target Name="AfterBuild">  
    <GetAssemblyIdentity AssemblyFiles="$(ProjectDir)..\isr.VI.Visa.IO\bin\$(Configuration)\$(_InstallerVersionFramework)\isr.VI.Visa.IO.exe">
      <Output TaskParameter="Assemblies" ItemName="AssemblyVersions" />
    </GetAssemblyIdentity>  
</Target>
`
