### ISSUE TITLE
DifxApp is deprecated, so WixDifxAppExtension should be removed from WiX v4

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6648]
* Describe the scenario and benefits that the feature supports.

> [DifxApp is deprecated](https://docs.microsoft.com/en-us/windows-hardware/drivers/install/difx-guidelines) and doesn't support ARM64 so we shouldn't ship it in WiX v4.

* Describe how you're accomplishing the feature today (if possible).

> n/a

* Describe what you'd like the new feature to do.

> n/a

**Comment by barnson** [comment]
Deprecation warning in v4.

**Comment by malyovanik** [comment]
@barnson  How to avoid deprecated messages?

**Comment by barnson** [comment]
Suppress the warning and/or stop using DifxApp.
