### ISSUE TITLE
bal.wixext - DncHostFixture.CanLoadTrimmedSCDEarliestCoreMBA() test failed

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6651]
**Encountered at:** https://github.com/wixtoolset/wix4/commit/dcdbe080bcbe191bf9543db58a44e57866d20576

**Detail:** Building with MSBuild64 (for VS2022) fails in the [DncHostFixture.CanLoadTrimmedSCDEarliestCoreMBA() test](https://github.com/wixtoolset/wix4/blob/develop/src/ext/Bal/test/WixToolsetTest.ManagedHost/DncHostFixture.cs).

```
[xUnit.net 00:00:01.48]     WixToolsetTest.ManagedHost.DncHostFixture.CanLoadTrimmedSCDEarliestCoreMBA [FAIL]
  Failed WixToolsetTest.ManagedHost.DncHostFixture.CanLoadTrimmedSCDEarliestCoreMBA [614 ms]
  Error Message:
   Assert.Equal() Failure
          ↓ (pos 0)
Expected: Creating BA thread to run asynchronously.
Actual:   Error 0x80131522: Failed to create the .N···
          ↑ (pos 0)
  Stack Trace:
     at WixToolsetTest.ManagedHost.DncHostFixture.CanLoadTrimmedSCDEarliestCoreMBA() in ...\wix4\src\ext\Bal\test\WixToolsetTest.ManagedHost\DncHostFixture.cs:line 62

Failed!  - Failed:     1, Passed:    13, Skipped:     0, Total:    14, Duration: 5 s - WixToolsetTest.ManagedHost.dll (netcoreapp3.1)
```

**Comment by rseanhall** [comment]
My guess would be that this is caused by a breaking change in the .NET 6 SDK and not MSBuild64/VS2022.

**Comment by robmen** [comment]
Ohh, fascinating. I guessed it was a 64-bit issue since references there were references to `x86` binaries. But the code did seem to launch executables so it didn't seem like 64-bit should be an issue.
