### ISSUE TITLE
Wax CoreEditor Error on VisualStudioExtension Install

### ISSUE THREAD

**Issue by sfullerbeckman** [wixtoolset/issues#6667]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> v3.11.2

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> v1.0.0.12 Prerelease

* Which version of .NET are you building with?

> .NET 4.8

* Describe the problem and the steps to reproduce it.

> The Wix toolset (v3.11.2) has been installed on my Windows computer. Installing the Visual Studio Extension (v1.0.0.12) in Visual Studio 2022, an error is thrown. `Wax This extension cannot be installed because the following references are missing: Microsoft.VisualStudio.Component.CoreEditor.` 
![Screenshot 2021-12-06 143740](https://user-images.githubusercontent.com/83652131/144910926-4b809add-8948-4f02-88cc-bec6bea85970.png)

* Describe the behavior you expected and how it differed from the actual behavior.

> I'd expect the extension to be installed successfully with no errors.

**Comment by sfullerbeckman** [comment]
Could this be because the Microsoft.VisualStudio.Component.CoreEditor version in the Source.extension.vsixmanifest in the Votive2022 directory was failed to be updated to the most recent version that supports VisualStudio 2022?

**Comment by robmen** [comment]
We don't work on "Wax" here. You'll want to follow up with the developers of that extension.
