### ISSUE TITLE
Burn needs to handle both 64-bit and 32-bit registry hives for 64-bit Burn engines

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6670]
* Describe the scenario and benefits that the feature supports.

> In WiX v3.x, all Burn engines are 32-bit and write to the 32-bit registry hive. In WiX v4, there are x64 and ARM64 engines as well, which write to the 64-bit registry hive. BUtil should handle this.

* Describe how you're accomplishing the feature today (if possible).

> n/a

* Describe what you'd like the new feature to do.

> Either take a bitness as an argument or enumerate over both 32-bit and 64-bit ARP hives.

**Comment by rseanhall** [comment]
I would think that deputil would have the same problem.

**Comment by barnson** [comment]
Butil as well but Burn engine is the high-order bit. 64-bit bundles need to handle the 32-bit registry for related bundles.

**Comment by barnson** [comment]
DepUtil is fine, only because the HKEYs are explicitly passed in. Burn's (and the compiler's) use of `Software\\Classes\\Installer\\Dependencies` is fine because `Software\\Classes` isn't redirected. https://docs.microsoft.com/en-us/windows/win32/winprog64/shared-registry-keys#redirected-shared-and-reflected-keys-under-wow
