### ISSUE TITLE
Extension for VS2022

### ISSUE THREAD

**Issue by pvkekem** [wixtoolset/issues#6673]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

On the download page of WixToolset, there is currently no option to download a VS2022 extension
(https://wixtoolset.org/releases/)

* Describe how you're accomplishing the feature today (if possible).

I'm using my VS2019 installation for now.

* Describe what you'd like the new feature to do.

Same awesomeness on VS2022.

**Comment by DaveMcD56** [comment]
Yes, please create this extension!

**Comment by barnson** [comment]
> Yes, please create this extension!

https://github.com/wixtoolset/issues/issues/6493

**Comment by carmangary** [comment]
I support this movement.

**Comment by ContentsMayVary** [comment]
This extension would be great and (moving forward) would allow us to just have Visual Studio 2022 installed on our development machines, rather than having to have Visual Studio 2019 installed as well.

**Comment by anton-martynyuk** [comment]
Please create this extension

**Comment by demidov71** [comment]
.NET 6 is available only on VS2022. Absence of WiX extension for it, hampers the development all over the world. Seriously, guys, leave the sofa!

**Comment by rseanhall** [comment]
https://github.com/wixtoolset/issues/issues/6493#issuecomment-968240767

**Comment by robmen** [comment]
@demidov71 You need to read this comment too: https://github.com/wixtoolset/issues/issues/6493#issuecomment-965493278
