### ISSUE TITLE
Dutch translation for UtilExtension for Wix v3 and v4

### ISSUE THREAD

**Issue by HarmvandenBrand** [wixtoolset/issues#6678]
I'm creating this issue so that I can reference it in my coming pull request, as instructed by the pull request instructions of the Wix repository.

## Feature requests

Currently, using the Util extension while the project's culture is set to nl-NL will yield an error:

`error LGHT0102: The localization variable !(loc.msierrSecureObjectsFailedCreateSD) is unknown.  Please ensure the variable is defined. [<path-to-my-wix-project>] C:\agent\_work\66\s\src\ext\UtilExtension\wixlib\UtilExtension.wxs(42): error LGHT0102: The localization variable !(loc.msierrSecureObjectsFailedSet) is unknown.  Please ensure the variable is defined. [<path-to-my-wix-project>]
C:\agent\_work\66\s\src\ext\UtilExtension\wixlib\UtilExtension.wxs(43): error LGHT0102: The localization variable !(loc.msierrSecureObjectsUnknownType) is unknown.  Please ensure the variable is defined.`

Presumably, this error occurs due to the lack of Dutch localization.

My project's culture setting is set to "nl-NL" and uses the Util extension. The aforementioned error occurs when Linking, with the following light command:

`C:\Program Files (x86)\WiX Toolset v3.11\bin\Light.exe -out "C:\Users\Herrum\Documents\Enveo\Enveo Revit Plugin\EnveoSetup\bin\Release\2019\EnveoSetup2019.msi" -pdbout "C:\Users\Herrum\Documents\Enveo\Enveo Revit Plugin\EnveoSetup\bin
  \Release\2019\EnveoSetup2019.wixpdb" -v -cultures:nl-NL -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUIExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.11\bin\\WixUtilExtension.dll" -contentsfile obj\Release\2019\E
  nveoSetup.wixproj.BindContentsFileListnl-NL.txt -outputsfile obj\Release\2019\EnveoSetup.wixproj.BindOutputsFileListnl-NL.txt -builtoutputsfile obj\Release\2019\EnveoSetup.wixproj.BindBuiltOutputsFileListnl-NL.txt -wixprojectfile "C:\
  Users\Herrum\Documents\Enveo\Enveo Revit Plugin\EnveoSetup\EnveoSetup.wixproj" obj\Release\2019\Product.wixobj`

The error does not occur when setting project culture to "en-US" or when not using the Util extension.

I'm currently making a pull-request for both Wix v3 and Wix v4 to add a Dutch translation. While awaiting approval, I will try to build  and use my fork. If in the meantime anyone could tell me if it's possible to point to an extension's localization file in a .wixproj file, that would be much appreciated.

**Comment by HarmvandenBrand** [comment]
Okay, I fixed the "issue" for myself by specifying a fallback culture (specifying `<Cultures>nl-nl,en-us</Cultures>` instead of only `<Cultures>nl-nl</Cultures>` in my .wixproj file). So the "I have an error" part of this issue can be disregarded. The contributed pull-requests still have value though, as they are legitimate translations.

**Comment by davidkarlsson** [comment]
This error also happens in WiX 4.0.0 when you don't set a locale attribute at all in the WixLocalization element. So it looks like the utils extension doesn't have a language neutral localization file to fallback on but it works if you specify "en-US" like @HarmvandenBrand said. 

Perhaps en-us.wxl for the extension should be renamed and have its culture attribute removed so it would be considered language neutral?

**Comment by barnson** [comment]
An American marking US English as "language neutral" would never be able to leave the country again. :)

**Comment by BMurri** [comment]
@barnson The platform targeted by WiX Toolset is always Microsoft Windows. US English has been "language neutral" since time immemorial.
