### ISSUE TITLE
tutorials  for wix 4 and dotnet cli

### ISSUE THREAD

**Issue by John0King** [wixtoolset/issues#6679]
## Triage

There no tutorials of wix-4 on wixtoolset.org .

## Feature requests

 we have dotnet cli verion of Wix now,
and it should be much easier for CI  with dotnet cli and dotnet cli template
I hope there are tutorials that I can lean.

**Comment by robmen** [comment]
There is plenty of work to do on the WiX website when WiX v4 is closer to being ready.
