### ISSUE TITLE
AzureSignTool: signature of bundle make the installation fails. Error 0x80070001: Failed to extract all files from container, erf: 1:2:0

### ISSUE THREAD

**Issue by valvador92** [wixtoolset/issues#6686]
## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> WiX version 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017

* Which version of .NET are you building with?

> 4.8.04084

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> I am creating a Bundle with Wix with 2 executables.
> I am signing those 2 .exe files with AzureSignTool before creating the bundle.
> Wix, 1st creates an .msi based on the 1st .exe. I sign this .msi with AzureSignTool.
> If I execute this .msi, installation goes fine, publisher is known.
> I sign the 2nd .exe
> Wix then creates the bundle.exe based on this signed .msi and the 2nd .exe signed file.
> If I try to install by using the  bundle.exe, it works but I have a warning message saying that the publisher is unknown.
> If I sign the bundle.exe and then try to install, I don't have a warning message saying that the publisher is unknown but installation fails...
> I am facing this error:
`Error 0x80070001: Failed to extract all files from container, erf: 1:2:0`
* Describe the behavior you expected and how it differed from the actual behavior.

> My program should install the same as with the signed .msi but with the signed bundle.exe file.

Here are the logs:
[logs_error_installation.txt](https://github.com/wixtoolset/issues/files/7774230/logs_error_installation.txt)

**Comment by barnson** [comment]
Bundles need special signing: https://wixtoolset.org/documentation/manual/v3/overview/insignia.html
