### ISSUE TITLE
Burn (`WixToolset.Burn.xxxx.nupkg`) does not have a .snupkg

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6698]
**Encountered at:** wixtoolset/wix4@db44f6cf

**Detail:**

Burn (`WixToolset.Burn.xxxx.nupkg`) does not have a .snupkg.

**Comment by robmen** [comment]
As per [this comment(https://github.com/wixtoolset/issues/issues/6461#issuecomment-1005263434) the burn .pdbs are found in the `WixToolset.Burn.xxx.nupkg` and should instead be in the missing .snupkg.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6461
