### ISSUE TITLE
Visual studio 2022 - Build Wix project x86 fails.

### ISSUE THREAD

**Issue by kraftknappen** [wixtoolset/issues#6703]
![image](https://user-images.githubusercontent.com/97203178/149198591-f015b19f-d943-4d85-ae38-336ac4ea6ce0.png)

`<Product Id="*" Name="XXXXXXXXXXXX" Language="1033" Version="1.0.0.0" Manufacturer="XXXXXXXXX" UpgradeCode="2f16475a-acef-48a0-95ca-a46fb0a38650">
		<Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine"  Platform="x86" />`

After this, Visual Studio 2022 crashes.

Visual Studio: Version 17.1.0 Preview 2.0

**Comment by robmen** [comment]
Almost certainly a duplicate of #6636.

If not, please add a link to a GitHub repo with your .sln and projects that reproduce the problem.
