### ISSUE TITLE
WixNetFxExtension not detecting/bundling files in \redist folder

### ISSUE THREAD

**Issue by Paddy-GitHub** [wixtoolset/issues#6706]
### My System
> Wix 3.11.2.4516
> Visual Studio 2017 15.9.43
> WiX Toolset Visual Studio Extension version: 1.0.0.18
> .NET version: 4.5.2
> Windows version: Windows 10 Pro 21H2-19044.1466

### The aim
I'm checking if .NET 4.5.2 is installed in my bootstrapper using `WixNetFxExtension`, if .NET isn't found I want to run a bundled .NET installer exe (not an online downloaded one - the target PC doesn't have internet connectivity).

### Code

    <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
      xmlns:util="http://schemas.microsoft.com/wix/UtilExtension"
      xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"
      xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension">
    
      <Bundle>
        <Chain>
          
          <PackageGroupRef Id="NetFx452Redist" />

My project contains the required exe in a \redist folder:

![image](https://user-images.githubusercontent.com/13437312/150229365-44fc31db-baf5-4492-8566-7f719b96b9f4.png)

### The Problem
Building the project does not result in the `NDP452-*.exe` being bundled into the output exe.

### Possible Cause...
Looking at the source code of WixNetFxExtension (https://github.com/wixtoolset/wix3/blob/develop/src/ext/NetFxExtension/wixlib/NetFx452.wxs) the `<ExePackage>` element is configured to look in a `redist` folder (`<WixVariable Id="NetFx452RedistPackageDirectory" Value="redist\" Overridable="yes" />`)

But the `<ExePackage>` element is configured to `Compressed="no"`. So from my understanding it will never embed the `redist\NDP-*.exe` into the output.

```
<PackageGroup Id="NetFx452Redist">
      <ExePackage
          InstallCommand="/q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx452FullLog].html&quot;"
          RepairCommand="/q /norestart /repair /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx452FullLog].html&quot;"
          UninstallCommand="/uninstall /q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx452FullLog].html&quot;"
          PerMachine="yes"
          DetectCondition="!(wix.NetFx452RedistDetectCondition)"
          InstallCondition="!(wix.NetFx452RedistInstallCondition)"
          Id="NetFx452Redist"
          Vital="yes"
          Permanent="yes"
          Protocol="netfx4"
          DownloadUrl="$(var.NetFx452RedistLink)"
          LogPathVariable="NetFx452FullLog"
   Compressed="no"
          Name="!(wix.NetFx452RedistPackageDirectory)NDP452-KB2901907-x86-x64-AllOS-ENU.exe">
        <RemotePayload 
          CertificatePublicKey="B78FE7F6917E1BC5F4A9C77BA3D555A0E807B9E0"
          CertificateThumbprint="67B1757863E3EFF760EA9EBB02849AF07D3A8080"
          Description="Microsoft .NET Framework 4.5.2 Setup"
          Hash="89F86F9522DC7A8A965FACCE839ABB790A285A63"
          ProductName="Microsoft .NET Framework 4.5.2"
          Size="69999448"
          Version="4.5.51209.34209" />
      </ExePackage>
    </PackageGroup>
```

### Workaround
Setting `Compressed="yes"`, and removing the `DownloadUrl` and `RemotePayload` (as required by the compiler), triggers the embedding of the desired `NDP452-*.exe`

```
    <PackageGroup Id="Netfx452Full_localWorkaround">
      <ExePackage
          InstallCommand="/q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx452FullLog].html&quot;"
          RepairCommand="/q /norestart /repair /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx452FullLog].html&quot;"
          UninstallCommand="/uninstall /q /norestart /ChainingPackage &quot;[WixBundleName]&quot; /log &quot;[NetFx452FullLog].html&quot;"
          PerMachine="yes"
          DetectCondition="!(wix.NetFx452RedistDetectCondition)"
          InstallCondition="!(wix.NetFx452RedistInstallCondition)"
          Id="Netfx452Full"
          Vital="yes"
          Permanent="yes"
          Protocol="netfx4"
          LogPathVariable="NetFx452FullLog"
          Compressed="yes"
          Name="!(wix.NetFx452RedistPackageDirectory)NDP452-KB2901907-x86-x64-AllOS-ENU.exe">
      </ExePackage>
    </PackageGroup>
```

### (Possible) Solution
Alongside the two existing `<PackageGroups>`  in `https://github.com/wixtoolset/wix3/blob/develop/src/ext/NetFxExtension/wixlib/NetFx452.wxs`, extra groups need to be configured to support `Compressed="yes"`

> (Be as specific as you can and err on the side of providing too much information.)

**Comment by barnson** [comment]
Adding compressed variants would include them in WixNetFxExtension, so that's probably not going to happen. Payload groups can do that. https://github.com/wixtoolset/issues/issues/5310 shows a bug with the doc.
