### ISSUE TITLE
WiX VS extension 2019: no context menu for setup projects in Solution explorer

### ISSUE THREAD

**Issue by apoggiali** [wixtoolset/issues#6710]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2 get from Nuget

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Professional 2019 Version 16.11.9

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.18

* Which version of .NET are you building with?

> .NET 5.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 version 20H2

* Describe the problem and the steps to reproduce it.

> Create a new solution, add a c# console app project, add a Wix setup project. On Solution Explorer Right click on the setup project. No "Wix editors" submenu can be found. Also the "Wix editors" icons are not shown in the Solution explorer toolbar.

* Describe the behavior you expected and how it differed from the actual behavior.

> The "Wix editors" submenu should be present: no way to work except for XML files manual editing.

**Comment by robmen** [comment]
I'm afraid you have us confused with something else. The WiX Toolset does not provide Visual Studio integration with "editors", just project system + build and using the XML editor.
