### ISSUE TITLE
WiX 3 Another version of this product is alraedy installed (Win10 vs Win11)

### ISSUE THREAD

**Issue by wstaelens** [wixtoolset/issues#6717]
## Triage

?

## Discussions and support

When we build our setup using VS2019 on Windows 11 and try to install it we get: "another version of this product is already installed. Installation of this version cannot continue. To configure or remove the existing version of this product, use Add/Remove Programs on the Control Panel."

When we build the same solution on Windows 11 using VS2019 the msi upgrade works just fine.

Is there anything different in Windows 11 vs. Windows 10?

The old version of the application is installed and normally we just overinstall the new version. When building the msi on Windows 10 this works and has worked for years. If the build comes from Windows 11, we can't overinstall the new version, we first have to remove the previous version, however it is an upgrade...

It feels like it doesn't see the upgrade code when built in Windows 11.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> wix toolset 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Professional 2019 v 16.11.9 - 

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Wix Toolset Visual Studio 2019 exention 1.0.0.18

* Which version of .NET are you building with?

> .NET Framework  4.8.04084

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 version 21H1 (19044.1466) <-- installing upgrade via msi works

> Windows 11 version 21H2 (22000.434) <-- installing upgrade via msi doesn't work

* Describe the problem and the steps to reproduce it.

> Building an upgrade in Windows 10 works fine. user installs the msi upgrade, over the existing version. Works fine.

> Building an upgrade in Windows 11 (same solution, same dev environment), the overinstallation doesn't work. User gets a message that another version of this product is already installed.

* Describe the behavior you expected and how it differed from the actual behavior.

> Should work as Windows 10. User should be able to install an msi upgrade of a software, without first uninstalling the previous version. When the build is made with Windows 11, this is not possible.
> We have no idea why. Feels like a wix bug...

**Comment by barnson** [comment]
WiX only builds packages; Windows Installer is responsible for running them. So unless your packages are being built incorrectly on Windows 11, it's not a WiX bug.

**Comment by wstaelens** [comment]
How do/would I know if the "packages are being built incorrectly" on Windows 11?

As it is clearly an issue that occurs in Windows 11 and same not in Windows 10 when builds are being made.
Running a msi package built on Windows 11 on a Windows 10 or 11 pc gives the same issue.

Running an msi package built in Windows 10 on a Windows 10 or 11 pc works fine.

This ticket is closed as external, are you that sure?

**Comment by robmen** [comment]
We don't use GitHub for support questions. [Please pick from one of the support options presented here](https://www.firegiant.com/support-options/).

It is possible through discussion that a specific bug in the WiX Toolset will be uncovered but usually, someone can help you find the error in your .wxs code.

**Comment by wstaelens** [comment]
ok, still think it is a bug and posted here also to see if anyone else has the same issue or not.

Build is made on Windows 11 pc vs2022.  installing this build on Windows 10 gives me "Another version of this product is already installed."

When the build is made on Windows 10 pc vs2022 and installing this build on Windows 10 works.
