### ISSUE TITLE
Error 217 Doc Page has dead URLs

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#6718]
## Bugs

In WiX 3.14 builds there is a problem with validation that displays an error message referring the user to http://wixtoolset.org/documentation/error217/ for more information.   The respource links on this page are dead.

Heath:  access denied.   Google search suggested replacement https://devblogs.microsoft.com/setup/windows-installer-errors-2738-and-2739-with-script-custom-actions/

Aaron: Redirect to blogs home page.  I searched https://docs.microsoft.com/en-us/archive/blogs/astebner/ but it wasn't obvious to me which article this was pointing to.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6449
