### ISSUE TITLE
Wix deployed config files - merging

### ISSUE THREAD

**Issue by greengumby** [wixtoolset/issues#6719]
## Feature requests

Along with our product, configuration files are deployed and changed by the end users. Should the dev team add a new setting to the product it would be great to be able to merge this with the existing configuration files upon upgrading. 

Was thinking along the lines of using some sort of merge tool (like winmerge) and than only notifying the users should there be a conflict.  i.e. The same line/s of config were both changed by the user and modified by the upgrade.

Currently the configuration files are overwritten by the defaults in the installer thus meaning the user is required to make the same edits on each upgrade.

Thanks

**Comment by barnson** [comment]
You can do this today for XML files with `XmlConfig`.

**Comment by barnson** [comment]
WiX doesn't currently have a JSON extension.
