### ISSUE TITLE
Add ability to force uninstall bundle

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6721]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

>  The new logic from https://github.com/wixtoolset/issues/issues/6297 is very likely to expose some bugs that end up making the engine never uninstall the bundle. There should be a way to override that behavior.

* Describe how you're accomplishing the feature today (if possible).

> Manually deleting files and registry cleaners.

* Describe what you'd like the new feature to do.

> Add a new switch that forces the bundle to unregister and remove itself from the cache, probably along with trying to uninstall all of its packages.

**Comment by barnson** [comment]
`-unsafeuninstall`
