### ISSUE TITLE
Consider not setting WixBundleInstalled and WixBundleAction before Detect and Plan, respectively

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6736]
BootstrapperApplications should have to call `Detect` to get `WixBundleInstalled` set, that shouldn't be too controversial.

Not setting `WixBundleAction` until `Plan` will break people, though. It seems to be common for people to use that in a `DetectCondition` or `LaunchCondition` even though that's not a good idea since the BA doesn't have to use the action from the command line. If we keep the current functionality, the BA probably needs to be able to change it before calling Detect.

**Comment by barnson** [comment]
👍 on `WixBundleInstalled`. Likewise for `WixBundleAction`, but can't the engine set it every time detect is called (using current default) and plan (with real action)?

**Comment by rseanhall** [comment]
Today, they are both set two times. The first is during bundle initialization. The second is at the beginning of their respective action (`Detect` for `WixBundleInstalled` and `Plan` for `WixBundleAction`). I am proposing to stop setting them during bundle initialization.

**Comment by barnson** [comment]
That's fine with me. But we'd need to set `WixBundleAction` during `Detect` too to avoid breakage (even though its use is suspect).

**Comment by rseanhall** [comment]
I don't think changing `WixBundleAction` that way is worth it, considering that BAs might not call Detect before evaluating LaunchConditions.

**Comment by barnson** [comment]
Ah, hadn't considered launch conditions. Need a solution for that.

**Comment by barnson** [comment]
Add `WixBundleCommandLineAction`.
