### ISSUE TITLE
candle.exe does not compile version greater than 255.255.65535

### ISSUE THREAD

**Issue by frankenpfalzer** [wixtoolset/issues#6737]
* Which version of WiX are you building with?

3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

 only commadline toolset

* Describe the problem and the steps to reproduce it.

We want to switch from "classic" semver to a more "modern" style of version numbers for our product. The new style schould be as following:
`2022.1.1`

Setting this value to the `Version`-Porperty in the `Product`-Block leads to following error message:

```XML
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
    <Product Id="..."
            Name="..."
             Language="1031"
             Codepage="1252"
             Version="2022.1.1"
             Manufacturer="..."
             UpgradeCode="...">
```

`...candle.exe'' finished with non-zero exit value 242` 

After some try and error we found out, that the highest compileable version number is `255.255.65535`. The 4th digit - if it is set - seems to be ignored.

* Describe the behavior you expected and how it differed from the actual behavior.

We expected `2022.1.1` as value of the version property should compile.

**Comment by barnson** [comment]
The error message is explicit. It's an MSI requirement for `ProductVersion`.

**Comment by frankenpfalzer** [comment]
Hi @barnson.
Many thanks for your quick response.
Just to clarify. MSI will not allow version numbers like `2022.1.1`?
I'm a little puzzled because https://docs.microsoft.com/en-us/windows/win32/msi/version says `65535.65535.65535.65535` is the highest possible version.
Maybe i am looking at the wrong part of docu. So please be so kind an provide me the right source...

Kind regards

**Comment by robmen** [comment]
@frankenpfalzer [ProductVersion is different](https://docs.microsoft.com/en-us/windows/win32/msi/productversion). Why? Ask Microsoft.

**Comment by frankenpfalzer** [comment]
@robmen thank you for pointing out the correct part of documentation.

BTW: I really appreciate your work on wixtoolset. Many thanks for that.
