### ISSUE TITLE
Missing installer location

### ISSUE THREAD

**Issue by lovettchris** [wixtoolset/issues#6741]
## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> VS 2019 Enterprise version 16.11.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> WiX Toolset Visual Studio Extension version 1.0.0.4

* Which version of .NET are you building with?

> .NET Framework 4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 21H2, build 22000.556

* Describe the problem and the steps to reproduce it.

> See https://github.com/microsoft/XmlNotepad/issues/102#issuecomment-1065982006 but the core issue is that the Location field is blank in this dialog:

![image](https://user-images.githubusercontent.com/18707114/158281308-955a114a-db00-4e51-8ce8-6065d3a9421d.png)

* Describe the behavior you expected and how it differed from the actual behavior.

> Would be nice if it showed where XML Notepad was installed.

**Comment by barnson** [comment]
https://docs.microsoft.com/en-us/windows/win32/msi/arpinstalllocation

**Comment by lovettchris** [comment]
Thanks for the MSI link, can you also show me the link to the wix documentation that shows me how to set such a property?

**Comment by lovettchris** [comment]
Never mind, I found it on stackoverflow:
```xml
<SetProperty Id="ARPINSTALLLOCATION" Value="[APPINSTALLROOTDIR]" After="CostFinalize" />
```

![image](https://user-images.githubusercontent.com/18707114/158285282-ef9ebfea-59a4-4035-ad6f-3d2f80ad4da7.png)
