### ISSUE TITLE
Remote payloads should not allow Hash information to be specified with Certificate information

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6745]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> It's counterintuitive for Hash and Size to be required for Authenticode verified payloads when they'll never be used. It's also confusing to users which validation will actually be performed.

* Describe how you're accomplishing the feature today (if possible).

> N/A

* Describe what you'd like the new feature to do.

> Compiler error

**Comment by robmen** [comment]
Currently, `Hash` is required to default the `CacheId` and why doesn't Burn use the `Size` if downloading the remote payload?

**Comment by barnson** [comment]
With certificate verification, `Hash` is forbidden, `Size` is optional, and `CacheId` is required. With hash verification, `Hash` is required, `Size` is optional, and `CacheId` is optional.

**Comment by rseanhall** [comment]
`Size` is required for hash verification. Burn checks both for acquired files.

**Comment by barnson** [comment]
I clearly need to be replaced as triage scribe.

**Comment by rseanhall** [comment]
We agreed at 25:00 (https://youtu.be/eIw02nRXH30?t=1500) that the remote payload subcommand should generate the CacheId as Hash+Certificate for Authenticode verified packages.

If the length of the hash is a concern for using it as the CacheId, then we can truncate it. When used as a source of random data, there is no problem with truncating a hash except for the obvious fact that more characters will have a smaller chance of collision than less characters.

Bob pushed for the CacheId in the NetFx package groups to be replaced with a stable guid for each package to further optimize reuse. We expect the vast majority of people to either use the extension directly or copy the package groups from the source code, and using a guid means the CacheId doesn't change when they release updates to existing versions. The NetFx package groups must be updated as part of this change, whether it's the output of the subcommand or a special CacheId, because it's currently specifying both and that is supposed to be a compiler error.
