### ISSUE TITLE
MsuPackage: `wusa.exe /uninstall /kb:# /quiet` is deprecated

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6749]
Silently uninstalling MSUs was deprecated in Windows 10 1507: https://docs.microsoft.com/en-us/windows/deployment/planning/windows-10-deprecated-features.

> The wusa usage to quietly uninstall an update has been deprecated. The uninstall command with /quiet switch fails with event ID 8 in the Setup event log. Uninstalling updates quietly could be a security risk because malicious software could quietly uninstall an update in the background without user intervention.

The inability to uninstall silently probably means that either MsuPackages should always be permanent, or their planned action should depend on the UI level of the bundle.

**Comment by barnson** [comment]
Yikes

**Comment by robmen** [comment]
Re-opening since there is a burn component to this
