### ISSUE TITLE
Can't open solution contains wix project (Visual Studio 2022 Preview).

### ISSUE THREAD

**Issue by Hominis06** [wixtoolset/issues#6753]
Hello everyone!
With latest Visual Studio update, I can't open a solution containing a .wixproj file. I understand that it may not be in your plans to support preview versions of visual studio, but I'm worried that this problem may migrate to the main build of visual studio [since Microsoft does not consider this a bug](https://developercommunity.visualstudio.com/t/error-opening-existing-solutions-in-vs-1720-previe/1698302).
I look forward to your reply, thanks in advance

* Which version of WiX are you building with?
> v 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?
> Version 17.2.0 Preview 2.1
> Note: wix opened (and built) fine on version preview 1. After updating to preview 2.0 and higher, the solution with the wix project stopped opening.

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> v 1.0.0.18

* Which version of .NET are you building with?
> .NET 4.8 (If it matters. In my case, i can't even open the solution)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
>Windows 10 Pro 21H2 19044.1620
>Or
>Windows 11 Pro 22H2 22581.1
>Choose what you like best 

* Describe the problem and the steps to reproduce it.
> Trying to open a solution results in the following errors:
> These errors occur, if i opened solution from windows explorer (in turn):
>![image](https://user-images.githubusercontent.com/72467784/161117681-29ed7e1c-99ea-44c0-959a-b5d53965b75d.png)
>![image](https://user-images.githubusercontent.com/72467784/161117745-b7942cfb-189b-4736-b254-84d02bd5e08a.png)
> This error occur, if i opened solution from solution explorer of Visual Studio:
>![image](https://user-images.githubusercontent.com/72467784/161118028-d7514fae-f6d9-476b-a519-f448202717b5.png)
>After I clicked OK, the solution can no longer open (solution explorer is empty) while it contains a .wixproj file. If i delete Wix project from .sln file manually, solution opened fine, but that this is a bad way out :/

* Describe the behavior you expected and how it differed from the actual behavior.
>An open source solution that I can build :)

**Comment by rseanhall** [comment]
You should reply to that Microsoft bug that it was closed in error. They should not have closed it when someone said it went away when they downgraded VS.

**Comment by Hominis06** [comment]
@rseanhall omy

**Comment by barnson** [comment]
What happens if you create an empty solution and add a new WiX project from the templates?

**Comment by Hominis06** [comment]
@barnson wix project folder with files is created in the solution folder, but the wix project is not added to the solution. The error is the same as before. After clicking create -> ok(in error window) the prompt window is still open.
![image](https://user-images.githubusercontent.com/72467784/161207933-e75db55c-9b34-464d-adb1-7b85a7bb3b9b.png)

**Comment by FabienF-Alten** [comment]
Hello!
Just passing to say that I have this problem too, and it persisted after a clean Visual Studio reinstall.
Microsoft most likely broke something in 17.2 Preview 2, which shouldn't be yours to fix, but seeing how they half-assed their support on the matter, a fix from your side would definitely be welcome (especially if they consider their bug to be a new feature going forward)

**Comment by FabienF-Alten** [comment]
17.2 Preview 3 -> problem not fixed by Microsoft. They were the one who broke it, but maybe something can be done on the extension side if it's a "simple" cast issue?

**Comment by Hominis06** [comment]
@FabienF-Alten 
> Given their lack on response on their feedback thread, this breaking change seems to be here to stay :/

The original topic of problem on Microsoft's forum is opened now. Let's just wait their reaction.

**Comment by FabienF-Alten** [comment]
> @FabienF-Alten
> 
> > Given their lack on response on their feedback thread, this breaking change seems to be here to stay :/
> 
> The original topic of problem on Microsoft's forum is opened now. Let's just wait their reaction.

Oh ok sorry. I'm not very familiar with how their forum works, I didn't notice that. Thanks for the info

**Comment by robmen** [comment]
This pre-release of Votive should have a change to avoid the issue exposed by Visual Studio 17.2.0: https://github.com/wixtoolset/VisualStudioExtension/releases/tag/v1.0.0.20

**Comment by Hominis06** [comment]
@ericmoreira-vinci I think you need to submit new issue with a detailed description of your case.
I just updated Visual Studio Preview up to latest version (17.3.0 Preview 2.0) and everything works fine for me (I mean solution that caused this issue was submited)
