### ISSUE TITLE
Wix submenu and solution explorer icons are absent in Visual Studio Community 2019

### ISSUE THREAD

**Issue by Martgqc** [wixtoolset/issues#6754]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
3.11.2.4516

* (Visual Studio version, including year and update)
Visual Studio Community 2019, Version 16.11.11

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
Extention 1.0.0.18
![image](https://user-images.githubusercontent.com/102700097/161177596-bfd35283-b566-4c17-9a81-21d64d653493.png)

* Which version of .NET are you building with?
4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Window 7, 64Bits

* Describe the problem and the steps to reproduce it.
The title says it all! Wix submenu and solution explorer icons are absent in Visual Studio Community 2019.
![image](https://user-images.githubusercontent.com/102700097/161177467-137d2c2c-0b2f-4242-b87b-de5d4dc3098c.png)
![image](https://user-images.githubusercontent.com/102700097/161177530-370edfeb-64e9-42b4-91f5-9732daea17c8.png)

* Describe the behavior you expected and how it differed from the actual behavior.
I tried many things like, utpdates, reinstall and repair. Nothing had worked so far.

Thanks!

Martin

**Comment by barnson** [comment]
What additional commands are you looking for?

**Comment by Martgqc** [comment]
I'm looking for these (copied from YouTube):
![image](https://user-images.githubusercontent.com/102700097/161337397-1d192009-467e-4eec-846b-5d7cd7129f17.png)

And this submenu (copied from YouTube also):
![image](https://user-images.githubusercontent.com/102700097/161337661-fc5c6dbd-ad12-4c9f-991e-71b31b695845.png)

Intellicode for WiX isn't working also.

Thanks!

Martin

**Comment by robmen** [comment]
Those editors are part of Votive (the WiX Visual Studio Extension). You're looking for some other product not built by us.

**Comment by Martgqc** [comment]
Oh! I see! As a beginner with WiX I thought it was part of it. I will continue my learnings then!

Thanks again for your time!

Martin
