### ISSUE TITLE
Harvesting non-compressed BundlePackage should probably add payloads

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6757]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> For MsiPackages, wix.exe harvests all of the non-compressed .cabs and files. For BundlePackages, it doesn't add anything other than the .exe even though there are similar concepts with Payloads and Containers. For bundles that don't support downloading their non-compressed payloads, the bundle author would have to manually add each payload for it to work in the parent bundle.

* Describe how you're accomplishing the feature today (if possible).

> Hoping everything is compressed in the bundle or can be downloaded.

* Describe what you'd like the new feature to do.

> Needs to be designed.

**Comment by robmen** [comment]
The `burn remotepayload` command does not support the new `BundlePackage`. But it can gather all of the files in a directory and create `ExePackage` or `MsuPackage` elements plus the yet to be finished "RemotePayload" (see #5601). One option might be to add introspection to the `ExePackage` case to automatically detect an .exe file as a `BundlePackage`.

**Comment by rseanhall** [comment]
This feature is for harvesting based on the contents of the bundle's manifest. I will be implementing remote support for BundlePackage separately from this issue. I believe everything you said is orthogonal to this issue.

**Comment by robmen** [comment]
Ahh, the use of `wix.exe` in the scenario description made me think this included both scenarios. This is about updating the `BurnBackend` or `wix.exe build` path only. Got it.

**Comment by barnson** [comment]
"Harvest"/gather/inspect/hunt all loose files and external packages/payloads and containers. Payloads with a `DownloadUrl` can be optional, based on a (to be named) `PayloadGeneration` enum (all/none/allOfThemUnlessTheyHaveADownloadUrlInWhichCaseIgnoreThem).

**Comment by rseanhall** [comment]
I'm thinking of `all`, `external`, `externalWithoutDownloadUrl`, `none`. I think we were talking about `external` being the default, but if the default is `externalWithoutDownloadUrl` instead then we could rename that one `default`.
