### ISSUE TITLE
Add ability for bundle author to disable repair for MsiPackage or BundlePackage

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6758]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> A common use of BundlePackage will be for redists that generally shouldn't be repaired with the bundle. There have been other requests for controlling whether a MsiPackage gets repaired.

* Describe how you're accomplishing the feature today (if possible).

> Custom BA

* Describe what you'd like the new feature to do.

> Needs to be designed. There was a lot of discussion around a similar feature in https://github.com/wixtoolset/burn/pull/51 and https://www.firegiant.com/blog/2021/7/22/wix-online-meeting-216-highlights/.

**Comment by barnson** [comment]
`RepairCondition`
