### ISSUE TITLE
error PYRO0260 : Product 'xxxxx': Table 'CreateFolder'

### ISSUE THREAD

**Issue by mounikapk** [wixtoolset/issues#6767]
We are introducing a new component in a WiX patch and encountered the below error-

error PYRO0260 : Product 'xxxxx': Table 'CreateFolder' has a new row 'SampleDir/SampleServiceComp' added. This makes the patch not uninstallable.
pyro.exe : error PYRO0261 : This patch is not uninstallable. The 'Patch' element's attribute 'AllowRemoval' should be set to 'no'.

We have always been setting AllowRemoval='yes' in our Patch.wxs for our cumulative patches but never introduced a new feature in a Patch. 

Can we add a new component in a Patch.msp, without setting the AllowRemoval='no'?

 I could hardly find any documentation about the problem. Can you help me with this issue?

**Comment by robmen** [comment]
We don't use GitHub for support questions. [Please pick from one of the support options presented here](https://www.firegiant.com/support-options/).

It is possible through discussion that a specific bug in the WiX Toolset will be uncovered but usually, someone can help you find the error in your .wxs code.

**Comment by mounikapk** [comment]
Ok. I tried the emailing list earlier but i couldn't get any answer. I submitted the same question in stackoverflow. Thanks!
