### ISSUE TITLE
ExePackage ARP Entry

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6772]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> There are popular installer frameworks that create .exe installers. These are often difficult to use in a bundle due to needing to write correct DetectCondition and UninstallArguments attributes. On top of that, .exe installers (including bundles) require source for uninstall which is inconvenient.

* Describe how you're accomplishing the feature today (if possible).

> Not very well.

* Describe what you'd like the new feature to do.

> Provide information about the ARP entry that is created by the .exe installer at build time, so that Burn can use that information to help detect and uninstall the package.

**Comment by barnson** [comment]
Disallowed: `UninstallArguments` and `DetectCondition`. Exact `Version` match.
