### ISSUE TITLE
WixToolset.Data.WixVersion Metadata is wrong when invalid

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6775]
**Encountered at:** https://github.com/wixtoolset/wix4/commit/02e682881979cd87592ee1e8e39b7744b575829c

**Detail:**

According to the [spec](https://wixtoolset.org/development/wips/6210-burn-engine-semantic-versioning/) when the WixVersion is invalid, the Metadata field is supposed to be set to the rest of the string starting from the point where it was recognized as invalid. This would have been caught if all of the native tests had been ported to managed as well.

**Comment by barnson** [comment]
`WixVersion.Parse`
