### ISSUE TITLE
MSI version rules should be applied at compile time

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6777]
**Encountered at:** https://github.com/wixtoolset/wix4/commit/02e682881979cd87592ee1e8e39b7744b575829c

**Detail:**

When compiling, it is already known whether an attribute value should be an MSI version or Wix version. The stricter rules for MSI versions should be applied at compile time. This prevents the bad user experience where wix.exe spent a lot of time generating the MSI just to see it fail at the end, especially when the offending version came from a .wixlib that was compiled separately from the current project.

**Comment by barnson** [comment]
We want as much data as possible to flow to the backend, where backend-specific rules can be applied.
