### ISSUE TITLE
Allow MSI version of 1.2.3.abc or 1.2.3.9876543210

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6778]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> The MSI product version's 4th field is ignored by Windows Installer. Some people like to put very letters or very large build numbers there.

* Describe how you're accomplishing the feature today (if possible).

> Not using WiX to build the MSI.

* Describe what you'd like the new feature to do.

> Loosen the verification of MSI product version to allow 1.2.3.abc or 1.2.3.9876543210.

**Comment by barnson** [comment]
Burn needs to understand any MSI version. New issue to discuss flowing 1.2.3.abc throughout the system.

**Comment by rseanhall** [comment]
As Bob said, we decided against this because Burn would not understand these versions. Although we theoretically could have  changed the WixVersion spec in order to allow this, I was against it. The current spec has very little chance of assigning intent where the version's author didn't intend since Windows's four part version scheme and SemVer merged so nicely. WixVersion (and SemVer) have two pivot points - the prerelease separator (`-`) and the metadata separator (`+`) - along with the `.` separating the version parts. Allowing the third dot to be ambiguous about being a version part separator, a prerelease separator, or a metadata separator would not only complicate the parsing but also have a significant chance of getting the version author's intent wrong.

For example, it sounded like we might have treated `1.2.3.9876543210` as equivalent to `1.2.3-9876543210`. This is almost certainly wrong because `9876543210` is most likely a build number and not a prerelease version. Treating `1.2.3.abc` as equivalent to `1.2.3-abc` might be correct, but for `1.2.3.a1b2c3d4` that's probably a git hash that should be equivalent to `1.2.3+a1b2c3d4`. The `1.2.3.{whatever}` scenario is probably where the WixVersion spec has the highest chance of getting it wrong and adding support for this in the toolset wouldn't make it any better.
