### ISSUE TITLE
Installation of VS 2022 Extension corrupts VS

### ISSUE THREAD

**Issue by beinhaerter** [wixtoolset/issues#6780]
* Which version of WiX are you building with?

3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

VS 2022 Professional, 17.2, German
running as regular user

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

3.11.2.4516

* Which version of .NET are you building with?

?

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 10 Enterprise 21H1, German

* Describe the problem and the steps to reproduce it.

Extensions/Manage Extensions -> Select Wix extension for installation -> Close VS -> Windows asks for admin credentials -> installer runs -> start VS again ->
VS dialogs open
![image](https://user-images.githubusercontent.com/34543625/168060005-6622b074-a71f-4775-b665-eda711841b2f.png)
![image](https://user-images.githubusercontent.com/34543625/168060144-844d13ae-e2fd-4f16-97f4-2772526e7213.png)
![image](https://user-images.githubusercontent.com/34543625/168060349-37f4a7a8-64bc-4948-a765-7fcddafeca09.png)

When VS opens, then there are no installed extensions listed under Extensions/Manage Extensions.

VS repair install does not help. VS uninstall + reinstall helps.

* Describe the behavior you expected and how it differed from the actual behavior.

I expect no error message and that the installed extensions are still visible and working.

* Additional info

The extensions are displayed when running VS as an admin. They are not displayed when running VS as a regular user.
[ActivityLog.zip](https://github.com/wixtoolset/issues/files/8678564/ActivityLog.zip)

**Comment by beinhaerter** [comment]
Works after running

```
devenv.exe /ResetSettings
devenv.exe /ResetUserData
devenv.exe /SafeMode
```

**Comment by MehdiKacim** [comment]
> 

Hi, this issue not working for me...

**Comment by MehdiKacim** [comment]
> > 
> 
> Hi, this issue not working for me...

In the end it worked.
You just have to be careful: empty the Windows temporary folder beforehand and between each command that launches VS

**Comment by robmen** [comment]
Visual Studio owns the VSIX installation experience. If this keeps reproducing for you, you might consider opening an issue with them at https://developercommunity.visualstudio.com . It doesn't seem like you should have to reset Visual Studio regularly.

**Comment by beinhaerter** [comment]
https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

**Comment by beinhaerter** [comment]
Can you please reopen? MS Feedback is

>Thank you for providing this information. I did reproduce this issue and got same result as you.
>I also tested other extensions, such as Microsoft Visual Studio Installer Projects 2022, AWS Toolkit for Visual Studio 2022, Project Explorer 2022. They all work well. So I do not think this is a VSIX installer issue.
>The Wix Toolset Visual Studio 2022 Extension is an external extension. I recommend that you contact the extension owner to report this issue. Thanks!
>https://marketplace.visualstudio.com/items?itemName=WixToolset.WixToolsetVisualStudio2022Extension
>To report bugs or feature requests please go to http://wixtoolset.org/issues/.

**Comment by robmen** [comment]
There seems to be an installation issue in VS17.2 as we haven't changed Votive so the failed installation behavior is new in this release of Visual Studio. Here are other issues that are also sometimes seeing installation failures in VS 17.2:

1. https://github.com/wixtoolset/issues/issues/6786
2. https://github.com/wixtoolset/issues/issues/6795
3. https://github.com/wixtoolset/issues/issues/6797

We need the Visual Studio VSIX installer team to explain what changed (or fix their bug) via: https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

**Comment by barnson** [comment]
Tracking this class of bug at https://github.com/wixtoolset/issues/issues/6803.
