### ISSUE TITLE
WiX Light can't find a downloaded github actions artifact

### ISSUE THREAD

**Issue by adlud** [wixtoolset/issues#6782]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> Using msbuild via github actions: Microsoft Build Engine version 16.11.2+f32259642 for .NET Framework

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n.a.

* Which version of .NET are you building with?

> n.a.

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n.a.

* Describe the problem and the steps to reproduce it.

> In one step of a github actions job, I download an artifact that was uploaded in a previous job. I see these messages in the workflow output:

- Artifact Executable_file was downloaded to D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\PCMPLUS.exe
- Artifact download has finished successfully

In a subsequent step of the same job, I run msbuild on a *.wixproj file. Candle runs without error, but Light fails with this error:

- error LGHT0103: The system cannot find the file 'D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\PCMPLUS.exe'.

The paths match, so the file should be found.

Here is some more info, in case it helps.

The relevant sections of the workflow .yml file:

`- name: Download executable file`
`  uses: actions/download-artifact@v3`
`  with:`
`    name: Executable_file`
`    path: ./PCMateSetup/PCMPLUS.exe`

`- name: Build PCMateSetup`
`  run: |`
`    msbuild /m /p:MajorVer="${{env.majVer}}" /p:MinorVer="${{env.minVer}}" /p:BuildVer="${{env.bldVer}}" /p:ProtoVer="0" /p:GithubBld="true" /p:Configuration=${{env.BUILD_CONFIGURATION}} /v:n ${{env.SOLUTION_FILE_PATH}}\PCMateSetup\PCMateSetup.wixproj`

From the .wxs files:

`<File Id="file.instDir.PCMPLUSExecutable" Vital="yes" Source="$(var.ProjectDir)PCMPLUS.exe" KeyPath="yes" />`

And also from the output messages:

- ProjectDir: D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\

Let me know if any more info is needed. Thanks for taking a look.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect Light to be able to find the file and complete successfully.

**Comment by robmen** [comment]
We don't use GitHub for support questions. [Please pick from one of the support options presented here](https://www.firegiant.com/support-options/).

It is possible through discussion that a specific bug in the WiX Toolset will be uncovered but usually, someone can help you find the error in your .wxs code.

**Comment by adlud** [comment]
@robmen Ok, I will ask this on the wix-users mailing list. Had already tried stackoverflow, but got no useful response. I think resolution may require some attention from the WiX devs, based on this output from the workflow:

Artifact Executable_file was downloaded to D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\PCMPLUS.exe

error LGHT0103: The system cannot find the file 'D:\a\pcm_pcmplatinum_u\pcm_pcmplatinum_u\PCMateSetup\PCMPLUS.exe'.
