### ISSUE TITLE
Wix toolset visual studio extension not getting installed with Visual studio community edition 

### ISSUE THREAD

**Issue by Sandeep2000gupta** [wixtoolset/issues#6786]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows 10, Visual Studio 2022 community edition 17.15 version, Wix Toolset Visual Studio 2022 Extension version 1.0.0.18, .Net version 4.8.04161

> When we try to install wix toolset extension it fails to install and gives error. The install log is as below
[dd_VSIXInstaller_20220524152455_6a7c.log](https://github.com/wixtoolset/issues/files/8768175/dd_VSIXInstaller_20220524152455_6a7c.log)

> (Be as specific as you can and err on the side of providing too much information.)

**Comment by robmen** [comment]
This log message:

```
24-05-2022 15:25:19 - Certificate is invalid: Votive2022.vsix
```

Almost always means your computer's certificate cache is not up to date with the latest root certificates. Windows Update should update the cache and if you are disconnected there is a way to update your certificate cache manually (search the Microsoft documentation sites for details).

**Comment by Sandeep2000gupta** [comment]
Certificate is invalid due to validity time expiry which expired 7th april 2022On May 25, 2022 11:03 AM, Rob Mensching ***@***.***> wrote:
This log message:
24-05-2022 15:25:19 - Certificate is invalid: Votive2022.vsix

Almost always means your computer's certificate cache is not up to date with the latest root certificates. Windows Update should update the cache and if you are disconnected there is a way to update your certificate cache manually (search the Microsoft documentation sites for details).

**Comment by robmen** [comment]
True but the package should be timestamped to indicate that it was signed when the certificate was valid. Interestingly, from your log file there is the line:

```
24-05-2022 15:24:56 - Signature Details...
24-05-2022 15:24:56 - 	Extension is signed with an invalid timestamp.
```

When I install the exact same package, you can see it is marked valid:

```
5/24/2022 10:54:20 PM - -------------------------------------------
5/24/2022 10:54:20 PM - Microsoft VSIX Installer
5/24/2022 10:54:20 PM - -------------------------------------------
5/24/2022 10:54:20 PM - Initializing Install...
5/24/2022 10:54:20 PM - Extension Details...
5/24/2022 10:54:20 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev17
5/24/2022 10:54:20 PM - 	Name               : Wix Toolset Visual Studio 2022 Extension
5/24/2022 10:54:20 PM - 	Author             : WiX Toolset
5/24/2022 10:54:20 PM - 	Version            : 1.0.0.18
5/24/2022 10:54:20 PM - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
5/24/2022 10:54:20 PM - 	Locale             : en-US
5/24/2022 10:54:20 PM - 	MoreInfoURL        : http://wixtoolset.org/
5/24/2022 10:54:20 PM - 	InstalledByMSI     : False
5/24/2022 10:54:20 PM - 	SupportedFrameworkVersionRange : [4.5,)
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	SignatureState     : ValidSignature
5/24/2022 10:54:20 PM - 	SignedBy           : WiX Toolset (.NET Foundation)
5/24/2022 10:54:20 PM - 	Certificate Info   : 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		[Subject]       : CN=WiX Toolset (.NET Foundation), O=WiX Toolset (.NET Foundation), L=Redmond, S=wa, C=US, SERIALNUMBER=603 389 068
5/24/2022 10:54:20 PM - 		[Issuer]        : CN=.NET Foundation Projects Code Signing CA, O=.NET Foundation, C=US
5/24/2022 10:54:20 PM - 		[Serial Number] : 0D5EF90303C2280377DFE04D74E20861
5/24/2022 10:54:20 PM - 		[Not Before]    : 4/2/2019 5:00:00 PM
5/24/2022 10:54:20 PM - 		[Not After]     : 4/7/2022 5:00:00 AM
5/24/2022 10:54:20 PM - 		[Thumbprint]    : C95FC39334E667F3DD3D82AF382E05719B88F7C1
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	Supported Products : 
5/24/2022 10:54:20 PM - 		Microsoft.VisualStudio.Community
5/24/2022 10:54:20 PM - 			Version : [17.0,18.0)
5/24/2022 10:54:20 PM - 			ProductArchitecture : amd64
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	References         : 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas3
5/24/2022 10:54:20 PM - 		Name         : WiX Toolset v3 Schemas for Visual Studio
5/24/2022 10:54:20 PM - 		Version      : 
5/24/2022 10:54:20 PM - 		MoreInfoURL  : 
5/24/2022 10:54:20 PM - 		Nested       : Yes
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas4
5/24/2022 10:54:20 PM - 		Name         : WiX Toolset v4 Schemas for Visual Studio
5/24/2022 10:54:20 PM - 		Version      : 
5/24/2022 10:54:20 PM - 		MoreInfoURL  : 
5/24/2022 10:54:20 PM - 		Nested       : Yes
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	Prerequisites      : 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/24/2022 10:54:20 PM - 		Name         : Visual Studio core editor
5/24/2022 10:54:20 PM - 		Version      : [17.0,18.0)
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - Signature Details...
5/24/2022 10:54:20 PM - 	Extension is signed with a valid signature.
5/24/2022 10:54:20 PM - 
```

It isn't clear why the package validates on my computer but not yours. Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll want to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

You might also try the next release of Votive here: https://github.com/wixtoolset/VisualStudioExtension/releases/tag/v1.0.0.20

That was signed with a newer certificate and may avoid the timestamp problems completely.

**Comment by Sandeep2000gupta** [comment]
Many thanks for looking into the issue. I will try new extension from link you shared and see if that resolves issue
thx
Sandeep
    On Wednesday, 25 May, 2022, 11:39:13 am IST, Rob Mensching ***@***.***> wrote:  
 
 


True but the package should be timestamped to indicate that it was signed when the certificate was valid. Interestingly, from your log file there is the line:
24-05-2022 15:24:56 - Signature Details...
24-05-2022 15:24:56 - 	Extension is signed with an invalid timestamp.

When I install the exact same package, you can see it is marked valid:
5/24/2022 10:54:20 PM - -------------------------------------------
5/24/2022 10:54:20 PM - Microsoft VSIX Installer
5/24/2022 10:54:20 PM - -------------------------------------------
5/24/2022 10:54:20 PM - Initializing Install...
5/24/2022 10:54:20 PM - Extension Details...
5/24/2022 10:54:20 PM - 	Identifier         : WixToolset.VisualStudioExtension.Dev17
5/24/2022 10:54:20 PM - 	Name               : Wix Toolset Visual Studio 2022 Extension
5/24/2022 10:54:20 PM - 	Author             : WiX Toolset
5/24/2022 10:54:20 PM - 	Version            : 1.0.0.18
5/24/2022 10:54:20 PM - 	Description        : Visual Studio integration for the WiX Toolset - the most powerful set of tools available to create your Windows installation experience.
5/24/2022 10:54:20 PM - 	Locale             : en-US
5/24/2022 10:54:20 PM - 	MoreInfoURL        : http://wixtoolset.org/
5/24/2022 10:54:20 PM - 	InstalledByMSI     : False
5/24/2022 10:54:20 PM - 	SupportedFrameworkVersionRange : [4.5,)
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	SignatureState     : ValidSignature
5/24/2022 10:54:20 PM - 	SignedBy           : WiX Toolset (.NET Foundation)
5/24/2022 10:54:20 PM - 	Certificate Info   : 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		[Subject]       : CN=WiX Toolset (.NET Foundation), O=WiX Toolset (.NET Foundation), L=Redmond, S=wa, C=US, SERIALNUMBER=603 389 068
5/24/2022 10:54:20 PM - 		[Issuer]        : CN=.NET Foundation Projects Code Signing CA, O=.NET Foundation, C=US
5/24/2022 10:54:20 PM - 		[Serial Number] : 0D5EF90303C2280377DFE04D74E20861
5/24/2022 10:54:20 PM - 		[Not Before]    : 4/2/2019 5:00:00 PM
5/24/2022 10:54:20 PM - 		[Not After]     : 4/7/2022 5:00:00 AM
5/24/2022 10:54:20 PM - 		[Thumbprint]    : C95FC39334E667F3DD3D82AF382E05719B88F7C1
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	Supported Products : 
5/24/2022 10:54:20 PM - 		Microsoft.VisualStudio.Community
5/24/2022 10:54:20 PM - 			Version : [17.0,18.0)
5/24/2022 10:54:20 PM - 			ProductArchitecture : amd64
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	References         : 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas3
5/24/2022 10:54:20 PM - 		Name         : WiX Toolset v3 Schemas for Visual Studio
5/24/2022 10:54:20 PM - 		Version      : 
5/24/2022 10:54:20 PM - 		MoreInfoURL  : 
5/24/2022 10:54:20 PM - 		Nested       : Yes
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		Identifier   : WixToolset.VisualStudioExtension.Schemas4
5/24/2022 10:54:20 PM - 		Name         : WiX Toolset v4 Schemas for Visual Studio
5/24/2022 10:54:20 PM - 		Version      : 
5/24/2022 10:54:20 PM - 		MoreInfoURL  : 
5/24/2022 10:54:20 PM - 		Nested       : Yes
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - 	Prerequisites      : 
5/24/2022 10:54:20 PM - 		-------------------------------------------------------
5/24/2022 10:54:20 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/24/2022 10:54:20 PM - 		Name         : Visual Studio core editor
5/24/2022 10:54:20 PM - 		Version      : [17.0,18.0)
5/24/2022 10:54:20 PM - 
5/24/2022 10:54:20 PM - Signature Details...
5/24/2022 10:54:20 PM - 	Extension is signed with a valid signature.
5/24/2022 10:54:20 PM - 

It isn't clear why the package validates on my computer but not yours. Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll want to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com

You might also try the next release of Votive here: https://github.com/wixtoolset/VisualStudioExtension/releases/tag/v1.0.0.20

That was signed with a newer certificate and may avoid the timestamp problems completely.

**Comment by objetitos** [comment]
I have the same issue.
WiX toolset 3.11.2 (latest)
Visual Studio 2022 Enterprise edition Versión 17.2.1 (latest)
Both at home (Windows 11 Pro 21H2 with all updates) and work (Windows 10 Pro 21H2 with all upgrades)

**Comment by robmen** [comment]
@objetitos please attach your log file to validate that you do have the same issue. After that, can you also try the latest Votive v1.0.0.20 release and see if that resolves the issue?  I have a hypothesis that Visual Studio's VSIX installer has a problem with timestamp signed `.vsix`s (possibly due to datetime evaluation in different locales).

**Comment by objetitos** [comment]
Hi @robmen.
I will attach the log file.
I just downloaded the latest release and tried, still can't see the extension installed. Don't have any hangs.
My locale at work is US, and at home is Argentina.  Not sure if that means something.
Also, I looked a few minutes ago into the VS installer's individual component's tab and right at the end I found checkboxes for Wix???  never knew they were there...

**Comment by objetitos** [comment]
Here is the install log from my workplace desktop:

[ActivityLog.Setup.zip](https://github.com/wixtoolset/issues/files/8780825/ActivityLog.Setup.zip)

**Comment by robmen** [comment]
@objetitos that's the activity log, not the VSIX install log. You said you had the same issue as @Sandeep2000gupta? Did you look in the failed VSIX log and see that the same error message `Certificate is invalid: Votive2022.vsix` was reported in your log file?

**Comment by miguelitop** [comment]
@robmen  
No, the problem is not with the certs.  Sorry.  My having the same issue related to the issue description, not the specific problem referred to in the comments.
The certificate for the vsix is ok.

Here I add the latest log.
[dd_VSIXInstaller_20220526152127_3e5c.log](https://github.com/wixtoolset/issues/files/8781322/dd_VSIXInstaller_20220526152127_3e5c.log)

**Comment by robmen** [comment]
@miguelitop the error in the log file doesn't have anything to do with the WiX Toolset:
```
05/26/2022 15:21:29 - Unable to load extension at: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\CHROMEDEBUGADAPTER\. Exception text: Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. ---> System.InvalidOperationException: There is an error in XML document (12, 5). ---> System.Xml.Schema.XmlSchemaValidationException: The element 'Identifier' in namespace 'http://schemas.microsoft.com/developer/vsx-schema/2010' has incomplete content. List of possible elements expected: 'SupportedProducts' in namespace 'http://schemas.microsoft.com/developer/vsx-schema/2010'.
```

**Comment by miguelitop** [comment]
Well, I have no idea how but now I can see the templates for a new Wix project.  
No my issue is it says my old projects are not compatible when I try to open the solution with vs 2022.

**Comment by miguelitop** [comment]
Since my projects are pretty standard, I just manually edited them from version 3.10 to 3.11 and from schema 2.0 to 3.0 and that did the trick.  Fully loaded and recompiled on 2022. Thanks!

As per why the templates didn´t appear with the several attempts to install/uninstall I did yesterday and today (and believe me, they were not there... I actually browsed manually all the whole lot of templates to check...), sorry for not being more helpful.  Only thing I did was to reboot the computer...
I can tell you I found a couple folders with the manifests but without binaries or folders. I got two or three different folders in Extensions (whish I had saved their names...) but the correct 43fptbix.b5r folder was not there until this last attempt. (I could read in the activity log this folder name, so I did looked it up there to no avail).
This is on my workplace (USA) machine.
I´ll let you know how it goes on my home´s one...

**Comment by objetitos** [comment]
At home still having the same issue... The install ends saying it was all fine, with the extension installed to the folder :
C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\ENTERPRISE\COMMON7\IDE\EXTENSIONS\43FPTBIX.B5R\
But actually, the folder was created and then erased... and I was left with another folder (also created during install) without anything useful.
![Screenshot 2022-05-26 163425](https://user-images.githubusercontent.com/40406029/170565875-f895a41c-d77a-41e7-95a8-f1a3abd7f4c4.png)
Two more folders created in different steps (I thinks, while dealing with schemas...)
![Screenshot 2022-05-26 163521](https://user-images.githubusercontent.com/40406029/170565983-dfc37d5f-9724-4beb-b978-62d59ce6fa35.png)

In the end, the right folder disappeared:
![Screenshot 2022-05-26 163551](https://user-images.githubusercontent.com/40406029/170566103-78153fb6-3d9b-4003-9c2d-03dff76663af.png)

**Comment by miguelitop** [comment]
There is something random it seems.  Here at my home´s pc, sometimes I end up with the folder shown in the last pic, at other try I ended up with the binaries folder (43pt etc.) but not the other two (resulting in the extension being installed but disabled...).  It seems it was sheer luck I could use the extension and see the templates in my workplace machine.

**Comment by adamhearn** [comment]
Have 2 systems that I cannot install the extension to. Both systems are using the Votive version as linked above (with latest cert).

Provided is the log taken from one system. The log clearly shows the successful install but no such extension (or folder with the extension) exist upon completion

[dd_VSIXInstaller_20220607225257_4db8.log](https://github.com/wixtoolset/issues/files/8858990/dd_VSIXInstaller_20220607225257_4db8.log)

On the other system (which does not have UAC enabled) I saw an error that the package could not be installed without admin rights:
```
07/06/2022 22:29:53 - The extension with ID 'WixToolset.VisualStudioExtension.Dev17' is not installed to Visual Studio Community 2022.
07/06/2022 22:29:53 - Microsoft.VisualStudio.ExtensionManager.RequiresAdminRightsException: You must have administrative privileges to install using the /admin switch.
```
So I ran the installer via the command line from an adminstrative developer tools console. No complain on install but the extension [and its folder] do not exist upon completion.

What information can I gather to help move the investigation further?

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, I'd recommend following up on this issue that seems to track new failures in 17.2: https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

**Comment by barnson** [comment]
Tracking this class of bug at https://github.com/wixtoolset/issues/issues/6803.

**Comment by ritchiecarroll** [comment]
FYI - here is a workaround that worked for me:
https://github.com/wixtoolset/issues/issues/6811#issuecomment-1366922353
