### ISSUE TITLE
RemoveFile fails with Unix domain socket

### ISSUE THREAD

**Issue by JohnMaguire** [wixtoolset/issues#6787]
* Which version of WiX are you building with?

> Wix 3.14.0.5722

* Which version of Visual Studio are you building with (if any)?

> n/a

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> n/a

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 Home 22000.675

* Describe the problem and the steps to reproduce it.

> 1. Create installer which installs and starts a Windows service. On uninstall, ServiceControl is used to stop the service.
> 2. Windows service creates a ".sock" Unix domain socket file.
> 3. Add RemoveFile to a component on uninstall to delete the UDS.
> 4. Receive permissions error, Unix domain socket still exists on disk.
>
> ```
> <Component Id="dnclientSOCKComponent" Guid="6ED5BF96-CA44-4F84-B437-0744860DE59B">
>     <RemoveFile Id="dnclientSOCK" On="uninstall" Name="dnclient.sock"/>
> </Component>
> ```

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected: I expected the Unix domain socket to be deleted.
> Actual: 
>
> ```
> MSI (s) (0C:F0) [15:35:50:694]: Executing op: FeatureUnpublish(Feature=ProductFeature,,Absent=2,Component=BH=%{](U}=WDO4n0*tK=TIX=jswqi@5(HLGxE2)]nSt]KasFWA`bNr99,s+Z*2xNWJPE^9_3B?N_]+M.k-?q0u)qB?e%DmhGBKZQtbR{xOFG39tOD]R*Cr?L)
> MSI (s) (0C:F0) [15:35:50:694]: Note: 1: 1402 2: UNKNOWN\Installer\Features\A74FD35CD0449214AB0923F377CBD1BC 3: 2 
> MSI (s) (0C:F0) [15:35:50:694]: Executing op: ActionStart(Name=StopServices,Description=Stopping services Service: [1],)
> MSI (s) (0C:F0) [15:35:50:694]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
> MSI (s) (0C:F0) [15:35:50:694]: Executing op: ServiceControl(,Name=dnclient,Action=2,,)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: ActionStart(Name=DeleteServices,Description=Deleting services Service: [1],)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: ServiceControl(,Name=dnclient,Action=8,,)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: ActionStart(Name=RemoveFiles,Description=Removing files File: [1], Directory: [9],)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=175000)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: SetTargetFolder(Folder=C:\Program Files\Defined Networking\DNClient\config\)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: SetTargetFolder(Folder=C:\Program Files\Defined Networking\DNClient\)
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: FileRemove(,FileName=dnclient.sock,,)
> MSI (s) (0C:F0) [15:35:51:208]: Verifying accessibility of file: dnclient.sock
> MSI (s) (0C:F0) [15:35:51:208]: Note: 1: 1321 2: C:\Program Files\Defined Networking\DNClient\dnclient.sock 3: 1920 
> MSI (s) (0C:F0) [15:35:51:208]: Note: 1: 2205 2:  3: Error 
> MSI (s) (0C:F0) [15:35:51:208]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1321 
> MSI (s) (0C:F0) [15:35:51:208]: Executing op: ProgressTotal(Total=4,Type=1,ByteEquivalent=175000)
> Info 1321.The Installer has insufficient privileges to modify this file: C:\Program Files\Defined Networking\DNClient\dnclient.sock. System Error 1920.
> ```

**Comment by barnson** [comment]
`RemoveFile` exposes the built-in MSI [`RemoveFile` table](https://docs.microsoft.com/en-us/windows/win32/msi/removefile-table) and [`RemoveFiles` action](https://docs.microsoft.com/en-us/windows/win32/msi/removefiles-action). WiX can't influence those so can't work around an MSI limitation like that. Maybe a custom action could.
