### ISSUE TITLE
sfxca.dll in WiX 3.11.2 Nuget includes signature that is not removed in build process

### ISSUE THREAD

**Issue by GregDomjan** [wixtoolset/issues#6793]
Believe this also relates to the previously resolved issue "Custom action dll is not in valid format" #6089

## Bugs
* Which version of WiX are you building with?

> 3.11.2
.CSProj

``` xml
  <ItemGroup>
    <PackageReference Include="WiX">
      <Version>3.11.2</Version>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
```

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2017 - 15.6.

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> NA

* Which version of .NET are you building with?

> .Net Framework 4.8

* Describe the problem and the steps to reproduce it.

> SignTool Error: SignedCode::Sign returned error: 0x800700C1
 	For more information, please see https://aka.ms/badexeformat
  SignTool Error: An error occurred while attempting to sign: E:\JenkinsSlave\...\x86\Release\caNet.CA.dll

1. Build .net CA with nuget dependency on "Wix" version 3.11.2
1. Use Signtool to attempt to sign

* Describe the behavior you expected and how it differed from the actual behavior.

> Should be able to apply our signature to newly built CA.dll 
Perhaps signature on sfxca.dll in nuget is fine and useful to validate as part of build makesfxca,  but built CA.dll should not have a stale signature after build is complete that blocks signing without running a seperate (custom) action to remove the signature

![image](https://user-images.githubusercontent.com/1988114/171356788-c1718733-e976-440b-8fbb-cd5135e3e6ae.png)
![image](https://user-images.githubusercontent.com/1988114/171356853-8df39cba-4d7f-4219-9c73-53474f6c7a96.png)

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6089 was fixed in WiX v3.14; the bug still exists in WiX v3.11.2.
