### ISSUE TITLE
Unable to install Wix extension into Visual Studio Enterprise 2022 (17.2)

### ISSUE THREAD

**Issue by Nico-1987** [wixtoolset/issues#6795]
On multiple machines in our organization, we are unable to install the Wix extension into Visual Studio 2022.

On my machine, I am running Visual Studio Enterprise 2022 LTSC 17.2 (as detected by the Wix installer)
The log file of the installation has been attached.
![image](https://user-images.githubusercontent.com/93312076/171664921-071368b7-aa02-415d-8336-608fb15c01d0.png)
![image](https://user-images.githubusercontent.com/93312076/171664990-90496d26-73d2-4598-870d-6d61329d3241.png)

I tried various steps
- Install the official version through the Visual Studio Extensions menu
- Download the 1.0.0.20 version, same errors
- Download the 1.0.0.18 version, same errors

Also, I observed that when installing the Schema3 and Schema4 manually, it will only detect it to install it for VS 2019.

The log file of the vortex installer seems to complain about being unable to download another package and that it cannot find a supported product, which it earlier says it did.

[dd_VSIXInstaller_20220602172044_2d08.log](https://github.com/wixtoolset/issues/files/8825275/dd_VSIXInstaller_20220602172044_2d08.log)

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, I'd recommend following up on this issue that seems to track new failures in 17.2: https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

**Comment by barnson** [comment]
Tracking this class of bug at https://github.com/wixtoolset/issues/issues/6803.
