### ISSUE TITLE
Should KB attribute be removed from MsuPackage element and/or WixBundleMsuPackageSymbol

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6801]
**Encountered at:** wixtoolset/wix4@ea7b44ab

**Detail:**

As per #6749 the KB attribute should not be used to remove MSU packages (because Windows no longer supports the silent removal of MSUs). Should we remove the KB attribute (I kinda' like having it for documentation purposes but no other strong argument). Additionally, should we remove the KB field from the `WixBundleMsuPackageSymbol`?

**Comment by barnson** [comment]
👍 💯 🥇

**Comment by barnson** [comment]
> 👍 💯 🥇

See above.
