### ISSUE TITLE
[FIXED in 17.2.5] Votive has problems installing in Visual Studio 17.2.x

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6803]
This is a tracking bug for multiple reports about problems installing Votive in Visual Studio v17.2.x. As Votive v1.0.0.18 came out months before VS v17.2.0, these failures strongly point to a regression in VSIX installation. (Votive v1.0.0.20 contains a fix for a bug introduced in VS 17.2 Previews that was since fixed in VS 17.2 RTM, but is otherwise similar in VSIX structure.)

The issue is currently being investigated by the Visual Studio team: https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

If you have problems installing Votive in Visual Studio 2022, please up-vote that issue so Microsoft is aware of the impact.

**Comment by PiechullaResearch** [comment]
Two out of three of my (after much trial and error) properly running build toolchains containing Wix +Votive + Wax survived an update to VS2022 17.2.4 -- seems to work with Votive 1.0.0.20 and also 1.0.0.18 (worked before -> still works with 17.2.4).
I can't say what was going on, though. Too much chaotic behavior. At least now I have a few cleanly reset machines as a cold reserve for such cases :-)

**Comment by JohnMerryweatherCooper** [comment]
Neither my team lead nor I can successfully get Votive install on VS 2022.  Install through "Manage Extensions", close VS, and get an "Installed Failed" dialog with "Process with an Id of 123204 is not running."

**Comment by robmen** [comment]
The Visual Studio team confirmed the issue was a bug in VS 17.2 and is expected to be fixed in VS v17.2.5 per the linked issue: https://developercommunity.visualstudio.com/t/Installation-of-wixtoolset-extension-cor/10057006

**Comment by JohnMerryweatherCooper** [comment]
After updating to VS 2022 v17.2.5, installation of Votive2022.vsix works.

**Comment by ritchiecarroll** [comment]
FYI - here is a workaround that worked for me - updating to latest VS 2022 did not help in my case:
https://github.com/wixtoolset/issues/issues/6811#issuecomment-1366922353
