### ISSUE TITLE
"Copy and modify" instructions not working for WixUI_Advanced and WixUI_Minimal

### ISSUE THREAD

**Issue by JVimes** [wixtoolset/issues#6805]
## Bugs

* Which version of WiX are you building with?

> 3.11.2

* Which version of Visual Studio are you building with (if any)?

> Community 2022 (64-bit) 17.3.0 Preview 1.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> None

* Which version of .NET are you building with?

> .NET Framework 4.8

### Describe the problem and the steps to reproduce it.

I'm trying to follow the instructions in [Customizing Built-in WixUI Dialog Sets](https://wixtoolset.org//documentation/manual/v3/wixui/wixui_customizations.html):

> ...copy the contents of the \<Fragment/\> that includes the definition of the dialog set that you want to customize from the WiX source code to your project. Then, you must modify...

This only seems to work for WixUI_FeatureTree, WixUI_InstallDir, and WixUI_Mondo.

For WixUI_Advanced and WixUI_Minimal, my build gives several "LGHT0091 Duplicate symbol" errors.

[Here's my Product.wxs](https://github.com/wixtoolset/issues/files/8882056/Product.zip), for reference.

**Comment by barnson** [comment]
You need to rename the `UI/@Id` so it isn't the same as the original.
