### ISSUE TITLE
InVS2019, heat does not load the current msbuild, but load older version of msbuild instead. 

### ISSUE THREAD

**Issue by albertxzh** [wixtoolset/issues#6809]
I found HEAT task use older version of MSBUILD to load the proj file instead of using the msbuild distributed with VS2019. It caused the problem like some of properties' values are not found and cause the build failed. Same bug is found in VS2022 environment also.

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/6641
