### ISSUE TITLE
CustomAction with semicolon character ";" in ExeCommand fails

### ISSUE THREAD

**Issue by LaRusCat** [wixtoolset/issues#6810]
* Which version of WiX are you building with?

> 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> 16.11.8

* Describe the problem and the steps to reproduce it.

> CustomAction fails if the semicolon character ";" used in ExeCommand. Example of CustomAction:
`<CustomAction Id="InstallService" Return="check" Impersonate="no" Execute="deferred" Directory="INSTALL_ROOT" ExeCommand="C:\Program Files\MyApp;\installer_utils.exe"/>`
Error message example:
`Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: InstallServiceConfiguration, location: C:\Program Files\MyApp;\, command: C:\Program Files\MyApp;\installer_utils.exe`
Everything works fine if there are no ";" character in ExeCommand path. I tried different king of escaping: used {$SMCOL}, added extra quotes(' "  &quot;). But it doesn't help. Possibly I missed something.

* Describe the behavior you expected and how it differed from the actual behavior.

> CustomAction should work fine with any possible path(including different special but allowed characters) in ExeCommand, because users can install apps into custom folder with any supported by File System characters

**Comment by barnson** [comment]
WiX is the build tool, not the runtime; Windows Installer is in charge of custom actions. Never heard of this limitation, but it's not surprising as MSI has several places where it uses semicolons as delimiters.
