### ISSUE TITLE
Light.exe failing to build from TeamCity when using Microsoft Merge Modules

### ISSUE THREAD

**Issue by jpwkeeper** [wixtoolset/issues#6815]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?  

Wix v3.11.2

* Which version of Visual Studio are you building with (if any)?

MSBuild 15.9.21.664

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

None

* Which version of .NET are you building with?

.NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.

Wix will no longer build MSIs for us on TeamCity.  We did not change our WIX installers or our code, but something must have changed on the build agents that we cannot track.  When we attempt to build using a TeamCity agent, we get the following error:
light.exe error LGHT0001: The system cannot open the device or file specified. (Exception from HRESULT: 0x8007006E)
[15:49:30][Light] 
[15:49:30][Light] Exception Type: System.IO.FileLoadException
[15:49:30][Light] 
[15:49:30][Light] Stack Trace:
[15:49:30][Light]    at Microsoft.Tools.WindowsInstallerXml.MergeMod.IMsmMerge2.OpenDatabase(String path)
[15:49:30][Light]    at Microsoft.Tools.WindowsInstallerXml.Binder.MergeModules(String tempDatabaseFile, Output output, FileRowCollection fileRows, StringCollection suppressedTableNames)
[15:49:30][Light]    at Microsoft.Tools.WindowsInstallerXml.Binder.BindDatabase(Output output, String databaseFile)
[15:49:30][Light]    at Microsoft.Tools.WindowsInstallerXml.Binder.Bind(Output output, String file)
[15:49:30][Light]    at Microsoft.Tools.WindowsInstallerXml.Tools.Light.Run(String[] args)

This does not occur when we build manually on the same build agent.  According to merge.log, the file it is complaining about is a copy of the MSI that is located in a temporary directory:

 Error: Failed to open MSI Database: D:\BuildAgent\temp\buildTmp\xjipvj2x\xjipvj2x\myInstaller.msi

This was the only line in the merge.log file.

When we looked, that file is there.  I presume it is a copy of the MSI prior to the merge modules being merged into it.

This only occurs when we try to use merge modules.   They are not ours, but are Microsoft's runtime libraries.  If we remove all merge modules the installer builds successfully.  If we build manually with or without the merge modules the installer builds successfully.

Currently we have only one merge module being included:  Microsoft_VC141_MFCLOC_x64.msm.  All other MSMs have been removed from the wxs.

This started happening just a few weeks ago, presumably from some sort of system update to the build agents.  We tried rolling back changes to the agent but it does not fix the issue.  Nothing else changed, and every installer on the build system with a merge module started failing at the same time, even on projects that were not being actively developed.

I have downloaded the Wix source code and taken the steps necessary to build it, so I can potentially add debug information into it if I can figure out how messaging works.

**Comment by barnson** [comment]
That's inside the black box of mergemod.dll, so printf debugging won't be much help. Two things to try: Turn off real-time antivirus to avoid the file being locked (because mergemod doesn't retry) and/or use Process Monitor to get the details of the failure.

**Comment by jpwkeeper** [comment]
I appreciate your quick response.  Unfortunately our build agents are pretty locked down by IT and I won't be able to disable virus checking.  Our IT guy swears that nothing has changed, but those are Amazon systems, so I can't help but wonder if their performance parameters have changed due to an update leading to a race condition.
At any rate, the issue I'm having now is that I can't run Wix Toolset on the build agent because I don't have the signing key, I can't seem to figure out how to get rid of assembly signing in the project (I changed all of the projects but it's ignoring me and doing a delayed signing anyway), and I don't know that I can put the signature ignore commands on the build agent.  I also don't have everything I would need for an "official" build and getting it could take weeks if it's even possible.  Remember, it does not fail on my dev system, nor even on the agent when you run it by hand.
How can I get rid of the signing and/or sign it myself so that I can run it in that environment?

**Comment by jpwkeeper** [comment]
FYI, I was able to verify that it was the anti-virus that was causing the issue, but it's not something I can get rid of.  I'd still like to either get rid of the signatures or sign the project myself so that we can use our custom version of the toolkit with a retry loop on opening the database before merging, which did actually fix the problem.  I've tried several things, but those temp keys just keep coming back no matter what I do.
So how can I do that without having to do an "official" build?

**Comment by jpwkeeper** [comment]
Thanks; that's definitely helpful.  However, this isn't working either.  I am unable to build in Release. 
"D:\Subversion\Wix3\wix3-6b461364c40e6d1c487043cd0eae7c1a3d15968c\wix.proj" (default target) (1) ->
"D:\Subversion\Wix3\wix3-6b461364c40e6d1c487043cd0eae7c1a3d15968c\src\dtf\dtf.proj" (default target) (14) ->
"D:\Subversion\Wix3\wix3-6b461364c40e6d1c487043cd0eae7c1a3d15968c\src\dtf\Documents\Guide\dtfguide.helpproj" (default t
arget) (39) ->
"D:\Subversion\Wix3\wix3-6b461364c40e6d1c487043cd0eae7c1a3d15968c\src\dtf\Documents\Reference\dtfref.shfbproj" (default
 target) (40:2) ->
(CoreBuildHelp target) ->
  SHFB : warning BHT0001: Unable to get executing project:  Unable to obtain matching project from the global collectio
n.  The specified project will be loaded but command line property overrides will be ignored. [D:\Subversion\Wix3\wix3-
6b461364c40e6d1c487043cd0eae7c1a3d15968c\src\dtf\Documents\Reference\dtfref.shfbproj]
 It appears to not be able to build the HTML Help, and the HTLM Help Workshop 1.4 that is linked in the build instructions apparently no longer exists as a downloadable entity.  I only have VS2010,17, and 19 (currently working on 2017) available to me at the moment, and do not have an easy way to get 2013 which apparently included it.

**Comment by rseanhall** [comment]
Can you provide the actual error that's failing the build? There are intermittent incremental build issues in v3, you may need to clean everything and build from scratch.

HTML Help Workshop has been a component of Visual Studio for a long time, you may need to run the installer again and explicitly install it. Otherwise, this file might work - https://github.com/wixtoolset/codeplex/blob/devbundle/src/packages/HtmlHelp/htmlhelp.exe. Or maybe try https://docs.microsoft.com/en-us/answers/questions/265752/htmlhelp-workshop-download-for-chm-compiler-instal.html.

**Comment by barnson** [comment]
Or, as you're not trying to do an official build, just comment out the project references to help projects.

**Comment by robmen** [comment]
Fixed by https://github.com/wixtoolset/wix4/pull/193
