### ISSUE TITLE
Add standard Variable name validation to util:Searches and SetVariable

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6819]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> All searches require a Variable name. That name should be validated as if it was specified in a Variable element.

* Describe how you're accomplishing the feature today (if possible).

> Not

* Describe what you'd like the new feature to do.

> Update SetVariable and util extension searches to use the standard Variable name validation.

**Comment by rseanhall** [comment]
@robmen Please don't close issues that I have reported if the PR only contains tests.

**Comment by robmen** [comment]
Why not?

**Comment by rseanhall** [comment]
I expect you to reach out to me in these scenarios before closing the issue, not after I reopen it. If you are expecting me to respond to PRs instead of reaching out to me, then that is not going to work as we saw today. Especially when you merge it as soon as the build finishes. By doing so, you are showing a lack of respect since you are basically assuming that you are right and that I was wrong.

We discussed in the meeting that this involves modifying the compiler code path for all of these searches to go through the same Variable name validation as the Variable element. I thought we agreed on that. You did not do that. If you want a concrete scenario that fails, then it is a name prefixed with `Wix` that does not exist today.

**Comment by robmen** [comment]
First, I don't know why you are taking this so personally.

Second, the issue said `to use the standard Variable name validation`.  The `ParseHelper.CreateWixSearchSymbol()` uses `BundleValidator.ValidateBundleVariableName()` which I understood to be the standard Variable name validation. I was not aware that `BundleValidator.ValidateBundleVariableName()` was supposed to prevent all variable names prefixed with `Wix`.

It seemed to me that the issue as opened didn't notice that `BundleValidator.ValidateBundleVariableName()` was used internally. I added the test to ensure the util extension worked correctly and it looked good.

It sounds like you have some additional expectations, so I'm curious to see what you add.

**Comment by robmen** [comment]
I apologize for suggesting you were taking this issue personally. I let my frustration project and should not have done that. Sorry.
