### ISSUE TITLE
Wix Toolset Visual Studio 2022 Extension fails to install

### ISSUE THREAD

**Issue by rmacfadyen** [wixtoolset/issues#6839]
Wix Toolset Visual Studio 2022 Extension version 1.0.0.18

Visual Studio Community Edition 2022 17.2.7 (up to date when this issue filed)

Windows 10

When installing the Wix VSIX through VS2022's Manage Extensions at the end I receive the message "Modifications Failed. Some modifications could not be applied successfully. For more information, click on the log link at the bottom of the dialog.". 

Clicking "Close" shows a dialog with this message "The extension "WixToolset.VisualStudioExtenion.Schemas3" nexted withing "WixToolset.VisualStudioExtension.Dev17" failed to install. One or more errors occurred.".

The log file contains a lot of information, but the first error that appears to be applicable is:

`2022-07-24 5:31:55 PM - Unable to load extension at: C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\CHROMEDEBUGADAPTER\. Exception text: Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: This VSIX does not apply to any product installed on this machine. The problem could be that the VSIX manifest's format is not recognized, or that the manifest has been corrupted. ---> System.InvalidOperationException: There is an error in XML document (12, 5). ---> System.Xml.Schema.XmlSchemaValidationException: The element 'Identifier' in namespace 'http://schemas.microsoft.com/developer/vsx-schema/2010' has incomplete content. List of possible elements expected: 'SupportedProducts' in namespace 'http://schemas.microsoft.com/developer/vsx-schema/2010'.`

I've attached the full log as well.

[dd_VSIXInstaller_20220724173152_9454.log](https://github.com/wixtoolset/issues/files/9176782/dd_VSIXInstaller_20220724173152_9454.log)

**Comment by barnson** [comment]
This looks like the root cause:

> 2022-07-24 5:32:42 PM - Package 'WixToolset.VisualStudioExtension.Schemas3,version=1.0.0.18' failed to install. System.IO.IOException: The file 'C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\WiX\v3.x\wix.ca.targets' already exists.
> 2022-07-24 5:32:42 PM - Skipping cache of package 'Component.WixToolset.VisualStudioExtension.Schemas3,version=1.0.0.18' since the package or a parent package had a vital failure.

**Comment by rmacfadyen** [comment]
Should I delete the file?
