### ISSUE TITLE
Including remote payloads in a package that is assigned to a container causes cab creation to fail

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6845]
**Encountered at:** wixtoolset/repo@8797650acd990ef71f143150b873b5b7a09db86d

**Detail:**

https://github.com/wixtoolset/wix4/pull/197#discussion_r921278571

The fix for https://github.com/wixtoolset/issues/issues/6406 was incomplete. Remote payloads included in the package are not available for embedding, so that situation either needs to be an error or it needs to revert to v3 behavior along with adding a warning.

**Comment by barnson** [comment]
Error. Error.

**Comment by barnson** [comment]
Is it fair to say that all the payloads in a package must have the same `PackagingType`?

**Comment by barnson** [comment]
Error instead of warning and stop trying to make them embedded.
