### ISSUE TITLE
wix.exe convert ignores commented inner text

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#6847]
**Encountered at:** wixtoolset/repo@814cf3a2c9bd5abf00ee58cef1a6c8b557591ec6

**Detail:**

wix.exe convert does not convert the `Condition` to a `Launch` element with commented inner text:

```
<Fragment>
  <Condition>
    <!-- commented inner text -->
    my condition
  </Condition>
</Fragment>
```

**Comment by cpuwzd** [comment]
This PR is ready to be closed.
