### ISSUE TITLE
Bundle without BootstrapperApplication fails with message from exception

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6852]
**Encountered at:** wixtoolset/wix4@16ed873f

**Detail:**

Currently `BindBundleCommand` expects that a single `WixBoostrapperApplicationDllSymbol` is enforced by the compiler. If not, binding throws an exception not intended for the user: `error WIX341: The Bundle is missing 'T' data, and cannot continue.`

However, the following code will get by the compiler:

```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Bundle Version="1.0.0" UpgradeCode="USE-A-REAL-G-U-I-D">

    <Chain>
      <MsiPackage SourceFile="path\to\a.msi" />
    </Chain>
  </Bundle>
</Wix>
```

A missing `Chain` element is caught by the compiler, so I think the fix is for the same check to happen for the bootstrapper application in the compiler, but I'm not sure thus this issue.

**Comment by barnson** [comment]
See https://github.com/wixtoolset/issues/issues/6305.

**Comment by robmen** [comment]
PS: I have a commit local to improve the exception message, but that will only "help" WiX devs, not end users.

**Comment by rseanhall** [comment]
The `WixBootstrapperApplicationDllSymbol` will almost always come from Bal.wixext so unlike the chain this can't be done in the compiler. We have a very similar problem with the package payload symbols (for example `ExePackagePayload`) which is caught in `GetPackageFacadesCommand`.
