### ISSUE TITLE
installer remove some file with specific version

### ISSUE THREAD

**Issue by Alice-Thirty** [wixtoolset/issues#6863]
I use intaller install the program test 
and my program will generate some file on C:\Program Files\test\temp

Assume I have these installer test version
test-1.1.msi
test-1.2.msi
test-1.3.msi

I only want to the "test program" upgrade 1.2 to 1.3 do remove some file on C:\Program Files\test\temp

How can I do? 
I hope the sample code to ref (include     "remove file"      and     "check upgrade 1.2 to 1.3" )

**Comment by Alice-Thirty** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<?include "cpack_variables.wxi"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
    RequiredVersion="3.6.3303.0">
    <Product Id="***"
                       /* ***  */
    </Product>


    <Fragment>
        <Binary Id="CommandPrompt" SourceFile="C:\Windows\System32\cmd.exe" />
        <CustomAction Id="DeleteFolder" BinaryKey="FooBinary" 
              ExeCommand='/c rmdir /S /Q "C:\Program Files\HelloWorld 1.0.1\test\HelloWorld.txt"' 
              Execute="deferred" Return="check" />
        <InstallExecuteSequence>
        <Custom Action="DeleteFolder" Before="InstallFiles" />
        </InstallExecuteSequence>
    </Fragment>

</Wix>
```

![image](https://user-images.githubusercontent.com/108393685/184089317-2c77b17c-ce01-4085-a892-4877d474bdfb.png)


it doesnt work for "remove file" .
And I dont know how to "check upgrade 1.2 to 1.3"

**Comment by barnson** [comment]
WiX doesn't use issues for support. Please follow up on the discussion thread you opened.
