### ISSUE TITLE
WiX build fails on .NET SDK 6.0.400

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6868]
* Which version of WiX are you building with?

> 4.0.HEAD

* Which version of Visual Studio are you building with (if any)?

> 17.3.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> See attached `dotnet --info` output. [dotnetinfo.txt](https://github.com/wixtoolset/issues/files/9334166/dotnetinfo.txt)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a

* Describe the problem and the steps to reproduce it.

> Build fails in Heat. See attached log. [fail.log](https://github.com/wixtoolset/issues/files/9334170/fail.log)

* Describe the behavior you expected and how it differed from the actual behavior.

> Build succeeds everywhere every time.

[TRX_WixToolsetTest.HeatTasks.trx.zip](https://github.com/wixtoolset/issues/files/9334171/TRX_WixToolsetTest.HeatTasks.trx.zip)

**Comment by robmen** [comment]
I believe the root issue is tracked by https://github.com/microsoft/MSBuildLocator/issues/159. The workaround used in the upgrade assistant https://github.com/dotnet/upgrade-assistant/pull/1162 does seem to work for heat.exe.

Given that the root issue seems to be retargeting `System.Configuration.ConfigurationManager` from netstandard2.0 to net6.0, I'm concerned that heat.exe will not support netcoreapp3.1. But we'll be unblocked for now and perhaps we should retarget WiX v4.0 to net6.0.
