### ISSUE TITLE
Wix is using the wrong path when installed standalone on a build server with VS2022 Build Tools

### ISSUE THREAD

**Issue by MoonStorm** [wixtoolset/issues#6874]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Build Tools 2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.18

* Which version of .NET are you building with?

> .NET SDK  6.0.400

* Describe the problem and the steps to reproduce it.

> Using the latest recommended setup to create a WiX Setup projects, the project works fine under Visual Studio 2022 but fails on the build server, where Visual Studio Build Tools 2022 and WiX are installed. The WiX project seems to be searching for '$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets', however building with 'dotnet build' on the build server, $(MSBuildExtensionsPath32) resolves to "C:\Program Files\dotnet\sdk\6.0.400". The wix installer does not install targets in that location.

* Describe the behavior you expected and how it differed from the actual behavior.

> The WiX project should use the right location where Wix.targets is installed.

**Comment by robmen** [comment]
Building .wixprojs using `dotnet build` is a feature of WiX v4.

**Comment by MoonStorm** [comment]
We're sure not going to use anything with "Preview" in its name. Any other suggestions with the current recommended tools?

**Comment by barnson** [comment]
Use Framework MSBuild.

**Comment by MoonStorm** [comment]
The 'msbuild' runner in our environment has been long deprecated. Just tried with 'dotnet msbuild' and got the same error.

**Comment by robmen** [comment]
Then it would be most productive to help us [complete the remaining WiX v4 tasks](https://github.com/wixtoolset/issues/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4.0+sort%3Acreated-asc) so that we can remove the preview label. 👍🏻 

This particular issue--using `dotnet build`--is already resolved in WiX v4.

**Comment by rseanhall** [comment]
Legacy (.NET Framework) MSBuild is not deprecated. The default location for VS2022 Enterprise is at "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe". I assume there is a similar location when installing other SKUs such as the Build Tools SKU.

**Comment by MoonStorm** [comment]
I never said that MsBuild was deprecated. That runner *under our environment* (TeamCity) has been deprecated and is not working with the 2022 toolset. However, for anyone who's using the same environment, it seems that msbuild can be called indirectly through the .NET  runner and more specifically 'dotnet msbuild', but targeting directly the 2022 version, with the extra command line "-restore", unless you run an explicit 'dotnet restore' beforehand. That way the WiX targets seem to be properly located and working normally.

As for helping with the tasks for v4, I did have a look at them and I simply lack the skill set to give you guys a hand. I do understand and appreciate the effort you're putting into it. I hope that soon you'll be able to release that version, cause we're already at the point where we're starting to have very limited options to use this gem.
