### ISSUE TITLE
ThmUtil coordinates and dimensions no longer support `-0`

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#6886]
* Which version of WiX are you building with?

> wix4@2f8bf7c0cc4402777315e93536fbc63e1e1f0fee

* Which version of Visual Studio are you building with (if any)?

> n/a

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> n/a

* Which version of .NET are you building with?

> n/a

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a

* Describe the problem and the steps to reproduce it.

> In WiX v3, coordinates and dimensions could be specified as `-0` to refer to the bottom/right-most of the parent. That now fails with `Invalid coordinate or dimension attribute value`.

* Describe the behavior you expected and how it differed from the actual behavior.

> `-0` should remain a valid coordinate or dimension. `-1` is close but not as pretty when you want to right-justify a pretty picture.

**Comment by rseanhall** [comment]
I created the following theme to test this:

```
<Theme xmlns="http://wixtoolset.org/schemas/thmutil/2010">
    <Window Width="512" Height="512" HexStyle="100a0000" FontId="0">wix3testing</Window>
    <Font Id="0" Height="-12" Weight="500" Foreground="000000" Background="FFFFFF">Segoe UI</Font>

    <Page Name="PositiveZero">
        <Image X="0" Y="0" Width="256" Height="256" ImageFile="image.bmp" Visible="yes"/>
    </Page>
    <Page Name="NegativeZero">
        <Image X="-0" Y="-0" Width="256" Height="256" ImageFile="image.bmp" Visible="yes"/>
    </Page>
</Theme>
```

Using 3.11.2 thmviewer (apparently 3.14 thmviewer crashes), it's true that this theme is valid (assuming you put a valid image file named image.bmp next to the theme file). However, I see no difference between the two pages. Both are left justified and top justified.

**Comment by barnson** [comment]
The repro I have is from an early WiX v4 ThmUtil. I'll see if I can get a repro on a modern build; not being able to right/bottom-justify all the way would be a sadness.

**Comment by barnson** [comment]
`-0` coordinates is nonsensical; ignore that. `-0` dimensions were parsed as `0`, which works both now and then. Fix is to add explicit documentation on `0`.
