### ISSUE TITLE
##[error]light.exe(0,0): Error LGHT0001: Failed to save resource. Error 110

### ISSUE THREAD

**Issue by robinNode** [wixtoolset/issues#6902]
Hi,
I have got this error recently. it is not always happening. I am using a pipeline of MS DevOps. 
If I manually run it's working fine. please help to check it. thanks a lot.

Error details
 C:\ADO_Agents\Agent1\Data\15\s\Setup\NuGetPackages\WiX.3.11.2\build\..\tools\Light.exe -out "C:\ADO_Agents\Agent1\Data\15\s\Setup\Output\Package_1.1.89.exe" -pdbout "C:\ADO_Agents\Agent1\Data\15\s\Setup\Output\Package_1.1.89.wixpdb" -ext C:\ADO_Agents\Agent1\Data\15\s\Setup\NuGetPackages\WiX.3.11.2\tools\WixUIExtension.dll -ext C:\ADO_Agents\Agent1\Data\15\s\Setup\NuGetPackages\WiX.3.11.2\build\..\tools\\WixUtilExtension.dll -ext C:\ADO_Agents\Agent1\Data\15\s\Setup\NuGetPackages\WiX.3.11.2\build\..\tools\\WixBalExtension.dll -loc theme\1033\HyperlinkTheme.wxl -spdb -contentsfile obj\Release\Bundle.wixproj.BindContentsFileList.txt -outputsfile obj\Release\Bundle.wixproj.BindOutputsFileList.txt -builtoutputsfile obj\Release\Bundle.wixproj.BindBuiltOutputsFileList.txt -wixprojectfile C:\ADO_Agents\Agent1\Data\15\s\Setup\Source\xxxx\Bundle\Bundle.wixproj obj\Release\Bundle.wixobj obj\Release\Prerequisites.wixobj obj\Release\Products.wixobj
**##[error]light.exe(0,0): Error LGHT0001: Failed to save resource. Error 110**
**light.exe : error LGHT0001: Failed to save resource. Error 110** [C:\ADO_Agents\Agent1\Data\15\s\Setup\Source\xxxx\Bundle\Bundle.wixproj]

OS Version: Windows 10 x64
MSBuild Version: 1.179.0
.NET version: 6.0.6
WiX Version: 3.11.2.4516

**Comment by barnson** [comment]
Probably related to https://github.com/wixtoolset/issues/issues/6882.

**Comment by barnson** [comment]
See also https://github.com/wixtoolset/issues/issues/4791.
