### ISSUE TITLE
Using <bal:Condition> in <Product> (instead of <Bundle>)

### ISSUE THREAD

**Issue by standardizer** [wixtoolset/issues#6906]
I’m using Wix 3.11 to create an MSI file for a Visual Studio C# .NET 6 Windows Desktop project. The installer only allows installation, if the .NET 6 Windows Desktop Runtime is installed. This is the content of my `Product.wsx` file:

> <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
	<Product Id="*" …>
		<Package InstallerVersion="200" Platform="x64" Compressed="yes" InstallScope="perUser" InstallPrivileges="limited" …/>

		
		<Media Id="1" Cabinet="$(var.CabName)" EmbedCab="yes" />

		
		<Feature Id="ProductFeature" Title="$(var.Name)" Level="1">
			
			<ComponentGroupRef Id="ProductComponents" />
			
			<ComponentRef Id="RegistryEntries" />
			
			<ComponentRef Id="ApplicationShortcut" />
			
			<ComponentGroupRef Id="ComponentGroupDesktopShortcut" />
		</Feature>

		
		<Property Id="CheckNETRuntime_Framework" Value="Microsoft.WindowsDesktop.App" />
		<Property Id="CheckNETRuntime_Version" Value="6.0.0" />
		<Property Id="CheckNETRuntime_Result" />

		
		<Binary Id="CustomActions" SourceFile="NetCoreCheckCA.dll" />

		<CustomAction Id="CheckRuntime" Return="ignore" BinaryKey="CustomActions" DllEntry="CheckNETRuntime" />

		<InstallExecuteSequence>
			<Custom Action="CheckRuntime" Before="LaunchConditions"  />
		</InstallExecuteSequence>
		<InstallUISequence>
			<Custom Action="CheckRuntime" Before="LaunchConditions"  />
		</InstallUISequence>

		<Condition Message="Please install .NET 6 Windows Desktop Runtime as it is required.">
			<![CDATA[CheckNETRuntime_Result=0]]>
		</Condition>
		
	</Product>
	… some Fragments here …
</Wix>

I’d like to add a link in the `Condition`, but need to use `bal:Condition` from the `WixBalExtension`. This `bal:Condition` is not accepted in `Product`, but must be nested in `Bundle` or `Fragment` according to the [WiX documentation](https://wixtoolset.org/documentation/manual/v3/xsd/bal/condition.html). I do not want to use the `Bundle` structure. How can I make use of this element?

**Comment by barnson** [comment]
`bal:Condition` is only supported in bundles.
