### ISSUE TITLE
Documented features in 3.11 not supported in WixNetFxExtension

### ISSUE THREAD

**Issue by ColinWPA** [wixtoolset/issues#6925]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> (WiX version in major.minor.release.build format) 3.11.2.4516

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update) 2019 (16.11.12)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format) 1.0.0.18

* Which version of .NET are you building with? 

> (.NET version) 4.8 or 5.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version) not an install problem, it is a compile problem

* Describe the problem and the steps to reproduce it.

> When using documented PackageGroupID types NetFx48Web and NetFx48Redist, the xml script will not compile. the error given is "Unresolved reference to symbol 'ChainPackageGroup:NetFx48Web'" (or the Redist variant). Similarly trying to use "WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED" as a way to include the web installer for .NET 4.8 results in the compile time error  "Unresolved reference to symbol 'Property:WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED'"

I include a reference to WixNetFxExtension in the references section, as well as including the reference in the script as well:

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
	 xmlns:util="http://schemas.microsoft.com/wix/UtilExtension"
	 xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension" >

It would seem then that the PackageGroupIDs or Property Names shown in the documents are as yet not built into the supporting dlls.

This is the contents of my Bundle file:

<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
	 xmlns:bal="http://schemas.microsoft.com/wix/BalExtension"
	 xmlns:netfx="http://schemas.microsoft.com/wix/NetFxExtension" >
	<?define ProjectDir=C:\Workspace\Fusion Wireless System Path Estimator\FusionPathEstimatorSetup\?>
	
	<Bundle Name="Fusion Path Estimator Installer" Version="1.0.0.0" Manufacturer="EMS" UpgradeCode="f13d997e-4683-446c-ab56-342f492cddbc">
		<WixVariable Id="WixUIBannerBmp"  Value="Images\installer_top-banner.bmp" />
		<WixVariable Id="WixUIDialogBmp"  Value="Images\installer_background.bmp" />
		<WixVariable Id="WixUILicenseRtf" Value="$(var.ProjectDir)\license.rtf" />

		<BootstrapperApplicationRef Id="WixStandardBootstrapperApplication.RtfLicense" >
			<bal:WixStandardBootstrapperApplication
				LicenseFile="$(var.ProjectDir)license.rtf"
				LogoFile="$(var.ProjectDir)Images\fusionlogo.bmp"
				LogoSideFile="$(var.ProjectDir)Images\installer_background.bmp"/>
		</BootstrapperApplicationRef>

		<Chain>
			
			<PackageGroupRef Id="NetFx48Web" />   

			<MsiPackage SourceFile="$(var.ProjectDir)\bin\Release\FusionPathEstimatorSetup.msi" />
		</Chain>
	</Bundle>
</Wix>

Is there a work around for this so that the Wix toolset can be successfully used to install a recent version of .NET along with the payload of application files?

* Describe the behavior you expected and how it differed from the actual behavior.

> Following the examples given by various users on various programmer websites, I would have expected to be able to extrapolate their examples (for 4.6.1 and 4.7.1 to be possible for 4.8 at least (but not necessarily 5.0 as that clearly is not yet supported in Wix3.11 - not yet documented). But 4.8 is documented but seems to not be in the relevant dll yet.

Is there another step needed to get this to work?

**Comment by barnson** [comment]
It's implemented in WiX v3.14.

**Comment by ColinWPA** [comment]
From your web page one can download 3.11.2 as the latest production build. It seems your organization is not keen for users to download development builds, but is this your recommendation?

Development Builds
These have the latest changes, but may introduce unexpected bugs. These are not considered to be production-ready.
If you are still interested, you can find them here<https://wixtoolset.org/releases/development/>.

I intend to use the tool in a production environment for distribution. Would you advice against this?

Thank you
Colin Attwell

From: Bob Arnson ***@***.***>
Sent: Wednesday, September 21, 2022 2:15 PM
To: wixtoolset/issues ***@***.***>
Cc: Attwell, Colin (Contractor) ***@***.***>; Author ***@***.***>
Subject: [External]Re: [wixtoolset/issues] Documented features in 3.11 not supported in WixNetFxExtension (Issue #6925)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

It's implemented in WiX v3.14.

**Comment by ColinWPA** [comment]
Ok thanks. I’ll pursue the option suggested to see if the organization want’s to go that route (or rather buy a license to a commercial product)

Thanks again for your help and support.

From: Rob Mensching ***@***.***>
Sent: Wednesday, September 21, 2022 2:33 PM
To: wixtoolset/issues ***@***.***>
Cc: Attwell, Colin (Contractor) ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [wixtoolset/issues] Documented features in 3.11 not supported in WixNetFxExtension (Issue #6925)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@ColinWPA<https://github.com/ColinWPA> this is an open source project, not an organization.

Development builds are what they say they are. A build from a point in time with no attempt at broad validation across the community.

If you want to treat the WiX toolset like a product, there are companies that provide support contracts for WiX<https://www.firegiant.com/services/>.
