### ISSUE TITLE
UICompiler custom actions duplication

### ISSUE THREAD

**Issue by StefanStojanovic** [wixtoolset/issues#6937]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Version 4.0.0-preview.1-build.532+dfcd6728a9d56ac37a5daa8cbedabbf10c333773 (latest develop at the time of reporting), though it was happening in previous versions of WiX 4

* Which version of Visual Studio are you building with (if any)?

> VS 2022, version 17.3.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A, building with CLI

* Which version of .NET are you building with?

> .NET 6.0.9

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A, problem occurs when running `wix build`

* Describe the problem and the steps to reproduce it.

The problem I'm experiencing is that when more then one `ui:WixUI` elements are used build command fails with error WIX0091 (duplicate symbol). The simplest way to reproduce this problem is to use the following product.wxs file and then just to run `wix build -ext WixToolset.UI.wixext product.wxs`. product.wxs file looks like this:
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">
  <Package Manufacturer="0" Name="0" Version="0.0.0.0" UpgradeCode="00000000-0000-0000-0000-000000000000">
    <ui:WixUI Id="WixUI_Common" />
    <ui:WixUI Id="WixUI_ErrorProgressText" />
  </Package>
</Wix>
```
I've checked UICompiler code and noticed that it adds `PrintEula` and `ValidatePath` custom action symbols for each `ui:WixUI` element detected, so as expected, when having two or more of those there will be duplication. I made a draft PR to address this issue https://github.com/wixtoolset/wix4/pull/255

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect to be able to use more then one `ui:WixUI` elements without any problems. The draft PR enabling this behavior can be found at https://github.com/wixtoolset/wix4/pull/255

**Comment by StefanStojanovic** [comment]
Fixed by landing https://github.com/wixtoolset/wix4/pull/255

**Comment by rseanhall** [comment]
I think it's worth noting that the fix only works in certain scenarios. For example, if there are multiple `ui:WixUI` elements in separate fragments and the fragment with the generated code is not included then it won't work (it will be referencing a custom action that doesn't exist).
