### ISSUE TITLE
Standardize on WiX v4 on .NET 6

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#6942]
* Describe the scenario and benefits that the feature supports.

> WiX v4 is expected to release when .NET 6 is the sole LTS. We should probably adopt that.

* Describe how you're accomplishing the feature today (if possible).

> WiX v4 standardized on `netcoreapp3.1` as that was the LTS at the start of WiX v4.0.

* Describe what you'd like the new feature to do.

> Update all `netcoreapp3.1` projects to `net6.0`.

**Comment by Adinihal** [comment]
hi @robmen is target framework net6.0-windows supports in wix project (ProductVersion -3.10) or do I need to update it to wix.4.0 , because after a successful build I am unable to install the artifacts(packages) in my local machine it says failed to install the msi.

**Comment by anbrikzone** [comment]
> hi @robmen is target framework net6.0-windows supports in wix project (ProductVersion -3.10) or do I need to update it to wix.4.0 , because after a successful build I am unable to install the artifacts(packages) in my local machine it says failed to install the msi.

Have the same problem 
NU1202	Package wix 4.0.0 is not compatible with net6.0-windows7.0 (.NETCoreApp,Version=v6.0). Package wix 4.0.0 supports: net6.0 (.NETCoreApp,Version=v6.0) / any
