### ISSUE TITLE
add -frag to website and command help

### ISSUE THREAD

**Issue by NiC1825** [wixtoolset/issues#6949]
Hello WiX Team,

I spend the last 3hours finding out why WiX Heat doesn't have the directory of folders and only has the files in that folder.
So I tried to check your list, and I didn't find -frag there, which resolves that problem.
Luckily a StackOverflow post has that tipp for me that you need to add -frag.
So please be so friendly as to add this on your website where "all" your commands are, besides of -frag.
Website:
https://wixtoolset.org/documentation/manual/v3/overview/heat.html

Thank you for making this world a better place.

**Comment by barnson** [comment]
Do you mean `-sfrag`?

**Comment by NiC1825** [comment]
Through misspelling, it actually works.
Not using -sfrag was the solotuion.
