### ISSUE TITLE
Test regression on arm64

### ISSUE THREAD

**Issue by pbo-linaro** [wixtoolset/issues#6960]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

develop branch: [e550b63845a90e1a9452060b50a00ca5d9ee8c67](https://github.com/wixtoolset/wix4/commit/e550b63845a90e1a9452060b50a00ca5d9ee8c67)

* Which version of Visual Studio are you building with (if any)?

VS 2022, latest stable

* Which version of .NET are you building with?

DotNet 6.0.402

* Describe the problem and the steps to reproduce it.

When building and testing on Windows on Arm, a new regression was introduced with commits on the 15th of October.

```
The specified task executable location "C:\ci\EjYHx3wk\0\Linaro\windowsonarm\nightly\wix4\wix4\build\wix\Debug\test\WixToolsetTest.BuildTasks\net472\..\..\..\publish\WixToolset.Sdk\tools\net472\arm64\wix.exe" is invalid.
Expected: True
Actual:   False
  Stack Trace:
     at WixToolsetTest.BuildTasks.WixBuildTaskFixture.CanBuildSimpleMsiPackage() in C:\ci\EjYHx3wk\0\Linaro\windowsonarm\nightly\wix4\wix4\src\wix\test\WixToolsetTest.BuildTasks\WixBuildTaskFixture.cs:line 61
```

[Log with fail](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/3176384382) | [log ok (previously)](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/3176384382)

[Full build script](https://gitlab.com/Linaro/windowsonarm/packages/wix4/-/blob/master/recipe.sh)

* Describe the behavior you expected and how it differed from the actual behavior.

Test should pass. The fact it is trying to find a binary in `...net472...` suggests there is a problem, as dotnet 6.0 should be targeted now.

**Comment by robmen** [comment]
`net472` is used when the NETFX MSBuild is used to execute the build (as is the case for two executions of the `CanBuildSimpleMsiPackage()` test). Using `net472` with NETFX MSBuild ensures the user does not also need to install .NET 6 (or greater). However, `net472` does not support `arm64` so we'll need to make sure `wix.exe` falls back to `x86` when built using the NETFX MSBuild on an ARM64 computer.

This break was exposed because NETFX MSBuild used to run `wix.exe` code in-proc but no longer does to prevent polluting the MSBuild process with the assembly loading `wix.exe` can do during a build.

**Comment by pbo-linaro** [comment]
That makes sense.
Don't hesitate to ping me so I can test your fix on this platform if needed.
Thanks a lot!

**Comment by robmen** [comment]
Alternatively, we could ship an `arm64 wix.exe` that targeted `net481` since I think that `net481` is the first NETFX with full support for `arm64`.

**Comment by pbo-linaro** [comment]
I'm not expert on dotnet, but I read that prior to dotnet 6.0, arm64 has issues, because it can't be installed along x64 version. (and depending in which order you install both, it will break your install, as some files are overwritten).

So I'd better stick with dotnet 6.0.

**Comment by pbo-linaro** [comment]
"ship an `arm64` wix": Does that mean to commit a binary file to bootstrap the rest?

**Comment by robmen** [comment]
@pbo-linaro Can you test a PR here using your ARM hardware on Windows 10? I'm curious about what happens if we provide an `arm64` `wix.exe` and run it on NETFX 4.7.2 (_not _NETFX 4.8.1).

**Comment by pbo-linaro** [comment]
Windows 10 is mandatory? I only got machines running Windows 11 at the moment.

**Comment by robmen** [comment]
Windows 11 is fine _if_ it has NETFX 4.7.2 (_not _NETFX 4.8.1).

**Comment by pbo-linaro** [comment]
Yes, no problem, I'll install that version specifically.

**Comment by pbo-linaro** [comment]
When looking for 4.7.2 installer [here](https://support.microsoft.com/en-us/topic/microsoft-net-framework-4-7-2-offline-installer-for-windows-05a72734-2127-a15d-50cf-daf56d5faec2), it offers me an x86-64 version.

Is there an arm64 version? If yes, with which architecture do you want it to run?

Thanks

**Comment by robmen** [comment]
Well, that actually points to the issue I was trying to sort out. I expected there was no support for ARM64 in NETFX 4.7.2 so I was curious what would happen if we tried to run an ARM64 binary without a matching NETFX architecture to go with it.

My lack of experience with the ARM64 support matrix in Windows is apparent here. I _think_ the scenarios are all covered where if we provide an ARM64 `wix.exe` the only time it will be called is if you are already running an ARM64 NETFX. So above, I was trying to manufacture a situation where you had ARM64 hardware but an x86 NETFX installed. Does that make sense? Is that scenario possible to manufacture with your available hardware?

Much appreciated, by the way.

**Comment by pbo-linaro** [comment]
After trying to install x86-64 version, it refuses, saying I have a more recent version.

Please find attached the error message, and all the .net version I have on this machine.
![dotnet](https://user-images.githubusercontent.com/101587250/196492410-adbfffba-1629-4025-971b-0b33fd6deb1b.png)

**Comment by pbo-linaro** [comment]
I removed all the .net installed on my machine, but it still does not want to install dotnet 4.7.2. For dotnet 4.8.0, I can;'t even find an installer on internet for it.

As you can see, my registry point that dotnet 4.8.X is installed, but I have no clue how it says that. Could it be built in Windows 11?

![status](https://user-images.githubusercontent.com/101587250/196500724-c1bc6628-fdc7-49da-bcbe-70bebec8ee5e.png)

When we discussed on mailing list, you agree to bring minimal version to dotnet 6.0 for building it. Why not push that for users of Wix as well? That would make so much sense.

**Comment by robmen** [comment]
Yes, NETFX is built into Windows by default. Unfortunately, it looks like that Windows 11 machine has already been upgraded to .NET Framework v4.8.1. The ideal would be to get a clean Windows 11 image before it was upgraded to v4.8.1.

Also note that the WiX Toolset supports both .NET Framework (NETFX v4.7.2) and .NET (v6.0) as platforms. That allows us to meet the needs of both sets of users. NETFX users do not need to install .NET 6 if they don't need it (as you've discovered NETFX is built into Windows). The .NET users can install and build using `dotnet.exe` without using the .NET Framework. What I agreed to in email was to move our .NET Core v3.1 minimum to .NET 6.0.

We do NOT want to require all WiX users to install .NET 6.0.

**Comment by pbo-linaro** [comment]
I understand your concern to require this from all users.

Regarding Windows on Arm, it's not possible easily to install a "clean image", as we could do on x86 machines. Thus, it won't be possible to try this.

Would that be acceptable to simply skip the concerned test when running on arm64 platform? Or are more things involved?

**Comment by robmen** [comment]
I see two options:

1. Introduce a NETFX `arm64 wix.exe`. Then the test will work for ARM64 same as all the other platforms.
2. Add the fallback behavior to the test that exists in the `WixBuild` task that handles the fact that there is no `arm64 wix.exe` on NETFX today.

I'm inclined towards option 1 since it seems like having native `arm64 wix.exe` as it seems more future proof. Namely, it would be required if WOW is ever removed from ARM64 Windows. Unfortunately, the .NET handling of native code continues to be under developed so that which should be simple still isn't working. Still working on it.

**Comment by pbo-linaro** [comment]
Yes, 1. seems the better solution. Would that be possible to deactivate this test (or implement 2) for the time being?

Since it is failing daily on our side, we won't be able to catch automatically any other regression during that time.

If that's not acceptable on develop branch, I'm ok to keep a patch on our side, but I need your expertise to disable this test, as I'm not familiar with C#, solutions stuff and .NET in general. Thanks.

**Comment by pbo-linaro** [comment]
Thanks for your workaround. I can confirm CI is back to [green](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/3201419462). Don't hesitate to ping me for testing a new PR on this platform.

**Comment by robmen** [comment]
@pbo-linaro I have a PR https://github.com/wixtoolset/wix4/pull/272 open to add native ARM64 wix.exe .NET Framework support. I've removed the workaround, so could you try that PR against your ARM64 hardware to see if everything keeps working?

**Comment by pbo-linaro** [comment]
@robmen I confirm it's working 👍 ([full log](https://github.com/wixtoolset/issues/files/9883201/pr_wix.log)). Thanks for your fix!
