### ISSUE TITLE
Nessus finding: Microsoft Windows Unquoted Service Path - windows exporter

### ISSUE THREAD

**Issue by albionb96** [wixtoolset/issues#6966]
I explained my issue on the prometheus exporter project here: https://github.com/prometheus-community/windows_exporter/issues/1079, but they said that I should open a bug report upstream into you project since they use wix3 to specify their service paths. I don't know how to continue here, just wanted to say that during an official Nessus scan, the path of a service which uses your product was considered as vulnerable and untrusted, and I think the reason was as I explained that the service path was unquoted.

**Comment by barnson** [comment]
WiX is the build tool; Windows Installer is what creates services; Windows is what turns those intro registry keys.
