### ISSUE TITLE
Unable to Access 'configure now' and 'close' buttons Using Keyboard.

### ISSUE THREAD

**Issue by msftedad** [wixtoolset/issues#6975]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
Wix Toolset v3.11.1.2318

* Which version of Visual Studio are you building with (if any)?
VS2017 version 15.9.12

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
0.9.21.62588

* Which version of .NET are you building with?
3.5

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 11

* Describe the problem and the steps to reproduce it.
1.Connect to virtual machine 
2. Open File manager and select ODJConnectorBootstrapper and open it
3. Intune Connector for Active Directory dialogue will be opened 
4.Navigate till check box and check it
5.Navigate to install button and invoke it 
6.Try to navigate to configure now and close buttons using keyboard and observe whether the focus is going or not.

* Describe the behavior you expected and how it differed from the actual behavior.
After installing, the keyboard focus should go to the configure now or close button
User should be able to access 'configure now' and 'close' buttons Using Keyboard.
But user is unable to Access 'configure now' and 'close' buttons Using Keyboard.

[dcfeaa1e-fc87-4cc8-b6ec-7e181014bdd3.zip](https://github.com/wixtoolset/issues/files/9900791/dcfeaa1e-fc87-4cc8-b6ec-7e181014bdd3.zip)

**Comment by barnson** [comment]
Focus isn't on the window. Fixed in v4.
