### ISSUE TITLE
System.IO.IOException: Failed to save resource. Error 5

### ISSUE THREAD

**Issue by grizoood** [wixtoolset/issues#6983]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> v3.14.0.6526

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Professional 2019
Version 16.11.17

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> WiX Toolset 1.0.0.20

* Which version of .NET are you building with?

> 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10 Entreprise 21H2

* Describe the problem and the steps to reproduce it.

> When I generate or regenerate the custom action, this bug occurs.

* Describe the behavior you expected and how it differed from the actual behavior.

> 2 Errors

>La commande ""C:\Program Files (x86)\WiX Toolset v3.14\bin\..\sdk\MakeSfxCA.exe" "C:\Test\CustomAction1\CustomAction1\obj\x86\Debug\CustomAction1.CA.dll" "C:\Program Files (x86)\WiX Toolset v3.14\bin\..\sdk\x86\SfxCA.dll" "C:\Test\CustomAction1\CustomAction1\obj\x86\Debug\CustomAction1.dll" "@C:\Test\CustomAction1\CustomAction1\obj\x86\Debug\CustomAction1.CA.rsp"" s'est arrêtée avec le code 1.	CustomAction1

> System.IO.IOException: Failed to save resource. Error 5	CustomAction1	C:\Test\CustomAction1\CustomAction1\EXEC

**Comment by barnson** [comment]
This isn't a general bug in WiX. Frequently, access denied errors occur because of real-time antivirus. You can use tools like Process Monitor to check for the root cause of the conflict.

**Comment by keremispirli** [comment]
@grizoood have you found a solution to this problem?

We have the same problem with 3.11.2, and for some reason it started to happen way too often recently. The build folder is excluded from AV, and there is no other scanner program running on the machine. Also, we have many other projects building on that machine **in parallel**; it's only Wix projects that throw this error (and Error 110).

It actually looks related to #4791. If it is, then it should be resolved in Wix 4.0 with wixtoolset/wix#258. Too bad it's not backported.
