### ISSUE TITLE
WiX v4 Conversion - WiXUIBannerBmp WiXUIDalogBmp WixUILecenseRtf variables not used

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#6995]
* Which version of WiX are you building with?

v4 preview 1  / heatwave 0.9.0.5

* Which version of Visual Studio are you building with (if any)?

2022 17.3.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

* Describe the problem and the steps to reproduce it.

I converted a v3 project that used WixUI_FeatureTree and defined WixUIBannerBmp=Resources\Banner.jpg;WixUIDialogBmp=Resources\Dialog.jpg;WixUILicenseRtf=Resources\EULA.rtf.   After conversion these were listed as binder variables and the built MSI did not have the branding and EULA that the v3 MSI had. 

* Describe the behavior you expected and how it differed from the actual behavior.

I'd expect a converted project to still use the branding and EULA that the v3 project used.

> (Be as specific as you can and err on the side of providing too much information.)

**Comment by barnson** [comment]
Can you attach the v3 .wixproj?

**Comment by chrpai** [comment]
<img width="387" alt="v3" src="https://user-images.githubusercontent.com/43178814/201738709-a03b2766-39c8-497b-9b29-34f22a9
[Sample.zip](https://github.com/wixtoolset/issues/files/10006060/Sample.zip)
f4042.png">
<img width="387" alt="v4" src="https://user-images.githubusercontent.com/43178814/201738717-88a4bf96-953e-409c-8ef9-290ec146f613.png">
