### ISSUE TITLE
error WIX0094: The identifier 'CustomAction:WixUIValidatePath' could not be found

### ISSUE THREAD

**Issue by matbech** [wixtoolset/issues#6998]
* Which version of WiX are you building with?
4.0.0-preview.1

* Describe the problem and the steps to reproduce it.
Instead of using the predefined UIs from the UI extension, define a WixUI_Test.wxs with the UI
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
    <Fragment>
        <UI Id="WixUI_Test">          
            <DialogRef Id="BrowseDlg" />
            <Publish Dialog="BrowseDlg" Control="OK" Event="DoAction" Value="WixUIValidatePath" Order="3" />
       </UI>
    <Fragment>
<Wix>
```

Then reference it:
```
<UIRef Id="WixUI_Test" />
```

* Describe the behavior you expected and how it differed from the actual behavior.
No errors

Actual result:
`error WIX0094: The identifier 'CustomAction:WixUIValidatePath' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.`

**Comment by barnson** [comment]
Custom actions like `WixUIValidatePath` are now platform-specific, so they need special handling. That's handled via the `WixUI` element in `WixToolset.UI.wixext`. So rather than `UIRef`, use `ui:WixUI` -- that will wire up the custom actions.

**Comment by matbech** [comment]
Thank you.

**Comment by barnson** [comment]
Investigate whether `wix convert` should warn

**Comment by ValentijnMakkenze** [comment]
I ran into a similar issue

WIX0094	The identifier 'CustomAction:WixUIPrintEula' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.	 D:\a\wix4\wix4\src\ext\UI\wixlib\LicenseAgreementDlg.wxs	15

But don't know what you mean with "rather than UIRef, use ui:WixUI" 
We have an UI block that starts with UIRef 

```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <UI Id="BRKMONUI">

      <UIRef Id="WixUI_Common" />
      <Property Id="DefaultUIFont" Value="WixUI_Font_Normal" />
      <TextStyle Id="WixUI_Font_Normal" FaceName="Tahoma" Size="8" />
      <TextStyle Id="WixUI_Font_Bigger" FaceName="Tahoma" Size="12" />
      <TextStyle Id="WixUI_Font_Title" FaceName="Tahoma" Size="9" Bold="yes" />

      <Property Id="WIXUI_INSTALLDIR" Value="InstanceDirectory" />
      <Property Id="ApplicationFolderName" Value="InstanceDirectory" />

      <DialogRef Id="BrowseDlg" />
      <DialogRef Id="DiskCostDlg" />
      <DialogRef Id="ErrorDlg" />
      <DialogRef Id="FatalError" />
      <DialogRef Id="FilesInUse" />
      <DialogRef Id="MsiRMFilesInUse" />
      <DialogRef Id="PrepareDlg" />
      <DialogRef Id="ProgressDlg" />
      <DialogRef Id="ResumeDlg" />
      <DialogRef Id="UserExit" />
      <DialogRef Id="ClientSecretErrorDlg" />

      <Publish Dialog="ExitDialog" Control="Finish" Event="EndDialog" Value="Return" Order="999" />
      <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="LicenseAgreementDlg" />
      <Publish Dialog="LicenseAgreementDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" />
      <Publish Dialog="LicenseAgreementDlg" Control="Next" Event="NewDialog" Value="SelectWebSiteDlg" Condition="LicenseAccepted = &quot;1&quot;" />
```
Btw: The Condition attributes on Publish gives an attribute is not declared warning and it's not in the documentation
https://wixtoolset.org/docs/reference/schema/wxs/publish/

**Comment by barnson** [comment]
Instead of `<UIRef Id="BRKMONUI" />`, use `<ui:WixUI Id="BRKMONUI" />`.

**Comment by virzak** [comment]
After modifying my code to look as suggested:

```
<ui:WixUI Id="WixUI_Common" />
```

I'm getting the following error:

```
error WIX0094: The identifier 'WixUI:WixUI_Common_X86' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.
```

That's with: 4.0.0-rc.1

**Comment by barnson** [comment]
`ui:WixUI` isn't needed for `WixUI_Common`, only the dialog sets that call custom actions. For `WixUI_Common`, `UIRef` will keep working. But I'll take a look at keeping it consistent.

**Comment by vdrasutis** [comment]
Looks like similar issue: https://github.com/wixtoolset/issues/issues/7925
