### ISSUE TITLE
Typo: OuputItems in CreateItemAvoidingInference task

### ISSUE THREAD

**Issue by matbech** [wixtoolset/issues#7000]
* Which version of WiX are you building with?
4.0.0-preview.1

The output params of the CreateItemAvoidingInference task are named:
**OuputItems**
https://github.com/wixtoolset/wix4/blob/develop/src/wix/WixToolset.BuildTasks/CreateItemAvoidingInference.cs

Search result for "OuputItems":
https://github.com/wixtoolset/wix4/search?q=ouputitems

**Comment by robmen** [comment]
Heh. That was introduced in WiX v3 and if we had MSBuild in v2 (I forget), I bet the typo was there too.

**Comment by matbech** [comment]
The summary of this task doesn't seem to be very accurate either:
https://github.com/wixtoolset/wix4/blob/develop/src/wix/WixToolset.BuildTasks/CreateItemAvoidingInference.cs#L10
as well as:
https://github.com/wixtoolset/wix4/blob/develop/src/wix/WixToolset.BuildTasks/CreateItemAvoidingInference.cs#L29
And a typo here:
converty->convert
https://github.com/wixtoolset/wix4/blob/develop/src/wix/WixToolset.BuildTasks/CreateItemAvoidingInference.cs#L17
