### ISSUE TITLE
64bit msm -> msi WIX0204 error

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7002]
* Which version of WiX are you building with?

wix 4 preview 1

* Which version of Visual Studio are you building with (if any)?

vs 2022 17.4.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

HeatWave 0.9.0.5

* Describe the problem and the steps to reproduce it.

I converted a 32bit  v3 project to v4.  On the MSM side it's using Directory Id="MergeRedirectFolder" as the root.  On the MSI side it was converted to StandardDirectory Id="ProgramFilesFolder".  It builds successfully 32bit.  When I switch to 64bit I get the error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	WIX0204	ICE80: This 64BitComponent 
componentX uses 32BitDirectory MergeRedirectFolder.GUID	TestApp	C:\GitHub\TestApp\Installer\TestApp\wix.exe	1	
 
I looked at the MSI in Orca and WiX incorrectly authore the directory as ProgramFilesFolder instead of ProgramFiles64Folder.  Fixing this in ORCA fixes the ICE80 error.

Additionally, in my testing I found that I could resolve this by changing the StandardDirectory Id to ProgramFiles64Folder  or ProgramFiles6432Folder.  Setting it to ProgramFiles64Folder made it look like what I did in ORCA.  Setting it to ProgramFiles32Folder authored ProgramFiles6432Folder a child of ProgramFiles64Folder with a value of '.'.   I thought that was kinda strange but wanted to include this as part of the big picture deep dive.

* Describe the behavior you expected and how it differed from the actual behavior.

The MSI should build correcly and pass validation when using StandardDirectory Id="ProgramFilesFolder".  This is a killer feature that makes switching from 32bit to 64 bit MSI easy.   Actually, almost too easy I fear.

**Comment by robmen** [comment]
For better or worse (mostly worse), Windows Installer defines `ProgramFilesFolder` as always the 32-bit "Program Files". Similarly, `ProgramFiles64Folder` is always 64-bit "Program Files" and is not valid in 32-bit packages. As you found, WiX v4 adds a "syntatic sugar" called `ProgramFiles6432Folder` that will switch based on the build target platform.

**Comment by chrpai** [comment]
So is this a HeatWave issue?  Should it have converted Directory Id="ProgramFilesFolder" to StandardDirectory="ProgramFiles6432Folder"  instead of StandardDirectory="ProgramFilesFolder"?

**Comment by rseanhall** [comment]
No, Heatwave relies on `wix.exe convert` to convert source files. Given that the architecture can be provided on the command line, I don't think there's enough information available to the converter to make that kind of change.

**Comment by robmen** [comment]
Conversion has to assume that if `ProgramFilesFolder` was used in the code then the goal was to install some content into the 32-bit location. That's a very realistic scenario.

At the same time, conversion isn't smart enough to know that 64-bit Components are being installed into 32-bit locations to provide an early warning. And with Merge Modules, the whole build process can't know until _after_ the MSI is built.

**Comment by chrpai** [comment]
I guess I'm conflicted between making it easy to build 64 and not making it to easy.  Your explanation is fine.

In my new project templates I'm going to default it to 6432 so that I can have an FAQ that says "How do I build 32bit and 64bit" and my answer is simple: Just change which platform your building.  No other code changes to .wxs files need to occur.

It'd been nice for that to be the behavior for converted projects as well but no biggie.  It's only 1 attribute to fix and it does sync up with my fear or making it too easy.

**Comment by robmen** [comment]
`ProgramFiles6432Folder` is a great thing to use in templates. It was added in WiX v4 because, most of the time, that is exactly what you want.

In WiX v3, getting the same behavior was annoying because it required a bit of preprocessor hackery.

**Comment by chrpai** [comment]
Would it be possible for WIX0204  to output a suggestion to use ProgramFiles6432Folder?

**Comment by robmen** [comment]
That error message comes from the `ICE` written by Microsoft. Also, adding `ProgramFiles6432Folder` isn't always the right answer to solve that problem.
