### ISSUE TITLE
Some issues with Wix3 docs (Page Not Found: /docs/docs/v3/)

### ISSUE THREAD

**Issue by edyoung** [wixtoolset/issues#7006]
### WiX Toolset Page URL

https://wixtoolset.org/docs/docs/v3/

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/wix3/

### Additional information (optional)

The page https://wixtoolset.org/docs/wix3/ says 'Version: v4.0" and has a link "[The WiX v3 documentation is available here.](https://wixtoolset.org/docs/docs/v3/) which is 404.

Presumably some side-effect of the wix4 doc updates.

**Comment by robmen** [comment]
The 404 is fixed, but we should look into if it is possible to remove the `Version: 4.0` label.

**Comment by barnson** [comment]
Seems that we'd have to take the `wix3` page out of `docs/` and add it as some kind of sidebar item: https://docusaurus.io/docs/sidebar/items
