### ISSUE TITLE
Page Not Found: /releases/v3-14-0-6526/

### ISSUE THREAD

**Issue by lyrilith** [wixtoolset/issues#7012]
### WiX Toolset Page URL

https://wixtoolset.org/releases/v3-14-0-6526/

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/wix3/#development-builds

### Additional information (optional)

Also, although this might be by design, the links to the 3.14.0.x pre-release builds posted on Twitter by @wixtoolset all redirect to the Wix v4 release notes instead.

**Comment by robmen** [comment]
FYI: The links posted to Twitter were a glitch in the website update. None of those were new releases so we did point them to the new release that triggered the glitch v4-preview.1. The broken link from `#development-tools` as a plain old bug fixed above. Refresh the web page and link should work again.
