### ISSUE TITLE
Heatwave doesn't convert xml namespaces of xslt files used in HeatDirectory

### ISSUE THREAD

**Issue by MBroholmA** [wixtoolset/issues#7019]
* Which version of WiX are you building with?
4.0 preview 1

* Which version of Visual Studio are you building with (if any)?
2022 17.3.6

* Describe the problem and the steps to reproduce it.
Heatwave doesn't convert the xml namespaces of the transform file used in HeatDirectory

The .wixproj have this segment at the end:
```
  <Target Name="HarvestFiles" AfterTargets="BeforeBuild">
    <HeatDirectory OutputFile="_MainFiles.wxs" DirectoryRefId="INSTALLDIR" ComponentGroupName="MainFiles" SuppressCom="true" Directory="$(MainFilesPath)" RunAsSeparateProcess="True" NoLogo="true" SuppressFragments="false" SuppressRegistry="true" SuppressRootDirectory="true" AutoGenerateGuids="true" GenerateGuidsNow="false" ToolPath="$(WixToolPath)" Transforms="HarvestMainFiles.xsl" />
  </Target>
```

The HarvestMainFiles.xsl file starts with a list of Wix 3 namespaces:
```
<xsl:stylesheet
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:wix="http://schemas.microsoft.com/wix/2006/wi"
xmlns="http://schemas.microsoft.com/wix/2006/wi"
xmlns:util="http://schemas.microsoft.com/wix/UtilExtension"

version="1.0" 
exclude-result-prefixes="xsl wix util"
>
```
These namespaces are not changed by Heatwave

* Describe the behavior you expected and how it differed from the actual behavior.
Heatwave should change them to their V4 counterparts:

```
<xsl:stylesheet
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:wix="http://wixtoolset.org/schemas/v4/wxs"
xmlns="http://wixtoolset.org/schemas/v4/wxs"
xmlns:util="http://wixtoolset.org/schemas/v4/wxs/util"

version="1.0" 
exclude-result-prefixes="xsl wix util"
>
```

**Comment by robmen** [comment]
Hey, @FireGiantHelp, this looks like a HeatWave conversion-specific issue for you to consider.
