### ISSUE TITLE
Heatwave: Build variables not available in Pre and Post-Build events

### ISSUE THREAD

**Issue by MBroholmA** [wixtoolset/issues#7020]
* Which version of WiX are you building with?
4.0 preview 1

* Which version of Visual Studio are you building with (if any)?
2022 17.3.6

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
4.0 preview 1

* Describe the problem and the steps to reproduce it.

Build variables not available in Pre and Post-Build events

1. Create a new blank V3 project
2. Add a post-build event:
`echo Test $(TargetPath)
3. Build and test that it outputs the path of the .msi file in the build log
4. Convert the project to V4 using Heatwave
5. Build and check the build log. It only outputs "Test " now

* Describe the behavior you expected and how it differed from the actual behavior.
I expect the same output as in V3. None of the build variables seems to be available

This simple example gets converted to a V4 SDK-style project. I don't know how to fix this for SDK projects, but for my real project this was fixed by moving the line <Import Project="Sdk.targets" Sdk="WixToolset.Sdk" Version="4.0.0-preview.1" /> up above the <PostBuildEvent> tag
 
EDIT: After testing these flows I found out that it's the same problem in a new V4 project

**Comment by robmen** [comment]
Can you link to a repository with a repo or (if sufficient) attach a .wixproj that demonstrates the problem(s)?

**Comment by MBroholmA** [comment]
I can make a repo to provoke the issue when upgrading from V3, but the problem is also present in a new V4 project.

1. Create a new project MSI Package (WiX V4). 
2. Insert "echo Test $(TargetPath)" as a post- or pre-build event

The $(TargetPath) is blank in the build log. This goes for all the build variables I tested

This might be a separate issue from the upgrade scenario, but the symptoms are the same.

**Comment by robmen** [comment]
Hey, @FireGiantHelp, this looks like a HeatWave conversion-specific issue for you to consider.
