### ISSUE TITLE
wix v4 - WIX6802: There must be at least one PrereqPackage when using the ManagedBootstrapperApplicationHost

### ISSUE THREAD

**Issue by pwallner** [wixtoolset/issues#7026]
## Bugs
* Which version of WiX are you building with?
4.0.0-preview.1

* Which version of Visual Studio are you building with (if any)?
VS 2022 (17.4.1)
VS 2019 (16.11.21)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
none

* Which version of .NET are you building with?
.NET Framework 4.7.2

* Describe the problem and the steps to reproduce it.
Upgrade from v3 to v4 adds line `<bal:WixManagedBootstrapperApplicationHost />` and package is not building
Bundle.wxs:
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">
    <Bundle DisableModify="no" Compressed="yes" DisableRemove="yes" Name="$(var.SuitName)" IconSourceFile="black.ico" Version="$(var.ProductVersion)" Manufacturer="Test" UpgradeCode="xxxxxxx-xxx-...">
    <BootstrapperApplication>
      <Payload SourceFile="..\..\........\BootstrapperCore.config" />
      <Payload SourceFile="..\..\.........\CustomBootstrapperApplication.dll" />
      <Payload SourceFile="..\..\..........\Microsoft.Deployment.WindowsInstaller.dll" />
      <!--language DE-->
      <Payload Name="de-DE\CustomBootstrapperApplication.resources.dll" SourceFile="..\..\..........\de-DE\CustomBootstrapperApplication.resources.dll" />

<bal:WixManagedBootstrapperApplicationHost />
</BootstrapperApplication>
...
```
Compile-Error:
```
wix.exe : error WIX6802: There must be at least one PrereqPackage when using the ManagedBootstrapperApplicationHost.
```
* Describe the behavior you expected and how it differed from the actual behavior.
working setup file with Bootstrapper CustomUI like in v3

**Comment by pwallner** [comment]
It doesn't compile, any hints how to compile?

**Comment by Falkesand** [comment]
@pwallner Check this link, maybe it can help you out. 
 https://stackoverflow.com/questions/37284941/wix-toolset-prerequisites-check-for-net-framework

**Comment by pwallner** [comment]
@Falkesand the problem I think isn't missing framework, because v3 is compiling and Setup.exe is working, only v4 is aborting compiling with the error in first post

**Comment by pwallner** [comment]
@rseanhall when I add like in your 2 years old examples
'''
<ExePackage DetectCondition="none" SourceFile="c:\windows\system32\kernel32.dll" bal:PrereqPackage="yes" />
'''
But with uninstallargs (missing in your old examples), it's working...
v3 it was not necessary...

**Comment by barnson** [comment]
This is a change of behavior in WiX v4.

**Comment by rseanhall** [comment]
v3 required the WixVariable `WixMbaPrereqPackageId`, but it was possible to specify the variable without having a package without that id. That loophole has been fixed. I will update the error message to say that at least one package must have `bal:PrereqPackage="yes"`

**Comment by robmen** [comment]
Additional context in the error message is great.

Would it be possible for the converter to look at the `WixMbaPrereqPackageId` and add the `bal:PrereqPacakage` attribute if everything is in the same .wxs file? I've seen a lot of single-file bundle .wxs files, so this might work out pretty often.

**Comment by rseanhall** [comment]
I can try. Are we doing something like that already?

**Comment by robmen** [comment]
Not exactly. Most of the converter uses a visitor. But after the visitor is complete, there are a couple of passes that do global namespace manipulations. This would be the first global operation not related to namespaces.
