### ISSUE TITLE
Problems with link to wix schema and links from wix schema

### ISSUE THREAD

**Issue by henkehedstrom** [wixtoolset/issues#7030]
### WiX Toolset Page URL

https://wixtoolset.org/docs/v3/xsd/include/

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/v3/xsd/wix/

### Additional information (optional)

The links on the wix schema page do not work. The include link takes you to a page not found, and the Wix link will just redirect you to the wix schema which you already are on. 

Almost every link that I have tried that should redirect you to the wix schema page actually redirects you to the wix element instead. Those links are not broken but I guess that they should link to wix schema. 

Example: Click on wix schema in https://wixtoolset.org/docs/v3/xsd/wix/chain/ and you will go to Wix element instead. From the wix element you can go to wix schema.

Great work on fixing the links @barnson :) 354 manually changes sounds fun! Hopefully this will be an easier fix.

**Comment by barnson** [comment]
Fixed in https://github.com/wixtoolset/web/pull/117.
