### ISSUE TITLE
Test hanging after VS 17.4 update on Windows on Arm

### ISSUE THREAD

**Issue by pbo-linaro** [wixtoolset/issues#7036]
Hi, after updating our machines to latest Visual Studio (17.4),

we started to notice failure in wix4 testing in our nightly CI.
I could reproduce that on my personal machine.
A test seems to hang, and no error message is returned.

Here is a log with this hang happening: [log](https://gitlab.com/Linaro/windowsonarm/nightly/-/jobs/3306764919)

```
Starting test execution, please wait...
A total of 3 test files matched the specified pattern.
[xUnit.net 00:00:02.22]     DutilTests.FileUtil.FileUtilTest [SKIP]
  Skipped DutilTests.FileUtil.FileUtilTest [1 ms]
[xUnit.net 00:00:02.38]     DutilTests.MonUtil.MonUtilTest [SKIP]
  Skipped DutilTests.MonUtil.MonUtilTest [1 ms]
---> HANG HAPPENS HERE
```

After looking at commit history on this date (11th of november), there does not seems to be a significant change on wix side. But maybe a change is responsible for this.

Is there any way to investigate that deeper?
How could we deactivate those 3 tests (on our side) to skip the issue for now?

Thanks!

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

develop branch

* Which version of Visual Studio are you building with (if any)?

17.4.1

* Which version of .NET are you building with?

6.0.401

* Describe the problem and the steps to reproduce it.

When running build and test, a test is hanging.

* Describe the behavior you expected and how it differed from the actual behavior.

Complete build and tests.

**Comment by robmen** [comment]
You'll want to attach to the `dotnet test` process and see what is causing the hang. You might also go back to the last known good `wix4` commit that you did and see if tests pass then. If the old commit does pass, then we know the bug is in WiX. Otherwise, the break is caused by the VS update.

**Comment by rseanhall** [comment]
There are several [command line options](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-test) for `dotnet test` that should help without using a debugger such as `--blame-hang` and `-v normal`. This would be used inside of src/libs/libs.cmd.

**Comment by pbo-linaro** [comment]
Thanks, for now I just disabled those specific unit tests (DUtilUnitTest.dll) waiting to investigate more on it.
I'll reopen that issue if I have more information.

Thanks!
