### ISSUE TITLE
Page Not Found: //documentation/manual/v3/wixui/wixui_localization.html

### ISSUE THREAD

**Issue by OndrejUzovic** [wixtoolset/issues#7037]
### WiX Toolset Page URL

https://wixtoolset.org//documentation/manual/v3/wixui/wixui_localization.html

### Page URL that linked to WiX Toolset

https://www.google.com/

**Comment by robmen** [comment]
I'm pretty sure that Google does not have a link to the WiX toolset website on their homepage. 😄
