### ISSUE TITLE
Signing seems more difficult than it should be

### ISSUE THREAD

**Issue by zdavidsen** [wixtoolset/issues#7038]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> I would love it if the WiX v4 signing targets would conditionally import custom signing targets, e.g. `$(MSBuidProjectDir)\$(MSBuildProjectName).Signing.targets` or something. (maybe that's the default, but it can be overridden with an msbuild property?)

* Describe how you're accomplishing the feature today (if possible).

> Right now, custom signing targets _must_ be imported via the `CustomAfterWixTargets`, because that's the user-definable area after the default signing targets are imported

* Describe what you'd like the new feature to do.

> Oops, I already did this in step 1. Oh well

**Comment by robmen** [comment]
That's a good point. The design from v3 is more annoying to use in Sdk-style projects. I'm not sure defining another `targets` file for signing is the best solution, but it might be. This will be something to noodle on and see if we can improve for `-rc.1`.

**Comment by zdavidsen** [comment]
Another alternative that I've done with some of my packages is to define
empty targets in the props file instead, so they're easier to override.

**Comment by pwallner** [comment]
@zdavidsen howto solve with CustomAfterWixTargets?

**Comment by zdavidsen** [comment]
You can put your custom targets in another file, say "Custom.targets", and then set the `CustomAfterWixTargets` property to the path of that custom file.  Then WiX will automatically import that file after everything else is defined.

**Comment by pwallner** [comment]
Could you please provide a sample?

I used in v3 signtool with my pfx file:


  <Target Name="SignBundle" DependsOnTargets="FindSignTool">
    <Exec Command="&quot;$(SignToolPath)signtool.exe&quot; sign /d &quot;MyApp Setup&quot;  /fd SHA256 /td SHA256 /a /f &quot;MyApp Code Certificate.pfx&quot; /p CertPassword /tr http://timestamp.digicert.com /a &quot;@(SignBundle)&quot;" />
  </Target>

**Comment by zdavidsen** [comment]
@pwallner Honestly, I'd probably just wait till RC1, since this issue should be fixed in that version.
If you really want it to be fixed before then, you could do something like the following

In your main file:
#### Project.wixproj
```xml
<Project Sdk="WixToolset.Sdk/4.0.0-preview.1">
  <PropertyGroup>
    <CustomAfterWixTargets>$(MSBuildThisFileDirectory)CustomSigning.targets</CustomAfterWixTargets>
  </PropertyGroup>
</Project>
```

In another file in the same directory as your main wixproj:
#### CustomSigning.targets
```xml
<Project>
  <Target Name="SignMsi">
    <Exec Command="signtool.exe sign /d &quot;$(ProductName)&quot; /debug /fd sha256 /n &quot;$(SigningCert)&quot; /tr $(TimestampServer) &quot;%(SignMsi.FullPath)&quot;" />
  </Target>
</Project>
```

**Comment by robmen** [comment]
You could also use the [alternative verbose Sdk import syntax](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022#use-the-import-element-anywhere-in-your-project).

```xml
<Project>
  <Import Sdk="WixToolset.Sdk" Version="4.0.0-preview.1" Project="Sdk.props" />


  <Import Sdk="WixToolset.Sdk" Version="4.0.0-preview.1" Project="Sdk.targets" />
  <Target Name="SignMsi">
    <Exec Command="signtool.exe sign ..." />
  </Target>
<Project>
```

Again, this won't be necessary in `-rc.1`.
