### ISSUE TITLE
Bootstrapper doesn't pass cli arguments with space to msiexec

### ISSUE THREAD

**Issue by davidgiga1993** [wixtoolset/issues#7040]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.11.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

>Windows 11 22H2

* Describe the problem and the steps to reproduce it.

1. Create a wix `.exe` bootstrapper installation
2. Try to pass a single cli argument which contains a space, for example:
```
installer-1.8.0.exe INR="C:\test a"
```

* Describe the behavior you expected and how it differed from the actual behavior.

The behavior should be the same as if `msiexec.exe /i main.msi  INR="C:\test a"` is called.

However, the bootstrapper doesn't seem to pass the arguments correctly to msiexec, causing it to hang/open the help dialog:
![image](https://user-images.githubusercontent.com/3924958/203016531-862dd6d0-9c90-4e88-a2ca-c6718cadb330.png)

Running the msiexec command manually does work as expected:
```
msiexec.exe /i main.msi INR="C:\test a"
```

## Additional information:
These are the commandline arguments passed to msiexec by the bootstrapper:
![image](https://user-images.githubusercontent.com/3924958/203016898-e2ad0660-9d08-45c0-a185-ae0cdae637dc.png)

As you can see the quote of the path has been moved around the entire argument, which explains the observed behavior.

Expected: `INR="C:\test a"`, observed: `"INR=C:\test a"`

## Workaround:
Use double quotes + quotes around the entire argument:
```
installer-1.8.0.exe "INR=""C:\test a"""
```

**Comment by barnson** [comment]
What does your `MsiPackage` authoring look like?

**Comment by davidgiga1993** [comment]
Think this can be closed, the exe wrapper is generated by ´jpackage`, I was initially under the assumption it's done by wix.

https://github.com/openjdk/jdk/blob/739769c8fc4b496f08a92225a12d07414537b6c0/src/jdk.jpackage/windows/native/msiwrapper/MsiWrapper.cpp#L73
