### ISSUE TITLE
wix v4 - Bundle ignores "AfterBuild" and "BeforeBuild" target

### ISSUE THREAD

**Issue by pwallner** [wixtoolset/issues#7048]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
4.0.0-preview.1

* Which version of Visual Studio are you building with (if any)?
VS 2022 (17.4.1)
VS 2019 (16.11.21)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
none

* Which version of .NET are you building with?
not relevant for bundle

* Describe the problem and the steps to reproduce it.

I want to do get the version with "BeforeBuild" like in v3 (was working):
```
<Target Name="BeforeBuild">
    <GetAssemblyIdentity AssemblyFiles="..\..\\mydll.dll">
      <Output TaskParameter="Assemblies" ItemName="AssemblyVersion" />
    </GetAssemblyIdentity>
    <PropertyGroup>
      <DefineConstants>BuildVersion=%(AssemblyVersion.Version)</DefineConstants>
    </PropertyGroup>
  </Target>
```
and in `Bundle.wxs`:
```
...
    <Bundle ... Version="$(var.BuildVersion)" ... >
...
```
but "BeforeBuild" and "AfterBuild" are **completly ignored** and I get the error
```
error WIX0150: Undefined preprocessor variable '$(var.BuildVersion)'.
```

* Describe the behavior you expected and how it differed from the actual behavior.
to be able to use "BeforeBuild" and "AfterBuild" like in v3

**Comment by robmen** [comment]
Did you use HeatWave to convert the v3 .wixproj to a v4 .wixproj? Or did you convert the project manually? Or is this a brand new v4 .wixproj?

**Comment by pwallner** [comment]
Converted with heatwave from v3 to v4. I can try with a new v4 if you want

**Comment by zdavidsen** [comment]
Pretty sure this is the same kind of problem as in https://github.com/wixtoolset/issues/issues/7038...
And since that's embedded in the common targets, I don't think it's changing anytime soon.

For the moment, I would suggest using BeforeTargets or AfterTargets instead of overriding the targets completely, e.g.
```xml
<Target Name="CustomBeforeBuild" BeforeTargets="BeforeBuild">
  <GetAssemblyIdentity AssemblyFiles="..\..\\mydll.dll">
    <Output TaskParameter="Assemblies" ItemName="AssemblyVersion" />
  </GetAssemblyIdentity>
  <PropertyGroup>
    <DefineConstants>BuildVersion=%(AssemblyVersion.Version)</DefineConstants>
  </PropertyGroup>
</Target>

**Comment by pwallner** [comment]
This works. Thank you

**Comment by robmen** [comment]
The converter in HeatWave should have updated your .wixproj. You might [open an issue with FireGiant](https://github.com/firegiant/HeatWaveSupport/issues/new?assignees=&labels=triage&template=bug.yml). I would recommend including your .wixproj for them to investigate.

**Comment by zieglerjm** [comment]
What is the replacement for <HeatDirectory .. />?
