### ISSUE TITLE
v4: Feature attribute "Absent" not accepted

### ISSUE THREAD

**Issue by dorssel** [wixtoolset/issues#7051]
If this issue is a bug:

* Which version of WiX are you building with?

4.0.0-preview.1

* Which version of Visual Studio are you building with (if any)?

N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

N/A

* Which version of .NET are you building with?

.NET 7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

N/A

* Describe the problem and the steps to reproduce it.

```
<Feature Absent="allow" ...>
```

Gives error:

```
error WIX0004: The Feature element contains an unexpected attribute 'Absent'.
```

* Describe the behavior you expected and how it differed from the actual behavior.

Works fine with v3. v4 XML schema suggests this is still a valid attribute.

**Comment by robmen** [comment]
This is fixed in -rc.1. The [documentation](https://wixtoolset.org/docs/reference/schema/wxs/feature/) was already updated.
