### ISSUE TITLE
WiX v4 VS Intellisense  Anamoly

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7056]
If this issue is a bug:

* Which version of WiX are you building with?

WiX v4 Preview 1

* Which version of Visual Studio are you building with (if any)?

VS 2022 Community 17.4.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Heatwave 0.9.0.5

In v3 schema an empty doesn't show any green info?/warning? tildes.  In v4 schema I see two:

The global element 'xmlns="http://wixtoolset.org/schemas/v4/wxs" wxs:PatchFamilyGroupRef' has already been declared.

The global element 'xmlns="http://wixtoolset.org/schemas/v4/wxs" wxs:Wix' has already been declared.

 
This is very minor and doesn't block functionality but I know you guys are perfectionists and I thought I'd mention it to you.

<img width="539" alt="diff" src="https://user-images.githubusercontent.com/43178814/204318979-7878da97-5865-4537-bb7b-f9b10c9913b9.png">

**Comment by robmen** [comment]
This almost always happens when there are multiple copies of "wix.xsd" in `C:\Program Files\Microsoft Visual Studio\2022\Community\Xml\Schemas`. The files don't have to be named "wix.xsd" but usually are, so you will likely find duplicates searching for `*wix.xsd`.

**Comment by chrpai** [comment]
I see a fg4_wix.xsd and a wix4.xsd. I know it's not my installer doing it cause I lay down in C:\Program Files (x86)\ISWIX LLC\IsWiX\Schemas and rely on what votive/heatwave install for me in Visual Studio.

I'll do more digging on a clean VM and either report findings or close the issue.

**Comment by robmen** [comment]
The `wix4.xsd` should no longer be present. Make sure you have the latest Votive. Older versions of Votive used to install very out-of-date `wix4.xsd`. Also, sometimes VS is not great about cleaning up properly, so after uninstalling Votive, delete the non `fg4_` WiX XSDs, and they should stay gone.

**Comment by chrpai** [comment]
Retested on a clean machine and everything is fine.
