### ISSUE TITLE
wix v4 - Custom bootstrapper Command.CommandLine always empty

### ISSUE THREAD

**Issue by pwallner** [wixtoolset/issues#7057]
### Bugs
* Which version of WiX are you building with?
4.0.0-preview.1

* Which version of Visual Studio are you building with (if any)?
VS 2022 (17.4.1)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
none

* Which version of .NET are you building with?
.NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10, Version 22H2

* Describe the problem and the steps to reproduce it.

CommandLine is always empty
```
namespace WPFMBA
{
    using System;
    using System.Windows.Forms;
    using System.Windows.Threading;
    using WixToolset.Dtf.WindowsInstaller;
    using WixToolset.Mba.Core;
    public class WPFBA : BootstrapperApplication
    {
        public WPFBA(IEngine engine, IBootstrapperCommand command)
            : base(engine)
        {
            MyCommand = command;
        }

        public static Dispatcher BADispatcher { get; private set; }
        public IBootstrapperCommand MyCommand { get; private set; }

        protected override void Run()
        {
   
                var tempcommandlineargs = MyCommand.CommandLine;
                MessageBox.Show("Argumente (neu): " + tempcommandlineargs);
....
```

* Describe the behavior you expected and how it differed from the actual behavior.

Receiving commandlineargs is what I expected

* Workaround

Using `Environment.GetCommandLineArgs()`

**Comment by rseanhall** [comment]
Please provide an example of command line arguments that are missing. The Burn engine removes arguments such as `/quiet` from Command.CommandLine because they are provided in other properties of Command (Display in the case of `/quiet`). We have multiple automated tests that rely on this functionality and they are passing so this doesn't appear to be a general problem.

**Comment by pwallner** [comment]
@rseanhall You are right, it was not clear for me, that Burn engine removes argumets such `/quiet`. Tested with `/foo` and this is the only command which is visible beside my other commands like `/quiet` or `/uninstall` by  `Command.CommandLine`.
