### ISSUE TITLE
Options button, install and close buttons are getting truncated when text scaling is applied.

### ISSUE THREAD

**Issue by msftedad** [wixtoolset/issues#7064]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wix.Corext.3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

>Not used

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

>Not used

* Which version of .NET are you building with?

>4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows 11)

* Describe the problem and the steps to reproduce it.

> Description: Options button, install and close buttons are getting truncated when text scaling is applied.
Steps to reproduce:
1.Connect to virtual machine 
2. Open File manager and select ODJConnectorBootstrapper and open it
3. Intune Connector for Active Directory dialogue will be opened 
4.Observe Options, install and close buttons whether they visible properly or not

* Describe the behavior you expected and how it differed from the actual behavior.

>Actual results: Options button, install and close buttons are getting truncated when text scaling is applied. v\Visually impaired users will not be able to see the controls if there is truncation.
Expected results: Every button and link should be visible properly when text scaling is applied.

Additional Notes: Similar issue Observed at Setup options->okay and cancel buttons, installed successfully dialogue ->configure now and close buttons and Enrollment dialogue ->privacy statement link

Attachments:
![configure now,close buttons  got truncated](https://user-images.githubusercontent.com/93735775/205627054-a31d5988-a646-4db5-b228-f6b19b0cc1a6.png)
![okay cancel buttons are truncated](https://user-images.githubusercontent.com/93735775/205627063-2372e573-fe43-4b89-915c-a27fbc71a5a0.png)
![options ,insatll,close buttons are getting truncated](https://user-images.githubusercontent.com/93735775/205627079-05138999-2fcc-46d5-bb99-a47db5ec46fe.png)
![privacy statement link getting truncated](https://user-images.githubusercontent.com/93735775/205627091-5034b7fd-dc0e-41a2-9476-b3d516cee327.png)

**Comment by barnson** [comment]
ThmUtil v4 adds support for DPI scaling.
