### ISSUE TITLE
Label of the checkbox is not visible clearly in High contrast 'Black' mode.

### ISSUE THREAD

**Issue by msftedad** [wixtoolset/issues#7065]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wix.Corext.3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

>Not used

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

>Not used

* Which version of .NET are you building with?

>4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows 11)

* Describe the problem and the steps to reproduce it.

> Description: People with low vision will not be able to see the label of the checkbox.
Steps to reproduce:
1.Connect to virtual machine 
2. Open File manager and select ODJConnectorBootstrapper and open it
3. Intune Connector for Active Directory dialogue will be opened 
4.Observe the label of the checkbox whether its visible clearly or not.

* Describe the behavior you expected and how it differed from the actual behavior.

>Actual results: Options button, install and close buttons are getting truncated when text scaling is applied.
Expected results: Label of the checkbox should be visible clearly in High contrast Black mode.

Additional Notes: In High contrast white mode it is visible clearly.

Attachments:
![checkbox label is not visible in HC-Aquatic mode](https://user-images.githubusercontent.com/93735775/205629226-bdd0a5ed-67f7-4ea7-8ba9-8a3c21325673.png)

![high contrast white mode](https://user-images.githubusercontent.com/93735775/205629244-b1de78a2-6fcd-4acd-af36-59b661b10185.png)

**Comment by barnson** [comment]
ThmUtil v4 adds support for system colors.
