### ISSUE TITLE
The Name of the 'privacy statement' link is not announced by the narrator.

### ISSUE THREAD

**Issue by msftedad** [wixtoolset/issues#7066]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> Wix.Corext.3.11.1.2318

* Which version of Visual Studio are you building with (if any)?

>Not used

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

>Not used

* Which version of .NET are you building with?

>4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows 11)
Application Environment:
OS Edition: Windows Server 2016 Datacenter
OS version: 1607
OS Build: 14393.5192
AT: Narrator

* Describe the problem and the steps to reproduce it.

> Description: Screen reader users will face difficulty if narrator does not announce the name of the link.
Steps to reproduce:
1. Connect to virtual machine 
2. Open File manager and select ODJConnectorBootstrapper and open it
3. Intune Connector for Active Directory dialogue will be opened 
4. Navigate till check box and check it
5. Navigate to install button and invoke it 
6. Navigate t]ill configure now button and invoke it
7. Navigate till privacy statement link and observe narrator announcement

* Describe the behavior you expected and how it differed from the actual behavior.

>Actual results: Narrator not announcing descriptively for 'privacy statement' link,
It is just announcing as Hyperlink, space.
Expected results: Narrator should announce the name of the link properly,
it should announce as 'privacy statement, link '.

Attachments:
![link name is not descriptive enough](https://user-images.githubusercontent.com/93735775/205631392-25ba1a09-c1ce-4d32-894d-b213cc758585.png)

**Comment by barnson** [comment]
That's not a WiX window.
