### ISSUE TITLE
Handle restart error codes from MsiEndTransaction in Burn

### ISSUE THREAD

**Issue by rseanhall** [wixtoolset/issues#7079]
**Encountered at:** https://github.com/wixtoolset/wix4/commit/fb0a8b74b598331dcf037d97a3adf89f5fe5ba92

**Detail:**

@nirbar has logs showing that MsiEndTransaction may return ERROR_SUCCESS_REBOOT_REQUIRED. The engine handles this return code as an error.

**Comment by rseanhall** [comment]
@nirbar Please comment here so I can assign it to you.

**Comment by nirbar** [comment]
Hi @rseanhall , please assign to me

**Comment by nirbar** [comment]
@rseanhall Do I need to do anything to merge the PR and close the issue?
