### ISSUE TITLE
Signing a bundle corrupts the bundle

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#7085]
**Encountered at:** wixtoolset/wix4@b91ef859

**Detail:**

Signing a bundle will create a corrupted bundle that hits the assert on `src\burn\engine\section.cpp(295)`:

> An attached container should either be present or completely absent from the bundle. Found a case where the attached container is partially present which is wrong.

**Comment by rseanhall** [comment]
One thing that changed in v4 is the splash screen information is written to an RCDATA resource - https://github.com/wixtoolset/wix4/pull/14/commits/a8e0b3ed82d7b157e25c946069bc8b26c7657b40. My guess would be that the new resource is breaking an assumption in the insignia code.

**Comment by robmen** [comment]
Thank goodness, this turned out to be a subtle mistake in the signing targets.

**Comment by mtissington** [comment]
This is happening in 4.0.1 - I can create a non signed bundle and it works, as soon as I sign it I get the issue.
[https://github.com/orgs/wixtoolset/discussions/7703](https://github.com/orgs/wixtoolset/discussions/7703)
