### ISSUE TITLE
Failing to get update feed should not block bundle progress

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#7090]
**Encountered at:** wixtoolset/wix4@f41e1ec

**Detail:**

If there is any issue getting the update feed of a bundle using `wixstdba`, the bundle fails with a file not found error. Notifying of newer versions is useful but not vital and should not block the install.

**Comment by barnson** [comment]
Only happens in full UI...

**Comment by barnson** [comment]
Right, because update detection is skipped except in full UI because with no UI, there's no way to prompt the user to consider an update. I knew that, what with implementing it that way and clearly I'm not going to disagree with myself.

**Comment by barnson** [comment]
For triage: Should WixStdBA plan an update in less-than-full UI?

**Comment by barnson** [comment]
No, it should require opt-in but that opt-in might be an authored setting or a command-line switch. Leaving the runtime test for such an eventuality.

**Comment by barnson** [comment]
Fixed in https://github.com/wixtoolset/wix4/pull/307.
