### ISSUE TITLE
Wix toolkit version 4 cannot be installed on Windows XP SP3

### ISSUE THREAD

**Issue by hulinning2** [wixtoolset/issues#7093]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

> Wix toolkit version 4 cannot be installed on Windows XP since Windows XP SP3 only support Installer Service version 4.5

* Currently, I use Visual Studio 2010 to create the installer or Wix toolkit version 3.x.x only

> Can Wix tool kit support older version of Windows Installer Service version 4.5 for Windows XP?

* It would be nice to be able to specify the version of Windows Installer Service

**Comment by robmen** [comment]
You can. Set the [`Package` element's `InstallerVersion` attribute](https://wixtoolset.org/docs/reference/schema/wxs/package/#attributes) to the version of the Windows Installer you want.
