### ISSUE TITLE
Heatwave - Requires legacy Windows SDK

### ISSUE THREAD

**Issue by rhuijben** [wixtoolset/issues#7109]
The Heatwave Visual Studio extension (v4 rc 1) has a dependency on an older version of the Windows SDK.

If I use WinGet to keep my packages up to date this version of the Windows SDK is removed and upgraded to a newer version, but then installing Heatwave makes Visual Studio install the old version again.

Can this dependency be updated to something like 'some Windows SDK' version instead of a hardcoded version?

I have most of the C# and most of the C++ workloads installed, so I wouldn't have expected any missing components.

**Comment by robmen** [comment]
FireGiant tracks HeatWave issues on the [HeatWaveSupport repo](https://github.com/firegiant/HeatWaveSupport). Best to open an issue there to start the conversation.

I did take a quick look, and it appeared that HeatWave only requires `Microsoft.VisualStudio.Component.CoreEditor` so it may be another facet of Visual Studio that is faulting in the older Windows SDK.
