### ISSUE TITLE
Unresolved bind-time variable in WIX4

### ISSUE THREAD

**Issue by virzak** [wixtoolset/issues#7111]
Here is the code that used to work fine in v3, but breaks in v4

```
<?ifndef Version?>
<?define Version = "!(bind.fileVersion.My.dll)"?>
<?endif?>

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:dep="http://wixtoolset.org/schemas/v4/wxs/dependency">
  <Package Name="~$(var.TestGroupName) - $(var.PackageName)" Language="1033" Version="$(var.Version)" Manufacturer="Microsoft Corporation" UpgradeCode="$(var.UpgradeCode)" Compressed="yes" ProductCode="$(var.ProductCode)" Scope="perUser">
```

The error message is: WIX0298: Unresolved bind-time variable !(bind.fileVersion.My.dll). 

Any advice?

**Comment by robmen** [comment]
Well, first, you have no `File` elements. You need one with `Id='My.dll'`.

**Comment by barnson** [comment]
https://github.com/wixtoolset/wix4/blob/develop/src/wix/test/WixToolsetTest.CoreIntegration/TestData/BindVariables/PackageWithBindVariables.wxs shows it in use.

**Comment by virzak** [comment]
Thanks.

I had
```xml
<Component Id="NoviViewDll">
  <File Id="___var.MyApp.Wpf.TargetDir_My.dll" Source="$(var.MyApp.Wpf.TargetDir)My.dll" />
</Component>
```

When I cleaned up File Id, the error went away.
