### ISSUE TITLE
License file scroll bar is at the bottom at load time

### ISSUE THREAD

**Issue by virzak** [wixtoolset/issues#7113]
* Which version of WiX are you building with?

4.0.0-rc1

* Which version of Visual Studio are you building with (if any)?

Using command line

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

None

* Which version of .NET are you building with?

7.0.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Windows 11

* Describe the problem and the steps to reproduce it.

After upgrading to Version 4 the RTF license shows up at the bottom:

![image](https://user-images.githubusercontent.com/6209775/209243756-fdf074da-d932-4c29-a376-e4f565ba357f.png)

```xml
<bal:WixStandardBootstrapperApplication LicenseFile="../NoviView.Installer/res/My App (EULA).rtf" ShowVersion="yes" LogoFile="res/MyApp-64px.png" Theme="rtfLargeLicense" />
```

Happens with both `rtfLicense` and `rtfLargeLicense`

* Describe the behavior you expected and how it differed from the actual behavior.

This is how v3 looks like:
![image](https://user-images.githubusercontent.com/6209775/209244129-1803d098-282a-487b-b361-48cfcf12d1cd.png)

**Comment by mjanulaitis** [comment]
@barnson Do you have an ETA on this on?
