### ISSUE TITLE
IIS componets are not fully installed

### ISSUE THREAD

**Issue by danlyons-softek** [wixtoolset/issues#7120]
WiX Version: v4.0.0-rc.1
IIS Version: 10.0.20348.1
Windows Version: Server 2022 21H2 (Build 20348.524)

One of the installer projects I work on adds several things to IIS: a `WebAppPool`, a `WebApplication`, and several `WebVirtualDirs`.  Unfortunately, while the MSI built from my WiX4 branch runs to completion, it fails to set any of them up.

The only changes to the *.wxs files related to the IIS setup when converting to WiX 4 were the XML namespaces.  Based on the WiX 4 documentation, this seems expected, though.

I do notice some differences in the log output between a working installer from a branch that still uses WiX 3.11 and the branch that converts everything to WiX 4, however:

WiX 4 log:
```text
MSI (s) (A4:28) [11:58:36:105]: Doing action: Wix4ConfigureIIs_X64
Action ended 11:58:36: StartServices. Return value 1.
MSI (s) (A4:0C) [11:58:36:105]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI1CEB.tmp, Entrypoint: ConfigureIIs
Action start 11:58:36: Wix4ConfigureIIs_X64.
MSI (s) (A4:28) [11:58:36:121]: Doing action: RegisterUser
Action ended 11:58:36: Wix4ConfigureIIs_X64. Return value 1.
```

Wix 3.11 log:
```text
MSI (s) (10:1C) [18:08:17:710]: Doing action: ConfigureIIs
Action ended 18:08:17: StartServices. Return value 1.
MSI (s) (10:E0) [18:08:17:710]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI3AF2.tmp, Entrypoint: ConfigureIIs
MSI (s) (10!D4) [18:08:17:725]: PROPERTY CHANGE: Adding StartIIS7ConfigTransaction property. Its value is '**********'.
Action start 18:08:17: ConfigureIIs.
MSI (s) (10!D4) [18:08:17:725]: Doing action: StartIIS7ConfigTransaction
Action start 18:08:17: StartIIS7ConfigTransaction.
MSI (s) (10!D4) [18:08:17:725]: PROPERTY CHANGE: Adding RollbackIIS7ConfigTransaction property. Its value is '**********'.
MSI (s) (10!D4) [18:08:17:725]: Doing action: RollbackIIS7ConfigTransaction
Action ended 18:08:17: StartIIS7ConfigTransaction. Return value 1.
Action start 18:08:17: RollbackIIS7ConfigTransaction.
MSI (s) (10!D4) [18:08:17:725]: PROPERTY CHANGE: Adding CommitIIS7ConfigTransaction property. Its value is '**********'.
MSI (s) (10!D4) [18:08:17:725]: Doing action: CommitIIS7ConfigTransaction
Action ended 18:08:17: RollbackIIS7ConfigTransaction. Return value 1.
Action start 18:08:17: CommitIIS7ConfigTransaction.
MSI (s) (10!D4) [18:08:19:695]: PROPERTY CHANGE: Adding ConfigureIIs7Exec property. Its value is '**********'.
Action ended 18:08:17: CommitIIS7ConfigTransaction. Return value 1.
MSI (s) (10!D4) [18:08:19:695]: Doing action: ConfigureIIs7Exec
Action start 18:08:19: ConfigureIIs7Exec.
MSI (s) (10!D4) [18:08:19:695]: PROPERTY CHANGE: Adding WriteIIS7ConfigChanges property. Its value is '**********'.
Action ended 18:08:19: ConfigureIIs7Exec. Return value 1.
MSI (s) (10!D4) [18:08:19:695]: Doing action: WriteIIS7ConfigChanges
Action start 18:08:19: WriteIIS7ConfigChanges.
Action ended 18:08:19: WriteIIS7ConfigChanges. Return value 1.
MSI (s) (10:1C) [18:08:19:695]: Doing action: RegisterUser
Action ended 18:08:19: ConfigureIIs. Return value 1.
```

Attached is a zip containing both complete install logs in case there is anything further to be gleaned.
[server install logs.zip](https://github.com/wixtoolset/issues/files/10322089/server.install.logs.zip)

**Comment by danlyons-softek** [comment]
Curious about the rename from `ConfigureIIs` to `Wix4ConfigureIIs_X64`, I opened up both MSIs in Orca.  I noticed that a significant number of tables are now prefixed with Wix4, though their contents seem identical.

Skimming through some of the code in src/ext/iis/ca, one thing that caught my eye was [scasched.cpp, Lines 55-56](https://github.com/wixtoolset/wix4/blob/fad58e4d2bbd8e451cdb725325a5d760b4d1a684/src/ext/Iis/ca/scasched.cpp#L55-L56):

```cpp
LPCWSTR vcsVDirQuery = L"SELECT `Web_`, `VirtualDir`, `Component_`, `Alias`, `Directory_`, `DirProperties_`, `Application_` "
    L"FROM `IIsWebVirtualDir`";
```

While most of the query strings prefix their table names with Wix4, this one does not.  Additionally, none of the `WcaTableExists` calls later on in the file appear to use the Wix4 prefixes for table names.

Could this possibly be why IIS isn't being updated properly on install?

**Comment by chrpai** [comment]
Is this supposed to be fixed in rc2 build 14?  I created a GitHub PAT and added it to my package sources.  Updated my wixproj to WixToolset.Sdk/4.0.0-rc.2-build.14 and updated all of my PackageReferences to 4.0.0-rc.2-build.14.  The MSI built but I don't see anything IIS related in it when looking at it with Orca.

**Comment by rseanhall** [comment]
4.0.0-rc.2-build.14 should include https://github.com/wixtoolset/wix4/pull/321. Given that the MSI log given here had IIS custom actions running, you seem to be having a different issue or you're looking in the wrong place for IIS related things.
