### ISSUE TITLE
Dotnet Install of Wix v4 .NET Tool fails

### ISSUE THREAD

**Issue by excelsi** [wixtoolset/issues#7125]
The Dotnet Tool Install of Wix v4 fails for me with .Net SDK 7 (or also 6).
I execute:

dotnet tool install --global wix --version 4.0.0-rc.1

I got back this:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/8747559/210380600-9cae107d-b19b-4dcd-9ddb-a8a339882880.png">

System can download everything directly so it should work normaly...
Thanks for help!

**Comment by excelsi** [comment]
Thanks after i added Nuget as source with
dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org
it worked.
Would be nice if you can add this to the Docs:
https://wixtoolset.org/docs/intro/

**Comment by jimk-bdrc** [comment]
Why is this closed when it is not documented? I'm a MacOS and Debian developer who is trying to install a Java app. This could be a one line change to your installation document.

**Comment by robmen** [comment]
I guess no one else thinks it is that important. I mean, you chose to comment on a closed issue rather than add the line you think is missing. So it can't be that valuable of an add, especially since the documentation is particularly straightforward to update because every page has an edit link.

**Comment by jimk-bdrc** [comment]
I also shot my mouth off before reading the whole post. It is documented.

**Comment by johnmaguire** [comment]
FYI, we needed `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` (note the addition of https://) to avoid it being interpreted as a file path.
