### ISSUE TITLE
Standalone Install of Heat from Nuget fails

### ISSUE THREAD

**Issue by excelsi** [wixtoolset/issues#7130]
The standalone Installation of Heat documented at:
https://wixtoolset.org/docs/development/wips/organized-obsolecscence-of-heat-in-v4/#proposal

doesn't work because the Pacakge could not be found:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/8747559/210588911-d5eece16-6c51-452c-9495-ebeed82b7b32.png">

Can you help here? Thanks!

**Comment by excelsi** [comment]
Solved it myself by using:
.\nuget.exe install WixToolset.Heat -Version 4.0.0-rc.1
Please add this to the Docs.
Thanks!

**Comment by robmen** [comment]
With all due respect, @excelsi, please stop opening issues against the WiX Toolset as you learn how to use NuGet. If you have recommendations for improving their error messages or documentation, please raise it with them.

The WiX Toolset will not be a tutorial on how to use NuGet.

**Comment by excelsi** [comment]
Sorry if i used the wrong Repository to report this missing documentation for the install command line.
Which repository or site should be used here?

**Comment by robmen** [comment]
I don't know. I don't work on NuGet. Maybe: https://github.com/NuGet/Home/issues

**Comment by excelsi** [comment]
For sure this is not a Nuget Issue ;-)

I only mentioned the missing part for the Install Command Line in the Wix Docs here:
https://wixtoolset.org/docs/development/wips/organized-obsolecscence-of-heat-in-v4/#proposal

It mentions to use:
nuget.exe install WixToolset.Heat
but it has to be:
nuget.exe install WixToolset.Heat -Version 4.0.0-rc.1
to install successfully.
