### ISSUE TITLE
The Package element contains an unhandled extension element 'WixUI'

### ISSUE THREAD

**Issue by mjanulaitis** [wixtoolset/issues#7135]
* Which version of WiX are you building with?

>4.0.0 RC 1

* Which version of Visual Studio are you building with (if any)?

> 2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 4.0.0 RC 1

* Which version of .NET are you building with?

> .Net 7

* Describe the problem and the steps to reproduce it.

```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">
<Package
...
<ui:WixUI Id="WixUI_InstallDir" />
</Package>
</Wix>

```

Compile and you will get the error:

Package.wxs(220): error WIX0200: The Package element contains an unhandled extension element 'WixUI'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/ui' namespace has been provided.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect the compiler to build the project.

**Comment by barnson** [comment]
How is your project referencing `WixToolset.UI.wixext`?

**Comment by mjanulaitis** [comment]
Well it sounds like that's the problem.  I have been unable to find the documentation relevant to the issue so I actually don't even know what you are referring too.  How to I reference the component you are mentioning?

**Comment by mjanulaitis** [comment]
OK NuGet.  I had no idea.  I read NuGet was being used but didn't really understand when I should be using it.

**Comment by mjanulaitis** [comment]
OK that worked please close the bug.

**Comment by wstaelens** [comment]
got the same issue after upgrading nuget from v4.0.5 to v5.0.0. (The namespace was ok and the project (msi setup) builded in v4.0.6)

My problem was that my two project tags were still referencing to v4 instead of v5:

```
<Project Sdk="WixToolset.Sdk/4.0.5">

<Project Sdk="WixToolset.Sdk/4.0.5">
```

changed to (edit project file) and rebuild the solution

```
<Project Sdk="WixToolset.Sdk/5.0.0">

<Project Sdk="WixToolset.Sdk/5.0.0">
```

after this, I didn't have an issue anymore.
