### ISSUE TITLE
DotNetCompatibilityCheck returning 12289 and 12290

### ISSUE THREAD

**Issue by FredAtIvory** [wixtoolset/issues#7138]
- WiX 4.0.0-rc.1
- VS 2022 17.4.3
- WixToolset.Netfx.wixext 4.0.0-rc.1
- .NET 6.0
- Windows 10 22H2

I'm moving an older .NET Framework application to .NET Core and want the installer to check if the required version of .NET is installed. I was happy to see that WiX 4 is RC and has an extension for performing this check.

I created a simple toy WiX 4 installer project to exercise <netfx:DotNetCompatibilityCheck> and see how it responds when different versions of .NET are installed. My dummy installer makes multiple calls to DotNetCompatibilityCheck with different settings for  RuntimeType, Platform, Version, and RollForward. I then run the installer and look at the MSIEXEC log to see the values returned by DotNetCompatibilityCheck. Unfortunately, the results I'm getting do not match the documentation or my expectations for the parameters I'm passing to DotNetCompatibilityCheck.

First, on a new AWS Windows 2022 server with no .NET Core installed, DotNetCompatibilityCheck always returns 12289 or 12290 which may be some Windows error number, but is not one of the possible return values listed in the [documentation](https://wixtoolset.org/docs/reference/schema/netfx/dotnetcompatibilitycheck/) (0-6).

Second, after installing .NET Desktop Runtime 6.0.12 x86, DotNetCompatibilityCheck with RuntimeType="desktop", Platform="x86", and Version="6.0.0.0" returns 0 for RollForward="major" and "latestMajor", but 12290 for RollForward="minor" or "latestMinor". I expected "minor" and "latestMinor" to work since the installed .NET version is 6.0.12 and I'm checking for 6.0.0.0. Or, maybe I don't understand the RollForward values (the current WiX 4 documentation  does not give any details on the RollForward options).

Third, with only .NET Desktop Runtime 6.0.12 installed, DotNetCompatibilityCheck returns 0 when I check for Version="3.0.0.0", "5.0.0.0", "6.0.0.0", and "7.0.0.0" and RollForward="major" or "latestMajor" which just seemed wrong to me. Again, maybe I'm misunderstanding how RollForward works.

My expectation is that DotNetCompatibilityCheck will return a documented value (0-6), and that the RollForward parameter will control the precision of the match (major, major + minor, etc. with the ability to roll forward to the "latest").

**Package.wxs**
`<netfx:DotNetCompatibilityCheck Id="Bar_64_3a_min" RuntimeType="aspnet"  Platform="x64" Version="3.0.0.0" RollForward="minor" Property="Bar_64_3a_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_64_3d_min" RuntimeType="desktop" Platform="x64" Version="3.0.0.0" RollForward="minor" Property="Bar_64_3d_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_64_3c_min" RuntimeType="core"    Platform="x64" Version="3.0.0.0" RollForward="minor" Property="Bar_64_3c_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_64_3a_maj" RuntimeType="aspnet"  Platform="x64" Version="3.0.0.0" RollForward="major" Property="Bar_64_3a_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_64_3d_maj" RuntimeType="desktop" Platform="x64" Version="3.0.0.0" RollForward="major" Property="Bar_64_3d_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_64_3c_maj" RuntimeType="core"    Platform="x64" Version="3.0.0.0" RollForward="major" Property="Bar_64_3c_maj" />`
`...`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_3a_min" RuntimeType="aspnet"  Platform="x86" Version="3.0.0.0" RollForward="minor" Property="Bar_86_3a_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_3d_min" RuntimeType="desktop" Platform="x86" Version="3.0.0.0" RollForward="minor" Property="Bar_86_3d_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_3c_min" RuntimeType="core"    Platform="x86" Version="3.0.0.0" RollForward="minor" Property="Bar_86_3c_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_3a_maj" RuntimeType="aspnet"  Platform="x86" Version="3.0.0.0" RollForward="major" Property="Bar_86_3a_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_3d_maj" RuntimeType="desktop" Platform="x86" Version="3.0.0.0" RollForward="major" Property="Bar_86_3d_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_3c_maj" RuntimeType="core"    Platform="x86" Version="3.0.0.0" RollForward="major" Property="Bar_86_3c_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_5a_min" RuntimeType="aspnet"  Platform="x86" Version="5.0.0.0" RollForward="minor" Property="Bar_86_5a_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_5d_min" RuntimeType="desktop" Platform="x86" Version="5.0.0.0" RollForward="minor" Property="Bar_86_5d_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_5c_min" RuntimeType="core"    Platform="x86" Version="5.0.0.0" RollForward="minor" Property="Bar_86_5c_min" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_5a_maj" RuntimeType="aspnet"  Platform="x86" Version="5.0.0.0" RollForward="major" Property="Bar_86_5a_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_5d_maj" RuntimeType="desktop" Platform="x86" Version="5.0.0.0" RollForward="major" Property="Bar_86_5d_maj" />`
`<netfx:DotNetCompatibilityCheck Id="Bar_86_5c_maj" RuntimeType="core"    Platform="x86" Version="5.0.0.0" RollForward="major" Property="Bar_86_5c_maj" />`

**MSIEXEC Log**
`Action 18:57:05: FindRelatedProducts. Searching for related applications Found application: [1]`
`Action start 18:57:05: FindRelatedProducts.`
`Action ended 18:57:05: FindRelatedProducts. Return value 1.`
`MSI (c) (24:E0) [18:57:05:245]: Doing action: Wix4NetFxDotNetCompatibilityCheck_X64`
`MSI (c) (24:E0) [18:57:05:245]: Note: 1: 2205 2:  3: ActionText `
`Action 18:57:05: Wix4NetFxDotNetCompatibilityCheck_X64. `
`Action start 18:57:05: Wix4NetFxDotNetCompatibilityCheck_X64.`
`MSI (c) (24:14) [18:57:05:259]: Invoking remote custom action. DLL: C:\Users\ADMINI~1\AppData\Local\Temp\2\MSI675A.tmp, Entrypoint: DotNetCompatibilityCheck`
`MSI (c) (24:BC) [18:57:05:264]: Cloaking enabled.`
`MSI (c) (24:BC) [18:57:05:264]: Attempting to enable all disabled privileges before calling Install on Server`
`MSI (c) (24:BC) [18:57:05:264]: Connected to service for CA interface.`
`MSI (c) (24!B4) [18:57:07:025]: PROPERTY CHANGE: Adding Bar_64_3a_min property. Its value is '12289'.`
`MSI (c) (24!B4) [18:57:07:433]: PROPERTY CHANGE: Adding Bar_64_3d_min property. Its value is '12289'.`
`MSI (c) (24!B4) [18:57:07:824]: PROPERTY CHANGE: Adding Bar_64_3c_min property. Its value is '12289'.`
`MSI (c) (24!B4) [18:57:08:200]: PROPERTY CHANGE: Adding Bar_64_3a_maj property. Its value is '12289'.`
`MSI (c) (24!B4) [18:57:08:546]: PROPERTY CHANGE: Adding Bar_64_3d_maj property. Its value is '12289'.`
`MSI (c) (24!B4) [18:57:08:906]: PROPERTY CHANGE: Adding Bar_64_3c_maj property. Its value is '12289'.`
`...`
`MSI (c) (24!B4) [18:57:31:378]: PROPERTY CHANGE: Adding Bar_86_3a_min property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:31:831]: PROPERTY CHANGE: Adding Bar_86_3d_min property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:32:081]: PROPERTY CHANGE: Adding Bar_86_3c_min property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:32:425]: PROPERTY CHANGE: Adding Bar_86_3a_maj property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:33:481]: PROPERTY CHANGE: Adding Bar_86_3d_maj property. Its value is '0'.`
`MSI (c) (24!B4) [18:57:33:925]: PROPERTY CHANGE: Adding Bar_86_3c_maj property. Its value is '0'.`
`MSI (c) (24!B4) [18:57:34:347]: PROPERTY CHANGE: Adding Bar_86_5a_min property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:34:764]: PROPERTY CHANGE: Adding Bar_86_5d_min property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:35:174]: PROPERTY CHANGE: Adding Bar_86_5c_min property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:35:752]: PROPERTY CHANGE: Adding Bar_86_5a_maj property. Its value is '12290'.`
`MSI (c) (24!B4) [18:57:36:159]: PROPERTY CHANGE: Adding Bar_86_5d_maj property. Its value is '0'.`
`MSI (c) (24!B4) [18:57:36:674]: PROPERTY CHANGE: Adding Bar_86_5c_maj property. Its value is '0'.`

[Package.wxs.txt](https://github.com/wixtoolset/issues/files/10357879/Package.wxs.txt)
[log2.txt](https://github.com/wixtoolset/issues/files/10357881/log2.txt)

**Comment by rseanhall** [comment]
DotNetCompatibilityCheck relies on Microsoft's netcorecheck.exe from https://github.com/dotnet/deployment-tools. This comes from the nuget packages such as https://www.nuget.org/packages/Microsoft.NET.Tools.NETCoreCheck.x86. Please manually run the .exe on the machine to verify whether the problem is with WiX's custom action or Microsoft's netcorecheck.exe.

**Comment by FredAtIvory** [comment]
I installed NETCoreCheck and sure enough, it returns error 12290 when I check for a .NET version that does not exist and apparently that value is then returned by DotNetCompatibilityCheck.

BTW, I searched on my clean test machine for NETCoreCheck.exe and noticed that is not there, but the installer does seem to be running it; is it automatically included in the MSI?

What do you recommend? I could go ask my question over at the NETCoreCheck project, but I'm only using it through DotNetCompatibilityCheck so they will probably just send me back here :)

**Comment by barnson** [comment]
Error codes are defined in https://github.com/dotnet/deployment-tools/blob/main/src/clickonce/native/projects/NetCoreCheck/NetCoreCheck.h#L18.

**Comment by FredAtIvory** [comment]
Thanks. Looking at the source code for NetCoreCheck I see the result values I am getting back (12289, 12290) and I now understand their meaning. Also, I was able to find more detailed descriptions of the RollForward options here: https://github.com/dotnet/runtime/blob/main/docs/design/features/framework-version-resolution.md. Closing this issue.
