### ISSUE TITLE
Automated Builds Randomly Hang

### ISSUE THREAD

**Issue by mjanulaitis** [wixtoolset/issues#7141]
* Which version of WiX are you building with?
> 4.0.0.rc1

* Which version of Visual Studio are you building with (if any)?
> 17.4.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> 4.0.0.rc1

* Which version of .NET are you building with?
> .Net 7

* Windows Version
> 10.19044.2364

* Steps to Repo:
> When running an automated build with the following commands, the process randomly hangs indefinitely requiring me to Ctrl-C out of the command.  This is a breaking bug since all production builds in our industry are automated.

```
"c:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv" /rebuild "Release|x86" "MyInstaller.sln"
"c:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv" /rebuild "Release|x64" "MyInstaller.sln"

* Describe the behavior you expected and how it differed from the actual behavior.
> The build process should not hang.

**Comment by robmen** [comment]
We'll need more information to begin assessing if this issue is related to WiX v4. Please provide a link to GitHub repo that reproduces this issue and/or an msbuild.binlog from the hung build(s).

**Comment by mjanulaitis** [comment]
My source code is private.  What can I do to help figure this out?  Can any debug logs be generated?

**Comment by robmen** [comment]
Text build log files would tell us a bit. You could review the text and redact private information.

Alternatively, if you have a [support contract with FireGiant](https://www.firegiant.com/services/support-programs/) they provide a private communication mechanism and will help track down this issue very quickly.

**Comment by mjanulaitis** [comment]
My build script is to the point where it hangs 100% of the time.  Now when I try to open my Wix project in Visual Studio, VS hangs indefinitely.  I suspect the issue is related.  After deleting all of my obj and bin directories, I was able to reopen the Wix project but still unable to run my automation scripts.  Now I can't open my Wix project anymore in Visual Studio.  VS just hangs at startup.  I suspect this is a problem with the VISX.

**Comment by robmen** [comment]
Ahh, I see you are building from the command-line using `devenv` instead of `msbuild`. I suppose `devenv` does load all of its VSIX's for the build. In that case, the issue over there may be relevant: https://github.com/firegiant/HeatWaveSupport/issues/13

**Comment by mjanulaitis** [comment]
I was thinking the same.  I will see about manually calling each project with msbuild to see how that works and get back when I've done that.  Thank you.

**Comment by mjanulaitis** [comment]
OK I switched to msbuild and the issues appears to be resolved.
