### ISSUE TITLE
Manually Installing WixToolset.Sdk as a NuGet File on a project managed by HeatWave causes error in project

### ISSUE THREAD

**Issue by ld0614** [wixtoolset/issues#7148]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0.0-rc1

* Which version of Visual Studio are you building with (if any)?

> 17.4.3 (VS 2022)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Heatwave for VS2022 0.9.2 (also Wix v3 - Visual Studio 2022 Extension 1.0.0.22)

* Which version of .NET are you building with?

> 4.6.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 22H2 (22621.963)

* Describe the problem and the steps to reproduce it.

>- Create new WixV4 MSI Project and/or solution
>- Manage NuGet Packages
>- Tick Include prerelease
>- Install WixToolset.SDK 4.0.0-rc.1

>This causes an error:
>`The project 'Installerv4' ran into a problem during the last operation: Importing the file "C:\Users\username\.nuget\packages\wixtoolset.sdk\4.0.0-rc.1\tools\wix.props" into the file "C:\Users\username\.nuget\packages\wixtoolset.sdk\4.0.0-rc.1\build\WixToolset.Sdk.props" results in a circular dependency.  C:\Users\username\.nuget\packages\wixtoolset.sdk\4.0.0-rc.1\build\WixToolset.Sdk.props You may need to reload the solution after fixing the problem. `

>After getting into this error state it is not possible to do the following
>- Uninstall the package from the nuget package manager
>- Open the Project Properties from within Visual Studio
>- Build the project

* Describe the behavior you expected and how it differed from the actual behavior.

> Ideally the documentation should be updated to clarify when nuget packages need to be added (or not added) to the project. I was fiddling with this when attempting to convert a project utilizing the UI and Util extensions and got build errors.
> Ideally the project should either not allow me to add the package or it should not break in a way that is irrecoverable. If neither are possible having some documentation to cover how to manually recover from this scenario would be useful

Thanks and overall v4 looks like an amazing upgrade. Thanks for all your work on Wix!

**Comment by ld0614** [comment]
For anyone else who needs to recover a project I took the following steps:
- Unload the affected project
- Edit the Project File
- Delete reference to WixToolset.Sdk
- Save and Close Visual Studio
- Delete package files at C:\Users\username\.nuget\packages\wixtoolset.sdk
- Delete bin and obj directories in project folder
- Reopen the Solution in Visual Studio
- Reload Project if not automatically loaded
- Add Required extensions from NuGet as required (WizToolset.UI.wixext etc)

**Comment by robmen** [comment]
First, never `PackageReference` an Sdk. That does not make sense.

I'll see if there is something simple we can do in the targets to improve the error.
