### ISSUE TITLE
ProjectReference against a multi-targeted project produces does not call _ConvertResolvedProjectReferencesIntoWixConstructs

### ISSUE THREAD

**Issue by mgaffigan** [wixtoolset/issues#7149]
## Bug

Versions: 
WixToolset.Sdk/4.0.0-rc.1
Microsoft Visual Studio Enterprise 2022 Version 17.4.3 VisualStudio.17.Release/17.4.3+33205.214
FireGiant HeatWave   0.9.2.1
WiX Toolset Visual Studio Extension   1.0.0.18

* Which version of .NET are you building with?
net7.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.

1. Create Console Project for .Net 7
2. Update project file to multi-target by changing `<TargetFramework>net7.0</TargetFramework>` to `<TargetFrameworks>net7.0</TargetFrameworks>`
3. Add Wix4 setup project
4. Add ProjectReference to console app
5. Add `<File Source="$(var.ConsoleApp1.TargetPath)" />` to `ExampleComponents` (set keypath or replace existing file in template to avoid unrelated errors).
6. Build

* Describe the behavior you expected and how it differed from the actual behavior.

Expected behavior: msi is produced with the exe from the console app
Actual behavior: `error WIX0150: Undefined preprocessor variable '$(var.ConsoleApp1.TargetPath)'`

## Workaround

Use `SetTargetFramework` to avoid multi-targeting in the project reference.

Updated Package1.wixproj:

    <Project Sdk="WixToolset.Sdk/4.0.0-rc.1">
      <ItemGroup>
        <ProjectReference Include="..\ConsoleApp1\ConsoleApp1.csproj">
          <SetTargetFramework>TargetFramework=net7.0</SetTargetFramework>
        </ProjectReference>
      </ItemGroup>
    </Project>

## Notes

ConsoleApp1.csproj:

    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net7.0</TargetFrameworks>
      </PropertyGroup>
    </Project>

Package1.wixproj

    <Project Sdk="WixToolset.Sdk/4.0.0-rc.1">
      <ItemGroup>
        <ProjectReference Include="..\ConsoleApp1\ConsoleApp1.csproj"/>
      </ItemGroup>
    </Project>

ExampleComponents.wxs

    <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
      <Fragment>
        <ComponentGroup Id="ExampleComponents" Directory="INSTALLFOLDER">
          <Component>
            <File Source="ExampleComponents.wxs" />
            <File Source="$(var.ConsoleApp1.TargetPath)" KeyPath="yes" />
          </Component>
        </ComponentGroup>
      </Fragment>
    </Wix>

Things that don't work:

- Setting `TargetFramework` or `TargetFrameworks` in the wixproj
- Using `AdditionalProperties="TargetFramework=net7.0"` in the wixproj `ProjectReference`
- Wailing in lamentation at the barren wix4 documentation page

If I use `<TargetFramework>` instead of `<TargetFrameworks>` in the console project, the error resolves - but I need to multi-target.

MSBuild diagnostic log for diff showing `_ConvertResolvedProjectReferencesIntoWixConstructs` being evaluated as `Condition=false` for multitargeting and true for single-targeting:
[single targeting (works).txt](https://github.com/wixtoolset/issues/files/10367545/single.txt)
[multi targeting (fails).txt](https://github.com/wixtoolset/issues/files/10367546/multi1.txt)

[Related stackoverflow post](https://stackoverflow.com/questions/75044988/error-wix0150-undefined-preprocessor-variable-when-using-projectreference-again)

**Comment by robmen** [comment]
Using `SetTargetFramework` is not a workaround. That's how you do this in MSBuild.

But I'm curious enough to try to see if `_ConvertResolvedProjectReferencesIntoWixConstructs` can do something useful in multi-targeting scenarios.
