### ISSUE TITLE
Wix cannot work with DebugType embedded

### ISSUE THREAD

**Issue by ChristianSauer** [wixtoolset/issues#7152]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0-rc.1

* Which version of Visual Studio are you building with (if any)?

> does not matter

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> does not matter

* Which version of .NET are you building with?

> Dotnet 7

* Describe the problem and the steps to reproduce it.

How to reproduce:

1. Add an Wix-Installer Project to a Solution
2. Add an `Directory.Build.props` file

```
<Project>
  <PropertyGroup>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
</Project>
```

3. Try to build the solution.
4. It will crash with `wix.exe : error WIX0268: The argument -pdbType value 'embedded' is invalid. Use one of the following values full, none `

Is there a way for wix to accomodate the new value?

**Comment by robmen** [comment]
1. That is not a crash. That is an error message. Please do not try to artificially elevate an issue by overstating the problem.

2. What would `embedded` mean in this context?

**Comment by ChristianSauer** [comment]
@robmen Well it prevents the project from building. Not a crash but blocking.

Embedded embeds the generated PDBs into the DLL. Making debugging easier and enriching stacktraces. It omits the need to ship the pdbs alongside the dll.
See https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/code-generation

**Comment by ChristianSauer** [comment]
To expand a little: I have a large project with dozens of projects and I want to apply this to each and very project. Using the g.props file is the best way to do that, but then then Wix build is broken.

**Comment by ChristianSauer** [comment]
Finally a workaround is to disable this for the Wix Project(s) by adding an empty file in the project. https://stackoverflow.com/questions/56155392/exclude-certain-projects-from-using-directory-build-props. 
Still no ideal, a lot a files are needed

**Comment by robmen** [comment]
1. It isn't blocking. You can override the `DebugType` in the .wixproj.

2. I understand the purpose of `embedded` in managed code projects. You could notice that we use it in WiX v4 .csproj files. When I said `"this context"`, I meant WiX and more specifically .wixprojs. What would it mean to set the `DebugType` to `embedded` in a .wixproj?

**Comment by ChristianSauer** [comment]
M.e it should be ignored. I certainly do not expect it to embed anything

**Comment by robmen** [comment]
But a `DebugType` value _was_ provided. Ignoring it provides no feedback that the value is incorrect. Valid values (in v4) are `full` and `none`? And why should the .wixpdb not be embedded? That _could_ be implemented.

**Comment by ChristianSauer** [comment]
It's your project, do as you like. 
For me it was unexpected. I would have expected that it ignores that value because (for me) adding a pdb for wix is not that useful. There are workarounds, but it's more clutter.

**Comment by robmen** [comment]
> I would have expected that it ignores that value because (for me) adding a pdb for wix is not that useful. 

Do you know what .wixpdbs are used for? If not, that seems like something to understand since they are deemed important enough to be on by default.

> There are workarounds, but it's more clutter.

On that, we agree. But you can't just say, "This doesn't make sense to me, so you should just get rid of it." and expect to get anywhere with your proposal. I've been raising issues with your proposal to help you think through the different aspects that need to be considered for the final design.

**Comment by ChristianSauer** [comment]
Thanks, the solution looks very reasonable
