### ISSUE TITLE
Page Not Found: 

### ISSUE THREAD

**Issue by xv-aleksandr-b** [wixtoolset/issues#7159]
### WiX Toolset Page URL

https://wixtoolset.org/downloads/v3.14.0.6526/wix314.exe

### Additional information (optional)

This release cannot be downloaded anymore. The link shows the following error:
```
<Error>
<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:48471cf7-601e-0024-7c0d-2728d3000000 Time:2023-01-13T05:13:46.1148771Z</Message>
</Error>
```

**Comment by MarkDaviesAGMT** [comment]
https://wixtoolset.org/downloads/v3.14.0.4118/wix314.exe is also removed breaking our ci pipeline

**Comment by robmen** [comment]
The networking issue seems to be resolved now.

Note: these downloads are development builds. They are not intended to be used in production and are definitely not intended to be downloaded by CI/CD systems. As this issue demonstrates, we do not make guarantees on up time for the development build downloads.
