### ISSUE TITLE
Creating cabinets greater than 2GB fails with error 0x80004005

### ISSUE THREAD

**Issue by LuxNegra** [wixtoolset/issues#7169]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

4.0.0-preview.1+7a4632ad

* Which version of Visual Studio are you building with (if any)?

Visual Studio 2022 x64 - 17.4.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

HeatWave for VS2022 0.9.3

* Which version of .NET are you building with?

.Net 7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

* Describe the problem and the steps to reproduce it.

When trying to generate a bundle, I encounter the error :
```
wix.exe : error WIX0001: WixToolset.Core.Native.WixNativeException: wixnative.exe failed with error code: -2147467259 - Unknown error (0x4005) Output:
1>WIXBUILD : error 0x80004005: failed to compress cabinet: <Path>\bundle-attached.cab ---> System.ComponentModel.Win32Exception: Unknown error (0x4005)
```

The bundle is composed of a MSI generated with Wix V4. The Msi is divided with 14 cabs.
```
<Chain>
     <MsiPackage Id="ProductMsi" SourceFile=".\build.msi" />
</Chain>
```
When i remove the msi, the bundle generate well and when i launch the msi, it install my product as desired.

The wix-badata.xml of the bundle generated during the build the contains the msi, and the 14 cabs.

```
  <WixPayloadProperties Package="ProductMsi" Payload="ProductMsi" Container="WixAttachedContainer" Name="build.msi" Size="724992" />
  <WixPayloadProperties Package="ProductMsi" Payload="cab0gHzNqCQEopR4V2ui3Iqa.TdJPU" Container="WixAttachedContainer" Name="cab3.cab" Size="136798426" />
  <WixPayloadProperties Package="ProductMsi" Payload="cab2pTjotJIscukb454kPrgRl4rE7I" Container="WixAttachedContainer" Name="cab14.cab" Size="101710110" />
  <WixPayloadProperties Package="ProductMsi" Payload="cab7mHIbnQuDgTewvevWSjZI7BirPc" Container="WixAttachedContainer" Name="cab7.cab" Size="203714241" />
  <WixPayloadProperties Package="ProductMsi" Payload="cab9PU.jwrnEKnUfFhvWoRu.ZSxfNg" Container="WixAttachedContainer" Name="cab13.cab" Size="186246729" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabCHivwkQY0rRaulV291Deny.9Ne4" Container="WixAttachedContainer" Name="cab4.cab" Size="209018073" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabFxo9tuthLIiar3bo0VsleOZRabw" Container="WixAttachedContainer" Name="cab9.cab" Size="177344092" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabLyjxtIjxPe0lJCB0gEq4O4o1q3g" Container="WixAttachedContainer" Name="cab1.cab" Size="23207871" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabUNpc65XOo1XmYaHnfx7sz2DP.4U" Container="WixAttachedContainer" Name="cab6.cab" Size="190501035" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabY1ng.UCRmQfqYlu6a7SjZkiVOD8" Container="WixAttachedContainer" Name="cab8.cab" Size="204480244" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabfqDGpK_PDYpVLrHR754FdbYkcFM" Container="WixAttachedContainer" Name="cab12.cab" Size="209018084" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabgyvnVn7rMI6WDRQlf.W3JnqY1Sc" Container="WixAttachedContainer" Name="cab2.cab" Size="161470397" />
  <WixPayloadProperties Package="ProductMsi" Payload="cablvKBR94dJk_vNLtw6ApRRRFyNkU" Container="WixAttachedContainer" Name="cab11.cab" Size="155697107" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabpCfVc0PcjPlMSweAYyBoFFdP_0A" Container="WixAttachedContainer" Name="cab5.cab" Size="186246780" />
  <WixPayloadProperties Package="ProductMsi" Payload="cabw87XELlw5N6y6U4JeZjOPW4L.FM" Container="WixAttachedContainer" Name="cab10.cab" Size="181181672" />
```

The error occure as well when i use the command line ```wix build```

* Describe the behavior you expected and how it differed from the actual behavior.

The expected behavior is to generate the bundle with the content.

**Comment by robmen** [comment]
I'm guessing the root issue is that more than 2GB of data is being compressed into a single .cab. That will not work, but there should be a better error message when it is attempted.

**Comment by robmen** [comment]
@LuxNegra can you confirm my hypothesis by commenting out a couple of hundred MB of files from your MSI to get its size under 2GB and trying to build the bundle? Should be pretty quick for you to confirm if that allows the bundle to build.

**Comment by rseanhall** [comment]
@LuxNegra Please get back to @robmen with the information he asked for. But to answer your question, @nirbar did add the ability to have more than one attached container in https://github.com/wixtoolset/issues/issues/6144 which allows a bundle's .exe to get over 2GB. But we did not get to https://github.com/wixtoolset/issues/issues/6521 in v4 which means that the contents of the bundle is not automatically spanned across multiple attached containers. I don't think the WiX language currently supports splitting up the contents of a package so if @robmen's psychic debugging is correct then the only way to get this working would be to write an extension that redistributes the payloads across multiple attached containers.

**Comment by LuxNegra** [comment]
@robmen I can confirm that it create the bundle when the Product (with all his cabs) under 2GB

@rseanhall Thanks for the informations about the extension.

**Comment by oferPresente** [comment]
We just converted to Wix 4 , hoping that it would allow us to overcome the 2 GB limit for bundle. 
We succeed to build an MSI with few cab files (64 bit) with total > 2 GB, but when trying to build a bundle, 
we get the same error as @LuxNegra :
wix.exe : error WIX0001: WixToolset.Core.Native.WixNativeException: wixnative.exe failed with error code: -2147467259 - Unknown error (0x4005)

I am trying to understand @rseanhall  comment from Jan 18. 
It is not clear if using containers can assist, and we couldn't find a single example of Bundle.wxs that uses containers. Can someone provide an example?

It is not clear if the fact that #6521 is not implemented yet, means that building a single bundle from {Msi + cabs exceeding 2 GB} is not possible at the moment.

Thanks

**Comment by nirbar** [comment]
@oferPresente 
Did you explicitly define attached containers that are less than 2GB each?
You can use my open source extension to automatically accomplish that (which handles both this case and https://github.com/wixtoolset/issues/issues/6521)

In project file add
~~~
  <ItemGroup>
    <PackageReference Include="PanelSwWixExtension4" Version="3.5.1.164" />
  </ItemGroup>
~~~

In the bundle add
~~~
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:panelsw="http://schemas.panel-sw.co.il/wix/WixExtension">
 <Bundle ...>
    <panelsw:ContainerTemplate CabinetTemplate="$(var.TargetName)-{0}.bin"/>
    ...
 </Bundle>
</Wix>
~~~

Contact me if you need any help

**Comment by oferPresente** [comment]
Thanks @nirbar for your quick response. 
I tried your proposal. 
The good news are that I succeeded to build the 3 GB bundle.
The bad news are that it doesn't work... after launching the bundle, nothing happens.  There is no error, but the installation doesn't start.
