### ISSUE TITLE
DisplayInternalUI attribute is not allowed

### ISSUE THREAD

**Issue by elaboy** [wixtoolset/issues#7170]
* Which version of WiX are you building with?

> WiX version 4.0.0-rc.1

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Community 2022 version 17.4.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave for VS2022 version 0.9.3

* Which version of .NET are you building with?

> .NET 6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 Enterprise Version 22H2 | OS build 22621.1105

* Describe the problem and the steps to reproduce it.

> Our software [MetaMorpheus](https://github.com/smith-chem-wisc/MetaMorpheus) used WiXV3 for the MSI build. I upgraded to version 4 using the HeatWave extension and an error prevented the build. https://github.com/wixtoolset/issues/issues/6164 I moved `DisplayInternalUI = yes` from `MsiPackage` to the `bal` extension. 

* Describe the behavior you expected and how it differed from the actual behavior.

> While moving `DisplayInternalUI` to the bal extension "fixed" the error (and the MSI is build without any problems), Visual Studio's editor stills marks the attribute with a green line, indicating `DisplayInternalUI attribute is not allowed`. I opened this issue as @robmen suggested me to do. 
![image](https://user-images.githubusercontent.com/63374885/212962632-b0b990e4-0ec8-4a3c-87b0-72b224a4cee7.png)

## Thank you so much for this awesome tool!

**Comment by rseanhall** [comment]
@robmen You can give this to me if you haven't started yet.

**Comment by rseanhall** [comment]
Sorry, I shouldn't have volunteered for this. It is already documented at https://github.com/wixtoolset/web/blob/645d99709292f9231302fcef1a6d7880e2b435a5/src/xsd4/bal.xsd#L509. I'm not interested in spending time figuring out why it's not making it to the final output when bal:Overridable and bal:PrimaryPackageType are working.

**Comment by rseanhall** [comment]
@elaboy By the way, `DisplayInternalUI` is not allowed because the real name is `DisplayInternalUICondition` and it is not for that element. You have to put `bal:DisplayInternalUICondition` on `MsiPackage` or `MspPackage` elements. It is not a bundle-wide setting.

**Comment by elaboy** [comment]
@rseanhall Thank you! I was able to fix the issue using your solution.

**Comment by dibyamani** [comment]
> @elaboy By the way, `DisplayInternalUI` is not allowed because the real name is `DisplayInternalUICondition` and it is not for that element. You have to put `bal:DisplayInternalUICondition` on `MsiPackage` or `MspPackage` elements. It is not a bundle-wide setting.

bal:DisplayInternalUICondition="yes" doesn't show any UI ma packaged msi file. Did I miss anything other than this?

**Comment by dibyamani** [comment]
> @rseanhall Thank you! I was able to fix the issue using your solution.

Can you share it? I did same but did not work.

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">
  <Bundle Name="eAttendanceSetup.Bundle" Manufacturer="PlanetInfosys" Version="1.0.0.0" UpgradeCode="a3839ede-1884-461f-b3c5-c6a1db2e9058">
    <BootstrapperApplication>
      <bal:WixStandardBootstrapperApplication LicenseUrl="https://www.example.com/license" Theme="hyperlinkLicense" />
    </BootstrapperApplication>
    <Chain>
      
      <PackageGroupRef Id="NetFx472Web" />
            
      
      <MsiPackage bal:DisplayInternalUICondition="yes" SourceFile="$(var.eAttendanceSetup.TargetPath)" Compressed="yes" />
    </Chain>

  </Bundle>
</Wix>

**Comment by g4m3r0** [comment]
@dibyamani `bal:DisplayInternalUICondition="1" ` worked for me with WiX 4.0.0.

**Comment by Bondarenko1990** [comment]
I upgraded Wix Bootstrapper project to WIX 4.0.0. And I have problems with displaying internal UI. The only problem is when uninstalling the application. I want the internal UI to not be displayed. With Wix 3 there were no such problems, everything worked properly. Tell me how I can solve this problem, please.
![image](https://github.com/user-attachments/assets/c0b7cf26-8a45-47f8-a0f5-833ccfb4f971)
`<Chain>
			
			

			<MsiPackage Id="Setup" SourceFile="$(var.Setup.TargetPath)" Compressed="yes">
				<MsiProperty Name="AddDesktopShortcut" Value="[AddDesktopShortcutMsiVariable]" />
				<MsiProperty Name="INSTALLFOLDER" Value="[InstallFolder]" />
			</MsiPackage>

			<MsiPackage DisplayInternalUI="no" Id="SetupMSI" ForcePerMachine="yes" 
                                 SourceFile="$(var.TargetDir)\......x64.msi" Compressed="yes">
			</MsiPackage>
		</Chain>`

**Comment by bevancollins** [comment]
@Bondarenko1990 try using `bal:DisplayFilesInUseDialogCondition="no"` instead
