### ISSUE TITLE
CRLF lost on git commit in *.cmd files that contain batch label - The system cannot find the batch label specified

### ISSUE THREAD

**Issue by maniglia** [wixtoolset/issues#7175]
**Encountered at:** wixtoolset/wix4@src/build_all.cmd

appveyor console:

_The system cannot find the batch label specified - StartDeveloperCommandPrompt
Command exited with code 1_

**Detail:**
After several experiments on my development pc i found it difficult to run the build_all.cmd script on appveyor after a commit.

The problem seems to be related to the line ending on the script: \LF vs \CR\LF

To fix this and make the repository more robust at git-related settings, I suggest to put the following line of code in the _.gitattributes_ file: `*.cmd   text eol=crlf`

Regards

**Comment by robmen** [comment]
The WiX Toolset standardized its builds on GitHub Actions. AppVeyor is a good service, and it was amazing what they provided for free. Challenges with line endings, _especially_ with test files, were one of the _very_ few negatives unique to AppVeyor. As such, there are no plans to futz with `.gitattributes` to address issues unique to AppVeyor.
