### ISSUE TITLE
Cannot uninstall bundle when WixInternalUIBootstrapperApplication is used in 4.0.0-rc.2

### ISSUE THREAD

**Issue by itn3000** [wixtoolset/issues#7184]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0-rc.2

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022(17.4.3)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> not used

* Which version of .NET are you building with?

> .NET SDK 7.0.101

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

here is steps to reproduce

1. create wix installer project as "installer1" using "WixUI_InstallDir"
2. create bundle project and write bootstrapper.wxs as follows
3. build installer project and put installer.msi into path/to/bundleproject/files
4. build bundle project
5. execute bundle and install
6. re-execute bundle with `/uninstall` argument

```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">
    <Bundle Name="Bundle1" Manufacturer="TODO Manufacturer" Version="1.0.0.0" UpgradeCode="[put-guid-here]">
      <BootstrapperApplication>
        <bal:WixInternalUIBootstrapperApplication Theme="standard"/>
      </BootstrapperApplication>
      <Chain>
        <MsiPackage SourceFile="files/installer1.msi"/>
      </Chain>
  
    </Bundle>
  </Wix>
```

* Describe the behavior you expected and how it differed from the actual behavior.

Expected: Bundle1 and installer1 uninstalled and removed from list of installed apps
Actual: Bundle1 and installer1 repaired and still exist in list of installed apps

Current Workaround: using "WixStandardBootstrapperApplication" for BootstrapperApplication

**Comment by barnson** [comment]
Please attach bundle log from uninstall attempt.

**Comment by itn3000** [comment]
here is the logs. `install*.log` is newly installation log, `uninstall*.log` is uninstallation log.
[installlog.zip](https://github.com/wixtoolset/issues/files/10531507/installlog.zip)

**Comment by itn3000** [comment]
In uninstallation, maintainance dialog was not displayed.
I investigated and found this is because [Preselected property](https://learn.microsoft.com/en-us/windows/win32/msi/preselected) was set as 1, and
this is because "REINSTALL" property was set(this is set by burn engine?)

**Comment by ntwerdochlib** [comment]
I am running into this same issue using Wix v6.0.2

[vsc-client-1.4.0.0-uninstall-1.log](https://github.com/user-attachments/files/28764799/vsc-client-1.4.0.0-uninstall-1.log)
[vsc-client-1.4.0.0-uninstall-1_000_VscClient.log](https://github.com/user-attachments/files/28764800/vsc-client-1.4.0.0-uninstall-1_000_VscClient.log)
