### ISSUE TITLE
error WIX0199: The Wix element has an incorrect namespace of 'http://schemas.microsoft.com/wix/2006/wi'. Please make the Wix element look like the following: <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">

### ISSUE THREAD

**Issue by GF-Huang** [wixtoolset/issues#7185]
I don't know if this documentation is up to date, but it appears to be. https://www.firegiant.com/wix/tutorial/user-interface/first-steps/

I try to build the `SampleWixUI`, but failed. Why I create a VS project rather use `candle.exe` and `light.exe`? Because I don't where these exes are. 

![image](https://user-images.githubusercontent.com/4510984/215427560-78a9ada2-8825-412b-a8d0-cec4d5b7f8bd.png)

**Comment by barnson** [comment]
That tutorial is for WiX v3. WiX v4 intro is at https://wixtoolset.org/docs/intro/.

**Comment by GF-Huang** [comment]
> That tutorial is for WiX v3. WiX v4 intro is at [wixtoolset.org/docs/intro](https://wixtoolset.org/docs/intro/).

Is there a v4 tutorial?

**Comment by barnson** [comment]
Not yet.
