### ISSUE TITLE
Page Not Found: /schemas/v4/wxs

### ISSUE THREAD

**Issue by mvp3** [wixtoolset/issues#7196]
### WiX Toolset Page URL

https://wixtoolset.org/schemas/v4/wxs

### Additional information (optional)

The Package.wxs defaults with the following as the first line:
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">

**Comment by DarkMio** [comment]
I'm sorry, but why the heck does this link to a smashing pumpinks link via bit.ly?

**Comment by robmen** [comment]
Why not? XML namespaces are just unique URIs. They do not actually have to resolve to anything on the web. But people keep trying. So it seemed like a fun thing to point to the Maintainers Anthem, "Bullet with Butterfly Wings". :)

**Comment by DarkMio** [comment]
In this case my IDE of choice doesn't seem to understand the namespace or has any references to it with wix being installed regularly. It then tries to fetch the URI, which confused it:
![image](https://user-images.githubusercontent.com/6331542/219658366-c031742f-b546-44fe-9f78-c27c0ad72a8c.png)
(This being Jetbrains Rider)

I'd expect the URI to either return a concrete HTTP error / document indicating that the schema is not published there or nothing at all. A random youtube video took me by surprise and looks like an error.

**Comment by DarkMio** [comment]
No problem. I'm mostly just confused why I was greeted with a music video and it looked like an unintentional mistake.

**Comment by travisvalenti** [comment]
Is there a specific reason http://wixtoolset.org/schemas/v4/wxs redirects to something that is completely unrelated to the URI?

This feels quite counter-productive, especially considering some IDEs that people are using may expect an https xmlns URI to be useful information without requiring downloading from a separate source. Consider the default behavior for VS Code and IntelliJ Rider (I can't attest to Visual Studio's behavior).

Would it not be more ideal to at a minimum redirect it to the web repo, (as @barnson claims in https://github.com/wixtoolset/issues/issues/7964) that's the location for anyone who wants the files?

I understand we may have different views surrounding the purpose of these xmlns URIs but it feels like an actively malicious step to deter or ridicule developers who expect these URIs to work as URLs the way that most other http URIs work (in my experience).

The usage of the http scheme, whilst not required to, realistically implies to a developer that this resource is available at the URL that matches the URI. If you wanted this to not be the case, it would make much more sense to use a URI scheme such as urn.
As you've already configured everything to put the http scheme into these URIs, the only logical conclusion is to make the matching route direct to the appropriate resource.

Feedback is appreciated on this matter, as I'm sure there must be a valid reason that I haven't considered, besides malice, to not update the URL.
