### ISSUE TITLE
Using the "old" ServiceConfig element in WiX4 causes WIX0136 error

### ISSUE THREAD

**Issue by manison** [wixtoolset/issues#7198]
* Which version of WiX are you building with?

> 4.0.0-rc.2

* Which version of Visual Studio are you building with (if any)?

> 2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave 0.9.4

* Which version of .NET are you building with?

> N/A

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

I converted the WiX3 project to WiX4. The project uses the not recommended ServiceConfig element to set DelayedAutoStart and ServiceSid parameters of the service. This worked in WiX3 and ends with WIX0136 error in WiX4 saying:

> There was an error importing file ...\\_idts\MsiServiceConfigFailureActions.idt.

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected this to work without errors.

The WiX script is:

```xml
<ServiceInstall Name="$(var.ServiceName)"
                        Type="ownProcess"
                        Start="auto"
                        ErrorControl="ignore"
                        DisplayName="!(loc.ServiceDisplayName)"
                        Description="!(loc.ServiceDescription)"
                        Interactive="no"
                        Account="NT AUTHORITY\LocalService">
          <ServiceConfig DelayedAutoStart="yes" ServiceSid="unrestricted" OnInstall="yes" />
</ServiceInstall>
```

The generated IDT file that fails the import:

```
MsiServiceConfigFailureActions	Name	Event	ResetPeriod	RebootMessage	Command	Actions	DelayActions	Component_
s72	l255	i2	I4	L255	L255	S0	S0	s72
MsiServiceConfigFailureActions	MsiServiceConfigFailureActions
mysvc.DS	mysvc	1	3	1	mysvc.exe			
mysvc.SS	mysvc	1	5	1	mysvc.exe			
```

**Comment by robmen** [comment]
The [test case](https://github.com/wixtoolset/wix4/blob/a143a9ce03e1d11eceeb56ccb3a5c688ee9c6b6a/src/wix/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs#L720-L754) works for me.
