### ISSUE TITLE
Possible typo in the word StrtMenu

### ISSUE THREAD

**Issue by maniglia** [wixtoolset/issues#7217]
**Encountered at:**
 [wixtoolset/wix4@src/api/wix/WixToolset.Data/WindowsInstaller/WindowsInstallerStandard.cs](https://github.com/wixtoolset/wix4/blob/a09eaf3c98cda2593d4ea34b8014cf669f5be762/src/api/wix/WixToolset.Data/WindowsInstaller/WindowsInstallerStandard.cs#L390)

**Detail:**

In _WindowsInstallerStandard.cs_ at line 390 I find the following line of code:
`new DirectorySymbol(null, new Identifier(AccessModifier.Global, "StartMenuFolder")) { Name = "StrtMenu" },`
Should the last word (`"StrtMenu"`) be replaced with `"StartMenu"`?

Regards

**Comment by robmen** [comment]
The `Name` must be 8 letters long and unique in the list.

Feel free to ask questions on the [WiX Development discussions](https://github.com/wixtoolset/issues/discussions/categories/wix-development) before opening a speculative bug.

**Comment by maniglia** [comment]
Thanks for the clarification, for next time I will follow the advice on [WiX Development discussions](https://github.com/wixtoolset/issues/discussions/categories/wix-development).
It is interesting to observe the length of the first element of this list, which is 9 characters long and which confused me: **SourceDir**

Regards

**Comment by robmen** [comment]
Yeah, `SourceDir` is special in the Windows Installer.
