### ISSUE TITLE
Add sys.BUILDARCHSUFFIX preprocessor variable

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7227]
* Describe the scenario and benefits that the feature supports.

> We have suffixes in extension custom actions to handle architecture-specific custom action and binary ids. There should be a preprocessor shortcut to help.

* Describe how you're accomplishing the feature today (if possible).

```xml
<?if $(sys.BUILDARCH) ~= "x86" ?>
  <?define UTILCA_ARCH = "_X86" ?>
<?elseif $(sys.sys.BUILDARCH) ~= "x64" ?>
  <?define UTILCA_ARCH = "_X64" ?>
<?elseif $(sys.sys.BUILDARCH) ~= "arm64" ?>
  <?define UTILCA_ARCH = "_A64" ?>
<?else?>
  <?error Unknown architecture: $(sys.BUILDARCH) ?>
<?endif?>
```

* Describe what you'd like the new feature to do.

> A `sys.BUILDARCHSUFFIX` preprocessor variable would do the equivalent of the above.

**Comment by barnson** [comment]
https://github.com/wixtoolset/wix4/pull/359

**Comment by robmen** [comment]
If we don't add the `_` could the value be used in more situations? Of course, in those places that use `_<suffix>` they could put the underscore back in. Just an idea.

**Comment by barnson** [comment]
:shrug: Not opposed.

**Comment by barnson** [comment]
Need better name...

**Comment by barnson** [comment]
Implemented in https://github.com/wixtoolset/wix4/pull/359.
