### ISSUE TITLE
Hyperlink component doesn't work the 3.x way and no documentation for 4.x seems to exist

### ISSUE THREAD

**Issue by BPodszun** [wixtoolset/issues#7235]
If this issue is a bug:

* Which version of WiX are you building with?

4.0.0-rc.2

* Which version of Visual Studio are you building with (if any)?

Version 17.4.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

FireGiant HeatWave   0.9.4.1

* Which version of .NET are you building with?

4.8.09032

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

n/a (but Win11)

* Describe the problem and the steps to reproduce it.

I'm trying to show a control with a hyperlink. Every example I find (arguably made hard due to the competing wix dot com product ranking much higher for "hyperlinks" etc) suggests to

* Use a `Control` with `type` Hyperlink
* Use a formatted HTML fragment for the text, like `<a href="example.com">Foo</a>`
* Since some of these characters don't belong in attributes, use a `<Text>` and add the fragment there (CDATA protected)

```
		  <Control Id="SomeLink" Type="Hyperlink" X="20" Y="150" Width="290" Height="18">
			  <Text>HereWouldBeTheHyperLink</Text>
		  </Control>
```

* Describe the behavior you expected and how it differed from the actual behavior.

I'd expect a label with a Hyperlink (knowing of the 500 version limitation)

Instead I get a warning (not great, but fine):

Warning		The element cannot contain text. Content model is empty

and a build error, killing the idea completely (not fine):

WIX0400	The Text element contains inner text which is obsolete. Use the Value attribute instead.

**Comment by barnson** [comment]
The error message tells you what to do (`Use the Value attribute instead.`).

And the documentation exists:
- https://wixtoolset.org/docs/reference/schema/wxs/control/
- https://wixtoolset.org/docs/reference/schema/wxs/text/

**Comment by BPodszun** [comment]
Thank you for replying. Unfortunately neither of these links help (or seem applicable)

From your first link, for `Control` it lists the following under the section Children (emphasis is mine)

> [Text](https://wixtoolset.org/docs/reference/schema/wxs/text/) (no more than 1) : alternative to Text **attribute** when CDATA is needed to escape XML delimiters

Your second link describes `Text` as (emphasis again mine) "An alternative to using the Text **attribute** on the Control element."

My way of reading this: Use `Text` if you CANNOT use the Text attribute/when you need to CDATA escape your text. Like.. for a hyperlink. I left the actual content out in the first message because it seemed not relevant, but a more realistic example of what I want to do would be

```
<Control Id="Link1" Type="Hyperlink" X="135" Y="250" Width="220" Height="18">
      <Text><![CDATA[<a href="http://www.example.com/">Click here!</a>]]></Text>
</Control>
```

At this point I'm having still multiple questions.

1) How would you actually use a Hyperlink type of control in Wix4 today (given that the way above using `Text` doesn't work anymore)

2) What is the actual use case of a `Text` if it is limited to its attributes now? It seems the documentation still implies that it is for scenarios where `<Control Text="Foo" />` doesn't work for you. But what's the point of changing this to `<Control><Text Value="Foo" /></Control>` here? It's _still_ an attribute, what is gained by using `Text` at all?

3) The actual documentation you linked me to explicitly refers to CDATA escaped values. Those **CANNOT** go into an attribute. The documentation therefor seems at least to be inconsistent with what is possible, no?

**Comment by robmen** [comment]
1. Like so: `<Control Id="Link1" Type="Hyperlink" X="135" Y="250" Width="220" Height="18" Text='%lt;a href="http://www.example.com/">Click here!&lt;/a>' />`

2. That's a good point. We could remove the `Text` element's `Value` attribute. It adds no extra value over the `Control` element's `Text` attribute because it cannot contain `CDATA`. Probably won't make that change in WiX v4.

3. The doc on the `Control` page has a bug. It should not mention `CDATA` at all. Any reference to `CDATA` is a bug (I found a couple of others).
