### ISSUE TITLE
RemoveFolderEx: Failed to open view on Wix4RemoveFolderEx table

### ISSUE THREAD

**Issue by jansohn** [wixtoolset/issues#7236]
* Which version of WiX are you building with?

> 4.0.0-rc.2

* Which version of Visual Studio are you building with (if any)?

> Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.4.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> FireGiant HeatWave   0.9.4.1

* Which version of .NET are you building with?

> .NET Framework 4.8

* Describe the problem and the steps to reproduce it.

> I'm trying to use `RemoveFolderEx` from the util extension to clean-up directory on uninstallation. The MSI package is in fixed scope `perUser` and I'm installing it to `LocalAppDataFolder`. From the uninstall log file I can see that it is failing:

    MSI (s) (CC:70) [14:11:42:674]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIA34E.tmp, Entrypoint: WixRemoveFoldersEx
    MSI (s) (CC:4C) [14:11:42:675]: Generating random cookie.
    MSI (s) (CC:4C) [14:11:42:686]: Created Custom Action Server with PID 19880 (0x4DA8).
    MSI (s) (CC:30) [14:11:42:760]: Running as a service.
    MSI (s) (CC:30) [14:11:42:764]: Hello, I'm your 64bit Impersonated custom action server.
    MSI (s) (CC!2C) [14:11:42:776]: Note: 1: 2237 2:  3: SELECT `Wix4RemoveFolderEx`, `Component_`, `Property`, `InstallMode`, `Wix4RemoveFolderEx`.`Condition`, `Component`.`Attributes`FROM `Wix4RemoveFolderEx``,`Component` WHERE `Wix4RemoveFolderEx`.`Component_`=`Component`.`Component` 4:  
    Action start 14:11:42: Wix4RemoveFoldersEx_X64.
    WixRemoveFoldersEx:  Error 0x8007064f: failed to open view on database
    WixRemoveFoldersEx:  Error 0x8007064f: Failed to open view on Wix4RemoveFolderEx table
    CustomAction Wix4RemoveFoldersEx_X64 returned actual error code 1603 but will be translated to success due to continue marking

> The fragment I'm using:

    <?include Config.wxi ?>
    <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs"
         xmlns:util="http://wixtoolset.org/schemas/v4/wxs/util">
      <Fragment>
        <Property Id="INSTALLFOLDER_PROP" Secure="yes">
            <RegistrySearch Id="APPLICATIONFOLDER_REGSEARCH"
                    Root="HKCU"
                    Key="SOFTWARE\$(var.Manufacturer)\$(var.ProductName)"
                    Type="raw"
                    Name="Path" />
        </Property>
        <Component Id="CleanUpDirectories" Directory="INSTALLFOLDER">
            <RegistryValue Root="HKCU"
                    Key="SOFTWARE\$(var.Manufacturer)\$(var.ProductName)"
                    Name="Path"
                    Type="string"
                    Value="[INSTALLFOLDER]"
                    KeyPath="yes" />
            <util:RemoveFolderEx On="uninstall" Property="INSTALLFOLDER_PROP" />
        </Component>
      </Fragment>
    </Wix>

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect the folder referenced by `INSTALLFOLDER_PROP` to get deleted even if it contains files/folders which are not part of the initial installation file.

**Comment by jansohn** [comment]
Thanks for the quick fix! Any way I can test/use this before the next pre-release?

**Comment by robmen** [comment]
Why, yes there is [Install a WiX v4 dev build](https://youtu.be/2iIjq6zt6z0).

**Comment by jansohn** [comment]
> Why, yes there is [Install a WiX v4 dev build](https://youtu.be/2iIjq6zt6z0).

Got it, thanks. Maybe you can add the source repository URL somewhere in the documentation? And link to your Youtube video for people needing more precise instructions.

This works now as expected with the latest build `4.0.0-rc.3-build.36`.

**Comment by robmen** [comment]
@jansohn sounds like a great thing for you to contribute. You've just gone through the experience of trying to find the information. Help the next person by writing down the information you just learned in the right place. It's harder for me... I already knew the answer. 😄

**Comment by jansohn** [comment]
Well, I'm not sure where you would like me to put it. Here? https://github.com/wixtoolset/wix4/blob/develop/README.md

**Comment by robmen** [comment]
Yeah, where to put it is the hard part. That's why I asked you. Where would you have found it naturally? wixtoolset.org will get picked up better by search engines... but maybe README works (although it's primarily about building WiX).

**Comment by jansohn** [comment]
wixtoolset.org is probably the better place. I would add a new topic "Development builds" tomorrow if you're fine with it.

**Comment by robmen** [comment]
I agree about wixtoolset.org so let's see how it looks. I expect Bob will have opinions (especially if you think it needs a whole new page) on whatever PR you send.

**Comment by barnson** [comment]
At first glance, I'd say it could go at the bottom of https://github.com/wixtoolset/web/blob/master/src/Docusaurus/docs/intro.md. The high-order bit is configuring your feed; that applies to both the dotnet tool and MSBuild SDK.
