### ISSUE TITLE
WIP: Support multi-targeting ProjectReferences from a .wixproj

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#7241]
## User stories

* As a setup developer, I can reference a .NET SDK project that targets multiple frameworks and runtime identifiers from a .wixproj to include the correct subset of files.

* As a setup developer, I can reference any project that supports multiple configurations and/or platforms from a .wixproj to include the correct subset of files.

## Proposal

WiX v4 automatically creates bind paths for `ProjectReferences`. In the simple and most common cases, this is a very simple addition where:

    <ProjectReference Include="..\..\path\to\SomeOther.csproj" BindName="SomeOther" />

Is made available as `!(bindpath.SomeOther)`. The `BindName` metadata is redundant in this case as it defaults to the name of the project reference's project file.

However, when the referenced project is a multi-targeting project (sets the `TargetFrameworks` Property) MSBuild does not return the target path of the project, breaking the feature. The workaround is to reference the project multiple times and set an explicit target framework like:

    <ProjectReference Include="..\..\path\to\SomeOther.csproj" SetTargetFramework="TargetFramework=net48"
                      BindName="SomeOther.net48" />
    <ProjectReference Include="..\..\path\to\SomeOther.csproj" SetTargetFramework="TargetFramework=net6.0"
                      BindName="SomeOther.net6.0" />

Note the `BindName` must be specified now because many files with the same name will be built to the two different target framework locations. This is doable if a bit ugly. But modern .csproj's can also target multiple runtime identifiers (e.g. `win-x86`, `win-x64`, `win-arm64`), which multiplies each target framework. If both `win-x86` and `win-x64` are desired, there end up with four project references:

    <ProjectReference Include="..\..\path\to\SomeOther.csproj" SetTargetFramework="TargetFramework=net48"
                      Properties="RuntimeIdentifier=win-x86" BindName="SomeOther.net48.win_x86" />
    <ProjectReference Include="..\..\path\to\SomeOther.csproj" SetTargetFramework="TargetFramework=net48"
                      Properties="RuntimeIdentifier=win-x64" BindName="SomeOther.net48.win_x64" />
    <ProjectReference Include="..\..\path\to\SomeOther.csproj" SetTargetFramework="TargetFramework=net6.0"
                      Properties="RuntimeIdentifier=win-x86" BindName="SomeOther.net6.0._winx86" />
    <ProjectReference Include="..\..\path\to\SomeOther.csproj" SetTargetFramework="TargetFramework=net6.0"
                      Properties="RuntimeIdentifier=win-x64" BindName="SomeOther.net6.0.win_x64" />

This quickly gets out of control.

It is also common for .wixproj's to reference projects that target multiple platforms (such as `Win32`, `x64` and `ARM64` in .vcxprojs). Again, it is possible to duplicate the `ProjectReference` and modify one piece of metadata to change the `Platform` for each reference. But what if we had a more concise way to specifiy the modifiers on `ProjectReference` items in a .wixproj? We might do something like:

    <ProjectReference Include="..\..\path\to\SomeOther.csproj" TargetFrameworks="net48,net6.0" RuntimeIdentifiers="win-x86,win-x64" />
    <ProjectReference Include="..\..\path\to\NativeCode.vcxproj" Configurations="Debug,Release" Platforms="Win32,X64,ARM64" />

Notice the `NativeCode.vcxproj` reference specifies multiple configurations as well as platforms. This example is a bit contrived for illustrative purposes as it isn't common to include both `Debug` and `Release` bits in the same installation package. The end result is that the .wixproj will build a total of 10 referenced projects like so:

* SomeOther.csproj TargetFramework=net48, RuntimeIdentifier=win-x86, BindName=SomeOther.net48.win_x86
* SomeOther.csproj TargetFramework=net48, RuntimeIdentifier=win-x86, BindName=SomeOther.net48.win_x86
* SomeOther.csproj TargetFramework=net6.0, RuntimeIdentifier=win-x86, BindName=SomeOther.net6.0.win_x86
* SomeOther.csproj TargetFramework=net6.0, RuntimeIdentifier=win-x64, BindName=SomeOther.net6.0.win_x64
* NativeCode.vcxproj Configuration=Debug, Platform=Win32, BindName=SomeOther.Debug.Win32
* NativeCode.vcxproj Configuration=Debug, Platform=X64, BindName=SomeOther.Debug.X64
* NativeCode.vcxproj Configuration=Debug, Platform=ARM64, BindName=SomeOther.Debug.ARM64
* NativeCode.vcxproj Configuration=Release, Platform=Win32, BindName=SomeOther.Release.Win32
* NativeCode.vcxproj Configuration=Release, Platform=X64, BindName=SomeOther.Release.X64
* NativeCode.vcxproj Configuration=Release, Platform=ARM64, BindName=SomeOther.Release.ARM64

Notice the `BindName` by default is composed from the provided metadata in the following order `<ProjectName>[.<Configuration>][.<Platform>][.<TargetFramework>][.<RuntimeIdentifier>]`. While, it is possible to specify all of the `Configurations`, `Platforms`, `TargetFrameworks`, and `RuntimeIdentifiers` metadata that isn't expected to be normal use.

## Considerations

* This feature is syntactic sugar and while not strictly necessary it _significantly_ reduces the number and complexity of project references when referencing multi-targeting projects from a .wixproj.

## See Also

* #5705
* #7149

**Comment by Sundow** [comment]
This issue description helped me a lot when I was looking for my multi-targetion project + WiX 4 issues. Thanks!

Is there a similar solution for HarvestProject? After I changed a project so that it become multi-targeted harvesting fails with the following error:
heat.exe : error HEAT5313: Build error during harvesting: MyProject.csproj : error MSB4057: The target "BuiltProjectOutputGroup" does not exist in the project.

**Comment by robmen** [comment]
No. #6838 is relevant.
