### ISSUE TITLE
LicenseAgreementDlg Print button does not have an event defined

### ISSUE THREAD

**Issue by kbhanley** [wixtoolset/issues#7249]
Which version of WiX are you building with?

4.0.0-rc.3

Which version of Visual Studio are you building with (if any)?

VS2022

Describe the problem and the steps to reproduce it.

"PushButton: 'Print' of Dialog: 'LicenseAgreementDlg' does not have an event defined in the ControlEvent table. It is a 'Do Nothing' button."	

I recently upgraded our wix installer from version 3.14 to 4.0 using the latest pre-release Nuget package and HeatWave tools. After the conversion, I am receiving an error for the 'Print' PushButton control on the LicenseAgreementDlg dialog (see above). I have attempted to manually add the event used in wix3 - "WixUIPrintEula" - but it tells me it can't find the specified event.

Describe the behavior you expected and how it differed from the actual behavior.

Based on the functionality/behavior of the control in version 3, I expected the event to either exist to manually add on to the control, or already added by default to the control.

**Comment by barnson** [comment]
This doesn't repro with the built-in dialog sets. If you're using a customized dialog set, can you share a GitHub repo that repros the problem?

**Comment by kbhanley** [comment]
Below is our UI Fragment that produces the error:

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:ui="http://wixtoolset.org/schemas/v4/wxs/ui">

  <?include $(sys.CURRENTDIR)Includes\GlobalInclude.wxi ?>
  <?include $(var.ApplicationArtifactPath)\AssemblyVersionInclude.wxi ?>

  <Fragment>
        <UI Id="MyWixUI_Mondo">

            <ui:WixUI Id="WixUI_Common" />
			
            <TextStyle Id="WixUI_Font_Normal" FaceName="Tahoma" Size="8" />
            <TextStyle Id="WixUI_Font_Normal_Bold" FaceName="Tahoma" Size="8" Bold="yes" />
            <TextStyle Id="WixUI_Font_Bigger" FaceName="Tahoma" Size="12" />
            <TextStyle Id="WixUI_Font_Title" FaceName="Tahoma" Size="9" Bold="yes" />

            <Property Id="DefaultUIFont" Value="WixUI_Font_Normal" />
            <Property Id="WixUI_Mode" Value="Mondo" />

            <DialogRef Id="ErrorDlg" />
            <DialogRef Id="FatalError" />
            <DialogRef Id="FilesInUse" />
            <DialogRef Id="MsiRMFilesInUse" />
            <DialogRef Id="PrepareDlg" />
            <DialogRef Id="ProgressDlg" />
            <DialogRef Id="ResumeDlg" />
            <DialogRef Id="UserExit" />

            <Publish Dialog="ExitDialog" Control="Finish" Event="EndDialog" Value="Return" Order="999" />

            <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="LicenseAgreementDlg" Condition="NOT Installed AND NOT PATCH" />
            <Publish Dialog="WelcomeDlg" Control="Next" Event="NewDialog" Value="MaintenanceTypeDlg" Condition="Installed AND PATCH" />

            <Publish Dialog="LicenseAgreementDlg" Control="Back" Event="NewDialog" Value="WelcomeDlg" />
            <Publish Dialog="LicenseAgreementDlg" Control="Next" Event="NewDialog" Value="SetupTypeDlg" Order="2" Condition="LicenseAccepted = &quot;1&quot;" />

            <Publish Dialog="SetupTypeDlg" Control="Back" Event="NewDialog" Value="LicenseAgreementDlg" />
            <Publish Dialog="SetupTypeDlg" Control="TypicalButton" Event="NewDialog" Value="VerifyReadyDlg" />
            <Publish Dialog="SetupTypeDlg" Control="CustomButton" Event="NewDialog" Value="CustomizeDlg" />
            <Publish Dialog="SetupTypeDlg" Control="CompleteButton" Event="NewDialog" Value="VerifyReadyDlg" />

            <Publish Dialog="CustomizeDlg" Control="Back" Event="NewDialog" Value="MaintenanceTypeDlg" Order="1" Condition="WixUI_InstallMode = &quot;Change&quot;" />
            <Publish Dialog="CustomizeDlg" Control="Back" Event="NewDialog" Value="SetupTypeDlg" Order="2" Condition="WixUI_InstallMode = &quot;InstallCustom&quot;" />
            <Publish Dialog="CustomizeDlg" Control="Next" Event="NewDialog" Value="VerifyReadyDlg" />

			<Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="MaintenanceTypeDlg" Order="1" Condition="WixUI_InstallMode = &quot;Change&quot;" />
			<Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="CustomizeDlg" Order="2" Condition="WixUI_InstallMode = &quot;InstallCustom&quot;" />
			<Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="SetupTypeDlg" Order="3" />

			<Publish Dialog="MaintenanceWelcomeDlg" Control="Next" Event="NewDialog" Value="MaintenanceTypeDlg" />

            <Publish Dialog="MaintenanceTypeDlg" Control="ChangeButton" Event="NewDialog" Value="CustomizeDlg" />
            <Publish Dialog="MaintenanceTypeDlg" Control="RepairButton" Event="NewDialog" Value="VerifyReadyDlg" />
            <Publish Dialog="MaintenanceTypeDlg" Control="RemoveButton" Event="NewDialog" Value="VerifyReadyDlg" />
            <Publish Dialog="MaintenanceTypeDlg" Control="Back" Event="NewDialog" Value="MaintenanceWelcomeDlg" />
        </UI>
			  
    </Fragment>
</Wix>

**Comment by kbhanley** [comment]
I found that the action changed to an architecture specific action name, so adding in the following line fixes the error:

<Publish Dialog="LicenseAgreementDlg" Control="Print" Event="DoAction" Value="WixUIPrintEula_X86" />

**Comment by kbhanley** [comment]
I found that the action name changed to an architecture specific name, so adding the following line fixes the error:

`<Publish Dialog="LicenseAgreementDlg" Control="Print" Event="DoAction" Value="WixUIPrintEula_X86" />`

**Comment by barnson** [comment]
You can use `$(sys.BUILDARCHSHORT)` instead of hard-coding x86. There's a placeholder for doc to help convert UI customizations.

**Comment by Captnwalker1** [comment]
In Wix3 no custom event was needed, can this be the default but overridable?

**Comment by barnson** [comment]
https://wixtoolset.org/docs/fourthree/#converting-custom-wixui-dialog-sets
