### ISSUE TITLE
Prerequisites (other than .NET) from winget using id and version

### ISSUE THREAD

**Issue by Wallby** [wixtoolset/issues#7262]
## Feature requests

E.g...
1. install a .dll using winget (e.g. KhronosGroup.VulkanSDK)
2. add a prerequisite by referencing the id (e.g. KhronosGroup.VulkanSDK) and version (range) (e.g. >=1.2.10 and <=1.3.100) of a package similar to how .NET can be a prerequisite[1]

I.e. instead of inserting the .dll in every package allow for a winget reference.

For the Vulkan SDK example they could properly support this if the VULKAN_SDK environment variable wasn't defined as [ProgramFilesFolder]\VulkanSDK\1.3.231.1 but as [ProgramFilesFolder]\VulkanSDK and than the program selecting the version folder.

[1] https://wixtoolset.org/docs/v3/howtos/redistributables_and_install_checks/install_dotnet/

**Comment by barnson** [comment]
It's not clear what you're looking for. My guess is that you want Burn to be able to treat WinGet as a download source. But it's not clear how that fits in with your listed examples. Please clarify and we can re-triage.

**Comment by Wallby** [comment]
> It's not clear what you're looking for. My guess is that you want Burn to be able to treat WinGet as a download source. But it's not clear how that fits in with your listed examples. Please clarify and we can re-triage.

I think might be unclear due to my lack of understanding of how different versions of programs are handled in windows.
.NET uses a program per version right? Thus multiple versions would, unlike as it is in linux, be entirely up to the implementation support or not?
From my experience as a user of programs on windows it seems that the common approach is if a version of an installed program is not supported for the program to present an error and stop the program?

A winget package contains an "InstallerUrl" ([example](https://github.com/microsoft/winget-pkgs/blob/master/manifests/o/OBSProject/OBSStudio/29.0.2/OBSProject.OBSStudio.installer.yaml#L23)) thus, if I understand how this works in wix correctly, instead of specifying a "DownloadURL=" for MsiPackage/ExePackage (as done [here](https://wixtoolset.org/docs/v3/bundle/authoring_bundle_package_manifest/)) there would be a "DownloadWingetID=" or something instead?

Advantage would be that if a developer changes to a different host they can change the URL in winget without breaking the current distributed installers?

Also a note from the [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) repository about which types of installers are supported..
> Note: At this time installers must be MSIX, MSI, APPX, or .exe application installers. Script-based installers and fonts are not currently supported.

**Comment by Wallby** [comment]
I editted the issue description.

**Comment by Wallby** [comment]
On the winget side there's apparently work on this as well, not sure if would be relevant.. https://github.com/microsoft/winget-cli/issues/163
