### ISSUE TITLE
Microsoft .NET Framework required message instead of custom BA when it is already present

### ISSUE THREAD

**Issue by pybride** [wixtoolset/issues#7263]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

4.0.0-rc.3

* Which version of Visual Studio are you building with (if any)?

17.5.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

0.9.5

* Which version of .NET are you building with?

6 (custom BA in .NET 4.8)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

11

* Describe the problem and the steps to reproduce it.

bal:PrereqPackage=yes is mandatory when using WixManagedBootstrapperApplicationHost.  Without declaring any .Net Framework package, I still get the "Microsoft .NET Framework required for ..." instead of my custom BA.

With Wix 3, I can just put:
<WixVariable Id="WixMbaPrereqPackageId" Value=""/>

and then the bundle is starting my custom .net 4.8 BA fine, as it is installed on any modern Windows.

* Describe the behavior you expected and how it differed from the actual behavior.

Launch my custom BA like wix 3 without bothering to install an unneeded .Net Framework.

**Comment by barnson** [comment]
Please post actual authoring and the resulting logs showing the error.

**Comment by pybride** [comment]
[1FD0:1090][2023-03-08T15:44:46]e000: Error 0x8007006e: Failed to load bootstrapper config file from path: C:\Windows\TEMP\{719EDA87-18B8-46AB-8975-3A45E27DBCB2}\.ba\WixToolset.Mba.Host.config
[1FD0:1090][2023-03-08T15:44:46]e000: Error 0x8007006e: Failed to find supported framework.
[1FD0:1090][2023-03-08T15:44:46]i000: Loading prerequisite bootstrapper application because managed host could not be loaded, error: 0x8007006e.

For the wxs, I have:

`<BootstrapperApplication>
<Payload SourceFile="xxxx" />
<WixManagedBootstrapperApplicationHost xmlns="http://wixtoolset.org/schemas/v4/wxs/bal" />
</BootstrapperApplication>		
		<Chain>			
			<PackageGroupRef Id="PGRP_SqlExpressUpgrade" />
			<PackageGroupRef Id="PGRP_SqlExpressInstall" />
			<PackageGroupRef Id="PGRP_vcredist_14" />
			<RollbackBoundary />
			<MsiPackage Id="PKG_visionCATS" Name="visionCATS Package" Cache="remove" Visible="no" SourceFile="$(var.VisionInstaller.TargetPath)" ForcePerMachine="yes" bal:PrereqPackage="yes">
				
			</MsiPackage>
		</Chain>
	</Bundle>`

Difference with the working bundle in WIX3 is the new `bal:PrereqPackage="yes"` and the now missing:
`<WixVariable Id="WixMbaPrereqLicenseUrl" Value=""/>
		<WixVariable Id="WixMbaPrereqPackageId" Value=""/>`

**Comment by pybride** [comment]
1. Why I need to add as payload WixToolset.Mba.Host.config? It is something internal to WIX, and I don't see any wxs on wix4 repo having that.

1. We don't support modified Windows installation

**Comment by robmen** [comment]
1. There are many examples of `WixToolset.Mba.Host.config` in the `wix4` repo.
2. Okay, but that doesn't make your v3 .wxs code correct.

**Comment by pybride** [comment]
![image](https://user-images.githubusercontent.com/13061922/223975382-97eab191-3d2c-4e9f-acad-c567e0fc8c83.png)

I cannot find them

**Comment by robmen** [comment]
![image](https://user-images.githubusercontent.com/131904/223975921-e0995901-844b-4d6e-8d7a-9e8114a2103d.png)
