### ISSUE TITLE
wix4 not compatible with esproj

### ISSUE THREAD

**Issue by mistoll** [wixtoolset/issues#7277]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

4.0.0-rc3

* Which version of Visual Studio are you building with (if any)?

17.5

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

HeatWave 0.9.4

* Which version of .NET are you building with?

.NET 6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Does not apply.

* Describe the problem and the steps to reproduce it.

When a ProjectReference to an esproj file is in the installer project the build fails with the message 

> wix.exe : error WIX0280: The -bindPath option requires a directory, but the provided path is a file: ...\reactproject1.esproj

The esproj tempates are pretty new. There's few information about them ( https://learn.microsoft.com/en-us/visualstudio/javascript/javascript-in-visual-studio?view=vs-2022 )

To reproduce (See attatched file):
1) Create new solution with Standalone React App
2) Add WIX4 MSI project
3) Add reference from MSI to React
4) Build MSI

* Describe the behavior you expected and how it differed from the actual behavior.

In WIX 3 the ProjectReference to the esproj file did not cause an error. I expect that the ProjectReference adds a build order dependency (ok). And build without an error (not ok).

While it would be nice to have, I do NOT expect that the esproj is harvested or wix project variables are set.
[reactproject1.zip](https://github.com/wixtoolset/issues/files/10978859/reactproject1.zip)

**Comment by robmen** [comment]
The .esproj project type has a buggy `GetTargetPath` implementation. It is returning `path\to\ProjectName.esproj\ProjectName.exe`. That is obviously not a valid path as a file cannot be the parent of a file. Probably a good idea to open a bug against the owners of the `.esproj` implementation.

You can work around their bug in WiX v4-rc.3 by adding a `BindPath` metadata value to the .esproj `ProjectReference` in the .wixproj and provide a valid path.

WiX v4-rc.4 will defend against this bug in other project types.
