### ISSUE TITLE
Wix4 Bundle Projects don't handle Reference Projects with Spaces in the Name

### ISSUE THREAD

**Issue by ld0614** [wixtoolset/issues#7286]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0-rc.3

* Which version of Visual Studio are you building with (if any)?

> 17.5.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave 0.9.5.1

* Which version of .NET are you building with?

> 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 22H2 22621.1265

* Describe the problem and the steps to reproduce it.

>  Solution has 3 Projects:
> - Bundle Installer (WIX Bundle Package)
> - Client Installer (WIX MSI Package)
> - Client Application (.Net 4.6.1 project)
> 
> Client Installer can successfully access Client Application References by using $ (ClientApplication.TargetPath) (When correctly cross-referenced) however Bundle Installer fails with unknown preprocessor variable. Attempting to use $(Client Application.TargetPath) also fails
> 
> Removing the space from Client Application project to make it ClientApplication enables the Bundle Installer successfully reference the project. 

* Describe the behavior you expected and how it differed from the actual behavior.

> Ideally the Bundle Preproccessor should remove spaces from project names automatically in the same way that the MSI Package does or the way to correctly reference these projects should be documented in https://wixtoolset.org/docs/reference/msbuild/project-references/

**Comment by robmen** [comment]
Can you provide a link to a GitHub repo with the example of the actual .csproj and .wixproj names and `ProjectReferences` you're using? That will make it crystal clear what you are doing.

Additionally, attaching a .binlog to the issue can be helpful.

**Comment by ld0614** [comment]
Hi Rob, thanks for looking into this, I've created a sample project at https://github.com/ld0614/WixBundle to give you a bit more of an idea as to what I'm looking at. I tried to recreate the issue even using a normal v4 MSI package and hit issues so it appears that a space in a project name is the exception rather than the rule.

In the project that is working, I noticed a Project Reference which I assume is being left over from the v3 build process
![image](https://user-images.githubusercontent.com/20439950/226482700-60d5b0e2-9aa6-4eb0-a036-0818ade0f992.png)

In the relevant .wxs file I have the following
![image](https://user-images.githubusercontent.com/20439950/226482924-debcbf6f-3a4d-4e16-9130-b8e2a55480b1.png)

And the project view looks like
![image](https://user-images.githubusercontent.com/20439950/226482976-0cea1499-2f76-4ec0-82b3-c1ca619c8ca7.png)

I appreciate that having spaces in project names is probably not considered good practice and I've been able to rename the projects to avoid the spaces to get the bundle working so it won't impact me on this project so I'm happy to close the issue or continue investigating if you'd like to understand how this has happened. If it is closed as 'wontfix' it might be worth adding a note about this issue in the document to avoid anyone else who stumbles across this issue going around in circles like I did for a while 😄

**Comment by ld0614** [comment]
Also I'm happy to get you a bin log but I'm not sure how to generate one/where they are stored?

**Comment by robmen** [comment]
You can create a binlog by using `msbuild -bl` from the command-line. That will create a `msbuild.binlog` in the same directory. It is a great resource to understand what is going on in the build.

Thank you for the test repository. That cleared up a lot. Here's what I see:

1. WiX v3 used by `ClientApp1 v3 Installer.wixproj` creates preprocessor defines with spaces in it. Those are unusable. The fact that no one has hit this in many, many years says this is uncommon at best (or users simply "fix" the project name to work around it).

2. WiX v4 used by `ClientApp2Installer.wixproj`, `ClientApp1 Installer.wixproj`, and `BundleInstaller.wixproj` replace invalid characters in preprocessor names (including spaces) with underscores.

The information in that last sentence would probably be good to have in the documentation.

**Comment by mwileczka** [comment]
Is this documented anywhere? I had a v3 project with similar references and then when converted everything failed because the project names had spaces. This worked in v3 and should have been noted in the upgrade guide (or fixed in the converter). Also, I hard time finding anything on using this feature. Not sure where I got the info for v3 (guessing google search) but it seems like there should be a section in the preprocessor manual about utilizing the project references and things like TargetFileName, etc. Related topic, why is there no search feature for the help? (in case it was there but I just couldn't find it)
