### ISSUE TITLE
PrereqLicenseFile won't compile despite PrereqPackage attribute being set

### ISSUE THREAD

**Issue by ld0614** [wixtoolset/issues#7287]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Thursdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are sent to the [wix-devs](http://wixtoolset.org/documentation/mailinglist/#wix-devs) and wix-users mailing lists, as well as in Discussions.

## Discussions and support

Note that discussions are best held on the mailing lists not in issues. Please do not open issues requesting support or debugging help; first start a thread on the [wix-users](http://wixtoolset.org/documentation/mailinglist/#wix-users) mailing list and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate. You can also try out the beta [Discussions](https://github.com/wixtoolset/issues/discussions?discussions_q=category%3AQuestions) feature.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0-rc3

* Which version of Visual Studio are you building with (if any)?

> 17.5.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Heatwave 0.9.5.1

* Which version of .NET are you building with?

> 4.6.1

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 22H2 22621.1265

* Describe the problem and the steps to reproduce it.

> Within a Bundle Project I have 2 MSI Packages and the UI configured to WixInternalUIBootstrapperApplication
> - I would like the initial PreReq UI to have the license terms Link go to a webpage
> - I would then like the main UI of the second MSI to launch to complete the installation

> When I set the value bal:PrereqLicenseFile on the first MSIPackage I get the build error:
> Error WIX6801: When the MsiPackage/@PrereqLicenseFile attribute is specified, the MsiPackage/@PrereqPackage attribute must be set to "yes".

This is despite the actual package being previously configured with this attribute so the Package description looks like
```
                        <MsiPackage Visible="yes"
						Cache="remove"
		                                ForcePerMachine="yes"
						Permanent="yes"
						bal:PrereqPackage="yes"
						bal:PrereqLicenseFile="https://www.mysite.com/prereqterms"
						Vital="yes">
				<MsiPackagePayload
					DownloadUrl="https://www.mysite.com/downloadlink"
					SourceFile="PreReqs\prereqapp.msi"
					Compressed="no"
				/>
				<MsiProperty Name="MYVALUE" Value="YES"/>
			</MsiPackage>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> My understanding is that with the above configuration the installer should compile and the hyperlink in the UI should go to https://www.mysite.com/prereqterms when clicked

**Comment by rseanhall** [comment]
This is a bug. You can work around it for now by putting the `bal:PrereqPackage` attribute after the license attribute. Note that you'll want `bal:PrereqLicenseUrl` instead.

**Comment by ld0614** [comment]
Thanks for the workaround and spotting I was about to use the wrong attribute 🙂
