### ISSUE TITLE
Heatwave 0.9.5 VS build event macros are not expanded in bundle projects

### ISSUE THREAD

**Issue by QuickWire** [wixtoolset/issues#7297]
* Which version of WiX are you building with?

> 4.0.0-rc.4

* Which version of Visual Studio are you building with (if any)?

> VS 2022 v17.5.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Heatwave for VS 2022 v0.9.5

* Which version of .NET are you building with?

> Just using simple Bundle project using bal:WixStandardBootstrapperApplication with slightly modified HyperlinkTheme.xml

* Describe the problem and the steps to reproduce it.

> I have a simple post build event running something like this:

>`copy /y "$(TargetDir)en-us\$(TargetFileName)" "$(TargetDir)en-us\$(TargetName)_x64$(TargetExt)"`

* Describe the behavior you expected and how it differed from the actual behavior.

> I expect the VS macros to expand and the copy command to complete without errors but this is the response:

>`error MSB3073: The command "copy /y "en-us\" "en-us\_x64"" exited with code 1.`

>As you can see the command ran but the macros did not expand.  Since they were stripped out I assume the VS macros were empty for some reason at the time of expansion.
>* This works fine with my new v4 MSI projects.

**Comment by robmen** [comment]
Please provide a link to a repository with .wixprojs that demonstrates this problem.

**Comment by robmen** [comment]
Quick guess (without knowing exactly how you structured your .wixproj) is that you need to use the [explicit Sdk-style imports](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022#use-the-import-element-anywhere-in-your-project) and place the post-build event after the `.targets` import. There are other ways to address this in MSBuild as well.

**Comment by QuickWire** [comment]
Yes, I just found this out.  Here's what I did to fix the project:

Original base Heatwave Bundle wixproj:
```
<Project Sdk="WixToolset.Sdk/4.0.0-rc.3">
  <PropertyGroup>
    <OutputType>Bundle</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.Bal.wixext" Version="4.0.0-rc.3" />
  </ItemGroup>
</Project>
```

Changed to:

```
<Project>
    <Import Project="Sdk.props" Sdk="WixToolset.Sdk" Version="4.0.0-rc.3" />
    <PropertyGroup>
         <OutputType>Bundle</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="WixToolset.Bal.wixext" Version="4.0.0-rc.3" />
    </ItemGroup>

    <Import Project="Sdk.targets" Sdk="WixToolset.Sdk" Version="4.0.0-rc.3" />

    <PropertyGroup>
        <PostBuildEvent>copy /y "$(TargetPath)" "$(TargetDir)$(TargetName)_x64$(TargetExt)" </PostBuildEvent>
    </PropertyGroup>
</Project>
```

Sorry I jumped the gun on this, I'm no VS proj skema expert. 
Not sure now if this is really an issue or not.  My v4 MSI projects worked because I ran update on them.

**Comment by robmen** [comment]
HeatWave tries to recognize the use of `PostBuildEvent` and use explicit imports in that scenario. This is the way.

**Comment by QuickWire** [comment]
Hmmm, well the WIX3 project template added a targets import by default. Devs like me that don't realize a targets import is required for build event macro expansion may have issues like I did.

**Comment by robmen** [comment]
WiX v4 adopts the [modern MSBuild Sdk-style projects](https://learn.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2022). You'll want to become familiar with them if you're planning to modify the .wixproj.
