### ISSUE TITLE
Implementing WindowsVolume as StandardDirectoryType

### ISSUE THREAD

**Issue by ramen-pipul** [wixtoolset/issues#7314]
## Feature request

Possibility to specify custom folders directly under Windows partition, like `C:\custom-folder1` in .wxs files, in **wix4**

## Description

One of the breaking changes in wix4 was the implementation of `<StandardDirectory />` to distinct between standard Windows folders and custom, user-defined ones.

The enum `StandardDirectoryType` is missing the `WindowsVolume` value which was, I believe the root path pointing to the Windows partition (C:\ in most scenarios). (see https://wixtoolset.org/docs/schema/wxs/standarddirectorytype/)

On **wix3** this worked by setting `<Directory Id="WindowsVolume" />` as root directory. Currently, setting `<StandardDirectory Id="WindowsVolume" />` complains about not allowed enum value.

## Possible workaround

I don't think there is a workaround for this. The closest one is to specify a directory structure like:
```
<Directory ComponentGuidGenerationSeed="[GENRATED_GUID]" Id="TARGETDIR" Name="SourceDir">
  <Directory Id="INSTALLFOLDER" Name="custom-folder1" />
</Directory>
```

This will however always choose a partition with biggest space available - not the system partition.

**Comment by robmen** [comment]
According to `ICE99` (inspite of the Windows Installer documentation), `WindowsVolume` is not a valid standard directory but a standard property.

You use the value of `WindowsVolume` to set a directory with `SetProperty` or `SetDirectory`.

See issue #7233 where `WindowsVolume` was removed as a standard directory.
