### ISSUE TITLE
Wix4 rc4 Patch creation outputs erroneous warning WIX1097

### ISSUE THREAD

**Issue by narcis-ro** [wixtoolset/issues#7315]
> wix.exe : warning WIX1097: File 'filOAVr9WdxfYzP.BrnMpUPCGIVDh0' in Component 'cmp_ET4oOEcciY.gZfa_J4Ho7PxrHI' was changed, but the KeyPath file 'filOAVr9WdxfYzP.BrnMpUPCGIVDh0' was not. This file will not be patched on the target system if the REINSTALLMODE does not contain 'A'. The KeyPath file should also be changed and included in your patch.

While creating a patch between 2 msi, where a json file has changed, the above warning results. This is due to a small bug in code [here](https://github.com/wixtoolset/wix4/blob/develop/src/wix/WixToolset.Core.WindowsInstaller/Bind/UpdateTransformsWithFileFacades.cs#L422).

Debugging it locally you can easily see that it's just a silly mistake between `FileKey` vs `ComponentId`

![image](https://user-images.githubusercontent.com/51541214/227747059-c55680fc-ef59-4bfe-b7a0-bae26742ad44.png)

With this all modified files in a patch show as warning, although they should be valid changes.

Changing it to, fixes the problem

![image](https://user-images.githubusercontent.com/51541214/227747157-52e22ce3-2be5-4bfc-8b4f-1fa93b44f31b.png)

**Comment by narcis-ro** [comment]
Created PR

**Comment by narcis-ro** [comment]
@robmen Thanks for the quick merge.

As a side question: I’m willing to contribute another PR regarding validation of patches, when files have changed but the version remains the same or the version has downgraded. In both scenarios the files won’t get patched unless there is an “A” in ReinstallMode.

Is this something you would be interested in? I would follow same tests you have written for this issue PR

**Comment by robmen** [comment]
We'll definitely consider more test cases to help with code coverage. We're getting *very* late in the `wix4` timeframe but in the worst case we could take it in the next major version.
