### ISSUE TITLE
Unable to override Next control on dialogs

### ISSUE THREAD

**Issue by kbhanley** [wixtoolset/issues#7321]
Which version of WiX are you building with?

4.0.0-rc.3

Which version of Visual Studio are you building with (if any)?

VS2022

Describe the problem and the steps to reproduce it.

I am attempting to add a dialog between the InstallDirDlg and VerifyReadyDlg using the built in InstallDir dialog set. I have added the publish lines to override the Next control on the InstallDirDlg, as well as the Back control on the VerifyReadyDlg, to the dialog called DatabaseConnectionDlg.

When running the installer, the Next control on the InstallDirDlg will move to the VerifyReadyDlg instead of the DatabaseConnectionDlg, but the Back control on the VerifyReadyDlg correctly moves to the DatabaseConnectionDlg. I have also attempted to use other dialog's Next control, but they still move to the standard dialogs.

Am I missing something?

Below is my Fragment:
```
<Fragment>
		<UI Id="MyWixUI_InstallDir">

			<ui:WixUI Id="WixUI_InstallDir" />

			<Publish Dialog="InstallDirDlg" Control="Next" Event="NewDialog" Value="DatabaseConnectionDlg" Order="4" Condition="WIXUI_DONTVALIDATEPATH OR WIXUI_INSTALLDIR_VALID=&quot;1&quot;" />
				
			<Publish Dialog="DatabaseConnectionDlg" Control="Back" Event="NewDialog" Value="InstallDirDlg" />
			<Publish Dialog="DatabaseConnectionDlg" Control="Next" Event="NewDialog" Value="VerifyReadyDlg" />

			<Publish Dialog="VerifyReadyDlg" Control="Back" Event="NewDialog" Value="DatabaseConnectionDlg" Order="1" Condition="NOT Installed" />
			
		</UI>
	</Fragment>
```

Describe the behavior you expected and how it differed from the actual behavior.

I expect the dialogs to move on to the dialogs specified in the publish value.

**Comment by barnson** [comment]
https://wixtoolset.org/docs/tools/wixext/wixui/#addingremovingdialogs
