### ISSUE TITLE
MsuPackage documentation page misleadingly includes documentation about a Permanent attribute

### ISSUE THREAD

**Issue by icnocop** [wixtoolset/issues#7327]
## Bugs

* Which version of WiX are you building with?
4.0.0-rc.4

* Which version of Visual Studio are you building with (if any)?
N/A
I'm building with the command line.

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
N/A

* Which version of .NET are you building with?
.net 6.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
N/A

* Describe the problem and the steps to reproduce it.

This `MsuPackage` documentation page describes a `Permanent` attribute.

https://wixtoolset.org/docs/schema/wxs/msupackage/

However, if I specify `Permanent="yes"` for example, I get the following error:
`error WIX0004: The MsuPackage element contains an unexpected attribute 'Permanent'.`

For example:
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs"
     xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">
    <Bundle
        Name="My Installer">
        <BootstrapperApplication>
            <bal:WixStandardBootstrapperApplication
                Theme="hyperlinkSidebarLicense"
                LicenseUrl=""
                SuppressOptionsUI="yes"
                ShowVersion="yes" />
        </BootstrapperApplication>
        <Chain>
            <MsuPackage
                Id="MsuPackage1"
                DisplayName="DisplayName"
                Vital="yes"
                Permanent="yes">
                <MsuPackagePayload
                    Hash="..."
                    Size="..."
                    Name="...msu"
                    DownloadUrl="....msu" />
            </MsuPackage>
        </Chain>
    </Bundle>
</Wix>
```

`.\tools\net6.0\any\wix.exe build MyBundle.wxs`
Returned exit code: 4

* Describe the behavior you expected and how it differed from the actual behavior.

I read that an MsuPackage will always be permanent.

If this is true, the page should indicate this.

Also, if I cannot set the `Permanent` attribute, the page should also indicate this by not documenting it as an attribute for example.

Thank you.

**Comment by rseanhall** [comment]
Yes, the attribute has been removed because all MsuPackages are now permanent. It would be great if you clicked on the "Edit the schema for this page" link in that documentation and sent a PR with this update.

**Comment by barnson** [comment]
It's a `ChainPackageCommonAttributes` thing...

**Comment by icnocop** [comment]
> It's a `ChainPackageCommonAttributes` thing...

Right.

The `Permanent` attribute is defined in the attribute group `ChainPackageCommonAttributes`.

The `MsuPackage` includes attributes from `ChainPackageCommonAttributes`.

There are several other elements which also include attributes from `ChainPackageCommonAttributes`, such as `MsiPackage`, `MspPackage`, `ExePackage`, and `BundlePackage`.

I'm not sure if introducing a new element in the schema will cause other things to break, or if duplicating elements is the best approach here.
