### ISSUE TITLE
'nuget' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by icnocop** [wixtoolset/issues#7331]
When following the steps here:
https://github.com/wixtoolset/wix4#developing-wix

and running the command `devbuild.cmd`, I get the following error:
`'nuget' is not recognized as an internal or external command, operable program or batch file.`

When a path to nuget.exe is added to the PATH environment variable, the error no longer occurs.

Also, `MSVC v143 - VS 2022 C++ ARM64 build tools (Latest)` shows up as `MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (Latest)` in Visual Studio 2022 - 17.5.3.

**Comment by BMurri** [comment]
Since the build makes use of the `dotnet`, we may want to consider replacing calls to the `nuget` tool with "dotnet nuget", to eliminate the need to download and add that binary to the path.

**Comment by barnson** [comment]
I doubt it can be completely replaced (there are a couple of packages.config instances, e.g.).

**Comment by robmen** [comment]
Fixed by https://github.com/wixtoolset/wix4/pull/383
