### ISSUE TITLE
NetFx Docs Confusing to me

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7362]
v4

Bearing in mind how MSFT generally rebraded .NET core to .NET and .NET to .NET Framework, it isn't clear to me what the DotNetCompatibilityCheckElement in the NetFx Extension does.

https://wixtoolset.org/docs/schema/netfx/dotnetcompatibilitycheck/

Is this .NET, .NET Framework or both?   The runtime enumeration is aspnet, core, desktop which is the same enum as in DotNetCoreSearch.    If this is for .NET framework, does the ASPNET detect IIS roll services?

Lots of vagueness to me as an outsider here.

**Comment by rseanhall** [comment]
As you might expect, DotNetCoreSearch is for .NET Core, aka .NET 5+, aka not .NET Framework. Same for DotNetCompatibilityCheck, which was contributed by Microsoft employees so naturally they used the confusing .NET == .NET Core name.

If you've ever gone to the [Download .NET page](https://dotnet.microsoft.com/en-us/download/dotnet/7.0), there is the core runtime and then the optional aspnet and desktop addons. Like most of the rest of the toolset, we can't be responsible for documenting everyone else's products so the line has to be drawn somewhere. If you think we came up too short and would like to enhance the documentation to help other people, there is a "Edit the schema for this page" link at the bottom of that page.

**Comment by chrpai** [comment]
I'm very well versed on all the iterations of .something.  My question is about the extension.  I'm not asking you to document somebody elses product I'm asking what do these things do exactly.  I'd be happy to submit the PR myself.

In wix v3 the netfx extension had a lot of properties and PackageGroups. Are they still in netfx or are they moved elsewhere?   I see no mention of them in https://wixtoolset.org/docs/schema/netfx/

**Comment by rseanhall** [comment]
I guess I am too close to the code to understand what you're asking for. Maybe it would help for you to read the WIP at https://wixtoolset.org/docs/development/wips/add-dotnet-runtime-compatibility-check/ along with all the links in there.

Those are ids that you use in `PropertyRef` or `PackageGroupRef`, not schema so they aren't there. I can't find a new version of the page at https://wixtoolset.org/docs/v3/customactions/wixnetfxextension/.

**Comment by chrpai** [comment]
Another thing strange to me about those checks is that 0 is success. I know that makes sense as an exit code but for MSI when you write an AppSearch / LaunchCondition it's usually like   Installed or SOMETHINGFOUND  and in this case you have to write Installed or Not SOMEPROPERTY or Installed or SOMEPROPERTY="0".   I'd prefer one property to be 1 or null and another property to have error codes if  someone cares.
