### ISSUE TITLE
Harvesting Project Names with Spaces

### ISSUE THREAD

**Issue by mwileczka** [wixtoolset/issues#7408]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0

* Which version of Visual Studio are you building with (if any)?

>2022 17.5.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 4.0.0 / HeatWave 1.0.1

* Which version of .NET are you building with?

> Project is 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> 10

* Describe the problem and the steps to reproduce it.

> Harvesting a project that has spaces in its name results in package build errors due to invalid variable naming. For example, if the project is named `XYZ Client`, the resulting `_XYZ Client.wxs` (hidden) file contains `Source="$(var.XYZ Client.TargetDir)\FILE"` where FILE is one of the outputs (content, source, etc.).

* Describe the behavior you expected and how it differed from the actual behavior.

> All of the entries really should be `Source="$(var.XYZ_Client.TargetDir)\FILE"` (underscore instead of space)

**Comment by mwileczka** [comment]
I didn't see any unit test for harvesting projects or I would have updates it. I'm not sure how to add that from scratch, not familiar with .NET testing.

**Comment by mwileczka** [comment]
yeah, i saw them, there wasn't one for harvesting a project, i'm guessing because they didn't want to commit a certain project type? I'll try to add a sample c# 4.72 project to harvest and make sure it works

**Comment by rseanhall** [comment]
There are definitely existing tests for harvesting projects. They seem to be in https://github.com/wixtoolset/wix4/blob/develop/src/tools/test/WixToolsetTest.HeatTasks/MsbuildHeatFixture.cs.

**Comment by mwileczka** [comment]
Thank you, I completely missed that, figured it would be with the other ones.

**Comment by mwileczka** [comment]
Can someone verify intended behavior? If there is a space in a file name, then the var name and the component ID should have an underscore instead, correct? (ie: there should be no spaces in an ID). I know the var requires it.

**Comment by robmen** [comment]
If the file path contains a non-[Identifier character](https://learn.microsoft.com/en-us/windows/win32/msi/identifier), it is replaced with an underscore.
