### ISSUE TITLE
Condition element not valid in wix 4

### ISSUE THREAD

**Issue by strawberryfield** [wixtoolset/issues#7411]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0

* Which version of Visual Studio are you building with (if any)?

> 17.5.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 4.0.0

* Which version of .NET are you building with?

> 6.0.311

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> win 10 22h2

* Describe the problem and the steps to reproduce it.

> Your example in detecting net.6 is
~~~
<netfx:DotNetCompatibilityCheck
Property="DOTNETRUNTIMECHECK"
Platform="x64"
RollForward="major"
RuntimeType="desktop"
Version="6.0.0"
  />

  <Launch
  Message="This application requires .NET 6."
  Condition="Installed OR DOTNETRUNTIMECHECK"
/>
~~~
* Describe the behavior you expected and how it differed from the actual behavior.

> The message does not fire when net 6 is missing.
The are other examples using the <Condition> tag but this appears not valid in Wix 4

**Comment by barnson** [comment]
It's not clear what you're describing. Which Condition element? What error messages are you getting?

**Comment by strawberryfield** [comment]
I do not receive any message while I expect "This program requires net 6"

Il lun 17 apr 2023, 16:30 Bob Arnson ***@***.***> ha scritto:

**Comment by barnson** [comment]
See the doc for the values you need to check: https://wixtoolset.org/docs/schema/netfx/dotnetcompatibilitycheck/

**Comment by strawberryfield** [comment]
I confirm it does not work.
Some **working example** in the documentation will be appreciated
