### ISSUE TITLE
DowngradeErrorMessage instead of DisallowUpgradeErrorMessage when Disallow is set to 'yes'

### ISSUE THREAD

**Issue by timberto** [wixtoolset/issues#7416]
* Which version of WiX are you building with?

> 4.0.0

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Heatwave 1.0.1.1

* Which version of .NET are you building with?

> n/a

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> n/a

* Describe the problem and the steps to reproduce it.

> I am trying to create package in which I want to block products from installing with higher versions. I am using the following MajorUpgrade element: 
`<MajorUpgrade Disallow="yes" DisallowUpgradeErrorMessage="!(loc.DisallowError)"  DowngradeErrorMessage="!(loc.DowngradeError)" />`
This is according to the documentation ([https://wixtoolset.org/docs/schema/wxs/majorupgrade/]()).
>
> When installing a newer version of the product I therefore expect to see the text `loc.DisallowError`, however I get an error message with the text `loc.DowngradeError`. It seems like the wrong message is being used when an upgrades are disallowed.
>
> Looking at the source code of wix4 it seems to be that the error lies at the following line: [https://github.com/wixtoolset/wix4/blob/8c757c0f67f26f21c6bcbbfb81b7ea8b91c35fe4/src/wix/WixToolset.Core/Compiler.cs#L6639](Compiler.cs). In this line the `Description` is set to `downgradeErrorMessage` instead of `disallowUpgradeErrorMessage`.

* Describe the behavior you expected and how it differed from the actual behavior.

> Expected to see an error message with as text `loc.DisallowError`, but got an error message with text `loc.DowngradeError`.

**Comment by barnson** [comment]
Can you add a unit test to your PR? If so, we can take it into v4.0.1; otherwise, the PR would go only into v5. We'll also investigate the other test failures.
