### ISSUE TITLE
Moving to the new .NET Foundation CLA service

### ISSUE THREAD

**Issue by dnfadmin** [wixtoolset/issues#7418]
Hi @barnson and @robmen - we need to move the WixToolset to the new .NET Foundation CLA service.  Can you email me at chris.sfanos @ dotnetfoundation.org to get started?  Also, I noticed missing references to the .NET Foundation itself from the READMEs.  I'll include that in the email for the CLA service - thanks!

Chris
.NET Foundation Operations Team

**Comment by robmen** [comment]
Thanks, but we run the CLA bot locally in the WiX Toolset project. No need to migrate to the new service.
