### ISSUE TITLE
Error dialog for SqlDatabase error not showing

### ISSUE THREAD

**Issue by davidkarlsson** [wixtoolset/issues#7422]
* Which version of WiX are you building with?

4.0.0

* Which version of Visual Studio are you building with (if any)?

VisualStudio.17.Release/17.5.4+33530.505

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

FireGiant HeatWave 1.0.1.1
WiX Toolset Visual Studio Extension 1.0.0.22

* Which version of .NET are you building with?

4.8.04084

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Microsoft Windows 10 Pro 10.0.19044 Build 19044

* Describe the problem and the steps to reproduce it.

Add a SqlDatabase to a component with `CreateOnInstall="yes"` and `ContinueOnError="no"` and set User to a non existent user so the database creation will fail:

```
<Wix
  xmlns="http://wixtoolset.org/schemas/v4/wxs"
  xmlns:sql="http://wixtoolset.org/schemas/v4/wxs/sql"
  xmlns:util="http://wixtoolset.org/schemas/v4/wxs/util">

  <Package Name="WixDatabaseTest" Manufacturer="TODO Manufacturer" Version="1.0.0.0" UpgradeCode="24e637fe-59b4-4c22-9815-3ba02b9e3110">
    <MajorUpgrade DowngradeErrorMessage="!(loc.DowngradeError)" />

    <Feature Id="Main">
      <ComponentRef Id="DatabaseComponent" />
    </Feature>
  </Package>

  <Fragment>
    <StandardDirectory Id="ProgramFiles6432Folder">
      <Directory Id="INSTALLFOLDER" Name="!(bind.Property.Manufacturer) !(bind.Property.ProductName)" />
    </StandardDirectory>
  </Fragment>

  <Fragment>
    <Component Id="DatabaseComponent" Guid="{5F1CC947-B726-481D-8BA1-913A24D1710B}" Directory="INSTALLFOLDER">

      <util:User Id="DatabaseUser" Name="test_user" Password="test" CreateUser="no" />

      <sql:SqlDatabase
        Id="SqlDatabaseTest"
        Server="localhost"
        Instance="SQLEXPRESS"
        Database="test_db"
        User="DatabaseUser"
        ConfirmOverwrite="yes"
        CreateOnInstall="yes"
        DropOnUninstall="no"
        ContinueOnError="no" />

      <CreateFolder />
    </Component>
  </Fragment>
</Wix>
```

With WiX 4.0.0 this causes a silent rollback without an error dialog showing that something went wrong when creating the database. This differs from the same case with WiX v3.14.0.6526 which show an error dialog saying "Error -2147217843: failed to create SQL Database: test_db, error detail: unknown error." in this case. 

The log for my WiX 4.0.0 test with this logs "Error 0x80070057: failed to set hresult code into error message" which might be the underlying cause for the error dialog not showing?:

```
MSI (s) (40:A8) [13:14:28:679]: Executing op: ActionStart(Name=Wix4CreateDatabase_X86,Description=Creating Databases,)
MSI (s) (40:A8) [13:14:28:679]: Executing op: CustomActionSchedule(Action=Wix4CreateDatabase_X86,ActionType=25601,Source=BinaryData,Target=**********,CustomActionData=**********)
MSI (s) (40:70) [13:14:28:681]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI4CC8.tmp, Entrypoint: CreateDatabase
CreateDatabase:  Error 0x80040e4d: failed to check if database exists: 'test_db', error: unknown error
CreateDatabase:  Error 0x80070057: failed to set hresult code into error message
CustomAction Wix4CreateDatabase_X86 returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 13:14:28: InstallFinalize. Return value 3.
```

The log is for a x86 build but I get the same issue with the error dialog not showing for x64 as well. The same test with WiX v3.14.0.6526 which shows the error dialog logs this:

```
MSI (s) (FC:08) [13:39:17:050]: Executing op: ActionStart(Name=CreateDatabase,Description=Creating Databases,)
MSI (s) (FC:08) [13:39:17:050]: Executing op: CustomActionSchedule(Action=CreateDatabase,ActionType=25601,Source=BinaryData,Target=**********,CustomActionData=**********)
MSI (s) (FC:24) [13:39:17:051]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI2A9.tmp, Entrypoint: CreateDatabase
CreateDatabase:  Error 0x80040e4d: failed to check if database exists: 'test_db', error: unknown error
MSI (c) (C4:FC) [13:39:17:067]: Font created.  Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

Error 26201. Error -2147217843: failed to create SQL database: test_db, error detail: unknown error.
MSI (s) (FC!F4) [13:40:32:310]: Product: WixDatabaseTestV3 -- Error 26201. Error -2147217843: failed to create SQL database: test_db, error detail: unknown error.

CustomAction CreateDatabase returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 13:40:32: InstallFinalize. Return value 3.
```

* Describe the behavior you expected and how it differed from the actual behavior.

I expected the error dialog the SqlDatabase extension used to show for this error in WiX 3.x to also be shown in WiX 4.0.0 as there still seems to exist functionality for it in the source code. Instead it just silently does a rollback which makes it difficult to pinpoint what went wrong with an installation.

[log-v3.txt](https://github.com/wixtoolset/issues/files/11272811/log-v3.txt)
[log-v4.txt](https://github.com/wixtoolset/issues/files/11272819/log-v4.txt)

**Comment by barnson** [comment]
Reopen for triage.
