### ISSUE TITLE
MSBuild HarvestDirectory ItemGroup doesn't allow customized AdditionalOptions per item

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#7427]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
4.0.0

* Which version of Visual Studio are you building with (if any)?
2022

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
2022 WiX 4.0.0

* Describe the problem and the steps to reproduce it.
I would like to pass customized AddiotnalOptions to heat.
I can do that in MSBuild by calling HeatDirectory task explictly. However I can't do that using HarvestDirectory ItemGroup

The fix may replace/amend the use of MSBuild property $(HarvestDirectoryAdditionalOptions) with an Item Metadata %(HarvestDirectory.AdditionalOptions)

**Comment by Zuhara786** [comment]
<Project Sdk="WixToolset.Sdk/4.0.0">

**Comment by Zuhara786** [comment]
@Appreciate
I would like to request I need option for my service application regarding renew trade license on my user account all three year payment option approve instead of one year and all my locker room (shajuch16@gamil.com)

**Comment by Zuhara786** [comment]
> 

$

**Comment by Zuhara786** [comment]
@Zuhara786

**Comment by Zuhara786** [comment]
> @Zuhara786

I WANT APPORVE ALL MY APPLICATION THREE YEARS PAYMENT OPTIONS REGARDING ACTION REQUIRED PROPERTY DOCUMENTS TENENCY CONTRACT

**Comment by Zuhara786** [comment]
@barnson

**Comment by Zuhara786** [comment]
> @Zuhara786

I WANT APPORVE ALL MY APPLICATION THREE YEARS PAYMENT OPTIONS REGARDING ACTION REQUIRED PROPERTY DOCUMENTS TENENCY CONTRACT

**Comment by Zuhara786** [comment]
`[> @Zuhara786  I WANT APPORVE ALL MY APPLICATION THREE YEARS PAYMENT OPTIONS REGARDING ACTION REQUIRED PROPERTY DOCUMENTS TENENCY CONTRACT ](www.tamm.com) `
