### ISSUE TITLE
Can't install Visual Studio 2019 Extensions

### ISSUE THREAD

**Issue by rebla01** [wixtoolset/issues#7433]
## Bugs

If this issue is a bug:

* Wix 3.11 current download

* Which version of Visual Studio are you building with (if any)?

>Visual Studio 2019 Version (V16.11.26)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

>WiX v3 - Visual Studio 2019 Extension

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)
current download

* Which version of .NET are you building with?

> 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows Server 2012 R2

* Describe the problem and the steps to reproduce it.

Can't install Visual Studio Extension. Installation failed with following errors:
[Uploading dd_VSIXInstaller_20230421125449_1c64.log…]()

**Comment by barnson** [comment]
Your log didn't attach.

**Comment by rebla01** [comment]
[dd_VSIXInstaller_20230421165228_0234.log](https://github.com/wixtoolset/issues/files/11296848/dd_VSIXInstaller_20230421165228_0234.log)

**Comment by barnson** [comment]
> 21.04.2023 16:52:29 - 	Extension is signed with an invalid timestamp.

Usually indicates your machine isn't up to date with the latest certificates.

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
