### ISSUE TITLE
Unable to install WiX v3 - Visual Studio 2015 Extension on Visual Studio 2015

### ISSUE THREAD

**Issue by sabarish-rajamohan** [wixtoolset/issues#7434]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
  Wix 3.11.2

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?
  Visual Studio 2015 Professional | Update 3

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
   WiX v3 - Visual Studio 2015 Extension 1.0.0.22

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?
  .NET Framework 4.5
> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 10 Pro - 19045.2846
> (Windows version)

* Describe the problem and the steps to reproduce it.

Tried installed wix tools. It asked to enable .NET 3.5 , and after enabling it. It got installed. Tried installing the extension, didn't seem to get installed. Getting the below error
![image](https://user-images.githubusercontent.com/60693369/233719474-63f59296-ff18-4d7b-a8af-2ab1621db540.png)

* Describe the behavior you expected and how it differed from the actual behavior.
Expected it to successfuly be installed to VS 2015

Logs:

[dd_VSIXInstaller_20230422004818_328c.log](https://github.com/wixtoolset/issues/files/11298725/dd_VSIXInstaller_20230422004818_328c.log)

**Comment by barnson** [comment]
What happens if you use the Tools|Extensions|Online to install?

**Comment by sabarish-rajamohan** [comment]
@barnson : I was able to install via that route. Thank you. Is it because there are two versions of Visual studio installed in my machine?

**Comment by barnson** [comment]
🤷 The ways of VSIX installation are mysterious...

**Comment by RogueOverride** [comment]
I too am running into this exact issue (using the exact same versions of everything, except I am using Windows Server 2016 1607 (OS Build 14393.6529)). Unfortunately this is part of a build process so I can't open a UI and install it, it must be done via this command line. So providing a solution of "use the UI" is not an acceptable solution. Please reopen this so that we can address this accordingly.
