### ISSUE TITLE
Autogenerated Directory Id keys are not unique

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7459]
# Bugs

If this issue is a bug:

* Which version of WiX are you building with?

4.0.0

* Which version of Visual Studio are you building with (if any)?

17.5.4  2022 Enterprise

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Heatwave for 2022 1.0.1.0

I've been writing automation to author components and in testing a large directory harvest I encountered an error.

```
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <?define ComponentRules="OneToOne"?>
  <!-- SourceDir instructs IsWiX the location of the directory that contains files for this merge module -->
  <?define SourceDir="C:\"?>
  <Fragment Id="ProductName1Lib">
    <ComponentGroup Id="ProductName1Lib">
      <Component Directory="INSTALLLOCATION" Subdirectory=".git\objects\e0">
        <File Source="$(var.SourceDir)GitHub\THDWiXProjects\.git\objects\e0\dd830876bdba0bf2c48cc65ee1c79a4fb00212" KeyPath="yes" />
      </Component>
      <Component Directory="INSTALLLOCATION" Subdirectory=".git\objects\fb">
        <File Source="$(var.SourceDir)GitHub\THDWiXProjects\.git\objects\fb\3b59054764a8561600393fb924b2c0b26957f7" KeyPath="yes" />
      </Component>
    </ComponentGroup>
  </Fragment>
</Wix>
```

The above code generates the following error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	WIX0130	The primary key 'd3sCLLU3gMZH5jqj7j4Piyl9AYes' is duplicated in table 'Directory'. Please remove one of the entries or rename a part of the primary key to avoid the collision.	ProductName1	C:\GitHub\Test\ProductName1\ProductName1Lib\ProductName1Lib.wxs	8	

The Directory and SubDirectory Ids are unique and WiX doesn't complain about them not meeting the requirements for autogeneration.  If can make the error go away if I do things like chainge Subdirectory="e0" and "fb" only.

**Comment by jcrawfor74** [comment]
I have the same error, VS 2022 v17.5.5, with HeatWave extension v1.0.1.1

In Folders.wxs
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <!-- Server-->
    <StandardDirectory Id="ProgramFiles6432Folder">
      <Directory Id="SRV_INSTALLFOLDER" Name="!(bind.Property.Manufacturer)\!(bind.Property.AppSuite)\Server"/>
    </StandardDirectory>
    <StandardDirectory Id="CommonAppDataFolder">
      <Directory Id="SRV_CONFIGFOLDER" Name="!(bind.Property.Manufacturer)\!(bind.Property.AppSuite)\Server" />
    </StandardDirectory>
    <!-- Client-->
    <StandardDirectory Id="ProgramFiles6432Folder">
      <Directory Id="CLNT_INSTALLFOLDER" Name="!(bind.Property.Manufacturer)\!(bind.Property.AppSuite)\Client"/>
    </StandardDirectory>
  </Fragment>
</Wix>
```
Where AppSuite is a property I define for a subdirectory path for my application

Error 

`Error	WIX0130	The primary key 'dJv7xXGIY864QqGBfSwOo3gL98Tk' is duplicated in table 'Directory'. Please remove one of the entries or rename a part of the primary key to avoid the collision.	`

**Comment by jcrawfor74** [comment]
It seems like I just don't understand how to use Wix :-)
What I was trying to achieve was  Root directory "c:\Program Files\Company\Application Suite" and then Server and Client Subfolders for each application. The issue is I was adding the StandardDirectory Twice when all I needed to do was configure inside the Directory like the following..

Fixed..

```
<Fragment>
  <StandardDirectory Id="ProgramFiles6432Folder">
    <Directory Id="BASE_INSTALLFOLDER" Name="!(bind.Property.Manufacturer)\MyApplication">
      <Directory Id="SERVER_INSTALLFOLDER" Name="Server"/>
      <Directory Id="CLIENT_INSTALLFOLDER" Name="Client" />
    </Directory>
  </StandardDirectory>
  <StandardDirectory Id="CommonAppDataFolder">
    <Directory Id="SRS_CONFIGFOLDER" Name="!(bind.Property.Manufacturer)\!(bind.Property.AppSuite)\SmartRetail Server" />
  </StandardDirectory>
</Fragment> 
```
