### ISSUE TITLE
Page Not Found: /schemas/

### ISSUE THREAD

**Issue by zharptitza** [wixtoolset/issues#7463]
### WiX Toolset Page URL

https://wixtoolset.org/schemas/

### Additional information (optional)

The schemas don't appear to be there.

**Comment by barnson** [comment]
Schema URIs are just unique identifiers. The schema doc is available at https://wixtoolset.org/docs/schema/.

**Comment by zharptitza** [comment]
Following: 
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
gets redirected to a Smashing pumpkins video on Youtube. This doesn't seem correct.

**Comment by barnson** [comment]
Schema URIs are just unique identifiers so all targets are equally correct.

**Comment by WillowPointJiuJitsu** [comment]
The schema pointed out by zharptitza is still going on, and changing it to v5 goes to 404. Given that it seems difficult to find documentation for some reason, it would be good to have some kind of option of finding out the xml format outside of reverse engineering.
