### ISSUE TITLE
mbanative.dll isn't automatically included in .NET Framework MBA UI payloads

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#7465]
* Which version of WiX are you building with?
4.0.0

* Describe the problem and the steps to reproduce it.
I have a .NET Framework MBA project that references WixToolset.Mba.Core package.
The BA build folder does not contain the required mbanative.dll, and I didn't find any documentation or example showing where to take this file from

* Describe the behavior you expected and how it differed from the actual behavior.
I'd expect the mbanative.dll to be automatically included in the UI payloads when the bundle _BootstrapperApplication_ element contains
```
<bal:WixManagedBootstrapperApplicationHost />
```

A workaround can be made by adding to the proj file:
```
  <ItemGroup>
    <PackageReference Include="WixToolset.Mba.Core" Version="4.0.0" GeneratePathProperty="true" />
    <Content Include="$(PkgWixToolset_Mba_Core)\runtimes\win-x64\native\mbanative.dll">
      <Visible>false</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <IsAssembly>false</IsAssembly>
    </Content>
  </ItemGroup>
```

This makes sure the BA build folder includes mbanative.dll

**Comment by robmen** [comment]
Correct `mbanative.dll` will now be published when referencing the v5 BA API .nupkg.
