### ISSUE TITLE
DirectoryRef/@FileSource should default to that of reference Directory/@FileSource 

### ISSUE THREAD

**Issue by dmcmenamin-kt** [wixtoolset/issues#7470]
* Describe the scenario and benefits that the feature supports.

In WiX v4.0.0, it seems that a DirectoryRef element's FileSource attribute does not inherit (or default) to the FileSource specified by the directory that it references. I think making the DirectoryRef/@FileSource default to the referenced parent would simplify file source/destination mappings in certain scenarios.

As an example, here is a slightly modified version of the example project created when creating a MSI Package (WiX 4) project via the Heatwave extension in Visual Studio:

Say in Folders.wxs, I want to centrally specify the directory hierarchy of my application, so it is easy to understand the various folders created by the installer. When appropriate, I want to specify that the folder (and the files within it) are to be sourced from a certain source folder.

```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <StandardDirectory Id="ProgramFiles6432Folder">
      <Directory Id="INSTALLFOLDER" Name="!(bind.Property.Manufacturer) !(bind.Property.ProductName)" FileSource="..\Example_Project\data" />
    </StandardDirectory>
  </Fragment>
</Wix>
```

In a different Wxs file (e.g. ExampleComponents.wxs), say I want to reference this directory and define a file to be installed. It would be convenient to allow the following, where ExampleComponents.wxs will specify the file to be installed, but it need not specify the path from where to source the file.

```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
      <DirectoryRef Id="INSTALLFOLDER">
        <Component Id="ExampleComponents">
          <File Name="myFile.txt" />
        </Component>
      </DirectoryRef>
  </Fragment>
</Wix>
```

This, however, results in WIX0103	Cannot find the File file 'myFile.txt'. The DirectoryRef did not look for `myFile.txt` in `..\Example_Project\data\`, even though the Directory referenced by DirectoryRef specifies the FileSource.

* Describe how you're accomplishing the feature today (if possible).

Currently, I am working around this by specifying the DirectoryRef/@FileSource in the ExampleComponents.wxs, like follows:
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
      <DirectoryRef Id="INSTALLFOLDER" FileSource="..\Example_Project\data">
        <Component Id="ExampleComponents">
          <File Name="myFile.txt" />
        </Component>
      </DirectoryRef>
  </Fragment>
</Wix>
```

However, this prohibits being able to specify the FileSource in Folders.wxs and breaks the centralized mapping I was hoping to achieve.

* Describe what you'd like the new feature to do.

DirectoryRef/@FileSource defaults to the value specified by the Directory/@FileSource attribute of the referenced directory. DirectoryRef/@FileSource can be overridden to specify a different file source, if desired. 

There is a similar feature request for the [DiskId attribute](https://github.com/wixtoolset/issues/issues/1281), but it looks like that issue was closed. I'm sure similar arguments could also be made for other *Ref elements.

Perhaps there is good technical reason for not implementing this feature, but I wanted to at least highlight the potential usability benefit it would provide.

**Comment by barnson** [comment]
Tracking in https://github.com/wixtoolset/issues/issues/7492.
