### ISSUE TITLE
Empty CustomTable not created in MSI

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7480]
## Bugs

If this issue is a bug:

wix 4.0.0
vs 2022 community 17.5.5
heatwave 1.0.1.0

* Describe the problem and the steps to reproduce it.

Author wxs that includes a CustomTable element without any Row elements.  Build the MSI and look at it in ORCA.   In V3 the table will be there.  In V4 it will not unless you explicitly add an EnsureTable element.

* Describe the behavior you expected and how it differed from the actual behavior.

I expected the table to be there without the EnsureTable element like in V3.  Also I did a V3 to V4 conversion and this isn't something that WiXCop gave any warnings on.

Precreated empty tables are useful for datadriven custom actions that use SQL INSERT TEMPORARY.

**Comment by barnson** [comment]
`CustomTable` defines the table; `CustomTableRef` is used to add rows -- and creating the table first. This is new behavior in WiX v4.
