### ISSUE TITLE
SignContainers is infunctional for detached bootstrapper containers

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#7490]
* Which version of WiX are you building with?
4.0.0

* Describe the problem and the steps to reproduce it.

1. Create a MSBuild target to create @SignContainers ItemGroup
1. Override SignContainers target to sign detached containers
    ~~~~
    <Target Name="MyGetContainersToSign" BeforeTargets="GetContainersToSign">
      <ItemGroup>
        <SignContainers Remove="*"/>
        <SignContainers Include="$(IntermediateOutputPath)\$(TargetName)-*.cab"/>
      </ItemGroup>
    </Target>
    <Target Name="SignContainers">
      <SignFiles .../>
    </Target>    
    ~~~~
1. Note that the built bootstrapper has detached containers sideloads and that they are signed
1. Execute the bootstrapper

Log says:
```
e054: Failed to resolve source for payload: (null), package: (null), container: 1, error: 0x80070002.
e000: Error 0x80070002: Failed to resolve source, payload: (null), package: (null), container: 1
e000: Error 0x80070002: Failed to acquire container: 1
e311: Failed to acquire container: 1 to working path: ********, error: 0x80070002.
e000: Error 0x80070002: Failed to acquire container: 1 to working path: ********
e000: Error 0x80070002: Failed to extract container for payload: ********
e000: Error 0x80070002: Failed to acquire payload: ********
e313: Failed to acquire payload: ******** to working path: ********, error: 0x80070002.
e000: Error 0x80070002: Failed to acquire payload: ******** to working path: ********
e000: Error 0x80070002: Failed cache action: cache package
e000: Error 0x8000ffff: Cache thread exited unexpectedly with exit code: 2147942402.

```

* Describe the behavior you expected and how it differed from the actual behavior.
I'd expect the bootstrapper to run smoothly

**Comment by barnson** [comment]
Burn has never supported signing detached containers. (Containers are cabs today, which are signable, but that's an implementation detail that would change to support LZMA or better compression, for example.) The error logging is consistent with the container being missing or having a different hash.

**Comment by nirbar** [comment]
In that case the fix should be to eliminate all references to SignContainers
