### ISSUE TITLE
No longer able to suppress ICE24 errors in Wix 4

### ISSUE THREAD

**Issue by paulvickery** [wixtoolset/issues#7522]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.0

* Which version of Visual Studio are you building with (if any)?

> 2022 (17.5.4)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave for VS2022 1.0.1

* Which version of .NET are you building with?

> 7.0.203

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> I have set my version to use a 4-digit year as the major version (e.g. 2024.3.1.1) and now, in Wix 4, I get the error message:
>
>error WIX0242: Invalid product version '2024.3.8550.19696'. MSI product versions must have a major version less than 256, a minor version less than 256, and a build version less than 65536. The revision value is ignored but version labels and metadata are not allowed.
>
>In Wix 3 I had added a suppression for ICE24 to allow me to use this version numbering, but this suppression is now not being honoured.
>
>I have tried adding WIX0242 to the suppression but it makes no difference.
>
>The suppression is in the wixproj file as:
>
	<PropertyGroup>
		<SuppressIces>ICE24</SuppressIces>
	</PropertyGroup>

* Describe the behavior you expected and how it differed from the actual behavior.

> I had expected the ICE24 error to have been ignored, and for the msi to have been generated. Instead, I just get the error as above, and no msi is produced.

**Comment by barnson** [comment]
The ICEs can still be suppressed; this is a new error. We're going to downgrade this message to a warning but be aware that Windows Installer doesn't support major version numbers greater than 255 like you'd expect. You'll probably be safe for a few years...

**Comment by paulvickery** [comment]
Thanks for that. I look forward to the next release! :) 

I know that Windows Installer doesn't really support this, but I seem to have got away with it for a few years already!

Ideally, I'd like to change to using a 2-digit date, but couldn't think of a way to do that without breaking upgrades. I posted a question earlier on that at https://github.com/orgs/wixtoolset/discussions/7521. If you have any wisdom you can share that would be great...! :)

You say this is a new error, and not an ICE, so am I right in thinking that these types of errors cannot be suppressed?

**Comment by barnson** [comment]
https://www.firegiant.com/blog/2023/5/30/wix-online-meeting-259-highlights/

**Comment by paulvickery** [comment]
Hi guys,

Many thanks for including this in 4.0.1. 

I have updated all nugets and the dotnet tool (globally and in the solution's config) to 4.0.1 but still get it showing as an error. Is there something I need to do to see it now as a warning?

Thanks,

Paul.

**Comment by barnson** [comment]
What's the exact message?

**Comment by paulvickery** [comment]
Exactly the same as I first reported:

`error WIX0242: Invalid product version '2024.3.8557.23820'. MSI product versions must have a major version less than 256, a minor version less than 256, and a build version less than 65536. The revision value is ignored but version labels and metadata are not allowed.`

Things which may be relevant:
- I'm using VS2022, with the HeatWave for VS2022 extension, version 1.0.1.
- I have installed wix 4.0.1 globally, and also have it my solution's .config\dotnet-tools.json
- My wixproj references WixToolset.Heat, WixToolset.Util.wixext and WixToolset.UI.wixext, all at version 4.0.1.
- I'm building using the VS2022 build.

My wixproj looks like this:

```<Project Sdk="WixToolset.Sdk/4.0.0">
	<PropertyGroup>
		<EnableProjectHarvesting>false</EnableProjectHarvesting>
		<HarvestDirectoryTransforms>OutputFilter.xslt</HarvestDirectoryTransforms>
		<HarvestDirectorySuppressFragments>true</HarvestDirectorySuppressFragments>
		<HarvestDirectoryAutogenerateGuids>true</HarvestDirectoryAutogenerateGuids>
		<!--<CompilerAdditionalOptions>-sice 24</CompilerAdditionalOptions>-->
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
		<DefineConstants>Debug</DefineConstants>
		<SuppressPdbOutput>False</SuppressPdbOutput>
		<SuppressSpecificWarnings>1113;0242;242</SuppressSpecificWarnings>
		<SuppressValidation>false</SuppressValidation>
		<SuppressIces>ICE24</SuppressIces>
		<SuppressAllWarnings>true</SuppressAllWarnings>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
		<SuppressPdbOutput>True</SuppressPdbOutput>
		<SuppressSpecificWarnings>1113</SuppressSpecificWarnings>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\MyProject\MyProject.csproj" />
	</ItemGroup>
	<ItemGroup>
		<HarvestDirectory Include="..\MyProject\bin\$(Configuration)\net6.0-windows">
			<DirectoryRefId>INSTALLFOLDER</DirectoryRefId>
			<ComponentGroupName>Output</ComponentGroupName>
			<SupressCOM>true</SupressCOM>
			<SuppressRegistry>true</SuppressRegistry>
			<SuppressRootDirectory>true</SuppressRootDirectory>
			<Transforms>OutputFilter.xslt</Transforms>
		</HarvestDirectory>
	</ItemGroup>
	<ItemGroup>
		<Content Include="Licence.rtf" />
		<Content Include="OutputFilter.xslt" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="WixToolset.Heat" Version="4.0.1" />
		<PackageReference Include="WixToolset.Util.wixext" Version="4.0.1" />
		<PackageReference Include="WixToolset.UI.wixext" Version="4.0.1" />
	</ItemGroup>
</Project>

**Comment by barnson** [comment]
That means you're still using v4.0.0. WIX0242 doesn't exist in v4.0.1. HeatWave doesn't use the .NET tool version of WiX, so you have to update `Project/@Sdk` or global.json.

**Comment by paulvickery** [comment]
Doh - I'm an idiot! For some reason my last reply doesn't show the first line of the wixproj, but it looks like this: 
`<Project Sdk="WixToolset.Sdk/4.0.0">`

Of course I need to change it to 4.0.1!

Sorry...
and thanks!
