### ISSUE TITLE
Util.PermissionEx not set with WIX 3.14

### ISSUE THREAD

**Issue by Whiletru3** [wixtoolset/issues#7523]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 3.14.6526.0 (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any)?

> build with light and candle

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with?

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

>Win10  21H2

* Describe the problem and the steps to reproduce it.

a wixproj used with wix 3.11.2 have an issue with latest wix 3.14
I use Util extension to set permissions on folder and service like this : 
```
<Component Id="LocalProjects" Guid="xxxxxxxx" Directory="PROGRAMDATA.LocalProjects" Win64='yes'>
        <CreateFolder>
          <util:PermissionEx User="Users" GenericAll="yes"/>
        </CreateFolder>
      </Component>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> With the 3.11.2 the permissions are set but not with the 3.14

**Comment by barnson** [comment]
Please provide a repo with a minimal repro project and attach to this issue a verbose log showing the problem.

**Comment by Whiletru3** [comment]
Here is the verbose log : 
[verbose log.txt](https://github.com/wixtoolset/issues/files/11615180/verbose.log.txt)

I tried to build from visual studio with success (ACL are set in this case). So I compared the product.wixobj and saw differences : 

the working one from VS2022 (x64 compilation)
```
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*28">
				<field>Directory</field>
				<field>PROGRAMDATA.LocalProjects</field>
			</row>
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*30">
				<field>CustomAction</field>
				<field>SchedSecureObjects_x64</field>
			</row>
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*34">
				<field>Directory</field>
				<field>PROGRAMDATA.Temp</field>
			</row>
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*36">
				<field>CustomAction</field>
				<field>SchedSecureObjects_x64</field>
			</row>
```
and the one from candle.exe :

```
                        <row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*28">
				<field>Directory</field>
				<field>PROGRAMDATA.LocalProjects</field>
			</row>
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*30">
				<field>CustomAction</field>
				<field>SchedSecureObjects</field>
			</row>
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*34">
				<field>Directory</field>
				<field>PROGRAMDATA.Temp</field>
			</row>
			<row sourceLineNumber="C:\TEMP\wix4test\SetupWix314\product.wxs*36">
				<field>CustomAction</field>
				<field>SchedSecureObjects</field>
			</row>
```

In this case there are no _x64 in SchedSecureObjects
so in my script I added "-arch x64" as parameter for candle.exe and bingo, it is working now.

With the 3.11 without specifying the arch, it was working.

**Comment by Whiletru3** [comment]
this commit trigger this change : 
https://github.com/wixtoolset/wix3/blame/develop/src/tools/wix/CompilerCore.cs#L875
it is doing nothing in case of x86.
and the default platform value of candle is x86 : https://github.com/wixtoolset/wix3/blob/master/src/tools/candle/candle.cs#L52

**Comment by barnson** [comment]
WiX v3.14 works like WiX v4 to support architecture-specific custom actions: If you have 64-bit components, you need to build the package with the right architecture.
