### ISSUE TITLE
IniFile addline does not support unicode strings correct

### ISSUE THREAD

**Issue by Mentopolis** [wixtoolset/issues#7526]
Using wix  3.14.4118.0 and try to add an unicode string to a CFG file

Entriy in WSX file:
`<IniFile Id="ConfigFileLocal2" Action="addLine" Directory="PRODUCT_BIN" Name="start.env" Section="ENVIRONS" Key="SETUP" Value="[SETUP]" />
`

log file from MSI:
`
MSI (s) (74:4C) [11:03:13:774]: Executing op: IniWriteRemoveValue(Section=ENVIRONS,Key=SETUP,Value=C:\temp\こんにちは\2\setup,Mode=0)
WriteIniValues: Datei: start.env, Abschnitt: ENVIRONS, Schlüssel: SETUP, Wert: C:\temp\こんにちは\2\setup
`

result in CFG: the original target file was stored as UTF8+BOM
`SETUP=C:\temp\?????\2\setup`

**Comment by robmen** [comment]
The `IniWriteRemoveValue` is owned by the Windows Installer team. That means you'll need to follow up with Microsoft to get its behavior changed; we (unfortunately) do not control it.
