### ISSUE TITLE
Condition 'WixBundleExecutePackageAction = 2' evaluates to false.

### ISSUE THREAD

**Issue by tm-nti** [wixtoolset/issues#7535]
* Which version of WiX are you building with?
  
> 4.0.1

* Which version of Visual Studio are you building with (if any)?

> 2022 17.6.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave 1.0.1

* Which version of .NET are you building with?

> .NET Framework 4.8

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 11 (A Hyper-V VM) and Windows 10 (my own machine)

* Describe the problem and the steps to reproduce it.

I would like to preface this with the fact that I am no expert at Wix or windows installers and most of my knowledge comes from googling

We are upgrading to Wix 4
We have a Bundle with several MsiPackages 
We have ui in the first msi and want to show this window on install (Same behaviour in 3.14)
I did as was described here: https://wixtoolset.org/docs/fourthree/faqs/#removal-of-displayinternalui
`bal:DisplayInternalUICondition="WixBundleExecutePackageAction = 2"`
But when running the installer and pressing the "Install" button it evaluates to false and does not show the msi ui

A small part of the log file
```
[1630:58B8][2023-06-07T14:59:41]i200: Plan begin, 8 packages, action: Install
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'VersionNT64' evaluates to true.
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'VersionNT64' evaluates to true.
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'VersionNT64' evaluates to true.
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'VersionNT64' evaluates to true.
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'VersionNT64' evaluates to true.
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'VersionNT64' evaluates to true.
[1630:58B8][2023-06-07T14:59:41]i052: Condition 'WixBundleExecutePackageAction = 2' evaluates to false.
```

I even tested if WixBundleExecutePackageAction was equal to 0 through 7, they all evaluated false.
I do not know how to log the value of WixBundleExecutePackageAction, so I have no idea what it's actual value is.

using `bal:DisplayInternalUICondition="1"` to show the ui works, but then it also shows on uninstall
I have also tried `bal:DisplayInternalUICondition="NOT Installed"` but that too shows on uninstall

* Describe the behavior you expected and how it differed from the actual behavior.

> The same behaviour as wix 3.14.

**Comment by barnson** [comment]
`WixBundleExecutePackageAction` is set during execution, so can't be used for `DisplayInternalUICondition`. You want `WixBundleAction` instead.

**Comment by tm-nti** [comment]
@barnson 'WixBundleAction = 2' also evaluates to false

**Comment by tm-nti** [comment]
@barnson Nevermind. It appears that 'WixBundleAction = 6' is what I wanted
For anyone else with this problem
`bal:DisplayInternalUICondition="WixBundleAction = 6"`
is what i ended up with
The FAQ is probably outdated slightly
