### ISSUE TITLE
HeatWave for VS2022 - Project templates older SDK version

### ISSUE THREAD

**Issue by MichelMichels** [wixtoolset/issues#7543]
* Which version of WiX are you building with?

> 4.0.1+6e6eb478

* Which version of Visual Studio are you building with (if any)?

> Visual Studio Community 2022 17.6.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave for VS2022 1.0.1

* Which version of .NET are you building with?

> .NET 7.0

* Describe the problem and the steps to reproduce it.

> When adding a new project with any WiX (HeatWave for VS2022) template, the project sdk is set at 4.0.0 in the project file.
> ```csproj
> <Project Sdk="WixToolset.Sdk/4.0.0">
> </Project>
> ```

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected this to be the latest SDK version (4.0.1)
> ```csproj
> <Project Sdk="WixToolset.Sdk/4.0.1">
> </Project>
> ```

**Comment by chrpai** [comment]
This should be filed over at https://github.com/firegiant/HeatWaveSupport/issues
