### ISSUE TITLE
Update signing service

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#7546]
**Encountered at:** wixtoolset/wix@783b829e1

**Detail:**

The currently provided .NET Foundation signing service is being removed. We need to update to the "[new signing tool](https://github.com/dotnet-foundation/wg-maintainers/issues/90)" from .NET Foundation or switch to using FireGiant's signing certificate.

**Comment by richlander** [comment]
FYI: Projects can sign with whatever signing cert they want, just like .NET signs with MS certs. The only requirement (going forward) is that certs are HSM based. Loose `.pfx` certs are going away, per my understanding.

The DNF solution is offered as a convenience to projects that want a free (for the cert and/or the HSM provider) and orchestration option.

Context: https://knowledge.digicert.com/generalinformation/new-private-key-storage-requirement-for-standard-code-signing-certificates-november-2022.html
