### ISSUE TITLE
Default CompressionLevel is not mszip in Wix 4

### ISSUE THREAD

**Issue by petm2022** [wixtoolset/issues#7549]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.1

* Which version of Visual Studio are you building with (if any)?

> 2022 - 17.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

>HeatWave for VS2022 1.0.1

* Describe the problem and the steps to reproduce it.

>When building a msi package and using MediaTemplate with no CompressionLevel specified, the used CompressionLevel will be "medium".

* Describe the behavior you expected and how it differed from the actual behavior.

> The documentation write that "mszip" is default. In Wix 3 the default was "mszip". We discovered the difference after upgrading our project from Wix 3 to Wix 4. After the upgrade the build time was mush longer due to the medium compression level.

**Comment by barnson** [comment]
That was an explicit change. You can set the default compression level via .wixproj and the command line if `medium` isn't right for you.
