### ISSUE TITLE
Support logging to console in burn

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#7552]
## Feature requests

If this issue is a feature request:

* Describe the scenario and benefits that the feature supports.

As a CI/CD developer or setup user, I would like to see installation progress on CMD window or in CI/CD pipeline logs

* Describe how you're accomplishing the feature today (if possible).

Today I attach the installation log file to pipelines as an artifact
The downside of this approach is that I can't see live progress of the installation

* Describe what you'd like the new feature to do.

The feature I request is to add a burn command line flag "/conlog" that logs to console while still logging to the regular log files

**Comment by barnson** [comment]
This is not considered a core scenario to get into the engine, given that there is an embedded protocol to get detailed progress information. That protocol would need to be enhanced to allow all logging. Then you'd need an external tool to run the bundle and attach to the embedded protocol, like https://github.com/wixtoolset/wix/tree/develop/src/tools/burn. It might be possible to create a bundle extension that could tweak logging.
