### ISSUE TITLE
The Name property of a focusable element is null for the document on 'End-user license agreement' window.

### ISSUE THREAD

**Issue by Kirank915** [wixtoolset/issues#7563]
**Pre-Requisite:** 
Download build from this link: [https://go.microsoft.com/fwlink/?linkid=2224908](https://go.microsoft.com/fwlink/?linkid=2224908.)

**Repro Steps:** 

1. Open the location where build downloaded and double click on that build file.
2. 'Welcome...' window appears and select the next button with the enter key.
3. 'End user agreement...' window appears. Turn on AI for Windows.
4. Verify whether the name property is defined for the document or not.

**Actual Result:**
The Name property of a focusable element is null for the document on 'End-user license agreement' window.
Observation:
Screen readers (Narrator, JAWS, NVDA) announce as "Document" when focus lands on it.

**Expected Result:**
The Name property of a focusable element must not be null for the document on 'End-user license agreement' window.
Ex: screen reader should announce as "End user license agreement Document".

**How to Fix:**
Provide a UI automation Name property that concisely identifies the element.
Note:
Issue reproes with all screen readers.

**MAS Reference:**
[MAS 4.2.1 – Object Information](https://aka.ms/MAS4.2.1)

<img width="1398" alt="AI-MAS4 2 1-Daqf sqlpackage-enuserlicenseagreement-" src="https://github.com/wixtoolset/issues/assets/117266902/aac602ce-82b5-4631-b26f-ff42bcbeed90">

**Comment by Kirank915** [comment]
Bug copied from Dac Fx and SQL Package: [BUG 2431442](https://msdata.visualstudio.com/SQLToolsAndLibraries/_workitems/edit/2431442)

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6205
