### ISSUE TITLE
The Name property of a focusable element is null for 'Status' progress bar available on 'Installing Microsoft SQL server...' window.

### ISSUE THREAD

**Issue by Kirank915** [wixtoolset/issues#7564]
**Pre-Requisite:** 
Download build from this link: https://go.microsoft.com/fwlink/?linkid=2224908.

**Repro Steps:**

1. Open the location where build downloaded and double click on that build file.
2. 'Welcome...' window appears and select the next button with the enter key.
3. 'End user agreement...' window appears. Press spacebar on the checkbox and press 3-tab keys to reach 'Next' button. Activate it with enter key.
4. 'Ready to install..' window appears with focus on install button. Activate it with enter key. Turn on AI **-fast** pass.
5. Verify whether the name property is defined for the progress bar or not. 

**Actual Result:**
The Name property of a focusable element is null for 'Status' progress bar available on 'Installing Microsoft SQL server...' window.
Observation:
Unable to mention screen reader narration for this as the screen lasts only for 1-2 seconds.

**Expected Result:**
The Name property of a focusable element must not be null for 'Status' progress bar available on 'Installing Microsoft SQL server...' window.

**How to Fix:**
Provide a UI automation Name property that concisely identifies the element.
Note:
Issue is not identified with screen readers.

**MAS Reference:**
<img width="1455" alt="AI-MAS4 2 1-daqfsql-installing-nameproperty" src="https://github.com/wixtoolset/issues/assets/117266902/48e157b0-85b8-4b47-a5bc-b3a7164a5637">

[MAS 4.2.1 – Object Information](https://aka.ms/MAS4.2.1)

**Comment by Kirank915** [comment]
Bug copied from Dac Fx and SQL Package: [BUG 2434325](https://msdata.visualstudio.com/SQLToolsAndLibraries/_workitems/edit/2434325)

**Comment by barnson** [comment]
There's no evidence Windows Installer supports this. If you can provide documentation to the contrary, we can consider adding this.
