### ISSUE TITLE
The RangeValue pattern of a progress bar doesn't have specific Minimum, Maximum, IsReadOnly values.

### ISSUE THREAD

**Issue by Kirank915** [wixtoolset/issues#7565]
**Pre-Requisite:** 
Download build from this link: https://go.microsoft.com/fwlink/?linkid=2224908.

**Repro Steps:** 

1. Open the location where build downloaded and double click on that build file.
2. 'Welcome...' window appears and select the next button with the enter key.
3. 'End user agreement...' window appears. Press the spacebar on the checkbox and press 3-tab keys to reach the 'Next' button. Activate it with the enter key.
4. 'Ready to install...' window appears with focus on install button. Activate it with enter key. Turn on AI -fast pass.
5. Verify whether the progress bar has specific values or not

**Actual Result:**
The RangeValue pattern of a progress bar doesn't have specific Minimum, Maximum, IsReadOnly values for the progress bar available on 'Installing Microsoft SQL server...' window.
Observation:
Unable to mention screen reader narration for this installing screen as the screen lasts only for 1-2 seconds.

**Expected Result:**
The Range Value pattern of a progress bar should have specific Minimum, Maximum, Is Read Only values for the progress bar available on 'Installing Microsoft SQL server...' window.

**How to Fix:**
Provide a UI automation Name property that concisely identifies the element.
Note:
Issue is not identified with screen readers.

**MAS Reference:**
[MAS 4.2.1 – Object Information](https://aka.ms/MAS4.2.1)

<img width="1462" alt="AI-MAS4 2 1-Daqf sqlpackage-installing-rangevalue" src="https://github.com/wixtoolset/issues/assets/117266902/8a27da9e-5038-4ecb-9b43-7293dc7233b6">

**Comment by Kirank915** [comment]
Bug copied from Dac Fx and SQL Package: [BUG 2434328](https://msdata.visualstudio.com/SQLToolsAndLibraries/_workitems/edit/2434328)

**Comment by barnson** [comment]
There's no evidence Windows Installer supports this. If you can provide documentation to the contrary, we can consider adding this.
