### ISSUE TITLE
Page Not Found: /documentation/manual/v3/main/

### ISSUE THREAD

**Issue by robin2777** [wixtoolset/issues#7572]
### WiX Toolset Page URL

https://wixtoolset.org/documentation/manual/v3/main/

### Page URL that linked to WiX Toolset

https://github.com/ViGEm/ViGEmBus/releases/tag/setup-v1.17.333

**Comment by BMurri** [comment]
The ViGEmBus project might consider updating their link to https://wixtoolset.org/docs/v3/.
