### ISSUE TITLE
NetFx Extension Always Produces Warning WIX5439 During Build

### ISSUE THREAD

**Issue by mark-monteiro** [wixtoolset/issues#7579]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.1

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022 - Version 17.6.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> N/A

* Which version of .NET are you building with?

> .NET 7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Using the NetFx extension produces the following build warning that appears to originates from the extension itself and not any code in the application. This makes it impossible to run the build with the `/p:MSBuildTreatWarningsAsErrors=true` flag

> `15>D:\a\wix\wix\src\ext\NetFx\wixlib\NetFx4.X.wxs(6): warning WIX5439: The *Search/@Variable attribute's value begins with the reserved prefix 'Wix'. Some prefixes are reserved by the WiX toolset for well-known values. Change your attribute's value to not begin with the same prefix.`

> The following is a small reproducible example of a .wxs file that produces this error. The associated .wixproj `OutputType` is set to `Bundle`

```xml
<Wix
  xmlns="http://wixtoolset.org/schemas/v4/wxs"
  xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal"
  xmlns:netfx="http://wixtoolset.org/schemas/v4/wxs/netfx"
  xmlns:util="http://wixtoolset.org/schemas/v4/wxs/util"
>
  <Bundle
    Name="Test App Bundle"
    Version="1.0.0"
    UpgradeCode="d400d660-ccc5-4136-92eb-2976159e218d"
    DisableModify="yes"
    DisableRemove="yes"
  >

    <!-- Define bootstrapper (UI) application type -->
    <BootstrapperApplication>
      <bal:WixStandardBootstrapperApplication
        ShowVersion="yes"
        LicenseUrl=""
        SuppressOptionsUI="yes"
        Theme="hyperlinkLargeLicense"
      />
    </BootstrapperApplication>
    
    <!-- Check the .NET Framework 4.x level -->
    <util:RegistrySearchRef Id="WixNetFramework4xInstalledRelease" />

    <Chain>

      <ExePackage
        SourceFile="dist\NDP481-x86-x64-AllOS-ENU.exe"
        Compressed="yes"
        LogPathVariable="NetFx48RedistLog"
        DetectCondition="WixNetFramework4xInstalledRelease &gt;= &quot;533320&quot;"
        InstallArguments="/install /passive /norestart /log &quot;[NetFx48RedistLog]&quot;"
        RepairArguments="/repair /passive /norestart /log &quot;[NetFx48RedistLog]&quot;"
        UninstallArguments="/uninstall /passive /norestart /log &quot;[NetFx48RedistLog]&quot;"
        PerMachine="yes"
        Permanent="yes"
      />
    </Chain>
  </Bundle>
</Wix>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> The build should complete without any warnings. This warning does not appear to have anything to do with the application source code.

> It isn't fully clear to me where the file reference in the warning (`D:\a\wix\wix\src\ext\NetFx\wixlib\NetFx4.X.wxs`) comes from, but based on a quick search it looks like it could be coming from here: https://github.com/wixtoolset/Netfx.wixext/blob/master/src/wixlib/NetFx4.wxs#L26

**Comment by chris-meuzelaar** [comment]
Just ran into this as well. It's a significant issue for our team since we have forced warnings as errors in our build processes. Is there any workaround that only suppresses this warning for that file?

**Comment by mark-monteiro** [comment]
@chris-meuzelaar The only workaround I was able to identity was to suppress this warning for the entire project. You can do so from the `.wixproj` file like so:

```xml
<Project Sdk="WixToolset.Sdk/4.0.1">
  <PropertyGroup>
    <!--
    NOTE: The WIX5439 warning needs to be suppressed for this project due to a bug in the NetFx plugin
    See: https://github.com/wixtoolset/issues/issues/7579
    -->
    <SuppressSpecificWarnings>5439</SuppressSpecificWarnings>
  </PropertyGroup>
</Project>
```
