### ISSUE TITLE
Action SchedServiceConfig fails in MsiGetComponentState call during Windows Service installation

### ISSUE THREAD

**Issue by vadmyst** [wixtoolset/issues#7594]
* Which version of WiX are you building with?

> Migrating from 3.11.2 to "WixToolset.Sdk" Version="4.0.1" using VS2022 extension HeatWave for WIX v4

* Which version of Visual Studio are you building with (if any)?

> VS 2022 (17.6.4)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave for VS2022 1.0.1

* Which version of .NET are you building with?

> .NET 7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

My project was converted from WIX v3 to WIX v4 and during installation it installs Windows Service.
However, during installation it fails in SchedServiceConfig custom action.
Here's a snippet from MSI log:

```
Action start 19:03:43: Wix4SchedServiceConfig_X86.
MSI (s) (04:BC) [19:03:43:116]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIE0DC.tmp, Entrypoint: SchedServiceConfig
MSI (s) (04!78) [19:03:43:124]: Note: 1: 2711 2: C__BE1458030797468FAA588CFF49B51870 
SchedServiceConfig:  Error 0x80070647: Failed to get install state for Component: C__BE1458030797468FAA588CFF49B51870
CustomAction Wix4SchedServiceConfig_X86 returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 19:03:43: Wix4SchedServiceConfig_X86. Return value 3.
```

Here's the screenshot from Orca of the Wix4ServiceConfig table contents
![image](https://github.com/wixtoolset/issues/assets/331752/35705a5a-bf2b-4d60-afb0-6523ed5e3e25)

The component is also present in Component table
![image](https://github.com/wixtoolset/issues/assets/331752/9917d024-ca84-4b1b-baf9-5422c09a3d97)

Component mentioned in the log that SchedServiceConfig complains about is present in all the necessary tables in the MSI (it used to work when built with WIX v3). I've checked the source of the SchedServiceConfig and it fails when calling MsiGetComponentStateW. Why would MsiGetComponentState fail for that particular component?

```
<Component Id="C__BE1458030797468FAA588CFF49B51870" Guid="{293e2888-0ad5-40b6-b1dc-efbf39d51cc3}">
    <File Id="ServiceExeFile" Name="Service.exe" Source="C:\project\Service.exe" Vital="yes" ReadOnly="no" Hidden="no" System="no" Checksum="no"/>
    <ServiceInstall Id="ServiceExeFile" Name="[SERVICENAME]" DisplayName="[PRODUCTFAMILY] - [ID]" Account="[SERVICE_LOGIN]" Password="[SERVICE_PASSWORD]" ErrorControl="normal" Start="auto" Type="ownProcess" Vital="yes" Description="Runs the service.">
        <ServiceDependency Id="PNP_TDI" Group="yes"/>
        <ServiceDependency Id="Cryptography" Group="yes"/>
        <ServiceDependency Id="Event Log" Group="yes"/>
        <ServiceDependency Id="CryptSvc" Group="no"/>
        <ServiceConfig xmlns="http://wixtoolset.org/schemas/v4/wxs/util" FirstFailureActionType="restart" ResetPeriodInDays="0" RestartServiceDelayInSeconds="120" SecondFailureActionType="restart" ThirdFailureActionType="restart"/>
    </ServiceInstall>
    <ServiceControl Id="ServiceExeFile" Name="[SERVICENAME]" Start="install" Stop="both" Remove="uninstall" Wait="yes"/>
</Component>
```

**Comment by barnson** [comment]
Can you attach the full log file? It's hard to diagnose without enough data.

**Comment by vadmyst** [comment]
Sure, here you go
[msi.log](https://github.com/wixtoolset/issues/files/11971419/msi.log)

**Comment by vadmyst** [comment]
I have figured out what happened - the problem is on my side.
When building MSI In WIX v4 Wix4ServiceConfig table is created to facilitate service configuration. It contains a reference to Service component. However, part of my deployment is patching Component table

In the log we can see that C__BE1458030797468FAA588CFF49B51870 changed into C__2C__BE1458030797468FAA588CFF49B51870:
```
(STATE)       MSI (s) (18:14) [11:59:30:329]: Component: C__2C__BE1458030797468FAA588CFF49B51870; Installed: Absent; Request: Local; Action: Local
```
But the patching process did not update Wix4ServiceConfig table, hence the error about being unable to locate the state of the component.

**Comment by barnson** [comment]
OK, that sounds weird. :)
