### ISSUE TITLE
WIP: WiX v5: Default major upgrade behavior and localized error message

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7605]
# Default major upgrade behavior and localized error message

## User story

As a setup developer, I get default major upgrade behavior if I don't specify my own. The default major upgrade behavior includes blocking attempted downgrades, which requires a localized string -- which WiX will provide and allow you to specify your own.

## Proposal

The default major upgrade you get with MajorUpgrade is so awesome that whoever implemented that feature must be even more awesome. However, is suffers one weakness: It must be authored. The primary reason is that the default behavior is to prevent downgrades. That's the right thing to do, but when downgrades are prevented, there must be a message presented to the user. Unfortunately, no existing system message qualifies, so the setup author must provide a string and it must be localized appropriately for the package being built.

What if we could get around that?

This proposal has two features:

- As in [other](https://github.com/wixtoolset/issues/issues/7581) [proposals](https://github.com/wixtoolset/issues/issues/7588), here I propose another instance of a WiX-gives-me-a-default-if-I-don't-specify-one language simplification. `MajorUpgrade` itself is almost there, given its copious defaults, but does require the element and one attribute, the localized downgrade-blocked message. In this proposal, the default major upgrade behavior kicks in if there are no `UpgradeSymbol`s linked in. That covers both `MajorUpgrade` and `Upgrade`/`UpgradeVersion` authoring.
- WiX comes with a built-in .wxl file. That localization file will contain (as of WiX v5) only one string: an awkwardly-named (so as to reduce risk of collision) loc string for the downgrade-blocked message. The loc file's culture will be neutral, to apply to every package. The string will be overridable, so setup authors can override the WiX-provided string and provide localized versions of it. The .wxl file will ship in the WiX SDK and .NET tool NuGet packages, in a well-known directory (probably next to wix.exe).

## Considerations

- WiX v4 allows you to specify an upgrade code but not author any major upgrade support. You can also omit upgrade code entirely (though there is a stern warning) and not author any major upgrade support. In this proposal, if you author an upgrade code, you'll get major upgrade support. Do we need a gesture to prevent this behavior?
- My original suggestion of providing the downgrade-blocked message in Klingon was not well received. So I guess it'll be in English. Making the .wxl file culture-neutral means it will always be picked up, even for non en-US builds. So there would be no warning that a string in another language is being included. Should we make the built-in .wxl file `en-US`?
- My current thinking is that the built-in .wxl file should be loaded as low-level as possible (e.g., inside `BuildCommand`). If we make the .wxl `en-US`, that would expose the different behavior between MSBuild and wix.exe when given a .wxl with a culture. (If the .wxl were provided as an MSBuild item, the culture output subdirectory would kick in). Is this a concern?
- We could, in theory, ship multiple default .wxl files, in multiple cultures, should translators offer their services. That would suggest the one we know of, written in US English, should be marked as `en-US`.

**Comment by barnson** [comment]
## Additional considerations

- Rather than restricting it to a single .wxl file, consider supporting a "built-in" .wixlib. A .wixlib could contain a .wxl file (or files) and additional authoring, such as for a [default feature](https://github.com/wixtoolset/issues/issues/7581) and a [default directory](https://github.com/wixtoolset/issues/issues/7588) rather than the current approach of poking in symbols.

**Comment by robmen** [comment]
A built-in `wixstd.lib` and (maybe) a new switch to `build` command called `-nostdlib` to allow it to be swapped out with a custom .wixlib?

**Comment by barnson** [comment]
Something like that. It's not a perfect solution -- to get the "only supply it if it's not defined" behavior, we still need link-time magic. But maybe we can make it more generic than what we have with the PRs I've submitted.

**Comment by barnson** [comment]
1. `Package/@UpgradeStrategy` wins.
2. Provide 0-LCID "ultimate fallback" language (en-US) localization.
3. Warn when falling back to 0, so those building non-en-US packages don't accidentally pollute their packages with American English.
