### ISSUE TITLE
Outdated Warning Message for UpgradeCode

### ISSUE THREAD

**Issue by SeanYoungIL55** [wixtoolset/issues#7631]
* Which version of WiX are you building with?

 4.0.1

* Describe the problem and the steps to reproduce it.

Create a simple wxs file and try to build.

Simple.wxs
`<?xml version='1.0' encoding='UTF-8'?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
<Package Manufacturer="Agilitas Ltd" Name="FPM Processor 0.1" Version="0.1.0">
</Package>
</Wix>`

Build Command:
`wix build -o App.msi Simple.wxs`

* Describe the behavior you expected and how it differed from the actual behavior.

Produces the warning message:
`warning WIX1075: The Product/@UpgradeCode attribute was not found; it is strongly recommended to ensure that this product can be upgraded.`

To me this implies that there should be a Product element with an UpgradeCode attribute. Yet on adding trying this I get another error stating that Product shouldn't be there.

I'm currently trying to learn Wix. But from what I can tell, as of v4 the Product element has been combined with Package.
As such, adding UpgradeCode to Package, instead of Product fixes everything.

But it would have made much more sense if the warning produced replaced Product with Package:
`warning WIX1075: The Package/@UpgradeCode attribute was not found; it is strongly recommended to ensure that this product can be upgraded.`

and possibly the second product as well:
`warning WIX1075: The Package/@UpgradeCode attribute was not found; it is strongly recommended to ensure that this package can be upgraded.`

**Comment by robmen** [comment]
Yep, missed a few warnings where `Product` should have been changed to `Package`.
