### ISSUE TITLE
Migrated WiX v3 to v4, now getting error doing action Wix4ConfigureSmbUninstall_X64 when installing

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7632]
### Discussed in https://github.com/orgs/wixtoolset/discussions/7630

<div type='discussions-op-text'>

<sup>Originally posted by **DarrelF** July 19, 2023</sup>
If this issue is a bug:

Which version of WiX are you building with?
WixToolset.UI.wixext 4.0.1

Which version of Visual Studio are you building with (if any)?
Microsoft Visual Studio Community 2022 (64-Bit) - Current
Version 17.6.5

Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
HeatWave for VS2022 V1.0.1

Which version of .NET are you building with?
6.0.102 x64/x86

If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
Windows 11 Enterprise (OS Build 22621.1992)
Windows Server 2016 (OS Build 14393.6085)

Describe the problem and the steps to reproduce it.
When I run the bootstrapper one of the MSI's fails on action **Wix4ConfigureSmbUninstall_X64**:

```

Action start 9:30:14: RemoveShortcuts.
MSI (s) (D0:6C) [09:30:14:978]: Doing action: SetUninstallWmiCustomAction
Action ended 9:30:14: RemoveShortcuts. Return value 1.
MSI (s) (D0:6C) [09:30:14:978]: PROPERTY CHANGE: Adding UninstallWmiCustomAction property. Its value is '"C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe" /LogFile= /u "C:\Program Files\Unisys\OS 2200 Server Management Control\Bin\SmcWmiProvider.dll"'.
Action start 9:30:14: SetUninstallWmiCustomAction.
MSI (s) (D0:6C) [09:30:14:978]: Skipping action: UninstallWmiCustomAction (condition is false)
MSI (s) (D0:6C) [09:30:14:978]: Doing action: RemoveFiles
Action ended 9:30:14: SetUninstallWmiCustomAction. Return value 1.
Action start 9:30:14: RemoveFiles.
MSI (s) (D0:6C) [09:30:14:978]: **Doing action: Wix4ConfigureSmbUninstall_X64**
Action ended 9:30:14: RemoveFiles. Return value 1.
MSI (s) (D0:08) [09:30:14:978]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI4835.tmp, Entrypoint: ConfigureSmbUninstall
MSI (s) (D0!80) [09:30:15:010]: Note: 1: 2235 2:  3: User_ 4: SELECT `FileShare`, `ShareName`, `Description`, `Directory_`, `Component_`, `User_`, `Permissions` FROM `Wix4FileShare` 
**Action start 9:30:14: Wix4ConfigureSmbUninstall_X64.**
**ConfigureSmbUninstall:  Error 0x8007064f: failed to open view on database
ConfigureSmbUninstall:  Error 0x8007064f: Failed to open view on Wix4FileShare table
ConfigureSmbUninstall:  Error 0x8007064f: failed to read Wix4FileShare table
CustomAction Wix4ConfigureSmbUninstall_X64 returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)**
MSI (s) (D0:6C) [09:30:15:010]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (D0:6C) [09:30:15:010]: Machine policy value 'DisableRollback' is 0
MSI (s) (D0:6C) [09:30:15:010]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
**Action ended 9:30:15: Wix4ConfigureSmbUninstall_X64. Return value 3.**
MSI (s) (D0:6C) [09:30:15:010]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (D0:6C) [09:30:15:010]: No System Restore sequence number for this installation.
MSI (s) (D0:6C) [09:30:15:010]: Unlocking Server
Action ended 9:30:15: INSTALL. Return value 3.

```
My questions are:
1) Has anyone had a problem with action Wix4ConfigureSmbUninstall_X64 execution like this?
2) Is there something that I am supposed to do to avoid this error?

It appears I don't have any control over Wix4ConfigureSmbUninstall_X64 action. At least I couldn't find anything searching the Internet on it that was useful with respect to the error I am getting.

Thanks,

Darrel</div>

**Comment by gizmoLover** [comment]
Are there any workarounds? I'm getting this exact error, and I think I'm begrudgingly going to have to abandon efforts to migrate to v4 if there are no workarounds.

**Comment by hegsie** [comment]
Hi,
I just stumbled onto this issue also, any idea when the fix will be released?
Thanks

**Comment by robmen** [comment]
The next WiX Online Meeting is tomorrow. That is where we review `triage` bugs.

**Comment by antmeehan** [comment]
Is there an ETA when this will land in a release? I've just moved to Wix v4 (as part of .NET 8 move) and am also hitting this issue. Many thanks.
