### ISSUE TITLE
Unable to install VSIX on Visual studio 2022

### ISSUE THREAD

**Issue by badigerpramod** [wixtoolset/issues#7659]
## Triage

Issues are triaged at [online meetings](https://www.firegiant.com/blog/), generally held alternate Tuesdays at 9:30 a.m. Pacific time (UTC-7/UTC-8). Meeting requests are posted in [Discussions](https://github.com/orgs/wixtoolset/discussions/categories/announcements).

## Discussions and support

Note that discussions are best held in [Discussions](https://github.com/orgs/wixtoolset/discussions/new?category=questions). Please do not open issues requesting support or debugging help; first start a thread in [Discussions](https://github.com/orgs/wixtoolset/discussions/new?category=questions) and open an issue if the discussion suggests a bug in the WiX Toolset or that a feature request is appropriate.

## Instructions

Read the sections above. Delete the Triage, Discussions and support, and Instructions sections and fill out the rest.

## Bugs

If this issue is a bug:

* Which version of **WiX are you building with: **17.6.2166+g22f8bbf459****

> (WiX version in major.minor.release.build format)

* Which version of Visual Studio are you building with (if any) VS 2022

> (Visual Studio version, including year and update) **Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.6.4**

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format)

* Which version of .NET are you building with? .net framework 4.7

> (.NET version)

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version) windows 10

* Describe the problem and the steps to reproduce it.

I am wpf developer, i am trying to install vsix from extensions option in vs 2022, after click on install i will restart the vs 2022, then i get the error
7/31/2023 11:46:34 AM - Microsoft VSIX Installer
7/31/2023 11:46:34 AM - -------------------------------------------
7/31/2023 11:46:34 AM - vsixinstaller.exe version:
7/31/2023 11:46:34 AM - 17.6.2166+g22f8bbf459
7/31/2023 11:46:34 AM - -------------------------------------------
7/31/2023 11:46:34 AM - Command line parameters:
7/31/2023 11:46:34 AM - C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:17.6.33815.320,/appidname:Microsoft Visual Studio Professional 2022,/culture:en-US,/noep,C:\Users\z003z6ee\AppData\Local\Temp\VSIXabdp4wpv.vsix
7/31/2023 11:46:34 AM - -------------------------------------------
7/31/2023 11:46:34 AM - Microsoft VSIX Installer
7/31/2023 11:46:34 AM - -------------------------------------------
7/31/2023 11:46:35 AM - System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at VSIXInstaller.App.SetGlobalLogger(IInteropLogger logger)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
![image](https://github.com/wixtoolset/issues/assets/46001464/020f089b-c250-484f-8eb7-a40ac01b780d)

**Comment by robmen** [comment]
Unfortunately, VSIX installation is wholly controlled by Visual Studio so there isn't anything we can do to resolve your installation failure. Instead, you'll need to follow up with Visual Studio. We've been directed to send people to this forum: https://developercommunity.visualstudio.com
