### ISSUE TITLE
Make heat.exe more accessible

### ISSUE THREAD

**Issue by computerquip-work** [wixtoolset/issues#7663]
## Feature requests

* Describe the scenario and benefits that the feature supports.

> HarvestDirectory is only available inside of an MSBuild-style project. Projects that use other means or compile directly via CLI have it a bit harder. I thought this was a supported use case but I could be mistaken. Previously, in wix3, heat was provided with the tools.

* Describe how you're accomplishing the feature today (if possible).

> Currently, in order to use heat from wix4, they must download the nuget package, figure out where it was installed, and either execute it directly or add it path.

* Describe what you'd like the new feature to do.

> Seems like one of these could be done:
> * Make heat.exe available via `dotnet tool install WixToolset.Heat`
> * Distribute heat.exe in the additional tools installer.
> * HarvestDirectory should be made available outside of MSBuild-style projects (might go against principle).

**Comment by robmen** [comment]
Heat is being deprecated as per [WIP 6838](https://github.com/wixtoolset/issues/issues/6838). We are still deciding how we want to replace it, but exposing it more than it already is a non-goal.

**Comment by computerquip-work** [comment]
I wasn't aware of that, thanks for the heads up.

**Comment by chrpai** [comment]
Will the replacement be in WiX or Heatwave?  Will it have command line availability in some form still?
