### ISSUE TITLE
In high contrast Aquatic mode, NPS Extension for Azure MFA text is not adapting applied theme. 

### ISSUE THREAD

**Issue by msftedad** [wixtoolset/issues#7668]
* Which version of WiX are you building with?
WIX: 3.14.0.1119

* Which version of Visual Studio are you building with (if any)?
Visual Studio 2017

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
I don't think we are using Wix Toolset Visual Studio Extension

* Which version of .NET are you building with?
This is a C++ application so I don't think the .net version question applies.

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
The installer runs on various versions of Windows Server

**Pre-requisites:**
1. Download exe file from https://www.microsoft.com/en-us/download/details.aspx?id=54688 

2. Navigate to Settings> Accessibility> Contrast themes. 

3. Apply Aquatic/Desert theme. 

**steps to reproduce:**

1. Launch the "NPS Extension for Azure MFA" setup file. 

2. "MICROSOFT SOFTWARE LICENSE TERMS" popup window will get open here. 

3. Observe the "NPS Extension for Azure MFA" text in aquatic mode. 

**Expected behaviour**
In Aquatic Theme, NPS Extension for Azure MFA content should adapt applied theme. 

**Note:**
Issue exists throughout the Process of installation and uninstallation and repair process wherever the NPS Extension for Azure MFA text is present on the screen. 

Similar issue exists on installation completion text message appeared after completion of the installation. PFA: Aquatic issue -on successful alert.png 

similar issue occurs on the log file link which will comes after the repair cancellation process. PFA: Aquatic issue on log file.png 

Issue does not repro on Desert theme. 

**Attachments:**
[OneDrive_1_4-27-2023.zip](https://github.com/wixtoolset/issues/files/12258827/OneDrive_1_4-27-2023.zip)

**Comment by barnson** [comment]
v4 supports system colors.

**Comment by msftedad** [comment]
Hi @barnson, What do you mean by v4 supports system colors?

**Comment by barnson** [comment]
Themes can use system colors in WiX v4.
