### ISSUE TITLE
Screen reader is not conveying the "Successful installation" message to the users. 

### ISSUE THREAD

**Issue by msftedad** [wixtoolset/issues#7669]
Which version of WiX are you building with?
WIX: 3.14.0.1119

Which version of Visual Studio are you building with (if any)?
Visual Studio 2017

Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
I don't think we are using Wix Toolset Visual Studio Extension

Which version of .NET are you building with?
This is a C++ application so I don't think the .net version question applies.

If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
The installer runs on various versions of Windows Server

**Pre-requisites:**
Download exe file from https://www.microsoft.com/en-us/download/details.aspx?id=54688
 Switch on the narrator using Control+Windows+Enter short key. 

**steps to reproduce:**

1. Launch the "NPS Extension for Azure MFA" setup file. 

2. "MICROSOFT SOFTWARE LICENSE TERMS" popup window will get open here. 

3. Navigate using Narrator in scan mode. 

4. Navigate on to the "I agree to the terms and conditions check box" using tab key and activate. 

5. Now navigate to "Install" button using tab key and activate using 'Enter' key. 

6. Activate Yes button on the "Do you want to make changes to your device pop-up window" 

7. Now observe the issue on "Installation successfully completed" text displayed on the application. 

**Expected behaviour**
Narrator should give the info to the users regarding "Installation successfully completed" message displayed on the screen which is appeared after activating 'install' button. 

**Note:**
Issue exists throughout the Process of installation and uninstallation and repair process wherever the NPS Extension for Similar issue while uninstallation Process of the application using narrator. PFA: Narrator is not giving any info regarding the uninstallation message 

Issue repro with NVDA and Jaws. 

**Test Environment:**

OS: Win 11 (22H2) 

Build: OS Build 25231.1000 

App: NPS Extension for Azure MFA setup (Version 1.2.1959.1) 

**Attachments:**
[OneDrive_2_4-27-2023.zip](https://github.com/wixtoolset/issues/files/12258900/OneDrive_2_4-27-2023.zip)

**Comment by robmen** [comment]
I'm curious. Why did you open these UI issues against the WiX Toolset? Why not open them against the "NPS Extension for Azure MFA" owners?

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6038
