### ISSUE TITLE
WiX4: Custom BA does not show MSI internal UI

### ISSUE THREAD

**Issue by oleg-shilo** [wixtoolset/issues#7670]
## Bugs

* Which version of WiX are you building with?

> 4.0.0.0

* Which version of Visual Studio are you building with (if any)?

> Building with CLI WiX tools but not Visual Studio. The CLI command is provided below with the WXS code.

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Not using VS

* Which version of .NET are you building with?

> .NET version: v4.7.2

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows10: 21H2 (OS Build 19044.3208 )

* Describe the problem and the steps to reproduce it.

In the test, I am using custom BA for a bundle that consists of only a single msi. I need to show msi internal UI.

This is the WXS code (`setup.wxs`):

```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:netfx="http://wixtoolset.org/schemas/v4/wxs/netfx" xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">
  <Bundle Name="My Product Bundle" UpgradeCode="6f330b47-2577-43ad-9095-1861bb25889a" Version="1.0.0.0" >
    <BootstrapperApplication>
      <bal:WixManagedBootstrapperApplicationHost />
      <Payload SourceFile="BA.dll" />
      <Payload Name="WixToolset.Mba.Host.config" SourceFile="BootstrapperCore.config" />
      <Payload SourceFile="bin\Debug\net472\win-x86\mbanative.dll" />
      <Payload SourceFile="bin\Debug\net472\win-x86\WixToolset.Mba.Core.dll" />
    </BootstrapperApplication>

    <Chain>
      <MsiPackage Id="MyProductPackageId" 
                  SourceFile="My Product.msi" 
                  bal:DisplayInternalUICondition="WixBundleAction = 6" 
                  bal:PrereqPackage="yes">
      </MsiPackage>
    </Chain>
  </Bundle>
</Wix>
```

This is the CLI build command I am using:

```ps
wix build -ext "WixToolset.Netfx.wixext" -ext "WixToolset.Bal.wixext"  ".\setup.wxs"  -o ".\My_Product.v1.0.0.0.exe"
```

The bundle builds OK, it also runs correctly and installs the embedded msi. However, the MSI UI is not displayed during the installation.

Interestingly enough, if I replace the custom BA with the standard one (code below) then msi internal UI is displayed correctly:
```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:netfx="http://wixtoolset.org/schemas/v4/wxs/netfx" xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">
  <Bundle Name="My Product Bundle" UpgradeCode="6f330b47-2577-43ad-9095-1861bb25889a" Version="1.0.0.0" >
    <BootstrapperApplication>
      <bal:WixStandardBootstrapperApplication Theme="hyperlinkLicense" LicenseUrl="" />
    </BootstrapperApplication>

    <Chain>
      <MsiPackage Id="MyProductPackageId" 
                  SourceFile="My Product.msi" 
                  bal:DisplayInternalUICondition="WixBundleAction = 6" 
                  bal:PrereqPackage="yes">
      </MsiPackage>
    </Chain>
  </Bundle>
</Wix>
```

* Describe the behavior you expected and how it differed from the actual behavior.

It is expected that the msi internal UI is displayed, when `DisplayInternalUICondition` is defined, regardless the type of the BA (standards stock BA or a custom one).

**Comment by barnson** [comment]
bal:DisplayInternalUICondition just sets data in BootstrapperApplicationData.xml. It's up to the BA to read and act on that data.

**Comment by oleg-shilo** [comment]
@barnson, I accept if you say it is not a defect and `DisplayInternalUICondition` was not expected to solve the problem with the msi internal UI.

But right now there is no way (at least a described way) to have a custom BA with the MSI internal UI displayed. 

> It's up to the BA to read and act on that data.

Can you guide me to the documentation, sample or a discussion that gives me the direction? How custom BA should act so MSI internal UI is displayed. 
Please note that I tried to get support in the "discussions" but without any luck.

**Comment by BMurri** [comment]
@oleg-shilo The `PlanMsiPackage` event (accessed by subscribing to the event or by overriding `OnPlanMsiPackage` has a property on its `EventArgs`-derived argument where you override the default UI setting for the msi package. Other things the BA can override in the plan are similarly accessed. This has been the basic design in burn since the very first public release.

**Comment by oleg-shilo** [comment]
@barnson, fantastic, thank you. 
That's exactly what I was looking for.

>This has been the basic design in burn since the very first public release.

I had to learn custom BA design in WiX3 by reverse engineering some code samples, which were rather limited. So I overlooked this event of `Engine`. 
It is still difficult to find some general info on the matter so I have to rely heavily on forums (like this one).

Thank you, setting `e.UiLevel = INSTALLUILEVEL.Full;` did the trick.

The whole direction of utilizing other planning events just makes sense.
Really appreciate your help.

**Comment by BMurri** [comment]
@oleg-shilo  We especially love to receive documentation contributions, and it's a most excellent way to pay it forward. Many times the best documentation is provided by those who DIDN'T write the code, because those learning it via the school-of-hard-knocks tend to be in the best position to know what needs to be described and how to word it so others can grok it as well.
