### ISSUE TITLE
File Name, Id, and Source confusion

### ISSUE THREAD

**Issue by computerquip-work** [wixtoolset/issues#7673]
## Bugs

* Which version of WiX are you building with?

> 4.0.1

* Which version of Visual Studio are you building with (if any)?

> N/A

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

>  N/A

* Which version of .NET are you building with?

> 7.3.6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> Previously, I was able to create a `Component` with a `File` and subsequent `RegistryKey` and `RegistryValue` that referenced that file via the `File/@Name` attribute. For example, if I had `<File Name="mydll.dll" />`, I'd be able to reference it in later on via ` <RegistryValue Type="string" Name="DLL Path" Value="[#mydll.dll]" />`. It seems this doesn't work anymore since the Id doesn't seem to default to the `File/@Name` attribute as it used to.

* Describe the behavior you expected and how it differed from the actual behavior.

> I don't necessarily expect the same behavior. Currently, to work around this, I'm doing `<File Id="mydll.dll" Name="mydll.dll" />` which seems redundant. If I were to go off the documentation, it says this about `File/@Id`:
>> The unique identifier for this File element. If you omit Id, it defaults to the file name portion of the Source attribute, if specified. May be referenced as a Property by specifying [#value].
>
> and this about `File/@Name`:
>> Finally, if this attribute is omitted then its default value is the file name portion of the Source attribute, if one is specified, or the value of the Id attribute, if the Source attribute is omitted or doesn't contain a file name.  
>
> This would seem to indicate that I can omit the `File/@Name` attribute but when I tried `<File Id="mydll.dll" />`, I was met with: `error WIX0010: The File/@Name attribute was not found; it is required.`

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/7598
