### ISSUE TITLE
ICE61 incorrect when version >= 128.0.0

### ISSUE THREAD

**Issue by jonathan-sansom** [wixtoolset/issues#7680]
* Which version of WiX are you building with?

WixToolset.Sdk/4.0.1

* Which version of Visual Studio are you building with (if any)?

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.7.1

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

FireGiant HeatWave   1.0.1.1

* Which version of .NET are you building with?

N/A for this issue, but Framework 4.8.1 insatlled, as well as Core  7.0.400

* Describe the problem and the steps to reproduce it.

When the Maximum attribute of the UpgradeVersion element is >= 128.0.0 , ICE61 incorrectly triggers with 

Error	WIX0204	ICE61: Upgrade.VersionMax cannot be less than Upgrade.VersionMin. (PREVIOUS)

```
<?define UpgradeCode="{3D25A67B-BA24-4969-BE88-EFA914FD1237}"?>
<?define aVersion="127.255.65535"?>
<?define Version="128.0.0"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
	<Package Name="SetupProject1" Language="1033" Version="$(var.Version).0" Manufacturer="ACME" UpgradeCode="$(var.UpgradeCode)" InstallerVersion="200">
		<MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
		<Upgrade Id="$(var.UpgradeCode)">
			<UpgradeVersion Minimum="1.0.0" Maximum="$(var.Version)" Property="PREVIOUS" IncludeMaximum="no" />
		</Upgrade>
		<Feature Id="ProductFeature" Title="SetupProject1" Level="1">
			<ComponentGroupRef Id="ProductComponents" />
		</Feature>
	</Package>
	<Fragment>
			<StandardDirectory Id="ProgramFilesFolder">
				<Directory Id="INSTALLFOLDER" Name="SetupProject1" />
			</StandardDirectory>
		</Fragment>
	<Fragment>
		<ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER">
		</ComponentGroup>
	</Fragment>
</Wix>
```

Build this project with version 127.255.65535 and the error disappears.

This appears to be an issue with the ICE validator, not Wix, I'm assuming its massaging the version details into a signed long and any value with the major >= 128 results in a 'negative' version number.

**Comment by barnson** [comment]
It also goes away if you remove the `Minimum="1.0.0"` so yeah, sounds like a buggy ICE.
