### ISSUE TITLE
Building native custom action on ARM64 platform fails to find wix header files

### ISSUE THREAD

**Issue by parvit** [wixtoolset/issues#7683]
## Bugs

* Which version of WiX are you building with?

> version 3.14.6526

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022 Community

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 1.0.0.22

* Which version of .NET are you building with?

> .NET Framework 4.8.1

* Describe the problem and the steps to reproduce it.

> Building a simple project (https://github.com/parvit/wix-vs2022-arm-bug) with a native custom action that uses includes files or links libraries from Wix Sdk folder (eg. wcautil), does not work when selecting ARM64 platform.

> The same project and code builds correctly using the x64 platform.

* Describe the behavior you expected and how it differed from the actual behavior.

> I've tracked the issue as being tied to the definitions in this file https://github.com/wixtoolset/wix3/blob/develop/src/tools/WixTasks/wix.nativeca.targets , that does not contain the 'VS2017' folder, which is the one that provides the files for the ARM64 platform.

> In the project provided as example, if one uncomments the lines https://github.com/parvit/wix-vs2022-arm-bug/blob/fe30c7b7749abb47debdac55c54864e25d23e001/BasicCA/basic_ca.vcxproj#L194-L198 , the project builds as expected using VS2022 (or VS2022 build tools).

I hope i've been clear enough, I'm available for further clarifications if needed.

Regards,

**Comment by barnson** [comment]
WiX v3 does not support VS2022. WiX v4 does.

**Comment by parvit** [comment]
@barnson Thank you for the fast response, however while i do understand that explicit support is targeted to the more recent v4, couldn't it be done to change the default in v3 at https://github.com/wixtoolset/wix3/blob/c5117b58502cace193732a6ba9204b68e2411355/src/tools/WixTasks/wix.nativeca.targets#L16 from VS2015 to VS2017? 

That would only affect unsupported platforms and allow for ARM support out of the box without adding workarounds in user code.

**Comment by barnson** [comment]
There are no plans to release another WiX v3 build.
