### ISSUE TITLE
In the `RtfTheme.xml`， what 's the meaning of width or height with negative values?

### ISSUE THREAD

**Issue by yanpeng** [wixtoolset/issues#7684]
**Encountered at:** wixtoolset/repo@sha
In the `RtfTheme.xml`， what 's the meaning of width or height with negative values?
**Detail:**
In the `RtfTheme.xml`, some line in the file has a negative width or height,
```
<Text Name="SuccessHeader" X="11" Y="80"  Width="-11" Height="30" FontId="2" HideWhenDisabled="yes" DisablePrefix="yes">#(loc.SuccessHeader)</Text>
```
what's the meaning of this negative value. What I know is that, the origin is the top left corner, x increases when going right, y increases when going down. Negative x means from the right border of this page to the right edge of a button or label. Negative y means from the bottom border of this page to the bottom edge of a button or label.

**Comment by robmen** [comment]
This issue template is used for developers working on the WiX Toolset itself. You did not include the repo or sha hash for the repro. Please take questions to Discussions.
