### ISSUE TITLE
WiX components unable to use preprocessor variables from project file

### ISSUE THREAD

**Issue by MikeFarrington** [wixtoolset/issues#7702]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.1.0

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 17.7.3

* Which version of .NET are you building with?

> 6.0.21

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> N/A

* Describe the problem and the steps to reproduce it.

> When attempting to use preprocessor variables defined in the project file, the error "WIX0510: Undefined preprocessor variable '$(<MyDesiredVariable>)' is produced (without placeholder).

Relevant portions of my .wixproj
```
<PropertyGroup>
 <RestorePackagesPath>$(ProjectDir)packages/</RestorePackagesPath>
</PropertyGroup>
<ItemGroup>
  <!-- 
   Note: this binding works just fine, but I have same-named files in
   multiple components and want to use preprocessor variable in components
  -->
  <BindPath Include="$(RestorePackagesPath)MyPackagesSubDirectory" />   
  <!-- This is the binding I want to use -->
  <BindPath Include="$(RestorePackagesPath)" />   
</ItemGroup>
```
> Relevant portions of a .wxs file:
```
<Component>
   <File Source="$(RestorePackagesPath)MyPackageSubDirectory/MyFile.ext" />    <!-- throws WIX0150 -->
</Component>
```

* Describe the behavior you expected and how it differed from the actual behavior.

> I would like to be able to use unusual/custom pre-processor variables throughout a project rather than be limited to known/common ones like $(SolutionDir) and $(ProjectDir).  The $(RestorePackagePath) I am trying to use is so I can use a Nuget's <PackageDownload> instead of standard <PackageReference> in order to stage files for inclusion in my installer (in my case, our Company's customized TeamViewer QuickSupport module).  To be clear, this is a low priority issue.  It's just nice to not have to repeat configuration details throughout the project instead of centralizing it.

**Comment by robmen** [comment]
See the [DefineConstants Property](https://wixtoolset.org/docs/tools/msbuild/#properties)
