### ISSUE TITLE
XML Namespace url riderected to spam ?

### ISSUE THREAD

**Issue by letherman255** [wixtoolset/issues#7714]
### WiX Toolset Page URL

http://wixtoolset.org/schemas/v4/wxs

### Additional information (optional)

Hi,

I'm not able to get autocompletion in my xml editort. For some reason URL in the namespace xmlns="http://wixtoolset.org/schemas/v4/wxs" redirects to this youtube video https://www.youtube.com/watch?v=8-r-V0uK4u0.

Thanks

**Comment by barnson** [comment]
Namespaces are URIs, not URLs. See https://www.firegiant.com/docs/wix/tutorial/sprint1/spike-explore-package/.

**Comment by jakob-ledermann** [comment]
And where can one obtain the schema definition file ".xsd" from?
That file would enable many editors to be more helpful.
They don't seem to be contained in the artifacts of the release or in the repository.

**Comment by robmen** [comment]
https://github.com/wixtoolset/web/tree/master/src/xsd4

**Comment by travisvalenti** [comment]
Is there a specific reason `http://wixtoolset.org/schemas/v4/wxs` redirects to something that is completely unrelated to the URI?

This feels quite counter-productive, especially considering some IDEs that people are using may expect an `https` xmlns URI to be useful information without requiring downloading from a separate source. Consider the default behavior for VS Code and IntelliJ Rider (I can't attest to Visual Studio's behavior).

Would it not be more ideal to at a minimum redirect it to the web repo, (as @barnson claims in #7964) that's the location for anyone who wants the files?

I understand we may have different views surrounding the purpose of these xmlns URIs but it feels like an actively malicious step to deter or ridicule developers who expect these URIs to work as URLs the way that most other http URIs work (in my experience).

The usage of the `http` scheme, whilst not required to, realistically implies to a developer that this resource is available at the URL that matches the URI. If you wanted this to not be the case, it would make much more sense to use a URI scheme such as `urn`. 
As you've already configured everything to put the `http` scheme into these URIs, the only logical conclusion is to make the matching route direct to the appropriate resource.

Feedback is appreciated on this matter, as I'm sure there must be a valid reason that I haven't considered, besides malice, to not update the URL.

**Comment by kopfsick** [comment]
Agree with @travisvalenti . IDEs like Rider can automatically try to download schemas from the schema URI. Someone deliberately set up `http://wixtoolset.org/schemas/v4/wxs` to forward to a youtube video instead of anything useful, which seems like a childish move to prove the point that "Namespaces are URIs, not URLs".

**Comment by djeikyb** [comment]
I added a schemaLocation like this and now Rider can offer suggestions:

```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://wixtoolset.org/schemas/v4/wxs https://raw.githubusercontent.com/wixtoolset/web/master/src/xsd4/wix.xsd">
```

**Comment by EvanHaklar** [comment]
> I added a schemaLocation like this and now Rider can offer suggestions:
> 
> ```
> <Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>      xsi:schemaLocation="http://wixtoolset.org/schemas/v4/wxs https://raw.githubusercontent.com/wixtoolset/web/master/src/xsd4/wix.xsd">
> ```

Just downloading `wix.xsd` ([link](https://github.com/wixtoolset/web/blob/master/src/xsd4/wix.xsd)) and including this file in your Wix project in Rider resolves the issue as well.  Rider's clever enough to find it automagically.
