### ISSUE TITLE
DotNetCompatibilityCheck with Platform attribute "x64" aborts installation on x86 OS

### ISSUE THREAD

**Issue by apacker1** [wixtoolset/issues#7737]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.2

* Which version of Visual Studio are you building with (if any)?

> Visual Studio 2022 17.7.4

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> HeatWave 1.0.1

* Which version of .NET are you building with?

> 6.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> any x86 version

* Describe the problem and the steps to reproduce it.

> If I include a DotNetCompatibilityCheck element in my wxs file, with a Platform attribute of "x64", then when I run the created MSI on an x86 version of Windows, the installation aborts with an error.

* Describe the behavior you expected and how it differed from the actual behavior.

> I hoped that the DotNetCompatibilityCheck would set its property to a nonzero value indicating that the x64 version of .NET is not installed because that platform is incompatible with the OS platform.  See also https://github.com/orgs/wixtoolset/discussions/7733

**Comment by chrpai** [comment]
I think I've hit a variation of this.  If I but a DotNetCoreCheck inside of a wixlib and build it as x86 but then consume it in a bundle built as x64  I get a runtime error saying the _X86.dll couldn't be loaded.  I'm not sure I see a workaround other then building the wix lib multiple times and making sure i reference the right one when i build the bundle.  It seems like I shouldn't have to do that.

**Comment by barnson** [comment]
Triage: See PR comments for possible return values.
