### ISSUE TITLE
Wix4UtilCA Automatic Arch

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7748]
* Describe the scenario and benefits that the feature supports.

As we now have StandardDirectory 6432 and no need to author bitness attributes, it'd be nice to do the same for Util CAs.

* Describe how you're accomplishing the feature today (if possible).

`BinaryRef="Wix4UtilCA_$(sys.BUILDARCHSHORT"`

* Describe what you'd like the new feature to do.

I'd like to be able tosimply  author `BinaryRef="Wix4UtilCA"`  and have WiX automatically pick the right arch at build time.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6821
