### ISSUE TITLE
Page Not Found: /docs/schema/wxs/file/~/howtos/general/specifying_source_files.html

### ISSUE THREAD

**Issue by jamesbvaughan** [wixtoolset/issues#7763]
### WiX Toolset Page URL

https://wixtoolset.org/docs/schema/wxs/file/~/howtos/general/specifying_source_files.html/

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/schema/wxs/file/

### Additional information (optional)

I found this page for v3, but couldn't find an equivalent page for v4.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/7437
