### ISSUE TITLE
WiX v4 - Directory Table Primary Key conflict

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#7767]
* Which version of WiX are you building with?

wixtoolset.sdk/4.0.2

* Which version of Visual Studio are you building with (if any)?

17.7.3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

Heatwave v1.0.1

* Describe the problem and the steps to reproduce it.

The following WiX XML throws error:

	WIX0130	The primary key 'dL1NZp0hsYuozrtgoeU55Nn66GRE' is duplicated in table 'Directory'. Please remove one of the entries or rename a part of the primary key to avoid the collision.

```
<?xml version="1.0" encoding="utf-8"?>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="OneSupportProtocolHandlerFiles">
      <Component Directory="INSTALLLOCATION" Subdirectory="Packages\SCCMRemote2012\00000409">
        <File Source="$(var.SourceDir)\Packages\SCCMRemote2012\00000409\srvmsgs.dll" KeyPath="yes" />
      </Component>
      <Component Directory="INSTALLLOCATION" Subdirectory="Packages\SCCMRemote2012">
        <File Source="$(var.SourceDir)\Packages\SCCMRemote2012\CmRcViewer.exe" KeyPath="yes" />
      </Component>
    </ComponentGroup>
  </Fragment>
</Wix>
```

INSTALLLOCATION is defined as below and is being built x64 platform.

```
<StandardDirectory Id="ProgramFiles6432Folder">
  <Directory Id="CompanyFolder" Name="THD">
    <Directory Id="INSTALLLOCATION" Name="OneSupportProtocolHandler">
    </Directory>
  </Directory>
</StandardDirectory>
```

* Describe the behavior you expected and how it differed from the actual behavior.

I should be able to add both components without getting a duplicate generated directory table id.

**Comment by chrpai** [comment]
Is there any chance this will make it into a 4.0.x?

**Comment by robmen** [comment]
There are no plans for another v4 release, but it is always possible.

**Comment by robmen** [comment]
I can believe this could happen but I do not reproduce the problem with the provided snippets. Can you please provide a full .wxs file that reproduces the problem?

**Comment by chrpai** [comment]
This is really wierd... I can't reproduce it anymore either.  I remember this error... I copy and pasted the generated Id in the error message and isolated 2 components that conflicted out of all the other components.  At the time I worked around it by deploying the files to a shorter path.  I can see that commit in my repos history.  I made a branch off of the SHA that had the problem and it builds just fine now.  The only difference I can see is I'm now on 17.7.4 instead of 17.7.3.

**Comment by robmen** [comment]
Bummer. There is going to be a v4.0.3 very soon and I'd like to get a fix for this issue in it but I've not been able to reproduce the problem.

**Comment by chrpai** [comment]
Challenge accepted. I will try to stress the hell out of wix and see if I can repro it.  Personally, I'm wondering if something in .NET was causing it and was fixed.

**Comment by chrpai** [comment]
I can't reproduce. Closing.
