### ISSUE TITLE
netfx:DotNetCompatibiltyCheck cannot be used to check for net8 release candidate

### ISSUE THREAD

**Issue by charristti** [wixtoolset/issues#7781]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with? 

> (WiX version in major.minor.release.build format) 4.0.2

* Which version of Visual Studio are you building with (if any)?

> (Visual Studio version, including year and update) VS2022 17.8.0 Preview 3

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)? 

> (WiX Toolset Visual Studio Extension version in major.minor.release.build format) FireGiant HeatWave 1.0.1.1

* Which version of .NET are you building with?

> (.NET version) 8.0.0-rc.2.23479.6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version) Windows 10

* Describe the problem and the steps to reproduce it.

> (Be as specific as you can and err on the side of providing too much information, including code, error messages, command lines you used to invoke the build, and so forth.)

* Describe the behavior you expected and how it differed from the actual behavior.

> (Be as specific as you can and err on the side of providing too much information.)
The net8.0 rc runtimes have been installed on the test machine. When the app installer runs netfx:DotNetCompatibilityCheck is used to verify core, desktop, and aspnet versions as shown below.
<Fragment>
  <netfx:DotNetCompatibilityCheck
    Id="CoreRuntimeCheck"
    Property="CoreRuntimeCheck"
    RollForward="latestMinor"
    RuntimeType="core"
    Platform="x64"
    Version="8.0.0" />
  <netfx:DotNetCompatibilityCheck
    Id="WindowsDesktopRuntimeCheck"
    Property="WindowsDesktopRuntimeCheck"
    RollForward="latestMinor"
    RuntimeType="desktop"
    Platform="x64"
    Version="8.0.0" />
  <netfx:DotNetCompatibilityCheck
    Id="AspNetCoreRuntimeCheck"
    Property="AspNetCoreRuntimeCheck"
    RollForward="latestMinor"
    RuntimeType="aspnet"
    Platform="x64"
    Version="8.0.0" />
</Fragment>

The results of the compatibilty check are 12290 instead of 0.

Work around is to check for Version="7.99.99" with RollForward="latestMajor". This giver return value of 0.

This occurs with the installer built from the command line with "dotnet build". In VS2022 17.8.0 Preview 3 the installs do not build at all within the IDE. In the solution explorer the wix projects do not display properly and attempting to build them fails. 

![image](https://github.com/wixtoolset/issues/assets/33519407/b241b14d-e207-40d8-9728-a203d4fb7abc)

![image](https://github.com/wixtoolset/issues/assets/33519407/949f7093-ca16-41e7-ae63-4ee152f57da1)

[VS2022v17.8.9Preview3WixBuildError.log](https://github.com/wixtoolset/issues/files/12889608/VS2022v17.8.9Preview3WixBuildError.log)

**Comment by barnson** [comment]
Please attach your authoring and a resulting verbose install log.

**Comment by barnson** [comment]
`8.0.0` > `8.0.0-anything` according to SemVer. So you could use a SemVer pre-release version or 7.99.999 (etc.).
