### ISSUE TITLE
iis: Wix4InstallCertificates_X86 fails with x64 BUILDARCH

### ISSUE THREAD

**Issue by matbech** [wixtoolset/issues#7784]
* Which version of WiX are you building with?
4.0.2

* Describe the problem and the steps to reproduce it.
When using iis:Certificate with x64 BUILDARCH x64, the Wix4InstallCertificates_X86 action returns an error during the installation of the .msi. This does not happen with a .msi built with BUILDARCH x86

**test.wxs**
```
<Binary Id="DevRootCertificate" SourceFile="..\..\Dev Certificate Authority\ca.cert.pem" />

<Component Id="DevRootCertificate" Guid="">
  <iis:Certificate Id="Certificate.RootCA" Name="xyz Root certificate" Request="no" StoreLocation="localMachine" StoreName="root" Overwrite="yes" BinaryRef="DevRootCertificate" />
</Component>
```

**Error from log**
msiexec.exe /i test.msi /l* log.txt
```
Action start 14:04:53: Wix4InstallCertificates_X86.
InstallCertificates:  Error 0x8007065b: failed to add temporary row, dberr: 0, err: 
InstallCertificates:  Error 0x8007065b: Failed to add encoded hash for certificate: Certificate.RootCA
```

Note that the Wix4InstallCertificates_X64 action which comes before the Wix4InstallCertificates_X86  action succeeds.

**Comment by barnson** [comment]
An x64 package should have only 64-bit custom actions. Please attach or link to a [repro case](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by matbech** [comment]
I figured out the cause. It happens when the Wix4InstallCertificates_X86 custom action is referenced in the After attribute.

```
<InstallExecuteSequence>
      <Custom Action="CA_SslCertificate_Rollback" After="Wix4InstallCertificates_X86" Condition="NOT REMOVE" />
</InstallExecuteSequence>
```

the wix build should probably fail in this case.

**Comment by barnson** [comment]
Don't hard-code: https://wixtoolset.org/docs/tools/wixext/quietexec/#architecture-specific-custom-action-dlls

**Comment by barnson** [comment]
Another example of something that would be solved by https://github.com/wixtoolset/issues/issues/6821.
