### ISSUE TITLE
Heat.exe not running in Linux build CI

### ISSUE THREAD

**Issue by UlrichAlt** [wixtoolset/issues#7792]
## Feature requests

* Describe the scenario and benefits that the feature supports.

Currently our CI builds run on AzureDevOps using the windows-latest containers which, as the name indicates, run on a Windows machine.

We were testing on migrating to Google Build where we run some other tasks for other software and the heat (harvesting task) fails with:
```
Step #2: Already have image (with digest): mcr.microsoft.com/dotnet/sdk:7.0
Step #2: MSBuild version 17.7.3+8ec440e68 for .NET
Step #2:   WeSt.AddIn -> /workspace/customer/bin/7.17/net48/WeSt.AddIn.dll
Step #2:   WeSt.AddIn -> /workspace/customer/bin/7.16/net48/WeSt.AddIn.dll
Step #2: heat.exe : error HEAT0001: System.DllNotFoundException: Unable to load shared library 'Kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: [/workspace/setup/setup.wixproj]
```

It seems like heat.exe is dependent on some non-portable DLL from Windows which hinders us to build the setups on the usual linux build machines.

Is this a strict necessity or can it be overcome by making heat "totally" portable?

**Comment by chrpai** [comment]
As WiX is designed to create MSIs which uses the Windows Installer service... a Windows platform service... it's unlikely to ever be "totally" portable.  For my LLC and FOSS work, I use AzureDevOps and just run my wix build either on an Azure-Pipelines hosted windows-2022 agent or on an on-prem agent.  For my day time work I use Concourse CI and sometimes have pipelines that run on multiple OS... such as building an Electron app on Linux and then packaging it on Windows with WiX.

I'm not 100% familiar with all the container images available on MCR but I see some of them use a server core image.  One of these might have the Windows Kernel32.dll that you are looking for rather then something based on Linux kernel.

**Comment by barnson** [comment]
Heat supports some Windows-specific stuff so would need to not do so when not needed. But even then, WiX relies on Windows components (e.g., msi.dll) so doesn't run on Linux end-to-end: https://github.com/wixtoolset/issues/issues/4381
