### ISSUE TITLE
Feature to allow MsiProperty to have empty value

### ISSUE THREAD

**Issue by DarrelF** [wixtoolset/issues#7798]
## Feature requests

WiX MsiProperty element produces the following compiler error when MsiProperty/@Value is an empty string (Value=""):

`Severity	Code	Description	Project	File	Line	Suppression State Error	WIX0006	The MsiProperty/@Value attribute's value cannot be an empty string. If a value is not required, simply remove the entire attribute.`

Some MSI's from third-party vendors, like MariaDB, for silent installs by convention define boolean properties where an empty value for the property means false. 

The feature request is for allowing MsiProperty/@Value to be empty to support setting a property value to false for MariaDB.

A possible solution would be to add another optional attribute to MsiProperty that indicates the property is allowed to be an empty value so the existing reason for MsiProperty/@Value not being an empty string can be retained, if necessary.

**Comment by chrpai** [comment]
I'm trying to understand the gap your trying to solve.  You mention silent install so presumably these are public properties (All CAPS) and more specifically  Secure Custom Public Properties listed in the SecureCustomPublicProperties property. Just add the Secure attribute and the error should go away.

If this is not a property passed at the command line (private property) then just remove the property.  If something is setting the property during the install it can do so dynamically. The property doesn't need to exist in the property table.

Is there some other scenario I'm not thinking of?

**Comment by DarrelF** [comment]
I am trying to install the MariaDB MSI by chaining it into the WiX Bundle as follows:

`    <Chain>
      
      <PackageGroupRef Id="DotNetPackage" />

      
      <MsiPackage SourceFile="$(var.ProjectDir)\Redistributables\mariadb-10.11.5-winx64.msi" Permanent="yes" Visible="no" Vital="yes">
        <MsiProperty Name="CLEANUPDATA" Value="" />

       . . .
`
The MsiProperty with an empty Value produces a WiX compiler error.

I interpret the MariaDB Silent Install documentation as needing CLEANUPDATA to be defined as a public property with an empty value to have the boolean value false. (See [https://mariadb.com/kb/en/installing-mariadb-msi-packages-on-windows/#silent-installation](url))

**Comment by chrpai** [comment]
If your never going to pass a value then don't pass the property at all.  If your going to have some kind of UI in the bootstrapper to let the user selelct the value or let them pass it from the command line to the bootstrapper then define a WiXVariable and assign that to the MsiProperty.

**Comment by barnson** [comment]
Needs to allow overriding a default (e.g., `=1`) with a value that indicates false (typically `0` but MSI uses a lot of empty strings to indicate false).

**Comment by robmen** [comment]
A workaround that might work is to define your `MsiProperty` with an undefined variable reference. Like `MsiProperty Value='[THISISNOTAVARIABLE]'`. At compile time, the value will not be empty, and at install time, the value will resolve to an empty string as you desire.

I have not tested this, so it is possible Burn v4 was changed to ignore properties that resolve to blank. But it's worth a shot. Let us know if that works.

**Comment by DarrelF** [comment]
It appears not to work. While it compiles without error, I see the following in the MariaDB .log file (CLEANUPDATA is the MsiProperty I am trying to set to an empty string):

`MSI (s) (40:F8) [12:23:01:118]: Command Line: **CLEANUPDATA=** DATADIR=C:\ProgramData\Unisys\Utilization Report Utility\Database\data INSTALLDIR=C:\ProgramFiles\ . . .

   . . .

MSI (s) (40:F8) [12:23:01:124]: Product installation will be elevated because user is admin and product is being installed per-machine.
MSI (s) (40:F8) [12:23:01:124]: Running product '{A5340DA7-FAD1-4775-86A7-3E165A5A5449}' with elevated privileges: Product is assigned.
MSI (s) (40:F8) [12:23:01:124]: **PROPERTY CHANGE: Deleting CLEANUPDATA property. Its current value is '1'.**

`
So even though I set **_<MsiProperty Name="CLEANUPDATA" Value="[THISISNOTAVARIABLE]" />_** it is still indicating a value of '1', which means it is true. I am not sure why it indicates it is "Deleting" it.

**Comment by AlexHolly** [comment]
I get the same log messages but it works in my case. The Data folder is still there after mariadb uninstall.

```
        <Property Id="CLEANUPDATAPROPERTY" Secure="yes" />`
        ...
        <MsiProperty Name="CLEANUPDATA" Value="[CLEANUPDATAPROPERTY]" />

```
