### ISSUE TITLE
Page Not Found: /docs/schema/wxs/file/~/howtos/general/specifying_source_files.html/

### ISSUE THREAD

**Issue by jvw-philips** [wixtoolset/issues#7804]
### WiX Toolset Page URL

https://wixtoolset.org/docs/schema/wxs/file/~/howtos/general/specifying_source_files.html/

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/schema/wxs/file/

### Additional information (optional)

Link under `Source` attribute description, for mor information about how to specify source files.

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/7437
