### ISSUE TITLE
Harvesting doesn't harvest

### ISSUE THREAD

**Issue by BryanCrotaz** [wixtoolset/issues#7806]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?
4.0.2

* Which version of Visual Studio are you building with (if any)?

Running in Github actions (after 2 weeks trying to get wix 4 to work in VS I gave up)

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> 4.0.2 from NuGet

* Which version of .NET are you building with?

> .Net 7.0

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

Github Actions OS windows-latest

* Describe the problem and the steps to reproduce it.

From the documentation I put this in my project file:
```xml
<Project Sdk="WixToolset.Sdk/4.0.2">
  <PropertyGroup>
    <PreBuildEvent>
    </PreBuildEvent>
  </PropertyGroup>
	<ItemGroup>
		<HarvestDirectory Include="$(SolutionDir)\AgentService\bin\Release\net7.0">
			<ComponentGroupName>AgentServiceFiles</ComponentGroupName>
			<DirectoryRefId>ApplicationFolder</DirectoryRefId>
			<SuppressRootDirectory>true</SuppressRootDirectory>
		</HarvestDirectory>

		<BindPath Include="$(SolutionDir)\AgentService\bin\Release\net7.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="WixToolset.Heat" />
	</ItemGroup>
</Project>
```

My Package.wxs:
```xml
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package 
	  Name="DisplaySureAgentSetup"
	  Manufacturer="Silver Curve"
	  Version="1.0.0.0"
	  UpgradeCode="68c96489-4459-4f0b-8c73-e4f6f8f8ddf1"
  >
    <MajorUpgrade DowngradeErrorMessage="!(loc.DowngradeError)" />

    <Feature Id="Main">
      <ComponentGroupRef Id="AgentServiceFiles" />
    </Feature>
  </Package>
</Wix>
```

Error when building:
*WIX0094: The identifier 'WixComponentGroup:AgentServiceFiles' could not be found*
```
  
MSBuild version 17.7.2+d6990bcfa for .NET Framework
Build started 10/27/2023 5:20:12 PM.

Project "D:\a\Client\Client\AgentSetupWix4\AgentSetupWix4.wixproj" on node 1 (rebuild target(s)).
CoreClean:
  Creating directory "obj\Release\".
PrepareForBuild:
  Creating directory "bin\Release\".
AssignTargetPaths:
  Culture: en-US
CoreCompile:
  C:\Users\runneradmin\.nuget\packages\wixtoolset.sdk\4.0.2\tools\net472\x86\wix.exe build -platform x86 -out obj\Release\en-US\AgentSetupWix4.msi -outputType Package -pdb obj\Release\en-US\AgentSetupWix4.wixpdb -pdbType full -culture en-US -d Configuration=Release -d OutDir=bin\Release\ -d InstallerPlatform=x86 -d Platform=AnyCPU -d ProjectDir=D:\a\Client\Client\AgentSetupWix4\ -d ProjectExt=.wixproj -d ProjectFileName=AgentSetupWix4.wixproj -d ProjectName=AgentSetupWix4 -d ProjectPath=D:\a\Client\Client\AgentSetupWix4\AgentSetupWix4.wixproj -d TargetDir=D:\a\Client\Client\AgentSetupWix4\bin\Release\ -d TargetExt=.msi -d TargetFileName=AgentSetupWix4.msi -d TargetName=AgentSetupWix4 -d TargetPath=D:\a\Client\Client\AgentSetupWix4\bin\Release\AgentSetupWix4.msi -intermediatefolder obj\Release\en-US\ -trackingfile obj\Release\AgentSetupWix4.wixproj.BindTracking-en-US.txt -nologo  -loc Package.en-us.wxl AgentComponents.wxs Folders.wxs Package.wxs
Error: D:\a\Client\Client\AgentSetupWix4\Package.wxs(11): error WIX0094: The identifier 'WixComponentGroup:AgentServiceFiles' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker. [D:\a\Client\Client\AgentSetupWix4\AgentSetupWix4.wixproj]
```

**Comment by robmen** [comment]
Almost certainly, you are doing the [same as in this discussion](https://github.com/orgs/wixtoolset/discussions/7805#discussioncomment-7398341). 

Look in a binlog from MSBuild (`msbuild -bl`) and search for references to `heat.exe` in it. It'll probably tell you the harvest folder does not exist.

**Comment by BryanCrotaz** [comment]
If that's the case, why isn't there a console output saying so?

**Comment by robmen** [comment]
> If that's the case, why isn't there a console output saying so?

I don't think the heat target even runs... look at the binlog it will show you for sure.

> And shouldn't that be a fatal error?

Or maybe a warning?

**Comment by BryanCrotaz** [comment]
Harvest a folder...
Error if it doesn't exist
Warning if it's empty

**Comment by BryanCrotaz** [comment]
The files do exist.

```
msbuild -bl

...

this error for every file:

  heat.exe : warning HEAT5151: Could not harvest data from a file that was expected to be an assembly: D:\a\Client\Client\AgentService\bin\Release\net7.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll. If this file is not an assembly you can ignore this warning. Otherwise, this error detail may be helpful to diagnose the failure: Could not load file or assembly 'System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. [D:\a\Client\Client\AgentSetupWix4\AgentSetupWix4.wixproj]

```

**Comment by BryanCrotaz** [comment]
Basically this thing desperately needs a simple single page tutorial - do these 10 steps to create an installer for a simple app, not 90+ hours (guessing but the first few I've looked at at 90 minutes and there's 70+) of dojo videos that take 15 minutes in some cases to actually get to the title of the video. Do I really need 90 hours of training to build a windows installer?

**Comment by BryanCrotaz** [comment]
```
dotnet-install: .NET Core SDK with version '7.0.403' is already installed.
```

**Comment by robmen** [comment]
> Basically this thing desperately needs a simple single page tutorial 

You sound passionate about this topic. Perhaps you will be the one to write a single-page tutorial and make it available for others.

Personally, I'm more interested in teaching the breadth and depth of software installation using the WiX Toolset. I also enjoy providing historical context so developers new to the domain can understand the why behind the design. That is why I produce the Deployment Dojo show for free. 

For example, in the first [Deployment Dojo episode on harvesting](https://www.youtube.com/live/XcUmwegYClg?si=_JqVHSjB4ad-pjf8), I provide some background on heat and its deficiencies and a (possibly too) quick mention of `SuppressRegistry` which will avoid the error message you are seeing.

> not 90+ hours (guessing but the first few I've looked at are 90 minutes and there's 70+) of dojo videos that take 15 minutes in some cases to actually get to the title of the video. Do I really need 90 hours of training to build a windows installer?

At this time, there are 52 episodes of the Deployment Dojo, and on average, they are ~45 minutes. I understand you may be frustrated because you have expectations that aren't being met. However, exaggerating to force your point when _everything_ you are complaining about is provided to you for free by the very people you are complaining at, is not cool.

Remember, this is an Open Source project. The source code displaying the error is available to you. You could investigate exactly why the error message happens and which switch can be used to avoid it. 

If you want to be treated like a customer, then you need to pay for a product.

I'm closing this issue since it's turned into a support request. We handle support via Discussions, not issues. If you'd like to open a feature request for heat to error/warn when the harvesting directory is missing, feel free to do so.

**Comment by BryanCrotaz** [comment]
All I'm suggesting is that you've spent a LOT of time providing a HUGE amount of detail, but you forgot to give a simple primer for someone new to the project. I'd love to write a one pager, but I'm drowning in detail and have no idea how to do it myself, let alone teach it

Why do I need to suppress registry keys when the problem is in finding the SDK files? I don't understand why the build of the exe found them but the build of the installer can't

**Comment by BryanCrotaz** [comment]
> Remember, this is an Open Source project. The source code displaying the error is available to you. You could investigate exactly why the error message happens and which switch can be used to avoid it.

I've googled:

```No results found for +wix "could not load file or assembly system.runtime version 7.0.0.0"```

+wix HEAT 5151:
https://stackoverflow.com/questions/20904084/heat5151-the-given-assembly-name-or-codebase-was-invalid

I'm not harvesting from the GAC, I'm harvesting from the project output folder, so this isn't relevant to me

https://wix-users.narkive.com/NtZfvrm9/heat-exe-warning-heat5151
I'm not trying to increment the assembly version - I haven't even managed to get the first build to work, let alone an upgrade

https://github.com/wixtoolset/issues/issues/7124
Now I feel I'm going round in circles when the third result in google is my own question!

**Comment by BryanCrotaz** [comment]
I'm trying to work out where I saw episode 72 of the dojo. I have a clear memory of watching it a couple of days ago. maybe I'm hallucinating after 2 weeks full time trying to build a simple installer and getting depressed and frustrated
