### ISSUE TITLE
First window doesn't use productName from Product.Name

### ISSUE THREAD

**Issue by BryanCrotaz** [wixtoolset/issues#7815]
Wix 4.0.2 uses the package name for the opening screen, but the documentation only talks about ProductName.

```xml
MyAgentSetupWix4.wixproj

<Project Sdk="WixToolset.Sdk/4.0.2" TreatWarningsAsErrors="true" Name="My Agent">
  <PropertyGroup>
    <PreBuildEvent>
    </PreBuildEvent>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference 
			Include="$(SolutionDir)AgentService\AgentService.csproj" 
			Publish="true" 
		/>
	</ItemGroup>
</Project>
```

Opening window has title `MyAgentSetup` and text `Please wait while Windows configures MyAgentSetup`.

Expected: Product name
Actual: Package Name

Searching the docs for `package name` only results in one page: https://wixtoolset.org/docs/development/wips/redesign-remote-payload/#proposal

Searching the docs for `ProductName` gives https://wixtoolset.org/docs/api/wixtoolset.dtf.windowsinstaller/productinstallation/#declaration-28

**Comment by barnson** [comment]
What is "opening window"? What does your WiX authoring look like?

**Comment by BryanCrotaz** [comment]
Opening window - the first window Wix setup shows.

My authoring?  I've seen this term in a few places in the docs but don't know what it means.

**Comment by barnson** [comment]
WiX authoring is the source code in your .wxs files. The .wixproj does not include WiX authoring.

**Comment by BryanCrotaz** [comment]
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
	<ComponentGroup Id="AgentServiceFiles" Directory="INSTALLFOLDER">
  	  <Component Id="ServiceExe">
        <File 
			BindPath="$(SolutionDir)AgentService\bin\release\net7.0\publish\win-x64" 
			Source="AgentService.exe"/>
		  <ServiceInstall 
			  Name="DisplaySureAgent"
			  DisplayName="Agent"
			  Type="ownProcess"
			  Start="auto"
			  ErrorControl="normal"	  
		  />
		  
	  </Component>
	</ComponentGroup>
  </Fragment>
</Wix>

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" >
  <Package 
	  Name="Display Sure Agent"
	  Manufacturer="Silver Curve"
	  Version="1.0.0.0"
	  UpgradeCode="68c96489-4459-4f0b-8c73-e4f6f8f8ddf1"
  >
    <MajorUpgrade DowngradeErrorMessage="!(loc.DowngradeError)" />

    <Feature Id="Main">
      <ComponentGroupRef Id="AgentServiceFiles" />
    </Feature>
  </Package>
</Wix>
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <StandardDirectory Id="ProgramFiles6432Folder">
      <Directory Id="INSTALLFOLDER" Name="!(bind.Property.Manufacturer)\!(bind.Property.ProductName)" />
    </StandardDirectory>
  </Fragment>
</Wix>

**Comment by BryanCrotaz** [comment]
I can't find any documentation on how to set the ProductName variable. I've tried with `SetProperty` but I get an error about having a duplicate ProductName

**Comment by barnson** [comment]
https://wixtoolset.org/docs/schema/wxs/package/

**Comment by BryanCrotaz** [comment]
Which of these is ProductName coming from?

- AdminExecuteSequence
- AdminUISequence
- AdvertiseExecuteSequence
- AppId
- Binary
- BroadcastEnvironmentChange (Util extension)
- BroadcastSettingChange (Util extension)
- CheckRebootRequired (Util extension)
- CloseApplication (Util extension)
- ComplianceCheck
- ComPlusApplication (Complus extension)
- ComPlusApplicationRole (Complus extension)
- ComPlusPartition (Complus extension)
- ComPlusPartitionRole (Complus extension)
- Component
- ComponentGroup
- CustomAction
- CustomActionRef
- CustomTable
- CustomTableRef
- Directory
- DirectoryRef
- DotNetCompatibilityCheck (Netfx extension)
- DotNetCompatibilityCheckRef (Netfx extension)
- EmbeddedChainer
- EmbeddedChainerRef
- EnsureTable
- ExitEarlyWithSuccess (Util extension)
- FailWhenDeferred (Util extension)
- Feature
- FeatureGroupRef
- FeatureRef
- FindVisualStudio (Vs extension)
- GetCapabilities (Directx extension)
- Group (Util extension)
- Icon
- InstallExecuteSequence
- InstallUISequence
- InstanceTransforms
- Launch
- MajorUpgrade
- Media
- MediaTemplate
- PackageCertificates
- PatchCertificates
- Property
- PropertyRef
- QueryNativeMachine (Util extension)
- QueryWindowsDirectories (Util extension)
- QueryWindowsDriverInfo (Util extension)
- QueryWindowsSuiteInfo (Util extension)
- QueryWindowsWellKnownSIDs (Util extension)
- Requires
- RestartResource (Util extension)
- SetDirectory
- SetProperty
- SFPCatalog
- SoftwareTag
- SqlDatabase (Sql extension)
- StandardDirectory
- SummaryInformation
- SymbolPath
- UI
- UIRef
- Upgrade
- User (Util extension)
- WaitForEvent (Util extension)
- WaitForEventDeferred (Util extension)
- WebApplication (Iis extension)
- WebAppPool (Iis extension)
- WebDirProperties (Iis extension)
- WebLog (Iis extension)
- WebSite (Iis extension)
- WixUI (Ui extension)
- WixVariable

**Comment by BryanCrotaz** [comment]
Ohhh do you have to use a Property child? 
```xml
<Package>
  <Property Name="ProductName">My Name</Property>
</Package>
```

**Comment by BryanCrotaz** [comment]
Submitted a docs PR to help the next person behind me
https://github.com/wixtoolset/web/compare/master...BryanCrotaz:wix-web:patch-3

**Comment by barnson** [comment]
Use Package/@Name.

**Comment by BryanCrotaz** [comment]
I've submitted a PR to state in the docs and Product and Package are the same thing to help other newbies.
