### ISSUE TITLE
Wix.exe should have a `compile` command

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7823]
* Describe the scenario and benefits that the feature supports.

> If you have a big project, `wix build` can take a long time (especially binding). But getting a syntax check on even a single file can be awesomely useful. `wix compile <filename>` could report success or compile errors.

* Describe how you're accomplishing the feature today (if possible).

> You can `wix build` a single file and verify that the error(s) are for missing files (from binding) or `Could not find entry section in provided list of intermediates` (from linking a file with only `Fragment`s).

* Describe what you'd like the new feature to do.

> Just compile the specified file(s) to check for syntax errors. Don't link. Don't bind.

**Comment by chrpai** [comment]
Would it be possible to surface this up in HeatWave somehow?

I know your not a fan of internal ui but another useful scenario would be a quick compile and non usable build of the MSI just to be able to preview the dialog sequence.  Something similiar for Burn also.  Just quickly build a bootstrapper that doesn't actually have it's payloads so you can quickly look at the UI and test busines logic like property searches and condition evaluations.
