### ISSUE TITLE
WIP: WiX v5: `Files`

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#7857]
## User story

As a developer writing setup, I can easily author sets of files in my package by specifying wildcarded paths to include in and exclude from my package.

## Proposal

WiX has always included some kind of tool to generate WiX authoring from a directory tree. (WiX v2 had Tallow and WiX v3 and v4 had Heat.) Tallow and Heat were not _designed_ to run during the build of a package: The design was that you would use Tallow/Heat to generate skeleton authoring, then maintain it manually thereafter. Well, that didn't sit well with people who didn't want to maintain something manually thereafter. With additions to WiX and Heat like support for generated component GUIDs, Heat now probably _only_ runs during builds.

Tallow and Heat have always been bolted on. Even with the introduction of NuGet packages as the delivery mechanism for Heat in WiX v4, the bolts are still apparent. With WiX v4 and v5 features like `Component/@Subdirectory` letting you specify arbitrary subdirectories and ["naked" files](https://github.com/wixtoolset/issues/issues/7696), we have the tools to replace clunky code generation.

Enter `Files`.

`Files` takes wildcarded paths, traverses the specified directories, and generates components and files for each file. Files can also be excluded via wildcarded paths.

## Implementation

- `Files`, like naked `File`s, generates components behind the scenes in the [optimization phase](https://github.com/wixtoolset/wix/pull/463), which happens after the preprocessor and compiler and before linking.
- Each file generates one component.
- `Files` can appear anywhere that today a `Component` element can appear.
- `Files` supports MSBuild-style wildcards, including the `**` wildcard to traverse subdirectories.
- Multiple wildcard paths are supported.
- Files can be _excluded_ via wildcard paths as well.
- `File` attributes _cannot_ be specified.
- `Component` attributes _cannot_ be specified.

Here's a proposed language example:

```xml
<ComponentGroup Id="MyFiles" Directory="BinFolder">
  <Files>
    <Include Path="!(bindpath.bin)**" />
    <Include Path="!(bindpath.bin_dependencies)**" />

    <!-- Don't harvest PDB files because we don't want to ship them. -->
    <Exclude Path="!(bindpath.bin)**\*.pdb" />
    <Exclude Path="!(bindpath.bin_dependencies)**\*.pdb" />

    <!-- Don't harvest the service because it needs manual authoring (below). -->
    <Exclude Path="!(bindpath.bin)foo.exe" />
  </Files>
  
  <!-- For simple wildcards, specify them "inline." -->
  <Files Subdirectory="assets" Include="$(ContentDirectory)\**" Exclude="**\*.pdf;**\bob*" />

  <!-- This file is a service and therefore needs lovingly hand-crafted authoring. -->
  <Component>
    <File Source="!(bindpath.bin)foo.exe" />
    <ServiceInstall ... />
    <ServiceControl ... />
  <Component>
</ComponentGroup>
```

## Considerations

- `Files` replaces Heat for directory harvesting. It does not support other Heat features like self-registration or project harvesting.
- Like a naked file, `Files` can appear under `ComponentGroup`, `Feature`, `FeatureRef`, and `FeatureGroup` and the generated components are parented to those groups.
- `Files` files under the following elements are only available via the default-feature feature: `Directory`, `DirectoryRef`, `Fragment`, `StandardDirectory`, `Package`.

**Comment by barnson** [comment]
I included child elements mostly for commenting purposes. If you don't want them, that's fine, but we have to continue supporting semicolon-delimited-list-in-an-attribute-value syndrome, otherwise you'll have problems balancing inclusions and exclusions.

```xml
<ComponentGroup Id="MyFiles" Directory="BinFolder">
  <!-- Don't harvest PDB files because we don't want to ship them. -->
  <!-- Don't harvest the service because it needs manual authoring (below). -->
  <Files Include="!(bindpath.bin)**" Exclude="!(bindpath.bin)foo.exe;!(bindpath.bin)**\*.pdb" />
  <Files Include="!(bindpath.bin_dependencies)**" Exclude="!(bindpath.bin_dependencies)**\*.pdb" />
  
  <Files Subdirectory="assets" Include="$(ContentDirectory)\**" Exclude="**\*.pdf;**\bob*" />

  <!-- This file is a service and therefore needs lovingly hand-crafted authoring. -->
  <Component>
    <File Source="!(bindpath.bin)foo.exe" />
    <ServiceInstall ... />
    <ServiceControl ... />
  <Component>
</ComponentGroup>
```

**Comment by barnson** [comment]
@robmen, based on your previous comment and that I figured `**` would probably be the most common inclusion, I think I'm settled on `Files/@Include` with `Exclude` the only allowed child element with `Files` attribute. That lets you write a comment per exclusion and if you need multiple inclusions, that's why you can have more than one `Files`. Opinions?

**Comment by fyodorkor** [comment]
How are you going to treat the cases when the names of target and source directories are not the same? For example when one service is going to be installed on different platforms? So the source directories for it would be ServiceName/x86 and ServiceName/x64 and the target directory will be ServiceName?
What about the following structure:
<ComponentGroup Id="MyFiles" Directory="BinFolder" DirectorySource="BinFolder\$(var.Platform)" Recursive="yes/no">
    <Exclude File="**/*.pdb; ServiceName.exe; Subdirectory\foo.dll.config" SubDirectory="Files-going-to-another- 
        componetgroup/subfeature" />
</ComponentGroup>

**Comment by barnson** [comment]
Implemented in https://github.com/wixtoolset/wix/pull/489.

**Comment by clawton** [comment]
This is a great enhancement!  
Question: Is there a way to exclude a whole folder?
I'm trying to include a demo Visual Studio C# project and want to exclude folder named `bin` and `obj`.

**Comment by olejniczak** [comment]
Great feature!
I have a question: is it possible to see automaticly generated components?

**Comment by chrpai** [comment]
How well should we expect these components to play with MajorUpgrades scheduled later then InstallInitialize.  Minor upgrades and patches?

**Comment by rgozim** [comment]
Is there any way to make the <Files> element copyable like an individual <File>? This would be useful for globbing files in a directory and then having them install with more than one ComponentGroup.

**Comment by RDSA-SYNENTEC** [comment]
_File attributes cannot be specified._
I currently use an xslt transform for a few hundred files. Any option we have here once heat is removed?

```xml
  <!-- Template to match Component elements and add attributes -->
  <xsl:template match="wix:Component[not(contains(wix:File/@Source, 'Default_Plates.xml')) and not(contains(wix:File/@Source, '.gitignore')) and not(contains(wix:File/@Source, '.sct'))]">
      <xsl:copy>
          <xsl:attribute name="Permanent">yes</xsl:attribute>
          <xsl:attribute name="NeverOverwrite">yes</xsl:attribute>
          <xsl:apply-templates select="@*|node()"/>
      </xsl:copy>
  </xsl:template>
  
  <!-- Add read/write permissions to files -->
  <xsl:template match="wix:File[not(contains(@Source, 'Default_Plates.xml'))]">
	<xsl:copy>
		<xsl:apply-templates select="@*|node()"/>
		<xsl:element name="Permission" xmlns="http://wixtoolset.org/schemas/v4/wxs">
			<xsl:attribute name="User">Everyone</xsl:attribute>
			<xsl:attribute name="GenericRead">yes</xsl:attribute>
			<xsl:attribute name="GenericWrite">yes</xsl:attribute>
		</xsl:element>		
	</xsl:copy>
  </xsl:template>
```
