### ISSUE TITLE
Errors while building in VS 2022 17.8 - MSB4057 - The target "CollectBuildAccelerationIncompatiblePackageDesignTime" does not exist in the project.

### ISSUE THREAD

**Issue by redtrina817** [wixtoolset/issues#7859]
* Which version of WiX are you building with?
* I tried versions 4.0.1 and 4.0.3

* Which version of Visual Studio are you building with (if any)?
> Visual Studio 2022 17.8

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?
> WxToolset.Bal.wixext 4.0.1 (and 4.0.3)
> WxToolset.UI.wixext 4.0.1 (and 4.0.3)
> WxToolset.Util.wixext 4.0.1 (and 4.0.3)

* Which version of .NET are you building with?
> .NET 6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?
> Building on Windows 10. The build produces an error. See below.

* Describe the problem and the steps to reproduce it.
> After upgrading to Visual Studio 17.8, I began getting an error from my .wixproj projects.

`MSB4057 - The target "CollectBuildAccelerationIncompatiblePackageDesignTime" does not exist in the project.`

I tried turning off Build Acceleration with a Directory.Build.props file containing the following:

```
<Project>
    <PropertyGroup>
        <AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
    </PropertyGroup>
</Project>
```

But it did not solve the issue. After adding the .props file, I got two additional errors:

`WIX0200	The Package element contains an unhandled extension element 'WixUI'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/ui' namespace has been provided.`

`WIX0200	The Package element contains an unhandled extension element 'QueryWindowsDirectories'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/util' namespace has been provided.`

* Describe the behavior you expected and how it differed from the actual behavior.

> I expected the project to build and produce a .msi file, but it errored out instead.

**Comment by barnson** [comment]
Works on My Machine(TM). Please attach a .wixproj demonstrating the problem.

**Comment by redtrina817** [comment]
> Works on My Machine(TM). Please attach a .wixproj demonstrating the problem.

I'll create one and send it. Did you have to turn off build acceleration?

**Comment by barnson** [comment]
Works with and without it.

**Comment by nickgrishaev** [comment]
VS 2022 17.7 -  my WIX project compiled fine.
Today I have updated Visual Studio to 17.8  After VS updated, compilation failed.
After update comilation failed.

A received multiply error what I need add link to differents WIX namespaces.
For example for one of file in project:

error WIX0200: The Package element contains an unhandled extension element 'DotNetCompatibilityCheck'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/netfx' namespace has been provided.

This wxi file with error:
<Include xmlns="http://wixtoolset.org/schemas/v4/wxs"
		  xmlns:netfx="http://wixtoolset.org/schemas/v4/wxs/netfx">
	<Launch Condition="Installed OR (VersionNT &gt;= 600)" Message="This application is only supported on Windows Vista, Windows Server 2008, or higher." />

	<PropertyRef Id="WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED" />
	<Launch Condition="Installed OR WIX_IS_NETFRAMEWORK_48_OR_LATER_INSTALLED" Message="This installation requires .NET Framework 4.8 or later. Please install the .NET Framework 4.8 or later then run this installer again." />
	<Launch Condition="Installed OR NET5PRESENT" Message="This application requires .NET 7. Please install the ASP.NET Core Runtime 7 Hosting Bundle then run this installer again." />

	<netfx:DotNetCompatibilityCheck
		  Platform="x64"
		  Property="DOTNETRUNTIMECHECK"
		  RollForward="major"
		  RuntimeType="aspnet"
		  Version="7.0.0"
  />
</Include>


Looking for how to downgrade VS:-(

**Comment by nickgrishaev** [comment]
After downgarde Visual Studio to version 17.7.6 my project compilation go without error.

 IMHO - VS 17.8 not compatible with WIX 4

**Comment by redtrina817** [comment]
I was able to get my WiX v4 project working on a different machine. I'm not sure why yet it doesn't work on my other machine yet though. The machine it's working on was set up from scratch.

**Comment by redtrina817** [comment]
> Looking for how to downgrade VS:-(

You can downgrade from the VS installer. Click More > Rollback to previous version.

I will note that the machine it's not working on was upgraded from 17.7.6 -> 17.8

**Comment by redtrina817** [comment]
After upgrading the Heatwave extension from 1.0.1 to 1.0.2 the errors went away. Closing this issue.
