### ISSUE TITLE
Macro $(ConfigurationName) not expanding in post-build event when building bootstrapper.

### ISSUE THREAD

**Issue by joseangelmt** [wixtoolset/issues#7866]
## Bugs

* Which version of WiX are you building with?

> 4.0.2

* Which version of Visual Studio are you building with (if any)?

> 17.8.0

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> Heatwave 1.0.2

* Which version of .NET are you building with?

> .NET 7

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> (Windows version)

* Describe the problem and the steps to reproduce it.

> I've the next Post-build event command line to rename the output executable:

```
ren "$(TargetDir)Setup.exe" "Setup_$(ConfigurationName).exe"
```

The Post-build event runs but it does not expand the macro `$(ConfigurationName)` so the name of the executable after finishing the compilation is:  `Setup_.exe`.

* Describe the behavior you expected and how it differed from the actual behavior.

> If the configuration name is "en-us", I want the final executable named: `Setup_en-us.exe`

**Comment by chrpai** [comment]
This appears to be a Heatwave bug, an SDK targets bug, or a misalignment between the two.  If I author a postbuild it puts it in the primary property group.  For console app sdk project type it authors it as:

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /y &quot;$(TargetPath)&quot; C:\GitHub" />
  </Target>
  
  If I move this to the .wixproj msbuild processes it correctly but HeatWave doesn't see it in the property designer.
  
  @joseangelmt  as a workaround you could just define the OutputName property is $(MSBuildProjectName)-$(ConfigurationName).  This way you wouldn't need the postbuild command.

**Comment by joseangelmt** [comment]
Unfortunately, the workaround did not work, as it does not seem to expand the macro in OutputName either.

```xml
  <PropertyGroup>
    <OutputName>Setup_$(ConfigurationName)</OutputName>
    <OutputType>Bundle</OutputType>
  </PropertyGroup>
```

**Comment by barnson** [comment]
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) as an attachment or GitHub repo.

**Comment by barnson** [comment]
This is how SDK-style projects work. See https://github.com/firegiant/HeatWaveSupport/issues/44.
