### ISSUE TITLE
. error DARK0182 : Cannot find the table definitions for the ' ISDRMFiIe' table. This is likely due to a typing dark. exe error or missing extension. Please ensure all the necessary extensions are supplied on the command line with the -ext parameter.

### ISSUE THREAD

**Issue by rajeshvku** [wixtoolset/issues#7872]
. error DARK0182 : Cannot find the table definitions for the ' ISDRMFiIe' table. This is likely due to a typing
dark. exe
error or missing extension. Please ensure all the necessary extensions are supplied on the command line with the -ext
parameter.

**Comment by rajeshvku** [comment]
Trying to decompile msi file generated from installshield to wix using dark.exe

**Comment by chrpai** [comment]
Out of curiosity, does this MSI fully pass validation?  Additionally, if you are trying to convert an InstallShield MSI to a WiX MSI, I could give you an hour of my time to show you easier ways then dark to do it.

**Comment by rajeshvku** [comment]
it is valid and functional MSI file from installshield

**Comment by rajeshvku** [comment]
@chrpai  Can you please give steps to convert msi to wxs,

**Comment by barnson** [comment]
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) as an attachment or GitHub repo.

**Comment by barnson** [comment]
If this repros with WiX v4, let us know and we can investigate.

**Comment by hliebig-zeiss** [comment]
Quick fix / workaround is to use Orca and remove the ISDRMAttribute entries from the _Validation table
