### ISSUE TITLE
ArpEntry doesn't read UninstallString and doesn't support additional arguments

### ISSUE THREAD

**Issue by nirbar** [wixtoolset/issues#7877]
* Which version of WiX are you building with?
4.0.2

* Describe the problem and the steps to reproduce it.
I have a bundle that install an ExePackage and uses ArpEntry to uninstall.
That package creates an ARP entry that contains `UninstallString` but doesn't contain `QuietUninstallString`
During uninstall I get a failure saying `QuietUninstallString is null`

* Describe the behavior you expected and how it differed from the actual behavior.
I would like ArpEntry to fallback to reading `UninstallString` if  there's no `QuietUninstallString`.
Additionally, to make uninstall run silently, I would like ArpEntry to use the `ExePackage @UninstallArguments` attribute for the uninstall command line. It might be a good idea for the ArpEntry to read the `UninstallArguments` even if `QuietUninstallString` does exist to allow flexibility to the bundle author

**Comment by barnson** [comment]
We discussed falling back from `QuietUninstallString` to `UninstallString` but decided against it. But failing without is bad so we agree that there should be an `UninstallCommand` attribute that would let you override the entire command line (not just adding switches). Does that sound reasonable?

**Comment by nirbar** [comment]
Why not use `UninstallString`? It is the same as `QuietUninstallString` except the silencing flag, so it already has the full path of the uninstaller, stored in a secure registry location.
Using an arbitrary `UninstallCommand` might launch an unsafe elevated process

**Comment by barnson** [comment]
> It is the same as QuietUninstallString except the silencing flag

That's not guaranteed, which is one of the reasons we decided against falling back automatically. Maybe it can fall back only if additional arguments are supplied? Leaving open for triage again.

**Comment by nirbar** [comment]
AFAIK `UninstallString` is used by ARP so that is the guaranteed option, while `QuietUninstallString` is the nice-to-have option. How about adding a `PreferQuietUninstallString="yes/no"` attribute with "yes" default?

**Comment by barnson** [comment]
It's the only safe default. If we go back to your original idea of appending arguments, then the story is "if arguments are provided, use `UninstallString`; otherwise `QuietUninstallString` is correct." If there are no additional arguments, `QuietUninstallString` must exist.

**Comment by barnson** [comment]
Though, naturally, that also opens us up to Little Bobby Tables injection...

**Comment by nirbar** [comment]
Adding arguments can be helpful for both, like `-norestart -log ...`

**Comment by nirbar** [comment]
OK, implemented in the PR
