### ISSUE TITLE
Find and Replace

### ISSUE THREAD

**Issue by computerquip-work** [wixtoolset/issues#7881]
## Feature requests

* Describe the scenario and benefits that the feature supports.

> InstallShield and AdvancedInstaller both provide "extensions" that allow one to generically search for a string such as `$REPLACEME` and replace with a value given by the user at install time. WiX is capable of such but it's mighty inconvenient in its current form and requires a bit of research and work. There are already [attempts](https://github.com/rottedfrog/TextReplace) at doing this as well but they're a bit outdated and unmaintained at this point.

* Describe how you're accomplishing the feature today (if possible).

> So far, I've been lucky in that I can change most of my configuration formats to fit the needs of WiX. I find this to be quite backwards. I recently didn't have such luck and it became a real problem since WiX doesn't understand the configuration file format and there is no real convenient way of accomplishing the task. It turned into custom data to a custom action that invoked PowerShell initially which was pretty awful and I'm not sure if it actually worked how I intended.

* Describe what you'd like the new feature to do.

> At install time, I'd like the user to be able to provide values that the installer can use to generate an initial configuration file. There's a few ways to go to accomplish that.
> * A regular expression search and replace in the style of sed
> * A templating engine in the style of jinja or similar
> * Something real simple similar to envsubst on Linux.

**Comment by chrpai** [comment]
Have you checked out https://github.com/dblock/msiext ?

**Comment by barnson** [comment]
Already supported: https://wixtoolset.org/docs/schema/util/formatfile/

**Comment by computerquip-work** [comment]
I had no idea this existed, thanks.
