### ISSUE TITLE
wix.exe : error WIX0001: System.UnauthorizedAccessException: Access to the path 'WixValidator' is denied.

### ISSUE THREAD

**Issue by HeikeHofmann** [wixtoolset/issues#7897]
## Bugs

If this issue is a bug:

* Which version of WiX are you building with?

> 4.0.1

* Which version of Visual Studio are you building with (if any)?

> 17.8.2

* Which version of the WiX Toolset Visual Studio Extension are you building with (if any)?

> None (only use nuget packages)

* Which version of .NET are you building with?

> .NET 6

* If the problem occurs when installing your packages built with WiX, what is the version of Windows the package is running on?

> Windows 10

* Describe the problem and the steps to reproduce it.

> We have a simple default project with only one file added.
> Compile fails sporadisch, but often with this error.

> **But we have found a complete strange new event log entry at compile runtime, which we haven't see with WiX3:** 
'Windows Installer installed the product. Product Name: ...'

* Describe the behavior you expected and how it differed from the actual behavior.

> Compile should work 100%, never fail with WIX0001
> EventLog shouldn't list any installation activity at build computer. Does that mean, that WiXValidator is executing installation? and can this be disabled ?

**Comment by HeikeHofmann** [comment]
We have disabled validation now:
<SuppressValidation>true</SuppressValidation>

**Comment by barnson** [comment]
Please paste in the stack trace for the error so we can investigate.
