### ISSUE TITLE
Accessibility: voiceover does not report "Installation was Successful"

### ISSUE THREAD

**Issue by mgreenegit** [wixtoolset/issues#7918]
### WiX Version

4

### .NET or MSBuild or Visual Studio Version

na

### HeatWave Version

na

### Windows Version

Win11

### Repro Steps

1. Start a MSI installer built from WiX that has the default Welcome Dialog
2. Start Narrator (Ctrl+Win+Enter)
3. Start Scan Mode (Insert+Space)
4. Complete the installation

### Actual Result

At the end of the installation, the text is not read correctly

### Expected Result

Expect text to be read by voiceover

**Comment by barnson** [comment]
Which text?

**Comment by barnson** [comment]
We can't do much without a useful bug report.
