### ISSUE TITLE
Wix Bundle flagged as torjan when executed 

### ISSUE THREAD

**Issue by MoonLigh1** [wixtoolset/issues#7920]
### WiX Version

4.0.1

### .NET or MSBuild or Visual Studio Version

Visual Studio 17.6.5

### HeatWave Version

1.0.2.1

### Windows Version

Windows Server 21H2 OS Build 20348.2031

### Repro Steps

1.  Create Bundle containing different exe and msi in chain
2. Run the bundle on latest updated windows 10 or windows 11 machine 
3. Your installer will be flagged as a virus
4. In windows defender I saw this 
![image](https://github.com/wixtoolset/issues/assets/89302206/2e2380bd-b0ab-4a4e-8fea-1f3db40b8909)
 

### Actual Result

![image](https://github.com/wixtoolset/issues/assets/89302206/a6ae0f81-1909-4bb5-b2e2-abeb5391eeae)

Afterwards the bundle exe is also deleted by windows defender

### Expected Result

I expected my bundle to run fine as it always used to do its that recently this thing popped up, also I tested my previous versions of bundle build the same way (almost a month ago) that worked fine before now they are also marked as a trojan.

**Comment by NJullienSweet** [comment]
Same for me, I have a Bundle downloading and installing .NET, Edge WebView2 Evergreen and my product MSI.

**Comment by robmen** [comment]
When your product gets flagged by anti-virus vendors, you have two options, and it is probably best to do both:

1. Sign your installation
2. Send your installation to the anti-virus vendors as a false positive
