### ISSUE TITLE
Can't install with `dotnet tool`

### ISSUE THREAD

**Issue by brandonh-msft** [wixtoolset/issues#7923]
### .NET or MSBuild or Visual Studio Version

.NET 8.0.100

### Windows Version

Win11 23H2

### Repro Steps

`> dotnet tool install -g wixtoolset.sdk`

### Actual Result

```
Skipping NuGet package signature verification.
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'wixtoolset.sdk' failed to install. Contact the tool author for assistance.
```

### Expected Result

a successful installation

**Comment by robmen** [comment]
`WixToolset.Sdk` is an MSBuild SDK, not a dotnet tool. You probably were looking for `wix`. [See the doc](https://wixtoolset.org/docs/intro/#nettool).

**Comment by brandonh-msft** [comment]
> `WixToolset.Sdk` is an MSBuild SDK, not a dotnet tool. You probably were looking for `wix`. [See the doc](https://wixtoolset.org/docs/intro/#nettool).

Thanks was coming to update just now; got this syntax from the referenced issue

**Comment by brandonh-msft** [comment]
How about this? Looks like the proj I'm trying to build isn't on SDK-Style for its `wixproj` file, so am trying to "downgrade" to wix v3:

```
> dotnet tool install -g wix --version 3.11.2
C:\Users\hurlburb\AppData\Local\Temp\0de4eb2e-5069-43ab-868b-f6fe7daaa777\restore.csproj : error NU1212: Invalid project-package combination for W
iX 3.11.2. DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'wix' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

this should work, right @robmen ?

**Comment by barnson** [comment]
WiX v3 isn't available as a tool or sdk. That's all new to WiX v4.

**Comment by robmen** [comment]
No. WiX v3 does not support running on .NET Core. It was designed before .NET Core existed. The last non-security release for WiX v3 was 2017.

[Unless you have a support contract](https://www.firegiant.com/services), you should be planning to upgrade to WiX v4. WiX v3 will be unsupported soon.

**Comment by brandonh-msft** [comment]
> WiX v3 isn't available as a tool or sdk. That's all new to WiX v4.

how do i get v3? i'm not really worried about support, just trying to build an OSS project that, apparently, requires wix v3 to `dotnet publish` its installer
