### ISSUE TITLE
Page Not Found: http://wix.codeplex.com/releases/view/93929

### ISSUE THREAD

**Issue by Praveer1981** [wixtoolset/issues#7934]
### WiX Toolset Page URL

https://wixtoolset.org/news/2012/12/24/wix-v3-7-released/

### Additional information (optional)

Hi, I need to download wix toolset 3.7 version

https://wixtoolset.org/news/2012/12/24/wix-v3-7-released/ this link has given another link to download , but the page has already expired. any advice where can I download wix toolset 3.7 from ?
thanks in advance

**Comment by barnson** [comment]
WiX v3.7 was released 11 years ago today, has known security vulnerabilities, and is no longer available.

**Comment by barnson** [comment]
https://wixtoolset.org/news/ has all the announcements.
