### ISSUE TITLE
 After using a Include.wxi the WiX installer (.exe) triggers a false positive for Trojan:Win32/Wacatac.B!ml on Windows 10

### ISSUE THREAD

**Issue by cathalmccosker** [wixtoolset/issues#7937]
### WiX Version

4.0.0

### .NET or MSBuild or Visual Studio Version

Visual Studio 2022 (64 bit) - Current Version 17.7.3 

### HeatWave Version

1.0.2

### Windows Version

Win10 22H2

### Repro Steps

1. Setup your MSI and Installer as normal
2. Add a Include.wxi, include the %userprofile% folder as a variable and reference it in your Folders.wxs/Bundle.wxs

### Actual Result

The .exe builds out normally, but when you drag it to a vanilla Windows 10 virtual machine the .exe installer gets flagged a false positive for Trojan:Win32/Wacatac.B!ml.

I've only recently added the Include.wxi and after testing I found this issue. If I walk back my changes and remove the Include.wxi and references to the %userprofile% folder then it doesn't trigger the false-positive.

The reason that I want to reference the %userprofile% folder is that it is currently hardcoded to my machine (and my user folder) but if I want to use a different machine and build from there I need to reference %userprofile%. 

### Expected Result

Adding a Include.wxi shouldn't trigger a false-positive from Windows Defender.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by ToreDemant** [comment]
We see something similar where our setup executable is put into quarantine shortly after creation. It started happening right after upgrading from version 4.0.2 to 4.0.3, but could be unrelated.

**Comment by barnson** [comment]
Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) as an attachment or GitHub repo. It's _extremely_ unlikely that an include file is causing a problem; installers routinely get false positives, especially when they are new and/or unsigned.

**Comment by robmen** [comment]
@barnson is correct, but this is an external issue. When your product gets flagged by anti-virus vendors, you have two options, and it is probably best to do both:

* Sign your installation
* Send your installation to the anti-virus vendors as a false positive

It is in the best interest of anti-virus companies to "over-classify" code as viruses rather than miss potential issues. Unfortunately, setup work looks a lot like virus work because we both do "elevation", "extracting files", "putting files in important places on the machine". You have to do the above to anti-virus vendors to get your product out of their over-classification.

It is likely that once enough people submit their various installations using the WiX Toolset as false positives anti-virus vendors will figure out how to correctly classify normal setups.

**Comment by cathalmccosker** [comment]
> Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) as an attachment or GitHub repo. It's _extremely_ unlikely that an include file is causing a problem; installers routinely get false positives, especially when they are new and/or unsigned.

Unfortunately I don't have time to recreate this, I need to move on with the project and reverting solves the problem for me. I'm just highlighting it in case someone else has a similar experience. 

The include .wxi referencing the %userprofile% is the _only_ thing that was changed. After the initial false-positive I tried signing the .exe with my own .pfx and signtool but the problem occurred again. Reverting back to the hardcoded location and removing the .wxi was the fastest way to solve the issue for me.

**Comment by JornWildt** [comment]
> The include .wxi referencing the %userprofile% is the only thing that was changed.

I have a case where we build a WIX4 MSI installation program. I have built exactly the same program twice, with exactly the same code commit and pipeline setup, the one built on the first day is fine, the one built on the second day is detected as containing the Wacatac virus. 

File sizes are identical. Both are signed with the same code signing certificate - only difference is the timestamp.

Go figure????

**Comment by cornem** [comment]
I have the same problem. New MSI built after minimal code changes now gets removed immediately by Windows Defender. I'm guessing they changed some things on their end, though...
