### ISSUE TITLE
UninstallString in registry is wrong

### ISSUE THREAD

**Issue by benperet** [wixtoolset/issues#7941]
### WiX Version

4.0.3

### .NET or MSBuild or Visual Studio Version

8.0.100

### HeatWave Version

1.0.2.1

### Windows Version

Win11 22h2

### Repro Steps

1. Install MSI
2. Go to its registry hive and look at "UninstallString".

### Actual Result

The UninstallString contains for example: "MsiExec.exe /I{6795E009-AAA2-40B1-95FA-8ECA24681312}".
![image](https://github.com/wixtoolset/issues/assets/99246342/49d5a9dd-e471-4734-97d9-65999a675a69)

### Expected Result

UninstallString should be something like this: "MsiExec.exe /X{6795E009-AAA2-40B1-95FA-8ECA24681312}".

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Windows Installer writes `Uninstall` key values for MSI packages. [WiX isn't involved other than letting you author properties.](https://stackoverflow.com/questions/10280952/uninstallstring-being-set-with-i-not-x-param)
