### ISSUE TITLE
Component identifier does not defaults to the identifier of the resource that is the explicit keypath of the component

### ISSUE THREAD

**Issue by danielh1989** [wixtoolset/issues#7945]
### WiX Version

4.0.3

### .NET or MSBuild or Visual Studio Version

VS Version 17.8.3

### HeatWave Version

1.0.2.1

### Windows Version

Windows 10 22H2

### Repro Steps

1. Have an existing Wix 3 project with following code:
`...`
`<ComponentRef Id="_MsgPack_dll_e3be" />`
`...`
`<Component Guid="6a2255db-b511-48a4-8550-e7422112b31a" Permanent="no" SharedDllRefCount="no" Transitive="no" Directory="TARGETDIR">`
`        <File Id="_MsgPack_dll_e3be" DiskId="1" Hidden="no" ReadOnly="no" TrueType="no" System="no" Vital="yes" Name="MsgPack.dll" Source="MsgPack.dll" KeyPath="yes" />`
`</Component>`
3. Convert existing Wix 3 project to Wix 4

### Actual Result

Getting following compilation error:
`Error	WIX0094	The identifier 'Component:_MsgPack_dll_e3be' is inaccessible due to its protection level.`

### Expected Result

The Id of the File should be used and available as component ID as described in the documentation:
`Id (String) : Component identifier; this is the primary key for identifying components. If omitted, the compiler defaults the identifier to the identifier of the resource that is the explicit keypath of the component (for example, a child File element with KeyPath attribute with value 'yes').`

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Accessibility of the keypath id should travel to the component id.

**Comment by barnson** [comment]
Eventually. For WiX v5, document the need for explicit ids if you want them outside the section.

**Comment by robmen** [comment]
This happened to get fixed in WiX v5-rc.1 as part of https://github.com/wixtoolset/wix/pull/496 while implementing out-of-proc BAs
