### ISSUE TITLE
The CoreCompile step using wix.exe does not include in parameters the .wxs files generated by heat.exe

### ISSUE THREAD

**Issue by 0xAndre** [wixtoolset/issues#7946]
### WiX Version

4.0.3

### .NET or MSBuild or Visual Studio Version

MSBuild version 17.7.2+d6990bcfa for .NET Framework

### HeatWave Version

n/a?

### Windows Version

Windows Server 2016 | Version 1607 OS Build 14393.6452

### Repro Steps

![image](https://github.com/wixtoolset/issues/assets/17546189/b3a38aad-cb10-40fd-b3ae-fbfa2e1a4bef)

In BeforeBuild step, 2 .wxs files (ServiceDesignerPackageFiles.wxs and CommonPackageFiles.wxs) are generated that do not exist initially in the folder. The files are successfully generated in BeforeBuild; however, in CoreCompile, this files are not passed in the parameters.

The CoreCompile step using wix.exe does not include in the parameters .wxs files generated by heat.exe when they are generated in the BeforeBuild.

![image](https://github.com/wixtoolset/issues/assets/17546189/deb3eba1-e53d-46e1-b383-672d17f85229)

If you try to compile again with the .wxs files already in the folder, wix.exe includes them in the parameters:

![image](https://github.com/wixtoolset/issues/assets/17546189/6e4356c5-3d66-46e0-ae58-b5f48144757f)

I tried adding a wait between BeforeBuild and CoreCompile in Setup.wixproj, thinking it could be a synchronization issue, but the problem persisted.

Workaround: I created ServiceDesignerPackageFiles.wxs and CommonPackageFiles.wxs empty. With this empty files created, the build was successful, and the .msi was generated. This leads me to believe that the empty files are not used, but rather the .wxs files generated by heat.exe.

I'm not sure if the bug might be in heat.exe, wix.exe, or another point that I am not aware of.

### Actual Result

The .wxs files generated by heat.exe are not being passed in the parameters of wix.exe

### Expected Result

The .wxs files generated by heat.exe need to be passed in the parameters of heat.exe

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
This issue is unlikely to gain traction without a repro.

**Comment by barnson** [comment]
Your project needs to do the same kind of work that [`HarvestDirectory`](https://wixtoolset.org/docs/tools/heat/) does to get generated names into the list of files to be compiled. Or just use `HarvestDirectory` and let it do the work.
