### ISSUE TITLE
Schema URL redirects to... YouTube video?

### ISSUE THREAD

**Issue by mbucchia-msft** [wixtoolset/issues#7964]
### WiX Toolset Page URL

http://wixtoolset.org/schemas/v4/wxs

### Page URL that linked to WiX Toolset

https://wixtoolset.org/docs/schema/wxs/

### Additional information (optional)

Schema URL http://wixtoolset.org/schemas/v4/wxs as listed in https://wixtoolset.org/docs/schema/wxs/

Maybe I have the wrong schema URL, or this is an inside joke I'm not getting... it's redirecting me to https://www.youtube.com/watch?v=8-r-V0uK4u0.

**Comment by mbucchia-msft** [comment]
Would it be more useful to redirect to something more meaningful than the youtube video? Like the GitHub issue?

**Comment by barnson** [comment]
🤷 The XSDs are in the HeatWave extension for VS Intellisense and in the Web repo for anyone who wants the files.
