### ISSUE TITLE
Allow setting the Group name for a FirewallException

### ISSUE THREAD

**Issue by Germs2004** [wixtoolset/issues#7975]
### User story

Once upon a time, there was a developer trying to figure out how to use WiX 4.0.3 in Visual Studio 2022 17.8.5 to create an installer for his application.  He ran into a problem where the Windows Firewall rule WiX created had a blank Group name, and he couldn't figure out how to specify a name within WiX.  So, he created a GitHub issue asking for the feature to be added.  The maintainers of the WiX project read his Issue and realized that this developer had no idea what a "User story" was, and they were correct.

### Proposal

In the Windows Firewall Advanced screen that lists all the rules, there is a "Group" column for each rule.  When I create a rule with WiX, its group is just blank.  Please allow us to specify a "group" name when creating a FirewallException.

For example:
`<fire:FirewallException Name="MyRuleName" Group="MyGroupName" Program="[MyInstallFolder]MyProgramName.exe" Scope="any" />`

### Considerations

If it cannot be done seamlessly by WiX, is there a way to use PowerShell or some other custom command within WiX to do it?  Thank you.

**Comment by barnson** [comment]
Wish granted. This is already supported in WiX v5.
