### ISSUE TITLE
Page Not Found: 

### ISSUE THREAD

**Issue by Joseph-Ndungi** [wixtoolset/issues#8016]
### WiX Toolset Page URL

https://wixtoolset.org/schemas/v4/wxs/ui

**Comment by barnson** [comment]
Namespaces are URIs, not URLs. See https://www.firegiant.com/docs/wix/tutorial/sprint1/spike-explore-package/. XSDs are available at https://github.com/wixtoolset/web/tree/master/src/xsd4.
