### ISSUE TITLE
Votive2022.vsix installation failed

### ISSUE THREAD

**Issue by mhendravarmansiemens** [wixtoolset/issues#8021]
### WiX Version

4.0.3

### .NET or MSBuild or Visual Studio Version

.net 8.04084

### HeatWave Version

1.0

### Windows Version

Win10 22H2

### Repro Steps

1. 
2. 

### Actual Result

[dd_VSIXInstaller_20240308092600_0754.log](https://github.com/wixtoolset/issues/files/14533165/dd_VSIXInstaller_20240308092600_0754.log)

### Expected Result

the wix tool should be installed

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/7266
