### ISSUE TITLE
WiX Toolset 5.0.0-rc.1 produces Deutsch msi with en-ca language setting

### ISSUE THREAD

**Issue by jcasale** [wixtoolset/issues#8036]
### WiX Version

5.0.0-rc.1

### .NET or MSBuild or Visual Studio Version

n/a

### HeatWave Version

n/a

### Windows Version

Windows Server 2022

### Repro Repo

https://github.com/jcasale/vim-msi-dev

### Repro Steps

1. Install wix toolset:
    ```
    dotnet.exe tool install --global wix --prerelease --verbosity diag
    wix.exe extension add WixToolset.UI.wixext --global
    wix.exe extension add WixToolset.Util.wixext --global
    wix.exe extension list --global
    nuget.exe install WixToolset.Heat -Prerelease -NonInteractive -Verbosity detailed
    ```
2. Clone the repro repo from https://github.com/jcasale/vim-msi-dev into the current directory.
3. Download and unpack the Windows gvim x64 zip archive from https://github.com/vim/vim-win32-installer into a `build` directory.
4. Harvest vim using the `heat.exe` that was downloaded above:
    ```PowerShell
    heat.exe `
      dir `
      build\vim\vim91 `
      -nologo `
      -cg ProductComponents `
      -g1 `
      -ag `
      -ke `
      -srd `
      -dr INSTALLDIR `
      -sfrag `
      -sreg `
      -var var.VimSource `
      -o build\Fragment.wxs
    ```
5. Build the msi after updating the `ProductVersion` to that of the gvim version that was downloaded above:
    ```PowerShell
    wix.exe `
      build `
      -arch x64 `
      -src src\Product.wxs build\Fragment.wxs `
      -d VimSource="build\vim\vim91 `
      -d SrcDirectory=src `
      -d ProductVersion="9.1.XXXX" `
      -d ProductVersionMajor="9" `
      -d ProductVersionMinor="1" `
      -ext WixToolset.UI.wixext `
      -ext WixToolset.Util.wixext `
      -out vim.msi
    ```

The repro repro has an action that automates this, it needs a personal access token as documented in the action.

The associated discussion can be found at [8034](https://github.com/orgs/wixtoolset/discussions/8034).

### Actual Result

The resulting msi appears to be Deutsch despite the [Package](https://github.com/jcasale/vim-msi-dev/blob/187f2ec9eeed4f4d5892b414da01bb8f31bdc66c/src/Product.wxs#L6) element having its `Language` attribute set to 1033.

### Expected Result

The resulting msi should be English (United States).

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Fix now available in WiX v5.0.0-rc.2.
