### ISSUE TITLE
WiX Toolset 5.0.0-rc.1<Files> issue with subfolders

### ISSUE THREAD

**Issue by Thylon1** [wixtoolset/issues#8040]
### WiX Version

5.0.0-rc.1

### .NET or MSBuild or Visual Studio Version

.NET 8

### HeatWave Version

N/A

### Windows Version

Windows Server 2019 / Win10

### Repro Repo

https://github.com/Thylon1/WebApplication1

### Repro Steps

1. Create a .NET project where the build output contains multiple subfolders
2. Harvest the output using the new <Files> element
3. Install the created MSI

--
Or download the provided repro repo and build its MSI.

Related discussion with screenshots #8039 

### Actual Result

After installing the MSI, all the subfolders were nested inside each other.

### Expected Result

Each subfolder should be on the same level and not nested inside each other.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Fix now available in WiX v5.0.0-rc.2.
