### ISSUE TITLE
FirewallException (v5) Profile regression

### ISSUE THREAD

**Issue by dorssel** [wixtoolset/issues#8043]
### WiX Version

5.0.0-rc.1

### .NET or MSBuild or Visual Studio Version

.NET 8.0.202

### HeatWave Version

1.0.2

### Windows Version

Win10 22H2

### Repro Repo

https://github.com/dorssel/usbipd-win

### Repro Steps

1. Have a FirewallException (v4) with an explicit Profile="all" property
2. Update to FirewallException (v5); see https://github.com/dorssel/usbipd-win/pull/891/files

### Actual Result

See: https://github.com/dorssel/usbipd-win/actions/runs/8263029572/job/22603593353?pr=891#step:10:47

> error WIX1076: ICE03: String overflow (greater than length permitted in column); Table: Wix5FirewallException, Column: Profile, Key(s): usbipd

### Expected Result

No error (or warning) when updating WixToolset.Firewall v4 -> v5

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by dorssel** [comment]
Edited: I originally thought it was about the Description property, but it turns out it is the Profile column that produces the error.

**Comment by dorssel** [comment]
Investigated:

It's the _Validation table that is wrong.

Currently it lists:

```
Wix5FirewallException	Profile	Y	1	2147483647			Formatted		Profile (1=domain; 2=private; 4=public; 2147483647=all).
```

It should not be Category=Formatted, but Category=`null` (see https://learn.microsoft.com/en-us/windows/win32/msi/-validation-table)

There is another definition wrong:

```
Wix5FirewallException	Direction	N	1	2			Integer		Direction (1=in; 2=out)
```

That does not give an error, but Category is never "Integer", it should be `null` instead.

**Comment by barnson** [comment]
It's a formatted (string) field (to support setting the profile at install time) but was limited to four characters.

**Comment by dorssel** [comment]
@barnson 
If I'm not mistaken, the field in the Wix5FirewallException table is actually an integer (flags). And ICE03 validates it according to the _Validation table. In WiX it is a text, but it gets translated to integer flags. I still think the _Validation table is wrong. Maybe there was *also* something wrong with the WiX text field. I don't know, since I only used "all". But in the final Wix5FirewallException table it is definitely a number...

**Comment by barnson** [comment]
It's formatted so you can author `Profile="[PROFILE]"` and have the type of profile specified at install time via the `PROFILE` property. If you use one the enum values, it'll get a number (but still be a string field): https://github.com/wixtoolset/wix/blob/develop/src/ext/Firewall/wixext/FirewallConstants.cs

**Comment by dorssel** [comment]
Ah, I see, so it can be either, including text. Yes, then formatted makes sense.
(Do note that the "Integer" in the Direction field should still probably be <null>, though).

Thanks for clarifying and fixing!
