### ISSUE TITLE
Wix extension fails to download

### ISSUE THREAD

**Issue by deeplow** [wixtoolset/issues#8044]
### WiX Version

4.0.4-a8592982

### .NET or MSBuild or Visual Studio Version

7.0.102

### HeatWave Version

(not using VS Studio)

### Windows Version

Win 11 22H2

### Repro Repo

(irrelevant)

### Repro Steps

1. `wix extension add WixToolset.UI.wixext`

### Actual Result

1. The exension `C:\users\user\.wix\extensions\WixToolset.UI.wixext\<VERSION>\` is empty
2. `wix extension list` shows the extension but with `(damaged)`

### Expected Result

1. `wix extension list` shows without the "(damaged)"
2. Extension dll is downloaded to the appropriate folder

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Use `wix extension add WixToolset.UI.wixext/4.0.4` to get a compatible version of the .wixext. (V5 is up on NuGet.org now.)

**Comment by barnson** [comment]
WiX extension versioning is independent of WiX versioning -- except that major versions of WiX can introduce breaking interface changes, which is what happened with WiX v5. See also https://github.com/wixtoolset/issues/issues/8033.
