### ISSUE TITLE
msi decompile -x deletes everything on the selected folder

### ISSUE THREAD

**Issue by Signum21** [wixtoolset/issues#8052]
### WiX Version

4.0.4+a8592982

### .NET or MSBuild or Visual Studio Version

.NET 6.0.420

### HeatWave Version

-

### Windows Version

Win10 22H2

### Repro Steps

```
wix msi decompile .\installer.msi -x .
```

### Actual Result

The current directory was emptied.

### Expected Result

The user should be warned that everything in the directory is going to be deleted, even though in my opinion, it would be better not to do so.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Should ensure it goes to an empty directory or works around the issue when extracting cabs.
