### ISSUE TITLE
WiX 3.11.2 -> 3.14 breaks NetFx PackageGroup References

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#8062]
### WiX Version

3.14.0.8606

### .NET or MSBuild or Visual Studio Version

VS 2022 v17.10.0 and Azure DevOps MSFT Hosted Server Also

### HeatWave Version

N/A

### Windows Version

Win 11 23H2

### Repro Steps

1.  Create a bootstrapper project in 3.11 that uses NetFx and PakageGroupRefs such as NetFx45Web.  Verify it builds.
2.  Replace WiX 3.11 with 3.14.0.8606 and try to build the project.  

### Actual Result

3.14 should build like 3.11.2.

### Expected Result

  C:\Program Files (x86)\WiX Toolset v3.14\bin\Light.exe -out D:\a\9\s\Installer\REDACTED\REDACTEDBootstrapper\bin\Release\REDACTED.exe -pdbout D:\a\9\s\Installer\REDACTED\REDACTEDBootstrapper\bin\Release\REDACTED.wixpdb -ext "C:\Program Files (x86)\WiX Toolset v3.14\bin\\WixUtilExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.14\bin\\WixNetFxExtension.dll" -ext "C:\Program Files (x86)\WiX Toolset v3.14\bin\\WixBalExtension.dll" -contentsfile obj\Release\REDACTEDBootstrapper.wixproj.BindContentsFileList.txt -outputsfile obj\Release\REDACTEDBootstrapper.wixproj.BindOutputsFileList.txt -builtoutputsfile obj\Release\REDACTEDBootstrapper.wixproj.BindBuiltOutputsFileList.txt -wixprojectfile D:\a\9\s\Installer\REDACTED\REDACTEDBootstrapper\REDACTEDBootstrapper.wixproj obj\Release\pth2D33F127540E5920F4EC89507F4C872E\Bundle.wixobj
##[error]Installer\REDACTED\REDACTEDBootstrapper\Code\Bundle.wxs(12,0): Error LGHT0094: Unresolved reference to symbol 'ChainPackageGroup:NetFx40ClientRedist' in section 'Bundle:REDACTED'.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by chrpai** [comment]
Is there a reason all of the package groups were removed?  
 The commit is titled 'Update NetFx package groups for their SHA2 updates.' but the end result seems to be they are just gone.


https://github.com/wixtoolset/wix3/commit/03d9a66371d21906748cce2b5f40d25a0c34cd1f#diff-aef7faa1c362f6ba985165e57cff659aeeec7d2f06e1a4bac24ad06a3a80fdec

**Comment by chrpai** [comment]
Copying the WixNetFxExtension.dll from the 3.11 to the 3.14\bin folder makes this error go away.

**Comment by chrpai** [comment]
@robmen I see you addressed the CUB issue and commented 3.14.1.  Do you have an official comment on this issue?  I'm just curious so I can relay the right messaging to the team that manages the Azure and GH runner images.

**Comment by barnson** [comment]
EOL package groups were removed.
