### ISSUE TITLE
WiX 3.14 introduces ICE103 validation error

### ISSUE THREAD

**Issue by chrpai** [wixtoolset/issues#8065]
### WiX Version

3.14.0.8606

### .NET or MSBuild or Visual Studio Version

VS 2022 v17.10.0 and Azure DevOps MSFT Hosted Server Also

### HeatWave Version

N/A

### Windows Version

Win 11 23H2

### Repro Repo

https://github.com/chrpai/repro9543

### Repro Steps

1. Create a WiX 3.14 merge module project in Votive
2. Make sure the Manufacturer attribute has a value.
3. Attempt to build it
4. Disable ICE103 and attempt to build it again.

### Actual Result

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error		Error executing ICE action 'ICE103'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor.  ".	Test	light.exe	0		

### Expected Result

I expected the merge module to build and validate without errors like in WiX 3.11.2.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by chrpai** [comment]
Copying the mergemod.cub from 3.11 into the 3.14  wix\bin folder makes this error go away.

**Comment by mk48** [comment]
> Copying the mergemod.cub from 3.11 into the 3.14 wix\bin folder makes this error go away.

Thanks, it worked for me
