### ISSUE TITLE
MSI Decompile results in trimmed source paths for File

### ISSUE THREAD

**Issue by nterhorst-eagerit** [wixtoolset/issues#8072]
### WiX Version

4.0.4

### .NET or MSBuild or Visual Studio Version

.NET 7.0.115

### HeatWave Version

1.0.2.1

### Windows Version

Win11

### Repro Steps

1.  Decompile msi with command "wix msi decompile "[Path to MSI file]" in Command Prompt
2.  Open the output .wxs file

### Actual Result

It seems that the generated node <File> contains an incomplete Source path, it looks trimmed. Below actual output:

<File Id="w1cv.twa.management.authoriz" Vital="no" ShortName="C23642~1.EXE" Name="W1cv.TWA.Management.AuthorizationCompiler.exe" Compressed="yes" KeyPath="yes" **Source="SourceDir\File\w1cv.twa.management.authoriz"** AssemblyManifest="w1cv.twa.management.authoriz" AssemblyApplication="w1cv.twa.management.authoriz" Assembly=".net" />

I have looked with Orca in the source MSI and in the File table, it seems the "File" field is used, but this can be trimmed so it seems. The "FileName" contains the actual full file name and thus this should be used I think?

### Expected Result

<File Id="w1cv.twa.management.authorizationcompiler.exe" Vital="no" ShortName="C23642~1.EXE" Name="W1cv.TWA.Management.AuthorizationCompiler.exe" Compressed="yes" KeyPath="yes" **Source="SourceDir\File\w1cv.twa.management.authorizationcompiler.exe"** AssemblyManifest="w1cv.twa.management.authorizationcompiler.exe" AssemblyApplication="w1cv.twa.management.authorizationcompiler.exe" Assembly=".net" />

This is what I would have expected. So using the FileName field for the Source path and not the File field.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
The decompiler uses the file id as the file name when extracting so it uses it for the Source value too.
