### ISSUE TITLE
Temp directory issue after wix v 4.0.5 upgrade

### ISSUE THREAD

**Issue by DipakTated** [wixtoolset/issues#8078]
### WiX Version

4.0.5

### .NET or MSBuild or Visual Studio Version

latest

### HeatWave Version

latest

### Windows Version

Win 10 64

### Repro Steps

Am getting this error
SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603

I also see, that regarding temp directory some breaking changes fixes are made by wix.  But how do i handle this code side issue at my end?

https://github.com/wixtoolset/issues/security/advisories/GHSA-rf39-3f98-xr7r

### Actual Result

SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603

### Expected Result

Success

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by robmen** [comment]
Can you please update the information above with your CustomAction element and where it is scheduled (the Custom element)? Those are very important pieces of information.

**Comment by richard-frolkovic** [comment]
Hi, I am facing the same issue.
My custom action is defined like this
<CustomAction Id="SetInstallFolderFromResponseFileCA" BinaryRef="CustomActionsDLL" DllEntry="SetInstallFolderFromResponseFile" Execute="immediate" />
<Custom Action="SetInstallFolderFromResponseFileCA" Before="CostFinalize" />

The issue seems to be, that the custom action server was moved from the temp folder to a system folder. Since immediate custom actions are to my knowledge always run as impersonated, they do not have the necessary elevated privileges.

**Comment by Smith00101010** [comment]
We have the same issue with Wix 3.14.1.

The Custom action related elements are:
```
<CustomAction Id="CA_SetupAccounts" BinaryKey="CustomActionsLib" DllEntry="SetupAccounts" Execute="immediate" Return="check"/>
<Custom Action="CA_SetupAccounts" After="CostFinalize"/>
```

The log output looks like this:
```
MSI (s) (38:F8) [11:29:24:214]: Doing action: CA_SetupAccounts
Action 11:29:24: CA_SetupAccounts. 
Action start 11:29:24: CA_SetupAccounts.
MSI (s) (38:34) [11:29:24:214]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI18C4.tmp, Entrypoint: SetupAccounts
MSI (s) (38:20) [11:29:24:214]: Generating random cookie.
MSI (s) (38:20) [11:29:24:214]: Created Custom Action Server with PID 4708 (0x1264).
MSI (s) (38:78) [11:29:24:230]: Running as a service.
MSI (s) (38:78) [11:29:24:230]: Hello, I'm your 32bit Impersonated custom action server.
SFXCA: Failed to create temp directory. Error code 5
CustomAction CA_SetupAccounts returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 11:29:24: CA_SetupAccounts. Return value 3.
Action ended 11:29:24: INSTALL. Return value 3.
```

If we execute the setup from a elevated command prompt it works, but we would like to avoid that if possible.

**Comment by robmen** [comment]
Interesting. I have this test:

```xml
<Binary Id="ManagedCA" SourceFile="TestCA.CA.dll" />

<CustomAction Id="ImmediateCA" BinaryRef="ManagedCA" DllEntry="ImmediateCA"
              Execute="immediate" Return="check" />

<InstallExecuteSequence>
  <Custom Action="ImmediateCA" Before="CostFinalize" />
</InstallExecuteSequence>
```

The MSI log file shows the Windows Installer using the user temp folder:

```log
MSI (c) (D8:F8) [07:01:21:794]: Doing action: ImmediateCA
MSI (c) (D8:F8) [07:01:21:794]: Note: 1: 2205 2:  3: ActionText 
Action 7:01:21: ImmediateCA. 
Action start 7:01:21: ImmediateCA.
MSI (c) (D8:5C) [07:01:21:796]: Invoking remote custom action. DLL: C:\Users\Rob\AppData\Local\Temp\MSICBED.tmp, Entrypoint: ImmediateCA
MSI (c) (D8:38) [07:01:21:797]: Cloaking enabled.
MSI (c) (D8:38) [07:01:21:797]: Attempting to enable all disabled privileges before calling Install on Server
MSI (c) (D8:38) [07:01:21:797]: Connected to service for CA interface.
SFXCA: Extracting custom action to temporary directory: C:\Users\Rob\AppData\Local\Temp\MSICBED.tmp-0\
SFXCA: Binding to CLR version v4.0.30319
Calling custom action TestCA!WixToolsetTest.TestCA.CustomActions.ImmediateCA
Begin ImmediateCA
Action ended 7:01:22: ImmediateCA. Return value 1.
```

I am on Windows 11 23H2, but this doesn't seem like something the Windows Installer would change.

**Comment by Bysza** [comment]
We face the same issue with 4.0.5. 
In 4.0.4 it works fine.

Definition:

```
<CustomAction Id="InstallSmth" DllEntry="InstallSmthDll" Execute="immediate" Impersonate="yes" Return="check" BinaryRef="our_bin" />

<InstallExecuteSequence>
   <Custom Action="InstallSmth" Before="StartServices" Condition="((NOT Installed AND NOT REMOVE) OR (IS_UPGRADE))" />
</InstallExecuteSequence>
```

**Comment by Yaswanth112** [comment]
We are also seeing same issue.
it was working fine, with wix version 4.0.4, but failing to install issue with version 4.0.5.

Here is how we defined CustomActions

<Binary Id="CustomActions" SourceFile="$(var.installer.TargetDir)$(var.installer.TargetName).CA.dll" />

<CustomAction Id="CheckingAppIsRunning" DllEntry="CheckRunningAppAction" Execute="immediate" Return="check" BinaryRef="CustomActions" />


<InstallExecuteSequence>
  <Custom Action="CheckingAppIsRunning" Before="LaunchConditions" />
</InstallExecuteSequence>

Issue: installation fails immediately, logs we see:

SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Comment by Yaswanth112** [comment]
We are also seeing same issue.
it was working fine, with wix version 4.0.4, but failing to install issue with version 4.0.5.

Here is how we defined CustomActions

<Binary Id="CustomActions" SourceFile="$(var.installer.TargetDir)$(var.installer.TargetName).CA.dll" />

<CustomAction Id="CheckingAppIsRunning" DllEntry="CheckRunningAppAction" Execute="immediate" Return="check" BinaryRef="CustomActions" />


<InstallExecuteSequence>
  <Custom Action="CheckingAppIsRunning" Before="LaunchConditions" />
</InstallExecuteSequence>

Issue: installation fails immediately, logs we see:

SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Comment by Yaswanth112** [comment]
We are also seeing same issue.
it was working fine, with wix version 4.0.4, but failing to install issue with version 4.0.5.

Here is how we defined CustomActions

<Binary Id="CustomActions" SourceFile="$(var.installer.TargetDir)$(var.installer.TargetName).CA.dll" />

<CustomAction Id="CheckingAppIsRunning" DllEntry="CheckRunningAppAction" Execute="immediate" Return="check" BinaryRef="CustomActions" />


<InstallExecuteSequence>
  <Custom Action="CheckingAppIsRunning" Before="LaunchConditions" />
</InstallExecuteSequence>

Issue: installation fails immediately, logs we see:

SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Comment by Yaswanth112** [comment]
We are also seeing same issue.
it was working fine, with wix version 4.0.4, but failing to install issue with version 4.0.5.

Here is how we defined CustomActions

`<Binary Id="CustomActions" SourceFile="$(var.installer.TargetDir)$(var.installer.TargetName).CA.dll" />`

`<CustomAction Id="CheckingAppIsRunning" DllEntry="CheckRunningAppAction" Execute="immediate" Return="check" BinaryRef="CustomActions" />`


```
<InstallExecuteSequence>
  <Custom Action="CheckingAppIsRunning" Before="LaunchConditions" />
</InstallExecuteSequence>
```

Issue: installation fails immediately, logs we see:

SFXCA: Failed to create temp directory. Error code 5
CustomAction CheckingAppIsRunning returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

**Comment by demienYu** [comment]
> Hi, I am facing the same issue. My custom action is defined like this
> 
> ```
> <CustomAction Id="SetInstallFolderFromResponseFileCA" BinaryRef="CustomActionsDLL" DllEntry="SetInstallFolderFromResponseFile" Execute="immediate" />
> <Custom Action="SetInstallFolderFromResponseFileCA" Before="CostFinalize" /> // in InstallExecuteSequence 
> ```
> 
> The issue seems to be, that the custom action server was moved from the temp folder to a system folder. Since immediate custom actions are to my knowledge always run as impersonated, they do not have the necessary elevated privileges.

I think you are pretty close.
I have been experiencing the same issue (same error) with my custom action. The only difference is my CA was impersonated. 
As I changed "Impersonate" property to "no" everything started to work just fine.
Wix and all extension versions = 4.0.5

**Comment by richard-frolkovic** [comment]
> Interesting. I have this test:
> 
> ```
> <Binary Id="ManagedCA" SourceFile="TestCA.CA.dll" />
> 
> <CustomAction Id="ImmediateCA" BinaryRef="ManagedCA" DllEntry="ImmediateCA"
>               Execute="immediate" Return="check" />
> 
> <InstallExecuteSequence>
>   <Custom Action="ImmediateCA" Before="CostFinalize" />
> </InstallExecuteSequence>
> ...
> ...
> I am on Windows 11 23H2, but this doesn't seem like something the Windows Installer would change.

I tested a completely new minimalistic solution and at first got the same result, however after some investigation found, that it was just, that the default vs project for CA used the Microsoft.Deployment.WindowsInstaller and not the wix tools nuget package. After changing that I got the bug again.

> > Hi, I am facing the same issue. My custom action is defined like this
> > ```
> >   
> > The issue seems to be, that the custom action server was moved from the temp folder to a system folder. Since immediate custom actions are to my knowledge always run as impersonated, they do not have the necessary elevated privileges.
> 
> I think you are pretty close. I have been experiencing the same issue (same error) with my custom action. The only difference is my CA was impersonated. As I changed "Impersonate" property to "no" everything started to work just fine. Wix and all extension versions = 4.0.5

Do you use immediate or deferred CA? Using impersonate=no on immediate actions doesn't change anything for me.

**Comment by demienYu** [comment]
I have deferred CA.

**Comment by juvo64** [comment]
Will the correction also be made for Wix 3.14.1?

**Comment by tve-altx** [comment]
> Will the correction also be made for Wix 3.14.1?

Also interested in the answer to this question

**Comment by CADbloke** [comment]
Workaround is to revert to 3.14.0 - https://github.com/wixtoolset/wix3/releases/tag/wix314rtm
Worked on my installation.

**Comment by tondrej** [comment]
> Workaround is to revert to 3.14.0 - https://github.com/wixtoolset/wix3/releases/tag/wix314rtm Worked on my installation.

Not really, as 3.14.0 contains the [vulnerability](https://github.com/wixtoolset/issues/security/advisories/GHSA-jx4p-m4wm-vvjg)

**Comment by CADbloke** [comment]
So there is no fix for Wix v3?

**Comment by birarroshan** [comment]
@robmen Any timelines for fix in Wix v3?

**Comment by robmen** [comment]
@birarroshan No.

**Comment by ian-g-holm-intel** [comment]
We've been using v4.0.5 with a custom bootstrapper that depends on Wixtoolset.Mba.Core. The problem is there is no version of Wixtoolset.Mba.Core v5.0.0. We can't downgrade to 4.0.4 because of the security upgrade and can't upgrade to 5.0.0. Is there no way this fix can be added to a new v4 release?

**Comment by robmen** [comment]
@ian-g-holm-intel I understand that would make your life much easier. However, we've spent more time this year fixing issues in the WiX Toolset for free than on anything else. That simply isn't sustainable. So, our focus now is to work for our paying customers for a while.

If you want guarantees and SLAs, [purchase a support contract](https://www.firegiant.com/services/support-programs/), and you will become one of those customers we work for.

**Comment by barnson** [comment]
> The problem is there is no version of Wixtoolset.Mba.Core v5.0.0. 

https://wixtoolset.org/docs/fivefour/oopbas/

**Comment by smaudet** [comment]
Just wanted to add a hint here for Wixsharp users - this does indeed affect Wix 4.0.5 but it seems that Wixtoolset.Dtf.CustomAction 5.0.0 can be safely installed alongside 4.0.5 to bypass/fix this issue.

**Comment by tyilo** [comment]
I had the same issue after updating WixTools from 3.14.0.8606 to 3.14.1.8722. Downgrading to 3.14.0.8606 fixed my the issue.

**Comment by robmen** [comment]
Because it's getting lost on this issue: Downgrading exposes you to potential security vulnerabilities.

WiX v5.0.x can be used without upgrading your .wixprojs so it is highly recommended to use that (or later) instead of downgrading.

**Comment by tyilo** [comment]
> Because it's getting lost on this issue: Downgrading exposes you to potential security vulnerabilities.
> 
> WiX v5.0.x can be used without upgrading your .wixprojs so it is highly recommended to use that (or later) instead of downgrading.

You can't just upgrade from WiX 3 to 5 without any changes to the project files. At least not for my projects. I just tried and this was one of the errors that I got:
```
The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\WiX\v3.x\Wix.CA.targets" was not found.
```

**Comment by smaudet** [comment]
@tyilo wix4 from wix3 is a significant change, but probably better (perhaps the maintainers can correct me) than trying wix3 to wix5.

If you upgraded to at least wix4, and upgrade the single package Wixtoolset.Dtf.CustomAction to 5.0.0, you should have the best of both worlds - minimal upgrade and minimal security exposure @robmen ?

**Comment by robmen** [comment]
In this case, the upgrade from from v3 to v4 is the same as v3 to v5. That is not always the situation. :)
