### ISSUE TITLE
Setting the "Scope" property to "perUser" results in an unexpected INSTALLFOLDER path

### ISSUE THREAD

**Issue by antoinebj** [wixtoolset/issues#8101]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

.NET 8.0 / VS 2022 17.9.5

### HeatWave Version

1.0.3

### Windows Version

Win11 23H2

### Repro Steps

- Set package scope to `perUser`
- Set `INSTALLFOLDER` to be under `ProgramFiles6432Folder`

### Actual Result

At runtime, `INSTALLFOLDER` is in `C:\Program Files`

### Expected Result

At runtime, `INSTALLFOLDER` is in `%LOCALAPPDATA%\Programs`

Note that if I set the scope to `perUserOrMachine`, the folder is as expected, but that makes the bundle configure itself to request elevated privileges

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by antoinebj** [comment]
Apparently this has been the behavior for a long time:
https://stackoverflow.com/questions/43981922/wix-installer-ignoring-my-peruser-install-scope-why

And the problem was already raised here:
https://github.com/wixtoolset/issues/issues/7617
But then converted to a discussion without explanation, and then apparently forgotten.

Using `perUserOrMachine` instead would be viable, if there was a `ForcePerUser` property on `MsiPackage` for the Burn bundle, or if the `InstallPrivileges` property was brought back to explicitly specify limited privilege requirements.

**Comment by antoinebj** [comment]
One potential workaround:
```xml
<SetProperty Id="INSTALLFOLDER" Value="[LocalAppDataFolder]Programs\!(bind.Property.ProductName)" Sequence="first" Before="FindRelatedProducts" />
```

However, I don't know if that plays well with various languages, "Programs" might vary from locale to locale, just like "Program Files" does.

In the end, I may have to resort to coding a custom action, using `SHGetKnownFolderPath` with `FOLDERID_UserProgramFiles`, which would be quite the defeat for such a simple scenario.

**Comment by robmen** [comment]
Note this fix addresses the (appropriate) surprise that `INSTALLFOLDER` didn't move to a per-user location for a per-user package. It does NOT address the underlying complexity of passing ICE validation in per-user MSIs nor the already open feature request for Burn to be more flexible with `perUserOrMachine` packages.
