### ISSUE TITLE
Overriding scheduling of FindRelatedProducts results in error WIX7009

### ISSUE THREAD

**Issue by avivanoff** [wixtoolset/issues#8115]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

MSBuild 17.9.8 and Visual Studio 2022 17.9.6

### HeatWave Version

1.0.3

### Windows Version

Windows 11 23H2

### Repro Steps

1. Create a basic installer project and add the following code:
```
<InstallExecuteSequence>
  <AppSearch After="FindRelatedProducts" />
  <FindRelatedProducts Before="LaunchConditions" />
  <RemoveExistingProducts After="InstallValidate" />
</InstallExecuteSequence>
```
2. Build with project.

### Actual Result

The build results in the error:
`error WIX7009: The action 'FindRelatedProducts' conflicts with a virtual symbol with the same id. To override the virtual symbol (e.g., to reschedule a custom action), use the 'override' access modifier: 'override FindRelatedProducts'. If you didn't intend to override a virtual symbol, use a different id to avoid the conflict.`

### Expected Result

No error.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by avivanoff** [comment]
Does v6.0.0-rc.1 milestone mean there will be no 5.0.x bug fix releases, or this bug is not planned to be included?

Sorry is I misunderstood the concept of v6.0.0-rc.1 milestone.

**Comment by avivanoff** [comment]
Any clarification on v6.0.0-rc.1 vs. 5.0.x?

**Comment by robmen** [comment]
As discussed in one of the recent WiX Online Meetings, patch builds are created for [customers](https://www.firegiant.com/services/support-programs/).

**Comment by porciusmaria** [comment]
I am facing the same problem while converting a project to WIX version 5 .....

**Comment by robmen** [comment]
@porciusmaria It is absolutely possible to get a fix out earlier. As mentioned in the WiX Online Meeting 281, the WiX Toolset is a customer-driven Open Source project. Dot releases are created to address issues hit by customers.

**Comment by orangedentalGit** [comment]
Hi there,
I just converted to Wix v5 (from v4) and I want you to let you that I'm facing this issue with the InstallServices element as well.
I hope there will be a fix very soon.

**Comment by wmanning** [comment]
@orangedentalGit  about your last comment robmen said fixes are only for customers (aka people who pay FireGiant).  
They also mentioned it here:
https://www.firegiant.com/blog/2024/4/16/wix-online-meeting-281-highlights/

> As we move into our new annual-release model, we need to also cut back on how many releases we support. So here's how it will work going forward:
>
  >  If you're a FireGiant customer, consult your support contract -- that determines your support, bug-fix, and security-fix lifecycle for all versions of WiX.
    If you're not a FireGiant customer, then:
        You should test WiX release candidates as soon as they're available. Bug reports we receive during the release candidate phase are likely to get fixed or at least documented. That happened several times during the WiX v5 release candidate phase.
        Bugs reported after a major version has been released are candidates for the next major version and only rarely in the just-shipped major version.
        Security fixes will be available for 10 months after the next major release, so given our annual release schedule, that means 22 months of security-fix support.
    Maintainers (:waving_hand_emoji:) may create patch releases to backport security fixes, customer bug fixes, and other bug fixes that, in their discretion, are high priority (important, embarrassing, annoying, the magic 8 ball said so, and so forth).

So might be possible for fix to come out.  But it's just as likely it won't come out until Wix 6.

**Comment by robmen** [comment]
@wmanning is correct, but I would change the last sentence to, "If you want guaranteed bug fixes in the WiX toolset, pay for support."

The fundamental truth is that the maintainers of the WiX toolset spent the bulk of this year tackling CVEs and finishing WiX v5. At some point, we need to do work for paying customers, or we aren't able to feed our families. That's what we're doing now.

I know most developers never consider the cost of maintaining an OSS project. Most think it is all free. I assure you there are costs for everything. So, if you are not a customer, then you have to wait until we volunteer more time to maintain the project or someone who is a customer has the same need that you do.

We are customer-driven.

**Comment by smacpherson-ces** [comment]
Happy to pay for this fix in v5 how much would it cost roughly?

**Comment by orangedentalGit** [comment]
Hey everyone, I in no way meant to imply that I don't appreciate your work. You guys are doing a great job! And of course I fully understand that you need financial compensation for all the work you do.  The main intention of my post was primarily to inform you that the problem described here also applies to the <InstallServices /> property.
Perhaps you can also understand that I didn't really expect such an essential feature (at least for us) to stop working after the update.
Having said that, I can agree with smacpherson-ces' question.

**Comment by Prakash08061993** [comment]
Any workaround for this issue?

**Comment by robmen** [comment]
@smacpherson-ces, at FireGiant, we build relationships with our customers to address their software installation needs. We have details about the support program and a form to send an inquiry at this link: https://www.firegiant.com/services/support-programs/

@orangedentalGit, I understood. I added my comment only to provide a little more detail that I thought was missing from @wmanning's comment. As for your expectations, if something is essential to you--and you choose to not pay for support--then you need to spend time to verify those essential things do not regress as we progress. As we've discussed in several WiX Online Meetings, we do work hard to fix regressions found during the -rc process. Unfortunately, this issue was found outside the -rc process. It also does not impact any customers. Therefore, it isn't a high priority. We're working on more important things for customers.

**Comment by pf-uvonceumer** [comment]
I had a similar issue with Wix4CloseApplications_X86 action. I finally gave up and reverted to 4.0.3. 😞

**Comment by NickeNor** [comment]
Upgraded to WiX 5.0.1 and InstallService still wont work, I guess this was supposed to fix it?
Do I need anything else apart from:

    <InstallExecuteSequence>
        
      <InstallServices Condition="NOT WIX_UPGRADE_DETECTED" />
        
      <DeleteServices Condition="NOT UPGRADINGPRODUCTCODE" />
    </InstallExecuteSequence>

This results in "error WIX7009: The action 'InstallServices' conflicts with a virtual symbol with the same id."
