### ISSUE TITLE
v5 VS Project Template

### ISSUE THREAD

**Issue by CoreTenet** [wixtoolset/issues#8141]
### User story

Is there a v5 project template?  I only find v3 and no documentation to direct me elsewhere...

### Proposal

Create a v5 project template

**Comment by barnson** [comment]
https://wixtoolset.org/docs/intro/#vs

**Comment by CoreTenet** [comment]
So, is the intent to create a v3 project and then upgrade it?  If so, I will move to another product...  Thanks!

**Comment by barnson** [comment]
No, the intent is to use the v5 templates.
