### ISSUE TITLE
Bal extension shows damaged with wix 5

### ISSUE THREAD

**Issue by metsma** [wixtoolset/issues#8155]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

8.0.204

### HeatWave Version

none

### Windows Version

Win11 23H2

### Repro Steps

1. Install wix `dotnet tool install wix --version 5.0.0 --global`
2. Info: `wix --version 5.0.0+41e11442`
3. Install Bal extension `wix extension add -g WixToolset.Bal.wixext`
4. List extension `wix extension list -g`

### Actual Result

`WixToolset.Bal.wixext 5.0.0 (damaged)`

### Expected Result

`WixToolset.Bal.wixext 5.0.0`

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
`WixToolset.Bal.wixext` is an alias. `WixToolset.BootstrapperApplications.wixext` is the new name and works as expected.

**Comment by metsma** [comment]
Maybe to mention this in here https://wixtoolset.org/docs/fivefour/#extension-changes.
And remove the Bal version if it does not work?
