### ISSUE TITLE
VSIX failed on VS 2022

### ISSUE THREAD

**Issue by FrodoHTX** [wixtoolset/issues#8157]
### WiX Version

4.0.4+a8592982

### .NET or MSBuild or Visual Studio Version

Microsoft Visual Studio Professional 2022 (64-bit) - LTSC 17.4; Version 17.4.13

### HeatWave Version

1.0.4 (installer FireGiant.HeatWave.Dev17.vsix)

### Windows Version

Win10 21H2

### Repro Steps

1. Download installer from FireGiant
2. Double click

### Actual Result

Install Failed

The install of 'HeatWave for VS2022' was not successful for all the selected products.

### Expected Result

Install succeeded
[dd_VSIXInstaller_20240424131909_4020.log](https://github.com/wixtoolset/issues/files/15098883/dd_VSIXInstaller_20240424131909_4020.log)

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by FrodoHTX** [comment]
@johncalls - Thank you for the guidance.  We are conservative in upgrading Visual Studio because the Intel Fortran compiler is sensitive to the versioning of the IDE.

**Comment by barnson** [comment]
HeatWave issues should go to https://github.com/firegiant/HeatWaveSupport/issues. In short, you need v17.8 or later.
