### ISSUE TITLE
Wix5: <Files> element @Include results in unexpected path when using relative paths

### ISSUE THREAD

**Issue by hypetsch** [wixtoolset/issues#8163]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

MSBuild version 17.9.8+b34f75857 for .NET Framework

### HeatWave Version

1.0.4.5

### Windows Version

Windows 10 22H2 (OS Build 19045.4291)

### Repro Steps

Due to the issue mentioned in discussion https://github.com/orgs/wixtoolset/discussions/8158 we switch to the new <Files> element and discovered the following behavior (Unexpected behavior is in point 4):

1. To determine which directory the <Files> element uses as its base when using it with relative paths we used the following markup:
`<Files Include="cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
This resulted in the following error which is perfectly fine as this path does not exist:
`error WIX8601: Missing directory for harvesting files: Could not find a part of the path 'D:\GIT\Tcs.Samweb2\installer\Tcs.Samcluster.Installer.Msi\Components\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'`
....the .wxs file with the `<Files>` element is located in `D:\GIT\Tcs.Samweb2\installer\Tcs.Samcluster.Installer.Msi\Components\`
So it seems paths are relative to the containing file.

2. To check if <Files> is capable of handling `../` we did this:
`<Files Include="../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
As expected, we still got an error but with a different path (one level up):
`error WIX8601: Missing directory for harvesting files: Could not find a part of the path 'D:\GIT\Tcs.Samweb2\installer\Tcs.Samcluster.Installer.Msi\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'`

3. Continuing with another `../` gives also the expected result:
`<Files Include="../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`error WIX8601: Missing directory for harvesting files: Could not find a part of the path 'D:\GIT\Tcs.Samweb2\installer\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'`

4. So with adding another `../` we would expect to get `D:\GIT\Tcs.Samweb2\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'` which would be the desired path. Sadly this does not work and results in the same path as the previous sample:
`<Files Include="../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`error WIX8601: Missing directory for harvesting files: Could not find a part of the path 'D:\GIT\Tcs.Samweb2\installer\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'`
Maybe noteworthy: `D:\GIT\Tcs.Samweb2\installer\` is the directory where the solution file is located.

5. adding another .`./` again results in the expected path
`<Files Include="../../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`error WIX8601: Missing directory for harvesting files: Could not find a part of the path 'D:\GIT\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'`

6. Adding even more `../` also results in expected paths - as we now reached the root path:
`<Files Include="../../../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`<Files Include="../../../../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`<Files Include="../../../../../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`<Files Include="../../../../../../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`<Files Include="../../../../../../../../../cluster-backend/NodeServices/Tcs.Samcluster.CqrsBroker/bin/Release/net8.0/win-x64/publish/**">`
`error WIX8601: Missing directory for harvesting files: Could not find a part of the path 'D:\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish'`

### Actual Result

Scenario described in point 4 results in a wrong path to harvest.

### Expected Result

For the scenario of point 4 the following path would be expected:
`D:\GIT\Tcs.Samweb2\cluster-backend\NodeServices\Tcs.Samcluster.CqrsBroker\bin\Release\net8.0\win-x64\publish`

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Works on my machine with different paths but same depth. Please provide a repo that reproduces the problem.

**Comment by hypetsch** [comment]
Tried to reproduce it today but couldn't manage to do so in the original repo as well as in a test file solution. I don't have any idea what went wrong the other day. Sorry for bothering you. Think you can close the issue.
