### ISSUE TITLE
Wix forum Category Improvement Request

### ISSUE THREAD

**Issue by Shanedymke** [wixtoolset/issues#8187]
### User story

As a role, I can accomplish task with proposal or benefit from proposal. I am utilizing the Wix forum app to unite the world behind crisis relief and prevention efforts.

I have been working on it for years so it isn't overwhelming to me, but I recently had a discussion with someone other than me that said she doesn't know where to begin because there are too many options to choose from. 

She requested sub categorizing to help her in her decision making. 

Then I started thinking about people who get overwhelmed when ordering food at a restaurant and it made sense.

Less is more at first and once they get more acquainted with the menu they explore it more.  

### Proposal

I am proposing what sems to be a fairly simple improvement to the categorization feature of the wix forum app.

Currently you can create a category and people can make posts related to that category but if you have a vast number of categories your forum becomes quite overwhelming for people.

I am proposing the addition of sub-categories to reduce the amount of initial overload that people get when they are first introduced to the forum. 

For example, instead of having to make several categories for air pollution, soil pollution, water pollution etc. I can make a category for environmental crises which will then have subcategories for relevant issues regarding the main category. 

Once the user clicks on a subcategory, they can then make posts like normal but an option to have no subcategories should be available.

I believe this will help reduce preliminary load times for the forum page as well as provide a better user experience for forum members.

I currently have 39 categories in my crisis relief and prevention forum @ pozzirecycles.org/forum.

I would like to reduce that down to at least a dozen.

### Considerations

I don't think there are any negatives associated with this proposed feature improvement other than developers having to take the time to code it into the app. 

I don't know anything about code designing but it seems as though this feature improvement would only bring positives.

**Comment by barnson** [comment]
Wrong place. This repo is for WiX Toolset.

**Comment by Shanedymke** [comment]
I reposted it in the correct place but how do I follow the progress of it?
Thank you for your help

**Comment by barnson** [comment]
You probably want somewhere on wix.com, which has nothing to do with the WiX Toolset.
