### ISSUE TITLE
Regression of RemoveFolderEx in WiX v4

### ISSUE THREAD

**Issue by johncalls** [wixtoolset/issues#8199]
### WiX Version

4.*

### .NET or MSBuild or Visual Studio Version

MSBuild version 17.8

### HeatWave Version

1.0.4

### Windows Version

Win 10

### Repro Repo

https://github.com/johncalls/removefolderex-regression-demo

### Repro Steps

1. Checkout branch `wix4` of the provided repo and build it to generate the installer
2. Create a folder in `C:\rmfex-regression-demo` with some files and/or subfolders in it
3. Run the install
4. Run the uninstall

NOTE: The example is provided for WiX v5 but this is reproducible for any WiX version since 4.0.0.

### Actual Result

The folder `C:\rmfex-regression-demo` is not removed as part of the uninstall.

### Expected Result

The folder `C:\rmfex-regression-demo` is removed as part of the uninstall.

---

In addition to the failing example, I provided the equivalent working example for WiX v3 in branch `wix3`. I've also provided a workaround to make RemoveFolderEx work as expected in Wix v4/v5 in branch `wix4-workaroud`. Please note, that the workaround is not limited to the use of `RemoveFolder`, for example, placing a `File` element in there would work, too.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Works as expected as long as `RemoveFiles` is scheduled (like when installing a file).

**Comment by barnson** [comment]
There is some inaccurate logging when the directory doesn't exist that should be fixed but it doesn't affect functionality.
