### ISSUE TITLE
Page Not Found: The Discussions page and all the useful history in there is 404 :'( 

### ISSUE THREAD

**Issue by rainbow180** [wixtoolset/issues#8525]
### WiX Toolset Page URL

https://github.com/orgs/wixtoolset/discussions

### Page URL that linked to WiX Toolset

https://github.com/wixtoolset

### Additional information (optional)

The WiX repo's GitHub Discussions page and all the useful history in there is not responding.

**Comment by robmen** [comment]
> I disabled the WiX Toolset GitHub Discussions to stop a spam attack. I've reported the issue to GitHub. After they delete the ~750 spam messages, I'll re-enable Discussions.

https://robmensching.com/blog/posts/2024/05/19/wix-toolset-github-discussions-disabled-due-to-spam-attack/

**Comment by robmen** [comment]
The Discussions forum has been cleaned up by GitHub and is now back online.
