### ISSUE TITLE
The WixVariable 'overridable' attribute appears to be ignored (Bundle / WixLib)

### ISSUE THREAD

**Issue by WalkerNA** [wixtoolset/issues#8528]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

Visual Studio 2022 (17.9.7)

### HeatWave Version

1.0.4

### Windows Version

Win11 22H2

### Repro Repo

https://github.com/WalkerNA/Wix5_WixVariable_Overridable_Test

### Repro Steps

1. Create a simple WiX 5.0.0 WixLib project.
2. Within this WixLib project, create a `<WixVariable />` element marked as overridable, e.g., `<WixVariable Id="TestWixVariable" Value="1" Overridable="true"/>`
4. Create a simple WiX 5.0.0 Bundle.
5. Within the new Bundle, include the new `*.wixlib` artifact after compiling the the project from step 1.
6. Within the new Bundle, include an override value for the WixLib's WixVariable, e.g., `<WixVariable Id="TestWixVariable" Value="0"/>`
7. Compile the new Bundle project.

![image](https://github.com/wixtoolset/issues/assets/35239937/e52b0efc-3c5c-4ac3-ab4b-2bca59284156)

### Actual Result

Received the following two errors:

1. WIX0091 - Duplicate WixVariable with identifier 'TestWixVariable' found. Access modifiers (global, library, file, section) cannot prevent these conflicts. Ensure all your identifiers of a given type (Directory, File, etc.) are unique.
2. WIX0092 - Location of symbol related to previous error.

### Expected Result

Compiling the Bundle project would be successful.  

The <WixVariable/> defined in the Bundle would successfully override the value originally defined within the WixLib (which is configured as "Overridable").

This was the behavior in WiX 3.  It is also the behavior as described in the WiX 5 documentation: https://wixtoolset.org/docs/schema/wxs/wixvariable/

![image](https://github.com/wixtoolset/issues/assets/35239937/3e376653-0e47-4b22-9766-87228463ab01)

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by robmen** [comment]
The fix (in WiX v6) is to treat the `Overridable` attribute as virtual correctly. The _overriding_ WixVariable still has to declare it does so explicitly. Thus, the code for the second definition would need to change to this: `<WixVariable Id="override TestWixVariable" Value="0"/>`. Fortunately, the error messages will lead you down that path correctly now.
