### ISSUE TITLE
Project name with Space not working in Bundle

### ISSUE THREAD

**Issue by Prakash08061993** [wixtoolset/issues#8530]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

MsBuild Version 17.8.3

### HeatWave Version

1.0.2.1

### Windows Version

Win 11

### Repro Steps

```
<MsiPackage SourceFile="$(TestProject With Server Components.TargetPath)" />
Or
<MsiPackage SourceFile="$(var.TestProject With Server Components.TargetPath)" />
In <Bundle><Chain></Chain></Bundle>
```

### Actual Result

Undefined preprocessor variable '$(TestProject With Server Components.TargetPath)'
Or
Undefined preprocessor variable '$(var.TestProject With Server Components.TargetPath)'

### Expected Result

Should not get any error.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by dcm99** [comment]
Hi,
I think this is intended behaviour because you cannot use whitespaces in a variable.
Simply replace the whitespaces in your variable name with underscores. Then you can use a project name containing whitespaces.

**Comment by Prakash08061993** [comment]
> Hi, I think this is intended behaviour because you cannot use whitespaces in a variable. Simply replace the whitespaces in your variable name with underscores. Then you can use a project name containing whitespaces.

Thank you so much for replying. It worked.

Could you please have a look at my other issues as well?
[https://github.com/wixtoolset/issues/issues/8540](url)
[https://github.com/wixtoolset/issues/issues/8539](url)
