### ISSUE TITLE
Could not run another process with elevated access after the Install Finalize action 

### ISSUE THREAD

**Issue by bhuvana-01m** [wixtoolset/issues#8534]
### WiX Version

3.11

### .NET or MSBuild or Visual Studio Version

Visual Studion 17.0 (2022)

### HeatWave Version

WiX Toolset Visual Studio Extension version 1.0.0.22

### Windows Version

Windows 10

### Repro Steps

During Silent Mode: 
Added a Custom Action(SilentLaunchSecApp) with deferred execute before InstallFinalize  
Action SilentLaunchSecApp will try to launch the process(another msi) in silent mode 
Error : Another Installation is in progress. You must complete that installation before continuing this one.

To overcome this Error , 
Added the custom action with immediate execute after InstallFinalize and this is not allowing the process to run in elevated mode.
While executing in silent mode , the UAC prompt is not allowed to trigger hence its will try to run the process and exited with error says "Ensure that the process running the MSI installer has sufficient permissions"

### Actual Result

SilentLaunchSecApp should install in silent as it completed the primary install

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by wmanning** [comment]
Are you sure the first install (which I assume is an MSI) is finished?  I think there is an option to run custom action without waiting for it to be done so maybe that would work, not sure.

**Comment by bhuvana-01m** [comment]
Yes by immediate Action works after Install Finalize . But need to execute the process with elevated access after the install Finalize.

**Comment by wmanning** [comment]
Only one MSI at a time can execute.  So I think this a discussion rather than an issue.

**Comment by bhuvana-01m** [comment]
Then how can we trigger the another MSI with elevated access to run silent after the primary installation finished?

**Comment by wmanning** [comment]
One option is a bundle: https://wixtoolset.org/docs/v3/bundle/

**Comment by bhuvana-01m** [comment]
This is something which creates an Exe to launch multiple MSI right? But need to trigger the MSI from one MSI.
