### ISSUE TITLE
Not able to set Custom icon on top left corner of installer

### ISSUE THREAD

**Issue by Prakash08061993** [wixtoolset/issues#8540]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

MsBuild Version 17.8.3

### HeatWave Version

1.0.2.1

### Windows Version

Win 11

### Repro Steps

I have one project and Bundle.wxs under that. The code of that is below.
```
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs" xmlns:bal="http://wixtoolset.org/schemas/v4/wxs/bal">

    <Bundle Name="Test Client" Version="$(var.WixVersion)" IconSourceFile="Images\TestIcon.ico" Manufacturer="Test" UpgradeCode="{GUID}">

        <BootstrapperApplication >

            <bal:WixStandardBootstrapperApplication LicenseUrl="" Theme="hyperlinkLicense" ThemeFile="Resources\HyperlinkTheme.xml" LocalizationFile="Resources\HyperlinkTheme.wxl" LogoFile="Images\left_banner.bmp"/>
        </BootstrapperApplication>
       
        <Chain>

            <MsiPackage bal:DisplayInternalUICondition="0" SourceFile="..\..\..\..\Application\Install\TestApp.msi">
                
            </MsiPackage>

            <MsiPackage bal:DisplayInternalUICondition="0" SourceFile="..\Test\App\Test.msi">
               
            </MsiPackage>

            <MsiPackage SourceFile="$(var.Test_App_Components.TargetPath)" />

        </Chain>

    </Bundle>

</Wix>
```

### Actual Result

Custom Icon on the top left corner is not getting reflected.
![image](https://github.com/wixtoolset/issues/assets/140159833/5e8a7df6-6b3a-449d-b94d-d3faf9b27921)

### Expected Result

Custom Icon should be visible.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by campersau** [comment]
See https://github.com/wixtoolset/issues/issues/8104#issuecomment-2074635376 for a workaround.

**Comment by Prakash08061993** [comment]
> See [#8104 (comment)](https://github.com/wixtoolset/issues/issues/8104#issuecomment-2074635376) for a workaround.

Thank you so much. It worked.
