### ISSUE TITLE
Calling to the InstallHinfSection SETUPAPI function makes bundle installer to run second install instance.

### ISSUE THREAD

**Issue by rukhov** [wixtoolset/issues#8567]
### WiX Version

4.0.4

### .NET or MSBuild or Visual Studio Version

.NET 8.0.300

### HeatWave Version

-

### Windows Version

Win11 23H2

### Repro Repo

https://github.com/rukhov/WiX-install-driver-issue

### Repro Steps

1. build the installer with command build.cmd
2. copy bundle installer swapBuffers-driver-bundle.exe to the machine where Test Signed drivers loading is enabled. See https://learn.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option
3. Double click the bundle installer swapBuffers-driver-bundle.exe.
4. Follow the installer's instructions to install the driver.

### Actual Result

When the installer's finish screen is appear or several seconds later the second instance of installer is started.

### Expected Result

There is not any additional installer instance appeared to user.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Please attach the resulting bundle logs. It's probably related to https://github.com/wixtoolset/issues/issues?q=runonce.

**Comment by rukhov** [comment]
@barnson 
Bundle logs: [logs.zip](https://github.com/user-attachments/files/15842170/logs.zip)

**Comment by barnson** [comment]
Were any other log files generated in %TEMP%? I'm not seeing a bundle invocation.

**Comment by barnson** [comment]
If you can provide additional detail, please attach it here and we'll re-open the issue.
