### ISSUE TITLE
Investigate the use of human-readable strings to generate upgrade code

### ISSUE THREAD

**Issue by barnson** [wixtoolset/issues#8584]
### User story

For some reason, not everyone loves GUIDs. WiX has spent many years fighting them. One remains: The upgrade code. What if we generated a stable GUID from a human-readable string? 

### Proposal

The `UpgradeCode` in MSIs and Bundles is a GUID that defines a group of packages/bundles where newer versions remove old versions. It turns out defining a lineage of versions is essentially the same role "package identifiers" provide in other technologies. So, what if the `UpgradeCode` was generated from a human friendly Package/Bundle Id attribute, like so:

 ```xml
<Package Id="Example.TestPackage" Name="My Package" Manufacturer="Example" Version="1">
```

The same would work for a Bundle element. Providing an Id attribute would make the `UpgradeCode` attribute optional. The `UpgradeCode` could still be specified for backwards compatiblity. For example,

```xml
<Bundle Id="Example.MyBundle" Name="My Bundle" Manufacturer="Example" Version="1" UpgradeCode="{...}">
```

Additionally, today each build of a Bundle gets a unique identifier called the "bundle id". It cannot be set by the user. As a result, this bundle id serves a similar role to both the `ProductCode` and `PackageCode` in MSI packages. To reduce confusion with the introduction of the Id attribute on the Bundle element, naturally the "Bundle Id", we should rename the generated identifier in the bundle to "bundle code" and update the Burn codebase. 

### Considerations

* We'll restrict the Package and Bundle elements' Id attribute to standard MSI identifier limiations, starts with letter and contains only alphanumeric, dots and underscore characters. This is not strictly necessary but these limitations are similar to those encouraged by other installation technologies.
 

_Additional Background_

The Windows Installer uses GUIDs to identify any concept that must be globally unique such as `ProductCode`, `UpgradeCode` and `ComponentId`. While this is a logical design decision (after all "globally unqiue" are the `G` and `U` in GUID), GUIDs are not human friendly. Most other installation technologies use a simple string and leave it up to the developer to make those strings globally unique when necessary. It turns out developers are pretty good at making globally unique strings (often prefixed with their company name or personal brand) so the human friendliness of a simple string outweighs the uniquess guarantees of GUIDs. (Note: with humans involved, GUIDs aren't actually guaranteed to be globally unique as developers often fallback to cut'n'paste when dealing with less than human friendly content).

---
~#### Proposal (for historical context)~

~We generate stable component GUIDs using the right set of inputs based on type of keypath. We could do the same thing for upgrade code and provide guidance for creating a well-formed human-readable "upgrade id." Two ideas:~

- ~A URI-like (scheme-less) string: `wixtoolset.org/products/wixadditionaltools`~
- ~A Java-like package id: `org.wixtoolset.products.wixadditionaltools`~

~It's an arbitrary string, so we could have advanced guidance for, e.g., side-by-side scenarios.~

~#### Considerations~

- ~Could be used anywhere (e.g., Upgrade/UpgradeVersion) or restricted to the package.~
- ~Could (probably) generate the GUID at bind-time, if we wanted to support loc strings. Not sure that's an interesting scenario; if it isn't, we should block bind-time variables.~

**Comment by bevanweiss** [comment]
I assume this would just be mapping the setup author string => MD5 hash or such (i.e. 128bit GUID equivalent)
Given in MD5/GUID form there is nothing special about the original string anymore, does it need any guidance beyond "This string should be unique"?

It could perhaps be 'in-place' i.e. where the current Upgrade Id requires a GUID, maybe the 'enhanced version' could accept either:
- GUID (Id="361E0C54-1F76-4B85-BD1B-0609EF570D4E"), default, backwards compatible..
- String (Id="string:This is the identifier that I would like to use for the Upgrade Id, it will just be replaced with the MD5 of this string", and then it will be as though I actually used the GUID "a777276d-93ad-a624-90c8-1496012f7160")

**Comment by jamescaldwell** [comment]
I could take on this task. The logic I would use would be to allow the regular call to GetAttributeGuidValue prodeed under the UpgradeCode case. If it fails, then make a hash using md5 and then convert back to a string.  This could be applied to every Guid parsing, or just to UpgradeCode.

**Comment by barnson** [comment]
If triage accepts this, it will need a WIP/design. For example, it can't use MD5 and I'd argue against overloading the existing UpgradeCode attribute.

**Comment by barnson** [comment]
Investigate whether other packaging technologies (e.g., Msix) have a concept of "product family" that we could use to come up with a name better than `UpgradeId`. @robmen is noodling on the concept of this idea as a "package identity" in more general terms. Assigning to him for the moment.

**Comment by barnson** [comment]
AUMIDs are another scheme: https://learn.microsoft.com/en-us/windows/win32/shell/appids

**Comment by bevanweiss** [comment]
> If triage accepts this, it will need a WIP/design. For example, it can't use MD5 and I'd argue against overloading the existing UpgradeCode attribute.

I've just seen the last WiX online.  What's the reason for the anti-MD5 in this context?
It's the most standard 128bit hashing algorithm.  And this is certainly not a cryptographic application, so the reversibility vulnerability isn't really a factor.

**Comment by barnson** [comment]
MD5 fails when FIPS is enabled.

**Comment by bevanweiss** [comment]
> MD5 fails when FIPS is enabled.

Ahh, so it's not anti-MD5, just can't use the CLR Cryptography MD5 implementation in FIPS environments.  And I guess when people deploy FIPS mode they push it to development machines as well... I wouldn't be surprised if that caused issues with Visual Studio usage also.. I guess VS has had the time to move away from MD5 for various hashing to GUID length things.

Does modern .NET Core still do similar?

> .NET Core:
> - Passes cryptographic primitives calls through to the standard modules the underlying operating system provides.
> - Does not enforce the use of FIPS Approved algorithms or key sizes in .NET Core apps.

https://learn.microsoft.com/en-us/dotnet/standard/security/fips-compliance
It looks like it does not.  So it's only really about .NET FW versioning (which I guess is still a majority support target for the development environment as well).
 
xxHash128 has been something that I've used before for cache management.
It looks like it's even so popular that it's made it's way into the .NET MS libraries
https://learn.microsoft.com/en-us/dotnet/api/system.io.hashing.xxhash128

**Comment by barnson** [comment]
WiX has `Uuid.NewUuid` to handle GUID creation for components.
