### ISSUE TITLE
Wix V4: ProjectName, TargetName, ProjectDir and TargetDir variables are not working in prebuild and postbuild events

### ISSUE THREAD

**Issue by leviyakir** [wixtoolset/issues#8595]
### WiX Version

4.0.5

### .NET or MSBuild or Visual Studio Version

Visual Studio 17.10.3

### HeatWave Version

1.0.4

### Windows Version

Win11 23H2

### Repro Steps

In a Wix4 project add a prebuild / postbuild event under the nodes PreBuildEvent or PostBuildEvent and use any of the following variables:
ProjectName
TargetName
ProjectDir
TargetDir
Note: SolutionDir does work

### Actual Result

Value of those vars is "" (empty string)

### Expected Result

The correct value according to VS macros

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
SDK-style projects require extra work. See the tip at https://wixtoolset.org/docs/tools/msbuild/.
