### ISSUE TITLE
WiX 5 auto-harvest (Files) creates two equal directories in the msi file

### ISSUE THREAD

**Issue by petm2022** [wixtoolset/issues#8608]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

VS 2022 17.10.3

### HeatWave Version

1.0.4

### Windows Version

Win10 22H2

### Repro Steps

1. Create a simple WiX 5 msi project with a ComponentGroup like this: 
```
    <ComponentGroup Id="Media">
      <Files Directory="INSTALLFOLDER" Subdirectory="Media" Include="..\..\Media\**" />
    </ComponentGroup>

```
3. In the Media folder create a folder 'z' with one file and two folders (z1 and z2) and one file in both z1 and z2.
4. Build and inspect the msi file with Orca.

### Actual Result

In the Directory table you see two entries for the folder 'z'. One used as parent for z1 and z2 the other one should not be there.
![image](https://github.com/wixtoolset/issues/assets/106153294/25cb3ca9-b766-4766-8dc0-022fda962d68)

When installing the msi file everything looks fine and there are no errors in the log file.
I would like to know if this is a problem or if it is ok to use it in my production code.

### Expected Result

Only one entry for the 'z' folder.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/7861 is the underlying cause.
