### ISSUE TITLE
Files element requires the "Keep empty directories" attribute.

### ISSUE THREAD

**Issue by toshiyukiohshima** [wixtoolset/issues#8619]
### User story

[As a setup developer]
When harvesting directories using the Files element, if an empty folder exists within it, an additional implementation is required to create that folder. Alternatively, I need to directly process the MSI file generated by WiX. In such cases, it is easier to implement using heat.exe with -ke option, but heat.exe is deprecated.

### Proposal

Files element requires the "Keep empty directories" attribute.

### Considerations

Anyone may want to add the ability to set attributes on the hidden components generated by the Files element.

**Comment by barnson** [comment]
`Files` is not going to support every possible scenario. This is one such; it's not commonly required.
