### ISSUE TITLE
Produce a wix-cli.msi

### ISSUE THREAD

**Issue by robmen** [wixtoolset/issues#8623]
### User story

* As a setup developer, I am accustomed to using WiX in major CI/CD systems (like GitHub Actions and Azure Pipelines) without needing to install it.

### Proposal

CI/CD systems start their VMs with a build image containing popular developer tools. Today, most of those images include WiX v3. WiX v4+ provided new acquisition models using `dotnet tool install` or MSBuild Sdk-style support. Both of those options download tooling from nuget.org. This works in almost all cases, but some users may still like to have a version of the WiX Toolset that is always available in the CI/CD image.

Therefore, we will produce a per-machine `wix-cli.msi` that contains WiX's command-line tools. CI/CD providers can then easily include that MSI in their image. The `wix-cli.msi` will install major versions side-by-side to allow CI/CD images to contain multiple versions in case of breaking changes. This means that `wix.exe` cannot be added to the PATH and instead will need to be referenced using an environment variable like `WIX#` where the `#` is replaced by the major version of the WiX Toolset. For example:

```bat
C:\> %WIX5%wix.exe build
```

The wix-cli.exe will install the following:

* `wix.exe` - obviously, the replacement for `candle.exe` and `light.exe`
* `heat.exe` - it is deprecated (use `Files` element instead) but will be included for compatibility purposes until wider deprecation notice can go out (WiX v6?)
* WiX Standard Extensions - all the standard WiX Extensions available from the per-machine location

### Considerations

* Technically, it would be possible to use `dotnet tool install` to include a version of WiX in the CI/CD image, only one version of the WiX Toolset would be supported. It's much easier if the `wix-cli.msi` installs WiX versions side-by-side.
* This `wix-cli.msi` needs to be introduced in the WiX v5 timeframe because WiX v6 will not be available until after WiX v3.14 is deprecated. There will NOT be a WiX v4 based wix-cli.msi

**Comment by barnson** [comment]
Will it be a per-machine install?

**Comment by bevanweiss** [comment]
For the bike-shedding, I feel that `%WIX#_DIR%` might be a bit more 'descriptive' for it being the actual WIX# directory path.
`WIX#` to me feels like a true(1)/false(0) indication that WIX version # is available.

It would also be nice if there were a way to just have a `WIX_DIR` which would reference the 'highest' installed WiX version.
In this way build scripts etc don't necessarily need to change with a new version of WiX being in use.

**Comment by robmen** [comment]
1. WiX v3 set the `WIX` variable so this follows in that precedent but with SxS.
2. Since there are breaking changes across major versions, there isn't much value in setting a variable to the highest version. Pick the one you want and use it.

**Comment by js69** [comment]
Not seeing it. Where is wix-cli.msi available for download?

**Comment by bevanweiss** [comment]
> Not seeing it. Where is wix-cli.msi available for download?

You could look in the artifacts from the build.
But you're probably better off waiting for an official versioned release.

**Comment by js69** [comment]
Looked some more, it is at https://github.com/wixtoolset/wix/releases
