### ISSUE TITLE
Build Error [NuGet security analysis]: Package 'System.Text.Json' 4.6.0 has a known high severity vulnerability error when attempting to build from fresh git clone

### ISSUE THREAD

**Issue by bevanweiss** [wixtoolset/issues#8626]
### WiX Version

5.0

### .NET or MSBuild or Visual Studio Version

.NET 8.0.300, Visual Studio Version 17.11.0 Preview 2.0

### HeatWave Version

N/A

### Windows Version

Win11 23H2

### Repro Steps

1. Download wix Toolset repository
2. Perform build using .\devbuild.cmd
3. Error will be reported based on NuGet security analysis around System.Text.Json

### Actual Result

The NuGet analysis stopped the build from completing successfully.

```
...wix\src\setup\MetadataTask\MetadataTask.csproj : error NU1903: Package 'System.Text.Json' 4.6.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

Build failed with 1 error(s) in 1.4s
```

### Expected Result

The build to complete, but with a warning reported about the NuGet security analysis.

I think we could potentially use:
<WarningsNotAsErrors>NU1901;NU1902;NU1903</WarningsNotAsErrors>
to remove all but Critical vulnerabilities from aborting builds, whilst still receiving warnings for them.

This leaves out NU1904 (Critical), which would still raise an error.
I think producing a build with a Critical vulnerability is probably not advisable (at least without doing something explicit to achieve..)

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by robmen** [comment]
I think we should just fix them, so this would be a duplicate of #8569.

**Comment by bevanweiss** [comment]
> I think we should just fix them, so this would be a duplicate of #8569.

Agree that updating the referenced package version is 'the solution' to this one instance.
But that doesn't resolve the potential build breaks for future NuGet security analysis warnings (which is more what I was trying to get at with this issue).  I anticipate these NuGet security analysis warnings will only increase in frequency, each one breaking the build (and hence breaking automated CI checks due to something unrelated to actual PR activity) seems undesirable.
Which is why I was suggesting marking the low, medium and high severity 'warnings' as not-escalating to errors.  Only criticals would break the build in that situation, and ideally these would be 'patched' swiftly (so the build wouldn't be down for long).

**Comment by robmen** [comment]
Understood. I think we should wait to see if that hypothetical comes to fruition. Until it does, updating our dependencies for the next release is both a direct and correct solution.

**Comment by robmen** [comment]
I never reproduced this issue, but it _should_ be resolved with the fix for #8569, right?

**Comment by bevanweiss** [comment]
A rebased build I did yesterday worked, so yep, I think this instance is fixed by #8569

**Comment by bevanweiss** [comment]
There's a number of new vulnerabilities which prevent recent Visual Studio releases from successfully completing the .\devbuild command.

This is with Visual Studio 2022 latest preview.
Baseline Visual Studio 2022 (non preview) does not yet have Nuget Vulnerability auditing enabled.

```
...\wix\src\libs\test\WixToolsetTest.Versioning\WixToolsetTest.Versioning.csproj : error NU1903: Package 'System.Net.Http' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-7jgj-8wvc-jh57
...\wix\src\libs\test\WixToolsetTest.Versioning\WixToolsetTest.Versioning.csproj : error NU1903: Package 'System.Text.RegularExpressions' 4.3.0 has a known high severity vulnerability, https://github.com/advisories/GHSA-cmhx-cq75-c4mj

Build failed with 2 error(s) in 2.3s
```

**Comment by robmen** [comment]
We should not be re-opening this issue every time there is a new transitive security vulnerability. I've added transitive auditing in wixtoolset/wix#581 to catch this more proactively, rather than dealing with Visual Studio previews which we do not generally support as a development environment for WiX.
