### ISSUE TITLE
Package with MSMQ custom action fails to install

### ISSUE THREAD

**Issue by djohnst10** [wixtoolset/issues#8628]
### WiX Version

5.0.0

### .NET or MSBuild or Visual Studio Version

.NET 9.0.100-preview.5.24307.3

### HeatWave Version

1.0.4.5

### Windows Version

Win 11 23H2

### Repro Steps

1. We have upgraded a WiX 3 project to WiX 5. We have made minimal changes to the installer project from what we used in Ensync 3.11.
2. The current version of our installer is the first one created with WiX 5.
3. The setup uses the WixToolset.Msmq extension and configures an MSMQ message queue during setup.
```
      <Component Bitness="always32">
        <File Id="JobService.exe" Name="JobService.exe" KeyPath="yes" />
        <ServiceInstall Name="JobService" DisplayName="Job Service" Description="Background job service" Start="auto" Type="ownProcess" ErrorControl="normal" Account="NT AUTHORITY\NETWORKSERVICE">
          <ServiceConfig DelayedAutoStart="yes" OnInstall="yes" OnReinstall="yes" PreShutdownDelay="30000" />
        </ServiceInstall>
        <ServiceControl Id="JobServiceControl" Name="JobService" Stop="both" Remove="uninstall" />
        <msmq:MessageQueue Id="JobsQueue" PathName=".\private$\hangfire-default" Label="HangFire Jobs Queue" Transactional="yes">
          <msmq:MessageQueuePermission Id="JobsQueue_Permission_Everyone" Group="Everyone" GetQueueProperties="yes" GetQueuePermissions="yes" WriteMessage="yes" />
          <msmq:MessageQueuePermission Id="JobsQueue_Permission_AnonymousLogon" Group="AnonymousLogon" WriteMessage="yes" />
          <msmq:MessageQueuePermission Id="JobsQueue_Permission_NetworkService" User="NetworkService" ReceiveMessage="yes" WriteMessage="yes" />
        </msmq:MessageQueue>
      </Component>
```

4. The installer compiles the MSI successfully.

### Actual Result

1. When installing the program without a previous version installed, everything installs successfully. I do not have a log for that install.
2. When installing the program as a major upgrade to the previous version build with WiX 3.11, the install fails.
```
MSI (s) (B0:14) [11:42:03:124]: Doing action: Wix4MessageQueuingInstall_X64
Action 11:42:03: Wix4MessageQueuingInstall_X64. 
Action start 11:42:03: Wix4MessageQueuingInstall_X64.
MSI (s) (B0:14) [11:42:03:140]: Creating MSIHANDLE (4018) of type 790542 for thread 7444
MSI (s) (B0:18) [11:42:03:156]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI837E.tmp, Entrypoint: MessageQueuingInstall
MSI (s) (B0!58) [11:42:03:171]: Creating MSIHANDLE (4019) of type 790541 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Creating MSIHANDLE (4020) of type 790540 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Creating MSIHANDLE (4021) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Creating MSIHANDLE (4022) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Closing MSIHANDLE (4022) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Creating MSIHANDLE (4023) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Closing MSIHANDLE (4023) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Closing MSIHANDLE (4021) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:202]: Closing MSIHANDLE (4020) of type 790540 for thread 9048
MSI (s) (B0!58) [11:42:03:218]: PROPERTY CHANGE: Adding MessageQueuingRollbackInstall property. Its value is '01JobsQueue-2147483648-2147483648HangFire Jobs Queue.\private$\hangfire-default-2147483648-21474836484'.
MSI (s) (B0!58) [11:42:03:218]: Doing action: MessageQueuingRollbackInstall
Action 11:42:03: MessageQueuingRollbackInstall. 
Action start 11:42:03: MessageQueuingRollbackInstall.
Action ended 11:42:03: MessageQueuingRollbackInstall. Return value 0.
MSI (s) (B0!58) [11:42:03:218]: Creating MSIHANDLE (4024) of type 790531 for thread 9048
MessageQueuingInstall:  Error 0x8007065a: Failed MsiDoAction on deferred action
MSI (s) (B0!58) [11:42:03:218]: Closing MSIHANDLE (4024) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:218]: Creating MSIHANDLE (4025) of type 790531 for thread 9048
MessageQueuingInstall:  Error 0x8007065a: Failed to schedule MessageQueuingRollbackInstall
MSI (s) (B0!58) [11:42:03:218]: Closing MSIHANDLE (4025) of type 790531 for thread 9048
MSI (s) (B0!58) [11:42:03:234]: Closing MSIHANDLE (4019) of type 790541 for thread 9048
CustomAction Wix4MessageQueuingInstall_X64 returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (B0:18) [11:42:03:234]: Closing MSIHANDLE (4018) of type 790542 for thread 7444
Action ended 11:42:03: Wix4MessageQueuingInstall_X64. Return value 3.
MSI (s) (B0:14) [11:42:03:234]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (B0:14) [11:42:03:249]: User policy value 'DisableRollback' is 0
MSI (s) (B0:14) [11:42:03:249]: Machine policy value 'DisableRollback' is 0
MSI (s) (B0:14) [11:42:03:249]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (B0:14) [11:42:03:249]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (B0:14) [11:42:03:249]: No System Restore sequence number for this installation.
MSI (s) (B0:14) [11:42:03:249]: Unlocking Server
Action ended 11:42:03: INSTALL. Return value 3.
```
3. When trying to uninstall the WiX 5 version of our installer that was installed without a previous version installed, the uninstall fails.
```
MSI (s) (50:6C) [12:42:39:007]: Doing action: Wix4MessageQueuingUninstall_X64
Action ended 12:42:39: Wix4ConfigureComPlusUninstall_X64. Return value 1.
MSI (s) (50:6C) [12:42:39:007]: Creating MSIHANDLE (4) of type 790542 for thread 10860
MSI (s) (50:DC) [12:42:39:007]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIE8D5.tmp, Entrypoint: MessageQueuingUninstall
MSI (s) (50!E8) [12:42:39:017]: Creating MSIHANDLE (5) of type 790541 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Creating MSIHANDLE (6) of type 790540 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Creating MSIHANDLE (7) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Creating MSIHANDLE (8) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Closing MSIHANDLE (8) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Creating MSIHANDLE (9) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Closing MSIHANDLE (9) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Closing MSIHANDLE (7) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: Closing MSIHANDLE (6) of type 790540 for thread 56040
MSI (s) (50!E8) [12:42:39:017]: PROPERTY CHANGE: Adding MessageQueuingRollbackUninstall property. Its value is '1JobsQueue-2147483648-2147483648HangFire Jobs Queue.\private$\hangfire-default-2147483648-214748364840'.
MSI (s) (50!E8) [12:42:39:017]: Doing action: MessageQueuingRollbackUninstall
Action start 12:42:39: Wix4MessageQueuingUninstall_X64.
Action start 12:42:39: MessageQueuingRollbackUninstall.
MSI (s) (50!E8) [12:42:39:032]: Creating MSIHANDLE (10) of type 790531 for thread 56040
Action ended 12:42:39: MessageQueuingRollbackUninstall. Return value 0.
MSI (s) (50!E8) [12:42:39:032]: Closing MSIHANDLE (10) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:032]: Creating MSIHANDLE (11) of type 790531 for thread 56040
MessageQueuingUninstall:  Error 0x8007065a: Failed MsiDoAction on deferred action
MSI (s) (50!E8) [12:42:39:032]: Closing MSIHANDLE (11) of type 790531 for thread 56040
MSI (s) (50!E8) [12:42:39:032]: Closing MSIHANDLE (5) of type 790541 for thread 56040
MessageQueuingUninstall:  Error 0x8007065a: Failed to schedule MessageQueuingRollbackUninstall
MSI (s) (50:DC) [12:42:39:032]: Closing MSIHANDLE (4) of type 790542 for thread 10860
CustomAction Wix4MessageQueuingUninstall_X64 returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
MSI (s) (50:6C) [12:42:39:032]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (50:6C) [12:42:39:032]: Machine policy value 'DisableRollback' is 0
MSI (s) (50:6C) [12:42:39:032]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
Action ended 12:42:39: Wix4MessageQueuingUninstall_X64. Return value 3.
MSI (s) (50:6C) [12:42:39:032]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Installer\Rollback\Scripts 3: 2 
MSI (s) (50:6C) [12:42:39:032]: No System Restore sequence number for this installation.
MSI (s) (50:6C) [12:42:39:032]: Unlocking Server
Action ended 12:42:39: INSTALL. Return value 3.
```

### Expected Result

Installing and uninstalling an installation package that configures an MSMQ message queue should just work.

Looking at the logs I noticed that the Wix4MessageQueuingInstall_X64 custom action seems to schedule another custom action MessageQueuingRollbackInstall. Missing are the Wix4 prefix and the _X64 suffix. When I look in the CustomAction table in the MSI, I don't see MessageQueuingRollbackInstall but I do see Wix4MessageQueuingRollbackInstall_X64. The uninstall log is very similar but with Wix4MessageQueuingUninstall_X64 and MessageQueuingRollbackUninstall.

Is this as simple as being that the wrong name for the rollback custom action was used in the code executed by the Wix4MessageQueuingInstall_X64 custom action? I think it is.

Here is code in the MessageQueuingInstall function of the MSMQ Custom action DLL that schedules the MessageQueuingRollbackInstall  custom action.

```
        hr = WcaDoDeferredAction(L"MessageQueuingRollbackInstall", pwzRollbackActionData, 0);
        ExitOnFailure(hr, "Failed to schedule MessageQueuingRollbackInstall");
```

The message "Failed to schedule MessageQueuingRollbackInstall" is actually seen in the log file:
```
MessageQueuingInstall:  Error 0x8007065a: Failed to schedule MessageQueuingRollbackInstall
```

Other places where WcaDoDeferredAction is executed in the MSMQ custom action code look the same but if you look at other custom action code you will mostly see something similar to this:

```
        hr = WcaDoDeferredAction(CUSTOM_ACTION_DECORATION(L"RollbackServiceConfig"), pwzScriptKey, cServices * COST_SERVICECONFIG);
        ExitOnFailure(hr, "failed to schedule RollbackServiceConfig action");
```

Where CUSTOM_ACTION_DECORATION adds the prefix and suffix to it's string parameter.

I also noticed the `WixToolSet.Converters.WixConverter` class where the `CustomActionIdsWithPlatformSuffix` property is a map from unprefixed and unsuffixed custom action ids to the prefixed and suffixed versions.
```
            { "MessageQueuingUninstall", "Wix4MessageQueuingUninstall_<PlatformSuffix>" },
            { "MessageQueuingInstall", "Wix4_MessageQueuingInstall<PlatformSuffix>" },
```
There is no mapping for MessageQueuingExecuteInstall, MessageQueuingRollbackInstall, MessageQueuingExecuteUninstall, and MessageQueuingRollbackUninstall. Should there be? 

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by bevanweiss** [comment]
I suspect that you're probably spot on in this situation.

I think what would be absolutely ideal in this situation is:

1. An Integration test which includes the absolute minimal reproducible for the current failure to install/uninstall, similar to others located here:
https://github.com/wixtoolset/wix/tree/main/src/test/msi

2.  The changes.  The custom action references do seem the issue within the C++, it would need checking of the names in the MSI itself, but I suspect these four references should gain the `CUSTOM_ACTION_DECORATION` wrapper
![image](https://github.com/user-attachments/assets/bdf988b9-7460-4dcd-a783-d4aef9e547d3)

3. Creation of compiler tests.. I think this part is a bit less important here, since I think you're right that it's just the CA code at fault currently
https://github.com/wixtoolset/wix/tree/main/src/ext/Util/test/WixToolsetTest.Util

If you have the absolute bare bones wxs for MSMQ, including details of pre-reqs required (for just the msmq install function) then I'm happy to do the rest.

**Comment by djohnst10** [comment]
I will see if I can create a repo for this issue this weekend.

**Comment by djohnst10** [comment]
I have created a minimal WiX 5 project that demonstrates the bug.

https://github.com/djohnst10/SimpleMsmqInstall

**Comment by djohnst10** [comment]
> ### Actual Result
> 1. When installing the program without a previous version installed, everything installs successfully. I do not have a log for that install.

The reason the first install of the program without a previous version installed work was because I already had the same MSMQ message queue set up. From reading the MSMQ extension's custom action code I see that nothing is scheduled for rollback or execution if all message queues to be created already present on the system.

**Comment by GuruBmt210** [comment]
Hi @bevanweiss / @robmen , can you please give information on which WiX version this fix is available? I currently faced this same issue in the WiX version 5.0.2. I couldn't find release notes list with fixed bugs for this version, that's why checking here.

**Comment by robmen** [comment]
WiX v6

**Comment by GuruBmt210** [comment]
> WiX v6

@robmen , Thanks for the quick reply. If I am right, v6 is going to be released after the 1st quarter of this year, correct?
Is there a possibility for this issue fix to be available in an earlier bug fix version?

**Comment by bevanweiss** [comment]
> > WiX v6
> 
> @robmen , Thanks for the quick reply. If I am right, v6 is going to be released after the 1st quarter of this year, correct? Is there a possibility for this issue fix to be available in an earlier bug fix version?

I don't think there's significant merit in having it in a 'bug fix version' within the v5 series.  It has been dormant since v4... so a fix for it doesn't seem 'urgent'.  It's also not a security issue.

If you were paying for support from FireGiant, then it could probably get some higher priority (Rob etc are the people to privately discuss such options with).. but otherwise I think it's just a change that fits into the v6 release cadance most appropriately.


The code is also freely available, so you can download it and build such an MSMQ supporting version yourself..

**Comment by GuruBmt210** [comment]
@bevanweiss - Ok, thank you for the information.

**Comment by robmen** [comment]
To be crystal clear, as per the [WiX Toolset Lifecycle](https://wixtoolset.org/docs/about/#lifecycle) minor versions are only created for FireGiant customers and security vulnerabilities in supported versions.

**Comment by MBroholmA** [comment]
I also ran into this. However there is another bug with regard to message queue permissions. 
The 2 SQL permission queries at the top of mqqueuesched.cpp are missing the 'Wix4' prefix for the Component_ column so it never reads any permissions and will always leave the queue with default Administrator permissions. 
It doesn't complain about this error as far as I could see. 

Shall I make a new issue or can this one be reopened?

Br Martin

**Comment by bevanweiss** [comment]
> I also ran into this. However there is another bug with regard to message queue permissions. The 2 SQL permission queries at the top of mqqueuesched.cpp are missing the 'Wix4' prefix for the Component_ column so it never reads any permissions and will always leave the queue with default Administrator permissions. It doesn't complain about this error as far as I could see.
> 
> Shall I make a new issue or can this one be reopened?
> 
> Br Martin

Since not having correct permissions is a different issue, then I'd suggest creating a new issue for it.
Ideally with a linked PR that shows the issue in an E2E Test.  Then you could either implement the fix also, or someone else can implement the fix.

The key reason for the E2E Test is so that this kind of issue doesn't sneak back into the code base.
