### ISSUE TITLE
RemoveFoldersEx doesn't force add RemoveFiles Standard Action to MSI to allow it to work

### ISSUE THREAD

**Issue by bevanweiss** [wixtoolset/issues#8672]
### WiX Version

5.0.1

### .NET or MSBuild or Visual Studio Version

.NET 8.0.300, Visual Studio Version 17.11.0 Preview 2.0

### HeatWave Version

N/A

### Windows Version

Win11 24H2

### Repro Steps

With authoring as below, say this is just an MSI to delete some files...

```xml
<Package Name="RemoveFolderExTest" Version="1.0.0" Manufacturer="Example Corporation" UpgradeCode="{B724D799-6288-471B-80FE-91F4E651E33F}">
  <SetProperty Id="REMOVEFOLDEREXTESTDIR" Value="\\?\[CommonAppDataFolder]RemoveFolderExTest" Sequence="execute" Before="Wix4RemoveFoldersEx_X86" />
        
  <Component Id="RemoveFolderTestComponent" Guid="{2BFD07F8-6154-4BBF-B5A1-AEB31E9CBC60}">
    <util:RemoveFolderEx Id ="RemoveAllTheFolders" On="both" Property="REMOVEFOLDEREXTESTDIR" />
  </Component>
</Package>
```

It ends up without RemoveFiles in the Execute Sequence, which then results in no files being removed when executed.
![image](https://github.com/user-attachments/assets/19a9a29b-4b6c-4d25-8a42-bd73c8a7fa21)

### Actual Result

No files were removed, RemoveFiles not shown in the logs.

### Expected Result

Expected RemoveFiles to be scheduled before RemoveFolders, even if no files or other items were authored in the MSI.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/8199 and https://github.com/wixtoolset/issues/issues/8632
