### ISSUE TITLE
Temp directory issue after wix v3.14.1.8722 upgrade

### ISSUE THREAD

**Issue by jj39** [wixtoolset/issues#8687]
### WiX Version

3.14.1.8722

### .NET or MSBuild or Visual Studio Version

latest

### HeatWave Version

latest

### Windows Version

Win11 23H2

### Repro Steps

This is the same as issue https://github.com/wixtoolset/issues/issues/8078 but that issue was only fixed for v4.x and not for v3.x

Many people can't upgrade from a v3.x project to a v4.x or v5.x project for various reasons. The most recent version of WixToolset v3 that does not have this issue is v3.14.0.8606 but that version does not have the fix to the security vulnerability that was fixed in v3.14.1.8722. 

It would be nice to get a new release of v3.x that fixes this issue.

The error in v3.14.1.8722 is:
SFXCA: Failed to create temp directory. Error code 5
CustomAction XYZ returned actual error code 1603

### Actual Result

SFXCA: Failed to create temp directory. Error code 5
CustomAction XYZ returned actual error code 1603

### Expected Result

No error

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
You can easily upgrade just your custom action projects without upgrading your MSI package projects. There are no plans for another v3.x release.
