### ISSUE TITLE
heat.exe ignores "-directoryid" parameter when harvesting a dir

### ISSUE THREAD

**Issue by madmaxoft** [wixtoolset/issues#8732]
### WiX Version

5.0.1+2f00cbe680fb01ab485d56f16de9cd19b133f875

### .NET or MSBuild or Visual Studio Version

.NET 8.0.4

### HeatWave Version

N/A

### Windows Version

Win10 22H2

### Repro Steps

1. Run `heat.exe dir ... -directoryid INSTALLDIR` (add the required parameters to harvest a real directory)

### Actual Result

The output uses `TARGETDIR` instead of `INSTALLDIR` as the directory ID.

### Expected Result

The output uses `INSTALLDIR` as the directory ID.

I've found out that for the standalone heat.exe, the commandline switch is `-dr` instead of `-directoryid` (as per \src\tools\heat\UtilHeatExtension.cs)

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
What's telling you to use `-directoryid`?

**Comment by madmaxoft** [comment]
I'm running the `heat.exe` tool "manually" from my CMakeLists.txt to generate a setup for a rather complicated app. There are several directories that need heat-harvesting, with several different IDs required.

**Comment by barnson** [comment]
They're both listed in `-?` and do different things:

```
   -directoryid  overridden directory id for generated directory elements
   -dr <DirectoryName>  directory reference to root directories (cannot contain spaces e.g. -dr MyAppDirRef)
```

**Comment by madmaxoft** [comment]
Right, I completely missed that. Though the description is so vague that I really thought what I needed was `-directoryid`. 
Sorry for the blunder.

**Comment by barnson** [comment]
Only so much doc you can squeeze into <80 characters. `-directoryId` is for MSBuild project harvesting.
