### ISSUE TITLE
Wix 5 WixStandardBootstrapperApplication Reopens After Install/Uninstall Completes

### ISSUE THREAD

**Issue by Bondarenko1990** [wixtoolset/issues#8754]
### WiX Version

5.0.1

### .NET or MSBuild or Visual Studio Version

.NET 8.0

### HeatWave Version

1.0.4.5

### Windows Version

23H2

### Repro Steps

I use Wix 5 WixStandardBootstrapperApplication. In the Bundle I added my WPF application to the chain
```
<Chain>
    <MsiPackage Id="Setup" SourceFile="$(var.MyProject.Setup.TargetPath)"  Compressed="yes" />
</Chain>
```
and I added a custom action in which I install the ImDisk bat file.

```
string installCmd = $"/silent /lang:english /installfolder:\"C:\\Program Files\\ImDisk\" > install.log 2>&1";
var startInfo = new ProcessStartInfo(".....\\ImDisk\\install.bat", installCmd );

startInfo.UseShellExecute = false;
startInfo.CreateNoWindow = true;

var proc = new Process();

proc.StartInfo = startInfo;
proc.Start();
proc.BeginOutputReadLine();
proc.BeginErrorReadLine();
proc.WaitForExit();
```

### Actual Result

And after the installation is complete, a new copy of the installer opens for some reason.

![image](https://github.com/user-attachments/assets/2027fd8e-80f5-4458-9e24-463570d95308)

If I remove silent install ImDisk from CustomAction everything is fine.

Tell me what I'm doing wrong. Why does the installer reopen after the installation is complete? What's interesting is that there is no such problem in Wix 3 WixStandardBootstrapperApplication.

### Expected Result

I expect after installation/uninstallation is complete not to show the installer again

![image](https://github.com/user-attachments/assets/8360464d-cf5f-43a6-b027-8c9793c7d316)

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
https://github.com/wixtoolset/issues/issues/6589

**Comment by glaure** [comment]
I have the same issue with a bundle where a MSI has custom actions for driver installation and deinstallation.
