### ISSUE TITLE
Is this a bug or an easter egg? Documentation link pointing to a youtube video

### ISSUE THREAD

**Issue by henkehedstrom** [wixtoolset/issues#8759]
### WiX Toolset Page URL

https://wixtoolset.org/schemas/v4/wxs/

### Additional information (optional)

I found a comment in a project I am working with that referenced https://wixtoolset.org/schemas/v4/wxs/util. This seems to be an older link and should now be https://wixtoolset.org/docs/schema/util/. This is not a problem.

However, the weird part was that if you remove the **/util** part so you get the link https://wixtoolset.org/schemas/v4/wxs you get a link that instead of showing "Page not found" redirects you to this youtube video: https://www.youtube.com/watch?v=8-r-V0uK4u0

Is this intended? Maybe an easter egg? It got me quite confused haha.

**Comment by wmanning** [comment]
Schemas are not URLs.  So in my opinion it's just trying to highlight that.  This was mentioned before: https://github.com/wixtoolset/issues/issues/8167.  It is intentional.

Related: https://github.com/wixtoolset/issues/issues/8681

**Comment by barnson** [comment]
It's an all-in-one easter egg, social experiment, and dessert topping.
