### ISSUE TITLE
Prevent Installer from Recommending Closure of Critical System Program (Windows Explorer)

### ISSUE THREAD

**Issue by galinareznikk** [wixtoolset/issues#8797]
### WiX Version

3.14.1

### .NET or MSBuild or Visual Studio Version

0.0.0

### HeatWave Version

0.0.0

### Windows Version

Windows 10

### Repro Steps

1) Start the installation process using a WiX-based installer.
2) Open a file explorer window that accesses the folder or files involved in the installation.
3) Proceed with the installation until the point where the installer detects that Windows Explorer is holding the files.
4) The installer displays a message suggesting that the user close Windows Explorer to continue with the installation.
5) Accept the prompt to close Windows Explorer.

### Actual Result

When the user opts to close Windows Explorer, the system becomes unstable or crashes, as Windows Explorer is a crucial system component.

### Expected Result

- Rather than suggesting the closure of Windows Explorer, the installer should identify the specific file handles that Explorer is holding and notify the user to close any open windows related to the installation folder.
- The installer should provide a retry mechanism, allowing the user to manually release those handles by closing relevant file explorer windows, without terminating Explorer itself.
- This change would improve system stability and prevent accidental crashes, leading to a better user experience.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by robmen** [comment]
Closing explorer.exe should not make a user's system unstable, but you'll need to file this issue with Microsoft, as all of the above is Windows behavior (explorer.exe and MSI).
