### ISSUE TITLE
Page Not Found: http://wixtoolset.org/schemas/v4/wxs

### ISSUE THREAD

**Issue by ijuedt** [wixtoolset/issues#8804]
### WiX Toolset Page URL

http://wixtoolset.org/schemas/v4/wxs

### Page URL that linked to WiX Toolset

From *.wxs file

### Additional information (optional)

Leads to "Smashing Pumpkins" youtube site: https://www.youtube.com/watch?v=8-r-V0uK4u0
Redirects on my PC and on that of colleague. Have you been hacked?

**Comment by wmanning** [comment]
Ha. No.

https://github.com/wixtoolset/issues/issues/7714
https://github.com/wixtoolset/issues/issues/7964
https://github.com/wixtoolset/issues/issues/8167
https://github.com/wixtoolset/issues/issues/8759

FYI not one of the devs but this comes up too much.

**Comment by ijuedt** [comment]
Thanks for the clarification! :-) So this is by intention, but I hold (hello devs) that the way this intention is expressed is not the best way to educate as intended. How about a web page that explicitly just states that: "URIs are not URLs, so do not expect something to be seen here." Or redirect to an appropriate help page.

**Comment by robmen** [comment]
We don't do any of those things because it is (as called out in 8759) a long-running social experiment. The experiment will come to a close soon.
