### ISSUE TITLE
Page Not Found: /docs/about/license/

### ISSUE THREAD

**Issue by briantolsen** [wixtoolset/issues#8812]
### WiX Toolset Page URL

https://wixtoolset.org/docs/about/license/

### Page URL that linked to WiX Toolset

https://marketplace.visualstudio.com/items/FireGiant.FireGiantHeatWaveDev17/license

### Additional information (optional)

Looks like this link is dead.

**Comment by barnson** [comment]
Nope, still broken. I tried.
