### ISSUE TITLE
Bootstrapper Localizations not appearing when uninstalling from Add or Remove Programs

### ISSUE THREAD

**Issue by haightt** [wixtoolset/issues#8838]
### WiX Version

5.0.2

### .NET or MSBuild or Visual Studio Version

Visual Studio Professional 2022 (64-bit) 17.11.6

### HeatWave Version

1.0.4.5

### Windows Version

Win11 21H2

### Repro Repo

https://github.com/haightt/WixLocalizationExample

### Repro Steps

1. Build the solution
2. Set the system display language to either French (Canada) or Spanish (Mexico)
3. Sign out of  the user
4. Sign in to the user
5. Verify Windows UI is in the desired language
6. Install the bootstrapper (WixLocalizationExample.Bootstrapper.exe) (Translations appear in the bootstrapper UI)
7. Open Add or Remove Programs 
8. Uninstall WixLocalizationExample

### Actual Result

The bootstrapper UI remains in English when you uninstall the program from either the Control Panel or Apps & Features in the Settings app. This occurs despite the display language being set to one of the two supported languages.

### Expected Result

I expected to see the bootstrapper UI match the machine's system language. I should see the Spanish translations in the UI if the system language is Spanish. I should see the French translations in the UI when set to French.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Works as expected on Windows 11 23H2.

**Comment by haightt** [comment]
@barnson So, is there something wrong with my implementation? Is it something with the version of Windows that I am running?

**Comment by haightt** [comment]
This appears to be occurring due to something with the IT settings on our machines. It works correctly in a VM and other Windows installations.
