### ISSUE TITLE
Download link points to documentation instead of downloads

### ISSUE THREAD

**Issue by Frank-Schmitt** [wixtoolset/issues#8849]
### WiX Toolset Page URL

https://wixtoolset.org/

### Additional information (optional)

I'd like to download Wix, but the download button links to https://wixtoolset.org/docs/intro/ which is the same link as the one on the left labeled Documentation. I can't find a link to a download page.

**Comment by robmen** [comment]
There are three ways to get the WiX toolset. That page lists them all.

**Comment by Frank-Schmitt** [comment]
Very confusing. I had assumed there is a link to an msi installer somewhere (in fact I found it manually on gitlab). So why do you have two separate links anyway if they both go to the same target.
