### ISSUE TITLE
void IBootstrapperEngine.Log(LogLevel level, string wzMessage) throws System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by EvgenPervenenko** [wixtoolset/issues#8856]
### WiX Version

5.0.1

### .NET or MSBuild or Visual Studio Version

.NET Framework 4.8.9290.0

### HeatWave Version

1.0.4.5

### Windows Version

 Windows 10.0.19045

### Repro Steps

There is no steps, on our crashlytics we see

```
void IBootstrapperEngine.Log(LogLevel level, string wzMessage)
In App

Assembly:
WixToolset.BootstrapperApplicationApi

void Engine.Log(LogLevel level, string message)
In App

CustomBA.cs in void CustomBA.TrackDebug(string message) at line 47
In App

MainWindowModel.cs in void MainWindowModel.OnMainWindowClosing(object sender, CancelEventArgs e) at line 152
In App

MainWindow.xaml.cs in void MainWindow.OnMainWindowClosing(object sender, CancelEventArgs e) at line 42
In App

Called from: void Window.OnClosing(CancelEventArgs e)
```

### Actual Result

An undocumented and unhandled exception was thrown from IBootstrapperEngine.Log

### Expected Result

IBootstrapperEngine.Log handle internal exceptions or document it

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
While it's possible there are bugs lurking in the WiX helper code for managed BAs, interop exceptions like these really need a debugger to figure out what's going on so there's not much we can do here without more information, or, better yet, a live repro.
