### ISSUE TITLE
BootstrapperApplicationRun method throws System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by EvgenPervenenko** [wixtoolset/issues#8857]
### WiX Version

5.0.2

### .NET or MSBuild or Visual Studio Version

.NET Framework 4.8.4420.0

### HeatWave Version

1.0.4.5

### Windows Version

 Windows 10

### Repro Steps

There is no steps only have stacktrace from crashlytics

```
void MbaNative.BootstrapperApplicationRun(IBootstrapperApplication pBA)
In App

Assembly:
WixToolset.BootstrapperApplicationApi

Main.cs in int Program.Main() at line 53
```

### Actual Result

The BootstrapperApplicationRun method throws a System.Runtime.InteropServices.COMException with the message: "This operation returned because the timeout period expired. (Exception from HRESULT: 0x800705B4)". As a result, the bootstrapper application is unable to install the application.

### Expected Result

No Exception Thrown: BootstrapperApplicationRun executes without throwing any exceptions.
Successful Installation: The bootstrapper application completes the installation process successfully.
Completion Time: The operation completes within the expected timeframe without any timeouts.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
While it's possible there are bugs lurking in the WiX helper code for managed BAs, interop exceptions like these really need a debugger to figure out what's going on so there's not much we can do here without more information, or, better yet, a live repro.
