### ISSUE TITLE
Migrating a wixproj from v3 to v4 causes invalid MSI file when using harvesting.

### ISSUE THREAD

**Issue by NiceLuc** [wixtoolset/issues#8858]
### WiX Version

5.0.2

### .NET or MSBuild or Visual Studio Version

.NET 4.8

### HeatWave Version

1.0.4

### Windows Version

Win11 23H2

### Repro Repo

https://github.com/NiceLuc/WixMigrationBug

### Repro Steps

1. Open a WiX 3 project in Visual Studio
2. Build the project and run the installer. (success)
3. Using the HeatWave extension, right click on the file and choose "Upgrade to WiX 4..."
4. Rebuild the project (**error**)

### Actual Result

When building the project, I saw the following error:

> The identifier 'WixComponentGroup:Product.Generated' could not be found. Ensure you have typed the reference correctly and that all the necessary inputs are provided to the linker.

### Expected Result

I would have expected that the tool did the necessary things when `EnableProjectHarvesting` is set to true. This will ensure that I can migrate my project to WiX 4 and it will build.

* Add a `<PackageReference Include="WixToolset.Heat" Version="{{latest version}}" />` in my wixproj file.
* Remove the `<ComponentGroupRef Id="Product.Generated" />` from my `Product.wxs` file.
* Replaced with multiple `<ComponentGroupRef />` elements according to my project references.

For example, it should have replaced my `<Feature />` node with the following nodes:

```xml
<!-- <ComponentGroupRef Id="Product.Generated" /> -->

<ComponentGroupRef Id="ClassLibrary1.Binaries" />
<ComponentGroupRef Id="ClassLibrary1.Content" />
<ComponentGroupRef Id="ClassLibrary1.Satellites" />

<ComponentGroupRef Id="ConsoleApp1.Binaries" />
<ComponentGroupRef Id="ConsoleApp1.Content" />
<ComponentGroupRef Id="ConsoleApp1.Satellites" />
```

### Acknowledgements

- [x] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
HeatWave handles the .wixproj conversion: https://github.com/firegiant/HeatWaveSupport/issues It might not handle the old Heat project harvesting, due to its general unreliability.
