### ISSUE TITLE
Performance of generating installer between Wix5 and Wix3

### ISSUE THREAD

**Issue by fforjan** [wixtoolset/issues#8859]
### WiX Version

5.0.2

### .NET or MSBuild or Visual Studio Version

MSBuild version 17.10.4+10fbfbf2e for .NET Framework

### HeatWave Version

<not used on build machine>

### Windows Version

Windows 2019 Server

### Repro Repo

<company private>

### Repro Steps

There is a different when building the installer for our product between using WIX3 and WIX5.
The installer is 'referencing' 80 projects and generating a 360Mb msi.

From the log on the build machine when building with WIX3 (before our migration) (summary for clarity)
```
2024-12-04T02:36:12.0948629Z Compile:
2024-12-04T02:36:12.1117224Z   D:\BldSrc\2\s\Source\NextGenSim\packages\wix.3.14.0\build\..\tools\candle.exe 
2024-12-04T02:36:15.0994215Z Link:
2024-12-04T02:36:15.0997170Z   D:\BldSrc\2\s\Source\NextGenSim\packages\wix.3.14.0\build\..\tools\Light.exe 
2024-12-04T02:40:42.6874100Z SignMsi:
2024-12-04T02:40:50.8568563Z PostBuildEvent:
2024-12-04T02:40:51.2166848Z Done Building Project "wixproj" (default targets).
```
so roughly 5 minutes.

Now with WIX5
```
2024-12-03T14:39:07.2266467Z CoreCompile:
2024-12-03T14:39:07.2581406Z   C:\Users\build\.nuget\packages\wixtoolset.sdk\5.0.2\tools\net472\x86\wix.exe build 
2024-12-03T14:47:21.1850499Z WindowsInstallerValidation:
2024-12-03T14:47:21.1851506Z   C:\Users\build\.nuget\packages\wixtoolset.sdk\5.0.2\tools\net472\x86\wix.exe msi validate 
2024-12-03T14:47:30.7184132Z SignMsi:
2024-12-03T14:47:36.2791070Z PostBuild:
2024-12-03T14:47:37.1560662Z Done Building Project "wixproj" (default targets).
```
Which is close to 9 minutes !

is this an expectation ? is there any option we could turn on to reduce the build time ? Any pattern to avoid ?

### Actual Result

Build time for WIX5 is close to be double the build time with WIX3 

### Expected Result

Build time should be roughtly the same

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
This needs way more data. How many files? How many directories? Embedded or external cabs? How many cabs? Identical compression level? This is why we ask for a repro.

**Comment by fforjan** [comment]
@barnson  thanks for the input, I would have love to give you a reproduction case but unfortunately the project is not open source so it will be difficult.

First, do you know a tool to extract statistic about the MSI so that I can give you some info ?

Nevertheless, let me try to answer by searching the project in wix3 format:
- embedded 1 cab:
![image](https://github.com/user-attachments/assets/c291682d-9c82-465a-9c19-249639aa12a3)
- How many files? 
![image](https://github.com/user-attachments/assets/1173784d-4b11-4068-88f1-43e59519348d)
- How many directories?
![image](https://github.com/user-attachments/assets/ad2f769d-ffea-4690-a8d7-5bca4ef2c324)

Building locally seems slow also, not only on the build machine, i'm happy to gather more log on my workstation if  there is a way for me to generate and review those.

**Comment by barnson** [comment]
Set `CompressionLevel` explicitly. You're getting different defaults.

**Comment by barnson** [comment]
We're assuming that's the cause. Let us know if not.

**Comment by fforjan** [comment]
@barnson  sorry I miss the previous notification and was busy, I've set the CompressionLevel as mszip as it was in Wix3 and will check the result (should be before the end of week)

**Comment by fforjan** [comment]
@barnson Confirmed, by switching back to mszip compression level, the project build CoreCompile is reduce from 6 minutes to just under 3 minutes.
