### ISSUE TITLE
MSI installer created with 3.14.1.8722, was working with Wix version 3.11

### ISSUE THREAD

**Issue by pelnarp** [wixtoolset/issues#8867]
### WiX Version

3.14.1.8722

### .NET or MSBuild or Visual Studio Version

.NET 4.8

### HeatWave Version

No version

### Windows Version

Win11 23H2

### Repro Steps

We (a customer) have a custom installer that installs our WPF application, windows service, Scheduled task. Medium size desktop app, installer has some custom actions.

Worked fine until we used version WiX Toolset v3.11.2

After downloaded latest version, 3.14.1 the installer created with this version of Wix creates MSI file which fails during installation.

I logged the installation with msiexec. Apparently the custom action is not able to access a temp directory.

When there is no error (previous Wix version) the log states this (much more, but this is different):
MSI (s) (10:FC) [13:51:26:954]: Hello, I'm your 32bit Impersonated custom action server.
SFXCA: Extracting custom action to temporary directory: C:\Users\petruser\AppData\Local\Temp\MSI7F9D.tmp-\
SFXCA: Binding to CLR version v4.0.30319

This is part of the log from the unsuccessful installation which does fail:

MSI (s) (10:FC) [13:49:52:768]: Running as a service.
MSI (s) (10:FC) [13:49:52:772]: Hello, I'm your 32bit Impersonated custom action server.
SFXCA: Failed to create temp directory. Error code 5
CustomAction PrepareInstallationParameters returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

Something changes between the versions. I can workaround by downgrading to the version 3.11.2

### Actual Result

MSI installation fails with new version of Wix

### Expected Result

Installation to succeed

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Duplicate: https://github.com/wixtoolset/issues/issues/8687

**Comment by robmen** [comment]
Note: As a customer you should contact support at firegiant.com. They will be able to help you there as per your support contract.
