### ISSUE TITLE
error WIX0200: unhandled extension element 'WixStandardBootstrapperApplication' when building with VS2022 17.13.0 Preview 2.0

### ISSUE THREAD

**Issue by vbaderks** [wixtoolset/issues#8870]
### WiX Version

5.0.2

### .NET or MSBuild or Visual Studio Version

MSBuild version 17.13.0-preview-24568-05+37fc8280d for .NET Framework

### HeatWave Version

1.0.4.5

### Windows Version

Win11 24H2

### Repro Repo

https://github.com/team-charls/netpbm-wic-codec

### Repro Steps

1. git clone https://github.com/team-charls/netpbm-wic-codec
2. Open a Visual Studio 2022 17.13 Preview 2.0 Developer prompt
3. cd netpbm-wc-codec
4. execute msbuild -t:build -p:Configuration=Release -p:Platform=x64

### Actual Result

  ```
C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\Bundle.wxs(23): error WIX0200: The BootstrapperApplication element contains an unhandled exten
sion element 'WixStandardBootstrapperApplication'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/bal' namespa
ce has been provided. [C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\bootstrapper.wixproj]
  C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\Bundle.wxs(22): error WIX0044: The BootstrapperApplication element's Name or SourceFile attrib
ute was not found; one of these is required. [C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\bootstrapper.wixproj]
  C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\Bundle.wxs(31): error WIX0200: The Bundle element contains an unhandled extension element 'Reg
istrySearch'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/util' namespace has been provided. [C:\Users\Vict
or\repos\netpbm-wic-codec\setup\bootstrapper\bootstrapper.wixproj]
  C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\Bundle.wxs(40): error WIX0200: The Bundle element contains an unhandled extension element 'Pro
ductSearch'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/util' namespace has been provided. [C:\Users\Victo
r\repos\netpbm-wic-codec\setup\bootstrapper\bootstrapper.wixproj]
  C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\Bundle.wxs(48): error WIX0200: The Bundle element contains an unhandled extension element 'Pro
ductSearch'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/util' namespace has been provided. [C:\Users\Victo
r\repos\netpbm-wic-codec\setup\bootstrapper\bootstrapper.wixproj]
  C:\Users\Victor\repos\netpbm-wic-codec\setup\bootstrapper\Bundle.wxs(57): error WIX0200: The Bundle element contains an unhandled extension element 'Pro
ductSearch'. Please ensure that the extension for elements in the 'http://wixtoolset.org/schemas/v4/wxs/util' namespace has been provided. [C:\Users\Victo
r\repos\netpbm-wic-codec\setup\bootstrapper\bootstrapper.wixproj]
```

### Expected Result

No error during the build. 

I am seeing this WIX issue only with the 17.13 **preview** version of Visual Studio  2022 released on December 10, 2024.. Building the project with the latest official release (VS 2022 17.12.3) works fine.

Please consider this bug report "informational". The defect may also be introduced in Visual Studio itself and Microsoft could fix it before their next official release. I will update this issue after preview 3.0 becomes available.

Note: loading the netpbm-wic-codec.sln into the VS2022 17.13 preview IDE also directly shows a yellow warning bar and building with the preview IDE also fails.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barjonas** [comment]
I can confirm that I hit the same issue and was able to work around it by switching to VS 2022 17.12.3. I can add two more clues.
1. Exception during design-time build: MSB4057 The target "CollectSuggestedVisualStudioComponentIds" does not exist in the project.
2. The VS UI does not show the Wix Extensions group under "Dependencies" in the Bundle project.

**Comment by fobrs** [comment]
Same problem here

**Comment by barnson** [comment]
The command-line build requires an explicit `msbuild -Restore` or to use `dotnet build` (which does an implicit restore). We'll see if Microsoft handles the design-time target. But that will be thing for HeatWave: https://github.com/firegiant/HeatWaveSupport/issues

**Comment by YuliiaKovalova** [comment]
reported here: https://github.com/firegiant/HeatWaveSupport/issues/73
