### ISSUE TITLE
Wix3 heat version 3.11 and heat version 3.14 produces different output because of different config file

### ISSUE THREAD

**Issue by bbuerger** [wixtoolset/issues#8875]
### WiX Version

3.14

### .NET or MSBuild or Visual Studio Version

not relevant

### HeatWave Version

not relevant

### Windows Version

Win11 H2

### Repro Steps

1. Use heat.exe v3.11 with an old .net mixed framework dll => Registry Values are created
2. Use heat.exe v3.14 with an old .net mixed framework dll => Registry Values are NOT created
  (The difference is only in the heat.exe.config file)
Heat arguments:
heat dir sourceFolder -suid -ag -cg sourceFolder -o out.wxs

### Actual Result

COM Registration values are not created, but there is a warning:
heat.exe : warning HEAT5151 : Could not harvest data from a file that was expected to be an assembly: C:\sourcefolder\SngSimbaStotaxStart.dll. If this file is not an assembly you can ignore this warning. Otherwise, this error detail may be helpful to diagnose the failure: Die Assembly im gemischten Modus wurde w�hrend Version v2.0.50727 der Laufzeit erstellt und kann nicht w�hrend der 4.0-Laufzeit ohne zus�tzliche Konfigurationsinformationen geladen werden.

### Expected Result

wxs file with COM registry values
[sourcefolder.zip](https://github.com/user-attachments/files/18126267/sourcefolder.zip)

_____________________
I acknowledge, that wix v3 will be out of support soon, so feel free to close the issue.
But maybe it helps someone else, because the warning is easily missed, especially if you just except only a security update of wix, and sometimes the resulting runtime errors are hard to diagnose.

### Acknowledgements

- [X] I acknowledge that this is a fully completed bug report. It is not a question or attempt to get help debugging my issue (because those should be sent to Discussions).

**Comment by barnson** [comment]
Probably due to dropping the hard requirement for .NET Framework v3.5.1. This wouldn't qualify as a security fix, so we'll leave it here for search engines to find.
